/** Studio OS Black Box Investigation™ — public diagnostic API. Observe-only. */
export {
  initStudioOsFlightRecorder,
  shutdownStudioOsFlightRecorder,
  recordFlightEvent,
  registerFlightContext,
  getFlightEvents,
  getFlightSessionIdFromRecorder,
  buildSessionForensicReport,
  loadLastSessionReport,
  captureEnvironmentSnapshot,
  saveEnvironmentSnapshot,
  loadEnvironmentSnapshots,
  compareEnvironmentSnapshots,
  buildEventTimeline,
  formatTimelineAscii,
  formatTimelineVertical,
  getTimerInventory,
  findThreeSecondTimers,
  getSubscriptionGraph,
  detectSubscriptionLoops,
  STATE_OWNERSHIP,
  buildOwnershipReport,
  emitStudioOsRuntimeEvent,
  pauseRecording,
  resumeRecording,
  startRecording,
  clearRecording,
  getRecorderRuntimeStatus,
  getRecordingElapsedMs,
  isRecorderActive,
  isRecorderPaused,
  buildMarkdownFlightReport,
} from './init';

export { onFlightEvent } from './flight-recorder/recorder';
export { FlightRecorderConsole } from './flight-recorder-console/FlightRecorderConsole';

export type {
  FlightEventType,
  FlightRecorderEvent,
  EnvironmentSnapshot,
  TimelineAnalysis,
  SessionForensicReport,
  FailureClassification,
  TimerRecord,
  SubscriptionEdge,
  SubscriptionLoop,
  OwnershipConflict,
} from './types';
