import type { VersionedPromptEntry } from './types';

/** Versioned generation prompts — no inline prompt text in routing code. */
export const VERSIONED_GENERATION_PROMPTS: VersionedPromptEntry[] = [
  {
    promptBuilderId: 'founder-full-room-preview-prompt.v1',
    promptVersion: 'founder-full-room-preview-prompt.v1',
    artifactIntent: 'founder-full-room-preview',
    assetClass: 'founder-full-room-preview',
    description: 'Experience Lab — photoreal full-room Founder Render preview.',
    workerFamily: 'world-architect',
  },
  {
    promptBuilderId: 'master-founder-landscape-prompt.v1',
    promptVersion: 'master-founder-landscape-prompt.v1',
    artifactIntent: 'master-founder-landscape',
    assetClass: 'founder-full-room-preview',
    description: 'Master Founder Render — 21:9 canonical landscape architectural truth.',
    workerFamily: 'world-architect',
  },
  {
    promptBuilderId: 'master-founder-portrait-recompose-prompt.v1',
    promptVersion: 'master-founder-portrait-recompose-prompt.v1',
    artifactIntent: 'master-founder-portrait-recompose',
    assetClass: 'founder-full-room-preview',
    description: 'Master Portrait — 9:16 recomposition from approved landscape only.',
    workerFamily: 'world-architect',
  },
  {
    promptBuilderId: 'environment-shell-prompt.v1',
    promptVersion: 'environment-shell-prompt.v1',
    artifactIntent: 'environment-shell',
    assetClass: 'environment-shell',
    description: 'Experience Lab — environment shell img2img.',
    workerFamily: 'world-architect',
  },
  {
    promptBuilderId: 'experience-environment-prompt.v1',
    promptVersion: 'experience-environment-prompt.v1',
    artifactIntent: 'experience-environment',
    assetClass: 'environment-shell',
    description: 'Experience Lab — whole environment generation.',
    workerFamily: 'world-architect',
  },
  {
    promptBuilderId: 'world-preview-prompt.v1',
    promptVersion: 'world-preview-prompt.v1',
    artifactIntent: 'world-preview',
    assetClass: 'environment-shell',
    description: 'Experience Lab — world preview render.',
    workerFamily: 'world-architect',
  },
  {
    promptBuilderId: 'world-expansion-prompt.v1',
    promptVersion: 'world-expansion-prompt.v1',
    artifactIntent: 'world-expansion',
    assetClass: 'environment-shell',
    description: 'Experience Lab — world expansion render.',
    workerFamily: 'world-architect',
  },
  {
    promptBuilderId: 'asset-reception-desk-prompt.v1',
    promptVersion: 'asset-reception-desk-prompt.v1',
    artifactIntent: 'reception-desk',
    assetClass: 'reception-structure',
    description: 'CD Studio — reception desk isolated asset.',
    workerFamily: 'asset-manufacturer',
  },
  {
    promptBuilderId: 'asset-chair-prompt.v1',
    promptVersion: 'asset-chair-prompt.v1',
    artifactIntent: 'furniture-asset',
    assetClass: 'furniture-objects',
    description: 'CD Studio — furniture / chair isolated asset.',
    workerFamily: 'asset-manufacturer',
  },
  {
    promptBuilderId: 'furniture-objects-isolated-prompt.v3',
    promptVersion: 'furniture-objects-isolated-prompt.v3',
    artifactIntent: 'object-group',
    assetClass: 'furniture-objects',
    description: 'Scene Stack — furniture object group.',
    workerFamily: 'asset-manufacturer',
  },
  {
    promptBuilderId: 'signature-landmark-isolated-prompt.v3',
    promptVersion: 'signature-landmark-isolated-prompt.v3',
    artifactIntent: 'landmark-asset',
    assetClass: 'signature-landmark',
    description: 'CD Studio — signature landmark isolated asset.',
    workerFamily: 'asset-manufacturer',
  },
  {
    promptBuilderId: 'asset-logo-prompt.v1',
    promptVersion: 'asset-logo-prompt.v1',
    artifactIntent: 'logo-asset',
    assetClass: 'signature-landmark',
    description: 'CD Studio — logo component generation.',
    workerFamily: 'asset-manufacturer',
  },
  {
    promptBuilderId: 'asset-campaign-prompt.v1',
    promptVersion: 'asset-campaign-prompt.v1',
    artifactIntent: 'campaign-graphic',
    assetClass: 'decorative-object',
    description: 'CD Studio — campaign graphic generation.',
    workerFamily: 'asset-manufacturer',
  },
  {
    promptBuilderId: 'asset-packaging-prompt.v1',
    promptVersion: 'asset-packaging-prompt.v1',
    artifactIntent: 'packaging-asset',
    assetClass: 'decorative-object',
    description: 'CD Studio — packaging composite generation.',
    workerFamily: 'asset-manufacturer',
  },
  {
    promptBuilderId: 'asset-decor-prompt.v1',
    promptVersion: 'asset-decor-prompt.v1',
    artifactIntent: 'decor-asset',
    assetClass: 'decorative-object',
    description: 'CD Studio — decorative object generation.',
    workerFamily: 'asset-manufacturer',
  },
  {
    promptBuilderId: 'asset-architecture-piece-prompt.v1',
    promptVersion: 'asset-architecture-piece-prompt.v1',
    artifactIntent: 'architecture-piece',
    assetClass: 'architectural-prop',
    description: 'CD Studio — architectural prop (not full room).',
    workerFamily: 'asset-manufacturer',
  },
  {
    promptBuilderId: 'asset-fixture-prompt.v1',
    promptVersion: 'asset-fixture-prompt.v1',
    artifactIntent: 'fixture',
    assetClass: 'architectural-prop',
    description: 'CD Studio — fixture isolated asset.',
    workerFamily: 'asset-manufacturer',
  },
  {
    promptBuilderId: 'asset-lighting-object-prompt.v1',
    promptVersion: 'asset-lighting-object-prompt.v1',
    artifactIntent: 'lighting-object',
    assetClass: 'decorative-object',
    description: 'CD Studio — lighting object isolated asset.',
    workerFamily: 'asset-manufacturer',
  },
  {
    promptBuilderId: 'blend-overlay-prompt.v1',
    promptVersion: 'blend-overlay-prompt.v1',
    artifactIntent: null,
    assetClass: null,
    description: 'Scene Stack — overlay / blend layers.',
    workerFamily: 'any',
  },
  {
    promptBuilderId: 'background-cleanup-prompt.v1',
    promptVersion: 'background-cleanup-prompt.v1',
    artifactIntent: 'background-cleanup',
    assetClass: 'background-removal',
    description: 'Background removal / masking / transparency worker.',
    workerFamily: 'background-cleanup',
  },
];

export function getVersionedPromptByBuilderId(promptBuilderId: string): VersionedPromptEntry | null {
  return VERSIONED_GENERATION_PROMPTS.find((p) => p.promptBuilderId === promptBuilderId) ?? null;
}
