/** BCF bundles PDP — CARE/STORAGE tab (matches NOIR tab typography + markers). */

const BODY_STYLE = {
  fontFamily: '"Futura PT Book"',
  fontSize: '10px',
  color: '#000000',
  fontWeight: 400,
  margin: 0,
  lineHeight: 1.45,
  textTransform: 'uppercase' as const,
};

/** Match `/brand/terms` bullet rows (`BrandTermsBody`). */
const BULLET_STYLE = {
  ...BODY_STYLE,
  paddingLeft: '12px',
};

const BULLET_MARK_STYLE = { color: '#EB1C24' };

const SECTION_TITLE_STYLE = {
  fontFamily: '"Bohemy", cursive',
  fontSize: '20px',
  color: '#808080',
  fontWeight: 400,
  margin: '12px 0 8px 0',
  textTransform: 'lowercase' as const,
};

const HAIR_CARE_BULLETS = [
  'CLEANSE HAIR AS NEEDED USING A HIGH QUALITY, SULFATE-FREE OR MILD SHAMPOO.',
  'FOLLOW WITH A MOISTURIZING CONDITIONER, FOCUSING ON THE MID-LENGTHS AND ENDS TO MAINTAIN SOFTNESS AND MANAGEABILITY.',
  'GENTLY DETANGLE HAIR USING A PADDLE BRUSH OR WIDE TOOTH COMB, WORKING FROM THE ENDS UPWARD TO MINIMIZE BREAKAGE, SHEDDING AND MATTING.',
  'AVOID EXCESSIVE HEAT STYLING AND ALWAYS USE A HEAT PROTECTANT WHEN APPLYING HOT TOOLS.',
  'FOR CURLY OR WAVY TEXTURES, USE A SPRAY BOTTLE MIXED WITH WATER, A LIGHT SERUM AND LEAVE-IN CONDITIONER TO REFRESH, HYDRATE AND REDEFINE THE PATTERN BETWEEN WASHES.',
  'AVOID HEAVY PRODUCT BUILDUP, AS EXCESSIVE OILS AND STYLING PRODUCTS MAY WEIGH THE HAIR DOWN AND REDUCE ITS NATURAL MOVEMENT.',
  'FOR THE LONGEST LIFESPAN, WE RECOMMEND WRAPPING HAIR IN SATIN OR SILK OR USING A SATIN PILLOWCASE DURING SLEEP.',
] as const;

const STORAGE_BULLETS = [
  'STORE YOUR BUNDLES IN A COOL, DRY ENVIRONMENT AWAY FROM DIRECT SUNLIGHT, EXCESS HEAT AND HUMIDITY.',
  'CAREFULLY PLACE HAIR INSIDE THE PROVIDED SATIN-LINED DUST BAG TO MINIMIZE FRICTION, FRIZZ, TANGLING AND DEBRIS BUILDUP.',
  'ENSURE HAIR IS CLEAN AND COMPLETELY DRY BEFORE STORING TO PREVENT ODOR, MILDEW OR DAMAGE TO THE HAIR FIBERS.',
  'AVOID STORING HAIR IN TIGHTLY PACKED OR CRUSHED SPACES, AS THIS MAY ALTER THE NATURAL PATTERN OR CREATE UNNECESSARY TANGLES.',
  'FOR EXTENDED STORAGE, WE RECOMMEND KEEPING BUNDLES DETANGLED AND NEATLY ORGANIZED TO HELP PRESERVE THEIR CONDITION.',
] as const;

export default function BundleProductCareStorageTab() {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
      <p style={BODY_STYLE}>
        PROPER CARE IS ESSENTIAL TO PRESERVING THE LONGEVITY, SOFTNESS AND OVERALL PERFORMANCE OF YOUR FRONTAL SLAYER RAW HAIR BUNDLES. WITH THE RIGHT MAINTENANCE ROUTINE, YOUR EXTENSIONS CAN PROVIDE YEARS OF BEAUTIFUL WEAR, VERSATILITY AND STYLING FLEXIBILITY.
      </p>

      <p style={SECTION_TITLE_STYLE}>hair care</p>
      {HAIR_CARE_BULLETS.map((bullet) => (
        <p key={bullet} style={BULLET_STYLE}>
          <span style={BULLET_MARK_STYLE}>•</span> {bullet}
        </p>
      ))}

      <p style={SECTION_TITLE_STYLE}>storage</p>
      <p style={BODY_STYLE}>
        WHEN NOT IN USE, PROPER STORAGE HELPS MAINTAIN THE QUALITY, APPEARANCE AND LIFESPAN OF YOUR EXTENSIONS.
      </p>
      {STORAGE_BULLETS.map((bullet) => (
        <p key={bullet} style={BULLET_STYLE}>
          <span style={BULLET_MARK_STYLE}>•</span> {bullet}
        </p>
      ))}

      <p style={SECTION_TITLE_STYLE}>built to last</p>
      <p style={BODY_STYLE}>
        WITH PROPER CARE, MAINTENANCE AND STORAGE, YOUR FRONTAL SLAYER RAW HAIR EXTENSIONS ARE DESIGNED TO MAINTAIN THEIR BEAUTY, SOFTNESS AND VERSATILITY FOR YEARS TO COME… MAKING THEM AN INVESTMENT WORTH PROTECTING.
      </p>
    </div>
  );
}
