/** BCF bundles PDP — DETAILS tab (matches NOIR tab typography + markers). */

import {
  NOIR_PRODUCT_TAB_ROSE_ALERT_BADGE_STYLE,
  NOIR_PRODUCT_TAB_ROSE_ALERT_SRC,
} from './noirProductTabRoseBadge';

const BODY_STYLE = {
  fontFamily: '"Futura PT Book"',
  fontSize: '10px',
  color: '#000000',
  fontWeight: 400,
  margin: 0,
  lineHeight: 1.45,
  textTransform: 'uppercase' as const,
};

/** Match `/brand/terms` bullet rows (`BrandTermsBody`). */
const BULLET_STYLE = {
  ...BODY_STYLE,
  paddingLeft: '12px',
};

const BULLET_MARK_STYLE = { color: '#EB1C24' };

const SECTION_TITLE_STYLE = {
  fontFamily: '"Bohemy", cursive',
  fontSize: '20px',
  color: '#808080',
  fontWeight: 400,
  margin: '12px 0 8px 0',
  textTransform: 'lowercase' as const,
};

const BUNDLE_DETAILS_INTRO =
  "WHETHER YOU'RE CREATING A FLAWLESS SEW-IN, CONSTRUCTING A CUSTOM WIG OR ELEVATING YOUR CURRENT INSTALL, OUR RAW HAIR BUNDLES ARE DESIGNED TO PROVIDE UNMATCHED VERSATILITY, DURABILITY AND LONGEVITY. SOURCED FOR CLIENTS WHO EXPECT PREMIUM QUALITY WITHOUT COMPROMISE. EACH BUNDLE DELIVERS NATURAL MOVEMENT, EXCEPTIONAL FULLNESS AND THE FREEDOM TO CUSTOMIZE YOUR LOOK EXACTLY HOW YOU ENVISION IT.";

const BUNDLE_DETAILS_BULLETS = [
  'CRAFTED USING 100% RAW HUMAN HAIR SOURCED FROM SINGLE DONOR BUNDLES FOR MAXIMUM CONSISTENCY, LONGEVITY AND PERFORMANCE.',
  'UNLIKE TRADITIONAL 100 GRAM BUNDLES, EACH FRONTAL SLAYER BUNDLE CONTAINS APPROXIMATELY 150 GRAMS OF PREMIUM RAW HUMAN HAIR, DELIVERING THE EQUIVALENT OF 1.5 INDUSTRY STANDARD BUNDLES. THE RESULT IS MORE DENSITY, MORE VOLUME AND A MORE LUXURIOUS INSTALL USING FEWER BUNDLES THAN TYPICALLY REQUIRED.',
  'AVAILABLE IN A VARIETY OF PREMIUM TEXTURES TO SEAMLESSLY MATCH YOUR DESIRED LOOK AND STYLING PREFERENCES.',
  'EACH BUNDLE MAINTAINS ITS NATURAL STRENGTH, SOFTNESS AND LUSTER WHILE PROVIDING EXCEPTIONAL VERSATILITY FOR EVERYDAY WEAR.',
  'AVAILABLE LENGTHS, ORIGINS AND TEXTURES VARY BY COLLECTION. PLEASE REVIEW PRODUCT OPTIONS PRIOR TO CHECKOUT.',
  'DELIVERED IN ITS NATURAL, UNPROCESSED STATE ALLOWING COMPLETE FREEDOM TO CUT, COLOR, TONE, BLEACH, STYLE AND CUSTOMIZE TO YOUR PREFERENCE.',
  'RAW HAIR CAN BE PROFESSIONALLY LIFTED, DYED, TONED OR BLEACHED WHILE MAINTAINING ITS QUALITY WHEN PROPERLY CARED FOR.',
  'DESIGNED TO BLEND NATURALLY WITH CLOSURES, FRONTALS AND CUSTOM UNITS FOR A FLAWLESS, COHESIVE FINISH.',
  'DUE TO THE AUTHENTIC NATURE OF RAW HUMAN HAIR, SLIGHT VARIATIONS IN TEXTURE, COLOR TONE, DENSITY AND PATTERN MAY OCCUR, MAKING EACH BUNDLE UNIQUE.',
  'PROFESSIONAL INSTALLATION IS RECOMMENDED TO ACHIEVE THE BEST POSSIBLE RESULTS AND MAXIMIZE THE LONGEVITY OF YOUR INVESTMENT.',
] as const;

const BUNDLE_PREMIUM_BY_DESIGN = [
  '100% RAW HUMAN HAIR',
  '150G BUNDLES, 1.5X THE INDUSTRY STANDARD WEIGHT',
  'SINGLE DONOR SOURCING',
  'NATURAL FULLNESS & MOVEMENT',
  'CAN BE COLORED, BLEACHED & CUSTOMIZED',
  'LONG-LASTING WITH PROPER CARE',
  'AVAILABLE IN MULTIPLE TEXTURES & LENGTHS',
  'IDEAL FOR SEW-INS, QUICK WEAVES & CUSTOM WIGS',
  'DESIGNED FOR PROFESSIONAL-GRADE RESULTS',
] as const;

export default function BundleProductDetailsTab() {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
      <p style={{ ...BODY_STYLE, marginBottom: '4px' }}>{BUNDLE_DETAILS_INTRO}</p>

      {BUNDLE_DETAILS_BULLETS.map((bullet) => (
        <p key={bullet} style={BULLET_STYLE}>
          <span style={BULLET_MARK_STYLE}>•</span> {bullet}
        </p>
      ))}

      <p style={SECTION_TITLE_STYLE}>premium by design</p>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
        {BUNDLE_PREMIUM_BY_DESIGN.map((label) => (
          <div key={label} style={{ display: 'flex', alignItems: 'flex-start', gap: '8px' }}>
            <img src={NOIR_PRODUCT_TAB_ROSE_ALERT_SRC} alt="" style={NOIR_PRODUCT_TAB_ROSE_ALERT_BADGE_STYLE} />
            <p style={BODY_STYLE}>{label}</p>
          </div>
        ))}
      </div>
    </div>
  );
}
