/** BCF closures PDP — DETAILS tab (matches NOIR tab typography + markers). */

import {
  NOIR_PRODUCT_TAB_ROSE_ALERT_BADGE_STYLE,
  NOIR_PRODUCT_TAB_ROSE_ALERT_SRC,
} from './noirProductTabRoseBadge';

const BODY_STYLE = {
  fontFamily: '"Futura PT Book"',
  fontSize: '10px',
  color: '#000000',
  fontWeight: 400,
  margin: 0,
  lineHeight: 1.45,
  textTransform: 'uppercase' as const,
};

/** Match `/brand/terms` bullet rows (`BrandTermsBody`). */
const BULLET_STYLE = {
  ...BODY_STYLE,
  paddingLeft: '12px',
};

const BULLET_MARK_STYLE = { color: '#EB1C24' };

const SECTION_TITLE_STYLE = {
  fontFamily: '"Bohemy", cursive',
  fontSize: '20px',
  color: '#808080',
  fontWeight: 400,
  margin: '12px 0 8px 0',
  textTransform: 'lowercase' as const,
};

const CLOSURE_DETAILS_INTRO =
  'DESIGNED FOR CLIENTS WHO WANT A SEAMLESS AND NATURAL-LOOKING FINISH WITH MINIMAL MAINTENANCE, OUR LACE CLOSURES PROVIDE THE PERFECT BALANCE OF REALISM, VERSATILITY AND CONVENIENCE. WHETHER PAIRED WITH OUR RAW HAIR BUNDLES OR INCORPORATED INTO A CUSTOM UNIT, EACH CLOSURE IS CRAFTED TO CREATE THE APPEARANCE OF A NATURAL SCALP WHILE DELIVERING A POLISHED, PROFESSIONAL RESULT.';

const CLOSURE_DETAILS_BULLETS = [
  'CRAFTED USING PREMIUM RAW HUMAN HAIR TO COMPLEMENT YOUR SELECTED TEXTURE AND PROVIDE A SEAMLESS BLEND.',
  'DESIGNED TO CREATE A NATURAL LOOKING PART AND SCALP EFFECT FOR A REALISTIC FINISH.',
  'AVAILABLE IN MULTIPLE TEXTURES, LENGTHS AND LACE OPTIONS DEPENDING ON COLLECTION AVAILABILITY.',
  'PROVIDES VERSATILE PARTING OPTIONS WHILE MAINTAINING A NATURAL HAIRLINE APPEARANCE.',
  'DELIVERED IN ITS NATURAL STATE, ALLOWING COMPLETE FREEDOM TO PLUCK, BLEACH, COLOR, TONE, CUT OR CUSTOMIZE TO YOUR DESIRED LOOK.',
  'PAIRS SEAMLESSLY WITH OUR RAW HUMAN HAIR BUNDLES FOR A COHESIVE, NATURAL APPEARANCE.',
  'RAW HAIR CAN BE PROFESSIONALLY LIFTED, DYED, TONED OR BLEACHED WHILE MAINTAINING ITS QUALITY WHEN PROPERLY CARED FOR.',
  'DUE TO THE AUTHENTIC NATURE OF RAW HUMAN HAIR, SLIGHT VARIATIONS IN TEXTURE, COLOR TONE, DENSITY AND PATTERN MAY OCCUR, MAKING EACH PIECE UNIQUE.',
  'PROFESSIONAL CUSTOMIZATION AND INSTALLATION ARE RECOMMENDED FOR THE MOST NATURAL RESULTS.',
] as const;

const CLOSURE_ENGINEERED_FOR_EXCELLENCE = [
  'NATURAL SCALP-LIKE APPEARANCE',
  'VERSATILE PARTING OPTIONS',
  'PREMIUM RAW HUMAN HAIR',
  'SEAMLESS BUNDLE MATCHING',
  'CAN BE COLORED, BLEACHED & CUSTOMIZED',
  'BEGINNER FRIENDLY',
  'LOW MAINTENANCE WEAR',
  'PROFESSIONAL QUALITY RESULTS',
] as const;

export default function ClosureProductDetailsTab() {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
      <p style={{ ...BODY_STYLE, marginBottom: '4px' }}>{CLOSURE_DETAILS_INTRO}</p>

      {CLOSURE_DETAILS_BULLETS.map((bullet) => (
        <p key={bullet} style={BULLET_STYLE}>
          <span style={BULLET_MARK_STYLE}>•</span> {bullet}
        </p>
      ))}

      <p style={SECTION_TITLE_STYLE}>engineered for excellence</p>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
        {CLOSURE_ENGINEERED_FOR_EXCELLENCE.map((label) => (
          <div key={label} style={{ display: 'flex', alignItems: 'flex-start', gap: '8px' }}>
            <img src={NOIR_PRODUCT_TAB_ROSE_ALERT_SRC} alt="" style={NOIR_PRODUCT_TAB_ROSE_ALERT_BADGE_STYLE} />
            <p style={BODY_STYLE}>{label}</p>
          </div>
        ))}
      </div>
    </div>
  );
}
