/** BCF closures PDP — CARE/STORAGE tab (matches NOIR tab typography + markers). */

const BODY_STYLE = {
  fontFamily: '"Futura PT Book"',
  fontSize: '10px',
  color: '#000000',
  fontWeight: 400,
  margin: 0,
  lineHeight: 1.45,
  textTransform: 'uppercase' as const,
};

/** Match `/brand/terms` bullet rows (`BrandTermsBody`). */
const BULLET_STYLE = {
  ...BODY_STYLE,
  paddingLeft: '12px',
};

const BULLET_MARK_STYLE = { color: '#EB1C24' };

const SECTION_TITLE_STYLE = {
  fontFamily: '"Bohemy", cursive',
  fontSize: '20px',
  color: '#808080',
  fontWeight: 400,
  margin: '12px 0 8px 0',
  textTransform: 'lowercase' as const,
};

const HAIR_LACE_CARE_BULLETS = [
  'CLEANSE HAIR AS NEEDED USING A HIGH-QUALITY, SULFATE-FREE OR MILD SHAMPOO.',
  'WHEN CONDITIONING, AVOID APPLYING HEAVY CONDITIONER DIRECTLY TO THE LACE TO HELP PRESERVE KNOT INTEGRITY AND MINIMIZE PREMATURE SHEDDING.',
  'GENTLY DETANGLE HAIR USING A PADDLE BRUSH OR WIDE TOOTH COMB, WORKING FROM THE ENDS UPWARD TO REDUCE BREAKAGE, SHEDDING AND MATTING.',
  'AVOID EXCESSIVE HEAT STYLING AND ALWAYS USE A HEAT PROTECTANT WHEN APPLYING HOT TOOLS.',
  'FOR CURLY OR WAVY TEXTURES, USE A SPRAY BOTTLE MIXED WITH WATER, A LIGHT SERUM AND LEAVE-IN CONDITIONER TO REFRESH, HYDRATE AND REDEFINE THE PATTERN BETWEEN WASHES.',
  'HANDLE THE LACE CAREFULLY DURING WASHING, STYLING AND CUSTOMIZATION TO HELP EXTEND ITS LIFESPAN.',
] as const;

const STORAGE_BULLETS = [
  'STORE YOUR CLOSURE IN A COOL, DRY ENVIRONMENT AWAY FROM DIRECT SUNLIGHT AND EXCESS HUMIDITY.',
  'CAREFULLY PLACE YOUR CLOSURE INSIDE THE PROVIDED SATIN-LINED DUST BAG TO MINIMIZE FRICTION, FRIZZ, TANGLING AND DEBRIS BUILDUP.',
  'ENSURE THE HAIR AND LACE ARE COMPLETELY DRY BEFORE STORING TO PREVENT ODOR, MILDEW OR DAMAGE.',
  'AVOID FOLDING, CRUSHING OR STORING THE LACE UNDER PRESSURE TO HELP MAINTAIN ITS SHAPE AND APPEARANCE.',
] as const;

export default function ClosureProductCareStorageTab() {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
      <p style={BODY_STYLE}>
        PROPER CARE IS ESSENTIAL TO MAINTAINING THE APPEARANCE, LONGEVITY AND NATURAL FINISH OF YOUR FRONTAL SLAYER CLOSURE. CONSISTENT MAINTENANCE HELPS PRESERVE THE INTEGRITY OF BOTH THE HAIR AND LACE WHILE ENSURING YOUR CLOSURE CONTINUES TO BLEND SEAMLESSLY WITH YOUR INSTALL.
      </p>

      <p style={SECTION_TITLE_STYLE}>hair & lace care</p>
      {HAIR_LACE_CARE_BULLETS.map((bullet) => (
        <p key={bullet} style={BULLET_STYLE}>
          <span style={BULLET_MARK_STYLE}>•</span> {bullet}
        </p>
      ))}

      <p style={SECTION_TITLE_STYLE}>storage</p>
      <p style={BODY_STYLE}>
        WHEN NOT IN USE, PROPER STORAGE HELPS PRESERVE BOTH THE HAIR FIBERS AND LACE MATERIAL.
      </p>
      {STORAGE_BULLETS.map((bullet) => (
        <p key={bullet} style={BULLET_STYLE}>
          <span style={BULLET_MARK_STYLE}>•</span> {bullet}
        </p>
      ))}

      <p style={SECTION_TITLE_STYLE}>protect your investment</p>
      <p style={BODY_STYLE}>
        WITH PROPER CARE AND MAINTENANCE, YOUR FRONTAL SLAYER CLOSURE CAN PROVIDE LONG LASTING PERFORMANCE, SEAMLESS BLENDING AND BEAUTIFUL WEAR THROUGH MULTIPLE INSTALLATIONS.
      </p>
    </div>
  );
}
