/** BCF frontals PDP — CARE/STORAGE tab (matches NOIR tab typography + markers). */

const BODY_STYLE = {
  fontFamily: '"Futura PT Book"',
  fontSize: '10px',
  color: '#000000',
  fontWeight: 400,
  margin: 0,
  lineHeight: 1.45,
  textTransform: 'uppercase' as const,
};

/** Match `/brand/terms` bullet rows (`BrandTermsBody`). */
const BULLET_STYLE = {
  ...BODY_STYLE,
  paddingLeft: '12px',
};

const BULLET_MARK_STYLE = { color: '#EB1C24' };

const SECTION_TITLE_STYLE = {
  fontFamily: '"Bohemy", cursive',
  fontSize: '20px',
  color: '#808080',
  fontWeight: 400,
  margin: '12px 0 8px 0',
  textTransform: 'lowercase' as const,
};

const HAIR_LACE_CARE_BULLETS = [
  'CLEANSE HAIR AS NEEDED USING A HIGH QUALITY, SULFATE-FREE OR MILD SHAMPOO.',
  'WHEN CONDITIONING, AVOID APPLYING HEAVY CONDITIONER DIRECTLY TO THE LACE TO HELP PRESERVE KNOT INTEGRITY AND REDUCE PREMATURE SHEDDING.',
  'GENTLY DETANGLE HAIR USING A PADDLE BRUSH OR WIDE TOOTH COMB, WORKING FROM THE ENDS UPWARD TO MINIMIZE BREAKAGE, MATTING AND SHEDDING.',
  'AVOID EXCESSIVE HEAT STYLING AND ALWAYS USE A HEAT PROTECTANT WHEN APPLYING HOT TOOLS.',
  'FOR CURLY OR WAVY TEXTURES, USE A SPRAY BOTTLE MIXED WITH WATER, A LIGHT SERUM AND LEAVE-IN CONDITIONER TO REFRESH, HYDRATE AND REDEFINE THE PATTERN BETWEEN WASHES.',
  'HANDLE THE HAIRLINE AND LACE WITH CARE DURING CUSTOMIZATION, INSTALLATION AND REMOVAL TO HELP MAINTAIN A NATURAL LOOKING FINISH.',
] as const;

const STORAGE_BULLETS = [
  'STORE YOUR FRONTAL IN A COOL, DRY ENVIRONMENT AWAY FROM DIRECT SUNLIGHT AND EXCESS HUMIDITY.',
  'CAREFULLY PLACE YOUR FRONTAL INSIDE THE PROVIDED SATIN-LINED DUST BAG TO MINIMIZE FRICTION, FRIZZ, TANGLING AND DEBRIS BUILDUP.',
  'ENSURE THE HAIR AND LACE ARE COMPLETELY DRY BEFORE STORING TO PREVENT ODOR, MILDEW OR DAMAGE.',
  'AVOID FOLDING, BENDING OR COMPRESSING THE LACE TO HELP PRESERVE ITS SHAPE AND STRUCTURAL INTEGRITY.',
] as const;

export default function FrontalProductCareStorageTab() {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
      <p style={BODY_STYLE}>
        YOUR FRONTAL IS ONE OF THE MOST IMPORTANT COMPONENTS OF A FLAWLESS INSTALL. PROPER CARE HELPS MAINTAIN THE APPEARANCE OF THE HAIRLINE, PRESERVE LACE INTEGRITY AND EXTEND THE LIFESPAN OF BOTH THE HAIR AND CUSTOMIZATION.
      </p>

      <p style={SECTION_TITLE_STYLE}>hair & lace care</p>
      {HAIR_LACE_CARE_BULLETS.map((bullet) => (
        <p key={bullet} style={BULLET_STYLE}>
          <span style={BULLET_MARK_STYLE}>•</span> {bullet}
        </p>
      ))}

      <p style={SECTION_TITLE_STYLE}>storage</p>
      <p style={BODY_STYLE}>
        WHEN NOT IN USE, PROPER STORAGE HELPS MAINTAIN THE SHAPE, APPEARANCE AND LONGEVITY OF YOUR FRONTAL.
      </p>
      {STORAGE_BULLETS.map((bullet) => (
        <p key={bullet} style={BULLET_STYLE}>
          <span style={BULLET_MARK_STYLE}>•</span> {bullet}
        </p>
      ))}

      <p style={SECTION_TITLE_STYLE}>preserve the melt</p>
      <p style={BODY_STYLE}>
        WITH PROPER CARE, MAINTENANCE AND STORAGE, YOUR FRONTAL SLAYER FRONTAL CAN MAINTAIN ITS NATURAL APPEARANCE, STYLING VERSATILITY AND FLAWLESS MELT THROUGH MULTIPLE INSTALLS AND CUSTOMIZATIONS.
      </p>
    </div>
  );
}
