/** BCF frontals PDP — SHIPPING tab (matches NOIR tab typography + markers). */

import {
  NOIR_PRODUCT_TAB_ROSE_ALERT_BADGE_STYLE,
  NOIR_PRODUCT_TAB_ROSE_ALERT_SRC,
} from './noirProductTabRoseBadge';

const BODY_STYLE = {
  fontFamily: '"Futura PT Book"',
  fontSize: '10px',
  color: '#000000',
  fontWeight: 400,
  margin: 0,
  lineHeight: 1.45,
  textTransform: 'uppercase' as const,
};

/** Match `/brand/terms` bullet rows (`BrandTermsBody`). */
const BULLET_STYLE = {
  ...BODY_STYLE,
  paddingLeft: '12px',
};

const BULLET_MARK_STYLE = { color: '#EB1C24' };

const SECTION_TITLE_STYLE = {
  fontFamily: '"Bohemy", cursive',
  fontSize: '20px',
  color: '#808080',
  fontWeight: 400,
  margin: '12px 0 8px 0',
  textTransform: 'lowercase' as const,
};

const CUSTOMIZATION_EXCLUSION_BULLETS = [
  'CUSTOM HAIR COLORING',
  'SPECIALTY COLOR SERVICES',
  'KNOT BLEACHING & TONING',
  'CUSTOM PLUCKING',
  'HAIRLINE CUSTOMIZATION',
  'CUSTOM STYLING',
  'ADDITIONAL ADD-ON SERVICES',
] as const;

const IMPORTANT_TO_NOTE_ITEMS = [
  'PROCESSING TIME BEGINS AFTER SUCCESSFUL PAYMENT VERIFICATION.',
  'PROCESSING TIMES DO NOT INCLUDE SHIPPING TRANSIT TIMES.',
  'BUSINESS DAYS EXCLUDE WEEKENDS AND MAJOR U.S. HOLIDAYS.',
  'PROCESSING ESTIMATES MAY VARY DURING SALES, PROMOTIONAL EVENTS, PRODUCT LAUNCHES AND HIGH VOLUME PERIODS.',
  'TRACKING INFORMATION WILL BE PROVIDED VIA EMAIL ONCE YOUR ORDER HAS SHIPPED.',
  'SELECTING EXPEDITED SHIPPING ALONE DOES NOT REDUCE CUSTOMIZATION TIMELINES UNLESS EXPRESS PROCESSING HAS ALSO BEEN PURCHASED.',
] as const;

export default function FrontalProductShippingTab() {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
      <p style={BODY_STYLE}>
        EVERY FRONTAL SLAYER FRONTAL IS CAREFULLY SOURCED, INSPECTED AND PREPARED BEFORE SHIPMENT TO ENSURE IT MEETS OUR STANDARDS FOR QUALITY, VERSATILITY AND REALISM. BECAUSE FRONTALS OFTEN REQUIRE ADDITIONAL ATTENTION AND CUSTOMIZATION, WE ENCOURAGE CLIENTS TO REVIEW ALL PROCESSING TIMELINES BEFORE PLACING AN ORDER.
      </p>

      <p style={SECTION_TITLE_STYLE}>standard processing</p>
      <p style={BODY_STYLE}>
        STANDARD PROCESSING FOR FRONTAL ORDERS IS APPROXIMATELY 4-6 WEEKS. ORDERS THAT INCLUDE CUSTOM COLORING, KNOT BLEACHING, PLUCKING, STYLING OR ADDITIONAL CUSTOMIZATION SERVICES MAY REQUIRE 6-8 WEEKS OR LONGER DEPENDING ON THE COMPLEXITY OF THE REQUESTED SERVICES.
      </p>

      <p style={SECTION_TITLE_STYLE}>express processing</p>
      <p style={BODY_STYLE}>
        NEED YOUR FRONTAL TO ARRIVE SOONER? WE OFFER EXPRESS PROCESSING + RUSH SHIPPING FOR AN ADDITIONAL $120 USD. ELIGIBLE ORDERS ARE PRIORITIZED WITHIN OUR PRODUCTION QUEUE AND PROCESSED WITHIN APPROXIMATELY 3-4 WEEKS.
      </p>
      <p style={BODY_STYLE}>
        PLEASE NOTE THAT EXPRESS PROCESSING IS AVAILABLE ONLY ON QUALIFYING ORDERS.
      </p>

      <p style={SECTION_TITLE_STYLE}>customization exclusions</p>
      <p style={BODY_STYLE}>
        TO MAINTAIN THE QUALITY AND INTEGRITY OF OUR WORK, THE FOLLOWING SERVICES ARE NOT ELIGIBLE FOR EXPRESS PROCESSING:
      </p>
      {CUSTOMIZATION_EXCLUSION_BULLETS.map((bullet) => (
        <p key={bullet} style={BULLET_STYLE}>
          <span style={BULLET_MARK_STYLE}>•</span> {bullet}
        </p>
      ))}
      <p style={BODY_STYLE}>
        ORDERS CONTAINING THESE SERVICES WILL FOLLOW STANDARD PRODUCTION TIMELINES REGARDLESS OF THE SHIPPING METHOD SELECTED.
      </p>

      <p style={SECTION_TITLE_STYLE}>important to note</p>
      <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
        {IMPORTANT_TO_NOTE_ITEMS.map((label) => (
          <div key={label} style={{ display: 'flex', alignItems: 'flex-start', gap: '8px' }}>
            <img src={NOIR_PRODUCT_TAB_ROSE_ALERT_SRC} alt="" style={NOIR_PRODUCT_TAB_ROSE_ALERT_BADGE_STYLE} />
            <p style={BODY_STYLE}>{label}</p>
          </div>
        ))}
      </div>

      <p style={SECTION_TITLE_STYLE}>built for a flawless melt</p>
      <p style={BODY_STYLE}>
        EVERY FRONTAL IS CAREFULLY PREPARED TO DELIVER THE MOST NATURAL LOOKING RESULTS POSSIBLE. WE PRIORITIZE QUALITY, PRECISION AND ATTENTION TO DETAIL OVER RUSHED FULFILLMENT SO YOUR FRONTAL ARRIVES READY FOR CUSTOMIZATION, INSTALLATION AND MAXIMUM STYLING VERSATILITY.
      </p>
    </div>
  );
}
