/** Gift card PDP — POLICY tab (matches NOIR / BCF tab typography + markers). */

const BODY_STYLE = {
  fontFamily: '"Futura PT Book"',
  fontSize: '10px',
  color: '#000000',
  fontWeight: 400,
  margin: 0,
  lineHeight: 1.45,
  textTransform: 'uppercase' as const,
};

/** Match `/brand/terms` bullet rows (`BrandTermsBody`). */
const BULLET_STYLE = {
  ...BODY_STYLE,
  paddingLeft: '12px',
};

const BULLET_MARK_STYLE = { color: '#EB1C24' };

const EMAIL_STYLE = {
  ...BODY_STYLE,
  color: '#EB1C24',
  fontFamily: '"Futura PT Medium"',
  fontWeight: 500,
};

const GIFT_CARD_POLICY_BULLETS = [
  'GIFT CARDS DO NOT EXPIRE AND MAY BE REDEEMED AT ANY TIME.',
  'GIFT CARDS MAY BE USED TOWARD ELIGIBLE PRODUCTS, SERVICES, CUSTOMIZATIONS, MEMBERSHIPS AND PURCHASES AVAILABLE THROUGH THE FRONTAL SLAYER WEBSITE.',
  'GIFT CARDS MAY BE COMBINED WITH ELIGIBLE PROMOTIONAL OFFERS, DISCOUNTS OR REWARDS PROGRAM BENEFITS UNLESS OTHERWISE STATED.',
  'GIFT CARDS ARE NON-REFUNDABLE, NON-TRANSFERABLE AND MAY NOT BE REDEEMED FOR CASH, EXCEPT WHERE REQUIRED BY LAW.',
  'LOST, STOLEN, DELETED OR INCORRECTLY DELIVERED GIFT CARDS MAY NOT BE REPLACED WITHOUT SUFFICIENT PROOF OF PURCHASE.',
  'GIFT CARD PURCHASES CANNOT BE RETURNED, EXCHANGED OR CANCELED ONCE DELIVERY HAS BEEN COMPLETED.',
  'FRONTAL SLAYER RESERVES THE RIGHT TO REFUSE, VOID OR CANCEL GIFT CARDS OBTAINED THROUGH FRAUDULENT, UNAUTHORIZED OR SUSPICIOUS ACTIVITY.',
  'ALL GIFT CARD PURCHASES AND REDEMPTIONS ARE SUBJECT TO OUR GENERAL TERMS OF SERVICE AND WEBSITE POLICIES.',
] as const;

export default function GiftCardProductPolicyTab() {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
      <p style={BODY_STYLE}>
        THE FRONTAL SLAYER GIFT CARD IS DESIGNED TO PROVIDE MAXIMUM FLEXIBILITY WHILE MAKING GIFTING SIMPLE AND CONVENIENT.
      </p>

      {GIFT_CARD_POLICY_BULLETS.map((bullet) => (
        <p key={bullet} style={BULLET_STYLE}>
          <span style={BULLET_MARK_STYLE}>•</span> {bullet}
        </p>
      ))}

      <p style={BODY_STYLE}>
        IF YOU EXPERIENCE AN ISSUE WITH YOUR GIFT CARD, PLEASE EMAIL{' '}
        <span style={EMAIL_STYLE}>CONTACT@FRONTALSLAYER.COM</span>
      </p>
      <p style={BODY_STYLE}>
        OUR TEAM WILL BE HAPPY TO ASSIST YOU WITH VERIFICATION, BALANCE INQUIRIES, REDEMPTION ISSUES OR DELIVERY CONCERNS.
      </p>
    </div>
  );
}
