/** NOIR unit PDP — DETAILS tab copy and list styling. */

const BODY_STYLE = {
  fontFamily: '"Futura PT Book"',
  fontSize: '10px',
  color: '#000000',
  fontWeight: 400,
  margin: 0,
  lineHeight: 1.45,
  textTransform: 'uppercase' as const,
};

/** Match `/brand/terms` bullet rows (`BrandTermsBody`). */
const BULLET_STYLE = {
  ...BODY_STYLE,
  paddingLeft: '12px',
};

const BULLET_MARK_STYLE = { color: '#EB1C24' };

const SECTION_TITLE_STYLE = {
  fontFamily: '"Bohemy", cursive',
  fontSize: '10px',
  color: '#EB1C24',
  fontWeight: 400,
  margin: '14px 0 10px 0',
  textTransform: 'lowercase' as const,
};

const NOIR_DETAILS_INTRO =
  'DESIGNED FOR THE CLIENT WHO REFUSES TO COMPROMISE ON QUALITY, THIS LUXURY HANDCRAFTED UNIT COMBINES PREMIUM RAW HAIR, ADVANCED LACE TECHNOLOGY AND EXCEPTIONAL CRAFTSMANSHIP TO DELIVER A TRULY ELEVATED WEARING EXPERIENCE. WHETHER YOU PREFER A SLEEK EVERYDAY LOOK OR A FULLY CUSTOMIZED TRANSFORMATION, THIS UNIT WAS CREATED TO PROVIDE MAXIMUM VERSATILITY, LONGEVITY WITH THE MOST NATURAL LOOKING RESULTS. EVERY DETAIL HAS BEEN CAREFULLY SELECTED TO ENSURE A FLAWLESS FINISH THAT LOOKS EXPENSIVE, FEELS COMFORTABLE AND STANDS THE TEST OF TIME.';

const NOIR_DETAILS_BULLETS = [
  'CRAFTED USING 100% RAW CAMBODIAN STRAIGHT HUMAN HAIR SOURCED FROM SINGLE DONOR BUNDLES FOR SUPERIOR LONGEVITY, CONSISTENCY AND VERSATILITY.',
  'FEATURES A 13X6 ULTRA THIN HD FILM LACE FS DESIGNED TO MELT SEAMLESSLY INTO THE SKIN FOR AN UNDETECTABLE, SCALP-LIKE APPEARANCE.',
  'HANDMADE UNIT MEASURING 24 INCHES IN LENGTH WITH AN OFF BLACK NATURAL HAIR COLOR AND 250% DENSITY FOR MAXIMUM FULLNESS, VOLUME AND STYLING FLEXIBILITY.',
  'CONSTRUCTED ON A STRETCHABLE, BREATHABLE WIG CAP EQUIPPED WITH REMOVABLE COMBS AND AN ADJUSTABLE ELASTIC BAND FOR A SECURE, COMFORTABLE FIT.',
  'HAIRLINE FEATURES LIGHTLY BLEACHED, SINGLE STRAND KNOTS TO CREATE THE MOST NATURAL LOOKING MELT AND REDUCE THE APPEARANCE OF VISIBLE KNOTTING FOR A READY TO WEAR APPLICATION.',
  'DELIVERED IN ITS NATURAL, UNCUSTOMIZED STATE ALLOWING COMPLETE FREEDOM TO CUT, LAYER, STYLE AND PERSONALIZE THE UNIT TO YOUR DESIRED LOOK.',
  'RAW HAIR CAN BE PROFESSIONALLY LIFTED, COLORED, TONED, DYED AND BLEACHED WHILE MAINTAINING ITS QUALITY WHEN PROPERLY CARED FOR.',
  'MEMBERS GAIN EXCLUSIVE ACCESS TO OUR 3D BUILD-A-WIG GENERATOR ALLOWING YOU TO PREVIEW AND CUSTOMIZE YOUR UNIT WITH COLOR SERVICES, STYLING OPTIONS, LACE CUSTOMIZATION, DENSITY ENHANCEMENTS AND ADDITIONAL UPGRADES BEFORE PURCHASING.',
  'DESIGNED FOR VERSATILITY, DURABILITY AND LONG-TERM WEAR WITH PROPER MAINTENANCE AND CARE.',
  'DUE TO THE NATURAL NATURE OF RAW HUMAN HAIR, SLIGHT VARIATIONS IN TEXTURE, COLOR TONE, DENSITY AND PATTERN MAY OCCUR MAKING EACH UNIT UNIQUELY YOURS.',
  'FOR THE PROTECTION OF BOTH OUR CLIENTS AND BRAND, IDENTITY VERIFICATION AND COMPLETION OF THE ORDER AUTHORIZATION FORM ARE REQUIRED BEFORE ALL WIG ORDERS CAN BE PROCESSED, CUSTOMIZED OR SHIPPED.',
] as const;

const NOIR_WHY_YOULL_LOVE_IT = [
  'ULTRA THIN HD FILM LACE FOR AN INVISIBLE MELT',
  '250% DENSITY FOR FULLNESS AND VOLUME',
  'SINGLE DONOR RAW CAMBODIAN HUMAN HAIR',
  'LIGHTLY BLEACHED SINGLE STRAND KNOTS',
  'BEGINNER & STYLIST FRIENDLY',
  'CAN BE COLORED, BLEACHED & CUSTOMIZED',
  'BUILT TO LAST WITH PROPER CARE',
  'COMPATIBLE WITH BUILD-A-WIG CUSTOMIZATION SERVICES',
] as const;

/** Red checkmarks match premium upgrade subscription chart (`PremiumSubscriptionUpgradeChart`). */
const PREMIUM_CHECK_STYLE = { width: '10px', height: '10px', flexShrink: 0 } as const;

export default function NoirProductDetailsTab() {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
      <p style={{ ...BODY_STYLE, marginBottom: '4px' }}>{NOIR_DETAILS_INTRO}</p>

      {NOIR_DETAILS_BULLETS.map((bullet) => (
        <p key={bullet} style={BULLET_STYLE}>
          <span style={BULLET_MARK_STYLE}>•</span> {bullet}
        </p>
      ))}

      <p style={SECTION_TITLE_STYLE}>why you&apos;ll love it</p>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
        {NOIR_WHY_YOULL_LOVE_IT.map((label) => (
          <div key={label} style={{ display: 'flex', alignItems: 'flex-start', gap: '8px' }}>
            <img src="/assets/premium-check.svg" alt="Included" style={PREMIUM_CHECK_STYLE} />
            <p style={BODY_STYLE}>{label}</p>
          </div>
        ))}
      </div>
    </div>
  );
}
