import type { UIElementPresence } from './types';

/**
 * Studio World UI element registry — every surface declares Presence Level™ metadata.
 * Individual components consult the engine; they do not self-decide visibility.
 */
export const STUDIO_WORLD_UI_REGISTRY: UIElementPresence[] = [
  // ── Level 0 — Architecture only ──
  {
    id: 'scene-stack-viewport',
    label: 'Scene Stack™ compositor',
    presenceLevel: 0,
    priority: 0,
    requiredIntent: 'ambient',
    visualWeight: 'none',
    animationWeight: 'subtle',
    dismissBehavior: 'persistent',
    medium: 'architecture',
    countsTowardAmbientCap: false,
  },
  {
    id: 'atlas-holographic-table',
    label: 'Studio World holographic projection',
    presenceLevel: 0,
    priority: 0,
    requiredIntent: 'ambient',
    visualWeight: 'none',
    animationWeight: 'normal',
    dismissBehavior: 'persistent',
    medium: 'architecture',
    countsTowardAmbientCap: false,
  },

  // ── Level 1 — Ambient (max 3 informational elements) ──
  {
    id: 'nav-rail-atlas',
    label: 'Atlas™',
    presenceLevel: 1,
    priority: 0,
    requiredIntent: 'ambient',
    visualWeight: 'subtle',
    animationWeight: 'none',
    dismissBehavior: 'persistent',
    medium: 'rail',
    countsTowardAmbientCap: false,
  },
  {
    id: 'nav-rail-location',
    label: 'Current district / room',
    presenceLevel: 1,
    priority: 1,
    requiredIntent: 'ambient',
    visualWeight: 'subtle',
    animationWeight: 'none',
    dismissBehavior: 'persistent',
    medium: 'rail',
    countsTowardAmbientCap: true,
  },
  {
    id: 'nav-rail-destinations',
    label: 'Architectural destinations',
    presenceLevel: 1,
    priority: 2,
    requiredIntent: 'ambient',
    visualWeight: 'normal',
    animationWeight: 'none',
    dismissBehavior: 'persistent',
    medium: 'rail',
    countsTowardAmbientCap: false,
  },
  {
    id: 'scene-tray',
    label: 'Scene Tray™',
    presenceLevel: 1,
    priority: 3,
    requiredIntent: 'ambient',
    visualWeight: 'normal',
    animationWeight: 'none',
    dismissBehavior: 'persistent',
    medium: 'tray',
    countsTowardAmbientCap: false,
  },
  {
    id: 'world-health-ambient',
    label: 'World Health™ indicator',
    presenceLevel: 1,
    priority: 4,
    requiredIntent: 'ambient',
    visualWeight: 'subtle',
    animationWeight: 'subtle',
    dismissBehavior: 'manual-collapse',
    medium: 'plaque',
    countsTowardAmbientCap: true,
  },
  {
    id: 'orb-courier-message',
    label: 'Studio Orb™ insight',
    presenceLevel: 1,
    priority: 5,
    requiredIntent: 'ambient',
    visualWeight: 'subtle',
    animationWeight: 'subtle',
    dismissBehavior: 'auto-collapse',
    medium: 'orb',
    countsTowardAmbientCap: true,
  },
  {
    id: 'room-teaching-line',
    label: 'Teaching line',
    presenceLevel: 1,
    priority: 6,
    requiredIntent: 'ambient',
    visualWeight: 'subtle',
    animationWeight: 'none',
    dismissBehavior: 'persistent',
    medium: 'engraving',
    countsTowardAmbientCap: true,
  },
  {
    id: 'atlas-district-labels',
    label: 'Orbital district labels',
    presenceLevel: 1,
    priority: 7,
    requiredIntent: 'tap',
    visualWeight: 'subtle',
    animationWeight: 'subtle',
    dismissBehavior: 'manual-collapse',
    medium: 'projection',
    countsTowardAmbientCap: true,
  },
  {
    id: 'atlas-travel-controls',
    label: 'Travel mode holographic controls',
    presenceLevel: 1,
    priority: 8,
    requiredIntent: 'tap',
    visualWeight: 'subtle',
    animationWeight: 'none',
    dismissBehavior: 'manual-collapse',
    medium: 'projection',
    countsTowardAmbientCap: false,
  },
  {
    id: 'atlas-breadcrumb-trail',
    label: 'Spatial breadcrumb trail',
    presenceLevel: 1,
    priority: 9,
    requiredIntent: 'tap',
    visualWeight: 'subtle',
    animationWeight: 'none',
    dismissBehavior: 'manual-collapse',
    medium: 'projection',
    countsTowardAmbientCap: false,
  },
  {
    id: 'atlas-orb-projections',
    label: 'Orb floating recommendations',
    presenceLevel: 1,
    priority: 10,
    requiredIntent: 'tap',
    visualWeight: 'subtle',
    animationWeight: 'subtle',
    dismissBehavior: 'auto-collapse',
    medium: 'orb',
    countsTowardAmbientCap: true,
  },

  // ── Level 2 — Context (after intentional interaction) ──
  {
    id: 'world-health-expanded',
    label: 'World Health™ detail',
    presenceLevel: 2,
    priority: 0,
    requiredIntent: 'tap',
    visualWeight: 'normal',
    animationWeight: 'subtle',
    dismissBehavior: 'manual-collapse',
    medium: 'hologram',
    countsTowardAmbientCap: false,
  },
  {
    id: 'civilization-ambient-pulse',
    label: 'Civilization pulse',
    presenceLevel: 2,
    priority: 1,
    requiredIntent: 'tap',
    visualWeight: 'subtle',
    animationWeight: 'subtle',
    dismissBehavior: 'manual-collapse',
    medium: 'projection',
    countsTowardAmbientCap: false,
  },
  {
    id: 'ecology-synergy-flows',
    label: 'Ecology synergy flows',
    presenceLevel: 2,
    priority: 2,
    requiredIntent: 'tap',
    visualWeight: 'subtle',
    animationWeight: 'none',
    dismissBehavior: 'manual-collapse',
    medium: 'projection',
    countsTowardAmbientCap: false,
  },
  {
    id: 'nav-rail-room-detail',
    label: 'Room / scene location detail',
    presenceLevel: 2,
    priority: 3,
    requiredIntent: 'tap',
    visualWeight: 'subtle',
    animationWeight: 'none',
    dismissBehavior: 'manual-collapse',
    medium: 'rail',
    countsTowardAmbientCap: false,
  },
  {
    id: 'atlas-focus-annotation',
    label: 'Architectural callout for selected destination',
    presenceLevel: 2,
    priority: 4,
    requiredIntent: 'tap',
    visualWeight: 'normal',
    animationWeight: 'subtle',
    dismissBehavior: 'manual-collapse',
    medium: 'hologram',
    countsTowardAmbientCap: false,
  },
  {
    id: 'atlas-world-ticker',
    label: 'Civilization activity ribbon',
    presenceLevel: 2,
    priority: 5,
    requiredIntent: 'tap',
    visualWeight: 'subtle',
    animationWeight: 'subtle',
    dismissBehavior: 'manual-collapse',
    medium: 'projection',
    countsTowardAmbientCap: false,
  },
  {
    id: 'atlas-travel-journey',
    label: 'Animated travel journey overlay',
    presenceLevel: 2,
    priority: 6,
    requiredIntent: 'tap',
    visualWeight: 'emphasis',
    animationWeight: 'normal',
    dismissBehavior: 'auto-collapse',
    medium: 'projection',
    countsTowardAmbientCap: false,
  },

  // ── Level 3 — Professional (deliberate exploration) ──
  {
    id: 'frame-status-strip',
    label: 'Frame status metrics',
    presenceLevel: 3,
    priority: 0,
    requiredIntent: 'explore',
    visualWeight: 'normal',
    animationWeight: 'none',
    dismissBehavior: 'manual-collapse',
    medium: 'hud',
    countsTowardAmbientCap: false,
  },
  {
    id: 'nav-rail-frame-status',
    label: 'Rail frame status block',
    presenceLevel: 3,
    priority: 1,
    requiredIntent: 'explore',
    visualWeight: 'normal',
    animationWeight: 'none',
    dismissBehavior: 'manual-collapse',
    medium: 'rail',
    countsTowardAmbientCap: false,
  },
  {
    id: 'living-architecture-monument',
    label: 'Architectural milestone monument',
    presenceLevel: 3,
    priority: 2,
    requiredIntent: 'explore',
    visualWeight: 'emphasis',
    animationWeight: 'subtle',
    dismissBehavior: 'manual-collapse',
    medium: 'plaque',
    countsTowardAmbientCap: false,
  },
  {
    id: 'civilization-economies',
    label: 'Civilization economies',
    presenceLevel: 3,
    priority: 3,
    requiredIntent: 'explore',
    visualWeight: 'normal',
    animationWeight: 'none',
    dismissBehavior: 'manual-collapse',
    medium: 'overlay',
    countsTowardAmbientCap: false,
  },
  {
    id: 'ecology-chain-reaction',
    label: 'Chain reaction detail',
    presenceLevel: 3,
    priority: 4,
    requiredIntent: 'explore',
    visualWeight: 'normal',
    animationWeight: 'subtle',
    dismissBehavior: 'manual-collapse',
    medium: 'overlay',
    countsTowardAmbientCap: false,
  },
  {
    id: 'atlas-engine-strip',
    label: 'Active civilization engines',
    presenceLevel: 3,
    priority: 5,
    requiredIntent: 'explore',
    visualWeight: 'subtle',
    animationWeight: 'none',
    dismissBehavior: 'manual-collapse',
    medium: 'projection',
    countsTowardAmbientCap: false,
  },
  {
    id: 'atlas-mode-controls',
    label: 'Map mode holographic selector',
    presenceLevel: 3,
    priority: 6,
    requiredIntent: 'explore',
    visualWeight: 'subtle',
    animationWeight: 'none',
    dismissBehavior: 'manual-collapse',
    medium: 'projection',
    countsTowardAmbientCap: false,
  },
  {
    id: 'atlas-planner-surfaces',
    label: 'Master Planner / Parallel Futures surfaces',
    presenceLevel: 3,
    priority: 7,
    requiredIntent: 'explore',
    visualWeight: 'normal',
    animationWeight: 'subtle',
    dismissBehavior: 'manual-collapse',
    medium: 'hologram',
    countsTowardAmbientCap: false,
  },
  {
    id: 'atlas-fog-legend',
    label: 'Discovery fog legend',
    presenceLevel: 3,
    priority: 8,
    requiredIntent: 'explore',
    visualWeight: 'subtle',
    animationWeight: 'none',
    dismissBehavior: 'manual-collapse',
    medium: 'projection',
    countsTowardAmbientCap: false,
  },

  // ── Level 4 — Architect (advanced / debug) ──
  {
    id: 'nav-rail-campus-destinations',
    label: 'Global campus destination list',
    presenceLevel: 4,
    priority: 0,
    requiredIntent: 'architect',
    visualWeight: 'normal',
    animationWeight: 'none',
    dismissBehavior: 'session',
    medium: 'rail',
    countsTowardAmbientCap: false,
  },
  {
    id: 'nav-rail-wing-tier-badges',
    label: 'Wing tier / ecology badges',
    presenceLevel: 4,
    priority: 1,
    requiredIntent: 'architect',
    visualWeight: 'subtle',
    animationWeight: 'none',
    dismissBehavior: 'session',
    medium: 'rail',
    countsTowardAmbientCap: false,
  },
  {
    id: 'world-graph-debug',
    label: 'World Graph debug',
    presenceLevel: 4,
    priority: 2,
    requiredIntent: 'architect',
    visualWeight: 'normal',
    animationWeight: 'none',
    dismissBehavior: 'session',
    medium: 'overlay',
    countsTowardAmbientCap: false,
  },
];

export function getUIElementPresence(elementId: string): UIElementPresence | null {
  return STUDIO_WORLD_UI_REGISTRY.find((e) => e.id === elementId) ?? null;
}
