/**
 * NDXBOOK Newsroom V1.0 bootstrap — production floor seed (Milestone 40).
 */

import { bootstrapNdxbookNewsroomStore } from './store';
import type { NewsroomStore, ProductionPage } from './types';

function hoursAgo(h: number): string {
  return new Date(Date.now() - h * 3600_000).toISOString();
}

function todayAt(hour: number, minute: number): string {
  const d = new Date();
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
}

function page(partial: ProductionPage): ProductionPage {
  return partial;
}

export function buildNdxbookNewsroomSeed(): Partial<NewsroomStore> {
  const pages: ProductionPage[] = [
    page({
      id: 'pg-042',
      pageNumber: 42,
      pageLabel: 'page 042',
      title: 'Why compound interest beats timing the market',
      volumeId: 'money',
      chapter: 'investing',
      stageId: 'idea',
      assignedExecutive: 'Chief Content Officer',
      priority: 'normal',
      confidencePct: 72,
      health: 'on-track',
      estimatedCompletionMins: 480,
      updatedAt: hoursAgo(1),
      researchNotes: ['Market timing studies 2010-2024', 'ndxbook money volume tone guide'],
      knowledgeSources: ['Federal Reserve FAQ', 'Labs #38 stat overlay data'],
      scriptExcerpt: '',
      storyboardStatus: 'not started',
      voiceStatus: 'pending host',
      animationStatus: 'pending',
      thumbnailStatus: 'pending',
      captionStatus: 'pending',
      hashtags: ['#money', '#investing', '#ndxbook'],
      platformVersions: ['tiktok', 'instagram', 'youtube-shorts'],
      approvalHistory: [],
      experiments: [],
      analyticsSnapshot: '—',
      comments: ['CoS: schedule after page 028 publishes'],
      revisionHistory: ['Created from Studio Intelligence opportunity signal'],
      knowledgeGraphNodeIds: ['node-ndxbook'],
      memoryReferences: ['Money volume template v3'],
      institutionalLearnings: [],
    }),
    page({
      id: 'pg-041',
      pageNumber: 41,
      pageLabel: 'page 041',
      title: 'Sleep debt recovery protocol',
      volumeId: 'body',
      chapter: 'sleep',
      stageId: 'research',
      assignedExecutive: 'Research AI',
      assignedHost: 'Body Host · pending confirm',
      priority: 'high',
      confidencePct: 81,
      health: 'on-track',
      estimatedCompletionMins: 120,
      updatedAt: hoursAgo(3),
      researchNotes: ['NIH sleep debt meta-analysis', '3 source verification required'],
      knowledgeSources: ['NIH · CDC · Sleep Foundation'],
      scriptExcerpt: '',
      storyboardStatus: 'pending research complete',
      voiceStatus: 'pending',
      animationStatus: 'pending',
      thumbnailStatus: 'pending',
      captionStatus: 'pending',
      hashtags: ['#sleep', '#health'],
      platformVersions: ['instagram', 'tiktok'],
      approvalHistory: [],
      experiments: ['exp-hook-sleep-041'],
      analyticsSnapshot: '—',
      comments: [],
      revisionHistory: [],
      knowledgeGraphNodeIds: ['node-ndxbook', 'node-memory-bible'],
      memoryReferences: ['Body volume research checklist'],
      institutionalLearnings: [],
    }),
    page({
      id: 'pg-040',
      pageNumber: 40,
      pageLabel: 'page 040',
      title: 'AI tools that actually save time',
      volumeId: 'tech',
      chapter: 'ai tools',
      stageId: 'script',
      assignedExecutive: 'Chief Content Officer',
      priority: 'normal',
      confidencePct: 78,
      health: 'on-track',
      estimatedCompletionMins: 90,
      updatedAt: hoursAgo(5),
      researchNotes: ['Tool comparison matrix complete'],
      knowledgeSources: ['Internal tool audit Q2'],
      scriptExcerpt: 'Most AI tools promise speed. Three actually deliver…',
      storyboardStatus: 'draft pending script lock',
      voiceStatus: 'pending',
      animationStatus: 'pending',
      thumbnailStatus: 'pending',
      captionStatus: 'pending',
      hashtags: ['#ai', '#productivity'],
      platformVersions: ['youtube-shorts', 'tiktok'],
      approvalHistory: ['Research complete · fact-check passed'],
      experiments: [],
      analyticsSnapshot: '—',
      comments: ['Writing Bible: direct tone · no hype'],
      revisionHistory: ['Script v1 submitted'],
      knowledgeGraphNodeIds: ['content-brain'],
      memoryReferences: ['Writing DNA · tech volume'],
      institutionalLearnings: [],
    }),
    page({
      id: 'pg-029',
      pageNumber: 29,
      pageLabel: 'page 029',
      title: 'Habits that stick without motivation',
      volumeId: 'mind',
      chapter: 'habits',
      stageId: 'creative-review',
      assignedExecutive: 'Chief Creative Officer',
      assignedHost: 'Mind Host',
      priority: 'high',
      confidencePct: 71,
      health: 'at-risk',
      estimatedCompletionMins: 45,
      updatedAt: hoursAgo(2),
      researchNotes: ['Habit loop research complete'],
      knowledgeSources: ['Labs #42 hook data'],
      scriptExcerpt: 'What if motivation isn\'t the problem?',
      storyboardStatus: 'question hook variant B',
      voiceStatus: 'queued',
      animationStatus: 'storyboard locked pending script revision',
      thumbnailStatus: '2 variants in Labs',
      captionStatus: 'draft',
      hashtags: ['#habits', '#mind'],
      platformVersions: ['tiktok', 'instagram'],
      approvalHistory: ['Script returned for hook revision · CoS'],
      experiments: ['exp-hook-029', 'exp-thumb-029'],
      analyticsSnapshot: '—',
      comments: ['CoS: apply Labs #42 question hook template B'],
      revisionHistory: ['Script v2 returned · hook too weak'],
      knowledgeGraphNodeIds: ['node-creative-dna', 'node-leadership-dna'],
      memoryReferences: ['Mind volume hook patterns'],
      institutionalLearnings: [],
    }),
    page({
      id: 'pg-028',
      pageNumber: 28,
      pageLabel: 'page 028',
      title: 'Why your credit score drops after paying off debt',
      volumeId: 'money',
      chapter: 'credit',
      stageId: 'thumbnail',
      assignedExecutive: 'Asset Director',
      assignedHost: 'Money Host',
      priority: 'critical',
      confidencePct: 88,
      health: 'on-track',
      estimatedCompletionMins: 25,
      updatedAt: hoursAgo(0.5),
      researchNotes: ['Credit utilization mechanics verified'],
      knowledgeSources: ['CFPB · prior page 019 pattern'],
      scriptExcerpt: 'Paying off debt should help your score. Sometimes it doesn\'t.',
      storyboardStatus: 'approved · stat overlay layout',
      voiceStatus: 'rendered · approved',
      animationStatus: 'complete',
      thumbnailStatus: 'variant B · stat overlay · Labs #38 winner',
      captionStatus: 'final review',
      hashtags: ['#credit', '#money', '#ndxbook'],
      platformVersions: ['youtube-shorts', 'tiktok', 'instagram'],
      approvalHistory: ['Script approved', 'Voice approved', 'Animation approved', 'CoS soft-approved thumbnail'],
      experiments: ['exp-thumb-028 · stat overlay +18% CTR'],
      analyticsSnapshot: '—',
      comments: ['Publish at 2 PM · Money Monday slot'],
      revisionHistory: ['Thumbnail A rejected · too much text', 'Thumbnail B approved'],
      knowledgeGraphNodeIds: ['node-creative-dna', 'node-ndxbook'],
      memoryReferences: ['Creative DNA · stat overlays', 'Leadership DNA · money approval pattern'],
      institutionalLearnings: [],
    }),
    page({
      id: 'pg-027',
      pageNumber: 27,
      pageLabel: 'page 027',
      title: 'Morning routine for focus',
      volumeId: 'mind',
      chapter: 'habits',
      stageId: 'voice-generation',
      assignedExecutive: 'Voice Lab',
      assignedHost: 'Mind Host',
      priority: 'normal',
      confidencePct: 84,
      health: 'on-track',
      estimatedCompletionMins: 40,
      updatedAt: hoursAgo(4),
      researchNotes: ['Complete'],
      knowledgeSources: ['Prior mind volume scripts'],
      scriptExcerpt: 'Three minutes. That\'s all this routine needs.',
      storyboardStatus: 'approved',
      voiceStatus: 'rendering · 78% complete',
      animationStatus: 'queued',
      thumbnailStatus: 'template assigned',
      captionStatus: 'draft',
      hashtags: ['#morning', '#focus'],
      platformVersions: ['instagram', 'tiktok'],
      approvalHistory: ['Script · storyboard approved'],
      experiments: [],
      analyticsSnapshot: '—',
      comments: [],
      revisionHistory: [],
      knowledgeGraphNodeIds: ['node-ndxbook'],
      memoryReferences: [],
      institutionalLearnings: [],
    }),
    page({
      id: 'pg-025',
      pageNumber: 25,
      pageLabel: 'page 025',
      title: 'Sleep temperature sweet spot',
      volumeId: 'body',
      chapter: 'sleep',
      stageId: 'scheduled',
      assignedExecutive: 'Chief Operations Officer',
      assignedHost: 'Body Host',
      priority: 'normal',
      confidencePct: 91,
      health: 'on-track',
      estimatedCompletionMins: 0,
      updatedAt: hoursAgo(6),
      researchNotes: ['Complete'],
      knowledgeSources: ['Sleep Foundation'],
      scriptExcerpt: '65-68°F. Here\'s why.',
      storyboardStatus: 'approved',
      voiceStatus: 'approved',
      animationStatus: 'approved',
      thumbnailStatus: 'approved · minimal text',
      captionStatus: 'approved',
      hashtags: ['#sleep'],
      platformVersions: ['instagram', 'tiktok'],
      approvalHistory: ['Full pipeline approved · CoS soft-approved'],
      experiments: ['exp-publish-time-025'],
      analyticsSnapshot: '—',
      comments: ['Scheduled 11:30 AM'],
      revisionHistory: [],
      knowledgeGraphNodeIds: ['node-ndxbook'],
      memoryReferences: [],
      institutionalLearnings: [],
    }),
    page({
      id: 'pg-024',
      pageNumber: 24,
      pageLabel: 'page 024',
      title: 'Credit utilization explained in 60 seconds',
      volumeId: 'money',
      chapter: 'credit',
      stageId: 'published',
      assignedExecutive: 'Distribution',
      assignedHost: 'Money Host',
      priority: 'normal',
      confidencePct: 93,
      health: 'complete',
      estimatedCompletionMins: 0,
      updatedAt: hoursAgo(8),
      researchNotes: ['Complete'],
      knowledgeSources: ['CFPB'],
      scriptExcerpt: 'Utilization is the number lenders watch most.',
      storyboardStatus: 'published',
      voiceStatus: 'published',
      animationStatus: 'published',
      thumbnailStatus: 'published · stat overlay',
      captionStatus: 'published',
      hashtags: ['#credit'],
      platformVersions: ['tiktok', 'instagram'],
      approvalHistory: ['Full approval chain complete'],
      experiments: ['exp-thumb-024'],
      analyticsSnapshot: '12K views first hour · 74% completion',
      comments: [],
      revisionHistory: [],
      knowledgeGraphNodeIds: ['node-ndxbook', 'node-creative-dna'],
      memoryReferences: ['Money volume stat overlay pattern'],
      institutionalLearnings: ['Stat overlays on money content outperform text-only by 18%'],
    }),
    page({
      id: 'pg-019',
      pageNumber: 19,
      pageLabel: 'page 019',
      title: 'Why paying off debt can hurt your score',
      volumeId: 'money',
      chapter: 'credit',
      stageId: 'institutional-knowledge',
      assignedExecutive: 'Memory Bible',
      assignedHost: 'Money Host',
      priority: 'low',
      confidencePct: 96,
      health: 'complete',
      estimatedCompletionMins: 0,
      updatedAt: hoursAgo(72),
      researchNotes: ['Archived'],
      knowledgeSources: ['All sources verified'],
      scriptExcerpt: 'Published archive',
      storyboardStatus: 'archived',
      voiceStatus: 'archived',
      animationStatus: 'archived',
      thumbnailStatus: 'template source · stat overlay v1',
      captionStatus: 'archived',
      hashtags: [],
      platformVersions: ['tiktok', 'instagram', 'youtube-shorts'],
      approvalHistory: ['Founder approved · fast approval pattern logged'],
      experiments: ['exp-thumb-019 · baseline'],
      analyticsSnapshot: '847K views · 76% completion · top money page',
      comments: [],
      revisionHistory: ['3 thumbnail iterations logged'],
      knowledgeGraphNodeIds: ['node-memory-bible', 'node-creative-dna', 'node-leadership-dna'],
      memoryReferences: ['Creative DNA', 'Leadership DNA decision journal'],
      institutionalLearnings: [
        'Stat overlay template v1 → reusable for money volume',
        'Founder fast-approval when Labs data supports',
        'Knowledge graph node created · feeds page 028 production',
      ],
    }),
  ];

  return {
    workspaceId: 'ai-media',
    dashboard: {
      summary:
        'Production floor active · 9 pages in pipeline · Chief of Staff orchestrating · 2 bottlenecks flagged · page 028 publishing today',
      pagesInProduction: 7,
      pagesPublishingToday: 2,
      bottlenecks: 2,
      overallHealthPct: 84,
      cosOrchestrationStatus: 'ORCHESTRATING · 4 AUTO-ACTIONS QUEUED',
    },
    pages,
    departments: [
      { id: 'research', label: 'RESEARCH', capacityPct: 72, currentWorkload: 2, estimatedCompletionMins: 120, healthPct: 88, activePages: ['pg-041', 'pg-042'], executiveLead: 'Research AI' },
      { id: 'writing', label: 'WRITING', capacityPct: 81, currentWorkload: 1, estimatedCompletionMins: 90, healthPct: 85, activePages: ['pg-040'], executiveLead: 'Chief Content Officer' },
      { id: 'creative', label: 'CREATIVE', capacityPct: 68, currentWorkload: 2, estimatedCompletionMins: 45, healthPct: 74, activePages: ['pg-029', 'pg-028'], executiveLead: 'Chief Creative Officer' },
      { id: 'voice', label: 'VOICE', capacityPct: 55, currentWorkload: 1, estimatedCompletionMins: 40, healthPct: 82, activePages: ['pg-027'], executiveLead: 'Voice Lab' },
      { id: 'animation', label: 'ANIMATION', capacityPct: 60, currentWorkload: 0, estimatedCompletionMins: 0, healthPct: 90, activePages: [], executiveLead: 'Animation Engine' },
      { id: 'publishing', label: 'PUBLISHING', capacityPct: 45, currentWorkload: 1, estimatedCompletionMins: 0, healthPct: 92, activePages: ['pg-025'], executiveLead: 'Chief Operations Officer' },
      { id: 'analytics', label: 'ANALYTICS', capacityPct: 30, currentWorkload: 1, estimatedCompletionMins: 0, healthPct: 95, activePages: ['pg-024'], executiveLead: 'Analytics Director' },
      { id: 'experiments', label: 'EXPERIMENTS', capacityPct: 78, currentWorkload: 4, estimatedCompletionMins: 30, healthPct: 86, activePages: ['pg-028', 'pg-029'], executiveLead: 'Labs Director' },
      { id: 'intelligence', label: 'INTELLIGENCE', capacityPct: 40, currentWorkload: 1, estimatedCompletionMins: 15, healthPct: 91, activePages: [], executiveLead: 'Studio Intelligence' },
      { id: 'legal', label: 'LEGAL', capacityPct: 20, currentWorkload: 0, estimatedCompletionMins: 0, healthPct: 100, activePages: [], executiveLead: 'Chief Legal Officer' },
      { id: 'brand', label: 'BRAND', capacityPct: 35, currentWorkload: 1, estimatedCompletionMins: 20, healthPct: 88, activePages: ['pg-028'], executiveLead: 'Brand Director' },
      { id: 'operations', label: 'OPERATIONS', capacityPct: 62, currentWorkload: 2, estimatedCompletionMins: 25, healthPct: 87, activePages: ['pg-025', 'pg-028'], executiveLead: 'Chief Operations Officer' },
    ],
    editorialCalendar: [
      { id: 'cal-1', title: 'Page 028 · Credit score', pageLabel: 'page 028', scheduledAt: todayAt(14, 0), view: 'daily', volumeId: 'money', platforms: ['youtube-shorts', 'tiktok'], status: 'ready' },
      { id: 'cal-2', title: 'Page 025 · Sleep temp', pageLabel: 'page 025', scheduledAt: todayAt(11, 30), view: 'daily', volumeId: 'body', platforms: ['instagram'], status: 'published' },
      { id: 'cal-3', title: 'Page 029 · Habits', pageLabel: 'page 029', scheduledAt: todayAt(16, 30), view: 'daily', volumeId: 'mind', platforms: ['tiktok'], status: 'in-production' },
      { id: 'cal-4', title: 'Money Monday March', pageLabel: 'campaign', scheduledAt: todayAt(14, 0), view: 'campaign', volumeId: 'money', platforms: ['instagram', 'tiktok'], status: 'in-production' },
      { id: 'cal-5', title: 'Q3 Mind volume push', pageLabel: 'initiative', scheduledAt: todayAt(9, 0), view: 'quarterly', volumeId: 'mind', platforms: ['tiktok', 'instagram'], status: 'planned' },
    ],
    activityWall: [
      { id: 'aw-1', timestamp: hoursAgo(0.25), message: 'page 042 created', executive: 'Chief Content Officer', confidencePct: 72, pageLabel: 'page 042', category: 'creation' },
      { id: 'aw-2', timestamp: hoursAgo(1), message: 'research complete · page 040', executive: 'Research AI', confidencePct: 85, pageLabel: 'page 040', category: 'research' },
      { id: 'aw-3', timestamp: hoursAgo(2), message: 'script approved · page 028 voice queue', executive: 'Chief of Staff', confidencePct: 88, pageLabel: 'page 028', category: 'approval' },
      { id: 'aw-4', timestamp: hoursAgo(3), message: 'thumbnail experiment won · stat overlay +18%', executive: 'Labs Director', confidencePct: 91, pageLabel: 'page 028', category: 'experiment' },
      { id: 'aw-5', timestamp: hoursAgo(4), message: 'voice rendering complete · page 027', executive: 'Voice Lab', confidencePct: 84, pageLabel: 'page 027', category: 'voice' },
      { id: 'aw-6', timestamp: hoursAgo(5), message: 'scheduled for publishing · page 025', executive: 'Chief Operations Officer', confidencePct: 91, pageLabel: 'page 025', category: 'publish' },
      { id: 'aw-7', timestamp: hoursAgo(6), message: 'published · page 024 · 12K first hour', executive: 'Distribution', confidencePct: 93, pageLabel: 'page 024', category: 'publish' },
      { id: 'aw-8', timestamp: hoursAgo(8), message: 'retention exceeded target · page 024 · 74%', executive: 'Analytics Director', confidencePct: 90, pageLabel: 'page 024', category: 'analytics' },
      { id: 'aw-9', timestamp: hoursAgo(12), message: 'institutional learning recorded · page 019 template', executive: 'Memory Bible', confidencePct: 96, pageLabel: 'page 019', category: 'learning' },
      { id: 'aw-10', timestamp: hoursAgo(1.5), message: 'CoS reassigned thumbnail queue · Asset Director', executive: 'Chief of Staff', confidencePct: 86, pageLabel: 'page 029', category: 'approval' },
    ],
    productionIntelligence: [
      { id: 'pi-1', signal: 'Thumbnail bottleneck · 3 pages > 24h', recommendation: 'Apply Labs #38 stat overlay as default for money/mind volumes', severity: 'warning', confidencePct: 88, department: 'creative' },
      { id: 'pi-2', signal: 'Mind volume retention +18%', recommendation: 'Allocate 2 extra pages to habits chapter this week', severity: 'info', confidencePct: 82, department: 'intelligence' },
      { id: 'pi-3', signal: 'Page 029 script confidence below threshold', recommendation: 'Return for hook revision · Labs #42 template B', severity: 'warning', confidencePct: 76, department: 'writing' },
      { id: 'pi-4', signal: 'Voice Lab at 55% capacity', recommendation: 'Batch voice renders for pages 027-029 overnight', severity: 'info', confidencePct: 84, department: 'voice' },
      { id: 'pi-5', signal: 'Creative fatigue on CCO queue', recommendation: 'Increase soft-approval threshold for DNA-aligned thumbnails', severity: 'critical', confidencePct: 79, department: 'creative' },
    ],
    orchestrationQueue: [
      { id: 'oq-1', action: 'Prioritize page 028 · publish 2 PM', target: 'page 028', rationale: 'Money Monday slot · Labs data · CoS soft-approved', status: 'applied', chiefOfStaffInitiated: true },
      { id: 'oq-2', action: 'Return page 029 script for hook revision', target: 'page 029', rationale: 'Confidence 71% · below Leadership DNA threshold', status: 'applied', chiefOfStaffInitiated: true },
      { id: 'oq-3', action: 'Assign Mind Host to page 029', target: 'page 029', rationale: 'Volume · chapter · historical performance match', status: 'applied', chiefOfStaffInitiated: true },
      { id: 'oq-4', action: 'Escalate affiliate disclaimer · page 031', target: 'page 031', rationale: 'Legal policy update · founder review required', status: 'escalated', chiefOfStaffInitiated: true },
    ],
    talentRouting: [
      { pageId: 'pg-028', pageLabel: 'page 028', recommendedHost: 'Money Host', rationale: 'Money volume · credit chapter · 847K avg on prior money pages', confidencePct: 94, factors: ['volume', 'chapter', 'historical performance'] },
      { pageId: 'pg-029', pageLabel: 'page 029', recommendedHost: 'Mind Host', rationale: 'Mind volume · habits chapter · question hook specialist', confidencePct: 89, factors: ['volume', 'brand', 'voice'] },
      { pageId: 'pg-027', pageLabel: 'page 027', recommendedHost: 'Mind Host', rationale: 'Mind volume · morning routine · host available', confidencePct: 91, factors: ['availability', 'volume', 'audience'] },
    ],
    experiments: [
      { id: 'exp-028', pageId: 'pg-028', type: 'thumbnail', name: 'Stat overlay vs text-only', status: 'completed', winner: 'Stat overlay B · +18% CTR', confidencePct: 91 },
      { id: 'exp-029a', pageId: 'pg-029', type: 'hook', name: 'Question hook A vs B', status: 'active', confidencePct: 78 },
      { id: 'exp-029b', pageId: 'pg-029', type: 'thumbnail', name: 'Minimal vs badge layout', status: 'active', confidencePct: 72 },
      { id: 'exp-025', pageId: 'pg-025', type: 'publish-time', name: '11:30 vs 2 PM slot', status: 'completed', winner: '11:30 AM body volume', confidencePct: 85 },
    ],
    assetLineage: [
      { id: 'al-1', pageId: 'pg-028', assetType: 'thumbnail', version: 1, label: 'Text-heavy variant A', revisedAt: hoursAgo(12), revisedBy: 'Asset Director', changeNote: 'Rejected · too much text · Leadership DNA pattern' },
      { id: 'al-2', pageId: 'pg-028', assetType: 'thumbnail', version: 2, label: 'Stat overlay variant B', revisedAt: hoursAgo(6), revisedBy: 'Chief Creative Officer', changeNote: 'Labs #38 winner · CoS soft-approved' },
      { id: 'al-3', pageId: 'pg-028', assetType: 'script', version: 1, label: 'Initial script', revisedAt: hoursAgo(24), revisedBy: 'Chief Content Officer', changeNote: 'Approved · Writing Bible compliant' },
      { id: 'al-4', pageId: 'pg-029', assetType: 'script', version: 2, label: 'Hook revision pending', revisedAt: hoursAgo(2), revisedBy: 'Chief of Staff', changeNote: 'Returned · apply Labs #42 template B' },
      { id: 'al-5', pageId: 'pg-024', assetType: 'voiceover', version: 1, label: 'Money Host take 1', revisedAt: hoursAgo(48), revisedBy: 'Voice Lab', changeNote: 'Approved · published' },
    ],
    operationalDna: [
      { id: 'od-1', title: 'PRODUCTION STANDARDS', principles: ['72%+ completion before publish', 'Every page = Labs experiment opportunity', 'Fact verification before script lock', 'QA gate before executive review'] },
      { id: 'od-2', title: 'WORKFLOW PREFERENCES', principles: ['Research → script → creative → production → publish', 'CoS orchestrates · founder sets priorities only', 'Batch voice renders overnight', 'Thumbnail experiments before final lock'] },
      { id: 'od-3', title: 'APPROVAL SEQUENCES', principles: ['DNA layers validated at each stage', 'CoS soft-approve when Leadership DNA aligned', 'Legal always founder-reviewed for policy updates', 'Executive review = CoS gate not founder default'] },
      { id: 'od-4', title: 'HANDOFF RULES', principles: ['Nothing exists outside the page workspace', 'Asset lineage tracked for every revision', 'Experiments attached to page forever', 'Completed pages → institutional knowledge automatically'] },
      { id: 'od-5', title: 'AUTOMATION RULES', principles: ['Talent routing by volume · chapter · performance', 'Auto-prioritize from Studio Intelligence signals', 'Reassign on bottleneck > 24h', 'Escalate exceptions only · not routine production'] },
    ],
    knowledgeOutputs: [
      { pageId: 'pg-019', pageLabel: 'page 019', institutionalKnowledge: 'Stat overlay template v1 for money volume', graphNodesCreated: ['node-creative-dna', 'node-leadership-dna'], templatesGenerated: ['money-stat-overlay-v1'], improvements: ['Creative taste engine +8%', 'CoS thumbnail confidence +6%'] },
      { pageId: 'pg-024', pageLabel: 'page 024', institutionalKnowledge: 'Credit utilization 60-second format validated', graphNodesCreated: ['node-ndxbook'], templatesGenerated: ['money-credit-60s'], improvements: ['Writing DNA hook pattern logged'] },
    ],
    selectedPageId: 'pg-028',
  };
}

export function bootstrapAiMediaNdxbookNewsroom(): void {
  bootstrapNdxbookNewsroomStore(buildNdxbookNewsroomSeed());
}
