import type { DependencyMapSeedInput } from '../types';

/** Canonical Studio OS core systems — seeded from STUDIO_OS_DEPENDENCY_MAP.md */
export const STUDIO_OS_DEPENDENCY_SEED: DependencyMapSeedInput[] = [
  {
    systemId: 'genesis',
    name: 'Genesis™',
    purpose: 'Canonical source-of-truth kernel and governance authority.',
    status: 'implemented',
    buildPhase: 0,
    buildOrder: 1,
    priority: 'P0',
    upstreamDependencies: [],
    ownedData: ['Canonical articles', 'Proposals', 'ADRs', 'Review status', 'Compile manifests'],
    eventsEmitted: ['Genesis Object Created™', 'Article Canonicalized™', 'ADR Accepted™', 'Compile Completed™'],
    eventsConsumed: ['Proposal Submitted™', 'Review Completed™'],
    implementationRisk: 'low',
    notes: 'Genesis Foundation Framework runtime shipped.',
  },
  {
    systemId: 'canonical-object-model',
    name: 'Canonical Object Model™',
    purpose: 'Universal ontology and relationship envelope for all Studio World objects.',
    status: 'implemented',
    buildPhase: 0,
    buildOrder: 2,
    priority: 'P0',
    upstreamDependencies: ['genesis'],
    ownedData: ['Object schemas', 'Object types', 'Relationship language'],
    eventsEmitted: ['Object Type Registered™', 'Object Validated™'],
    eventsConsumed: ['Genesis Article Canonicalized™'],
    implementationRisk: 'low',
    notes: 'Object model infrastructure shipped under genesis/object-model.',
  },
  {
    systemId: 'universal-interaction-model',
    name: 'Universal Interaction Model™',
    purpose: 'Shared grammar for interactions, events, commands, workflows, and audit.',
    status: 'implemented',
    buildPhase: 0,
    buildOrder: 3,
    priority: 'P0',
    upstreamDependencies: ['genesis', 'canonical-object-model'],
    ownedData: ['Interaction records', 'Event contracts', 'Workflow primitives', 'Audit events'],
    eventsEmitted: ['Interaction Submitted™', 'Event Emitted™', 'Workflow Advanced™'],
    eventsConsumed: ['Object Validated™', 'Command Requested™'],
    implementationRisk: 'medium',
    notes: 'Interaction model infrastructure shipped.',
  },
  {
    systemId: 'universal-decision-architecture',
    name: 'Universal Decision Architecture™',
    purpose: 'Shared reasoning model for recommendations, priorities, confidence, evidence, review, and learning.',
    status: 'implemented',
    buildPhase: 0,
    buildOrder: 4,
    priority: 'P0',
    upstreamDependencies: ['genesis', 'canonical-object-model', 'universal-interaction-model'],
    ownedData: ['Decisions', 'Recommendations', 'Priorities', 'Evidence', 'Confidence', 'Audit', 'Learning feedback'],
    eventsEmitted: ['Decision Proposed™', 'Recommendation Delivered™', 'Priority Ranked™'],
    eventsConsumed: ['Evidence Submitted™', 'Analytics Signal Raised™'],
    implementationRisk: 'medium',
    notes: 'Decision engine infrastructure shipped.',
  },
  {
    systemId: 'core-systems-registry',
    name: 'Core Systems Registry™',
    purpose: 'Platform system boundaries, dependencies, capabilities, contracts, and lifecycle.',
    status: 'implemented',
    buildPhase: 0,
    buildOrder: 5,
    priority: 'P0',
    upstreamDependencies: ['genesis', 'canonical-object-model', 'universal-interaction-model', 'universal-decision-architecture'],
    ownedData: ['System blueprints', 'Dependency records', 'Boundaries', 'Integration contracts'],
    eventsEmitted: ['System Registered™', 'Dependency Linked™', 'Lifecycle Transitioned™'],
    eventsConsumed: ['Genesis Article Canonicalized™'],
    implementationRisk: 'medium',
    notes: 'Core Systems Blueprint scaffolding shipped.',
  },
  {
    systemId: 'studio-os-dependency-map',
    name: 'Studio OS Dependency Map™',
    purpose: 'Master planning engine for build order, readiness, risks, and dependency truth.',
    status: 'implemented',
    buildPhase: 0,
    buildOrder: 6,
    priority: 'P0',
    upstreamDependencies: ['genesis', 'core-systems-registry'],
    ownedData: ['Dependency system records', 'Build order', 'Readiness scores', 'Architecture risks'],
    eventsEmitted: ['Dependency Map Seeded™', 'Readiness Recomputed™', 'Build Order Updated™'],
    eventsConsumed: ['System Registered™', 'System Status Changed™'],
    implementationRisk: 'medium',
    notes: 'This sprint — dependency mapping infrastructure.',
  },
  {
    systemId: 'knowledge-core',
    name: 'Knowledge Core™',
    purpose: 'Canonical knowledge store and retrieval substrate.',
    status: 'planned',
    buildPhase: 1,
    buildOrder: 7,
    priority: 'P1',
    upstreamDependencies: ['genesis', 'canonical-object-model', 'world-graph'],
    ownedData: ['Knowledge artifacts', 'Citations', 'Source status', 'Semantic metadata'],
    eventsEmitted: ['Knowledge Artifact Added™', 'Knowledge Approved™', 'Knowledge Linked™'],
    eventsConsumed: ['Genesis Article Canonicalized™', 'Research Finding Submitted™'],
    implementationRisk: 'high',
    notes: 'Recommended next implementation sprint.',
  },
  {
    systemId: 'world-graph',
    name: 'World Graph™',
    purpose: 'Relationship graph connecting objects, systems, companies, places, knowledge, missions, and assets.',
    status: 'planned',
    buildPhase: 1,
    buildOrder: 8,
    priority: 'P1',
    upstreamDependencies: ['canonical-object-model', 'genesis'],
    ownedData: ['Graph nodes', 'Graph edges', 'Graph metadata', 'Dependency overlays'],
    eventsEmitted: ['Graph Node Added™', 'Relationship Linked™', 'Graph Projection Compiled™'],
    eventsConsumed: ['Object Registered™', 'System Registered™', 'Knowledge Artifact Approved™'],
    implementationRisk: 'high',
  },
  {
    systemId: 'codex',
    name: 'Codex™',
    purpose: 'Compiled developer/architect knowledge projection from Genesis and canonical sources.',
    status: 'planned',
    buildPhase: 1,
    buildOrder: 9,
    priority: 'P1',
    upstreamDependencies: ['genesis', 'knowledge-core'],
    ownedData: ['Compiled reference entries', 'API/spec projections', 'Canonical excerpts'],
    eventsEmitted: ['Codex Entry Published™', 'Projection Updated™'],
    eventsConsumed: ['Genesis Compile Completed™', 'Knowledge Artifact Approved™'],
    implementationRisk: 'medium',
  },
  {
    systemId: 'knowledge-retention',
    name: 'Knowledge Retention™',
    purpose: 'Retains, summarizes, ages, promotes, and archives knowledge/memory over time.',
    status: 'planned',
    buildPhase: 1,
    buildOrder: 10,
    priority: 'P2',
    upstreamDependencies: ['knowledge-core', 'universal-decision-architecture'],
    ownedData: ['Retention policies', 'Summaries', 'Archived knowledge', 'Promotion signals'],
    eventsEmitted: ['Knowledge Summarized™', 'Knowledge Archived™', 'Retention Review Requested™'],
    eventsConsumed: ['Knowledge Artifact Added™', 'Learning Feedback Recorded™'],
    implementationRisk: 'medium',
  },
  {
    systemId: 'identity-engine',
    name: 'Identity Engine™',
    purpose: 'Trusted identity fabric for humans, AI workers, companies, roles, credentials, and agents.',
    status: 'planned',
    buildPhase: 2,
    buildOrder: 11,
    priority: 'P1',
    upstreamDependencies: ['canonical-object-model', 'company-registry'],
    ownedData: ['Identities', 'Profiles', 'Roles', 'Credentials', 'Affiliations'],
    eventsEmitted: ['Identity Created™', 'Role Assigned™', 'Credential Linked™'],
    eventsConsumed: ['Company Registered™', 'Permission Scope Requested™'],
    implementationRisk: 'high',
    notes: 'Minimal company-registry link required first.',
  },
  {
    systemId: 'company-registry',
    name: 'Company Registry™',
    purpose: 'System of record for companies, headquarters, departments, workspaces, memberships, and ownership.',
    status: 'planned',
    buildPhase: 2,
    buildOrder: 12,
    priority: 'P1',
    upstreamDependencies: ['canonical-object-model'],
    ownedData: ['Company records', 'Departments', 'Memberships', 'Workspace metadata'],
    eventsEmitted: ['Company Registered™', 'Department Created™', 'Membership Updated™'],
    eventsConsumed: ['Identity Created™', 'Role Assigned™'],
    implementationRisk: 'high',
  },
  {
    systemId: 'permissions-engine',
    name: 'Permissions Engine™',
    purpose: 'Authority, scope, delegation, approval, and access decisions.',
    status: 'planned',
    buildPhase: 2,
    buildOrder: 13,
    priority: 'P1',
    upstreamDependencies: ['identity-engine', 'universal-decision-architecture', 'genesis'],
    ownedData: ['Policies', 'Grants', 'Denials', 'Scopes', 'Delegations', 'Approval requirements'],
    eventsEmitted: ['Permission Granted™', 'Permission Denied™', 'Delegation Revoked™'],
    eventsConsumed: ['Identity Updated™', 'Command Requested™', 'Risk Raised™'],
    implementationRisk: 'critical',
  },
  {
    systemId: 'mission-control',
    name: 'Mission Control™',
    purpose: 'Mission state, progress, ownership, blockers, outcomes, and learning.',
    status: 'planned',
    buildPhase: 3,
    buildOrder: 14,
    priority: 'P2',
    upstreamDependencies: ['company-registry', 'universal-interaction-model', 'universal-decision-architecture', 'command-center', 'permissions-engine'],
    ownedData: ['Missions', 'Assignments', 'Blockers', 'Outcomes', 'Lessons'],
    eventsEmitted: ['Mission Created™', 'Mission Advanced™', 'Blocker Raised™', 'Mission Completed™'],
    eventsConsumed: ['Command Executed™', 'Priority Ranked™', 'Workflow Advanced™'],
    implementationRisk: 'high',
  },
  {
    systemId: 'production-board',
    name: 'Production Board™',
    purpose: 'Operational board for work queues, statuses, blockers, approvals, and production visibility.',
    status: 'planned',
    buildPhase: 3,
    buildOrder: 15,
    priority: 'P2',
    upstreamDependencies: ['mission-control', 'universal-interaction-model', 'company-registry', 'permissions-engine'],
    ownedData: ['Board columns', 'Cards', 'Status views', 'Blocker metadata'],
    eventsEmitted: ['Production Card Created™', 'Status Changed™', 'Blocker Raised™'],
    eventsConsumed: ['Mission Created™', 'Workflow Advanced™', 'Permission Granted™'],
    implementationRisk: 'medium',
  },
  {
    systemId: 'command-center',
    name: 'Command Center™',
    purpose: 'Safe command intake, validation, routing, monitoring, rollback, and audit.',
    status: 'planned',
    buildPhase: 3,
    buildOrder: 16,
    priority: 'P2',
    upstreamDependencies: ['universal-interaction-model', 'universal-decision-architecture', 'permissions-engine', 'identity-engine'],
    ownedData: ['Command history', 'Execution state', 'Approval/rollback metadata'],
    eventsEmitted: ['Command Issued™', 'Command Approved™', 'Command Executed™', 'Command Failed™'],
    eventsConsumed: ['Permission Granted/Denied™', 'Recommendation Delivered™', 'Workflow Advanced™'],
    implementationRisk: 'critical',
  },
  {
    systemId: 'notification-engine',
    name: 'Notification Engine™',
    purpose: 'Meaningful alerts, prompts, reminders, digests, and attention orchestration.',
    status: 'planned',
    buildPhase: 3,
    buildOrder: 17,
    priority: 'P2',
    upstreamDependencies: ['universal-interaction-model', 'identity-engine', 'permissions-engine', 'mission-control'],
    ownedData: ['Notifications', 'Delivery state', 'Preference signals', 'Read/action history'],
    eventsEmitted: ['Notification Created™', 'Notification Delivered™', 'Notification Acted™'],
    eventsConsumed: ['Mission Advanced™', 'Command Failed™', 'Permission Requested™'],
    implementationRisk: 'medium',
  },
  {
    systemId: 'production-orchestrator',
    name: 'Production Orchestrator™',
    purpose: 'Coordinates production execution across recipes, assets, missions, commands, permissions, and compiles.',
    status: 'planned',
    buildPhase: 3,
    buildOrder: 18,
    priority: 'P3',
    upstreamDependencies: ['command-center', 'permissions-engine', 'mission-control', 'production-board', 'generation-recipes', 'asset-registry'],
    ownedData: ['Production runs', 'Job state', 'Execution logs', 'Rollback plans'],
    eventsEmitted: ['Production Started™', 'Step Completed™', 'Production Failed™', 'Rollback Requested™'],
    eventsConsumed: ['Command Approved™', 'Mission Advanced™', 'Recipe Approved™'],
    implementationRisk: 'critical',
  },
  {
    systemId: 'search-engine',
    name: 'Search Engine™',
    purpose: 'Finds objects, knowledge, systems, assets, missions, people, and marketplace offerings.',
    status: 'planned',
    buildPhase: 8,
    buildOrder: 19,
    priority: 'P2',
    upstreamDependencies: ['world-graph', 'knowledge-core', 'permissions-engine', 'asset-registry'],
    ownedData: ['Indexes', 'Query history', 'Result metadata', 'Relevance signals'],
    eventsEmitted: ['Search Submitted™', 'Result Opened™', 'No Result Found™'],
    eventsConsumed: ['Object Registered™', 'Graph Projection Compiled™', 'Asset Registered™'],
    implementationRisk: 'high',
  },
  {
    systemId: 'analytics-engine',
    name: 'Analytics Engine™',
    purpose: 'Observes events, computes metrics, trends, health, and decision evidence.',
    status: 'planned',
    buildPhase: 8,
    buildOrder: 20,
    priority: 'P3',
    upstreamDependencies: ['universal-interaction-model', 'world-graph', 'mission-control', 'company-registry'],
    ownedData: ['Metrics', 'Reports', 'Observations', 'Trend summaries', 'Evidence packages'],
    eventsEmitted: ['Metric Updated™', 'Trend Detected™', 'Risk Signal Raised™', 'Briefing Generated™'],
    eventsConsumed: ['Event Emitted™', 'Mission Completed™', 'Search Submitted™'],
    implementationRisk: 'high',
    notes: 'Observes only — must not mutate operational systems.',
  },
  {
    systemId: 'company-headquarters',
    name: 'Company Headquarters™',
    purpose: 'Founder/company operating environment and executive surface.',
    status: 'planned',
    buildPhase: 4,
    buildOrder: 21,
    priority: 'P3',
    upstreamDependencies: ['company-registry', 'command-center', 'mission-control', 'world-graph', 'analytics-engine', 'permissions-engine'],
    ownedData: ['HQ layout state', 'Executive summaries', 'Room composition', 'Dashboard view state'],
    eventsEmitted: ['Headquarters Opened™', 'Briefing Requested™', 'Room Entered™'],
    eventsConsumed: ['Mission Advanced™', 'Metric Updated™', 'Command Executed™'],
    implementationRisk: 'high',
    notes: 'Consumer surface — do not own mission or analytics truth.',
  },
  {
    systemId: 'atlas',
    name: 'Atlas™',
    purpose: 'Navigational/structural map of Studio OS systems, companies, worlds, rooms, and dependencies.',
    status: 'planned',
    buildPhase: 4,
    buildOrder: 22,
    priority: 'P3',
    upstreamDependencies: ['world-graph', 'search-engine', 'company-registry', 'core-systems-registry'],
    ownedData: ['Map overlays', 'Route metadata', 'Structural navigation state'],
    eventsEmitted: ['Route Requested™', 'Map Layer Opened™', 'Dependency Viewed™'],
    eventsConsumed: ['Graph Projection Compiled™', 'Search Submitted™'],
    implementationRisk: 'medium',
  },
  {
    systemId: 'orb',
    name: 'Orb™',
    purpose: 'Intelligent companion and command interface coordinating systems.',
    status: 'planned',
    buildPhase: 4,
    buildOrder: 23,
    priority: 'P3',
    upstreamDependencies: ['command-center', 'universal-decision-architecture', 'knowledge-core', 'identity-engine', 'permissions-engine', 'world-graph'],
    ownedData: ['Conversation context', 'Intent interpretations', 'Routing metadata', 'Memory candidates'],
    eventsEmitted: ['Orb Request Created™', 'Approval Requested™', 'Memory Candidate Created™'],
    eventsConsumed: ['Command Resulted™', 'Recommendation Delivered™', 'Knowledge Artifact Approved™'],
    implementationRisk: 'critical',
    notes: 'Wait until command, permission, knowledge, and graph are stable.',
  },
  {
    systemId: 'asset-registry',
    name: 'Asset Registry™',
    purpose: 'Source of truth for assets, files, components, provenance, rights, versions, and usage.',
    status: 'planned',
    buildPhase: 5,
    buildOrder: 24,
    priority: 'P2',
    upstreamDependencies: ['canonical-object-model', 'identity-engine', 'permissions-engine'],
    ownedData: ['Asset metadata', 'Provenance', 'Versions', 'Licenses', 'Usage references'],
    eventsEmitted: ['Asset Registered™', 'Asset Versioned™', 'Asset Licensed™'],
    eventsConsumed: ['Identity Verified™', 'Permission Granted™'],
    implementationRisk: 'high',
  },
  {
    systemId: 'experience-engine',
    name: 'Experience Engine™',
    purpose: 'Composes and renders interactive/spatial/product experiences from canonical state.',
    status: 'planned',
    buildPhase: 5,
    buildOrder: 25,
    priority: 'P3',
    upstreamDependencies: ['world-graph', 'identity-engine', 'permissions-engine', 'asset-registry'],
    ownedData: ['Experience definitions', 'Layout composition state', 'Presentation contracts'],
    eventsEmitted: ['Experience Opened™', 'Scene Requested™', 'Experience Updated™'],
    eventsConsumed: ['Graph Projection Compiled™', 'Asset Registered™'],
    implementationRisk: 'high',
  },
  {
    systemId: 'generation-recipes',
    name: 'Generation Recipes™',
    purpose: 'Reusable generation instructions, constraints, prompts, templates, and review requirements.',
    status: 'planned',
    buildPhase: 5,
    buildOrder: 26,
    priority: 'P3',
    upstreamDependencies: ['universal-decision-architecture', 'knowledge-core', 'asset-registry', 'permissions-engine'],
    ownedData: ['Recipes', 'Constraints', 'Input/output specs', 'Review rules'],
    eventsEmitted: ['Recipe Created™', 'Recipe Approved™', 'Recipe Deprecated™'],
    eventsConsumed: ['Evidence Submitted™', 'Asset Registered™'],
    implementationRisk: 'high',
  },
  {
    systemId: 'scene-graph',
    name: 'Scene Graph™',
    purpose: 'Structured scene/world composition graph for spatial and experience assembly.',
    status: 'planned',
    buildPhase: 5,
    buildOrder: 27,
    priority: 'P3',
    upstreamDependencies: ['world-graph', 'asset-registry', 'experience-engine'],
    ownedData: ['Scene nodes', 'Scene edges', 'Placements', 'Environment metadata'],
    eventsEmitted: ['Scene Node Added™', 'Scene Linked™', 'Scene Graph Validated™'],
    eventsConsumed: ['Asset Registered™', 'Experience Updated™'],
    implementationRisk: 'high',
  },
  {
    systemId: 'world-compiler',
    name: 'World Compiler™',
    purpose: 'Compiles graph/scene/asset/experience inputs into deployable world outputs.',
    status: 'planned',
    buildPhase: 5,
    buildOrder: 28,
    priority: 'P3',
    upstreamDependencies: ['scene-graph', 'asset-registry', 'experience-engine', 'generation-recipes'],
    ownedData: ['Compile manifests', 'Build outputs', 'Validation reports'],
    eventsEmitted: ['World Compile Started™', 'World Compile Completed™', 'Compile Failed™'],
    eventsConsumed: ['Scene Graph Validated™', 'Recipe Approved™', 'Asset Versioned™'],
    implementationRisk: 'high',
  },
  {
    systemId: 'studio-foundry',
    name: 'Studio Foundry™',
    purpose: 'Creation environment for producing worlds, assets, scenes, and generated experiences.',
    status: 'planned',
    buildPhase: 5,
    buildOrder: 29,
    priority: 'P4',
    upstreamDependencies: ['asset-registry', 'generation-recipes', 'scene-graph', 'world-compiler', 'permissions-engine'],
    ownedData: ['Foundry project state', 'Creation sessions', 'Output manifests'],
    eventsEmitted: ['Foundry Session Started™', 'Asset Requested™', 'Build Submitted™'],
    eventsConsumed: ['Recipe Approved™', 'Asset Registered™', 'Compile Completed™'],
    implementationRisk: 'high',
  },
  {
    systemId: 'research-engine',
    name: 'Research Engine™',
    purpose: 'Captures research questions, sources, findings, evidence, and review status.',
    status: 'planned',
    buildPhase: 6,
    buildOrder: 30,
    priority: 'P3',
    upstreamDependencies: ['knowledge-core', 'codex', 'universal-decision-architecture'],
    ownedData: ['Research projects', 'Sources', 'Findings', 'Evidence packages'],
    eventsEmitted: ['Research Started™', 'Finding Submitted™', 'Finding Approved™'],
    eventsConsumed: ['Knowledge Gap Raised™', 'Decision Evidence Requested™'],
    implementationRisk: 'medium',
  },
  {
    systemId: 'institute-of-knowledge',
    name: 'Institute of Knowledge™',
    purpose: 'Learning and publishing institution for canonical knowledge.',
    status: 'planned',
    buildPhase: 1,
    buildOrder: 31,
    priority: 'P2',
    upstreamDependencies: ['genesis', 'knowledge-core', 'codex', 'world-graph'],
    ownedData: ['Curricula', 'Knowledge programs', 'Learning paths', 'Instructional artifacts'],
    eventsEmitted: ['Knowledge Program Published™', 'Curriculum Revised™'],
    eventsConsumed: ['Knowledge Artifact Approved™', 'Research Finding Approved™'],
    implementationRisk: 'medium',
  },
  {
    systemId: 'profession-brains',
    name: 'Profession Brains™',
    purpose: 'Profession-specific cognition, standards, workflows, examples, and recommendations.',
    status: 'planned',
    buildPhase: 6,
    buildOrder: 32,
    priority: 'P4',
    upstreamDependencies: ['institute-of-knowledge', 'knowledge-core', 'research-engine', 'professional-memory'],
    ownedData: ['Profession models', 'Competency maps', 'Standards', 'Templates'],
    eventsEmitted: ['Profession Brain Updated™', 'Competency Linked™'],
    eventsConsumed: ['Research Finding Approved™', 'Memory Summarized™'],
    implementationRisk: 'high',
  },
  {
    systemId: 'professional-memory',
    name: 'Professional Memory™',
    purpose: 'Long-term profession-specific memory and lessons learned.',
    status: 'planned',
    buildPhase: 6,
    buildOrder: 33,
    priority: 'P4',
    upstreamDependencies: ['identity-engine', 'knowledge-retention', 'profession-brains', 'knowledge-core'],
    ownedData: ['Memory records', 'Lessons', 'Summaries', 'Applicability metadata'],
    eventsEmitted: ['Professional Memory Captured™', 'Lesson Promoted™'],
    eventsConsumed: ['Mission Completed™', 'Learning Feedback Recorded™'],
    implementationRisk: 'high',
  },
  {
    systemId: 'simulation-engine',
    name: 'Simulation Engine™',
    purpose: 'Safe what-if environments for decisions, worlds, careers, production, and scenarios.',
    status: 'planned',
    buildPhase: 6,
    buildOrder: 34,
    priority: 'P4',
    upstreamDependencies: ['universal-decision-architecture', 'scene-graph', 'experience-engine', 'analytics-engine'],
    ownedData: ['Simulation scenarios', 'Assumptions', 'Outputs', 'Confidence records'],
    eventsEmitted: ['Simulation Started™', 'Simulation Completed™', 'Scenario Compared™'],
    eventsConsumed: ['Decision Proposed™', 'Scene Graph Validated™', 'Metric Updated™'],
    implementationRisk: 'high',
  },
  {
    systemId: 'career-worlds',
    name: 'Career Worlds™',
    purpose: 'Learning/career experience worlds for professions, missions, simulations, and portfolios.',
    status: 'planned',
    buildPhase: 7,
    buildOrder: 35,
    priority: 'P4',
    upstreamDependencies: ['experience-engine', 'profession-brains', 'identity-engine', 'permissions-engine', 'mission-control', 'asset-registry'],
    ownedData: ['Career world progress', 'Learner missions', 'Portfolio state', 'Experience state'],
    eventsEmitted: ['Career World Entered™', 'Lesson Completed™', 'Portfolio Updated™'],
    eventsConsumed: ['Profession Brain Updated™', 'Mission Completed™', 'Asset Registered™'],
    implementationRisk: 'critical',
  },
  {
    systemId: 'studio-exchange',
    name: 'Studio Exchange™',
    purpose: 'Marketplace/economy surface for packaging, listing, selling, licensing, and fulfillment.',
    status: 'planned',
    buildPhase: 7,
    buildOrder: 36,
    priority: 'P4',
    upstreamDependencies: ['identity-engine', 'permissions-engine', 'company-registry', 'asset-registry', 'search-engine', 'analytics-engine'],
    ownedData: ['Listings', 'Offers', 'Entitlements', 'Fulfillment state', 'Marketplace pages'],
    eventsEmitted: ['Listing Published™', 'Offer Purchased™', 'Entitlement Granted™'],
    eventsConsumed: ['Asset Licensed™', 'Permission Granted™', 'Search Submitted™'],
    implementationRisk: 'critical',
    notes: 'Postpone until identity, permissions, assets, search, and analytics are stable.',
  },
];
