import { bootstrapEcosystemMarketplaceStore } from './store';
import type { EcosystemMarketplaceStore, MarketplaceAssetProfile } from './types';

export function buildEcosystemMarketplaceSeed(): Partial<EcosystemMarketplaceStore> {
  const assets: MarketplaceAssetProfile[] = [
    {
      id: 'asset-newsroom-playbook',
      workspaceId: 'ndxbook',
      title: 'NDXBOOK NEWSROOM OPERATING PLAYBOOK',
      category: 'playbooks',
      creatorOrg: 'NDXBOOK',
      organization: 'NDXBOOK',
      description: 'Complete newsroom cadence · page strategy · editorial QA · CoS approval flows · Labs integration',
      version: '2.4.1',
      rating: 4.9,
      downloads: 847,
      activeCompanies: 12,
      performancePct: 91,
      reviewCount: 34,
      compatibilityPct: 88,
      lastUpdated: '2026-06-15',
      inheritanceCompatible: true,
      knowledgeMaturityPct: 92,
      licensing: 'subscription',
      verified: true,
      verificationBadges: ['verified-playbook', 'verified-organization'],
      featured: true,
    },
    {
      id: 'asset-leadership-dna-vxd',
      workspaceId: 'studio-os',
      title: 'VXD LEADERSHIP DNA FRAMEWORK',
      category: 'organizational-dna',
      creatorOrg: 'VXD',
      organization: 'VXD',
      description: 'Founder operating blueprint · delegation modes · soft approval thresholds · escalation routing',
      version: '1.8.0',
      rating: 4.8,
      downloads: 623,
      activeCompanies: 8,
      performancePct: 94,
      reviewCount: 28,
      compatibilityPct: 91,
      lastUpdated: '2026-05-22',
      inheritanceCompatible: true,
      knowledgeMaturityPct: 89,
      licensing: 'enterprise',
      verified: true,
      verificationBadges: ['verified-organization', 'verified-enterprise'],
      featured: true,
    },
    {
      id: 'asset-creative-dna-fs',
      workspaceId: 'frontal-slayer',
      title: 'FRONTAL SLAYER CREATIVE DNA SYSTEM',
      category: 'creative-systems',
      creatorOrg: 'FRONTAL SLAYER',
      organization: 'FRONTAL SLAYER',
      description: 'Luxury raw aesthetic · PSA voice · product photography bible · lounge TV creative standards',
      version: '3.1.2',
      rating: 4.7,
      downloads: 412,
      activeCompanies: 6,
      performancePct: 88,
      reviewCount: 19,
      compatibilityPct: 76,
      lastUpdated: '2026-06-01',
      inheritanceCompatible: true,
      knowledgeMaturityPct: 91,
      licensing: 'paid',
      verified: true,
      verificationBadges: ['verified-playbook'],
      featured: true,
    },
    {
      id: 'asset-campaign-framework',
      workspaceId: 'ndxbook',
      title: 'CAMPAIGN ENGINE FRAMEWORK · STAT-FORWARD',
      category: 'marketing-systems',
      creatorOrg: 'NDXBOOK',
      organization: 'NDXBOOK',
      description: 'Money Monday · Truth Tuesday · page strategy linkage · distribution handoff · Labs experiments',
      version: '1.2.0',
      rating: 4.6,
      downloads: 534,
      activeCompanies: 9,
      performancePct: 86,
      reviewCount: 22,
      compatibilityPct: 84,
      lastUpdated: '2026-06-10',
      inheritanceCompatible: true,
      knowledgeMaturityPct: 85,
      licensing: 'community-edition',
      verified: true,
      verificationBadges: ['verified-playbook'],
      featured: false,
    },
    {
      id: 'asset-creator-program',
      workspaceId: 'ndxbook',
      title: 'CREATOR AMBASSADOR PROGRAM TEMPLATE',
      category: 'creator-programs',
      creatorOrg: 'NDXBOOK',
      organization: 'NDXBOOK',
      description: 'Creator marketplace integration · alignment scoring · deal pipeline · career graph · academy modules',
      version: '1.0.0',
      rating: 4.5,
      downloads: 189,
      activeCompanies: 4,
      performancePct: 82,
      reviewCount: 11,
      compatibilityPct: 90,
      lastUpdated: '2026-07-01',
      inheritanceCompatible: true,
      knowledgeMaturityPct: 78,
      licensing: 'free',
      verified: false,
      verificationBadges: [],
      featured: false,
    },
    {
      id: 'asset-relationship-engine',
      workspaceId: 'studio-os',
      title: 'RELATIONSHIP ENGINE · NEXT BEST ACTION SYSTEM',
      category: 'automation-systems',
      creatorOrg: 'STUDIO OS',
      organization: 'STUDIO OS',
      description: 'Reader graph → active nurturing · recognition · loyalty intelligence · institutional learning loop',
      version: '1.0.0',
      rating: 4.8,
      downloads: 267,
      activeCompanies: 5,
      performancePct: 89,
      reviewCount: 15,
      compatibilityPct: 87,
      lastUpdated: '2026-07-04',
      inheritanceCompatible: true,
      knowledgeMaturityPct: 83,
      licensing: 'subscription',
      verified: true,
      verificationBadges: ['verified-automation'],
      featured: false,
    },
  ];

  return {
    dashboard: {
      summary:
        'ECOSYSTEM MARKETPLACE V1.0 — central exchange for organizational intelligence. Not an app store · organizational capability · outcomes over templates · wisdom compounds.',
      featuredAssets: 0,
      verifiedOrgs: 0,
      installedAssets: 0,
      avgCompatibility: 0,
      topContributors: 0,
      marketplaceHealthPct: 86,
    },
    activeWorkspaceId: 'ndxbook',
    assets,
    inheritanceIntegrations: [
      {
        assetId: 'asset-newsroom-playbook',
        modes: ['preview', 'simulation', 'compatibility-check', 'partial', 'full', 'custom'],
        recommendedMode: 'partial',
        compatibilityPct: 88,
        reasoning: 'High compatibility with media/content companies · partial inherit editorial + skip commerce modules',
        partialOptions: ['Editorial cadence', 'Page strategy linkage', 'CoS approval flows', 'Labs integration'],
      },
      {
        assetId: 'asset-leadership-dna-vxd',
        modes: ['preview', 'simulation', 'compatibility-check', 'full', 'custom'],
        recommendedMode: 'full',
        compatibilityPct: 91,
        reasoning: 'Leadership DNA as conflict arbiter · full inherit recommended for new companies',
        partialOptions: ['Delegation modes', 'Soft approval thresholds', 'Escalation routing'],
      },
      {
        assetId: 'asset-creative-dna-fs',
        modes: ['preview', 'simulation', 'compatibility-check', 'partial', 'custom'],
        recommendedMode: 'custom',
        compatibilityPct: 76,
        reasoning: 'Luxury commerce DNA · custom blend for non-commerce companies · preview before install',
        partialOptions: ['Photography bible', 'PSA voice', 'Product presentation standards'],
      },
    ],
    compatibilitySimulations: [
      {
        id: 'sim-1',
        assetId: 'asset-newsroom-playbook',
        label: 'NEWSROOM PLAYBOOK · PARTIAL INHERIT',
        workflowConflicts: ['Approval threshold mismatch with existing Leadership DNA'],
        executiveOverlap: ['CoS editorial queue vs existing content director'],
        departmentOverlap: ['Marketing + Content editorial routing'],
        dnaCompatibilityPct: 88,
        knowledgeConflicts: ['Writing Bible tone vs Money Monday stat-forward override'],
        automationConflicts: ['Labs experiment cadence vs existing campaign calendar'],
        confidencePct: 87,
        adjustments: ['Set unified approval band in Leadership DNA', 'Assign single editorial queue owner', 'Run 7-day pilot before full activation'],
        readyToInstall: true,
      },
      {
        id: 'sim-2',
        assetId: 'asset-creative-dna-fs',
        label: 'CREATIVE DNA · CUSTOM BLEND',
        workflowConflicts: ['Luxury product QA vs media content velocity'],
        executiveOverlap: ['Creative director scope expansion'],
        departmentOverlap: ['Creative + Commerce product photography'],
        dnaCompatibilityPct: 76,
        knowledgeConflicts: ['PSA voice vs stat-forward editorial tone'],
        automationConflicts: ['Build-a-Wig preview pipeline not applicable'],
        confidencePct: 72,
        adjustments: ['Inherit photography bible only · skip commerce automation', 'Blend PSA voice with existing Writing Bible', 'Preview creative standards before activation'],
        readyToInstall: false,
      },
    ],
    assetEvolutions: [
      {
        assetId: 'asset-newsroom-playbook',
        versions: [
          { version: '2.4.1', date: '2026-06-15', summary: 'Labs integration · page strategy linkage' },
          { version: '2.3.0', date: '2026-04-01', summary: 'CoS approval flows · editorial QA gates' },
          { version: '2.0.0', date: '2026-01-15', summary: 'Campaign engine handoff · distribution calendar sync' },
        ],
        contributors: ['NDXBOOK Editorial', 'Studio Intelligence', '3 community reviewers'],
        knowledgeGrowthPct: 34,
        performanceTrend: '+12% adoption performance vs v2.3',
        communityFeedback: 'Best-in-class newsroom cadence · partial inherit highly recommended',
        adoptionCount: 12,
        intelligenceRecommendation: 'Recommend partial inherit for all media companies entering Studio OS',
      },
    ],
    contributions: [
      { id: 'contrib-1', contributorType: 'founder', contributorName: 'NDXBOOK', assetTitle: 'NEWSROOM PLAYBOOK v2.4', status: 'published', reviewNotes: 'Verified playbook · editorial excellence' },
      { id: 'contrib-2', contributorType: 'consultant', contributorName: 'ORG DESIGN PARTNER', assetTitle: 'EXECUTIVE TEAM TEMPLATE', status: 'review', reviewNotes: 'Pending verification · executive overlap check' },
      { id: 'contrib-3', contributorType: 'agency', contributorName: 'CREATIVE STUDIO X', assetTitle: 'BRAND SYSTEM STARTER', status: 'verified', reviewNotes: 'Verified creative system · quality standards met' },
    ],
    collaborations: [
      { id: 'collab-1', label: 'SHARED RESEARCH FRAMEWORK', organizations: ['NDXBOOK', 'FRONTAL SLAYER'], sharedAssetType: 'Knowledge assets', history: 'Cross-company stat-forward research methodology · 6 months collaborative development' },
      { id: 'collab-2', label: 'CREATOR NETWORK BRIDGE', organizations: ['NDXBOOK', 'STUDIO OS'], sharedAssetType: 'Creator programs', history: 'Ambassador program template · marketplace intelligence shared' },
    ],
    intelligenceRecs: [
      { id: 'rec-1', type: 'high-performing', assetId: 'asset-newsroom-playbook', label: 'NEWSROOM PLAYBOOK · HIGH PERFORMER', confidencePct: 94, expectedRoi: '3.2x editorial velocity · 91% performance', riskLevel: 'low', rationale: '12 active companies · 4.9 rating · partial inherit optimal for media' },
      { id: 'rec-2', type: 'org-upgrade', assetId: 'asset-leadership-dna-vxd', label: 'LEADERSHIP DNA · ORG UPGRADE', confidencePct: 91, expectedRoi: 'Unified approval · reduced founder bottleneck', riskLevel: 'low', rationale: 'Conflict arbiter for multi-source inheritance · 8 enterprise adoptions' },
      { id: 'rec-3', type: 'emerging-system', assetId: 'asset-relationship-engine', label: 'RELATIONSHIP ENGINE · EMERGING', confidencePct: 85, expectedRoi: 'Advocate pipeline +34% · retention lift', riskLevel: 'medium', rationale: 'New v1.0 · high compatibility with reader graph adopters' },
      { id: 'rec-4', type: 'risk', assetId: 'asset-creative-dna-fs', label: 'CREATIVE DNA · COMPATIBILITY RISK', confidencePct: 72, expectedRoi: 'Brand lift for commerce · limited for media-only', riskLevel: 'medium', rationale: '76% compatibility · custom blend required for non-commerce' },
    ],
    reputations: [
      { orgId: 'ndxbook', orgName: 'NDXBOOK', qualityPct: 94, innovationPct: 88, communityContributionPct: 91, supportPct: 86, knowledgeSharingPct: 92, collaborationPct: 85, assetPerformancePct: 91, reliabilityPct: 93, trustPct: 94, verified: true },
      { orgId: 'frontal-slayer', orgName: 'FRONTAL SLAYER', qualityPct: 92, innovationPct: 90, communityContributionPct: 78, supportPct: 88, knowledgeSharingPct: 80, collaborationPct: 82, assetPerformancePct: 88, reliabilityPct: 91, trustPct: 92, verified: true },
      { orgId: 'vxd', orgName: 'VXD', qualityPct: 89, innovationPct: 95, communityContributionPct: 72, supportPct: 84, knowledgeSharingPct: 86, collaborationPct: 76, assetPerformancePct: 94, reliabilityPct: 88, trustPct: 90, verified: true },
    ],
    installedAssets: [
      { id: 'inst-1', assetId: 'asset-leadership-dna-vxd', title: 'VXD LEADERSHIP DNA FRAMEWORK', installedAt: '2026-03-01', inheritanceMode: 'full', healthPct: 94, lastSync: '2026-07-04' },
      { id: 'inst-2', assetId: 'asset-campaign-framework', title: 'CAMPAIGN ENGINE FRAMEWORK', installedAt: '2026-05-15', inheritanceMode: 'partial', healthPct: 86, lastSync: '2026-07-03' },
    ],
    industryCollections: [
      { id: 'col-media', label: 'MEDIA & CONTENT EXCELLENCE', industry: 'Media · Digital publishing', assetIds: ['asset-newsroom-playbook', 'asset-campaign-framework', 'asset-creator-program'], description: 'Complete operating stack for media companies · newsroom to creator programs' },
      { id: 'col-commerce', label: 'LUXURY COMMERCE SYSTEMS', industry: 'Commerce · Luxury retail', assetIds: ['asset-creative-dna-fs'], description: 'Creative DNA · brand systems · customer experience for luxury commerce' },
      { id: 'col-leadership', label: 'ORGANIZATIONAL GENETICS STARTER', industry: 'Cross-industry', assetIds: ['asset-leadership-dna-vxd', 'asset-relationship-engine'], description: 'Leadership DNA + relationship intelligence for any company entering Studio OS' },
    ],
    crossCompanyLearnings: [
      { id: 'learn-1', category: 'workflow', insight: 'Partial inherit + 7-day pilot reduces activation conflicts by 62%', anonymized: true, adoptionCount: 8 },
      { id: 'learn-2', category: 'approval', insight: 'Unified Leadership DNA approval band eliminates 89% of workflow conflicts in multi-source blends', anonymized: true, adoptionCount: 6 },
      { id: 'learn-3', category: 'campaign', insight: 'Campaign framework + distribution engine handoff improves reach by 28% vs standalone campaigns', anonymized: true, adoptionCount: 9 },
      { id: 'learn-4', category: 'relationship', insight: 'Relationship engine adoption after reader graph increases advocate pipeline 3x', anonymized: false, adoptionCount: 5 },
    ],
    selectedAssetId: 'asset-newsroom-playbook',
  };
}

export function bootstrapEcosystemMarketplacePlatform(): void {
  bootstrapEcosystemMarketplaceStore(buildEcosystemMarketplaceSeed());
}
