import { bootstrapOrganizationalMaturityModelStore } from './store';
import type { OrganizationalMaturityModelStore } from './types';

export function buildOrganizationalMaturityModelSeed(): Partial<OrganizationalMaturityModelStore> {
  return {
    companyName: 'NDXBOOK',
    activeWorkspaceId: 'ndxbook',
    dashboard: {
      summary:
        'ORGANIZATIONAL MATURITY MODEL V1.0 — master progression system · NDXBOOK at SCALE stage · readiness before enterprise advancement.',
      maturityScorePct: 74,
      confidencePct: 81,
      currentStageLabel: 'SCALE',
      nextMilestone: 'ENTERPRISE',
      readinessPct: 68,
      autonomyLevel: 3,
      campusStage: 'CREATIVE HEADQUARTERS → EXECUTIVE HEADQUARTERS',
    },
    organizationalStages: [
      { id: 'idea', label: 'IDEA', description: 'Vision exists · validation has not occurred', current: false, completed: true },
      { id: 'validation', label: 'VALIDATION', description: 'Customer discovery · research · market testing · initial learning', current: false, completed: true },
      { id: 'launch', label: 'LAUNCH', description: 'Products launch · first customers · first workflows · first knowledge assets', current: false, completed: true },
      { id: 'growth', label: 'GROWTH', description: 'Consistent revenue · team expansion · executive systems · community growth', current: false, completed: true },
      { id: 'scale', label: 'SCALE', description: 'Multiple departments · organizational intelligence · executive council · cross-functional orchestration', current: true, completed: false },
      { id: 'enterprise', label: 'ENTERPRISE', description: 'Multi-product · international expansion · advanced governance · multiple leadership layers', current: false, completed: false },
      { id: 'holding-company', label: 'HOLDING COMPANY', description: 'Multiple companies · shared executives · shared knowledge · portfolio campus', current: false, completed: false },
      { id: 'legacy', label: 'LEGACY', description: 'Institutional wisdom · succession planning · future leadership · organizational preservation', current: false, completed: false },
    ],
    maturityDimensions: [
      { id: 'md-1', dimension: 'Leadership maturity', scorePct: 78, readiness: 'ready' },
      { id: 'md-2', dimension: 'Knowledge maturity', scorePct: 82, readiness: 'advanced' },
      { id: 'md-3', dimension: 'Operational maturity', scorePct: 71, readiness: 'developing' },
      { id: 'md-4', dimension: 'Relationship maturity', scorePct: 76, readiness: 'ready' },
      { id: 'md-5', dimension: 'Customer maturity', scorePct: 69, readiness: 'developing' },
      { id: 'md-6', dimension: 'Brand maturity', scorePct: 85, readiness: 'advanced' },
      { id: 'md-7', dimension: 'Technology maturity', scorePct: 64, readiness: 'developing' },
      { id: 'md-8', dimension: 'Financial maturity', scorePct: 58, readiness: 'emerging' },
      { id: 'md-9', dimension: 'Community maturity', scorePct: 72, readiness: 'ready' },
      { id: 'md-10', dimension: 'Governance maturity', scorePct: 80, readiness: 'ready' },
    ],
    adaptiveExperience: [
      { id: 'ae-1', area: 'UI complexity', currentLevel: 'Moderate · executive panels visible', adaptsTo: 'Scale stage · full C-suite active' },
      { id: 'ae-2', area: 'Executive participation', currentLevel: 'Full C-suite + Executive Council', adaptsTo: 'Scale readiness · council synthesis active' },
      { id: 'ae-3', area: 'Recommended workflows', currentLevel: 'Cross-functional orchestration', adaptsTo: 'OWF active · 5 coordinated workflows' },
      { id: 'ae-4', area: 'Organizational autonomy', currentLevel: 'OAF Level 3 · trusted execution', adaptsTo: 'Earned through trust score 86%' },
      { id: 'ae-5', area: 'Governance', currentLevel: 'Constitutional safeguards active', adaptsTo: 'OGS V1.0 · invisible stewardship' },
      { id: 'ae-6', area: 'Reporting & dashboards', currentLevel: 'Executive + maturity dashboards', adaptsTo: 'Scale complexity · not enterprise overhead' },
      { id: 'ae-7', area: 'Architect studios', currentLevel: 'All four architects active', adaptsTo: 'Brand · experience · digital · growth maturity earned' },
      { id: 'ae-8', area: 'Campus evolution', currentLevel: 'Creative headquarters · 68% to executive HQ', adaptsTo: 'Campus progression tied to maturity' },
      { id: 'ae-9', area: 'Organizational intelligence', currentLevel: 'Full OI · wisdom compounding', adaptsTo: 'Scale stage intelligence depth' },
    ],
    executiveReadiness: [
      { id: 'er-1', stage: 'Idea', executive: 'Chief of Staff', status: 'active', rationale: 'Foundational coordination · earned at day one' },
      { id: 'er-2', stage: 'Idea', executive: 'Business Architect', status: 'active', rationale: 'Organizational blueprint · structure before scale' },
      { id: 'er-3', stage: 'Validation', executive: 'Brand Architect', status: 'active', rationale: 'Brand identity emerging · editorial DNA forming' },
      { id: 'er-4', stage: 'Validation', executive: 'Experience Architect', status: 'active', rationale: 'Customer journey mapping · trust gates designed' },
      { id: 'er-5', stage: 'Launch', executive: 'Chief Brand Officer', status: 'active', rationale: 'Brand integrity guardian · stat-forward consistency' },
      { id: 'er-6', stage: 'Launch', executive: 'Chief Experience Officer', status: 'active', rationale: 'Customer trust protector · onboarding gates active' },
      { id: 'er-7', stage: 'Growth', executive: 'Chief Digital Officer', status: 'active', rationale: 'Digital quality · platform reliability earned' },
      { id: 'er-8', stage: 'Growth', executive: 'Chief Growth Officer', status: 'active', rationale: 'Sustainable growth · relationship metrics over vanity' },
      { id: 'er-9', stage: 'Scale', executive: 'Chief Technology Officer', status: 'active', rationale: 'Engineering resilience · auth refactor critical path' },
      { id: 'er-10', stage: 'Scale', executive: 'Executive Council', status: 'active', rationale: 'Cross-functional wisdom · healthy disagreement culture' },
      { id: 'er-11', stage: 'Enterprise', executive: 'Future executive roles', status: 'future', rationale: 'Not ready · onboarding gates must clear first' },
      { id: 'er-12', stage: 'Holding company', executive: 'Portfolio leadership', status: 'not-ready', rationale: 'Requires multi-company maturity · Studio OS portfolio stage' },
    ],
    autonomyProgression: [
      { id: 'ap-1', level: 'Observation', description: 'System observes · learns patterns · no autonomous action', earned: true, current: false },
      { id: 'ap-2', level: 'Guided recommendations', description: 'Executives recommend · founder decides', earned: true, current: false },
      { id: 'ap-3', level: 'Assisted execution', description: 'Prepare actions · founder approves before execution', earned: true, current: false },
      { id: 'ap-4', level: 'Trusted execution', description: 'Execute within governance boundaries · OAF Level 3', earned: true, current: true, changeReason: 'Trust score 86% · onboarding gates enforced · governance active' },
      { id: 'ap-5', level: 'Cross-functional autonomy', description: 'Coordinated autonomous workflows across C-suite', earned: false, current: false, changeReason: 'Requires enterprise readiness · onboarding score > 85' },
      { id: 'ap-6', level: 'Organizational stewardship', description: 'Full trusted stewardship · founder visibility preserved', earned: false, current: false },
    ],
    campusProgression: [
      { id: 'cp-1', campus: 'Founder studio', description: 'Day one · possibility · founder workspace', current: false, completed: true },
      { id: 'cp-2', campus: 'Innovation loft', description: 'First product · early team · knowledge wall grows', current: false, completed: true },
      { id: 'cp-3', campus: 'Creative headquarters', description: 'Brand identity · experience atelier · newsroom', current: true, completed: false },
      { id: 'cp-4', campus: 'Executive headquarters', description: 'Leadership maturity · executive council · strategy observatory', current: false, completed: false },
      { id: 'cp-5', campus: 'Innovation campus', description: 'Multiple products · creator pavilion · innovation lab', current: false, completed: false },
      { id: 'cp-6', campus: 'Global campus', description: 'International expansion · relationship center · global commons', current: false, completed: false },
      { id: 'cp-7', campus: 'Organizational institute', description: 'Knowledge institute · legacy hall · teaching', current: false, completed: false },
      { id: 'cp-8', campus: 'Legacy campus', description: 'Decades of intentional leadership · living monument', current: false, completed: false },
    ],
    organizationalAssessments: [
      { id: 'oa-1', domain: 'Leadership', scorePct: 78, confidence: 85, strength: 'Full C-suite active · executive council operational', opportunity: 'Enterprise leadership layers not yet earned' },
      { id: 'oa-2', domain: 'Operations', scorePct: 71, confidence: 79, strength: 'OWF cross-functional orchestration · 5 active workflows', opportunity: 'Onboarding friction · Step 3 simplification needed' },
      { id: 'oa-3', domain: 'Knowledge', scorePct: 82, confidence: 88, strength: 'Writing DNA · Memory Bible · institutional learning active', opportunity: 'Creator marketplace knowledge automation pending' },
      { id: 'oa-4', domain: 'Technology', scorePct: 64, confidence: 72, strength: 'Platform operational · live preview pipeline active', opportunity: 'Auth refactor · security infrastructure debt' },
      { id: 'oa-5', domain: 'Customer relationships', scorePct: 69, confidence: 76, strength: 'Reader graph · relationship engine · trust gates designed', opportunity: 'Onboarding score below enterprise threshold' },
      { id: 'oa-6', domain: 'Brand', scorePct: 85, confidence: 91, strength: 'Stat-forward editorial · CBO guardian active · zero generic templates', opportunity: 'Creator marketplace brand dilution risk if automated' },
      { id: 'oa-7', domain: 'Community', scorePct: 72, confidence: 80, strength: 'Spotlight program · belonging over volume', opportunity: 'Scale community moderation governance' },
      { id: 'oa-8', domain: 'Governance', scorePct: 80, confidence: 86, strength: 'OGS constitutional · OAF Level 3 · trust preserved', opportunity: 'Enterprise governance layers not yet required' },
      { id: 'oa-9', domain: 'Financial readiness', scorePct: 58, confidence: 65, strength: 'Revenue growing · relationship-driven acquisition', opportunity: 'Paid acquisition blocked · financial maturity emerging' },
      { id: 'oa-10', domain: 'Organizational resilience', scorePct: 76, confidence: 82, strength: 'OSI continuous improvement · blind spots documented', opportunity: 'Premature GTM pressure risk · trust gates enforced' },
    ],
    growthRoadmap: {
      currentStage: 'SCALE',
      nextStage: 'ENTERPRISE',
      readinessPct: 68,
      remainingRequirements: [
        'Onboarding score > 85 before enterprise GTM',
        'Auth refactor complete · technology maturity threshold',
        'Financial readiness above emerging · sustainable unit economics',
        'Creator marketplace quality gates automated safely',
        'Executive council enterprise governance patterns established',
      ],
      recommendedPriorities: [
        'Complete onboarding simplification sprint · CEO-led',
        'CTO auth refactor · security trust infrastructure',
        'Trust-before-scale GTM gates · founder review only after readiness',
        'Document scale-stage governance precedents in OGS',
        'Campus progression to executive headquarters at 85% maturity',
      ],
      dependencies: [
        'Customer maturity → onboarding gates',
        'Technology maturity → auth refactor',
        'Financial maturity → sustainable growth metrics',
        'Governance maturity → enterprise approval patterns',
      ],
      futureExecutives: [
        'Future enterprise executive roles · not yet recommended',
        'Portfolio leadership · holding company stage only',
      ],
    },
    companyOnboarding: [
      { id: 'co-1', signal: 'Website analysis', finding: 'Stat-forward editorial · Writing DNA evident · trust-first positioning', generated: 'Brand maturity score · editorial genome seed' },
      { id: 'co-2', signal: 'Product analysis', finding: 'Reader platform · onboarding funnel · live preview pipeline', generated: 'Customer maturity · technology maturity assessment' },
      { id: 'co-3', signal: 'Customer signals', finding: 'Engaged reader base · relationship-driven growth · advocacy emerging', generated: 'Relationship maturity · community maturity scores' },
      { id: 'co-4', signal: 'Team & operations', finding: 'Full C-suite · executive council · cross-functional orchestration', generated: 'Leadership maturity · scale stage classification' },
      { id: 'co-5', signal: 'Knowledge assets', finding: 'Memory Bible · Writing DNA · institutional learning active', generated: 'Company genome · knowledge graph · maturity model' },
      { id: 'co-6', signal: 'Campus assessment', finding: 'Creative headquarters active · executive HQ progression at 68%', generated: 'Campus starting point · evolution roadmap' },
    ],
    oiMaturityIntegration: [
      { id: 'oi-1', evaluation: 'GTM Phase 1 pressure before onboarding gates cleared', recommendation: 'Slow down · trust-before-scale enforced', action: 'slow-down' },
      { id: 'oi-2', evaluation: 'Executive systems maturing appropriately for scale stage', recommendation: 'Maintain current executive participation', action: 'maintain' },
      { id: 'oi-3', evaluation: 'Knowledge compounding accelerating · OSI learning active', recommendation: 'Accelerate institutional knowledge capture', action: 'accelerate' },
      { id: 'oi-4', evaluation: 'Creator marketplace automation risk if quality gates bypassed', recommendation: 'Strengthen governance before advancing', action: 'strengthen' },
      { id: 'oi-5', evaluation: 'Brand integrity strong · culture preserved through growth', recommendation: 'Preserve stat-forward editorial culture', action: 'maintain' },
    ],
    recommendedNextSteps: [
      'Complete onboarding gate before enterprise stage advancement',
      'Advance campus to executive headquarters when maturity reaches 85%',
      'Document scale-stage autonomy earned rationale in OAF',
      'OI continuous evaluation before any maturity stage promotion',
    ],
    futureOpportunities: [
      'Master operating framework governing every Studio OS recommendation',
      'Portfolio-wide maturity comparison across holding company stage',
      'Predictive readiness scoring before executive recommendations',
    ],
  };
}

export function bootstrapOrganizationalMaturityModelPlatform(): void {
  bootstrapOrganizationalMaturityModelStore(buildOrganizationalMaturityModelSeed());
}
