/** P0.VR.3G — Experience page abstraction on design manifest */
export const DESIGN_ROUTE_MANIFEST_VERSION = '3.3.0';
export const DESIGN_ROUTE_MANIFEST_SCHEMA_VERSION = 'studio-world-design-route-manifest@3.3';
/** Prior — P0.VR.3G */
export const DESIGN_ROUTE_MANIFEST_SCHEMA_V3_2 = 'studio-world-design-route-manifest@3.2';
/** Prior schemas */
export const DESIGN_ROUTE_MANIFEST_SCHEMA_V3_1 = 'studio-world-design-route-manifest@3.1';
export const DESIGN_ROUTE_MANIFEST_SCHEMA_V3 = 'studio-world-design-route-manifest@3';
export const DESIGN_ROUTE_MANIFEST_SCHEMA_V2 = 'studio-world-design-route-manifest@2';
export const DESIGN_ROUTE_MANIFEST_SCHEMA_V1 = 'studio-world-design-route-manifest@1';
export const PROJECT_PAGE_SET_SCHEMA_VERSION = 'studio-world-project-page-set@2';
export const EXPERIENCE_PAGE_SET_SCHEMA_VERSION = 'studio-world-experience-page-set@1';

export const EXPERIENCE_PAGE_ABSTRACTION_CONFIDENCE_LEVELS = ['HIGH', 'MEDIUM', 'LOW'] as const;

export const EXPERIENCE_PAGE_TYPES = [
  'PUBLIC_PAGE',
  'WORKFLOW_PAGE',
  'PORTAL_PAGE',
  'WORKSPACE_PAGE',
  'IMMERSIVE_PAGE',
  'DETAIL_PAGE',
  'MISSING_PAGE',
] as const;

export const MATERIAL_SCREEN_STEP_TYPES = [
  'ENTRY',
  'SELECTION',
  'CONFIGURATION',
  'REVIEW',
  'COMPLETION',
  'DETAIL',
  'OTHER',
] as const;

export const PROJECT_WEBSITE_EXPERIENCE_CLASSES = [
  'PUBLIC_WEBSITE',
  'CUSTOMER_FLOW',
  'COMMERCE_FLOW',
  'ACCOUNT_FLOW',
  'AUTH_FLOW',
  'MEMBERSHIP_FLOW',
  'PORTAL_FLOW',
  'CLIENT_WORKFLOW',
  'CONTENT_EXPERIENCE',
  'IMMERSIVE_EXPERIENCE',
  'SUPPORT_FLOW',
  'FOUNDER_WORKSPACE',
  'ADMIN_INTERNAL',
  'SYSTEM_INTERNAL',
  'DEV_ONLY',
  'HISTORICAL',
] as const;

export const PRIMARY_EXPERIENCE_CLASSES = [
  'PUBLIC_WEBSITE',
  'CUSTOMER_FLOW',
  'COMMERCE_FLOW',
  'ACCOUNT_FLOW',
  'AUTH_FLOW',
  'MEMBERSHIP_FLOW',
  'PORTAL_FLOW',
  'CLIENT_WORKFLOW',
  'CONTENT_EXPERIENCE',
  'IMMERSIVE_EXPERIENCE',
  'SUPPORT_FLOW',
] as const;

export const COMPILED_PAGE_STATUSES = [
  'IMPLEMENTED',
  'IMPLEMENTED_PARTIAL',
  'IMPLEMENTATION_MISSING',
  'REFERENCE_MISSING',
  'REFERENCE_CANONICAL',
  'NEEDS_REBUILD',
  'INHERITS_FAMILY_REFERENCE',
  'ASSET_ONLY',
  'STATE_DERIVED',
  'CONTENT_ONLY',
  'DATA_ONLY',
  'BLOCKED',
] as const;

export const PAGE_COMPILATION_CONFIDENCE_LEVELS = ['HIGH', 'MEDIUM', 'LOW'] as const;

export const CUSTOMER_JOURNEY_STAGES = [
  'ENTRY',
  'DISCOVERY',
  'CONSIDERATION',
  'CONFIGURATION',
  'CONVERSION',
  'ACCOUNT',
  'RETENTION',
  'SUPPORT',
] as const;

export const MANIFEST_ARTIFACT_FILENAME = 'studio-world-design-route-manifest.json';
export const MANIFEST_ARTIFACT_RELATIVE_PATH = `public/studio-world/${MANIFEST_ARTIFACT_FILENAME}`;

export const VIEWPORT_CLASSES = ['MOBILE', 'TABLET', 'DESKTOP'] as const;
export const OPTIONAL_VIEWPORT_CLASSES = ['ULTRAWIDE', 'CUSTOM'] as const;

export const DEFAULT_VIEWPORT_DIMENSIONS = {
  MOBILE: { referenceWidth: 390, referenceHeight: 844 },
  TABLET: { referenceWidth: 834, referenceHeight: 1194 },
  DESKTOP: { referenceWidth: 1440, referenceHeight: 900 },
  ULTRAWIDE: { referenceWidth: 1920, referenceHeight: 1080 },
} as const;

export const ROUTE_FAMILIES = [
  'MARKETING',
  'COMMERCE',
  'ACCOUNT',
  'ONBOARDING',
  'WORKSPACE',
  'TOOLS',
  'CONTENT',
  'ADMIN',
  'SUPPORT',
  'OTHER',
] as const;

export const DESIGN_ROUTE_PRIORITIES = [
  'CRITICAL',
  'PRIMARY',
  'SECONDARY',
  'SUPPORTING',
  'INTERNAL',
] as const;

export const DESIGNABLE_SURFACE_CLASSES = [
  'FOUNDER_DESIGNABLE',
  'SYSTEM_INTERNAL',
  'DEV_ONLY',
  'TEST_ONLY',
  'DEPRECATED',
] as const;

export const ROUTE_REACHABILITY_CLASSES = [
  'NAV_REACHABLE',
  'PROGRAMMATIC_REACHABLE',
  'DYNAMIC_INSTANCE_REACHABLE',
  'WORKFLOW_REACHABLE',
  'AUTH_GATED_REACHABLE',
  'DEEP_LINK_SUPPORTED',
  'NOTIFICATION_REACHABLE',
  'STATE_MACHINE_REACHABLE',
  'ADMIN_REACHABLE',
  'TEST_ONLY',
  'LEGACY',
  'SUPERSEDED',
  'TRUE_ORPHAN',
  'UNKNOWN',
] as const;

export const ROUTE_ENTRY_EVIDENCE_TYPES = [
  'STATIC_LINK',
  'NAV_CONFIG',
  'NAVIGATE_CALL',
  'LOCATION_ASSIGNMENT',
  'ROUTER_PUSH',
  'CTA_HANDLER',
  'PRODUCT_CARD_ROUTE',
  'DYNAMIC_SLUG_GENERATOR',
  'WORKFLOW_TRANSITION',
  'AUTH_REDIRECT',
  'NOTIFICATION_LINK',
  'DEEP_LINK_REGISTRY',
  'STATE_MACHINE_TRANSITION',
  'TEST_FIXTURE',
  'MANUAL_ENTRY_ALLOWED',
  'REDIRECT_TARGET',
  'PARENT_ROUTE',
  'IMMERSIVE_TRANSITION',
] as const;

export const ROUTE_ALIAS_CLASSES = ['CANONICAL', 'ALIAS', 'LEGACY', 'SUPERSEDED'] as const;

export const REFERENCE_NECESSITY_CLASSES = [
  'UNIQUE_REFERENCE_REQUIRED',
  'SHARED_FAMILY_REFERENCE',
  'VIEWPORT_SPECIFIC_REFERENCE_REQUIRED',
  'STATE_DERIVED',
  'CONTENT_ONLY_VARIANT',
  'ASSET_ONLY_VARIANT',
  'DATA_ONLY_VARIANT',
  'NO_NEW_REFERENCE_REQUIRED',
  'UNKNOWN_REVIEW_REQUIRED',
] as const;

export const DESIGN_FAMILY_CONFIDENCE_LEVELS = ['HIGH', 'MEDIUM', 'LOW'] as const;

export const DESIGN_FAMILY_STATUSES = ['ACTIVE', 'PROPOSED_MERGE', 'SPLIT', 'FOUNDER_REVIEW_REQUIRED'] as const;

export const INHERITANCE_STATUSES = [
  'INHERITS_FAMILY',
  'SCREEN_OVERRIDE',
  'VIEWPORT_OVERRIDE',
  'FOUNDER_REVIEW_REQUIRED',
  'NO_REFERENCE',
] as const;

export const REFERENCE_AUTHORITY_LEVELS = [
  'SCREEN_OVERRIDE',
  'VIEWPORT_OVERRIDE',
  'FAMILY_REFERENCE',
  'NONE',
] as const;

export const FAILURE_TAXONOMY = [
  'FAIL_PROJECT_DISCOVERY_INCOMPLETE',
  'FAIL_ROUTER_ROUTE_OMITTED',
  'FAIL_LINK_TARGET_NOT_AUDITED',
  'FAIL_DEPENDENCY_ROUTE_MISSING',
  'FAIL_ROUTE_ORPHANED',
  'FAIL_ROUTE_DUPLICATE_UNKNOWN_AUTHORITY',
  'FAIL_VIEWPORT_COVERAGE_UNKNOWN',
  'FAIL_REFERENCE_COVERAGE_UNKNOWN',
  'FAIL_IMPLEMENTATION_COVERAGE_UNKNOWN',
  'FAIL_MOBILE_DESKTOP_CONFLATED',
  'FAIL_TABLET_CONFLATED_WITH_MOBILE',
  'FAIL_OUTDATED_REFERENCE_ACTIVE',
  'FAIL_ROUTE_MANIFEST_STALE',
  'FAIL_CROSS_PROJECT_ROUTE_LEAK',
  'FAIL_DESIGNABLE_ROUTE_NOT_VISIBLE_IN_DESIGN',
  'FAIL_FALSE_ORPHAN_CLASSIFICATION',
  'FAIL_STATIC_LINK_ONLY_REACHABILITY',
  'FAIL_PROGRAMMATIC_NAVIGATION_NOT_SCANNED',
  'FAIL_DYNAMIC_ROUTE_NOT_NORMALIZED',
  'FAIL_AUTH_ROUTE_MARKED_ORPHAN',
  'FAIL_WORKFLOW_CHILD_MARKED_ORPHAN',
  'FAIL_DEEP_LINK_MARKED_ORPHAN',
  'FAIL_IMPLEMENTATION_ROUTE_SHOWN_AS_DESIGN_SCREEN_UNNECESSARILY',
  'FAIL_ROUTE_FAMILY_OVER_COLLAPSED',
  'FAIL_REFERENCE_LOST_DURING_SCREEN_NORMALIZATION',
  'FAIL_REFERENCE_FAMILY_CONFLICT_AUTO_MERGED',
  'FAIL_SCREEN_GENERATION_WITH_VALID_FAMILY_REFERENCE',
  'FAIL_DESIGN_FAMILY_OVER_COLLAPSE',
  'FAIL_DESIGN_FAMILY_UNDER_COLLAPSE',
  'FAIL_CONTENT_ONLY_VARIANT_MARKED_UNIQUE',
  'FAIL_ASSET_ONLY_VARIANT_MARKED_UNIQUE',
  'FAIL_STATE_VARIANT_MARKED_FULL_REFERENCE_REQUIRED',
  'FAIL_VIEWPORT_REFERENCE_NECESSITY_CONFLATED',
  'FAIL_LOW_CONFIDENCE_FAMILY_AUTO_APPROVED',
  'FAIL_REFERENCE_FAMILY_CONFLICT_AUTO_RESOLVED',
  'FAIL_SCREEN_OVERRIDE_IGNORED',
  'FAIL_PAF_ASSET_VARIANT_CAUSES_PAGE_REFERENCE_DUPLICATION',
  'FAIL_DESIGN_SCREEN_PROMOTED_TO_PAGE_BY_DEFAULT',
  'FAIL_ROUTE_INSTANCE_PROMOTED_TO_PRIMARY_PAGE',
  'FAIL_STATE_PROMOTED_TO_PRIMARY_PAGE',
  'FAIL_WORKFLOW_NODE_PROMOTED_TO_PRIMARY_PAGE',
  'FAIL_INTERNAL_ROUTE_LEAKED_TO_PRIMARY_EXPERIENCE',
  'FAIL_MATERIAL_SCREEN_COLLAPSED_INCORRECTLY',
  'FAIL_DISTINCT_EXPERIENCES_OVER_MERGED',
  'FAIL_SITE00_P0_VR_3D_PRIMARY_SCOPE_REGRESSION',
  'FAIL_SCREENSHOT_BACKFILL_USES_RAW_SCREEN_SET',
  'FAIL_REFERENCE_BATCH_USES_RAW_SCREEN_SET',
  'FAIL_EXPERIENCE_OVERRIDE_LOST_ON_RECOMPILE',
  'FAIL_FOUNDER_OVERRIDE_IGNORED',
  'FAIL_OVERRIDE_CONFLICT_SILENTLY_DROPPED',
  'FAIL_INTERNAL_PAGE_REMAINS_PRIMARY',
  'FAIL_CUSTOMER_PAGE_AUTO_DEMOTED_INCORRECTLY',
  'FAIL_AIO_CONTENT_INSTANCE_REMAINS_PRIMARY_PAGE',
  'FAIL_AIO_DISTINCT_SERVICE_OVER_MERGED',
  'FAIL_SITE00_PRIMARY_SET_REGRESSION',
  'FAIL_NDXBOOK_INTENTIONAL_SCREEN_OVER_COLLAPSED',
  'FAIL_SCREENSHOT_PLAN_USES_UNCURATED_SET',
  'FAIL_REFERENCE_PLAN_USES_UNCURATED_SET',
  'FAIL_CURATION_VERSION_MISSING',
  'FAIL_CURATION_ACTION_NOT_PERSISTED',
  'FAIL_CURATION_BUTTON_NO_OP',
  'FAIL_SPLIT_OVERRIDE_NOT_APPLIED',
  'FAIL_MERGE_OVERRIDE_NOT_APPLIED',
  'FAIL_CURATION_RECEIPT_MISSING',
  'FAIL_LOCK_WITH_UNRESOLVED_BLOCKER',
  'FAIL_LOCK_VERSION_MISSING',
  'FAIL_LOCKED_PROJECT_NOT_MARKED_STALE_AFTER_SOURCE_CHANGE',
  'FAIL_FS_INTERNAL_ROUTE_REPROMOTED',
  'FAIL_AIO_APPROVED_INSTANCE_REPROMOTED',
  'FAIL_STUDIO_WORLD_NOT_AUDITED',
  'FAIL_CAPTURE_PLAN_INCLUDES_SITE00',
  'FAIL_CAPTURE_PLAN_INCLUDES_NDXBOOK',
  'FAIL_CAPTURE_PLAN_USES_REVIEWING_PROJECT',
  'FAIL_REPORTING_DENOMINATOR_INCONSISTENT',
] as const;

/** P0.VR.3H-FSBW — Missing route completion */
export const FSBW_MISSING_ROUTE_COMPLETION_SPRINT = 'P0.VR.3H-FSBW';
export const FSBW_COMPOSER_PAGE_REGISTRY_RELATIVE_PATH = 'public/studio-world/fsbw-composer-page-registry.json';

export const FSBW_OWNED_PROJECT_IDS = [
  'frontal-slayer',
  'studio-world',
  'all-in-one-enterprise',
] as const;

export const EXTERNAL_REPO_OWNED_PROJECT_IDS = ['site00', 'ndxbook'] as const;

export const MISSING_PAGE_COMPLETION_MODES = [
  'FAMILY_DERIVED_SIMPLE',
  'STRUCTURAL_COMPLEX',
  'CREATIVE_COMPLEX',
  'FUNCTIONAL_COMPLEX',
  'UNKNOWN_REVIEW_REQUIRED',
] as const;

export const CONTENT_PROVENANCE_SOURCES = [
  'SOURCE_CANON',
  'SOURCE_EXISTING_ROUTE',
  'SOURCE_DATABASE',
  'SOURCE_PROJECT_DOC',
  'COMPOSER_INFERRED',
  'CONTENT_REQUIRED',
] as const;

export const PAGE_AUTHOR_TYPES = ['COMPOSER', 'MIXED', 'FOUNDER'] as const;
export const PAGE_REVIEW_STATUSES = ['UNREVIEWED', 'IN_REVIEW', 'CHANGES_REQUESTED', 'APPROVED_FOR_RELEASE'] as const;
export const PAGE_PUBLISH_STATUSES = ['PREVIEW_ONLY', 'LIVE'] as const;
export const REVIEW_DIMENSIONS = ['VISUAL', 'CONTENT', 'FUNCTION'] as const;
export const COMPOSER_DRAFT_SNAPSHOT_LABEL = 'CURRENT · COMPOSER DRAFT';
export const FAMILY_SOURCE_SNAPSHOT_LABEL = 'FAMILY SOURCE · EXISTING IMPLEMENTATION';
export const COMPOSER_DERIVED_DRAFT_LABEL = 'CURRENT · COMPOSER DERIVED DRAFT';

/** P0.VR.3E — persistent implementation snapshot storage authority */
export const P0_VR_3E_SNAPSHOT_AUTHORITY = 'P0.VR.3E';

/** P0.VR.3L-FSBW — Family-derived missing target workflow */
export const FSBW_FAMILY_DERIVATION_SPRINT = 'P0.VR.3L-FSBW';
/** P0.VR.3L.1-FSBW — Voice Lab execution + founder review readiness */
export const FSBW_VOICE_LAB_EXECUTION_SPRINT = 'P0.VR.3L.1-FSBW';
export const VOICE_LAB_TARGET_ID = 'studio-world:missing:character-lab:voice-lab';
export const DEFAULT_SHELL_PROPAGATION_SCOPE = 'TARGET_ONLY' as const;

export const FAMILY_DERIVATION_FAILURES = [
  'FAIL_TAB_TARGET_PROMOTED_TO_PAGE',
  'FAIL_INSTANCE_TARGET_PROMOTED_TO_PAGE',
  'FAIL_MASS_CAPTURE_REQUIRED_BEFORE_DERIVATION',
  'FAIL_CROSS_PROJECT_SHELL_PROPAGATION',
  'FAIL_UNEXPLAINED_FAMILY_DRIFT',
  'FAIL_REFERENCE_CONFLICT_ON_PROPAGATION',
  'FAIL_SHELL_PROPAGATION_WITHOUT_APPROVAL',
] as const;
