/** P0.VR.3B — Reachability normalization + design screen registry */
export const DESIGN_ROUTE_MANIFEST_VERSION = '2.0.0';
export const DESIGN_ROUTE_MANIFEST_SCHEMA_VERSION = 'studio-world-design-route-manifest@2';
/** Prior schema for diff/migration */
export const DESIGN_ROUTE_MANIFEST_SCHEMA_V1 = 'studio-world-design-route-manifest@1';

export const MANIFEST_ARTIFACT_FILENAME = 'studio-world-design-route-manifest.json';
export const MANIFEST_ARTIFACT_RELATIVE_PATH = `public/studio-world/${MANIFEST_ARTIFACT_FILENAME}`;

export const VIEWPORT_CLASSES = ['MOBILE', 'TABLET', 'DESKTOP'] as const;
export const OPTIONAL_VIEWPORT_CLASSES = ['ULTRAWIDE', 'CUSTOM'] as const;

export const DEFAULT_VIEWPORT_DIMENSIONS = {
  MOBILE: { referenceWidth: 390, referenceHeight: 844 },
  TABLET: { referenceWidth: 834, referenceHeight: 1194 },
  DESKTOP: { referenceWidth: 1440, referenceHeight: 900 },
  ULTRAWIDE: { referenceWidth: 1920, referenceHeight: 1080 },
} as const;

export const ROUTE_FAMILIES = [
  'MARKETING',
  'COMMERCE',
  'ACCOUNT',
  'ONBOARDING',
  'WORKSPACE',
  'TOOLS',
  'CONTENT',
  'ADMIN',
  'SUPPORT',
  'OTHER',
] as const;

export const DESIGN_ROUTE_PRIORITIES = [
  'CRITICAL',
  'PRIMARY',
  'SECONDARY',
  'SUPPORTING',
  'INTERNAL',
] as const;

export const DESIGNABLE_SURFACE_CLASSES = [
  'FOUNDER_DESIGNABLE',
  'SYSTEM_INTERNAL',
  'DEV_ONLY',
  'TEST_ONLY',
  'DEPRECATED',
] as const;

export const ROUTE_REACHABILITY_CLASSES = [
  'NAV_REACHABLE',
  'PROGRAMMATIC_REACHABLE',
  'DYNAMIC_INSTANCE_REACHABLE',
  'WORKFLOW_REACHABLE',
  'AUTH_GATED_REACHABLE',
  'DEEP_LINK_SUPPORTED',
  'NOTIFICATION_REACHABLE',
  'STATE_MACHINE_REACHABLE',
  'ADMIN_REACHABLE',
  'TEST_ONLY',
  'LEGACY',
  'SUPERSEDED',
  'TRUE_ORPHAN',
  'UNKNOWN',
] as const;

export const ROUTE_ENTRY_EVIDENCE_TYPES = [
  'STATIC_LINK',
  'NAV_CONFIG',
  'NAVIGATE_CALL',
  'LOCATION_ASSIGNMENT',
  'ROUTER_PUSH',
  'CTA_HANDLER',
  'PRODUCT_CARD_ROUTE',
  'DYNAMIC_SLUG_GENERATOR',
  'WORKFLOW_TRANSITION',
  'AUTH_REDIRECT',
  'NOTIFICATION_LINK',
  'DEEP_LINK_REGISTRY',
  'STATE_MACHINE_TRANSITION',
  'TEST_FIXTURE',
  'MANUAL_ENTRY_ALLOWED',
  'REDIRECT_TARGET',
  'PARENT_ROUTE',
  'IMMERSIVE_TRANSITION',
] as const;

export const ROUTE_ALIAS_CLASSES = ['CANONICAL', 'ALIAS', 'LEGACY', 'SUPERSEDED'] as const;

export const FAILURE_TAXONOMY = [
  'FAIL_PROJECT_DISCOVERY_INCOMPLETE',
  'FAIL_ROUTER_ROUTE_OMITTED',
  'FAIL_LINK_TARGET_NOT_AUDITED',
  'FAIL_DEPENDENCY_ROUTE_MISSING',
  'FAIL_ROUTE_ORPHANED',
  'FAIL_ROUTE_DUPLICATE_UNKNOWN_AUTHORITY',
  'FAIL_VIEWPORT_COVERAGE_UNKNOWN',
  'FAIL_REFERENCE_COVERAGE_UNKNOWN',
  'FAIL_IMPLEMENTATION_COVERAGE_UNKNOWN',
  'FAIL_MOBILE_DESKTOP_CONFLATED',
  'FAIL_TABLET_CONFLATED_WITH_MOBILE',
  'FAIL_OUTDATED_REFERENCE_ACTIVE',
  'FAIL_ROUTE_MANIFEST_STALE',
  'FAIL_CROSS_PROJECT_ROUTE_LEAK',
  'FAIL_DESIGNABLE_ROUTE_NOT_VISIBLE_IN_DESIGN',
  'FAIL_FALSE_ORPHAN_CLASSIFICATION',
  'FAIL_STATIC_LINK_ONLY_REACHABILITY',
  'FAIL_PROGRAMMATIC_NAVIGATION_NOT_SCANNED',
  'FAIL_DYNAMIC_ROUTE_NOT_NORMALIZED',
  'FAIL_AUTH_ROUTE_MARKED_ORPHAN',
  'FAIL_WORKFLOW_CHILD_MARKED_ORPHAN',
  'FAIL_DEEP_LINK_MARKED_ORPHAN',
  'FAIL_IMPLEMENTATION_ROUTE_SHOWN_AS_DESIGN_SCREEN_UNNECESSARILY',
  'FAIL_ROUTE_FAMILY_OVER_COLLAPSED',
  'FAIL_REFERENCE_LOST_DURING_SCREEN_NORMALIZATION',
  'FAIL_REFERENCE_FAMILY_CONFLICT_AUTO_MERGED',
] as const;
