import type { SlayTip } from '../types';

/**
 * DEV-ONLY presentation density — never shipped in production builds.
 * Demonstrates Slay Tips collection layout when the canonical catalog is sparse.
 */
const DEMO_THUMB = '/assets/NOIR/blanco-thumb.png';

const demoPage = (heading: string, body: string) => ({
  id: 'dev-page-1',
  order: 1,
  layout: 'tip' as const,
  heading,
  body,
  imageUrl: DEMO_THUMB,
});

export const SLAY_TIP_LEARN_DENSITY_DEMOS: SlayTip[] = [
  {
    id: 'slay-tip-dev-density-dont-overpluck',
    slug: 'dev-dont-overpluck',
    title: 'DO NOT OVERPLUCK THE HAIRLINE',
    publicTitle: "DON'T OVERPLUCK",
    previewCopy: 'Density loss usually starts with one aggressive pass.',
    subtitle: 'SLAY TIP · DEV DENSITY',
    shortDescription: 'Density loss usually starts with one aggressive pass.',
    pillar: 'lace',
    format: 'scrapbook',
    slayTicketCost: 0,
    published: true,
    readTime: '1 MIN',
    thumbnailUrl: DEMO_THUMB,
    coverImageUrl: DEMO_THUMB,
    pages: [demoPage('DEV', 'Placeholder scrapbook page.')],
  },
  {
    id: 'slay-tip-dev-density-melt-check',
    slug: 'dev-melt-check',
    title: 'MELT CHECK BEFORE YOU STEP OUT',
    publicTitle: 'MELT CHECK BEFORE YOU STEP OUT',
    previewCopy: 'Three mirror angles catch what the bathroom light hides.',
    subtitle: 'SLAY TIP · DEV DENSITY',
    shortDescription: 'Three mirror angles catch what the bathroom light hides.',
    pillar: 'install',
    format: 'scrapbook',
    slayTicketCost: 1,
    published: true,
    readTime: '2 MIN',
    thumbnailUrl: DEMO_THUMB,
    coverImageUrl: DEMO_THUMB,
    pages: [demoPage('DEV', 'Placeholder scrapbook page.')],
  },
  {
    id: 'slay-tip-dev-density-lace-not-dirty',
    slug: 'dev-lace-not-dirty',
    title: 'YOUR LACE IS NOT DIRTY',
    publicTitle: 'YOUR LACE ISN\'T DIRTY',
    previewCopy: 'Discoloration and product buildup are not the same problem.',
    subtitle: 'SLAY TIP · DEV DENSITY',
    shortDescription: 'Discoloration and product buildup are not the same problem.',
    pillar: 'care',
    format: 'scrapbook',
    slayTicketCost: 0,
    published: true,
    readTime: '1 MIN',
    thumbnailUrl: DEMO_THUMB,
    coverImageUrl: DEMO_THUMB,
    pages: [demoPage('DEV', 'Placeholder scrapbook page.')],
  },
  {
    id: 'slay-tip-dev-density-low-heat',
    slug: 'dev-low-heat',
    title: 'LOW HEAT LONG LIFE',
    publicTitle: 'LOW HEAT. LONG LIFE.',
    previewCopy: 'Fiber memory breaks down faster than most people expect.',
    subtitle: 'SLAY TIP · DEV DENSITY',
    shortDescription: 'Fiber memory breaks down faster than most people expect.',
    pillar: 'care',
    format: 'scrapbook',
    slayTicketCost: 0,
    published: true,
    readTime: '2 MIN',
    thumbnailUrl: DEMO_THUMB,
    coverImageUrl: DEMO_THUMB,
    pages: [demoPage('DEV', 'Placeholder scrapbook page.')],
  },
  {
    id: 'slay-tip-dev-density-brush-ends',
    slug: 'dev-brush-ends',
    title: 'BRUSH FROM THE ENDS',
    publicTitle: 'BRUSH FROM THE ENDS',
    previewCopy: 'Start where tangles cost you the least hair.',
    subtitle: 'SLAY TIP · DEV DENSITY',
    shortDescription: 'Start where tangles cost you the least hair.',
    pillar: 'styling',
    format: 'scrapbook',
    slayTicketCost: 0,
    published: true,
    readTime: '1 MIN',
    thumbnailUrl: DEMO_THUMB,
    coverImageUrl: DEMO_THUMB,
    pages: [demoPage('DEV', 'Placeholder scrapbook page.')],
  },
  {
    id: 'slay-tip-dev-density-night-routine',
    slug: 'dev-night-routine',
    title: 'NIGHTTIME ROUTINE',
    publicTitle: 'NIGHTTIME ROUTINE',
    previewCopy: 'What you do before sleep sets tomorrow\'s lace behavior.',
    subtitle: 'SLAY TIP · DEV DENSITY',
    shortDescription: 'What you do before sleep sets tomorrow\'s lace behavior.',
    pillar: 'after-care',
    format: 'scrapbook',
    slayTicketCost: 1,
    published: true,
    readTime: '3 MIN',
    thumbnailUrl: DEMO_THUMB,
    coverImageUrl: DEMO_THUMB,
    pages: [demoPage('DEV', 'Placeholder scrapbook page.')],
  },
  {
    id: 'slay-tip-dev-density-secure-sides',
    slug: 'dev-secure-sides',
    title: 'SECURE THE SIDES',
    publicTitle: 'SECURE THE SIDES',
    previewCopy: 'Lift at the temple often starts with tension, not glue.',
    subtitle: 'SLAY TIP · DEV DENSITY',
    shortDescription: 'Lift at the temple often starts with tension, not glue.',
    pillar: 'install',
    format: 'scrapbook',
    slayTicketCost: 1,
    published: true,
    readTime: '2 MIN',
    thumbnailUrl: DEMO_THUMB,
    coverImageUrl: DEMO_THUMB,
    pages: [demoPage('DEV', 'Placeholder scrapbook page.')],
  },
  {
    id: 'slay-tip-dev-density-keep-fresh',
    slug: 'dev-keep-fresh',
    title: 'KEEP IT FRESH',
    publicTitle: 'KEEP IT FRESH',
    previewCopy: 'Refresh without stripping the lace you just melted.',
    subtitle: 'SLAY TIP · DEV DENSITY',
    shortDescription: 'Refresh without stripping the lace you just melted.',
    pillar: 'after-care',
    format: 'scrapbook',
    slayTicketCost: 0,
    published: true,
    readTime: '1 MIN',
    thumbnailUrl: DEMO_THUMB,
    coverImageUrl: DEMO_THUMB,
    pages: [demoPage('DEV', 'Placeholder scrapbook page.')],
  },
  {
    id: 'slay-tip-dev-density-tone-match',
    slug: 'dev-tone-match',
    title: 'TONE MATCH CHECK',
    publicTitle: 'TONE MATCH CHECK',
    previewCopy: 'Swatch in the light you actually wear the unit in.',
    subtitle: 'SLAY TIP · DEV DENSITY',
    shortDescription: 'Swatch in the light you actually wear the unit in.',
    pillar: 'color',
    format: 'scrapbook',
    slayTicketCost: 1,
    published: true,
    readTime: '2 MIN',
    thumbnailUrl: DEMO_THUMB,
    coverImageUrl: DEMO_THUMB,
    pages: [demoPage('DEV', 'Placeholder scrapbook page.')],
  },
  {
    id: 'slay-tip-dev-density-part-line',
    slug: 'dev-part-line',
    title: 'PART LINE PRECISION',
    publicTitle: 'PART LINE PRECISION',
    previewCopy: 'A clean part reads luxury before anyone sees the lace.',
    subtitle: 'SLAY TIP · DEV DENSITY',
    shortDescription: 'A clean part reads luxury before anyone sees the lace.',
    pillar: 'styling',
    format: 'scrapbook',
    slayTicketCost: 0,
    published: true,
    readTime: '1 MIN',
    thumbnailUrl: DEMO_THUMB,
    coverImageUrl: DEMO_THUMB,
    pages: [demoPage('DEV', 'Placeholder scrapbook page.')],
  },
  {
    id: 'slay-tip-dev-density-glue-cure',
    slug: 'dev-glue-cure',
    title: 'GLUE CURE WINDOW',
    publicTitle: 'GLUE CURE WINDOW',
    previewCopy: 'Rushing the cure is the fastest way to lift mid-day.',
    subtitle: 'SLAY TIP · DEV DENSITY',
    shortDescription: 'Rushing the cure is the fastest way to lift mid-day.',
    pillar: 'lace',
    format: 'scrapbook',
    slayTicketCost: 1,
    published: true,
    readTime: '2 MIN',
    thumbnailUrl: DEMO_THUMB,
    coverImageUrl: DEMO_THUMB,
    pages: [demoPage('DEV', 'Placeholder scrapbook page.')],
  },
];
