import type { KnowledgeGraphEdge, KnowledgeGraphNode, KnowledgeGraphWorkflowMap } from './schema';
import {
  adminStudioBrandAssetsAssetFactoryPath,
  adminStudioGrowthNetworkPath,
  adminStudioLabsPath,
  adminStudioAiMediaNetworkPath,
  adminStudioTalentNetworkPath,
  adminStudioMarketplacePath,
  adminStudioBusinessModelEnginePath,
  adminStudioEcosystemPath,
  adminStudioGovernancePath,
  adminStudioVisionEnginePath,
  adminStudioMemoryBiblePath,
  adminStudioPhotographyBiblePath,
} from '../../utils/adminStudioRoutes';

/** Canonical cross-module nodes and pipeline relationships. */
export const SEED_GRAPH_NODES: KnowledgeGraphNode[] = [
  {
    id: 'node-creative-dna',
    name: 'CREATIVE DNA',
    type: 'feature',
    description: 'Locked prompt, display bust, and editorial reference that govern all product photography.',
    purpose: 'Single source of truth — products inherit rules instead of one-off image management.',
    route: adminStudioPhotographyBiblePath(),
    moduleId: 'photography-bible',
    relatedManualChapter: 'CHAPTER · PHOTOGRAPHY · CREATIVE DNA',
    manualSection: 'Product Photography',
    manualAnchor: 'creative-dna-v1',
    versionIntroduced: 'Milestone 22.5',
    status: 'live',
    searchKeywords: ['creative dna', 'approved prompt', 'display bust', 'what is creative dna'],
  },
  {
    id: 'node-master-hero',
    name: 'MASTER HERO PORTRAIT',
    type: 'asset-type',
    description: 'Approved Fal-generated master portrait per signature unit — input to Asset Factory.',
    purpose: 'Defines the canonical product image before background removal and smart crops.',
    moduleId: 'photography-bible',
    relatedManualChapter: 'CHAPTER · PHOTOGRAPHY · MASTER HERO',
    searchKeywords: ['master hero', 'hero portrait', 'generate master'],
  },
  {
    id: 'node-transparent-master',
    name: 'TRANSPARENT MASTER',
    type: 'asset-type',
    description: 'Background-removed PNG produced by Asset Factory from approved masters.',
    moduleId: 'brand-assets-asset-factory',
    searchKeywords: ['transparent master', 'background removal', 'cutout'],
  },
  {
    id: 'node-smart-asset-registry',
    name: 'SMART ASSET REGISTRY',
    type: 'module',
    description: 'Context-aware product images — wishlist, cart, checkout, email, and Build-A-Wig snapshots.',
    purpose: 'Delivers the correct variant image per surface without duplicate uploads.',
    route: adminStudioBrandAssetsAssetFactoryPath(),
    moduleId: 'brand-assets-asset-factory',
    relatedManualChapter: 'CHAPTER · SMART ASSETS · REGISTRY',
    versionIntroduced: 'Milestone 22',
    status: 'demo',
    searchKeywords: ['smart asset', 'cart images', 'where do cart images come from', 'fallback_used'],
  },
  {
    id: 'node-baw-snapshot',
    name: 'BUILD-A-WIG VISUAL SNAPSHOT',
    type: 'feature',
    description: 'Reads configured unit, resolves approved variant from Smart Asset Registry, falls back when missing.',
    purpose: 'Shows customer configuration accurately in cart and orders.',
    searchKeywords: ['build-a-wig snapshot', 'baw cart', 'variant lookup', 'fallback'],
  },
  {
    id: 'node-onboarding-tutorial',
    name: 'ONBOARDING TUTORIAL',
    type: 'customer-feature',
    description: 'Customer-facing Mansion Tour — teaches website features (not studio os).',
    purpose: 'Separate from admin Interactive Manual; shares tutorial-os architecture.',
    route: '/home/shop',
    moduleId: 'tutorial-os',
    relatedManualChapter: 'CHAPTER 0 · CUSTOMER ONBOARDING',
    searchKeywords: ['onboarding tutorial', 'mansion tour', 'customer tutorial'],
  },
  {
    id: 'node-written-manual',
    name: 'WRITTEN OPERATING MANUAL',
    type: 'manual-chapter',
    description: 'Future 300–500 page Frontal Slayer operating manual — methodology and deep reference.',
    purpose: 'Long-form docs cross-linked from every Interactive Manual node.',
    searchKeywords: ['written manual', 'owners manual', 'full chapter'],
  },
  {
    id: 'node-interactive-manual',
    name: 'STUDIO OS INTERACTIVE MANUAL',
    type: 'module',
    description: 'Admin live walkthroughs powered by the Knowledge Graph.',
    moduleId: 'knowledge-hub',
    searchKeywords: ['interactive manual', 'studio os manual', 'knowledge graph'],
  },
  {
    id: 'node-memory-bible',
    name: 'MEMORY BIBLE',
    type: 'module',
    description:
      'Curated institutional knowledge — founder profile, naming bible, decision log, workspace memory, and AI Context Builder.',
    purpose: 'studio os owns long-term context for agents, contractors, and team — not vendor chat history alone.',
    route: adminStudioMemoryBiblePath(),
    moduleId: 'memory-bible',
    relatedManualChapter: 'CHAPTER · MEMORY BIBLE · INSTITUTIONAL KNOWLEDGE',
    versionIntroduced: 'Milestone 25',
    status: 'live',
    searchKeywords: [
      'memory bible',
      'institutional knowledge',
      'naming bible',
      'decision log',
      'ai context builder',
      'founder profile',
      'cursor prompt standards',
    ],
  },
  {
    id: 'node-fallback-used',
    name: 'FALLBACK_USED STATUS',
    type: 'status',
    description: 'Smart Asset Registry could not resolve variant — displays safe fallback image.',
    purpose: 'Signals missing approved asset; check Photography Bible + Factory pipeline.',
    searchKeywords: ['fallback_used', 'what does fallback_used mean', 'missing variant'],
  },
  {
    id: 'node-workspace-creation-engine',
    name: 'WORKSPACE CREATION ENGINE',
    type: 'module',
    description: 'Blueprint-driven company provisioning — wizard, registry, executive teams, and promotion pipeline.',
    purpose: 'Launch entire companies from studio os without hardcoding each workspace.',
    route: '/admin/studio-os',
    moduleId: 'studio-os',
    relatedManualChapter: 'CHAPTER · WORKSPACE CREATION ENGINE',
    versionIntroduced: 'Milestone 26',
    status: 'live',
    searchKeywords: ['workspace creation', 'launch new company', 'blueprint', 'provisioning'],
  },
  {
    id: 'node-ai-media-pilot',
    name: 'AI MEDIA PILOT WORKSPACE',
    type: 'feature',
    description: 'Permanent pilot workspace — validates every studio os feature before Frontal Slayer promotion.',
    purpose: 'Reference environment for production testing and promotion pipeline.',
    route: '/admin/studio-os/workspace/ai-media/dashboard',
    moduleId: 'studio-os',
    versionIntroduced: 'Milestone 26',
    status: 'live',
    searchKeywords: ['ai media', 'pilot workspace', 'reference workspace'],
  },
  {
    id: 'node-ai-executive-team',
    name: 'AI EXECUTIVE TEAM',
    type: 'feature',
    description: 'Blueprint-provisioned specialized AI advisors inheriting Memory Bible, Creative DNA, and workflows.',
    purpose: 'Company-specific leadership — not generic chatbots.',
    moduleId: 'studio-os',
    versionIntroduced: 'Milestone 26',
    status: 'live',
    searchKeywords: ['executive team', 'chief content officer', 'ai executives', 'collaboration'],
  },
  {
    id: 'node-promotion-pipeline',
    name: 'PROMOTION PIPELINE',
    type: 'workflow',
    description: 'Develop → AI Media → test → approve → promote to Frontal Slayer → all workspaces.',
    purpose: 'Built-in feature lifecycle for studio os capabilities.',
    route: '/admin/studio-os/promotion-center',
    moduleId: 'studio-os',
    versionIntroduced: 'Milestone 26',
    status: 'live',
    searchKeywords: ['promotion center', 'pilot to production', 'frontal slayer promotion'],
  },
  {
    id: 'node-growth-network',
    name: 'GROWTH NETWORK',
    type: 'module',
    description:
      'Intelligent business growth ecosystem — growth profiles, opportunity engine, deal pipeline CRM, revenue center, and marketplaces.',
    purpose: 'Operating layer between businesses and opportunities — not a traditional talent agency.',
    route: adminStudioGrowthNetworkPath(),
    moduleId: 'growth-network',
    relatedManualChapter: 'CHAPTER · GROWTH NETWORK · BUSINESS GROWTH ECOSYSTEM',
    versionIntroduced: 'Milestone 27',
    status: 'live',
    searchKeywords: [
      'growth network',
      'partnerships',
      'opportunity engine',
      'deal pipeline',
      'revenue center',
      'growth score',
    ],
  },
  {
    id: 'node-opportunity-engine',
    name: 'OPPORTUNITY ENGINE',
    type: 'feature',
    description: 'Matches brand partnerships, affiliates, sponsorships, and collaborations to workspace growth profiles.',
    purpose: 'Continuous opportunity matching based on Memory Bible growth strategy and company DNA.',
    moduleId: 'growth-network',
    versionIntroduced: 'Milestone 27',
    status: 'live',
    searchKeywords: ['opportunity engine', 'brand partnership match', 'sponsorship opportunities'],
  },
  {
    id: 'node-deal-pipeline',
    name: 'DEAL PIPELINE CRM',
    type: 'workflow',
    description: 'Lead → qualified → meeting → proposal → negotiation → contract → campaign → deliverables → invoice → payment → renewal → completed.',
    purpose: 'Full partnership lifecycle for every opportunity in Growth Network.',
    moduleId: 'growth-network',
    versionIntroduced: 'Milestone 27',
    status: 'live',
    searchKeywords: ['deal pipeline', 'partnership crm', 'partnership lifecycle'],
  },
  {
    id: 'node-revenue-center',
    name: 'REVENUE CENTER',
    type: 'feature',
    description: 'Centralized revenue dashboard — brand deals, affiliates, platform payouts, products, and diversification score.',
    purpose: 'Track and forecast revenue across all channels for growth intelligence.',
    moduleId: 'growth-network',
    versionIntroduced: 'Milestone 27',
    status: 'live',
    searchKeywords: ['revenue center', 'revenue diversification', 'monthly revenue'],
  },
  {
    id: 'node-vision-engine',
    name: 'VISION ENGINE',
    type: 'module',
    description:
      'Studio OS cinematic presentation operating system — Vision Modes, Builder, Recorder, Share, Analytics. Internal only.',
    purpose: 'Generate immersive presentations from any workspace without separate decks or screen recordings.',
    route: adminStudioVisionEnginePath(),
    moduleId: 'vision-engine',
    relatedManualChapter: 'CHAPTER · VISION ENGINE · CINEMATIC PRESENTATIONS',
    versionIntroduced: 'Milestone 28',
    status: 'live',
    searchKeywords: [
      'vision engine',
      'vision mode',
      'presentation builder',
      'vision share',
      'vision recorder',
      'vision analytics',
    ],
  },
  {
    id: 'node-vision-share',
    name: 'VISION SHARE',
    type: 'feature',
    description: 'Secure interactive Vision Links — autoplay, narration, presenter mode, password protection.',
    purpose: 'Share cinematic presentations without exporting static videos.',
    moduleId: 'vision-engine',
    versionIntroduced: 'Milestone 28',
    status: 'live',
    searchKeywords: ['vision link', 'vision share', 'interactive presentation'],
  },
  {
    id: 'node-studio-os-labs',
    name: 'STUDIO OS LABS',
    type: 'module',
    description:
      'Research & experimentation division — Experiment Engine, performance tracking, learning engine, hook/thumbnail/caption intel, benchmarks, and promotion pipeline.',
    purpose: 'Every published asset becomes an experiment; platform learns from real production data — not analytics dashboards.',
    route: adminStudioLabsPath(),
    moduleId: 'labs',
    relatedManualChapter: 'CHAPTER · STUDIO OS LABS · EXPERIMENT ENGINE',
    versionIntroduced: 'Milestone 28',
    status: 'live',
    searchKeywords: [
      'studio os labs',
      'experiment engine',
      'learning engine',
      'hook library',
      'thumbnail intelligence',
      'benchmarks',
    ],
  },
  {
    id: 'node-experiment-engine',
    name: 'EXPERIMENT ENGINE',
    type: 'feature',
    description: 'Auto-creates unique experiment IDs on every publish — records topic, pillar, hook, script, voice, thumbnail, AI models, and DNA versions.',
    purpose: 'Operating system that gets smarter every time content is published.',
    moduleId: 'labs',
    versionIntroduced: 'Milestone 28',
    status: 'live',
    searchKeywords: ['experiment engine', 'published asset experiment', 'variable capture'],
  },
  {
    id: 'node-learning-engine',
    name: 'LEARNING ENGINE',
    type: 'feature',
    description: 'Generates insights from completed experiments — not raw metrics. Promotes discoveries to Memory Bible and Knowledge Graph.',
    purpose: 'Institutional intelligence from real business data.',
    moduleId: 'labs',
    versionIntroduced: 'Milestone 28',
    status: 'live',
    searchKeywords: ['learning engine', 'experiment insights', 'institutional memory'],
  },
  {
    id: 'node-ai-media-network',
    name: 'AI MEDIA NETWORK',
    type: 'module',
    description:
      'Digital media network — Company DNA, 5 evergreen pillars, 5 recurring shows (Money Monday–Future Friday), programming calendar, cross-platform publishing, monetization center.',
    purpose: 'Transform AI Media from content workspace into structured TV network + AI publishing company.',
    route: adminStudioAiMediaNetworkPath(),
    moduleId: 'ai-media-network',
    relatedManualChapter: 'CHAPTER · AI MEDIA NETWORK · DIGITAL MEDIA COMPANY',
    versionIntroduced: 'Milestone 29',
    status: 'live',
    searchKeywords: [
      'ai media network',
      'programming network',
      'money monday',
      'content pillars',
      'network calendar',
    ],
  },
  {
    id: 'node-programming-network',
    name: 'PROGRAMMING NETWORK',
    type: 'feature',
    description: 'Recurring shows with own branding, thumbnail style, intro/outro, host, Creative DNA, and Knowledge Graph nodes.',
    purpose: 'Replace random uploads with purposeful network programming.',
    moduleId: 'ai-media-network',
    versionIntroduced: 'Milestone 29',
    status: 'live',
    searchKeywords: ['programming network', 'money monday', 'truth tuesday', 'recurring shows'],
  },
  {
    id: 'node-talent-network',
    name: 'TALENT NETWORK',
    type: 'module',
    description:
      'Unified talent operating system — centralized registry for AI presenters and human creators. Casting, wardrobe, contracts, performance score, audience intelligence, character evolution.',
    purpose: 'Manage every personality in a workspace through one architecture regardless of talent type.',
    route: adminStudioTalentNetworkPath(),
    moduleId: 'talent-network',
    relatedManualChapter: 'CHAPTER · TALENT NETWORK · UNIFIED TALENT OS',
    versionIntroduced: 'Milestone 30',
    status: 'live',
    searchKeywords: [
      'talent network',
      'ai presenter',
      'human creator',
      'casting',
      'wardrobe manager',
      'talent score',
      'character evolution',
    ],
  },
  {
    id: 'node-talent-registry',
    name: 'TALENT REGISTRY',
    type: 'feature',
    description: 'Centralized talent profiles — display name, type, status, portfolio, contracts, availability, verified and onboarding status.',
    purpose: 'Single source of truth for AI and human talent in every workspace.',
    moduleId: 'talent-network',
    versionIntroduced: 'Milestone 30',
    status: 'live',
    searchKeywords: ['talent registry', 'talent profile', 'ai talent', 'human talent'],
  },
  {
    id: 'node-talent-maya-chen',
    name: 'MAYA CHEN',
    type: 'feature',
    description: 'AI presenter — Money Monday primary host. Finance credibility, business wardrobe, Voice A warm authority.',
    purpose: 'Recurring network host talent node linked to shows, campaigns, and Creative DNA.',
    moduleId: 'talent-network',
    versionIntroduced: 'Milestone 30',
    status: 'live',
    searchKeywords: ['maya chen', 'money monday host', 'ai presenter'],
  },
  {
    id: 'node-marketplace',
    name: 'MARKETPLACE',
    type: 'module',
    description:
      'Professional operating network — brands, creators, agencies, and service providers discover, collaborate, hire, and grow through lasting partnerships. Not a freelancer marketplace.',
    purpose: 'Connect businesses intelligently — relationship-first deal center, collaboration hubs, trust engine.',
    route: adminStudioMarketplacePath(),
    moduleId: 'marketplace',
    relatedManualChapter: 'CHAPTER · MARKETPLACE · BUSINESS ECOSYSTEM',
    versionIntroduced: 'Milestone 31',
    status: 'live',
    searchKeywords: [
      'marketplace',
      'deal center',
      'collaboration hub',
      'professional network',
      'business ecosystem',
    ],
  },
  {
    id: 'node-deal-center',
    name: 'DEAL CENTER',
    type: 'feature',
    description: 'Structured deal workflow — discovery through renewal with relationship history.',
    purpose: 'Every opportunity becomes a long-term partnership pipeline, not a one-off gig.',
    moduleId: 'marketplace',
    versionIntroduced: 'Milestone 31',
    status: 'live',
    searchKeywords: ['deal center', 'deal workflow', 'negotiation', 'contract', 'renewal'],
  },
  {
    id: 'node-collaboration-hub',
    name: 'COLLABORATION HUB',
    type: 'feature',
    description: 'Per-deal workspace — messages, files, deliverables, timelines, approvals, contracts, payments, AI recommendations.',
    purpose: 'Shared operating room for every business relationship.',
    moduleId: 'marketplace',
    versionIntroduced: 'Milestone 31',
    status: 'live',
    searchKeywords: ['collaboration hub', 'deal workspace', 'deliverables', 'activity feed'],
  },
  {
    id: 'node-business-model-engine',
    name: 'BUSINESS MODEL ENGINE',
    type: 'module',
    description:
      'Economic engine — membership tiers, workspace billing, usage, platform fees, wallets, royalties, asset marketplaces, affiliate engine, enterprise licensing, economic dashboard.',
    purpose: 'Diversified monetization aligned with ecosystem success — not a billing page alone.',
    route: adminStudioBusinessModelEnginePath(),
    moduleId: 'business-model-engine',
    relatedManualChapter: 'CHAPTER · BUSINESS MODEL ENGINE · ECONOMIC ENGINE',
    versionIntroduced: 'Milestone 32',
    status: 'live',
    searchKeywords: [
      'business model engine',
      'membership',
      'subscriptions',
      'royalties',
      'wallets',
      'platform fees',
      'enterprise licensing',
    ],
  },
  {
    id: 'node-membership-engine',
    name: 'MEMBERSHIP ENGINE',
    type: 'feature',
    description: 'Centralized membership — Free through Enterprise Plus. Unlocks capabilities across ecosystem, not just pages.',
    purpose: 'Tier-based capability gates for workspaces, AI, automation, marketplace, analytics, team seats.',
    moduleId: 'business-model-engine',
    versionIntroduced: 'Milestone 32',
    status: 'live',
    searchKeywords: ['membership', 'creator tier', 'enterprise plus', 'capabilities'],
  },
  {
    id: 'node-wallet-system',
    name: 'WALLET SYSTEM',
    type: 'feature',
    description: 'Participant wallets — earnings, pending payouts, credits, affiliate earnings, royalties, commissions.',
    purpose: 'Every participant tracks economic activity inside Studio OS.',
    moduleId: 'business-model-engine',
    versionIntroduced: 'Milestone 32',
    status: 'live',
    searchKeywords: ['wallet', 'payouts', 'earnings', 'credits'],
  },
  {
    id: 'node-studio-os-ecosystem',
    name: 'STUDIO OS ECOSYSTEM',
    type: 'module',
    description:
      'Business operating ecosystem — community blueprints, DNA, automations, executives, integrations. Install complete operating systems for specific business models.',
    purpose: 'Not an app store — companies build tools that help other companies succeed. Every published asset becomes a KG node.',
    route: adminStudioEcosystemPath(),
    moduleId: 'ecosystem',
    relatedManualChapter: 'CHAPTER · STUDIO OS ECOSYSTEM · BUSINESS OPERATING ECOSYSTEM',
    versionIntroduced: 'Milestone 33',
    status: 'live',
    searchKeywords: [
      'studio os ecosystem',
      'company blueprint',
      'install operating system',
      'publishing center',
      'creator center',
    ],
  },
  {
    id: 'node-publishing-center',
    name: 'PUBLISHING CENTER',
    type: 'feature',
    description: 'Creator workflow — draft → private testing → pilot → review → approved → published → updates → retired.',
    purpose: 'Every community-created asset passes quality, documentation, compatibility, and licensing review.',
    moduleId: 'ecosystem',
    versionIntroduced: 'Milestone 33',
    status: 'live',
    searchKeywords: ['publishing center', 'ecosystem review', 'asset publication'],
  },
  {
    id: 'node-installation-engine',
    name: 'INSTALLATION ENGINE',
    type: 'feature',
    description: 'Install ecosystem assets — verify compatibility, backup, install dependencies, update KG and Memory Bible, register version.',
    purpose: 'Users install complete business operating systems, not isolated plugins.',
    moduleId: 'ecosystem',
    versionIntroduced: 'Milestone 33',
    status: 'live',
    searchKeywords: ['installation engine', 'dependency engine', 'blueprint install'],
  },
  {
    id: 'node-eco-media-blueprint',
    name: 'DIGITAL MEDIA NETWORK BLUEPRINT',
    type: 'feature',
    description: 'Ecosystem asset — complete operating system for digital media company. 1,842 downloads.',
    purpose: 'Example ecosystem package — launch a media company from blueprint.',
    moduleId: 'ecosystem',
    versionIntroduced: 'Milestone 33',
    status: 'live',
    searchKeywords: ['media network blueprint', 'company blueprint', 'ecosystem asset'],
  },
  {
    id: 'node-studio-os-governance',
    name: 'STUDIO OS GOVERNANCE',
    type: 'module',
    description:
      'Trust, quality, compliance, moderation, verification, certification, AI governance, and ecosystem health — the platform constitution for responsible growth.',
    purpose: 'Governance is not punishment — every verified company, creator, blueprint, AI executive, and marketplace asset evaluated through transparent systems.',
    route: adminStudioGovernancePath(),
    moduleId: 'governance',
    relatedManualChapter: 'CHAPTER · STUDIO OS GOVERNANCE · PLATFORM CONSTITUTION',
    versionIntroduced: 'Milestone 34',
    status: 'live',
    searchKeywords: [
      'studio os governance',
      'trust engine',
      'verification center',
      'moderation',
      'platform constitution',
    ],
  },
  {
    id: 'node-trust-engine',
    name: 'TRUST ENGINE',
    type: 'feature',
    description: 'Dynamic trust scores for workspaces, creators, agencies, AI executives, blueprints, and ecosystem assets.',
    purpose: 'Account history, verification, completion, ratings, compliance, payments, disputes, quality, contributions.',
    moduleId: 'governance',
    versionIntroduced: 'Milestone 34',
    status: 'live',
    searchKeywords: ['trust score', 'participant trust', 'reputation trust'],
  },
  {
    id: 'node-verification-center',
    name: 'VERIFICATION CENTER',
    type: 'feature',
    description: 'Identity, business, workspace, creator, enterprise, portfolio, agency, developer verification — official badges.',
    purpose: 'Verified profiles receive official badges across the platform.',
    moduleId: 'governance',
    versionIntroduced: 'Milestone 34',
    status: 'live',
    searchKeywords: ['verification', 'verified creator', 'verified badge'],
  },
  {
    id: 'node-audit-center',
    name: 'AUDIT CENTER',
    type: 'feature',
    description: 'Permanent audit history — verification, certifications, payments, policy changes, governance actions, executive AI updates.',
    purpose: 'Every important platform event recorded in institutional knowledge graph.',
    moduleId: 'governance',
    versionIntroduced: 'Milestone 34',
    status: 'live',
    searchKeywords: ['audit center', 'audit history', 'compliance audit'],
  },
];

export const SEED_GRAPH_EDGES: KnowledgeGraphEdge[] = [
  { id: 'e-photo-contains-dna', fromId: 'photography-bible', toId: 'node-creative-dna', type: 'contains', label: 'CONTAINS' },
  { id: 'e-dna-defines-hero', fromId: 'node-creative-dna', toId: 'node-master-hero', type: 'generates', label: 'DEFINES' },
  { id: 'e-hero-feeds-factory', fromId: 'node-master-hero', toId: 'asset-factory', type: 'feeds', label: 'FEEDS' },
  { id: 'e-factory-creates-transparent', fromId: 'asset-factory', toId: 'node-transparent-master', type: 'creates' },
  { id: 'e-transparent-registry', fromId: 'node-transparent-master', toId: 'node-smart-asset-registry', type: 'updates' },
  { id: 'e-registry-displays-cart', fromId: 'node-smart-asset-registry', toId: 'node-baw-snapshot', type: 'displays' },
  { id: 'e-baw-used-by-orders', fromId: 'node-baw-snapshot', toId: 'node-smart-asset-registry', type: 'used-by', label: 'CART · CHECKOUT · ORDERS' },
  { id: 'e-tutorial-teaches-customer', fromId: 'tutorial-os', toId: 'node-onboarding-tutorial', type: 'teaches' },
  { id: 'e-manual-documents-interactive', fromId: 'node-written-manual', toId: 'node-interactive-manual', type: 'documented-by' },
  { id: 'e-interactive-documents-manual', fromId: 'node-interactive-manual', toId: 'node-written-manual', type: 'related-to' },
  { id: 'e-knowledge-contains-graph', fromId: 'knowledge-hub', toId: 'node-interactive-manual', type: 'contains' },
  { id: 'e-memory-bible-documents-platform', fromId: 'node-memory-bible', toId: 'memory-bible', type: 'documented-by', label: 'CURATED MEMORY' },
  { id: 'e-memory-links-manual', fromId: 'node-memory-bible', toId: 'node-interactive-manual', type: 'related-to', label: 'INTERACTIVE MANUAL' },
  { id: 'e-memory-links-dna-decision', fromId: 'node-memory-bible', toId: 'node-creative-dna', type: 'related-to', label: 'CREATIVE DNA DECISION' },
  { id: 'e-memory-links-factory', fromId: 'node-memory-bible', toId: 'node-smart-asset-registry', type: 'related-to', label: 'ASSET PIPELINE' },
  { id: 'e-knowledge-contains-memory', fromId: 'knowledge-hub', toId: 'node-memory-bible', type: 'contains' },
  { id: 'e-writing-rules-memory', fromId: 'node-memory-bible', toId: 'content-brain', type: 'feeds', label: 'WRITING RULES' },
  { id: 'e-registry-fallback', fromId: 'node-smart-asset-registry', toId: 'node-fallback-used', type: 'displays' },
  { id: 'e-brand-assets-photo', fromId: 'brand-assets', toId: 'photography-bible', type: 'contains' },
  { id: 'e-brand-assets-factory', fromId: 'brand-assets', toId: 'brand-assets-asset-factory', type: 'contains' },
  { id: 'e-asset-director-approval', fromId: 'asset-factory', toId: 'asset-director', type: 'requires-approval-from' },
  { id: 'e-director-publishes', fromId: 'asset-director', toId: 'publishing-queue', type: 'publishes-to' },
  { id: 'e-wce-provisions-ai-media', fromId: 'node-workspace-creation-engine', toId: 'node-ai-media-pilot', type: 'creates', label: 'PROVISIONS' },
  { id: 'e-wce-executive-team', fromId: 'node-workspace-creation-engine', toId: 'node-ai-executive-team', type: 'contains' },
  { id: 'e-ai-media-promotion', fromId: 'node-ai-media-pilot', toId: 'node-promotion-pipeline', type: 'feeds', label: 'PILOT TESTING' },
  { id: 'e-promotion-frontal', fromId: 'node-promotion-pipeline', toId: 'mission-control', type: 'related-to', label: 'PROMOTE TO FRONTAL SLAYER' },
  { id: 'e-executive-collab', fromId: 'node-ai-executive-team', toId: 'node-ai-media-pilot', type: 'related-to', label: 'CCO → CREATIVE → DISTRIBUTION' },
  { id: 'e-executive-memory', fromId: 'node-ai-executive-team', toId: 'node-memory-bible', type: 'inherits-from', label: 'MEMORY BIBLE' },
  { id: 'e-growth-profile-memory', fromId: 'node-growth-network', toId: 'node-memory-bible', type: 'inherits-from', label: 'GROWTH STRATEGY' },
  { id: 'e-growth-contains-opportunity', fromId: 'node-growth-network', toId: 'node-opportunity-engine', type: 'contains' },
  { id: 'e-growth-contains-pipeline', fromId: 'node-growth-network', toId: 'node-deal-pipeline', type: 'contains' },
  { id: 'e-growth-contains-revenue', fromId: 'node-growth-network', toId: 'node-revenue-center', type: 'contains' },
  { id: 'e-opportunity-pipeline', fromId: 'node-opportunity-engine', toId: 'node-deal-pipeline', type: 'feeds', label: 'QUALIFIED LEADS' },
  { id: 'e-pipeline-revenue', fromId: 'node-deal-pipeline', toId: 'node-revenue-center', type: 'feeds', label: 'CLOSED DEALS' },
  { id: 'e-growth-knowledge', fromId: 'node-growth-network', toId: 'node-interactive-manual', type: 'related-to', label: 'KNOWLEDGE GRAPH' },
  { id: 'e-ai-media-growth', fromId: 'node-ai-media-pilot', toId: 'node-growth-network', type: 'feeds', label: 'PILOT VALIDATION' },
  { id: 'e-audience-growth', fromId: 'audience-brain', toId: 'node-growth-network', type: 'feeds', label: 'AUDIENCE SIGNALS' },
  { id: 'e-vision-memory', fromId: 'node-vision-engine', toId: 'node-memory-bible', type: 'inherits-from', label: 'BRAND STORY' },
  { id: 'e-vision-contains-share', fromId: 'node-vision-engine', toId: 'node-vision-share', type: 'contains' },
  { id: 'e-vision-knowledge', fromId: 'node-vision-engine', toId: 'node-interactive-manual', type: 'related-to', label: 'KNOWLEDGE GRAPH' },
  { id: 'e-growth-vision', fromId: 'node-growth-network', toId: 'node-vision-engine', type: 'related-to', label: 'INVESTOR DEMOS' },
  { id: 'e-labs-memory', fromId: 'node-studio-os-labs', toId: 'node-memory-bible', type: 'inherits-from', label: 'INSTITUTIONAL LEARNINGS' },
  { id: 'e-labs-contains-experiment', fromId: 'node-studio-os-labs', toId: 'node-experiment-engine', type: 'contains' },
  { id: 'e-labs-contains-learning', fromId: 'node-studio-os-labs', toId: 'node-learning-engine', type: 'contains' },
  { id: 'e-labs-knowledge', fromId: 'node-studio-os-labs', toId: 'node-interactive-manual', type: 'related-to', label: 'KNOWLEDGE GRAPH' },
  { id: 'e-ai-media-labs', fromId: 'node-ai-media-pilot', toId: 'node-studio-os-labs', type: 'feeds', label: 'FIRST WORKSPACE PILOT' },
  { id: 'e-distribution-labs', fromId: 'publishing-queue', toId: 'node-experiment-engine', type: 'feeds', label: 'EVERY PUBLISH' },
  { id: 'e-audience-labs', fromId: 'audience-brain', toId: 'node-studio-os-labs', type: 'feeds', label: 'PERFORMANCE SIGNALS' },
  { id: 'e-experiment-learning', fromId: 'node-experiment-engine', toId: 'node-learning-engine', type: 'feeds', label: 'COMPLETED EXPERIMENTS' },
  { id: 'e-ai-media-network', fromId: 'node-ai-media-pilot', toId: 'node-ai-media-network', type: 'contains', label: 'NETWORK OPERATING MODEL' },
  { id: 'e-network-labs', fromId: 'node-ai-media-network', toId: 'node-studio-os-labs', type: 'feeds', label: 'EVERY EPISODE = EXPERIMENT' },
  { id: 'e-network-programming', fromId: 'node-ai-media-network', toId: 'node-programming-network', type: 'contains' },
  { id: 'e-network-memory', fromId: 'node-ai-media-network', toId: 'node-memory-bible', type: 'inherits-from', label: 'COMPANY DNA' },
  { id: 'e-network-knowledge', fromId: 'node-ai-media-network', toId: 'node-interactive-manual', type: 'related-to', label: 'KNOWLEDGE GRAPH' },
  { id: 'e-talent-network-memory', fromId: 'node-talent-network', toId: 'node-memory-bible', type: 'inherits-from', label: 'TALENT CONTEXT' },
  { id: 'e-talent-contains-registry', fromId: 'node-talent-network', toId: 'node-talent-registry', type: 'contains' },
  { id: 'e-talent-knowledge', fromId: 'node-talent-network', toId: 'node-interactive-manual', type: 'related-to', label: 'KNOWLEDGE GRAPH' },
  { id: 'e-talent-growth', fromId: 'node-growth-network', toId: 'node-talent-network', type: 'feeds', label: 'TALENT RECOMMENDATIONS' },
  { id: 'e-network-talent', fromId: 'node-ai-media-network', toId: 'node-talent-network', type: 'related-to', label: 'SHOW HOSTS' },
  { id: 'e-talent-labs', fromId: 'node-talent-network', toId: 'node-studio-os-labs', type: 'feeds', label: 'PERFORMANCE SIGNALS' },
  { id: 'e-talent-maya', fromId: 'node-talent-registry', toId: 'node-talent-maya-chen', type: 'contains' },
  { id: 'e-maya-programming', fromId: 'node-talent-maya-chen', toId: 'node-programming-network', type: 'related-to', label: 'MONEY MONDAY HOST' },
  { id: 'e-marketplace-memory', fromId: 'node-marketplace', toId: 'node-memory-bible', type: 'inherits-from', label: 'PARTNERSHIP CONTEXT' },
  { id: 'e-marketplace-contains-deal', fromId: 'node-marketplace', toId: 'node-deal-center', type: 'contains' },
  { id: 'e-marketplace-contains-collab', fromId: 'node-marketplace', toId: 'node-collaboration-hub', type: 'contains' },
  { id: 'e-marketplace-knowledge', fromId: 'node-marketplace', toId: 'node-interactive-manual', type: 'related-to', label: 'KNOWLEDGE GRAPH' },
  { id: 'e-talent-marketplace', fromId: 'node-talent-network', toId: 'node-marketplace', type: 'feeds', label: 'TALENT → PARTICIPANTS' },
  { id: 'e-growth-marketplace', fromId: 'node-growth-network', toId: 'node-marketplace', type: 'feeds', label: 'OPPORTUNITY → DEAL' },
  { id: 'e-deal-collab', fromId: 'node-deal-center', toId: 'node-collaboration-hub', type: 'contains', label: 'DEAL WORKSPACE' },
  { id: 'e-bme-memory', fromId: 'node-business-model-engine', toId: 'node-memory-bible', type: 'inherits-from', label: 'PRICING DECISIONS' },
  { id: 'e-bme-contains-membership', fromId: 'node-business-model-engine', toId: 'node-membership-engine', type: 'contains' },
  { id: 'e-bme-contains-wallet', fromId: 'node-business-model-engine', toId: 'node-wallet-system', type: 'contains' },
  { id: 'e-bme-knowledge', fromId: 'node-business-model-engine', toId: 'node-interactive-manual', type: 'related-to', label: 'KNOWLEDGE GRAPH' },
  { id: 'e-marketplace-bme', fromId: 'node-marketplace', toId: 'node-business-model-engine', type: 'feeds', label: 'MARKETPLACE REVENUE' },
  { id: 'e-growth-bme', fromId: 'node-growth-network', toId: 'node-business-model-engine', type: 'feeds', label: 'REVENUE SIGNALS' },
  { id: 'e-wallet-marketplace', fromId: 'node-wallet-system', toId: 'node-marketplace', type: 'related-to', label: 'DEAL PAYOUTS' },
  { id: 'e-ecosystem-memory', fromId: 'node-studio-os-ecosystem', toId: 'node-memory-bible', type: 'inherits-from', label: 'ASSET CONTEXT' },
  { id: 'e-ecosystem-contains-publishing', fromId: 'node-studio-os-ecosystem', toId: 'node-publishing-center', type: 'contains' },
  { id: 'e-ecosystem-contains-install', fromId: 'node-studio-os-ecosystem', toId: 'node-installation-engine', type: 'contains' },
  { id: 'e-ecosystem-knowledge', fromId: 'node-studio-os-ecosystem', toId: 'node-interactive-manual', type: 'related-to', label: 'KNOWLEDGE GRAPH' },
  { id: 'e-bme-ecosystem', fromId: 'node-business-model-engine', toId: 'node-studio-os-ecosystem', type: 'feeds', label: 'ASSET REVENUE' },
  { id: 'e-ecosystem-blueprint', fromId: 'node-publishing-center', toId: 'node-eco-media-blueprint', type: 'contains' },
  { id: 'e-governance-memory', fromId: 'node-studio-os-governance', toId: 'node-memory-bible', type: 'inherits-from', label: 'GOVERNANCE CONTEXT' },
  { id: 'e-governance-contains-trust', fromId: 'node-studio-os-governance', toId: 'node-trust-engine', type: 'contains' },
  { id: 'e-governance-contains-verification', fromId: 'node-studio-os-governance', toId: 'node-verification-center', type: 'contains' },
  { id: 'e-governance-contains-audit', fromId: 'node-studio-os-governance', toId: 'node-audit-center', type: 'contains' },
  { id: 'e-governance-knowledge', fromId: 'node-studio-os-governance', toId: 'node-interactive-manual', type: 'related-to', label: 'KNOWLEDGE GRAPH' },
  { id: 'e-governance-ecosystem', fromId: 'node-studio-os-governance', toId: 'node-studio-os-ecosystem', type: 'related-to', label: 'QUALITY REVIEW' },
  { id: 'e-governance-marketplace', fromId: 'node-studio-os-governance', toId: 'node-marketplace', type: 'related-to', label: 'MODERATION & TRUST' },
  { id: 'e-governance-bme', fromId: 'node-studio-os-governance', toId: 'node-business-model-engine', type: 'related-to', label: 'COMPLIANCE & PAYMENTS' },
  { id: 'e-eco-media-network', fromId: 'node-eco-media-blueprint', toId: 'node-ai-media-network', type: 'related-to', label: 'INSTALLED OS' },
  { id: 'e-install-kg', fromId: 'node-installation-engine', toId: 'node-interactive-manual', type: 'updates', label: 'KG NODES PER ASSET' },
];

export const SEED_GRAPH_WORKFLOWS: KnowledgeGraphWorkflowMap[] = [
  {
    id: 'wf-photography-pipeline',
    title: 'PHOTOGRAPHY PIPELINE',
    subtitle: 'Creative DNA → Master Hero → Factory → Smart Assets → Website',
    nodeIds: [
      'node-creative-dna',
      'node-master-hero',
      'asset-factory',
      'node-transparent-master',
      'node-smart-asset-registry',
      'brand-assets',
    ],
    moduleIds: ['photography-bible', 'asset-factory', 'brand-assets-asset-factory'],
  },
  {
    id: 'wf-baw-cart-snapshot',
    title: 'BUILD-A-WIG CART SNAPSHOT',
    subtitle: 'Configuration → Variant Lookup → Registry → Cart → Order',
    nodeIds: ['node-baw-snapshot', 'node-smart-asset-registry', 'node-fallback-used'],
    moduleIds: ['brand-assets-asset-factory', 'tutorial-os'],
  },
  {
    id: 'wf-rewards-customer',
    title: 'REWARDS WORKFLOW (CUSTOMER)',
    subtitle: 'Purchase → Points → Voucher → History → Checkout',
    nodeIds: ['node-onboarding-tutorial'],
    moduleIds: ['tutorial-os'],
  },
  {
    id: 'wf-tutorial-layering',
    title: 'TUTORIAL LAYERING',
    subtitle: 'Page → Feature → Widget → Action → Completion',
    nodeIds: ['node-onboarding-tutorial', 'tutorial-os', 'node-interactive-manual'],
    moduleIds: ['tutorial-os', 'knowledge-hub'],
  },
  {
    id: 'wf-institutional-memory',
    title: 'INSTITUTIONAL MEMORY',
    subtitle: 'Memory Bible → Naming · Decisions · Context Builder → AI Sessions',
    nodeIds: [
      'node-memory-bible',
      'memory-bible',
      'node-interactive-manual',
      'node-creative-dna',
      'node-smart-asset-registry',
    ],
    moduleIds: ['memory-bible', 'knowledge-hub', 'photography-bible', 'brand-assets-asset-factory'],
  },
  {
    id: 'wf-workspace-promotion',
    title: 'WORKSPACE PROMOTION LIFECYCLE',
    subtitle: 'Develop → AI Media Pilot → Test → Approve → Frontal Slayer → All Workspaces',
    nodeIds: [
      'node-workspace-creation-engine',
      'node-ai-media-pilot',
      'node-promotion-pipeline',
      'node-ai-executive-team',
      'mission-control',
    ],
    moduleIds: ['studio-os'],
  },
  {
    id: 'wf-growth-network',
    title: 'GROWTH NETWORK LIFECYCLE',
    subtitle: 'Memory Bible → Growth Profile → Opportunities → Deal Pipeline → Revenue → Knowledge Graph',
    nodeIds: [
      'node-memory-bible',
      'node-growth-network',
      'node-opportunity-engine',
      'node-deal-pipeline',
      'node-revenue-center',
      'node-interactive-manual',
    ],
    moduleIds: ['growth-network', 'memory-bible', 'knowledge-hub', 'audience-brain'],
  },
  {
    id: 'wf-vision-engine',
    title: 'VISION ENGINE LIFECYCLE',
    subtitle: 'Workspace Manifest → Vision Modes → Builder → Recorder → Share → Analytics',
    nodeIds: [
      'node-vision-engine',
      'node-vision-share',
      'node-memory-bible',
      'node-interactive-manual',
    ],
    moduleIds: ['vision-engine', 'memory-bible', 'knowledge-hub'],
  },
  {
    id: 'wf-studio-os-labs',
    title: 'STUDIO OS LABS LIFECYCLE',
    subtitle: 'Publish → Experiment → Performance → Learning → Recommendation → Promotion → Memory Bible',
    nodeIds: [
      'node-experiment-engine',
      'node-studio-os-labs',
      'node-learning-engine',
      'node-memory-bible',
      'node-interactive-manual',
      'node-ai-media-pilot',
    ],
    moduleIds: ['labs', 'memory-bible', 'knowledge-hub', 'distribution-network', 'audience-brain'],
  },
  {
    id: 'wf-ai-media-network',
    title: 'AI MEDIA NETWORK LIFECYCLE',
    subtitle: 'Company DNA → Pillars → Programming → Calendar → Publish → Labs → Monetization → Memory',
    nodeIds: [
      'node-ai-media-pilot',
      'node-ai-media-network',
      'node-programming-network',
      'node-experiment-engine',
      'node-studio-os-labs',
      'node-memory-bible',
    ],
    moduleIds: ['ai-media-network', 'labs', 'memory-bible', 'knowledge-hub', 'distribution-network'],
  },
  {
    id: 'wf-talent-network',
    title: 'TALENT NETWORK LIFECYCLE',
    subtitle: 'Registry → Cast → Produce → Perform → Score → Evolve → Growth Recommendations → Memory',
    nodeIds: [
      'node-talent-network',
      'node-talent-registry',
      'node-talent-maya-chen',
      'node-programming-network',
      'node-growth-network',
      'node-studio-os-labs',
      'node-memory-bible',
    ],
    moduleIds: ['talent-network', 'growth-network', 'labs', 'memory-bible', 'knowledge-hub', 'ai-media-network'],
  },
  {
    id: 'wf-marketplace',
    title: 'MARKETPLACE LIFECYCLE',
    subtitle: 'Discover → Match → Deal → Collaborate → Trust → Pay → Renew → Ecosystem Growth',
    nodeIds: [
      'node-marketplace',
      'node-deal-center',
      'node-collaboration-hub',
      'node-talent-network',
      'node-growth-network',
      'node-memory-bible',
      'node-interactive-manual',
    ],
    moduleIds: ['marketplace', 'talent-network', 'growth-network', 'memory-bible', 'knowledge-hub'],
  },
  {
    id: 'wf-business-model-engine',
    title: 'BUSINESS MODEL ENGINE LIFECYCLE',
    subtitle: 'Membership → Billing → Usage → Fees → Wallets → Royalties → Enterprise → Ecosystem Health',
    nodeIds: [
      'node-business-model-engine',
      'node-membership-engine',
      'node-wallet-system',
      'node-marketplace',
      'node-growth-network',
      'node-memory-bible',
      'node-interactive-manual',
    ],
    moduleIds: ['business-model-engine', 'marketplace', 'growth-network', 'memory-bible', 'knowledge-hub', 'talent-network'],
  },
  {
    id: 'wf-studio-os-ecosystem',
    title: 'STUDIO OS ECOSYSTEM LIFECYCLE',
    subtitle: 'Publish → Review → Install → Operate → Update → Reward Creators → Strengthen Platform',
    nodeIds: [
      'node-studio-os-ecosystem',
      'node-publishing-center',
      'node-installation-engine',
      'node-eco-media-blueprint',
      'node-business-model-engine',
      'node-memory-bible',
      'node-interactive-manual',
    ],
    moduleIds: ['ecosystem', 'business-model-engine', 'memory-bible', 'knowledge-hub', 'marketplace'],
  },
  {
    id: 'wf-studio-os-governance',
    title: 'STUDIO OS GOVERNANCE LIFECYCLE',
    subtitle: 'Trust → Verify → Review → Certify → Moderate → Appeal → Audit → Healthy Growth',
    nodeIds: [
      'node-studio-os-governance',
      'node-trust-engine',
      'node-verification-center',
      'node-audit-center',
      'node-studio-os-ecosystem',
      'node-marketplace',
      'node-business-model-engine',
      'node-memory-bible',
      'node-interactive-manual',
    ],
    moduleIds: ['governance', 'ecosystem', 'marketplace', 'business-model-engine', 'memory-bible', 'knowledge-hub'],
  },
];

/** Sub-module page guides merged into manual + graph builders. */
export const SUB_MODULE_GRAPH_NODES: KnowledgeGraphNode[] = [
  {
    id: 'photography-bible',
    name: 'PHOTOGRAPHY BIBLE',
    type: 'module',
    description: 'Locked product photography standards — Creative DNA, master heroes, and generation package.',
    purpose: 'Official visual rules every signature unit and derivative inherits.',
    route: adminStudioPhotographyBiblePath(),
    moduleId: 'photography-bible',
    relatedManualChapter: 'CHAPTER · PHOTOGRAPHY BIBLE',
    versionIntroduced: 'Milestone 22',
    status: 'live',
    searchKeywords: ['photography bible', 'product photography', 'master hero portrait'],
  },
  {
    id: 'brand-assets-asset-factory',
    name: 'PRODUCT ASSET FACTORY / SMART REGISTRY',
    type: 'module',
    description: 'Manufactures transparent masters and registers smart assets for every storefront context.',
    purpose: 'Pipeline from approved master to cart/checkout/email images.',
    route: adminStudioBrandAssetsAssetFactoryPath(),
    moduleId: 'brand-assets-asset-factory',
    relatedManualChapter: 'CHAPTER · SMART ASSET REGISTRY',
    status: 'demo',
    searchKeywords: ['smart asset registry', 'product asset factory', 'product crops'],
  },
];
