import type { KnowledgeGraphEdge, KnowledgeGraphNode, KnowledgeGraphWorkflowMap } from './schema';
import {
  adminStudioBrandAssetsAssetFactoryPath,
  adminStudioMemoryBiblePath,
  adminStudioPhotographyBiblePath,
} from '../../utils/adminStudioRoutes';

/** Canonical cross-module nodes and pipeline relationships. */
export const SEED_GRAPH_NODES: KnowledgeGraphNode[] = [
  {
    id: 'node-creative-dna',
    name: 'CREATIVE DNA',
    type: 'feature',
    description: 'Locked prompt, display bust, and editorial reference that govern all product photography.',
    purpose: 'Single source of truth — products inherit rules instead of one-off image management.',
    route: adminStudioPhotographyBiblePath(),
    moduleId: 'photography-bible',
    relatedManualChapter: 'CHAPTER · PHOTOGRAPHY · CREATIVE DNA',
    manualSection: 'Product Photography',
    manualAnchor: 'creative-dna-v1',
    versionIntroduced: 'Milestone 22.5',
    status: 'live',
    searchKeywords: ['creative dna', 'approved prompt', 'display bust', 'what is creative dna'],
  },
  {
    id: 'node-master-hero',
    name: 'MASTER HERO PORTRAIT',
    type: 'asset-type',
    description: 'Approved Fal-generated master portrait per signature unit — input to Asset Factory.',
    purpose: 'Defines the canonical product image before background removal and smart crops.',
    moduleId: 'photography-bible',
    relatedManualChapter: 'CHAPTER · PHOTOGRAPHY · MASTER HERO',
    searchKeywords: ['master hero', 'hero portrait', 'generate master'],
  },
  {
    id: 'node-transparent-master',
    name: 'TRANSPARENT MASTER',
    type: 'asset-type',
    description: 'Background-removed PNG produced by Asset Factory from approved masters.',
    moduleId: 'brand-assets-asset-factory',
    searchKeywords: ['transparent master', 'background removal', 'cutout'],
  },
  {
    id: 'node-smart-asset-registry',
    name: 'SMART ASSET REGISTRY',
    type: 'module',
    description: 'Context-aware product images — wishlist, cart, checkout, email, and Build-A-Wig snapshots.',
    purpose: 'Delivers the correct variant image per surface without duplicate uploads.',
    route: adminStudioBrandAssetsAssetFactoryPath(),
    moduleId: 'brand-assets-asset-factory',
    relatedManualChapter: 'CHAPTER · SMART ASSETS · REGISTRY',
    versionIntroduced: 'Milestone 22',
    status: 'demo',
    searchKeywords: ['smart asset', 'cart images', 'where do cart images come from', 'fallback_used'],
  },
  {
    id: 'node-baw-snapshot',
    name: 'BUILD-A-WIG VISUAL SNAPSHOT',
    type: 'feature',
    description: 'Reads configured unit, resolves approved variant from Smart Asset Registry, falls back when missing.',
    purpose: 'Shows customer configuration accurately in cart and orders.',
    searchKeywords: ['build-a-wig snapshot', 'baw cart', 'variant lookup', 'fallback'],
  },
  {
    id: 'node-onboarding-tutorial',
    name: 'ONBOARDING TUTORIAL',
    type: 'customer-feature',
    description: 'Customer-facing Mansion Tour — teaches website features (not studio os).',
    purpose: 'Separate from admin Interactive Manual; shares tutorial-os architecture.',
    route: '/home/shop',
    moduleId: 'tutorial-os',
    relatedManualChapter: 'CHAPTER 0 · CUSTOMER ONBOARDING',
    searchKeywords: ['onboarding tutorial', 'mansion tour', 'customer tutorial'],
  },
  {
    id: 'node-written-manual',
    name: 'WRITTEN OPERATING MANUAL',
    type: 'manual-chapter',
    description: 'Future 300–500 page Frontal Slayer operating manual — methodology and deep reference.',
    purpose: 'Long-form docs cross-linked from every Interactive Manual node.',
    searchKeywords: ['written manual', 'owners manual', 'full chapter'],
  },
  {
    id: 'node-interactive-manual',
    name: 'STUDIO OS INTERACTIVE MANUAL',
    type: 'module',
    description: 'Admin live walkthroughs powered by the Knowledge Graph.',
    moduleId: 'knowledge-hub',
    searchKeywords: ['interactive manual', 'studio os manual', 'knowledge graph'],
  },
  {
    id: 'node-memory-bible',
    name: 'MEMORY BIBLE',
    type: 'module',
    description:
      'Curated institutional knowledge — founder profile, naming bible, decision log, workspace memory, and AI Context Builder.',
    purpose: 'studio os owns long-term context for agents, contractors, and team — not vendor chat history alone.',
    route: adminStudioMemoryBiblePath(),
    moduleId: 'memory-bible',
    relatedManualChapter: 'CHAPTER · MEMORY BIBLE · INSTITUTIONAL KNOWLEDGE',
    versionIntroduced: 'Milestone 25',
    status: 'live',
    searchKeywords: [
      'memory bible',
      'institutional knowledge',
      'naming bible',
      'decision log',
      'ai context builder',
      'founder profile',
      'cursor prompt standards',
    ],
  },
  {
    id: 'node-fallback-used',
    name: 'FALLBACK_USED STATUS',
    type: 'status',
    description: 'Smart Asset Registry could not resolve variant — displays safe fallback image.',
    purpose: 'Signals missing approved asset; check Photography Bible + Factory pipeline.',
    searchKeywords: ['fallback_used', 'what does fallback_used mean', 'missing variant'],
  },
];

export const SEED_GRAPH_EDGES: KnowledgeGraphEdge[] = [
  { id: 'e-photo-contains-dna', fromId: 'photography-bible', toId: 'node-creative-dna', type: 'contains', label: 'CONTAINS' },
  { id: 'e-dna-defines-hero', fromId: 'node-creative-dna', toId: 'node-master-hero', type: 'generates', label: 'DEFINES' },
  { id: 'e-hero-feeds-factory', fromId: 'node-master-hero', toId: 'asset-factory', type: 'feeds', label: 'FEEDS' },
  { id: 'e-factory-creates-transparent', fromId: 'asset-factory', toId: 'node-transparent-master', type: 'creates' },
  { id: 'e-transparent-registry', fromId: 'node-transparent-master', toId: 'node-smart-asset-registry', type: 'updates' },
  { id: 'e-registry-displays-cart', fromId: 'node-smart-asset-registry', toId: 'node-baw-snapshot', type: 'displays' },
  { id: 'e-baw-used-by-orders', fromId: 'node-baw-snapshot', toId: 'node-smart-asset-registry', type: 'used-by', label: 'CART · CHECKOUT · ORDERS' },
  { id: 'e-tutorial-teaches-customer', fromId: 'tutorial-os', toId: 'node-onboarding-tutorial', type: 'teaches' },
  { id: 'e-manual-documents-interactive', fromId: 'node-written-manual', toId: 'node-interactive-manual', type: 'documented-by' },
  { id: 'e-interactive-documents-manual', fromId: 'node-interactive-manual', toId: 'node-written-manual', type: 'related-to' },
  { id: 'e-knowledge-contains-graph', fromId: 'knowledge-hub', toId: 'node-interactive-manual', type: 'contains' },
  { id: 'e-memory-bible-documents-platform', fromId: 'node-memory-bible', toId: 'memory-bible', type: 'documented-by', label: 'CURATED MEMORY' },
  { id: 'e-memory-links-manual', fromId: 'node-memory-bible', toId: 'node-interactive-manual', type: 'related-to', label: 'INTERACTIVE MANUAL' },
  { id: 'e-memory-links-dna-decision', fromId: 'node-memory-bible', toId: 'node-creative-dna', type: 'related-to', label: 'CREATIVE DNA DECISION' },
  { id: 'e-memory-links-factory', fromId: 'node-memory-bible', toId: 'node-smart-asset-registry', type: 'related-to', label: 'ASSET PIPELINE' },
  { id: 'e-knowledge-contains-memory', fromId: 'knowledge-hub', toId: 'node-memory-bible', type: 'contains' },
  { id: 'e-writing-rules-memory', fromId: 'node-memory-bible', toId: 'content-brain', type: 'feeds', label: 'WRITING RULES' },
  { id: 'e-registry-fallback', fromId: 'node-smart-asset-registry', toId: 'node-fallback-used', type: 'displays' },
  { id: 'e-brand-assets-photo', fromId: 'brand-assets', toId: 'photography-bible', type: 'contains' },
  { id: 'e-brand-assets-factory', fromId: 'brand-assets', toId: 'brand-assets-asset-factory', type: 'contains' },
  { id: 'e-asset-director-approval', fromId: 'asset-factory', toId: 'asset-director', type: 'requires-approval-from' },
  { id: 'e-director-publishes', fromId: 'asset-director', toId: 'publishing-queue', type: 'publishes-to' },
];

export const SEED_GRAPH_WORKFLOWS: KnowledgeGraphWorkflowMap[] = [
  {
    id: 'wf-photography-pipeline',
    title: 'PHOTOGRAPHY PIPELINE',
    subtitle: 'Creative DNA → Master Hero → Factory → Smart Assets → Website',
    nodeIds: [
      'node-creative-dna',
      'node-master-hero',
      'asset-factory',
      'node-transparent-master',
      'node-smart-asset-registry',
      'brand-assets',
    ],
    moduleIds: ['photography-bible', 'asset-factory', 'brand-assets-asset-factory'],
  },
  {
    id: 'wf-baw-cart-snapshot',
    title: 'BUILD-A-WIG CART SNAPSHOT',
    subtitle: 'Configuration → Variant Lookup → Registry → Cart → Order',
    nodeIds: ['node-baw-snapshot', 'node-smart-asset-registry', 'node-fallback-used'],
    moduleIds: ['brand-assets-asset-factory', 'tutorial-os'],
  },
  {
    id: 'wf-rewards-customer',
    title: 'REWARDS WORKFLOW (CUSTOMER)',
    subtitle: 'Purchase → Points → Voucher → History → Checkout',
    nodeIds: ['node-onboarding-tutorial'],
    moduleIds: ['tutorial-os'],
  },
  {
    id: 'wf-tutorial-layering',
    title: 'TUTORIAL LAYERING',
    subtitle: 'Page → Feature → Widget → Action → Completion',
    nodeIds: ['node-onboarding-tutorial', 'tutorial-os', 'node-interactive-manual'],
    moduleIds: ['tutorial-os', 'knowledge-hub'],
  },
  {
    id: 'wf-institutional-memory',
    title: 'INSTITUTIONAL MEMORY',
    subtitle: 'Memory Bible → Naming · Decisions · Context Builder → AI Sessions',
    nodeIds: [
      'node-memory-bible',
      'memory-bible',
      'node-interactive-manual',
      'node-creative-dna',
      'node-smart-asset-registry',
    ],
    moduleIds: ['memory-bible', 'knowledge-hub', 'photography-bible', 'brand-assets-asset-factory'],
  },
];

/** Sub-module page guides merged into manual + graph builders. */
export const SUB_MODULE_GRAPH_NODES: KnowledgeGraphNode[] = [
  {
    id: 'photography-bible',
    name: 'PHOTOGRAPHY BIBLE',
    type: 'module',
    description: 'Locked product photography standards — Creative DNA, master heroes, and generation package.',
    purpose: 'Official visual rules every signature unit and derivative inherits.',
    route: adminStudioPhotographyBiblePath(),
    moduleId: 'photography-bible',
    relatedManualChapter: 'CHAPTER · PHOTOGRAPHY BIBLE',
    versionIntroduced: 'Milestone 22',
    status: 'live',
    searchKeywords: ['photography bible', 'product photography', 'master hero portrait'],
  },
  {
    id: 'brand-assets-asset-factory',
    name: 'PRODUCT ASSET FACTORY / SMART REGISTRY',
    type: 'module',
    description: 'Manufactures transparent masters and registers smart assets for every storefront context.',
    purpose: 'Pipeline from approved master to cart/checkout/email images.',
    route: adminStudioBrandAssetsAssetFactoryPath(),
    moduleId: 'brand-assets-asset-factory',
    relatedManualChapter: 'CHAPTER · SMART ASSET REGISTRY',
    status: 'demo',
    searchKeywords: ['smart asset registry', 'product asset factory', 'product crops'],
  },
];
