import type { KnowledgeGraphEdge, KnowledgeGraphNode, KnowledgeGraphWorkflowMap } from './schema';
import {
  adminStudioBrandAssetsAssetFactoryPath,
  adminStudioGrowthNetworkPath,
  adminStudioMemoryBiblePath,
  adminStudioPhotographyBiblePath,
} from '../../utils/adminStudioRoutes';

/** Canonical cross-module nodes and pipeline relationships. */
export const SEED_GRAPH_NODES: KnowledgeGraphNode[] = [
  {
    id: 'node-creative-dna',
    name: 'CREATIVE DNA',
    type: 'feature',
    description: 'Locked prompt, display bust, and editorial reference that govern all product photography.',
    purpose: 'Single source of truth — products inherit rules instead of one-off image management.',
    route: adminStudioPhotographyBiblePath(),
    moduleId: 'photography-bible',
    relatedManualChapter: 'CHAPTER · PHOTOGRAPHY · CREATIVE DNA',
    manualSection: 'Product Photography',
    manualAnchor: 'creative-dna-v1',
    versionIntroduced: 'Milestone 22.5',
    status: 'live',
    searchKeywords: ['creative dna', 'approved prompt', 'display bust', 'what is creative dna'],
  },
  {
    id: 'node-master-hero',
    name: 'MASTER HERO PORTRAIT',
    type: 'asset-type',
    description: 'Approved Fal-generated master portrait per signature unit — input to Asset Factory.',
    purpose: 'Defines the canonical product image before background removal and smart crops.',
    moduleId: 'photography-bible',
    relatedManualChapter: 'CHAPTER · PHOTOGRAPHY · MASTER HERO',
    searchKeywords: ['master hero', 'hero portrait', 'generate master'],
  },
  {
    id: 'node-transparent-master',
    name: 'TRANSPARENT MASTER',
    type: 'asset-type',
    description: 'Background-removed PNG produced by Asset Factory from approved masters.',
    moduleId: 'brand-assets-asset-factory',
    searchKeywords: ['transparent master', 'background removal', 'cutout'],
  },
  {
    id: 'node-smart-asset-registry',
    name: 'SMART ASSET REGISTRY',
    type: 'module',
    description: 'Context-aware product images — wishlist, cart, checkout, email, and Build-A-Wig snapshots.',
    purpose: 'Delivers the correct variant image per surface without duplicate uploads.',
    route: adminStudioBrandAssetsAssetFactoryPath(),
    moduleId: 'brand-assets-asset-factory',
    relatedManualChapter: 'CHAPTER · SMART ASSETS · REGISTRY',
    versionIntroduced: 'Milestone 22',
    status: 'demo',
    searchKeywords: ['smart asset', 'cart images', 'where do cart images come from', 'fallback_used'],
  },
  {
    id: 'node-baw-snapshot',
    name: 'BUILD-A-WIG VISUAL SNAPSHOT',
    type: 'feature',
    description: 'Reads configured unit, resolves approved variant from Smart Asset Registry, falls back when missing.',
    purpose: 'Shows customer configuration accurately in cart and orders.',
    searchKeywords: ['build-a-wig snapshot', 'baw cart', 'variant lookup', 'fallback'],
  },
  {
    id: 'node-onboarding-tutorial',
    name: 'ONBOARDING TUTORIAL',
    type: 'customer-feature',
    description: 'Customer-facing Mansion Tour — teaches website features (not studio os).',
    purpose: 'Separate from admin Interactive Manual; shares tutorial-os architecture.',
    route: '/home/shop',
    moduleId: 'tutorial-os',
    relatedManualChapter: 'CHAPTER 0 · CUSTOMER ONBOARDING',
    searchKeywords: ['onboarding tutorial', 'mansion tour', 'customer tutorial'],
  },
  {
    id: 'node-written-manual',
    name: 'WRITTEN OPERATING MANUAL',
    type: 'manual-chapter',
    description: 'Future 300–500 page Frontal Slayer operating manual — methodology and deep reference.',
    purpose: 'Long-form docs cross-linked from every Interactive Manual node.',
    searchKeywords: ['written manual', 'owners manual', 'full chapter'],
  },
  {
    id: 'node-interactive-manual',
    name: 'STUDIO OS INTERACTIVE MANUAL',
    type: 'module',
    description: 'Admin live walkthroughs powered by the Knowledge Graph.',
    moduleId: 'knowledge-hub',
    searchKeywords: ['interactive manual', 'studio os manual', 'knowledge graph'],
  },
  {
    id: 'node-memory-bible',
    name: 'MEMORY BIBLE',
    type: 'module',
    description:
      'Curated institutional knowledge — founder profile, naming bible, decision log, workspace memory, and AI Context Builder.',
    purpose: 'studio os owns long-term context for agents, contractors, and team — not vendor chat history alone.',
    route: adminStudioMemoryBiblePath(),
    moduleId: 'memory-bible',
    relatedManualChapter: 'CHAPTER · MEMORY BIBLE · INSTITUTIONAL KNOWLEDGE',
    versionIntroduced: 'Milestone 25',
    status: 'live',
    searchKeywords: [
      'memory bible',
      'institutional knowledge',
      'naming bible',
      'decision log',
      'ai context builder',
      'founder profile',
      'cursor prompt standards',
    ],
  },
  {
    id: 'node-fallback-used',
    name: 'FALLBACK_USED STATUS',
    type: 'status',
    description: 'Smart Asset Registry could not resolve variant — displays safe fallback image.',
    purpose: 'Signals missing approved asset; check Photography Bible + Factory pipeline.',
    searchKeywords: ['fallback_used', 'what does fallback_used mean', 'missing variant'],
  },
  {
    id: 'node-workspace-creation-engine',
    name: 'WORKSPACE CREATION ENGINE',
    type: 'module',
    description: 'Blueprint-driven company provisioning — wizard, registry, executive teams, and promotion pipeline.',
    purpose: 'Launch entire companies from studio os without hardcoding each workspace.',
    route: '/admin/studio-os',
    moduleId: 'studio-os',
    relatedManualChapter: 'CHAPTER · WORKSPACE CREATION ENGINE',
    versionIntroduced: 'Milestone 26',
    status: 'live',
    searchKeywords: ['workspace creation', 'launch new company', 'blueprint', 'provisioning'],
  },
  {
    id: 'node-ai-media-pilot',
    name: 'AI MEDIA PILOT WORKSPACE',
    type: 'feature',
    description: 'Permanent pilot workspace — validates every studio os feature before Frontal Slayer promotion.',
    purpose: 'Reference environment for production testing and promotion pipeline.',
    route: '/admin/studio-os/workspace/ai-media/dashboard',
    moduleId: 'studio-os',
    versionIntroduced: 'Milestone 26',
    status: 'live',
    searchKeywords: ['ai media', 'pilot workspace', 'reference workspace'],
  },
  {
    id: 'node-ai-executive-team',
    name: 'AI EXECUTIVE TEAM',
    type: 'feature',
    description: 'Blueprint-provisioned specialized AI advisors inheriting Memory Bible, Creative DNA, and workflows.',
    purpose: 'Company-specific leadership — not generic chatbots.',
    moduleId: 'studio-os',
    versionIntroduced: 'Milestone 26',
    status: 'live',
    searchKeywords: ['executive team', 'chief content officer', 'ai executives', 'collaboration'],
  },
  {
    id: 'node-promotion-pipeline',
    name: 'PROMOTION PIPELINE',
    type: 'workflow',
    description: 'Develop → AI Media → test → approve → promote to Frontal Slayer → all workspaces.',
    purpose: 'Built-in feature lifecycle for studio os capabilities.',
    route: '/admin/studio-os/promotion-center',
    moduleId: 'studio-os',
    versionIntroduced: 'Milestone 26',
    status: 'live',
    searchKeywords: ['promotion center', 'pilot to production', 'frontal slayer promotion'],
  },
  {
    id: 'node-growth-network',
    name: 'GROWTH NETWORK',
    type: 'module',
    description:
      'Intelligent business growth ecosystem — growth profiles, opportunity engine, deal pipeline CRM, revenue center, and marketplaces.',
    purpose: 'Operating layer between businesses and opportunities — not a traditional talent agency.',
    route: adminStudioGrowthNetworkPath(),
    moduleId: 'growth-network',
    relatedManualChapter: 'CHAPTER · GROWTH NETWORK · BUSINESS GROWTH ECOSYSTEM',
    versionIntroduced: 'Milestone 27',
    status: 'live',
    searchKeywords: [
      'growth network',
      'partnerships',
      'opportunity engine',
      'deal pipeline',
      'revenue center',
      'growth score',
    ],
  },
  {
    id: 'node-opportunity-engine',
    name: 'OPPORTUNITY ENGINE',
    type: 'feature',
    description: 'Matches brand partnerships, affiliates, sponsorships, and collaborations to workspace growth profiles.',
    purpose: 'Continuous opportunity matching based on Memory Bible growth strategy and company DNA.',
    moduleId: 'growth-network',
    versionIntroduced: 'Milestone 27',
    status: 'live',
    searchKeywords: ['opportunity engine', 'brand partnership match', 'sponsorship opportunities'],
  },
  {
    id: 'node-deal-pipeline',
    name: 'DEAL PIPELINE CRM',
    type: 'workflow',
    description: 'Lead → qualified → meeting → proposal → negotiation → contract → campaign → deliverables → invoice → payment → renewal → completed.',
    purpose: 'Full partnership lifecycle for every opportunity in Growth Network.',
    moduleId: 'growth-network',
    versionIntroduced: 'Milestone 27',
    status: 'live',
    searchKeywords: ['deal pipeline', 'partnership crm', 'partnership lifecycle'],
  },
  {
    id: 'node-revenue-center',
    name: 'REVENUE CENTER',
    type: 'feature',
    description: 'Centralized revenue dashboard — brand deals, affiliates, platform payouts, products, and diversification score.',
    purpose: 'Track and forecast revenue across all channels for growth intelligence.',
    moduleId: 'growth-network',
    versionIntroduced: 'Milestone 27',
    status: 'live',
    searchKeywords: ['revenue center', 'revenue diversification', 'monthly revenue'],
  },
];

export const SEED_GRAPH_EDGES: KnowledgeGraphEdge[] = [
  { id: 'e-photo-contains-dna', fromId: 'photography-bible', toId: 'node-creative-dna', type: 'contains', label: 'CONTAINS' },
  { id: 'e-dna-defines-hero', fromId: 'node-creative-dna', toId: 'node-master-hero', type: 'generates', label: 'DEFINES' },
  { id: 'e-hero-feeds-factory', fromId: 'node-master-hero', toId: 'asset-factory', type: 'feeds', label: 'FEEDS' },
  { id: 'e-factory-creates-transparent', fromId: 'asset-factory', toId: 'node-transparent-master', type: 'creates' },
  { id: 'e-transparent-registry', fromId: 'node-transparent-master', toId: 'node-smart-asset-registry', type: 'updates' },
  { id: 'e-registry-displays-cart', fromId: 'node-smart-asset-registry', toId: 'node-baw-snapshot', type: 'displays' },
  { id: 'e-baw-used-by-orders', fromId: 'node-baw-snapshot', toId: 'node-smart-asset-registry', type: 'used-by', label: 'CART · CHECKOUT · ORDERS' },
  { id: 'e-tutorial-teaches-customer', fromId: 'tutorial-os', toId: 'node-onboarding-tutorial', type: 'teaches' },
  { id: 'e-manual-documents-interactive', fromId: 'node-written-manual', toId: 'node-interactive-manual', type: 'documented-by' },
  { id: 'e-interactive-documents-manual', fromId: 'node-interactive-manual', toId: 'node-written-manual', type: 'related-to' },
  { id: 'e-knowledge-contains-graph', fromId: 'knowledge-hub', toId: 'node-interactive-manual', type: 'contains' },
  { id: 'e-memory-bible-documents-platform', fromId: 'node-memory-bible', toId: 'memory-bible', type: 'documented-by', label: 'CURATED MEMORY' },
  { id: 'e-memory-links-manual', fromId: 'node-memory-bible', toId: 'node-interactive-manual', type: 'related-to', label: 'INTERACTIVE MANUAL' },
  { id: 'e-memory-links-dna-decision', fromId: 'node-memory-bible', toId: 'node-creative-dna', type: 'related-to', label: 'CREATIVE DNA DECISION' },
  { id: 'e-memory-links-factory', fromId: 'node-memory-bible', toId: 'node-smart-asset-registry', type: 'related-to', label: 'ASSET PIPELINE' },
  { id: 'e-knowledge-contains-memory', fromId: 'knowledge-hub', toId: 'node-memory-bible', type: 'contains' },
  { id: 'e-writing-rules-memory', fromId: 'node-memory-bible', toId: 'content-brain', type: 'feeds', label: 'WRITING RULES' },
  { id: 'e-registry-fallback', fromId: 'node-smart-asset-registry', toId: 'node-fallback-used', type: 'displays' },
  { id: 'e-brand-assets-photo', fromId: 'brand-assets', toId: 'photography-bible', type: 'contains' },
  { id: 'e-brand-assets-factory', fromId: 'brand-assets', toId: 'brand-assets-asset-factory', type: 'contains' },
  { id: 'e-asset-director-approval', fromId: 'asset-factory', toId: 'asset-director', type: 'requires-approval-from' },
  { id: 'e-director-publishes', fromId: 'asset-director', toId: 'publishing-queue', type: 'publishes-to' },
  { id: 'e-wce-provisions-ai-media', fromId: 'node-workspace-creation-engine', toId: 'node-ai-media-pilot', type: 'creates', label: 'PROVISIONS' },
  { id: 'e-wce-executive-team', fromId: 'node-workspace-creation-engine', toId: 'node-ai-executive-team', type: 'contains' },
  { id: 'e-ai-media-promotion', fromId: 'node-ai-media-pilot', toId: 'node-promotion-pipeline', type: 'feeds', label: 'PILOT TESTING' },
  { id: 'e-promotion-frontal', fromId: 'node-promotion-pipeline', toId: 'mission-control', type: 'related-to', label: 'PROMOTE TO FRONTAL SLAYER' },
  { id: 'e-executive-collab', fromId: 'node-ai-executive-team', toId: 'node-ai-media-pilot', type: 'related-to', label: 'CCO → CREATIVE → DISTRIBUTION' },
  { id: 'e-executive-memory', fromId: 'node-ai-executive-team', toId: 'node-memory-bible', type: 'inherits-from', label: 'MEMORY BIBLE' },
  { id: 'e-growth-profile-memory', fromId: 'node-growth-network', toId: 'node-memory-bible', type: 'inherits-from', label: 'GROWTH STRATEGY' },
  { id: 'e-growth-contains-opportunity', fromId: 'node-growth-network', toId: 'node-opportunity-engine', type: 'contains' },
  { id: 'e-growth-contains-pipeline', fromId: 'node-growth-network', toId: 'node-deal-pipeline', type: 'contains' },
  { id: 'e-growth-contains-revenue', fromId: 'node-growth-network', toId: 'node-revenue-center', type: 'contains' },
  { id: 'e-opportunity-pipeline', fromId: 'node-opportunity-engine', toId: 'node-deal-pipeline', type: 'feeds', label: 'QUALIFIED LEADS' },
  { id: 'e-pipeline-revenue', fromId: 'node-deal-pipeline', toId: 'node-revenue-center', type: 'feeds', label: 'CLOSED DEALS' },
  { id: 'e-growth-knowledge', fromId: 'node-growth-network', toId: 'node-interactive-manual', type: 'related-to', label: 'KNOWLEDGE GRAPH' },
  { id: 'e-ai-media-growth', fromId: 'node-ai-media-pilot', toId: 'node-growth-network', type: 'feeds', label: 'PILOT VALIDATION' },
  { id: 'e-audience-growth', fromId: 'audience-brain', toId: 'node-growth-network', type: 'feeds', label: 'AUDIENCE SIGNALS' },
];

export const SEED_GRAPH_WORKFLOWS: KnowledgeGraphWorkflowMap[] = [
  {
    id: 'wf-photography-pipeline',
    title: 'PHOTOGRAPHY PIPELINE',
    subtitle: 'Creative DNA → Master Hero → Factory → Smart Assets → Website',
    nodeIds: [
      'node-creative-dna',
      'node-master-hero',
      'asset-factory',
      'node-transparent-master',
      'node-smart-asset-registry',
      'brand-assets',
    ],
    moduleIds: ['photography-bible', 'asset-factory', 'brand-assets-asset-factory'],
  },
  {
    id: 'wf-baw-cart-snapshot',
    title: 'BUILD-A-WIG CART SNAPSHOT',
    subtitle: 'Configuration → Variant Lookup → Registry → Cart → Order',
    nodeIds: ['node-baw-snapshot', 'node-smart-asset-registry', 'node-fallback-used'],
    moduleIds: ['brand-assets-asset-factory', 'tutorial-os'],
  },
  {
    id: 'wf-rewards-customer',
    title: 'REWARDS WORKFLOW (CUSTOMER)',
    subtitle: 'Purchase → Points → Voucher → History → Checkout',
    nodeIds: ['node-onboarding-tutorial'],
    moduleIds: ['tutorial-os'],
  },
  {
    id: 'wf-tutorial-layering',
    title: 'TUTORIAL LAYERING',
    subtitle: 'Page → Feature → Widget → Action → Completion',
    nodeIds: ['node-onboarding-tutorial', 'tutorial-os', 'node-interactive-manual'],
    moduleIds: ['tutorial-os', 'knowledge-hub'],
  },
  {
    id: 'wf-institutional-memory',
    title: 'INSTITUTIONAL MEMORY',
    subtitle: 'Memory Bible → Naming · Decisions · Context Builder → AI Sessions',
    nodeIds: [
      'node-memory-bible',
      'memory-bible',
      'node-interactive-manual',
      'node-creative-dna',
      'node-smart-asset-registry',
    ],
    moduleIds: ['memory-bible', 'knowledge-hub', 'photography-bible', 'brand-assets-asset-factory'],
  },
  {
    id: 'wf-workspace-promotion',
    title: 'WORKSPACE PROMOTION LIFECYCLE',
    subtitle: 'Develop → AI Media Pilot → Test → Approve → Frontal Slayer → All Workspaces',
    nodeIds: [
      'node-workspace-creation-engine',
      'node-ai-media-pilot',
      'node-promotion-pipeline',
      'node-ai-executive-team',
      'mission-control',
    ],
    moduleIds: ['studio-os'],
  },
  {
    id: 'wf-growth-network',
    title: 'GROWTH NETWORK LIFECYCLE',
    subtitle: 'Memory Bible → Growth Profile → Opportunities → Deal Pipeline → Revenue → Knowledge Graph',
    nodeIds: [
      'node-memory-bible',
      'node-growth-network',
      'node-opportunity-engine',
      'node-deal-pipeline',
      'node-revenue-center',
      'node-interactive-manual',
    ],
    moduleIds: ['growth-network', 'memory-bible', 'knowledge-hub', 'audience-brain'],
  },
];

/** Sub-module page guides merged into manual + graph builders. */
export const SUB_MODULE_GRAPH_NODES: KnowledgeGraphNode[] = [
  {
    id: 'photography-bible',
    name: 'PHOTOGRAPHY BIBLE',
    type: 'module',
    description: 'Locked product photography standards — Creative DNA, master heroes, and generation package.',
    purpose: 'Official visual rules every signature unit and derivative inherits.',
    route: adminStudioPhotographyBiblePath(),
    moduleId: 'photography-bible',
    relatedManualChapter: 'CHAPTER · PHOTOGRAPHY BIBLE',
    versionIntroduced: 'Milestone 22',
    status: 'live',
    searchKeywords: ['photography bible', 'product photography', 'master hero portrait'],
  },
  {
    id: 'brand-assets-asset-factory',
    name: 'PRODUCT ASSET FACTORY / SMART REGISTRY',
    type: 'module',
    description: 'Manufactures transparent masters and registers smart assets for every storefront context.',
    purpose: 'Pipeline from approved master to cart/checkout/email images.',
    route: adminStudioBrandAssetsAssetFactoryPath(),
    moduleId: 'brand-assets-asset-factory',
    relatedManualChapter: 'CHAPTER · SMART ASSET REGISTRY',
    status: 'demo',
    searchKeywords: ['smart asset registry', 'product asset factory', 'product crops'],
  },
];
