import type { EducationMastery } from '../types';

export const EDUCATION_MASTERIES: EducationMastery[] = [
  {
    id: 'mastery-lace',
    slug: 'lace-mastery',
    title: 'LACE MASTERY',
    subtitle: 'LACE',
    description: 'UNDERSTAND, CUSTOMIZE, AND TROUBLESHOOT LACE BEFORE AND DURING INSTALLATION.',
    pillar: 'lace',
    seasonIds: [
      'season-lace-01-understand-your-lace',
      'season-lace-02-customize-your-lace',
      'season-lace-03-lace-troubleshooting',
    ],
    status: 'active',
    published: true,
    sortOrder: 1,
  },
  {
    id: 'mastery-color',
    slug: 'color-mastery',
    title: 'COLOR MASTERY',
    subtitle: 'COLOR',
    description: 'COLOR EDUCATION — SEASONS COMING SOON.',
    pillar: 'color',
    seasonIds: [],
    status: 'planned',
    published: false,
    sortOrder: 2,
  },
  {
    id: 'mastery-install',
    slug: 'install-mastery',
    title: 'INSTALLATION MASTERY',
    subtitle: 'INSTALLATION',
    description: 'PREP, INSTALL, FINISH, REMOVE, AND RESTORE — INSTALLATION-SPECIFIC TECHNIQUES.',
    pillar: 'install',
    seasonIds: [
      'season-install-01-prep-install-finish',
      'season-install-02-removal-restoration',
    ],
    status: 'planned',
    published: false,
    sortOrder: 3,
  },
  {
    id: 'mastery-care',
    slug: 'care-mastery',
    title: 'CARE MASTERY',
    subtitle: 'CARE',
    description: 'PREMIUM HAIR CARE EDUCATION — PURCHASE WITH SLAY TICKETS OR SEASON PASS.',
    pillar: 'care',
    seasonIds: [
      'season-care-mastery',
      'season-care-02-the-care-ritual',
      'season-care-03-wash-day',
      'season-care-04-preserve-the-slay',
      'season-care-05-revive-restore',
    ],
    status: 'active',
    published: true,
    sortOrder: 4,
    careAccessModel: 'dual-access',
  },
  {
    id: 'mastery-style',
    slug: 'style-mastery',
    title: 'STYLING MASTERY',
    subtitle: 'STYLING',
    description: 'FINISHING, SHAPING, AND STYLING TECHNIQUES — SEASONS COMING SOON.',
    pillar: 'style',
    seasonIds: [],
    status: 'planned',
    published: false,
    sortOrder: 5,
  },
  {
    id: 'mastery-after-care',
    slug: 'after-care-mastery',
    title: 'UPKEEP MASTERY',
    subtitle: 'UPKEEP',
    description: 'MAINTAIN YOUR INSTALL AND HAIR BETWEEN STYLING SESSIONS — SEASONS COMING SOON.',
    pillar: 'care',
    seasonIds: [],
    status: 'planned',
    published: false,
    sortOrder: 6,
  },
];
