/**
 * OpenArt Director production package builder — external/manual workflow.
 * No fabricated API integration; human-transferable export.
 */

import type { DirectorProductionPackage, VirtualProductionCampaign, VirtualProductionScene, VirtualProductionShot } from './types';
import type { VirtualProductionBrand, VirtualProductionCharacter, VirtualProductionEnvironment, VirtualProductionProduct } from './types';

type PackageBuildInput = {
  campaign: VirtualProductionCampaign;
  brand: VirtualProductionBrand;
  scenes: VirtualProductionScene[];
  shots: VirtualProductionShot[];
  characters: VirtualProductionCharacter[];
  environments: VirtualProductionEnvironment[];
  products: VirtualProductionProduct[];
  wardrobe?: Array<{ key: string; label: string }>;
  cameraLanguage?: Record<string, unknown>;
  forbiddenDeviations?: string[];
  audioDirection?: string;
};

export function buildDirectorProductionPackage(input: PackageBuildInput): DirectorProductionPackage {
  const { campaign, scenes, shots, characters, environments, products } = input;

  const scenePlan = scenes
    .sort((a, b) => a.sortOrder - b.sortOrder)
    .map((scene) => ({
      sceneKey: scene.sceneKey,
      title: scene.title,
      shots: shots.filter((s) => s.sceneId === scene.id).map((s) => s.shotKey),
    }));

  const shotRequirements = shots
    .sort((a, b) => a.sortOrder - b.sortOrder)
    .map((s) => ({
      shotKey: s.shotKey,
      description: s.description,
      duration: s.durationSeconds,
    }));

  return {
    campaign: {
      key: campaign.campaignKey,
      name: campaign.name,
      objective: campaign.objective,
    },
    story: campaign.narrativeConcept,
    treatment: campaign.treatment,
    characters: characters.map((c) => ({
      key: c.characterKey,
      name: c.canonicalName,
      references: c.referenceUrls,
    })),
    environments: environments.map((e) => ({
      key: e.environmentKey,
      name: e.name,
      references: Array.isArray(e.canonicalImages) ? (e.canonicalImages as string[]) : [],
    })),
    products: products.map((p) => ({
      key: p.productKey,
      name: p.name,
      references: typeof p.canonicalImages === 'object' ? (p.canonicalImages as Record<string, string>) : {},
    })),
    wardrobe: input.wardrobe ?? [],
    cameraLanguage: input.cameraLanguage ?? {},
    scenePlan,
    shotRequirements,
    continuityRequirements: (campaign.canonSnapshot.continuity as Record<string, unknown>) ?? {},
    forbiddenDeviations: input.forbiddenDeviations ?? input.brand.forbiddenDeviations,
    deliverableRequirements: campaign.deliverables,
    aspectRatio: typeof campaign.format.aspectRatio === 'string' ? campaign.format.aspectRatio : undefined,
    durationTarget: typeof campaign.format.durationTarget === 'number' ? campaign.format.durationTarget : undefined,
    audioDirection: input.audioDirection,
  };
}

export function formatDirectorPackageMarkdown(pkg: DirectorProductionPackage): string {
  const lines: string[] = [
    `# OpenArt Director Production Package`,
    ``,
    `## Campaign`,
    `- **Name:** ${pkg.campaign.name}`,
    `- **Key:** ${pkg.campaign.key}`,
    pkg.campaign.objective ? `- **Objective:** ${pkg.campaign.objective}` : '',
    ``,
    `## Story`,
    pkg.story ?? '_[Setup required]_',
    ``,
    `## Treatment`,
    pkg.treatment ?? '_[Setup required]_',
    ``,
    `## Characters`,
    ...pkg.characters.map((c) => `- **${c.name}** (\`${c.key}\`)`),
    ``,
    `## Environments`,
    ...pkg.environments.map((e) => `- **${e.name}** (\`${e.key}\`)`),
    ``,
    `## Products`,
    ...pkg.products.map((p) => `- **${p.name}** (\`${p.key}\`)`),
    ``,
    `## Scene Plan`,
    ...pkg.scenePlan.flatMap((s) => [
      `### ${s.title} (\`${s.sceneKey}\`)`,
      ...s.shots.map((sh) => `- Shot \`${sh}\``),
      ``,
    ]),
    `## Shot Requirements`,
    ...pkg.shotRequirements.map((s) => `- \`${s.shotKey}\`: ${s.description ?? 'TBD'} (${s.duration ?? '?'}s)`),
    ``,
    `## Forbidden Deviations`,
    ...pkg.forbiddenDeviations.map((d) => `- ${d}`),
    ``,
    `## Deliverables`,
    `- Aspect ratio: ${pkg.aspectRatio ?? 'TBD'}`,
    `- Duration target: ${pkg.durationTarget ?? 'TBD'}s`,
    pkg.audioDirection ? `- Audio: ${pkg.audioDirection}` : '',
    ``,
    `_Generated by Studio World Virtual Production OS — transfer manually to OpenArt Director._`,
  ];

  return lines.filter((l) => l !== '').join('\n');
}

/** OpenArt Director integration status */
export const OPENART_DIRECTOR_INTEGRATION = {
  programmaticApi: false,
  externalManualWorkflow: true,
  mcpModelApiAvailable: true,
  blockedBy: 'No supported OpenArt Director programmatic API in codebase or MCP',
} as const;
