import type { BuildOrderSeedInput } from '../types';

/** Canonical Studio OS systems — seeded from STUDIO_OS_BUILD_ORDER.md */
export const STUDIO_OS_BUILD_ORDER_SEED: BuildOrderSeedInput[] = [
  {
    systemId: 'genesis',
    officialName: 'Genesis™',
    purpose: 'Canonical source-of-truth kernel.',
    architecturalPhase: 0,
    priority: 'P0',
    topologicalOrder: 1,
    dependencies: [],
    blocks: ['canonical-object-registry', 'universal-interaction-engine', 'universal-decision-engine', 'studio-os-dependency-map'],
    complexity: 'medium',
    businessValue: 'high',
    platformValue: 'highest',
    estimatedBuildTime: 'Sprint 0',
    architecturalReadiness: 'high',
    implementationReadiness: 'shipped',
    rewriteRisk: 'low',
    technicalDebtRisk: 'low',
    currentStatus: 'implemented',
    notes: 'Genesis Foundation Framework runtime shipped.',
  },
  {
    systemId: 'canonical-object-registry',
    officialName: 'Canonical Object Registry™',
    purpose: 'Canonical object identity and validation.',
    architecturalPhase: 0,
    priority: 'P0',
    topologicalOrder: 2,
    dependencies: ['genesis'],
    blocks: ['business-discovery', 'organization-registry', 'knowledge-core', 'asset-registry'],
    complexity: 'medium',
    businessValue: 'high',
    platformValue: 'highest',
    estimatedBuildTime: 'Sprint 0',
    architecturalReadiness: 'high',
    implementationReadiness: 'shipped',
    rewriteRisk: 'low',
    technicalDebtRisk: 'low',
    currentStatus: 'implemented',
    notes: 'Shipped as object-model infrastructure.',
  },
  {
    systemId: 'universal-interaction-engine',
    officialName: 'Universal Interaction Engine™',
    purpose: 'Shared interaction/event/workflow/command grammar.',
    architecturalPhase: 0,
    priority: 'P0',
    topologicalOrder: 3,
    dependencies: ['genesis', 'canonical-object-registry'],
    blocks: ['event-bus', 'workflow-engine', 'command-center'],
    complexity: 'high',
    businessValue: 'high',
    platformValue: 'highest',
    estimatedBuildTime: 'Sprint 0',
    architecturalReadiness: 'high',
    implementationReadiness: 'shipped',
    rewriteRisk: 'medium',
    technicalDebtRisk: 'low',
    currentStatus: 'implemented',
  },
  {
    systemId: 'universal-decision-engine',
    officialName: 'Universal Decision Engine™',
    purpose: 'Shared decision, evidence, priority, confidence, review model.',
    architecturalPhase: 0,
    priority: 'P0',
    topologicalOrder: 4,
    dependencies: ['genesis', 'canonical-object-registry', 'universal-interaction-engine'],
    blocks: ['orb', 'command-center', 'automation-engine', 'analytics'],
    complexity: 'high',
    businessValue: 'high',
    platformValue: 'highest',
    estimatedBuildTime: 'Sprint 0',
    architecturalReadiness: 'high',
    implementationReadiness: 'shipped',
    rewriteRisk: 'medium',
    technicalDebtRisk: 'low',
    currentStatus: 'implemented',
  },
  {
    systemId: 'studio-os-dependency-map',
    officialName: 'Studio OS Dependency Map™',
    purpose: 'Live dependency planning engine.',
    architecturalPhase: 0,
    priority: 'P0',
    topologicalOrder: 5,
    dependencies: ['genesis'],
    blocks: [],
    complexity: 'medium',
    businessValue: 'high',
    platformValue: 'highest',
    estimatedBuildTime: 'Sprint 0',
    architecturalReadiness: 'high',
    implementationReadiness: 'shipped',
    rewriteRisk: 'medium',
    technicalDebtRisk: 'low',
    currentStatus: 'implemented',
  },
  {
    systemId: 'business-discovery',
    officialName: 'Business Discovery™',
    purpose: 'Converts founder/business context into structured architecture inputs.',
    architecturalPhase: 1,
    priority: 'P0',
    topologicalOrder: 6,
    dependencies: ['canonical-object-registry', 'universal-interaction-engine', 'universal-decision-engine'],
    blocks: ['company-genome', 'blueprint-engine', 'company-registry'],
    complexity: 'high',
    businessValue: 'high',
    platformValue: 'high',
    estimatedBuildTime: 'Cycle 1',
    architecturalReadiness: 'high',
    implementationReadiness: 'medium',
    rewriteRisk: 'medium',
    technicalDebtRisk: 'medium',
    currentStatus: 'planned',
    notes: 'Recommended next implementation sprint.',
  },
  {
    systemId: 'company-genome',
    officialName: 'Company Genome™',
    purpose: 'Business operating DNA map: systems, flows, risks, events, dependencies.',
    architecturalPhase: 1,
    priority: 'P0',
    topologicalOrder: 7,
    dependencies: ['business-discovery', 'canonical-object-registry'],
    blocks: ['company-registry', 'department-framework', 'mission-engine', 'executive-headquarters'],
    complexity: 'high',
    businessValue: 'highest',
    platformValue: 'high',
    estimatedBuildTime: 'Cycle 2',
    architecturalReadiness: 'high',
    implementationReadiness: 'medium',
    rewriteRisk: 'medium',
    technicalDebtRisk: 'medium',
    currentStatus: 'planned',
  },
  {
    systemId: 'blueprint-engine',
    officialName: 'Blueprint Engine™',
    purpose: 'Converts discovery/goals into architecture blueprints.',
    architecturalPhase: 1,
    priority: 'P1',
    topologicalOrder: 8,
    dependencies: ['business-discovery', 'company-genome', 'universal-decision-engine'],
    blocks: ['studio-foundry', 'department-framework', 'experience-engine'],
    complexity: 'high',
    businessValue: 'high',
    platformValue: 'high',
    estimatedBuildTime: 'Cycle 1 parallel',
    architecturalReadiness: 'medium',
    implementationReadiness: 'low',
    rewriteRisk: 'medium',
    technicalDebtRisk: 'medium',
    currentStatus: 'planned',
  },
  {
    systemId: 'organization-registry',
    officialName: 'Organization Registry™',
    purpose: 'System of record for organizations/workspaces above companies.',
    architecturalPhase: 2,
    priority: 'P0',
    topologicalOrder: 9,
    dependencies: ['canonical-object-registry'],
    blocks: ['authentication', 'workspace-framework', 'permissions-engine'],
    complexity: 'medium',
    businessValue: 'high',
    platformValue: 'highest',
    estimatedBuildTime: 'Cycle 3',
    architecturalReadiness: 'medium',
    implementationReadiness: 'low',
    rewriteRisk: 'high',
    technicalDebtRisk: 'high',
    currentStatus: 'planned',
  },
  {
    systemId: 'company-registry',
    officialName: 'Company Registry™',
    purpose: 'System of record for companies, departments, memberships, HQs.',
    architecturalPhase: 2,
    priority: 'P0',
    topologicalOrder: 10,
    dependencies: ['company-genome', 'organization-registry', 'canonical-object-registry'],
    blocks: ['executive-headquarters', 'mission-engine', 'permissions-engine', 'studio-exchange'],
    complexity: 'high',
    businessValue: 'highest',
    platformValue: 'highest',
    estimatedBuildTime: 'Cycle 3',
    architecturalReadiness: 'high',
    implementationReadiness: 'low',
    rewriteRisk: 'high',
    technicalDebtRisk: 'high',
    currentStatus: 'planned',
  },
  {
    systemId: 'identity-engine',
    officialName: 'Identity Engine™',
    purpose: 'Actor identity for humans, AI workers, companies, roles, credentials.',
    architecturalPhase: 2,
    priority: 'P0',
    topologicalOrder: 11,
    dependencies: ['canonical-object-registry', 'organization-registry'],
    blocks: ['authentication', 'permissions-engine', 'orb', 'marketplace'],
    complexity: 'high',
    businessValue: 'highest',
    platformValue: 'highest',
    estimatedBuildTime: 'Cycle 4',
    architecturalReadiness: 'medium',
    implementationReadiness: 'low',
    rewriteRisk: 'high',
    technicalDebtRisk: 'high',
    currentStatus: 'planned',
  },
  {
    systemId: 'authentication',
    officialName: 'Authentication',
    purpose: 'Session and sign-in boundary for identified actors.',
    architecturalPhase: 2,
    priority: 'P0',
    topologicalOrder: 12,
    dependencies: ['identity-engine', 'organization-registry'],
    blocks: ['permissions-engine', 'api-layer', 'workspace-framework'],
    complexity: 'high',
    businessValue: 'highest',
    platformValue: 'high',
    estimatedBuildTime: 'Cycle 4',
    architecturalReadiness: 'medium',
    implementationReadiness: 'medium',
    rewriteRisk: 'critical',
    technicalDebtRisk: 'high',
    currentStatus: 'planned',
  },
  {
    systemId: 'permissions-engine',
    officialName: 'Permissions Engine™',
    purpose: 'Authority, scopes, delegation, approval, and access decisions.',
    architecturalPhase: 2,
    priority: 'P0',
    topologicalOrder: 13,
    dependencies: ['identity-engine', 'authentication', 'organization-registry', 'company-registry', 'universal-decision-engine'],
    blocks: ['command-center', 'automation-engine', 'studio-exchange', 'api-layer'],
    complexity: 'high',
    businessValue: 'highest',
    platformValue: 'highest',
    estimatedBuildTime: 'Cycle 5',
    architecturalReadiness: 'high',
    implementationReadiness: 'low',
    rewriteRisk: 'critical',
    technicalDebtRisk: 'critical',
    currentStatus: 'planned',
  },
  {
    systemId: 'knowledge-core',
    officialName: 'Knowledge Core™',
    purpose: 'Source-backed canonical knowledge store.',
    architecturalPhase: 3,
    priority: 'P1',
    topologicalOrder: 14,
    dependencies: ['canonical-object-registry', 'genesis'],
    blocks: ['codex', 'research-engine', 'orb', 'institute-of-knowledge'],
    complexity: 'high',
    businessValue: 'high',
    platformValue: 'highest',
    estimatedBuildTime: 'Cycle 6',
    architecturalReadiness: 'high',
    implementationReadiness: 'medium',
    rewriteRisk: 'high',
    technicalDebtRisk: 'high',
    currentStatus: 'planned',
  },
  {
    systemId: 'knowledge-graph',
    officialName: 'Knowledge Graph™',
    purpose: 'Semantic graph of knowledge artifacts, citations, concepts, lessons.',
    architecturalPhase: 3,
    priority: 'P1',
    topologicalOrder: 15,
    dependencies: ['knowledge-core', 'canonical-object-registry'],
    blocks: ['search', 'codex', 'research-engine', 'profession-brains'],
    complexity: 'high',
    businessValue: 'medium',
    platformValue: 'highest',
    estimatedBuildTime: 'Cycle 6 parallel',
    architecturalReadiness: 'medium',
    implementationReadiness: 'low',
    rewriteRisk: 'high',
    technicalDebtRisk: 'medium',
    currentStatus: 'planned',
  },
  {
    systemId: 'world-graph',
    officialName: 'World Graph™',
    purpose: 'Graph of systems, companies, rooms, missions, knowledge, assets, relationships.',
    architecturalPhase: 3,
    priority: 'P1',
    topologicalOrder: 16,
    dependencies: ['canonical-object-registry', 'company-registry', 'knowledge-graph'],
    blocks: ['atlas', 'orb', 'search', 'experience-engine', 'analytics'],
    complexity: 'high',
    businessValue: 'high',
    platformValue: 'highest',
    estimatedBuildTime: 'Cycle 7',
    architecturalReadiness: 'high',
    implementationReadiness: 'medium',
    rewriteRisk: 'high',
    technicalDebtRisk: 'medium',
    currentStatus: 'planned',
  },
  {
    systemId: 'codex',
    officialName: 'Codex™',
    purpose: 'Compiled developer/architect knowledge projection.',
    architecturalPhase: 3,
    priority: 'P2',
    topologicalOrder: 17,
    dependencies: ['genesis', 'knowledge-core', 'knowledge-graph'],
    blocks: ['developer-sdk', 'institute-of-knowledge', 'orb'],
    complexity: 'medium',
    businessValue: 'medium',
    platformValue: 'high',
    estimatedBuildTime: 'Cycle 12 parallel',
    architecturalReadiness: 'high',
    implementationReadiness: 'medium',
    rewriteRisk: 'medium',
    technicalDebtRisk: 'medium',
    currentStatus: 'planned',
  },
  {
    systemId: 'event-bus',
    officialName: 'Event Bus™',
    purpose: 'Shared event transport and contract registry.',
    architecturalPhase: 4,
    priority: 'P0',
    topologicalOrder: 18,
    dependencies: ['universal-interaction-engine'],
    blocks: ['workflow-engine', 'notifications', 'analytics', 'integration-framework'],
    complexity: 'medium',
    businessValue: 'high',
    platformValue: 'highest',
    estimatedBuildTime: 'Cycle 8',
    architecturalReadiness: 'high',
    implementationReadiness: 'medium',
    rewriteRisk: 'high',
    technicalDebtRisk: 'high',
    currentStatus: 'planned',
  },
  {
    systemId: 'workflow-engine',
    officialName: 'Workflow Engine™',
    purpose: 'Sequences approved work across systems.',
    architecturalPhase: 4,
    priority: 'P0',
    topologicalOrder: 19,
    dependencies: ['event-bus', 'universal-interaction-engine', 'universal-decision-engine', 'permissions-engine'],
    blocks: ['mission-engine', 'automation-engine'],
    complexity: 'high',
    businessValue: 'high',
    platformValue: 'highest',
    estimatedBuildTime: 'Cycle 8',
    architecturalReadiness: 'high',
    implementationReadiness: 'low',
    rewriteRisk: 'high',
    technicalDebtRisk: 'high',
    currentStatus: 'planned',
  },
  {
    systemId: 'mission-engine',
    officialName: 'Mission Engine™',
    purpose: 'Mission state, owners, blockers, outcomes, learning.',
    architecturalPhase: 4,
    priority: 'P0',
    topologicalOrder: 20,
    dependencies: ['company-registry', 'workflow-engine', 'universal-decision-engine'],
    blocks: ['executive-headquarters', 'orb', 'analytics', 'career-worlds'],
    complexity: 'medium',
    businessValue: 'highest',
    platformValue: 'high',
    estimatedBuildTime: 'Cycle 9',
    architecturalReadiness: 'high',
    implementationReadiness: 'low',
    rewriteRisk: 'high',
    technicalDebtRisk: 'medium',
    currentStatus: 'planned',
  },
  {
    systemId: 'command-center',
    officialName: 'Command Center™',
    purpose: 'Safe command intake, authorization, routing, monitoring, rollback.',
    architecturalPhase: 4,
    priority: 'P0',
    topologicalOrder: 21,
    dependencies: ['permissions-engine', 'event-bus', 'workflow-engine', 'universal-decision-engine'],
    blocks: ['orb', 'executive-headquarters', 'automation-engine', 'api-layer'],
    complexity: 'high',
    businessValue: 'highest',
    platformValue: 'highest',
    estimatedBuildTime: 'Cycle 9',
    architecturalReadiness: 'high',
    implementationReadiness: 'low',
    rewriteRisk: 'critical',
    technicalDebtRisk: 'critical',
    currentStatus: 'planned',
  },
  {
    systemId: 'notifications',
    officialName: 'Notifications™',
    purpose: 'Attention signals, prompts, reminders, digests.',
    architecturalPhase: 4,
    priority: 'P2',
    topologicalOrder: 22,
    dependencies: ['event-bus', 'identity-engine', 'permissions-engine'],
    blocks: ['orb', 'executive-headquarters', 'mission-engine'],
    complexity: 'medium',
    businessValue: 'medium',
    platformValue: 'medium',
    estimatedBuildTime: 'Cycle 8 parallel',
    architecturalReadiness: 'high',
    implementationReadiness: 'medium',
    rewriteRisk: 'medium',
    technicalDebtRisk: 'medium',
    currentStatus: 'planned',
  },
  {
    systemId: 'workspace-framework',
    officialName: 'Workspace Framework™',
    purpose: 'Workspace shell, scoped stores, context switching.',
    architecturalPhase: 5,
    priority: 'P0',
    topologicalOrder: 23,
    dependencies: ['organization-registry', 'authentication', 'permissions-engine'],
    blocks: ['executive-headquarters', 'department-framework', 'api-layer'],
    complexity: 'medium',
    businessValue: 'highest',
    platformValue: 'high',
    estimatedBuildTime: 'Cycle 10',
    architecturalReadiness: 'medium',
    implementationReadiness: 'medium',
    rewriteRisk: 'high',
    technicalDebtRisk: 'medium',
    currentStatus: 'planned',
  },
  {
    systemId: 'department-framework',
    officialName: 'Department Framework™',
    purpose: 'Department structures, responsibilities, rooms, workflows.',
    architecturalPhase: 5,
    priority: 'P1',
    topologicalOrder: 24,
    dependencies: ['company-registry', 'company-genome', 'workspace-framework'],
    blocks: ['executive-headquarters', 'mission-engine', 'analytics'],
    complexity: 'medium',
    businessValue: 'high',
    platformValue: 'high',
    estimatedBuildTime: 'Cycle 10 parallel',
    architecturalReadiness: 'medium',
    implementationReadiness: 'low',
    rewriteRisk: 'medium',
    technicalDebtRisk: 'medium',
    currentStatus: 'planned',
  },
  {
    systemId: 'executive-headquarters',
    officialName: 'Executive Headquarters™',
    purpose: 'Founder/company command environment.',
    architecturalPhase: 5,
    priority: 'P0',
    topologicalOrder: 25,
    dependencies: ['workspace-framework', 'company-registry', 'mission-engine', 'command-center', 'permissions-engine'],
    blocks: ['orb', 'atlas'],
    complexity: 'high',
    businessValue: 'highest',
    platformValue: 'medium',
    estimatedBuildTime: 'Cycle 10',
    architecturalReadiness: 'medium',
    implementationReadiness: 'low',
    rewriteRisk: 'high',
    technicalDebtRisk: 'high',
    currentStatus: 'planned',
  },
  {
    systemId: 'search',
    officialName: 'Search™',
    purpose: 'Permission-aware search over objects, knowledge, assets, missions.',
    architecturalPhase: 9,
    priority: 'P1',
    topologicalOrder: 26,
    dependencies: ['world-graph', 'knowledge-graph', 'permissions-engine', 'asset-registry'],
    blocks: ['atlas', 'orb', 'studio-exchange', 'api-layer'],
    complexity: 'medium',
    businessValue: 'high',
    platformValue: 'high',
    estimatedBuildTime: 'Cycle 7 parallel',
    architecturalReadiness: 'medium',
    implementationReadiness: 'low',
    rewriteRisk: 'high',
    technicalDebtRisk: 'medium',
    currentStatus: 'planned',
  },
  {
    systemId: 'atlas',
    officialName: 'Atlas™',
    purpose: 'Structural navigation map for systems, companies, rooms, worlds.',
    architecturalPhase: 5,
    priority: 'P2',
    topologicalOrder: 27,
    dependencies: ['world-graph', 'search', 'company-registry', 'workspace-framework'],
    blocks: ['executive-headquarters', 'orb', 'career-worlds'],
    complexity: 'medium',
    businessValue: 'medium',
    platformValue: 'medium',
    estimatedBuildTime: 'Post-Cycle 10',
    architecturalReadiness: 'medium',
    implementationReadiness: 'low',
    rewriteRisk: 'medium',
    technicalDebtRisk: 'low',
    currentStatus: 'planned',
  },
  {
    systemId: 'knowledge-retention',
    officialName: 'Knowledge Retention™',
    purpose: 'Summarizes, ages, promotes, archives knowledge and memory.',
    architecturalPhase: 3,
    priority: 'P2',
    topologicalOrder: 28,
    dependencies: ['knowledge-core', 'universal-decision-engine'],
    blocks: ['professional-memory', 'orb', 'research-engine'],
    complexity: 'medium',
    businessValue: 'medium',
    platformValue: 'high',
    estimatedBuildTime: 'Cycle 6 parallel',
    architecturalReadiness: 'medium',
    implementationReadiness: 'low',
    rewriteRisk: 'medium',
    technicalDebtRisk: 'medium',
    currentStatus: 'planned',
  },
  {
    systemId: 'research-engine',
    officialName: 'Research Engine™',
    purpose: 'Research questions, sources, findings, evidence, review.',
    architecturalPhase: 7,
    priority: 'P2',
    topologicalOrder: 29,
    dependencies: ['knowledge-core', 'codex', 'universal-decision-engine'],
    blocks: ['institute-of-knowledge', 'profession-brains', 'orb'],
    complexity: 'medium',
    businessValue: 'medium',
    platformValue: 'medium',
    estimatedBuildTime: 'Intelligence track',
    architecturalReadiness: 'medium',
    implementationReadiness: 'low',
    rewriteRisk: 'medium',
    technicalDebtRisk: 'medium',
    currentStatus: 'planned',
  },
  {
    systemId: 'institute-of-knowledge',
    officialName: 'Institute of Knowledge™',
    purpose: 'Canonical learning/publishing institution.',
    architecturalPhase: 3,
    priority: 'P2',
    topologicalOrder: 30,
    dependencies: ['knowledge-core', 'codex', 'research-engine'],
    blocks: ['profession-brains', 'career-worlds'],
    complexity: 'medium',
    businessValue: 'medium',
    platformValue: 'medium',
    estimatedBuildTime: 'Intelligence track',
    architecturalReadiness: 'medium',
    implementationReadiness: 'low',
    rewriteRisk: 'medium',
    technicalDebtRisk: 'low',
    currentStatus: 'planned',
  },
  {
    systemId: 'asset-registry',
    officialName: 'Asset Registry™',
    purpose: 'Source of truth for assets, files, provenance, rights, versions, usage.',
    architecturalPhase: 6,
    priority: 'P1',
    topologicalOrder: 31,
    dependencies: ['canonical-object-registry', 'identity-engine', 'permissions-engine'],
    blocks: ['scene-engine', 'asset-compiler', 'studio-foundry', 'studio-exchange'],
    complexity: 'high',
    businessValue: 'high',
    platformValue: 'high',
    estimatedBuildTime: 'Cycle 11',
    architecturalReadiness: 'high',
    implementationReadiness: 'low',
    rewriteRisk: 'high',
    technicalDebtRisk: 'high',
    currentStatus: 'planned',
  },
  {
    systemId: 'generation-recipes',
    officialName: 'Generation Recipes™',
    purpose: 'Reusable generation instructions, prompts, constraints, review rules.',
    architecturalPhase: 6,
    priority: 'P2',
    topologicalOrder: 32,
    dependencies: ['knowledge-core', 'asset-registry', 'universal-decision-engine', 'permissions-engine'],
    blocks: ['asset-compiler', 'studio-foundry', 'automation-engine'],
    complexity: 'high',
    businessValue: 'medium',
    platformValue: 'high',
    estimatedBuildTime: 'Cycle 11 parallel',
    architecturalReadiness: 'medium',
    implementationReadiness: 'low',
    rewriteRisk: 'high',
    technicalDebtRisk: 'medium',
    currentStatus: 'planned',
  },
  {
    systemId: 'asset-compiler',
    officialName: 'Asset Compiler™',
    purpose: 'Compiles assets/recipes into validated outputs.',
    architecturalPhase: 6,
    priority: 'P2',
    topologicalOrder: 33,
    dependencies: ['asset-registry', 'generation-recipes', 'event-bus'],
    blocks: ['scene-engine', 'studio-foundry', 'studio-exchange'],
    complexity: 'high',
    businessValue: 'medium',
    platformValue: 'high',
    estimatedBuildTime: 'Cycle 11 parallel',
    architecturalReadiness: 'medium',
    implementationReadiness: 'low',
    rewriteRisk: 'high',
    technicalDebtRisk: 'medium',
    currentStatus: 'planned',
  },
  {
    systemId: 'scene-engine',
    officialName: 'Scene Engine™',
    purpose: 'Structured scene composition for spatial/experience assembly.',
    architecturalPhase: 6,
    priority: 'P2',
    topologicalOrder: 34,
    dependencies: ['world-graph', 'asset-registry', 'asset-compiler'],
    blocks: ['experience-engine', 'simulation-engine', 'career-worlds'],
    complexity: 'high',
    businessValue: 'medium',
    platformValue: 'high',
    estimatedBuildTime: 'Creation track',
    architecturalReadiness: 'medium',
    implementationReadiness: 'low',
    rewriteRisk: 'high',
    technicalDebtRisk: 'medium',
    currentStatus: 'planned',
  },
  {
    systemId: 'experience-engine',
    officialName: 'Experience Engine™',
    purpose: 'Composes/renders experiences from canonical state.',
    architecturalPhase: 6,
    priority: 'P1',
    topologicalOrder: 35,
    dependencies: ['scene-engine', 'world-graph', 'workspace-framework', 'permissions-engine'],
    blocks: ['executive-headquarters', 'career-worlds', 'studio-exchange'],
    complexity: 'high',
    businessValue: 'high',
    platformValue: 'medium',
    estimatedBuildTime: 'Creation track',
    architecturalReadiness: 'medium',
    implementationReadiness: 'low',
    rewriteRisk: 'high',
    technicalDebtRisk: 'medium',
    currentStatus: 'planned',
  },
  {
    systemId: 'studio-foundry',
    officialName: 'Studio Foundry™',
    purpose: 'Creation environment for worlds, assets, scenes, experiences.',
    architecturalPhase: 6,
    priority: 'P2',
    topologicalOrder: 36,
    dependencies: ['blueprint-engine', 'asset-registry', 'generation-recipes', 'asset-compiler', 'scene-engine', 'experience-engine'],
    blocks: ['career-worlds', 'studio-exchange'],
    complexity: 'high',
    businessValue: 'medium',
    platformValue: 'medium',
    estimatedBuildTime: 'Creation track',
    architecturalReadiness: 'medium',
    implementationReadiness: 'low',
    rewriteRisk: 'high',
    technicalDebtRisk: 'medium',
    currentStatus: 'planned',
  },
  {
    systemId: 'analytics',
    officialName: 'Analytics™',
    purpose: 'Observes events and computes metrics/trends/evidence.',
    architecturalPhase: 9,
    priority: 'P1',
    topologicalOrder: 37,
    dependencies: ['event-bus', 'mission-engine', 'company-registry', 'world-graph'],
    blocks: ['executive-headquarters', 'simulation-engine', 'marketplace'],
    complexity: 'high',
    businessValue: 'high',
    platformValue: 'high',
    estimatedBuildTime: 'Cycle 9 parallel',
    architecturalReadiness: 'medium',
    implementationReadiness: 'low',
    rewriteRisk: 'high',
    technicalDebtRisk: 'high',
    currentStatus: 'planned',
  },
  {
    systemId: 'automation-engine',
    officialName: 'Automation Engine™',
    purpose: 'Executes delegated actions inside approved guardrails.',
    architecturalPhase: 4,
    priority: 'P1',
    topologicalOrder: 38,
    dependencies: ['command-center', 'workflow-engine', 'permissions-engine', 'universal-decision-engine'],
    blocks: ['integration-framework'],
    complexity: 'high',
    businessValue: 'high',
    platformValue: 'high',
    estimatedBuildTime: 'Post-Cycle 9',
    architecturalReadiness: 'medium',
    implementationReadiness: 'low',
    rewriteRisk: 'critical',
    technicalDebtRisk: 'critical',
    currentStatus: 'planned',
  },
  {
    systemId: 'professional-memory',
    officialName: 'Professional Memory™',
    purpose: 'Long-term profession-specific memory and lessons learned.',
    architecturalPhase: 7,
    priority: 'P2',
    topologicalOrder: 39,
    dependencies: ['knowledge-retention', 'identity-engine', 'mission-engine'],
    blocks: ['profession-brains', 'career-worlds', 'orb'],
    complexity: 'medium',
    businessValue: 'medium',
    platformValue: 'medium',
    estimatedBuildTime: 'Intelligence track',
    architecturalReadiness: 'medium',
    implementationReadiness: 'low',
    rewriteRisk: 'medium',
    technicalDebtRisk: 'medium',
    currentStatus: 'planned',
  },
  {
    systemId: 'profession-brains',
    officialName: 'Profession Brains™',
    purpose: 'Profession-specific cognition, standards, workflows, examples.',
    architecturalPhase: 7,
    priority: 'P1',
    topologicalOrder: 40,
    dependencies: ['institute-of-knowledge', 'research-engine', 'professional-memory', 'knowledge-core'],
    blocks: ['career-worlds', 'orb', 'simulation-engine'],
    complexity: 'high',
    businessValue: 'high',
    platformValue: 'medium',
    estimatedBuildTime: 'Intelligence track',
    architecturalReadiness: 'medium',
    implementationReadiness: 'low',
    rewriteRisk: 'high',
    technicalDebtRisk: 'medium',
    currentStatus: 'planned',
  },
  {
    systemId: 'simulation-engine',
    officialName: 'Simulation Engine™',
    purpose: 'Safe what-if environments for decisions, production, worlds, careers.',
    architecturalPhase: 7,
    priority: 'P2',
    topologicalOrder: 41,
    dependencies: ['universal-decision-engine', 'scene-engine', 'analytics', 'experience-engine'],
    blocks: ['career-worlds', 'orb', 'research-engine'],
    complexity: 'high',
    businessValue: 'medium',
    platformValue: 'medium',
    estimatedBuildTime: 'Postponed',
    architecturalReadiness: 'low',
    implementationReadiness: 'low',
    rewriteRisk: 'high',
    technicalDebtRisk: 'medium',
    currentStatus: 'deferred',
  },
  {
    systemId: 'career-worlds',
    officialName: 'Career Worlds™',
    purpose: 'Learning/career experience worlds.',
    architecturalPhase: 8,
    priority: 'P1',
    topologicalOrder: 42,
    dependencies: ['experience-engine', 'profession-brains', 'identity-engine', 'permissions-engine', 'mission-engine'],
    blocks: ['studio-exchange', 'professional-memory'],
    complexity: 'high',
    businessValue: 'high',
    platformValue: 'medium',
    estimatedBuildTime: 'Postponed',
    architecturalReadiness: 'low',
    implementationReadiness: 'low',
    rewriteRisk: 'critical',
    technicalDebtRisk: 'high',
    currentStatus: 'deferred',
  },
  {
    systemId: 'studio-exchange',
    officialName: 'Studio Exchange™',
    purpose: 'Product/economy surface for packaged value.',
    architecturalPhase: 8,
    priority: 'P0',
    topologicalOrder: 43,
    dependencies: ['identity-engine', 'permissions-engine', 'company-registry', 'asset-registry', 'search', 'analytics'],
    blocks: ['marketplace'],
    complexity: 'high',
    businessValue: 'highest',
    platformValue: 'medium',
    estimatedBuildTime: 'Postponed',
    architecturalReadiness: 'low',
    implementationReadiness: 'low',
    rewriteRisk: 'critical',
    technicalDebtRisk: 'critical',
    currentStatus: 'deferred',
  },
  {
    systemId: 'api-layer',
    officialName: 'API Layer™',
    purpose: 'Stable programmatic boundary for Studio OS capabilities.',
    architecturalPhase: 9,
    priority: 'P1',
    topologicalOrder: 44,
    dependencies: ['authentication', 'permissions-engine', 'command-center', 'search'],
    blocks: ['developer-sdk', 'integration-framework'],
    complexity: 'high',
    businessValue: 'high',
    platformValue: 'highest',
    estimatedBuildTime: 'Cycle 12',
    architecturalReadiness: 'medium',
    implementationReadiness: 'low',
    rewriteRisk: 'critical',
    technicalDebtRisk: 'critical',
    currentStatus: 'planned',
  },
  {
    systemId: 'marketplace',
    officialName: 'Marketplace™',
    purpose: 'Commerce infrastructure and external marketplace operations.',
    architecturalPhase: 8,
    priority: 'P0',
    topologicalOrder: 45,
    dependencies: ['studio-exchange', 'identity-engine', 'permissions-engine', 'api-layer'],
    blocks: ['developer-sdk'],
    complexity: 'high',
    businessValue: 'highest',
    platformValue: 'medium',
    estimatedBuildTime: 'Postponed',
    architecturalReadiness: 'low',
    implementationReadiness: 'low',
    rewriteRisk: 'critical',
    technicalDebtRisk: 'critical',
    currentStatus: 'deferred',
  },
  {
    systemId: 'integration-framework',
    officialName: 'Integration Framework™',
    purpose: 'External systems/plugins/adapters with event/workflow contracts.',
    architecturalPhase: 9,
    priority: 'P2',
    topologicalOrder: 46,
    dependencies: ['api-layer', 'event-bus', 'workflow-engine', 'permissions-engine'],
    blocks: ['developer-sdk'],
    complexity: 'high',
    businessValue: 'medium',
    platformValue: 'high',
    estimatedBuildTime: 'Cycle 12',
    architecturalReadiness: 'medium',
    implementationReadiness: 'low',
    rewriteRisk: 'critical',
    technicalDebtRisk: 'high',
    currentStatus: 'planned',
  },
  {
    systemId: 'developer-sdk',
    officialName: 'Developer SDK™',
    purpose: 'Public developer interface for Studio OS.',
    architecturalPhase: 9,
    priority: 'P2',
    topologicalOrder: 47,
    dependencies: ['api-layer', 'codex', 'integration-framework', 'permissions-engine'],
    blocks: [],
    complexity: 'high',
    businessValue: 'medium',
    platformValue: 'high',
    estimatedBuildTime: 'Cycle 12 parallel',
    architecturalReadiness: 'medium',
    implementationReadiness: 'low',
    rewriteRisk: 'critical',
    technicalDebtRisk: 'critical',
    currentStatus: 'deferred',
  },
];

/** 12-cycle implementation sequence from STUDIO_OS_BUILD_ORDER.md §11 */
export const BUILD_ORDER_SPRINT_CYCLES = [
  {
    cycle: 1,
    primaryBuild: 'Business Discovery™ MVP',
    primarySystemId: 'business-discovery',
    secondaryParallel: ['Blueprint Engine™ schema draft'],
    secondarySystemIds: ['blueprint-engine'],
    exitCondition: 'Discovery sessions produce canonical company inputs.',
  },
  {
    cycle: 2,
    primaryBuild: 'Company Genome™ platform MVP',
    primarySystemId: 'company-genome',
    secondaryParallel: ['Company Genome → Company Registry mapping'],
    secondarySystemIds: ['company-registry'],
    exitCondition: 'Business systems, flows, risks, events become reusable company objects.',
  },
  {
    cycle: 3,
    primaryBuild: 'Organization Registry™ + Company Registry™ MVP',
    primarySystemId: 'organization-registry',
    secondaryParallel: ['Identity actor envelope draft'],
    secondarySystemIds: ['identity-engine'],
    exitCondition: 'Studio OS has tenant/company/workspace truth.',
  },
  {
    cycle: 4,
    primaryBuild: 'Identity Engine™ + Authentication MVP',
    primarySystemId: 'identity-engine',
    secondaryParallel: ['Workspace Framework™ scope resolver'],
    secondarySystemIds: ['workspace-framework'],
    exitCondition: 'Actors can sign in and resolve workspace/company context.',
  },
  {
    cycle: 5,
    primaryBuild: 'Permissions Engine™ MVP',
    primarySystemId: 'permissions-engine',
    secondaryParallel: ['API permission middleware draft'],
    secondarySystemIds: ['api-layer'],
    exitCondition: 'Commands and APIs can be authorized/audited.',
  },
  {
    cycle: 6,
    primaryBuild: 'Knowledge Core™ MVP',
    primarySystemId: 'knowledge-core',
    secondaryParallel: ['Knowledge Graph™ schema'],
    secondarySystemIds: ['knowledge-graph'],
    exitCondition: 'Source-backed artifacts and citations exist.',
  },
  {
    cycle: 7,
    primaryBuild: 'World Graph™ MVP',
    primarySystemId: 'world-graph',
    secondaryParallel: ['Search™ index prototype'],
    secondarySystemIds: ['search'],
    exitCondition: 'Systems, companies, knowledge, missions, assets can be related.',
  },
  {
    cycle: 8,
    primaryBuild: 'Event Bus™ + Workflow Engine™ MVP',
    primarySystemId: 'event-bus',
    secondaryParallel: ['Notifications™ records'],
    secondarySystemIds: ['workflow-engine', 'notifications'],
    exitCondition: 'Cross-system work is evented, sequenced, auditable.',
  },
  {
    cycle: 9,
    primaryBuild: 'Mission Engine™ + Command Center™ MVP',
    primarySystemId: 'mission-engine',
    secondaryParallel: ['Analytics™ event ingestion'],
    secondarySystemIds: ['command-center', 'analytics'],
    exitCondition: 'Work can be commanded, tracked, blocked, completed.',
  },
  {
    cycle: 10,
    primaryBuild: 'Workspace Framework™ + Executive Headquarters™ shell',
    primarySystemId: 'workspace-framework',
    secondaryParallel: ['Department Framework™'],
    secondarySystemIds: ['executive-headquarters', 'department-framework'],
    exitCondition: 'Founder/company operating surface consumes stable state.',
  },
  {
    cycle: 11,
    primaryBuild: 'Asset Registry™ + Generation Recipes™ MVP',
    primarySystemId: 'asset-registry',
    secondaryParallel: ['Asset Compiler™ skeleton'],
    secondarySystemIds: ['generation-recipes', 'asset-compiler'],
    exitCondition: 'Creation work has provenance, recipes, and validation.',
  },
  {
    cycle: 12,
    primaryBuild: 'API Layer™ + Integration Framework™ internal MVP',
    primarySystemId: 'api-layer',
    secondaryParallel: ['Codex™ projection + Developer SDK draft'],
    secondarySystemIds: ['integration-framework', 'codex', 'developer-sdk'],
    exitCondition: 'Core capabilities can be safely exposed after permission contracts.',
  },
] as const;

/** Parallel tracks from STUDIO_OS_BUILD_ORDER.md §6 */
export const BUILD_ORDER_PARALLEL_TRACKS = [
  {
    trackId: 'business-truth',
    label: 'Business truth',
    canProceedAfter: ['canonical-object-registry', 'universal-interaction-engine', 'universal-decision-engine'],
    systemIds: ['business-discovery', 'company-genome', 'blueprint-engine'],
  },
  {
    trackId: 'trust-substrate',
    label: 'Trust substrate',
    canProceedAfter: ['organization-registry', 'identity-engine'],
    systemIds: ['authentication', 'permissions-engine', 'company-registry'],
  },
  {
    trackId: 'knowledge-substrate',
    label: 'Knowledge substrate',
    canProceedAfter: ['knowledge-core'],
    systemIds: ['knowledge-graph', 'codex', 'knowledge-retention'],
  },
  {
    trackId: 'operational-spine',
    label: 'Operational spine',
    canProceedAfter: ['event-bus', 'permissions-engine'],
    systemIds: ['workflow-engine', 'mission-engine', 'notifications'],
  },
  {
    trackId: 'executive-surfaces',
    label: 'Executive surfaces',
    canProceedAfter: ['mission-engine', 'command-center', 'workspace-framework'],
    systemIds: ['executive-headquarters', 'department-framework', 'atlas'],
  },
  {
    trackId: 'creation-substrate',
    label: 'Creation substrate',
    canProceedAfter: ['asset-registry'],
    systemIds: ['generation-recipes', 'asset-compiler', 'scene-engine'],
  },
  {
    trackId: 'intelligence-substrate',
    label: 'Intelligence substrate',
    canProceedAfter: ['knowledge-core', 'research-engine', 'knowledge-retention'],
    systemIds: ['research-engine', 'profession-brains', 'professional-memory'],
  },
  {
    trackId: 'external-platform',
    label: 'External platform',
    canProceedAfter: ['api-layer'],
    systemIds: ['integration-framework', 'developer-sdk', 'marketplace'],
  },
] as const;
