import {
  DDNA_SCENE_LAYER_LABELS,
  DDNA_SCENE_LAYERS,
  DDNA_SUBSYSTEM_VERSION,
  type DdnaSceneLayerId,
  type DdnaTokenCategory,
} from '../constants';
import type {
  DdnaAnimationHook,
  DdnaComponentSpec,
  DdnaDepartmentTheme,
  DdnaDesignToken,
  DdnaGlassMaterial,
  DdnaIconTreatment,
  DdnaLightingPreset,
  DdnaMotionPreset,
  DdnaNavigationRule,
  DdnaSceneLayerSpec,
  DdnaSceneTemplate,
  DdnaTypographyScale,
} from '../types';

function token(
  tokenId: string,
  name: string,
  category: DdnaTokenCategory,
  value: string,
  description: string,
  source = 'STUDIO_OS_DESIGN_DNA.md'
): DdnaDesignToken {
  return {
    tokenId,
    name,
    category,
    value,
    cssVariable: `--studio-ddna-${tokenId.replace(/\./g, '-')}`,
    description,
    immutable: true,
    source,
  };
}

export const SEED_DESIGN_TOKENS: DdnaDesignToken[] = [
  // Spacing
  token('space.3xs', 'Space 3XS', 'spacing', '4px', 'Micro gaps, icon-label rhythm.'),
  token('space.2xs', 'Space 2XS', 'spacing', '6px', 'Dense metadata gaps.'),
  token('space.xs', 'Space XS', 'spacing', '8px', 'Compact control padding.'),
  token('space.sm', 'Space SM', 'spacing', '12px', 'Card inner rhythm.'),
  token('space.md', 'Space MD', 'spacing', '16px', 'Panel inner rhythm.'),
  token('space.lg', 'Space LG', 'spacing', '24px', 'Section separation.'),
  token('space.xl', 'Space XL', 'spacing', '32px', 'Hero card separation.'),
  token('space.2xl', 'Space 2XL', 'spacing', '48px', 'Room section breaks.'),
  token('space.3xl', 'Space 3XL', 'spacing', '72px', 'Arrival / ceremony breaks.'),
  token('space.4xl', 'Space 4XL', 'spacing', '96px', 'Cinematic whitespace.'),
  // Grid
  token('grid.columns-desktop', 'Desktop Columns', 'grid', '12', 'Desktop 12-column grid.'),
  token('grid.columns-tablet', 'Tablet Columns', 'grid', '6', 'Tablet 6-column grid.'),
  token('grid.columns-mobile', 'Mobile Columns', 'grid', '1', 'Mobile single column.'),
  token('grid.max-width', 'Max Content Width', 'grid', '1440px', 'Room shell max width.'),
  token('grid.nav-rail-width', 'Nav Rail Width', 'grid', '260px', 'Spatial navigation rail.'),
  token('grid.hero-viewport-pct', 'Hero Viewport', 'grid', '68%', 'Hero zone viewport height desktop.'),
  // Typography
  token('type.label', 'Executive Label', 'typography', 'Futura PT Medium 10px uppercase', 'Section labels and CTAs.'),
  token('type.caption', 'Caption', 'typography', 'Futura PT Book 9px uppercase', 'Peripheral metadata.'),
  token('type.display', 'Grace Display', 'typography', 'Covered By Your Grace 18px', 'Hero titles and greetings.'),
  token('type.body', 'Body Calm', 'typography', 'Futura PT Book 14px', 'Executive summary body.'),
  token('type.action', 'Action Button', 'typography', 'Futura PT Medium 8px uppercase', 'Primary action labels.'),
  // Color (constitutional base)
  token('color.studio-red', 'Studio Red', 'color', '#EB1C24', 'Headquarters primary — brand anchor.'),
  token('color.executive-black', 'Executive Black', 'color', '#1A1A1A', 'Primary text and framing.'),
  token('color.executive-gold', 'Executive Gold', 'color', '#C9A962', 'Approval and ceremonial accent.'),
  token('color.marble-base', 'Marble Base', 'color', '#F8F6F3', 'Bright marble atmosphere base.'),
  // Glass
  token('glass.panel', 'Glass Panel', 'glass', 'rgba(255,255,255,0.55)', 'Primary acrylic panel.'),
  token('glass.panel-strong', 'Glass Panel Strong', 'glass', 'rgba(255,255,255,0.85)', 'Active nav and emphasis panels.'),
  token('glass.department-tint', 'Department Glass Tint', 'glass', 'department-derived', 'Glass tint from active department.'),
  // Blur
  token('blur.panel', 'Panel Blur', 'blur', '12px', 'Standard backdrop blur.'),
  token('blur.hero', 'Hero Blur', 'blur', '20px', 'Deep atmospheric blur.'),
  token('blur.dock', 'Dock Blur', 'blur', '16px', 'Ephemeral dock overlay blur.'),
  // Elevation
  token('elevation.panel', 'Panel Elevation', 'elevation', 'glass + blur 12px', 'Standard floating panel stack.'),
  token('elevation.card', 'Card Elevation', 'elevation', '0 4px 24px rgba(0,0,0,0.06)', 'Capability card shadow.'),
  token('elevation.orb', 'Orb Elevation', 'elevation', '0 8px 32px rgba(201,169,98,0.25)', 'Orb crystal glow stack.'),
  // Borders
  token('border.default', 'Default Border', 'borders', '1.3px solid rgba(0,0,0,0.12)', 'Standard panel border.'),
  token('border.department-active', 'Department Active Border', 'borders', '2px solid var(--studio-ddna-dept-primary)', 'Active nav department edge.'),
  token('border.radius.panel', 'Panel Radius', 'borders', '12px', 'Glass panel corner radius.'),
  token('border.radius.chip', 'Chip Radius', 'borders', '2px', 'Status chip radius.'),
  // Animation
  token('animation.timing-micro', 'Micro Timing', 'animation', '150ms', 'Micro-interactions.'),
  token('animation.timing-standard', 'Standard Timing', 'animation', '250ms', 'Panel transitions.'),
  token('animation.timing-cinematic', 'Cinematic Timing', 'animation', '600ms', 'Room arrival reveals.'),
  token('animation.easing-calm', 'Calm Easing', 'animation', 'cubic-bezier(0.4, 0, 0.2, 1)', 'Executive calm motion.'),
  token('animation.easing-expressive', 'Expressive Easing', 'animation', 'cubic-bezier(0.34, 1.2, 0.64, 1)', 'Creative department motion.'),
  // Lighting
  token('lighting.ambient-warm', 'Warm Ambient', 'lighting', 'linear-gradient(165deg, #f8f6f3, #efeae4)', 'Marble warm ambient.'),
  token('lighting.horizon-red', 'Red Horizon', 'lighting', 'linear-gradient(90deg, transparent, #EB1C2422)', 'HQ horizon accent.'),
  token('lighting.department-glow', 'Department Glow', 'lighting', 'radial-gradient(ellipse at top, var(--studio-ddna-dept-primary)22, transparent 70%)', 'Department ambient wash.'),
  // Particles
  token('particles.crystal-dust', 'Crystal Dust', 'particles', 'subtle gold refraction', 'Orb-adjacent restrained particles.'),
  token('particles.none', 'No Particles', 'particles', 'none', 'Utility and security rooms default.'),
  token('particles.flow-stream', 'Flow Stream', 'particles', 'teal directional dots', 'Operations workflow rooms.'),
  // Icons
  token('icon.size-sm', 'Icon SM', 'icons', '16px', 'Inline metadata icons.'),
  token('icon.size-md', 'Icon MD', 'icons', '24px', 'Navigation and capability icons.'),
  token('icon.size-lg', 'Icon LG', 'icons', '32px', 'Hero focal object icons.'),
  token('icon.treatment', 'Icon Treatment', 'icons', 'department-bound silhouette', 'Permanent color-bound silhouettes.'),
  // Cards
  token('card.padding', 'Card Padding', 'cards', '16px', 'Capability card interior.'),
  token('card.glass', 'Card Glass', 'cards', 'var(--studio-ddna-glass-panel)', 'Card surface material.'),
  token('card.hover-glow', 'Card Hover Glow', 'cards', '0 0 0 1px var(--studio-ddna-dept-accent)', 'Department-derived hover.'),
  // Buttons
  token('button.primary', 'Primary Button', 'buttons', 'department primary fill', 'One high-confidence action per viewport.'),
  token('button.secondary', 'Secondary Button', 'buttons', 'glass outline', 'Grouped secondary actions.'),
  token('button.ghost', 'Ghost Button', 'buttons', 'transparent + underline', 'Tertiary navigation actions.'),
  // Navigation
  token('nav.rail-width', 'Nav Rail', 'navigation', '260px', 'Spatial navigation rail width.'),
  token('nav.active-glow', 'Active Nav Glow', 'navigation', 'department primary directional glow', 'Cognitive location signal.'),
  token('nav.breadcrumb', 'Breadcrumb', 'navigation', 'Futura PT Medium 8px uppercase', 'Wayfinding typography.'),
  // Panels
  token('panel.glass', 'Panel Glass', 'panels', 'var(--studio-ddna-glass-panel)', 'Feature panel surface.'),
  token('panel.inspector', 'Inspector Panel', 'panels', 'floating overlay max 360px', 'Ephemeral inspector — never permanent.'),
  token('panel.capability-gap', 'Capability Gap', 'panels', '24px', 'Gap between capability panels.'),
];

type DeptSeed = Omit<DdnaDepartmentTheme, 'departmentId'> & { id: string };

const DEPT_ROWS: DeptSeed[] = [
  {
    id: 'headquarters',
    officialName: 'Headquarters',
    primaryColor: '#EB1C24',
    secondaryColor: '#1A1A1A',
    accentColor: '#C9A962',
    ambientLighting: 'warm marble + red horizon',
    glassTint: 'clear white + red edge',
    motionStyle: 'calm executive reveal',
    particleSystem: 'crystal dust restrained',
    notificationStyle: 'gold approval pulse',
    selectionStyle: 'decisive red underline',
    orbVariant: 'executive crystal',
    iconTreatment: 'studio red silhouette',
    sceneMood: 'executive lobby calm',
    animationPersonality: 'calm executive reveal',
    interactionEffects: 'decisive red underline, gold approval',
  },
  {
    id: 'executive-leadership',
    officialName: 'Executive Leadership',
    primaryColor: '#8B1E2D',
    secondaryColor: '#2B1A1E',
    accentColor: '#D6B36A',
    ambientLighting: 'boardroom warmth',
    glassTint: 'ivory/cabernet',
    motionStyle: 'measured ceremonial',
    particleSystem: 'none',
    notificationStyle: 'brass seal flash',
    selectionStyle: 'seal focus ring',
    orbVariant: 'cabernet crystal',
    iconTreatment: 'burgundy line-symbol',
    sceneMood: 'boardroom gravitas',
    animationPersonality: 'measured, ceremonial',
    interactionEffects: 'seal, approval, council focus',
  },
  {
    id: 'mission-control',
    officialName: 'Mission Control',
    primaryColor: '#F97316',
    secondaryColor: '#7C2D12',
    accentColor: '#FACC15',
    ambientLighting: 'command horizon',
    glassTint: 'amber glass',
    motionStyle: 'purposeful directional',
    particleSystem: 'mission amber trails',
    notificationStyle: 'queue pulse amber',
    selectionStyle: 'active queue glow',
    orbVariant: 'signal orange',
    iconTreatment: 'orange silhouette',
    sceneMood: 'command readiness',
    animationPersonality: 'purposeful, directional',
    interactionEffects: 'active queue glow',
  },
  {
    id: 'command-center',
    officialName: 'Command Center',
    primaryColor: '#EF4444',
    secondaryColor: '#111827',
    accentColor: '#F59E0B',
    ambientLighting: 'alert-ready but calm',
    glassTint: 'clear/red edge',
    motionStyle: 'precise quick',
    particleSystem: 'none',
    notificationStyle: 'action lock pulse',
    selectionStyle: 'confirmation pulse',
    orbVariant: 'command red',
    iconTreatment: 'slate-red bound',
    sceneMood: 'decisive operations',
    animationPersonality: 'precise, quick',
    interactionEffects: 'action lock, confirmation pulse',
  },
  {
    id: 'artificial-intelligence',
    officialName: 'Artificial Intelligence',
    primaryColor: '#6366F1',
    secondaryColor: '#312E81',
    accentColor: '#A5B4FC',
    ambientLighting: 'crystal violet',
    glassTint: 'violet glass',
    motionStyle: 'thinking breathing',
    particleSystem: 'model lattice pulse',
    notificationStyle: 'spectral soft reveal',
    selectionStyle: 'lattice focus',
    orbVariant: 'indigo intelligence',
    iconTreatment: 'indigo line-symbol',
    sceneMood: 'contemplative intelligence',
    animationPersonality: 'thinking, breathing',
    interactionEffects: 'model lattice pulse',
  },
  {
    id: 'orb',
    officialName: 'Orb',
    primaryColor: '#C9A962',
    secondaryColor: '#FFF8F0',
    accentColor: '#88C8FF',
    ambientLighting: 'living crystal glow',
    glassTint: 'acrylic clear',
    motionStyle: 'alive restrained',
    particleSystem: 'refraction shimmer',
    notificationStyle: 'radial projection',
    selectionStyle: 'crystal shimmer',
    orbVariant: 'champagne gold primary',
    iconTreatment: 'gold silhouette',
    sceneMood: 'living presence',
    animationPersonality: 'alive, restrained',
    interactionEffects: 'radial projection shimmer',
  },
  {
    id: 'creative',
    officialName: 'Creative',
    primaryColor: '#EC4899',
    secondaryColor: '#831843',
    accentColor: '#F9A8D4',
    ambientLighting: 'studio stage wash',
    glassTint: 'rose glass',
    motionStyle: 'expressive fluid',
    particleSystem: 'soft neon drift',
    notificationStyle: 'material hover glow',
    selectionStyle: 'rose edge glow',
    orbVariant: 'magenta studio',
    iconTreatment: 'magenta silhouette',
    sceneMood: 'studio expression',
    animationPersonality: 'expressive, fluid',
    interactionEffects: 'material hover glow',
  },
  {
    id: 'knowledge',
    officialName: 'Knowledge',
    primaryColor: '#2563EB',
    secondaryColor: '#1E3A8A',
    accentColor: '#93C5FD',
    ambientLighting: 'library skylight',
    glassTint: 'blue-white glass',
    motionStyle: 'quiet archival',
    particleSystem: 'none',
    notificationStyle: 'source highlight',
    selectionStyle: 'archive underline',
    orbVariant: 'knowledge blue',
    iconTreatment: 'navy line-symbol',
    sceneMood: 'library quiet',
    animationPersonality: 'quiet, archival',
    interactionEffects: 'source highlight',
  },
  {
    id: 'institute-of-knowledge',
    officialName: 'Institute of Knowledge',
    primaryColor: '#4F46E5',
    secondaryColor: '#312E81',
    accentColor: '#C4B5FD',
    ambientLighting: 'museum/library light',
    glassTint: 'violet-blue glass',
    motionStyle: 'reverent scholarly',
    particleSystem: 'manuscript dust',
    notificationStyle: 'canon glow',
    selectionStyle: 'shelf reveal',
    orbVariant: 'institute violet',
    iconTreatment: 'violet bound silhouette',
    sceneMood: 'institutional reverence',
    animationPersonality: 'reverent, scholarly',
    interactionEffects: 'canon glow, shelf reveal',
  },
  {
    id: 'operations',
    officialName: 'Operations',
    primaryColor: '#0D9488',
    secondaryColor: '#134E4A',
    accentColor: '#5EEAD4',
    ambientLighting: 'workflow stream light',
    glassTint: 'teal glass',
    motionStyle: 'efficient steady',
    particleSystem: 'flow stream',
    notificationStyle: 'status flow tick',
    selectionStyle: 'stream highlight',
    orbVariant: 'operations teal',
    iconTreatment: 'teal silhouette',
    sceneMood: 'workflow clarity',
    animationPersonality: 'efficient, steady',
    interactionEffects: 'status flow',
  },
  {
    id: 'engineering',
    officialName: 'Engineering',
    primaryColor: '#0284C7',
    secondaryColor: '#0C4A6E',
    accentColor: '#67E8F9',
    ambientLighting: 'blueprint glow',
    glassTint: 'cyan glass',
    motionStyle: 'exact mechanical',
    particleSystem: 'circuit trace',
    notificationStyle: 'diagnostic edge',
    selectionStyle: 'grid snap focus',
    orbVariant: 'engineering cyan',
    iconTreatment: 'blueprint line-symbol',
    sceneMood: 'precision build',
    animationPersonality: 'exact, mechanical',
    interactionEffects: 'diagnostic edge',
  },
  {
    id: 'infrastructure',
    officialName: 'Infrastructure',
    primaryColor: '#475569',
    secondaryColor: '#0F172A',
    accentColor: '#CBD5E1',
    ambientLighting: 'foundation light',
    glassTint: 'smoke-clear glass',
    motionStyle: 'stable minimal',
    particleSystem: 'none',
    notificationStyle: 'steel tick',
    selectionStyle: 'grid snap',
    orbVariant: 'slate foundation',
    iconTreatment: 'slate silhouette',
    sceneMood: 'foundation stability',
    animationPersonality: 'stable, minimal',
    interactionEffects: 'grid snap',
  },
  {
    id: 'platform',
    officialName: 'Platform',
    primaryColor: '#9333EA',
    secondaryColor: '#581C87',
    accentColor: '#D8B4FE',
    ambientLighting: 'platform aura',
    glassTint: 'purple glass',
    motionStyle: 'composed expandable',
    particleSystem: 'system glow motes',
    notificationStyle: 'module reveal',
    selectionStyle: 'purple edge',
    orbVariant: 'platform purple',
    iconTreatment: 'purple bound',
    sceneMood: 'system expansion',
    animationPersonality: 'composed, expandable',
    interactionEffects: 'module reveal',
  },
  {
    id: 'finance',
    officialName: 'Finance',
    primaryColor: '#A16207',
    secondaryColor: '#3F2D0B',
    accentColor: '#FDE68A',
    ambientLighting: 'ledger table light',
    glassTint: 'gold ivory',
    motionStyle: 'deliberate conservative',
    particleSystem: 'none',
    notificationStyle: 'value tick',
    selectionStyle: 'ledger underline',
    orbVariant: 'finance gold',
    iconTreatment: 'gold-brown silhouette',
    sceneMood: 'ledger deliberation',
    animationPersonality: 'deliberate, conservative',
    interactionEffects: 'value tick',
  },
  {
    id: 'research',
    officialName: 'Research',
    primaryColor: '#0891B2',
    secondaryColor: '#164E63',
    accentColor: '#A5F3FC',
    ambientLighting: 'lab/observatory',
    glassTint: 'cyan glass',
    motionStyle: 'investigative smooth',
    particleSystem: 'evidence motes',
    notificationStyle: 'evidence focus',
    selectionStyle: 'hypothesis ring',
    orbVariant: 'research cyan',
    iconTreatment: 'cyan line-symbol',
    sceneMood: 'observatory focus',
    animationPersonality: 'investigative, smooth',
    interactionEffects: 'evidence focus',
  },
  {
    id: 'marketing',
    officialName: 'Marketing',
    primaryColor: '#F43F5E',
    secondaryColor: '#881337',
    accentColor: '#FDA4AF',
    ambientLighting: 'campaign glow',
    glassTint: 'rose clear',
    motionStyle: 'energetic polished',
    particleSystem: 'launch sparkle restrained',
    notificationStyle: 'campaign pulse',
    selectionStyle: 'rose shimmer',
    orbVariant: 'marketing rose',
    iconTreatment: 'rose silhouette',
    sceneMood: 'campaign energy',
    animationPersonality: 'energetic, polished',
    interactionEffects: 'launch sparkle restrained',
  },
  {
    id: 'customer-experience',
    officialName: 'Customer Experience',
    primaryColor: '#14B8A6',
    secondaryColor: '#115E59',
    accentColor: '#99F6E4',
    ambientLighting: 'concierge warmth',
    glassTint: 'aqua glass',
    motionStyle: 'empathetic soft',
    particleSystem: 'response ripple',
    notificationStyle: 'care light pulse',
    selectionStyle: 'ripple highlight',
    orbVariant: 'cx aqua',
    iconTreatment: 'aqua bound',
    sceneMood: 'concierge warmth',
    animationPersonality: 'empathetic, soft',
    interactionEffects: 'response ripple',
  },
  {
    id: 'academy',
    officialName: 'Academy',
    primaryColor: '#7C3AED',
    secondaryColor: '#4C1D95',
    accentColor: '#DDD6FE',
    ambientLighting: 'study hall glow',
    glassTint: 'violet ivory',
    motionStyle: 'guided uplifting',
    particleSystem: 'progress constellation',
    notificationStyle: 'learning pulse',
    selectionStyle: 'constellation focus',
    orbVariant: 'academy violet',
    iconTreatment: 'violet silhouette',
    sceneMood: 'guided learning',
    animationPersonality: 'guided, uplifting',
    interactionEffects: 'progress constellation',
  },
  {
    id: 'simulation',
    officialName: 'Simulation',
    primaryColor: '#06B6D4',
    secondaryColor: '#155E75',
    accentColor: '#67E8F9',
    ambientLighting: 'theater horizon',
    glassTint: 'holographic cyan',
    motionStyle: 'cinematic controlled',
    particleSystem: 'scenario orbit',
    notificationStyle: 'hologram flash',
    selectionStyle: 'orbit focus',
    orbVariant: 'simulation cyan',
    iconTreatment: 'hologram line-symbol',
    sceneMood: 'theater scenario',
    animationPersonality: 'cinematic, controlled',
    interactionEffects: 'scenario orbit',
  },
  {
    id: 'automation',
    officialName: 'Automation',
    primaryColor: '#22C55E',
    secondaryColor: '#14532D',
    accentColor: '#86EFAC',
    ambientLighting: 'process glow',
    glassTint: 'green clear',
    motionStyle: 'rhythmic reliable',
    particleSystem: 'completion pulse dots',
    notificationStyle: 'completion pulse',
    selectionStyle: 'process tick',
    orbVariant: 'automation green',
    iconTreatment: 'green silhouette',
    sceneMood: 'process rhythm',
    animationPersonality: 'rhythmic, reliable',
    interactionEffects: 'completion pulse',
  },
  {
    id: 'security',
    officialName: 'Security',
    primaryColor: '#DC2626',
    secondaryColor: '#450A0A',
    accentColor: '#FCA5A5',
    ambientLighting: 'restrained warning',
    glassTint: 'red clear',
    motionStyle: 'still serious',
    particleSystem: 'none',
    notificationStyle: 'still warning edge',
    selectionStyle: 'risk ring',
    orbVariant: 'security red',
    iconTreatment: 'security bound',
    sceneMood: 'risk restraint',
    animationPersonality: 'still, serious',
    interactionEffects: 'still warning edge',
  },
  {
    id: 'support',
    officialName: 'Support',
    primaryColor: '#0EA5E9',
    secondaryColor: '#075985',
    accentColor: '#BAE6FD',
    ambientLighting: 'service glow',
    glassTint: 'sky glass',
    motionStyle: 'helpful light',
    particleSystem: 'reply ripple',
    notificationStyle: 'help light',
    selectionStyle: 'sky underline',
    orbVariant: 'support sky',
    iconTreatment: 'sky silhouette',
    sceneMood: 'service clarity',
    animationPersonality: 'helpful, light',
    interactionEffects: 'reply ripple',
  },
  {
    id: 'expansion',
    officialName: 'Expansion',
    primaryColor: '#10B981',
    secondaryColor: '#064E3B',
    accentColor: '#A7F3D0',
    ambientLighting: 'horizon growth',
    glassTint: 'emerald glass',
    motionStyle: 'optimistic spacious',
    particleSystem: 'map expansion motes',
    notificationStyle: 'growth pulse',
    selectionStyle: 'horizon glow',
    orbVariant: 'expansion emerald',
    iconTreatment: 'emerald bound',
    sceneMood: 'growth horizon',
    animationPersonality: 'optimistic, spacious',
    interactionEffects: 'map expansion',
  },
  {
    id: 'studio-exchange',
    officialName: 'Studio Exchange',
    primaryColor: '#D97706',
    secondaryColor: '#78350F',
    accentColor: '#FCD34D',
    ambientLighting: 'marketplace warmth',
    glassTint: 'amber glass',
    motionStyle: 'active transactional',
    particleSystem: 'listing glow',
    notificationStyle: 'trade tick',
    selectionStyle: 'amber edge',
    orbVariant: 'exchange amber',
    iconTreatment: 'amber silhouette',
    sceneMood: 'marketplace activity',
    animationPersonality: 'active, transactional',
    interactionEffects: 'listing glow',
  },
  {
    id: 'company-management',
    officialName: 'Company Management',
    primaryColor: '#64748B',
    secondaryColor: '#1E293B',
    accentColor: '#E2E8F0',
    ambientLighting: 'structured office',
    glassTint: 'slate clear',
    motionStyle: 'stable administrative',
    particleSystem: 'none',
    notificationStyle: 'record focus',
    selectionStyle: 'registry underline',
    orbVariant: 'company slate',
    iconTreatment: 'slate line-symbol',
    sceneMood: 'governance order',
    animationPersonality: 'stable, administrative',
    interactionEffects: 'record focus',
  },
  {
    id: 'profession-brains',
    officialName: 'Profession Brains',
    primaryColor: '#8B5CF6',
    secondaryColor: '#5B21B6',
    accentColor: '#C4B5FD',
    ambientLighting: 'role constellation',
    glassTint: 'violet glass',
    motionStyle: 'mentoring intelligent',
    particleSystem: 'skill graph glow',
    notificationStyle: 'brain pulse',
    selectionStyle: 'graph focus',
    orbVariant: 'profession violet',
    iconTreatment: 'violet bound',
    sceneMood: 'expertise constellation',
    animationPersonality: 'mentoring, intelligent',
    interactionEffects: 'skill graph glow',
  },
];

export const SEED_DEPARTMENT_THEMES: DdnaDepartmentTheme[] = DEPT_ROWS.map((row) => ({
  departmentId: row.id,
  officialName: row.officialName,
  primaryColor: row.primaryColor,
  secondaryColor: row.secondaryColor,
  accentColor: row.accentColor,
  ambientLighting: row.ambientLighting,
  glassTint: row.glassTint,
  motionStyle: row.motionStyle,
  particleSystem: row.particleSystem,
  notificationStyle: row.notificationStyle,
  selectionStyle: row.selectionStyle,
  orbVariant: row.orbVariant,
  iconTreatment: row.iconTreatment,
  sceneMood: row.sceneMood,
  divisionShade: row.secondaryColor,
  roomAccent: row.accentColor,
  animationPersonality: row.animationPersonality,
  interactionEffects: row.interactionEffects,
}));

const SCENE_LAYER_Z: Record<DdnaSceneLayerId, number> = {
  'hero-environment': 0,
  'primary-focal-object': 10,
  'executive-header': 20,
  'department-identity': 15,
  'capability-panels': 30,
  'navigation-layer': 40,
  'orb-layer': 100,
  'transition-layer': 200,
  footer: 50,
  'animation-hooks': 60,
};

export const SEED_SCENE_LAYERS: DdnaSceneLayerSpec[] = DDNA_SCENE_LAYERS.map((layerId) => ({
  layerId,
  zIndex: SCENE_LAYER_Z[layerId],
  required: layerId !== 'transition-layer',
  description: `${DDNA_SCENE_LAYER_LABELS[layerId]} — constitutional layer for every Headquarters scene.`,
  cssSelector: `[data-ddna-layer="${layerId}"]`,
  animationHook: layerId === 'animation-hooks' ? 'ddna-scene-enter' : undefined,
}));

export const SEED_SCENE_TEMPLATE: DdnaSceneTemplate = {
  templateId: 'hq-master-scene-v1',
  officialName: 'Headquarters Master Scene Template™',
  version: DDNA_SUBSYSTEM_VERSION,
  layers: SEED_SCENE_LAYERS,
  gridColumns: 12,
  maxContentWidthPx: 1440,
  heroViewportPct: 68,
  orbPersistent: true,
};

export const SEED_GLASS_MATERIALS: DdnaGlassMaterial[] = [
  {
    materialId: 'glass-executive-panel',
    name: 'Executive Glass Panel',
    background: 'rgba(255,255,255,0.55)',
    backdropBlur: '12px',
    border: '1.3px solid rgba(0,0,0,0.12)',
    tintDepartmentAware: true,
    legibilityRule: 'Department tint may influence glass but cannot reduce legibility.',
  },
  {
    materialId: 'glass-hero-atmosphere',
    name: 'Hero Atmosphere Glass',
    background: 'rgba(255,255,255,0.35)',
    backdropBlur: '20px',
    border: '1px solid rgba(255,255,255,0.4)',
    tintDepartmentAware: true,
    legibilityRule: 'Atmosphere layer — low density, high breath.',
  },
  {
    materialId: 'glass-capability-card',
    name: 'Capability Card Glass',
    background: 'rgba(255,255,255,0.65)',
    backdropBlur: '8px',
    border: '1.3px solid rgba(0,0,0,0.08)',
    tintDepartmentAware: true,
    legibilityRule: 'Cards float as glass surfaces with environmental role.',
  },
  {
    materialId: 'glass-dock-overlay',
    name: 'Ephemeral Dock Glass',
    background: 'rgba(255,255,255,0.72)',
    backdropBlur: '16px',
    border: '1.3px solid rgba(0,0,0,0.15)',
    tintDepartmentAware: false,
    legibilityRule: 'Floating overlay — never permanent if competing with focal object.',
  },
];

export const SEED_LIGHTING_PRESETS: DdnaLightingPreset[] = [
  {
    presetId: 'light-marble-warm',
    name: 'Marble Warm Ambient',
    ambientColor: '#F8F6F3',
    horizonGradient: 'linear-gradient(165deg, #f8f6f3 0%, #efeae4 50%, #faf8f5 100%)',
    keyLightDirection: 'top-left warm',
    fillIntensity: 0.85,
    departmentBindable: true,
  },
  {
    presetId: 'light-department-wash',
    name: 'Department Color Wash',
    ambientColor: 'department-primary-12pct',
    horizonGradient: 'radial-gradient(ellipse at top, var(--studio-ddna-dept-primary)18, transparent 65%)',
    keyLightDirection: 'hero-top',
    fillIntensity: 0.7,
    departmentBindable: true,
  },
  {
    presetId: 'light-library-skylight',
    name: 'Library Skylight',
    ambientColor: '#EFF6FF',
    horizonGradient: 'linear-gradient(180deg, #DBEAFE 0%, #F8FAFC 100%)',
    keyLightDirection: 'overhead diffuse',
    fillIntensity: 0.9,
    departmentBindable: false,
  },
  {
    presetId: 'light-command-horizon',
    name: 'Command Horizon',
    ambientColor: '#FFF7ED',
    horizonGradient: 'linear-gradient(90deg, transparent, var(--studio-ddna-dept-primary)22)',
    keyLightDirection: 'horizon-right',
    fillIntensity: 0.75,
    departmentBindable: true,
  },
];

export const SEED_MOTION_PRESETS: DdnaMotionPreset[] = [
  {
    presetId: 'motion-executive-calm',
    name: 'Executive Calm',
    entrance: 'fade + scale 0.98→1 over 600ms',
    exit: 'fade out 250ms',
    hover: 'translateY(-1px) 150ms',
    focus: 'department tint ring 2px',
    departmentDerived: true,
  },
  {
    presetId: 'motion-purposeful',
    name: 'Purposeful Directional',
    entrance: 'slide-from-right 400ms',
    exit: 'slide-to-left 250ms',
    hover: 'directional glow 150ms',
    focus: 'active queue glow',
    departmentDerived: true,
  },
  {
    presetId: 'motion-expressive',
    name: 'Expressive Fluid',
    entrance: 'fade + blur resolve 500ms',
    exit: 'scale-down fade 300ms',
    hover: 'material glow 200ms',
    focus: 'accent edge pulse',
    departmentDerived: true,
  },
  {
    presetId: 'motion-ceremonial',
    name: 'Ceremonial Measured',
    entrance: 'slow reveal 800ms',
    exit: 'dissolve 400ms',
    hover: 'gold underline reveal',
    focus: 'seal ring',
    departmentDerived: false,
  },
];

export const SEED_ANIMATION_HOOKS: DdnaAnimationHook[] = [
  { hookId: 'ddna-scene-enter', name: 'Scene Enter', trigger: 'route-change', durationMs: 600, easing: 'cubic-bezier(0.4, 0, 0.2, 1)', layerTarget: 'hero-environment' },
  { hookId: 'ddna-panel-reveal', name: 'Panel Reveal', trigger: 'scroll-into-view', durationMs: 400, easing: 'cubic-bezier(0.4, 0, 0.2, 1)', layerTarget: 'capability-panels' },
  { hookId: 'ddna-orb-pulse', name: 'Orb Pulse', trigger: 'recommendation-ready', durationMs: 1500, easing: 'ease-in-out', layerTarget: 'orb-layer' },
  { hookId: 'ddna-nav-active', name: 'Nav Active Glow', trigger: 'nav-select', durationMs: 250, easing: 'ease-out', layerTarget: 'navigation-layer' },
  { hookId: 'ddna-transition-carry', name: 'Department Transition', trigger: 'department-change', durationMs: 500, easing: 'cubic-bezier(0.4, 0, 0.2, 1)', layerTarget: 'transition-layer' },
];

export const SEED_TYPOGRAPHY_SCALE: DdnaTypographyScale[] = [
  { scaleId: 'type-room-title', role: 'Room Title', fontFamily: 'Covered By Your Grace', fontSize: '18px', fontWeight: '400', letterSpacing: '0.02em', textTransform: 'none', lineHeight: '1.3' },
  { scaleId: 'type-department-mark', role: 'Department Mark', fontFamily: 'Futura PT Medium', fontSize: '10px', fontWeight: '500', letterSpacing: '0.12em', textTransform: 'uppercase', lineHeight: '1.2' },
  { scaleId: 'type-executive-summary', role: 'Executive Summary', fontFamily: 'Futura PT Book', fontSize: '14px', fontWeight: '400', letterSpacing: '0.01em', textTransform: 'none', lineHeight: '1.6' },
  { scaleId: 'type-capability-label', role: 'Capability Label', fontFamily: 'Futura PT Medium', fontSize: '8px', fontWeight: '500', letterSpacing: '0.14em', textTransform: 'uppercase', lineHeight: '1.2' },
  { scaleId: 'type-metadata', role: 'Metadata', fontFamily: 'Futura PT Book', fontSize: '9px', fontWeight: '400', letterSpacing: '0.1em', textTransform: 'uppercase', lineHeight: '1.3' },
  { scaleId: 'type-breadcrumb', role: 'Breadcrumb', fontFamily: 'Futura PT Medium', fontSize: '8px', fontWeight: '500', letterSpacing: '0.12em', textTransform: 'uppercase', lineHeight: '1.2' },
];

export const SEED_COMPONENTS: DdnaComponentSpec[] = [
  { componentId: 'ddna-glass-panel', officialName: 'Glass Panel™', category: 'glass', description: 'Primary floating glass surface for feature panels.', tokenBindings: ['glass.panel', 'blur.panel', 'border.default'], sceneLayer: 'capability-panels', reuseScore: 98 },
  { componentId: 'ddna-executive-header', officialName: 'Executive Header™', category: 'header', description: 'Room arrival header with department mark and primary action.', tokenBindings: ['type.department-mark', 'type.room-title', 'nav.breadcrumb'], sceneLayer: 'executive-header', reuseScore: 96 },
  { componentId: 'ddna-capability-card', officialName: 'Capability Card™', category: 'card', description: 'Actionable capability unit — not arbitrary stats.', tokenBindings: ['card.padding', 'card.glass', 'card.hover-glow'], sceneLayer: 'capability-panels', reuseScore: 94 },
  { componentId: 'ddna-primary-action', officialName: 'Primary Action Button™', category: 'button', description: 'One high-confidence action per viewport moment.', tokenBindings: ['button.primary', 'type.action'], sceneLayer: 'capability-panels', reuseScore: 92 },
  { componentId: 'ddna-spatial-nav-rail', officialName: 'Spatial Nav Rail™', category: 'navigation', description: 'Cognitive navigation rail with department color binding.', tokenBindings: ['nav.rail-width', 'nav.active-glow', 'border.department-active'], sceneLayer: 'navigation-layer', reuseScore: 95 },
  { componentId: 'ddna-hero-environment', officialName: 'Hero Environment™', category: 'panel', description: 'Atmosphere layer establishing place and mood.', tokenBindings: ['lighting.ambient-warm', 'lighting.department-glow', 'grid.hero-viewport-pct'], sceneLayer: 'hero-environment', reuseScore: 97 },
  { componentId: 'ddna-focal-object', officialName: 'Primary Focal Object™', category: 'panel', description: 'One dominant object of attention per room.', tokenBindings: ['elevation.card', 'space.2xl'], sceneLayer: 'primary-focal-object', reuseScore: 93 },
  { componentId: 'ddna-department-identity', officialName: 'Department Identity Strip™', category: 'panel', description: 'Cognitive location — color, mark, ambient light.', tokenBindings: ['color.studio-red', 'lighting.department-glow'], sceneLayer: 'department-identity', reuseScore: 91 },
  { componentId: 'ddna-orb-mount', officialName: 'Orb Layer Mount™', category: 'orb', description: 'Bottom-weighted persistent Orb integration.', tokenBindings: ['elevation.orb', 'particles.crystal-dust'], sceneLayer: 'orb-layer', reuseScore: 99 },
  { componentId: 'ddna-scene-footer', officialName: 'Context Ribbon Footer™', category: 'panel', description: 'Metrics, state, provenance, validation ribbon.', tokenBindings: ['type.metadata', 'panel.glass'], sceneLayer: 'footer', reuseScore: 88 },
  { componentId: 'ddna-transition-veil', officialName: 'Transition Layer Veil™', category: 'panel', description: 'Department color continuity across room transitions.', tokenBindings: ['animation.timing-cinematic', 'animation.easing-calm'], sceneLayer: 'transition-layer', reuseScore: 90 },
  { componentId: 'ddna-typography-stack', officialName: 'Typography Stack™', category: 'typography', description: 'Futura + Grace hierarchy for all inherited scenes.', tokenBindings: ['type.label', 'type.display', 'type.body'], reuseScore: 100 },
];

export const SEED_NAVIGATION_RULES: DdnaNavigationRule[] = [
  { ruleId: 'nav-dept-color', layer: 'department-color', description: 'Permanent primary color for operating domain.', derivation: 'From Department Theme Registry™ primaryColor.' },
  { ruleId: 'nav-division-shade', layer: 'division-shade', description: 'Derived tone for sub-domain/wing.', derivation: 'secondaryColor at 85% opacity for rails.' },
  { ruleId: 'nav-room-accent', layer: 'room-accent', description: 'Room/focal object accent.', derivation: 'accentColor for selected cards and object glow.' },
  { ruleId: 'nav-interactive', layer: 'interactive-state', description: 'Hover/active/focus/pressed.', derivation: 'Must derive from department primary — never generic blue.' },
  { ruleId: 'nav-notification', layer: 'notification-state', description: 'Semantic overlay for info/success/warning/risk.', derivation: 'Semantic colors — never replace department identity.' },
];

export const SEED_ICON_TREATMENTS: DdnaIconTreatment[] = [
  { treatmentId: 'icon-dept-silhouette', name: 'Department Silhouette', style: 'department-bound', colorRule: 'Fill with department primary; stroke none.', sizeTokens: ['icon.size-sm', 'icon.size-md', 'icon.size-lg'] },
  { treatmentId: 'icon-line-symbol', name: 'Line Symbol', style: 'line-symbol', colorRule: '1.3px stroke department primary; fill transparent.', sizeTokens: ['icon.size-md', 'icon.size-lg'] },
  { treatmentId: 'icon-permanent-silhouette', name: 'Permanent Silhouette', style: 'silhouette', colorRule: 'Simple silhouette — color-bound, no gradients.', sizeTokens: ['icon.size-sm', 'icon.size-md'] },
];
