import { RENDER_QUEUE_PHILOSOPHY } from './constants';
import { bootstrapRenderQueueStore } from './store';
import type { RenderQueueStore } from './types';

const now = Date.now();
const mins = (m: number) => new Date(now - m * 60_000).toISOString();

export function buildRenderQueueSeed(): Partial<RenderQueueStore> {
  return {
    companyName: 'NDXBOOK',
    selectedRenderId: 'rq-lace-mastery',
    batchMode: false,
    selectedBatchIds: [],
    dashboard: {
      summary:
        'RENDER QUEUE V1.0 · NDXBOOK production floor · 7 active pipelines · founders always see what AI is doing.',
      activeRenders: 5,
      pausedRenders: 1,
      queuedCount: 2,
      readyForReview: 1,
      avgConfidencePct: 87,
      floorActivityPct: 71,
    },
    philosophy: [...RENDER_QUEUE_PHILOSOPHY],
    renders: [
      {
        id: 'rq-lace-mastery',
        productionTitle: 'CUTTING YOUR LACE · LACE MASTERY',
        pageRoute: '/ndxbook/lace-mastery/cutting-your-lace',
        stage: 'generating-voice',
        controlState: 'running',
        priority: 'high',
        progressPct: 62,
        startedAt: mins(18),
        elapsedSec: 1080,
        estimatedCompletionSec: 420,
        aiWorker: 'VOICE AGENT · ELEVENLABS POOL',
        confidencePct: 91,
        warnings: ['Voice rendering slower today — elevated queue load on voice pool.'],
        sourceProductionJobId: 'ps-job-lace-mastery',
      },
      {
        id: 'rq-slay-report',
        productionTitle: 'SLAY REPORT · WEEK 12',
        pageRoute: '/ndxbook/slay-report/week-12',
        stage: 'building-motion-graphics',
        controlState: 'running',
        priority: 'normal',
        batchId: 'batch-demo-1',
        progressPct: 44,
        startedAt: mins(32),
        elapsedSec: 1920,
        estimatedCompletionSec: 780,
        aiWorker: 'MOTION AGENT · AFTER EFFECTS SIM',
        confidencePct: 84,
        warnings: ['Motion graphics still processing — chart animations queued behind NOIR macro set.'],
        sourceProductionJobId: 'ps-job-slay-report',
      },
      {
        id: 'rq-noir-color',
        productionTitle: 'NOIR COLOR THEORY · DEPTH & DIMENSION',
        pageRoute: '/ndxbook/noir/color-theory',
        stage: 'rendering',
        controlState: 'running',
        priority: 'normal',
        progressPct: 78,
        startedAt: mins(45),
        elapsedSec: 2700,
        estimatedCompletionSec: 240,
        aiWorker: 'RENDER AGENT · GPU CLUSTER A',
        confidencePct: 94,
        warnings: [],
        sourceProductionJobId: 'ps-job-noir-color',
      },
      {
        id: 'rq-membership-guide',
        productionTitle: 'MEMBERSHIP VALUE GUIDE · PREMIUM PATH',
        pageRoute: '/ndxbook/membership/value-guide',
        stage: 'creating-thumbnail',
        controlState: 'paused',
        priority: 'normal',
        progressPct: 35,
        startedAt: mins(12),
        elapsedSec: 720,
        estimatedCompletionSec: 600,
        aiWorker: 'THUMBNAIL AGENT · BRAND CONCIERGE',
        confidencePct: 72,
        warnings: ['Thumbnail being regenerated due to confidence below threshold.'],
        sourceProductionJobId: 'ps-job-membership-guide',
      },
      {
        id: 'rq-spring-launch',
        productionTitle: 'SPRING COLLECTION LAUNCH · CAMPAIGN FILM',
        pageRoute: '/ndxbook/campaigns/spring-collection',
        stage: 'ready-for-review',
        controlState: 'complete',
        priority: 'normal',
        progressPct: 100,
        startedAt: mins(90),
        elapsedSec: 5400,
        estimatedCompletionSec: 0,
        aiWorker: 'EXPORT AGENT · DISTRIBUTION',
        confidencePct: 92,
        warnings: [],
        sourceProductionJobId: 'ps-job-spring-launch',
      },
      {
        id: 'rq-community-spotlight',
        productionTitle: 'COMMUNITY SPOTLIGHT · READER STORIES',
        pageRoute: '/ndxbook/community/spotlight',
        stage: 'queued',
        controlState: 'running',
        priority: 'normal',
        progressPct: 0,
        startedAt: mins(2),
        elapsedSec: 120,
        estimatedCompletionSec: 1800,
        aiWorker: 'SCRIPT AGENT · WRITING DNA',
        confidencePct: 88,
        warnings: [],
      },
      {
        id: 'rq-install-guide',
        productionTitle: 'INSTALL GUIDE · SOFT WAVE UNIT',
        pageRoute: '/ndxbook/guides/soft-wave-install',
        stage: 'queued',
        controlState: 'running',
        priority: 'high',
        progressPct: 0,
        startedAt: mins(1),
        elapsedSec: 60,
        estimatedCompletionSec: 1200,
        aiWorker: 'SCRIPT AGENT · WRITING DNA',
        confidencePct: 90,
        warnings: ['Priority rendering enabled — moved ahead of standard queue.'],
      },
      {
        id: 'rq-brand-story',
        productionTitle: 'BRAND STORY · FOUNDER PROMISE',
        pageRoute: '/ndxbook/brand/founder-promise',
        stage: 'optimizing',
        controlState: 'running',
        priority: 'normal',
        progressPct: 55,
        startedAt: mins(28),
        elapsedSec: 1680,
        estimatedCompletionSec: 360,
        aiWorker: 'OPTIMIZE AGENT · PLATFORM ADAPT',
        confidencePct: 86,
        warnings: [],
      },
    ],
    intelligenceAlerts: [
      {
        id: 'alert-1',
        renderJobId: 'rq-lace-mastery',
        message: 'Voice rendering slower today — ElevenLabs pool at 78% capacity. Est. +6 min on this job.',
        severity: 'warning',
        createdAt: mins(5),
      },
      {
        id: 'alert-2',
        renderJobId: 'rq-slay-report',
        message: 'Motion graphics still processing — chart layer waiting on Asset Director approved macro set.',
        severity: 'info',
        createdAt: mins(8),
      },
      {
        id: 'alert-3',
        renderJobId: 'rq-membership-guide',
        message: 'Thumbnail being regenerated due to confidence below threshold (72% → target 85%). Brand Concierge reviewing.',
        severity: 'warning',
        createdAt: mins(3),
      },
      {
        id: 'alert-4',
        renderJobId: 'rq-install-guide',
        message: 'Priority rendering active — this job moved ahead of 3 standard-queue productions.',
        severity: 'info',
        createdAt: mins(1),
      },
    ],
  };
}

export function bootstrapRenderQueuePlatform(): void {
  bootstrapRenderQueueStore(buildRenderQueueSeed());
}
