import type { ContextualOrbToolbelt, HeroObjectDefinition } from './types';

const SHARED_SURFACES: HeroObjectDefinition['surfaces'] = [
  'orb',
  'atlas',
  'studio-foundry',
  'asset-registry',
  'museum',
  'knowledge-core',
];

const standardEditions: HeroObjectDefinition['editions'] = [
  {
    editionType: 'standard',
    displayName: 'Standard Edition',
    unlockCondition: 'Destination available in Studio World™',
    scarcity: 'common',
  },
  {
    editionType: 'founder',
    displayName: 'Founder Edition',
    materialOverride: 'smoked crystal with founder-gold inlay',
    unlockCondition: 'Unlocked by the founding workspace that first activates the destination.',
    scarcity: 'rare',
  },
  {
    editionType: 'golden',
    displayName: 'Golden Edition',
    materialOverride: 'brushed gold, luminous enamel, and refracted inner light',
    unlockCondition: 'Unlocked when the destination completes a Golden Build™ or approved production milestone.',
    scarcity: 'legendary',
  },
];

function motion(personality: string): HeroObjectDefinition['motion'] {
  return {
    ambientMotion: 'Slow museum-grade float with a subtle tilt toward the founder.',
    internalEnergy: 'Soft internal pulse that brightens when the destination has live work.',
    materialBehavior: 'Luxury material shifts between matte depth and polished highlight as context changes.',
    lightRefraction: 'Edges refract nearby scene color without becoming noisy.',
    environmentalReflection: 'Reflects the current room lighting so it belongs to the place where it appears.',
    personality,
  };
}

function history(title: string): HeroObjectDefinition['usageHistory'] {
  return [
    { date: '2026-07-08', title: 'Introduced', note: title },
  ];
}

export const HERO_OBJECTS: HeroObjectDefinition[] = [
  {
    id: 'world-atlas-globe',
    displayName: 'World Atlas Globe™',
    destinationId: 'world-atlas',
    destinationLabel: 'World Atlas™',
    destinationRouteId: 'world-atlas',
    destinationPath: '/admin/studio/world-atlas',
    summary: 'A suspended living globe that opens Studio World as a spatial civilization map.',
    silhouetteFamily: 'orbital-globe',
    silhouetteLaw: 'Perfect orbital sphere with a halo ring; no other Hero Object may use the globe-plus-ring silhouette.',
    material: 'smoked crystal, holographic continents, platinum orbit ring',
    creator: 'Studio Foundry™',
    dateIntroduced: '2026-07-08',
    version: '1.0.0',
    assetRegistryId: 'hero-object-world-atlas-globe-v1',
    worldGraphSlug: 'world-atlas-globe',
    foundryProductLine: 'Navigation Relics™',
    surfaces: [...SHARED_SURFACES, 'expeditions'],
    motion: motion('curious cartographer'),
    editions: standardEditions,
    usageHistory: history('Created as the primary Hero Object for spatial navigation.'),
    evolutionTimeline: history('D09 established it as a collectible navigation primitive.'),
    contextualOrbPlacements: [
      { contextId: 'command-center', contextLabel: 'Command Center™', relevanceRank: 1, reason: 'Primary world navigation object.' },
    ],
    tags: ['atlas', 'navigation', 'command-center'],
  },
  {
    id: 'mission-control-console',
    displayName: 'Mission Control Console™',
    destinationId: 'mission-control',
    destinationLabel: 'Mission Control™',
    destinationRouteId: 'mission-control',
    destinationPath: '/admin/studio/overview',
    summary: 'A miniature executive command console that calls up missions, approvals, and live operational state.',
    silhouetteFamily: 'performance-monolith',
    silhouetteLaw: 'Low angled command slab with five glowing executive keys; cannot share a rectangular app-tile silhouette.',
    material: 'black glass, brushed graphite, warm gold key light',
    creator: 'Studio Foundry™',
    dateIntroduced: '2026-07-08',
    version: '1.0.0',
    assetRegistryId: 'hero-object-mission-control-console-v1',
    worldGraphSlug: 'mission-control-console',
    foundryProductLine: 'Command Relics™',
    surfaces: [...SHARED_SURFACES, 'production-board'],
    motion: motion('decisive operator'),
    editions: standardEditions,
    usageHistory: history('Assigned to Command Center toolbelt.'),
    evolutionTimeline: history('D09 established it as a toolbelt object rather than a menu icon.'),
    contextualOrbPlacements: [
      { contextId: 'command-center', contextLabel: 'Command Center™', relevanceRank: 2, reason: 'Founder command and operational awareness.' },
    ],
    tags: ['mission-control', 'operations', 'command-center'],
  },
  {
    id: 'daily-brief-lens',
    displayName: 'Daily Brief Lens™',
    destinationId: 'daily-brief',
    destinationLabel: 'Daily Brief™',
    destinationRouteId: 'chief-of-staff',
    destinationPath: '/admin/studio/chief-of-staff',
    summary: 'A crystal briefing lens that condenses today into one founder-readable signal.',
    silhouetteFamily: 'holographic-constellation',
    silhouetteLaw: 'Single magnifying lens with orbiting briefing motes; no other object may use the lens-and-motes outline.',
    material: 'clear sapphire glass, pale champagne rim, moving ink-light',
    creator: 'Studio Foundry™',
    dateIntroduced: '2026-07-08',
    version: '1.0.0',
    assetRegistryId: 'hero-object-daily-brief-lens-v1',
    worldGraphSlug: 'daily-brief-lens',
    foundryProductLine: 'Command Relics™',
    surfaces: SHARED_SURFACES,
    motion: motion('calm chief of staff'),
    editions: standardEditions,
    usageHistory: history('Assigned to Command Center toolbelt for daily orientation.'),
    evolutionTimeline: history('D09 made briefing access a living artifact.'),
    contextualOrbPlacements: [
      { contextId: 'command-center', contextLabel: 'Command Center™', relevanceRank: 3, reason: 'Daily orientation belongs near executive arrival.' },
    ],
    tags: ['daily-brief', 'chief-of-staff', 'command-center'],
  },
  {
    id: 'knowledge-core-crystal',
    displayName: 'Knowledge Core Crystal™',
    destinationId: 'knowledge-core',
    destinationLabel: 'Knowledge Core™',
    destinationRouteId: 'knowledge-hub',
    destinationPath: '/admin/studio/knowledge-hub',
    summary: 'A faceted memory crystal containing canon, history, and approved institutional knowledge.',
    silhouetteFamily: 'archive-scroll',
    silhouetteLaw: 'Tall faceted crystal with an inner archive spine; cannot resemble generic document or book icons.',
    material: 'frosted crystal, archival gold filament, deep blue memory core',
    creator: 'Studio Foundry™',
    dateIntroduced: '2026-07-08',
    version: '1.0.0',
    assetRegistryId: 'hero-object-knowledge-core-crystal-v1',
    worldGraphSlug: 'knowledge-core-crystal',
    foundryProductLine: 'Knowledge Relics™',
    surfaces: [...SHARED_SURFACES, 'innovation-hall'],
    motion: motion('quiet archivist'),
    editions: standardEditions,
    usageHistory: history('Assigned to Command Center toolbelt as canonical memory access.'),
    evolutionTimeline: history('D09 established Knowledge Core access as a collectible artifact.'),
    contextualOrbPlacements: [
      { contextId: 'command-center', contextLabel: 'Command Center™', relevanceRank: 4, reason: 'Architecture and memory are high-relevance command actions.' },
    ],
    tags: ['knowledge-core', 'memory', 'canon'],
  },
  {
    id: 'production-board-slate',
    displayName: 'Production Board Slate™',
    destinationId: 'production-board',
    destinationLabel: 'Production Board™',
    destinationRouteId: 'production-orchestrator',
    destinationPath: '/admin/studio/production-orchestrator',
    summary: 'A living production slate that tracks idea, architecture, implementation, assets, motion, and review.',
    silhouetteFamily: 'architectural-table',
    silhouetteLaw: 'Clapper-slate meets architectural drafting board; no other object may use the hinged slate silhouette.',
    material: 'black ceramic, gold hinge, illuminated pipeline grooves',
    creator: 'Studio Foundry™',
    dateIntroduced: '2026-07-08',
    version: '1.0.0',
    assetRegistryId: 'hero-object-production-board-slate-v1',
    worldGraphSlug: 'production-board-slate',
    foundryProductLine: 'Production Relics™',
    surfaces: [...SHARED_SURFACES, 'production-board'],
    motion: motion('disciplined producer'),
    editions: standardEditions,
    usageHistory: history('Assigned to Command Center toolbelt after Production Orchestrator launch.'),
    evolutionTimeline: history('D09 connected production workflow to Hero Object navigation.'),
    contextualOrbPlacements: [
      { contextId: 'command-center', contextLabel: 'Command Center™', relevanceRank: 5, reason: 'Active production orchestration belongs in executive toolbelt.' },
    ],
    tags: ['production-board', 'orchestrator', 'handoff'],
  },
  {
    id: 'story-table-relic',
    displayName: 'Story Table Relic™',
    destinationId: 'story-table',
    destinationLabel: 'Story Table™',
    destinationRouteId: 'creative-direction-immersive',
    destinationPath: '/admin/studio/department/creative-direction',
    summary: 'A miniature illuminated creative altar used to enter concept, story, and Golden Build decisions.',
    silhouetteFamily: 'architectural-table',
    silhouetteLaw: 'Wide altar-table silhouette with four floating corner lights; distinct from the hinged Production Board Slate.',
    material: 'white marble, embedded gold grid, warm creative light',
    creator: 'Studio Foundry™',
    dateIntroduced: '2026-07-08',
    version: '1.0.0',
    assetRegistryId: 'hero-object-story-table-relic-v1',
    worldGraphSlug: 'story-table-relic',
    foundryProductLine: 'Creative Relics™',
    surfaces: SHARED_SURFACES,
    motion: motion('creative director'),
    editions: standardEditions,
    usageHistory: history('Assigned to Creative Direction Studio toolbelt.'),
    evolutionTimeline: history('D09 elevated Story Table access into a collectible artifact.'),
    contextualOrbPlacements: [
      { contextId: 'creative-direction-studio', contextLabel: 'Creative Direction Studio™', relevanceRank: 1, reason: 'Primary creative decision surface.' },
    ],
    tags: ['creative-direction', 'story-table', 'golden-build'],
  },
  {
    id: 'mood-wall-prism',
    displayName: 'Mood Wall Prism™',
    destinationId: 'mood-wall',
    destinationLabel: 'Mood Wall™',
    destinationRouteId: 'creative-direction-immersive',
    destinationPath: '/admin/studio/department/creative-direction',
    summary: 'A vertical prism that opens visual direction, references, tone, and emotional atmosphere.',
    silhouetteFamily: 'vertical-wall',
    silhouetteLaw: 'Tall translucent wall shard; no other toolbelt object may use the vertical-panel shard outline.',
    material: 'rose glass, liquid chrome, refracted inspiration fragments',
    creator: 'Studio Foundry™',
    dateIntroduced: '2026-07-08',
    version: '1.0.0',
    assetRegistryId: 'hero-object-mood-wall-prism-v1',
    worldGraphSlug: 'mood-wall-prism',
    foundryProductLine: 'Creative Relics™',
    surfaces: SHARED_SURFACES,
    motion: motion('atmospheric stylist'),
    editions: standardEditions,
    usageHistory: history('Assigned to Creative Direction Studio toolbelt.'),
    evolutionTimeline: history('D09 made mood navigation tactile and collectible.'),
    contextualOrbPlacements: [
      { contextId: 'creative-direction-studio', contextLabel: 'Creative Direction Studio™', relevanceRank: 2, reason: 'Visual direction is high-context inside CDS.' },
    ],
    tags: ['creative-direction', 'mood-wall', 'visual-system'],
  },
  {
    id: 'studio-foundry-crucible',
    displayName: 'Studio Foundry Crucible™',
    destinationId: 'studio-foundry',
    destinationLabel: 'Studio Foundry™',
    destinationRouteId: 'asset-factory',
    destinationPath: '/admin/studio/brand-assets/asset-factory',
    summary: 'A glowing crucible representing object manufacturing, variants, and asset production lines.',
    silhouetteFamily: 'foundry-crucible',
    silhouetteLaw: 'Bowl-crucible with suspended molten core; no other object may use a vessel silhouette.',
    material: 'blackened steel, molten gold, violet foundry flame',
    creator: 'Studio Foundry™',
    dateIntroduced: '2026-07-08',
    version: '1.0.0',
    assetRegistryId: 'hero-object-studio-foundry-crucible-v1',
    worldGraphSlug: 'studio-foundry-crucible',
    foundryProductLine: 'Foundry Relics™',
    surfaces: [...SHARED_SURFACES, 'marketplace'],
    motion: motion('master craftsperson'),
    editions: standardEditions,
    usageHistory: history('Assigned to CDS and Warehouse toolbelts as the manufacturing entry.'),
    evolutionTimeline: history('D09 established Studio Foundry as Hero Object manufacturer.'),
    contextualOrbPlacements: [
      { contextId: 'creative-direction-studio', contextLabel: 'Creative Direction Studio™', relevanceRank: 3, reason: 'Creative decisions often require asset manufacturing.' },
    ],
    tags: ['foundry', 'asset-factory', 'manufacturing'],
  },
  {
    id: 'asset-registry-vault',
    displayName: 'Asset Registry Vault™',
    destinationId: 'asset-registry',
    destinationLabel: 'Asset Registry™',
    destinationRouteId: 'asset-registry',
    destinationPath: '/admin/studio/asset-registry',
    summary: 'A vault artifact that opens registered, versioned, reusable Studio World assets.',
    silhouetteFamily: 'vault-door',
    silhouetteLaw: 'Circular vault-door silhouette with three asymmetric locks; no other object may use this vault face.',
    material: 'bronze, smoked glass, archival blue light',
    creator: 'Studio Foundry™',
    dateIntroduced: '2026-07-08',
    version: '1.0.0',
    assetRegistryId: 'hero-object-asset-registry-vault-v1',
    worldGraphSlug: 'asset-registry-vault',
    foundryProductLine: 'Asset Relics™',
    surfaces: [...SHARED_SURFACES, 'marketplace'],
    motion: motion('meticulous librarian'),
    editions: standardEditions,
    usageHistory: history('Assigned to CDS and Warehouse toolbelts.'),
    evolutionTimeline: history('D09 made Asset Registry access a luxury object.'),
    contextualOrbPlacements: [
      { contextId: 'creative-direction-studio', contextLabel: 'Creative Direction Studio™', relevanceRank: 4, reason: 'Reuse before regeneration inside creative work.' },
      { contextId: 'warehouse-wing', contextLabel: 'Warehouse Wing™', relevanceRank: 5, reason: 'All warehouse production depends on registered assets.' },
    ],
    tags: ['asset-registry', 'versioning', 'reuse'],
  },
  {
    id: 'golden-review-marquee',
    displayName: 'Golden Review Marquee™',
    destinationId: 'golden-review',
    destinationLabel: 'Golden Review™',
    destinationRouteId: 'screening-room',
    destinationPath: '/admin/studio/screening-room',
    summary: 'A miniature private-theater marquee that opens founder review and approval.',
    silhouetteFamily: 'theater-marquee',
    silhouetteLaw: 'Arched theater marquee with five light ribs; no other object may use the arch-and-ribs silhouette.',
    material: 'polished gold, smoked enamel, soft cinema bulbs',
    creator: 'Studio Foundry™',
    dateIntroduced: '2026-07-08',
    version: '1.0.0',
    assetRegistryId: 'hero-object-golden-review-marquee-v1',
    worldGraphSlug: 'golden-review-marquee',
    foundryProductLine: 'Review Relics™',
    surfaces: [...SHARED_SURFACES, 'achievements'],
    motion: motion('cinematic reviewer'),
    editions: standardEditions,
    usageHistory: history('Assigned to Creative Direction Studio toolbelt.'),
    evolutionTimeline: history('D09 connected approval to a recognizable artifact.'),
    contextualOrbPlacements: [
      { contextId: 'creative-direction-studio', contextLabel: 'Creative Direction Studio™', relevanceRank: 5, reason: 'Golden Review is the local creative approval endpoint.' },
    ],
    tags: ['golden-review', 'screening-room', 'approval'],
  },
  {
    id: 'generation-bay-engine',
    displayName: 'Generation Bay Engine™',
    destinationId: 'generation-bay',
    destinationLabel: 'Generation Bay™',
    destinationRouteId: 'asset-factory',
    destinationPath: '/admin/studio/brand-assets/asset-factory',
    summary: 'A compact kinetic manufacturing engine for asset generation and variants.',
    silhouetteFamily: 'mechanical-bay',
    silhouetteLaw: 'Open turbine-bay silhouette with visible inner rotor; no other object may use the rotor bay outline.',
    material: 'titanium, black ceramic, molten violet energy',
    creator: 'Studio Foundry™',
    dateIntroduced: '2026-07-08',
    version: '1.0.0',
    assetRegistryId: 'hero-object-generation-bay-engine-v1',
    worldGraphSlug: 'generation-bay-engine',
    foundryProductLine: 'Warehouse Relics™',
    surfaces: SHARED_SURFACES,
    motion: motion('industrial producer'),
    editions: standardEditions,
    usageHistory: history('Assigned to Warehouse Wing toolbelt.'),
    evolutionTimeline: history('D09 turned generation access into an industrial artifact.'),
    contextualOrbPlacements: [
      { contextId: 'warehouse-wing', contextLabel: 'Warehouse Wing™', relevanceRank: 1, reason: 'Primary production bay for generated assets.' },
    ],
    tags: ['warehouse', 'generation', 'asset-factory'],
  },
  {
    id: 'materials-library-tower',
    displayName: 'Materials Library Tower™',
    destinationId: 'materials-library',
    destinationLabel: 'Materials Library™',
    destinationRouteId: 'asset-registry',
    destinationPath: '/admin/studio/asset-registry',
    summary: 'A rotating tower of luxury material swatches and shader samples.',
    silhouetteFamily: 'material-tower',
    silhouetteLaw: 'Stacked rotating material tower; no other object may use stacked sample discs.',
    material: 'marble, chrome, velvet, glass, living shader strips',
    creator: 'Studio Foundry™',
    dateIntroduced: '2026-07-08',
    version: '1.0.0',
    assetRegistryId: 'hero-object-materials-library-tower-v1',
    worldGraphSlug: 'materials-library-tower',
    foundryProductLine: 'Material Relics™',
    surfaces: SHARED_SURFACES,
    motion: motion('material curator'),
    editions: standardEditions,
    usageHistory: history('Assigned to Warehouse Wing toolbelt.'),
    evolutionTimeline: history('D09 established materials as collectible navigation artifacts.'),
    contextualOrbPlacements: [
      { contextId: 'warehouse-wing', contextLabel: 'Warehouse Wing™', relevanceRank: 2, reason: 'Material selection is local to warehouse production.' },
    ],
    tags: ['warehouse', 'materials', 'asset-registry'],
  },
  {
    id: 'blueprint-archive-scroll',
    displayName: 'Blueprint Archive Scroll™',
    destinationId: 'blueprint-archive',
    destinationLabel: 'Blueprint Archive™',
    destinationRouteId: 'blueprint-manager',
    destinationPath: '/admin/studio/blueprint-manager',
    summary: 'A living scroll and drafting instrument that opens canonical blueprints and archived plans.',
    silhouetteFamily: 'archive-scroll',
    silhouetteLaw: 'Partially unfurled scroll with drafting compass spine; distinct from Knowledge Core Crystal.',
    material: 'vellum glass, ink-blue wireframe, brass drafting compass',
    creator: 'Studio Foundry™',
    dateIntroduced: '2026-07-08',
    version: '1.0.0',
    assetRegistryId: 'hero-object-blueprint-archive-scroll-v1',
    worldGraphSlug: 'blueprint-archive-scroll',
    foundryProductLine: 'Archive Relics™',
    surfaces: [...SHARED_SURFACES, 'innovation-hall'],
    motion: motion('architectural historian'),
    editions: standardEditions,
    usageHistory: history('Assigned to Warehouse Wing toolbelt.'),
    evolutionTimeline: history('D09 connected blueprints to living object navigation.'),
    contextualOrbPlacements: [
      { contextId: 'warehouse-wing', contextLabel: 'Warehouse Wing™', relevanceRank: 3, reason: 'Warehouse production depends on approved blueprints.' },
    ],
    tags: ['blueprint', 'archive', 'warehouse'],
  },
  {
    id: 'marketplace-pavilion-arch',
    displayName: 'Marketplace Pavilion Arch™',
    destinationId: 'marketplace-pavilion',
    destinationLabel: 'Marketplace Pavilion™',
    destinationRouteId: 'marketplace-nav',
    destinationPath: '/admin/studio/marketplace',
    summary: 'A miniature pavilion arch for reusable objects, editions, and civilization commerce.',
    silhouetteFamily: 'pavilion-arch',
    silhouetteLaw: 'Tall pavilion arch with suspended exchange jewel; no other object may use the arch silhouette.',
    material: 'cream stone, bronze, gemstone exchange light',
    creator: 'Studio Foundry™',
    dateIntroduced: '2026-07-08',
    version: '1.0.0',
    assetRegistryId: 'hero-object-marketplace-pavilion-arch-v1',
    worldGraphSlug: 'marketplace-pavilion-arch',
    foundryProductLine: 'Marketplace Relics™',
    surfaces: [...SHARED_SURFACES, 'marketplace'],
    motion: motion('market curator'),
    editions: standardEditions,
    usageHistory: history('Assigned to Warehouse Wing toolbelt.'),
    evolutionTimeline: history('D09 made commerce access object-based and collectible.'),
    contextualOrbPlacements: [
      { contextId: 'warehouse-wing', contextLabel: 'Warehouse Wing™', relevanceRank: 4, reason: 'Finished assets can become marketplace products.' },
    ],
    tags: ['marketplace', 'warehouse', 'commerce'],
  },
  {
    id: 'campaign-studio-beacon',
    displayName: 'Campaign Studio Beacon™',
    destinationId: 'campaign-studio',
    destinationLabel: 'Campaign Studio™',
    destinationRouteId: 'campaign-engine',
    destinationPath: '/admin/studio/campaign-engine',
    summary: 'A directional launch beacon for campaign strategy and activation.',
    silhouetteFamily: 'performance-monolith',
    silhouetteLaw: 'Triangular beacon tower with sweeping signal fin; distinct from monolithic consoles.',
    material: 'white ceramic, ruby signal glass, gold antenna lines',
    creator: 'Studio Foundry™',
    dateIntroduced: '2026-07-08',
    version: '1.0.0',
    assetRegistryId: 'hero-object-campaign-studio-beacon-v1',
    worldGraphSlug: 'campaign-studio-beacon',
    foundryProductLine: 'Marketing Relics™',
    surfaces: SHARED_SURFACES,
    motion: motion('launch strategist'),
    editions: standardEditions,
    usageHistory: history('Assigned to Marketing HQ toolbelt.'),
    evolutionTimeline: history('D09 made campaign navigation a launch artifact.'),
    contextualOrbPlacements: [
      { contextId: 'marketing-hq', contextLabel: 'Marketing HQ™', relevanceRank: 1, reason: 'Campaign Studio is the primary marketing work surface.' },
    ],
    tags: ['marketing', 'campaign', 'launch'],
  },
  {
    id: 'launch-theater-marquee',
    displayName: 'Launch Theater Marquee™',
    destinationId: 'launch-theater',
    destinationLabel: 'Launch Theater™',
    destinationRouteId: 'shows',
    destinationPath: '/admin/studio/shows',
    summary: 'A premiere marquee for show launches, releases, and launch presentations.',
    silhouetteFamily: 'theater-marquee',
    silhouetteLaw: 'Wide premiere marquee with twin vertical spotlights; distinct from Golden Review arch.',
    material: 'red enamel, polished brass, cinema-white light',
    creator: 'Studio Foundry™',
    dateIntroduced: '2026-07-08',
    version: '1.0.0',
    assetRegistryId: 'hero-object-launch-theater-marquee-v1',
    worldGraphSlug: 'launch-theater-marquee',
    foundryProductLine: 'Marketing Relics™',
    surfaces: [...SHARED_SURFACES, 'marketplace'],
    motion: motion('premiere host'),
    editions: standardEditions,
    usageHistory: history('Assigned to Marketing HQ toolbelt.'),
    evolutionTimeline: history('D09 turned launch surfaces into collectible marquee objects.'),
    contextualOrbPlacements: [
      { contextId: 'marketing-hq', contextLabel: 'Marketing HQ™', relevanceRank: 2, reason: 'Launch review and release belong near campaigns.' },
    ],
    tags: ['marketing', 'launch', 'shows'],
  },
  {
    id: 'social-media-lab-signal',
    displayName: 'Social Media Lab Signal™',
    destinationId: 'social-media-lab',
    destinationLabel: 'Social Media Lab™',
    destinationRouteId: 'social-accounts',
    destinationPath: '/admin/studio/social-accounts',
    summary: 'A living signal sculpture for channels, posts, and social publishing systems.',
    silhouetteFamily: 'holographic-constellation',
    silhouetteLaw: 'Three nested signal arcs around a suspended post jewel; no other object may use signal arcs.',
    material: 'clear acrylic, neon signal filaments, pearl base',
    creator: 'Studio Foundry™',
    dateIntroduced: '2026-07-08',
    version: '1.0.0',
    assetRegistryId: 'hero-object-social-media-lab-signal-v1',
    worldGraphSlug: 'social-media-lab-signal',
    foundryProductLine: 'Marketing Relics™',
    surfaces: SHARED_SURFACES,
    motion: motion('social pulse reader'),
    editions: standardEditions,
    usageHistory: history('Assigned to Marketing HQ toolbelt.'),
    evolutionTimeline: history('D09 made social publishing a living artifact, not a channel icon.'),
    contextualOrbPlacements: [
      { contextId: 'marketing-hq', contextLabel: 'Marketing HQ™', relevanceRank: 3, reason: 'Social publishing is high-relevance marketing work.' },
    ],
    tags: ['marketing', 'social', 'publishing'],
  },
  {
    id: 'brand-partnerships-handshake',
    displayName: 'Brand Partnerships Handshake™',
    destinationId: 'brand-partnerships',
    destinationLabel: 'Brand Partnerships™',
    destinationRouteId: 'brand-architect',
    destinationPath: '/admin/studio/brand-architect',
    summary: 'An abstract sculptural clasp for collaborations, sponsors, and partnership memory.',
    silhouetteFamily: 'pavilion-arch',
    silhouetteLaw: 'Interlocking twin arches with shared center jewel; distinct from marketplace pavilion arch.',
    material: 'champagne metal, black glass, shared white glow',
    creator: 'Studio Foundry™',
    dateIntroduced: '2026-07-08',
    version: '1.0.0',
    assetRegistryId: 'hero-object-brand-partnerships-handshake-v1',
    worldGraphSlug: 'brand-partnerships-handshake',
    foundryProductLine: 'Marketing Relics™',
    surfaces: [...SHARED_SURFACES, 'innovation-hall'],
    motion: motion('relationship broker'),
    editions: standardEditions,
    usageHistory: history('Assigned to Marketing HQ toolbelt.'),
    evolutionTimeline: history('D09 encoded partnerships as a collectible artifact.'),
    contextualOrbPlacements: [
      { contextId: 'marketing-hq', contextLabel: 'Marketing HQ™', relevanceRank: 4, reason: 'Partnerships live near brand and campaign work.' },
    ],
    tags: ['marketing', 'brand', 'partnerships'],
  },
  {
    id: 'performance-wall-monolith',
    displayName: 'Performance Wall Monolith™',
    destinationId: 'performance-wall',
    destinationLabel: 'Performance Wall™',
    destinationRouteId: 'analytics',
    destinationPath: '/admin/studio/analytics',
    summary: 'A data monolith that turns marketing performance into spatial signal.',
    silhouetteFamily: 'performance-monolith',
    silhouetteLaw: 'Tall split monolith with flowing metric river; no other object may use this split-stone silhouette.',
    material: 'obsidian, liquid ruby data, mirrored bevels',
    creator: 'Studio Foundry™',
    dateIntroduced: '2026-07-08',
    version: '1.0.0',
    assetRegistryId: 'hero-object-performance-wall-monolith-v1',
    worldGraphSlug: 'performance-wall-monolith',
    foundryProductLine: 'Marketing Relics™',
    surfaces: SHARED_SURFACES,
    motion: motion('performance analyst'),
    editions: standardEditions,
    usageHistory: history('Assigned to Marketing HQ toolbelt.'),
    evolutionTimeline: history('D09 turned analytics entry into a recognizable artifact.'),
    contextualOrbPlacements: [
      { contextId: 'marketing-hq', contextLabel: 'Marketing HQ™', relevanceRank: 5, reason: 'Performance closes the marketing loop.' },
    ],
    tags: ['marketing', 'analytics', 'performance'],
  },
  {
    id: 'hero-object-vault',
    displayName: 'Hero Object Vault™',
    destinationId: 'hero-object-vault',
    destinationLabel: 'Hero Object Vault™',
    destinationRouteId: 'asset-registry',
    destinationPath: '/admin/studio/asset-registry',
    summary: 'A vault dedicated to collecting, preserving, versioning, and exhibiting Hero Objects.',
    silhouetteFamily: 'vault-door',
    silhouetteLaw: 'Vault cube with visible object pedestals inside; distinct from circular Asset Registry Vault.',
    material: 'smoked museum glass, black marble plinth, violet security light',
    creator: 'Studio Foundry™',
    dateIntroduced: '2026-07-08',
    version: '1.0.0',
    assetRegistryId: 'hero-object-vault-v1',
    worldGraphSlug: 'hero-object-vault',
    foundryProductLine: 'Hero Object Infrastructure™',
    surfaces: [...SHARED_SURFACES, 'achievements', 'marketplace'],
    motion: motion('vault keeper'),
    editions: standardEditions,
    usageHistory: history('Assigned to Warehouse Wing toolbelt as the collection home.'),
    evolutionTimeline: history('D09 established collectible object storage as a first-class destination.'),
    contextualOrbPlacements: [
      { contextId: 'warehouse-wing', contextLabel: 'Warehouse Wing™', relevanceRank: 5, reason: 'Collectibles need a visible home inside Warehouse Wing.' },
    ],
    tags: ['hero-objects', 'vault', 'collectibles'],
  },
];

export const CONTEXTUAL_ORB_TOOLBELTS: ContextualOrbToolbelt[] = [
  {
    contextId: 'command-center',
    contextLabel: 'Command Center™',
    heroObjectIds: [
      'world-atlas-globe',
      'mission-control-console',
      'daily-brief-lens',
      'knowledge-core-crystal',
      'production-board-slate',
    ],
  },
  {
    contextId: 'creative-direction-studio',
    contextLabel: 'Creative Direction Studio™',
    heroObjectIds: [
      'story-table-relic',
      'mood-wall-prism',
      'studio-foundry-crucible',
      'asset-registry-vault',
      'golden-review-marquee',
    ],
  },
  {
    contextId: 'warehouse-wing',
    contextLabel: 'Warehouse Wing™',
    heroObjectIds: [
      'generation-bay-engine',
      'materials-library-tower',
      'blueprint-archive-scroll',
      'marketplace-pavilion-arch',
      'hero-object-vault',
    ],
  },
  {
    contextId: 'marketing-hq',
    contextLabel: 'Marketing HQ™',
    heroObjectIds: [
      'campaign-studio-beacon',
      'launch-theater-marquee',
      'social-media-lab-signal',
      'brand-partnerships-handshake',
      'performance-wall-monolith',
    ],
  },
];

export function getHeroObject(id: string): HeroObjectDefinition | undefined {
  return HERO_OBJECTS.find((object) => object.id === id);
}

export function getContextualHeroObjects(contextId: string): HeroObjectDefinition[] {
  const toolbelt = CONTEXTUAL_ORB_TOOLBELTS.find((entry) => entry.contextId === contextId);
  if (!toolbelt) return [];
  return toolbelt.heroObjectIds
    .map((id) => getHeroObject(id))
    .filter((object): object is HeroObjectDefinition => Boolean(object));
}

export function assertUniqueHeroObjectSilhouettes(objects: HeroObjectDefinition[] = HERO_OBJECTS): string[] {
  const notes: string[] = [];
  const seen = new Map<string, string[]>();
  for (const object of objects) {
    const key = object.silhouetteLaw.toLowerCase();
    seen.set(key, [...(seen.get(key) ?? []), object.displayName]);
  }
  for (const [key, names] of seen.entries()) {
    if (names.length > 1) {
      notes.push(`Silhouette law collision (${key}): ${names.join(', ')}`);
    }
  }
  return notes;
}
