import { useState, type ReactNode } from 'react';
import { AsstsGlass } from './AsstsGlass';
import { AsstsStatusBadge } from './AsstsMobileNav';

type VersionStripProps = {
  versions: Array<{ id: string; version_number: number; previewUrl: string | null; status: string; label?: string }>;
  selectedId: string | null;
  onSelect: (id: string) => void;
  approvedVersionId?: string | null;
};

export function AsstsVersionStrip({ versions, selectedId, onSelect, approvedVersionId }: VersionStripProps) {
  if (!versions.length) return null;
  return (
    <div className="assts-version-strip" role="tablist" aria-label="Asset versions">
      {versions.map((v) => {
        const isSelected = v.id === selectedId;
        const isCanonical = v.id === approvedVersionId;
        const label =
          v.label ??
          (isCanonical ? 'CANONICAL MASTER' : v.id === selectedId ? 'CURRENT ASSET' : `V${String(v.version_number).padStart(2, '0')}`);
        return (
          <button
            key={v.id}
            type="button"
            role="tab"
            aria-selected={isSelected}
            className={`assts-version-strip__item ${isSelected ? 'assts-version-strip__item--active' : ''}`}
            onClick={() => onSelect(v.id)}
          >
            <div className="assts-version-strip__thumb">
              {v.previewUrl ? <img src={v.previewUrl} alt="" loading="lazy" /> : <div className="assts-version-strip__thumb--empty" />}
            </div>
            <span className="assts-version-strip__label">{label}</span>
          </button>
        );
      })}
    </div>
  );
}

type MetadataPanelProps = {
  batchKey?: string | null;
  versionNumber?: number;
  status?: string;
  generator?: string | null;
  promptVersion?: string | null;
  expandedContent?: ReactNode;
};

export function AsstsMetadataPanel({
  batchKey,
  versionNumber,
  status,
  generator,
  promptVersion,
  expandedContent,
}: MetadataPanelProps) {
  const [open, setOpen] = useState(false);
  return (
    <AsstsGlass variant="panel" className="assts-metadata-panel">
      <dl className="assts-metadata-panel__list">
        {batchKey ? (
          <>
            <dt>BATCH</dt>
            <dd>{batchKey}</dd>
          </>
        ) : null}
        {versionNumber != null ? (
          <>
            <dt>VERSION</dt>
            <dd>V{String(versionNumber).padStart(2, '0')}</dd>
          </>
        ) : null}
        {status ? (
          <>
            <dt>STATUS</dt>
            <dd>
              <AsstsStatusBadge status={status} />
            </dd>
          </>
        ) : null}
        {generator ? (
          <>
            <dt>GENERATED BY</dt>
            <dd>{generator.toUpperCase()}</dd>
          </>
        ) : null}
        {promptVersion ? (
          <>
            <dt>PROMPT VERSION</dt>
            <dd>{promptVersion}</dd>
          </>
        ) : null}
      </dl>
      {expandedContent ? (
        <>
          <button type="button" className="assts-metadata-panel__toggle" onClick={() => setOpen((v) => !v)}>
            {open ? 'HIDE DETAILS' : 'VIEW DETAILS'}
          </button>
          {open ? <div className="assts-metadata-panel__expanded">{expandedContent}</div> : null}
        </>
      ) : null}
    </AsstsGlass>
  );
}

type InspectorFooterProps = {
  prevAssetId: string | null;
  nextAssetId: string | null;
  position: number;
  total: number;
  onNavigate: (assetId: string) => void;
};

export function AsstsInspectorFooter({ prevAssetId, nextAssetId, position, total, onNavigate }: InspectorFooterProps) {
  return (
    <div className="assts-inspector-footer assts-glass assts-glass--float">
      <button type="button" disabled={!prevAssetId} onClick={() => prevAssetId && onNavigate(prevAssetId)}>
        ← PREVIOUS
      </button>
      <span className="assts-inspector-footer__pos">
        {position} OF {total}
      </span>
      <button type="button" disabled={!nextAssetId} onClick={() => nextAssetId && onNavigate(nextAssetId)}>
        NEXT →
      </button>
    </div>
  );
}

type FullScreenViewerProps = {
  open: boolean;
  url: string;
  title: string;
  onClose: () => void;
};

export function AsstsFullScreenViewer({ open, url, title, onClose }: FullScreenViewerProps) {
  if (!open) return null;
  return (
    <div className="assts-fullscreen" role="dialog" aria-label={`Full size: ${title}`}>
      <button type="button" className="assts-fullscreen__close" onClick={onClose} aria-label="Close">
        ✕
      </button>
      <div className="assts-fullscreen__title">{title}</div>
      <div className="assts-fullscreen__stage">
        <img src={url} alt={title} className="assts-fullscreen__img" />
      </div>
    </div>
  );
}

type CompareOverlayProps = {
  currentUrl: string;
  masterUrl: string | null;
  currentLabel?: string;
  masterLabel?: string;
  onClose: () => void;
};

export function AsstsCompareOverlay({
  currentUrl,
  masterUrl,
  currentLabel = 'CURRENT',
  masterLabel = 'CANONICAL MASTER',
  onClose,
}: CompareOverlayProps) {
  const [showMaster, setShowMaster] = useState(false);
  if (!masterUrl) {
    return (
      <AsstsGlass variant="panel" className="assts-compare-hint">
        <p>No canonical master available for comparison.</p>
        <button type="button" onClick={onClose}>
          DISMISS
        </button>
      </AsstsGlass>
    );
  }
  return (
    <div className="assts-compare assts-glass assts-glass--panel">
      <div className="assts-compare__toggle">
        <button type="button" className={!showMaster ? 'active' : ''} onClick={() => setShowMaster(false)}>
          {currentLabel}
        </button>
        <button type="button" className={showMaster ? 'active' : ''} onClick={() => setShowMaster(true)}>
          {masterLabel}
        </button>
      </div>
      <div className="assts-compare__stage">
        <img src={showMaster ? masterUrl : currentUrl} alt={showMaster ? masterLabel : currentLabel} />
      </div>
      <button type="button" className="assts-compare__close" onClick={onClose}>
        CLOSE COMPARE
      </button>
    </div>
  );
}
