import type { PromptCategory, PromptEntry } from './types';

function prompt(
  partial: Pick<
    PromptEntry,
    'promptId' | 'name' | 'description' | 'purpose' | 'promptType' | 'category' | 'owner' | 'department' | 'associatedFeature'
  > &
    Partial<PromptEntry>
): PromptEntry {
  return {
    organizationScope: partial.organizationScope ?? ['all'],
    version: partial.version ?? '1.0.0',
    status: partial.status ?? 'active',
    dependencies: partial.dependencies ?? [],
    supportedModels: partial.supportedModels ?? ['gpt-4o', 'claude-sonnet'],
    variables: partial.variables ?? [],
    expectedOutput: partial.expectedOutput ?? 'Structured JSON or executive prose per prompt spec.',
    documentation: partial.documentation ?? [`docs/studio-os/${partial.category}.md`],
    lastUpdated: partial.lastUpdated ?? new Date().toISOString(),
    registered: true,
    qualityScorePct: partial.qualityScorePct ?? 88,
    testCount: partial.testCount ?? 0,
    ...partial,
  };
}

/** Canonical Prompt Registry™ catalog — every AI prompt a first-class platform asset. */
export function buildPromptCatalog(): PromptEntry[] {
  const items: PromptEntry[] = [
    prompt({
      promptId: 'command-dock.intent-routing',
      name: 'Command Dock Intent Routing',
      description: 'System prompt for routing founder commands to Studio OS modules.',
      purpose: 'Resolve natural-language commands to module advice chains.',
      promptType: 'system',
      category: 'command-dock',
      owner: 'Command Dock',
      department: 'Executive',
      associatedFeature: 'command-dock',
      variables: ['userQuery', 'organizationContext', 'pathname'],
      expectedOutput: 'Module advice or routing summary with concierge voice.',
      dependencies: ['command-dock', 'studio-intelligence-architecture'],
      qualityScorePct: 94,
      testCount: 420,
    }),
    prompt({
      promptId: 'command-dock.proactive-briefing',
      name: 'Headquarters Proactive Briefing',
      description: 'Generates ambient opening briefing for Mission Control.',
      purpose: 'Deliver contextual founder briefing on headquarters entry.',
      promptType: 'instruction',
      category: 'command-dock',
      owner: 'Ambient Awareness',
      department: 'Executive',
      associatedFeature: 'mission-control',
      variables: ['organizationProfile', 'recentEvents'],
      qualityScorePct: 91,
    }),
    prompt({
      promptId: 'concierge.chief-concierge',
      name: 'Chief Concierge System Prompt',
      description: 'Primary digital concierge voice and behavioral guardrails.',
      purpose: 'Maintain executive assistant tone across all concierge interactions.',
      promptType: 'system',
      category: 'digital-concierge',
      owner: 'Digital Concierge',
      department: 'Executive',
      associatedFeature: 'command-dock',
      supportedModels: ['gpt-4o', 'claude-sonnet', 'studio-local'],
      qualityScorePct: 96,
      testCount: 890,
    }),
    prompt({
      promptId: 'concierge.department-concierge',
      name: 'Department Concierge Template',
      description: 'Scoped concierge prompt for department-specific assistance.',
      purpose: 'Adapt concierge behavior per department context.',
      promptType: 'instruction',
      category: 'digital-concierge',
      owner: 'Digital Concierge',
      department: 'Operations',
      associatedFeature: 'digital-concierge',
      variables: ['departmentId', 'departmentPolicies'],
    }),
    prompt({
      promptId: 'executive-council.meeting-synthesis',
      name: 'Executive Council Meeting Synthesis',
      description: 'Synthesizes council deliberations into actionable recommendations.',
      purpose: 'Transform multi-advisor council output into founder-ready decisions.',
      promptType: 'workflow',
      category: 'executive-council',
      owner: 'Executive Council',
      department: 'Executive',
      associatedFeature: 'executive-council',
      variables: ['advisorOutputs', 'decisionContext'],
      expectedOutput: 'Executive summary with consensus, dissent, and recommended action.',
      qualityScorePct: 93,
      testCount: 156,
    }),
    prompt({
      promptId: 'executive-council.deliberation',
      name: 'Council Advisor Deliberation',
      description: 'Individual advisor reasoning template for council sessions.',
      purpose: 'Standardize advisor perspective generation.',
      promptType: 'reasoning-template',
      category: 'executive-council',
      owner: 'Executive Council',
      department: 'Executive',
      associatedFeature: 'executive-council',
      variables: ['advisorRole', 'topic', 'organizationContext'],
    }),
    prompt({
      promptId: 'profession-brain.domain-reasoning',
      name: 'Profession Brain Domain Reasoning',
      description: 'Applies profession-specific knowledge before model reasoning.',
      purpose: 'Ground AI responses in registered profession expertise.',
      promptType: 'chain-of-thought',
      category: 'profession-brain',
      owner: 'Profession Brain',
      department: 'Knowledge',
      associatedFeature: 'profession-brain',
      variables: ['professionId', 'knowledgeNodes', 'query'],
      dependencies: ['profession-brain', 'studio-intelligence-architecture'],
      qualityScorePct: 95,
      testCount: 340,
    }),
    prompt({
      promptId: 'studio-institute.course-generation',
      name: 'Institute Course Generation',
      description: 'Generates structured course modules from organization knowledge.',
      purpose: 'Auto-build Academy content from registered expertise.',
      promptType: 'workflow',
      category: 'studio-institute',
      owner: 'Studio Institute',
      department: 'Education',
      associatedFeature: 'studio-institute',
      variables: ['topic', 'audienceLevel', 'knowledgeSources'],
      status: 'active',
    }),
    prompt({
      promptId: 'knowledge-commerce.product-builder',
      name: 'Knowledge Product Builder',
      description: 'Transforms expertise into sellable knowledge products.',
      purpose: 'Generate product outlines, pricing tiers, and marketing copy.',
      promptType: 'workflow',
      category: 'knowledge-commerce',
      owner: 'Knowledge Commerce',
      department: 'Revenue',
      associatedFeature: 'knowledge-commerce',
      variables: ['expertiseArea', 'targetAudience'],
    }),
    prompt({
      promptId: 'automation-workflow.trigger-analysis',
      name: 'Automation Trigger Analysis',
      description: 'Analyzes events to recommend automation triggers.',
      purpose: 'Connect Event Bus patterns to Automation Registry entries.',
      promptType: 'reasoning-template',
      category: 'automation-workflow',
      owner: 'Automation Registry',
      department: 'Operations',
      associatedFeature: 'automation-registry',
      dependencies: ['event-bus', 'automation-registry'],
    }),
    prompt({
      promptId: 'marketplace.expert-listing',
      name: 'Marketplace Expert Listing',
      description: 'Generates expert marketplace profiles from profession data.',
      purpose: 'Publish verified expertise listings with consistent structure.',
      promptType: 'instruction',
      category: 'marketplace',
      owner: 'Marketplace',
      department: 'Revenue',
      associatedFeature: 'marketplace',
    }),
    prompt({
      promptId: 'help-center.article-generation',
      name: 'Help Center Article Generation',
      description: 'Creates help articles from Documentation Registry metadata.',
      purpose: 'Keep help center synchronized with platform documentation.',
      promptType: 'workflow',
      category: 'help-center',
      owner: 'Documentation Sync',
      department: 'Support',
      associatedFeature: 'knowledge-hub',
      dependencies: ['documentation-registry', 'documentation-sync'],
    }),
    prompt({
      promptId: 'search.semantic-query',
      name: 'Semantic Search Query Expansion',
      description: 'Expands natural-language queries for registry search.',
      purpose: 'Improve search recall across System, Component, and Documentation registries.',
      promptType: 'few-shot',
      category: 'search',
      owner: 'Studio Intelligence',
      department: 'Platform',
      associatedFeature: 'knowledge-hub',
      variables: ['query', 'searchScope'],
      qualityScorePct: 89,
    }),
    prompt({
      promptId: 'summaries.executive-daily',
      name: 'Executive Daily Summary',
      description: 'Condenses organization activity into founder morning briefing.',
      purpose: 'Deliver scannable executive summary each morning.',
      promptType: 'instruction',
      category: 'summaries',
      owner: 'Organization Pulse',
      department: 'Executive',
      associatedFeature: 'organization-pulse',
      variables: ['pulseIndicators', 'recentEvents'],
      qualityScorePct: 92,
    }),
    prompt({
      promptId: 'content-creation.social-calendar',
      name: 'Social Content Calendar',
      description: 'Generates scheduled social content from brand positioning.',
      purpose: 'Maintain consistent brand voice across scheduled posts.',
      promptType: 'workflow',
      category: 'content-creation',
      owner: 'Brand Positioning',
      department: 'Marketing',
      associatedFeature: 'brand-positioning',
    }),
    prompt({
      promptId: 'research.world-knowledge-filter',
      name: 'World Knowledge Signal Filter',
      description: 'Filters external signals for organization relevance.',
      purpose: 'Reduce noise in World Knowledge Engine briefings.',
      promptType: 'chain-of-thought',
      category: 'research',
      owner: 'World Knowledge Engine',
      department: 'Strategy',
      associatedFeature: 'world-knowledge-engine',
      variables: ['industryContext', 'rawSignals'],
    }),
    prompt({
      promptId: 'decision-support.scenario-analysis',
      name: 'Scenario Analysis Template',
      description: 'Structured reasoning for strategic decision support.',
      purpose: 'Present options, risks, and recommendations for founder decisions.',
      promptType: 'reasoning-template',
      category: 'decision-support',
      owner: 'Predictive Organization',
      department: 'Strategy',
      associatedFeature: 'predictive-organization',
      qualityScorePct: 90,
    }),
    prompt({
      promptId: 'developer-tools.code-review',
      name: 'Developer Code Review Assistant',
      description: 'Reviews code changes against Studio OS conventions.',
      purpose: 'Enforce motherboard patterns and registry-first development.',
      promptType: 'instruction',
      category: 'developer-tools',
      owner: 'Platform Engineering',
      department: 'Engineering',
      associatedFeature: 'system-registry',
      status: 'draft',
    }),
    prompt({
      promptId: 'summaries.meeting-notes',
      name: 'Meeting Notes Summarizer',
      description: 'Transforms meeting transcripts into action items.',
      purpose: 'Extract decisions, owners, and deadlines from meetings.',
      promptType: 'instruction',
      category: 'summaries',
      owner: 'Executive Timeline',
      department: 'Executive',
      associatedFeature: 'executive-timeline',
    }),
    prompt({
      promptId: 'content-creation.newsletter',
      name: 'Newsletter Content Generator',
      description: 'Drafts organization newsletter from recent activity.',
      purpose: 'Automate newsletter content with brand voice compliance.',
      promptType: 'workflow',
      category: 'content-creation',
      owner: 'Marketing',
      department: 'Marketing',
      associatedFeature: 'marketing',
    }),
    prompt({
      promptId: 'future.custom-prompt',
      name: 'Future Custom Prompt Slot',
      description: 'Reserved slot for organization-specific custom prompts.',
      purpose: 'Register new AI workflows without hidden prompt text.',
      promptType: 'system',
      category: 'future',
      owner: 'Organization Admin',
      department: 'Platform',
      associatedFeature: 'prompt-registry',
      status: 'draft',
      version: '0.1.0',
    }),
  ];

  return items;
}

export function getPromptEntry(promptId: string): PromptEntry | undefined {
  return buildPromptCatalog().find((p) => p.promptId === promptId);
}

export function listPromptsByCategory(category: PromptCategory): PromptEntry[] {
  return buildPromptCatalog().filter((p) => p.category === category);
}

export function listPromptsByFeature(feature: string): PromptEntry[] {
  const f = feature.toLowerCase();
  return buildPromptCatalog().filter(
    (p) => p.associatedFeature.toLowerCase().includes(f) || p.category.includes(f)
  );
}

export function listPromptsByStatus(status: PromptEntry['status']): PromptEntry[] {
  return buildPromptCatalog().filter((p) => p.status === status);
}
