import type {
  BackupStatusRecord,
  DataRetentionPolicy,
  PrivacyRequest,
  SecurityAuditEvent,
  SecurityFinding,
  SecurityIncident,
  SecuritySession,
  SecuritySettings,
  VendorSecurityRecord,
} from './securityTypes';
import { defaultSecuritySettings } from './productionGate';

export function createSecuritySeedData(now = new Date()) {
  const iso = (d: Date) => d.toISOString();
  const daysAgo = (n: number) => iso(new Date(now.getTime() - n * 86400000));

  const settings: SecuritySettings = defaultSecuritySettings();

  const sessions: SecuritySession[] = [
    {
      id: 'sess-staff-current',
      principalType: 'staff',
      principalId: 'staff-1',
      principalLabel: 'Jordan Ellis (Owner)',
      userAgentApprox: 'Chrome on macOS',
      deviceLabel: 'Office MacBook',
      createdAt: daysAgo(0.02),
      lastActiveAt: iso(now),
      isCurrent: true,
    },
    {
      id: 'sess-staff-other',
      principalType: 'staff',
      principalId: 'staff-1',
      principalLabel: 'Jordan Ellis (Owner)',
      userAgentApprox: 'Safari on iPhone',
      deviceLabel: 'Mobile Safari',
      createdAt: daysAgo(2),
      lastActiveAt: daysAgo(0.5),
    },
    {
      id: 'sess-customer-current',
      principalType: 'customer',
      principalId: 'client-a',
      principalLabel: 'Marcus Webb — Summit Ridge Hauling',
      userAgentApprox: 'Chrome on Android',
      deviceLabel: 'Pixel Phone',
      createdAt: daysAgo(1),
      lastActiveAt: daysAgo(0.1),
      isCurrent: true,
    },
  ];

  const findings: SecurityFinding[] = [
    {
      id: 'find-mfa-staff',
      controlId: 'mfa-foundation',
      severity: 'MEDIUM',
      category: 'IDENTITY',
      title: 'MFA not yet required for all staff',
      description: 'MFA policy architecture exists; provider enforcement pending Sprint 20.',
      detectedAt: daysAgo(14),
      status: 'OPEN',
      owner: 'Platform',
      isDemo: true,
    },
    {
      id: 'find-backup',
      controlId: 'backup-production',
      severity: 'HIGH',
      category: 'BACKUP',
      title: 'Production backup provider not configured',
      description: 'Debug environment — backup status NOT CONFIGURED is expected.',
      detectedAt: daysAgo(7),
      status: 'OPEN',
      owner: 'Infrastructure',
      isDemo: true,
    },
    {
      id: 'find-domain',
      severity: 'MEDIUM',
      category: 'OPERATIONS',
      title: 'Production domain not configured',
      description: 'All In One remains on temporary debug host inside Frontal Slayer repository.',
      detectedAt: daysAgo(30),
      status: 'OPEN',
      owner: 'Platform',
      isDemo: true,
    },
    {
      id: 'find-demo-mode',
      severity: 'INFO',
      category: 'OPERATIONS',
      title: 'Demo mode active',
      description: 'External providers run in demo/sandbox mode — no real submissions.',
      detectedAt: daysAgo(1),
      status: 'OPEN',
      isDemo: true,
    },
    {
      id: 'find-deps',
      severity: 'LOW',
      category: 'DEPENDENCIES',
      title: 'Routine dependency review due',
      description: 'Schedule npm audit review before production extraction.',
      detectedAt: daysAgo(45),
      status: 'OPEN',
      owner: 'Engineering',
      isDemo: true,
    },
  ];

  const auditEvents: SecurityAuditEvent[] = [
    {
      id: 'aud-1',
      eventType: 'LOGIN_SUCCESS',
      timestamp: daysAgo(0.02),
      actorId: 'staff-1',
      actorLabel: 'Jordan Ellis',
      actorRole: 'owner',
      action: 'Staff login',
      result: 'SUCCESS',
      correlationId: 'AIO-ERR-DEMO0001',
      isDemo: true,
    },
    {
      id: 'aud-2',
      eventType: 'FINANCIAL_RECORD_CHANGED',
      timestamp: daysAgo(3),
      actorId: 'staff-6',
      actorLabel: 'Riley Chen',
      actorRole: 'billing_specialist',
      organizationId: 'client-a',
      entityType: 'invoice',
      entityId: 'inv-demo-1',
      action: 'Invoice line item adjusted',
      result: 'SUCCESS',
      metadata: { field: 'discount', rowCount: 1 },
      beforeSnapshot: { totalMinor: 45000 },
      afterSnapshot: { totalMinor: 42000 },
      correlationId: 'AIO-ERR-DEMO0002',
      isDemo: true,
    },
    {
      id: 'aud-3',
      eventType: 'DOCUMENT_DOWNLOADED',
      timestamp: daysAgo(5),
      actorId: 'client-a',
      actorLabel: 'Marcus Webb',
      organizationId: 'client-a',
      entityType: 'document',
      entityId: 'vdoc-a1',
      action: 'Signed download issued',
      result: 'SUCCESS',
      correlationId: 'AIO-ERR-DEMO0003',
      isDemo: true,
    },
    {
      id: 'aud-4',
      eventType: 'INTEGRATION_CONNECTED',
      timestamp: daysAgo(8),
      actorId: 'staff-1',
      actorLabel: 'Jordan Ellis',
      actorRole: 'owner',
      entityType: 'integration',
      entityId: 'conn-demo-email',
      action: 'Demo email provider connected (sandbox)',
      result: 'SUCCESS',
      isDemo: true,
    },
    {
      id: 'aud-5',
      eventType: 'ROLE_CHANGED',
      timestamp: daysAgo(10),
      actorId: 'staff-1',
      actorLabel: 'Jordan Ellis',
      entityType: 'staff',
      entityId: 'staff-6',
      action: 'Granted reports.export to billing specialist',
      result: 'SUCCESS',
      beforeSnapshot: { permissions: ['billing.read'] },
      afterSnapshot: { permissions: ['billing.read', 'reports.export'] },
      isDemo: true,
    },
    {
      id: 'aud-6',
      eventType: 'EXPORT_CREATED',
      timestamp: daysAgo(4),
      actorId: 'staff-1',
      actorLabel: 'Jordan Ellis',
      action: 'Management financial export',
      result: 'SUCCESS',
      metadata: { reportId: 'financial-summary', rowCount: 42 },
      isDemo: true,
    },
    {
      id: 'aud-7',
      eventType: 'SESSION_REVOKED',
      timestamp: daysAgo(6),
      actorId: 'staff-1',
      actorLabel: 'Jordan Ellis',
      entityType: 'session',
      entityId: 'sess-staff-revoked-demo',
      action: 'Revoked other session',
      result: 'SUCCESS',
      isDemo: true,
    },
  ];

  const privacyRequests: PrivacyRequest[] = [
    {
      id: 'pr-1',
      organizationId: 'client-b',
      requesterLabel: 'Demo Customer — Heartland Freight LLC',
      requestType: 'ACCESS',
      status: 'UNDER_REVIEW',
      submittedAt: daysAgo(2),
      updatedAt: daysAgo(1),
      reviewNotes: 'Identity verification pending — fictional demo request.',
      isDemo: true,
    },
  ];

  const incidents: SecurityIncident[] = [
    {
      id: 'inc-demo-rotation',
      severity: 'SEV-4',
      category: 'CREDENTIAL_EXPOSURE',
      title: 'Provider credential rotation drill (DEMO)',
      summary: 'Fictional tabletop exercise — rotated demo integration credential references.',
      detectedAt: daysAgo(20),
      status: 'RESOLVED',
      owner: 'Jordan Ellis',
      affectedSystems: ['Demo payment adapter'],
      containment: 'Disabled demo connection; rotated credential reference metadata',
      resolution: 'Verified replacement credential reference; no production impact',
      postmortemRequired: false,
      isDemo: true,
    },
  ];

  const vendors: VendorSecurityRecord[] = [
    {
      id: 'vendor-supabase',
      name: 'Supabase (planned AIO project)',
      purpose: 'Database, auth, storage',
      dataCategories: ['CONFIDENTIAL', 'RESTRICTED'],
      accessLevel: 'Platform infrastructure',
      environment: 'DEMO',
      contractStatus: 'PENDING',
      securityReviewStatus: 'REVIEW_REQUIRED',
      notes: 'Dedicated AIO project — not FS Website production',
    },
    {
      id: 'vendor-resend',
      name: 'Email provider (demo adapter)',
      purpose: 'Transactional email',
      dataCategories: ['CONFIDENTIAL'],
      accessLevel: 'Message metadata',
      environment: 'DEMO',
      contractStatus: 'NONE',
      securityReviewStatus: 'NOT_REVIEWED',
    },
    {
      id: 'vendor-fmcsa',
      name: 'FMCSA / regulatory source',
      purpose: 'USDOT carrier lookup',
      dataCategories: ['PUBLIC', 'INTERNAL'],
      accessLevel: 'Read-only regulatory data',
      environment: 'DEMO',
      contractStatus: 'NONE',
      securityReviewStatus: 'REVIEWED',
      lastReviewedAt: daysAgo(60),
    },
  ];

  const retentionPolicies: DataRetentionPolicy[] = [
    {
      id: 'ret-audit',
      dataCategory: 'Security audit events',
      classification: 'CONFIDENTIAL',
      retentionPeriod: 'TBD — LEGAL/BUSINESS REVIEW REQUIRED',
      trigger: 'Event creation',
      disposition: 'Archive then delete per policy',
      legalBasis: 'TBD — LEGAL/BUSINESS REVIEW REQUIRED',
      reviewRequired: true,
      status: 'TBD',
    },
    {
      id: 'ret-financial',
      dataCategory: 'Invoices and payments',
      classification: 'CONFIDENTIAL',
      retentionPeriod: 'TBD — LEGAL/BUSINESS REVIEW REQUIRED',
      trigger: 'Transaction date',
      disposition: 'RETAIN per financial records policy',
      legalBasis: 'TBD — LEGAL/BUSINESS REVIEW REQUIRED',
      reviewRequired: true,
      status: 'TBD',
    },
    {
      id: 'ret-marketing',
      dataCategory: 'Marketing consents',
      classification: 'INTERNAL',
      retentionPeriod: 'Until revoked + grace period (TBD)',
      trigger: 'Consent grant',
      disposition: 'DELETE or anonymize after retention',
      legalBasis: 'Business operational',
      reviewRequired: true,
      status: 'DRAFT',
    },
  ];

  const backupStatus: BackupStatusRecord = {
    database: 'NOT_CONFIGURED',
    objectStorage: 'NOT_CONFIGURED',
    configuration: 'NOT_CONFIGURED',
    auditRecords: 'NOT_CONFIGURED',
    lastCheckedAt: iso(now),
    targetRpo: 'TARGET RPO: TBD BEFORE PRODUCTION',
    targetRto: 'TARGET RTO: TBD BEFORE PRODUCTION',
    notes: 'Debug environment — production backup not configured (expected).',
  };

  return {
    securitySettings: settings,
    securitySessions: sessions,
    securityFindings: findings,
    securityAuditEvents: auditEvents,
    privacyRequests,
    securityIncidents: incidents,
    vendorSecurityRecords: vendors,
    dataRetentionPolicies: retentionPolicies,
    backupStatus,
    signedDownloadGrants: [] as import('./securityTypes').SignedDownloadGrant[],
    staffPermissionOverrides: {} as Record<string, string[]>,
  };
}
