import type { CanonicalArticleSeed } from '../article-builder';

export const VOLUME_III_WORLD_BIBLE_ARTICLES: CanonicalArticleSeed[] = [
  {
    articleId: 'ARTICLE-W01',
    title: 'Studio World Hierarchy™',
    volume: 'volume-iii-world-bible',
    category: 'World Structure',
    summary:
      'Studio World is organized as civilization layers: Eras, Companies, Headquarters, Districts, Wings, Rooms, Departments, Engines, and Citizens.',
    philosophy: 'Everything has a home. No feature exists as a webpage orphan.',
    guidingPrinciples: [
      'Physical Place Law — features live in rooms and districts.',
      'World Graph Is Truth — if it is not in the graph, it is not canonical.',
      'No Orphan Objects Law — every object has relationship edges.',
    ],
    relatedSystems: ['World Graph™', 'World Atlas™', 'Mission Control™'],
    relatedArticles: ['ARTICLE-AR01', 'ARTICLE-W02', 'ARTICLE-K18'],
    tags: ['world-bible', 'hierarchy', 'spatial'],
    docPaths: ['docs/studio-os/canon/STUDIO_WORLD_CANON_HIERARCHY.md'],
  },
  {
    articleId: 'ARTICLE-W02',
    title: 'Command Center & Mission Control™',
    volume: 'volume-iii-world-bible',
    category: 'Executive District',
    summary:
      'Mission Control™ is the executive command center — civilization pulse, attention routing, and founder-facing operational intelligence.',
    philosophy: 'The founder enters headquarters to steer a civilization — not to open admin panels.',
    relatedSystems: ['Mission Control™', 'Executive Command Center™', 'Chief of Staff™'],
    relatedArticles: ['ARTICLE-W01', 'ARTICLE-W05'],
    tags: ['world-bible', 'mission-control', 'executive'],
    docPaths: ['docs/studio-os/world-atlas-mission-control.md'],
  },
  {
    articleId: 'ARTICLE-W03',
    title: 'Companies & Headquarters™',
    volume: 'volume-iii-world-bible',
    category: 'Organization Lore',
    summary:
      'Companies are sovereign organizations within Studio World. Headquarters are flagship campuses where departments, districts, and executive rooms coexist.',
    philosophy: 'Multi-company architecture lets every organization inherit Studio World physics without forking the platform.',
    relatedSystems: ['Company Genome™', 'Headquarters Marketplace™', 'Multi-Company Architecture™'],
    relatedArticles: ['ARTICLE-AR04', 'ARTICLE-W04'],
    tags: ['world-bible', 'companies', 'headquarters'],
  },
  {
    articleId: 'ARTICLE-W04',
    title: 'Districts, Scenes & Workspaces™',
    volume: 'volume-iii-world-bible',
    category: 'Spatial Canon',
    summary:
      'Districts group related profession and department experiences. Scenes are assembled environments. Workspaces are where professional work happens.',
    philosophy: 'Spatial continuity — citizens should feel they traveled, not clicked.',
    relatedSystems: ['World Atlas™', 'Scene Assembly™', 'Scene Stack™'],
    relatedArticles: ['ARTICLE-W01', 'ARTICLE-AR03'],
    tags: ['world-bible', 'districts', 'scenes', 'workspaces'],
    docPaths: ['docs/studio-os/scene-stack/README.md'],
  },
  {
    articleId: 'ARTICLE-W05',
    title: 'Orb™ & Atlas™',
    volume: 'volume-iii-world-bible',
    category: 'Navigation Citizens',
    summary:
      'Orb™ is the mentoring courier and contextual toolbelt. Atlas™ is spatial navigation — districts, travel, and world orientation.',
    philosophy: 'Orb connects; Atlas orients. Together they replace sidebar navigation.',
    relatedSystems: ['Orb™', 'Atlas™', 'Hero Objects™'],
    relatedArticles: ['ARTICLE-D09', 'ARTICLE-D05', 'ARTICLE-W02'],
    tags: ['world-bible', 'orb', 'atlas', 'navigation'],
    docPaths: ['docs/studio-os/studio-orb.md', 'docs/studio-os/studio-world-atlas.md'],
  },
  {
    articleId: 'ARTICLE-W06',
    title: 'Career Worlds & Profession Brains in World Context™',
    volume: 'volume-iii-world-bible',
    category: 'Profession Districts',
    summary:
      'Each Career World is a district with workplaces, NPCs, economy, and profession truth. Profession Brains supply canonical knowledge inside those districts.',
    philosophy: 'Professions are places with laws — not content categories.',
    relatedSystems: ['Career Worlds™', 'Profession Brains™', 'Profession Simulation Engine™'],
    relatedArticles: ['ARTICLE-E02', 'ARTICLE-B01', 'ARTICLE-E01'],
    tags: ['world-bible', 'career-worlds', 'profession-brains'],
    docPaths: ['docs/studio-os/career-worlds/ARTICLE_E02_CAREER_WORLDS.md'],
  },
  {
    articleId: 'ARTICLE-W07',
    title: 'NPC Ecosystem & World Clock™',
    volume: 'volume-iii-world-bible',
    category: 'Living World',
    summary:
      'NPC professionals have roles, trust, memory, and schedules. World Clock advances simulated time — seasons, events, and industry rhythms.',
    philosophy: 'Every system should feel alive — the world continues when the citizen is away.',
    relatedSystems: ['Career Worlds™', 'World Clock™', 'Industry Events™'],
    relatedArticles: ['ARTICLE-E02', 'ARTICLE-W08'],
    tags: ['world-bible', 'npc', 'world-clock', 'simulation'],
    codePaths: ['src/studio-os-core/career-worlds/world-clock/'],
  },
  {
    articleId: 'ARTICLE-W08',
    title: 'Studio Exchange & Studio Economy™',
    volume: 'volume-iii-world-bible',
    category: 'Civic Economy',
    summary:
      'Studio Exchange is the civic marketplace — licenses, expansions, mentorship, businesses, and ceremonies. Studio Economy tracks contribution and mentor value.',
    philosophy: 'Contribution, teaching, and building are the center of economic life — not content consumption.',
    relatedSystems: ['Studio Exchange™', 'Studio Economy™', 'Mentor Economy™'],
    relatedArticles: ['ARTICLE-E05', 'ARTICLE-E08', 'ARTICLE-F03'],
    tags: ['world-bible', 'economy', 'exchange'],
    docPaths: ['docs/studio-os/marketplace/studio-exchange.md'],
  },
  {
    articleId: 'ARTICLE-W09',
    title: 'Citizen Progression™',
    volume: 'volume-iii-world-bible',
    category: 'Identity Lore',
    summary:
      'Citizens progress through licenses, certifications, reputation tiers, district unlocks, and legacy achievements — identity persists across Career Worlds.',
    philosophy: 'Build identities instead of accounts.',
    relatedSystems: ['Identity Timeline™', 'Professional Licenses™', 'Reputation Engine™'],
    relatedArticles: ['ARTICLE-E06', 'ARTICLE-E07', 'ARTICLE-M01'],
    tags: ['world-bible', 'citizen', 'progression', 'identity'],
  },
];
