import type { CanonicalArticleSeed } from '../article-builder';

export const VOLUME_II_CONSTITUTION_ARTICLES: CanonicalArticleSeed[] = [
  {
    articleId: 'ARTICLE-C01',
    title: 'The Codex First Principle™',
    volume: 'volume-ii-constitution',
    category: 'Constitutional Law',
    summary:
      'Every major Studio World feature must become a Codex Article™ before implementation begins.',
    philosophy:
      'The Codex is not documentation; it is Studio World remembering itself before it builds.',
    guidingPrinciples: [
      'Document before implementation.',
      'Every major feature must answer why it should exist.',
      'Approved ideas become Codex Articles before engineering begins.',
      'The Codex must outlive individual AI models, conversations, contributors, and implementations.',
      'Reusable platform capabilities are preferred over one-off features.',
    ],
    architecturalDecisions: [
      'Major feature work starts in the Codex lifecycle, not directly in code.',
      'Knowledge Core, World Bible, ADRs, and implementation plans become projections of Codex-approved truth.',
      'Constitution Review™ becomes the formal gate between article approval and implementation planning.',
      'Post-launch learnings must update the relevant article instead of living only in memory or chat.',
    ],
    implementationReferences: [
      'docs/studio-os/codex/ARTICLE_C01_CODEX_FIRST_PRINCIPLE.md',
      'src/studio-os-core/studio-world-codex/',
    ],
    relatedSystems: ['Knowledge Core™', 'World Graph™', 'Production Completion System™'],
    relatedArticles: ['ARTICLE-C02', 'ARTICLE-K21', 'ARTICLE-K22', 'ARTICLE-K23', 'ARTICLE-K24'],
    tags: ['codex-first', 'constitution', 'governance'],
    department: 'Constitution Hall',
    docPaths: ['docs/studio-os/codex/ARTICLE_C01_CODEX_FIRST_PRINCIPLE.md'],
    codePaths: ['src/studio-os-core/studio-world-codex/'],
    worldGraphNodeId: 'W-LAW-codex-first-principle',
  },
  {
    articleId: 'ARTICLE-C02',
    title: 'The Complete Studio World Codex™',
    volume: 'volume-ii-constitution',
    category: 'Constitutional Library Architecture',
    summary:
      'The first ten volumes remain the Foundational Collection™. Future Codex growth happens through specialized collections that expand independently without redesigning the original books.',
    philosophy:
      'The Codex is not a book that grows until it becomes unusable. It is a civilization library: foundational law stays stable while specialized knowledge grows through collections.',
    guidingPrinciples: [
      'Foundational volumes are permanent — Volumes I-X remain unchanged.',
      'Future domains become Codex Collections™ instead of Volume XI by default.',
      'Collections expand independently while remaining searchable, versioned, related, and governed by canon.',
      'Relationships cross collections by design.',
      'A new engineer, model, or contributor should understand where knowledge belongs without memorizing dozens of files.',
      'Adding a new civilization domain should be a registry operation, not an architecture migration.',
    ],
    architecturalDecisions: [
      'Define Foundational Collection™ as the permanent home of Volumes I-X.',
      'Introduce Codex Collections™ as top-level expansion units for specialized domains.',
      'Collection records store purpose, scope, governance level, owning systems, related collections, tags, status, and World Graph node IDs.',
      'Future collections include Company & Headquarters, Product & Commerce, Experience & Interface, Intelligence & Agents, Production & Operations, Professions & Career Worlds, Memory/History/Archive, Economy & Governance, and Future Eras.',
      'Article IDs remain globally unique across every collection.',
      'Semantic search crosses all collections by default.',
      'World Graph nodes represent collections, volumes, and articles.',
    ],
    implementationReferences: [
      'docs/studio-os/codex/ARTICLE_C02_COMPLETE_STUDIO_WORLD_CODEX.md',
      'src/studio-os-core/studio-world-codex/collections.ts',
      'docs/studio-os/codex/CODEX_PLATFORM.md',
    ],
    relatedSystems: ['Studio World Codex™', 'Knowledge Core™', 'World Graph™', 'Orb Curator™'],
    relatedArticles: ['ARTICLE-C01', 'ARTICLE-K22', 'ARTICLE-K23', 'ARTICLE-AR01', 'ARTICLE-F05'],
    tags: ['complete-codex', 'collections', 'constitution', 'library-architecture'],
    department: 'Constitution Hall',
    docPaths: ['docs/studio-os/codex/ARTICLE_C02_COMPLETE_STUDIO_WORLD_CODEX.md'],
    codePaths: ['src/studio-os-core/studio-world-codex/collections.ts'],
    worldGraphNodeId: 'W-LAW-complete-studio-world-codex',
  },
  {
    articleId: 'ARTICLE-K18',
    title: 'Progressive Presence™',
    volume: 'volume-ii-constitution',
    category: 'Behavioral Law',
    summary:
      'Information earns visibility. Architecture is the interface. UI appears only when curiosity or interaction requires it.',
    philosophy: 'The environment comes first. Knowledge comes second. UI comes last.',
    guidingPrinciples: [
      'Five Presence Levels™ from Architecture-only to Architect mode.',
      'One Primary Focus™ per room — each space answers one question first.',
      'If removing a panel improves the room, remove the panel.',
      'Components consult resolvePresenceVisibility() — they do not self-decide.',
    ],
    architecturalDecisions: [
      'Progressive Presence Engine™ is the central visibility authority.',
      'Every UI element registers Presence Level, Priority, Required Intent, Visual Weight.',
      'Departments inherit behavior through StudioWorldExperienceProvider.',
    ],
    relatedSystems: ['Experience Engine™', 'Global Experience System™', 'Orb™'],
    relatedArticles: ['ARTICLE-M02', 'ARTICLE-D09', 'ARTICLE-W01'],
    tags: ['constitution', 'progressive-presence', 'behavioral-law'],
    docPaths: ['docs/studio-os/governance/PROGRESSIVE_PRESENCE.md'],
    codePaths: ['src/studio-os-core/progressive-presence/'],
    worldGraphNodeId: 'W-LAW-progressive-presence',
  },
  {
    articleId: 'ARTICLE-D09',
    title: 'Hero Objects™ & Contextual Orb™',
    volume: 'volume-ii-constitution',
    category: 'Design Law',
    summary:
      'Studio World navigates with collectible living artifacts — not software iconography. Hero Objects are navigation primitives, World Graph nodes, and Foundry product line.',
    philosophy: 'Studio World does not navigate with icons; it navigates with collectible living artifacts.',
    guidingPrinciples: [
      'Hero Objects Over Icons™ — destinations remembered by silhouette, material, behavior, edition.',
      'Contextual Orb™ surfaces location-aware artifact sets — not an app launcher.',
      'Every Hero Object registers in World Graph as W-HO-* node.',
      'Foundry manufactures Hero Objects — no hardcoded emoji or placeholder art as final state.',
    ],
    architecturalDecisions: [
      'Hero Objects depend on Studio Foundry™ for asset generation.',
      'Orb behavior adapts to room, district, and work context.',
      'Signature Landmarks™ remain department-scale anchors; Hero Objects are navigation citizens.',
    ],
    relatedSystems: ['Studio Foundry™', 'Orb™', 'World Graph™', 'Asset Registry™'],
    relatedArticles: ['ARTICLE-A02', 'ARTICLE-A01', 'ARTICLE-D01'],
    tags: ['constitution', 'hero-objects', 'orb', 'navigation'],
    docPaths: ['docs/studio-os/hero-objects/ARTICLE_D09_HERO_OBJECTS_CONTEXTUAL_ORB.md'],
    worldGraphNodeId: 'W-LAW-hero-objects',
  },
  {
    articleId: 'ARTICLE-A02',
    title: 'Studio Foundry™',
    volume: 'volume-ii-constitution',
    category: 'Manufacturing Law',
    summary:
      'No future visual object should be a loose file or standalone library. UI, Orb, and Atlas request asset IDs; Foundry manufactures via Generation Recipes™ and Asset Compiler™.',
    philosophy: 'Studio World manufactures assets through a universal boundary — not ad-hoc generation scattered across features.',
    guidingPrinciples: [
      'Request asset IDs from Asset Registry™ — never bypass Foundry for visual objects.',
      'Generation Recipes™ define intent; Asset Compiler™ compiles FAL requests.',
      'Every manufactured asset versions, registers, and caches.',
      'Hero Icons, environments, furniture, glass UI, and portraits are Foundry product lines.',
    ],
    architecturalDecisions: [
      'Studio Foundry™ owns W-ENG-studio-foundry in World Graph.',
      'Asset Compiler™ is internal machinery; Foundry is the public manufacturing API.',
      'Knowledge Core receives Foundry lineage for institutional memory.',
    ],
    relatedSystems: ['Asset Compiler™', 'Asset Registry™', 'Generation Recipes™', 'Knowledge Core™'],
    relatedArticles: ['ARTICLE-A01', 'ARTICLE-D09', 'ARTICLE-K22'],
    tags: ['constitution', 'foundry', 'manufacturing'],
    docPaths: ['docs/studio-os/engine/asset-compiler/ARTICLE_A02_STUDIO_FOUNDRY.md'],
    codePaths: ['src/studio-os-core/studio-foundry/'],
    worldGraphNodeId: 'W-LAW-studio-foundry',
  },
  {
    articleId: 'ARTICLE-E03',
    title: 'Knowledge Retention Engine™',
    volume: 'volume-ii-constitution',
    category: 'Lifelong Mastery Law',
    summary:
      'Studio World preserves long-term professional mastery through retention profiles, adaptive refreshers, Orb mentorship, and living industry updates.',
    philosophy: 'Mastery decays without refresh. Retention is a constitutional obligation for profession platforms.',
    guidingPrinciples: [
      'Retention profiles track profession-specific decay curves.',
      'Orb delivers optional refresh reminders — mentorship, not nagging.',
      'Profession Brain updates queue through retention hooks.',
      'Refreshers are generated from canon — not hardcoded per profession in UI.',
    ],
    architecturalDecisions: [
      'Knowledge Retention extends Profession Brains™ — it does not replace them.',
      'Professional Memory™ records meaningful retention moments.',
      'World Graph registers retention engine nodes.',
    ],
    relatedSystems: ['Profession Brains™', 'Orb™', 'Professional Memory™', 'Career Worlds™'],
    relatedArticles: ['ARTICLE-B01', 'ARTICLE-E04', 'ARTICLE-E02'],
    tags: ['constitution', 'retention', 'mastery'],
    docPaths: ['docs/studio-os/engine/knowledge-retention/ARTICLE_E03_KNOWLEDGE_RETENTION_ENGINE.md'],
    codePaths: ['src/studio-os-core/knowledge-retention-engine/'],
  },
  {
    articleId: 'ARTICLE-E04',
    title: 'Professional Memory™ & Wisdom Engine™',
    volume: 'volume-ii-constitution',
    category: 'Lifelong Mastery Law',
    summary:
      'Knowledge teaches how; wisdom teaches when. Professional Memory preserves career history; Wisdom Engine synthesizes context-aware judgment.',
    philosophy: 'Studio World tracks experiences — not completed lessons.',
    guidingPrinciples: [
      'Professional Timeline™ is learner-owned permanent history.',
      'Memory Types™: Career, Client, Simulation, Teaching, Innovation, Business, Leadership, Community, Historical.',
      'Memory Reflection™ modes: Career Recap, Year In Review, Five-Year Journey, Mastery Timeline.',
      'Wisdom Engine inputs: Profession Brain, Professional Memory, Career History, Simulation Outcomes.',
    ],
    architecturalDecisions: [
      'Professional Memory extends Knowledge Retention™.',
      'E03 memories can be retained concepts; E04 memories are meaningful career experiences.',
      'Orb evolves from reminder to professional mentor citing lived context.',
    ],
    relatedSystems: ['Wisdom Engine™', 'Profession Brains™', 'Knowledge Retention Engine™', 'Orb™'],
    relatedArticles: ['ARTICLE-E03', 'ARTICLE-B01', 'ARTICLE-M03'],
    tags: ['constitution', 'professional-memory', 'wisdom'],
    docPaths: ['docs/studio-os/engine/professional-memory/ARTICLE_E04_PROFESSIONAL_MEMORY_WISDOM_ENGINE.md'],
    codePaths: ['src/studio-os-core/professional-memory-wisdom-engine/'],
  },
  {
    articleId: 'ARTICLE-E02',
    title: 'Career Worlds™',
    volume: 'volume-ii-constitution',
    category: 'Profession Platform Law',
    summary:
      'Studio World creates persistent professional lives — not academies or course catalogs. Career Worlds merge learning, simulation, economy, identity, and community.',
    philosophy: 'What kind of life are you building?',
    guidingPrinciples: [
      'Career Hub replaces course dashboard — profession-agnostic view model.',
      'Every profession plugs into one reusable Career Worlds engine.',
      'Persistent world clock, economy, NPC memory, and career progression.',
      'Profession Simulation Engine™ is runtime inside Career Worlds — not a separate LMS.',
    ],
    architecturalDecisions: [
      'Career Worlds use Profession Simulation Engine™ for shift-based gameplay.',
      'Studio Exchange™ grants Professional Licenses™ — not course purchases.',
      'World Graph registers W-ENG-career-worlds and district nodes per profession.',
    ],
    relatedSystems: ['Profession Simulation Engine™', 'Studio Exchange™', 'Profession Brains™'],
    relatedArticles: ['ARTICLE-E01', 'ARTICLE-E05', 'ARTICLE-W06'],
    tags: ['constitution', 'career-worlds', 'simulation'],
    docPaths: ['docs/studio-os/career-worlds/ARTICLE_E02_CAREER_WORLDS.md'],
    codePaths: ['src/studio-os-core/career-worlds/'],
  },
  {
    articleId: 'ARTICLE-E05',
    title: 'Studio Exchange™ & Professional License System™',
    volume: 'volume-ii-constitution',
    category: 'Economy Law',
    summary:
      'Studio World never sells courses. Citizens acquire Professional Licenses™ that unlock Career Worlds, mentors, simulations, and lifetime world updates.',
    philosophy: 'Buy Course / Enroll / Subscription language is forbidden — Acquire Professional License™ / Enter Career World™.',
    guidingPrinciples: [
      'Certifications are in-world ceremonies with meaningful unlocks — not PDFs only.',
      'Career Expansions™ are professional specializations — not DLC.',
      'Mentor Economy™ and Legacy Businesses™ center the Studio Economy™.',
      'Marketplace architecture becomes one product class inside the Exchange.',
    ],
    architecturalDecisions: [
      'Studio Exchange connects Career Worlds™, licenses, expansions, and ceremonies.',
      'Historical marketplace docs remain valid as internal product architecture.',
      'World Graph registers studio-exchange engine node.',
    ],
    relatedSystems: ['Career Worlds™', 'Studio Economy™', 'Expert Marketplace™'],
    relatedArticles: ['ARTICLE-E02', 'ARTICLE-E07', 'ARTICLE-W08'],
    tags: ['constitution', 'studio-exchange', 'licenses', 'economy'],
    docPaths: ['docs/studio-os/marketplace/studio-exchange.md'],
  },
  {
    articleId: 'ARTICLE-E01',
    title: 'Profession Simulation Engine™',
    volume: 'volume-ii-constitution',
    category: 'Simulation Law',
    summary:
      'Careers are playable workplace progression — shifts, clients, challenges, projects, promotions. Not predictions; lived professional simulation.',
    philosophy: 'Learners master professions by working — not by watching.',
    guidingPrinciples: [
      'Simulation scenes replace lesson modules where profession allows.',
      'Studio Institute routes through simulation when a profession can be simulated.',
      'Tick engine advances world state; outcomes feed Professional Memory™.',
      'Every profession world shares simulation contracts — not one-off LMS paths.',
    ],
    relatedSystems: ['Career Worlds™', 'Profession Brains™', 'Scene Assembly™'],
    relatedArticles: ['ARTICLE-E02', 'ARTICLE-B01', 'ARTICLE-AR05'],
    tags: ['constitution', 'simulation', 'profession'],
    docPaths: ['docs/studio-os/profession-simulation-engine/ARTICLE_E01_PROFESSION_SIMULATION_ENGINE.md'],
  },
  {
    articleId: 'ARTICLE-K21',
    title: 'Architecture Decision Records™',
    volume: 'volume-ii-constitution',
    category: 'Governance Law',
    summary: 'Every major architectural decision receives an ADR. History is never deleted — only superseded.',
    philosophy: 'Studio World remembers why things were built — not just what was built.',
    guidingPrinciples: [
      'ADRs link to Codex Articles, World Graph nodes, and Knowledge Core entries.',
      'Immutability of History — Historical plane objects are never deleted.',
      'Documentation-First Law — no Implementation Sprint without architectural home.',
    ],
    relatedSystems: ['Knowledge Core™', 'World Graph™', 'Codex™'],
    relatedArticles: ['ARTICLE-C01', 'ARTICLE-K22', 'ARTICLE-AR01'],
    tags: ['constitution', 'adr', 'governance'],
    docPaths: ['docs/studio-os/architecture-decision-records/ARTICLE_K21_ARCHITECTURE_DECISION_RECORDS.md'],
  },
  {
    articleId: 'ARTICLE-C10',
    title: 'Reserved — Era Transition Governance™',
    volume: 'volume-ii-constitution',
    category: 'Future Constitutional Slot',
    status: 'Draft',
    summary:
      'Future constitutional article governing transitions between Studio World Eras — when new platform capabilities may activate without breaking canon.',
    philosophy: 'Era discipline preserves future ideas while avoiding premature complexity.',
    guidingPrinciples: ['Three Eras Roadmap™ informs but does not auto-implement future systems.'],
    relatedArticles: ['ARTICLE-F05', 'ARTICLE-AR01'],
    tags: ['constitution', 'future-slot', 'era-governance'],
  },
  {
    articleId: 'ARTICLE-C11',
    title: 'Reserved — AI Council Governance™',
    volume: 'volume-ii-constitution',
    category: 'Future Constitutional Slot',
    status: 'Draft',
    summary:
      'Future constitutional article for multi-agent governance — when AI councils may recommend, review, or gate architectural changes.',
    philosophy: 'Agent memory is subordinate to institutional canon.',
    relatedArticles: ['ARTICLE-F03', 'ARTICLE-K23'],
    tags: ['constitution', 'future-slot', 'ai-governance'],
  },
  {
    articleId: 'ARTICLE-C12',
    title: 'Reserved — Citizen Rights & Data Sovereignty™',
    volume: 'volume-ii-constitution',
    category: 'Future Constitutional Slot',
    status: 'Draft',
    summary:
      'Future constitutional article defining citizen-owned identity, professional timeline sovereignty, and cross-world portability.',
    philosophy: 'Citizens own their professional timeline — the platform preserves, never exploits, identity.',
    relatedArticles: ['ARTICLE-F02', 'ARTICLE-W09'],
    tags: ['constitution', 'future-slot', 'citizen-rights'],
  },
];
