import type { StudioWorldRegistry } from './studio-world-registry';
import { STUDIO_WORLD_REGISTRY_VERSION } from './studio-world-registry';

function scene(
  partial: Omit<import('./studio-world-registry').StudioWorldSceneRecord, 'registryVersion'>
): import('./studio-world-registry').StudioWorldSceneRecord {
  return { ...partial, registryVersion: STUDIO_WORLD_REGISTRY_VERSION };
}

/** Beauty Headquarters — canonical Studio World default campus. */
export const BEAUTY_HEADQUARTERS_REGISTRY: StudioWorldRegistry = {
  registryVersion: STUDIO_WORLD_REGISTRY_VERSION,
  campusId: 'beauty-headquarters',
  campusDisplayName: 'Beauty Headquarters',
  scenes: [
    scene({
      sceneId: 'reception',
      displayName: 'Reception',
      purpose: 'Guest arrival and brand first impression',
      zone: 'customer',
      flagshipId: 'frontal-slayer-hq',
      routeRegistryId: null,
      blueprintId: 'reception-blueprint',
      founderRenderRequired: true,
      constructionPlanRequired: true,
      requiredCapabilities: ['founder-render', 'scene-stack'],
      dependencies: ['grand-lobby'],
      socketIds: ['reception-desk', 'guest-seating', 'brand-wall'],
      lightingProfileId: 'executive-reception',
      materialLibraryId: 'founder-material-library',
      version: '1.0.0',
      compatibility: ['studio-os.v1'],
      marketplaceEligible: true,
    }),
    scene({
      sceneId: 'grand-lobby',
      displayName: 'Grand Lobby',
      purpose: 'Primary circulation and arrival hall',
      zone: 'public',
      flagshipId: 'frontal-slayer-hq',
      routeRegistryId: null,
      blueprintId: 'grand-lobby-blueprint',
      founderRenderRequired: true,
      constructionPlanRequired: true,
      requiredCapabilities: ['founder-render', 'navigation'],
      dependencies: ['reception'],
      socketIds: ['lobby-hero', 'circulation-path'],
      lightingProfileId: 'grand-lobby-ambient',
      materialLibraryId: 'founder-material-library',
      version: '1.0.0',
      compatibility: ['studio-os.v1'],
      marketplaceEligible: true,
    }),
    scene({
      sceneId: 'transformation-suite',
      displayName: 'Transformation Suite',
      purpose: 'Client transformation experience',
      zone: 'customer',
      flagshipId: 'frontal-slayer-hq',
      routeRegistryId: null,
      blueprintId: 'transformation-suite-blueprint',
      founderRenderRequired: true,
      constructionPlanRequired: true,
      requiredCapabilities: ['founder-render', 'asset-manufacturing'],
      dependencies: [],
      socketIds: ['styling-chair', 'mirror-station'],
      lightingProfileId: 'suite-soft',
      materialLibraryId: 'founder-material-library',
      version: '1.0.0',
      compatibility: ['studio-os.v1'],
      marketplaceEligible: false,
      contentClass: 'FOUNDER_CREATED_MODDED_SCENE',
      creatorOrganizationId: 'frontal-slayer',
    }),
    scene({
      sceneId: 'build-a-wig-atelier',
      displayName: 'Build A Wig Atelier',
      purpose: 'Customization and product configuration',
      zone: 'manufacturing',
      flagshipId: 'frontal-slayer-hq',
      routeRegistryId: null,
      blueprintId: 'baw-atelier-blueprint',
      founderRenderRequired: true,
      constructionPlanRequired: true,
      requiredCapabilities: ['founder-render', 'asset-manufacturing'],
      dependencies: [],
      socketIds: ['display-case', 'mannequin-station'],
      lightingProfileId: 'atelier-bright',
      materialLibraryId: 'founder-material-library',
      version: '1.0.0',
      compatibility: ['studio-os.v1'],
      marketplaceEligible: true,
      contentClass: 'FOUNDER_CREATED_MODDED_SCENE',
      creatorOrganizationId: 'frontal-slayer',
    }),
    scene({
      sceneId: 'hair-analysis-lab',
      displayName: 'Hair Analysis Lab',
      purpose: 'Consultation and analysis workflows',
      zone: 'operations',
      flagshipId: 'frontal-slayer-hq',
      routeRegistryId: null,
      blueprintId: 'hair-analysis-lab-blueprint',
      founderRenderRequired: true,
      constructionPlanRequired: true,
      requiredCapabilities: ['founder-render'],
      dependencies: [],
      socketIds: ['analysis-station'],
      lightingProfileId: 'lab-clinical',
      materialLibraryId: 'founder-material-library',
      version: '1.0.0',
      compatibility: ['studio-os.v1'],
      marketplaceEligible: false,
      contentClass: 'FOUNDER_CREATED_MODDED_SCENE',
      creatorOrganizationId: 'frontal-slayer',
    }),
    scene({
      sceneId: 'extensions-boutique',
      displayName: 'Extensions Boutique',
      purpose: 'Retail extensions experience',
      zone: 'customer',
      flagshipId: 'frontal-slayer-hq',
      routeRegistryId: null,
      blueprintId: 'extensions-boutique-blueprint',
      founderRenderRequired: true,
      constructionPlanRequired: true,
      requiredCapabilities: ['founder-render', 'asset-manufacturing'],
      dependencies: [],
      socketIds: ['boutique-display'],
      lightingProfileId: 'retail-warm',
      materialLibraryId: 'founder-material-library',
      version: '1.0.0',
      compatibility: ['studio-os.v1'],
      marketplaceEligible: true,
    }),
    scene({
      sceneId: 'founder-suite',
      displayName: 'Founder Suite',
      purpose: 'Executive private office and decision space',
      zone: 'executive',
      flagshipId: 'frontal-slayer-hq',
      routeRegistryId: null,
      blueprintId: 'founder-suite-blueprint',
      founderRenderRequired: true,
      constructionPlanRequired: true,
      requiredCapabilities: ['founder-render'],
      dependencies: [],
      socketIds: ['executive-desk', 'founder-artifact-wall'],
      lightingProfileId: 'executive-suite',
      materialLibraryId: 'founder-material-library',
      version: '1.0.0',
      compatibility: ['studio-os.v1'],
      marketplaceEligible: false,
    }),
    scene({
      sceneId: 'creative-direction-studio',
      displayName: 'Creative Director Studio',
      purpose: 'Licensed construction contractor — asset manufacturing',
      zone: 'creative',
      flagshipId: 'creative-direction-studio',
      routeRegistryId: 'creative-direction-immersive',
      blueprintId: null,
      founderRenderRequired: false,
      constructionPlanRequired: false,
      requiredCapabilities: ['asset-manufacturing', 'approved-founder-render-handoff'],
      dependencies: ['experience-lab'],
      socketIds: [],
      lightingProfileId: null,
      materialLibraryId: 'founder-material-library',
      version: '1.0.0',
      compatibility: ['studio-os.v1', 'production-pipeline.v1'],
      marketplaceEligible: false,
    }),
    scene({
      sceneId: 'experience-lab',
      displayName: 'Experience Lab',
      purpose: 'Architecture firm — world design and Founder Render',
      zone: 'creative',
      flagshipId: 'experience-lab',
      routeRegistryId: null,
      blueprintId: null,
      founderRenderRequired: true,
      constructionPlanRequired: true,
      requiredCapabilities: ['founder-render', 'blueprint-author'],
      dependencies: [],
      socketIds: [],
      lightingProfileId: null,
      materialLibraryId: 'founder-material-library',
      version: '1.0.0',
      compatibility: ['studio-os.v1', 'model-routing-engine.v1'],
      marketplaceEligible: false,
    }),
    scene({
      sceneId: 'institute',
      displayName: 'Institute',
      purpose: 'Education and academy operations',
      zone: 'operations',
      flagshipId: 'studio-institute',
      routeRegistryId: null,
      blueprintId: 'institute-blueprint',
      founderRenderRequired: false,
      constructionPlanRequired: false,
      requiredCapabilities: ['knowledge-hub'],
      dependencies: [],
      socketIds: [],
      lightingProfileId: 'institute-neutral',
      materialLibraryId: null,
      version: '1.0.0',
      compatibility: ['studio-os.v1'],
      marketplaceEligible: true,
    }),
    scene({
      sceneId: 'marketing-department',
      displayName: 'Marketing Department',
      purpose: 'Brand and campaign operations',
      zone: 'operations',
      flagshipId: 'frontal-slayer-hq',
      routeRegistryId: null,
      blueprintId: null,
      founderRenderRequired: false,
      constructionPlanRequired: false,
      requiredCapabilities: ['campaign-orchestrator'],
      dependencies: [],
      socketIds: [],
      lightingProfileId: null,
      materialLibraryId: null,
      version: '1.0.0',
      compatibility: ['studio-os.v1'],
      marketplaceEligible: true,
    }),
    scene({
      sceneId: 'finance-department',
      displayName: 'Finance Department',
      purpose: 'Financial operations and reporting',
      zone: 'operations',
      flagshipId: 'frontal-slayer-hq',
      routeRegistryId: null,
      blueprintId: null,
      founderRenderRequired: false,
      constructionPlanRequired: false,
      requiredCapabilities: ['analytics'],
      dependencies: [],
      socketIds: [],
      lightingProfileId: null,
      materialLibraryId: null,
      version: '1.0.0',
      compatibility: ['studio-os.v1'],
      marketplaceEligible: false,
    }),
    scene({
      sceneId: 'operations-department',
      displayName: 'Operations Department',
      purpose: 'Day-to-day business operations',
      zone: 'operations',
      flagshipId: 'frontal-slayer-hq',
      routeRegistryId: null,
      blueprintId: null,
      founderRenderRequired: false,
      constructionPlanRequired: false,
      requiredCapabilities: ['work-orchestration'],
      dependencies: [],
      socketIds: [],
      lightingProfileId: null,
      materialLibraryId: null,
      version: '1.0.0',
      compatibility: ['studio-os.v1'],
      marketplaceEligible: false,
    }),
  ],
};
