import { AUTOMATION_REGISTRY_ACCENT } from './constants';
import type { AutomationCategory, AutomationEntry, AutomationRiskLevel, AutomationStatus } from './types';

function automation(
  partial: Pick<
    AutomationEntry,
    'automationId' | 'name' | 'description' | 'category' | 'owner' | 'department' | 'trigger'
  > &
    Partial<AutomationEntry>
): AutomationEntry {
  return {
    conditions: partial.conditions ?? [],
    actions: partial.actions ?? [],
    dependencies: partial.dependencies ?? [],
    permissions: partial.permissions ?? ['organization-admin'],
    organizations: partial.organizations ?? ['all'],
    status: partial.status ?? 'active',
    confidencePct: partial.confidencePct ?? 88,
    riskLevel: partial.riskLevel ?? 'low',
    approvalRequired: partial.approvalRequired ?? false,
    successRatePct: partial.successRatePct ?? 94,
    failureRatePct: partial.failureRatePct ?? 6,
    avgDurationMs: partial.avgDurationMs ?? 420,
    version: partial.version ?? '1.0.0',
    documentation: partial.documentation ?? [`docs/studio-os/${partial.category}.md`],
    executionCount: partial.executionCount ?? 0,
    registered: true,
    ...partial,
  };
}

/** Canonical Automation Registry™ catalog — every automation a registered organizational asset. */
export function buildAutomationCatalog(): AutomationEntry[] {
  const items: AutomationEntry[] = [
    automation({
      automationId: 'command-dock.routing',
      name: 'Command Dock Intent Routing',
      description: 'Routes founder commands to appropriate Studio OS modules via concierge intelligence.',
      category: 'command-dock',
      owner: 'Command Dock',
      department: 'Executive',
      trigger: 'User submits Command Dock query',
      conditions: ['Authenticated workspace', 'Active organization context'],
      actions: ['Resolve module advice', 'Update routing summary', 'Suggest follow-up command'],
      dependencies: ['command-dock', 'studio-intelligence-architecture'],
      successRatePct: 97,
      executionCount: 1240,
      lastExecutedAt: new Date(Date.now() - 1800000).toISOString(),
    }),
    automation({
      automationId: 'command-dock.proactive-briefing',
      name: 'Headquarters Proactive Briefing',
      description: 'Delivers ambient opening briefing when Mission Control loads.',
      category: 'command-dock',
      owner: 'Ambient Awareness',
      department: 'Executive',
      trigger: 'Mission Control / Headquarters entry',
      conditions: ['Organization profile synced'],
      actions: ['Build headquarters briefing', 'Queue proactive suggestion'],
      dependencies: ['ambient-awareness', 'command-dock'],
      confidencePct: 92,
    }),
    automation({
      automationId: 'workflow.autonomous-preparation',
      name: 'Autonomous Preparation Queue',
      description: 'Prepares agendas, briefings, and assets awaiting founder approval.',
      category: 'workflow',
      owner: 'Autonomous Preparation',
      department: 'Operations',
      trigger: 'Anticipation Engine prediction',
      conditions: ['Approval gate enabled', 'Confidence threshold met'],
      actions: ['Generate preparation item', 'Queue pending approval'],
      dependencies: ['autonomous-preparation', 'anticipation-engine'],
      approvalRequired: true,
      riskLevel: 'medium',
      status: 'active',
      executionCount: 86,
    }),
    automation({
      automationId: 'workflow.approval-chain',
      name: 'Executive Approval Chain',
      description: 'Routes high-impact decisions through approval workflow before execution.',
      category: 'approval-chain',
      owner: 'Executive Council',
      department: 'Executive',
      trigger: 'workflow.approved event OR manual approval request',
      conditions: ['Risk level medium or high', 'Founder not bypassing'],
      actions: ['Notify approvers', 'Hold execution until approved', 'Log decision history'],
      dependencies: ['executive-council', 'event-bus'],
      approvalRequired: true,
      riskLevel: 'high',
      successRatePct: 99,
    }),
    automation({
      automationId: 'email.newsletter-dispatch',
      name: 'Newsletter Send Automation',
      description: 'Dispatches marketing newsletters to opted-in clients via Resend.',
      category: 'email',
      owner: 'Marketing',
      department: 'Marketing',
      trigger: 'Admin newsletter send OR scheduled campaign',
      conditions: ['Recipient opt-in', 'RESEND_API_KEY configured'],
      actions: ['Chunk recipients', 'Send branded HTML', 'Log delivery'],
      dependencies: ['distribution-engine'],
      approvalRequired: true,
      riskLevel: 'medium',
      status: 'paused',
      executionCount: 12,
    }),
    automation({
      automationId: 'calendar.executive-sync',
      name: 'Executive Calendar Sync',
      description: 'Syncs Mission Control executive calendar with organizational milestones.',
      category: 'calendar',
      owner: 'Mission Control',
      department: 'Executive',
      trigger: 'Daily sync OR milestone created',
      conditions: ['Mission Control profile active'],
      actions: ['Update calendar entries', 'Surface upcoming deadlines'],
      dependencies: ['mission-control', 'executive-timeline'],
    }),
    automation({
      automationId: 'marketplace.listing-publish',
      name: 'Expert Marketplace Listing',
      description: 'Publishes approved Profession Brain surfaces to Expert Marketplace.',
      category: 'marketplace',
      owner: 'Expert Marketplace',
      department: 'Revenue',
      trigger: 'Expert profile approved',
      conditions: ['Trust tier validated', 'Brain surface approved'],
      actions: ['Create listing', 'Index for discovery', 'Notify expert'],
      dependencies: ['expert-marketplace', 'profession-brain'],
      approvalRequired: true,
    }),
    automation({
      automationId: 'studio-institute.course-sync',
      name: 'Institute Course Auto-Generation',
      description: 'Auto-generates courses from Profession Brain updates.',
      category: 'studio-institute',
      owner: 'Studio Institute',
      department: 'Learning',
      trigger: 'Profession Brain knowledge update',
      conditions: ['Institute sync enabled'],
      actions: ['Generate lesson draft', 'Queue course review'],
      dependencies: ['studio-institute', 'profession-brain'],
      confidencePct: 85,
    }),
    automation({
      automationId: 'knowledge-commerce.product-builder',
      name: 'Knowledge Product Builder',
      description: 'Creates monetizable knowledge products from approved Brain modules.',
      category: 'knowledge-commerce',
      owner: 'Knowledge Commerce',
      department: 'Revenue',
      trigger: 'Product publish request',
      conditions: ['Publication controls approved', 'Pricing set'],
      actions: ['Build product bundle', 'Enable revenue channel'],
      dependencies: ['knowledge-commerce'],
      approvalRequired: true,
      riskLevel: 'medium',
    }),
    automation({
      automationId: 'organization-pulse.indicator-scan',
      name: 'Pulse Indicator Scan',
      description: 'Continuously evaluates 14 pulse indicators and raises alerts.',
      category: 'organization-pulse',
      owner: 'Organization Pulse',
      department: 'Intelligence',
      trigger: 'Scheduled interval OR intelligence stack sync',
      conditions: ['Organization boundary active'],
      actions: ['Compute pulse state', 'Publish pulse.alert event', 'Recommend actions'],
      dependencies: ['organization-pulse', 'event-bus'],
      successRatePct: 96,
      executionCount: 520,
    }),
    automation({
      automationId: 'executive-council.meeting-synthesis',
      name: 'Executive Council Meeting',
      description: 'Conducts collaborative executive meetings and synthesizes briefings.',
      category: 'executive-council',
      owner: 'Executive Council',
      department: 'Executive',
      trigger: 'Founder strategic query OR scheduled council',
      conditions: ['Multiple executives available'],
      actions: ['Gather executive inputs', 'Synthesize briefing', 'Record decision history'],
      dependencies: ['executive-council'],
      confidencePct: 91,
    }),
    automation({
      automationId: 'documentation.registry-sync',
      name: 'Documentation Registry Sync',
      description: 'Syncs documentation metadata across all help surfaces.',
      category: 'documentation',
      owner: 'Documentation Registry',
      department: 'Platform',
      trigger: 'Module registered OR doc updated',
      conditions: ['Documentation sync chain active'],
      actions: ['Update doc registry', 'Trigger governance audit', 'Re-index search'],
      dependencies: ['documentation-registry', 'documentation-governance', 'event-bus'],
      successRatePct: 98,
      executionCount: 340,
    }),
    automation({
      automationId: 'content.scheduling-distribution',
      name: 'Content Scheduling Pipeline',
      description: 'Schedules and publishes approved content across distribution network.',
      category: 'content-scheduling',
      owner: 'Distribution Engine',
      department: 'Marketing',
      trigger: 'Campaign approved + schedule reached',
      conditions: ['Social accounts connected', 'Admin approval granted'],
      actions: ['Queue publish job', 'Notify content owner'],
      dependencies: ['distribution-engine', 'campaign-engine'],
      approvalRequired: true,
      status: 'pending-approval',
    }),
    automation({
      automationId: 'customer.followup-sequence',
      name: 'Customer Follow-up Sequence',
      description: 'Automated follow-ups after consult completion or purchase.',
      category: 'customer-followup',
      owner: 'Relationship Memory',
      department: 'Customer Experience',
      trigger: 'customer.created OR order.completed event',
      conditions: ['Follow-up rules configured', 'Customer opted in'],
      actions: ['Schedule follow-up', 'Personalize message', 'Log interaction'],
      dependencies: ['relationship-memory', 'event-bus'],
      successRatePct: 93,
    }),
    automation({
      automationId: 'notification.rule-engine',
      name: 'Notification Rule Engine',
      description: 'Delivers notifications based on organizational rules and events.',
      category: 'notification',
      owner: 'Notifications',
      department: 'Platform',
      trigger: 'Any subscribed Event Bus event',
      conditions: ['Recipient resolved', 'Channel available'],
      actions: ['Deliver notification', 'Log delivery', 'Record analytics'],
      dependencies: ['event-bus', 'notifications'],
      executionCount: 890,
    }),
    automation({
      automationId: 'legacy-vault.auto-archive',
      name: 'Legacy Vault Auto-Archive',
      description: 'Archives meaningful organizational moments to Legacy Vault.',
      category: 'legacy-vault',
      owner: 'Legacy Vault',
      department: 'Legacy',
      trigger: 'Milestone OR preserve moment detected',
      conditions: ['Preserve category matched'],
      actions: ['Archive moment', 'Update timeline', 'Notify founder optionally'],
      dependencies: ['legacy-vault', 'memory-engine'],
    }),
    automation({
      automationId: 'workflow.event-bus-reaction',
      name: 'Event Bus Workflow Trigger',
      description: 'Triggers registered automations when Event Bus events publish.',
      category: 'workflow',
      owner: 'Event Bus',
      department: 'Platform',
      trigger: 'Event Bus publish',
      conditions: ['Automation registered', 'Status active'],
      actions: ['Match subscribers', 'Execute automation actions', 'Log execution'],
      dependencies: ['event-bus', 'automation-registry'],
      successRatePct: 95,
      failureRatePct: 5,
      status: 'active',
      executionCount: 2100,
    }),
    automation({
      automationId: 'workflow.documentation-governance-audit',
      name: 'Documentation Governance Audit',
      description: 'Runs continuous documentation audits on sync chain completion.',
      category: 'documentation',
      owner: 'Documentation Governance',
      department: 'Platform',
      trigger: 'Documentation Registry sync',
      conditions: ['Coverage threshold configured'],
      actions: ['Run audit', 'Flag findings', 'Recommend fixes'],
      dependencies: ['documentation-governance'],
      confidencePct: 90,
    }),
    automation({
      automationId: 'workflow.shadow-mode-learning',
      name: 'Shadow Mode Learning Loop',
      description: 'Observes concierge behavior before enabling automation.',
      category: 'workflow',
      owner: 'Shadow Mode',
      department: 'Intelligence',
      trigger: 'Concierge action observed',
      conditions: ['Confidence below threshold', 'Shadow phase active'],
      actions: ['Log observation', 'Update confidence score', 'Recommend automate when ready'],
      dependencies: ['shadow-mode'],
      approvalRequired: true,
      confidencePct: 78,
      status: 'active',
    }),
    automation({
      automationId: 'future.placeholder',
      name: 'Future Automation Slot',
      description: 'Reserved registration slot for upcoming Studio OS automations.',
      category: 'future',
      owner: 'Studio OS Platform',
      department: 'Platform',
      trigger: 'TBD',
      conditions: ['Not yet implemented'],
      actions: ['Register before execute'],
      status: 'paused',
      confidencePct: 0,
      registered: true,
      approvalRequired: true,
    }),
    automation({
      automationId: 'workflow.failed-recovery',
      name: 'Failed Automation Recovery',
      description: 'Retries failed automations with exponential backoff.',
      category: 'workflow',
      owner: 'Automation Registry',
      department: 'Platform',
      trigger: 'Automation execution failed',
      conditions: ['Retry count below max', 'Not high-risk without approval'],
      actions: ['Queue retry', 'Notify owner on repeated failure'],
      dependencies: ['automation-registry', 'event-bus'],
      status: 'failed',
      successRatePct: 72,
      failureRatePct: 28,
      riskLevel: 'medium',
      executionCount: 45,
    }),
  ];

  items.push(
    automation({
      automationId: 'registry.self',
      name: 'Automation Registry™',
      description: 'Master catalog — nothing executes without registration.',
      category: 'workflow',
      owner: 'Studio OS Platform',
      department: 'Platform',
      trigger: 'Platform bootstrap',
      conditions: ['Organization boundary synced'],
      actions: ['Index all automations', 'Enforce registration gate'],
      documentation: ['docs/studio-os/automation-registry.md'],
      registered: true,
    })
  );

  void AUTOMATION_REGISTRY_ACCENT;
  return items;
}

export function getAutomationEntry(automationId: string): AutomationEntry | undefined {
  return buildAutomationCatalog().find((a) => a.automationId === automationId);
}

export function listAutomationsByCategory(category: AutomationCategory): AutomationEntry[] {
  return buildAutomationCatalog().filter((a) => a.category === category);
}

export function listAutomationsByStatus(status: AutomationStatus): AutomationEntry[] {
  return buildAutomationCatalog().filter((a) => a.status === status);
}

export function listAutomationsByRisk(risk: AutomationRiskLevel): AutomationEntry[] {
  return buildAutomationCatalog().filter((a) => a.riskLevel === risk);
}
