/**
 * Build the AIO OFFICE unified review as one self-contained page + its image files.
 *
 *   node design-authority/aio-office/office/build.mjs [outDir]      (default: design-authority/aio-office/office/dist)
 *
 * The page inlines the scoped studio CSS (the approved roots), office.css, the review chrome, the icon sheet and every
 * script (studio.js in embed mode → office-data → generated MIG_SCREENS → office-ui → page modules → office-app).
 * Images are copied at the relative paths the scripts use (P = '.'), resized for review with python3 + Pillow.
 * Nothing here touches the live app: it reads public/, the approved migration authority and the IFTA captures.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync, statSync, copyFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

const HERE = dirname(fileURLToPath(import.meta.url));
const STUDIO = resolve(HERE, '..');
const APP = resolve(HERE, '../../..');
const REPO = resolve(APP, '..');
const OUT = resolve(process.argv[2] || join(HERE, 'dist'));
const read = (p) => readFileSync(p, 'utf8');
const sub = (s, a, b, all = false) => {
  if (!s.includes(a)) throw new Error(`build: expected text not found: ${a.slice(0, 80)}`);
  return all ? s.split(a).join(b) : s.replace(a, b);
};

/* ── CSS: scope the approved studio styles to the device (as the approved prototype did) ── */
let css = read(join(STUDIO, 'studio.css'));
css = css.replace(/@font-face \{[^}]*\}\n/g, '');
css = sub(css, ":root {\n  --text: 'AO Roboto', Roboto, Arial, sans-serif;\n  --cond: 'AO Roboto Condensed', 'Roboto Condensed', 'Arial Narrow', sans-serif;", ".ao-root {\n  --text: Roboto, Arial, sans-serif;\n  --cond: 'Roboto Condensed', 'Arial Narrow', sans-serif;");
css = sub(css, '* {\n  box-sizing: border-box;\n}', '.ao-root * {\n  box-sizing: border-box;\n}');
css = sub(css, 'html,\nbody {', '.ao-root {');
css = sub(css, 'img {\n  display: block;\n}', '.ao-root img {\n  display: block;\n}');
css = sub(css, '  min-height: 100vh;\n}', '  min-height: 100%;\n}');
css = sub(css, '100vw', 'var(--dw)', true);
const officeCss = read(join(HERE, 'office.css'));
const viewerCss = read(join(HERE, 'viewer.css'));

/* ── JS ── */
let studio = read(join(STUDIO, 'studio.js'));
studio = sub(studio, '${P}/brand/all-in-one-hero-truck.png', '${P}/brand/all-in-one-hero-truck.jpg');
studio = sub(studio, '${P}/brand/aio-login-hero.png', '${P}/brand/aio-login-hero.jpg');
const manifest = JSON.parse(read(join(REPO, 'AIO_CLIENT_MIGRATION_AUTHORITY/authority-manifest.json')));
const MIG_SCREENS = manifest
  .filter((m) => m.branch !== 'ROOT')
  .map((m) => ({ id: m.authority_id, branch: m.branch.toLowerCase(), state: m.state, life: m.lifecycle_state, name: m.screen_name, route: m.route, interactions: m.required_interactions }));
const js = [
  "window.AIO_STUDIO_EMBED = true;\nwindow.AIO_STUDIO_ASSETS = '.';",
  studio,
  read(join(HERE, 'office-data.js')),
  `/* generated by build.mjs from AIO_CLIENT_MIGRATION_AUTHORITY/authority-manifest.json */\nconst MIG_SCREENS = ${JSON.stringify(MIG_SCREENS)};`,
  read(join(HERE, 'office-ui.js')),
  read(join(HERE, 'pages-core.js')),
  read(join(HERE, 'pages-intake.js')),
  read(join(HERE, 'pages-work.js')),
  read(join(HERE, 'pages-reports-more.js')),
  read(join(HERE, 'office-app.js')),
  'boot();',
].join('\n\n');
if (js.includes('</script')) throw new Error('build: a script contains </script');
const sheet = read(join(APP, 'public/migration/icons/aio-icon-sheet.svg'));

/* ── page ── */
const lanes = [
  ['permitting', 'Permitting & Authorities'], ['filing', 'Filing & Fuel Taxes'], ['compliance', 'Compliance'], ['vehicles', 'Vehicles & Fleet'], ['dispatch', 'Dispatch'], ['brokerage', 'Brokerage'],
  ['insurance', 'Insurance'], ['factoring', 'Factoring'], ['bookkeeping', 'Bookkeeping'], ['drivers', 'Drivers & Carriers'], ['maintenance', 'Mechanic / Maintenance'], ['roadready', 'Road Ready'],
];
const domains = [['clients', 'Clients'], ['services', 'Services'], ['financial_revenue', 'Financial / Revenue'], ['filing_history', 'Filing history'], ['compliance', 'Compliance'], ['dispatch_brokerage', 'Dispatch & Brokerage'], ['bookkeeping', 'Bookkeeping'], ['migration', 'Migration'], ['exports', 'Exports']];
const moreEntries = [['clients', 'Clients'], ['documents_vault', 'Documents & Vault'], ['messages', 'Messages'], ['growth_crm', 'Growth / CRM'], ['billing', 'Billing'], ['service_catalog', 'Service catalog'], ['team_staff', 'Team & Staff'], ['mechanic_network', 'Mechanic network'], ['system_settings', 'System settings'], ['help_support', 'Help & Support'], ['account', 'Account']];
const opt = (v, l) => `<option value="${v}">${l}</option>`;
const jump = `<select id="vjump" aria-label="Go to a page"><option value="">Go to…</option>
  <optgroup label="Roots">${[['home', 'Home'], ['intake', 'Intake'], ['work', 'Work'], ['reports', 'Reports'], ['more', 'More']].map(([v, l]) => opt(v, l)).join('')}</optgroup>
  <optgroup label="Work">${[['work/mine', 'My work'], ['work/queue', 'All open work'], ...lanes.map(([v, l]) => [`work/${v}`, l])].map(([v, l]) => opt(v, l)).join('')}</optgroup>
  <optgroup label="Intake">${[['intake/status', 'Migration status'], ['intake/review', 'Founder review'], ['intake/prebuilt', 'Prebuilt clients'], ['intake/activation', 'Activation & invites'], ['intake/flow/existing/0', 'Approved flow · existing client']].map(([v, l]) => opt(v, l)).join('')}</optgroup>
  <optgroup label="Reports">${domains.map(([v, l]) => opt(`reports/${v}`, l)).join('')}</optgroup>
  <optgroup label="More">${moreEntries.map(([v, l]) => opt(`more/${v}`, l)).join('')}</optgroup>
  <optgroup label="Client 360">${[['client/c-dh', 'Delta Hauling LLC'], ['client/c-tk', 'T&K Transport'], ['client/c-mt', 'Mason Transport (prebuilt)']].map(([v, l]) => opt(v, l)).join('')}</optgroup>
</select>`;
/* The artifact host adds the document skeleton, so the published page is a fragment (as the approved prototype was);
   local.html wraps the same fragment in a standards-mode document for QA. */
const html = `<title>AIO Office Review</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@400;500;600;700;800&family=Roboto:wght@400;500;600;700&display=swap" rel="stylesheet">
<style>
${viewerCss}
${css}
${officeCss}
</style>
<div class="viewer">
  <header class="v-top"><h1>AIO Office · unified review</h1><p>The internal office as one connected product: five roots, twelve WORK lanes, INTAKE, ten report areas and eleven MORE destinations. Sample records only. This is a review, not the live app.</p></header>
  <div class="tools">
    <div class="group" role="group" aria-label="Screen size"><span>Screen</span><button type="button" data-device="phone">Phone</button><button type="button" data-device="tablet">Tablet</button><button type="button" data-device="desktop">Desktop</button><button type="button" data-device="wide">Ultra-wide</button></div>
    <div class="group" role="group" aria-label="View as"><span>View as</span><button type="button" data-role="founder">Founder</button><button type="button" data-role="staff">Staff</button><button type="button" data-role="staff-granted">Staff with reports</button></div>
    <div class="group" role="group" aria-label="Navigate"><button type="button" id="vback">Back</button><button type="button" id="vsearch">Search</button>${jump}<button type="button" id="guide-toggle" aria-pressed="true">Guide</button></div>
  </div>
  <div class="v-addr"><code id="addr"></code><span id="scale"></span></div>
  <div class="v-body has-guide" id="vbody">
    <div id="stage"><div id="sizer"><div id="ao-root" class="ao-root device"><div id="ao-screen" class="screen"></div><div id="ao-layer"></div><div id="ao-toast" class="proto-toast" hidden></div></div></div></div>
    <aside id="guide" class="guide" aria-label="Review guide"></aside>
  </div>
</div>
<div style="display:none" aria-hidden="true">${sheet}</div>
<script>
${js}
</script>
`;

/* ── images (relative to the page, as the scripts reference them) ── */
const jobs = [];
const plate = (name, w) => jobs.push([join(APP, `public/brand/ifta/plates/${name}`), join(OUT, `brand/ifta/plates/${name}`), w, 'jpg']);
['client-hero.jpg', 'public-hero.jpg', 'client-insights.jpg', 'public-footer-desktop.jpg', 'public-road.jpg', 'public-map.jpg', 'staff-hero.jpg'].forEach((n) => plate(n, 2560));
jobs.push([join(APP, 'public/brand/all-in-one-hero-truck.png'), join(OUT, 'brand/all-in-one-hero-truck.jpg'), 1774, 'jpg']);
jobs.push([join(APP, 'public/brand/aio-login-hero.png'), join(OUT, 'brand/aio-login-hero.jpg'), 1536, 'jpg']);
for (const n of ['brand-lockup.png', 'hero-root.jpg', 'env-wide-tablet.jpg', 'env-wide-desktop.jpg', 'path-existing.jpg', 'path-new.jpg', 'path-bulk.jpg', 'secure-laptop.jpg', ...['samsara', 'motive', 'geotab', 'omnitracs', 'trimble', 'keeptruckin'].map((p) => `prov-${p}.png`)]) jobs.push([join(APP, `public/migration/${n}`), join(OUT, `migration/${n}`), 0, 'copy']);
for (const n of ['permitting-authorities', 'compliance', 'insurance', 'factoring', 'bookkeeping', 'drivers-carriers', 'mechanic-maintenance']) jobs.push([join(STUDIO, `standins/${n}.jpg`), join(OUT, `standins/${n}.jpg`), 0, 'copy']);
for (const m of manifest) jobs.push([join(REPO, 'AIO_CLIENT_MIGRATION_AUTHORITY', m.source_image), join(OUT, `mig/${m.authority_id}.jpg`), 600, 'jpg']);
for (const k of ['QUEUE', 'CASE']) for (const w of [393, 834, 1440]) jobs.push([join(APP, `docs/aio/ifta/visual-reconstruction/captures/after/STAFF_${k}_${w}.jpg`), join(OUT, `ifta/STAFF_${k}_${w}.jpg`), 0, 'copy']);

mkdirSync(OUT, { recursive: true });
const fresh = (src, dst) => existsSync(dst) && statSync(dst).mtimeMs >= statSync(src).mtimeMs;
const resize = [];
for (const [src, dst, w, kind] of jobs) {
  if (!existsSync(src)) throw new Error(`build: missing asset ${src}`);
  mkdirSync(dirname(dst), { recursive: true });
  if (fresh(src, dst)) continue;
  if (kind === 'copy') copyFileSync(src, dst);
  else resize.push([src, dst, w]);
}
if (resize.length) {
  const py = `import json,sys\nfrom PIL import Image\nfor src,dst,w in json.loads(sys.argv[1]):\n  im=Image.open(src).convert('RGB')\n  if im.width>w: im=im.resize((w,round(im.height*w/im.width)),Image.LANCZOS)\n  im.save(dst,'JPEG',quality=82,optimize=True,progressive=True)`;
  execFileSync('python3', ['-I', '-c', py, JSON.stringify(resize)], { stdio: 'inherit' });
}
writeFileSync(join(OUT, 'index.html'), html);
writeFileSync(join(OUT, 'local.html'), `<!doctype html>\n<html lang="en">\n<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"></head>\n<body>\n${html}</body>\n</html>\n`);
writeFileSync(join(OUT, 'files.json'), JSON.stringify(jobs.map(([, dst]) => dst.slice(OUT.length + 1)), null, 1));
console.log(`built ${join(OUT, 'index.html')} (${(html.length / 1024).toFixed(0)} KB) + ${jobs.length} images (${resize.length} resized)`);
