/*
 * AIO OFFICE unified review — INTAKE. The approved client-migration experience is not redesigned: the INTAKE root
 * carries the approved root's own modules (hero, the three paths, migration status, file types, providers, the security
 * panel, START MIGRATION) inside the office frame, and every flow step is the approved authority screen itself
 * (AIO_CLIENT_MIGRATION_AUTHORITY, 41 screens). What is new is the staff working layer around it: the ten INTAKE sections
 * and a case page per migration. Staff preparation stops at PREBUILT; only the client's confirmation makes a client ACTIVE.
 * MIG_SCREENS is generated by build.mjs from AIO_CLIENT_MIGRATION_AUTHORITY/authority-manifest.json.
 */
const MIG_FLOW_ARTIFACT = 'https://claude.ai/artifact/1rPbngoDNkMNwTg695HUZQ';
const MIG_BRANCH = {
  existing: ['EXISTING CLIENT FILE', 'IMPORT CURRENT RECORDS FROM ANOTHER PROVIDER OR A PREVIOUS SYSTEM.', 'path-existing.jpg', 'migrate'],
  new: ['NEW CLIENT FILE', 'START FRESH AND UPLOAD RECORDS TO AIO.', 'path-new.jpg', 'person-plus'],
  bulk: ['BULK BATCH MIGRATION', 'IMPORT MULTIPLE CLIENTS AT ONCE (FOR FLEETS OR ACCOUNTANTS).', 'path-bulk.jpg', 'database'],
  activation: ['CLIENT ACTIVATION', 'WHAT THE CLIENT SEES IN THEIR OWN OFFICE WHEN THEY CONFIRM. STAFF NEVER CONFIRM FOR THEM.', null, 'profile'],
};
const INTAKE_SECTIONS = [
  ['existing', 'EXISTING CLIENT FILE', 'migrate', 'A CURRENT CLIENT’S RECORDS FROM ANOTHER PROVIDER.'],
  ['new', 'NEW CLIENT FILE', 'person-plus', 'A NEW CLIENT, FROM THEIR UPLOADS.'],
  ['bulk', 'BULK BATCH MIGRATION', 'database', 'MANY CLIENTS AT ONCE.'],
  ['status', 'MIGRATION STATUS', 'time-log', 'EVERY CASE AND WHERE IT STANDS.'],
  ['extraction', 'EXTRACTION & CLASSIFICATION', 'search-file', 'WHAT AIO READ FROM THE FILES.'],
  ['match', 'MATCH & RECONCILE', 'filter', 'DUPLICATES AND CONFLICTS TO SETTLE.'],
  ['review', 'FOUNDER REVIEW', 'security', 'APPROVAL LANDS ON PREBUILT — NEVER ACTIVE.'],
  ['prebuilt', 'PREBUILT CLIENTS', 'company', 'PREPARED BY STAFF, NOT ACTIVE.'],
  ['activation', 'ACTIVATION & INVITES', 'letter', 'THE CLIENT CONFIRMS IN THEIR OWN OFFICE.'],
  ['history', 'MIGRATION HISTORY', 'history', 'COMPLETED MIGRATIONS.'],
];
const migStatus = (m) => SESSION.status[`mig:${m.id}`] ?? m.stage;
const migLife = (m) => SESSION.status[`miglife:${m.id}`]?.[0] ?? m.life;
const migIdx = (life) => MIG_LIFE.findIndex(([k]) => k === life);
const branchScreens = (b) => MIG_SCREENS.filter((s) => s.branch === b);
const screenAt = (id) => {
  const s = MIG_SCREENS.find((x) => x.id === id);
  return s ? [s.branch, branchScreens(s.branch).indexOf(s)] : ['existing', 0];
};
const GATE = `<div class="gate">${ico('lock')}<div><b>STAFF PREPARATION DOES NOT MAKE A CLIENT ACTIVE.</b><span>APPROVAL LANDS A CLIENT ON PREBUILT. THE CLIENT IS INVITED AND CONFIRMS THEIR OWN INFORMATION — ONLY THAT CONFIRMATION MAKES THEM ACTIVE.</span></div></div>`;
const caseRow = (m) => ({ go: `intake/case/${m.id}`, lead: icoTile(MIG_BRANCH[m.branch][3]), title: m.name, sub: `${MIG_BRANCH[m.branch][0]} · ${m.files} FILES · ${m.source}`, meta: `${staffName(m.owner)} · STARTED ${m.started}`, status: migStatus(m) });

function intakePage(r) {
  const [, a, b, c] = r.seg;
  if (!a) return intakeRoot();
  if (a === 'case') return intakeCase(b, r);
  if (a === 'flow') return flowViewer(b, Number(c) || 0, r);
  if (INTAKE_SECTIONS.some(([k]) => k === a)) return intakeSection(a);
  return missing(r);
}

/* ── INTAKE root: the approved migration root's modules, inside the office frame ── */
function intakeRoot() {
  meta('INTAKE', 'APPROVED AUTHORITY', 'LIVE: PARTIAL · /office/migration (MigrationStudioPage)', 'The approved migration root’s modules, in the office frame. The cases and sections below them are new for staff.');
  const paths = ['existing', 'new', 'bulk']
    .map((k) => {
      const [t, s, img] = MIG_BRANCH[k];
      return `<div class="pathc" data-go="intake/flow/${k}/0"><div class="pathc__img"><img src="migration/${img}" alt=""></div><b>${t}</b><small>${s}</small><span class="arrow" style="justify-self:end">${ico('arrow')}</span></div>`;
    })
    .join('');
  const steps = ['UPLOAD · FILES RECEIVED', 'EXTRACT · READING DATA', 'CLASSIFY · ORGANIZING RECORDS', 'VALIDATE · CHECKING ACCURACY', 'REVIEW · CONFIRMATION', 'COMPLETE · READY TO USE'];
  const open = Object.values(MIG_CASES).filter((m) => migLife(m) !== 'ACTIVE');
  const provs = ['samsara', 'motive', 'geotab', 'omnitracs', 'trimble', 'keeptruckin'];
  return `<main class="main">
    <section class="plate plate--light hero plate--fade bleed mig-hero"><img src="migration/${{ mobile: 'hero-root.jpg', tablet: 'env-wide-tablet.jpg', desktop: 'env-wide-desktop.jpg' }[VP]}" alt="" style="object-position:${VP === 'mobile' ? '70% 50%' : '100% 50%'}">
      <p class="hero__kicker">CLIENT MIGRATION INTAKE</p><h1 class="hero__title"><span>BRING YOUR</span><span>DATA TO AIO</span></h1><p class="hero__sub">LET’S GET EXISTING RECORDS INTO AIO SO EVERYTHING IS MANAGED IN ONE SECURE PLACE.</p></section>
    <div class="after-band"><div class="paths">${paths}</div></div>
    <section class="sec">${secHead('MIGRATION STATUS', 'TRACK THE PROGRESS OF DATA AFTER UPLOAD.', `<span class="btn" data-go="intake/status">VIEW ALL MIGRATIONS ${ico('fwd')}</span>`)}${stepper(steps, 0).replace('class="steps"', 'class="steps steps--h"')}</section>
    <div class="grid2" style="margin-top:14px">
      <section class="panel" style="padding:14px">${secHead('SUPPORTED FILE TYPES', 'IMPORT RECORDS FROM THE CURRENT PROVIDER.')}<div class="ftypes"><span>EXCEL</span><span>PDF</span><span>CSV</span><span>DOCUMENTS</span><span>ZIP FILES</span></div></section>
      <section class="panel" style="padding:14px">${secHead('COMMON PROVIDERS', 'WE SUPPORT MOST MAJOR SYSTEMS.')}<div class="provs">${provs.map((p) => `<span><img src="migration/prov-${p}.png" alt="">${p === 'keeptruckin' ? 'KEEPTRUCKIN' : p.toUpperCase()}</span>`).join('')}</div></section>
    </div>
    <section class="panel secure" style="margin-top:14px"><div><b>YOUR DATA IS SECURE</b><span>BANK-LEVEL ENCRYPTION AND SECURE PROCESSING KEEP INFORMATION SAFE. FILES ARE NEVER SHARED.</span></div><img src="migration/secure-laptop.jpg" alt=""></section>
    <div class="cta-wide"><span class="btn btn--gold" data-go="intake/flow/existing/0">START MIGRATION ${ico('fwd')}</span></div>
    ${GATE}
    <section class="sec">${secHead('CASES IN PROGRESS', `${open.length} OPEN · SAMPLE CASES`, `<span class="btn btn--sm" data-go="intake/status">BOARD ${ico('fwd')}</span>`)}${rows(open.map(caseRow))}</section>
    <section class="sec">${secHead('INTAKE SECTIONS', 'TEN PLACES THE MIGRATION WORK HAPPENS.')}<div class="panel rows">${INTAKE_SECTIONS.map(([k, t, i, s]) => `<div class="row" data-go="intake/${k}"><span class="row__lead">${icoTile(i)}</span><span class="row__t"><b>${t}</b><small>${s}</small></span><span class="row__s">${st(['PARTIAL', 'mute'])}</span>${ico('fwd', 'chev')}</div>`).join('')}</div></section>
    <p class="muted" style="margin-top:12px;font:500 10px/1.4 var(--text);letter-spacing:.08em">THE CLICKABLE MIGRATION FLOW (LIVE SCREENS, EVERY BRANCH) IS ALSO AVAILABLE: <a class="ext" href="${MIG_FLOW_ARTIFACT}" target="_blank" rel="noopener">${ico('open-link')}OPEN THE MIGRATION FLOW PROTOTYPE</a></p>
  </main>`;
}

/* ── the ten sections ── */
function intakeSection(k) {
  const [, title, icon, sub] = INTAKE_SECTIONS.find(([x]) => x === k);
  meta(`INTAKE › ${title}`, 'NEW · FOR REVIEW', 'LIVE: PARTIAL · /office/migration/*', 'Staff working layer around the approved migration screens.');
  const head = pageHead({ trail: [['INTAKE', 'intake'], [title]], title, sub, chips: [['SAMPLE', 'mute']] });
  const cases = Object.values(MIG_CASES);
  const tabsRow = tabs(INTAKE_SECTIONS.map(([x, t]) => [x, t, null, `intake/${x}`]), k);
  let body = '';
  if (['existing', 'new', 'bulk'].includes(k)) {
    const [t, s, img] = MIG_BRANCH[k];
    const list = cases.filter((m) => m.branch === k && migLife(m) !== 'ACTIVE');
    body = `<div class="split"><div class="stack">
        ${section('APPROVED SCREENS IN THIS PATH', 'THE AUTHORITY SCREENS, IN ORDER. EACH OPENS FULL SIZE.', thumbs(k))}
        ${section('CASES ON THIS PATH', '', rows(list.map(caseRow), 'NO OPEN CASES ON THIS PATH'))}
      </div><aside class="aside"><div class="pathc" data-go="intake/flow/${k}/0"><div class="pathc__img" style="height:140px"><img src="migration/${img}" alt=""></div><b>${t}</b><small>${s}</small><span class="btn btn--gold">START ${ico('fwd')}</span></div>${GATE}</aside></div>`;
  }
  if (k === 'status') {
    const cols = [
      ['INTAKE', ['INTAKE_IN_PROGRESS', 'MIGRATION_IN_PROGRESS']],
      ['REVIEW', ['MIGRATION_REVIEW_REQUIRED']],
      ['PREBUILT', ['PREBUILT']],
      ['AWAITING CLIENT', ['CLIENT_CONFIRMATION_REQUIRED']],
      ['ACTIVE', ['ACTIVE']],
    ];
    body = `<div class="board" style="--cols:5">${cols
      .map(([t, lifes]) => {
        const list = cases.filter((m) => lifes.includes(migLife(m)));
        return `<div class="col"><div class="col__h">${t}<i>${list.length}</i></div>${list.map((m) => `<div class="card" data-go="intake/case/${m.id}"><b>${m.name}</b><small>${MIG_BRANCH[m.branch][0]} · ${m.files} FILES</small><div class="card__m">${st(migStatus(m))}</div></div>`).join('') || '<small class="muted">NOTHING HERE</small>'}</div>`;
      })
      .join('')}</div>${GATE}`;
  }
  if (k === 'extraction') {
    const list = cases.filter((m) => ['INTAKE_IN_PROGRESS', 'MIGRATION_IN_PROGRESS'].includes(migLife(m)));
    body = `${rows(list.map(caseRow), 'NOTHING IS BEING READ RIGHT NOW')}
      ${section('WHAT AIO READ · LAKEVIEW DISTRIBUTION CO.', 'CLASSIFIED FROM 9 FILES. STAFF CHECK EVERY CLASSIFICATION BEFORE REVIEW.', rows([
        { title: 'BUSINESS IDENTITY', sub: 'ARTICLES OF ORGANIZATION · EIN LETTER', status: ['READ', 'ok'], sim: 'cls-1' },
        { title: 'PERMITS & AUTHORITY', sub: 'USDOT REGISTRATION · MC CERTIFICATE', status: ['READ', 'ok'], sim: 'cls-2' },
        { title: 'INSURANCE', sub: 'CERTIFICATE OF INSURANCE', status: ['READ', 'ok'], sim: 'cls-3' },
        { title: 'VEHICLES', sub: '2 CAB CARDS', status: ['READING', 'gold'], sim: 'cls-4' },
        { title: 'UNREADABLE', sub: '1 PHOTO OF A RECEIPT — NEEDS A BETTER SCAN', status: ['NEEDS STAFF', 'warn'], sim: 'cls-5' },
      ]))}${section('APPROVED SCREENS', '', thumbs('new', ['AIO-MIG-NEW-RECEIVED-001', 'AIO-MIG-NEW-EXTRACT-001', 'AIO-MIG-NEW-IDENTITY-001', 'AIO-MIG-NEW-RECORDS-001']))}`;
  }
  if (k === 'match') {
    const conflicts = [
      ['TWO VEHICLE RECORDS SHARE VIN …4410', 'THE SAMSARA EXPORT AND A SCANNED CAB CARD DISAGREE ON THE UNIT NUMBER.'],
      ['OWNER NAME DIFFERS BETWEEN THE EIN LETTER AND THE MC CERTIFICATE', '“BLUELINE TRANSPORT LLC” VS “BLUE LINE TRANSPORT”.'],
    ];
    body = `${rows(cases.filter((m) => m.conflicts && migLife(m) === 'MIGRATION_REVIEW_REQUIRED').map(caseRow))}
      ${section('CONFLICTS · BLUELINE TRANSPORT', 'EACH ONE IS SETTLED BY A PERSON. NOTHING IS MERGED SILENTLY.', `<div class="panel">${conflicts.map(([t, s], i) => `<div class="conf"><b>${t}</b><small class="muted">${s}</small><div class="conf__opts"><span class="btn btn--sm" data-sim="conf-${i}-a" data-label="KEEP THE FILE’S VALUE" data-effect="USE THE VALUE FROM THE UPLOADED FILE AND RECORD WHY.">KEEP THE FILE’S VALUE</span><span class="btn btn--sm" data-sim="conf-${i}-b" data-label="KEEP BOTH FOR REVIEW" data-effect="FLAG BOTH VALUES FOR FOUNDER REVIEW.">KEEP BOTH FOR REVIEW</span></div></div>`).join('')}</div>`)}
      ${section('APPROVED SCREENS', '', thumbs('existing', ['AIO-MIG-EXISTING-MATCH-001', 'AIO-MIG-EXISTING-CONFLICTS-001']))}`;
  }
  if (k === 'review') {
    const list = cases.filter((m) => migLife(m) === 'MIGRATION_REVIEW_REQUIRED');
    body = `${FOUNDER ? '' : notice('THE FOUNDER APPROVES MIGRATIONS. YOU CAN PREPARE A CASE AND SEND IT FOR REVIEW.')}${rows(list.map(caseRow))}${GATE}
      ${section('APPROVED SCREENS', '', thumbs('existing', ['AIO-MIG-EXISTING-REVIEW-001', 'AIO-MIG-EXISTING-APPROVAL-001']))}`;
  }
  if (k === 'prebuilt') {
    const list = cases.filter((m) => migLife(m) === 'PREBUILT');
    body = `${GATE}${rows(list.map(caseRow), 'NO PREBUILT CLIENTS')}${section('APPROVED SCREENS', '', thumbs('existing', ['AIO-MIG-EXISTING-PREBUILT-001', 'AIO-MIG-EXISTING-INVITE-001']))}`;
  }
  if (k === 'activation') {
    const list = cases.filter((m) => migLife(m) === 'CLIENT_CONFIRMATION_REQUIRED');
    body = `${GATE}${rows(list.map(caseRow), 'NO INVITES WAITING')}
      ${section('WHAT THE CLIENT SEES', 'THE APPROVED ACTIVATION SCREENS IN THE CLIENT’S OFFICE. SHOWN SO STAFF KNOW WHAT THE CLIENT IS ASKED.', thumbs('activation'))}`;
  }
  if (k === 'history') {
    const list = cases.filter((m) => migLife(m) === 'ACTIVE');
    body = section('COMPLETED', 'CLIENTS WHO CONFIRMED AND ARE ACTIVE.', rows(list.map((m) => ({ ...caseRow(m), meta: `CONFIRMED ${m.confirmed}` }))));
  }
  return `<main class="main">${head}${tabsRow}<div style="margin-top:12px">${body}</div></main>`;
}
function thumbs(branch, only) {
  const list = branchScreens(branch).filter((s) => !only || only.includes(s.id));
  return `<div class="thumbs">${list
    .map((s) => `<div class="thumb" data-go="intake/flow/${branch}/${branchScreens(branch).indexOf(s)}"><div class="thumb__img"><img src="mig/${s.id}.jpg" alt="" loading="lazy"></div><b>${s.name}</b><small>${s.state.replace(/_/g, ' ')}</small></div>`)
    .join('')}</div>`;
}

/* ── the approved flow, one authority screen at a time ── */
function flowViewer(branch, n, r) {
  const list = branchScreens(branch);
  if (!list.length) return missing(r);
  const i = Math.max(0, Math.min(n, list.length - 1));
  const s = list[i];
  const [bt, bs] = MIG_BRANCH[branch];
  const client = branch === 'activation';
  meta(`INTAKE › ${bt} › ${s.name}`, 'APPROVED AUTHORITY', `LIVE: ${s.route}`, `${s.id} — the approved screen, unchanged. ${client ? 'It shows the client office.' : 'It predates the five-root decision, so its own dock still shows FILING; the office navigation around it is the approved five roots, and the live React flow renders the current dock.'}`);
  const life = MIG_LIFE.find(([k]) => k === s.life);
  const gate = ['PREBUILT', 'CLIENT_CONFIRMATION_REQUIRED'].includes(s.life) ? GATE : '';
  const nav = `<div class="flow-nav">${i > 0 ? `<span class="btn" data-go="intake/flow/${branch}/${i - 1}">${ico('back')}PREVIOUS</span>` : ''}${i < list.length - 1 ? `<span class="btn btn--gold" data-go="intake/flow/${branch}/${i + 1}">NEXT · ${list[i + 1].name} ${ico('fwd')}</span>` : `<span class="btn btn--gold" data-go="intake">${ico('pass')}BACK TO INTAKE</span>`}</div>`;
  const detail = `<div class="flowd panel" style="padding:16px">
      <div class="pg__chips">${st([`STEP ${i + 1} OF ${list.length}`, 'gold'])}${life ? st([life[1], s.life === 'ACTIVE' ? 'ok' : s.life === 'PREBUILT' ? 'mute' : 'gold']) : ''}${client ? st(['CLIENT OFFICE', 'mute']) : ''}</div>
      <h2 class="flowd__t">${s.name}</h2>
      <p class="sec__sub">${client ? 'SHOWN FROM THE CLIENT’S OFFICE. STAFF SEE IT; ONLY THE CLIENT ACTS ON IT.' : 'WHAT STAFF CAN DO ON THIS SCREEN:'}</p>
      <ul>${s.interactions.map((x) => `<li>${ico('pass')}${x.toUpperCase()}</li>`).join('')}</ul>
      ${nav}
      <div class="flow-steps">${list.map((x, k) => `<a class="${k === i ? 'is-on' : ''}" data-go="intake/flow/${branch}/${k}" title="${x.name}">${k + 1}</a>`).join('')}</div>
      <small class="muted">${s.id} · LIVE ROUTE ${s.route}</small>
      <a class="ext" href="${MIG_FLOW_ARTIFACT}" target="_blank" rel="noopener">${ico('open-link')}TRY IT IN THE CLICKABLE MIGRATION FLOW</a>
    </div>${gate}`;
  const branchList = WIDE ? `<aside class="aside">${section(bt, bs, `<div class="panel rows">${list.map((x, k) => `<div class="row" data-go="intake/flow/${branch}/${k}"><span class="row__lead"><span class="row__ico">${k + 1}</span></span><span class="row__t"><b>${x.name}</b><small>${x.state.replace(/_/g, ' ')}</small></span>${k === i ? `<span class="row__s">${st(['HERE', 'gold'])}</span>` : ''}</div>`).join('')}</div>`)}</aside>` : '';
  return `<main class="main">${pageHead({ trail: [['INTAKE', 'intake'], [bt, branch === 'activation' ? 'intake/activation' : `intake/${branch}`], [`STEP ${i + 1}`]], title: bt, sub: bs })}
    <div class="embed__bar" style="margin:12px 0"><span><b>APPROVED MIGRATION AUTHORITY</b> — SHOWN EXACTLY AS APPROVED. NOT REDESIGNED.</span><span>${s.id}</span></div>
    <div class="flowv"><div class="phone-shot"><img src="mig/${s.id}.jpg" alt="${s.name} — approved screen"></div>${detail}${branchList}</div></main>`;
}

/* ── one migration case ── */
function intakeCase(id, r) {
  const m = MIG_CASES[id];
  if (!m) return missing(r);
  meta('INTAKE › MIGRATION CASE', 'NEW · FOR REVIEW', 'LIVE: PARTIAL · MIGRATION BATCHES (approveMigrationBatchForOffice → PREBUILT)', 'A case page for staff; each step links to its approved screen.');
  const life = migLife(m);
  const [b, idx] = screenAt(m.screen);
  const acts = {
    INTAKE_IN_PROGRESS: [{ label: 'CHECK THE CLASSIFICATIONS', sim: 'mig-cls', ico: 'search', effect: 'CONFIRM WHAT AIO READ FROM EACH FILE.' }],
    MIGRATION_REVIEW_REQUIRED: m.conflicts
      ? [{ label: 'SETTLE CONFLICTS', sim: 'mig-conf', ico: 'filter', effect: 'DECIDE EACH CONFLICT; NOTHING IS MERGED SILENTLY.' }, { label: 'SEND FOR FOUNDER REVIEW', sim: 'mig-send', effect: 'PUT THE CASE IN THE FOUNDER REVIEW QUEUE.' }]
      : [
          { label: 'APPROVE · LANDS ON PREBUILT', sim: 'mig-approve', ico: 'pass', founder: true, effect: 'CREATE THE CLIENT AS PREBUILT — PREPARED, NOT ACTIVE. NO SERVICE STARTS.', set: `mig:${m.id}=PREBUILT · NOT ACTIVE YET|mute;miglife:${m.id}=PREBUILT` },
          { label: 'SEND BACK TO STAFF', sim: 'mig-back', founder: true, effect: 'RETURN THE CASE WITH NOTES.' },
          ...(FOUNDER ? [] : [{ label: 'SEND FOR FOUNDER REVIEW', sim: 'mig-send', effect: 'PUT THE CASE IN THE FOUNDER REVIEW QUEUE.' }]),
        ],
    PREBUILT: [{ label: 'SEND ACTIVATION INVITE', sim: 'mig-invite', ico: 'letter', effect: 'EMAIL THE CLIENT A SECURE LINK TO REVIEW AND CONFIRM THEIR INFORMATION.', set: `mig:${m.id}=INVITED · AWAITING CLIENT|gold;miglife:${m.id}=CLIENT_CONFIRMATION_REQUIRED` }, { label: 'MARK ACTIVE', off: 'ONLY THE CLIENT’S CONFIRMATION MAKES A CLIENT ACTIVE' }],
    CLIENT_CONFIRMATION_REQUIRED: [{ label: 'RESEND INVITE', sim: 'mig-resend', ico: 'letter', effect: 'SEND THE SAME SECURE LINK AGAIN.' }, { label: 'CONFIRM ON THE CLIENT’S BEHALF', off: 'NOT ALLOWED — THE CLIENT CONFIRMS IN THEIR OWN OFFICE' }],
    ACTIVE: [{ label: 'NOTHING LEFT TO DO', off: 'THE CLIENT CONFIRMED · ACTIVE' }],
  }[life];
  const main = `${section('LIFECYCLE', 'WHERE THIS CLIENT IS. STAFF WORK STOPS AT PREBUILT.', stepper(MIG_LIFE.map(([, t]) => t), migIdx(life)))}
    ${section('THE CASE', '', kv([['PATH', MIG_BRANCH[m.branch][0]], ['SOURCE', m.source], ['FILES', String(m.files)], ['WHAT AIO FOUND', m.found], ['CONFLICTS', String(m.conflicts)], ['OWNER', staffName(m.owner)], ['STARTED', m.started], ['CLIENT RECORD', m.client ? `<a class="lnk" data-go="client/${m.client}">${clientName(m.client)}</a>` : 'NONE UNTIL APPROVAL LANDS ON PREBUILT']], 2))}
    ${section('APPROVED SCREEN FOR THIS STEP', 'THE AUTHORITY SCREEN STAFF USE HERE.', `<div class="grid2"><div class="thumb" data-go="intake/flow/${b}/${idx}" style="max-width:220px"><div class="thumb__img"><img src="mig/${m.screen}.jpg" alt=""></div><b>${MIG_SCREENS.find((s) => s.id === m.screen)?.name ?? ''}</b><small>OPEN FULL SIZE</small></div>${['PREBUILT', 'CLIENT_CONFIRMATION_REQUIRED'].includes(life) ? GATE : ''}</div>`)}`;
  const head = pageHead({ trail: [['INTAKE', 'intake'], [INTAKE_SECTIONS.find(([k]) => k === m.section)?.[1] ?? 'CASES', `intake/${m.section}`], [m.name]], title: m.name, sub: `${MIG_BRANCH[m.branch][0]} · SAMPLE CASE`, chips: [migStatus(m)], actions: VP === 'desktop' ? '' : actionsBar(acts.filter((a) => !a.off).slice(0, 1)) });
  return `<main class="main">${head}${m.client ? ctxBar(m.client) : ''}<div class="split" style="margin-top:14px"><div class="stack">${main}${section('HISTORY', '', timeline(histFor(`mig:${m.id}`, [[m.confirmed ?? 'OCT 7, 2026', m.confirmed ? 'CLIENT CONFIRMED — ACTIVE' : 'CASE UPDATED', m.confirmed ? 'CLIENT' : staffName(m.owner), m.confirmed ? 'client' : 'internal'], [m.started, `${m.files} FILES RECEIVED`, staffName(m.owner), 'internal']])))}</div>
    <aside class="aside">${actionsPanel(acts)}${m.client ? section('RELATED', '', related([{ lane: 'CLIENT 360', title: clientName(m.client), go: `client/${m.client}`, why: LIFE[client(m.client).life][0] }])) : ''}</aside></div></main>`;
}
