import type { VisionStop } from '../../../studio-os-core/vision-engine/types';
import { VISION_DEFAULT_DWELL_MS, VISION_OPENING_MS, VISION_SLOW_DWELL_MS } from '../../../studio-os-core/vision-engine/constants';

function notes(partial: VisionStop['presenter']): VisionStop['presenter'] {
  return partial;
}

const DWELL = VISION_DEFAULT_DWELL_MS;
const SLOW = VISION_SLOW_DWELL_MS;

function chapterIdFromSection(sectionLabel: string): string {
  return sectionLabel.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

/** Canonical auto-tour script — desktop mansion → Build-A-Wig → mobile → finale. */
const RAW_FRONTAL_SLAYER_VISION_STOPS: Omit<VisionStop, 'chapterId'>[] = [
  {
    id: 'opening',
    sectionLabel: 'WELCOME',
    title: 'Frontal Slayer',
    durationMs: VISION_OPENING_MS,
    transition: 'fade',
    presenter: notes({
      voiceover:
        'Welcome. Before we show you a single button or menu, take a breath. Frontal Slayer is not a website you browse — it is a mansion you enter. Every surface, every animation, every room exists because luxury beauty deserves a destination, not a catalog.',
      whyExists: 'Establish emotional tone before feature walkthrough.',
      problemSolved: 'Stakeholders often judge UX before understanding world-building.',
      emotionalResponse: 'Awe, calm, anticipation.',
      designPhilosophy: 'Cinematic reveal — Apple keynote pacing.',
      customerJourney: 'Arrival before exploration.',
      futureExpansion: 'Seasonal opening sequences for launches.',
    }),
  },
  {
    id: 'home-intro',
    sectionLabel: 'HOMEPAGE',
    title: 'The Entry Experience',
    route: '/home/shop',
    durationMs: SLOW,
    transition: 'bloom',
    cinematicDrift: true,
    hotspots: [{ id: 'shop-hero', label: '✨ Shop', x: 0.5, y: 0.35 }],
    presenter: notes({
      voiceover:
        'This is the threshold. Notice the atmosphere — marble light, floating acrylic panels, motion that feels expensive because it is intentional. Nothing here asks you to hurry. The homepage is the first room of the mansion, not a landing page template.',
      whyExists: 'Primary brand first impression for every visitor segment.',
      problemSolved: 'Luxury brands lose trust when digital feels generic.',
      emotionalResponse: 'Confidence that this brand invests in craft.',
      designPhilosophy: 'Environmental storytelling over feature lists.',
      customerJourney: 'Discover → explore mansion → convert when ready.',
      futureExpansion: 'Seasonal hero takeovers tied to collections.',
    }),
  },
  {
    id: 'mansion-intro',
    sectionLabel: 'THE MANSION',
    title: 'A Living Architecture',
    route: '/home/shop',
    durationMs: DWELL,
    transition: 'none',
    presenter: notes({
      voiceover:
        'The mansion already exists. Four floors. Dozens of rooms. Each one designed for a purpose — reception, gallery, atelier, concierge, lounge. You are not looking at mockups. You are touring a universe creatives will expand, not invent.',
      whyExists: 'Frame the product as an existing world.',
      problemSolved: 'Agencies assume greenfield when the vision is established.',
      emotionalResponse: 'Desire to contribute to something real.',
      designPhilosophy: 'Persistent world — not page-based IA.',
      customerJourney: 'Orientation before deep room visits.',
      futureExpansion: 'New floors as brand lines launch.',
    }),
  },
  {
    id: 'concierge-reception',
    sectionLabel: 'CONCIERGE',
    title: 'Reception',
    route: '/desktop/concierge?zone=reception',
    durationMs: SLOW,
    transition: 'elevator',
    useElevator: true,
    hotspots: [{ id: 'concierge', label: '✨ Concierge', x: 0.72, y: 0.55 }],
    presenter: notes({
      voiceover:
        'Floor One — Concierge. Reception is where trust begins. White-glove service, appointments, human warmth translated into holographic UI. The elevator is not a loading bar — it is travel through the building.',
      whyExists: 'Service layer for high-touch luxury clientele.',
      problemSolved: 'E-commerce feels cold without a concierge metaphor.',
      emotionalResponse: 'Being welcomed, not processed.',
      designPhilosophy: 'Hospitality-first digital.',
      customerJourney: 'Questions → guidance → right room.',
      futureExpansion: 'Live concierge integrations.',
    }),
  },
  {
    id: 'gallery',
    sectionLabel: 'GALLERY',
    title: 'Slay Cam Gallery',
    route: '/desktop/gallery?zone=slay-cam-gallery',
    durationMs: DWELL,
    transition: 'elevator',
    useElevator: true,
    hotspots: [{ id: 'gallery', label: '✨ Gallery', x: 0.4, y: 0.45 }],
    presenter: notes({
      voiceover:
        'The Gallery floor celebrates the community — Slay Cam, creator energy, social proof as art. This is where the brand breathes beyond product photography.',
      whyExists: 'Community & UGC as luxury social proof.',
      problemSolved: 'Hair brands rarely feel culturally alive online.',
      emotionalResponse: 'Belonging, inspiration.',
      designPhilosophy: 'Museum-quality presentation of human stories.',
      customerJourney: 'Browse → aspire → shop.',
      futureExpansion: 'Curated exhibitions & collaborations.',
    }),
  },
  {
    id: 'lobby',
    sectionLabel: 'LOBBY',
    title: 'Grand Lobby',
    route: '/desktop/lobby?zone=grand-lobby',
    durationMs: SLOW,
    transition: 'elevator',
    useElevator: true,
    presenter: notes({
      voiceover:
        'The Grand Lobby — heart of circulation. Acrylic panels float like glass in marble air. Every hover, every drawer expansion, every micro-interaction was choreographed. This is where members feel the mansion pulse.',
      whyExists: 'Central hub connecting commerce & experience.',
      problemSolved: 'Flat nav hides the magic of discovery.',
      emotionalResponse: 'Playful luxury — effortless control.',
      designPhilosophy: 'Micro-interactions as jewelry.',
      customerJourney: 'Orient → choose destination.',
      futureExpansion: 'Live events & drop countdowns.',
    }),
  },
  {
    id: 'penthouse-showroom',
    sectionLabel: 'SHOWROOM',
    title: 'Hair Showroom',
    route: '/desktop/penthouse?room=showroom',
    durationMs: SLOW,
    transition: 'elevator',
    useElevator: true,
    hotspots: [{ id: 'showroom', label: '✨ Showroom', x: 0.55, y: 0.5 }],
    presenter: notes({
      voiceover:
        'Penthouse — Hair Showroom. Signature units presented like couture on mannequins in natural light. This is retail theater: each texture, each length, each silhouette tells a story before price enters the conversation.',
      whyExists: 'Hero product presentation for Signature Collection.',
      problemSolved: 'Wigs sold like SKUs instead of luxury objects.',
      emotionalResponse: 'Desire, tactile imagination.',
      designPhilosophy: 'Product as protagonist.',
      customerJourney: 'Browse units → customize → cart.',
      futureExpansion: 'AR try-on & stylist consultations.',
    }),
  },
  {
    id: 'analysis-lab',
    sectionLabel: 'ANALYSIS LAB',
    title: 'Hair Analysis Lab',
    route: '/desktop/penthouse?room=analysis-lab',
    durationMs: DWELL,
    transition: 'glass-wipe',
    presenter: notes({
      voiceover:
        'The Analysis Lab — education meets diagnostics. Tools that help guests understand their hair journey with science and empathy, not sales pressure.',
      whyExists: 'Trust-building through expertise.',
      problemSolved: 'Customers fear wrong purchases.',
      emotionalResponse: 'Empowerment, hair bestie energy.',
      designPhilosophy: 'Educator pillar of the brand voice.',
      customerJourney: 'Learn → match → recommend.',
      futureExpansion: 'AI analysis & personalized routines.',
    }),
  },
  {
    id: 'extensions-boutique',
    sectionLabel: 'BOUTIQUE',
    title: 'Extensions Boutique',
    route: '/desktop/penthouse?room=boutique',
    durationMs: DWELL,
    transition: 'glass-wipe',
    presenter: notes({
      voiceover:
        'Extensions Boutique — curated add-ons, closures, frontals. A dedicated retail room so customization never feels buried in a dropdown.',
      whyExists: 'Separate merchandising for extension ecosystem.',
      problemSolved: 'Accessory revenue lost in generic shop grids.',
      emotionalResponse: 'Completeness — build the full look.',
      designPhilosophy: 'Room per product category.',
      customerJourney: 'Discover add-ons during or after unit selection.',
      futureExpansion: 'Stylist bundles & pro kits.',
    }),
  },
  {
    id: 'baw-atelier',
    sectionLabel: 'BUILD-A-WIG',
    title: 'The Atelier',
    route: '/build-a-wig/view/noir',
    durationMs: SLOW,
    transition: 'bloom',
    hotspots: [{ id: 'baw', label: '✨ Build-A-Wig', x: 0.5, y: 0.6 }],
    presenter: notes({
      voiceover:
        'Build-A-Wig is not configuration — it is entering a digital atelier. Select your unit like choosing a silhouette from a master tailor. Every step — texture, length, density, lace — is a ritual, not a form field.',
      whyExists: 'Flagship customization experience.',
      problemSolved: 'Complex products need guided luxury flows.',
      emotionalResponse: 'Creative control, exclusivity.',
      designPhilosophy: 'Atelier pacing — one decision at a time.',
      customerJourney: 'Unit → options → preview → cart.',
      futureExpansion: 'Saved configurations & stylist handoff.',
    }),
  },
  {
    id: 'baw-texture',
    sectionLabel: 'BUILD-A-WIG',
    title: 'Texture',
    route: '/build-a-wig/view/noir/texture',
    durationMs: DWELL,
    transition: 'fade',
    presenter: notes({
      voiceover: 'Texture sets the personality of the hair — silk press straight, soft wave, beach curl. The UI lets you feel the difference before you commit.',
      whyExists: 'First tactile decision in the build.',
      problemSolved: 'Abstract SKU names confuse guests.',
      emotionalResponse: 'Sensory anticipation.',
      designPhilosophy: 'Visual-first option selection.',
      customerJourney: 'Texture → length → density chain.',
      futureExpansion: 'Video loops per texture.',
    }),
  },
  {
    id: 'baw-length',
    sectionLabel: 'BUILD-A-WIG',
    title: 'Length',
    route: '/build-a-wig/view/noir/length',
    durationMs: DWELL,
    transition: 'fade',
    presenter: notes({
      voiceover: 'Length defines silhouette. The preview updates in real time — luxury means seeing your choice, not imagining it.',
      whyExists: 'Core variant axis.',
      problemSolved: 'Returns from wrong length expectations.',
      emotionalResponse: 'Confidence in the mirror moment.',
      designPhilosophy: 'Immediate visual feedback.',
      customerJourney: 'Progressive refinement.',
      futureExpansion: 'Length guides by face shape.',
    }),
  },
  {
    id: 'baw-density',
    sectionLabel: 'BUILD-A-WIG',
    title: 'Density',
    route: '/build-a-wig/view/noir/density',
    durationMs: DWELL,
    transition: 'fade',
    presenter: notes({
      voiceover: 'Density is volume without words — from everyday natural to red-carpet full. Educate while they choose.',
      whyExists: 'Technical choice made approachable.',
      problemSolved: 'Industry jargon alienates newcomers.',
      emotionalResponse: 'Expert guidance, no gatekeeping.',
      designPhilosophy: 'PSA educator voice in UI copy.',
      customerJourney: 'Informed upsell to premium density.',
      futureExpansion: 'Density recommendations from analysis lab.',
    }),
  },
  {
    id: 'baw-lace',
    sectionLabel: 'BUILD-A-WIG',
    title: 'Lace & Hairline',
    route: '/build-a-wig/view/noir/lace',
    durationMs: DWELL,
    transition: 'fade',
    presenter: notes({
      voiceover: 'Lace and hairline options — where realism meets luxury. This is the detail that separates a unit from an transformation.',
      whyExists: 'Premium differentiation.',
      problemSolved: 'Underselling technical quality.',
      emotionalResponse: 'Trust in invisible finish.',
      designPhilosophy: 'Show the craft.',
      customerJourney: 'Education → premium lace upsell.',
      futureExpansion: 'HD lace tutorials in-lab.',
    }),
  },
  {
    id: 'baw-color',
    sectionLabel: 'BUILD-A-WIG',
    title: 'Color',
    route: '/build-a-wig/view/noir/color',
    durationMs: SLOW,
    transition: 'fade',
    presenter: notes({
      voiceover: 'Color is the emotional climax — swatches rendered with photography-bible fidelity. Live previews where premium allows. This is couture color, not hex codes.',
      whyExists: 'Highest-anxiety purchase decision.',
      problemSolved: 'Color mismatch drives returns.',
      emotionalResponse: 'Delight at accuracy.',
      designPhilosophy: 'Creative DNA pipeline to commerce.',
      customerJourney: 'Preview → confirm → slay card.',
      futureExpansion: 'Custom color consultations.',
    }),
  },
  {
    id: 'baw-styling',
    sectionLabel: 'BUILD-A-WIG',
    title: 'Styling & Finish',
    route: '/build-a-wig/view/noir/styling',
    durationMs: DWELL,
    transition: 'fade',
    presenter: notes({
      voiceover: 'Final styling — layers, crimps, flat iron finishes. The atelier completes your look before it ever ships.',
      whyExists: 'Salon finish as product option.',
      problemSolved: 'Gap between received unit and worn look.',
      emotionalResponse: 'Ready-to-slay confidence.',
      designPhilosophy: 'Salon as digital service.',
      customerJourney: 'Finish → share slay card → checkout.',
      futureExpansion: 'Stylist marketplace add-ons.',
    }),
  },
  {
    id: 'psa-suite',
    sectionLabel: 'PSA SUITE',
    title: 'Founder Hologram',
    route: '/desktop/concierge?zone=psa-suite',
    durationMs: SLOW,
    transition: 'elevator',
    useElevator: true,
    presenter: notes({
      voiceover:
        'The PSA Suite — founder voice as concierge hologram. Trust over hard sell. Four pillars: concierge, hair bestie, educator, no gatekeeping. Technology in service of human connection.',
      whyExists: 'Brand voice at scale.',
      problemSolved: 'Anonymous ecommerce lacks soul.',
      emotionalResponse: 'Intimacy, being seen.',
      designPhilosophy: 'Holographic UI — luxury sci-fi.',
      customerJourney: 'Questions → personalized guidance.',
      futureExpansion: 'Multilingual PSA & voice clone ethics guardrails.',
    }),
  },
  {
    id: 'founder-suite',
    sectionLabel: 'FOUNDER SUITE',
    title: 'Vision Room',
    route: '/desktop/concierge?zone=founder-suite',
    durationMs: DWELL,
    transition: 'glass-wipe',
    presenter: notes({
      voiceover:
        'Founder Suite — where institutional memory lives. Decisions, philosophy, the why behind every room. Partners who join are not guessing the vision — they inherit it.',
      whyExists: 'Align collaborators with north star.',
      problemSolved: 'Creative drift on distributed teams.',
      emotionalResponse: 'Invitation to build legacy.',
      designPhilosophy: 'Transparency as luxury.',
      customerJourney: 'Internal — partner onboarding.',
      futureExpansion: 'Investor data room integrations.',
    }),
  },
  {
    id: 'tv-lounge',
    sectionLabel: 'TV LOUNGE',
    title: 'Cinema Suite',
    route: '/desktop/gallery?zone=lounge',
    durationMs: SLOW,
    transition: 'elevator',
    useElevator: true,
    hotspots: [{ id: 'lounge', label: '✨ Lounge TV', x: 0.48, y: 0.42 }],
    presenter: notes({
      voiceover:
        'TV Lounge — Lounge TV, editorial content, the brand as media company. Sit in velvet darkness and watch the universe expand episode by episode.',
      whyExists: 'Retention through entertainment.',
      problemSolved: 'One-and-done transactions.',
      emotionalResponse: 'Membership in a culture.',
      designPhilosophy: 'Salon as streaming destination.',
      customerJourney: 'Watch → learn → shop integrated CTAs.',
      futureExpansion: 'Live premieres & member-only drops.',
    }),
  },
  {
    id: 'members-lounge',
    sectionLabel: 'MEMBERS',
    title: 'Members Lounge',
    route: '/desktop/lobby?zone=members-lounge',
    durationMs: DWELL,
    transition: 'elevator',
    useElevator: true,
    hotspots: [{ id: 'members', label: '✨ Members', x: 0.35, y: 0.5 }],
    presenter: notes({
      voiceover:
        'Members Lounge — premium tiers, BLACK membership, rewards that feel like keys to private rooms. Loyalty is architecture, not points spam.',
      whyExists: 'Recurring revenue & retention.',
      problemSolved: 'Discount-only loyalty cheapens luxury.',
      emotionalResponse: 'Exclusivity earned.',
      designPhilosophy: 'Membership as mansion access pass.',
      customerJourney: 'Upgrade → unlock rooms & perks.',
      futureExpansion: 'Physical member events.',
    }),
  },
  {
    id: 'rewards',
    sectionLabel: 'REWARDS',
    title: 'Rewards Gallery',
    route: '/account/rewards',
    durationMs: DWELL,
    transition: 'fade',
    hotspots: [{ id: 'rewards', label: '✨ Rewards', x: 0.6, y: 0.4 }],
    presenter: notes({
      voiceover:
        'Rewards Gallery — vouchers, milestones, slay tickets. Gamification with grace — every badge feels collectible, not childish.',
      whyExists: 'Behavior reinforcement.',
      problemSolved: 'Low repeat purchase rate.',
      emotionalResponse: 'Achievement, delight.',
      designPhilosophy: 'Luxury loyalty visual language.',
      customerJourney: 'Earn → redeem → celebrate.',
      futureExpansion: 'Partner brand cross-rewards.',
    }),
  },
  {
    id: 'interactive',
    sectionLabel: 'INTERACTION',
    title: 'Effortless Motion',
    route: '/desktop/lobby?zone=grand-lobby',
    durationMs: SLOW,
    transition: 'bloom',
    cinematicDrift: true,
    presenter: notes({
      voiceover:
        'Watch the details — drawers that breathe, panels that float, routing that feels like walking not clicking. This is the standard future creatives will extend.',
      whyExists: 'Prove interaction quality to partners.',
      problemSolved: 'Static comps misrepresent the product.',
      emotionalResponse: 'Desire to touch the UI.',
      designPhilosophy: 'Motion design as brand equity.',
      customerJourney: 'N/A — demonstration beat.',
      futureExpansion: 'Haptic & spatial interfaces.',
    }),
  },
  {
    id: 'mobile-intro',
    sectionLabel: 'MOBILE',
    title: 'Pocket Mansion',
    route: '/mobile/home',
    durationMs: SLOW,
    transition: 'mobile-reveal',
    presenter: notes({
      voiceover:
        'The mansion travels. Mobile is not a responsive afterthought — it is the same universe in your pocket. Beautiful transitions, thumb-native navigation, every room reimagined for intimacy.',
      whyExists: 'Majority traffic on mobile.',
      problemSolved: 'Desktop-only luxury visions fail in market.',
      emotionalResponse: 'Continuity — same brand, anywhere.',
      designPhilosophy: 'Native app quality in web.',
      customerJourney: 'Parallel paths to desktop rooms.',
      futureExpansion: 'iOS/Android shells wrapping web core.',
    }),
  },
  {
    id: 'mobile-showroom',
    sectionLabel: 'MOBILE SHOP',
    title: 'Mobile Showroom',
    route: '/mobile/showroom',
    durationMs: DWELL,
    transition: 'fade',
    presenter: notes({
      voiceover: 'Mobile showroom — swipe through signature units with the same photography standards as desktop penthouse.',
      whyExists: 'Commerce on the go.',
      problemSolved: 'Cramped mobile product grids.',
      emotionalResponse: 'Quick confidence purchase.',
      designPhilosophy: 'Thumb-zone luxury.',
      customerJourney: 'Browse → BAW → checkout.',
      futureExpansion: 'Apple Pay express lanes.',
    }),
  },
  {
    id: 'mobile-baw',
    sectionLabel: 'MOBILE BAW',
    title: 'Mobile Atelier',
    route: '/mobile/build-a-wig',
    durationMs: DWELL,
    transition: 'fade',
    presenter: notes({
      voiceover: 'Build-A-Wig on mobile — same ritual, tighter frames. Configure from anywhere without losing the atelier feeling.',
      whyExists: 'Complete mobile parity.',
      problemSolved: 'Desktop-only customization.',
      emotionalResponse: 'Empowerment on the go.',
      designPhilosophy: 'One engine, two presentations.',
      customerJourney: 'Social share → return to complete.',
      futureExpansion: 'Camera-based length estimation.',
    }),
  },
  {
    id: 'mobile-concierge',
    sectionLabel: 'MOBILE CONCIERGE',
    title: 'Concierge In Your Hand',
    route: '/mobile/concierge',
    durationMs: DWELL,
    transition: 'fade',
    presenter: notes({
      voiceover: 'Concierge, account, memberships — service layers always one tap away, never buried in hamburger menus.',
      whyExists: 'Support & retention touchpoints.',
      problemSolved: 'Hidden account features.',
      emotionalResponse: 'Always cared for.',
      designPhilosophy: 'Service as primary nav item.',
      customerJourney: 'Help → resolve → return to joy.',
      futureExpansion: 'Push concierge for appointment reminders.',
    }),
  },
  {
    id: 'closing-home',
    sectionLabel: 'HOMEPAGE',
    title: 'Return to Threshold',
    route: '/home/shop',
    durationMs: SLOW,
    transition: 'fade',
    cinematicDrift: true,
    presenter: notes({
      voiceover:
        'We return to where we began — but you have seen what lives beneath the homepage. The mansion is real. The rooms have names. The future is expansion, not invention.',
      whyExists: 'Bookend the narrative.',
      problemSolved: 'Presentations that end abruptly.',
      emotionalResponse: 'Completion, invitation.',
      designPhilosophy: 'Circular storytelling.',
      customerJourney: 'Tour complete → free explore or partner briefing.',
      futureExpansion: 'Personalized tour paths by audience.',
    }),
  },
  {
    id: 'ending',
    sectionLabel: 'FINALE',
    title: 'Luxury Without Limits',
    durationMs: VISION_OPENING_MS,
    transition: 'fade',
    presenter: notes({
      voiceover:
        'Frontal Slayer. Luxury without limits. You did not tour a website today — you walked the future flagship of immersive beauty. The door is open. Come build this world with us.',
      whyExists: 'Memorable close for recordings.',
      problemSolved: 'Weak CTAs after demos.',
      emotionalResponse: 'Inspiration → action.',
      designPhilosophy: 'Brand mantra as final frame.',
      customerJourney: 'Partner outreach, hiring, investment.',
      futureExpansion: 'Localized taglines.',
    }),
  },
];

export const FRONTAL_SLAYER_VISION_STOPS: VisionStop[] = RAW_FRONTAL_SLAYER_VISION_STOPS.map((stop) => ({
  ...stop,
  chapterId: chapterIdFromSection(stop.sectionLabel),
}));

export function getVisionStopById(id: string): VisionStop | undefined {
  return FRONTAL_SLAYER_VISION_STOPS.find((s) => s.id === id);
}

export function getVisionStopIndex(id: string): number {
  return FRONTAL_SLAYER_VISION_STOPS.findIndex((s) => s.id === id);
}
