import type { ImplementationStandard } from './types';

/** Engineering patterns — Layer 4; evolve continuously; subordinate to all governance layers above. */
export const IMPLEMENTATION_STANDARDS: ImplementationStandard[] = [
  {
    id: 'world-graph-compile-gate',
    title: 'World Graph Compile Gate™',
    summary: 'prebuild runs compile-world-graph; build fails on dangling edges and validation errors.',
    docPaths: ['docs/studio-os/world-graph/STUDIO_WORLD_GRAPH_ARCHITECTURE.md'],
    codePaths: ['scripts/compile-world-graph-runner.ts', 'src/studio-os-core/world-graph/validator.ts'],
    implementsLaws: ['world-memory', 'no-orphan-objects', 'relationship-gravity'],
  },
  {
    id: 'w-id-registry',
    title: 'W-ID Registry™',
    summary: 'Stable World Graph IDs via worldNodeId(); prefixes per node type; no identity churn.',
    docPaths: ['knowledge/schema/node-types.yaml'],
    codePaths: ['src/studio-os-core/world-graph/id.ts'],
    implementsLaws: ['identity-persistence', 'world-memory'],
  },
  {
    id: 'route-registry-pattern',
    title: 'Route Registry Pattern™',
    summary: 'Every admin studio route registers room + flagship + located-in edge in World Graph.',
    docPaths: ['docs/studio-os/studio-world-responsibility-framework.md'],
    codePaths: ['src/studio-os-core/studio-world/route-registry.ts'],
    implementsLaws: ['physical-place-law', 'spatial-continuity'],
  },
  {
    id: 'repository-structure',
    title: 'Repository Structure™',
    summary: 'studio-os-core platform logic · workspaces brand impl · knowledge/canon governance · docs/studio-os specs.',
    docPaths: ['motherboard/CODEBASE.md', 'docs/studio-os/architecture.md'],
    codePaths: ['src/studio-os-core/', 'knowledge/canon/'],
    implementsLaws: ['repository-governance', 'documentation-first'],
  },
  {
    id: 'naming-conventions',
    title: 'Naming Conventions™',
    summary: 'Trademark™ product names · W-* graph IDs · flagship slugs · scene-stack.v* prompt versions.',
    docPaths: ['docs/studio-os/canon/STUDIO_WORLD_CANON_HIERARCHY.md'],
    codePaths: ['src/studio-os-core/world-graph/id.ts'],
    implementsLaws: ['identity-persistence'],
  },
  {
    id: 'scene-graph-contract',
    title: 'Scene Graph Contract™',
    summary: 'Master Scene Blueprint™, layer types, assembly law, quality guard, export rules — pinned contracts.',
    docPaths: ['docs/studio-os/scene-stack/quality-preservation-law.md'],
    codePaths: ['src/studio-os-core/scene-stack/'],
    implementsLaws: ['scene-integrity', 'blueprint-determinism', 'scene-assembly-rules'],
  },
  {
    id: 'scene-stack-prompt-version',
    title: 'Scene Stack Prompt Version™',
    summary: 'Pinned prompt versions (scene-stack.v2) for Blueprint Determinism and reproducible assembly.',
    docPaths: ['docs/studio-os/scene-stack/quality-preservation-law.md'],
    codePaths: ['src/studio-os-core/scene-stack/prompt-compiler.ts'],
    implementsLaws: ['blueprint-determinism', 'scene-integrity'],
  },
  {
    id: 'generation-api-contract',
    title: 'Generation API Contract™',
    summary: 'FAL reference enforcement, single shell ref max, forbidden cumulative layer inputs.',
    docPaths: ['docs/studio-os/scene-stack/quality-preservation-law.md'],
    codePaths: ['api/_lib/sceneStackReferenceEnforcement.ts', 'api/_lib/studioBuilderGeneration.ts'],
    implementsLaws: ['scene-integrity', 'asset-conservation'],
  },
  {
    id: 'era-evaluation-gate',
    title: 'Era Evaluation Gate™',
    summary: 'Major implementations evaluated against Three Eras Roadmap before shipping.',
    docPaths: ['docs/studio-os/world-graph/STUDIO_WORLD_THREE_ERAS_ROADMAP.md'],
    codePaths: ['src/studio-os-core/world-graph/era-evaluation.ts'],
    implementsLaws: ['world-memory', 'temporal-continuity'],
  },
  {
    id: 'design-review-filter',
    title: 'Design Review Filter™',
    summary: 'Six-step flagship review: Principles → Physics → Constitution → Standards → Technical → Experience.',
    docPaths: ['docs/studio-os/governance/STUDIO_WORLD_GOVERNANCE_HIERARCHY.md'],
    codePaths: ['src/studio-os-core/design-principles/design-review.ts'],
    implementsLaws: ['knowledge-review', 'approval-workflow'],
  },
  {
    id: 'motherboard-sync-contract',
    title: 'Motherboard Sync Contract™',
    summary: 'Agent memory appends to MEMORY.md; graph ingestion is canon. One deploy per task.',
    docPaths: ['motherboard/ADDING.md', '.cursor/rules/one-deploy-per-task.mdc'],
    codePaths: ['motherboard/MEMORY.md'],
    implementsLaws: ['agent-memory-subordination', 'world-memory'],
  },
  {
    id: 'one-deploy-per-task',
    title: 'One Deploy Per Task™',
    summary: 'Each completed task = one commit + one push; MEMORY folded into same commit.',
    docPaths: ['.cursor/rules/one-deploy-per-task.mdc'],
    codePaths: ['scripts/agent-commit.sh'],
    implementsLaws: ['knowledge-conservation', 'repository-governance'],
  },
  {
    id: 'ci-validation-gate',
    title: 'CI Validation Gate™',
    summary: 'tsc --noEmit + world graph compile + master spec reconciliation in prebuild.',
    docPaths: ['package.json'],
    codePaths: ['scripts/compile-master-spec.mjs'],
    implementsLaws: ['documentation-first', 'world-memory'],
  },
  {
    id: 'migration-strategy',
    title: 'Migration Strategy™',
    summary: 'Legacy paths preserved in route-registry; migration-audit tracks immersive status; no silent breaks.',
    docPaths: ['src/studio-os-core/studio-world/migration-audit.ts'],
    codePaths: ['src/studio-os-core/studio-world/migration-audit.ts'],
    implementsLaws: ['temporal-continuity', 'spatial-continuity'],
  },
];
