/** About Us body copy for `/brand/about` — displayed in uppercase on the page. */
export const BRAND_ABOUT_US_PARAGRAPHS = [
  "WELCOME & THANK YOU FOR CHOOSING TO SHOP WITH US. OUR GOAL IS TO GIVE YOU MORE THAN JUST HAIR. WE'RE HERE TO DELIVER A FULL VIRTUAL EXPERIENCE WITH A TOUCH OF NOSTALGIA, A LITTLE BIT OF FUN, AND A WHOLE LOT OF SLAY.",
  'WE CREATED THIS SPACE TO BRING THE SALON DIRECTLY TO YOU IN A LUXE YET BEGINNER-FRIENDLY WAY WHILE MAKING THE ENTIRE PROCESS SEAMLESS, CONVENIENT, AND ACTUALLY ENJOYABLE. WHETHER YOU\'RE A FIRST TIME WIG WEARER OR A CERTIFIED FRONTAL ASSASSIN, WE BELIEVE PREMIUM HAIR SHOULD FEEL EFFORTLESS.',
  'WITH OVER 10 YEARS OF EXPERIENCE IN CUSTOM INSTALLS, COLORING, STYLING, AND ETHICALLY SOURCING QUALITY RAW HAIR THAT ACTUALLY LASTS, OUR CEO BUILT FRONTAL SLAYER WITH ONE MISSION IN MIND: HELPING CLIENTS LOOK EXPENSIVE WITHOUT THE CONFUSION, GATEKEEPING, OR SALON ANXIETY.',
  "BECAUSE FRONTAL SLAYER ISN'T JUST A NAME… IT'S A MINDSET.",
  "WE'RE HERE TO HELP YOU SURVIVE THE TRIALS AND TRIBULATIONS OF DOING YOUR OWN HAIR THROUGH EDUCATIONAL GUIDES, TIPS + TRICKS, STEP-BY-STEP TUTORIALS, AND INSTRUCTIONAL VIDEOS DESIGNED TO PUT THE POWER BACK IN YOUR HANDS. OUR GOAL IS SIMPLE: TO HELP YOU SLAY YOUR OWN HAIR WITH CONFIDENCE, CONVENIENCE, AND ZERO INTIMIDATION SO YOU TOO CAN SLAY YOUR OWN FRONTALS & HAIR ONE DAY.",
  'LUXURY HAIR. REAL EDUCATION. NO GATEKEEPING. JUST PRESSURE.',
] as const;
