/** About Us body copy for `/brand/about` — displayed in uppercase on the page. */
export const BRAND_ABOUT_US_PARAGRAPHS = [
  "WELCOME & THANK YOU FOR CHOOSING TO SHOP WITH US. OUR GOAL IS TO GIVE YOU MORE THAN JUST HAIR. WE'RE HERE TO DELIVER A FULL VIRTUAL EXPERIENCE WITH A TOUCH OF NOSTALGIA, A LITTLE BIT OF FUN, AND A WHOLE LOT OF SLAY.",
  'WE CREATED THIS SPACE TO BRING THE SALON DIRECTLY TO YOU IN A LUXE YET BEGINNER-FRIENDLY WAY WHILE MAKING THE ENTIRE PROCESS SEAMLESS, CONVENIENT, AND ACTUALLY ENJOYABLE. WHETHER YOU\'RE A FIRST TIME WIG WEARER OR A CERTIFIED FRONTAL ASSASSIN, WE BELIEVE PREMIUM HAIR SHOULD FEEL EFFORTLESS.',
  'WITH OVER 10 YEARS OF EXPERIENCE IN CUSTOM INSTALLS, COLORING, STYLING, AND ETHICALLY SOURCING QUALITY RAW HAIR THAT ACTUALLY LASTS, OUR CEO BUILT FRONTAL SLAYER WITH ONE MISSION IN MIND: HELPING CLIENTS LOOK EXPENSIVE WITHOUT THE CONFUSION, GATEKEEPING, OR SALON ANXIETY.',
  "BECAUSE FRONTAL SLAYER ISN'T JUST A NAME… IT'S A MINDSET.",
  "WE'RE HERE TO HELP YOU SURVIVE THE TRIALS AND TRIBULATIONS OF DOING YOUR OWN HAIR THROUGH EDUCATIONAL GUIDES, TIPS + TRICKS, STEP-BY-STEP TUTORIALS, AND INSTRUCTIONAL VIDEOS DESIGNED TO PUT THE POWER BACK IN YOUR HANDS. OUR GOAL IS SIMPLE: TO HELP YOU SLAY YOUR OWN HAIR WITH CONFIDENCE, CONVENIENCE, AND ZERO INTIMIDATION SO YOU TOO CAN SLAY YOUR OWN FRONTALS & HAIR ONE DAY.",
  'WHAT TRULY SEPARATES FRONTAL SLAYER FROM THE AVERAGE HAIR BRAND IS THE EXPERIENCE. FROM FULLY CUSTOMIZABLE UNITS INCLUDING COLOR SERVICES & TAILORED STYLING REQUESTS VIA OUR INTERACTIVE SHOPPING EXPERIENCE. EVERY DETAIL IS DESIGNED WITH YOU IN MIND. WE UNDERSTAND THAT LUXURY ISN\'T ONE SIZE FITS ALL. YOUR HAIR SHOULD FEEL PERSONAL.',
  "BEYOND THE HAIR ITSELF, WE'VE CREATED A COMMUNITY DRIVEN PLATFORM PACKED WITH EXCLUSIVE MEMBERSHIP SUBSCRIPTIONS, LOYALTY REWARDS, REFERRAL PERKS, VIP DISCOUNTS, GIVEAWAYS, EARLY ACCESS TO NEW DROPS AND CLIENT CENTERED INCENTIVES THAT REWARD YOU SIMPLY FOR BEING A PART OF THE SLAY COMMUNITY. THINK CONCIERGE LEVEL SERVICE WITH MAIN CHARACTER ENERGY.",
  'WHETHER YOU NEED GUIDANCE CHOOSING THE PERFECT UNIT USING OUR COMPLIMENTARY CONSULTATION SERVICES, NEED HELP MASTERING YOUR INSTALL SKILLS, OR JUST WANT PREMIUM HAIR THAT STANDS THE TEST OF TIME, FRONTAL SLAYER IS HERE TO MAKE THE PROCESS FEEL ELEVATED, EDUCATIONAL, AND EFFORTLESS FROM START TO FINISH.',
  'LUXURY HAIR. REAL EDUCATION. NO GATEKEEPING. JUST PRESSURE.',
] as const;

/** Red accent lines on About Us — Futura PT Medium. */
export const BRAND_ABOUT_ACCENT_PARAGRAPHS: ReadonlySet<string> = new Set([
  "BECAUSE FRONTAL SLAYER ISN'T JUST A NAME… IT'S A MINDSET.",
  'LUXURY HAIR. REAL EDUCATION. NO GATEKEEPING. JUST PRESSURE.',
]);
