/** Contact Us intro copy for `/brand/contact` — displayed in uppercase on the page. */
export const BRAND_CONTACT_INTRO_PARAGRAPHS = [
  'QUESTIONS, COMMENTS OR CONCERNS? FILL OUT THE FORM BELOW OR SEND US AN EMAIL AT CONTACT@FRONTALSLAYER.COM',
  'PLEASE ALLOW AT LEAST 72 HOURS TO RECEIVE A RESPONSE FOR ALL INQUIRIES. BUSINESS OPERATIONAL BETWEEN THE HOURS OF 10AM - 6PM CST DURING WEEKDAYS ONLY.',
] as const;
