/** Terms of Service body for `/brand/terms` — displayed in uppercase on the page. */
export type BrandTermsSection = {
  id: string;
  title: string;
  paragraphs: string[];
  /** Optional bullet lines rendered after paragraphs. */
  bullets?: string[];
};


/** Inline-rendered in BrandTermsBody with link to /brand/contact */
export const BRAND_TERMS_CONTACT_FORM_LINK_SENTINEL = '__BRAND_TERMS_CONTACT_FORM_LINK__';

export const BRAND_TERMS_CONTACT_FORM_LINE_PREFIX = 'OR USE THE CONTACT FORM LOCATED ';

export const BRAND_TERMS_CONTACT_FORM_LINK_LABEL = 'HERE';

export const BRAND_TERMS_BUSINESS_HOURS_SENTINEL = '__BRAND_TERMS_BUSINESS_HOURS__';

export const BRAND_TERMS_BUSINESS_HOURS_HTML =
  'BUSINESS OPERATIONAL HOURS: 10AM–6PM CST ON WEEKDAYS.<br>MAJOR U.S. HOLIDAYS EXCLUDED.';

export const BRAND_TERMS_INTRO_PARAGRAPHS: string[] = [
  'BY ACCESSING THIS WEBSITE AND/OR PLACING AN ORDER WITH FRONTAL SLAYER, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD AND AGREED TO ALL TERMS, CONDITIONS, POLICIES AND NOTICES STATED BELOW. BY SUBMITTING PAYMENT, YOU AGREE TO COMPLY WITH THESE TERMS OF SERVICE IN FULL.',
  'FRONTAL SLAYER RESERVES THE RIGHT TO UPDATE, MODIFY OR CHANGE THESE TERMS AT ANY TIME WITHOUT PRIOR NOTICE. CONTINUED USE OF THIS WEBSITE CONSTITUTES ACCEPTANCE OF ANY UPDATES MADE.',
];

export const BRAND_TERMS_SECTIONS: BrandTermsSection[] = [
  {
    id: 'order-agreement',
    title: 'ORDER AGREEMENT',
    paragraphs: [
      'BY PLACING AN ORDER WITH FRONTAL SLAYER, YOU CONFIRM THAT:',
      'YOU HAVE CAREFULLY REVIEWED ALL PRODUCT DESCRIPTIONS, CUSTOMIZATION DETAILS, PROCESSING TIMES AND POLICIES PRIOR TO PURCHASE.',
      'YOU UNDERSTAND THAT MANY PRODUCTS ARE HANDMADE, CUSTOMIZED OR MADE-TO-ORDER AND MAY REQUIRE ADDITIONAL PROCESSING TIME BEYOND STANDARD READY-TO-SHIP TIMELINES.',
      'YOU HAVE ENTERED THE CORRECT BILLING AND SHIPPING INFORMATION BEFORE SUBMITTING YOUR ORDER.',
      'FOR APPLICABLE PHYSICAL ORDERS, YOU UNDERSTAND THAT YOU MUST COMPLETE AND SUBMIT YOUR SIGNED ORDER AUTHORIZATION FORM WITHIN 24 HOURS OF PURCHASE OR YOUR ORDER MAY BE CANCELED AND REFUNDED PER OUR CHECKOUT POLICY.',
      'YOU UNDERSTAND THAT ONCE AN ORDER HAS BEEN SUBMITTED AND CONFIRMED, IT CANNOT BE CANCELED, MODIFIED OR EDITED UNDER ANY CIRCUMSTANCES. THIS INCLUDES:',
    ],
    bullets: [
      'SHIPPING ADDRESS CHANGES',
      'PRODUCT CHANGES',
      'CUSTOMIZATION REQUESTS',
      'PAYMENT METHOD ADJUSTMENTS',
    ],
  },
  {
    id: 'order-agreement-close',
    title: '',
    paragraphs: [
      'CUSTOMERS ARE SOLELY RESPONSIBLE FOR ENSURING ALL SUBMITTED INFORMATION IS ACCURATE AT CHECKOUT.',
    ],
  },
  {
    id: 'processing-shipping',
    title: 'PROCESSING + SHIPPING',
    paragraphs: [
      'PROCESSING TIMES ARE SEPARATE FROM SHIPPING TIMES AND VARY BY PRODUCT, CUSTOMIZATION LEVEL, ORDER VOLUME, HOLIDAYS AND AVAILABILITY.',
      'MADE-TO-ORDER CUSTOM UNITS TYPICALLY REQUIRE 6–8 WEEKS OF PROCESSING (UP TO 10 WEEKS FOR EXTENSIVE CUSTOMIZATION). EXPRESS PROCESSING (4–6 WEEKS) IS AVAILABLE ON SELECT UNITS FOR AN ADDITIONAL FEE WHERE OFFERED. OTHER ORDERS MAY PROCESS WITHIN THE TIMELINES STATED ON THE PRODUCT PAGE OR AT CHECKOUT.',
      'EXPEDITED SHIPPING OPTIONS, WHEN AVAILABLE, AFFECT TRANSIT TIME AFTER YOUR ORDER SHIPS — NOT PROCESSING OR CUSTOMIZATION TIME.',
      'ONCE AN ORDER HAS SHIPPED, FRONTAL SLAYER IS NOT RESPONSIBLE FOR:',
    ],
    bullets: [
      'DELAYED DELIVERY CAUSED BY SHIPPING CARRIERS',
      'LOST, STOLEN OR MISPLACED PACKAGES',
      'DAMAGES THAT OCCUR DURING TRANSIT',
      'INCORRECT SHIPPING ADDRESSES SUBMITTED BY THE CUSTOMER',
      'CARRIER DELIVERY ERRORS OR DELIVERY EXCEPTIONS',
    ],
  },
  {
    id: 'processing-shipping-close',
    title: '',
    paragraphs: [
      'CUSTOMERS ASSUME RESPONSIBILITY FOR CONTACTING THE SHIPPING CARRIER REGARDING ANY TRANSIT-RELATED ISSUES ONCE TRACKING INFORMATION HAS BEEN PROVIDED.',
      'IF A PACKAGE IS RETURNED TO SENDER DUE TO AN INCORRECT ADDRESS OR FAILED DELIVERY ATTEMPTS, THE CUSTOMER WILL BE RESPONSIBLE FOR ANY RESHIPPING FEES.',
    ],
  },
  {
    id: 'product-disclaimer',
    title: 'PRODUCT DISCLAIMER',
    paragraphs: [
      'PLEASE UNDERSTAND THAT SLIGHT VARIATIONS MAY OCCUR IN:',
    ],
    bullets: [
      'LACE TINT',
      'HAIR TEXTURE',
      'DENSITY',
      'LENGTH',
      'COLOR',
      'CURL/WAVE PATTERN',
    ],
  },
  {
    id: 'product-disclaimer-close',
    title: '',
    paragraphs: [
      'DUE TO THE RAW AND NATURAL NATURE OF OUR PRODUCTS, NO TWO BUNDLES OR UNITS ARE GUARANTEED TO BE IDENTICAL.',
      'FRONTAL SLAYER DOES NOT GUARANTEE RESULTS FROM BLEACHING, COLORING, CHEMICAL PROCESSING, EXCESSIVE HEAT STYLING, IMPROPER INSTALLATION OR IMPROPER MAINTENANCE PERFORMED AFTER DELIVERY. WE RECOMMEND A LICENSED PROFESSIONAL FOR ANY CHEMICAL SERVICES.',
    ],
  },
  {
    id: 'refund-return',
    title: 'REFUND + RETURN POLICY',
    paragraphs: [
      'ALL SALES ARE FINAL.',
      'DUE TO THE SANITARY NATURE, CUSTOMIZATION AND HIGH DEMAND OF OUR PRODUCTS, FRONTAL SLAYER DOES NOT OFFER REFUNDS, RETURNS OR EXCHANGES UNDER ANY CIRCUMSTANCES UNLESS AN ORDER ISSUE IS DETERMINED TO BE THE DIRECT RESULT OF OUR ERROR.',
      'FRONTAL SLAYER RESERVES THE RIGHT TO REFUSE ALL REFUND REQUESTS, RETURNS, EXCHANGES, CHARGEBACK DISPUTES AND CLAIMS THAT VIOLATE OUR POLICIES.',
      'IF YOU RECEIVE:',
    ],
    bullets: [
      'THE WRONG ITEM',
      'A DEFECTIVE PRODUCT',
      'AN INCOMPLETE ORDER',
    ],
  },
  {
    id: 'refund-return-claim',
    title: '',
    paragraphs: [
      'YOU MUST CONTACT US WITHIN 48 HOURS OF CONFIRMED DELIVERY AT CONTACT@FRONTALSLAYER.COM WITH:',
    ],
    bullets: [
      'YOUR FULL NAME',
      'ORDER NUMBER',
      'CLEAR PHOTOS/VIDEOS OF THE ISSUE',
      'ORIGINAL PACKAGING IF APPLICABLE',
    ],
  },
  {
    id: 'refund-return-close',
    title: '',
    paragraphs: [
      'CLAIMS SUBMITTED OUTSIDE OF THIS TIMEFRAME MAY NOT QUALIFY FOR REVIEW. ALL INQUIRIES SHOULD RECEIVE A RESPONSE WITHIN 72 HOURS.',
      'IF AN ISSUE IS VERIFIED ON OUR END, WE RESERVE THE RIGHT TO:',
    ],
    bullets: [
      'REPLACE THE ITEM',
      'CORRECT THE SHIPMENT',
      'ISSUE STORE CREDIT',
      'OFFER A COMPARABLE REPLACEMENT PRODUCT',
    ],
  },
  {
    id: 'refund-return-credit',
    title: '',
    paragraphs: [
      'STORE CREDIT MAY BE ISSUED AT OUR DISCRETION IF THE ORIGINAL ITEM IS UNAVAILABLE. FRONTAL SLAYER IS NOT LIABLE FOR DAMAGE THAT MAY OCCUR DURING SHIPMENT OR WHILE YOUR PRODUCT IS IN TRANSIT.',
    ],
  },
  {
    id: 'fraud-prevention',
    title: 'FRAUD PREVENTION',
    paragraphs: [
      'FOR SECURITY PURPOSES, FRONTAL SLAYER RESERVES THE RIGHT TO:',
    ],
    bullets: [
      'CANCEL OR REFUSE SUSPICIOUS ORDERS',
      'REQUEST IDENTITY VERIFICATION',
      'REQUIRE ADDITIONAL BILLING VERIFICATION',
      'REFUSE SERVICE TO ANYONE SUSPECTED OF FRAUDULENT ACTIVITY',
    ],
  },
  {
    id: 'fraud-prevention-close',
    title: '',
    paragraphs: [
      'ANY FRAUDULENT CHARGEBACKS OR UNAUTHORIZED PAYMENT DISPUTES WILL BE INVESTIGATED THOROUGHLY AND MAY RESULT IN LEGAL ACTION.',
    ],
  },
  {
    id: 'intellectual-property',
    title: 'INTELLECTUAL PROPERTY',
    paragraphs: [
      'ALL WEBSITE CONTENT INCLUDING BRANDING, LOGOS, GRAPHICS, PRODUCT IMAGES, VIDEOS, TUTORIALS, TEXT AND MARKETING MATERIALS ARE THE INTELLECTUAL PROPERTY OF FRONTAL SLAYER AND MAY NOT BE COPIED, REPRODUCED, DISTRIBUTED OR USED WITHOUT WRITTEN PERMISSION.',
    ],
  },
  {
    id: 'limitation-liability',
    title: 'LIMITATION OF LIABILITY',
    paragraphs: [
      'USE OF OUR PRODUCTS AND WEBSITE IS AT YOUR OWN DISCRETION AND RISK. FRONTAL SLAYER SHALL NOT BE HELD LIABLE FOR ANY INDIRECT, INCIDENTAL, CONSEQUENTIAL OR ACCIDENTAL DAMAGES RESULTING FROM:',
    ],
    bullets: [
      'PRODUCT MISUSE',
      'IMPROPER INSTALLATION',
      'ALLERGIC REACTIONS',
      'SHIPPING DELAYS',
      'THIRD-PARTY CARRIER ISSUES',
      'UNAUTHORIZED PRODUCT ALTERATIONS',
    ],
  },
  {
    id: 'contact',
    title: '',
    paragraphs: [
      'FOR ALL CUSTOMER SERVICE INQUIRIES, PLEASE EMAIL:',
      'CONTACT@FRONTALSLAYER.COM',
      BRAND_TERMS_CONTACT_FORM_LINK_SENTINEL,
      'PLEASE ALLOW AT LEAST 72 HOURS TO RECEIVE A RESPONSE FOR ALL INQUIRIES RESPONSE TIMES ARE TYPICALLY WITHIN 72 BUSINESS HOURS. RESPONSE TIMES MAY INCREASE DURING HOLIDAYS, SALES, LAUNCHES AND HIGH VOLUME PERIODS.',
      BRAND_TERMS_BUSINESS_HOURS_SENTINEL,
    ],
  },
];
