/** FAQ sections for `/brand/faq` — displayed in uppercase on the page. */
export type BrandFaqItem = {
  id: string;
  question: string;
  /** One or more paragraphs (rendered in order). */
  answerParagraphs: string[];
};

export type BrandFaqSection = {
  id: string;
  title: string;
  items: BrandFaqItem[];
};

const BRAND_FAQ_SECTIONS_LIST: BrandFaqSection[] = [
  {
    id: 'ordering-processing',
    title: 'ORDERING + PROCESSING',
    items: [
      {
        id: 'processing-time',
        question: 'HOW LONG DOES PROCESSING TAKE?',
        answerParagraphs: [
          'PROCESSING TIMES VARY BY PRODUCT AND CUSTOMIZATION LEVEL. READY-TO-SHIP OR STANDARD ORDERS OFTEN PROCESS WITHIN 3–10 BUSINESS DAYS DEPENDING ON ORDER VOLUME AND SERVICE REQUESTS.',
          'MADE-TO-ORDER CUSTOM UNITS TYPICALLY REQUIRE 6–8 WEEKS OF PROCESSING (UP TO 10 WEEKS FOR EXTENSIVE CUSTOMIZATION). EXPRESS PROCESSING (4–6 WEEKS) IS AVAILABLE ON SELECT UNITS FOR AN ADDITIONAL FEE. SPECIALTY COLOR, PLUCKING, AND OTHER UPGRADES MAY ADD TIME SO QUALITY STANDARDS ARE MET.',
        ],
      },
      {
        id: 'expedited-shipping',
        question: 'DO YOU OFFER EXPEDITED SHIPPING?',
        answerParagraphs: [
          'YES. EXPEDITED SHIPPING OPTIONS ARE AVAILABLE AT CHECKOUT. PLEASE NOTE THAT SHIPPING SPEED DOES NOT REDUCE PROCESSING OR CUSTOMIZATION TIME — IT ONLY AFFECTS TRANSIT TIME AFTER YOUR ORDER SHIPS.',
        ],
      },
      {
        id: 'change-cancel-order',
        question: 'CAN I CHANGE OR CANCEL MY ORDER AFTER PLACING IT?',
        answerParagraphs: [
          'BECAUSE MANY OF OUR PRODUCTS ARE CUSTOMIZED AND PREPARED SPECIFICALLY FOR EACH CLIENT, ORDERS CANNOT BE CHANGED OR CANCELED ONCE SUBMITTED AND CONFIRMED — INCLUDING ITEM OR SHIPPING ADDRESS CHANGES. PLEASE DOUBLE-CHECK ALL ORDER DETAILS BEFORE SUBMITTING PAYMENT.',
          'FOR QUALIFYING PHYSICAL ORDERS, YOU MUST ALSO COMPLETE AND SIGN YOUR ORDER AUTHORIZATION FORM WITHIN 24 HOURS OF PURCHASE OR YOUR ORDER MAY BE CANCELED AND REFUNDED PER OUR CHECKOUT POLICY.',
        ],
      },
      {
        id: 'order-authorization-form',
        question: 'DO I NEED TO COMPLETE AN ORDER AUTHORIZATION FORM?',
        answerParagraphs: [
          'YES, FOR APPLICABLE ORDERS. AFTER CHECKOUT YOU MUST COMPLETE AND SUBMIT YOUR SIGNED ORDER AUTHORIZATION FORM WITHIN 24 HOURS OF PURCHASE. IF THE FORM IS NOT COMPLETED IN TIME, YOUR ORDER MAY BE REFUNDED AND CANCELED. TRACK YOUR ORDER STATUS FROM YOUR ACCOUNT ORDERS PAGE.',
        ],
      },
      {
        id: 'payment-plans',
        question: 'DO YOU OFFER PAYMENT PLANS?',
        answerParagraphs: [
          'YES. WE OFFER INSTALLMENT PAYMENT OPTIONS AT CHECKOUT THROUGH SELECT PROVIDERS (INCLUDING AFFIRM AND KLARNA, WHERE AVAILABLE) SO YOU CAN SLAY NOW AND SPLIT PAYMENTS OVER TIME.',
        ],
      },
      {
        id: 'tracking',
        question: 'WILL I RECEIVE TRACKING INFORMATION?',
        answerParagraphs: [
          'ABSOLUTELY. ONCE YOUR ORDER SHIPS, TRACKING INFORMATION WILL BE SENT TO THE EMAIL ADDRESS ASSOCIATED WITH YOUR ORDER. YOU CAN ALSO VIEW ORDER STATUS AND TRACKING FROM YOUR ACCOUNT ORDERS PAGE WHEN SIGNED IN.',
        ],
      },
    ],
  },
  {
    id: 'hair-quality',
    title: 'HAIR QUALITY + MAINTENANCE',
    items: [
      {
        id: 'hair-type',
        question: 'WHAT TYPE OF HAIR DO YOU SELL?',
        answerParagraphs: [
          'WE SPECIALIZE IN PREMIUM-QUALITY RAW AND LUXURY VIRGIN HAIR EXTENSIONS AND UNITS SOURCED FOR LONGEVITY, SOFTNESS, VERSATILITY, AND MINIMAL SHEDDING WHEN PROPERLY MAINTAINED.',
        ],
      },
      {
        id: 'hair-longevity',
        question: 'HOW LONG DOES THE HAIR LAST?',
        answerParagraphs: [
          'WITH PROPER CARE AND MAINTENANCE, OUR HAIR CAN LAST ANYWHERE FROM 1–3+ YEARS DEPENDING ON HOW FREQUENTLY IT IS WORN, COLORED, HEAT-STYLED, AND MAINTAINED.',
        ],
      },
      {
        id: 'color-bleach',
        question: 'CAN THE HAIR BE COLORED OR BLEACHED?',
        answerParagraphs: [
          'YES. OUR HAIR CAN BE PROFESSIONALLY COLORED, TONED, LIFTED, AND STYLED. WE STRONGLY RECOMMEND USING A LICENSED PROFESSIONAL FOR ANY CHEMICAL SERVICES TO PRESERVE THE INTEGRITY OF THE HAIR.',
        ],
      },
      {
        id: 'shed-tangle',
        question: 'DOES THE HAIR SHED OR TANGLE?',
        answerParagraphs: [
          'MINIMAL SHEDDING IS NORMAL WITH ANY EXTENSIONS OR WIGS, ESPECIALLY AFTER CUSTOMIZATION. PROPER MAINTENANCE, BRUSHING TECHNIQUES, AND NIGHTTIME CARE HELP REDUCE TANGLING AND EXTEND THE LIFE OF YOUR HAIR.',
        ],
      },
      {
        id: 'bundle-count',
        question: 'HOW MANY BUNDLES DO I NEED FOR A FULL INSTALL?',
        answerParagraphs: [
          'THIS DEPENDS ON YOUR DESIRED FULLNESS AND LENGTH. TYPICALLY:',
          '12"–18" = 2–3 BUNDLES',
          '20"–26" = 3–4 BUNDLES',
          '28"+ = 4 OR MORE BUNDLES RECOMMENDED',
        ],
      },
    ],
  },
  {
    id: 'wigs-customization',
    title: 'WIGS + CUSTOMIZATION',
    items: [
      {
        id: 'beginner-friendly',
        question: 'ARE YOUR WIGS BEGINNER FRIENDLY?',
        answerParagraphs: [
          'YES. MANY OF OUR UNITS ARE DESIGNED WITH BEGINNER-FRIENDLY CUSTOMIZATION OPTIONS TO MAKE INSTALLATION EASIER AND MORE CONVENIENT FOR EVERYDAY WEAR.',
        ],
      },
      {
        id: 'pre-plucked',
        question: 'DO YOUR WIGS COME PRE-PLUCKED OR CUSTOMIZED?',
        answerParagraphs: [
          'CUSTOMIZATION OPTIONS VARY BY UNIT. WE OFFER SERVICES SUCH AS PRE-PLUCKING, BLEACHING KNOTS, STYLING, COLORING, LAYERING, AND OTHER UPGRADES DEPENDING ON YOUR SELECTION AT CHECKOUT OR THROUGH OUR BUILD-A-WIG FLOW.',
        ],
      },
      {
        id: 'custom-color-style',
        question: 'CAN I REQUEST A CUSTOM COLOR OR STYLE?',
        answerParagraphs: [
          'ABSOLUTELY. WE OFFER VARIOUS CUSTOMIZATION SERVICES TO PERSONALIZE YOUR UNIT. AVAILABILITY MAY VARY BASED ON THE COMPLEXITY OF THE REQUEST AND CURRENT PRODUCTION VOLUME.',
        ],
      },
      {
        id: 'cap-size',
        question: 'HOW DO I CHOOSE THE CORRECT WIG CAP SIZE?',
        answerParagraphs: [
          'WE RECOMMEND MEASURING YOUR HEAD CIRCUMFERENCE BEFORE ORDERING. USE OUR BUILD-A-WIG CAP SIZE STEP OR THE CAP SIZE OPTIONS ON THE PRODUCT PAGE TO SELECT THE BEST FIT. WHEN IN DOUBT, CONTACT US BEFORE PURCHASING.',
        ],
      },
      {
        id: 'build-a-wig',
        question: 'WHAT IS BUILD-A-WIG?',
        answerParagraphs: [
          'BUILD-A-WIG IS OUR STEP-BY-STEP CUSTOMIZATION FLOW WHERE YOU SELECT LENGTH, TEXTURE, COLOR, DENSITY, LACE, CAP SIZE, STYLING, AND ADD-ONS TO CREATE A MADE-TO-ORDER UNIT TAILORED TO YOUR PREFERENCES.',
        ],
      },
    ],
  },
  {
    id: 'returns-policies',
    title: 'RETURNS + POLICIES',
    items: [
      {
        id: 'returns-exchanges',
        question: 'DO YOU ACCEPT RETURNS OR EXCHANGES?',
        answerParagraphs: [
          'DUE TO THE BESPOKE NATURE OF OUR PRODUCTS AND HYGIENE STANDARDS, ALL SALES ARE FINAL. WE ARE UNABLE TO OFFER REFUNDS, RETURNS, OR EXCHANGES. FRONTAL SLAYER RESERVES THE RIGHT TO REFUSE ALL REFUNDS, RETURNS, AND EXCHANGES.',
          'IF THERE IS AN ISSUE WITH YOUR ORDER, PLEASE CONTACT US PROMPTLY. FULL TERMS ARE AVAILABLE ON OUR TERMS OF SERVICE PAGE.',
        ],
      },
      {
        id: 'wrong-item',
        question: 'WHAT IF I RECEIVE THE WRONG ITEM?',
        answerParagraphs: [
          'IF YOU RECEIVE THE WRONG ITEM, CONTACT CUSTOMER SUPPORT WITHIN 48 HOURS OF DELIVERY WITH CLEAR PHOTOS AND YOUR ORDER NUMBER SO WE CAN ASSIST YOU PROMPTLY.',
          'WE WILL INVESTIGATE ALL CONCERNS THOROUGHLY AND, WHEN APPROPRIATE, CORRECT YOUR SHIPMENT OR ISSUE STORE CREDIT IF THE ITEM IS NO LONGER IN STOCK.',
        ],
      },
      {
        id: 'order-issue',
        question: "WHAT IF THERE'S AN ISSUE WITH MY ORDER?",
        answerParagraphs: [
          'IF YOUR ORDER ARRIVES DEFECTIVE OR DAMAGED, CONTACT CUSTOMER SUPPORT WITHIN 48 HOURS OF DELIVERY WITH CLEAR PHOTOS AND YOUR ORDER NUMBER SO WE CAN ASSIST YOU PROMPTLY.',
          'FRONTAL SLAYER IS NOT LIABLE FOR DAMAGE THAT MAY OCCUR DURING SHIPMENT OR WHILE YOUR PRODUCT IS IN TRANSIT.',
        ],
      },
      {
        id: 'terms-link',
        question: 'WHERE CAN I READ THE FULL TERMS OF SERVICE?',
        answerParagraphs: [
          'VISIT THE TERMS OF SERVICE PAGE UNDER BRAND IN THE SITE MENU, OR GO TO /BRAND/TERMS FOR COMPLETE TERMS, REFUND POLICY, AND PURCHASE CONDITIONS.',
        ],
      },
    ],
  },
  {
    id: 'membership-rewards',
    title: 'MEMBERSHIP + REWARDS',
    items: [
      {
        id: 'loyalty',
        question: 'HOW DOES THE LOYALTY REWARDS PROGRAM WORK?',
        answerParagraphs: [
          'YOU CAN EARN LOYALTY POINTS THROUGH PURCHASES, PRODUCT REVIEWS, REFERRALS, SOCIAL MEDIA ENGAGEMENT, AND OTHER PROMOTIONAL ACTIVITIES. POINTS CAN BE REDEEMED TOWARD DISCOUNTS, PERKS, FREE GIFTS, AND SAVINGS ON FUTURE ORDERS.',
        ],
      },
      {
        id: 'referral',
        question: 'HOW DOES THE REFERRAL PROGRAM WORK?',
        answerParagraphs: [
          'MEMBERS RECEIVE A PERSONALIZED REFERRAL CODE TO SHARE AFTER COMPLETING THEIR FIRST PURCHASE. WHEN SOMEONE USES YOUR CODE ON THEIR FIRST PURCHASE, THEY RECEIVE AN ADDITIONAL $20 OFF AND YOU EARN DIGITAL CASH DEPOSITED INTO YOUR ACCOUNT ONCE THEIR ORDER IS CONFIRMED.',
        ],
      },
      {
        id: 'member-perks',
        question: 'DO YOU OFFER EXCLUSIVE PERKS FOR MEMBERS?',
        answerParagraphs: [
          'YES. MEMBERS RECEIVE ACCESS TO EARLY DROPS, GIVEAWAYS, PROMOTIONAL OFFERS, LOYALTY REWARDS, EXCLUSIVE DISCOUNTS, AND OTHER VIP COMMUNITY PERKS. NEW MEMBERS WHO SUBSCRIBE TO OUR NEWSLETTER ALSO RECEIVE $10 DIGITAL CASH IN THEIR ACCOUNT.',
        ],
      },
      {
        id: 'create-account',
        question: 'DO I NEED AN ACCOUNT TO SHOP?',
        answerParagraphs: [
          'YOU CAN BROWSE WITHOUT AN ACCOUNT, BUT CREATING ONE UNLOCKS ORDER TRACKING, WISHLIST, LOYALTY REWARDS, REFERRALS, AND MEMBER-ONLY UPDATES. VISIT BECOME A MEMBER UNDER BRAND TO LEARN MORE.',
        ],
      },
    ],
  },
  {
    id: 'general',
    title: 'GENERAL',
    items: [
      {
        id: 'contact-support',
        question: 'HOW CAN I CONTACT CUSTOMER SUPPORT?',
        answerParagraphs: [
          'REACH OUR TEAM THROUGH THE CONTACT FORM ON OUR WEBSITE (/BRAND/CONTACT) OR EMAIL CONTACT@FRONTALSLAYER.COM.',
          'PLEASE ALLOW AT LEAST 72 HOURS TO RECEIVE A RESPONSE FOR SUBMITTED INQUIRIES. BUSINESS HOURS ARE 10AM–6PM CST ON WEEKDAYS; MAJOR U.S. HOLIDAYS EXCLUDED.',
        ],
      },
      {
        id: 'submit-review',
        question: 'HOW DO I LEAVE A PRODUCT REVIEW?',
        answerParagraphs: [
          'FROM THE BRAND REVIEWS PAGE, TAP SUBMIT REVIEW (SIGN IN IF PROMPTED) TO OPEN YOUR ORDERS. ELIGIBLE DELIVERED ORDERS INCLUDE A LEAVE A REVIEW OPTION SO YOU CAN SHARE FEEDBACK AND EARN LOYALTY POINTS WHERE APPLICABLE.',
        ],
      },
    ],
  },
];

/** Display order for FAQ accordion sections on `/brand/faq`. */
export const BRAND_FAQ_SECTION_DISPLAY_ORDER = [
  'general',
  'ordering-processing',
  'membership-rewards',
  'hair-quality',
  'wigs-customization',
  'returns-policies',
] as const;

export const BRAND_FAQ_SECTIONS: BrandFaqSection[] = BRAND_FAQ_SECTION_DISPLAY_ORDER.map(
  (sectionId) => {
    const section = BRAND_FAQ_SECTIONS_LIST.find((s) => s.id === sectionId);
    if (!section) throw new Error(`Missing FAQ section: ${sectionId}`);
    return section;
  },
);
