/** About Us body copy for `/brand/about` — displayed in uppercase on the page. */
export const BRAND_ABOUT_US_PARAGRAPHS = [
  "THANK YOU FOR CHOOSING TO SHOP WITH US! THIS WEBSITE IS ABOUT MORE THAN JUST HAIR. HERE AT FRONTAL SLAYER WE ARE DETERMINED TO DELIVER A FIRST OF ITS KIND VIRTUAL 3D HAIR SALON THAT OFFERS A TOUCH OF NOSTALGIA, A LITTLE BIT OF FUN, AND A WHOLE LOT OF SLAY.",
  "WE'VE CURATED THIS SPACE TO BRING THE SALON DIRECTLY TO YOU IN A LUXE YET BEGINNER FRIENDLY WAY WHILE MAKING THE ENTIRE PROCESS SEAMLESS, CONVENIENT AND ACTUALLY ENJOYABLE TOO. WHETHER YOU'RE CURIOUS ABOUT HAIR EXTENSIONS, A FIRST TIME WIG WEARER OR A CERTIFIED FRONTAL ASSASSIN, WE BELIEVE PREMIUM HAIR SHOULD FEEL EFFORTLESS.",
  "WITH OVER 10 YEARS EXPERIENCE IN CUSTOMIZING INSTALLS, COLORING, STYLING, AND ETHICALLY SOURCING QUALITY RAW HUMAN HAIR THAT ACTUALLY LASTS, OUR FOUNDER AND CEO CREATED FRONTAL SLAYER WITH ONE MISSION IN MIND: HELPING CLIENTS LOOK EXPENSIVE WITHOUT THE CONFUSION, GATEKEEPING, OR SALON ANXIETY WE'VE ALL FACED.",
  "BECAUSE FRONTAL SLAYER ISN'T JUST A NAME… IT'S A MINDSET.",
  "WE'RE HERE TO HELP YOU SURVIVE THE TRIALS AND TRIBULATIONS OF DOING YOUR OWN HAIR THROUGH EDUCATIONAL GUIDES, TIPS + TRICKS, STEP BY STEP TUTORIALS AND INSTRUCTIONAL VIDEOS DESIGNED TO PUT THE POWER BACK INTO YOUR HANDS. THE GOAL IS SIMPLE: TO HELP YOU SLAY YOUR OWN HAIR WITH CONFIDENCE, CONVENIENCE, AND ZERO INTIMIDATION SO YOU TOO CAN SLAY YOUR OWN FRONTALS AND HAIR ONE DAY.",
  "WHAT TRULY SEPARATES US FROM YOUR AVERAGE HAIR BRAND IS THE OVERALL CUSTOMER EXPERIENCE. FROM FULLY CUSTOMIZABLE UNITS INCLUDING COLOR SERVICES TO TAILORED STYLING REQUESTS VIA OUR INTERACTIVE SHOPPING EXPERIENCE. EVERY SINGLE DETAIL IS DESIGNED WITH YOU IN MIND. WE UNDERSTAND AND HONOR THE FACT THAT LUXURY ISN'T ONE SIZE FITS ALL. YOUR HAIR SHOULD FEEL PERSONAL, BECAUSE IT IS.",
  "BEYOND THE HAIR ITSELF, WE'VE CREATED A COMMUNITY DRIVEN PLATFORM PACKED WITH EXCLUSIVE MEMBERSHIP SUBSCRIPTION OPTIONS, LOYALTY POINTS, REFERRAL PERKS, VIP DISCOUNTS, GIVEAWAYS, EARLY ACCESS TO NEW DROPS AND CLIENT CENTERED INCENTIVES THAT REWARD YOU SIMPLY FOR BEING A PART OF OUR SLAY SOCIETY. THINK WHITE GLOVE, CONCIERGE LEVEL SERVICE WITH MAIN CHARACTER ENERGY.",
  'WHETHER YOU NEED GUIDANCE CHOOSING THE PERFECT UNIT USING OUR COMPLIMENTARY CONSULTATION SERVICES, NEED HELP MASTERING YOUR INSTALL SKILLS OR JUST WANT PREMIUM HAIR THAT STANDS THE TEST OF TIME… FRONTAL SLAYER IS HERE TO MAKE THAT PROCESS FEEL ELEVATED, EDUCATIONAL, AND EFFORTLESS FROM START TO FINISH.',
  'LUXURY HAIR. REAL EDUCATION. NO GIMMICKS, JUST PRESSURE.',
] as const;

/** Red accent lines on About Us — Futura PT Medium. */
export const BRAND_ABOUT_ACCENT_PARAGRAPHS: ReadonlySet<string> = new Set([
  "BECAUSE FRONTAL SLAYER ISN'T JUST A NAME… IT'S A MINDSET.",
]);

/** Futura PT Demi lines on About Us. */
export const BRAND_ABOUT_DEMI_PARAGRAPHS: ReadonlySet<string> = new Set([
  'LUXURY HAIR. REAL EDUCATION. NO GIMMICKS, JUST PRESSURE.',
]);
