/** Contact Us intro copy for `/brand/contact` — displayed in uppercase on the page. */
export const BRAND_CONTACT_EMAIL = 'CONTACT@FRONTALSLAYER.COM';

export const BRAND_CONTACT_INTRO_LINE_1_PREFIX =
  'QUESTIONS, COMMENTS OR CONCERNS? FILL OUT THE FORM BELOW OR SEND US AN EMAIL AT ';

export const BRAND_CONTACT_INTRO_LINE_2_PREFIX =
  'PLEASE ALLOW AT LEAST 72 HOURS TO RECEIVE A RESPONSE FOR ALL SUBMITTED INQUIRIES. BUSINESS OPERATIONAL BETWEEN THE HOURS OF ';

export const BRAND_CONTACT_INTRO_HOURS = '10AM - 6PM CST';

export const BRAND_CONTACT_INTRO_LINE_2_SUFFIX =
  ' DURING WEEKDAYS ONLY. MAJOR US HOLIDAYS EXCLUDED.';
