/** Become a Member body copy for `/brand/member` — displayed in uppercase on the page. */
export const BRAND_MEMBER_PARAGRAPHS = [
  'JOIN THE SLAY SOCIETY!',
  'CREATING AN ACCOUNT WITH FRONTAL SLAYER UNLOCKS MORE THAN JUST FASTER CHECKOUT, IT GIVES YOU ACCESS TO THE FULL VIP EXPERIENCE. KEEP TRACK OF YOUR ORDER HISTORY, SAVE YOUR FAVORITE PRODUCTS, RECEIVE EXCLUSIVE NOTIFICATIONS ON NEW DROPS, RESTOCKS, SALES, GIVEAWAYS, AND BRAND UPDATES BEFORE THE PUBLIC DOES.',
  'AND YES… WE BELIEVE LOYALTY SHOULD ACTUALLY BE REWARDED.',
  'WITH OUR REWARDS PROGRAM, YOU CAN EARN LOYALTY POINTS THROUGH PURCHASES, PRODUCT REVIEWS, REFERRALS, SOCIAL MEDIA ENGAGEMENT, AND OTHER COMMUNITY INTERACTIONS. THEN YOU CAN CASH THOSE POINTS IN FOR DISCOUNTS, PERKS, FREE GIFTS AND SAVE BIG ON FUTURE ORDERS. BECAUSE SUPPORTING THE BRAND SHOULD COME WITH BENEFITS.',
  'NEW MEMBERS WHO SIGN UP & SUBSCRIBE TO OUR NEWSLETTER ALSO RECEIVE $10 OFF THEIR FIRST ORDER, BECAUSE YOUR FIRST SLAY WITH US DESERVES A PROPER INTRODUCTION.',
  "BUT THE PERKS DON'T STOP THERE.",
  "AS AN AFFILIATE MEMBER, YOU'LL RECEIVE YOUR OWN PERSONALIZED REFERRAL CODE TO SHARE WITH FRIENDS, FOLLOWERS, AND FELLOW HAIR ADDICTS ONCE YOU MAKE YOUR FIRST PURCHASE. EVERY REFERRAL GIFTS THEM AN ADDITIONAL $20 OFF THEIR FIRST PURCHASE WHILE DEPOSITING THE SAME AMOUNT OF DIGITAL CASH DIRECTLY INTO YOUR ACCOUNT ONCE THEIR ORDER HAS BEEN CONFIRMED. TRANSLATION? THE MORE PEOPLE YOU PUT ON, THE MORE REWARDS YOU UNLOCK!",
  'WANT TO EARN POINTS EVEN FASTER? TAG US IN YOUR SOCIAL MEDIA CONTENT, POST PHOTOS & VIDEOS, LEAVE CONTENT REVIEWS OR SHOW OFF YOUR FRONTAL SLAYER TRANSFORMATIONS ACROSS PLATFORMS LIKE INSTAGRAM, TIKTOK, YOUTUBE, FACEBOOK, AND X TO EARN ADDITIONAL REWARDS AND COMMUNITY PERKS.',
  'THIS IS YOUR OFFICIAL INVITE. WELCOME TO THE INNER CIRCLE.',
] as const;
