import { PSA_MEMBERSHIP_TITLE } from './psaMembershipCopy';

/** Unlock premium rewards copy (matches Account → Rewards marketing list). */
export type BrandUnlockPremiumRewardItem = {
  id: string;
  title: string;
  subtitle: string;
};

export const BRAND_UNLOCK_PREMIUM_REWARD_ITEMS: BrandUnlockPremiumRewardItem[] = [
  {
    id: 'psa',
    title: PSA_MEMBERSHIP_TITLE,
    subtitle:
      'YOUR PRIVATE AI HAIR CONCIERGE FOR EXPERT RECOMMENDATIONS, BUILD-A-WIG GUIDANCE, PRODUCT EDUCATION, ORDER ASSISTANCE, LOYALTY SUPPORT + INSTANT ANSWERS.',
  },
  {
    id: 'wig-selections',
    title: 'PREMIUM 3D WIG SELECTIONS',
    subtitle:
      'ACCESS PREMIUM BUILD-A-WIG OPTIONS DESIGNED FOR CLIENTS WHO WANT EVEN MORE CONTROL OVER THEIR FINAL LOOK.',
  },
  {
    id: 'lounge',
    title: 'MEMBERS ONLY LOBBY + LOUNGE',
    subtitle:
      'EXPLORE A PRIVATE DIGITAL LOUNGE FEATURING EXCLUSIVE CONTENT, EDUCATIONAL RESOURCES, MEMBER EVENTS, EARLY ACCESS DROPS + SPECIAL OFFERS.',
  },
  {
    id: 'support',
    title: 'PRIORITY MEMBER SUPPORT',
    subtitle:
      'SKIP THE LINE WITH PRIORITY ASSISTANCE, FASTER RESPONSE TIMES + DEDICATED MEMBER SUPPORT.',
  },
  {
    id: 'booking',
    title: 'PRIORITY BOOKING + PROCESSING',
    subtitle:
      'GAIN EARLIER ACCESS TO APPOINTMENTS, PRIORITY CONSIDERATION FOR ELIGIBLE SERVICES + EXPEDITED MEMBER EXPERIENCES WHEN AVAILABLE.',
  },
  {
    id: 'rewards',
    title: 'EXCLUSIVE REWARDS + CHALLENGES',
    subtitle:
      'COMPLETE MEMBERS ONLY CHALLENGES TO UNLOCK BONUS POINTS, FREE GIFTS, DISCOUNTS, VOUCHERS + SPECIAL REWARD OPPORTUNITIES.',
  },
  {
    id: 'watch-learn',
    title: 'WATCH + LEARN',
    subtitle:
      'UNLOCK EXCLUSIVE VIDEO CONTENT COVERING INSTALLATION, STYLING, MAINTENANCE, LACE CUSTOMIZATION + PROFESSIONAL TECHNIQUES.',
  },
  {
    id: 'slay-academy',
    title: 'SLAY ACADEMY',
    subtitle:
      'ACCESS MEMBERS ONLY CLASSES, EDUCATIONAL CONTENT, TUTORIALS + EXPERT GUIDANCE DESIGNED TO HELP YOU GET THE MOST FROM YOUR HAIR INVESTMENT.',
  },
  {
    id: 'anniversary-rewards',
    title: 'ANNIVERSARY REWARDS',
    subtitle:
      'CELEBRATE EACH MEMBERSHIP MILESTONE WITH BONUS POINTS, SPECIAL OFFERS, EXCLUSIVE GIFTS + SURPRISE MEMBER REWARDS.',
  },
  {
    id: 'points',
    title: 'DOUBLE YOUR POINTS',
    subtitle:
      'ACCELERATE YOUR REWARDS JOURNEY WITH 2X POINTS ON QUALIFYING PURCHASES, REVIEWS, REFERRALS + MEMBER ACTIVITIES.',
  },
];
