/** Become a Member body copy for `/brand/member` — displayed in uppercase on the page. */
export type BrandMemberBlockVariant = 'headline' | 'body' | 'accent' | 'demiGray';

export type BrandMemberBlock = {
  id: string;
  text: string;
  variant: BrandMemberBlockVariant;
};

export const BRAND_MEMBER_BLOCKS: BrandMemberBlock[] = [
  {
    id: 'headline',
    text: 'JOIN THE SLAY SOCIETY!',
    variant: 'headline',
  },
  {
    id: 'vip-experience',
    text: "CREATING AN ACCOUNT WITH FRONTAL SLAYER UNLOCKS MORE THAN JUST A FASTER CHECKOUT, IT GIVES YOU ACCESS TO THE FULL VIP EXPERIENCE AND THEN SOME. YOU'RE ABLE TO KEEP TRACK OF YOUR ORDER HISTORY, SAVE YOUR FAVORITE PRODUCTS TO YOUR WISHLIST AND CART, RECEIVE EXCLUSIVE NOTIFICATIONS ON NEW DROPS, RESTOCKS, SALES, GIVEAWAYS, AND BRAND RELATED UPDATES BEFORE THE PUBLIC DOES.",
    variant: 'body',
  },
  {
    id: 'loyalty-rewarded',
    text: 'AND YES… WE BELIEVE LOYALTY SHOULD ACTUALLY BE REWARDED.',
    variant: 'accent',
  },
  {
    id: 'rewards-program',
    text: 'WITH OUR REWARDS PROGRAM YOU CAN EARN LOYALTY POINTS THROUGH PURCHASES, PRODUCT REVIEWS, REFERRALS, SOCIAL MEDIA ENGAGEMENT AND OTHER COMMUNITY INTERACTIONS. YOU CAN REDEEM THOSE POINTS FOR DISCOUNTS, PERKS, FREE GIFTS AND SAVE BIG ON FUTURE ORDERS. BECAUSE SUPPORTING THE BRAND SHOULD COME WITH BENEFITS.',
    variant: 'body',
  },
  {
    id: 'newsletter-cash',
    text: 'NEW MEMBERS WHO SIGN UP AND SUBSCRIBE TO OUR NEWSLETTER WILL ALSO RECEIVE $10 DIGITAL CASH DEPOSITED INTO THEIR ACCOUNT. YOUR FIRST SLAY WITH US DESERVES A PROPER INTRODUCTION.',
    variant: 'body',
  },
  {
    id: 'perks-continue',
    text: "BUT THE PERKS DON'T STOP THERE…",
    variant: 'accent',
  },
  {
    id: 'affiliate',
    text: "AS AN AFFILIATE MEMBER YOU'LL RECEIVE YOUR OWN PERSONALIZED REFERRAL CODE TO SHARE WITH FRIENDS, FOLLOWERS AND FELLOW HAIR ADDICTS ONCE YOU COMPLETE YOUR FIRST PURCHASE. EVERY REFERRAL CODE GIFTS THEM AN ADDITIONAL $20 OFF THEIR FIRST PURCHASE WHILE DEPOSITING THE SAME AMOUNT OF DIGITAL CASH DIRECTLY INTO YOUR ACCOUNT ONCE THEIR ORDER HAS BEEN CONFIRMED. TRANSLATION? THE MORE PEOPLE YOU PUT ON, THE MORE REWARDS YOU UNLOCK!",
    variant: 'body',
  },
  {
    id: 'social-points',
    text: 'WANT TO EARN POINTS EVEN FASTER? TAG US IN YOUR SOCIAL MEDIA CONTENT, POST PHOTOS & VIDEOS, LEAVE CONTENT REVIEWS OR SHOW OFF YOUR FRONTAL SLAYER TRANSFORMATIONS ACROSS PLATFORMS LIKE INSTAGRAM, TIKTOK, YOUTUBE, FACEBOOK, AND X TO EARN ADDITIONAL PREMIUM REWARDS AND COMMUNITY PERKS.',
    variant: 'body',
  },
  {
    id: 'invite',
    text: 'THIS IS YOUR OFFICIAL INVITE. WELCOME TO THE INNER CIRCLE.',
    variant: 'accent',
  },
];
