/** Order authorization form acknowledgment copy — `/tools/order-form`. */

export const ORDER_FORM_UPLOAD_PRIVACY_NOTE =
  'FOR YOUR PROTECTION, SENSITIVE INFORMATION SUCH AS ID NUMBERS AND ALL BUT THE LAST FOUR DIGITS OF PAYMENT CARDS SHOULD BE COVERED BEFORE UPLOADING.';

export const ORDER_FORM_IDENTITY_VERIFICATION_LABEL =
  'IDENTITY VERIFICATION (CARDHOLDER) — NAME/ADDRESS SHOULD MATCH ORDER DETAILS. YOU MAY CENSOR OTHER INFO.';

export const ORDER_FORM_PAYMENT_VERIFICATION_LABEL =
  'PAYMENT VERIFICATION (CARDHOLDER) — PHOTO SHOWING FULL NAME AND LAST 4 DIGITS OF CARD. YOU MAY CENSOR OTHER DIGITS. DISREGARD IF USING A PAYMENT PLAN.';

export const ORDER_FORM_ACK_NO_CHARGEBACK =
  'I AGREE TO CONTACT FRONTAL SLAYER DIRECTLY REGARDING ANY ORDER CONCERNS BEFORE INITIATING A CHARGEBACK, PAYMENT DISPUTE, OR CLAIM WITH MY FINANCIAL INSTITUTION.';

export const ORDER_FORM_ACK_NO_CHARGEBACK_NOTE =
  'FRONTAL SLAYER IS COMMITTED TO RESOLVING LEGITIMATE ORDER CONCERNS. UNAUTHORIZED OR FRAUDULENT CHARGEBACKS MAY BE DISPUTED USING SUBMITTED VERIFICATION RECORDS AND SUPPORTING DOCUMENTATION.';

export const ORDER_FORM_ACK_RAW_HAIR =
  'I UNDERSTAND THAT RAW HUMAN HAIR IS A NATURAL PRODUCT AND SLIGHT VARIATIONS IN COLOR, TEXTURE, DENSITY, CURL PATTERN, AND LACE APPEARANCE ARE NORMAL AND NOT CONSIDERED DEFECTS.';

export function orderFormAckProcessingTimeline(timelineLabel?: string): string {
  const timeline = (timelineLabel || '').trim();
  if (timeline) {
    return `I HAVE REVIEWED AND UNDERSTAND THE PROCESSING TIMELINE ASSOCIATED WITH MY ORDER (${timeline}) AND UNDERSTAND THAT PROCESSING TIMES AND SHIPPING TIMES ARE SEPARATE.`;
  }
  return 'I HAVE REVIEWED AND UNDERSTAND THE PROCESSING TIMELINE ASSOCIATED WITH MY ORDER AND UNDERSTAND THAT PROCESSING TIMES AND SHIPPING TIMES ARE SEPARATE.';
}

export const ORDER_FORM_PAYMENT_METHOD_OPTIONS = [
  { value: 'CREDIT_CARD', label: 'CREDIT CARD' },
  { value: 'DEBIT_CARD', label: 'DEBIT CARD' },
  { value: 'SHOP_PAY', label: 'SHOP PAY' },
  { value: 'AFFIRM', label: 'AFFIRM' },
  { value: 'KLARNA', label: 'KLARNA' },
  { value: 'AFTERPAY', label: 'AFTERPAY' },
  { value: 'PAYPAL', label: 'PAYPAL' },
  { value: 'OTHER', label: 'OTHER' },
] as const;

export type OrderFormPaymentMethodValue = (typeof ORDER_FORM_PAYMENT_METHOD_OPTIONS)[number]['value'];
