/** Order Authorization Form intro copy — displayed in uppercase on `/tools/order-form`. */

export const ORDER_FORM_INTRO_OPENING =
  'TO PROTECT BOTH OUR CLIENTS AND OUR BUSINESS FROM FRAUDULENT ACTIVITY, UNAUTHORIZED TRANSACTIONS AND CHARGEBACKS, FRONTAL SLAYER REQUIRES ALL CUSTOMERS PURCHASING HAIR-RELATED PRODUCTS TO COMPLETE AN ORDER AUTHORIZATION FORM AFTER CHECKOUT.';

export const ORDER_FORM_INTRO_PURPOSE_TITLE = 'THIS FORM SERVES AS:';

export const ORDER_FORM_INTRO_PURPOSE_BULLETS = [
  'VERIFICATION OF YOUR IDENTITY AND PURCHASE',
  'AUTHORIZATION OF PAYMENT AND ORDER PROCESSING',
  'PROTECTION AGAINST FRAUDULENT CLAIMS AND DISPUTES',
  'CONFIRMATION THAT YOU AGREE TO OUR TERMS OF SERVICE, PROCESSING TIMES, AND REFUND POLICY',
] as const;

export const ORDER_FORM_INTRO_MATCH_INFO =
  'TO AVOID DELAYS, CANCELLATIONS, OR VERIFICATION ISSUES, ALL INFORMATION SUBMITTED ON THIS FORM MUST EXACTLY MATCH THE BILLING AND SHIPPING INFORMATION ASSOCIATED WITH YOUR ORDER.';

export const ORDER_FORM_INTRO_PLEASE_NOTE_TITLE = 'PLEASE NOTE:';

export const ORDER_FORM_INTRO_PLEASE_NOTE_BULLETS = [
  'ORDERS WILL NOT BE PROCESSED, CUSTOMIZED, OR SHIPPED UNTIL THIS FORM HAS BEEN SUCCESSFULLY COMPLETED AND SUBMITTED.',
  'THE ORDER AUTHORIZATION FORM MUST BE SUBMITTED WITHIN 24 HOURS OF PURCHASE.',
  'FAILURE TO COMPLETE THE FORM WITHIN THE REQUIRED TIMEFRAME MAY RESULT IN YOUR ORDER BEING AUTOMATICALLY CANCELED AND REFUNDED AT OUR DISCRETION.',
  'FRONTAL SLAYER RESERVES THE RIGHT TO REQUEST ADDITIONAL VERIFICATION DOCUMENTATION IF NECESSARY FOR SECURITY PURPOSES.',
  'ANY SUSPICIOUS, INCOMPLETE, MISMATCHED, OR POTENTIALLY FRAUDULENT ORDERS MAY BE DELAYED, CANCELED, OR REFUSED ENTIRELY TO PROTECT BOTH PARTIES INVOLVED.',
] as const;

export const ORDER_FORM_INTRO_AUTHORIZATION =
  'BY SUBMITTING THIS FORM, YOU ACKNOWLEDGE AND AUTHORIZE FRONTAL SLAYER TO PROCESS YOUR ORDER AND VERIFY THE INFORMATION PROVIDED. YOU ALSO CONFIRM THAT YOU ARE THE AUTHORIZED CARDHOLDER OR ACCOUNT HOLDER ASSOCIATED WITH THE PAYMENT METHOD USED DURING CHECKOUT.';

export const ORDER_FORM_INTRO_RECORDKEEPING =
  'FOR QUALITY ASSURANCE, FRAUD PREVENTION, AND RECORDKEEPING PURPOSES, SUBMITTED AUTHORIZATION FORMS AND RELATED COMMUNICATIONS MAY BE SECURELY STORED AND DOCUMENTED. COPIES MAY BE PROVIDED UPON REQUEST WHEN APPLICABLE.';

export const ORDER_FORM_INTRO_CONTACT_PREFIX =
  'IF YOU HAVE ANY QUESTIONS, CONCERNS, OR ISSUES COMPLETING THIS FORM, PLEASE CONTACT US AT ';

export const ORDER_FORM_INTRO_CONTACT_EMAIL = 'CONTACT@FRONTALSLAYER.COM';

export const ORDER_FORM_INTRO_CLOSING =
  "AS ALWAYS, THANK YOU FOR CHOOSING FRONTAL SLAYER. YOUR SUPPORT, TRUST AND BUSINESS ARE GENUINELY APPRECIATED. WE CAN'T WAIT FOR YOU TO SLAY!";
