import { PSA_MEMBERSHIP_BENEFIT_LABEL } from './psaMembershipCopy';

export const PREMIUM_BENEFITS_BY_TIER: Record<string, string[]> = {
    '3months': [
      'BIRTHDAY GIFT',
      'DISCOUNTED SHIPPING',
      'PREMIUM 3D WIG CUSTOMIZATION OPTIONS',
      'MEMBERS ONLY LOBBY + LOUNGE',
      PSA_MEMBERSHIP_BENEFIT_LABEL,
      'PRIORITY MEMBER SUPPORT',
      'PRIORITY BOOKING + PROCESSING',
      'WATCH + LEARN',
      'SLAY ACADEMY',
      'EXCLUSIVE REWARDS + CHALLENGES',
      'ANNIVERSARY REWARD: 500 LOYALTY POINTS',
      'LIVE ORDER TRACKING'
    ],
    '6months': [
      'BIRTHDAY GIFT',
      'DISCOUNTED SHIPPING',
      'PREMIUM 3D WIG CUSTOMIZATION OPTIONS',
      'MEMBERS ONLY LOBBY + LOUNGE',
      PSA_MEMBERSHIP_BENEFIT_LABEL,
      'PRIORITY MEMBER SUPPORT',
      'PRIORITY BOOKING + PROCESSING',
      'WATCH + LEARN',
      'SLAY ACADEMY',
      'EXCLUSIVE REWARDS + CHALLENGES',
      'ANNIVERSARY REWARD: 1,000 LOYALTY POINTS',
      'LIVE ORDER TRACKING',
      'PRIORITY MESSAGES'
    ],
    '12months': [
      'BIRTHDAY GIFT',
      'DISCOUNTED SHIPPING',
      'PREMIUM 3D WIG CUSTOMIZATION OPTIONS',
      'MEMBERS ONLY LOBBY + LOUNGE',
      PSA_MEMBERSHIP_BENEFIT_LABEL,
      'PRIORITY MEMBER SUPPORT',
      'PRIORITY BOOKING + PROCESSING',
      'WATCH + LEARN',
      'SLAY ACADEMY',
      'EXCLUSIVE REWARDS + CHALLENGES',
      'ANNIVERSARY REWARD: 1,500 LOYALTY POINTS',
      'LIVE ORDER TRACKING',
      'PRIORITY MESSAGES',
      'SPECIAL OFFERS',
      'DOUBLE YOUR POINTS'
    ]
  };

