export const PREMIUM_BENEFITS_BY_TIER: Record<string, string[]> = {
    '3months': [
      'BIRTHDAY GIFT',
      'DISCOUNTED SHIPPING',
      'PREMIUM 3D WIG CUSTOMIZATION OPTIONS',
      'ENTRY TO VIP MEMBERS ONLY LOUNGE',
      'FAST TRACK CUSTOMER SUPPORT',
      'PRIORITY BOOKING',
      'CHALLENGES',
      'LIVE ORDER TRACKING',
      'MEMBER REWARDS'
    ],
    '6months': [
      'BIRTHDAY GIFT',
      'DISCOUNTED SHIPPING',
      'PREMIUM 3D WIG CUSTOMIZATION OPTIONS',
      'ENTRY TO VIP MEMBERS ONLY LOUNGE',
      'FAST TRACK CUSTOMER SUPPORT',
      'PRIORITY BOOKING',
      'CHALLENGES',
      'LIVE ORDER TRACKING',
      'PRIORITY MESSAGES',
      'MEMBER REWARDS'
    ],
    '12months': [
      'BIRTHDAY GIFT',
      'DISCOUNTED SHIPPING',
      'PREMIUM 3D WIG CUSTOMIZATION OPTIONS',
      'ENTRY TO VIP MEMBERS ONLY LOUNGE',
      'FAST TRACK CUSTOMER SUPPORT',
      'PRIORITY BOOKING',
      'CHALLENGES',
      'LIVE ORDER TRACKING',
      'PRIORITY MESSAGES',
      'MEMBER REWARDS',
      'SPECIAL OFFERS',
      '2X LOYALTY POINTS'
    ]
  };

