export const PREMIUM_BENEFITS_BY_TIER: Record<string, string[]> = {
    '3months': [
      'BIRTHDAY GIFT',
      'DISCOUNTED SHIPPING',
      'PREMIUM 3D WIG CUSTOMIZATION OPTIONS',
      'ENTRY TO VIP MEMBERS ONLY LOUNGE',
      'FAST TRACK CUSTOMER SUPPORT',
      'PRIORITY BOOKING',
      'CHALLENGES',
      'MEMBER REWARDS'
    ],
    '6months': [
      'BIRTHDAY GIFT',
      'DISCOUNTED SHIPPING',
      'PREMIUM 3D WIG CUSTOMIZATION OPTIONS',
      'ENTRY TO VIP MEMBERS ONLY LOUNGE',
      'FAST TRACK CUSTOMER SUPPORT',
      'PRIORITY BOOKING',
      'CHALLENGES',
      'PRIORITY MESSAGES',
      'MEMBER REWARDS',
      'LIVE ORDER TRACKING'
    ],
    '12months': [
      'BIRTHDAY GIFT',
      'DISCOUNTED SHIPPING',
      'PREMIUM 3D WIG CUSTOMIZATION OPTIONS',
      'ENTRY TO VIP MEMBERS ONLY LOUNGE',
      'FAST TRACK CUSTOMER SUPPORT',
      'PRIORITY BOOKING',
      'CHALLENGES',
      'PRIORITY MESSAGES',
      'MEMBER REWARDS',
      'LIVE ORDER TRACKING',
      'SPECIAL OFFERS',
      '2X LOYALTY POINTS'
    ]
  };

