import { bootstrapOrganizationalWorkflowOrchestrationStore } from './store';
import type { OrganizationalWorkflowOrchestrationStore } from './types';

export function buildOrganizationalWorkflowOrchestrationSeed(): Partial<OrganizationalWorkflowOrchestrationStore> {
  return {
    companyName: 'NDXBOOK',
    activeWorkspaceId: 'ndxbook',
    dashboard: {
      summary:
        'ORGANIZATIONAL WORKFLOW ORCHESTRATION V1.0 — coordinated teams · not disconnected automations · the organization at work.',
      activeWorkflows: 5,
      departmentCollaborations: 18,
      completedInitiatives: 9,
      organizationalConfidencePct: 88,
      workflowHealthPct: 91,
      learningOpportunities: 4,
    },
    workflowTypes: [
      { id: 'wt-1', type: 'Product launches', description: 'Cross-functional GTM · editorial · distribution · relationship nurture' },
      { id: 'wt-2', type: 'Marketing campaigns', description: 'Brand · growth · campaign engine · creator collaborations' },
      { id: 'wt-3', type: 'Customer onboarding', description: 'Experience · digital · technology · trust-before-scale gates' },
      { id: 'wt-4', type: 'Content publishing', description: 'Writing DNA · distribution · reader graph · relationship intelligence' },
      { id: 'wt-5', type: 'Creator collaborations', description: 'Creator marketplace · brand alignment · revenue share validation' },
      { id: 'wt-6', type: 'Community growth', description: 'Advocacy pathways · engagement · belonging · organic share' },
      { id: 'wt-7', type: 'Executive planning', description: 'Council synthesis · strategy alignment · delegation handoff' },
      { id: 'wt-8', type: 'Knowledge creation', description: 'Institutional memory · wisdom elevation · organizational intelligence' },
    ],
    activeWorkflows: [
      {
        id: 'wf-1',
        name: 'Trust-first onboarding orchestration',
        type: 'Customer onboarding',
        status: 'active',
        objective: 'Reduce onboarding friction while preserving trust-before-scale gates',
        executiveOwner: 'Chief Experience Officer',
        departments: ['Experience', 'Digital', 'Technology', 'Growth'],
      },
      {
        id: 'wf-2',
        name: '100K reader GTM choreography',
        type: 'Product launches',
        status: 'planning',
        objective: 'Relationship-driven GTM to 100K engaged readers',
        executiveOwner: 'Chief Growth Officer',
        departments: ['Growth', 'Brand', 'Experience', 'Digital', 'Technology'],
      },
      {
        id: 'wf-3',
        name: 'Community engagement workflow',
        type: 'Community growth',
        status: 'adapting',
        objective: 'Increase community engagement through advocacy pathways',
        executiveOwner: 'Chief Growth Officer',
        departments: ['Growth', 'Brand', 'Experience', 'Relationship'],
      },
      {
        id: 'wf-4',
        name: 'Creator marketplace launch',
        type: 'Creator collaborations',
        status: 'active',
        objective: 'Establish curated creator ecosystem with Writing DNA gates',
        executiveOwner: 'Chief Growth Officer',
        departments: ['Growth', 'Brand', 'Digital', 'Creator Marketplace'],
      },
      {
        id: 'wf-5',
        name: 'Editorial identity consistency',
        type: 'Content publishing',
        status: 'active',
        objective: 'Stat-forward editorial identity across all publishing workflows',
        executiveOwner: 'Chief Brand Officer',
        departments: ['Brand', 'Creative', 'Distribution', 'Knowledge'],
      },
    ],
    crossFunctionalCoordination: [
      {
        id: 'cfc-1',
        workflowId: 'wf-1',
        workflow: 'Trust-first onboarding orchestration',
        executives: ['Chief Experience Officer', 'Chief Digital Officer', 'Chief Technology Officer'],
        architects: ['Experience Architect', 'Digital Architect'],
        departments: ['Experience', 'Digital', 'Technology'],
        knowledgeAssets: ['Onboarding journey map', 'Auth refactor spec', 'Trust gate checklist'],
        executionOrder: 'CEO audit → CDO UX simplification → CTO auth refactor → CoS validation → founder review Week 4',
        participantBrief: 'Each participant owns dependencies · timing · organizational impact · OI supports continuously',
      },
      {
        id: 'cfc-2',
        workflowId: 'wf-3',
        workflow: 'Community engagement workflow',
        executives: ['Chief Growth Officer', 'Chief Brand Officer', 'Chief Experience Officer'],
        architects: ['Growth Architect', 'Brand Architect'],
        departments: ['Growth', 'Brand', 'Experience', 'Relationship'],
        knowledgeAssets: ['Reader advocacy playbook', 'Community spotlight template', 'Belonging metrics'],
        executionOrder: 'CGO strategy → CBO messaging → CEO touchpoints → Relationship Engine nurture → measure advocacy',
        participantBrief: 'Collaborative execution · no isolated social posts · outcome is engagement not content volume',
      },
    ],
    workflowIntelligence: [
      {
        id: 'wi-1',
        workflow: 'Trust-first onboarding orchestration',
        strategy: 'Simplify journey without bypassing trust gates · CTO resolves auth debt in parallel',
        departmentResponsibilities: 'CEO: journey · CDO: UX · CTO: engineering · CoS: coordination · Growth: retention watch',
        dependencies: ['ODE delegation od-1', 'CTO auth refactor', 'OAF Level 3 customer workflow approval'],
        knowledgeRequirements: ['Onboarding friction audit', 'Step 3 drop-off data', 'Reader Graph early signals'],
        relationshipOpportunities: ['Welcome nurture sequence', 'Advocacy pathway early activation'],
        risks: ['Scope creep', 'Premature GTM pressure', 'Auth refactor delay'],
        timeline: '6 weeks · founder review Week 4 · automatic below OAF threshold after approval',
        resourceAllocation: 'CEO 40% · CDO 35% · CTO 25% · CoS orchestration continuous',
        confidence: 87,
        alternativePaths: 'Minimal simplification vs full journey redesign · parallel vs sequential auth',
        organizationRationale: 'Cross-functional because onboarding spans experience, digital, and technology — isolated task automation would miss trust gates',
      },
      {
        id: 'wi-2',
        workflow: '100K reader GTM choreography',
        strategy: 'Phased relationship-driven acquisition · vanity metrics blocked · council-approved sequencing',
        departmentResponsibilities: 'CGO: GTM · CBO: brand · CEO: touchpoints · CDO/CTO: platform readiness · CoS: conductor',
        dependencies: ['Council synthesis', 'Onboarding workflow health > 85%', 'Relationship metrics dashboard'],
        knowledgeRequirements: ['100K GTM plan', 'Trust-before-scale wisdom', 'Competitive positioning'],
        relationshipOpportunities: ['Creator pipeline', 'Advocate referral loops', 'Newsletter engagement'],
        risks: ['Paid acquisition temptation', 'Brand dilution', 'Platform scale before trust'],
        timeline: '12 weeks phased · founder gate at each phase',
        resourceAllocation: 'Full C-suite participation · architects on quality gates',
        confidence: 82,
        alternativePaths: 'Pilot market first vs full launch · creator-led vs editorial-led GTM',
        organizationRationale: 'GTM is organizational choreography — every department participates toward shared reader outcome',
      },
    ],
    livingWorkflowAdaptations: [
      {
        id: 'lwa-1',
        workflow: 'Community engagement workflow',
        trigger: 'Campaign underperforms on advocacy metric',
        executive: 'Chief Growth Officer',
        adaptation: 'Shift from volume tactics to reader spotlight program · CBO refines messaging',
        objectivePreserved: true,
      },
      {
        id: 'lwa-2',
        workflow: 'Trust-first onboarding orchestration',
        trigger: 'Customer feedback highlights Step 3 confusion',
        executive: 'Chief Experience Officer',
        adaptation: 'Experience officer updates onboarding copy · CDO simplifies Step 3 UI',
        objectivePreserved: true,
      },
      {
        id: 'lwa-3',
        workflow: 'Creator marketplace launch',
        trigger: 'New market opportunity in creator segment',
        executive: 'Chief Brand Officer',
        adaptation: 'Brand officer adjusts creator messaging · maintain Writing DNA gates',
        objectivePreserved: true,
      },
    ],
    chiefOfStaffCoordination: [
      {
        id: 'cos-1',
        workflow: 'Trust-first onboarding orchestration',
        responsibility: 'Coordinate departments',
        status: 'active',
        detail: 'Daily standup across CEO · CDO · CTO · surface blockers · maintain ODE alignment',
      },
      {
        id: 'cos-2',
        workflow: 'Trust-first onboarding orchestration',
        responsibility: 'Prepare executive updates',
        status: 'active',
        detail: 'Weekly founder briefing · progress · risks · pending approvals · organizational impact',
      },
      {
        id: 'cos-3',
        workflow: 'Community engagement workflow',
        responsibility: 'Facilitate collaboration',
        status: 'active',
        detail: 'CGO-CBO-CEO sync · recommend engagement adjustments · OI learning loop',
      },
      {
        id: 'cos-4',
        workflow: '100K reader GTM choreography',
        responsibility: 'Monitor execution',
        status: 'monitoring',
        detail: 'Pre-launch readiness · council prerequisites · relationship metrics dashboard',
      },
    ],
    workflowTransparency: [
      {
        id: 'wt-1',
        workflow: 'Trust-first onboarding orchestration',
        workflowMap: 'Audit → Simplify → Validate → GTM gate review',
        departmentParticipation: 'Experience · Digital · Technology · Growth (watch)',
        executiveOwnership: 'CEO owner · CDO · CTO supporting · CoS conductor',
        currentStatus: 'Week 2 · friction audit complete · simplification in progress',
        organizationalHealthPct: 89,
        risks: ['Auth refactor scope', 'GTM pressure'],
        confidence: 87,
        nextMilestones: ['Step 3 redesign complete', 'Auth refactor merge', 'Founder review Week 4'],
        organizationalLearning: 'Cross-functional onboarding reduces drop-off faster than isolated UX tasks',
      },
      {
        id: 'wt-2',
        workflow: 'Community engagement workflow',
        workflowMap: 'Strategy → Spotlight design → Pilot → Measure advocacy',
        departmentParticipation: 'Growth · Brand · Experience · Relationship',
        executiveOwnership: 'CGO owner · CBO · CEO supporting',
        currentStatus: 'Adapting · spotlight program replacing volume tactics',
        organizationalHealthPct: 85,
        risks: ['Community fatigue', 'Brand dilution'],
        confidence: 84,
        nextMilestones: ['Spotlight pilot launch', 'Advocacy +15% target', 'OI learning capture'],
        organizationalLearning: 'Engagement outcomes require relationship intelligence not content volume',
      },
    ],
    organizationalAdaptations: [
      {
        id: 'oa-1',
        workflow: 'Community engagement workflow',
        adaptationType: 'Workflow optimization',
        description: 'Parallel execution of spotlight design and nurture sequence · no founder intervention required',
        governanceAllowed: true,
      },
      {
        id: 'oa-2',
        workflow: 'Trust-first onboarding orchestration',
        adaptationType: 'Additional executive support',
        description: 'CTO added to critical path for auth refactor · CoS rebalanced resource allocation',
        governanceAllowed: true,
      },
      {
        id: 'oa-3',
        workflow: '100K reader GTM choreography',
        adaptationType: 'Risk mitigation',
        description: 'Council review gate inserted before Phase 2 · paid acquisition blocked by OAF',
        governanceAllowed: true,
      },
    ],
    workflowMemory: [
      {
        id: 'wm-1',
        workflow: 'Newsletter launch Q1',
        outcome: 'success',
        lessons: ['Relationship nurture outperformed broadcast', 'Writing DNA gates prevented generic templates'],
        bottlenecks: ['Initial distribution sequencing'],
        collaborationNotes: 'CGO-CBO-CoS triangle effective · Distribution Engine handoff smooth',
        customerOutcome: 'Open rate +22% · advocacy pathway activation +12%',
      },
      {
        id: 'wm-2',
        workflow: 'Brand refresh pilot',
        outcome: 'partial',
        lessons: ['Stat-forward consistency requires CBO early involvement', 'Architect gates save rework'],
        bottlenecks: ['Late technology validation'],
        collaborationNotes: 'Added CTO earlier in future brand workflows',
        customerOutcome: 'Brand recognition stable · minor touchpoint inconsistency resolved',
      },
    ],
    workflowSimulations: [
      {
        id: 'ws-1',
        workflow: '100K reader GTM choreography',
        bestCase: '100K engaged readers · retention stable · brand integrity preserved · creator pipeline active',
        worstCase: 'Vanity metric chase · trust erosion · onboarding overwhelmed · council escalation',
        organizationalRisks: ['Premature scale', 'Department silos', 'Paid acquisition temptation'],
        customerImpact: 'Best: belonging + advocacy · Worst: generic experience · churn spike',
        resourceUtilization: 'Full C-suite 12 weeks · architects on gates · CoS continuous',
        timelineVariation: '10-14 weeks depending on onboarding prerequisite',
        alternativeModel: 'Creator-led GTM vs editorial-led · pilot market vs full launch',
        executiveParticipation: 'CGO lead · full C-suite · council synthesis at gates',
        confidence: 82,
      },
      {
        id: 'ws-2',
        workflow: 'Trust-first onboarding orchestration',
        bestCase: 'Onboarding score > 85 · Step 3 drop-off -20% · GTM gate cleared',
        worstCase: 'Scope creep · auth delay · founder intervention required',
        organizationalRisks: ['Feature creep', 'Parallel work conflicts'],
        customerImpact: 'Best: frictionless trust-first entry · Worst: confusing steps · abandonment',
        resourceUtilization: 'CEO 40% · CDO 35% · CTO 25%',
        timelineVariation: '4-8 weeks depending on auth complexity',
        alternativeModel: 'Minimal simplification vs full redesign',
        executiveParticipation: 'CEO owner · CDO · CTO · CoS conductor',
        confidence: 87,
      },
    ],
    recommendedOptimizations: [
      {
        id: 'ro-1',
        workflow: 'Community engagement workflow',
        optimization: 'Integrate Reader Graph signals into weekly CoS standup',
        rationale: 'Advocacy data available but not yet in orchestration rhythm',
        confidence: 91,
      },
      {
        id: 'ro-2',
        workflow: 'Creator marketplace launch',
        optimization: 'Parallel brand review and technical onboarding paths',
        rationale: 'Reduce sequential bottleneck · maintain Writing DNA gates',
        confidence: 86,
      },
    ],
    recommendedNextSteps: [
      'Complete onboarding friction audit · hand off to CDO simplification sprint',
      'Run 100K GTM simulation with founder · compare alternative execution models',
      'Capture community engagement adaptation in OI learning loop',
      'Extend CoS conductor pattern to creator marketplace workflow',
    ],
    futureOpportunities: [
      'Workflow templates from successful newsletter launch memory',
      'Autonomous workflow reorganization when OAF trust exceeds Level 4',
      'Cross-workspace orchestration for portfolio companies',
    ],
  };
}

export function bootstrapOrganizationalWorkflowOrchestrationPlatform(): void {
  bootstrapOrganizationalWorkflowOrchestrationStore(buildOrganizationalWorkflowOrchestrationSeed());
}
