import { daysAgo } from './dateHelpers';
import type {
  BookkeepingException,
  BookkeepingPeriod,
  BookkeepingTransaction,
  CustomerClarification,
  FinancialAccount,
  FinancialConnection,
} from '../bookkeeping/autopilot/autopilotTypes';
import { dollarsToMinor } from '../billing/money';

export function createAutopilotSeedData(): {
  financialConnections: FinancialConnection[];
  financialAccounts: FinancialAccount[];
  bookkeepingTransactions: BookkeepingTransaction[];
  bookkeepingPeriods: BookkeepingPeriod[];
  bookkeepingExceptions: BookkeepingException[];
  customerClarifications: CustomerClarification[];
} {
  const financialConnections: FinancialConnection[] = [
    {
      id: 'fin-conn-b',
      organizationId: 'client-b',
      provider: 'demo',
      institutionName: 'Demo Regional Bank',
      status: 'CONNECTED',
      lastSuccessfulSyncAt: daysAgo(0),
      lastAttemptedSyncAt: daysAgo(0),
      requiresCustomerAction: false,
      createdAt: daysAgo(60),
      updatedAt: daysAgo(0),
    },
    {
      id: 'fin-conn-c',
      organizationId: 'client-c',
      provider: 'demo',
      institutionName: 'Demo Commerce Bank',
      status: 'CONNECTED',
      lastSuccessfulSyncAt: daysAgo(1),
      lastAttemptedSyncAt: daysAgo(1),
      requiresCustomerAction: false,
      createdAt: daysAgo(180),
      updatedAt: daysAgo(1),
    },
    {
      id: 'fin-conn-a',
      organizationId: 'client-a',
      provider: 'demo',
      institutionName: 'Demo Credit Union',
      status: 'ACTION_REQUIRED',
      lastSuccessfulSyncAt: daysAgo(14),
      lastAttemptedSyncAt: daysAgo(2),
      requiresCustomerAction: true,
      errorCode: 'REAUTH_REQUIRED',
      createdAt: daysAgo(7),
      updatedAt: daysAgo(2),
    },
  ];

  const financialAccounts: FinancialAccount[] = [
    {
      id: 'fin-acct-b-checking',
      connectionId: 'fin-conn-b',
      organizationId: 'client-b',
      accountName: 'Business Checking',
      accountMask: '4821',
      accountType: 'depository',
      accountSubtype: 'checking',
      currency: 'USD',
      active: true,
      bookkeepingEnabled: true,
      createdAt: daysAgo(60),
      updatedAt: daysAgo(0),
    },
    {
      id: 'fin-acct-b-fuel',
      connectionId: 'fin-conn-b',
      organizationId: 'client-b',
      accountName: 'Fuel Card',
      accountMask: '9103',
      accountType: 'credit',
      accountSubtype: 'credit card',
      currency: 'USD',
      active: true,
      bookkeepingEnabled: true,
      createdAt: daysAgo(60),
      updatedAt: daysAgo(0),
    },
    {
      id: 'fin-acct-c-checking',
      connectionId: 'fin-conn-c',
      organizationId: 'client-c',
      accountName: 'Operating Account',
      accountMask: '2207',
      accountType: 'depository',
      accountSubtype: 'checking',
      currency: 'USD',
      active: true,
      bookkeepingEnabled: true,
      createdAt: daysAgo(180),
      updatedAt: daysAgo(1),
    },
    {
      id: 'fin-acct-a-checking',
      connectionId: 'fin-conn-a',
      organizationId: 'client-a',
      accountName: 'Business Checking',
      accountMask: '1188',
      accountType: 'depository',
      accountSubtype: 'checking',
      currency: 'USD',
      active: true,
      bookkeepingEnabled: true,
      createdAt: daysAgo(7),
      updatedAt: daysAgo(2),
    },
  ];

  const bookkeepingPeriods: BookkeepingPeriod[] = [
    {
      id: 'bk-period-b-aug',
      subscriptionId: 'bk-sub-b',
      organizationId: 'client-b',
      periodStart: '2026-08-01',
      periodEnd: '2026-08-31',
      label: 'August 2026',
      status: 'EXCEPTIONS_FOUND',
      transactionCount: 246,
      autoClassifiedCount: 239,
      reviewCount: 3,
      reconciliationStatus: 'MATCHED',
      reportStatus: 'DRAFT',
      autopilotCoveragePct: 97,
      openedAt: daysAgo(15),
    },
    {
      id: 'bk-period-c-aug',
      subscriptionId: 'bk-sub-c',
      organizationId: 'client-c',
      periodStart: '2026-08-01',
      periodEnd: '2026-08-31',
      label: 'August 2026',
      status: 'READY_TO_CLOSE',
      transactionCount: 412,
      autoClassifiedCount: 408,
      reviewCount: 0,
      reconciliationStatus: 'MATCHED',
      reportStatus: 'GENERATED',
      autopilotCoveragePct: 99,
      openedAt: daysAgo(15),
      readyToCloseAt: daysAgo(1),
    },
  ];

  const bookkeepingTransactions: BookkeepingTransaction[] = [
    {
      id: 'bk-tx-b-1',
      organizationId: 'client-b',
      financialAccountId: 'fin-acct-b-fuel',
      providerTransactionReference: 'demo-tx-1001',
      transactionDate: '2026-08-13',
      amountMinor: dollarsToMinor(612.84),
      direction: 'debit',
      merchantName: "Love's Travel Stop",
      category: 'Fuel',
      classificationSource: 'MERCHANT_RULE',
      classificationConfidence: 'VERY_HIGH',
      classificationReason: "Merchant rule — Love's Travel Stop",
      truckId: 'truck-b-1',
      status: 'classified',
      reviewState: 'AUTO_APPROVABLE',
      periodId: 'bk-period-b-aug',
      provenance: 'BANK_FEED',
      createdAt: daysAgo(3),
      updatedAt: daysAgo(3),
    },
    {
      id: 'bk-tx-b-2',
      organizationId: 'client-b',
      financialAccountId: 'fin-acct-b-checking',
      transactionDate: '2026-08-14',
      amountMinor: dollarsToMinor(942),
      direction: 'debit',
      merchantName: 'ABC Supply',
      category: 'Other — Review Required',
      classificationConfidence: 'UNCLASSIFIED',
      classificationReason: 'No matching merchant rule — clarification may be required',
      status: 'pending',
      reviewState: 'CUSTOMER_CLARIFICATION',
      periodId: 'bk-period-b-aug',
      provenance: 'BANK_FEED',
      createdAt: daysAgo(2),
      updatedAt: daysAgo(2),
    },
    {
      id: 'bk-tx-b-3',
      organizationId: 'client-b',
      financialAccountId: 'fin-acct-b-checking',
      transactionDate: '2026-08-10',
      amountMinor: dollarsToMinor(4750),
      direction: 'credit',
      merchantName: 'Demo Factor Advance',
      category: 'Freight Revenue',
      classificationSource: 'DOCUMENT_MATCH',
      classificationConfidence: 'HIGH',
      classificationReason: 'Factoring settlement matched to invoice #INV-4402',
      status: 'classified',
      reviewState: 'AUTO_APPROVABLE',
      periodId: 'bk-period-b-aug',
      provenance: 'BANK_FEED',
      createdAt: daysAgo(5),
      updatedAt: daysAgo(4),
    },
    {
      id: 'bk-tx-b-4',
      organizationId: 'client-b',
      financialAccountId: 'fin-acct-b-checking',
      transactionDate: '2026-08-11',
      amountMinor: dollarsToMinor(89.5),
      direction: 'debit',
      merchantName: 'Unknown Vendor',
      status: 'pending',
      reviewState: 'REVIEW_REQUIRED',
      periodId: 'bk-period-b-aug',
      provenance: 'BANK_FEED',
      createdAt: daysAgo(4),
      updatedAt: daysAgo(4),
    },
    {
      id: 'bk-tx-c-1',
      organizationId: 'client-c',
      financialAccountId: 'fin-acct-c-checking',
      transactionDate: '2026-08-05',
      amountMinor: dollarsToMinor(320.15),
      direction: 'debit',
      merchantName: 'PrePass',
      category: 'Tolls',
      classificationSource: 'MERCHANT_RULE',
      classificationConfidence: 'VERY_HIGH',
      status: 'classified',
      reviewState: 'AUTO_APPROVABLE',
      periodId: 'bk-period-c-aug',
      provenance: 'BANK_FEED',
      createdAt: daysAgo(10),
      updatedAt: daysAgo(10),
    },
  ];

  const bookkeepingExceptions: BookkeepingException[] = [
    {
      id: 'bk-ex-b-1',
      organizationId: 'client-b',
      periodId: 'bk-period-b-aug',
      type: 'CUSTOMER_CLARIFICATION',
      priority: 'NORMAL',
      title: 'ABC Supply — $942.00',
      explanation: 'Customer clarification needed for purchase category',
      transactionId: 'bk-tx-b-2',
      status: 'open',
      createdAt: daysAgo(2),
      updatedAt: daysAgo(2),
    },
    {
      id: 'bk-ex-b-2',
      organizationId: 'client-b',
      periodId: 'bk-period-b-aug',
      type: 'UNKNOWN_CATEGORY',
      priority: 'NORMAL',
      title: 'Unknown Vendor — $89.50',
      explanation: 'Low-confidence classification — staff review',
      transactionId: 'bk-tx-b-4',
      status: 'open',
      createdAt: daysAgo(4),
      updatedAt: daysAgo(4),
    },
    {
      id: 'bk-ex-b-3',
      organizationId: 'client-b',
      periodId: 'bk-period-b-aug',
      type: 'MISSING_RECEIPT',
      priority: 'LOW',
      title: 'Fuel receipt needed — Truck 01',
      explanation: 'Policy requires receipt for fuel over $500',
      transactionId: 'bk-tx-b-1',
      status: 'open',
      createdAt: daysAgo(3),
      updatedAt: daysAgo(3),
    },
  ];

  const customerClarifications: CustomerClarification[] = [
    {
      id: 'bk-clar-b-1',
      organizationId: 'client-b',
      periodId: 'bk-period-b-aug',
      transactionId: 'bk-tx-b-2',
      merchantLabel: 'ABC Supply',
      amountMinor: dollarsToMinor(942),
      transactionDate: '2026-08-14',
      question: 'What was this purchase for?',
      options: ['Truck Repair', 'Trailer Repair', 'Equipment', 'Office / Business', 'Personal / Owner', 'Other'],
      status: 'pending',
      createdAt: daysAgo(2),
      updatedAt: daysAgo(2),
    },
  ];

  return {
    financialConnections,
    financialAccounts,
    bookkeepingTransactions,
    bookkeepingPeriods,
    bookkeepingExceptions,
    customerClarifications,
  };
}
