import { dollarsToMinor } from '../billing/money';
import { computeGrossMinor } from '../dispatch/dispatchCalculations';
import type {
  BrokerContact,
  DispatchBillingConfig,
  DispatchCounters,
  DispatchEnrollment,
  Load,
  LoadTimelineEvent,
  TruckDispatchProfile,
} from '../dispatch/dispatchTypes';
import { daysAgo, daysAhead, isoNow } from '../demo/dateHelpers';

function timeline(
  loadId: string,
  entries: Omit<LoadTimelineEvent, 'id' | 'loadId'>[],
): LoadTimelineEvent[] {
  return entries.map((e, i) => ({
    id: `${loadId}-tl-${i}`,
    loadId,
    ...e,
  }));
}

export function createDispatchSeedData(): {
  enrollments: DispatchEnrollment[];
  truckProfiles: TruckDispatchProfile[];
  loads: Load[];
  brokerContacts: BrokerContact[];
  dispatchBillingConfigs: DispatchBillingConfig[];
  dispatchCounters: DispatchCounters;
} {
  const brokers: BrokerContact[] = [
    {
      id: 'broker-demo-logistics',
      companyName: 'Demo Logistics LLC',
      contactName: 'Sam Broker',
      phone: '(404) 555-8800',
      email: 'dispatch@demologistics.example',
      status: 'preferred',
      preferredContactMethod: 'email',
      createdAt: daysAgo(30),
    },
    {
      id: 'broker-example-freight',
      companyName: 'Example Freight Partners',
      contactName: 'Jordan Miles',
      phone: '(214) 555-4400',
      status: 'active',
      createdAt: daysAgo(60),
    },
  ];

  const enrollments: DispatchEnrollment[] = [
    {
      id: 'enroll-a',
      organizationId: 'client-a',
      status: 'active',
      agreementStatus: 'accepted',
      primaryDispatcherStaffId: 'staff-4',
      onboardingComplete: true,
      activatedAt: daysAgo(14),
      preferences: {
        preferredFreightTypes: ['Dry Van', 'General Freight'],
        preferredRegions: ['Southeast', 'South Central'],
        preferredStates: ['TX', 'GA', 'FL', 'LA'],
        trailerType: 'Dry Van',
        teamOrSolo: 'solo',
        homeCity: 'Austin',
        homeState: 'TX',
        minPreferredRpmMinor: 250,
      },
      createdAt: daysAgo(20),
      updatedAt: daysAgo(1),
    },
    {
      id: 'enroll-b',
      organizationId: 'client-b',
      status: 'active',
      agreementStatus: 'accepted',
      primaryDispatcherStaffId: 'staff-4',
      onboardingComplete: true,
      activatedAt: daysAgo(90),
      preferences: {
        preferredFreightTypes: ['Dry Van'],
        preferredStates: ['OH', 'PA', 'IN', 'KY'],
        homeCity: 'Columbus',
        homeState: 'OH',
      },
      createdAt: daysAgo(100),
      updatedAt: daysAgo(0),
    },
    {
      id: 'enroll-c',
      organizationId: 'client-c',
      status: 'active',
      agreementStatus: 'accepted',
      primaryDispatcherStaffId: 'staff-4',
      onboardingComplete: true,
      activatedAt: daysAgo(180),
      createdAt: daysAgo(200),
      updatedAt: daysAgo(0),
    },
    {
      id: 'enroll-d',
      organizationId: 'client-d',
      status: 'active',
      agreementStatus: 'accepted',
      primaryDispatcherStaffId: 'staff-4',
      onboardingComplete: true,
      activatedAt: daysAgo(60),
      createdAt: daysAgo(70),
      updatedAt: daysAgo(0),
    },
    {
      id: 'enroll-e',
      organizationId: 'client-e',
      status: 'interested',
      agreementStatus: 'pending',
      onboardingComplete: false,
      createdAt: daysAgo(5),
      updatedAt: daysAgo(5),
    },
  ];

  const truckProfiles: TruckDispatchProfile[] = [
    {
      id: 'tdp-a1',
      organizationId: 'client-a',
      powerUnitId: 'unit-a1',
      nickname: 'Unit 01',
      availability: 'available',
      nextAvailableDate: daysAhead(0),
      nextAvailableCity: 'Austin',
      nextAvailableState: 'TX',
      trailerType: 'Dry Van',
      lastKnownLat: 30.2672,
      lastKnownLng: -97.7431,
      lastKnownLocationAt: isoNow(),
      lastKnownLocationLabel: 'Austin, TX',
      currentOdometerMiles: 428000,
      nextPmOdometerMiles: 429000,
      updatedAt: isoNow(),
    },
    {
      id: 'tdp-b1',
      organizationId: 'client-b',
      powerUnitId: 'unit-b1',
      nickname: 'Truck 204',
      availability: 'in_transit',
      currentLoadId: 'load-b-active',
      trailerType: 'Dry Van',
      primaryDriverId: 'drv-b1',
      updatedAt: isoNow(),
    },
    {
      id: 'tdp-c1',
      organizationId: 'client-c',
      powerUnitId: 'unit-c1',
      nickname: 'Truck 01',
      availability: 'in_transit',
      currentLoadId: 'load-c-transit',
      trailerType: 'Dry Van',
      primaryDriverId: 'drv-c1',
      updatedAt: isoNow(),
    },
    {
      id: 'tdp-c2',
      organizationId: 'client-c',
      powerUnitId: 'unit-c2',
      nickname: 'Truck 02',
      availability: 'available',
      nextAvailableDate: daysAhead(0),
      nextAvailableCity: 'Atlanta',
      nextAvailableState: 'GA',
      trailerType: 'Dry Van',
      updatedAt: isoNow(),
    },
    {
      id: 'tdp-c3',
      organizationId: 'client-c',
      powerUnitId: 'unit-c3',
      nickname: 'Truck 03',
      availability: 'home_time',
      nextAvailableDate: daysAhead(3),
      nextAvailableCity: 'Atlanta',
      nextAvailableState: 'GA',
      trailerType: 'Dry Van',
      updatedAt: isoNow(),
    },
    {
      id: 'tdp-d1',
      organizationId: 'client-d',
      powerUnitId: 'unit-d1',
      nickname: 'Unit 7',
      availability: 'available_soon',
      nextAvailableDate: daysAhead(1),
      nextAvailableCity: 'Jacksonville',
      nextAvailableState: 'FL',
      currentLoadId: 'load-d-pod',
      trailerType: 'Dry Van',
      updatedAt: isoNow(),
    },
  ];

  // Carrier A — load offer awaiting carrier
  const loadOfferA: Load = {
    id: 'load-a-offer',
    loadNumber: 'AIO-LD-2026-000001',
    organizationId: 'client-a',
    dispatchEnrollmentId: 'enroll-a',
    powerUnitId: 'unit-a1',
    assignedDispatcherStaffId: 'staff-4',
    sourceType: 'manual',
    brokerContactId: 'broker-demo-logistics',
    brokerName: 'Demo Logistics LLC',
    brokerContactName: 'Sam Broker',
    commodity: 'General Freight',
    weight: '32,000 lbs',
    equipmentType: 'Dry Van',
    originCity: 'Atlanta',
    originState: 'GA',
    destinationCity: 'Dallas',
    destinationState: 'TX',
    pickupDate: daysAhead(2),
    pickupTimeStart: '09:00',
    pickupTimeEnd: '12:00',
    deliveryDate: daysAhead(3),
    deliveryTimeStart: '08:00',
    loadedMiles: 780,
    deadheadMiles: 42,
    linehaulMinor: dollarsToMinor(2200),
    fuelSurchargeMinor: dollarsToMinor(150),
    accessorialMinor: 0,
    grossMinor: dollarsToMinor(2350),
    confirmedGrossMinor: dollarsToMinor(2350),
    currency: 'USD',
    offerStatus: 'awaiting_carrier',
    operationalStatus: 'opportunity',
    rateConfirmationStatus: 'missing',
    rateDetailsReviewed: false,
    factoringHandoffStatus: 'not_ready',
    accessorials: [],
    rateRevisions: [],
    timeline: timeline('load-a-offer', [
      { label: 'Load opportunity created', operationalStatus: 'opportunity', actor: 'dispatcher', actorLabel: 'Riley Chen', visibility: 'internal', createdAt: daysAgo(0) },
      { label: 'Load offer sent to carrier', actor: 'dispatcher', actorLabel: 'Riley Chen', visibility: 'customer', createdAt: daysAgo(0) },
    ]),
    customerNotes: 'Demo load — review rate and deadhead before accepting.',
    createdByStaffId: 'staff-4',
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
    version: 1,
  };

  // Carrier B — in transit Atlanta → Dallas
  const loadBActive: Load = {
    id: 'load-b-active',
    loadNumber: 'AIO-LD-2026-000002',
    organizationId: 'client-b',
    dispatchEnrollmentId: 'enroll-b',
    powerUnitId: 'unit-b1',
    primaryDriverId: 'drv-b1',
    assignedDispatcherStaffId: 'staff-4',
    sourceType: 'manual',
    brokerName: 'Example Freight Partners',
    equipmentType: 'Dry Van',
    originCity: 'Atlanta',
    originState: 'GA',
    destinationCity: 'Dallas',
    destinationState: 'TX',
    pickupDate: daysAhead(-1),
    deliveryDate: daysAhead(1),
    loadedMiles: 780,
    deadheadMiles: 55,
    linehaulMinor: dollarsToMinor(2400),
    fuelSurchargeMinor: dollarsToMinor(100),
    accessorialMinor: 0,
    grossMinor: dollarsToMinor(2500),
    confirmedGrossMinor: dollarsToMinor(2500),
    currency: 'USD',
    offerStatus: 'accepted',
    operationalStatus: 'in_transit',
    rateConfirmationStatus: 'details_reviewed',
    rateDetailsReviewed: true,
    bolDocumentId: 'vdoc-b-bol',
    factoringHandoffStatus: 'not_ready',
    accessorials: [],
    rateRevisions: [],
    timeline: timeline('load-b-active', [
      { label: 'Load booked', operationalStatus: 'booked', visibility: 'customer', createdAt: daysAgo(3) },
      { label: 'Marked in transit', operationalStatus: 'in_transit', actor: 'driver', actorLabel: 'Driver', visibility: 'customer', createdAt: daysAgo(0) },
    ]),
    createdByStaffId: 'staff-4',
    createdAt: daysAgo(4),
    updatedAt: daysAgo(0),
    version: 2,
  };

  // Carrier D — delivered, POD missing
  const loadDPod: Load = {
    id: 'load-d-pod',
    loadNumber: 'AIO-LD-2026-000003',
    organizationId: 'client-d',
    dispatchEnrollmentId: 'enroll-d',
    powerUnitId: 'unit-d1',
    assignedDispatcherStaffId: 'staff-4',
    sourceType: 'manual',
    brokerName: 'Demo Logistics LLC',
    equipmentType: 'Dry Van',
    originCity: 'Jacksonville',
    originState: 'FL',
    destinationCity: 'Orlando',
    destinationState: 'FL',
    pickupDate: daysAhead(-2),
    deliveryDate: daysAhead(-1),
    loadedMiles: 140,
    deadheadMiles: 20,
    linehaulMinor: dollarsToMinor(650),
    fuelSurchargeMinor: 0,
    accessorialMinor: 0,
    grossMinor: dollarsToMinor(650),
    confirmedGrossMinor: dollarsToMinor(650),
    currency: 'USD',
    offerStatus: 'accepted',
    operationalStatus: 'pod_needed',
    rateConfirmationStatus: 'details_reviewed',
    rateDetailsReviewed: true,
    bolDocumentId: 'vdoc-d-bol',
    factoringHandoffStatus: 'not_ready',
    accessorials: [],
    rateRevisions: [],
    timeline: timeline('load-d-pod', [
      { label: 'Delivered', operationalStatus: 'delivered', actor: 'driver', visibility: 'customer', createdAt: daysAgo(1) },
      { label: 'POD needed', operationalStatus: 'pod_needed', visibility: 'customer', createdAt: daysAgo(1) },
    ]),
    createdByStaffId: 'staff-4',
    createdAt: daysAgo(5),
    updatedAt: daysAgo(1),
    version: 1,
  };

  // Carrier C fleet — truck 01 in transit
  const loadCTransit: Load = {
    id: 'load-c-transit',
    loadNumber: 'AIO-LD-2026-000004',
    organizationId: 'client-c',
    dispatchEnrollmentId: 'enroll-c',
    powerUnitId: 'unit-c1',
    primaryDriverId: 'drv-c1',
    assignedDispatcherStaffId: 'staff-4',
    sourceType: 'manual',
    brokerName: 'Example Freight Partners',
    equipmentType: 'Dry Van',
    originCity: 'Charlotte',
    originState: 'NC',
    destinationCity: 'Nashville',
    destinationState: 'TN',
    pickupDate: daysAhead(-1),
    deliveryDate: daysAhead(0),
    loadedMiles: 410,
    deadheadMiles: 30,
    linehaulMinor: dollarsToMinor(1200),
    fuelSurchargeMinor: dollarsToMinor(50),
    accessorialMinor: 0,
    grossMinor: computeGrossMinor(dollarsToMinor(1200), dollarsToMinor(50), 0),
    confirmedGrossMinor: computeGrossMinor(dollarsToMinor(1200), dollarsToMinor(50), 0),
    currency: 'USD',
    offerStatus: 'accepted',
    operationalStatus: 'in_transit',
    rateConfirmationStatus: 'uploaded',
    rateDetailsReviewed: true,
    factoringHandoffStatus: 'not_ready',
    accessorials: [],
    rateRevisions: [],
    timeline: timeline('load-c-transit', [
      { label: 'In transit', operationalStatus: 'in_transit', visibility: 'customer', createdAt: daysAgo(0) },
    ]),
    createdByStaffId: 'staff-4',
    createdAt: daysAgo(3),
    updatedAt: daysAgo(0),
    version: 1,
  };

  // Carrier E scenario on client-d — completed, factoring ready
  const loadComplete: Load = {
    id: 'load-d-complete',
    loadNumber: 'AIO-LD-2026-000005',
    organizationId: 'client-d',
    dispatchEnrollmentId: 'enroll-d',
    powerUnitId: 'unit-d2',
    assignedDispatcherStaffId: 'staff-4',
    sourceType: 'manual',
    brokerName: 'Demo Logistics LLC',
    equipmentType: 'Dry Van',
    originCity: 'Tampa',
    originState: 'FL',
    destinationCity: 'Miami',
    destinationState: 'FL',
    pickupDate: daysAhead(-7),
    deliveryDate: daysAhead(-6),
    loadedMiles: 280,
    deadheadMiles: 15,
    linehaulMinor: dollarsToMinor(900),
    fuelSurchargeMinor: 0,
    accessorialMinor: 0,
    grossMinor: dollarsToMinor(900),
    confirmedGrossMinor: dollarsToMinor(900),
    currency: 'USD',
    offerStatus: 'accepted',
    operationalStatus: 'complete',
    rateConfirmationStatus: 'details_reviewed',
    rateDetailsReviewed: true,
    rateConfirmationDocumentId: 'vdoc-d-rc',
    bolDocumentId: 'vdoc-d-bol2',
    podDocumentId: 'vdoc-d-pod',
    factoringHandoffStatus: 'ready',
    accessorials: [],
    rateRevisions: [],
    timeline: timeline('load-d-complete', [
      { label: 'Load complete', operationalStatus: 'complete', visibility: 'customer', createdAt: daysAgo(5) },
    ]),
    createdByStaffId: 'staff-4',
    createdAt: daysAgo(10),
    updatedAt: daysAgo(5),
    version: 1,
  };

  // Carrier B — completed, ready for factoring (all docs)
  const loadBComplete: Load = {
    id: 'load-b-complete',
    loadNumber: 'AIO-LD-2026-000006',
    organizationId: 'client-b',
    dispatchEnrollmentId: 'enroll-b',
    powerUnitId: 'unit-b1',
    assignedDispatcherStaffId: 'staff-4',
    sourceType: 'manual',
    brokerName: 'Example Freight Partners',
    equipmentType: 'Dry Van',
    originCity: 'Columbus',
    originState: 'OH',
    destinationCity: 'Indianapolis',
    destinationState: 'IN',
    pickupDate: daysAhead(-5),
    deliveryDate: daysAhead(-4),
    loadedMiles: 175,
    deadheadMiles: 25,
    linehaulMinor: dollarsToMinor(650),
    fuelSurchargeMinor: dollarsToMinor(50),
    accessorialMinor: 0,
    grossMinor: dollarsToMinor(700),
    confirmedGrossMinor: dollarsToMinor(700),
    currency: 'USD',
    offerStatus: 'accepted',
    operationalStatus: 'complete',
    rateConfirmationStatus: 'details_reviewed',
    rateDetailsReviewed: true,
    rateConfirmationDocumentId: 'vdoc-b-rc',
    bolDocumentId: 'vdoc-b-bol',
    podDocumentId: 'vdoc-b-pod',
    factoringHandoffStatus: 'ready',
    accessorials: [],
    rateRevisions: [],
    timeline: timeline('load-b-complete', [
      { label: 'Load complete', operationalStatus: 'complete', visibility: 'customer', createdAt: daysAgo(3) },
    ]),
    createdByStaffId: 'staff-4',
    createdAt: daysAgo(8),
    updatedAt: daysAgo(3),
    version: 1,
  };

  const loadEComplete: Load = {
    id: 'load-e-complete',
    loadNumber: 'AIO-LD-2026-000007',
    organizationId: 'client-e',
    sourceType: 'carrier_provided',
    brokerName: 'Demo Logistics LLC',
    equipmentType: 'Dry Van',
    originCity: 'Chicago',
    originState: 'IL',
    destinationCity: 'Detroit',
    destinationState: 'MI',
    pickupDate: daysAhead(-8),
    deliveryDate: daysAhead(-7),
    loadedMiles: 280,
    deadheadMiles: 30,
    linehaulMinor: dollarsToMinor(2400),
    fuelSurchargeMinor: dollarsToMinor(50),
    accessorialMinor: 0,
    grossMinor: dollarsToMinor(2450),
    confirmedGrossMinor: dollarsToMinor(2450),
    currency: 'USD',
    offerStatus: 'accepted',
    operationalStatus: 'complete',
    rateConfirmationStatus: 'details_reviewed',
    rateDetailsReviewed: true,
    podDocumentId: 'vdoc-e-pod',
    factoringHandoffStatus: 'ready',
    accessorials: [],
    rateRevisions: [],
    timeline: timeline('load-e-complete', [
      { label: 'Load complete', operationalStatus: 'complete', visibility: 'customer', createdAt: daysAgo(6) },
    ]),
    createdAt: daysAgo(10),
    updatedAt: daysAgo(6),
    version: 1,
  };

  const dispatchBillingConfigs: DispatchBillingConfig[] = [
    {
      organizationId: 'client-a',
      billingMode: 'percentage',
      billingRateBasisPoints: 800,
      commissionableComponents: ['linehaul', 'fuel_surcharge'],
      active: true,
    },
    {
      organizationId: 'client-b',
      billingMode: 'percentage',
      billingRateBasisPoints: 750,
      commissionableComponents: ['linehaul'],
      active: true,
    },
    {
      organizationId: 'client-c',
      billingMode: 'flat_per_load',
      flatPerLoadMinor: dollarsToMinor(75),
      commissionableComponents: ['linehaul'],
      active: true,
    },
    {
      organizationId: 'client-d',
      billingMode: 'percentage',
      billingRateBasisPoints: 800,
      commissionableComponents: ['linehaul', 'fuel_surcharge'],
      active: true,
    },
  ];

  return {
    enrollments,
    truckProfiles,
    loads: [loadOfferA, loadBActive, loadDPod, loadCTransit, loadComplete, loadBComplete, loadEComplete],
    brokerContacts: brokers,
    dispatchBillingConfigs,
    dispatchCounters: { load: 7 },
  };
}
