/**
 * AI Media workspace — Labs demo seeds & bootstrap.
 * First workspace powered by Studio OS Labs.
 */

import type { Experiment, LabsStore } from '../../../studio-os-core/labs/types';
import { readLabsStore, mergeLabsStorePatch, syncLabsIntelligence } from '../../../studio-os-core/labs/store';

const AI_MEDIA_WS = 'ai-media';

function demoExperiment(
  partial: Omit<Experiment, 'knowledgeGraphNodeId' | 'createdAt' | 'updatedAt' | 'workspaceId'> & { id: string }
): Experiment {
  const now = '2026-06-28T18:00:00.000Z';
  return {
    ...partial,
    workspaceId: AI_MEDIA_WS,
    knowledgeGraphNodeId: `node-experiment-${partial.id}`,
    createdAt: now,
    updatedAt: now,
  };
}

export const AI_MEDIA_DEMO_EXPERIMENTS: Experiment[] = [
  demoExperiment({
    id: 'exp-ai-money-myth-01',
    status: 'completed',
    variables: {
      topic: 'Credit score myths debunked',
      pillar: 'money',
      series: 'CREDIT SECRETS',
      campaign: 'Q2 Finance Push',
      workspace: AI_MEDIA_WS,
      publishingPlatform: 'tiktok',
      publishDate: '2026-06-15',
      publishTime: '18:30',
      hook: 'Did you know this credit myth is costing you money?',
      openingLine: 'Most people believe this — but banks don\'t want you to know.',
      script: '30s myth-bust script with 3 facts',
      storyboard: 'talking-head + text overlay',
      voice: 'voice-b',
      thumbnail: 'red-text-shocked-face',
      caption: 'Stop believing this credit myth 👇\n\nWhich myth surprised you most?',
      hashtags: ['#creditscore', '#personalfinance', '#moneymyths'],
      cta: 'Link in bio for free credit checklist',
      music: 'trending-upbeat-128',
      videoDurationSec: 38,
      animationStyle: 'kinetic-text',
      editingStyle: 'fast-cut',
      aiModelsUsed: ['gpt-4o', 'elevenlabs-v2'],
      promptVersions: ['hook-v3', 'script-v2'],
      creativeDnaVersion: 'v1.2',
      writingBibleVersion: 'v1.1',
      companyDnaVersion: 'v1.0',
    },
    metrics: {
      views: 84200,
      watchTimeSec: 2526000,
      averageViewDurationSec: 30,
      completionRate: 0.79,
      rewatches: 4200,
      likes: 6800,
      shares: 920,
      comments: 1100,
      saves: 3400,
      follows: 890,
      profileVisits: 2100,
      websiteClicks: 480,
      emailSignups: 62,
      affiliateClicks: 340,
      sales: 28,
      revenue: 412.5,
      platformRpm: 4.9,
      platformCpm: 8.2,
      platformCpc: 0.86,
      engagementRate: 0.12,
      conversionRate: 0.058,
      returnViewers: 1200,
      retentionCurve: [1, 0.92, 0.85, 0.78, 0.72, 0.65],
      audienceDemographics: '25–34 · US 68%',
      trafficSources: 'FYP 72% · Search 18%',
      collectedAt: '2026-06-22T12:00:00.000Z',
    },
    thumbnailIntel: {
      composition: 'face-left-text-right',
      colors: ['#FF0000', '#FFFFFF', '#000000'],
      textPlacement: 'top-third',
      subjectPlacement: 'center-left',
      cameraFraming: 'medium-close',
      emotion: 'shocked',
      contrast: 'high',
      ctr: 0.082,
    },
    completedAt: '2026-06-22T12:00:00.000Z',
  }),
  demoExperiment({
    id: 'exp-ai-health-myth-02',
    status: 'completed',
    variables: {
      topic: 'Sleep supplement truth',
      pillar: 'health',
      series: 'HEALTH MYTHS',
      campaign: 'Wellness Week',
      workspace: AI_MEDIA_WS,
      publishingPlatform: 'instagram-reels',
      publishDate: '2026-06-18',
      publishTime: '19:00',
      hook: 'This sleep hack is actually making you tired.',
      openingLine: 'Doctors see this mistake every week.',
      script: '35s health myth breakdown',
      storyboard: 'b-roll + captions',
      voice: 'voice-a',
      thumbnail: 'white-text-calm-face',
      caption: 'Your sleep routine might be wrong 😴\n\nSave this for tonight.',
      hashtags: ['#sleephacks', '#healthmyths', '#wellness'],
      cta: 'Free sleep guide — link in bio',
      music: 'ambient-soft-90',
      videoDurationSec: 42,
      animationStyle: 'minimal',
      editingStyle: 'smooth-transitions',
      aiModelsUsed: ['gpt-4o', 'runway-gen3'],
      promptVersions: ['hook-v2', 'script-v3'],
      creativeDnaVersion: 'v1.2',
      writingBibleVersion: 'v1.1',
      companyDnaVersion: 'v1.0',
    },
    metrics: {
      views: 52100,
      watchTimeSec: 1875600,
      averageViewDurationSec: 36,
      completionRate: 0.86,
      rewatches: 3100,
      likes: 4200,
      shares: 680,
      comments: 890,
      saves: 5200,
      follows: 620,
      profileVisits: 1400,
      websiteClicks: 210,
      emailSignups: 45,
      affiliateClicks: 180,
      sales: 12,
      revenue: 186.0,
      platformRpm: 3.6,
      platformCpm: 6.1,
      platformCpc: 0.72,
      engagementRate: 0.15,
      conversionRate: 0.032,
      returnViewers: 980,
      retentionCurve: [1, 0.95, 0.88, 0.82, 0.78, 0.74],
      audienceDemographics: '28–44 · US 55%',
      trafficSources: 'Reels tab 65% · Profile 22%',
      collectedAt: '2026-06-25T10:00:00.000Z',
    },
    thumbnailIntel: {
      composition: 'centered-face',
      colors: ['#FFFFFF', '#4A90D9'],
      textPlacement: 'bottom-third',
      subjectPlacement: 'center',
      cameraFraming: 'close-up',
      emotion: 'calm',
      contrast: 'medium',
      ctr: 0.061,
    },
    completedAt: '2026-06-25T10:00:00.000Z',
  }),
  demoExperiment({
    id: 'exp-ai-psychology-03',
    status: 'collecting',
    variables: {
      topic: 'Why your brain ignores good advice',
      pillar: 'psychology',
      series: 'PSYCHOLOGY FACTS',
      campaign: 'Mind Hacks',
      workspace: AI_MEDIA_WS,
      publishingPlatform: 'youtube-shorts',
      publishDate: '2026-07-01',
      publishTime: '17:00',
      hook: 'Your brain is wired to ignore this type of advice.',
      openingLine: 'Neuroscience explains why motivation fails.',
      script: '40s psychology fact',
      storyboard: 'split-screen brain graphics',
      voice: 'voice-b',
      thumbnail: 'brain-diagram-red-accent',
      caption: 'The psychology behind self-sabotage 🧠',
      hashtags: ['#psychology', '#mindhacks', '#brainscience'],
      cta: 'Subscribe for weekly mind facts',
      music: 'cinematic-tension-100',
      videoDurationSec: 44,
      animationStyle: 'motion-graphics',
      editingStyle: 'documentary',
      aiModelsUsed: ['gpt-4o', 'midjourney-v6'],
      promptVersions: ['hook-v4'],
      creativeDnaVersion: 'v1.2',
      writingBibleVersion: 'v1.1',
      companyDnaVersion: 'v1.0',
    },
    metrics: {
      views: 12800,
      watchTimeSec: 409600,
      averageViewDurationSec: 32,
      completionRate: 0.73,
      rewatches: 890,
      likes: 1100,
      shares: 220,
      comments: 340,
      saves: 780,
      follows: 210,
      profileVisits: 520,
      websiteClicks: 85,
      emailSignups: 18,
      affiliateClicks: 42,
      sales: 3,
      revenue: 54.0,
      platformRpm: 4.2,
      platformCpm: 7.0,
      platformCpc: 0.0,
      engagementRate: 0.11,
      conversionRate: 0.021,
      returnViewers: 340,
      retentionCurve: [1, 0.9, 0.82, 0.75, 0.68],
      audienceDemographics: '18–34 · Global',
      trafficSources: 'Shorts feed 80%',
      collectedAt: '2026-07-03T08:00:00.000Z',
    },
    thumbnailIntel: {
      composition: 'diagram-overlay',
      colors: ['#FF0000', '#1A1A2E'],
      textPlacement: 'center',
      subjectPlacement: 'background',
      cameraFraming: 'wide',
      emotion: 'curious',
      contrast: 'high',
      ctr: 0.071,
    },
  }),
  demoExperiment({
    id: 'exp-ai-tools-04',
    status: 'active',
    variables: {
      topic: 'AI tool that edits videos in 60 seconds',
      pillar: 'ai',
      series: 'AI TOOLS',
      campaign: 'Creator Stack',
      workspace: AI_MEDIA_WS,
      publishingPlatform: 'tiktok',
      publishDate: '2026-07-03',
      publishTime: '12:00',
      hook: 'This AI tool replaced my entire editing workflow.',
      openingLine: 'I tested 12 tools — this one won.',
      script: '45s tool demo',
      storyboard: 'screen-recording + face cam',
      voice: 'voice-a',
      thumbnail: 'split-screen-before-after',
      caption: 'Save hours every week with this AI editor ⚡',
      hashtags: ['#aitools', '#contentcreator', '#videoediting'],
      cta: 'Affiliate link in bio',
      music: 'tech-beats-120',
      videoDurationSec: 45,
      animationStyle: 'screen-capture',
      editingStyle: 'demo-walkthrough',
      aiModelsUsed: ['gpt-4o', 'claude-3.5'],
      promptVersions: ['script-v4'],
      creativeDnaVersion: 'v1.2',
      writingBibleVersion: 'v1.1',
      companyDnaVersion: 'v1.0',
    },
    metrics: {
      views: 3200,
      watchTimeSec: 96000,
      averageViewDurationSec: 30,
      completionRate: 0.67,
      rewatches: 180,
      likes: 280,
      shares: 95,
      comments: 62,
      saves: 410,
      follows: 88,
      profileVisits: 190,
      websiteClicks: 120,
      emailSignups: 8,
      affiliateClicks: 95,
      sales: 6,
      revenue: 89.4,
      platformRpm: 5.1,
      platformCpm: 0,
      platformCpc: 1.2,
      engagementRate: 0.09,
      conversionRate: 0.063,
      returnViewers: 45,
      retentionCurve: [1, 0.88, 0.75, 0.67],
      audienceDemographics: '22–35 · Creator niche',
      trafficSources: 'FYP 85%',
      collectedAt: '2026-07-04T06:00:00.000Z',
    },
    thumbnailIntel: {
      composition: 'split-screen',
      colors: ['#00FF88', '#000000'],
      textPlacement: 'top-half',
      subjectPlacement: 'dual',
      cameraFraming: 'screen-recording',
      emotion: 'excited',
      contrast: 'high',
      ctr: 0.095,
    },
  }),
  demoExperiment({
    id: 'exp-ai-money-myth-05',
    status: 'completed',
    variables: {
      topic: 'Debt avalanche vs snowball — which wins?',
      pillar: 'money',
      series: 'MONEY MYTHS',
      campaign: 'Q2 Finance Push',
      workspace: AI_MEDIA_WS,
      publishingPlatform: 'youtube-shorts',
      publishDate: '2026-06-20',
      publishTime: '18:00',
      hook: 'Which debt payoff method actually saves more money?',
      openingLine: 'The math might surprise you.',
      script: '32s comparison',
      storyboard: 'chart animation',
      voice: 'voice-b',
      thumbnail: 'chart-red-vs-green',
      caption: 'Avalanche or snowball? Comment your pick 💬',
      hashtags: ['#debtfree', '#moneymyths', '#financialliteracy'],
      cta: 'Debt calculator — link in bio',
      music: 'corporate-upbeat-110',
      videoDurationSec: 32,
      animationStyle: 'chart-motion',
      editingStyle: 'data-driven',
      aiModelsUsed: ['gpt-4o'],
      promptVersions: ['hook-v3'],
      creativeDnaVersion: 'v1.2',
      writingBibleVersion: 'v1.1',
      companyDnaVersion: 'v1.0',
    },
    metrics: {
      views: 67400,
      watchTimeSec: 2022000,
      averageViewDurationSec: 30,
      completionRate: 0.81,
      rewatches: 2800,
      likes: 5400,
      shares: 1100,
      comments: 2400,
      saves: 2900,
      follows: 720,
      profileVisits: 1800,
      websiteClicks: 390,
      emailSignups: 55,
      affiliateClicks: 280,
      sales: 22,
      revenue: 328.0,
      platformRpm: 4.87,
      platformCpm: 7.8,
      platformCpc: 0.84,
      engagementRate: 0.14,
      conversionRate: 0.051,
      returnViewers: 890,
      retentionCurve: [1, 0.93, 0.86, 0.8, 0.74],
      audienceDemographics: '25–40 · US 62%',
      trafficSources: 'Shorts 78% · Suggested 15%',
      collectedAt: '2026-06-24T14:00:00.000Z',
    },
    thumbnailIntel: {
      composition: 'chart-center',
      colors: ['#FF0000', '#00AA44'],
      textPlacement: 'top',
      subjectPlacement: 'data-viz',
      cameraFraming: 'graphic',
      emotion: 'analytical',
      contrast: 'high',
      ctr: 0.078,
    },
    completedAt: '2026-06-24T14:00:00.000Z',
  }),
];

export function buildAiMediaLabsStorePatch(): Partial<LabsStore> {
  return {
    experiments: AI_MEDIA_DEMO_EXPERIMENTS,
    institutionalMemory: [
      'Finance content consistently produces the highest affiliate revenue.',
      'Psychology videos achieve the highest average retention.',
      'Voice B converts better than Voice A on money pillar content.',
      'Red text thumbnails outperform white text on finance hooks.',
    ],
  };
}

export function bootstrapAiMediaLabs(): void {
  const store = readLabsStore();
  if (store.experiments.some((e) => e.workspaceId === AI_MEDIA_WS)) {
    syncLabsIntelligence(AI_MEDIA_WS);
    return;
  }
  mergeLabsStorePatch(buildAiMediaLabsStorePatch());
  syncLabsIntelligence(AI_MEDIA_WS);
}
