import { PRODUCTION_STAGES } from '../../ndxbook/mission-control/constants';
import type { NdxbookMissionControlStore } from '../../ndxbook/mission-control/types';

/** Clean mission control seed — zero fabricated history (Founder Pilot Mode). */
export function buildPilotMissionControlSeed(): Partial<NdxbookMissionControlStore> {
  const launchAt = new Date(Date.now() + 86400_000).toISOString();

  return {
    briefing: {
      greeting: 'welcome to ndxbook',
      pagesPublishingToday: 0,
      pagesInProduction: 0,
      pendingApprovals: 0,
      estimatedReachToday: 0,
      estimatedRevenueToday: 0,
      highestPerformingPage: '—',
      highestPerformingVolume: '—',
      highestPerformingHost: '—',
      studioRecommendation: 'learning — publish 5 posts to unlock basic recommendations',
      topOpportunity: 'connect instagram & create page 001',
      topRisk: '—',
      nextSuggestedAction: 'connect instagram · create page 001 · schedule your first post',
    },
    companyHealth: [
      { id: 'overall', label: 'ORGANIZATION MATURITY', score: 0, trend: 'flat', trendLabel: 'Day one — history begins now' },
      { id: 'publishing', label: 'PAGES PUBLISHED', score: 0, trend: 'flat', trendLabel: '0 pages live' },
      { id: 'growth', label: 'FOLLOWERS', score: 0, trend: 'flat', trendLabel: '0 followers' },
      { id: 'knowledge', label: 'KNOWLEDGE ASSETS', score: 0, trend: 'flat', trendLabel: '0 assets' },
      { id: 'revenue', label: 'REVENUE', score: 0, trend: 'flat', trendLabel: '$0 earned' },
    ],
    newsroomStages: PRODUCTION_STAGES.map((stage) => ({
      id: stage.id,
      label: stage.label,
      pageCount: 0,
      activeItems: 0,
      estimatedCompletionMins: 0,
      assignedExecutive: 'Awaiting first page',
    })),
    publishingSchedule: [],
    pageOfTheDay: {
      pageNumber: 1,
      pageLabel: 'page 001',
      title: 'Create your first knowledge asset',
      volumeId: 'money',
      chapter: '—',
      hostName: 'Unassigned',
      thumbnailNote: 'Awaiting first page creation',
      platforms: ['instagram'],
      status: 'not started',
      predictedPerformance: '—',
      launchAt,
    },
    library: {
      latestPages: [],
      recentlyUpdated: [],
      mostBookmarked: [],
      highestShared: [],
      highestRetention: [],
      recentCollections: [],
    },
    volumes: [],
    chaptersByVolume: {},
    readerIntelligence: {
      newReaders: 0,
      returningReaders: 0,
      retentionPct: 0,
      bookmarks: 0,
      shares: 0,
      comments: 0,
      watchTimeHours: 0,
      avgCompletionPct: 0,
      bestPublishingHour: '—',
      topCountries: [],
      topAgeGroups: [],
      topInterests: [],
    },
    intelligence: [],
    revenue: {
      today: 0,
      yesterday: 0,
      changeVsYesterdayPct: 0,
      topChannel: 'instagram',
      projectedEndOfDay: 0,
      thisWeek: 0,
      thisMonth: 0,
      thisYear: 0,
      breakdown: {
        youtube: 0,
        instagram: 0,
        tiktok: 0,
        facebook: 0,
        affiliate: 0,
        brandPartnerships: 0,
        marketplace: 0,
        digitalProducts: 0,
        futureMemberships: 0,
      },
      forecastNextMonth: 0,
      forecastConfidencePct: 0,
    },
    experiments: [],
    talentBoard: [],
    missionActions: [
      { id: 'create-page', label: 'CREATE PAGE 001', route: '/admin/studio/ndxbook?tab=pages', priority: 1, frequencyScore: 100 },
      { id: 'connect-ig', label: 'CONNECT INSTAGRAM', route: '/admin/studio/ndxbook?tab=socials', priority: 1, frequencyScore: 99 },
      { id: 'publish', label: 'PUBLISH FIRST POST', route: '/admin/studio/distribution-network?brand=ndxbook', priority: 2, frequencyScore: 98 },
      { id: 'intelligence', label: 'STUDIO INTELLIGENCE', route: '/admin/studio/studio-intelligence', priority: 3, frequencyScore: 50 },
      { id: 'knowledge-graph', label: 'KNOWLEDGE GRAPH', route: '/admin/studio/knowledge-hub', priority: 4, frequencyScore: 40 },
    ],
    activityFeed: [
      {
        id: 'pilot-org-created',
        timestamp: new Date().toISOString(),
        message: 'NDXBOOK founder pilot mode activated — organization begins at zero',
        category: 'production',
      },
    ],
  };
}
