import type { ExpertCaptureQuestion } from '../types';

export const ALL_IN_ONE_PERMITTING_ROUTE = '/expert-capture/all-in-one-permitting';
export const ALL_IN_ONE_PERMITTING_SESSION_KEY = 'studioExpertCaptureSession_allInOnePermitting_v1';

export const ALL_IN_ONE_PERMITTING_QUESTIONS: ExpertCaptureQuestion[] = [
  {
    id: 'p-business',
    text: 'Give me an overview of All In One — what permitting services do you offer, and who are your typical clients?',
    category: 'Business Overview',
    order: 0,
    optional: false,
  },
  {
    id: 'p-first-client',
    text: 'Walk me through your first interaction with a new client — from initial contact through understanding what they need.',
    category: 'Customer Intake',
    order: 1,
    optional: false,
  },
  {
    id: 'p-determine-permits',
    text: 'How do you know which permits are required for a project? Walk me through your decision process.',
    category: 'Permit Types',
    order: 2,
    optional: false,
  },
  {
    id: 'p-first-info',
    text: 'What information do you request first from a client or contractor before you can start a permit?',
    category: 'Required Documentation',
    order: 3,
    optional: false,
  },
  {
    id: 'p-jurisdictions',
    text: 'What cities, counties, and states does All In One serve — and how do you track jurisdiction-specific requirements?',
    category: 'Jurisdictions',
    order: 4,
    optional: false,
  },
  {
    id: 'p-submission',
    text: 'Walk me through the permit submission process from package preparation to municipality acceptance.',
    category: 'Permit Submission Process',
    order: 5,
    optional: false,
  },
  {
    id: 'p-docs',
    text: 'What documentation is typically required in a permit package — and how do you know when something is missing?',
    category: 'Required Documentation',
    order: 6,
    optional: false,
  },
  {
    id: 'p-inspections',
    text: 'When and how do you schedule inspections — and when do you contact inspectors directly?',
    category: 'Inspection Scheduling',
    order: 7,
    optional: false,
  },
  {
    id: 'p-revisions',
    text: 'How do you handle permit revisions — from identifying the need through resubmission?',
    category: 'Revisions',
    order: 8,
    optional: false,
  },
  {
    id: 'p-rejected',
    text: 'What happens when a permit is rejected — how do you diagnose the problem and get it back on track?',
    category: 'Rejected Permits',
    order: 9,
    optional: false,
  },
  {
    id: 'p-expediting',
    text: 'When do clients need expedited permits — and how does your expediting process work?',
    category: 'Permit Expediting',
    order: 10,
    optional: false,
  },
  {
    id: 'p-contractors',
    text: 'How do you coordinate with contractors during the permitting process?',
    category: 'Contractor Coordination',
    order: 11,
    optional: false,
  },
  {
    id: 'p-design',
    text: 'How do you work with architects and engineers when their documents are part of the permit package?',
    category: 'Design Coordination',
    order: 12,
    optional: false,
  },
  {
    id: 'p-municipality',
    text: 'How do you communicate with municipalities — building departments, plan reviewers, and inspectors?',
    category: 'Municipality Communication',
    order: 13,
    optional: false,
  },
  {
    id: 'p-fees',
    text: 'How does fee collection work — who pays, when, and how do you track it?',
    category: 'Fee Collection',
    order: 14,
    optional: false,
  },
  {
    id: 'p-organization',
    text: 'How is All In One organized internally — roles, handoffs, and how dozens of active permits stay organized?',
    category: 'Internal Organization',
    order: 15,
    optional: false,
  },
  {
    id: 'p-software',
    text: 'What software and document storage systems do you use — and what naming conventions do you follow?',
    category: 'Software & Storage',
    order: 16,
    optional: false,
  },
  {
    id: 'p-time-pricing',
    text: 'How do you estimate timelines and make pricing decisions for permit work?',
    category: 'Time & Pricing',
    order: 17,
    optional: false,
  },
  {
    id: 'p-customer-updates',
    text: 'How do you keep customers updated throughout the permit process — especially when things go wrong or slow down?',
    category: 'Customer Updates',
    order: 18,
    optional: false,
  },
  {
    id: 'p-city-diff',
    text: 'How do different cities and municipalities differ in their requirements and processes?',
    category: 'Municipality Differences',
    order: 19,
    optional: false,
  },
  {
    id: 'p-qa',
    text: 'What quality checks do you always perform before submitting a permit package?',
    category: 'Quality Assurance',
    order: 20,
    optional: false,
  },
  {
    id: 'p-exceptions',
    text: 'What exception handling rules do you follow — when something falls outside the normal workflow?',
    category: 'Exception Handling',
    order: 21,
    optional: false,
  },
  {
    id: 'p-mistakes',
    text: 'What mistakes do homeowners and inexperienced permit coordinators usually make?',
    category: 'Common Mistakes',
    order: 22,
    optional: false,
  },
  {
    id: 'p-delays',
    text: 'What typically slows permits down — and how do you prevent or recover from delays?',
    category: 'Common Failures',
    order: 23,
    optional: false,
  },
  {
    id: 'p-escalation',
    text: 'What situations require escalation — and who gets involved at each level?',
    category: 'Escalation Rules',
    order: 24,
    optional: false,
  },
  {
    id: 'p-prioritize',
    text: 'How do you prioritize your workload when multiple permits need attention at once?',
    category: 'Professional Judgment',
    order: 25,
    optional: false,
  },
  {
    id: 'p-never-delegate',
    text: 'What would you never delegate to someone without deep permitting experience?',
    category: 'Professional Judgment',
    order: 26,
    optional: false,
  },
  {
    id: 'p-lessons',
    text: 'What has experience taught you that is not written in any code book or municipality guide?',
    category: 'Lessons Learned',
    order: 27,
    optional: false,
  },
  {
    id: 'p-never-do',
    text: 'What are the things you would never do in permitting work — the hard lines?',
    category: 'Things Never To Do',
    order: 28,
    optional: false,
  },
];

export const ALL_IN_ONE_PERMITTING_FUTURE_PLACEHOLDERS = [
  'Permit Knowledge Graph',
  'Jurisdiction Database',
  'Inspection Timeline Generator',
  'Permit Status Tracker',
  'Municipality Intelligence',
  'Studio Permit Worker',
  'Scenario Testing',
  'Certification',
  'Competency Testing',
  'Worker Graduation',
  'Multi-Expert Knowledge Merging',
  'Studio HR',
  'Studio Institute',
] as const;
