import type { KnowledgeIndustryUpdate, KnowledgeRetentionProfile } from './types';

const learned = '2026-01-01T09:00:00.000Z';

export const LAUNCH_RETENTION_PROFILES: KnowledgeRetentionProfile[] = [
  {
    id: 'memory-hair-bleaching-chemistry',
    brainId: 'hair-color',
    conceptTitle: 'Hair bleaching chemistry',
    domain: 'chemistry',
    learnedAt: learned,
    successfulApplications: 18,
    lastRealUsageAt: '2026-06-18T14:00:00.000Z',
    confidenceScore: 84,
    recallStrength: 79,
    industryUpdateCount: 1,
    certificationRelevance: 92,
    difficulty: 'advanced',
    careerGoalIds: ['licensed-colorist', 'corrective-color-specialist'],
    upcomingSimulationIds: ['sim-corrective-color-consult'],
    upcomingProjectIds: ['client-color-correction-week'],
  },
  {
    id: 'memory-color-theory',
    brainId: 'hair-color',
    conceptTitle: 'Color theory',
    domain: 'color-theory',
    learnedAt: learned,
    successfulApplications: 42,
    lastRealUsageAt: '2026-07-01T11:30:00.000Z',
    confidenceScore: 91,
    recallStrength: 88,
    industryUpdateCount: 0,
    certificationRelevance: 77,
    difficulty: 'intermediate',
    careerGoalIds: ['licensed-colorist'],
    upcomingSimulationIds: [],
    upcomingProjectIds: ['summer-shade-consultations'],
  },
  {
    id: 'memory-lace-installation',
    brainId: 'hair-analysis',
    conceptTitle: 'Lace installation',
    domain: 'installation',
    learnedAt: learned,
    successfulApplications: 25,
    lastRealUsageAt: '2026-05-20T16:45:00.000Z',
    confidenceScore: 76,
    recallStrength: 68,
    industryUpdateCount: 0,
    certificationRelevance: 61,
    difficulty: 'intermediate',
    careerGoalIds: ['luxury-install-specialist'],
    upcomingSimulationIds: ['sim-lace-customization-client'],
    upcomingProjectIds: ['bridal-install-series'],
  },
  {
    id: 'memory-client-consultations',
    brainId: 'customer-experience',
    conceptTitle: 'Client consultations',
    domain: 'consultation',
    learnedAt: learned,
    successfulApplications: 64,
    lastRealUsageAt: '2026-07-07T10:15:00.000Z',
    confidenceScore: 93,
    recallStrength: 90,
    industryUpdateCount: 0,
    certificationRelevance: 52,
    difficulty: 'foundational',
    careerGoalIds: ['premium-client-experience'],
    upcomingSimulationIds: ['sim-sensitive-client-consult'],
    upcomingProjectIds: ['vip-consult-block'],
  },
  {
    id: 'memory-corrective-color',
    brainId: 'hair-color',
    conceptTitle: 'Corrective color',
    domain: 'technical-skill',
    learnedAt: learned,
    successfulApplications: 9,
    lastRealUsageAt: '2025-12-06T13:20:00.000Z',
    confidenceScore: 67,
    recallStrength: 54,
    industryUpdateCount: 1,
    certificationRelevance: 88,
    difficulty: 'expert',
    careerGoalIds: ['corrective-color-specialist'],
    upcomingSimulationIds: ['sim-corrective-color-consult'],
    upcomingProjectIds: ['high-risk-color-calendar'],
  },
  {
    id: 'memory-salon-management',
    brainId: 'customer-experience',
    conceptTitle: 'Salon management',
    domain: 'operations',
    learnedAt: learned,
    successfulApplications: 13,
    lastRealUsageAt: '2026-04-12T09:00:00.000Z',
    confidenceScore: 72,
    recallStrength: 65,
    industryUpdateCount: 0,
    certificationRelevance: 45,
    difficulty: 'advanced',
    careerGoalIds: ['studio-owner'],
    upcomingSimulationIds: ['sim-staffing-salon-day'],
    upcomingProjectIds: ['operations-playbook'],
  },
  {
    id: 'memory-marketing-strategy',
    brainId: 'marketing',
    conceptTitle: 'Marketing strategy',
    domain: 'marketing',
    learnedAt: learned,
    successfulApplications: 21,
    lastRealUsageAt: '2026-06-09T12:00:00.000Z',
    confidenceScore: 81,
    recallStrength: 74,
    industryUpdateCount: 2,
    certificationRelevance: 36,
    difficulty: 'intermediate',
    careerGoalIds: ['beauty-brand-builder'],
    upcomingSimulationIds: ['sim-launch-campaign'],
    upcomingProjectIds: ['fall-campaign'],
  },
  {
    id: 'memory-accounting',
    brainId: 'bookkeeping',
    conceptTitle: 'Accounting',
    domain: 'finance',
    learnedAt: learned,
    successfulApplications: 7,
    lastRealUsageAt: '2026-03-02T15:00:00.000Z',
    confidenceScore: 62,
    recallStrength: 57,
    industryUpdateCount: 1,
    certificationRelevance: 70,
    difficulty: 'advanced',
    careerGoalIds: ['profitable-studio-owner'],
    upcomingSimulationIds: ['sim-month-end-close'],
    upcomingProjectIds: ['quarterly-finance-review'],
  },
  {
    id: 'memory-leadership',
    brainId: 'customer-experience',
    conceptTitle: 'Leadership',
    domain: 'leadership',
    learnedAt: learned,
    successfulApplications: 16,
    lastRealUsageAt: '2026-06-25T08:30:00.000Z',
    confidenceScore: 78,
    recallStrength: 72,
    industryUpdateCount: 0,
    certificationRelevance: 40,
    difficulty: 'advanced',
    careerGoalIds: ['team-lead'],
    upcomingSimulationIds: ['sim-team-conflict'],
    upcomingProjectIds: ['assistant-stylist-training'],
  },
];

export const LAUNCH_INDUSTRY_UPDATES: KnowledgeIndustryUpdate[] = [
  {
    id: 'update-bleaching-bond-integrity-standard',
    conceptId: 'memory-hair-bleaching-chemistry',
    title: 'Bleaching standard now emphasizes bond integrity documentation',
    changedAt: '2026-07-08T09:00:00.000Z',
    summary: 'Record hair history, strand-test outcome, and bond-support plan before high-lift services.',
    whyItChanged: 'New professional guidance prioritizes damage prevention and informed consent.',
    workImpact: 'Consultations should include a clearer risk explanation before bleach processing.',
    severity: 'certification',
  },
  {
    id: 'update-short-form-local-campaign-shift',
    conceptId: 'memory-marketing-strategy',
    title: 'Local beauty marketing shifted toward short-form proof content',
    changedAt: '2026-07-06T09:00:00.000Z',
    summary: 'Campaigns perform better when they show transformation evidence quickly.',
    whyItChanged: 'Audience trust is moving toward proof, behind-the-scenes process, and visible expertise.',
    workImpact: 'Marketing refreshers should connect offer strategy to before/after client narratives.',
    severity: 'moderate',
  },
];

export function listRetentionProfiles(): KnowledgeRetentionProfile[] {
  return LAUNCH_RETENTION_PROFILES;
}

export function listIndustryUpdates(): KnowledgeIndustryUpdate[] {
  return LAUNCH_INDUSTRY_UPDATES;
}
