/** AUTO-GENERATED by scripts/ingest-season1-visual-authority-package.mjs — do not hand-edit */
import type { ResidentId } from '../types';

export type Season1PackageAssetStatus =
  | 'FOUNDER_APPROVED'
  | 'FOUNDER_APPROVED_REFERENCE'
  | 'REFERENCE_ONLY'
  | 'CONCEPT_REFERENCE_ONLY'
  | 'ALTERNATE_MODE_REFERENCE';

export type Season1IngestedVisualAsset = {
  assetId: string;
  residentId: ResidentId;
  residentName: string;
  publicPath: string;
  repoPath: string;
  sourceFilename: string;
  organizedPath: string;
  packageStatus: Season1PackageAssetStatus;
  category: 'natural-authority' | 'closeups' | 'work-uniform-candidates' | 'alternate-modes' | 'other';
  sourcePackage: 'STUDIO_WORLD_SEASON1_VISUAL_AUTHORITY_CURSOR_LIGHT_v1';
};

export const SEASON1_INGESTED_VISUAL_ASSETS: Season1IngestedVisualAsset[] = [
  {
    "assetId": "swa:SW-RESIDENT-001:natural-authority:sw-resident-001-etta-vale-natural-fullbody-01.jpg",
    "residentId": "SW-RESIDENT-001",
    "residentName": "Etta Vale",
    "publicPath": "/studio-world/residents/season-1/sw-resident-001-etta-vale/natural-authority/sw-resident-001-etta-vale-natural-fullbody-01.jpg",
    "repoPath": "public/studio-world/residents/season-1/sw-resident-001-etta-vale/natural-authority/sw-resident-001-etta-vale-natural-fullbody-01.jpg",
    "sourceFilename": "D3BE948B-1E6B-480B-8253-337AA7BAB250.png",
    "organizedPath": "SW-RESIDENT-001__etta-vale/01-natural-authority/etta-vale__natural-full-body__sophisticated-fashionista.jpg",
    "packageStatus": "FOUNDER_APPROVED",
    "category": "natural-authority",
    "sourcePackage": "STUDIO_WORLD_SEASON1_VISUAL_AUTHORITY_CURSOR_LIGHT_v1"
  },
  {
    "assetId": "swa:SW-RESIDENT-001:closeups:sw-resident-001-etta-vale-closeup-01.jpg",
    "residentId": "SW-RESIDENT-001",
    "residentName": "Etta Vale",
    "publicPath": "/studio-world/residents/season-1/sw-resident-001-etta-vale/closeups/sw-resident-001-etta-vale-closeup-01.jpg",
    "repoPath": "public/studio-world/residents/season-1/sw-resident-001-etta-vale/closeups/sw-resident-001-etta-vale-closeup-01.jpg",
    "sourceFilename": "2796CA93-AB24-43D1-90A3-1C3D7C81B016.png",
    "organizedPath": "SW-RESIDENT-001__etta-vale/02-closeups/etta-vale__closeup__sophisticated-fashionista.jpg",
    "packageStatus": "FOUNDER_APPROVED_REFERENCE",
    "category": "closeups",
    "sourcePackage": "STUDIO_WORLD_SEASON1_VISUAL_AUTHORITY_CURSOR_LIGHT_v1"
  },
  {
    "assetId": "swa:SW-RESIDENT-001:work-uniform-candidates:sw-resident-001-etta-vale-work-uniform-candidate-01.jpg",
    "residentId": "SW-RESIDENT-001",
    "residentName": "Etta Vale",
    "publicPath": "/studio-world/residents/season-1/sw-resident-001-etta-vale/work-uniform-candidates/sw-resident-001-etta-vale-work-uniform-candidate-01.jpg",
    "repoPath": "public/studio-world/residents/season-1/sw-resident-001-etta-vale/work-uniform-candidates/sw-resident-001-etta-vale-work-uniform-candidate-01.jpg",
    "sourceFilename": "EBFEDC59-7936-4687-9A39-0CA88A848116.png",
    "organizedPath": "SW-RESIDENT-001__etta-vale/03-work-uniform-candidates/etta-vale__shared-uniform-candidate__v1.jpg",
    "packageStatus": "CONCEPT_REFERENCE_ONLY",
    "category": "work-uniform-candidates",
    "sourcePackage": "STUDIO_WORLD_SEASON1_VISUAL_AUTHORITY_CURSOR_LIGHT_v1"
  },
  {
    "assetId": "swa:SW-RESIDENT-002:natural-authority:sw-resident-002-zuri-xu-natural-fullbody-01.jpg",
    "residentId": "SW-RESIDENT-002",
    "residentName": "Zuri Xu",
    "publicPath": "/studio-world/residents/season-1/sw-resident-002-zuri-xu/natural-authority/sw-resident-002-zuri-xu-natural-fullbody-01.jpg",
    "repoPath": "public/studio-world/residents/season-1/sw-resident-002-zuri-xu/natural-authority/sw-resident-002-zuri-xu-natural-fullbody-01.jpg",
    "sourceFilename": "9A349F3E-2D87-4AA9-A066-8884AC5F411F.png",
    "organizedPath": "SW-RESIDENT-002__zuri-xu/01-natural-authority/zuri-xu__natural-full-body__architectural-fashion-strategist.jpg",
    "packageStatus": "FOUNDER_APPROVED",
    "category": "natural-authority",
    "sourcePackage": "STUDIO_WORLD_SEASON1_VISUAL_AUTHORITY_CURSOR_LIGHT_v1"
  },
  {
    "assetId": "swa:SW-RESIDENT-002:closeups:sw-resident-002-zuri-xu-closeup-01.jpg",
    "residentId": "SW-RESIDENT-002",
    "residentName": "Zuri Xu",
    "publicPath": "/studio-world/residents/season-1/sw-resident-002-zuri-xu/closeups/sw-resident-002-zuri-xu-closeup-01.jpg",
    "repoPath": "public/studio-world/residents/season-1/sw-resident-002-zuri-xu/closeups/sw-resident-002-zuri-xu-closeup-01.jpg",
    "sourceFilename": "C541BDC8-F93F-4B0B-AAF7-FF4E0AEDB57B.png",
    "organizedPath": "SW-RESIDENT-002__zuri-xu/02-closeups/zuri-xu__closeup__architectural-fashion-strategist.jpg",
    "packageStatus": "FOUNDER_APPROVED_REFERENCE",
    "category": "closeups",
    "sourcePackage": "STUDIO_WORLD_SEASON1_VISUAL_AUTHORITY_CURSOR_LIGHT_v1"
  },
  {
    "assetId": "swa:SW-RESIDENT-002:work-uniform-candidates:sw-resident-002-zuri-xu-work-uniform-candidate-01.jpg",
    "residentId": "SW-RESIDENT-002",
    "residentName": "Zuri Xu",
    "publicPath": "/studio-world/residents/season-1/sw-resident-002-zuri-xu/work-uniform-candidates/sw-resident-002-zuri-xu-work-uniform-candidate-01.jpg",
    "repoPath": "public/studio-world/residents/season-1/sw-resident-002-zuri-xu/work-uniform-candidates/sw-resident-002-zuri-xu-work-uniform-candidate-01.jpg",
    "sourceFilename": "14182919-EC3B-4EC6-A192-0B55E6E25FE7.png",
    "organizedPath": "SW-RESIDENT-002__zuri-xu/03-work-uniform-candidates/zuri-xu__shared-uniform-candidate__v1.jpg",
    "packageStatus": "CONCEPT_REFERENCE_ONLY",
    "category": "work-uniform-candidates",
    "sourcePackage": "STUDIO_WORLD_SEASON1_VISUAL_AUTHORITY_CURSOR_LIGHT_v1"
  },
  {
    "assetId": "swa:SW-RESIDENT-003:natural-authority:sw-resident-003-jules-mercer-natural-fullbody-01.jpg",
    "residentId": "SW-RESIDENT-003",
    "residentName": "Jules Mercer",
    "publicPath": "/studio-world/residents/season-1/sw-resident-003-jules-mercer/natural-authority/sw-resident-003-jules-mercer-natural-fullbody-01.jpg",
    "repoPath": "public/studio-world/residents/season-1/sw-resident-003-jules-mercer/natural-authority/sw-resident-003-jules-mercer-natural-fullbody-01.jpg",
    "sourceFilename": "IMG_6238.png",
    "organizedPath": "SW-RESIDENT-003__jules-mercer/01-natural-authority/jules-mercer__natural-full-body__relaxed-romantic.jpg",
    "packageStatus": "FOUNDER_APPROVED",
    "category": "natural-authority",
    "sourcePackage": "STUDIO_WORLD_SEASON1_VISUAL_AUTHORITY_CURSOR_LIGHT_v1"
  },
  {
    "assetId": "swa:SW-RESIDENT-003:closeups:sw-resident-003-jules-mercer-closeup-01.jpg",
    "residentId": "SW-RESIDENT-003",
    "residentName": "Jules Mercer",
    "publicPath": "/studio-world/residents/season-1/sw-resident-003-jules-mercer/closeups/sw-resident-003-jules-mercer-closeup-01.jpg",
    "repoPath": "public/studio-world/residents/season-1/sw-resident-003-jules-mercer/closeups/sw-resident-003-jules-mercer-closeup-01.jpg",
    "sourceFilename": "827885CF-0224-4B87-843B-9F4D3D4DC682.png",
    "organizedPath": "SW-RESIDENT-003__jules-mercer/02-closeups/jules-mercer__closeup__relaxed-romantic.jpg",
    "packageStatus": "FOUNDER_APPROVED_REFERENCE",
    "category": "closeups",
    "sourcePackage": "STUDIO_WORLD_SEASON1_VISUAL_AUTHORITY_CURSOR_LIGHT_v1"
  },
  {
    "assetId": "swa:SW-RESIDENT-003:work-uniform-candidates:sw-resident-003-jules-mercer-work-uniform-candidate-01.jpg",
    "residentId": "SW-RESIDENT-003",
    "residentName": "Jules Mercer",
    "publicPath": "/studio-world/residents/season-1/sw-resident-003-jules-mercer/work-uniform-candidates/sw-resident-003-jules-mercer-work-uniform-candidate-01.jpg",
    "repoPath": "public/studio-world/residents/season-1/sw-resident-003-jules-mercer/work-uniform-candidates/sw-resident-003-jules-mercer-work-uniform-candidate-01.jpg",
    "sourceFilename": "39279AB8-B958-4DB6-B89A-8D3248C2326C.png",
    "organizedPath": "SW-RESIDENT-003__jules-mercer/03-work-uniform-candidates/jules-mercer__shared-uniform-candidate__v1.jpg",
    "packageStatus": "CONCEPT_REFERENCE_ONLY",
    "category": "work-uniform-candidates",
    "sourcePackage": "STUDIO_WORLD_SEASON1_VISUAL_AUTHORITY_CURSOR_LIGHT_v1"
  },
  {
    "assetId": "swa:SW-RESIDENT-004:natural-authority:sw-resident-004-noa-kline-natural-fullbody-01.jpg",
    "residentId": "SW-RESIDENT-004",
    "residentName": "Noa Kline",
    "publicPath": "/studio-world/residents/season-1/sw-resident-004-noa-kline/natural-authority/sw-resident-004-noa-kline-natural-fullbody-01.jpg",
    "repoPath": "public/studio-world/residents/season-1/sw-resident-004-noa-kline/natural-authority/sw-resident-004-noa-kline-natural-fullbody-01.jpg",
    "sourceFilename": "8141BEAD-0ABA-401D-8F71-26D1BF1978A4.png",
    "organizedPath": "SW-RESIDENT-004__noa-kline/01-natural-authority/noa-kline__natural-full-body__understated-systems-dad.jpg",
    "packageStatus": "FOUNDER_APPROVED",
    "category": "natural-authority",
    "sourcePackage": "STUDIO_WORLD_SEASON1_VISUAL_AUTHORITY_CURSOR_LIGHT_v1"
  },
  {
    "assetId": "swa:SW-RESIDENT-004:closeups:sw-resident-004-noa-kline-closeup-01.jpg",
    "residentId": "SW-RESIDENT-004",
    "residentName": "Noa Kline",
    "publicPath": "/studio-world/residents/season-1/sw-resident-004-noa-kline/closeups/sw-resident-004-noa-kline-closeup-01.jpg",
    "repoPath": "public/studio-world/residents/season-1/sw-resident-004-noa-kline/closeups/sw-resident-004-noa-kline-closeup-01.jpg",
    "sourceFilename": "41E61B95-7D10-4D20-BD4D-9C23322157A8.png",
    "organizedPath": "SW-RESIDENT-004__noa-kline/02-closeups/noa-kline__closeup-reference__01.jpg",
    "packageStatus": "REFERENCE_ONLY",
    "category": "closeups",
    "sourcePackage": "STUDIO_WORLD_SEASON1_VISUAL_AUTHORITY_CURSOR_LIGHT_v1"
  },
  {
    "assetId": "swa:SW-RESIDENT-004:closeups:sw-resident-004-noa-kline-closeup-02.jpg",
    "residentId": "SW-RESIDENT-004",
    "residentName": "Noa Kline",
    "publicPath": "/studio-world/residents/season-1/sw-resident-004-noa-kline/closeups/sw-resident-004-noa-kline-closeup-02.jpg",
    "repoPath": "public/studio-world/residents/season-1/sw-resident-004-noa-kline/closeups/sw-resident-004-noa-kline-closeup-02.jpg",
    "sourceFilename": "D1E1D42D-D145-4737-AE90-E386CAB8696F.png",
    "organizedPath": "SW-RESIDENT-004__noa-kline/02-closeups/noa-kline__closeup-reference__02.jpg",
    "packageStatus": "REFERENCE_ONLY",
    "category": "closeups",
    "sourcePackage": "STUDIO_WORLD_SEASON1_VISUAL_AUTHORITY_CURSOR_LIGHT_v1"
  },
  {
    "assetId": "swa:SW-RESIDENT-004:closeups:sw-resident-004-noa-kline-closeup-03.jpg",
    "residentId": "SW-RESIDENT-004",
    "residentName": "Noa Kline",
    "publicPath": "/studio-world/residents/season-1/sw-resident-004-noa-kline/closeups/sw-resident-004-noa-kline-closeup-03.jpg",
    "repoPath": "public/studio-world/residents/season-1/sw-resident-004-noa-kline/closeups/sw-resident-004-noa-kline-closeup-03.jpg",
    "sourceFilename": "FEBF8B3E-E978-49CF-BB5D-D92441188E2C.png",
    "organizedPath": "SW-RESIDENT-004__noa-kline/02-closeups/noa-kline__closeup-reference__03.jpg",
    "packageStatus": "REFERENCE_ONLY",
    "category": "closeups",
    "sourcePackage": "STUDIO_WORLD_SEASON1_VISUAL_AUTHORITY_CURSOR_LIGHT_v1"
  },
  {
    "assetId": "swa:SW-RESIDENT-004:work-uniform-candidates:sw-resident-004-noa-kline-work-uniform-candidate-01.jpg",
    "residentId": "SW-RESIDENT-004",
    "residentName": "Noa Kline",
    "publicPath": "/studio-world/residents/season-1/sw-resident-004-noa-kline/work-uniform-candidates/sw-resident-004-noa-kline-work-uniform-candidate-01.jpg",
    "repoPath": "public/studio-world/residents/season-1/sw-resident-004-noa-kline/work-uniform-candidates/sw-resident-004-noa-kline-work-uniform-candidate-01.jpg",
    "sourceFilename": "0202633E-1841-450A-891A-1FF48C69DFB8.png",
    "organizedPath": "SW-RESIDENT-004__noa-kline/03-work-uniform-candidates/noa-kline__shared-uniform-candidate__v1.jpg",
    "packageStatus": "CONCEPT_REFERENCE_ONLY",
    "category": "work-uniform-candidates",
    "sourcePackage": "STUDIO_WORLD_SEASON1_VISUAL_AUTHORITY_CURSOR_LIGHT_v1"
  },
  {
    "assetId": "swa:SW-RESIDENT-005:natural-authority:sw-resident-005-caspian-reed-natural-fullbody-01.jpg",
    "residentId": "SW-RESIDENT-005",
    "residentName": "Caspian Reed",
    "publicPath": "/studio-world/residents/season-1/sw-resident-005-caspian-reed/natural-authority/sw-resident-005-caspian-reed-natural-fullbody-01.jpg",
    "repoPath": "public/studio-world/residents/season-1/sw-resident-005-caspian-reed/natural-authority/sw-resident-005-caspian-reed-natural-fullbody-01.jpg",
    "sourceFilename": "BBCAD99B-F64E-4101-8237-6A30E2A3DF43.png",
    "organizedPath": "SW-RESIDENT-005__caspian-reed/01-natural-authority/caspian-reed__natural-full-body__decadent-bohemian-aristocrat.jpg",
    "packageStatus": "FOUNDER_APPROVED",
    "category": "natural-authority",
    "sourcePackage": "STUDIO_WORLD_SEASON1_VISUAL_AUTHORITY_CURSOR_LIGHT_v1"
  },
  {
    "assetId": "swa:SW-RESIDENT-005:closeups:sw-resident-005-caspian-reed-closeup-01.jpg",
    "residentId": "SW-RESIDENT-005",
    "residentName": "Caspian Reed",
    "publicPath": "/studio-world/residents/season-1/sw-resident-005-caspian-reed/closeups/sw-resident-005-caspian-reed-closeup-01.jpg",
    "repoPath": "public/studio-world/residents/season-1/sw-resident-005-caspian-reed/closeups/sw-resident-005-caspian-reed-closeup-01.jpg",
    "sourceFilename": "E2D5E22F-6F71-4D17-A3E5-8FA28D8F93F5.png",
    "organizedPath": "SW-RESIDENT-005__caspian-reed/02-closeups/caspian-reed__closeup__decadent-bohemian-aristocrat.jpg",
    "packageStatus": "FOUNDER_APPROVED_REFERENCE",
    "category": "closeups",
    "sourcePackage": "STUDIO_WORLD_SEASON1_VISUAL_AUTHORITY_CURSOR_LIGHT_v1"
  },
  {
    "assetId": "swa:SW-RESIDENT-005:work-uniform-candidates:sw-resident-005-caspian-reed-work-uniform-candidate-01.jpg",
    "residentId": "SW-RESIDENT-005",
    "residentName": "Caspian Reed",
    "publicPath": "/studio-world/residents/season-1/sw-resident-005-caspian-reed/work-uniform-candidates/sw-resident-005-caspian-reed-work-uniform-candidate-01.jpg",
    "repoPath": "public/studio-world/residents/season-1/sw-resident-005-caspian-reed/work-uniform-candidates/sw-resident-005-caspian-reed-work-uniform-candidate-01.jpg",
    "sourceFilename": "9F733CC5-3B6D-4A84-9240-E849214B5920.png",
    "organizedPath": "SW-RESIDENT-005__caspian-reed/03-work-uniform-candidates/caspian-reed__shared-uniform-candidate__v1.jpg",
    "packageStatus": "CONCEPT_REFERENCE_ONLY",
    "category": "work-uniform-candidates",
    "sourcePackage": "STUDIO_WORLD_SEASON1_VISUAL_AUTHORITY_CURSOR_LIGHT_v1"
  },
  {
    "assetId": "swa:SW-RESIDENT-006:natural-authority:sw-resident-006-iona-wells-natural-fullbody-01.jpg",
    "residentId": "SW-RESIDENT-006",
    "residentName": "Iona Wells",
    "publicPath": "/studio-world/residents/season-1/sw-resident-006-iona-wells/natural-authority/sw-resident-006-iona-wells-natural-fullbody-01.jpg",
    "repoPath": "public/studio-world/residents/season-1/sw-resident-006-iona-wells/natural-authority/sw-resident-006-iona-wells-natural-fullbody-01.jpg",
    "sourceFilename": "IMG_6276.png",
    "organizedPath": "SW-RESIDENT-006__iona-wells/01-natural-authority/iona-wells__natural-full-body__precision-utilitarian.jpg",
    "packageStatus": "FOUNDER_APPROVED",
    "category": "natural-authority",
    "sourcePackage": "STUDIO_WORLD_SEASON1_VISUAL_AUTHORITY_CURSOR_LIGHT_v1"
  },
  {
    "assetId": "swa:SW-RESIDENT-006:closeups:sw-resident-006-iona-wells-closeup-01.jpg",
    "residentId": "SW-RESIDENT-006",
    "residentName": "Iona Wells",
    "publicPath": "/studio-world/residents/season-1/sw-resident-006-iona-wells/closeups/sw-resident-006-iona-wells-closeup-01.jpg",
    "repoPath": "public/studio-world/residents/season-1/sw-resident-006-iona-wells/closeups/sw-resident-006-iona-wells-closeup-01.jpg",
    "sourceFilename": "F46A6DF3-48E7-4FD9-A0AB-22F7BAF3E4E8.png",
    "organizedPath": "SW-RESIDENT-006__iona-wells/02-closeups/iona-wells__closeup__precision-utilitarian.jpg",
    "packageStatus": "FOUNDER_APPROVED_REFERENCE",
    "category": "closeups",
    "sourcePackage": "STUDIO_WORLD_SEASON1_VISUAL_AUTHORITY_CURSOR_LIGHT_v1"
  },
  {
    "assetId": "swa:SW-RESIDENT-006:work-uniform-candidates:sw-resident-006-iona-wells-work-uniform-candidate-01.jpg",
    "residentId": "SW-RESIDENT-006",
    "residentName": "Iona Wells",
    "publicPath": "/studio-world/residents/season-1/sw-resident-006-iona-wells/work-uniform-candidates/sw-resident-006-iona-wells-work-uniform-candidate-01.jpg",
    "repoPath": "public/studio-world/residents/season-1/sw-resident-006-iona-wells/work-uniform-candidates/sw-resident-006-iona-wells-work-uniform-candidate-01.jpg",
    "sourceFilename": "37BF712F-0553-4863-ACBA-DB7E13610995.png",
    "organizedPath": "SW-RESIDENT-006__iona-wells/03-work-uniform-candidates/iona-wells__shared-uniform-candidate__v1.jpg",
    "packageStatus": "CONCEPT_REFERENCE_ONLY",
    "category": "work-uniform-candidates",
    "sourcePackage": "STUDIO_WORLD_SEASON1_VISUAL_AUTHORITY_CURSOR_LIGHT_v1"
  },
  {
    "assetId": "swa:SW-RESIDENT-006:alternate-modes:sw-resident-006-iona-wells-alternate-mode-01.jpg",
    "residentId": "SW-RESIDENT-006",
    "residentName": "Iona Wells",
    "publicPath": "/studio-world/residents/season-1/sw-resident-006-iona-wells/alternate-modes/sw-resident-006-iona-wells-alternate-mode-01.jpg",
    "repoPath": "public/studio-world/residents/season-1/sw-resident-006-iona-wells/alternate-modes/sw-resident-006-iona-wells-alternate-mode-01.jpg",
    "sourceFilename": "07607EEC-49A1-44D6-A532-FD0D7AF41B52.png",
    "organizedPath": "SW-RESIDENT-006__iona-wells/04-alternate-modes/iona-wells__full-glam__alternate-mode.jpg",
    "packageStatus": "ALTERNATE_MODE_REFERENCE",
    "category": "alternate-modes",
    "sourcePackage": "STUDIO_WORLD_SEASON1_VISUAL_AUTHORITY_CURSOR_LIGHT_v1"
  },
  {
    "assetId": "swa:SW-RESIDENT-007:natural-authority:sw-resident-007-marlowe-saint-natural-fullbody-01.jpg",
    "residentId": "SW-RESIDENT-007",
    "residentName": "Marlowe Saint",
    "publicPath": "/studio-world/residents/season-1/sw-resident-007-marlowe-saint/natural-authority/sw-resident-007-marlowe-saint-natural-fullbody-01.jpg",
    "repoPath": "public/studio-world/residents/season-1/sw-resident-007-marlowe-saint/natural-authority/sw-resident-007-marlowe-saint-natural-fullbody-01.jpg",
    "sourceFilename": "653088E8-4A41-4618-B869-9C6E96BF6B9B.png",
    "organizedPath": "SW-RESIDENT-007__marlowe-saint/01-natural-authority/marlowe-saint__natural-full-body__off-duty-cultural-icon.jpg",
    "packageStatus": "FOUNDER_APPROVED",
    "category": "natural-authority",
    "sourcePackage": "STUDIO_WORLD_SEASON1_VISUAL_AUTHORITY_CURSOR_LIGHT_v1"
  },
  {
    "assetId": "swa:SW-RESIDENT-007:alternate-modes:sw-resident-007-marlowe-saint-alternate-mode-01.jpg",
    "residentId": "SW-RESIDENT-007",
    "residentName": "Marlowe Saint",
    "publicPath": "/studio-world/residents/season-1/sw-resident-007-marlowe-saint/alternate-modes/sw-resident-007-marlowe-saint-alternate-mode-01.jpg",
    "repoPath": "public/studio-world/residents/season-1/sw-resident-007-marlowe-saint/alternate-modes/sw-resident-007-marlowe-saint-alternate-mode-01.jpg",
    "sourceFilename": "0D841DDD-094C-45C2-B4A1-E3A5FAF006F5.png",
    "organizedPath": "SW-RESIDENT-007__marlowe-saint/04-alternate-modes/marlowe-saint__grand-cultural-icon__alternate-reference.jpg",
    "packageStatus": "REFERENCE_ONLY",
    "category": "alternate-modes",
    "sourcePackage": "STUDIO_WORLD_SEASON1_VISUAL_AUTHORITY_CURSOR_LIGHT_v1"
  },
  {
    "assetId": "swa:SW-RESIDENT-007:work-uniform-candidates:sw-resident-007-marlowe-saint-work-uniform-candidate-01.jpg",
    "residentId": "SW-RESIDENT-007",
    "residentName": "Marlowe Saint",
    "publicPath": "/studio-world/residents/season-1/sw-resident-007-marlowe-saint/work-uniform-candidates/sw-resident-007-marlowe-saint-work-uniform-candidate-01.jpg",
    "repoPath": "public/studio-world/residents/season-1/sw-resident-007-marlowe-saint/work-uniform-candidates/sw-resident-007-marlowe-saint-work-uniform-candidate-01.jpg",
    "sourceFilename": "1D701D29-55D5-4C14-9CC3-2011161E2623.png",
    "organizedPath": "SW-RESIDENT-007__marlowe-saint/03-work-uniform-candidates/marlowe-saint__shared-uniform-candidate__corrected-larger-body-v1.jpg",
    "packageStatus": "CONCEPT_REFERENCE_ONLY",
    "category": "work-uniform-candidates",
    "sourcePackage": "STUDIO_WORLD_SEASON1_VISUAL_AUTHORITY_CURSOR_LIGHT_v1"
  },
  {
    "assetId": "swa:SW-RESIDENT-008:natural-authority:sw-resident-008-elio-vahn-natural-fullbody-01.jpg",
    "residentId": "SW-RESIDENT-008",
    "residentName": "Elio Vahn",
    "publicPath": "/studio-world/residents/season-1/sw-resident-008-elio-vahn/natural-authority/sw-resident-008-elio-vahn-natural-fullbody-01.jpg",
    "repoPath": "public/studio-world/residents/season-1/sw-resident-008-elio-vahn/natural-authority/sw-resident-008-elio-vahn-natural-fullbody-01.jpg",
    "sourceFilename": "589F06FC-8AE7-432C-8663-47FFDB1B400D.png",
    "organizedPath": "SW-RESIDENT-008__elio-vahn/01-natural-authority/elio-vahn__natural-full-body__private-club-strategist.jpg",
    "packageStatus": "FOUNDER_APPROVED",
    "category": "natural-authority",
    "sourcePackage": "STUDIO_WORLD_SEASON1_VISUAL_AUTHORITY_CURSOR_LIGHT_v1"
  },
  {
    "assetId": "swa:SW-RESIDENT-008:closeups:sw-resident-008-elio-vahn-closeup-01.jpg",
    "residentId": "SW-RESIDENT-008",
    "residentName": "Elio Vahn",
    "publicPath": "/studio-world/residents/season-1/sw-resident-008-elio-vahn/closeups/sw-resident-008-elio-vahn-closeup-01.jpg",
    "repoPath": "public/studio-world/residents/season-1/sw-resident-008-elio-vahn/closeups/sw-resident-008-elio-vahn-closeup-01.jpg",
    "sourceFilename": "53E548C2-37F2-4A95-A150-24FBC3A80337.png",
    "organizedPath": "SW-RESIDENT-008__elio-vahn/02-closeups/elio-vahn__closeup__private-club-strategist.jpg",
    "packageStatus": "FOUNDER_APPROVED_REFERENCE",
    "category": "closeups",
    "sourcePackage": "STUDIO_WORLD_SEASON1_VISUAL_AUTHORITY_CURSOR_LIGHT_v1"
  },
  {
    "assetId": "swa:SW-RESIDENT-008:work-uniform-candidates:sw-resident-008-elio-vahn-work-uniform-candidate-01.jpg",
    "residentId": "SW-RESIDENT-008",
    "residentName": "Elio Vahn",
    "publicPath": "/studio-world/residents/season-1/sw-resident-008-elio-vahn/work-uniform-candidates/sw-resident-008-elio-vahn-work-uniform-candidate-01.jpg",
    "repoPath": "public/studio-world/residents/season-1/sw-resident-008-elio-vahn/work-uniform-candidates/sw-resident-008-elio-vahn-work-uniform-candidate-01.jpg",
    "sourceFilename": "DE6539F4-DAFA-4062-9F5E-E6DE2C453A80.png",
    "organizedPath": "SW-RESIDENT-008__elio-vahn/03-work-uniform-candidates/elio-vahn__shared-uniform-candidate__v1.jpg",
    "packageStatus": "CONCEPT_REFERENCE_ONLY",
    "category": "work-uniform-candidates",
    "sourcePackage": "STUDIO_WORLD_SEASON1_VISUAL_AUTHORITY_CURSOR_LIGHT_v1"
  }
] as Season1IngestedVisualAsset[];

export const SEASON1_VISUAL_ASSET_BY_ID: Record<string, Season1IngestedVisualAsset> = Object.fromEntries(
  SEASON1_INGESTED_VISUAL_ASSETS.map((a) => [a.assetId, a])
);
