import { bootstrapCreatorMarketplaceStore } from './store';
import type { CreatorMarketplaceStore, CreatorProfile } from './types';

export function buildCreatorMarketplaceSeed(): Partial<CreatorMarketplaceStore> {
  const creators: CreatorProfile[] = [
    {
      id: 'creator-jordan-t',
      workspaceId: 'ndxbook',
      displayName: 'JORDAN T · HEALTH EDUCATOR',
      careerStage: 'brand-ambassador',
      creatorScore: 91,
      brandAlignmentScore: 94,
      trustScore: 94,
      professionalismScore: 88,
      communityScore: 85,
      knowledgeScore: 86,
      engagementQuality: '95% completion · 51s avg watch · thoughtful comments',
      audienceDemographics: 'Health-curious 25-45 · 62% returning · US/UK',
      contentCategories: ['Health', 'Research-gated facts', 'Truth Tuesday'],
      industries: ['Media', 'Wellness', 'Education'],
      platforms: ['TikTok', 'YouTube', 'Newsletter'],
      pricing: '$500-800/collab · $2K/quarter ambassador',
      availability: '2 slots/month · Tue-Thu preferred',
      languages: ['English'],
      location: 'Remote · US timezone',
      verified: true,
      relationshipEngineId: 'rel-jordan-t',
      futureGoals: ['Creator marketplace host', 'Wellness course', 'Agency for health educators'],
    },
    {
      id: 'creator-finance-ed',
      workspaceId: 'ndxbook',
      displayName: 'FINANCE EDUCATOR · TIER A',
      careerStage: 'preferred-creator',
      creatorScore: 88,
      brandAlignmentScore: 92,
      trustScore: 90,
      professionalismScore: 91,
      communityScore: 78,
      knowledgeScore: 88,
      engagementQuality: '+34% reach on finance clips · authority tone',
      audienceDemographics: 'Money-curious 25-45 · finance-focused',
      contentCategories: ['Finance', 'Money Monday', 'Stat-forward'],
      industries: ['Finance', 'Media', 'Education'],
      platforms: ['Instagram', 'TikTok', 'LinkedIn'],
      pricing: '$400-600/collab',
      availability: '4 slots/month',
      languages: ['English'],
      location: 'US',
      verified: true,
      futureGoals: ['Preferred creator tier', 'Affiliate program lead'],
    },
    {
      id: 'creator-mind-host',
      workspaceId: 'ndxbook',
      displayName: 'MIND VOLUME HOST · TIER B',
      careerStage: 'verified-creator',
      creatorScore: 78,
      brandAlignmentScore: 82,
      trustScore: 85,
      professionalismScore: 80,
      communityScore: 72,
      knowledgeScore: 79,
      engagementQuality: 'Strong completion on mind content · internal talent',
      audienceDemographics: 'Existing ndxbook readers · mind volume fans',
      contentCategories: ['Psychology', 'Mind volume', 'Long-form'],
      industries: ['Media', 'Education'],
      platforms: ['ndxbook', 'YouTube', 'Podcast'],
      pricing: 'Internal · $300/collab external',
      availability: 'Flexible',
      languages: ['English'],
      location: 'Remote',
      verified: true,
      futureGoals: ['Verified creator → preferred', 'Podcast series host'],
    },
  ];

  return {
    dashboard: {
      summary:
        'CREATOR MARKETPLACE V1.0 — intelligent layer connecting creators, brands, and long-term partnerships. Not buying posts · building creator businesses · alignment over follower counts.',
      verifiedCreators: 0,
      activeDeals: 0,
      avgMatchConfidence: 0,
      risingCreators: 0,
      partnershipRenewalPct: 72,
      marketplaceHealthPct: 84,
    },
    activeWorkspaceId: 'ndxbook',
    creators,
    brands: [
      {
        id: 'brand-ndxbook',
        workspaceId: 'ndxbook',
        name: 'NDXBOOK',
        industry: 'Digital media · Knowledge',
        mission: 'Authority through consistency · 100K readers',
        companyDna: 'Research-gated · fact-forward · returning reader focus',
        creativeDna: 'Stat overlays · question hooks · Labs-validated templates',
        partnershipPhilosophy: 'Long-term alignment · education · trust · not one-time posts',
        budgetRange: '$400-2K/collab · $5K/quarter ambassador programs',
        brandValues: ['Authority', 'Trust', 'Consistency', 'Education'],
        preferredCreatorTypes: ['Educators', 'Health experts', 'Finance creators'],
        collaborationStyles: ['Co-create content', 'Guest host', 'Affiliate', 'Ambassador'],
        brandReputation: 88,
        campaignCount: 12,
      },
      {
        id: 'brand-frontal-slayer',
        workspaceId: 'frontal-slayer',
        name: 'FRONTAL SLAYER',
        industry: 'Luxury raw hair · Commerce',
        mission: 'Interactive luxury commerce · community-first luxury',
        companyDna: 'Premium · concierge · Build-a-Wig · Lounge TV',
        creativeDna: 'Luxury raw · live previews · PSA founder voice',
        partnershipPhilosophy: 'Brand alignment · luxury audience · long-term ambassadors',
        budgetRange: '$1K-5K/collab · product + fee',
        brandValues: ['Luxury', 'Quality', 'Community', 'Education'],
        preferredCreatorTypes: ['Beauty educators', 'Hair experts', 'Luxury lifestyle'],
        collaborationStyles: ['Product integration', 'Lounge TV guest', 'Ambassador'],
        brandReputation: 92,
        campaignCount: 6,
      },
    ],
    matches: [
      {
        id: 'match-1',
        creatorId: 'creator-jordan-t',
        brandId: 'brand-ndxbook',
        campaignId: 'camp-truth-tuesday',
        campaignLabel: 'TRUTH TUESDAY · FACT-FORWARD',
        confidencePct: 94,
        reasoning: '94% brand alignment · health expertise · 5 referrals · advocate behavior · Writing DNA match',
        expectedImpact: '+40% reach on health clips · authority signal · 3 new advocate candidates',
        longTermPotential: 'Ambassador → partner → wellness course co-creator',
        factors: { companyDna: 96, campaignObjective: 92, creativeDna: 90, audienceOverlap: 88, brandValues: 95, performance: 91, professionalism: 88, pricing: 85 },
      },
      {
        id: 'match-2',
        creatorId: 'creator-finance-ed',
        brandId: 'brand-ndxbook',
        campaignId: 'camp-money-monday-mar',
        campaignLabel: 'MONEY MONDAY · MARCH CYCLE',
        confidencePct: 91,
        reasoning: 'Finance educator Tier A · +34% historical reach · stat-forward alignment · Money Monday cadence',
        expectedImpact: '+28% CTR on money content · affiliate pipeline',
        longTermPotential: 'Preferred creator · Money Monday co-host · affiliate program lead',
        factors: { companyDna: 92, campaignObjective: 94, creativeDna: 88, audienceOverlap: 90, brandValues: 91, performance: 93, professionalism: 91, pricing: 88 },
      },
      {
        id: 'match-3',
        creatorId: 'creator-mind-host',
        brandId: 'brand-ndxbook',
        campaignId: 'camp-page-028',
        campaignLabel: 'PAGE 028 · CROSS-PLATFORM PUSH',
        confidencePct: 76,
        reasoning: 'Mind volume alignment · existing reader base · internal talent · cost-effective',
        expectedImpact: '2x reach vs organic on mind content',
        longTermPotential: 'Verified → preferred · podcast series',
        factors: { companyDna: 80, campaignObjective: 78, creativeDna: 82, audienceOverlap: 85, brandValues: 80, performance: 72, professionalism: 80, pricing: 95 },
      },
    ],
    deals: [
      {
        id: 'deal-1',
        creatorId: 'creator-jordan-t',
        brandId: 'brand-ndxbook',
        campaignLabel: 'TRUTH TUESDAY · GUEST HOST Q2',
        status: 'negotiating',
        deliverables: ['4 TikTok clips', '2 YouTube Shorts', '1 newsletter feature'],
        timeline: 'Apr – Jun 2026',
        payment: '$2,400/quarter · affiliate bonus',
        renewalPotential: 'High · ambassador tier candidate',
      },
      {
        id: 'deal-2',
        creatorId: 'creator-finance-ed',
        brandId: 'brand-ndxbook',
        campaignLabel: 'MONEY MONDAY · STAT OVERLAY COLLAB',
        status: 'active',
        deliverables: ['3 Reels', '2 TikTok', 'Affiliate links'],
        timeline: 'Mar 2026',
        payment: '$600/collab · 15% affiliate',
        performance: 'Labs #38 pattern · +18% CTR validated',
        renewalPotential: 'Very high · preferred creator pipeline',
      },
    ],
    creatorOs: {
      'creator-jordan-t': {
        creatorId: 'creator-jordan-t',
        monthlyRevenue: '$840 affiliate + $600 collab',
        activeCampaigns: 2,
        pendingContracts: 1,
        upcomingDeliverables: 4,
        brandRelationships: 3,
        careerProgressPct: 78,
      },
      'creator-finance-ed': {
        creatorId: 'creator-finance-ed',
        monthlyRevenue: '$1,200 avg',
        activeCampaigns: 1,
        pendingContracts: 0,
        upcomingDeliverables: 3,
        brandRelationships: 2,
        careerProgressPct: 65,
      },
    },
    agencyTeams: [
      { id: 'ag-1', creatorId: 'creator-jordan-t', role: 'editor', label: 'Video editor · part-time', status: 'planned' },
      { id: 'ag-2', creatorId: 'creator-jordan-t', role: 'manager', label: 'Creator manager · Q3 hire', status: 'planned' },
    ],
    intelligenceSignals: [
      { id: 'mi-1', type: 'rising-creator', label: 'JORDAN T · RISING AMBASSADOR', targetId: 'creator-jordan-t', confidencePct: 91, opportunity: 'Invite before competitor capture · ambassador program Q2' },
      { id: 'mi-2', type: 'undervalued', label: 'MIND VOLUME HOST · UNDERVALUED', targetId: 'creator-mind-host', confidencePct: 78, opportunity: 'Internal talent · expand to external collabs at premium' },
      { id: 'mi-3', type: 'future-agency', label: 'JORDAN T · AGENCY POTENTIAL', targetId: 'creator-jordan-t', confidencePct: 72, opportunity: 'Health educator agency · 3 creator roster by 2027' },
    ],
    relationships: [
      { id: 'mr-1', creatorId: 'creator-jordan-t', brandId: 'brand-ndxbook', trustPct: 94, renewals: 2, collaborationHealthPct: 89, feedback: 'Excellent communication · on-time · brand-aligned', longTerm: true },
      { id: 'mr-2', creatorId: 'creator-finance-ed', brandId: 'brand-ndxbook', trustPct: 90, renewals: 1, collaborationHealthPct: 85, feedback: 'Strong performance · stat overlay fit', longTerm: true },
    ],
    simulations: [
      {
        id: 'msim-1',
        creatorId: 'creator-jordan-t',
        brandId: 'brand-ndxbook',
        label: 'TRUTH TUESDAY AMBASSADOR · Q2',
        campaignPerformance: '+40% reach · 91% retention',
        brandFit: '94% alignment · health authority',
        audienceResponse: 'High share rate · advocate pipeline +3',
        relationshipImpact: 'Trust +6% · renewal 85% likely',
        expectedRoi: '3.2x · affiliate + brand lift',
        expectedRevenue: '$4.8K creator · $12K brand value',
        confidencePct: 88,
        adjustments: ['Add newsletter feature for owned audience', 'Extend to podcast outline'],
      },
    ],
    education: [
      { id: 'edu-1', category: 'negotiation', title: 'NEGOTIATION FUNDAMENTALS', description: 'Rate setting · contract terms · long-term vs one-time', progressPct: 0 },
      { id: 'edu-2', category: 'contracts', title: 'CONTRACT ESSENTIALS', description: 'Deliverables · exclusivity · usage rights · FTC', progressPct: 0 },
      { id: 'edu-3', category: 'pricing', title: 'PRICING YOUR VALUE', description: 'Not follower counts · alignment · outcomes · LTV', progressPct: 0 },
      { id: 'edu-4', category: 'brand-building', title: 'CREATOR BRAND BUILDING', description: 'Niche · authority · community · trust', progressPct: 0 },
      { id: 'edu-5', category: 'finance', title: 'CREATOR FINANCE 101', description: 'Revenue mix · taxes · forecasting · diversification', progressPct: 0 },
      { id: 'edu-6', category: 'studio-os', title: 'STUDIO OS FOR CREATORS', description: 'Creator OS dashboard · deals · analytics · career roadmap', progressPct: 0 },
    ],
    talentDiscoveries: [
      { id: 'td-1', type: 'educator', name: 'JORDAN T · HEALTH EDUCATOR', fitScore: 94, brandId: 'brand-ndxbook' },
      { id: 'td-2', type: 'presenter', name: 'MIND VOLUME HOST', fitScore: 82, brandId: 'brand-ndxbook' },
      { id: 'td-3', type: 'consultant', name: 'FINANCE EDUCATOR · TIER A', fitScore: 91, brandId: 'brand-ndxbook' },
    ],
    careerRecommendations: [
      { id: 'cr-1', creatorId: 'creator-jordan-t', type: 'course', label: 'WELLNESS LEARNING PATH · COURSE', rationale: 'Health expertise · 94% trust · audience requests depth', projectedLift: '$8K/quarter passive · ambassador retention' },
      { id: 'cr-2', creatorId: 'creator-jordan-t', type: 'agency-expansion', label: 'HEALTH EDUCATOR AGENCY · ROSTER', rationale: 'Agency stage candidate · 3 educators in network', projectedLift: 'Scale to $15K/mo · preferred creator pipeline' },
      { id: 'cr-3', creatorId: 'creator-finance-ed', type: 'rate-increase', label: 'RATE INCREASE · PREFERRED TIER', rationale: '+18% CTR validated · underpriced vs performance', projectedLift: '+25% revenue per collab' },
    ],
    paymentIntel: {
      'creator-jordan-t': {
        creatorId: 'creator-jordan-t',
        monthlyRevenue: '$1,440 avg',
        annualRevenue: '$17.2K projected',
        brandConcentrationPct: 65,
        incomeDiversityPct: 42,
        forecast: '+22% YoY with ambassador tier',
        financialHealthPct: 78,
        recommendation: 'Diversify · course revenue · reduce ndxbook concentration below 50%',
      },
      'creator-finance-ed': {
        creatorId: 'creator-finance-ed',
        monthlyRevenue: '$1,200',
        annualRevenue: '$14.4K',
        brandConcentrationPct: 80,
        incomeDiversityPct: 35,
        forecast: 'Stable · preferred tier unlocks +30%',
        financialHealthPct: 72,
        recommendation: 'Expand brand relationships · affiliate diversification',
      },
    },
    selectedCreatorId: 'creator-jordan-t',
    selectedBrandId: 'brand-ndxbook',
  };
}

export function bootstrapCreatorMarketplacePlatform(): void {
  bootstrapCreatorMarketplaceStore(buildCreatorMarketplaceSeed());
}
