import type { MemoryBibleSnapshot } from './types.js';

/** Memory Bible v1.0 — curated institutional knowledge (admin-only). */
export const MEMORY_BIBLE_V1_0: MemoryBibleSnapshot = {
  version: '1.0',
  founderProfile: {
    preferredName: 'Founder',
    activeCompanies: ['VXD Inc.', 'Frontal Slayer'],
    activeWorkspaces: ['frontal-slayer', 'sandbox', 'future-brand', 'future-client'],
    currentPriorityProjects: [
      'studio os platform maturity',
      'Product Photography Bible + Asset Factory pipeline',
      'Build-A-Wig visual snapshot system',
      'Onboarding Tutorial (The Mansion Tour)',
      'studio os Interactive Manual + Knowledge Graph',
    ],
    longTermGoals: [
      'Multi-brand studio os operating system for modern companies',
      'Self-documenting admin with institutional memory outside any single AI vendor',
      'Scalable asset pipelines from approved masters',
      'Luxury customer experience with premium membership depth',
    ],
    preferredTools: ['Cursor', 'FAL', 'Supabase', 'Vercel', 'OpenAI (select workflows)'],
    workingStyle: [
      'Architecture-first before feature sprawl',
      'Visual proof before metadata-heavy admin',
      'Iterate in milestones with one deploy per task',
      'Prefer reusable systems over one-off fixes',
    ],
    decisionMakingStyle: [
      'Define source-of-truth systems early',
      'Separate creative direction from manufacturing execution',
      'Approval gates before publishing or derivative processing',
      'Document decisions in Memory Bible, not chat history alone',
    ],
    founderNotes:
      'Memory Bible is internal admin-only. Do not expose founder profile fields on customer-facing pages. Update when priorities shift — append version history instead of silent overwrites.',
  },
  communicationStyle: {
    id: 'communication-style',
    title: 'Communication Style',
    rules: [
      'Use lowercase for copy-paste drafts when matching founder voice',
      'Use standard capitalization for normal internal explanations unless otherwise requested',
      'Avoid em dashes',
      'Use "&" instead of "and" where it sounds natural',
      'Keep spacing clean',
      'Avoid excessive emojis',
      'Avoid unnecessary bolding',
      'Avoid filler',
      'Write naturally',
      'Prioritize clarity over polish',
      'Avoid generic intros & conclusions',
      'Avoid repetitive wording',
      'Avoid overexplaining',
      'Use concrete examples',
      'Keep cursor prompts direct & implementation-focused',
    ],
  },
  writingRules: {
    id: 'writing-rules',
    title: 'Writing Rules',
    rules: [
      'Match Frontal Slayer luxury editorial tone — trust over hard sell',
      'PSA founder voice: concierge, hair bestie, educator, no gatekeeping',
      'Uppercase Futura labels in admin UI copy; Grace accent for hero numbers only where designed',
      'Product references must use real catalog units — never invent SKUs',
      'Email & Signature Collection copy follows Photography Bible visual standards',
      'Onboarding Tutorial product name: Onboarding Tutorial — tour name: The Mansion Tour',
      'Do not label customer concierge as "FS Concierge" in new platform docs — use Onboarding Tutorial',
    ],
    notes: 'Links to Content Brain, email builder, and Tutorial OS copy workflows.',
  },
  cursorPromptStandards: {
    id: 'cursor-prompt-standards',
    title: 'Cursor Prompt Standards',
    rules: [
      'Read like instructions to a senior engineer',
      'Be direct & implementation-focused',
      'Explain intent before implementation',
      'Define expected outcomes',
      'Include edge cases when relevant',
      'Avoid motivational language',
      'Avoid repeating constraints unless critical',
      'Use logical sections',
      'Easy to copy/paste into Cursor',
      'One Vercel deploy per completed task on master',
      'Append motherboard/MEMORY.md before commit when code changes',
    ],
  },
  designPhilosophy: {
    id: 'design-philosophy',
    title: 'Design Philosophy',
    rules: [
      'Luxury over generic',
      'Immersive over flat',
      'Interactive over static',
      'Modular over one-off',
      'Reusable systems over quick fixes',
      'White marble, glass, acrylic, chrome, red accents (#EB1C24)',
      'Premium spacing & editorial hierarchy',
      'Visual storytelling',
      'Self-documenting interfaces',
      'Guided walkthroughs over static help pages',
    ],
  },
  engineeringPhilosophy: {
    id: 'engineering-philosophy',
    title: 'Engineering Philosophy',
    rules: [
      'Architecture first',
      'Avoid hardcoding brand knowledge in studio os core',
      'Build reusable systems',
      'Separate platform core from workspace data',
      'Version everything important',
      'Keep source-of-truth systems clean',
      'Prefer scalable pipelines over manual workflows',
      'Documentation should live with the product',
      'Knowledge graph should connect systems',
      'Approval queues before publishing',
      'Assets generated from approved master systems only',
    ],
  },
  brandPhilosophy: {
    id: 'brand-philosophy',
    title: 'Brand Philosophy',
    rules: [
      'studio os is the platform — workspaces are tenants (Frontal Slayer is first production workspace)',
      'Creative DNA defines visual standard; Asset Factory manufactures from that standard',
      'Photography Bible is permanent product photography source of truth',
      'Never assume beauty/hair/e-commerce in platform core — that belongs to workspaces',
      'Official platform name is always "studio os" (spaced, lowercase in prose)',
    ],
  },
  namingBible: [
    {
      id: 'name-studio-os',
      officialName: 'studio os',
      deprecatedNames: ['studioos', 'StudioOS', 'studioOS', 'vxd studios os'],
      usageNotes: 'Platform operating system. UI all-caps: STUDIO OS. Routes stay /admin/studio-os.',
      relatedModules: ['platform-settings', 'knowledge-hub', 'memory-bible'],
      relatedGraphNodeIds: ['node-memory-bible', 'node-interactive-manual'],
    },
    {
      id: 'name-frontal-slayer',
      officialName: 'Frontal Slayer',
      deprecatedNames: [],
      usageNotes: 'First production workspace — luxury raw hair brand & media studio.',
      relatedModules: ['mission-control', 'content-brain', 'brand-assets'],
    },
    {
      id: 'name-vxd',
      officialName: 'VXD Inc.',
      deprecatedNames: [],
      usageNotes: 'Owns studio os. Independent from any single workspace.',
      relatedModules: ['platform-settings'],
    },
    {
      id: 'name-creative-dna',
      officialName: 'Creative DNA',
      deprecatedNames: [],
      usageNotes: 'Locked photography generation package — not the same as Asset Factory.',
      relatedModules: ['photography-bible', 'brand-assets-asset-factory'],
      relatedGraphNodeIds: ['node-creative-dna'],
    },
    {
      id: 'name-photography-bible',
      officialName: 'Photography Bible',
      deprecatedNames: [],
      usageNotes: 'Product photography standards for Signature Collection & future lines.',
      relatedModules: ['brand-assets', 'photography-bible'],
    },
    {
      id: 'name-memory-bible',
      officialName: 'Memory Bible',
      deprecatedNames: [],
      usageNotes: 'Curated institutional knowledge — not chat history.',
      relatedModules: ['memory-bible'],
      relatedGraphNodeIds: ['node-memory-bible'],
    },
    {
      id: 'name-writing-bible',
      officialName: 'Writing Bible',
      deprecatedNames: [],
      usageNotes: 'Editorial & copy standards (Content Brain adjacent).',
      relatedModules: ['content-brain'],
    },
    {
      id: 'name-asset-factory',
      officialName: 'Asset Factory',
      deprecatedNames: [],
      usageNotes: 'Manufacturing department — generates assets from approved masters.',
      relatedModules: ['brand-assets-asset-factory', 'asset-factory'],
      relatedGraphNodeIds: ['node-smart-asset-registry'],
    },
    {
      id: 'name-onboarding-tutorial',
      officialName: 'Onboarding Tutorial',
      deprecatedNames: ['FS Concierge (when referring to onboarding tutorial platform name)'],
      usageNotes: 'Customer onboarding product. Tour name: The Mansion Tour.',
      relatedModules: ['tutorial-os'],
      relatedGraphNodeIds: ['node-onboarding-tutorial'],
    },
    {
      id: 'name-interactive-manual',
      officialName: 'studio os Interactive Manual',
      deprecatedNames: [],
      usageNotes: 'Admin help — Knowledge Graph backed. Not customer onboarding.',
      relatedModules: ['knowledge-hub'],
      relatedGraphNodeIds: ['node-interactive-manual'],
    },
    {
      id: 'name-knowledge-graph',
      officialName: 'Knowledge Graph',
      deprecatedNames: [],
      usageNotes: 'Cross-module relationships for Interactive Manual & ⓘ panels.',
      relatedModules: ['knowledge-hub'],
    },
    {
      id: 'name-mission-control',
      officialName: 'Mission Control',
      deprecatedNames: [],
      usageNotes: 'Workspace executive HQ landing after workspace selection.',
      relatedModules: ['mission-control'],
    },
    {
      id: 'name-production-builder',
      officialName: 'Production Builder',
      deprecatedNames: [],
      usageNotes: 'Visual production assembly workspace.',
      relatedModules: ['production-builder'],
    },
    {
      id: 'name-director-mode',
      officialName: 'Director Mode',
      deprecatedNames: [],
      usageNotes: 'Cinematic rehearsal control room linked to Production Builder.',
      relatedModules: ['director-mode'],
    },
    {
      id: 'name-campaign-orchestrator',
      officialName: 'Campaign Orchestrator',
      deprecatedNames: [],
      usageNotes: 'Operational launch planner — one goal, one plan.',
      relatedModules: ['campaign-orchestrator'],
    },
    {
      id: 'name-executive-ai-director',
      officialName: 'Executive AI Director',
      deprecatedNames: ['creatoros (deprecated platform name)'],
      usageNotes: 'Strategic advisor — coaches from workspace data, does not replace production tools.',
      relatedModules: ['executive-ai-director'],
    },
    {
      id: 'name-baw-visual-snapshot',
      officialName: 'Build-A-Wig Visual Snapshot System',
      deprecatedNames: [],
      usageNotes: 'Live Fal/GPT preview pipeline for BAW customize flows.',
      relatedModules: ['build-a-wig'],
    },
  ],
  decisionLog: [
    {
      id: 'dec-studio-os-branding',
      title: 'Rename studioos to studio os',
      date: '2026-07-04',
      workspace: 'global',
      relatedModule: 'platform-settings',
      decision: 'Official platform name is "studio os" (spaced). User-facing copy uses studio os / STUDIO OS.',
      reason:
        'Official branding requires the spaced name for visibility, documentation, & platform identity.',
      alternativesConsidered: ['Keep StudioOS camelCase', 'Rename routes to /admin/studio-os only'],
      outcome: 'Branding correction shipped — technical routes unchanged.',
      status: 'active',
      relatedGraphNodeIds: ['node-memory-bible'],
      relatedManualChapter: 'CHAPTER · PLATFORM · NAMING',
    },
    {
      id: 'dec-creative-dna-vs-factory',
      title: 'Separate Creative DNA from Asset Factory',
      date: '2026-07-04',
      workspace: 'frontal-slayer',
      relatedModule: 'brand-assets-asset-factory',
      decision:
        'Creative DNA defines the visual standard. Asset Factory manufactures assets from that standard.',
      reason:
        'Keeps creative direction separate from production execution. Prevents factory from inventing photography rules.',
      alternativesConsidered: ['Single combined photography + factory module', 'FAL-only without approval gate'],
      outcome: 'Master Hero approval gate + derivative pipeline active for SOFT WAVE POC.',
      status: 'active',
      relatedGraphNodeIds: ['node-creative-dna', 'node-master-hero', 'node-smart-asset-registry'],
      relatedManualChapter: 'CHAPTER · PHOTOGRAPHY · ASSET FACTORY',
    },
    {
      id: 'dec-memory-bible',
      title: 'Launch Memory Bible v1.0',
      date: '2026-07-04',
      workspace: 'global',
      relatedModule: 'memory-bible',
      decision:
        'studio os owns curated institutional memory with AI Context Builder — not vendor chat history alone.',
      reason:
        'Future agents, contractors, & team members need stable context before helping on any milestone.',
      alternativesConsidered: ['Rely on motherboard folder only', 'External Notion wiki'],
      outcome: 'Memory Bible module + context packages in admin.',
      status: 'active',
      relatedGraphNodeIds: ['node-memory-bible', 'node-interactive-manual'],
    },
  ],
  aiPreferences: {
    defaultTone: 'Direct, implementation-focused, luxury-aware but not verbose.',
    contextPackageDefaults: [
      'Include naming bible for any dev milestone',
      'Include cursor prompt standards for Cursor target',
      'Include workspace memory when workspace is frontal-slayer',
      'Include related decisions for scoped modules',
    ],
    agentOnboardingChecklist: [
      'Read motherboard README, CORE, CODEBASE, MEMORY at conversation start',
      'Confirm official names from Naming Bible',
      'Check Decision Log for recent platform choices',
      'Use Context Builder for task-specific packages',
      'Never expose admin-only memory on customer pages',
    ],
    doNotRules: [
      'Do not invent product SKUs or photography rules outside Photography Bible / Creative DNA',
      'Do not silently fall back to placeholder product images in Asset Factory master pipeline',
      'Do not create cursor/* or feature/* branches — work on master per project policy',
      'Do not redesign admin dashboard when adding modules',
    ],
  },
  workspaceMemory: [
    {
      workspaceId: 'global',
      workspaceLabel: 'studio os (platform)',
      summary: 'Multi-brand operating system — platform core, workspace registry, institutional memory.',
      pillars: [
        'studio-os-core package',
        'Workspace picker at /admin/studio-os',
        'Knowledge Graph + Interactive Manual',
        'Memory Bible + AI Context Builder',
      ],
      relatedModules: ['memory-bible', 'knowledge-hub', 'platform-settings'],
    },
    {
      workspaceId: 'frontal-slayer',
      workspaceLabel: 'Frontal Slayer',
      summary: 'Luxury raw hair brand, Signature Collection, media studio, premium membership.',
      pillars: [
        'Signature Collection (6 flagship units)',
        'Build-A-Wig + live NOIR preview pipeline',
        'Lounge TV + rewards + Slay Tickets',
        'Photography Bible + Creative DNA + Asset Factory',
        'Onboarding Tutorial (The Mansion Tour) for customers',
      ],
      relatedModules: [
        'brand-assets',
        'mission-control',
        'content-brain',
        'tutorial-os',
        'production-builder',
      ],
    },
  ],
  versionHistory: [
    {
      version: '1.0',
      label: 'Memory Bible v1.0',
      status: 'active',
      effectiveDate: '2026-07-04',
      updatedBy: 'studio os admin',
      notes: 'Initial institutional memory layer — founder profile, naming, decisions, context builder.',
      changeSummary: [
        'Founder profile & communication standards',
        'Naming bible with deprecated aliases',
        'Decision log with Knowledge Graph links',
        'AI Context Builder for Cursor & creative tools',
        'Workspace memory for global + Frontal Slayer',
      ],
    },
  ],
};
