import type { CatalogServiceEntry, ServiceNeedOption } from './serviceCatalogTypes';

/** Canonical service catalog — public site, Road Ready, portal, office derive from here. */
export const CANONICAL_SERVICE_CATALOG: CatalogServiceEntry[] = [
  // ── START MY BUSINESS ──
  {
    id: 'llc-formation',
    slug: 'llc-formation-assistance',
    name: 'LLC Formation',
    shortDescription: 'Help forming your trucking LLC.',
    description: 'Business formation coordination — not legal representation.',
    category: 'start-my-business',
    legacyDivision: 'business-formation',
    fulfillmentType: 'AIO_DIRECT',
    activationStatus: 'LIMITED_PILOT',
    jurisdictionDependent: true,
    defaultJurisdictionAvailability: 'AVAILABLE',
    pricingModel: 'quote_required',
    quoteRequired: true,
    documentsRequired: true,
    workflowTemplateSlug: 'business-formation',
    renewalInterval: null,
    roadReadyApplicable: true,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'QUOTE_REQUIRED',
    icon: 'formation',
    cta: 'Request Assistance',
    relatedSlugs: ['ein-assistance', 'trucking-business-startup'],
  },
  {
    id: 'corp-formation',
    slug: 'corporation-formation-assistance',
    name: 'Corporation / INC Formation',
    shortDescription: 'Help forming a corporation for your trucking business.',
    description: 'Corporation formation coordination assistance.',
    category: 'start-my-business',
    legacyDivision: 'business-formation',
    fulfillmentType: 'AIO_DIRECT',
    activationStatus: 'LIMITED_PILOT',
    jurisdictionDependent: true,
    defaultJurisdictionAvailability: 'AVAILABLE',
    pricingModel: 'quote_required',
    quoteRequired: true,
    documentsRequired: true,
    workflowTemplateSlug: 'business-formation',
    roadReadyApplicable: true,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'QUOTE_REQUIRED',
    icon: 'formation',
    cta: 'Request Assistance',
  },
  {
    id: 'ein',
    slug: 'ein-assistance',
    name: 'EIN / Business Registration Support',
    shortDescription: 'Employer Identification Number guidance.',
    description: 'Assistance obtaining an EIN for your trucking business.',
    category: 'start-my-business',
    legacyDivision: 'business-formation',
    fulfillmentType: 'AIO_DIRECT',
    activationStatus: 'LIMITED_PILOT',
    jurisdictionDependent: false,
    defaultJurisdictionAvailability: 'AVAILABLE',
    pricingModel: 'quote_required',
    quoteRequired: true,
    documentsRequired: true,
    roadReadyApplicable: true,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'QUOTE_REQUIRED',
    icon: 'formation',
    cta: 'Request Assistance',
  },
  {
    id: 'startup',
    slug: 'trucking-business-startup',
    name: 'Trucking Business Startup',
    shortDescription: 'End-to-end startup guidance package.',
    description: 'Comprehensive startup coordination from formation through initial registrations.',
    category: 'start-my-business',
    legacyDivision: 'business-formation',
    fulfillmentType: 'AIO_MANAGED',
    activationStatus: 'LIMITED_PILOT',
    jurisdictionDependent: false,
    defaultJurisdictionAvailability: 'AVAILABLE',
    pricingModel: 'quote_required',
    quoteRequired: true,
    documentsRequired: true,
    workflowTemplateSlug: 'new-carrier-startup',
    roadReadyApplicable: true,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'QUOTE_REQUIRED',
    icon: 'startup',
    cta: 'Get Started',
  },
  {
    id: 'business-consult',
    slug: 'business-setup-consultation',
    name: 'Startup Consultation',
    shortDescription: 'One-on-one startup consultation.',
    description: 'Consultation to understand your startup path — preliminary guidance only.',
    category: 'start-my-business',
    legacyDivision: 'business-formation',
    fulfillmentType: 'AIO_DIRECT',
    activationStatus: 'ACTIVE',
    jurisdictionDependent: false,
    defaultJurisdictionAvailability: 'AVAILABLE',
    pricingModel: 'contact_us',
    quoteRequired: false,
    documentsRequired: false,
    roadReadyApplicable: false,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'QUOTE_REQUIRED',
    icon: 'formation',
    cta: 'Request Consultation',
  },

  // ── GET ROAD READY ──
  {
    id: 'usdot',
    slug: 'usdot-registration',
    name: 'USDOT Registration',
    shortDescription: 'USDOT number registration assistance.',
    description: 'Assistance with USDOT number registration for qualifying motor carriers.',
    category: 'get-road-ready',
    discoveryCategories: ['permits-taxes-compliance'],
    legacyDivision: 'permitting',
    fulfillmentType: 'AIO_DIRECT',
    activationStatus: 'LIMITED_PILOT',
    jurisdictionDependent: false,
    defaultJurisdictionAvailability: 'AVAILABLE',
    pricingModel: 'quote_required',
    quoteRequired: true,
    documentsRequired: true,
    workflowTemplateSlug: 'usdot-registration',
    roadReadyApplicable: true,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'QUOTE_REQUIRED',
    icon: 'permitting',
    cta: 'Request Assistance',
    publicDisclosure: 'All In One provides administrative filing assistance — not FMCSA.',
  },
  {
    id: 'operating-authority',
    slug: 'operating-authority-assistance',
    name: 'MC / Operating Authority',
    shortDescription: 'Guidance on USDOT and MC operating authority.',
    description: 'Assistance navigating operating authority requirements for motor carriers.',
    category: 'get-road-ready',
    discoveryCategories: ['permits-taxes-compliance'],
    legacyDivision: 'permitting',
    fulfillmentType: 'AIO_DIRECT',
    activationStatus: 'LIMITED_PILOT',
    jurisdictionDependent: false,
    defaultJurisdictionAvailability: 'AVAILABLE',
    pricingModel: 'quote_required',
    quoteRequired: true,
    documentsRequired: true,
    workflowTemplateSlug: 'operating-authority',
    renewalInterval: 'as_needed',
    roadReadyApplicable: true,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'QUOTE_REQUIRED',
    icon: 'permitting',
    cta: 'Request Assistance',
  },
  {
    id: 'authority-maintenance',
    slug: 'authority-maintenance',
    name: 'Authority Maintenance',
    shortDescription: 'Ongoing authority status and maintenance support.',
    description: 'Track authority status, updates, renewals where applicable, and related compliance alerts.',
    category: 'permits-taxes-compliance',
    discoveryCategories: ['get-road-ready'],
    legacyDivision: 'permitting',
    fulfillmentType: 'AIO_MANAGED',
    activationStatus: 'PREPARING',
    jurisdictionDependent: false,
    defaultJurisdictionAvailability: 'AVAILABLE',
    pricingModel: 'quote_required',
    quoteRequired: true,
    documentsRequired: true,
    workflowTemplateSlug: 'authority-maintenance',
    renewalInterval: 'as_needed',
    roadReadyApplicable: true,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'QUOTE_REQUIRED',
    icon: 'permitting',
    cta: 'Request Service',
  },
  {
    id: 'boc3',
    slug: 'boc-3-assistance',
    name: 'BOC-3',
    shortDescription: 'Process agent designation filing support.',
    description: 'BOC-3 filing assistance — designates process agents for federally regulated motor carriers.',
    category: 'get-road-ready',
    legacyDivision: 'permitting',
    fulfillmentType: null,
    activationStatus: 'COMING_SOON',
    jurisdictionDependent: false,
    defaultJurisdictionAvailability: 'CONTACT_US',
    pricingModel: 'quote_required',
    quoteRequired: true,
    documentsRequired: true,
    workflowTemplateSlug: 'boc-3',
    roadReadyApplicable: true,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'QUOTE_REQUIRED',
    icon: 'permitting',
    cta: 'Request Information',
  },
  {
    id: 'ucr-registration',
    slug: 'ucr-registration',
    name: 'UCR Registration',
    shortDescription: 'New UCR registration assistance.',
    description: 'Unified Carrier Registration setup — applicability varies by operation type and fleet.',
    category: 'get-road-ready',
    discoveryCategories: ['permits-taxes-compliance'],
    legacyDivision: 'permitting',
    fulfillmentType: null,
    activationStatus: 'PREPARING',
    jurisdictionDependent: false,
    defaultJurisdictionAvailability: 'AVAILABLE',
    pricingModel: 'quote_required',
    quoteRequired: true,
    documentsRequired: true,
    workflowTemplateSlug: 'ucr-registration',
    renewalInterval: 'annual',
    roadReadyApplicable: true,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'QUOTE_REQUIRED',
    icon: 'ucr',
    cta: 'Request Service',
  },
  {
    id: 'ucr-renewal',
    slug: 'ucr-renewal',
    name: 'UCR Renewal',
    shortDescription: 'Annual UCR renewal assistance.',
    description: 'UCR renewal tracking, document collection, and filing coordination.',
    category: 'permits-taxes-compliance',
    discoveryCategories: ['get-road-ready'],
    legacyDivision: 'permitting',
    fulfillmentType: null,
    activationStatus: 'PREPARING',
    jurisdictionDependent: false,
    defaultJurisdictionAvailability: 'AVAILABLE',
    pricingModel: 'quote_required',
    quoteRequired: true,
    documentsRequired: true,
    workflowTemplateSlug: 'ucr-renewal',
    renewalInterval: 'annual',
    roadReadyApplicable: true,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'QUOTE_REQUIRED',
    icon: 'ucr',
    cta: 'Request Renewal',
  },
  {
    id: 'hvut-2290',
    slug: 'hvut-form-2290',
    name: 'HVUT / Form 2290 Assistance',
    shortDescription: 'Heavy vehicle use tax filing assistance.',
    description: 'HVUT / Form 2290 support — vehicle and tax-year information, document collection, and filing workflow. All In One is not the IRS.',
    category: 'get-road-ready',
    discoveryCategories: ['permits-taxes-compliance'],
    legacyDivision: 'permitting',
    fulfillmentType: null,
    activationStatus: 'PREPARING',
    jurisdictionDependent: false,
    defaultJurisdictionAvailability: 'AVAILABLE',
    pricingModel: 'quote_required',
    quoteRequired: true,
    documentsRequired: true,
    workflowTemplateSlug: 'hvut-form-2290',
    renewalInterval: 'annual',
    roadReadyApplicable: true,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'QUOTE_REQUIRED',
    icon: 'hvut',
    cta: 'Request Assistance',
    publicDisclosure: 'Filing completion is confirmed only when the approved workflow confirms submission.',
  },
  {
    id: 'irp',
    slug: 'irp-apportioned-registration',
    name: 'IRP / Apportioned Registration',
    shortDescription: 'Guidance for apportioned registration.',
    description: 'IRP apportioned registration assistance for qualifying interstate operations.',
    category: 'get-road-ready',
    discoveryCategories: ['permits-taxes-compliance'],
    legacyDivision: 'permitting',
    fulfillmentType: 'AIO_MANAGED',
    activationStatus: 'LIMITED_PILOT',
    jurisdictionDependent: true,
    defaultJurisdictionAvailability: 'LIMITED',
    pricingModel: 'quote_required',
    quoteRequired: true,
    documentsRequired: true,
    workflowTemplateSlug: 'irp-registration',
    renewalInterval: 'annual',
    roadReadyApplicable: true,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'QUOTE_REQUIRED',
    icon: 'permitting',
    cta: 'Request Assistance',
  },
  {
    id: 'ifta-reg',
    slug: 'ifta-fuel-tax-assistance',
    name: 'IFTA Registration',
    shortDescription: 'Support for fuel tax reporting accounts.',
    description: 'Assistance with IFTA account setup and ongoing fuel tax reporting coordination.',
    category: 'get-road-ready',
    discoveryCategories: ['permits-taxes-compliance'],
    legacyDivision: 'permitting',
    fulfillmentType: 'AIO_DIRECT',
    activationStatus: 'LIMITED_PILOT',
    jurisdictionDependent: false,
    defaultJurisdictionAvailability: 'AVAILABLE',
    pricingModel: 'quote_required',
    quoteRequired: true,
    documentsRequired: true,
    workflowTemplateSlug: 'ifta-registration',
    renewalInterval: 'quarterly',
    roadReadyApplicable: true,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'QUOTE_REQUIRED',
    icon: 'permitting',
    cta: 'Request Assistance',
  },
  {
    id: 'ifta-filing',
    slug: 'ifta-filing',
    name: 'IFTA Filing',
    shortDescription: 'Quarterly IFTA filing assistance.',
    description: 'IFTA quarterly filing coordination and document support.',
    category: 'permits-taxes-compliance',
    legacyDivision: 'permitting',
    fulfillmentType: 'AIO_DIRECT',
    activationStatus: 'PREPARING',
    jurisdictionDependent: false,
    defaultJurisdictionAvailability: 'AVAILABLE',
    pricingModel: 'quote_required',
    quoteRequired: true,
    documentsRequired: true,
    renewalInterval: 'quarterly',
    roadReadyApplicable: false,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'QUOTE_REQUIRED',
    icon: 'permitting',
    cta: 'Request Filing',
  },
  {
    id: 'road-tax',
    slug: 'road-tax-assistance',
    name: 'Road / Use Taxes',
    shortDescription: 'Review of highway use and road tax accounts.',
    description: 'Guidance on road tax and highway use accounts that may apply to your operation.',
    category: 'permits-taxes-compliance',
    discoveryCategories: ['get-road-ready'],
    legacyDivision: 'permitting',
    fulfillmentType: 'AIO_DIRECT',
    activationStatus: 'LIMITED_PILOT',
    jurisdictionDependent: true,
    defaultJurisdictionAvailability: 'LIMITED',
    pricingModel: 'quote_required',
    quoteRequired: true,
    documentsRequired: true,
    roadReadyApplicable: true,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'QUOTE_REQUIRED',
    icon: 'permitting',
    cta: 'Request Assistance',
  },
  {
    id: 'mcs150',
    slug: 'mcs-150-biennial-update',
    name: 'DOT Biennial Update / MCS-150',
    shortDescription: 'Biennial update filing assistance.',
    description: 'MCS-150 biennial update support — business and fleet information review, submission workflow, and next due date tracking.',
    category: 'permits-taxes-compliance',
    discoveryCategories: ['get-road-ready'],
    legacyDivision: 'permitting',
    fulfillmentType: null,
    activationStatus: 'PREPARING',
    jurisdictionDependent: false,
    defaultJurisdictionAvailability: 'AVAILABLE',
    pricingModel: 'quote_required',
    quoteRequired: true,
    documentsRequired: true,
    workflowTemplateSlug: 'mcs-150-update',
    renewalInterval: 'biennial',
    roadReadyApplicable: true,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'QUOTE_REQUIRED',
    icon: 'mcs150',
    cta: 'Request Update',
  },
  {
    id: 'tag-services',
    slug: 'tag-services',
    name: 'Tag / Plate Services',
    shortDescription: 'Commercial vehicle tags and registration assistance.',
    description: 'Tag and plate request, renewal, replacement — requirements vary by jurisdiction.',
    category: 'get-road-ready',
    discoveryCategories: ['operate-my-business'],
    legacyDivision: 'permitting',
    fulfillmentType: null,
    activationStatus: 'PREPARING',
    jurisdictionDependent: true,
    defaultJurisdictionAvailability: 'LIMITED',
    pricingModel: 'quote_required',
    quoteRequired: true,
    documentsRequired: true,
    workflowTemplateSlug: 'tag-plate-service',
    renewalInterval: 'annual',
    roadReadyApplicable: true,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'QUOTE_REQUIRED',
    icon: 'tags',
    cta: 'Request Assistance',
  },
  {
    id: 'title-services',
    slug: 'title-services',
    name: 'Title Services',
    shortDescription: 'Title transfer and registration-related title support.',
    description: 'New title, title transfer, and related documentation — availability varies by state.',
    category: 'get-road-ready',
    discoveryCategories: ['operate-my-business'],
    legacyDivision: 'permitting',
    fulfillmentType: null,
    activationStatus: 'PREPARING',
    jurisdictionDependent: true,
    defaultJurisdictionAvailability: 'LIMITED',
    pricingModel: 'quote_required',
    quoteRequired: true,
    documentsRequired: true,
    workflowTemplateSlug: 'title-service',
    roadReadyApplicable: true,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'QUOTE_REQUIRED',
    icon: 'title',
    cta: 'Request Service',
  },
  {
    id: 'commercial-insurance',
    slug: 'commercial-auto-liability',
    name: 'Commercial Trucking Insurance',
    shortDescription: 'Liability coverage quote assistance.',
    description: 'Request assistance exploring commercial auto liability coverage — All In One is not the licensed insurer.',
    category: 'get-road-ready',
    discoveryCategories: ['operate-my-business'],
    legacyDivision: 'insurance',
    fulfillmentType: 'PARTNER_PROVIDED',
    activationStatus: 'LIMITED_PILOT',
    jurisdictionDependent: true,
    defaultJurisdictionAvailability: 'PARTNER_PROVIDED',
    pricingModel: 'quote_required',
    quoteRequired: true,
    documentsRequired: true,
    workflowTemplateSlug: 'insurance-assistance',
    renewalInterval: 'annual',
    roadReadyApplicable: true,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'REFERRAL_ONLY',
    providerRequirements: ['insurance'],
    icon: 'insurance',
    cta: 'Request Quote',
    publicDisclosure: 'Coverage is provided by licensed insurers — All In One facilitates quotes and coordination.',
  },
  {
    id: 'eld-services',
    slug: 'eld-services',
    name: 'ELD Services',
    shortDescription: 'ELD setup assistance and provider coordination.',
    description: 'Tell us about your fleet — recommended ELD service, provider setup, vehicle and driver assignment. All In One does not manufacture ELD hardware.',
    category: 'safety-drivers',
    discoveryCategories: ['get-road-ready', 'operate-my-business'],
    legacyDivision: 'permitting',
    fulfillmentType: 'HYBRID',
    activationStatus: 'PREPARING',
    jurisdictionDependent: false,
    defaultJurisdictionAvailability: 'AVAILABLE',
    pricingModel: 'quote_required',
    quoteRequired: true,
    documentsRequired: true,
    workflowTemplateSlug: 'eld-service',
    renewalInterval: 'annual',
    roadReadyApplicable: true,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'QUOTE_REQUIRED',
    providerRequirements: ['eld'],
    icon: 'eld',
    cta: 'Request Service',
  },
  {
    id: 'drug-alcohol-consortium',
    slug: 'drug-alcohol-consortium',
    name: 'Drug & Alcohol Consortium Services',
    shortDescription: 'Consortium enrollment and coordination.',
    description: 'Drug and alcohol consortium enrollment — provider relationship disclosed per configuration.',
    category: 'safety-drivers',
    discoveryCategories: ['get-road-ready'],
    fulfillmentType: null,
    activationStatus: 'PREPARING',
    jurisdictionDependent: false,
    defaultJurisdictionAvailability: 'AVAILABLE',
    pricingModel: 'quote_required',
    quoteRequired: true,
    documentsRequired: true,
    workflowTemplateSlug: 'drug-alcohol-consortium',
    renewalInterval: 'annual',
    roadReadyApplicable: true,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'QUOTE_REQUIRED',
    providerRequirements: ['drug_alcohol_consortium'],
    icon: 'consortium',
    cta: 'Request Enrollment',
  },
  {
    id: 'clearinghouse',
    slug: 'fmcsa-clearinghouse-assistance',
    name: 'FMCSA Clearinghouse Assistance',
    shortDescription: 'Clearinghouse registration and query workflow support.',
    description: 'Registration assistance, query-related workflow support, and compliance reminders. Sensitive data minimized.',
    category: 'safety-drivers',
    discoveryCategories: ['get-road-ready'],
    fulfillmentType: 'AIO_MANAGED',
    activationStatus: 'PREPARING',
    jurisdictionDependent: false,
    defaultJurisdictionAvailability: 'AVAILABLE',
    pricingModel: 'quote_required',
    quoteRequired: true,
    documentsRequired: true,
    workflowTemplateSlug: 'clearinghouse-assistance',
    roadReadyApplicable: true,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'QUOTE_REQUIRED',
    icon: 'clearinghouse',
    cta: 'Request Assistance',
  },

  // ── PERMITS, TAXES & COMPLIANCE ──
  {
    id: 'trip-permits',
    slug: 'trip-permits',
    name: 'Trip Permits',
    shortDescription: 'Temporary permit coordination.',
    description: 'Assistance obtaining temporary permits when needed for specific trips or states.',
    category: 'permits-taxes-compliance',
    legacyDivision: 'permitting',
    fulfillmentType: 'AIO_DIRECT',
    activationStatus: 'LIMITED_PILOT',
    jurisdictionDependent: true,
    defaultJurisdictionAvailability: 'LIMITED',
    pricingModel: 'quote_required',
    quoteRequired: true,
    documentsRequired: true,
    roadReadyApplicable: false,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'QUOTE_REQUIRED',
    icon: 'permitting',
    cta: 'Request Assistance',
  },
  {
    id: 'temp-permits',
    slug: 'temporary-permits',
    name: 'Temporary / Specialty Permits',
    shortDescription: 'Short-term and specialty permit assistance.',
    description: 'Coordination for temporary operating permits across applicable states.',
    category: 'permits-taxes-compliance',
    legacyDivision: 'permitting',
    fulfillmentType: 'AIO_DIRECT',
    activationStatus: 'PREPARING',
    jurisdictionDependent: true,
    defaultJurisdictionAvailability: 'LIMITED',
    pricingModel: 'quote_required',
    quoteRequired: true,
    documentsRequired: true,
    roadReadyApplicable: false,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'QUOTE_REQUIRED',
    icon: 'permitting',
    cta: 'Request Assistance',
  },
  {
    id: 'renewals',
    slug: 'renewals',
    name: 'Renewals',
    shortDescription: 'Renewal tracking and filing assistance.',
    description: 'Support managing registration, permit, and authority renewals.',
    category: 'permits-taxes-compliance',
    legacyDivision: 'permitting',
    fulfillmentType: 'AIO_MANAGED',
    activationStatus: 'ACTIVE',
    jurisdictionDependent: false,
    defaultJurisdictionAvailability: 'AVAILABLE',
    pricingModel: 'quote_required',
    quoteRequired: true,
    documentsRequired: true,
    workflowTemplateSlug: 'renewal',
    roadReadyApplicable: false,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'QUOTE_REQUIRED',
    icon: 'permitting',
    cta: 'View Renewals',
  },
  {
    id: 'compliance-support',
    slug: 'compliance-support',
    name: 'Compliance Support',
    shortDescription: 'Ongoing compliance administration.',
    description: 'Assistance with filings, renewals, deadlines, and document organization.',
    category: 'permits-taxes-compliance',
    legacyDivision: 'permitting',
    fulfillmentType: 'AIO_DIRECT',
    activationStatus: 'ACTIVE',
    jurisdictionDependent: false,
    defaultJurisdictionAvailability: 'AVAILABLE',
    pricingModel: 'quote_required',
    quoteRequired: true,
    documentsRequired: true,
    roadReadyApplicable: false,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'QUOTE_REQUIRED',
    icon: 'compliance',
    cta: 'Request Assistance',
  },
  {
    id: 'dot-compliance',
    slug: 'dot-compliance-support',
    name: 'DOT Compliance Support',
    shortDescription: 'Umbrella ongoing DOT compliance assistance.',
    description: 'Document reviews, deadline management, renewal coordination, and record organization — no guaranteed compliance.',
    category: 'safety-drivers',
    discoveryCategories: ['permits-taxes-compliance'],
    legacyDivision: 'permitting',
    fulfillmentType: 'AIO_MANAGED',
    activationStatus: 'PREPARING',
    jurisdictionDependent: false,
    defaultJurisdictionAvailability: 'AVAILABLE',
    pricingModel: 'quote_required',
    quoteRequired: true,
    documentsRequired: true,
    workflowTemplateSlug: 'dot-compliance-support',
    roadReadyApplicable: false,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'QUOTE_REQUIRED',
    icon: 'compliance',
    cta: 'Request Support',
  },

  // ── SAFETY & DRIVERS ──
  {
    id: 'dq-files',
    slug: 'driver-qualification-files',
    name: 'Driver Qualification File Management',
    shortDescription: 'DQ file status, documents, and renewal reminders.',
    description: 'Driver profile, required documents, expiration tracking, and staff review — uses Document Vault infrastructure.',
    category: 'safety-drivers',
    fulfillmentType: 'AIO_DIRECT',
    activationStatus: 'PREPARING',
    jurisdictionDependent: false,
    defaultJurisdictionAvailability: 'AVAILABLE',
    pricingModel: 'quote_required',
    quoteRequired: true,
    documentsRequired: true,
    workflowTemplateSlug: 'dq-file-setup',
    roadReadyApplicable: true,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'QUOTE_REQUIRED',
    icon: 'dq-files',
    cta: 'Request Setup',
  },
  {
    id: 'dot-audit',
    slug: 'dot-audit-support',
    name: 'DOT Audit Support',
    shortDescription: 'Audit readiness and document checklist support.',
    description: 'Audit support request, document collection, readiness review — no guarantee of audit outcome or legal representation.',
    category: 'safety-drivers',
    fulfillmentType: null,
    activationStatus: 'PREPARING',
    jurisdictionDependent: false,
    defaultJurisdictionAvailability: 'AVAILABLE',
    pricingModel: 'quote_required',
    quoteRequired: true,
    documentsRequired: true,
    workflowTemplateSlug: 'dot-audit-support',
    roadReadyApplicable: false,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'QUOTE_REQUIRED',
    icon: 'dot-audit',
    cta: 'Request Support',
  },
  {
    id: 'new-entrant-audit',
    slug: 'new-entrant-audit-support',
    name: 'New Entrant Audit Support',
    shortDescription: 'New entrant safety audit preparation.',
    description: 'Document checklist, collection, and readiness review for new entrant audits.',
    category: 'safety-drivers',
    fulfillmentType: null,
    activationStatus: 'PREPARING',
    jurisdictionDependent: false,
    defaultJurisdictionAvailability: 'AVAILABLE',
    pricingModel: 'quote_required',
    quoteRequired: true,
    documentsRequired: true,
    workflowTemplateSlug: 'new-entrant-audit-support',
    roadReadyApplicable: true,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'QUOTE_REQUIRED',
    icon: 'dot-audit',
    cta: 'Request Support',
  },
  {
    id: 'safety-programs',
    slug: 'safety-compliance-programs',
    name: 'Safety & Compliance Programs',
    shortDescription: 'Configurable safety and compliance program enrollment.',
    description: 'Umbrella for approved safety and compliance offerings — activated individually per configuration.',
    category: 'safety-drivers',
    fulfillmentType: 'HYBRID',
    activationStatus: 'PREPARING',
    jurisdictionDependent: false,
    defaultJurisdictionAvailability: 'CONTACT_US',
    pricingModel: 'contact_us',
    quoteRequired: true,
    documentsRequired: true,
    workflowTemplateSlug: 'safety-program-enrollment',
    roadReadyApplicable: false,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'QUOTE_REQUIRED',
    icon: 'safety',
    cta: 'Contact Us',
  },

  // ── OPERATE MY BUSINESS ──
  {
    id: 'dispatch',
    slug: 'carrier-dispatch-support',
    name: 'Dispatching',
    shortDescription: 'Dispatch support to keep your truck moving.',
    description: 'Operational dispatch assistance — does not guarantee freight or revenue.',
    category: 'operate-my-business',
    legacyDivision: 'dispatching',
    fulfillmentType: 'AIO_DIRECT',
    activationStatus: 'ACTIVE',
    jurisdictionDependent: false,
    defaultJurisdictionAvailability: 'AVAILABLE',
    pricingModel: 'quote_required',
    quoteRequired: true,
    documentsRequired: true,
    workflowTemplateSlug: 'dispatch-onboarding',
    roadReadyApplicable: false,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'QUOTE_REQUIRED',
    icon: 'dispatching',
    cta: 'Request Assistance',
  },
  {
    id: 'load-coord',
    slug: 'load-coordination',
    name: 'Load Coordination',
    shortDescription: 'Load booking and coordination support.',
    description: 'Assistance coordinating loads for your operation.',
    category: 'operate-my-business',
    legacyDivision: 'dispatching',
    fulfillmentType: 'AIO_DIRECT',
    activationStatus: 'ACTIVE',
    jurisdictionDependent: false,
    defaultJurisdictionAvailability: 'AVAILABLE',
    pricingModel: 'quote_required',
    quoteRequired: true,
    documentsRequired: false,
    roadReadyApplicable: false,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'QUOTE_REQUIRED',
    icon: 'dispatching',
    cta: 'Request Assistance',
  },
  {
    id: 'doc-support',
    slug: 'document-support',
    name: 'Document Management',
    shortDescription: 'Operational document support.',
    description: 'Assistance managing operational documents — rate confirmations, POD, and related records.',
    category: 'operate-my-business',
    legacyDivision: 'dispatching',
    fulfillmentType: 'AIO_DIRECT',
    activationStatus: 'ACTIVE',
    jurisdictionDependent: false,
    defaultJurisdictionAvailability: 'AVAILABLE',
    pricingModel: 'quote_required',
    quoteRequired: false,
    documentsRequired: false,
    roadReadyApplicable: false,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'QUOTE_REQUIRED',
    icon: 'dispatching',
    cta: 'Request Assistance',
  },
  {
    id: 'ops-support',
    slug: 'operational-support',
    name: 'Operational Support',
    shortDescription: 'General carrier operational assistance.',
    description: 'Broader operational support for running your trucking business day-to-day.',
    category: 'operate-my-business',
    legacyDivision: 'dispatching',
    fulfillmentType: 'AIO_DIRECT',
    activationStatus: 'ACTIVE',
    jurisdictionDependent: false,
    defaultJurisdictionAvailability: 'AVAILABLE',
    pricingModel: 'quote_required',
    quoteRequired: true,
    documentsRequired: false,
    roadReadyApplicable: false,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'QUOTE_REQUIRED',
    icon: 'dispatching',
    cta: 'Request Assistance',
  },
  {
    id: 'cargo',
    slug: 'cargo-coverage',
    name: 'Cargo Coverage',
    shortDescription: 'Cargo insurance quote assistance.',
    description: 'Assistance exploring cargo coverage options.',
    category: 'operate-my-business',
    discoveryCategories: ['get-road-ready'],
    legacyDivision: 'insurance',
    fulfillmentType: 'PARTNER_PROVIDED',
    activationStatus: 'LIMITED_PILOT',
    jurisdictionDependent: true,
    defaultJurisdictionAvailability: 'PARTNER_PROVIDED',
    pricingModel: 'quote_required',
    quoteRequired: true,
    documentsRequired: true,
    renewalInterval: 'annual',
    roadReadyApplicable: false,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'REFERRAL_ONLY',
    providerRequirements: ['insurance'],
    icon: 'insurance',
    cta: 'Request Quote',
  },
  {
    id: 'physical-damage',
    slug: 'physical-damage',
    name: 'Physical Damage',
    shortDescription: 'Physical damage coverage quote assistance.',
    description: 'Explore physical damage coverage for power units and equipment.',
    category: 'operate-my-business',
    legacyDivision: 'insurance',
    fulfillmentType: 'PARTNER_PROVIDED',
    activationStatus: 'LIMITED_PILOT',
    jurisdictionDependent: true,
    defaultJurisdictionAvailability: 'PARTNER_PROVIDED',
    pricingModel: 'quote_required',
    quoteRequired: true,
    documentsRequired: true,
    roadReadyApplicable: false,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'REFERRAL_ONLY',
    providerRequirements: ['insurance'],
    icon: 'insurance',
    cta: 'Request Quote',
  },
  {
    id: 'insurance-review',
    slug: 'general-transportation-insurance-review',
    name: 'Insurance Review',
    shortDescription: 'Holistic insurance review for your operation.',
    description: 'Recommended preliminary review of transportation coverage needs.',
    category: 'operate-my-business',
    discoveryCategories: ['get-road-ready'],
    legacyDivision: 'insurance',
    fulfillmentType: 'PARTNER_PROVIDED',
    activationStatus: 'LIMITED_PILOT',
    jurisdictionDependent: false,
    defaultJurisdictionAvailability: 'AVAILABLE',
    pricingModel: 'quote_required',
    quoteRequired: true,
    documentsRequired: false,
    roadReadyApplicable: true,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'REFERRAL_ONLY',
    providerRequirements: ['insurance'],
    icon: 'insurance',
    cta: 'Request Review',
  },

  // ── MOVE FREIGHT ──
  {
    id: 'freight-quote',
    slug: 'freight-quote',
    name: 'Freight Quote',
    shortDescription: 'Request a preliminary freight quote.',
    description: 'Shipper-focused freight quote request — subject to review, not a guaranteed rate.',
    category: 'move-freight',
    legacyDivision: 'brokerage',
    fulfillmentType: 'AIO_DIRECT',
    activationStatus: 'COMING_SOON',
    jurisdictionDependent: false,
    defaultJurisdictionAvailability: 'CONTACT_US',
    pricingModel: 'quote_required',
    quoteRequired: true,
    documentsRequired: false,
    roadReadyApplicable: false,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'QUOTE_REQUIRED',
    icon: 'brokerage',
    cta: 'Request a Quote',
  },
  {
    id: 'shipment-coord',
    slug: 'shipment-coordination',
    name: 'Shipment Coordination',
    shortDescription: 'End-to-end shipment coordination.',
    description: 'Coordination support once your freight quote is reviewed.',
    category: 'move-freight',
    legacyDivision: 'brokerage',
    fulfillmentType: 'AIO_DIRECT',
    activationStatus: 'COMING_SOON',
    jurisdictionDependent: false,
    defaultJurisdictionAvailability: 'CONTACT_US',
    pricingModel: 'quote_required',
    quoteRequired: true,
    documentsRequired: true,
    roadReadyApplicable: false,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'QUOTE_REQUIRED',
    icon: 'brokerage',
    cta: 'Request Assistance',
  },
  {
    id: 'shipper-services',
    slug: 'shipper-services',
    name: 'Shipper Services',
    shortDescription: 'Comprehensive shipper support.',
    description: 'Broader shipper services including quotes, coordination, and tracking.',
    category: 'move-freight',
    legacyDivision: 'brokerage',
    fulfillmentType: 'AIO_DIRECT',
    activationStatus: 'COMING_SOON',
    jurisdictionDependent: false,
    defaultJurisdictionAvailability: 'CONTACT_US',
    pricingModel: 'quote_required',
    quoteRequired: true,
    documentsRequired: true,
    roadReadyApplicable: false,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'QUOTE_REQUIRED',
    icon: 'brokerage',
    cta: 'Request Assistance',
  },
  {
    id: 'recurring-freight',
    slug: 'recurring-freight-support',
    name: 'Recurring Freight Support',
    shortDescription: 'Ongoing freight coordination for repeat lanes.',
    description: 'Support for businesses with recurring freight needs.',
    category: 'move-freight',
    legacyDivision: 'brokerage',
    fulfillmentType: 'AIO_DIRECT',
    activationStatus: 'COMING_SOON',
    jurisdictionDependent: false,
    defaultJurisdictionAvailability: 'CONTACT_US',
    pricingModel: 'quote_required',
    quoteRequired: true,
    documentsRequired: false,
    roadReadyApplicable: false,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'QUOTE_REQUIRED',
    icon: 'brokerage',
    cta: 'Request Assistance',
  },

  // ── MANAGE MY MONEY ──
  {
    id: 'bookkeeping',
    slug: 'bookkeeping',
    name: 'Trucking Bookkeeping',
    shortDescription: 'Bookkeeping built for trucking — Essentials, Plus, and All In One plans.',
    description: 'Recurring bookkeeping organized around carrier operations.',
    category: 'manage-my-money',
    discoveryCategories: ['operate-my-business'],
    legacyDivision: 'bookkeeping',
    fulfillmentType: 'AIO_DIRECT',
    activationStatus: 'LIMITED_PILOT',
    jurisdictionDependent: false,
    defaultJurisdictionAvailability: 'AVAILABLE',
    pricingModel: 'starting_at',
    quoteRequired: false,
    documentsRequired: true,
    workflowTemplateSlug: 'bookkeeping-onboarding',
    renewalInterval: 'monthly',
    roadReadyApplicable: false,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'AIO_COLLECTS',
    icon: 'bookkeeping',
    cta: 'View Plans',
    relatedSlugs: ['books-rescue', 'bookkeeping-essentials', 'bookkeeping-plus', 'all-in-one-bookkeeping'],
  },
  {
    id: 'books-rescue',
    slug: 'books-rescue',
    name: 'Books Rescue',
    shortDescription: 'One-time historical cleanup before recurring bookkeeping.',
    description: 'Cleanup for behind, uncategorized, or unreconciled books — starting at $499; final quote after review.',
    category: 'manage-my-money',
    legacyDivision: 'bookkeeping',
    fulfillmentType: 'AIO_DIRECT',
    activationStatus: 'LIMITED_PILOT',
    jurisdictionDependent: false,
    defaultJurisdictionAvailability: 'AVAILABLE',
    pricingModel: 'starting_at',
    quoteRequired: false,
    documentsRequired: true,
    workflowTemplateSlug: 'books-rescue-cleanup',
    roadReadyApplicable: false,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'AIO_COLLECTS',
    icon: 'bookkeeping',
    cta: 'Start Assessment',
  },
  {
    id: 'bk-essentials',
    slug: 'bookkeeping-essentials',
    name: 'Bookkeeping Essentials',
    shortDescription: 'Starting at $249/month — foundational monthly bookkeeping.',
    description: 'Monthly bookkeeping, categorization, reconciliations, and monthly P&L.',
    category: 'manage-my-money',
    legacyDivision: 'bookkeeping',
    fulfillmentType: 'AIO_DIRECT',
    activationStatus: 'LIMITED_PILOT',
    jurisdictionDependent: false,
    defaultJurisdictionAvailability: 'AVAILABLE',
    pricingModel: 'starting_at',
    quoteRequired: false,
    documentsRequired: true,
    roadReadyApplicable: false,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'AIO_COLLECTS',
    icon: 'bookkeeping',
    cta: 'Request Essentials',
  },
  {
    id: 'bk-plus',
    slug: 'bookkeeping-plus',
    name: 'Bookkeeping Plus',
    shortDescription: 'Starting at $449/month — deeper reporting and reconciliation.',
    description: 'Essentials plus balance sheet, cash flow, factoring/load reconciliation, and quarterly review.',
    category: 'manage-my-money',
    legacyDivision: 'bookkeeping',
    fulfillmentType: 'AIO_DIRECT',
    activationStatus: 'LIMITED_PILOT',
    jurisdictionDependent: false,
    defaultJurisdictionAvailability: 'AVAILABLE',
    pricingModel: 'starting_at',
    quoteRequired: false,
    documentsRequired: true,
    roadReadyApplicable: false,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'AIO_COLLECTS',
    icon: 'bookkeeping',
    cta: 'Request Plus',
  },
  {
    id: 'bk-all-in-one',
    slug: 'all-in-one-bookkeeping',
    name: 'All In One Bookkeeping',
    shortDescription: 'Starting at $749/month — full back-office bookkeeping.',
    description: 'Comprehensive bookkeeping including payroll reconciliation — distinct from Payroll Services processing.',
    category: 'manage-my-money',
    legacyDivision: 'bookkeeping',
    fulfillmentType: 'AIO_DIRECT',
    activationStatus: 'LIMITED_PILOT',
    jurisdictionDependent: false,
    defaultJurisdictionAvailability: 'AVAILABLE',
    pricingModel: 'starting_at',
    quoteRequired: false,
    documentsRequired: true,
    roadReadyApplicable: false,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'AIO_COLLECTS',
    icon: 'bookkeeping',
    cta: 'Request All In One Bookkeeping',
  },
  {
    id: 'factoring-consult',
    slug: 'factoring-consultation',
    name: 'Factoring',
    shortDescription: 'Explore invoice funding options through approved partners.',
    description: 'Preliminary factoring review — partner referral model; All In One does not fund receivables.',
    category: 'manage-my-money',
    discoveryCategories: ['operate-my-business'],
    legacyDivision: 'factoring',
    fulfillmentType: 'PARTNER_PROVIDED',
    activationStatus: 'LIMITED_PILOT',
    jurisdictionDependent: false,
    defaultJurisdictionAvailability: 'PARTNER_PROVIDED',
    pricingModel: 'quote_required',
    quoteRequired: true,
    documentsRequired: true,
    workflowTemplateSlug: 'factoring-onboarding',
    roadReadyApplicable: false,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'REFERRAL_ONLY',
    providerRequirements: ['factoring'],
    icon: 'factoring',
    cta: 'Request Consultation',
    publicDisclosure: 'Service fulfilled through an approved AIO partner.',
  },
  {
    id: 'invoice-factoring',
    slug: 'invoice-factoring',
    name: 'Invoice Factoring',
    shortDescription: 'Explore invoice funding options.',
    description: 'Preliminary factoring review — not an approval or funding guarantee.',
    category: 'manage-my-money',
    legacyDivision: 'factoring',
    fulfillmentType: 'PARTNER_PROVIDED',
    activationStatus: 'LIMITED_PILOT',
    jurisdictionDependent: false,
    defaultJurisdictionAvailability: 'PARTNER_PROVIDED',
    pricingModel: 'quote_required',
    quoteRequired: true,
    documentsRequired: true,
    roadReadyApplicable: false,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'REFERRAL_ONLY',
    providerRequirements: ['factoring'],
    icon: 'factoring',
    cta: 'Request Consultation',
    publicDisclosure: 'Service fulfilled through an approved AIO partner.',
  },
  {
    id: 'payroll',
    slug: 'payroll-services',
    name: 'Payroll Services',
    shortDescription: 'Payroll setup and processing workflow support.',
    description: 'Payroll setup, employee/contractor support, and processing coordination — distinct from payroll bookkeeping reconciliation.',
    category: 'manage-my-money',
    fulfillmentType: null,
    activationStatus: 'PREPARING',
    jurisdictionDependent: false,
    defaultJurisdictionAvailability: 'AVAILABLE',
    pricingModel: 'quote_required',
    quoteRequired: true,
    documentsRequired: true,
    workflowTemplateSlug: 'payroll-onboarding',
    renewalInterval: 'monthly',
    roadReadyApplicable: false,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'QUOTE_REQUIRED',
    providerRequirements: ['payroll'],
    icon: 'payroll',
    cta: 'Request Service',
  },
  {
    id: 'tax-prep',
    slug: 'tax-preparation',
    name: 'Tax Preparation',
    shortDescription: 'Business tax preparation coordination.',
    description: 'Tax preparation request, document checklist, preparer assignment, and filing status — provider relationship disclosed per configuration.',
    category: 'manage-my-money',
    fulfillmentType: null,
    activationStatus: 'PREPARING',
    jurisdictionDependent: false,
    defaultJurisdictionAvailability: 'AVAILABLE',
    pricingModel: 'quote_required',
    quoteRequired: true,
    documentsRequired: true,
    workflowTemplateSlug: 'tax-preparation',
    renewalInterval: 'annual',
    roadReadyApplicable: false,
    customerPortalVisible: true,
    officeVisible: true,
    paymentModel: 'QUOTE_REQUIRED',
    providerRequirements: ['tax_preparation'],
    icon: 'tax-prep',
    cta: 'Request Service',
    publicDisclosure: 'Tax preparation may be fulfilled by an approved provider where disclosure is required.',
  },
];

export function getCatalogServiceBySlug(slug: string): CatalogServiceEntry | undefined {
  return CANONICAL_SERVICE_CATALOG.find((s) => s.slug === slug);
}

export function getCatalogServicesByCategory(category: string): CatalogServiceEntry[] {
  return CANONICAL_SERVICE_CATALOG.filter(
    (s) => s.category === category || s.discoveryCategories?.includes(category as CatalogServiceEntry['category']),
  );
}

export function getPublicCatalogServices(): CatalogServiceEntry[] {
  return CANONICAL_SERVICE_CATALOG.filter((s) => s.customerPortalVisible && s.activationStatus !== 'DISABLED');
}

export function searchCatalogServices(query: string, categoryFilter?: string): CatalogServiceEntry[] {
  const term = query.trim().toLowerCase();
  let list = getPublicCatalogServices();
  if (categoryFilter && categoryFilter !== 'all') {
    list = list.filter(
      (s) => s.category === categoryFilter || s.discoveryCategories?.includes(categoryFilter as CatalogServiceEntry['category']),
    );
  }
  if (!term) return list;
  return list.filter(
    (s) =>
      s.name.toLowerCase().includes(term) ||
      s.slug.toLowerCase().includes(term) ||
      s.shortDescription.toLowerCase().includes(term) ||
      s.description.toLowerCase().includes(term),
  );
}

export function fulfillmentDisclosure(entry: CatalogServiceEntry): string | null {
  if (entry.publicDisclosure) return entry.publicDisclosure;
  if (entry.fulfillmentType === 'PARTNER_PROVIDED') {
    return entry.publicDisclosure ?? 'Available through an approved provider.';
  }
  return null;
}

export const SERVICE_NEED_OPTIONS: ServiceNeedOption[] = [
  { id: 'starting-company', label: 'Starting my company', description: 'Formation, EIN, and business setup.', recommendedSlugs: ['llc-formation-assistance', 'ein-assistance', 'trucking-business-startup'] },
  { id: 'getting-authority', label: 'Getting my authority', description: 'USDOT, MC, and BOC-3.', recommendedSlugs: ['usdot-registration', 'operating-authority-assistance', 'boc-3-assistance'] },
  { id: 'getting-road-ready', label: 'Getting road ready', description: 'Registration, taxes, insurance, and startup requirements.', recommendedSlugs: ['ucr-registration', 'irp-apportioned-registration', 'ifta-fuel-tax-assistance', 'commercial-auto-liability'] },
  { id: 'staying-compliant', label: 'Staying compliant', description: 'Renewals, filings, and compliance calendar.', recommendedSlugs: ['renewals', 'mcs-150-biennial-update', 'ucr-renewal', 'compliance-support'] },
  { id: 'managing-drivers', label: 'Managing drivers', description: 'DQ files, consortium, and Clearinghouse.', recommendedSlugs: ['driver-qualification-files', 'drug-alcohol-consortium', 'fmcsa-clearinghouse-assistance'] },
  { id: 'preparing-audit', label: 'Preparing for a DOT audit', description: 'Audit readiness and document checklists.', recommendedSlugs: ['dot-audit-support', 'new-entrant-audit-support', 'dot-compliance-support'] },
  { id: 'titles-tags', label: 'Titles / tags', description: 'Title and plate services by jurisdiction.', recommendedSlugs: ['title-services', 'tag-services'] },
  { id: 'dispatch', label: 'Dispatch', description: 'Keep your truck moving.', recommendedSlugs: ['carrier-dispatch-support', 'load-coordination'] },
  { id: 'moving-freight', label: 'Moving freight', description: 'Brokerage and shipper services.', recommendedSlugs: ['freight-quote', 'shipper-services'] },
  { id: 'insurance', label: 'Insurance', description: 'Commercial trucking coverage assistance.', recommendedSlugs: ['commercial-auto-liability', 'general-transportation-insurance-review'] },
  { id: 'bookkeeping', label: 'Bookkeeping', description: 'Trucking-focused monthly bookkeeping.', recommendedSlugs: ['bookkeeping', 'books-rescue'] },
  { id: 'payroll', label: 'Payroll', description: 'Payroll setup and processing support.', recommendedSlugs: ['payroll-services'] },
  { id: 'taxes', label: 'Taxes', description: 'Tax preparation with bookkeeping handoff.', recommendedSlugs: ['tax-preparation', 'bookkeeping'] },
  { id: 'getting-paid-faster', label: 'Getting paid faster', description: 'Factoring through approved partners.', recommendedSlugs: ['factoring-consultation', 'invoice-factoring'] },
  { id: 'not-sure', label: 'Not sure — tell us about your business', description: 'We will suggest what you may need.', recommendedSlugs: ['trucking-business-startup', 'business-setup-consultation'] },
];

export const COMPLIANCE_DISCLAIMER =
  'All In One provides administrative, filing, compliance-support, and partner-facilitated services according to the selected service. Requirements vary by operation and jurisdiction. Government agencies and third-party providers make final determinations where applicable.';

export const MISSING_ICON_SLOTS = [
  'ucr',
  'hvut',
  'mcs150',
  'consortium',
  'clearinghouse',
  'dq-files',
  'dot-audit',
  'eld',
  'title',
  'tags',
  'payroll',
  'tax-prep',
  'safety',
] as const;
