import type { CareerWorldBlueprint, CareerWorldId } from './types';

const LIFE_SYSTEMS: CareerWorldBlueprint['lifeSystems'] = [
  'companies',
  'workplaces',
  'districts',
  'npc-professionals',
  'mentors',
  'clients',
  'suppliers',
  'competitors',
  'economy',
  'events',
  'challenges',
  'promotions',
  'industry-news',
  'seasonal-changes',
  'community-achievements',
];

const IDENTITY_FIELDS: CareerWorldBlueprint['identityFields'] = [
  'reputation',
  'resume',
  'portfolio',
  'income',
  'network',
  'certifications',
  'achievements',
  'promotion-history',
  'mentorship-history',
  'industry-influence',
];

const PROGRESSION_PHASES: CareerWorldBlueprint['progressionPhases'] = [
  'entry',
  'apprentice',
  'operator',
  'specialist',
  'leader',
  'founder',
  'master-professional',
  'mentor',
];

const ENDGAME: CareerWorldBlueprint['endgameMilestones'] = [
  'start-business',
  'hire-employees',
  'open-new-locations',
  'mentor-apprentices',
  'invent-techniques',
  'publish-research',
  'speak-at-conferences',
  'win-industry-awards',
  'change-the-profession',
];

function world(input: {
  id: CareerWorldId;
  name: string;
  profession: string;
  oneLine: string;
  primaryFantasy: string;
  districts: string[];
  npcArchetypes: string[];
  mentorArchetypes: string[];
  clientArchetypes: string[];
  challengeLoops: string[];
  revenueSources: string[];
  marketForces: string[];
  graphTags: string[];
}): CareerWorldBlueprint {
  return {
    id: input.id,
    slug: input.id,
    name: input.name,
    profession: input.profession,
    oneLine: input.oneLine,
    worldQuestion: 'What kind of professional life are you building?',
    primaryFantasy: input.primaryFantasy,
    lifeSystems: LIFE_SYSTEMS,
    identityFields: IDENTITY_FIELDS,
    progressionPhases: PROGRESSION_PHASES,
    endgameMilestones: ENDGAME,
    economy: {
      currencyName: 'professional capital',
      revenueSources: input.revenueSources,
      marketForces: input.marketForces,
      offlineActivity: [
        'clients continue booking',
        'coworkers continue working',
        'competitors continue improving',
        'industry news continues moving',
      ],
    },
    canonicalDistricts: input.districts,
    npcArchetypes: input.npcArchetypes,
    mentorArchetypes: input.mentorArchetypes,
    clientArchetypes: input.clientArchetypes,
    challengeLoops: input.challengeLoops,
    offlineEvolutionSignals: [
      'market demand shifts',
      'new technologies emerge',
      'seasonal opportunities open',
      'community achievements unlock',
      'competitor reputation changes',
    ],
    graphTags: ['career-world', input.profession.toLowerCase().replace(/[^a-z0-9]+/g, '-'), ...input.graphTags],
  };
}

export const CAREER_WORLD_BLUEPRINTS: CareerWorldBlueprint[] = [
  world({
    id: 'hair-world',
    name: 'Hair World™',
    profession: 'Hair',
    oneLine: 'A living beauty-industry world where learners become stylists, salon operators, founders, and master educators.',
    primaryFantasy: 'Build a reputation from chair assistant to industry-changing hair professional.',
    districts: ['Salon Row', 'Color Lab District', 'Editorial Runway', 'Supplier Market', 'Founder Suites'],
    npcArchetypes: ['senior stylist', 'color specialist', 'salon coordinator', 'brand educator'],
    mentorArchetypes: ['master colorist', 'salon owner', 'celebrity stylist'],
    clientArchetypes: ['new client', 'bridal client', 'editorial client', 'high-maintenance regular'],
    challengeLoops: ['consultation accuracy', 'service quality', 'client retention', 'trend adaptation'],
    revenueSources: ['appointments', 'retail', 'education', 'brand partnerships'],
    marketForces: ['seasonal color trends', 'supplier shortages', 'social media demand'],
    graphTags: ['beauty', 'salon', 'frontal-slayer'],
  }),
  world({
    id: 'marketing-world',
    name: 'Marketing World™',
    profession: 'Marketing',
    oneLine: 'A persistent agency and brand-growth world where campaigns, audiences, competitors, and markets move daily.',
    primaryFantasy: 'Become the strategist who can grow brands, lead teams, and shape culture.',
    districts: ['Brand Strategy Quarter', 'Campaign Studio', 'Media Exchange', 'Analytics Tower', 'Launch Plaza'],
    npcArchetypes: ['creative strategist', 'media buyer', 'copy lead', 'analytics director'],
    mentorArchetypes: ['CMO', 'agency founder', 'growth operator'],
    clientArchetypes: ['startup founder', 'local business owner', 'enterprise brand team'],
    challengeLoops: ['brief interpretation', 'campaign design', 'budget allocation', 'performance review'],
    revenueSources: ['retainers', 'performance bonuses', 'launch packages', 'consulting'],
    marketForces: ['platform changes', 'audience fatigue', 'competitor launches'],
    graphTags: ['growth', 'campaigns', 'brand'],
  }),
  world({
    id: 'architecture-world',
    name: 'Architecture World™',
    profession: 'Architecture',
    oneLine: 'A living built-environment world of studios, sites, clients, permits, materials, and city-scale design problems.',
    primaryFantasy: 'Progress from studio apprentice to architect whose buildings change the skyline.',
    districts: ['Model Shop', 'Planning Office', 'Materials Library', 'Construction Site', 'Civic Review Hall'],
    npcArchetypes: ['project architect', 'structural engineer', 'urban planner', 'site superintendent'],
    mentorArchetypes: ['principal architect', 'design critic', 'developer partner'],
    clientArchetypes: ['homeowner', 'public agency', 'developer', 'cultural institution'],
    challengeLoops: ['site constraints', 'client brief', 'code review', 'design iteration'],
    revenueSources: ['design fees', 'consulting', 'competitions', 'licensed plans'],
    marketForces: ['material costs', 'zoning shifts', 'sustainability standards'],
    graphTags: ['architecture', 'built-environment'],
  }),
  world({
    id: 'construction-world',
    name: 'Construction World™',
    profession: 'Construction',
    oneLine: 'A field operations world where projects, crews, suppliers, weather, budgets, and safety evolve in real time.',
    primaryFantasy: 'Build from crew member to contractor, developer, and mentor of new builders.',
    districts: ['Jobsite Grid', 'Equipment Yard', 'Permit Office', 'Supplier Depot', 'Safety Academy'],
    npcArchetypes: ['foreman', 'inspector', 'supplier rep', 'project manager'],
    mentorArchetypes: ['general contractor', 'master tradesperson', 'developer'],
    clientArchetypes: ['homeowner', 'commercial tenant', 'municipal client'],
    challengeLoops: ['schedule coordination', 'quality control', 'budget pressure', 'safety decisions'],
    revenueSources: ['contracts', 'change orders', 'maintenance', 'development deals'],
    marketForces: ['weather', 'labor availability', 'material pricing'],
    graphTags: ['construction', 'trades'],
  }),
  world({
    id: 'photography-world',
    name: 'Photography World™',
    profession: 'Photography',
    oneLine: 'A creative commerce world of clients, studios, assignments, galleries, editors, and visual reputation.',
    primaryFantasy: 'Grow from first bookings to signature visual voice and industry recognition.',
    districts: ['Portrait Studio', 'Editorial Desk', 'Gear Market', 'Gallery Lane', 'Location Scout Office'],
    npcArchetypes: ['photo editor', 'retoucher', 'producer', 'studio assistant'],
    mentorArchetypes: ['award-winning photographer', 'gallery curator', 'commercial director'],
    clientArchetypes: ['family client', 'brand manager', 'magazine editor', 'artist'],
    challengeLoops: ['brief capture', 'lighting choices', 'client delivery', 'portfolio curation'],
    revenueSources: ['sessions', 'licensing', 'prints', 'campaign shoots'],
    marketForces: ['visual trends', 'equipment changes', 'seasonal bookings'],
    graphTags: ['photography', 'creative'],
  }),
  world({
    id: 'film-world',
    name: 'Film World™',
    profession: 'Film',
    oneLine: 'A living production world where crews, scripts, budgets, locations, festivals, and audiences keep moving.',
    primaryFantasy: 'Evolve from production assistant to filmmaker, studio founder, and mentor.',
    districts: ['Writers Room', 'Soundstage', 'Edit Bay', 'Festival Circuit', 'Distribution Market'],
    npcArchetypes: ['producer', 'cinematographer', 'editor', 'assistant director'],
    mentorArchetypes: ['showrunner', 'director', 'studio executive'],
    clientArchetypes: ['brand client', 'streaming buyer', 'festival programmer'],
    challengeLoops: ['script development', 'production planning', 'shoot execution', 'release strategy'],
    revenueSources: ['production fees', 'licensing', 'distribution', 'sponsorship'],
    marketForces: ['audience taste', 'platform demand', 'crew availability'],
    graphTags: ['film', 'production'],
  }),
  world({
    id: 'music-world',
    name: 'Music World™',
    profession: 'Music',
    oneLine: 'A career ecosystem of studios, collaborators, venues, labels, fans, royalties, and cultural momentum.',
    primaryFantasy: 'Build a musical identity from practice rooms to influence, ownership, and mentorship.',
    districts: ['Practice Rooms', 'Recording Studio', 'Venue Row', 'Label Office', 'Publishing House'],
    npcArchetypes: ['producer', 'engineer', 'manager', 'session player'],
    mentorArchetypes: ['music director', 'label founder', 'tour veteran'],
    clientArchetypes: ['artist collaborator', 'sync buyer', 'venue booker'],
    challengeLoops: ['song craft', 'release planning', 'performance quality', 'catalog ownership'],
    revenueSources: ['performances', 'royalties', 'sync', 'merchandise'],
    marketForces: ['streaming trends', 'venue calendars', 'fan growth'],
    graphTags: ['music', 'creative-economy'],
  }),
  world({
    id: 'finance-world',
    name: 'Finance World™',
    profession: 'Finance',
    oneLine: 'A professional trust world of clients, markets, portfolios, regulation, risk, and long-term reputation.',
    primaryFantasy: 'Become the trusted advisor who grows wealth, manages risk, and teaches the next generation.',
    districts: ['Client Advisory Office', 'Market Floor', 'Risk Lab', 'Compliance Hall', 'Wealth Studio'],
    npcArchetypes: ['analyst', 'advisor', 'compliance officer', 'portfolio manager'],
    mentorArchetypes: ['CFO', 'investment principal', 'wealth strategist'],
    clientArchetypes: ['young professional', 'family office', 'small business owner'],
    challengeLoops: ['risk assessment', 'portfolio design', 'client education', 'market response'],
    revenueSources: ['advisory fees', 'planning packages', 'asset management', 'research'],
    marketForces: ['interest rates', 'market volatility', 'regulatory updates'],
    graphTags: ['finance', 'trust'],
  }),
  world({
    id: 'fashion-world',
    name: 'Fashion World™',
    profession: 'Fashion',
    oneLine: 'A living design, production, editorial, retail, and cultural influence world.',
    primaryFantasy: 'Build taste, collections, teams, and a label that changes how people present themselves.',
    districts: ['Design Atelier', 'Pattern Room', 'Runway District', 'Textile Market', 'Retail Salon'],
    npcArchetypes: ['designer', 'patternmaker', 'buyer', 'stylist'],
    mentorArchetypes: ['creative director', 'label founder', 'editor'],
    clientArchetypes: ['private client', 'boutique buyer', 'celebrity stylist'],
    challengeLoops: ['collection concept', 'fit refinement', 'sourcing', 'launch reception'],
    revenueSources: ['garments', 'styling', 'licensing', 'retail partnerships'],
    marketForces: ['seasonal trends', 'fabric availability', 'cultural moments'],
    graphTags: ['fashion', 'design'],
  }),
  world({
    id: 'legal-world',
    name: 'Legal World™',
    profession: 'Legal',
    oneLine: 'A professional judgment world of clients, cases, courts, contracts, ethics, and reputation.',
    primaryFantasy: 'Become a trusted legal professional who protects people, builds institutions, and mentors advocates.',
    districts: ['Client Intake Office', 'Research Library', 'Negotiation Room', 'Court Corridor', 'Ethics Chamber'],
    npcArchetypes: ['paralegal', 'associate', 'judge', 'opposing counsel'],
    mentorArchetypes: ['senior partner', 'public defender', 'general counsel'],
    clientArchetypes: ['individual client', 'startup founder', 'nonprofit director'],
    challengeLoops: ['issue spotting', 'research', 'client communication', 'ethical judgment'],
    revenueSources: ['case work', 'retainers', 'advisory packages', 'templates'],
    marketForces: ['regulation', 'precedent shifts', 'client demand'],
    graphTags: ['legal', 'professional-trust'],
  }),
  world({
    id: 'healthcare-world',
    name: 'Healthcare World™',
    profession: 'Healthcare',
    oneLine: 'A care-delivery world of patients, teams, protocols, ethics, technology, and community health.',
    primaryFantasy: 'Build clinical judgment, trust, and leadership while improving patient outcomes.',
    districts: ['Clinic Floor', 'Patient Education Wing', 'Diagnostics Lab', 'Care Team Hub', 'Public Health Square'],
    npcArchetypes: ['nurse', 'clinician', 'care coordinator', 'administrator'],
    mentorArchetypes: ['chief medical officer', 'senior nurse educator', 'public health leader'],
    clientArchetypes: ['patient', 'family caregiver', 'community organization'],
    challengeLoops: ['triage', 'care planning', 'communication', 'protocol adherence'],
    revenueSources: ['care services', 'education', 'operations leadership', 'community programs'],
    marketForces: ['policy changes', 'technology adoption', 'population needs'],
    graphTags: ['healthcare', 'care'],
  }),
  world({
    id: 'restaurant-world',
    name: 'Restaurant World™',
    profession: 'Restaurant',
    oneLine: 'A hospitality world where service, food, staff, suppliers, reviews, margins, and community evolve daily.',
    primaryFantasy: 'Rise from shift learner to operator, restaurateur, and mentor of a hospitality community.',
    districts: ['Kitchen Line', 'Dining Room', 'Supplier Market', 'Reservation Desk', 'Expansion Office'],
    npcArchetypes: ['chef', 'server', 'manager', 'supplier'],
    mentorArchetypes: ['executive chef', 'restaurant group founder', 'hospitality critic'],
    clientArchetypes: ['regular guest', 'private event host', 'reviewer', 'tourist'],
    challengeLoops: ['service flow', 'menu design', 'team coordination', 'margin control'],
    revenueSources: ['dining', 'events', 'catering', 'products'],
    marketForces: ['seasonality', 'review momentum', 'food costs'],
    graphTags: ['restaurant', 'hospitality'],
  }),
];

export const CAREER_WORLD_BLUEPRINT_BY_ID: Record<CareerWorldId, CareerWorldBlueprint> =
  Object.fromEntries(CAREER_WORLD_BLUEPRINTS.map((blueprint) => [blueprint.id, blueprint])) as Record<
    CareerWorldId,
    CareerWorldBlueprint
  >;
