/**
 * AIO icon sheet — the founder-supplied icon sheet traced to vector symbols (56×56 sheet-px window per icon,
 * so relative scale between icons is the sheet's own). Generated by scripts/icon-sheet/; do not edit by hand.
 */
export const AIO_SHEET_URL = '/migration/icons/aio-icon-sheet.svg';

export const AIO_SHEET_ICONS = ['back', 'forward', 'home', 'inbox', 'explore', 'copilot', 'more', 'close', 'dropdown', 'collapse', 'menu', 'repo', 'settings', 'success', 'failure', 'skipped', 'pending', 'running', 'queued', 'warning', 'info', 'pass', 'fail', 'blocked', 'skipped-small', 'more-small', 'run', 'stop', 're-run', 'add', 'remove', 'edit', 'delete', 'download', 'upload', 'open-link', 'copy', 'view', 'search', 'setup', 'checkout', 'build', 'install', 'database', 'security', 'migrate', 'connectivity', 'api-keys', 'tests', 'summary', 'artifact', 'deploy', 'home-active', 'home-inactive', 'inbox-tab', 'explore-tab', 'copilot-tab', 'battery', 'signal', 'wifi', 'repo-small', 'profile', 'help', 'notification', 'calendar', 'filter', 'log', 'code', 'image', 'pdf', 'text', 'terminal', 'folder', 'search-file', 'error-log', 'info-log', 'success-log', 'time-log', 'line-number', 'arrow-right', 'info-mark', 'help-mark', 'alert-mark'] as const;

export type AioSheetIcon = (typeof AIO_SHEET_ICONS)[number];

/** Colours sampled from the sheet for its coloured status icons. */
export const AIO_SHEET_TONES: Partial<Record<AioSheetIcon, string>> = {
  'success': '#2a873a',
  'failure': '#eb1c1a',
  'skipped': '#656c75',
  'pending': '#5e6c7d',
  'running': '#175bdf',
  'warning': '#eca409',
  'info': '#696f76',
  'pass': '#218a38',
  'fail': '#f01716',
  'skipped-small': '#666d74',
  'home-active': '#1559e1',
  'home-inactive': '#6c7177',
  'error-log': '#ef1a17',
  'info-log': '#1559da',
  'success-log': '#268939',
  'info-mark': '#1559da',
  'alert-mark': '#ef1a17',
};
