import type { JournalStep } from '../types';

/** Researched starter. Not an approved AIO procedure. The expert confirms or corrects each step. */
export const OPERATING_AUTHORITY_STEPS: JournalStep[] = [
  {
    id: 'oa-eligibility',
    order: 1,
    title: 'Confirm authority is required',
    researchedWording:
      'Confirm this is an interstate for-hire operation that needs a docket number. Private carriers, exempt-commodity haulers, and commercial-zone-only carriers are examples FMCSA lists as not needing operating authority.',
    proposedWording: null,
    confirmedWording: null,
    expertResponse: null,
    kind: 'decision',
    disposition: 'unreviewed',
    layer: 'industry',
    visibility: 'company_standard',
    requirementClass: 'legal_requirement',
    sourceIds: ['fmcsa-operating-authority'],
    approvalRequired: true,
    neverAutomate: true,
    guidanceMayHaveChanged: false,
  },
  {
    id: 'oa-usdot',
    order: 2,
    title: 'USDOT or first registration',
    researchedWording:
      'A first-time applicant who has never registered with FMCSA starts in the Unified Registration System. A company that already has a USDOT number uses the path FMCSA provides for an additional authority.',
    proposedWording: null,
    confirmedWording: null,
    expertResponse: null,
    kind: 'action',
    disposition: 'unreviewed',
    layer: 'industry',
    visibility: 'company_standard',
    requirementClass: 'legal_requirement',
    sourceIds: ['fmcsa-operating-authority'],
    approvalRequired: false,
    neverAutomate: false,
    guidanceMayHaveChanged: false,
  },
  {
    id: 'oa-type',
    order: 3,
    title: 'Choose only the authority types needed',
    researchedWording:
      'Select only the authority types the business will run. FMCSA says a separate fee is due for each kind, and mistaken applications are not refunded. The operating-authority page listed a $300 permanent-authority fee on 20 April 2026. Re-check that figure before quoting it.',
    proposedWording: null,
    confirmedWording: null,
    expertResponse: null,
    kind: 'decision',
    disposition: 'unreviewed',
    layer: 'industry',
    visibility: 'company_standard',
    requirementClass: 'legal_requirement',
    sourceIds: ['fmcsa-operating-authority'],
    approvalRequired: true,
    neverAutomate: true,
    guidanceMayHaveChanged: false,
  },
  {
    id: 'oa-identity',
    order: 4,
    title: 'Match the business identity',
    researchedWording:
      'Collect the legal name, addresses, and ownership so the application matches the client’s other paperwork. This is a common preparation practice. It is not stated as its own rule on the authority page.',
    proposedWording: null,
    confirmedWording: null,
    expertResponse: null,
    kind: 'action',
    disposition: 'unreviewed',
    layer: 'industry',
    visibility: 'company_standard',
    requirementClass: 'standard_industry_practice',
    sourceIds: ['fmcsa-operating-authority'],
    approvalRequired: false,
    neverAutomate: false,
    guidanceMayHaveChanged: false,
  },
  {
    id: 'oa-submit',
    order: 5,
    title: 'Submit the application',
    researchedWording:
      'File through the path that matches the client: Unified Registration System for a first registration, or the additional-authority path when a USDOT number already exists. Mailed credit-card filings are also described for companies that are already registered.',
    proposedWording: null,
    confirmedWording: null,
    expertResponse: null,
    kind: 'action',
    disposition: 'unreviewed',
    layer: 'industry',
    visibility: 'company_standard',
    requirementClass: 'legal_requirement',
    sourceIds: ['fmcsa-operating-authority'],
    approvalRequired: true,
    neverAutomate: true,
    guidanceMayHaveChanged: false,
  },
  {
    id: 'oa-insurance',
    order: 6,
    title: 'Insurance company files the proof',
    researchedWording:
      'The insurance company files bodily-injury and property-damage proof, commonly BMC-91 or BMC-91X. The applicant does not file those forms. Minimums depend on cargo and vehicle weight. Do not quote a dollar amount until the current FMCSA insurance table is re-read. The OP-1 text and the insurance-page excerpt describe the dismissal window differently, so the exact deadline is unverified.',
    proposedWording: null,
    confirmedWording: null,
    expertResponse: null,
    kind: 'approval',
    disposition: 'unreviewed',
    layer: 'industry',
    visibility: 'company_standard',
    requirementClass: 'research_uncertainty',
    sourceIds: ['fmcsa-insurance', 'fmcsa-insurance-faq', 'fmcsa-op1'],
    approvalRequired: true,
    neverAutomate: true,
    guidanceMayHaveChanged: true,
  },
  {
    id: 'oa-boc3',
    order: 7,
    title: 'Process agent files the BOC-3',
    researchedWording:
      'A process agent files Form BOC-3 for the carrier. One form must cover every state that requires a designation, and a post office box is not a valid agent address. If this filing is missing, authority is not complete.',
    proposedWording: null,
    confirmedWording: null,
    expertResponse: null,
    kind: 'exception',
    disposition: 'unreviewed',
    layer: 'industry',
    visibility: 'company_standard',
    requirementClass: 'legal_requirement',
    sourceIds: ['fmcsa-boc3'],
    approvalRequired: true,
    neverAutomate: true,
    guidanceMayHaveChanged: false,
  },
  {
    id: 'oa-complete',
    order: 8,
    title: 'Confirm the grant and tell the client',
    researchedWording:
      'Check authority history on the FMCSA Licensing and Insurance site. FMCSA described 20–25 business days for many URS applications and 45–60 business days for mailed applications, unless the file needs more review. Tell the client only after the grant is visible. Keep the company’s BOC-3 copy at the principal place of business.',
    proposedWording: null,
    confirmedWording: null,
    expertResponse: null,
    kind: 'completion',
    disposition: 'unreviewed',
    layer: 'industry',
    visibility: 'company_standard',
    requirementClass: 'legal_requirement',
    sourceIds: ['fmcsa-operating-authority', 'fmcsa-boc3'],
    approvalRequired: true,
    neverAutomate: true,
    guidanceMayHaveChanged: false,
  },
];
