import type { ResearchSource } from '../types';

/** Checked 2026-10-09. Fees and deadlines are included only when the cited page was read. */
export const RESEARCH_SOURCES: ResearchSource[] = [
  {
    id: 'fmcsa-operating-authority',
    publisher: 'FMCSA',
    title: 'Get Operating Authority (Docket Number)',
    url: 'https://www.fmcsa.dot.gov/registration/get-mc-number-authority-operate',
    dateChecked: '2026-10-09',
    publishedOrUpdated: '2026-04-20',
    jurisdiction: 'United States — interstate',
    applicability: 'Companies that need an MC, FF, or MX docket in addition to a USDOT number',
    confidence: 'high',
    verification: 'page_read',
    notes: 'Page states permanent authority fee $300, name change $14, reinstatement $80, and that fees are not refunded. URS timing 20–25 business days; mailed applications 45–60 business days. Private carriers, exempt-commodity carriers, and commercial-zone-only carriers are listed as not needing authority.',
  },
  {
    id: 'fmcsa-boc3',
    publisher: 'FMCSA',
    title: 'Form BOC-3 — Designation of Agents for Service of Process',
    url: 'https://www.fmcsa.dot.gov/registration/form-boc-3-designation-agents-service-process',
    dateChecked: '2026-10-09',
    publishedOrUpdated: '2026-07-16',
    jurisdiction: 'United States',
    applicability: 'Carriers, brokers, and freight forwarders designating process agents',
    confidence: 'high',
    verification: 'page_read',
    notes: 'Only a process agent files BOC-3 for a carrier. A broker or freight forwarder without CMVs may file on its own behalf. One form, all required states. A post office box is not an acceptable agent address. Governed by 49 CFR 366.',
  },
  {
    id: 'fmcsa-insurance',
    publisher: 'FMCSA',
    title: 'Insurance Filing Requirements',
    url: 'https://www.fmcsa.dot.gov/registration/insurance-filing-requirements',
    dateChecked: '2026-10-09',
    publishedOrUpdated: null,
    jurisdiction: 'United States',
    applicability: 'Applicants for operating authority under 49 CFR Part 387',
    confidence: 'medium',
    verification: 'indexed_excerpt',
    notes: 'Full page fetch timed out. Do not quote a dollar minimum from this pilot until the table is re-read. Excerpt: the insurer files the form; requirements vary by entity, cargo, and vehicle.',
  },
  {
    id: 'fmcsa-insurance-faq',
    publisher: 'FMCSA',
    title: 'What forms are required for insurance?',
    url: 'https://www.fmcsa.dot.gov/faq/what-forms-are-required-insurance-and-where-can-i-find-them',
    dateChecked: '2026-10-09',
    publishedOrUpdated: null,
    jurisdiction: 'United States',
    applicability: 'Insurance filings for authority applicants',
    confidence: 'medium',
    verification: 'indexed_excerpt',
    notes: 'Excerpt: BMC-91 or BMC-91X are filed by the insurance company, not the applicant. FMCSA does not give those forms to applicants.',
  },
  {
    id: 'fmcsa-op1',
    publisher: 'FMCSA',
    title: 'Form OP-1 instructions (insurance timing)',
    url: 'https://www.fmcsa.dot.gov/sites/fmcsa.dot.gov/files/2022-10/OP-1%20Form.pdf',
    dateChecked: '2026-10-09',
    publishedOrUpdated: '2022-10',
    jurisdiction: 'United States',
    applicability: 'Motor property carrier and broker authority applications',
    confidence: 'medium',
    verification: 'indexed_excerpt',
    notes: 'OP-1 text says the insurer must file within 90 days of Register publication or the application is dismissed and the fee is not refunded, with a warning if nothing is received in 20 days. The insurance requirements page excerpt describes a 20-day notice and 60 additional days. Treat the exact window as conflicting until re-checked. OP-1 itself may not be the current online path for every applicant.',
  },
  {
    id: 'fmcsa-broker-guidance',
    publisher: 'FMCSA / Federal Register',
    title: 'Definitions of Broker and Bona Fide Agents',
    url: 'https://www.federalregister.gov/documents/2023/06/16/2023-13080/definitions-of-broker-and-bona-fide-agents',
    dateChecked: '2026-10-09',
    publishedOrUpdated: '2023-06-16',
    jurisdiction: 'United States',
    applicability: 'Dispatch services, brokers, and bona fide agents. 49 CFR 371.2. Docket FMCSA-2022-0134.',
    confidence: 'high',
    verification: 'indexed_excerpt',
    notes: 'The notice says the guidance does not have the force and effect of law. Dispatch work is broker or bona fide agent based on the facts. Carrier control matters. Do not treat dispatch and brokerage as the same operating model. Newsroom summary: https://www.fmcsa.dot.gov/newsroom/fmcsa-issues-final-guidance-clarifying-broker-and-bona-fide-agents-definitions',
  },
  {
    id: 'iftach-home',
    publisher: 'IFTA, Inc.',
    title: 'International Fuel Tax Association',
    url: 'https://www.iftach.org/',
    dateChecked: '2026-10-09',
    publishedOrUpdated: '2026-10-09',
    jurisdiction: 'IFTA member jurisdictions',
    applicability: 'Base-jurisdiction fuel tax credentials and returns',
    confidence: 'high',
    verification: 'page_read',
    notes: 'IFTA, Inc. states that a subscriber membership does not provide credentials, decals, licenses, or tax-return support. Carriers contact the base jurisdiction. No filing deadline was copied from this page.',
  },
  {
    id: 'irs-2290',
    publisher: 'IRS',
    title: 'About Form 2290, Heavy Highway Vehicle Use Tax Return',
    url: 'https://www.irs.gov/forms-pubs/about-form-2290',
    dateChecked: '2026-10-09',
    publishedOrUpdated: null,
    jurisdiction: 'United States',
    applicability: 'Heavy highway vehicle use tax',
    confidence: 'low',
    verification: 'indexed_excerpt',
    notes: 'Page was not fully read in this sprint. Do not state a tax year, fee, or deadline from memory.',
  },
  {
    id: 'ecfr-391',
    publisher: 'eCFR / FMCSA',
    title: '49 CFR Part 391 — Qualifications of drivers',
    url: 'https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-391',
    dateChecked: '2026-10-09',
    publishedOrUpdated: null,
    jurisdiction: 'United States',
    applicability: 'Driver qualification for motor carriers subject to the FMCSRs',
    confidence: 'low',
    verification: 'indexed_excerpt',
    notes: 'Cited as the regulation home. This pilot does not reproduce a DQ-file checklist.',
  },
  {
    id: 'aio-launch-matrix',
    publisher: 'All In One Enterprises repository',
    title: 'Service launch matrix',
    url: 'all-in-one-enterprises/src/launch/serviceActivationLaunch.ts',
    dateChecked: '2026-10-09',
    publishedOrUpdated: null,
    jurisdiction: 'AIO commercial configuration',
    applicability: 'What AIO currently offers, pauses, or has not launched',
    confidence: 'high',
    verification: 'repository_catalog',
  },
  {
    id: 'aio-service-catalog',
    publisher: 'All In One Enterprises repository',
    title: 'Canonical service catalog',
    url: 'all-in-one-enterprises/src/services/catalog/serviceCatalog.ts',
    dateChecked: '2026-10-09',
    publishedOrUpdated: null,
    jurisdiction: 'AIO commercial configuration',
    applicability: 'Public and office service names, including Road Ready',
    confidence: 'high',
    verification: 'repository_catalog',
    notes: 'Road Ready is an AIO service family, not a government certification.',
  },
];

export function sourceById(id: string): ResearchSource | undefined {
  return RESEARCH_SOURCES.find((source) => source.id === id);
}
