import { dollarsToMinor } from '../billing/money';
import { computeGrossMinor } from '../dispatch/dispatchCalculations';
import type { Load } from '../dispatch/dispatchTypes';
import type {
  BrokerageAccessorial,
  BrokerageCapabilityState,
  BrokerageCounters,
  BrokerageFreightQuote,
  BrokerageIssue,
  BrokerageLoadFinancials,
  BrokerageRateConfirmation,
  BrokerageShipperInvoice,
  CarrierNetworkProfile,
  CarrierOffer,
  CarrierPayable,
  CoverageHistoryEvent,
  ShipperProfile,
  ShipmentRequest,
} from '../brokerage/brokerageTypes';
import { BROKERAGE_READINESS_CHECKLIST, DEFAULT_BROKERAGE_CAPABILITY } from '../brokerage/brokerageConfig';
import { daysAgo, daysAhead, isoNow } from './dateHelpers';

function mkLoad(
  id: string,
  num: string,
  partial: Partial<Load> & Pick<Load, 'operationalStatus' | 'brokerName' | 'originCity' | 'originState' | 'destinationCity' | 'destinationState'>,
): Load {
  const linehaul = partial.linehaulMinor ?? dollarsToMinor(2400);
  const fuel = partial.fuelSurchargeMinor ?? 0;
  const acc = partial.accessorialMinor ?? 0;
  const gross = partial.grossMinor ?? computeGrossMinor(linehaul, fuel, acc);
  return {
    id,
    loadNumber: num,
    organizationId: partial.organizationId ?? 'client-b',
    sourceType: 'brokerage',
    brokerName: partial.brokerName,
    equipmentType: partial.equipmentType ?? 'Dry Van',
    originCity: partial.originCity,
    originState: partial.originState,
    destinationCity: partial.destinationCity,
    destinationState: partial.destinationState,
    pickupDate: partial.pickupDate ?? daysAhead(1),
    deliveryDate: partial.deliveryDate ?? daysAhead(3),
    loadedMiles: partial.loadedMiles ?? 650,
    deadheadMiles: partial.deadheadMiles ?? 40,
    linehaulMinor: linehaul,
    fuelSurchargeMinor: fuel,
    accessorialMinor: acc,
    grossMinor: gross,
    confirmedGrossMinor: partial.confirmedGrossMinor ?? gross,
    currency: 'USD',
    offerStatus: partial.offerStatus ?? 'accepted',
    operationalStatus: partial.operationalStatus,
    rateConfirmationStatus: partial.rateConfirmationStatus ?? 'verified',
    rateDetailsReviewed: true,
    factoringHandoffStatus: partial.factoringHandoffStatus ?? 'not_ready',
    accessorials: partial.accessorials ?? [],
    rateRevisions: [],
    timeline: partial.timeline ?? [],
    shipperOrganizationId: partial.shipperOrganizationId ?? 'client-e',
    brokerageCoverageStatus: partial.brokerageCoverageStatus ?? 'needs_coverage',
    assignedBrokerStaffId: 'staff-7',
    createdAt: daysAgo(5),
    updatedAt: isoNow(),
    version: 1,
    ...partial,
  };
}

export function createBrokerageSeedData(): {
  capability: BrokerageCapabilityState;
  shipperProfiles: ShipperProfile[];
  shipmentRequests: ShipmentRequest[];
  freightQuotes: BrokerageFreightQuote[];
  carrierNetwork: CarrierNetworkProfile[];
  carrierOffers: CarrierOffer[];
  rateConfirmations: BrokerageRateConfirmation[];
  loads: Load[];
  financials: BrokerageLoadFinancials[];
  accessorials: BrokerageAccessorial[];
  shipperInvoices: BrokerageShipperInvoice[];
  carrierPayables: CarrierPayable[];
  issues: BrokerageIssue[];
  coverageHistory: CoverageHistoryEvent[];
  counters: BrokerageCounters;
} {
  const capability: BrokerageCapabilityState = {
    capability: DEFAULT_BROKERAGE_CAPABILITY,
    readinessItems: BROKERAGE_READINESS_CHECKLIST.map((item) => ({
      ...item,
      status: item.key === 'rate_confirmation_template' ? 'pending' : 'missing',
    })),
    updatedAt: isoNow(),
    updatedByStaffId: 'staff-1',
  };

  const shipperProfiles: ShipperProfile[] = [
    {
      id: 'shipper-e',
      organizationId: 'client-e',
      legalName: 'NorthStar Manufacturing',
      primaryContactName: 'Elena Vasquez',
      primaryEmail: 'elena.demo@northstar.example',
      primaryPhone: '(312) 555-4400',
      status: 'active',
      agreementStatus: 'accepted',
      preferredEquipment: ['Dry Van', 'Flatbed'],
      createdAt: daysAgo(30),
      updatedAt: daysAgo(1),
    },
    {
      id: 'shipper-demo-b',
      organizationId: 'shipper-demo-b',
      legalName: 'Lakeview Distribution Co.',
      primaryContactName: 'Pat Morrison',
      primaryEmail: 'pat.demo@lakeview.example',
      status: 'onboarding',
      agreementStatus: 'pending',
      createdAt: daysAgo(3),
      updatedAt: daysAgo(1),
    },
  ];

  const shipmentRequests: ShipmentRequest[] = [
    {
      id: 'sr-demo-a',
      requestNumber: 'SR-2026-0101',
      shipperOrganizationId: 'client-e',
      status: 'under_review',
      pickupCity: 'Chicago',
      pickupState: 'IL',
      deliveryCity: 'Atlanta',
      deliveryState: 'GA',
      pickupDate: daysAhead(5),
      deliveryDate: daysAhead(7),
      equipmentType: 'Dry Van',
      commodity: 'Consumer Goods',
      weight: '42,000 lbs',
      assignedBrokerStaffId: 'staff-7',
      documentIds: [],
      createdAt: daysAgo(1),
      updatedAt: daysAgo(0),
      version: 1,
    },
    {
      id: 'sr-demo-b',
      requestNumber: 'SR-2026-0102',
      shipperOrganizationId: 'shipper-demo-b',
      status: 'quoted',
      pickupCity: 'Indianapolis',
      pickupState: 'IN',
      deliveryCity: 'Memphis',
      deliveryState: 'TN',
      pickupDate: daysAhead(4),
      deliveryDate: daysAhead(6),
      equipmentType: 'Dry Van',
      commodity: 'Retail Freight',
      weight: '38,000 lbs',
      assignedBrokerStaffId: 'staff-7',
      documentIds: [],
      createdAt: daysAgo(2),
      updatedAt: daysAgo(1),
      version: 1,
    },
    {
      id: 'sr-converted',
      requestNumber: 'SR-2026-0099',
      shipperOrganizationId: 'client-e',
      status: 'converted_to_load',
      pickupCity: 'Detroit',
      pickupState: 'MI',
      deliveryCity: 'Nashville',
      deliveryState: 'TN',
      pickupDate: daysAhead(-2),
      deliveryDate: daysAhead(1),
      equipmentType: 'Dry Van',
      commodity: 'Auto Parts',
      weight: '18,000 lbs',
      convertedLoadId: 'br-load-a',
      assignedBrokerStaffId: 'staff-7',
      documentIds: [],
      createdAt: daysAgo(8),
      updatedAt: daysAgo(6),
      version: 2,
    },
  ];

  const freightQuotes: BrokerageFreightQuote[] = [
    {
      id: 'bq-demo-b',
      quoteNumber: 'BQ-2026-0202',
      shipmentRequestId: 'sr-demo-b',
      shipperOrganizationId: 'shipper-demo-b',
      status: 'sent',
      freightChargeMinor: dollarsToMinor(2850),
      currency: 'USD',
      currentRevision: 1,
      revisions: [
        {
          id: 'bqr-1',
          quoteId: 'bq-demo-b',
          version: 1,
          freightChargeMinor: dollarsToMinor(2850),
          expiresAt: daysAhead(3),
          preparedByStaffId: 'staff-7',
          createdAt: daysAgo(1),
        },
      ],
      expiresAt: daysAhead(3),
      preparedByStaffId: 'staff-7',
      createdAt: daysAgo(1),
      updatedAt: daysAgo(1),
      version: 1,
    },
    {
      id: 'bq-converted',
      quoteNumber: 'BQ-2026-0199',
      shipmentRequestId: 'sr-converted',
      shipperOrganizationId: 'client-e',
      status: 'converted',
      freightChargeMinor: dollarsToMinor(3000),
      currency: 'USD',
      currentRevision: 1,
      revisions: [
        {
          id: 'bqr-99',
          quoteId: 'bq-converted',
          version: 1,
          freightChargeMinor: dollarsToMinor(3000),
          preparedByStaffId: 'staff-7',
          createdAt: daysAgo(7),
        },
      ],
      acceptedRevisionId: 'bqr-99',
      convertedLoadId: 'br-load-a',
      preparedByStaffId: 'staff-7',
      createdAt: daysAgo(7),
      updatedAt: daysAgo(6),
      version: 2,
    },
  ];

  const carrierNetwork: CarrierNetworkProfile[] = [
    {
      id: 'cn-heartland',
      organizationId: 'client-b',
      legalName: 'Heartland Freight Co.',
      usdot: '1234567',
      mcNumber: 'MC-654321',
      equipmentTypes: ['Dry Van', 'Reefer'],
      authorityVerification: 'document_reviewed',
      insuranceVerification: 'document_reviewed',
      w9Status: 'verified',
      agreementStatus: 'accepted',
      status: 'active',
      createdAt: daysAgo(120),
      updatedAt: daysAgo(1),
    },
    {
      id: 'cn-pioneer',
      organizationId: 'client-c',
      legalName: 'Pioneer Fleet Services',
      usdot: '2345678',
      mcNumber: 'MC-765432',
      equipmentTypes: ['Dry Van'],
      authorityVerification: 'staff_verified',
      insuranceVerification: 'document_reviewed',
      w9Status: 'received',
      agreementStatus: 'accepted',
      status: 'active',
      createdAt: daysAgo(200),
      updatedAt: daysAgo(2),
    },
    {
      id: 'cn-external',
      legalName: 'External Demo Trucking LLC',
      usdot: '3456789',
      mcNumber: 'MC-876543',
      equipmentTypes: ['Flatbed'],
      authorityVerification: 'self_reported',
      insuranceVerification: 'self_reported',
      w9Status: 'received',
      agreementStatus: 'sent',
      status: 'approved_internal',
      createdAt: daysAgo(45),
      updatedAt: daysAgo(10),
    },
    {
      id: 'cn-blueline',
      organizationId: 'client-d',
      legalName: 'BlueLine Transport',
      usdot: '4567890',
      mcNumber: 'MC-987654',
      equipmentTypes: ['Dry Van'],
      authorityVerification: 'document_reviewed',
      insuranceVerification: 'document_reviewed',
      w9Status: 'verified',
      agreementStatus: 'accepted',
      status: 'active',
      createdAt: daysAgo(90),
      updatedAt: daysAgo(0),
    },
  ];

  const loads: Load[] = [
    mkLoad('br-load-a', 'BR-LD-2026-0001', {
      shipperOrganizationId: 'client-e',
      brokerageShipmentRequestId: 'sr-converted',
      brokerageQuoteId: 'bq-converted',
      brokerageCoverageStatus: 'needs_coverage',
      originCity: 'Detroit',
      originState: 'MI',
      destinationCity: 'Nashville',
      destinationState: 'TN',
      operationalStatus: 'booked',
      brokerName: 'All In One Brokerage (Demo)',
      pickupDate: daysAhead(1),
      deliveryDate: daysAhead(3),
    }),
    mkLoad('br-load-b', 'BR-LD-2026-0002', {
      shipperOrganizationId: 'client-e',
      brokerageCoverageStatus: 'carrier_contacted',
      originCity: 'Columbus',
      originState: 'OH',
      destinationCity: 'Charlotte',
      destinationState: 'NC',
      operationalStatus: 'booking_in_progress',
      brokerName: 'All In One Brokerage (Demo)',
    }),
    mkLoad('br-load-c', 'BR-LD-2026-0003', {
      organizationId: 'client-c',
      brokerageCarrierOrganizationId: 'client-c',
      brokerageCarrierNetworkProfileId: 'cn-pioneer',
      shipperOrganizationId: 'client-e',
      brokerageCoverageStatus: 'carrier_accepted',
      originCity: 'Atlanta',
      originState: 'GA',
      destinationCity: 'Miami',
      destinationState: 'FL',
      operationalStatus: 'booking_in_progress',
      brokerName: 'All In One Brokerage (Demo)',
    }),
    mkLoad('br-load-d', 'BR-LD-2026-0004', {
      organizationId: 'client-b',
      brokerageCarrierOrganizationId: 'client-b',
      brokerageCarrierNetworkProfileId: 'cn-heartland',
      shipperOrganizationId: 'client-e',
      brokerageCoverageStatus: 'booked',
      originCity: 'Dallas',
      originState: 'TX',
      destinationCity: 'Phoenix',
      destinationState: 'AZ',
      operationalStatus: 'in_transit',
      brokerName: 'All In One Brokerage (Demo)',
      bolDocumentId: 'vdoc-bol-br-d',
      pickupDate: daysAhead(-1),
      deliveryDate: daysAhead(2),
    }),
    mkLoad('br-load-e', 'BR-LD-2026-0005', {
      organizationId: 'client-b',
      brokerageCarrierOrganizationId: 'client-b',
      brokerageCarrierNetworkProfileId: 'cn-heartland',
      shipperOrganizationId: 'client-e',
      brokerageCoverageStatus: 'booked',
      originCity: 'Houston',
      originState: 'TX',
      destinationCity: 'Denver',
      destinationState: 'CO',
      operationalStatus: 'pod_needed',
      brokerName: 'All In One Brokerage (Demo)',
      bolDocumentId: 'vdoc-bol-br-e',
      pickupDate: daysAhead(-3),
      deliveryDate: daysAhead(-1),
    }),
    mkLoad('br-load-f', 'BR-LD-2026-0006', {
      organizationId: 'client-c',
      brokerageCarrierOrganizationId: 'client-c',
      brokerageCarrierNetworkProfileId: 'cn-pioneer',
      shipperOrganizationId: 'client-e',
      brokerageCoverageStatus: 'booked',
      originCity: 'Memphis',
      originState: 'TN',
      destinationCity: 'Chicago',
      destinationState: 'IL',
      operationalStatus: 'complete',
      brokerName: 'All In One Brokerage (Demo)',
      bolDocumentId: 'vdoc-bol-br-f',
      podDocumentId: 'vdoc-pod-br-f',
      pickupDate: daysAhead(-5),
      deliveryDate: daysAhead(-2),
      factoringHandoffStatus: 'not_ready',
    }),
    mkLoad('br-load-g', 'BR-LD-2026-0007', {
      organizationId: 'client-b',
      brokerageCarrierOrganizationId: 'client-b',
      brokerageCarrierNetworkProfileId: 'cn-heartland',
      shipperOrganizationId: 'client-e',
      brokerageCoverageStatus: 'booked',
      originCity: 'Kansas City',
      originState: 'MO',
      destinationCity: 'St. Louis',
      destinationState: 'MO',
      operationalStatus: 'complete',
      brokerName: 'All In One Brokerage (Demo)',
      bolDocumentId: 'vdoc-bol-br-g',
      podDocumentId: 'vdoc-pod-br-g',
      linehaulMinor: dollarsToMinor(2500),
      grossMinor: dollarsToMinor(2500),
      confirmedGrossMinor: dollarsToMinor(2500),
      pickupDate: daysAhead(-7),
      deliveryDate: daysAhead(-4),
    }),
    mkLoad('br-load-h', 'BR-LD-2026-0008', {
      organizationId: 'client-g',
      brokerageCarrierOrganizationId: 'client-g',
      brokerageCarrierNetworkProfileId: 'cn-blueline',
      shipperOrganizationId: 'client-e',
      brokerageCoverageStatus: 'booked',
      originCity: 'Tampa',
      originState: 'FL',
      destinationCity: 'Orlando',
      destinationState: 'FL',
      operationalStatus: 'complete',
      brokerName: 'All In One Brokerage (Demo)',
      bolDocumentId: 'vdoc-bol-br-h',
      podDocumentId: 'vdoc-pod-br-h',
      pickupDate: daysAhead(-6),
      deliveryDate: daysAhead(-3),
    }),
  ];

  const carrierOffers: CarrierOffer[] = [
    {
      id: 'co-b-decline',
      loadId: 'br-load-b',
      carrierNetworkProfileId: 'cn-external',
      status: 'declined',
      carrierPayMinor: dollarsToMinor(2100),
      currency: 'USD',
      currentRevision: 1,
      revisions: [{ id: 'cor-b1', offerId: 'co-b-decline', version: 1, carrierPayMinor: dollarsToMinor(2100), createdAt: daysAgo(2) }],
      createdByStaffId: 'staff-7',
      createdAt: daysAgo(2),
      updatedAt: daysAgo(1),
      version: 1,
    },
    {
      id: 'co-b-pending',
      loadId: 'br-load-b',
      carrierNetworkProfileId: 'cn-heartland',
      carrierOrganizationId: 'client-b',
      status: 'sent',
      carrierPayMinor: dollarsToMinor(2200),
      currency: 'USD',
      currentRevision: 1,
      revisions: [{ id: 'cor-b2', offerId: 'co-b-pending', version: 1, carrierPayMinor: dollarsToMinor(2200), createdAt: daysAgo(1) }],
      sentAt: daysAgo(1),
      createdByStaffId: 'staff-7',
      createdAt: daysAgo(1),
      updatedAt: daysAgo(1),
      version: 1,
    },
    {
      id: 'co-c-accepted',
      loadId: 'br-load-c',
      carrierNetworkProfileId: 'cn-pioneer',
      carrierOrganizationId: 'client-c',
      status: 'accepted',
      carrierPayMinor: dollarsToMinor(1950),
      currency: 'USD',
      currentRevision: 1,
      revisions: [{ id: 'cor-c1', offerId: 'co-c-accepted', version: 1, carrierPayMinor: dollarsToMinor(1950), createdAt: daysAgo(2) }],
      respondedAt: daysAgo(1),
      createdByStaffId: 'staff-7',
      createdAt: daysAgo(2),
      updatedAt: daysAgo(1),
      version: 1,
    },
  ];

  const rateConfirmations: BrokerageRateConfirmation[] = [
    {
      id: 'rc-c-pending',
      loadId: 'br-load-c',
      carrierOfferId: 'co-c-accepted',
      status: 'sent',
      templateLabel: 'DEVELOPMENT TEMPLATE — NOT FOR PRODUCTION USE',
      carrierPayMinor: dollarsToMinor(1950),
      sentAt: daysAgo(1),
      createdAt: daysAgo(1),
      updatedAt: daysAgo(1),
    },
  ];

  const financials: BrokerageLoadFinancials[] = loads.map((l) => {
    const shipper = l.id === 'br-load-g' ? dollarsToMinor(3000) : dollarsToMinor(2800);
    const carrier = l.confirmedGrossMinor;
    return {
      loadId: l.id,
      shipperChargeMinor: shipper,
      carrierLinehaulMinor: carrier,
      carrierFuelSurchargeMinor: 0,
      carrierAccessorialMinor: 0,
      totalCarrierPayMinor: carrier,
      confirmedShipperChargeMinor: l.operationalStatus === 'complete' || l.operationalStatus === 'pod_needed' ? shipper : 0,
      confirmedCarrierPayMinor: ['booked', 'in_transit', 'pod_needed', 'complete'].includes(l.operationalStatus) ? carrier : 0,
      currency: 'USD',
      version: 1,
      updatedAt: isoNow(),
    };
  });

  const shipperInvoices: BrokerageShipperInvoice[] = [
    {
      id: 'bsi-g',
      organizationId: 'client-e',
      loadId: 'br-load-g',
      shipperOrganizationId: 'client-e',
      invoiceNumber: 'BSI-2026-0007',
      baseFreightChargeMinor: dollarsToMinor(3000),
      accessorialsMinor: 0,
      adjustmentsMinor: 0,
      totalMinor: dollarsToMinor(3000),
      paidAmountMinor: 0,
      balanceMinor: dollarsToMinor(3000),
      currency: 'USD',
      status: 'issued',
      invoiceDate: daysAhead(-3),
      dueDate: daysAhead(27),
      podDocumentId: 'vdoc-pod-br-g',
      createdAt: daysAgo(2),
      updatedAt: daysAgo(2),
      version: 1,
    },
  ];

  const carrierPayables: CarrierPayable[] = [
    {
      id: 'cp-g',
      loadId: 'br-load-g',
      carrierNetworkProfileId: 'cn-heartland',
      carrierOrganizationId: 'client-b',
      confirmedAmountMinor: dollarsToMinor(2500),
      accessorialAmountMinor: 0,
      deductionsMinor: 0,
      totalPayableMinor: dollarsToMinor(2500),
      currency: 'USD',
      status: 'approved',
      createdAt: daysAgo(2),
      updatedAt: daysAgo(1),
      version: 1,
    },
    {
      id: 'cp-h',
      loadId: 'br-load-h',
      carrierNetworkProfileId: 'cn-blueline',
      carrierOrganizationId: 'client-g',
      confirmedAmountMinor: dollarsToMinor(1800),
      accessorialAmountMinor: 0,
      deductionsMinor: 0,
      totalPayableMinor: dollarsToMinor(1800),
      currency: 'USD',
      status: 'approved',
      factoringAssignmentOnFile: true,
      paymentDestinationProtected: true,
      createdAt: daysAgo(2),
      updatedAt: daysAgo(1),
      version: 1,
    },
  ];

  const coverageHistory: CoverageHistoryEvent[] = [
    {
      id: 'ch-b1',
      loadId: 'br-load-b',
      kind: 'offer_sent',
      carrierNetworkProfileId: 'cn-external',
      carrierOfferId: 'co-b-decline',
      summary: 'Offer sent to External Demo Trucking LLC',
      actorStaffId: 'staff-7',
      createdAt: daysAgo(2),
    },
    {
      id: 'ch-b2',
      loadId: 'br-load-b',
      kind: 'declined',
      carrierNetworkProfileId: 'cn-external',
      carrierOfferId: 'co-b-decline',
      summary: 'Carrier declined — equipment timing conflict',
      createdAt: daysAgo(1),
    },
  ];

  const issues: BrokerageIssue[] = [
    {
      id: 'bi-e-pod',
      loadId: 'br-load-e',
      type: 'pod_issue',
      severity: 'attention',
      status: 'open',
      summary: 'POD missing after delivery',
      customerVisible: true,
      createdAt: daysAgo(1),
      updatedAt: daysAgo(1),
    },
  ];

  const accessorials: BrokerageAccessorial[] = [];

  return {
    capability,
    shipperProfiles,
    shipmentRequests,
    freightQuotes,
    carrierNetwork,
    carrierOffers,
    rateConfirmations,
    loads,
    financials,
    accessorials,
    shipperInvoices,
    carrierPayables,
    issues,
    coverageHistory,
    counters: { shipmentRequest: 110, freightQuote: 202, shipperInvoice: 7 },
  };
}
