import type {
  CommConsentRecord,
  CommContextLink,
  CommConversation,
  CommDelivery,
  CommMessage,
  CommParticipant,
  CommPreference,
  CommReadState,
  CommRoutingRule,
  CommSettings,
  CommSuppression,
  CommTemplate,
} from '../communications/communicationTypes';

function daysAgo(now: Date, d: number): string {
  return new Date(now.getTime() - d * 86400000).toISOString();
}

export function createCommunicationsSeedData(now = new Date()) {
  const settings: CommSettings = {
    staleConversationDays: 14,
    defaultResponseDueBusinessDays: 2,
    businessHoursStart: '09:00',
    businessHoursEnd: '17:00',
    businessTimezone: 'America/Chicago',
    providerMode: 'demo',
  };

  const templates: CommTemplate[] = [
    {
      id: 'tpl-welcome',
      slug: 'welcome',
      name: 'Welcome',
      category: 'transactional',
      currentVersionId: 'tpl-welcome-v1',
      versions: [{
        id: 'tpl-welcome-v1',
        templateId: 'tpl-welcome',
        versionNumber: 1,
        status: 'published',
        portalBody: 'Welcome to All In One, {{first_name}}. We received your request for {{service_name}}.',
        emailBody: 'Welcome to All In One...',
        smsBody: 'All In One: Welcome {{first_name}}.',
        publishedAt: daysAgo(now, 30),
        createdAt: daysAgo(now, 30),
      }],
    },
    {
      id: 'tpl-docs-needed',
      slug: 'documents_needed',
      name: 'Documents Needed',
      category: 'service',
      currentVersionId: 'tpl-docs-v1',
      versions: [{
        id: 'tpl-docs-v1',
        templateId: 'tpl-docs-needed',
        versionNumber: 1,
        status: 'published',
        portalBody: 'We need {{document_name}} to continue {{service_name}}.',
        publishedAt: daysAgo(now, 20),
        createdAt: daysAgo(now, 20),
      }],
    },
  ];

  const routingRules: CommRoutingRule[] = [
    { id: 'route-permitting', conversationType: 'permitting', teamId: 'team-permitting', priority: 1, active: true },
    { id: 'route-insurance', conversationType: 'insurance', teamId: 'team-insurance', priority: 1, active: true },
    { id: 'route-dispatch', conversationType: 'dispatch', teamId: 'team-dispatch', priority: 1, active: true },
    { id: 'route-factoring', conversationType: 'factoring', teamId: 'team-factoring', priority: 1, active: true },
    { id: 'route-brokerage', conversationType: 'brokerage', teamId: 'team-brokerage', priority: 1, active: true },
    { id: 'route-billing', conversationType: 'billing', teamId: 'team-billing', priority: 1, active: true },
    { id: 'route-sales', conversationType: 'sales', teamId: 'team-support', priority: 1, active: true },
  ];

  const conversations: CommConversation[] = [
    {
      id: 'conv-a',
      leadId: 'lead-a',
      subject: 'Operating Authority — next steps',
      conversationType: 'sales',
      status: 'waiting_on_staff',
      priority: 'normal',
      responseResponsibility: 'staff',
      assignedUserId: 'staff-2',
      assignedTeamId: 'team-permitting',
      lastMessageAt: daysAgo(now, 0),
      lastCustomerMessageAt: daysAgo(now, 0),
      primaryContextType: 'lead',
      primaryContextId: 'lead-a',
      createdAt: daysAgo(now, 1),
      updatedAt: daysAgo(now, 0),
      isDemo: true,
    },
    {
      id: 'conv-b',
      organizationId: 'client-a',
      subject: 'IRP Documents Needed',
      conversationType: 'documents',
      status: 'waiting_on_customer',
      priority: 'normal',
      responseResponsibility: 'customer',
      assignedUserId: 'staff-2',
      assignedTeamId: 'team-permitting',
      lastMessageAt: daysAgo(now, 1),
      lastStaffMessageAt: daysAgo(now, 1),
      primaryContextType: 'service_request',
      primaryContextId: 'req-1',
      createdAt: daysAgo(now, 5),
      updatedAt: daysAgo(now, 1),
      isDemo: true,
    },
    {
      id: 'conv-c',
      organizationId: 'client-c',
      subject: 'Pickup delay — Load DEMO-1001',
      conversationType: 'dispatch',
      status: 'waiting_on_staff',
      priority: 'urgent',
      responseResponsibility: 'staff',
      assignedUserId: 'staff-4',
      assignedTeamId: 'team-dispatch',
      lastMessageAt: daysAgo(now, 0),
      lastCustomerMessageAt: daysAgo(now, 0),
      primaryContextType: 'load',
      primaryContextId: 'load-1',
      createdAt: daysAgo(now, 2),
      updatedAt: daysAgo(now, 0),
      isDemo: true,
    },
    {
      id: 'conv-d',
      organizationId: 'client-d',
      subject: 'Factoring submission status',
      conversationType: 'factoring',
      status: 'waiting_on_staff',
      priority: 'normal',
      responseResponsibility: 'staff',
      assignedUserId: 'staff-6',
      assignedTeamId: 'team-factoring',
      lastMessageAt: daysAgo(now, 1),
      lastCustomerMessageAt: daysAgo(now, 1),
      primaryContextType: 'factoring_submission',
      primaryContextId: 'fs-1',
      createdAt: daysAgo(now, 3),
      updatedAt: daysAgo(now, 1),
      isDemo: true,
    },
    {
      id: 'conv-e-shipper',
      organizationId: 'client-e',
      subject: 'Recurring lane — Chicago to Dallas',
      conversationType: 'brokerage',
      status: 'waiting_on_staff',
      priority: 'normal',
      responseResponsibility: 'staff',
      assignedUserId: 'staff-7',
      assignedTeamId: 'team-brokerage',
      lastMessageAt: daysAgo(now, 2),
      lastCustomerMessageAt: daysAgo(now, 2),
      primaryContextType: 'shipment',
      primaryContextId: 'ship-req-1',
      createdAt: daysAgo(now, 4),
      updatedAt: daysAgo(now, 2),
      isDemo: true,
    },
    {
      id: 'conv-f',
      organizationId: 'client-g',
      subject: 'Insurance information submitted',
      conversationType: 'insurance',
      status: 'waiting_external',
      priority: 'normal',
      responseResponsibility: 'external',
      assignedUserId: 'staff-5',
      assignedTeamId: 'team-insurance',
      lastMessageAt: daysAgo(now, 1),
      lastCustomerMessageAt: daysAgo(now, 2),
      primaryContextType: 'insurance_request',
      primaryContextId: 'ins-req-1',
      createdAt: daysAgo(now, 6),
      updatedAt: daysAgo(now, 1),
      isDemo: true,
    },
    {
      id: 'conv-g',
      leadId: 'lead-b',
      subject: 'New Business Consultation',
      conversationType: 'appointment',
      status: 'open',
      priority: 'normal',
      responseResponsibility: 'none',
      assignedUserId: 'staff-2',
      lastMessageAt: daysAgo(now, 1),
      lastStaffMessageAt: daysAgo(now, 1),
      primaryContextType: 'appointment',
      primaryContextId: 'appt-tomorrow',
      createdAt: daysAgo(now, 3),
      updatedAt: daysAgo(now, 1),
      isDemo: true,
    },
    {
      id: 'conv-h',
      organizationId: 'client-b',
      subject: 'Invoice question — resolved',
      conversationType: 'billing',
      status: 'resolved',
      priority: 'normal',
      responseResponsibility: 'none',
      assignedUserId: 'staff-8',
      assignedTeamId: 'team-billing',
      lastMessageAt: daysAgo(now, 5),
      lastStaffMessageAt: daysAgo(now, 5),
      primaryContextType: 'invoice',
      primaryContextId: 'inv-1',
      createdAt: daysAgo(now, 10),
      updatedAt: daysAgo(now, 5),
      closedAt: daysAgo(now, 5),
      isDemo: true,
    },
  ];

  const contextLinks: CommContextLink[] = [
    { id: 'ctx-b1', conversationId: 'conv-b', entityType: 'service_request', entityId: 'req-1', relationshipType: 'primary', label: 'Operating Authority' },
    { id: 'ctx-c1', conversationId: 'conv-c', entityType: 'load', entityId: 'load-1', relationshipType: 'primary', label: 'DEMO-1001' },
    { id: 'ctx-d1', conversationId: 'conv-d', entityType: 'factoring_submission', entityId: 'fs-1', relationshipType: 'primary' },
  ];

  const participants: CommParticipant[] = conversations.flatMap((c) => {
    const parts: CommParticipant[] = [];
    if (c.organizationId) {
      parts.push({ id: `part-${c.id}-cust`, conversationId: c.id, kind: 'contact', participantId: c.organizationId, displayName: c.organizationId });
    }
    if (c.leadId) {
      parts.push({ id: `part-${c.id}-lead`, conversationId: c.id, kind: 'prospect', participantId: c.leadId, displayName: c.leadId });
    }
    if (c.assignedUserId) {
      parts.push({ id: `part-${c.id}-staff`, conversationId: c.id, kind: 'staff', participantId: c.assignedUserId, displayName: c.assignedUserId });
    }
    return parts;
  });

  const messages: CommMessage[] = [
    {
      id: 'msg-conv-a-1',
      conversationId: 'conv-a',
      senderType: 'customer',
      senderName: 'Jordan Reed',
      channel: 'portal',
      direction: 'inbound',
      visibility: 'customer_visible',
      body: 'I already have my USDOT number. What do I need to do next?',
      status: 'sent',
      createdAt: daysAgo(now, 0),
      sentAt: daysAgo(now, 0),
      isDemo: true,
    },
    {
      id: 'msg-conv-b-1',
      conversationId: 'conv-b',
      senderType: 'staff',
      senderId: 'staff-2',
      senderName: 'Jordan Lee',
      channel: 'portal',
      direction: 'outbound',
      visibility: 'customer_visible',
      body: 'Hi Marcus — we need your EIN confirmation letter and Articles of Organization to continue IRP setup.',
      status: 'sent',
      createdAt: daysAgo(now, 1),
      sentAt: daysAgo(now, 1),
      isDemo: true,
    },
    {
      id: 'msg-conv-b-int',
      conversationId: 'conv-b',
      senderType: 'staff',
      senderId: 'staff-2',
      senderName: 'Jordan Lee',
      channel: 'portal',
      direction: 'internal',
      visibility: 'internal_only',
      body: 'Customer promised upload by Friday — follow up if missing.',
      status: 'sent',
      createdAt: daysAgo(now, 1),
      sentAt: daysAgo(now, 1),
      isDemo: true,
    },
    {
      id: 'msg-conv-c-1',
      conversationId: 'conv-c',
      senderType: 'customer',
      senderName: 'Chris Nguyen',
      channel: 'portal',
      direction: 'inbound',
      visibility: 'customer_visible',
      body: 'Driver reports pickup delay at shipper — ETA pushed 2 hours.',
      status: 'sent',
      createdAt: daysAgo(now, 0),
      sentAt: daysAgo(now, 0),
      isDemo: true,
    },
    {
      id: 'msg-conv-d-1',
      conversationId: 'conv-d',
      senderType: 'customer',
      senderName: 'Kevin Shaw',
      channel: 'portal',
      direction: 'inbound',
      visibility: 'customer_visible',
      body: 'Was my invoice submitted to the factor yet?',
      status: 'sent',
      createdAt: daysAgo(now, 1),
      sentAt: daysAgo(now, 1),
      isDemo: true,
    },
    {
      id: 'msg-conv-e-1',
      conversationId: 'conv-e-shipper',
      senderType: 'customer',
      senderName: 'Elena Vasquez',
      channel: 'portal',
      direction: 'inbound',
      visibility: 'customer_visible',
      body: 'Looking for recurring dry van capacity Chicago to Dallas weekly.',
      status: 'sent',
      createdAt: daysAgo(now, 2),
      sentAt: daysAgo(now, 2),
      isDemo: true,
    },
    {
      id: 'msg-conv-f-1',
      conversationId: 'conv-f',
      senderType: 'customer',
      senderName: 'Pat Ridge',
      channel: 'portal',
      direction: 'inbound',
      visibility: 'customer_visible',
      body: 'Uploaded loss runs and vehicle schedule as requested.',
      status: 'sent',
      createdAt: daysAgo(now, 2),
      sentAt: daysAgo(now, 2),
      isDemo: true,
    },
    {
      id: 'msg-conv-h-1',
      conversationId: 'conv-h',
      senderType: 'staff',
      senderId: 'staff-8',
      senderName: 'Jamie Ortiz',
      channel: 'portal',
      direction: 'outbound',
      visibility: 'customer_visible',
      body: 'Your invoice question is resolved — payment posted to your account.',
      status: 'read',
      createdAt: daysAgo(now, 5),
      sentAt: daysAgo(now, 5),
      readAt: daysAgo(now, 4),
      isDemo: true,
    },
  ];

  const deliveries: CommDelivery[] = messages
    .filter((m) => m.channel === 'portal' && m.visibility === 'customer_visible')
    .map((m) => ({
      id: `del-${m.id}`,
      messageId: m.id,
      channel: 'portal' as const,
      provider: 'internal',
      status: m.status,
      sentAt: m.sentAt,
    }));

  const preferences: CommPreference[] = [
    {
      id: 'pref-lead-a',
      leadId: 'lead-a',
      preferredChannel: 'phone_log',
      emailAllowed: true,
      smsAllowed: false,
      portalAllowed: true,
      phoneAllowed: true,
      marketingEmailAllowed: false,
      marketingSmsAllowed: false,
      timezone: 'America/Chicago',
      updatedAt: daysAgo(now, 1),
    },
    {
      id: 'pref-client-a',
      organizationId: 'client-a',
      preferredChannel: 'portal',
      emailAllowed: true,
      smsAllowed: true,
      portalAllowed: true,
      phoneAllowed: true,
      marketingEmailAllowed: false,
      marketingSmsAllowed: false,
      timezone: 'America/Chicago',
      updatedAt: daysAgo(now, 5),
    },
  ];

  const consentRecords: CommConsentRecord[] = [
    {
      id: 'consent-lead-a-email',
      leadId: 'lead-a',
      channel: 'email',
      purpose: 'transactional',
      state: 'granted',
      source: 'contact_form',
      recordedAt: daysAgo(now, 1),
    },
    {
      id: 'consent-lead-a-sms-mkt',
      leadId: 'lead-a',
      channel: 'sms',
      purpose: 'marketing',
      state: 'declined',
      source: 'contact_form',
      recordedAt: daysAgo(now, 1),
    },
  ];

  const suppressions: CommSuppression[] = [
    {
      id: 'sup-lead-j',
      leadId: 'lead-j',
      channel: 'all',
      reason: 'do_not_contact',
      createdAt: daysAgo(now, 3),
      createdBy: 'staff-1',
      active: true,
    },
  ];

  const readStates: CommReadState[] = [
    { id: 'read-b', conversationId: 'conv-b', participantKind: 'contact', participantId: 'client-a', lastReadAt: daysAgo(now, 2) },
  ];

  return {
    commSettings: settings,
    commTemplates: templates,
    commRoutingRules: routingRules,
    commConversations: conversations,
    commContextLinks: contextLinks,
    commParticipants: participants,
    commMessages: messages,
    commDeliveries: deliveries,
    commPreferences: preferences,
    commConsentRecords: consentRecords,
    commSuppressions: suppressions,
    commReadStates: readStates,
    commPhoneLogs: [],
    commAttachments: [],
  };
}
