import type {
  CrmActivity,
  CrmFollowUp,
  CrmLead,
  CrmLeadSource,
  CrmLostReason,
  CrmOpportunity,
  CrmPipeline,
  CrmPipelineStage,
  CrmReferral,
  CrmServiceInterest,
  CrmSettings,
} from '../crm/crmTypes';
import { CARRIER_PIPELINE_ID, SHIPPER_PIPELINE_ID } from '../crm/crmTypes';
import type { Quote } from '../billing/billingTypes';
import { dollarsToMinor } from '../billing/money';

function daysAgo(now: Date, d: number): string {
  return new Date(now.getTime() - d * 86400000).toISOString();
}

function daysAhead(now: Date, d: number): string {
  return new Date(now.getTime() + d * 86400000).toISOString();
}

function secureToken(): string {
  return `qt_${crypto.randomUUID().replace(/-/g, '')}`;
}

export function createCrmSeedData(now = new Date()) {
  const sources: CrmLeadSource[] = [
    { id: 'src-website', slug: 'website', name: 'Website' },
    { id: 'src-intake', slug: 'smart_intake', name: 'Smart Intake' },
    { id: 'src-phone', slug: 'phone', name: 'Phone' },
    { id: 'src-referral', slug: 'referral', name: 'Referral' },
    { id: 'src-service', slug: 'service_page', name: 'Service Page' },
    { id: 'src-callback', slug: 'callback', name: 'Callback Request' },
    { id: 'src-unknown', slug: 'unknown', name: 'Unknown' },
  ];

  const pipelines: CrmPipeline[] = [
    { id: CARRIER_PIPELINE_ID, slug: 'carrier-services', name: 'Carrier Services Pipeline' },
    { id: SHIPPER_PIPELINE_ID, slug: 'shipper', name: 'Shipper / Brokerage Sales Pipeline' },
  ];

  const carrierStages: CrmPipelineStage[] = [
    { id: 'cs-new', pipelineId: CARRIER_PIPELINE_ID, slug: 'new_inquiry', name: 'New Inquiry', sortOrder: 1 },
    { id: 'cs-contacted', pipelineId: CARRIER_PIPELINE_ID, slug: 'contacted', name: 'Contacted', sortOrder: 2 },
    { id: 'cs-discovery', pipelineId: CARRIER_PIPELINE_ID, slug: 'discovery', name: 'Discovery', sortOrder: 3 },
    { id: 'cs-qualified', pipelineId: CARRIER_PIPELINE_ID, slug: 'qualified', name: 'Qualified', sortOrder: 4 },
    { id: 'cs-solution', pipelineId: CARRIER_PIPELINE_ID, slug: 'solution_selected', name: 'Solution / Services Selected', sortOrder: 5 },
    { id: 'cs-quote-prep', pipelineId: CARRIER_PIPELINE_ID, slug: 'quote_preparation', name: 'Quote Preparation', sortOrder: 6 },
    { id: 'cs-quote-sent', pipelineId: CARRIER_PIPELINE_ID, slug: 'quote_sent', name: 'Quote Sent', sortOrder: 7 },
    { id: 'cs-decision', pipelineId: CARRIER_PIPELINE_ID, slug: 'decision', name: 'Decision', sortOrder: 8 },
    { id: 'cs-won', pipelineId: CARRIER_PIPELINE_ID, slug: 'won', name: 'Won', sortOrder: 9, isTerminal: true, isWon: true },
    { id: 'cs-lost', pipelineId: CARRIER_PIPELINE_ID, slug: 'lost', name: 'Lost', sortOrder: 10, isTerminal: true, isLost: true },
  ];

  const shipperStages: CrmPipelineStage[] = [
    { id: 'sh-new', pipelineId: SHIPPER_PIPELINE_ID, slug: 'new_shipper', name: 'New Shipper Lead', sortOrder: 1 },
    { id: 'sh-contacted', pipelineId: SHIPPER_PIPELINE_ID, slug: 'contacted', name: 'Contacted', sortOrder: 2 },
    { id: 'sh-qualified', pipelineId: SHIPPER_PIPELINE_ID, slug: 'qualified', name: 'Qualified', sortOrder: 3 },
    { id: 'sh-discovery', pipelineId: SHIPPER_PIPELINE_ID, slug: 'freight_discovery', name: 'Lane / Freight Discovery', sortOrder: 4 },
    { id: 'sh-pricing', pipelineId: SHIPPER_PIPELINE_ID, slug: 'pricing_quote', name: 'Pricing / Quote', sortOrder: 5 },
    { id: 'sh-decision', pipelineId: SHIPPER_PIPELINE_ID, slug: 'decision', name: 'Decision', sortOrder: 6 },
    { id: 'sh-active', pipelineId: SHIPPER_PIPELINE_ID, slug: 'active_shipper', name: 'Active Shipper', sortOrder: 7, isTerminal: true, isWon: true },
    { id: 'sh-lost', pipelineId: SHIPPER_PIPELINE_ID, slug: 'lost', name: 'Lost', sortOrder: 8, isTerminal: true, isLost: true },
  ];

  const lostReasons: CrmLostReason[] = [
    { id: 'lr-timing', slug: 'timing', label: 'Timing' },
    { id: 'lr-price', slug: 'price', label: 'Price' },
    { id: 'lr-no-response', slug: 'no_response', label: 'No Response' },
    { id: 'lr-not-qualified', slug: 'not_qualified', label: 'Not Qualified' },
    { id: 'lr-competitor', slug: 'competitor', label: 'Chose Another Provider' },
    { id: 'lr-other', slug: 'other', label: 'Other' },
  ];

  const leads: CrmLead[] = [
    {
      id: 'lead-a',
      firstName: 'Marcus',
      lastName: 'Reeves',
      businessName: 'Reeves Hauling',
      email: 'marcus.reeves@demo.local',
      phone: '555-0101',
      preferredContactMethod: 'phone',
      leadType: 'owner_operator',
      leadSourceId: 'src-website',
      originalSourceId: 'src-website',
      latestSourceId: 'src-website',
      status: 'new',
      priority: 'normal',
      qualificationState: 'not_started',
      createdAt: daysAgo(now, 0),
      updatedAt: daysAgo(now, 0),
      isDemo: true,
    },
    {
      id: 'lead-b',
      firstName: 'Tanya',
      lastName: 'Brooks',
      businessName: 'Brooks Freight Start LLC',
      email: 'tanya.brooks@demo.local',
      phone: '555-0102',
      leadType: 'new_trucking_business',
      leadSourceId: 'src-intake',
      originalSourceId: 'src-intake',
      latestSourceId: 'src-intake',
      status: 'qualifying',
      priority: 'high',
      assignedUserId: 'staff-2',
      assignedTeamId: 'team-permitting',
      qualificationState: 'in_progress',
      firstStaffActionAt: daysAgo(now, 1),
      createdAt: daysAgo(now, 2),
      updatedAt: daysAgo(now, 0),
      isDemo: true,
    },
    {
      id: 'lead-c',
      firstName: 'Devon',
      lastName: 'Walsh',
      businessName: 'Walsh Transport Co',
      email: 'devon.walsh@demo.local',
      phone: '555-0103',
      leadType: 'existing_carrier',
      leadSourceId: 'src-phone',
      originalSourceId: 'src-phone',
      latestSourceId: 'src-phone',
      status: 'qualified',
      priority: 'normal',
      assignedUserId: 'staff-4',
      assignedTeamId: 'team-dispatch',
      qualificationState: 'complete',
      qualifiedAt: daysAgo(now, 1),
      firstContactAt: daysAgo(now, 3),
      createdAt: daysAgo(now, 5),
      updatedAt: daysAgo(now, 1),
      isDemo: true,
    },
    {
      id: 'lead-d',
      firstName: 'Riley',
      lastName: 'Chen',
      businessName: 'Heartland Freight LLC',
      email: 'dispatch@heartland.demo',
      phone: '555-0104',
      leadType: 'existing_carrier',
      leadSourceId: 'src-phone',
      status: 'qualified',
      priority: 'normal',
      organizationId: 'client-b',
      assignedUserId: 'staff-6',
      assignedTeamId: 'team-factoring',
      qualificationState: 'complete',
      qualifiedAt: daysAgo(now, 2),
      createdAt: daysAgo(now, 4),
      updatedAt: daysAgo(now, 1),
      isDemo: true,
    },
    {
      id: 'lead-e',
      firstName: 'Pat',
      lastName: 'Nguyen',
      businessName: 'Midwest Produce Co',
      email: 'pat.nguyen@demo.local',
      phone: '555-0105',
      leadType: 'shipper',
      leadSourceId: 'src-referral',
      originalSourceId: 'src-referral',
      latestSourceId: 'src-referral',
      status: 'qualified',
      priority: 'high',
      assignedUserId: 'staff-7',
      assignedTeamId: 'team-brokerage',
      qualificationState: 'complete',
      createdAt: daysAgo(now, 6),
      updatedAt: daysAgo(now, 1),
      isDemo: true,
    },
    {
      id: 'lead-f',
      firstName: 'Jordan',
      lastName: 'Lee',
      businessName: 'Peakline Logistics',
      email: 'jordan.peakline@demo.local',
      phone: '555-0106',
      leadType: 'owner_operator',
      leadSourceId: 'src-website',
      status: 'qualified',
      priority: 'high',
      assignedUserId: 'staff-2',
      qualificationState: 'complete',
      firstContactAt: daysAgo(now, 5),
      createdAt: daysAgo(now, 7),
      updatedAt: daysAgo(now, 0),
      isDemo: true,
    },
    {
      id: 'lead-g',
      firstName: 'Avery',
      lastName: 'Stone',
      businessName: 'Apex Route Logistics LLC',
      email: 'avery@apexroute.demo',
      phone: '555-0107',
      leadType: 'new_trucking_business',
      leadSourceId: 'src-intake',
      status: 'qualified',
      priority: 'urgent',
      assignedUserId: 'staff-2',
      qualificationState: 'complete',
      qualifiedAt: daysAgo(now, 1),
      createdAt: daysAgo(now, 10),
      updatedAt: daysAgo(now, 0),
      isDemo: true,
    },
    {
      id: 'lead-h',
      firstName: 'Sam',
      lastName: 'Ortiz',
      businessName: 'Future Haul LLC',
      email: 'sam.future@demo.local',
      phone: '555-0108',
      leadType: 'new_trucking_business',
      leadSourceId: 'src-website',
      status: 'nurturing',
      priority: 'normal',
      qualificationState: 'complete',
      createdAt: daysAgo(now, 30),
      updatedAt: daysAgo(now, 5),
      isDemo: true,
    },
    {
      id: 'lead-i',
      firstName: 'Chris',
      lastName: 'Morgan',
      businessName: 'Morgan Express',
      email: 'chris.morgan@demo.local',
      phone: '555-0109',
      leadType: 'existing_carrier',
      leadSourceId: 'src-service',
      status: 'lost',
      priority: 'normal',
      qualificationState: 'complete',
      createdAt: daysAgo(now, 20),
      updatedAt: daysAgo(now, 3),
      isDemo: true,
    },
    {
      id: 'lead-j',
      firstName: 'Alex',
      lastName: 'Kim',
      email: 'alex.kim@demo.local',
      phone: '555-0110',
      leadType: 'unknown',
      leadSourceId: 'src-callback',
      status: 'do_not_contact',
      priority: 'normal',
      doNotContact: true,
      doNotContactReason: 'Requested no contact',
      doNotContactAt: daysAgo(now, 2),
      doNotContactById: 'staff-9',
      consent: { emailContactAllowed: false, smsContactAllowed: false, marketingOptIn: false },
      qualificationState: 'not_started',
      createdAt: daysAgo(now, 15),
      updatedAt: daysAgo(now, 2),
      isDemo: true,
    },
  ];

  const interests: CrmServiceInterest[] = [
    { id: 'si-a1', leadId: 'lead-a', serviceSlug: 'operating-authority-assistance', serviceTitle: 'Operating Authority Assistance', state: 'interested', createdAt: daysAgo(now, 0) },
    { id: 'si-a2', leadId: 'lead-a', serviceSlug: 'boc-3-assistance', serviceTitle: 'BOC-3 Process Agent Assistance', state: 'interested', createdAt: daysAgo(now, 0) },
    { id: 'si-b1', leadId: 'lead-b', serviceSlug: 'llc-formation-assistance', serviceTitle: 'LLC Formation Assistance', state: 'discussing', createdAt: daysAgo(now, 2) },
    { id: 'si-b2', leadId: 'lead-b', serviceSlug: 'operating-authority-assistance', serviceTitle: 'Operating Authority Assistance', state: 'recommended', createdAt: daysAgo(now, 2) },
    { id: 'si-b3', leadId: 'lead-b', serviceSlug: 'irp-apportioned-registration', serviceTitle: 'IRP Apportioned Registration Assistance', state: 'interested', createdAt: daysAgo(now, 2) },
    { id: 'si-b4', leadId: 'lead-b', serviceSlug: 'commercial-auto-liability', serviceTitle: 'Commercial Auto Liability', state: 'interested', createdAt: daysAgo(now, 2) },
    { id: 'si-c1', leadId: 'lead-c', serviceSlug: 'dispatching', serviceTitle: 'Dispatch Support', state: 'quote_requested', createdAt: daysAgo(now, 5) },
    { id: 'si-d1', leadId: 'lead-d', serviceSlug: 'factoring', serviceTitle: 'Factoring Assistance', state: 'discussing', createdAt: daysAgo(now, 4) },
    { id: 'si-e1', leadId: 'lead-e', serviceSlug: 'brokerage', serviceTitle: 'Brokerage Services', state: 'quote_included', createdAt: daysAgo(now, 6) },
    { id: 'si-g1', leadId: 'lead-g', serviceSlug: 'operating-authority-assistance', serviceTitle: 'Operating Authority Assistance', state: 'quote_included', createdAt: daysAgo(now, 10) },
    { id: 'si-g2', leadId: 'lead-g', serviceSlug: 'boc-3-assistance', serviceTitle: 'BOC-3 Process Agent Assistance', state: 'quote_included', createdAt: daysAgo(now, 10) },
  ];

  const quoteGToken = secureToken();
  const quoteFToken = secureToken();

  const demoQuotes: Quote[] = [
    {
      id: 'quote-crm-g',
      quoteNumber: 'AIO-QTE-2026-000099',
      organizationId: 'prospect-lead-g',
      leadId: 'lead-g',
      opportunityId: 'opp-g',
      secureToken: quoteGToken,
      serviceTitle: 'Startup Package — USDOT, Authority, BOC-3',
      status: 'accepted',
      currentVersionId: 'quote-crm-g-v1',
      versions: [{
        id: 'quote-crm-g-v1',
        quoteId: 'quote-crm-g',
        versionNumber: 1,
        lineItems: [
          { id: 'li1', description: 'USDOT Registration Assistance', quantity: 1, unitAmountMinor: dollarsToMinor(199), lineAmountMinor: dollarsToMinor(199), feeCategory: 'service_fee', amountStatus: 'known' },
          { id: 'li2', description: 'Operating Authority Assistance', quantity: 1, unitAmountMinor: dollarsToMinor(499), lineAmountMinor: dollarsToMinor(499), feeCategory: 'service_fee', amountStatus: 'known' },
          { id: 'li3', description: 'BOC-3 Process Agent Assistance', quantity: 1, unitAmountMinor: dollarsToMinor(125), lineAmountMinor: dollarsToMinor(125), feeCategory: 'service_fee', amountStatus: 'known' },
          { id: 'li4', description: 'FMCSA filing fee (estimated pass-through)', quantity: 1, unitAmountMinor: dollarsToMinor(300), lineAmountMinor: dollarsToMinor(300), feeCategory: 'government_fee', amountStatus: 'estimated', notes: 'Government fee — pass-through' },
        ],
        subtotalServiceFeesMinor: dollarsToMinor(823),
        subtotalExternalFeesMinor: dollarsToMinor(300),
        discountTotalMinor: 0,
        taxTotalMinor: 0,
        totalKnownMinor: dollarsToMinor(1123),
        hasPendingExternalFees: true,
        createdAt: daysAgo(now, 3),
        createdByStaffId: 'staff-2',
      }],
      issueDate: new Date(now.getTime() - 3 * 86400000).toISOString().slice(0, 10),
      expirationDate: new Date(now.getTime() + 14 * 86400000).toISOString().slice(0, 10),
      preparedByStaffId: 'staff-2',
      acceptance: {
        versionId: 'quote-crm-g-v1',
        acceptedAt: daysAgo(now, 0),
        totalAcceptedMinor: dollarsToMinor(1123),
        acceptedByLabel: 'Avery Stone',
      },
      createdAt: daysAgo(now, 4),
      updatedAt: daysAgo(now, 0),
    },
    {
      id: 'quote-crm-f',
      quoteNumber: 'AIO-QTE-2026-000088',
      organizationId: 'prospect-lead-f',
      leadId: 'lead-f',
      opportunityId: 'opp-f',
      secureToken: quoteFToken,
      serviceTitle: 'Authority + BOC-3',
      status: 'sent',
      currentVersionId: 'quote-crm-f-v1',
      versions: [{
        id: 'quote-crm-f-v1',
        quoteId: 'quote-crm-f',
        versionNumber: 1,
        lineItems: [
          { id: 'li5', description: 'Operating Authority Assistance', quantity: 1, unitAmountMinor: dollarsToMinor(499), lineAmountMinor: dollarsToMinor(499), feeCategory: 'service_fee', amountStatus: 'known' },
          { id: 'li6', description: 'BOC-3 Process Agent Assistance', quantity: 1, unitAmountMinor: dollarsToMinor(125), lineAmountMinor: dollarsToMinor(125), feeCategory: 'service_fee', amountStatus: 'known' },
        ],
        subtotalServiceFeesMinor: dollarsToMinor(624),
        subtotalExternalFeesMinor: 0,
        discountTotalMinor: 0,
        taxTotalMinor: 0,
        totalKnownMinor: dollarsToMinor(624),
        hasPendingExternalFees: false,
        createdAt: daysAgo(now, 4),
        createdByStaffId: 'staff-2',
      }],
      issueDate: new Date(now.getTime() - 4 * 86400000).toISOString().slice(0, 10),
      expirationDate: new Date(now.getTime() + 10 * 86400000).toISOString().slice(0, 10),
      preparedByStaffId: 'staff-2',
      createdAt: daysAgo(now, 4),
      updatedAt: daysAgo(now, 2),
    },
  ];

  const opportunities: CrmOpportunity[] = [
    { id: 'opp-c', leadId: 'lead-c', name: 'Dispatch Service', status: 'open', pipelineId: CARRIER_PIPELINE_ID, pipelineStageId: 'cs-quote-prep', assignedUserId: 'staff-4', estimatedValueMinor: dollarsToMinor(1500), createdAt: daysAgo(now, 3), updatedAt: daysAgo(now, 1), isDemo: true },
    { id: 'opp-d', leadId: 'lead-d', name: 'Factoring Assistance', status: 'open', pipelineId: CARRIER_PIPELINE_ID, pipelineStageId: 'cs-discovery', organizationId: 'client-b', assignedUserId: 'staff-6', createdAt: daysAgo(now, 4), updatedAt: daysAgo(now, 1), isDemo: true },
    { id: 'opp-e', leadId: 'lead-e', name: 'Recurring Lane — Midwest Produce', status: 'open', pipelineId: SHIPPER_PIPELINE_ID, pipelineStageId: 'sh-pricing', assignedUserId: 'staff-7', estimatedValueMinor: dollarsToMinor(5000), createdAt: daysAgo(now, 5), updatedAt: daysAgo(now, 1), isDemo: true },
    { id: 'opp-f', leadId: 'lead-f', name: 'Authority Package', status: 'open', pipelineId: CARRIER_PIPELINE_ID, pipelineStageId: 'cs-decision', quoteId: 'quote-crm-f', assignedUserId: 'staff-2', estimatedValueMinor: dollarsToMinor(624), createdAt: daysAgo(now, 6), updatedAt: daysAgo(now, 2), isDemo: true },
    { id: 'opp-g', leadId: 'lead-g', name: 'Startup Package', status: 'open', pipelineId: CARRIER_PIPELINE_ID, pipelineStageId: 'cs-decision', quoteId: 'quote-crm-g', assignedUserId: 'staff-2', estimatedValueMinor: dollarsToMinor(1123), createdAt: daysAgo(now, 8), updatedAt: daysAgo(now, 0), isDemo: true },
    { id: 'opp-i', leadId: 'lead-i', name: 'IRP Renewal', status: 'lost', pipelineId: CARRIER_PIPELINE_ID, pipelineStageId: 'cs-lost', lostReasonId: 'lr-timing', lostAt: daysAgo(now, 3), createdAt: daysAgo(now, 15), updatedAt: daysAgo(now, 3), isDemo: true },
  ];

  const activities: CrmActivity[] = [
    { id: 'act-crm-1', leadId: 'lead-b', activityType: 'note', title: 'Smart Intake completed', body: 'Prospect starting trucking business — multiple services identified.', createdAt: daysAgo(now, 2), isDemo: true },
    { id: 'act-crm-2', leadId: 'lead-f', activityType: 'quote_sent', title: 'Quote sent — AIO-QTE-2026-000088', createdAt: daysAgo(now, 2), actorStaffId: 'staff-2', isDemo: true },
    { id: 'act-crm-3', leadId: 'lead-g', activityType: 'quote_sent', title: 'Quote sent — startup package', createdAt: daysAgo(now, 3), actorStaffId: 'staff-2', isDemo: true },
    { id: 'act-crm-4', leadId: 'lead-g', activityType: 'customer_reply', title: 'Quote accepted online', body: 'Avery Stone accepted quote via secure link.', createdAt: daysAgo(now, 0), isDemo: true },
  ];

  const followUps: CrmFollowUp[] = [
    {
      id: 'fu-f',
      leadId: 'lead-f',
      opportunityId: 'opp-f',
      purpose: 'Follow up on sent quote',
      scheduledFor: daysAhead(now, 0),
      assignedUserId: 'staff-2',
      status: 'due',
      createdAt: daysAgo(now, 2),
      isDemo: true,
    },
    {
      id: 'fu-a',
      leadId: 'lead-a',
      purpose: 'First contact — new website lead',
      scheduledFor: daysAhead(now, 0),
      assignedUserId: 'staff-2',
      status: 'due',
      createdAt: daysAgo(now, 0),
      isDemo: true,
    },
  ];

  const referrals: CrmReferral[] = [
    { id: 'ref-e', referrerType: 'customer', referrerLabel: 'Summit Ridge Hauling (customer)', referredLeadId: 'lead-e', createdAt: daysAgo(now, 6), status: 'pending', isDemo: true },
  ];

  const settings: CrmSettings = {
    staleQualifiedDays: 7,
    staleQuoteSentDays: 5,
  };

  return {
    crmLeadSources: sources,
    crmPipelines: pipelines,
    crmPipelineStages: [...carrierStages, ...shipperStages],
    crmLostReasons: lostReasons,
    crmLeads: leads,
    crmServiceInterests: interests,
    crmOpportunities: opportunities,
    crmActivities: activities,
    crmFollowUps: followUps,
    crmReferrals: referrals,
    crmConversionRecords: [],
    crmSettings: settings,
    demoQuotes,
    quoteTokens: { g: quoteGToken, f: quoteFToken },
  };
}
