import { defaultIntakeAnswers } from '../intake/intakeTypes';
import type { DemoStore, StaffMember } from './demoTypes';
import { createRoadReadySeedData } from './roadReadySeed';
import { createVaultSeedData, defaultNotificationPreferences } from './vaultSeed';
import { createBillingSeedData, defaultServicePricingSeed } from './billingSeed';
import { createDispatchSeedData } from './dispatchSeed';
import { createFactoringSeedData } from './factoringSeed';
import { createBrokerageSeedData } from './brokerageSeed';
import { createInsuranceSeedData } from './insuranceSeed';
import { createCommandCenterSeedData } from './commandCenterSeed';

const STAFF: StaffMember[] = [
  { id: 'staff-1', name: 'Taylor Brooks', initials: 'TB', role: 'Administrator', status: 'available' },
  { id: 'staff-2', name: 'Jordan Lee', initials: 'JL', role: 'Permitting Specialist', status: 'available' },
  { id: 'staff-3', name: 'Casey Morgan', initials: 'CM', role: 'Compliance Specialist', status: 'busy' },
  { id: 'staff-4', name: 'Riley Chen', initials: 'RC', role: 'Dispatcher', status: 'available' },
  { id: 'staff-5', name: 'Alex Rivera', initials: 'AR', role: 'Insurance Specialist', status: 'available' },
  { id: 'staff-6', name: 'Sam Patel', initials: 'SP', role: 'Factoring Specialist', status: 'busy' },
  { id: 'staff-7', name: 'Morgan Hayes', initials: 'MH', role: 'Brokerage Specialist', status: 'available' },
  { id: 'staff-8', name: 'Jamie Ortiz', initials: 'JO', role: 'Support', status: 'available' },
];

export function createDemoSeed(): DemoStore {
  const now = new Date();
  const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000).toISOString();
  const daysAhead = (d: number) => new Date(now.getTime() + d * 86400000).toISOString().slice(0, 10);

  const billing = createBillingSeedData();
  const vault = createVaultSeedData();
  const dispatch = createDispatchSeedData();
  const factoring = createFactoringSeedData();
  const brokerage = createBrokerageSeedData();
  const insurance = createInsuranceSeedData();
  const commandCenter = createCommandCenterSeedData();

  const requests = [
      mkRequest('req-1', 'AIO-DEMO-0001', 'client-a', 'Authority + BOC-3 Assistance', 'permitting', 'new_request', 'staff-2', daysAgo(3), ['vdoc-a1', 'vdoc-a2']),
      mkRequest('req-2', 'AIO-DEMO-0002', 'client-b', 'IRP / Apportioned Registration', 'permitting', 'documents_needed', 'staff-2', daysAgo(10), ['vdoc-b2']),
      mkRequest('req-3', 'AIO-DEMO-0003', 'client-c', 'Carrier Dispatch Support', 'dispatching', 'in_progress', 'staff-4', daysAgo(5), []),
      mkRequest('req-4', 'AIO-DEMO-0004', 'client-e', 'Freight Quote', 'brokerage', 'under_review', 'staff-7', daysAgo(2), []),
    ].map((r) => {
      if (r.id === 'req-1') return { ...r, billingStatus: 'awaiting_quote_acceptance' as const };
      if (r.id === 'req-2') return { ...r, billingStatus: 'paid' as const, nextStep: 'Payment received — processing IRP renewal' };
      return r;
    });

  return {
    version: 12,
    requestCounter: 4,
    portalClientId: 'client-a',
    shipperPortalOrgId: 'client-e',
    brokeragePortalClientId: 'client-b',
    portalMemberRole: commandCenter.portalMemberRole,
    organizationMembers: commandCenter.organizationMembers,
    intake: defaultIntakeAnswers(),
    roadmap: null,
    servicePlan: [],
    staff: STAFF,
    clients: [
      {
        id: 'client-a',
        companyName: 'Summit Ridge Hauling LLC',
        contactName: 'Marcus Webb',
        contactEmail: 'marcus.demo@summitridge.example',
        clientType: 'owner_operator',
        primaryState: 'TX',
        accountStatus: 'pending',
        assignedStaffId: 'staff-2',
        roadmapProgress: 35,
        customerSince: daysAgo(14).slice(0, 10),
        services: ['Business Formation', 'Operating Authority'],
        activeRequestCount: 2,
        documentsNeededCount: 3,
        lastActivityAt: daysAgo(1),
      },
      {
        id: 'client-b',
        companyName: 'Heartland Freight Co.',
        contactName: 'Diana Cole',
        contactEmail: 'diana.demo@heartland.example',
        clientType: 'carrier',
        primaryState: 'OH',
        accountStatus: 'active',
        assignedStaffId: 'staff-3',
        roadmapProgress: 72,
        customerSince: daysAgo(120).slice(0, 10),
        services: ['IRP', 'IFTA', 'Renewals'],
        activeRequestCount: 1,
        documentsNeededCount: 1,
        lastActivityAt: daysAgo(0),
      },
      {
        id: 'client-c',
        companyName: 'Pioneer Fleet Services',
        contactName: 'Chris Nguyen',
        contactEmail: 'chris.demo@pioneerfleet.example',
        clientType: 'fleet',
        primaryState: 'GA',
        accountStatus: 'active',
        assignedStaffId: 'staff-4',
        roadmapProgress: 88,
        customerSince: daysAgo(200).slice(0, 10),
        services: ['Dispatch', 'Document Support'],
        activeRequestCount: 1,
        documentsNeededCount: 0,
        lastActivityAt: daysAgo(0),
      },
      {
        id: 'client-d',
        companyName: 'BlueLine Transport',
        contactName: 'Kevin Shaw',
        contactEmail: 'kevin.demo@blueline.example',
        clientType: 'carrier',
        primaryState: 'FL',
        accountStatus: 'active',
        assignedStaffId: 'staff-6',
        roadmapProgress: 90,
        customerSince: daysAgo(90).slice(0, 10),
        services: ['Factoring Consultation'],
        activeRequestCount: 1,
        documentsNeededCount: 2,
        lastActivityAt: daysAgo(2),
      },
      {
        id: 'client-e',
        companyName: 'NorthStar Manufacturing',
        contactName: 'Elena Vasquez',
        contactEmail: 'elena.demo@northstar.example',
        clientType: 'shipper',
        primaryState: 'IL',
        accountStatus: 'active',
        assignedStaffId: 'staff-7',
        roadmapProgress: 0,
        customerSince: daysAgo(7).slice(0, 10),
        services: ['Freight Quote', 'Shipment Coordination'],
        activeRequestCount: 1,
        documentsNeededCount: 0,
        lastActivityAt: daysAgo(1),
      },
      {
        id: 'shipper-demo-b',
        companyName: 'Lakeview Distribution Co.',
        contactName: 'Pat Morrison',
        contactEmail: 'pat.demo@lakeview.example',
        clientType: 'shipper',
        primaryState: 'IN',
        accountStatus: 'pending',
        assignedStaffId: 'staff-7',
        roadmapProgress: 0,
        customerSince: daysAgo(3).slice(0, 10),
        services: ['Brokerage'],
        activeRequestCount: 1,
        documentsNeededCount: 0,
        lastActivityAt: daysAgo(1),
      },
      {
        id: 'client-f',
        companyName: 'Delta Haul LLC',
        contactName: 'Chris Delta',
        contactEmail: 'chris.demo@deltahaul.example',
        clientType: 'owner_operator',
        primaryState: 'TN',
        accountStatus: 'active',
        assignedStaffId: 'staff-6',
        roadmapProgress: 80,
        customerSince: daysAgo(200).slice(0, 10),
        services: ['Dispatch', 'Factoring Assistance'],
        activeRequestCount: 0,
        documentsNeededCount: 0,
        lastActivityAt: daysAgo(5),
      },
      {
        id: 'client-g',
        companyName: 'RidgeLine Carriers',
        contactName: 'Pat Ridge',
        contactEmail: 'pat.demo@ridgeline.example',
        clientType: 'carrier',
        primaryState: 'GA',
        accountStatus: 'active',
        assignedStaffId: 'staff-6',
        roadmapProgress: 90,
        customerSince: daysAgo(300).slice(0, 10),
        services: ['Factoring (Existing Provider)'],
        activeRequestCount: 0,
        documentsNeededCount: 0,
        lastActivityAt: daysAgo(10),
      },
    ],
    requests,
    documents: vault.documents,
    renewals: vault.renewals,
    notes: [
      {
        id: 'note-1',
        clientId: 'client-a',
        requestId: 'req-1',
        authorId: 'staff-2',
        authorInitials: 'TB',
        body: 'Customer called regarding registration renewal. Waiting for updated insurance card.',
        createdAt: daysAgo(1),
        visibility: 'internal',
      },
    ],
    messages: [
      {
        id: 'msg-1',
        clientId: 'client-a',
        requestId: 'req-1',
        division: 'permitting',
        from: 'staff',
        authorName: 'Jordan Lee',
        body: 'Hi Marcus — we need your insurance certificate to continue with authority filing.',
        createdAt: daysAgo(2),
        visibility: 'customer',
        read: true,
      },
      {
        id: 'msg-2',
        clientId: 'client-a',
        requestId: 'req-1',
        from: 'customer',
        authorName: 'Marcus Webb',
        body: 'Thanks — I will upload as soon as my agent sends the updated certificate.',
        createdAt: daysAgo(1),
        visibility: 'customer',
        read: false,
      },
    ],
    tasks: [
      { id: 'task-1', title: 'Follow up for insurance card', clientId: 'client-a', requestId: 'req-1', assignedStaffId: 'staff-2', priority: 'high', status: 'open', category: 'Documents', dueDate: daysAhead(2), createdAt: daysAgo(1) },
      { id: 'task-2', title: 'Review authority documents', clientId: 'client-b', requestId: 'req-2', assignedStaffId: 'staff-2', priority: 'normal', status: 'in_progress', category: 'Permitting', dueDate: daysAhead(5), createdAt: daysAgo(3) },
      { id: 'task-3', title: 'Check permit renewal', clientId: 'client-b', assignedStaffId: 'staff-3', priority: 'urgent', status: 'open', category: 'Compliance', dueDate: daysAhead(1), createdAt: daysAgo(0) },
      { id: 'task-4', title: 'Review factoring invoice', clientId: 'client-d', assignedStaffId: 'staff-6', priority: 'normal', status: 'open', category: 'Factoring', dueDate: daysAhead(3), createdAt: daysAgo(2) },
      { id: 'task-5', title: 'Prepare brokerage quote', clientId: 'client-e', requestId: 'req-4', assignedStaffId: 'staff-7', priority: 'high', status: 'open', category: 'Brokerage', dueDate: daysAhead(1), createdAt: daysAgo(1) },
    ],
    deadlines: vault.deadlines.concat([
      { id: 'dl-5', label: 'Service request deadline — Authority filing', clientId: 'client-a', dueDate: daysAhead(7), severity: 'upcoming', category: 'Service Request', complete: false, requestId: 'req-1', source: 'service_request' },
    ]),
    activity: [
      evt('act-1', 'REQUEST_CREATED', 'Service request submitted', 'client-a', 'req-1', daysAgo(3)),
      evt('act-2', 'REQUEST_ASSIGNED', 'Request assigned to Jordan Lee', 'client-a', 'req-1', daysAgo(2)),
      evt('act-3', 'DOCUMENT_REQUESTED', 'Insurance Certificate requested', 'client-a', 'req-1', daysAgo(2)),
      evt('act-4', 'MESSAGE_SENT', 'Staff message sent to customer', 'client-a', 'req-1', daysAgo(2)),
      evt('act-5', 'LOAD_STATUS_CHANGED', 'Load in transit updated', 'client-b', undefined, daysAgo(1)),
      evt('act-6', 'FACTORING_STATUS_CHANGED', 'Factoring review opened', 'client-d', undefined, daysAgo(1)),
    ],
    loads: [...dispatch.loads, ...brokerage.loads],
    dispatchEnrollments: dispatch.enrollments,
    truckProfiles: dispatch.truckProfiles,
    brokerContacts: dispatch.brokerContacts,
    dispatchBillingConfigs: dispatch.dispatchBillingConfigs,
    dispatchBillingEvents: [],
    dispatchCounters: dispatch.dispatchCounters,
    factoringProviders: factoring.providers,
    factoringProfiles: factoring.profiles,
    debtorAccounts: factoring.debtors,
    freightInvoices: factoring.freightInvoices,
    factoringSubmissions: factoring.submissions,
    factoringIssues: factoring.issues,
    factoringCounters: factoring.counters,
    brokerageCapability: brokerage.capability,
    shipperProfiles: brokerage.shipperProfiles,
    shipmentRequests: brokerage.shipmentRequests,
    brokerageFreightQuotes: brokerage.freightQuotes,
    carrierNetworkProfiles: brokerage.carrierNetwork,
    carrierOffers: brokerage.carrierOffers,
    brokerageRateConfirmations: brokerage.rateConfirmations,
    brokerageLoadFinancials: brokerage.financials,
    brokerageAccessorials: brokerage.accessorials,
    brokerageShipperInvoices: brokerage.shipperInvoices,
    carrierPayables: brokerage.carrierPayables,
    brokerageIssues: brokerage.issues,
    coverageHistory: brokerage.coverageHistory,
    brokerageCounters: brokerage.counters,
    insuranceCapability: insurance.capability,
    insurancePartners: insurance.partners,
    insurancePolicies: insurance.policies,
    insurancePolicyCoverages: insurance.coverages,
    insurancePolicyVehicles: insurance.policyVehicles,
    insuranceRequests: insurance.requests,
    insurancePartnerHandoffs: insurance.handoffs,
    insuranceQuoteRecords: insurance.quoteRecords,
    insuranceCertificateHolders: insurance.certificateHolders,
    insuranceCertificates: insurance.certificates,
    insuranceIssues: insurance.issues,
    insuranceCounters: insurance.counters,
    brokerageQuotes: [],
    shipments: [],
    quotes: billing.quotes,
    invoices: billing.invoices,
    payments: billing.payments,
    receipts: billing.receipts,
    credits: billing.credits,
    servicePricing: defaultServicePricingSeed(),
    billingCounters: billing.billingCounters,
    billingEvaluatorLastRun: new Date().toISOString(),
    notifications: [...vault.notifications],
    notificationPreferences: defaultNotificationPreferences(),
    expirationEvaluatorLastRun: new Date().toISOString(),
    ...(() => {
      const rr = createRoadReadySeedData();
      return {
        roadReadyProfiles: rr.profiles,
        roadReadyItems: rr.items,
        roadReadyHistory: rr.history,
        roadReadyVerifications: rr.verifications,
        powerUnits: rr.powerUnits,
        trailers: rr.trailers,
        drivers: rr.drivers,
      };
    })(),
  };
}

function mkRequest(
  id: string,
  num: string,
  clientId: string,
  title: string,
  division: string,
  status: DemoStore['requests'][0]['status'],
  staffId: string,
  createdAt: string,
  docIds: string[],
) {
  const labels: Record<string, string> = {
    new_request: 'New Request',
    documents_needed: 'Documents Needed',
    in_progress: 'In Progress',
    under_review: 'Under Review',
  };
  return {
    id,
    requestNumber: num,
    clientId,
    services: [{ slug: division, title, division }],
    division,
    status,
    statusLabel: labels[status] ?? status,
    workflowStep: status,
    priority: 'normal' as const,
    assignedStaffId: staffId,
    createdAt,
    nextStep: status === 'documents_needed' ? 'Awaiting client documents' : 'Initial Review',
    timeline: [
      { id: 'received', label: 'Request Received', status: 'completed' as const },
      { id: 'review', label: 'Initial Review', status: status === 'new_request' ? ('current' as const) : ('completed' as const) },
      { id: 'docs', label: 'Documents Needed', status: status === 'documents_needed' ? ('current' as const) : ('upcoming' as const) },
      { id: 'submission', label: 'Submission', status: 'upcoming' as const },
      { id: 'complete', label: 'Complete', status: 'upcoming' as const },
    ],
    documentIds: docIds,
    taskIds: [],
    isDemo: true as const,
    businessName: undefined,
    contactName: undefined,
  };
}

function evt(
  id: string,
  kind: DemoStore['activity'][0]['kind'],
  title: string,
  clientId: string,
  requestId: string | undefined,
  createdAt: string,
) {
  return {
    id,
    kind,
    title,
    clientId,
    requestId,
    createdAt,
    visibility: 'internal' as const,
  };
}
