import { dollarsToMinor } from '../billing/money';
import type {
  DebtorAccount,
  FactoringCounters,
  FactoringIssue,
  FactoringProfile,
  FactoringProvider,
  FactoringSubmission,
  FreightInvoice,
} from '../factoring/factoringTypes';
import { daysAgo, daysAhead } from './dateHelpers';

export function createFactoringSeedData(): {
  providers: FactoringProvider[];
  profiles: FactoringProfile[];
  debtors: DebtorAccount[];
  freightInvoices: FreightInvoice[];
  submissions: FactoringSubmission[];
  issues: FactoringIssue[];
  counters: FactoringCounters;
} {
  const providers: FactoringProvider[] = [
    {
      id: 'fp-demo-partner',
      name: 'Demo Factor Partners LLC',
      providerType: 'demo',
      contactName: 'Alex Factor',
      phone: '(555) 010-9900',
      email: 'submissions@demofactor.example',
      submissionMethod: 'manual_portal',
      status: 'approved_partner',
      integrationType: 'manual',
      createdAt: daysAgo(365),
      updatedAt: daysAgo(30),
    },
    {
      id: 'fp-carrier-existing',
      name: 'Summit Receivables Co. (Carrier Existing)',
      providerType: 'external',
      submissionMethod: 'email',
      status: 'carrier_existing_provider',
      createdAt: daysAgo(200),
      updatedAt: daysAgo(10),
    },
  ];

  const profiles: FactoringProfile[] = [
    {
      id: 'fprof-a',
      organizationId: 'client-a',
      enrollmentStatus: 'interested',
      serviceMode: 'factoring_assistance',
      createdAt: daysAgo(5),
      updatedAt: daysAgo(5),
    },
    {
      id: 'fprof-b',
      organizationId: 'client-b',
      enrollmentStatus: 'active',
      serviceMode: 'partner_factoring',
      providerId: 'fp-demo-partner',
      advanceRateBasisPoints: 9500,
      reserveBasisPoints: 500,
      termVerification: 'self_reported',
      primarySpecialistStaffId: 'staff-6',
      createdAt: daysAgo(60),
      updatedAt: daysAgo(1),
    },
    {
      id: 'fprof-c',
      organizationId: 'client-c',
      enrollmentStatus: 'active',
      serviceMode: 'partner_factoring',
      providerId: 'fp-demo-partner',
      primarySpecialistStaffId: 'staff-6',
      createdAt: daysAgo(90),
      updatedAt: daysAgo(0),
    },
    {
      id: 'fprof-d',
      organizationId: 'client-d',
      enrollmentStatus: 'active',
      serviceMode: 'partner_factoring',
      providerId: 'fp-demo-partner',
      primarySpecialistStaffId: 'staff-6',
      createdAt: daysAgo(45),
      updatedAt: daysAgo(0),
    },
    {
      id: 'fprof-e',
      organizationId: 'client-e',
      enrollmentStatus: 'active',
      serviceMode: 'partner_factoring',
      providerId: 'fp-demo-partner',
      primarySpecialistStaffId: 'staff-6',
      createdAt: daysAgo(30),
      updatedAt: daysAgo(2),
    },
    {
      id: 'fprof-f',
      organizationId: 'client-f',
      enrollmentStatus: 'active',
      serviceMode: 'partner_factoring',
      providerId: 'fp-demo-partner',
      primarySpecialistStaffId: 'staff-6',
      createdAt: daysAgo(120),
      updatedAt: daysAgo(5),
    },
    {
      id: 'fprof-g',
      organizationId: 'client-g',
      enrollmentStatus: 'active',
      serviceMode: 'factoring_assistance',
      hasExistingFactor: true,
      existingProviderName: 'Summit Receivables Co.',
      providerId: 'fp-carrier-existing',
      primarySpecialistStaffId: 'staff-6',
      createdAt: daysAgo(180),
      updatedAt: daysAgo(10),
    },
  ];

  const debtors: DebtorAccount[] = [
    {
      id: 'debtor-demo-logistics',
      organizationId: 'client-d',
      brokerContactId: 'broker-demo-logistics',
      legalName: 'Demo Logistics LLC',
      verificationStatus: 'carrier_provided',
      createdAt: daysAgo(40),
    },
    {
      id: 'debtor-example-freight',
      organizationId: 'client-b',
      legalName: 'Example Freight Partners',
      verificationStatus: 'staff_reviewed',
      createdAt: daysAgo(50),
    },
  ];

  const freightInvoices: FreightInvoice[] = [
    {
      id: 'fi-d-complete',
      organizationId: 'client-d',
      loadId: 'load-d-complete',
      invoiceNumber: 'HF-2026-1042',
      debtorName: 'Demo Logistics LLC',
      amountMinor: dollarsToMinor(900),
      currency: 'USD',
      invoiceDate: daysAhead(-5).slice(0, 10),
      status: 'issued',
      rateConfirmationDocumentId: 'vdoc-d-rc',
      bolDocumentId: 'vdoc-d-bol2',
      podDocumentId: 'vdoc-d-pod',
      createdAt: daysAgo(4),
      updatedAt: daysAgo(4),
      version: 1,
    },
    {
      id: 'fi-c-transit',
      organizationId: 'client-c',
      loadId: 'load-c-transit',
      invoiceNumber: 'HF-2026-1088',
      debtorName: 'Example Freight Partners',
      amountMinor: dollarsToMinor(1250),
      currency: 'USD',
      invoiceDate: daysAhead(-1).slice(0, 10),
      status: 'issued',
      createdAt: daysAgo(2),
      updatedAt: daysAgo(2),
      version: 1,
    },
    {
      id: 'fi-e-demo',
      organizationId: 'client-e',
      loadId: 'load-e-complete',
      invoiceNumber: 'HF-2026-1101',
      debtorName: 'Demo Logistics LLC',
      amountMinor: dollarsToMinor(2450),
      currency: 'USD',
      invoiceDate: daysAhead(-3).slice(0, 10),
      status: 'issued',
      createdAt: daysAgo(3),
      updatedAt: daysAgo(3),
      version: 1,
    },
    {
      id: 'fi-f-funded',
      organizationId: 'client-f',
      loadId: 'load-d-complete',
      invoiceNumber: 'HF-2026-0999',
      debtorName: 'Demo Logistics LLC',
      amountMinor: dollarsToMinor(2500),
      currency: 'USD',
      invoiceDate: daysAhead(-14).slice(0, 10),
      status: 'issued',
      createdAt: daysAgo(14),
      updatedAt: daysAgo(14),
      version: 1,
    },
  ];

  const submissions: FactoringSubmission[] = [
    {
      id: 'fs-c-review',
      organizationId: 'client-c',
      loadId: 'load-c-transit',
      freightInvoiceId: 'fi-c-transit',
      providerId: 'fp-demo-partner',
      status: 'provider_review',
      submittedAmountMinor: dollarsToMinor(1250),
      currency: 'USD',
      assignedSpecialistStaffId: 'staff-6',
      packageDocumentIds: [],
      submittedAt: daysAgo(2),
      timeline: [
        { id: 'tl-1', submissionId: 'fs-c-review', label: 'Submitted to provider', status: 'submitted', visibility: 'customer', createdAt: daysAgo(2) },
        { id: 'tl-2', submissionId: 'fs-c-review', label: 'Provider review', status: 'provider_review', visibility: 'customer', createdAt: daysAgo(1) },
      ],
      createdByStaffId: 'staff-6',
      createdAt: daysAgo(3),
      updatedAt: daysAgo(1),
      version: 2,
    },
    {
      id: 'fs-d-action',
      organizationId: 'client-d',
      loadId: 'load-d-complete',
      freightInvoiceId: 'fi-d-complete',
      providerId: 'fp-demo-partner',
      status: 'additional_information_needed',
      submittedAmountMinor: dollarsToMinor(900),
      currency: 'USD',
      assignedSpecialistStaffId: 'staff-6',
      packageDocumentIds: ['vdoc-d-rc', 'vdoc-d-pod'],
      submittedAt: daysAgo(3),
      timeline: [
        { id: 'tl-3', submissionId: 'fs-d-action', label: 'Additional document requested', status: 'additional_information_needed', visibility: 'customer', createdAt: daysAgo(1) },
      ],
      createdByStaffId: 'staff-6',
      createdAt: daysAgo(4),
      updatedAt: daysAgo(1),
      version: 2,
    },
    {
      id: 'fs-e-pending',
      organizationId: 'client-e',
      loadId: 'load-e-complete',
      freightInvoiceId: 'fi-e-demo',
      providerId: 'fp-demo-partner',
      status: 'funding_pending',
      submittedAmountMinor: dollarsToMinor(2450),
      approvedAmountMinor: dollarsToMinor(2450),
      currency: 'USD',
      assignedSpecialistStaffId: 'staff-6',
      packageDocumentIds: [],
      submittedAt: daysAgo(5),
      approvedAt: daysAgo(1),
      timeline: [
        { id: 'tl-4', submissionId: 'fs-e-pending', label: 'Approved by provider', status: 'approved', visibility: 'customer', createdAt: daysAgo(1) },
        { id: 'tl-5', submissionId: 'fs-e-pending', label: 'Funding pending', status: 'funding_pending', visibility: 'customer', createdAt: daysAgo(0) },
      ],
      createdByStaffId: 'staff-6',
      createdAt: daysAgo(6),
      updatedAt: daysAgo(0),
      version: 3,
    },
    {
      id: 'fs-f-funded',
      organizationId: 'client-f',
      loadId: 'load-d-complete',
      freightInvoiceId: 'fi-f-funded',
      providerId: 'fp-demo-partner',
      status: 'funded',
      submittedAmountMinor: dollarsToMinor(2500),
      approvedAmountMinor: dollarsToMinor(2500),
      reportedAdvanceMinor: dollarsToMinor(2375),
      reportedReserveMinor: dollarsToMinor(125),
      currency: 'USD',
      externalReference: 'DEMO-REF-88421',
      assignedSpecialistStaffId: 'staff-6',
      packageDocumentIds: [],
      submittedAt: daysAgo(10),
      approvedAt: daysAgo(8),
      fundedAt: daysAgo(6),
      timeline: [
        { id: 'tl-6', submissionId: 'fs-f-funded', label: 'Provider reported funding', status: 'funded', visibility: 'customer', createdAt: daysAgo(6) },
      ],
      createdByStaffId: 'staff-6',
      createdAt: daysAgo(12),
      updatedAt: daysAgo(6),
      version: 4,
    },
  ];

  const issues: FactoringIssue[] = [
    {
      id: 'fissue-d-1',
      organizationId: 'client-d',
      submissionId: 'fs-d-action',
      loadId: 'load-d-complete',
      type: 'provider_additional_info',
      status: 'waiting_on_carrier',
      summary: 'Provider requested accessorial backup for detention claim',
      customerActionRequired: true,
      createdByStaffId: 'staff-6',
      createdAt: daysAgo(1),
    },
    {
      id: 'fissue-e-mismatch',
      organizationId: 'client-e',
      loadId: 'load-e-complete',
      type: 'invoice_amount_mismatch',
      status: 'under_review',
      summary: 'Freight invoice amount differs from confirmed load gross — review required',
      customerActionRequired: false,
      createdByStaffId: 'staff-6',
      createdAt: daysAgo(2),
    },
  ];

  return {
    providers,
    profiles,
    debtors,
    freightInvoices,
    submissions,
    issues,
    counters: { freightInvoice: 1101, submission: 4 },
  };
}
