import type {
  OfficeApprovalRequest,
  OfficeAssignmentRecord,
  OfficeEscalation,
  OfficeHandoff,
  OfficeTeam,
  OfficeWorkItem,
} from '../office-core/officeWorkTypes';
import type { InternalNote, StaffMember } from './demoTypes';
import type { OfficeStaffRole } from '../office-core/officeWorkTypes';

export const OFFICE_TEAMS: OfficeTeam[] = [
  { id: 'team-permitting', name: 'Permitting & Compliance', division: 'permitting_compliance' },
  { id: 'team-road-ready', name: 'Road Ready', division: 'road_ready' },
  { id: 'team-insurance', name: 'Insurance', division: 'insurance' },
  { id: 'team-dispatch', name: 'Dispatch', division: 'dispatch' },
  { id: 'team-factoring', name: 'Factoring', division: 'factoring' },
  { id: 'team-brokerage', name: 'Brokerage', division: 'brokerage' },
  { id: 'team-billing', name: 'Billing', division: 'billing' },
  { id: 'team-support', name: 'Customer Support', division: 'customer_support' },
  { id: 'team-management', name: 'Management', division: 'management' },
];

export function createOfficeStaffSeed(): StaffMember[] {
  return [
    { id: 'staff-1', name: 'Alex Manager', initials: 'AM', role: 'Manager', officeRole: 'manager', status: 'available', teamIds: ['team-management'] },
    { id: 'staff-2', name: 'Jordan Lee', initials: 'JL', role: 'Permitting Specialist', officeRole: 'permitting_specialist', status: 'available', teamIds: ['team-permitting'] },
    { id: 'staff-3', name: 'Casey Morgan', initials: 'CM', role: 'Road Ready Specialist', officeRole: 'road_ready_specialist', status: 'busy', teamIds: ['team-road-ready', 'team-permitting'] },
    { id: 'staff-4', name: 'Riley Chen', initials: 'RC', role: 'Dispatcher', officeRole: 'dispatcher', status: 'available', teamIds: ['team-dispatch'] },
    { id: 'staff-5', name: 'Sam Patel', initials: 'SP', role: 'Insurance Coordinator', officeRole: 'insurance_coordinator', status: 'available', teamIds: ['team-insurance'] },
    { id: 'staff-6', name: 'Taylor Brooks', initials: 'TB', role: 'Factoring Coordinator', officeRole: 'factoring_coordinator', status: 'busy', teamIds: ['team-factoring'] },
    { id: 'staff-7', name: 'Morgan Hayes', initials: 'MH', role: 'Broker', officeRole: 'broker', status: 'available', teamIds: ['team-brokerage'] },
    { id: 'staff-8', name: 'Jamie Ortiz', initials: 'JO', role: 'Billing Specialist', officeRole: 'billing_specialist', status: 'available', teamIds: ['team-billing'] },
    { id: 'staff-9', name: 'Chris Support', initials: 'CS', role: 'Customer Support', officeRole: 'customer_support', status: 'available', teamIds: ['team-support'] },
  ];
}

export function createOfficeSeedData(now = new Date()) {
  const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000).toISOString();
  const daysAhead = (d: number) => new Date(now.getTime() + d * 86400000).toISOString();
  const today = now.toISOString().slice(0, 10);
  const yesterday = daysAgo(1);

  const workItems: OfficeWorkItem[] = [
    // Demo A — Summit Ridge: permitting, missing doc, assigned permitting
    {
      id: 'owi-a1',
      sourceDomain: 'service_request',
      sourceEntityType: 'service_request',
      sourceEntityId: 'req-1',
      organizationId: 'client-a',
      title: 'Review customer BOC-3 documents',
      description: 'Authority package — one document still missing from customer.',
      workType: 'document_review',
      division: 'permitting_compliance',
      queueId: 'missing_documents',
      priority: 'high',
      status: 'waiting_on_customer',
      statusLabel: 'Waiting on Customer',
      assignedUserId: 'staff-2',
      assignedTeamId: 'team-permitting',
      dueAt: daysAhead(3),
      waitingOn: 'customer',
      createdAt: daysAgo(3),
      updatedAt: daysAgo(1),
      version: 1,
      isDemo: true,
    },
    {
      id: 'owi-a2',
      sourceDomain: 'service_request',
      sourceEntityType: 'service_request',
      sourceEntityId: 'req-1',
      organizationId: 'client-a',
      title: 'Process authority application',
      workType: 'review',
      division: 'permitting_compliance',
      queueId: 'new_service_requests',
      priority: 'normal',
      status: 'in_progress',
      statusLabel: 'In Progress',
      assignedUserId: 'staff-2',
      assignedTeamId: 'team-permitting',
      dueAt: daysAhead(5),
      waitingOn: 'none',
      createdAt: daysAgo(3),
      updatedAt: daysAgo(0),
      version: 1,
      isDemo: true,
    },
    // Demo B — Heartland: insurance expiring, customer waiting on us
    {
      id: 'owi-b1',
      sourceDomain: 'insurance',
      sourceEntityType: 'insurance_request',
      sourceEntityId: 'ir-demo-b',
      organizationId: 'client-b',
      title: 'Review insurance renewal information request',
      description: 'Customer submitted vehicle updates — review needed.',
      workType: 'review',
      division: 'insurance',
      queueId: 'insurance_requests',
      priority: 'urgent',
      status: 'ready_for_review',
      statusLabel: 'Ready for Review',
      assignedUserId: 'staff-5',
      assignedTeamId: 'team-insurance',
      dueAt: today,
      waitingOn: 'all_in_one',
      createdAt: daysAgo(2),
      updatedAt: yesterday,
      version: 1,
      isDemo: true,
    },
    {
      id: 'owi-b2',
      sourceDomain: 'document',
      sourceEntityType: 'document',
      sourceEntityId: 'vdoc-b-upload',
      organizationId: 'client-b',
      title: 'Review uploaded insurance certificate',
      description: 'Document uploaded yesterday — no staff review yet.',
      workType: 'document_review',
      division: 'insurance',
      queueId: 'document_review',
      priority: 'high',
      status: 'assigned',
      statusLabel: 'Assigned',
      assignedUserId: 'staff-5',
      assignedTeamId: 'team-insurance',
      dueAt: yesterday,
      waitingOn: 'all_in_one',
      createdAt: yesterday,
      updatedAt: yesterday,
      version: 1,
      isDemo: true,
    },
    // Demo C — Pioneer Fleet: dispatch POD needed
    {
      id: 'owi-c1',
      sourceDomain: 'dispatch',
      sourceEntityType: 'load',
      sourceEntityId: 'load-delta-active',
      organizationId: 'client-f',
      title: 'Obtain POD for delivered load',
      workType: 'follow_up',
      division: 'dispatch',
      queueId: 'dispatch_actions',
      priority: 'high',
      status: 'waiting_on_customer',
      statusLabel: 'Waiting on Customer',
      assignedUserId: 'staff-4',
      assignedTeamId: 'team-dispatch',
      dueAt: daysAhead(1),
      waitingOn: 'customer',
      createdAt: daysAgo(2),
      updatedAt: daysAgo(1),
      version: 1,
      isDemo: true,
    },
    // Demo D — BlueLine factoring: missing POD
    {
      id: 'owi-d1',
      sourceDomain: 'factoring',
      sourceEntityType: 'factoring_submission',
      sourceEntityId: 'fs-demo-d',
      organizationId: 'client-d',
      title: 'Follow up on missing POD for factoring package',
      workType: 'follow_up',
      division: 'factoring',
      queueId: 'factoring_submissions',
      priority: 'normal',
      status: 'waiting_on_customer',
      statusLabel: 'Waiting on Customer',
      assignedUserId: 'staff-6',
      assignedTeamId: 'team-factoring',
      dueAt: daysAhead(4),
      waitingOn: 'customer',
      createdAt: daysAgo(4),
      updatedAt: daysAgo(2),
      version: 1,
      isDemo: true,
    },
    // Demo E — NorthStar shipper: unassigned quote
    {
      id: 'owi-e1',
      sourceDomain: 'brokerage',
      sourceEntityType: 'shipment_request',
      sourceEntityId: 'sr-demo-e',
      organizationId: 'client-e',
      title: 'Prepare freight quote for new shipment request',
      workType: 'review',
      division: 'brokerage',
      queueId: 'brokerage_coverage',
      priority: 'high',
      status: 'new',
      statusLabel: 'New',
      assignedTeamId: 'team-brokerage',
      dueAt: today,
      waitingOn: 'all_in_one',
      createdAt: daysAgo(1),
      updatedAt: daysAgo(1),
      version: 1,
      isDemo: true,
    },
    // Demo F — brokerage load needs coverage
    {
      id: 'owi-f1',
      sourceDomain: 'brokerage',
      sourceEntityType: 'load',
      sourceEntityId: 'br-load-coverage',
      organizationId: 'client-e',
      title: 'Secure carrier coverage for brokerage load',
      workType: 'assignment',
      division: 'brokerage',
      queueId: 'brokerage_coverage',
      priority: 'urgent',
      status: 'in_progress',
      statusLabel: 'In Progress',
      assignedUserId: 'staff-7',
      assignedTeamId: 'team-brokerage',
      dueAt: today,
      waitingOn: 'carrier',
      createdAt: daysAgo(1),
      updatedAt: daysAgo(0),
      version: 1,
      isDemo: true,
    },
    // Demo G — billing past due
    {
      id: 'owi-g1',
      sourceDomain: 'invoice',
      sourceEntityType: 'invoice',
      sourceEntityId: 'inv-past-due',
      organizationId: 'client-g',
      title: 'Follow up on past due service invoice',
      workType: 'billing',
      division: 'billing',
      queueId: 'billing_issues',
      priority: 'normal',
      status: 'assigned',
      statusLabel: 'Assigned',
      assignedUserId: 'staff-8',
      assignedTeamId: 'team-billing',
      dueAt: daysAhead(2),
      waitingOn: 'customer',
      createdAt: daysAgo(7),
      updatedAt: daysAgo(3),
      version: 1,
      isDemo: true,
    },
    // Waiting externally — government filing
    {
      id: 'owi-ext1',
      sourceDomain: 'renewal',
      sourceEntityType: 'renewal',
      sourceEntityId: 'ren-demo-ext',
      organizationId: 'client-b',
      title: 'Monitor IRP renewal — submitted to state',
      workType: 'follow_up',
      division: 'permitting_compliance',
      queueId: 'renewals',
      priority: 'normal',
      status: 'waiting_externally',
      statusLabel: 'Waiting Externally',
      assignedUserId: 'staff-2',
      assignedTeamId: 'team-permitting',
      dueAt: daysAhead(10),
      waitingOn: 'government',
      createdAt: daysAgo(14),
      updatedAt: daysAgo(5),
      version: 1,
      isDemo: true,
    },
    // Overdue unassigned-style for manager visibility
    {
      id: 'owi-unassigned1',
      sourceDomain: 'service_request',
      sourceEntityType: 'service_request',
      sourceEntityId: 'req-4',
      organizationId: 'client-e',
      title: 'Review new freight quote request',
      workType: 'review',
      division: 'brokerage',
      queueId: 'unassigned',
      priority: 'high',
      status: 'new',
      statusLabel: 'New',
      assignedTeamId: 'team-brokerage',
      dueAt: daysAgo(1),
      waitingOn: 'all_in_one',
      createdAt: daysAgo(2),
      updatedAt: daysAgo(2),
      version: 1,
      isDemo: true,
    },
  ];

  const handoffs: OfficeHandoff[] = [
    {
      id: 'handoff-1',
      fromTeamId: 'team-permitting',
      toTeamId: 'team-insurance',
      organizationId: 'client-a',
      relatedEntityType: 'service_request',
      relatedEntityId: 'req-1',
      reason: 'Authority filing complete — insurance onboarding next',
      summary: 'Summit Ridge completed USDOT and authority steps. Insurance coordinator should initiate coverage review.',
      priority: 'high',
      dueAt: daysAhead(3),
      assignedUserId: 'staff-5',
      status: 'pending',
      createdById: 'staff-2',
      createdAt: daysAgo(1),
      isDemo: true,
    } as OfficeHandoff & { isDemo?: boolean },
  ];

  const approvals: OfficeApprovalRequest[] = [
    {
      id: 'appr-1',
      sourceEntityType: 'invoice',
      sourceEntityId: 'inv-adjust-demo',
      organizationId: 'client-c',
      actionType: 'manual_financial_adjustment',
      title: 'Manual invoice adjustment — $150 credit',
      reason: 'Duplicate filing fee charged in error',
      requestedById: 'staff-8',
      requestedAt: daysAgo(1),
      status: 'pending',
    },
  ];

  const escalations: OfficeEscalation[] = [
    {
      id: 'esc-1',
      sourceDomain: 'insurance',
      sourceEntityType: 'insurance_request',
      sourceEntityId: 'ir-demo-b',
      organizationId: 'client-b',
      reason: 'Customer waiting over 24 hours on renewal review',
      level: 'high',
      ownerId: 'staff-1',
      createdById: 'staff-5',
      createdAt: daysAgo(0),
      workItemId: 'owi-b2',
    },
  ];

  const assignmentHistory: OfficeAssignmentRecord[] = [
    {
      id: 'assign-1',
      workItemId: 'owi-a1',
      assignedUserId: 'staff-2',
      assignedTeamId: 'team-permitting',
      assignedById: 'staff-1',
      assignedAt: daysAgo(3),
    },
    {
      id: 'assign-2',
      workItemId: 'owi-e1',
      assignedTeamId: 'team-brokerage',
      assignedById: 'staff-1',
      assignedAt: daysAgo(1),
      reason: 'Routed to brokerage queue — awaiting specialist assignment',
    },
  ];

  const pinnedNotes: InternalNote[] = [
    {
      id: 'note-pinned-b',
      clientId: 'client-b',
      authorId: 'staff-5',
      authorInitials: 'SP',
      body: 'Customer prefers text before calling for insurance updates.',
      createdAt: daysAgo(30),
      visibility: 'internal',
      noteType: 'customer_preference',
      pinned: true,
    },
  ];

  return {
    officeStaffId: 'staff-2' as const,
    officeStaffRole: 'permitting_specialist' as OfficeStaffRole,
    officeTeams: OFFICE_TEAMS,
    officeWorkItems: workItems,
    officeHandoffs: handoffs,
    officeApprovals: approvals,
    officeEscalations: escalations,
    officeAssignmentHistory: assignmentHistory,
    officeWorkComments: [],
    officeSavedViews: [],
    officeDashboardPreferences: [],
    staff: createOfficeStaffSeed(),
    extraNotes: pinnedNotes,
  };
}
