/**
 * Studio OS Governance — AI Media workspace demo seeds & bootstrap.
 */

import { AI_MEDIA_WORKSPACE_ID } from '../../../studio-os-core/ai-media-network/constants';
import {
  bootstrapGovernanceStore,
  mergeGovernancePatch,
  readGovernanceStore,
  refreshGovernanceDashboard,
} from '../../../studio-os-core/governance/store';
import { computeTrustScore } from '../../../studio-os-core/governance/trustEngine';
import type { GovernanceStore } from '../../../studio-os-core/governance/types';

const WS = AI_MEDIA_WORKSPACE_ID;
const now = '2026-07-04T18:00:00.000Z';

function trustFactors(partial: Partial<ReturnType<typeof baseFactors>>) {
  return { ...baseFactors(), ...partial };
}

function baseFactors() {
  return {
    accountHistory: 85,
    verification: 90,
    projectCompletion: 88,
    ratings: 92,
    customerSatisfaction: 87,
    policyCompliance: 95,
    responseTime: 80,
    paymentHistory: 90,
    disputes: 95,
    quality: 88,
    communityContributions: 75,
  };
}

export function buildGovernanceStorePatch(): Partial<GovernanceStore> {
  const mayaFactors = trustFactors({ communityContributions: 92, ratings: 96 });
  const pulseFactors = trustFactors({ verification: 88, projectCompletion: 94 });
  const cmoFactors = trustFactors({ verification: 100, policyCompliance: 98, quality: 94 });

  const trustScores = [
    {
      id: 'trust-maya-chen',
      workspaceId: WS,
      participantId: 'creator-maya',
      participantName: 'Maya Chen',
      participantType: 'creator' as const,
      score: computeTrustScore(mayaFactors),
      factors: mayaFactors,
      updatedAt: now,
    },
    {
      id: 'trust-pulse-agency',
      workspaceId: WS,
      participantId: 'participant-pulse',
      participantName: 'Pulse Agency',
      participantType: 'agency' as const,
      score: computeTrustScore(pulseFactors),
      factors: pulseFactors,
      updatedAt: now,
    },
    {
      id: 'trust-cmo-exec',
      workspaceId: WS,
      participantId: 'exec-cmo-team',
      participantName: 'CMO Executive AI Team',
      participantType: 'ai-executive' as const,
      score: computeTrustScore(cmoFactors),
      factors: cmoFactors,
      updatedAt: now,
    },
    {
      id: 'trust-media-blueprint',
      workspaceId: WS,
      participantId: 'eco-asset-media-bp',
      participantName: 'Digital Media Network Blueprint',
      participantType: 'ecosystem-asset' as const,
      score: computeTrustScore(trustFactors({ quality: 96, communityContributions: 88 })),
      factors: trustFactors({ quality: 96, communityContributions: 88 }),
      updatedAt: now,
    },
    {
      id: 'trust-ai-media-ws',
      workspaceId: WS,
      participantId: WS,
      participantName: 'AI Media Network',
      participantType: 'workspace' as const,
      score: computeTrustScore(trustFactors({ accountHistory: 92, verification: 94 })),
      factors: trustFactors({ accountHistory: 92, verification: 94 }),
      updatedAt: now,
    },
  ];

  const ecosystemHealth = {
    creatorSuccessPct: 78,
    businessSuccessPct: 72,
    marketplaceLiquidity: 68,
    customerSatisfaction: 4.7,
    retentionPct: 84,
    networkGrowthPct: 22,
    qualityIndex: 86,
    trustIndex: 88,
    collaborationIndex: 81,
    industryDiversity: 74,
    overallHealthScore: 82,
  };

  return {
    trustScores,
    verificationRequests: [
      {
        id: 'ver-maya-creator',
        workspaceId: WS,
        participantId: 'creator-maya',
        participantName: 'Maya Chen',
        type: 'creator',
        status: 'approved',
        submittedAt: '2026-05-01T00:00:00.000Z',
        reviewedAt: '2026-05-03T00:00:00.000Z',
        badgeIssued: true,
      },
      {
        id: 'ver-jordan-dev',
        workspaceId: WS,
        participantId: 'participant-jordan',
        participantName: 'Jordan Reyes',
        type: 'developer',
        status: 'pending',
        submittedAt: '2026-07-02T00:00:00.000Z',
        badgeIssued: false,
      },
      {
        id: 'ver-learnflow-enterprise',
        workspaceId: WS,
        participantId: 'participant-learnflow',
        participantName: 'LearnFlow EdTech',
        type: 'enterprise',
        status: 'pending',
        submittedAt: '2026-07-03T00:00:00.000Z',
        badgeIssued: false,
      },
    ],
    qualityReviews: [
      {
        id: 'qa-media-blueprint',
        workspaceId: WS,
        assetId: 'eco-asset-media-bp',
        assetTitle: 'Digital Media Network Blueprint',
        documentation: 'pass',
        compatibility: 'pass',
        security: 'pass',
        dependencies: 'pass',
        performance: 'pass',
        branding: 'pass',
        userExperience: 'pass',
        reviewerNotes: 'Flagship ecosystem package — complete docs, Studio OS compatible, all dependencies declared.',
        reviewedAt: '2026-06-15T00:00:00.000Z',
      },
      {
        id: 'qa-writing-bible',
        workspaceId: WS,
        assetId: 'eco-asset-writing',
        assetTitle: 'Finance Myth-Busting Writing Bible',
        documentation: 'pass',
        compatibility: 'pass',
        security: 'pass',
        dependencies: 'pending',
        performance: 'pass',
        branding: 'pass',
        userExperience: 'pass',
        reviewerNotes: 'Pending dependency audit — requires Memory Bible module confirmation.',
        reviewedAt: '2026-07-01T00:00:00.000Z',
      },
    ],
    certifications: [
      {
        id: 'cert-maya-consultant',
        workspaceId: WS,
        holderId: 'creator-maya',
        holderName: 'Maya Chen',
        type: 'studio-os-consultant',
        status: 'active',
        issuedAt: '2026-04-01T00:00:00.000Z',
        expiresAt: '2027-04-01T00:00:00.000Z',
        renewalDueAt: '2027-01-01T00:00:00.000Z',
        examHistory: ['Foundation Exam 94%', 'Implementation Lab Pass'],
        continuingEducationHours: 24,
        badgeId: 'badge-certified-consultant',
      },
      {
        id: 'cert-studio-os-blueprint',
        workspaceId: WS,
        holderId: 'creator-studio-os',
        holderName: 'Studio OS Labs',
        type: 'blueprint-architect',
        status: 'active',
        issuedAt: '2026-03-01T00:00:00.000Z',
        expiresAt: '2027-03-01T00:00:00.000Z',
        renewalDueAt: '2026-12-01T00:00:00.000Z',
        examHistory: ['Blueprint Architecture Mastery 98%'],
        continuingEducationHours: 40,
        badgeId: 'badge-blueprint-architect',
      },
      {
        id: 'cert-pulse-partner',
        workspaceId: WS,
        holderId: 'participant-pulse',
        holderName: 'Pulse Agency',
        type: 'implementation-partner',
        status: 'pending-renewal',
        issuedAt: '2025-06-01T00:00:00.000Z',
        expiresAt: '2026-06-01T00:00:00.000Z',
        renewalDueAt: '2026-05-01T00:00:00.000Z',
        examHistory: ['Implementation Partner 2025'],
        continuingEducationHours: 12,
        badgeId: 'badge-implementation-partner',
      },
    ],
    moderationCases: [
      {
        id: 'mod-fake-reviews',
        workspaceId: WS,
        category: 'fraud',
        subjectId: 'listing-unknown-42',
        subjectName: 'Suspicious Marketplace Listing',
        reporterId: 'system-fraud-detection',
        status: 'open',
        policyRef: 'policy-marketplace-rules-v2',
        actionLog: ['Auto-flagged by fraud detection — review velocity anomaly (fake reviews suspected)'],
        createdAt: '2026-07-03T12:00:00.000Z',
      },
      {
        id: 'mod-copyright',
        workspaceId: WS,
        category: 'copyright',
        subjectId: 'eco-asset-disputed',
        subjectName: 'Disputed Asset Pack',
        reporterId: 'creator-external',
        status: 'escalated',
        policyRef: 'policy-licensing-v1',
        actionLog: ['Report received', 'Initial review', 'Escalated to legal review'],
        createdAt: '2026-06-28T00:00:00.000Z',
      },
    ],
    policies: [
      { id: 'policy-terms-v3', category: 'terms', title: 'Studio OS Terms of Service', version: '3.0', effectiveAt: '2026-01-01', summary: 'Platform usage, account responsibilities, and service boundaries.' },
      { id: 'policy-community-v2', category: 'community-guidelines', title: 'Community Guidelines', version: '2.1', effectiveAt: '2026-03-01', summary: 'Respectful collaboration, no harassment, authentic engagement.' },
      { id: 'policy-marketplace-rules-v2', category: 'marketplace-rules', title: 'Marketplace Rules', version: '2.0', effectiveAt: '2026-06-01', summary: 'Deal integrity, accurate listings, dispute resolution, renewal expectations.' },
      { id: 'policy-ai-v1', category: 'ai-policies', title: 'AI Governance Policies', version: '1.0', effectiveAt: '2026-05-01', summary: 'Executive AI transparency, human approval, restricted actions, audit requirements.' },
      { id: 'policy-privacy-v2', category: 'privacy', title: 'Privacy Policy', version: '2.0', effectiveAt: '2026-01-01', summary: 'Data handling, workspace isolation, enterprise compliance.' },
      { id: 'policy-licensing-v1', category: 'licensing', title: 'Ecosystem Licensing', version: '1.0', effectiveAt: '2026-07-01', summary: 'Asset licensing models, royalties, enterprise terms.' },
      { id: 'policy-developer-v1', category: 'developer', title: 'Developer Policies', version: '1.0', effectiveAt: '2026-07-01', summary: 'SDK usage, API keys, publishing standards, security requirements.' },
      { id: 'policy-partner-v1', category: 'partner', title: 'Partner Policies', version: '1.0', effectiveAt: '2026-04-01', summary: 'Implementation partners, certification requirements, co-marketing.' },
    ],
    appeals: [
      {
        id: 'appeal-trust-jordan',
        workspaceId: WS,
        participantId: 'participant-jordan',
        participantName: 'Jordan Reyes',
        type: 'trust-score',
        reason: 'Trust score dropped after disputed project — requesting manual review of completion evidence.',
        status: 'under-review',
        submittedAt: '2026-07-02T00:00:00.000Z',
      },
      {
        id: 'appeal-mod-copyright',
        workspaceId: WS,
        participantId: 'creator-disputed',
        participantName: 'Asset Pack Creator',
        type: 'moderation',
        reason: 'Copyright claim disputed — original work with license documentation attached.',
        status: 'submitted',
        submittedAt: '2026-07-04T00:00:00.000Z',
      },
    ],
    fraudAlerts: [
      {
        id: 'fraud-fake-reviews',
        workspaceId: WS,
        alertType: 'fake-reviews',
        subjectId: 'listing-unknown-42',
        subjectName: 'Suspicious Marketplace Listing',
        severity: 'high',
        status: 'investigating',
        flaggedAt: '2026-07-03T12:00:00.000Z',
      },
      {
        id: 'fraud-bot-engagement',
        workspaceId: WS,
        alertType: 'bot-activity',
        subjectId: 'account-suspicious-17',
        subjectName: 'New Creator Account',
        severity: 'medium',
        status: 'flagged',
        flaggedAt: '2026-07-04T08:00:00.000Z',
      },
    ],
    reputations: [
      {
        id: 'rep-maya',
        workspaceId: WS,
        participantId: 'creator-maya',
        participantName: 'Maya Chen',
        overall: 94,
        professionalism: 96,
        communication: 92,
        quality: 98,
        reliability: 93,
        repeatBusiness: 88,
        platformContributions: 90,
        industryReputation: 91,
        workspaceReputation: 95,
        updatedAt: now,
      },
      {
        id: 'rep-pulse',
        workspaceId: WS,
        participantId: 'participant-pulse',
        participantName: 'Pulse Agency',
        overall: 87,
        professionalism: 90,
        communication: 85,
        quality: 88,
        reliability: 86,
        repeatBusiness: 82,
        platformContributions: 78,
        industryReputation: 84,
        workspaceReputation: 89,
        updatedAt: now,
      },
    ],
    ecosystemHealth,
    aiGovernance: [
      {
        id: 'ai-gov-cmo',
        workspaceId: WS,
        executiveId: 'exec-cmo-team',
        executiveName: 'CMO · Growth Strategist Team',
        version: '1.3.0',
        decisionLogCount: 1247,
        promptHistoryCount: 89,
        knowledgeSources: ['Memory Bible', 'Company DNA', 'Growth Network', 'Marketplace Deals'],
        capabilityScope: ['Campaign strategy', 'Partnership recommendations', 'Content calendar'],
        allowedActions: ['Recommend', 'Draft proposals', 'Analyze performance'],
        restrictedActions: ['Execute payments', 'Publish without approval', 'Modify billing'],
        humanApprovalRequired: true,
        confidenceLevel: 'high',
        lastAuditAt: '2026-07-01T00:00:00.000Z',
      },
      {
        id: 'ai-gov-cco',
        workspaceId: WS,
        executiveId: 'exec-cco',
        executiveName: 'Chief Creative Officer',
        version: '2.0.1',
        decisionLogCount: 892,
        promptHistoryCount: 64,
        knowledgeSources: ['Creative DNA', 'Writing Bible', 'Show Bible', 'Asset Director'],
        capabilityScope: ['Creative direction', 'Brand consistency', 'Production standards'],
        allowedActions: ['Review assets', 'Approve creative', 'Flag deviations'],
        restrictedActions: ['Override locked DNA', 'Publish unapproved assets'],
        humanApprovalRequired: true,
        confidenceLevel: 'high',
        lastAuditAt: '2026-06-28T00:00:00.000Z',
      },
    ],
    auditEvents: [
      {
        id: 'audit-ver-maya',
        workspaceId: WS,
        type: 'verification',
        actorId: 'gov-admin',
        actorName: 'Governance Admin',
        subjectId: 'creator-maya',
        subjectName: 'Maya Chen',
        policyRef: 'policy-community-v2',
        summary: 'Creator verification approved — badge issued',
        timestamp: '2026-05-03T00:00:00.000Z',
        knowledgeGraphNodeId: 'node-governance-verification',
      },
      {
        id: 'audit-cert-studio-os',
        workspaceId: WS,
        type: 'certification',
        actorId: 'gov-admin',
        actorName: 'Certification Board',
        subjectId: 'creator-studio-os',
        subjectName: 'Studio OS Labs',
        policyRef: 'policy-partner-v1',
        summary: 'Blueprint Architect certification issued',
        timestamp: '2026-03-01T00:00:00.000Z',
        knowledgeGraphNodeId: 'node-governance-certification',
      },
      {
        id: 'audit-ws-created',
        workspaceId: WS,
        type: 'workspace-creation',
        actorId: 'wce-engine',
        actorName: 'Workspace Creation Engine',
        subjectId: WS,
        subjectName: 'AI Media Network',
        summary: 'Workspace provisioned from Digital Media blueprint',
        timestamp: '2026-02-01T00:00:00.000Z',
        knowledgeGraphNodeId: 'node-governance-audit',
      },
      {
        id: 'audit-ai-update',
        workspaceId: WS,
        type: 'executive-ai-update',
        actorId: 'exec-cmo-team',
        actorName: 'CMO Executive AI Team',
        subjectId: 'exec-cmo-team',
        subjectName: 'CMO Team v1.3.0',
        policyRef: 'policy-ai-v1',
        summary: 'Executive AI version 1.3.0 deployed — decision log archived',
        timestamp: '2026-07-01T00:00:00.000Z',
        knowledgeGraphNodeId: 'node-governance-ai',
      },
    ],
    enterpriseRules: [
      {
        id: 'ent-vxd-governance',
        workspaceId: WS,
        orgName: 'VXD Inc. · Enterprise',
        departmentPolicies: ['Marketing — CMO approval required', 'Finance — dual sign-off', 'Legal — contract review'],
        approvalChains: ['Creator → CCO → CMO → Publish', 'Deal > $10K → Legal + Finance'],
        workspacePermissions: ['Role-based module access', 'Executive AI restricted actions', 'Audit export enabled'],
        complianceReports: ['Q2 2026 Trust Report', 'AI Governance Audit', 'Marketplace Compliance'],
        auditExportEnabled: true,
        privateRules: ['Internal blueprint library', 'Private executive AI configs', 'Enterprise-only certifications'],
      },
    ],
  };
}

export function bootstrapAiMediaGovernance(): void {
  bootstrapGovernanceStore();
  const store = readGovernanceStore();
  if (store.trustScores.length > 0) return;
  mergeGovernancePatch(buildGovernanceStorePatch());
  refreshGovernanceDashboard(WS);
}
