import type { CurriculumBibleEntry } from '../../types';

/** Approved LACE Curriculum Bible — editorial registry only. */
export const LACE_CURRICULUM_ENTRIES: CurriculumBibleEntry[] = [
  {
    id: 'lace-01-know-your-lace',
    curriculumCode: 'LACE-01',
    pillar: 'lace',
    contentType: 'psa-today',
    title: 'KNOW YOUR LACE',
    role: 'foundation',
    lifecyclePhase: 'foundation',
    primaryLearningObjective:
      'Understand lace anatomy and distinguish lace, knots, hairline density, lace edge, and installed finish as separate variables.',
    ownsConcepts: [
      'basic lace anatomy',
      'HD / ultra-thin lace fundamentals',
      'lace vs knots',
      'lace vs hairline',
      'knot visibility concept',
      'lace tone concept',
      'density concept',
      'lace-edge concept',
      'lace delicacy',
      'variables affecting lace realism',
    ],
    referencesConcepts: [
      'plucking',
      'knot bleaching',
      'tinting',
      'cutting',
      'installation',
      'melting',
    ],
    excludesConcepts: [
      'complete plucking procedure',
      'complete knot bleaching procedure',
      'complete tinting procedure',
      'complete cutting procedure',
      'installation procedure',
      'melting procedure',
    ],
    cameraBVisualRequirements: ['Macro educational anatomy / visual inspection'],
    antiOverlapNotes: [
      'Plucking changes density. Bleaching changes knot visibility. Tinting changes lace color. Cutting changes the lace edge. Installation secures the lace. Melting refines the installed finish.',
    ],
    recommendedNextIds: ['lace-02-how-to-pluck-your-frontal', 'lace-05-what-does-your-lace-need'],
    status: 'planned',
    editorialNotes: ['Camera B type: macro educational anatomy / visual inspection.'],
  },
  {
    id: 'lace-02-how-to-pluck-your-frontal',
    curriculumCode: 'LACE-02',
    pillar: 'lace',
    contentType: 'psa-today',
    title: 'HOW TO PLUCK YOUR FRONTAL',
    role: 'customization',
    lifecyclePhase: 'customization',
    primaryLearningObjective:
      'Refine a pre-plucked frontal into a softer believable hairline without unnecessarily removing density or creating bald spots.',
    linkedContentId: 'psa-today-ep-01-how-to-pluck-your-frontal',
    prerequisiteContentIds: ['lace-01-know-your-lace'],
    recommendedNextIds: ['lace-05-what-does-your-lace-need', 'lace-03-how-to-bleach-your-knots'],
    ownsConcepts: [
      'assessing existing density',
      'identifying areas requiring softness',
      'sectioning for plucking',
      'working behind first row',
      'tweezer placement',
      'controlled removal',
      'movement across hairline',
      'density variation',
      'temple-area judgment',
      'checking progress',
      'over-plucking prevention',
      'knowing when to stop',
    ],
    referencesConcepts: ['knots', 'lace color', 'pre-plucked construction'],
    excludesConcepts: [
      'knot bleaching',
      'lace tinting',
      'lace cutting',
      'adhesive',
      'melting',
      'baby hair styling',
    ],
    classKitRequirements: [
      { id: 'frontal-unit', name: 'frontal/unit', required: true },
      { id: 'mannequin-head', name: 'mannequin head', required: true },
      { id: 'mannequin-stand', name: 'secure mannequin stand', required: true },
      { id: 't-pins', name: 'T-pins where appropriate', required: false },
      { id: 'tweezers', name: 'tweezers', required: true },
      { id: 'rat-tail-comb', name: 'rat-tail comb', required: true },
      { id: 'sectioning-clips', name: 'sectioning clips', required: true },
      { id: 'water-mist', name: 'water/mist if used in final approved technique', required: false },
    ],
    cameraAResponsibility: [
      'Explain conceptually that plucking is about creating believable hairline density, not simply making the frontal thinner.',
      'Camera A ends with PSA: seated → gradually standing → turning → walking toward CLASS KIT station — NOT demonstration station.',
    ],
    cameraBDemonstration: [
      'Hands + mannequin + hairline.',
      'Macro instructional demonstration.',
      'PSA herself only visible if technically necessary.',
    ],
    companionSlayTipIds: ['slay-tip-dev-wet-hairline-plucking'],
    companionSlayTipConceptSlots: [
      { id: 'slay-tip-concept-damp-plucking', title: 'Why Damp Hair Can Make Plucking Easier', status: 'planned' },
      { id: 'slay-tip-concept-stop-one-spot', title: 'Stop Plucking in One Spot', status: 'planned' },
      {
        id: 'slay-tip-concept-install-distance-check',
        title: 'Check Your Hairline From Installation Distance',
        status: 'planned',
      },
      { id: 'slay-tip-concept-tweezer-signals', title: 'What Your Tweezers Are Telling You', status: 'planned' },
      { id: 'slay-tip-concept-put-tweezers-down', title: 'The "Put the Tweezers Down" Test', status: 'planned' },
    ],
    status: 'in-development',
    editorialNotes: [
      'Runtime PSA Today Episode 01 exists (structural placeholder — Camera B media pending).',
    ],
  },
  {
    id: 'lace-03-how-to-bleach-your-knots',
    curriculumCode: 'LACE-03',
    pillar: 'lace',
    contentType: 'psa-today',
    title: 'HOW TO BLEACH YOUR KNOTS',
    role: 'customization',
    lifecyclePhase: 'customization',
    primaryLearningObjective: 'Reduce visible dark knots while preserving hair/lace integrity.',
    prerequisiteContentIds: ['lace-01-know-your-lace'],
    recommendedNextIds: ['lace-04-how-to-tint-your-lace', 'lace-05-what-does-your-lace-need'],
    ownsConcepts: [
      'diagnosing visible knots',
      'bleach/developer preparation',
      'consistency',
      'protecting hair',
      'controlled application',
      'processing',
      'checking',
      'rinsing',
      'neutralization related to knot bleaching',
      'under-processing',
      'over-processing',
    ],
    excludesConcepts: ['general hair lightening', 'lace tinting', 'plucking'],
    antiOverlapNotes: ['BLEACHING KNOTS != LIGHTENING HAIR. COLOR owns hair-lightening education.'],
    status: 'planned',
  },
  {
    id: 'lace-04-how-to-tint-your-lace',
    curriculumCode: 'LACE-04',
    pillar: 'lace',
    contentType: 'psa-today',
    title: 'HOW TO TINT YOUR LACE',
    role: 'customization',
    lifecyclePhase: 'customization',
    primaryLearningObjective: "Adjust lace tone to better complement the wearer's complexion.",
    prerequisiteContentIds: ['lace-01-know-your-lace'],
    recommendedNextIds: ['lace-05-what-does-your-lace-need', 'lace-07-prep-skin-lace-install'],
    ownsConcepts: [
      'diagnosing lace-tone mismatch',
      'depth',
      'undertone',
      'tint selection',
      'application',
      'gradual building',
      'dry-state evaluation',
      'skin comparison',
      'excessive-tint correction where appropriate',
    ],
    excludesConcepts: ['knot bleaching', 'plucking', 'installation'],
    antiOverlapNotes: [
      'Tint changes lace material appearance. Bleach changes knot visibility.',
    ],
    status: 'planned',
  },
  {
    id: 'lace-05-what-does-your-lace-need',
    curriculumCode: 'LACE-05',
    pillar: 'lace',
    contentType: 'psa-today',
    title: 'WHAT DOES YOUR LACE ACTUALLY NEED?',
    role: 'diagnostic',
    lifecyclePhase: 'customization',
    primaryLearningObjective: 'Diagnose the problem before choosing a customization technique.',
    prerequisiteContentIds: ['lace-01-know-your-lace'],
    ownsConcepts: [
      'diagnostic routing: heavy/artificial hairline → density → plucking',
      'diagnostic routing: dark dots → knots → knot bleaching',
      'diagnostic routing: ashy/wrong mesh tone → lace color → tinting',
      'diagnostic routing: visible excess edge → cutting',
      'diagnostic routing: poor bond/lifting → installation',
      'diagnostic routing: secured but visible finish → melting / troubleshooting',
    ],
    referencesConcepts: [
      'plucking',
      'knot bleaching',
      'tinting',
      'cutting',
      'installation',
      'melting',
      'troubleshooting',
    ],
    excludesConcepts: [
      'complete plucking procedure',
      'complete knot bleaching procedure',
      'complete tinting procedure',
      'complete cutting procedure',
      'complete installation procedure',
      'complete melting procedure',
    ],
    diagnosticRouteIds: [
      'lace-02-how-to-pluck-your-frontal',
      'lace-03-how-to-bleach-your-knots',
      'lace-04-how-to-tint-your-lace',
      'lace-06-how-to-cut-your-lace',
      'lace-08-glueless-installation',
      'lace-09-adhesive-installation',
      'lace-10-how-to-melt-your-lace',
      'lace-12-why-your-lace-isnt-melting',
    ],
    antiOverlapNotes: ['DO NOT reteach full procedures — route to primary owner lessons.'],
    status: 'planned',
  },
  {
    id: 'lace-06-how-to-cut-your-lace',
    curriculumCode: 'LACE-06',
    pillar: 'lace',
    contentType: 'psa-today',
    title: 'HOW TO CUT YOUR LACE',
    role: 'preparation',
    lifecyclePhase: 'preparation',
    primaryLearningObjective:
      'Remove excess lace while preserving an organic believable edge and protecting the hairline.',
    prerequisiteContentIds: ['lace-01-know-your-lace'],
    recommendedNextIds: ['lace-07-prep-skin-lace-install'],
    ownsConcepts: [
      'timing',
      'positioning',
      'sectioning',
      'cutting control',
      'organic edge',
      'avoiding ruler-straight cutting',
      'hairline protection',
      'ear-area considerations',
      'determining how much lace to leave',
    ],
    excludesConcepts: ['adhesive', 'melt', 'full installation'],
    status: 'planned',
  },
  {
    id: 'lace-07-prep-skin-lace-install',
    curriculumCode: 'LACE-07',
    pillar: 'lace',
    contentType: 'psa-today',
    title: 'PREP YOUR SKIN + LACE FOR INSTALLATION',
    role: 'preparation',
    lifecyclePhase: 'preparation',
    primaryLearningObjective: 'Create a clean, properly positioned foundation for installation.',
    recommendedNextIds: ['lace-08-glueless-installation', 'lace-09-adhesive-installation'],
    ownsConcepts: [
      'skin prep',
      'oil/residue removal',
      'lace prep',
      'positioning',
      'hairline alignment',
      'natural-hair/edge protection',
      'recognizing poor prep',
    ],
    excludesConcepts: ['complete adhesive application', 'glueless securing', 'final melt'],
    status: 'planned',
  },
  {
    id: 'lace-08-glueless-installation',
    curriculumCode: 'LACE-08',
    pillar: 'lace',
    contentType: 'psa-today',
    title: 'GLUELESS INSTALLATION',
    role: 'installation',
    lifecyclePhase: 'installation-finish',
    primaryLearningObjective:
      'Secure and position a unit without adhesive while maintaining a natural lace presentation.',
    prerequisiteContentIds: ['lace-07-prep-skin-lace-install'],
    recommendedNextIds: ['lace-10-how-to-melt-your-lace', 'lace-11-baby-hairs-judgment'],
    ownsConcepts: [
      'fit',
      'cap adjustment',
      'built-in securing components where applicable',
      'positioning',
      'hairline placement',
      'ear-area fit',
      'glueless security',
      'final fit assessment',
    ],
    excludesConcepts: ['adhesive installation'],
    status: 'planned',
  },
  {
    id: 'lace-09-adhesive-installation',
    curriculumCode: 'LACE-09',
    pillar: 'lace',
    contentType: 'psa-today',
    title: 'ADHESIVE INSTALLATION',
    role: 'installation',
    lifecyclePhase: 'installation-finish',
    primaryLearningObjective:
      'Create a clean secure adhesive bond while protecting lace/hairline.',
    prerequisiteContentIds: ['lace-07-prep-skin-lace-install'],
    recommendedNextIds: ['lace-10-how-to-melt-your-lace', 'lace-12-why-your-lace-isnt-melting'],
    ownsConcepts: [
      'adhesive amount',
      'thin layers',
      'layer readiness',
      'tack',
      'placement',
      'controlled lace contact',
      'bonding',
      'avoiding adhesive contamination',
    ],
    referencesConcepts: ['skin prep'],
    excludesConcepts: ['full skin prep re-teach', 'final melting process'],
    antiOverlapNotes: ['LACE 07 strongly recommended prerequisite — do not reteach full skin prep.'],
    status: 'planned',
  },
  {
    id: 'lace-10-how-to-melt-your-lace',
    curriculumCode: 'LACE-10',
    pillar: 'lace',
    contentType: 'psa-today',
    title: 'HOW TO MELT YOUR LACE',
    role: 'finishing',
    lifecyclePhase: 'installation-finish',
    primaryLearningObjective: 'Refine the appearance of an already-secured lace edge.',
    ownsConcepts: [
      'meaning of melt',
      'finishing product where applicable',
      'melt-band placement',
      'pressure',
      'timing',
      'band removal',
      'edge evaluation',
      'residue prevention',
      'final refinement',
    ],
    antiOverlapNotes: ['INSTALLATION = SECURE. MELTING = REFINE THE FINISH.'],
    status: 'planned',
  },
  {
    id: 'lace-11-baby-hairs-judgment',
    curriculumCode: 'LACE-11',
    pillar: 'lace',
    contentType: 'psa-today',
    title: 'BABY HAIRS: DO YOU ACTUALLY NEED THEM?',
    role: 'finishing',
    lifecyclePhase: 'installation-finish',
    primaryLearningObjective:
      'Teach intentional baby-hair creation while establishing that baby hairs are optional.',
    ownsConcepts: [
      'determining whether baby hairs benefit the install',
      'selecting hair',
      'density',
      'sectioning',
      'length',
      'shaping',
      'product restraint',
      'no-baby-hair alternative',
    ],
    antiOverlapNotes: [
      'Baby hairs must NOT be positioned as mandatory camouflage for poorly customized lace.',
    ],
    status: 'planned',
  },
  {
    id: 'lace-12-why-your-lace-isnt-melting',
    curriculumCode: 'LACE-12',
    pillar: 'lace',
    contentType: 'psa-today',
    title: "WHY YOUR LACE ISN'T MELTING",
    role: 'troubleshooting',
    lifecyclePhase: 'troubleshooting',
    primaryLearningObjective: 'Diagnose why installed lace remains visible or performs poorly.',
    ownsConcepts: [
      'diagnosis: white/ashy cast',
      'diagnosis: lifting',
      'diagnosis: residue',
      'diagnosis: wrinkles',
      'diagnosis: poor placement',
      'diagnosis: excessive adhesive',
      'diagnosis: incorrect tint',
      'diagnosis: contamination',
      'diagnosis: poor prep',
      'diagnosis: inappropriate finishing',
    ],
    referencesConcepts: ['tinting', 'installation', 'melting', 'prep'],
    excludesConcepts: [
      'complete tint procedure',
      'complete install procedure',
      'complete melt procedure',
    ],
    diagnosticRouteIds: [
      'lace-04-how-to-tint-your-lace',
      'lace-07-prep-skin-lace-install',
      'lace-09-adhesive-installation',
      'lace-10-how-to-melt-your-lace',
    ],
    antiOverlapNotes: ['Route to primary owner lessons — do not reteach complete procedures.'],
    status: 'planned',
  },
  {
    id: 'lace-13-remove-unit-safely',
    curriculumCode: 'LACE-13',
    pillar: 'lace',
    contentType: 'psa-today',
    title: 'REMOVE YOUR UNIT WITHOUT DAMAGING YOUR LACE',
    role: 'removal',
    lifecyclePhase: 'removal-restoration',
    primaryLearningObjective:
      'Release an installed unit while protecting lace, natural hair and edges.',
    ownsConcepts: [
      'release process',
      'remover dwell time where applicable',
      'gentle separation',
      'direction/control',
      'recognizing resistance',
      'natural edge protection',
      'knowing when to stop pulling',
    ],
    criticalSuccessInformation: [
      'Damage-prevention information cannot be withheld for Slay Tips.',
    ],
    recommendedNextIds: ['lace-14-clean-adhesive-from-lace'],
    status: 'planned',
  },
  {
    id: 'lace-14-clean-adhesive-from-lace',
    curriculumCode: 'LACE-14',
    pillar: 'lace',
    contentType: 'psa-today',
    title: 'CLEAN ADHESIVE FROM YOUR LACE',
    role: 'restoration',
    lifecyclePhase: 'removal-restoration',
    primaryLearningObjective:
      'Remove adhesive/product residue from lace without unnecessarily damaging mesh/hairline.',
    prerequisiteContentIds: ['lace-13-remove-unit-safely'],
    ownsConcepts: [
      'post-removal inspection',
      'cleanup sequence',
      'residue softening',
      'gentle removal',
      'lace-focused cleaning',
      'recognizing when more treatment/time is needed',
      'avoiding scraping/pulling',
    ],
    excludesConcepts: ['full-unit routine washing'],
    antiOverlapNotes: ['CARE owns routine hair washing.'],
    relatedCareIds: ['care-lace-between-wears'],
    status: 'planned',
  },
  {
    id: 'lace-15-preserve-lace-care-route',
    curriculumCode: 'LACE-15',
    pillar: 'lace',
    contentType: 'care-route',
    title: 'PROTECT + PRESERVE YOUR LACE (CARE ROUTE)',
    role: 'maintenance',
    lifecyclePhase: 'preservation',
    primaryLearningObjective:
      'Route routine lace preservation between wears to purchase-included CARE — not a paid PSA Today duplicate.',
    ownsConcepts: ['cross-pillar care routing for lace preservation'],
    relatedCareIds: ['care-lace-between-wears'],
    referencesConcepts: ['lace preservation between wears', 'routine ownership maintenance'],
    excludesConcepts: ['paid PSA Today preservation lesson', 'advanced customization'],
    antiOverlapNotes: [
      'DO NOT create paid PSA Today: "Protect + Preserve Your Lace".',
      'Primary owner: CARE — LACE CARE BETWEEN WEARS.',
    ],
    status: 'planned',
    editorialNotes: ['Cross-pillar route only — no PSA Today episode for LACE-15.'],
  },
];

export const LACE_CURRICULUM_LIFECYCLE = {
  foundation: ['LACE-01'],
  customization: ['LACE-02', 'LACE-03', 'LACE-04', 'LACE-05'],
  preparation: ['LACE-06', 'LACE-07'],
  'installation-finish': ['LACE-08', 'LACE-09', 'LACE-10', 'LACE-11'],
  troubleshooting: ['LACE-12'],
  'removal-restoration': ['LACE-13', 'LACE-14'],
  preservation: ['LACE-15'],
} as const;
