import type { EmailTemplateDefinition, EmailTemplateType } from './types.js';

const ORDER_ROWS = [
  { label: 'Order Number', valueKey: 'orderNumber', fallback: '—' },
] as const;

const TRACKING_ROWS = [
  { label: 'Order Number', valueKey: 'orderNumber', fallback: '—' },
  { label: 'Tracking Number', valueKey: 'trackingNumber', fallback: '—' },
] as const;

const POINTS_ROWS = [
  { label: 'Points Earned', valueKey: 'pointsAmount', fallback: '0' },
  { label: 'Your Balance', valueKey: 'balance', fallback: '0' },
] as const;

const AFFILIATE_SUBMIT_ROWS = [
  { label: 'Submitted On', valueKey: 'submissionDate', fallback: '—' },
  { label: 'Content Type', valueKey: 'contentType', fallback: '—' },
  { label: 'Platform', valueKey: 'platformName', fallback: '—' },
] as const;

export const EMAIL_TEMPLATE_REGISTRY: Record<EmailTemplateType, EmailTemplateDefinition> = {
  welcome: {
    defaultSubject: 'Welcome to the Slay Society',
    scriptAccent: 'Welcome to',
    headline: 'The Slay Society',
    bodyParagraphs: [
      'Hi {{customerName}}, you\'re in. It\'s time to get rewarded.',
      'You\'ve officially joined a world of luxury without limits.',
    ],
    heroIcon: 'welcome',
    showMemberPerks: true,
    defaultCtaLabel: 'START EARNING',
    defaultCtaPath: '/account/rewards',
    preheader: 'Your luxury rewards journey starts now.',
  },
  newsletter: {
    defaultSubject: 'The Latest from Frontal Slayer',
    scriptAccent: 'The Latest',
    headline: 'The Slay List',
    bodyParagraphs: [''],
    heroIcon: 'fs',
    defaultCtaLabel: 'READ THE LATEST',
    defaultCtaPath: '/home/shop',
    preheader: 'Exclusive updates from Frontal Slayer.',
  },
  email_verification: {
    defaultSubject: 'Verify Your Email',
    scriptAccent: 'Almost There!',
    headline: 'Verify Your Email',
    bodyParagraphs: [
      'Hi {{customerName}}, confirm your email to unlock your account and member perks.',
    ],
    heroIcon: 'envelope',
    defaultCtaLabel: 'VERIFY EMAIL',
    defaultCtaPath: '/sign-in',
    preheader: 'One tap to confirm your Frontal Slayer account.',
  },
  email_confirmed: {
    defaultSubject: 'Email Confirmed',
    scriptAccent: "You're In!",
    headline: 'Email Confirmed',
    bodyParagraphs: ['Your email is verified. Welcome to luxury without limits.'],
    heroIcon: 'check',
    defaultCtaLabel: 'SHOP NOW',
    defaultCtaPath: '/home/shop',
  },
  password_reset: {
    defaultSubject: 'Reset Your Password',
    scriptAccent: 'Reset Your',
    headline: 'Password',
    bodyParagraphs: [
      'Hi {{customerName}}, we received a request to reset your password.',
      'If you did not request this, you can safely ignore this email.',
    ],
    heroIcon: 'lock',
    defaultCtaLabel: 'RESET PASSWORD',
    defaultCtaPath: '/sign-in',
    preheader: 'Secure your Frontal Slayer account.',
  },
  password_reset_success: {
    defaultSubject: 'Password Reset Successful',
    scriptAccent: "You're All Set!",
    headline: 'Password Reset Successful',
    bodyParagraphs: ['Your password has been updated. You can sign in with your new credentials.'],
    heroIcon: 'check',
    defaultCtaLabel: 'LOGIN NOW',
    defaultCtaPath: '/sign-in',
  },
  password_changed: {
    defaultSubject: 'Your Password Was Changed',
    scriptAccent: 'Security Update',
    headline: 'Password Changed',
    bodyParagraphs: [
      'Hi {{customerName}}, your account password was recently updated.',
      'If this was not you, secure your account immediately.',
    ],
    heroIcon: 'lock',
    defaultCtaLabel: 'SECURE MY ACCOUNT',
    defaultCtaPath: '/account/settings',
  },
  order_received: {
    defaultSubject: 'We Received Your Order',
    scriptAccent: "We've Received",
    headline: 'Your Order',
    bodyParagraphs: ['Thank you — we have received your order and will begin processing shortly.'],
    heroIcon: 'bag',
    dataRows: [...ORDER_ROWS],
    defaultCtaLabel: 'VIEW ORDER DETAILS',
    defaultCtaPath: '/account/orders',
  },
  order_confirmed: {
    defaultSubject: 'Order Confirmed',
    scriptAccent: 'Thank You!',
    headline: 'Order Confirmed',
    bodyParagraphs: [
      'Hi {{customerName}}, your luxury order is confirmed.',
      'Our team is preparing it with care.',
    ],
    heroIcon: 'check',
    dataRows: [...ORDER_ROWS],
    defaultCtaLabel: 'VIEW ORDER DETAILS',
    defaultCtaPath: '/account/orders',
  },
  order_processing: {
    defaultSubject: 'Your Order Is Processing',
    scriptAccent: 'Good News!',
    headline: "We're Processing Your Order",
    bodyParagraphs: ['Your order is being prepared in our studio.'],
    heroIcon: 'gear',
    dataRows: [
      { label: 'Order Number', valueKey: 'orderNumber', fallback: '—' },
      { label: 'Estimated Ship Date', valueKey: 'estimatedDate', fallback: '—' },
    ],
    defaultCtaLabel: 'VIEW ORDER DETAILS',
    defaultCtaPath: '/account/orders',
  },
  order_shipped: {
    defaultSubject: 'Your Order Has Shipped',
    scriptAccent: "It's On The Way!",
    headline: 'Your Order Has Shipped',
    bodyParagraphs: ['Your package is on its way. Track your delivery below.'],
    heroIcon: 'truck',
    dataRows: [...TRACKING_ROWS],
    defaultCtaLabel: 'TRACK MY ORDER',
    defaultCtaPath: '/account/orders',
  },
  order_out_for_delivery: {
    defaultSubject: 'Out For Delivery',
    scriptAccent: 'Almost There!',
    headline: 'Out For Delivery',
    bodyParagraphs: ['Your order is out for delivery today.'],
    heroIcon: 'pin',
    dataRows: [
      { label: 'Order Number', valueKey: 'orderNumber', fallback: '—' },
      { label: 'Estimated Delivery', valueKey: 'estimatedDate', fallback: 'TODAY' },
    ],
    defaultCtaLabel: 'TRACK MY ORDER',
    defaultCtaPath: '/account/orders',
  },
  order_delivered: {
    defaultSubject: 'Your Order Has Arrived',
    scriptAccent: 'Delivered!',
    headline: 'Your Order Has Arrived',
    bodyParagraphs: [
      'Your order has been delivered. Tag us on social — #FRONTALSLAYER.',
    ],
    heroIcon: 'bag',
    dataRows: [...ORDER_ROWS],
    defaultCtaLabel: 'VIEW ORDER DETAILS',
    defaultCtaPath: '/account/orders',
  },
  order_delayed: {
    defaultSubject: 'Order Update',
    scriptAccent: 'We Appreciate Your Patience',
    headline: 'A Quick Update',
    bodyParagraphs: ['Your order needs a little extra time. We will keep you posted.'],
    heroIcon: 'hourglass',
    dataRows: [
      { label: 'Order Number', valueKey: 'orderNumber', fallback: '—' },
      { label: 'New Estimated Ship Date', valueKey: 'estimatedDate', fallback: '—' },
    ],
    defaultCtaLabel: 'VIEW ORDER DETAILS',
    defaultCtaPath: '/account/orders',
  },
  order_canceled: {
    defaultSubject: 'Order Canceled',
    scriptAccent: "We're Sorry",
    headline: 'Order Canceled',
    bodyParagraphs: ['Your order has been canceled. Contact us if you need assistance.'],
    heroIcon: 'x',
    dataRows: [...ORDER_ROWS],
    defaultCtaLabel: 'CONTACT US',
    defaultCtaPath: '/brand/contact',
  },
  payment_received: {
    defaultSubject: 'Payment Received',
    scriptAccent: 'Thank You!',
    headline: 'Payment Received',
    bodyParagraphs: ['We received your payment. Thank you for shopping with Frontal Slayer.'],
    heroIcon: 'payment',
    dataRows: [
      { label: 'Order Number', valueKey: 'orderNumber', fallback: '—' },
      { label: 'Amount', valueKey: 'paymentAmount', fallback: '—' },
    ],
    defaultCtaLabel: 'VIEW ORDER DETAILS',
    defaultCtaPath: '/account/orders',
  },
  partially_shipped: {
    defaultSubject: 'Partial Shipment On The Way',
    scriptAccent: 'Partial Shipment',
    headline: 'On The Way',
    bodyParagraphs: [
      'Some items from your order have shipped. Remaining items will follow soon.',
    ],
    heroIcon: 'bag',
    dataRows: [...TRACKING_ROWS],
    defaultCtaLabel: 'TRACK MY ORDER',
    defaultCtaPath: '/account/orders',
  },
  points_earned: {
    defaultSubject: 'You Earned Loyalty Points',
    scriptAccent: 'You Earned',
    headline: '{{pointsAmount}} Points',
    bodyParagraphs: ['Great slay — loyalty points have been added to your account.'],
    heroIcon: 'diamond',
    dataRows: [...POINTS_ROWS],
    defaultCtaLabel: 'VIEW YOUR BALANCE',
    defaultCtaPath: '/account/rewards',
  },
  points_redeemed: {
    defaultSubject: 'Points Redeemed',
    scriptAccent: 'Redeemed',
    headline: 'Points Redeemed',
    bodyParagraphs: ['You redeemed loyalty points. Enjoy your reward.'],
    heroIcon: 'gift',
    dataRows: [
      { label: 'Redeemed For', valueKey: 'redeemedFor', fallback: '—' },
      { label: 'Points Used', valueKey: 'pointsAmount', fallback: '—' },
      { label: 'Remaining Balance', valueKey: 'balance', fallback: '0' },
    ],
    defaultCtaLabel: 'VIEW REWARDS',
    defaultCtaPath: '/account/rewards',
  },
  points_expiring: {
    defaultSubject: 'Loyalty Points Expiring Soon',
    scriptAccent: 'Reminder!',
    headline: 'Points Expiring Soon',
    bodyParagraphs: ['Use your points before they expire.'],
    heroIcon: 'hourglass',
    dataRows: [
      { label: 'Points Expiring', valueKey: 'pointsAmount', fallback: '—' },
      { label: 'Expiration Date', valueKey: 'expirationDate', fallback: '—' },
    ],
    defaultCtaLabel: 'REDEEM NOW',
    defaultCtaPath: '/account/rewards',
  },
  voucher_expiring: {
    defaultSubject: 'Your Voucher Is Expiring',
    scriptAccent: 'Reminder!',
    headline: 'Your Voucher Is Expiring',
    bodyParagraphs: ['Do not miss your member voucher — shop before it expires.'],
    heroIcon: 'hourglass',
    dataRows: [
      { label: 'Voucher Type', valueKey: 'voucherType', fallback: '—' },
      { label: 'Expires On', valueKey: 'expirationDate', fallback: '—' },
    ],
    defaultCtaLabel: 'SHOP NOW',
    defaultCtaPath: '/home/shop',
  },
  referral_redeemed: {
    defaultSubject: 'Referral Reward Earned',
    scriptAccent: 'Great News!',
    headline: 'Referral Redeemed',
    bodyParagraphs: ['Someone used your referral — points have been added to your account.'],
    heroIcon: 'heart',
    dataRows: [
      { label: 'Points Earned', valueKey: 'referralPoints', fallback: '—' },
      { label: 'Your Balance', valueKey: 'balance', fallback: '0' },
    ],
    defaultCtaLabel: 'VIEW MY REWARDS',
    defaultCtaPath: '/account/referrals',
  },
  digital_cash_update: {
    defaultSubject: 'Digital Cash Update',
    scriptAccent: 'Balance Update',
    headline: 'Digital Cash Update',
    bodyParagraphs: ['Your digital cash balance has been updated.'],
    heroIcon: 'fs',
    dataRows: [
      { label: 'Current Balance', valueKey: 'balance', fallback: '$0.00' },
      { label: 'Recent Deposit', valueKey: 'digitalCashAmount', fallback: '—' },
    ],
    defaultCtaLabel: 'VIEW BALANCE',
    defaultCtaPath: '/account',
  },
  affiliate_content_received: {
    defaultSubject: 'Affiliate Content Received',
    scriptAccent: 'Received',
    headline: 'Content Received',
    bodyParagraphs: ['We received your affiliate submission and will review it shortly.'],
    heroIcon: 'check',
    dataRows: [...AFFILIATE_SUBMIT_ROWS],
    defaultCtaLabel: 'VIEW AFFILIATE DASHBOARD',
    defaultCtaPath: '/account/affiliate',
  },
  affiliate_content_pending: {
    defaultSubject: 'Affiliate Content Pending Review',
    scriptAccent: 'Pending',
    headline: 'Content Pending Approval',
    bodyParagraphs: ['Your submission is in review. Typically takes 1–3 business days.'],
    heroIcon: 'hourglass',
    dataRows: [...AFFILIATE_SUBMIT_ROWS],
    defaultCtaLabel: 'VIEW AFFILIATE DASHBOARD',
    defaultCtaPath: '/account/affiliate',
  },
  affiliate_content_approved: {
    defaultSubject: 'Affiliate Content Approved',
    scriptAccent: 'Approved!',
    headline: 'Content Approved',
    bodyParagraphs: ['Your affiliate content was approved. Points will be credited to your account.'],
    heroIcon: 'diamond',
    dataRows: [
      { label: 'Content Type', valueKey: 'contentType', fallback: '—' },
      { label: 'Platform', valueKey: 'platformName', fallback: '—' },
      { label: 'Points Earned', valueKey: 'pointsAmount', fallback: '—' },
    ],
    defaultCtaLabel: 'VIEW MY EARNINGS',
    defaultCtaPath: '/account/affiliate',
  },
  affiliate_content_denied: {
    defaultSubject: 'Affiliate Content Not Approved',
    scriptAccent: 'Update',
    headline: 'Content Not Approved',
    bodyParagraphs: [
      'Your submission did not meet our guidelines.',
      'Reason: {{declineReason}}',
    ],
    heroIcon: 'x',
    dataRows: [...AFFILIATE_SUBMIT_ROWS],
    defaultCtaLabel: 'VIEW GUIDELINES',
    defaultCtaPath: '/account/affiliate',
  },
  affiliate_points_earned: {
    defaultSubject: 'Affiliate Points Earned',
    scriptAccent: 'You Earned',
    headline: '{{pointsAmount}} Affiliate Points',
    bodyParagraphs: ['Points have been added for your approved affiliate content.'],
    heroIcon: 'diamond',
    dataRows: [...POINTS_ROWS],
    defaultCtaLabel: 'VIEW MY EARNINGS',
    defaultCtaPath: '/account/affiliate',
  },
  affiliate_payment_sent: {
    defaultSubject: 'Affiliate Payment Sent',
    scriptAccent: 'Payment Sent',
    headline: 'Your Payment Is On The Way',
    bodyParagraphs: ['We sent your affiliate payout.'],
    heroIcon: 'fs',
    dataRows: [
      { label: 'Amount', valueKey: 'paymentAmount', fallback: '—' },
      { label: 'Date', valueKey: 'submissionDate', fallback: '—' },
      { label: 'Method', valueKey: 'platformName', fallback: 'PayPal' },
    ],
    defaultCtaLabel: 'VIEW AFFILIATE DASHBOARD',
    defaultCtaPath: '/account/affiliate',
  },
  membership_welcome: {
    defaultSubject: 'Welcome to Premium Membership',
    scriptAccent: 'Welcome to',
    headline: 'Premium Membership',
    bodyParagraphs: [
      'Hi {{customerName}}, your premium membership is active.',
      'Enjoy exclusive access, early drops, and VIP perks.',
    ],
    heroIcon: 'crown',
    showMemberPerks: true,
    defaultCtaLabel: 'EXPLORE PERKS',
    defaultCtaPath: '/account/rewards',
  },
  tier_upgraded: {
    defaultSubject: 'Rewards Tier Upgraded',
    scriptAccent: 'Congratulations!',
    headline: 'Tier Upgraded to {{tierName}}',
    bodyParagraphs: ['You unlocked a new rewards tier. Enjoy elevated member benefits.'],
    heroIcon: 'trophy',
    dataRows: [{ label: 'New Tier', valueKey: 'tierName', fallback: '—' }],
    defaultCtaLabel: 'VIEW REWARDS',
    defaultCtaPath: '/account/rewards',
  },
  birthday_reward: {
    defaultSubject: 'Happy Birthday — A Gift For You',
    scriptAccent: 'Happy Birthday!',
    headline: 'Birthday Reward',
    bodyParagraphs: ['Celebrate with an exclusive birthday reward from Frontal Slayer.'],
    heroIcon: 'crown',
    defaultCtaLabel: 'CLAIM REWARD',
    defaultCtaPath: '/account/concierge',
  },
  special_offer: {
    defaultSubject: 'Exclusive Offer Just For You',
    scriptAccent: 'Just for You',
    headline: 'Exclusive Offer',
    bodyParagraphs: ['Enjoy a members-only discount on your next order.'],
    heroIcon: 'gift',
    dataRows: [{ label: 'Discount Code', valueKey: 'discountCode', fallback: '—' }],
    defaultCtaLabel: 'SHOP THE COLLECTION',
    defaultCtaPath: '/home/shop',
  },
  back_in_stock: {
    defaultSubject: 'Back In Stock',
    scriptAccent: 'Good News!',
    headline: 'Back In Stock',
    bodyParagraphs: ['{{productName}} is back — grab it before it sells out again.'],
    heroIcon: 'bag',
    dataRows: [{ label: 'Product', valueKey: 'productName', fallback: '—' }],
    defaultCtaLabel: 'SHOP NOW',
    defaultCtaPath: '/home/shop',
  },
  wishlist_price_drop: {
    defaultSubject: 'Wishlist Price Drop',
    scriptAccent: 'Price Drop',
    headline: 'Your Wishlist Item Dropped',
    bodyParagraphs: ['A saved item is now at a better price.'],
    heroIcon: 'bag',
    dataRows: [{ label: 'Product', valueKey: 'productName', fallback: '—' }],
    defaultCtaLabel: 'CHECK IT OUT',
    defaultCtaPath: '/wishlist',
  },
  consult_offer_sent: {
    defaultSubject: 'Your Consult Offer Is Ready',
    scriptAccent: 'Your Offer',
    headline: 'Consult Offer Available',
    bodyParagraphs: ['Your custom unit offer is ready to review and claim.'],
    heroIcon: 'gift',
    dataRows: [{ label: 'Order Number', valueKey: 'orderNumber', fallback: '—' }],
    defaultCtaLabel: 'VIEW OFFER',
    defaultCtaPath: '/account/orders',
  },
  meeting_reschedule: {
    defaultSubject: 'Appointment Reschedule Request',
    scriptAccent: 'Appointment Update',
    headline: 'Reschedule Request',
    bodyParagraphs: [
      'Your stylist requested to reschedule your appointment.',
      'Reason: {{meetingReason}}. {{meetingMessage}}',
    ],
    heroIcon: 'envelope',
    defaultCtaLabel: 'REVIEW APPOINTMENT',
    defaultCtaPath: '/account/notifications',
  },
  meeting_cancel: {
    defaultSubject: 'Appointment Cancel Request',
    scriptAccent: 'Appointment Update',
    headline: 'Cancel Request',
    bodyParagraphs: [
      'There is an update regarding your appointment.',
      'Reason: {{meetingReason}}. {{meetingMessage}}',
    ],
    heroIcon: 'x',
    defaultCtaLabel: 'REVIEW APPOINTMENT',
    defaultCtaPath: '/account/notifications',
  },
  account_login_alert: {
    defaultSubject: 'New Account Login',
    scriptAccent: 'Security Alert',
    headline: 'Account Login Detected',
    bodyParagraphs: ['We noticed a sign-in to your Frontal Slayer account.'],
    heroIcon: 'lock',
    dataRows: [
      { label: 'Location', valueKey: 'loginLocation', fallback: '—' },
      { label: 'Device', valueKey: 'loginDevice', fallback: '—' },
      { label: 'Date & Time', valueKey: 'loginDateTime', fallback: '—' },
    ],
    defaultCtaLabel: 'SECURE MY ACCOUNT',
    defaultCtaPath: '/account/settings',
  },
  profile_updated: {
    defaultSubject: 'Profile Updated',
    scriptAccent: 'Updated',
    headline: 'Profile Updated',
    bodyParagraphs: ['Your account profile was successfully updated.'],
    heroIcon: 'check',
    defaultCtaLabel: 'VIEW PROFILE',
    defaultCtaPath: '/account/settings',
  },
  email_updated: {
    defaultSubject: 'Email Address Updated',
    scriptAccent: 'Updated',
    headline: 'Email Updated',
    bodyParagraphs: ['Your account email address was changed.'],
    heroIcon: 'envelope',
    defaultCtaLabel: 'VIEW ACCOUNT',
    defaultCtaPath: '/account/settings',
  },
};

export function isEmailTemplateType(value: string): value is EmailTemplateType {
  return Object.prototype.hasOwnProperty.call(EMAIL_TEMPLATE_REGISTRY, value);
}
