"""icons.json → public sprite + typed name list."""
import os
HERE = os.path.dirname(os.path.abspath(__file__))
SHEET = os.path.join(HERE, '..', '..', 'docs', 'migration-recovery', 'icon-sheet', 'aio-icon-sheet-source.png')
BUILD = os.path.join(HERE, '.build')
os.makedirs(BUILD, exist_ok=True)
import json
APP = os.path.join(HERE, '..', '..')
icons = json.load(open(os.path.join(BUILD, 'icons.json')))
COLORED = {'success', 'failure', 'skipped', 'pending', 'running', 'warning', 'info', 'pass', 'fail', 'skipped-small',
           'home-active', 'home-inactive', 'error-log', 'info-log', 'success-log', 'info-mark', 'alert-mark'}
syms = ''.join(f'<symbol id="{k}" viewBox="0 0 56 56"><path fill-rule="evenodd" d="{v["d"]}"/></symbol>' for k, v in icons.items())
os.makedirs(f'{APP}/public/migration/icons', exist_ok=True)
open(f'{APP}/public/migration/icons/aio-icon-sheet.svg', 'w').write(
    '<svg xmlns="http://www.w3.org/2000/svg"><!-- AIO icon sheet (founder-supplied), traced to vector. Regenerate: scripts/icon-sheet/ -->' + syms + '</svg>\n')
names = ', '.join(f"'{k}'" for k in icons)
tones = ''.join(f"\n  '{k}': '{v['color']}'," for k, v in icons.items() if k in COLORED)
open(f'{APP}/src/client-migration/visual/aioIconSheet.ts', 'w').write(f"""/**
 * AIO icon sheet — the founder-supplied icon sheet traced to vector symbols (56×56 sheet-px window per icon,
 * so relative scale between icons is the sheet's own). Generated by scripts/icon-sheet/; do not edit by hand.
 */
export const AIO_SHEET_URL = '/migration/icons/aio-icon-sheet.svg';

export const AIO_SHEET_ICONS = [{names}] as const;

export type AioSheetIcon = (typeof AIO_SHEET_ICONS)[number];

/** Colours sampled from the sheet for its coloured status icons. */
export const AIO_SHEET_TONES: Partial<Record<AioSheetIcon, string>> = {{{tones}
}};
""")
print(os.path.getsize(f'{APP}/public/migration/icons/aio-icon-sheet.svg') // 1024, 'KB sprite')
