/**
 * Chief of Staff V1.0 bootstrap — demo operational seed (Milestone 38).
 */

import { EXECUTIVE_LEADERSHIP_ROSTER, SOFT_APPROVAL_SOURCES } from './constants';
import { bootstrapChiefOfStaffStore, refreshChiefOfStaffDashboard } from './store';
import type { ChiefOfStaffStore, ExecutiveInboxItem } from './types';

function hoursAgo(h: number): string {
  return new Date(Date.now() - h * 3600_000).toISOString();
}

function buildInboxItem(partial: ExecutiveInboxItem): ExecutiveInboxItem {
  return partial;
}

export function buildChiefOfStaffSeed(): Partial<ChiefOfStaffStore> {
  const executiveInbox: ExecutiveInboxItem[] = [
    buildInboxItem({
      id: 'inbox-1',
      submittedAt: hoursAgo(1),
      executiveId: 'chief-creative-officer',
      executiveTitle: 'Chief Creative Officer',
      department: 'Creative',
      category: 'thumbnail approval',
      title: 'Page 028 thumbnail — stat overlay variant B',
      summary: 'CCO recommends stat overlay for money volume page 028 credit chapter.',
      decisionLevel: 2,
      status: 'soft-approved',
      confidencePct: 88,
      riskLevel: 'low',
      supportingEvidence: ['Matches approved money volume template', 'Labs experiment #38 winner (+18% CTR)', 'Creative DNA: bold stat overlays preferred'],
      similarHistoricalApprovals: ['Page 019 thumbnail approved 2026-06-28', 'Page 024 stat overlay auto-approved'],
      reasoning: 'High alignment with Creative DNA and historical founder approvals for money volume stat overlays.',
      recommendedAction: 'Soft approve — no founder review needed',
      evaluatedAgainst: [...SOFT_APPROVAL_SOURCES.slice(0, 5)],
      workspaceId: 'ai-media',
    }),
    buildInboxItem({
      id: 'inbox-2',
      submittedAt: hoursAgo(2),
      executiveId: 'chief-content-officer',
      executiveTitle: 'Chief Content Officer',
      department: 'Content',
      category: 'script approval',
      title: 'Page 029 script — habits chapter hook revision',
      summary: 'CCO returned script for stronger question hook per Labs #42 results.',
      decisionLevel: 2,
      status: 'returned-revision',
      confidencePct: 71,
      riskLevel: 'medium',
      supportingEvidence: ['Hook variant B outperforms in experiments', 'Writing Bible: question hooks for mind volume'],
      similarHistoricalApprovals: ['Page 014 script approved after hook revision'],
      reasoning: 'Confidence below soft threshold — revision recommended before scheduling.',
      recommendedAction: 'Return to content team with hook template B',
      evaluatedAgainst: ['Writing Bible', 'Creative DNA', 'Previous Founder Decisions'],
      workspaceId: 'ai-media',
    }),
    buildInboxItem({
      id: 'inbox-3',
      submittedAt: hoursAgo(3),
      executiveId: 'chief-marketing-officer',
      executiveTitle: 'Chief Marketing Officer',
      department: 'Marketing',
      category: 'marketing campaign',
      title: 'Money Monday March cycle — cross-platform push',
      summary: 'CMO proposes coordinated Instagram + TikTok push for 3 money pages.',
      decisionLevel: 2,
      status: 'soft-approved',
      confidencePct: 85,
      riskLevel: 'low',
      supportingEvidence: ['Campaign template approved Q1', 'Distribution calendar alignment', 'No brand deviation'],
      similarHistoricalApprovals: ['February Money Monday cycle auto-approved'],
      reasoning: 'Standard campaign sequencing within approved playbook.',
      recommendedAction: 'Soft approve campaign schedule',
      evaluatedAgainst: ['Memory Bible', 'Company DNA', 'Institutional Knowledge'],
      workspaceId: 'ai-media',
    }),
    buildInboxItem({
      id: 'inbox-4',
      submittedAt: hoursAgo(4),
      executiveId: 'chief-operations-officer',
      executiveTitle: 'Chief Operations Officer',
      department: 'Operations',
      category: 'publishing schedule',
      title: 'Reschedule page 030 to 6 PM — tech volume slot',
      summary: 'COO requests schedule shift based on analytics best-hour data.',
      decisionLevel: 1,
      status: 'auto-approved',
      confidencePct: 92,
      riskLevel: 'low',
      supportingEvidence: ['Level 1 scheduling authority', 'Analytics Director sign-off', 'No conflict with page 028'],
      similarHistoricalApprovals: ['12 schedule adjustments auto-approved this week'],
      reasoning: 'Minor scheduling optimization — automatic approval.',
      recommendedAction: 'Applied to publishing timeline',
      evaluatedAgainst: ['Approved Design Systems', 'Previous Founder Decisions'],
      workspaceId: 'ai-media',
    }),
    buildInboxItem({
      id: 'inbox-5',
      submittedAt: hoursAgo(5),
      executiveId: 'chief-financial-officer',
      executiveTitle: 'Chief Financial Officer',
      department: 'Finance',
      category: 'budget request',
      title: 'Q3 creator tools subscription — $2,400 annual',
      summary: 'CFO requests approval for analytics + scheduling tool stack renewal.',
      decisionLevel: 3,
      status: 'escalated',
      confidencePct: 68,
      riskLevel: 'high',
      supportingEvidence: ['ROI projection 3.2x based on time savings', 'Within discretionary budget band', 'Requires founder sign-off per spending policy'],
      similarHistoricalApprovals: ['Q2 tool renewal approved with 15% discount negotiation'],
      reasoning: 'High-value spending exceeds CoS authority — founder judgment required on vendor and timing.',
      recommendedAction: 'Escalate to founder — review ROI deck',
      evaluatedAgainst: ['Company DNA', 'Memory Bible', 'Previous Founder Decisions'],
      workspaceId: 'ai-media',
    }),
    buildInboxItem({
      id: 'inbox-6',
      submittedAt: hoursAgo(6),
      executiveId: 'chief-growth-officer',
      executiveTitle: 'Chief Growth Officer',
      department: 'Growth',
      category: 'workflow improvement',
      title: 'Automate caption A/B routing to Labs',
      summary: 'CGO proposes automation rule: all captions → Labs caption test before publish.',
      decisionLevel: 2,
      status: 'soft-approved',
      confidencePct: 84,
      riskLevel: 'low',
      supportingEvidence: ['Automation Engineer reviewed', 'No manual step removed without fallback', 'Aligns with quality bar'],
      similarHistoricalApprovals: ['Hook testing automation approved Milestone 35'],
      reasoning: 'Workflow optimization within CoS delegation — soft approved.',
      recommendedAction: 'Deploy automation rule to ndxbook pipeline',
      evaluatedAgainst: ['Knowledge Graph', 'Institutional Knowledge', 'Approved Design Systems'],
      workspaceId: 'ai-media',
    }),
    buildInboxItem({
      id: 'inbox-7',
      submittedAt: hoursAgo(8),
      executiveId: 'chief-legal-officer',
      executiveTitle: 'Chief Legal Officer',
      department: 'Legal',
      category: 'brand review',
      title: 'Affiliate disclosure language — consumer volume',
      summary: 'CLO reviews standard affiliate disclaimer for page 031 consumer deals content.',
      decisionLevel: 3,
      status: 'escalated',
      confidencePct: 74,
      riskLevel: 'medium',
      supportingEvidence: ['New FTC guidance reference attached', 'Diff from approved template v2.1', 'Legal prefers founder acknowledgment on policy updates'],
      similarHistoricalApprovals: ['Consumer volume disclaimer v2.0 approved 2026-05-12'],
      reasoning: 'Legal policy update — founder should confirm alignment with brand risk tolerance.',
      recommendedAction: 'Founder review disclosure copy (2 min read)',
      evaluatedAgainst: ['Memory Bible', 'Company DNA', 'Writing Bible'],
      workspaceId: 'ai-media',
    }),
    buildInboxItem({
      id: 'inbox-8',
      submittedAt: hoursAgo(0.5),
      executiveId: 'chief-creative-officer',
      executiveTitle: 'Chief Creative Officer',
      department: 'Creative',
      category: 'creative approval',
      title: 'Brand voice check — page 028 caption tone',
      summary: 'Minor copy edit: soften one phrase to match Writing Bible avoid-list.',
      decisionLevel: 1,
      status: 'auto-approved',
      confidencePct: 95,
      riskLevel: 'low',
      supportingEvidence: ['Single phrase swap', 'Writing Bible compliance', 'No meaning change'],
      similarHistoricalApprovals: ['47 minor copy edits auto-approved this month'],
      reasoning: 'Level 1 automatic — internal organization / minor copy.',
      recommendedAction: 'Applied to page 028 caption',
      evaluatedAgainst: ['Writing Bible', 'Creative DNA'],
      workspaceId: 'ai-media',
    }),
  ];

  // Add bulk auto-approved items for attention protection stats
  for (let i = 9; i <= 27; i++) {
    executiveInbox.push(
      buildInboxItem({
        id: `inbox-${i}`,
        submittedAt: hoursAgo(i * 0.3),
        executiveId: 'chief-content-officer',
        executiveTitle: 'Chief Content Officer',
        department: 'Content',
        category: 'creative approval',
        title: `Page ${String(i).padStart(3, '0')} production checkpoint`,
        summary: 'Routine production gate passed soft approval.',
        decisionLevel: 1,
        status: i % 5 === 0 ? 'soft-approved' : 'auto-approved',
        confidencePct: 86 + (i % 10),
        riskLevel: 'low',
        supportingEvidence: ['Template match', 'DNA compliance'],
        similarHistoricalApprovals: ['Batch auto-approval pattern'],
        reasoning: 'Routine operational approval.',
        recommendedAction: 'Processed without founder interruption',
        evaluatedAgainst: ['Creative DNA', 'Writing Bible'],
        workspaceId: 'ai-media',
      })
    );
  }

  return {
    softApprovalThresholdPct: 82,
    dashboard: {
      executiveSummary:
        '27 pages completed overnight · 25 automatically approved · 2 require founder review · ndxbook publishing on track · thumbnail bottleneck clearing',
      todayPriorities: [
        'Review Q3 tools budget ($2,400) — CFO escalated',
        'Confirm affiliate disclosure update — CLO escalated',
        'Approve page 028 publish at 2 PM — already soft-approved by CoS',
        'Clear remaining thumbnail queue before Friday',
      ],
      itemsRequiringApproval: 2,
      itemsAutoApproved: 25,
      itemsRejected: 0,
      itemsReturnedRevision: 1,
      pendingRisks: 2,
      pendingOpportunities: 3,
      overallConfidencePct: 84,
      estimatedFounderReviewMins: 4,
      attentionProtectionNote: '27 pages completed · 25 automatically approved · 2 require founder review · estimated review time · 4 minutes',
    },
    morningBriefing: {
      businessHealthSummary: 'Company health 78% · publishing 82% · reader growth +12% WoW · revenue pacing $428/day',
      departmentSummaries: [
        'Content · 14 pages in production · 1 revision returned',
        'Creative · thumbnail queue clearing · 3 active approvals',
        'Marketing · Money Monday cycle soft-approved',
        'Operations · schedule optimized · automation +1 rule',
        'Finance · 1 budget escalation pending founder',
        'Legal · 1 disclosure review pending founder',
      ],
      majorOpportunities: [
        'Mind volume retention +18% — expand habits chapter',
        'Credit content trending — accelerate page 028',
        '2 PM publish slot historically +22% first-hour views',
      ],
      majorRisks: [
        'Thumbnail review bottleneck > 24h on 3 pages',
        'Affiliate disclosure policy update needs founder sign-off',
      ],
      importantApprovals: ['Q3 creator tools $2,400', 'Consumer volume affiliate disclaimer v2.2'],
      todayPriorities: [
        'Founder: 2 escalations (~4 min)',
        'Publish page 028 at 2 PM',
        'Connect Instagram OAuth for ndxbook',
      ],
      executiveRecommendations: [
        'CoS: soft-approve remaining thumbnails using Labs #38 template',
        'CMO: hold carousel test until page 028 publishes',
        'CGO: increase mind volume cadence to 3 pages/week',
      ],
      studioIntelligenceSummary: 'Delegate additional L2 approvals — creative consistency improving · founder overload risk low today',
      estimatedFounderWorkloadMins: 4,
    },
    executiveInbox,
    executiveLeadership: EXECUTIVE_LEADERSHIP_ROSTER.map((exec, i) => ({
      id: exec.id,
      title: exec.title,
      department: exec.department,
      reportsTo: 'chief-of-staff' as const,
      status: i === 2 ? ('coaching' as const) : ('active' as const),
      pendingSubmissions: [2, 1, 3, 1, 1, 0, 0, 1, 2][i] ?? 0,
      autoApprovalRatePct: [88, 91, 72, 85, 94, 90, 87, 89, 86][i] ?? 85,
    })),
    departments: [
      { id: 'marketing', name: 'Marketing', healthPct: 81, autonomy: 'soft-approval', pendingItems: 1, autoApprovedToday: 4, escalatedToday: 0, executiveId: 'chief-marketing-officer' },
      { id: 'operations', name: 'Operations', healthPct: 86, autonomy: 'fully-autonomous', pendingItems: 0, autoApprovedToday: 8, escalatedToday: 0, executiveId: 'chief-operations-officer' },
      { id: 'creative', name: 'Creative', healthPct: 74, autonomy: 'soft-approval', pendingItems: 3, autoApprovedToday: 6, escalatedToday: 0, executiveId: 'chief-creative-officer' },
      { id: 'finance', name: 'Finance', healthPct: 79, autonomy: 'founder-review', pendingItems: 1, autoApprovedToday: 2, escalatedToday: 1, executiveId: 'chief-financial-officer' },
      { id: 'legal', name: 'Legal', healthPct: 92, autonomy: 'manual-approval', pendingItems: 1, autoApprovedToday: 0, escalatedToday: 1, executiveId: 'chief-legal-officer' },
      { id: 'growth', name: 'Growth', healthPct: 77, autonomy: 'chief-of-staff-only', pendingItems: 0, autoApprovedToday: 3, escalatedToday: 0, executiveId: 'chief-growth-officer' },
      { id: 'content', name: 'Content', healthPct: 83, autonomy: 'soft-approval', pendingItems: 2, autoApprovedToday: 12, escalatedToday: 0, executiveId: 'chief-content-officer' },
    ],
    founderDecisions: [
      { id: 'fd-1', timestamp: hoursAgo(48), itemId: 'hist-1', action: 'approved', reason: 'Stat overlay aligns with brand', patternsLearned: ['Prefers bold stat thumbnails for money volume', 'Fast approval when Labs data supports'] },
      { id: 'fd-2', timestamp: hoursAgo(72), itemId: 'hist-2', action: 'rejected', reason: 'Too casual for money content', patternsLearned: ['Rejects casual tone in money volume', 'Writing Bible enforcement priority'] },
      { id: 'fd-3', timestamp: hoursAgo(96), itemId: 'hist-3', action: 'approved', reason: 'Standard tool renewal', patternsLearned: ['Approves ops tools under $3K with ROI deck', 'Prefers annual vs monthly billing'] },
    ],
    coachingNotes: [
      { id: 'coach-1', executiveId: 'chief-creative-officer', executiveTitle: 'Chief Creative Officer', issue: 'Thumbnail queue aging > 24h on 3 items', feedback: 'Implement Labs #38 template as default for money/mind volumes', trainingRecommended: 'Asset Director thumbnail playbook · Knowledge Hub', recurring: true },
      { id: 'coach-2', executiveId: 'chief-content-officer', executiveTitle: 'Chief Content Officer', issue: 'Script confidence below threshold on habits chapter', feedback: 'Apply question hook template B from Labs #42 before resubmit', trainingRecommended: 'Writing Bible · hook patterns module', recurring: false },
    ],
    leadershipTimeline: [
      { id: 'tl-1', timestamp: hoursAgo(2), type: 'approval', title: '25 ITEMS AUTO-APPROVED OVERNIGHT', detail: 'CoS soft approval engine · threshold 82%' },
      { id: 'tl-2', timestamp: hoursAgo(4), type: 'delegation', title: 'OPERATIONS → FULLY AUTONOMOUS', detail: 'Founder increased scheduling autonomy' },
      { id: 'tl-3', timestamp: hoursAgo(24), type: 'learning', title: 'DECISION PATTERN · MONEY THUMBNAILS', detail: 'Founder approved stat overlay 3x — confidence +8%' },
      { id: 'tl-4', timestamp: hoursAgo(48), type: 'confidence', title: 'CoS CONFIDENCE 84% → 86%', detail: 'Improved alignment with Creative DNA evaluations' },
      { id: 'tl-5', timestamp: hoursAgo(72), type: 'decision', title: 'FOUNDER REJECTED CASUAL MONEY COPY', detail: 'Pattern stored — Writing Bible enforcement' },
    ],
    crossWorkspaceInsights: [
      { id: 'cw-1', workspaceId: 'ai-media', workspaceName: 'AI Media · ndxbook', insight: 'Mind volume outperforming — allocate 2 extra pages this week', founderAttentionImpact: 'high' },
      { id: 'cw-2', workspaceId: 'frontal-slayer', workspaceName: 'Frontal Slayer', insight: 'Product photography pipeline reusable for ndxbook thumbnails', founderAttentionImpact: 'medium' },
      { id: 'cw-3', workspaceId: 'ai-media', workspaceName: 'AI Media', insight: 'Duplicate hook testing in Labs and Content Brain — consolidate', founderAttentionImpact: 'low' },
    ],
    studioIntelligenceAdvisories: [
      { id: 'si-1', signal: 'Founder overload risk · LOW today', recommendation: 'Delegate 2 additional L2 creative approvals to CoS', confidencePct: 88 },
      { id: 'si-2', signal: 'Creative consistency improving +6% WoW', recommendation: 'Increase creative department autonomy to soft-approval', confidencePct: 81 },
      { id: 'si-3', signal: 'Marketing confidence decreased on carousel format', recommendation: 'Reduce automation threshold for Instagram carousels to 90%', confidencePct: 76 },
    ],
    executiveMemory: {
      visualTaste: ['Bold stat overlays on money content', 'Minimal text on thumbnails', 'Red accent sparingly', 'Page number badges on all ndxbook pages'],
      writingStyle: ['Direct · no hype', 'Question hooks for mind volume', 'Avoid casual tone in money content', 'Short sentences · scannable'],
      decisionPatterns: ['Fast approval when Labs data supports', 'Rejects casual money copy', 'Approves ops tools under $3K with ROI', 'Legal updates always reviewed personally'],
      qualityExpectations: ['72%+ completion target', 'Brand voice per Writing Bible', 'Every page = Labs experiment', 'No live social without OAuth'],
      brandPhilosophy: ['ndxbook = index for everyday knowledge', 'AI Media internal · ndxbook public', 'Quality over volume', 'Founder vision > operational noise'],
      communicationPreferences: ['One morning briefing · not dozens of pings', 'Escalate with confidence + evidence', '4-minute review budget respected'],
      longTermVision: ['Build media company operating system', 'ndxbook as flagship public brand', 'Automate operations · protect founder attention'],
      sources: ['Leadership DNA', 'Creative DNA', 'Writing Bible', 'Memory Bible', 'Knowledge Graph', 'Founder decision history'],
    },
    delegationByDepartment: {
      marketing: 'soft-approval',
      operations: 'fully-autonomous',
      creative: 'soft-approval',
      finance: 'founder-review',
      legal: 'manual-approval',
      growth: 'chief-of-staff-only',
      content: 'soft-approval',
    },
  };
}

export function bootstrapChiefOfStaffPlatform(): void {
  bootstrapChiefOfStaffStore(buildChiefOfStaffSeed());
  refreshChiefOfStaffDashboard();
}

