/**
 * Simulation Engine — AI Media workspace demo seeds & bootstrap.
 */

import { AI_MEDIA_WORKSPACE_ID } from '../../../studio-os-core/ai-media-network/constants';
import {
  bootstrapSimulationEngineStore,
  mergeSimulationEnginePatch,
  readSimulationEngineStore,
  refreshSimulationDashboard,
} from '../../../studio-os-core/simulation-engine/store';
import type { SimulationEngineStore } from '../../../studio-os-core/simulation-engine/types';

const WS = AI_MEDIA_WORKSPACE_ID;
const now = '2026-07-04T22:00:00.000Z';
const SIM_PRICING = 'sim-pricing-q3';

export function buildSimulationEngineStorePatch(): Partial<SimulationEngineStore> {
  return {
    simulations: [
      {
        id: SIM_PRICING,
        workspaceId: WS,
        title: 'Q3 Subscription Pricing — $29 vs $39 vs $49',
        type: 'pricing-change',
        status: 'completed',
        depth: 'deep',
        assumptions: {
          budget: '$12K marketing',
          timeline: '90 days',
          teamSize: 4,
          industry: 'Digital media / education',
          pricing: '$29 / $39 / $49',
          marketingSpend: '$8K/mo',
          traffic: '124K/mo baseline',
          conversion: '4.2% newsletter',
          riskTolerance: 'medium',
        },
        confidence: 76,
        createdAt: '2026-07-01T00:00:00.000Z',
        completedAt: now,
        knowledgeGraphNodeId: 'node-simulation-pricing-q3',
        recommendedByIntelligence: true,
      },
      {
        id: 'sim-learnflow-partnership',
        workspaceId: WS,
        title: 'LearnFlow Co-Sponsorship Deal Simulation',
        type: 'brand-partnership',
        status: 'completed',
        depth: 'standard',
        assumptions: {
          budget: '$0 upfront',
          timeline: '6 months',
          pricing: '$18K/mo sponsorship',
          riskTolerance: 'low',
        },
        confidence: 82,
        createdAt: '2026-06-28T00:00:00.000Z',
        completedAt: '2026-07-02T00:00:00.000Z',
        knowledgeGraphNodeId: 'node-simulation-learnflow',
        recommendedByIntelligence: true,
      },
      {
        id: 'sim-finance-series',
        workspaceId: WS,
        title: 'Finance Myth-Busting Mini-Series Launch',
        type: 'content-strategy',
        status: 'running',
        depth: 'standard',
        assumptions: {
          timeline: '6 episodes over 8 weeks',
          teamSize: 3,
          marketingSpend: '$4K',
          conversion: '5% target',
        },
        confidence: 0,
        createdAt: now,
        knowledgeGraphNodeId: 'node-simulation-finance-series',
        recommendedByIntelligence: true,
      },
      {
        id: 'sim-bd-hire',
        workspaceId: WS,
        title: 'Part-Time Sponsorship Coordinator Hire',
        type: 'new-hire',
        status: 'draft',
        depth: 'quick',
        assumptions: {
          budget: '$3.5K/mo',
          timeline: '30-day hire',
          teamSize: 5,
          riskTolerance: 'medium',
        },
        confidence: 0,
        createdAt: now,
        knowledgeGraphNodeId: 'node-simulation-bd-hire',
        recommendedByIntelligence: true,
      },
    ],
    scenarios: [
      {
        id: 'scen-29',
        simulationId: SIM_PRICING,
        label: '$29/mo',
        parameters: { price: '29' },
        projectedRevenue: '$18.2K/mo',
        projectedConversion: '6.1%',
        projectedRetention: '88%',
        projectedProfit: '$12.4K/mo',
        projectedGrowth: '+22% subs',
        customerAcquisition: '$14 CAC',
        confidence: 81,
        recommended: false,
      },
      {
        id: 'scen-39',
        simulationId: SIM_PRICING,
        label: '$39/mo',
        parameters: { price: '39' },
        projectedRevenue: '$21.8K/mo',
        projectedConversion: '4.8%',
        projectedRetention: '91%',
        projectedProfit: '$15.1K/mo',
        projectedGrowth: '+14% subs',
        customerAcquisition: '$18 CAC',
        confidence: 76,
        recommended: true,
      },
      {
        id: 'scen-49',
        simulationId: SIM_PRICING,
        label: '$49/mo',
        parameters: { price: '49' },
        projectedRevenue: '$19.6K/mo',
        projectedConversion: '3.2%',
        projectedRetention: '93%',
        projectedProfit: '$14.2K/mo',
        projectedGrowth: '+8% subs',
        customerAcquisition: '$24 CAC',
        confidence: 68,
        recommended: false,
      },
    ],
    riskAnalyses: [
      {
        simulationId: SIM_PRICING,
        bestCase: '$39 tier drives +18% MRR with minimal churn — finance audience accepts premium',
        expectedCase: '+12% MRR at $39 with 2% churn bump — aligns with Labs EXP-042 audience data',
        worstCase: 'Price sensitivity on Wellness Wednesday audience — 8% churn, net -4% MRR',
        confidenceScore: 76,
        majorAssumptions: ['Finance audience less price-sensitive', 'No competitor undercut in Q3', 'Marketing spend held constant'],
        keyRisks: ['Sponsor concentration unchanged', 'Wellness audience cross-over churn'],
        mitigationStrategies: ['Grandfather existing subs 90 days', 'Bundle Writing Bible at $39 tier', 'A/B test on Money Monday first'],
      },
    ],
    financialSims: [
      {
        simulationId: SIM_PRICING,
        cashFlow: '+$4.2K/mo net positive',
        expenses: '$6.7K/mo fixed + $8K marketing',
        profit: '$15.1K/mo at $39 scenario',
        runway: '18 months at current burn',
        burnRate: '$14.7K/mo',
        revenueGrowth: '+12% projected',
        subscriptionGrowth: '+14% subs',
        marketplaceRevenue: '+$2.1K from deal velocity',
        royalties: '$420/mo Writing Bible',
        walletBalance: '$47K pending payouts',
        teamCosts: '$22K/mo',
      },
    ],
    marketingSims: [
      {
        simulationId: 'sim-finance-series',
        campaignPerformance: '+34% vs network avg (historical finance content)',
        reach: '48K incremental views',
        engagement: '62% completion target',
        conversions: '340 newsletter subs',
        affiliateRevenue: '$1.2K projected',
        emailGrowth: '+15% open rate on finance topics',
        audienceGrowth: '+2.8K subs',
        cac: '$11.50',
        roas: '3.2x on $4K spend',
      },
    ],
    contentSims: [
      {
        simulationId: 'sim-finance-series',
        publishingFrequency: '6 episodes / 8 weeks',
        contentPillars: ['Finance myth-busting', 'Money Monday extension'],
        thumbnailImpact: '+12% CTR (Labs thumbnail test inconclusive — use finance template)',
        hookVariation: 'Question-first hooks — EXP-042 validated',
        voiceChange: 'No change — Maya Chen host',
        platformSelection: 'YouTube primary · Newsletter secondary',
        seriesExpansion: 'Tech Tuesday cross-promote week 4',
        historicalBasis: ['Q1 Finance series +41% subs', 'EXP-042 +28% completion', 'Money Monday 90d performance'],
      },
    ],
    organizationSims: [
      {
        simulationId: 'sim-bd-hire',
        hiringPlan: 'Part-time sponsorship coordinator — 20 hrs/wk',
        restructuring: 'None',
        outsourcing: 'Pulse Agency retained for production',
        newAiExecutives: [],
        newDepartments: [],
        estimatedCost: '$3.5K/mo + $1K onboarding',
        efficiencyGain: 'Deal response time 4.2d → 1.5d projected',
        deliverySpeed: '+35% close rate (benchmark)',
        operationalComplexity: 'Low — reports to CMO executive AI',
      },
    ],
    marketplaceSims: [
      {
        simulationId: 'sim-learnflow-partnership',
        brandDeals: 'LearnFlow EdTech co-sponsorship $18K/mo',
        creatorPartnerships: 'Maya Chen + LearnFlow cross-promote',
        pricingNegotiations: '12-month term · 6-month review clause',
        affiliatePartnerships: 'Finance tool affiliates +$800/mo',
        serviceProviders: 'Casey Lee editor retainer',
        revenueImpact: '+$18.8K/mo weighted · 82% confidence',
      },
    ],
    timelineProjections: [
      {
        simulationId: SIM_PRICING,
        horizon: '90-day',
        milestones: ['Week 2: A/B on Money Monday', 'Week 6: Full rollout', 'Week 12: Retention review'],
        revenueProjection: '+$26K cumulative',
        growthProjection: '+420 net subs',
        confidence: 76,
      },
      {
        simulationId: SIM_PRICING,
        horizon: '1-year',
        milestones: ['Q1: $39 tier stable', 'Q2: Bundle launch', 'Q4: Enterprise tier pilot'],
        revenueProjection: 'ARR $340K (+19%)',
        growthProjection: '+2.1K subs',
        confidence: 62,
      },
    ],
    decisionReports: [
      {
        simulationId: SIM_PRICING,
        executiveSummary: 'Recommend $39/mo tier — optimal profit/revenue balance with acceptable conversion tradeoff. Not a guarantee — explore with 90-day grandfather and Money Monday A/B first.',
        confidenceScore: 76,
        supportingEvidence: ['Labs EXP-042 finance audience data', 'Q1 pricing test +12% MRR', 'Studio Intelligence revenue concentration risk'],
        majorAssumptions: ['Finance audience premium tolerance', 'Stable marketing spend', 'No major competitor move'],
        keyOpportunities: ['Bundle Writing Bible at $39', 'LearnFlow cross-sell to subscribers'],
        majorRisks: ['Wellness audience churn', 'Sponsor concentration unchanged'],
        recommendedActions: ['A/B test on Money Monday first', 'Grandfather existing 90 days', 'Monitor churn weekly'],
        alternativeScenarios: ['Stay at $29 and volume-grow', 'Jump to $49 with enterprise positioning'],
      },
    ],
    executiveContributions: [
      {
        simulationId: SIM_PRICING,
        executiveRole: 'cfo',
        executiveName: 'CFO · Financial Strategist',
        contribution: 'Profit maximization at $39 — runway extends 2 months vs $29 scenario',
        confidence: 78,
      },
      {
        simulationId: SIM_PRICING,
        executiveRole: 'cmo',
        executiveName: 'CMO · Growth Strategist',
        contribution: 'Conversion dip at $49 unacceptable — $39 preserves brand premium without CAC spike',
        confidence: 74,
      },
      {
        simulationId: SIM_PRICING,
        executiveRole: 'cgo',
        executiveName: 'Chief Growth Officer',
        contribution: '14% sub growth at $39 vs 22% at $29 — net revenue favors $39',
        confidence: 71,
      },
    ],
    library: [
      {
        id: 'lib-pricing-template',
        workspaceId: WS,
        title: 'Subscription Pricing Comparison Template',
        type: 'pricing-change',
        version: '1.2.0',
        shared: false,
        archived: false,
        templateReady: true,
        createdAt: '2026-06-01T00:00:00.000Z',
      },
      {
        id: 'lib-partnership-template',
        workspaceId: WS,
        title: 'Brand Partnership Revenue Template',
        type: 'brand-partnership',
        version: '1.0.0',
        forkedFrom: 'sim-learnflow-partnership',
        shared: false,
        archived: false,
        templateReady: true,
        createdAt: '2026-07-02T00:00:00.000Z',
      },
    ],
    learningLoops: [
      {
        id: 'learn-q1-pricing',
        simulationId: 'sim-q1-pricing-archived',
        workspaceId: WS,
        predictedOutcome: '+15% MRR from $5 price increase',
        actualOutcome: '+12% MRR — close to prediction',
        accuracyPct: 80,
        incorrectAssumptions: ['Underestimated wellness audience sensitivity'],
        unexpectedVariables: ['Competitor free tier launch in Q1'],
        confidenceImprovement: 8,
        recordedAt: '2026-04-15T00:00:00.000Z',
      },
    ],
    intelligenceRecommendations: [
      {
        id: 'intel-rec-pricing',
        workspaceId: WS,
        trigger: 'Studio Intelligence flagged revenue diversification',
        suggestedSimulationType: 'pricing-change',
        reason: 'Before increasing prices — simulate $29 vs $39 vs $49 with historical conversion data',
        confidence: 88,
      },
      {
        id: 'intel-rec-hire',
        workspaceId: WS,
        trigger: 'Deal response time 4.2 days vs benchmark 1.5',
        suggestedSimulationType: 'new-hire',
        reason: 'Before hiring sponsorship coordinator — simulate cost vs close rate improvement',
        confidence: 71,
      },
      {
        id: 'intel-rec-campaign',
        workspaceId: WS,
        trigger: 'Finance Myth-Busting campaign recommendation',
        suggestedSimulationType: 'marketing-campaign',
        reason: 'Before major marketing spend — simulate $4K campaign ROI from Labs historical data',
        confidence: 85,
      },
    ],
  };
}

export function bootstrapAiMediaSimulationEngine(): void {
  bootstrapSimulationEngineStore();
  const store = readSimulationEngineStore();
  if (store.simulations.length > 0) return;
  mergeSimulationEnginePatch(buildSimulationEngineStorePatch());
  refreshSimulationDashboard(WS);
}
