import type {
  AplCoreSystemReference,
  AplDependency,
  AplExecutionRecord,
  AplGenesisReference,
  AplLaunchStackReference,
  AplLessonLearned,
  AplModelPerformanceRecord,
  AplPromptCollection,
  AplPromptRelationship,
  AplPromptTemplate,
  AplPromptVersion,
  AplGeneratedOutput,
  AplValidationResult,
  AplVersionComparison,
} from '../types';

function ts(daysAgo = 0): string {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  return d.toISOString();
}

export const SEED_COLLECTIONS: AplPromptCollection[] = [
  {
    collectionId: 'col-studio-architecture',
    officialName: 'Studio OS Architecture Collection™',
    purpose: 'Constitutional and platform architecture prompts for Studio OS design.',
    steward: 'Orb · Library Curator',
    categories: ['architecture', 'platform-evolution', 'system-review'],
    promptIds: ['apl-evolution-room-arch', 'apl-executive-reflection-arch', 'apl-genesis-governance'],
    healthScore: 92,
    lastReviewed: ts(7),
  },
  {
    collectionId: 'col-launch-stack',
    officialName: 'Launch Stack Implementation Collection™',
    purpose: 'Implementation prompts tied to Launch Stack milestones and graduation.',
    steward: 'Studio OS Architect',
    categories: ['implementation', 'engineering', 'validation'],
    promptIds: ['apl-launch-stack-impl', 'apl-fat-validation', 'apl-lvs-diary'],
    healthScore: 88,
    lastReviewed: ts(14),
  },
  {
    collectionId: 'col-executive-experience',
    officialName: 'Executive Experience Design Collection™',
    purpose: 'Founder-facing immersive environments and reflection ceremonies.',
    steward: 'Executive Experience Lead',
    categories: ['creative', 'founder-experience', 'architecture'],
    promptIds: ['apl-evolution-room-arch', 'apl-executive-reflection-arch'],
    healthScore: 90,
    lastReviewed: ts(10),
  },
  {
    collectionId: 'col-validation-testing',
    officialName: 'Validation and Testing Collection™',
    purpose: 'FAT, LVS, and platform validation prompts.',
    steward: 'Validation Architect',
    categories: ['validation', 'testing', 'system-review'],
    promptIds: ['apl-fat-validation', 'apl-lvs-diary'],
    healthScore: 86,
    lastReviewed: ts(5),
  },
];

export const SEED_PROMPTS: AplPromptTemplate[] = [
  {
    promptId: 'apl-evolution-room-arch',
    officialName: 'Evolution Room™ Architecture Prompt',
    purpose: 'Design the immersive Evolution Room executive strategy environment with Genesis integration.',
    category: 'architecture',
    collectionIds: ['col-studio-architecture', 'col-executive-experience'],
    recommendedModel: 'claude-opus',
    alternativeModels: ['gpt-4.1', 'claude-sonnet'],
    requiredContext: ['Genesis.md', 'Launch Stack status', 'Executive Headquarters IA'],
    body: `Design Evolution Room™ as an immersive executive strategy environment inside Studio OS Headquarters — not dashboards.

Requirements:
- Genesis submodule with persistence under genesis_v1
- Integration with Live Validation System™ and Founder Acceptance Testing™
- Orb Presentation Mode™
- Launch Stack health synthesis
- Never auto-modify Genesis — proposals only
- Marble/glass immersive aesthetic`,
    expectedDeliverables: ['Architecture article', 'Genesis rule', 'Runtime spec', 'UI room routes'],
    expectedArtifacts: ['genesis/articles/EVOLUTION_ROOM.md', 'src/studio-os-core/genesis/evolution-room/'],
    priority: 'critical',
    complexity: 'constitutional',
    estimatedRuntimeMin: 120,
    lifecycleStage: 'canonized',
    reviewStatus: 'approved',
    approvalStatus: 'canonized',
    canonical: true,
    author: 'Founder · Studio OS Architect',
    currentVersion: '1.0.0',
    tags: ['evolution-room', 'executive', 'genesis', 'immersive'],
    knownLimitations: ['Requires LVS/FAT subsystems bootstrapped first'],
    lastUpdated: ts(30),
  },
  {
    promptId: 'apl-executive-reflection-arch',
    officialName: 'Executive Reflection Suite™ Architecture Prompt',
    purpose: 'Expand Evolution Room into full Executive Reflection Suite with 17 rooms and ceremonies.',
    category: 'architecture',
    collectionIds: ['col-studio-architecture', 'col-executive-experience'],
    recommendedModel: 'claude-opus',
    alternativeModels: ['gpt-4.1'],
    requiredContext: ['Evolution Room runtime', 'Genesis §9B', 'FAT withdrawal/replacement tests'],
    body: `Build Executive Reflection Suite™ as a first-class Headquarters wing — 17 rooms, 18 engines, Orb Presentation Mode.

Rooms: Founder Diary, Victory Gallery, Boardroom, Annual Summit, Quarterly Retreat, Failure Laboratory, etc.
Integrate LVS diary, FAT tests, Evolution Room brief.
Session outputs: executive summary, strategic priorities, Genesis improvement proposals.`,
    expectedDeliverables: ['Architecture article', 'Genesis rule §9B.11', 'Full runtime + UI'],
    expectedArtifacts: ['genesis/articles/EXECUTIVE_REFLECTION_SUITE.md', 'executive-reflection-suite/'],
    priority: 'critical',
    complexity: 'constitutional',
    estimatedRuntimeMin: 180,
    lifecycleStage: 'canonized',
    reviewStatus: 'approved',
    approvalStatus: 'canonized',
    canonical: true,
    author: 'Founder · Studio OS Architect',
    currentVersion: '1.0.0',
    tags: ['executive-reflection', 'headquarters', 'genesis'],
    knownLimitations: ['Depends on Evolution Room subsystem'],
    lastUpdated: ts(20),
  },
  {
    promptId: 'apl-genesis-governance',
    officialName: 'Genesis Governance Architecture Prompt',
    purpose: 'Design constitutional governance for Genesis objects, proposals, and canonization.',
    category: 'architecture',
    collectionIds: ['col-studio-architecture'],
    recommendedModel: 'claude-opus',
    alternativeModels: ['claude-sonnet'],
    requiredContext: ['Genesis.md', 'Build Order', 'Core Systems map'],
    body: `Define Genesis as constitutional infrastructure: object model, pipeline stages, review gates, ADR flow, compile targets.
No auto-canonization. Founder approval required for constitutional changes.`,
    expectedDeliverables: ['Genesis framework modules', 'Review gates', 'Compiler pipeline'],
    expectedArtifacts: ['src/studio-os-core/genesis/'],
    priority: 'critical',
    complexity: 'constitutional',
    estimatedRuntimeMin: 240,
    lifecycleStage: 'canonized',
    reviewStatus: 'approved',
    approvalStatus: 'canonized',
    canonical: true,
    author: 'Founder',
    currentVersion: '2.1.0',
    tags: ['genesis', 'governance', 'constitution'],
    knownLimitations: [],
    lastUpdated: ts(60),
  },
  {
    promptId: 'apl-launch-stack-impl',
    officialName: 'Launch Stack Implementation Prompt',
    purpose: 'Implement a Launch Stack milestone with build order tracking and graduation criteria.',
    category: 'implementation',
    collectionIds: ['col-launch-stack'],
    recommendedModel: 'composer',
    alternativeModels: ['claude-sonnet', 'gpt-4.1'],
    requiredContext: ['Build Order registry', 'Milestone spec', 'Genesis subsystem pattern'],
    body: `Implement Launch Stack milestone following Genesis submodule pattern:
- types, persistence, bootstrap/seed, engines, room/ready-view, hook, immersive UI
- updateBuildOrderSystemStatus on bootstrap
- Single commit + push per task`,
    expectedDeliverables: ['Runtime code', 'UI routes', 'Platform doc', 'Motherboard update'],
    expectedArtifacts: ['src/studio-os-core/genesis/<subsystem>/', 'docs/studio-os/genesis/'],
    priority: 'high',
    complexity: 'complex',
    estimatedRuntimeMin: 90,
    lifecycleStage: 'genesis-updated',
    reviewStatus: 'approved',
    approvalStatus: 'founder-approved',
    canonical: false,
    author: 'Studio OS Engineer',
    currentVersion: '1.2.0',
    tags: ['launch-stack', 'implementation'],
    knownLimitations: ['Must follow one-deploy-per-task rule'],
    lastUpdated: ts(8),
  },
  {
    promptId: 'apl-fat-validation',
    officialName: 'Founder Acceptance Testing Validation Prompt',
    purpose: 'Run FAT withdrawal and replacement tests for platform indispensability.',
    category: 'validation',
    collectionIds: ['col-validation-testing', 'col-launch-stack'],
    recommendedModel: 'claude-sonnet',
    alternativeModels: ['gpt-4o'],
    requiredContext: ['FAT store', 'System registry', 'Launch Stack milestones'],
    body: `Execute Founder Acceptance Testing:
- Withdrawal Test: would founder miss this system?
- Replacement Test: can external tools replace it?
Document scores, dependencies, graduation eligibility.`,
    expectedDeliverables: ['FAT test records', 'Health readings', 'Launch Stack health panel data'],
    expectedArtifacts: ['founder-acceptance-testing engines'],
    priority: 'high',
    complexity: 'moderate',
    estimatedRuntimeMin: 45,
    lifecycleStage: 'canonized',
    reviewStatus: 'approved',
    approvalStatus: 'canonized',
    canonical: true,
    author: 'Validation Architect',
    currentVersion: '1.0.0',
    tags: ['fat', 'validation', 'launch-stack'],
    knownLimitations: [],
    lastUpdated: ts(25),
  },
  {
    promptId: 'apl-lvs-diary',
    officialName: 'Live Validation Founder Diary Prompt',
    purpose: 'Generate adaptive founder diary prompts from Live Validation System signals.',
    category: 'validation',
    collectionIds: ['col-validation-testing'],
    recommendedModel: 'claude-sonnet',
    alternativeModels: ['gpt-4o'],
    requiredContext: ['LVS diary store', 'Escape patterns', 'Executive health lenses'],
    body: `Synthesize founder diary prompts from LVS signals — frustration, delight, escape velocity, mission drift.
Adaptive tone. Never auto-modify Genesis.`,
    expectedDeliverables: ['Diary prompts', 'Escape pattern analysis', 'Genesis improvement proposals (draft)'],
    expectedArtifacts: ['live-validation-system/'],
    priority: 'medium',
    complexity: 'moderate',
    estimatedRuntimeMin: 30,
    lifecycleStage: 'canonized',
    reviewStatus: 'approved',
    approvalStatus: 'canonized',
    canonical: true,
    author: 'LVS Architect',
    currentVersion: '1.1.0',
    tags: ['lvs', 'founder-diary', 'validation'],
    knownLimitations: ['Sentiment values must match LVS schema'],
    lastUpdated: ts(18),
  },
  {
    promptId: 'apl-prompt-library-arch',
    officialName: "Architect's Prompt Library™ Architecture Prompt",
    purpose: 'Design institutional prompt management as Institute of Knowledge subsystem.',
    category: 'architecture',
    collectionIds: ['col-studio-architecture'],
    recommendedModel: 'claude-opus',
    alternativeModels: ['gpt-4.1'],
    requiredContext: ['Institute of Knowledge IA', 'Prompt Registry existing code', 'Genesis §9B.12'],
    body: `Build The Architect's Prompt Library™ — not a prompt database.
Versioning, relationships, execution history, model intelligence, canonization, Orb librarian mode.
Every prompt connects to Genesis, Launch Stack, Core Systems, implementation results.`,
    expectedDeliverables: ['Architecture article', 'Genesis rule §9B.12', 'Full runtime + 13 room UI'],
    expectedArtifacts: ['genesis/articles/ARCHITECTS_PROMPT_LIBRARY.md', 'architects-prompt-library/'],
    priority: 'critical',
    complexity: 'constitutional',
    estimatedRuntimeMin: 150,
    lifecycleStage: 'execution',
    reviewStatus: 'in-review',
    approvalStatus: 'unapproved',
    canonical: false,
    author: 'Founder · Studio OS Architect',
    currentVersion: '1.0.0',
    tags: ['prompt-library', 'institute-of-knowledge', 'genesis'],
    knownLimitations: ['Must integrate with existing Prompt Registry workspace'],
    lastUpdated: ts(1),
  },
];

export const SEED_VERSIONS: AplPromptVersion[] = [
  {
    versionId: 'ver-evolution-1-0-0',
    promptId: 'apl-evolution-room-arch',
    semver: '1.0.0',
    changedSections: ['initial'],
    rationale: 'Canonical Evolution Room architecture approved.',
    author: 'Founder',
    fromExecutionLesson: false,
    compatibility: 'Evolution Room runtime v1',
    bodySnapshot: SEED_PROMPTS[0].body,
    approvedAt: ts(30),
    status: 'approved',
  },
  {
    versionId: 'ver-ers-1-0-0',
    promptId: 'apl-executive-reflection-arch',
    semver: '1.0.0',
    changedSections: ['initial'],
    rationale: 'Executive Reflection Suite wing architecture.',
    author: 'Founder',
    fromExecutionLesson: false,
    compatibility: 'ERS runtime v1',
    bodySnapshot: SEED_PROMPTS[1].body,
    approvedAt: ts(20),
    status: 'approved',
  },
  {
    versionId: 'ver-launch-1-2-0',
    promptId: 'apl-launch-stack-impl',
    semver: '1.2.0',
    changedSections: ['one-deploy rule', 'motherboard MEMORY'],
    rationale: 'Added one-deploy-per-task enforcement from execution lesson.',
    author: 'Studio OS Engineer',
    reviewer: 'Founder',
    fromExecutionLesson: true,
    supersedes: '1.1.0',
    compatibility: 'Build-a-Wig deploy policy',
    bodySnapshot: SEED_PROMPTS[3].body,
    approvedAt: ts(8),
    status: 'approved',
  },
  {
    versionId: 'ver-launch-1-1-0',
    promptId: 'apl-launch-stack-impl',
    semver: '1.1.0',
    changedSections: ['bootstrap pattern'],
    rationale: 'Standardized Genesis submodule bootstrap.',
    author: 'Studio OS Engineer',
    fromExecutionLesson: false,
    supersedes: '1.0.0',
    compatibility: 'Genesis v1',
    bodySnapshot: 'Earlier launch stack implementation prompt.',
    approvedAt: ts(45),
    retiredAt: ts(8),
    status: 'superseded',
  },
  {
    versionId: 'ver-apl-1-0-0',
    promptId: 'apl-prompt-library-arch',
    semver: '1.0.0',
    changedSections: ['initial'],
    rationale: 'Architect Prompt Library architecture draft.',
    author: 'Founder',
    fromExecutionLesson: false,
    compatibility: 'Institute of Knowledge',
    bodySnapshot: SEED_PROMPTS[6].body,
    status: 'draft',
  },
];

export const SEED_RELATIONSHIPS: AplPromptRelationship[] = [
  {
    relationshipId: 'rel-ers-derives-er',
    fromPromptId: 'apl-executive-reflection-arch',
    toRef: 'apl-evolution-room-arch',
    toLabel: 'Evolution Room™ Architecture Prompt',
    toKind: 'prompt',
    relationshipType: 'derives-from',
    rationale: 'ERS expands Evolution Room into full reflection wing.',
  },
  {
    relationshipId: 'rel-er-implements-genesis',
    fromPromptId: 'apl-evolution-room-arch',
    toRef: 'genesis/articles/EVOLUTION_ROOM.md',
    toLabel: 'Evolution Room Article',
    toKind: 'genesis-article',
    relationshipType: 'implements',
  },
  {
    relationshipId: 'rel-fat-validates-launch',
    fromPromptId: 'apl-fat-validation',
    toRef: 'launch-stack/milestone-graduation',
    toLabel: 'Launch Stack Graduation',
    toKind: 'launch-stack',
    relationshipType: 'validates',
  },
  {
    relationshipId: 'rel-apl-implements-genesis',
    fromPromptId: 'apl-prompt-library-arch',
    toRef: 'genesis/articles/ARCHITECTS_PROMPT_LIBRARY.md',
    toLabel: "Architect's Prompt Library Article",
    toKind: 'genesis-article',
    relationshipType: 'implements',
  },
  {
    relationshipId: 'rel-lvs-follows-fat',
    fromPromptId: 'apl-lvs-diary',
    toRef: 'apl-fat-validation',
    toLabel: 'FAT Validation Prompt',
    toKind: 'prompt',
    relationshipType: 'follows-up',
  },
];

export const SEED_DEPENDENCIES: AplDependency[] = [
  {
    dependencyId: 'dep-ers-evolution',
    promptId: 'apl-executive-reflection-arch',
    dependencyType: 'existing-prompt',
    targetRef: 'apl-evolution-room-arch',
    label: 'Evolution Room architecture must exist',
    required: true,
    satisfied: true,
  },
  {
    dependencyId: 'dep-er-genesis',
    promptId: 'apl-evolution-room-arch',
    dependencyType: 'genesis-article',
    targetRef: 'Genesis.md',
    label: 'Genesis constitutional framework',
    required: true,
    satisfied: true,
  },
  {
    dependencyId: 'dep-apl-genesis-rule',
    promptId: 'apl-prompt-library-arch',
    dependencyType: 'genesis-article',
    targetRef: 'genesis/articles/ARCHITECTS_PROMPT_LIBRARY.md',
    label: 'Prompt Library architecture article',
    required: true,
    satisfied: true,
  },
  {
    dependencyId: 'dep-launch-build-order',
    promptId: 'apl-launch-stack-impl',
    dependencyType: 'core-system',
    targetRef: 'build-order',
    label: 'Build Order registry',
    required: true,
    satisfied: true,
  },
];

export const SEED_EXECUTIONS: AplExecutionRecord[] = [
  {
    executionId: 'exec-evolution-room-1',
    promptId: 'apl-evolution-room-arch',
    promptVersion: '1.0.0',
    model: 'claude-opus',
    operator: 'Cursor Cloud Agent',
    contextSummary: 'Genesis runtime pattern · LVS/FAT integration · HQ aesthetic',
    startedAt: ts(32),
    completedAt: ts(31),
    outputSummary: 'Evolution Room runtime + UI shipped to master.',
    generatedArtifacts: ['src/studio-os-core/genesis/evolution-room/', '/admin/studio/evolution-room'],
    followUpTasks: ['Executive Reflection Suite expansion'],
    validationPassed: true,
    qualityScore: 94,
    costUsd: 12.4,
    runtimeMs: 7200000,
    linkedCommits: ['5ff30898e'],
  },
  {
    executionId: 'exec-ers-1',
    promptId: 'apl-executive-reflection-arch',
    promptVersion: '1.0.0',
    model: 'claude-opus',
    operator: 'Cursor Cloud Agent',
    contextSummary: '17 rooms · 18 engines · Orb mode',
    startedAt: ts(22),
    completedAt: ts(21),
    outputSummary: 'Executive Reflection Suite runtime + 17 sub-routes.',
    generatedArtifacts: ['executive-reflection-suite/', '/admin/studio/executive-reflection'],
    followUpTasks: ['Annual Summit ceremony polish'],
    validationPassed: true,
    qualityScore: 91,
    costUsd: 18.2,
    runtimeMs: 10800000,
    linkedCommits: ['ea390ddb2'],
  },
  {
    executionId: 'exec-apl-arch-1',
    promptId: 'apl-prompt-library-arch',
    promptVersion: '1.0.0',
    model: 'claude-opus',
    operator: 'Cursor Cloud Agent',
    contextSummary: 'Institute of Knowledge · 13 subsystems · Orb curator',
    startedAt: ts(2),
    completedAt: ts(1),
    outputSummary: 'Architecture article + Genesis rule §9B.12 approved.',
    generatedArtifacts: ['genesis/articles/ARCHITECTS_PROMPT_LIBRARY.md'],
    followUpTasks: ['Full runtime implementation'],
    validationPassed: true,
    qualityScore: 89,
    runtimeMs: 5400000,
    linkedCommits: ['93a9c6e66'],
  },
];

export const SEED_VALIDATIONS: AplValidationResult[] = [
  {
    validationId: 'val-evolution-1',
    promptId: 'apl-evolution-room-arch',
    executionId: 'exec-evolution-room-1',
    deliverablesComplete: true,
    buildPassed: true,
    founderApproved: true,
    genesisUpdated: true,
    reusable: true,
    contradictionsFound: false,
    canonizationEligible: true,
    notes: 'Build verified · Genesis rule added · LVS/FAT integrated.',
    validatedAt: ts(30),
  },
  {
    validationId: 'val-apl-arch-1',
    promptId: 'apl-prompt-library-arch',
    executionId: 'exec-apl-arch-1',
    deliverablesComplete: true,
    buildPassed: true,
    founderApproved: false,
    genesisUpdated: true,
    reusable: true,
    contradictionsFound: false,
    canonizationEligible: false,
    notes: 'Architecture approved — runtime implementation pending founder approval.',
    validatedAt: ts(1),
  },
];

export const SEED_MODEL_PERFORMANCE: AplModelPerformanceRecord[] = [
  {
    recordId: 'mp-arch-opus',
    promptId: 'apl-evolution-room-arch',
    category: 'architecture',
    model: 'claude-opus',
    successRate: 96,
    consistencyScore: 92,
    avgLatencyMs: 45000,
    avgQualityScore: 93,
    executionCount: 3,
    lastExecutedAt: ts(31),
    strengths: ['Constitutional reasoning', 'Long-form architecture', 'Genesis integration'],
    weaknesses: ['Higher cost', 'Slower iteration'],
  },
  {
    recordId: 'mp-impl-composer',
    promptId: 'apl-launch-stack-impl',
    category: 'implementation',
    model: 'composer',
    successRate: 88,
    consistencyScore: 85,
    avgLatencyMs: 12000,
    avgQualityScore: 87,
    executionCount: 12,
    lastExecutedAt: ts(8),
    strengths: ['Code generation', 'Repo conventions', 'Multi-file edits'],
    weaknesses: ['Needs architecture context upfront'],
  },
  {
    recordId: 'mp-val-sonnet',
    promptId: 'apl-fat-validation',
    category: 'validation',
    model: 'claude-sonnet',
    successRate: 91,
    consistencyScore: 89,
    avgLatencyMs: 8000,
    avgQualityScore: 90,
    executionCount: 8,
    lastExecutedAt: ts(25),
    strengths: ['Structured validation', 'Test schema compliance'],
    weaknesses: [],
  },
];

export const SEED_LESSONS: AplLessonLearned[] = [
  {
    lessonId: 'lesson-one-deploy',
    promptId: 'apl-launch-stack-impl',
    title: 'One deploy per task prevents Vercel churn',
    context: 'Multiple pushes to master triggered redundant production deploys.',
    insight: 'Append MEMORY.md before single agent-commit.sh run.',
    recommendation: 'Always fold motherboard updates into the same commit as code.',
    recordedAt: ts(8),
  },
  {
    lessonId: 'lesson-lvs-sentiment',
    promptId: 'apl-lvs-diary',
    title: 'LVS diary sentiment values are schema-bound',
    context: 'Used "frustrated" instead of "frustration" in seed data.',
    insight: 'Match exact LVS enum values in all integrations.',
    recommendation: 'Validate against LVS types before seeding.',
    recordedAt: ts(18),
  },
];

export const SEED_OUTPUTS: AplGeneratedOutput[] = [
  {
    outputId: 'out-er-runtime',
    promptId: 'apl-evolution-room-arch',
    executionId: 'exec-evolution-room-1',
    outputType: 'implementation-file',
    label: 'Evolution Room Genesis runtime',
    ref: 'src/studio-os-core/genesis/evolution-room/',
    createdAt: ts(31),
  },
  {
    outputId: 'out-ers-article',
    promptId: 'apl-executive-reflection-arch',
    executionId: 'exec-ers-1',
    outputType: 'genesis-article',
    label: 'Executive Reflection Suite architecture',
    ref: 'genesis/articles/EXECUTIVE_REFLECTION_SUITE.md',
    createdAt: ts(21),
  },
];

export const SEED_GENESIS_REFS: AplGenesisReference[] = [
  {
    refId: 'gref-er',
    promptId: 'apl-evolution-room-arch',
    articlePath: 'genesis/articles/EVOLUTION_ROOM.md',
    articleTitle: 'Evolution Room™',
    relationship: 'implements',
  },
  {
    refId: 'gref-ers',
    promptId: 'apl-executive-reflection-arch',
    articlePath: 'genesis/articles/EXECUTIVE_REFLECTION_SUITE.md',
    articleTitle: 'Executive Reflection Suite™',
    relationship: 'implements',
  },
  {
    refId: 'gref-apl',
    promptId: 'apl-prompt-library-arch',
    articlePath: 'genesis/articles/ARCHITECTS_PROMPT_LIBRARY.md',
    articleTitle: "The Architect's Prompt Library™",
    relationship: 'implements',
  },
];

export const SEED_LAUNCH_STACK_REFS: AplLaunchStackReference[] = [
  {
    refId: 'lsref-er',
    promptId: 'apl-evolution-room-arch',
    milestoneId: 'milestone-evolution-room',
    milestoneLabel: 'Evolution Room™ Graduation',
    systemId: 'evolution-room',
  },
  {
    refId: 'lsref-ers',
    promptId: 'apl-executive-reflection-arch',
    milestoneId: 'milestone-executive-reflection',
    milestoneLabel: 'Executive Reflection Suite™ Graduation',
    systemId: 'executive-reflection-suite',
  },
  {
    refId: 'lsref-apl',
    promptId: 'apl-prompt-library-arch',
    milestoneId: 'milestone-prompt-library',
    milestoneLabel: "Architect's Prompt Library™ Graduation",
    systemId: 'architects-prompt-library',
  },
];

export const SEED_CORE_SYSTEM_REFS: AplCoreSystemReference[] = [
  { refId: 'csref-genesis', promptId: 'apl-genesis-governance', systemId: 'genesis', systemLabel: 'Genesis™' },
  { refId: 'csref-fat', promptId: 'apl-fat-validation', systemId: 'founder-acceptance-testing', systemLabel: 'Founder Acceptance Testing™' },
  { refId: 'csref-lvs', promptId: 'apl-lvs-diary', systemId: 'live-validation-system', systemLabel: 'Live Validation System™' },
  { refId: 'csref-orb', promptId: 'apl-prompt-library-arch', systemId: 'orb', systemLabel: 'Orb™ · Library Curator' },
];

export const SEED_COMPARISONS: AplVersionComparison[] = [
  {
    comparisonId: 'cmp-launch-1-1-vs-1-2',
    promptId: 'apl-launch-stack-impl',
    versionA: '1.1.0',
    versionB: '1.2.0',
    summary: 'Added one-deploy-per-task rule from execution lesson.',
    qualityDelta: 4,
    bodyDiffSummary: '+ motherboard MEMORY fold-in · + agent-commit.sh enforcement',
  },
];
