import type { ModelRouteDefinition } from './types';
import {
  NANO_BANANA_2_EDIT_ENDPOINT,
  NANO_BANANA_2_T2I_ENDPOINT,
} from './nano-banana-2-schema';

export const SCENE_STACK_SHELL_FAL_MODEL = 'fal-ai/nano-banana-pro/edit' as const;

/** Background removal — dedicated route, not NB2. */
export const BACKGROUND_REMOVAL_FAL_MODEL = 'fal-ai/birefnet/v2' as const;

const FOUNDER_APPROVED_AT = '2026-07-12';
const FOUNDER_APPROVED_BY = 'founder-visual-comparison';

export const MODEL_REGISTRY_ROUTES: ModelRouteDefinition[] = [
  {
    routeId: 'nano-banana-pro-edit-shell',
    assetClass: 'environment-shell',
    generationMode: 'image-to-image',
    provider: 'fal',
    endpointId: SCENE_STACK_SHELL_FAL_MODEL,
    qualityPreset: 'production',
    targetResolution: '4K',
    referencePolicy: 'marble-genesis-anchor',
    alphaPolicy: 'none',
    backgroundPolicy: 'full-scene',
    supportsBrandAssetGuidance: false,
    supportsMultipleReferences: true,
    fallbackRouteIds: [],
    enabled: true,
    rolloutState: 'production',
    policyVersion: 'layer-model-routing.v2',
    approvedBy: FOUNDER_APPROVED_BY,
    approvedAt: FOUNDER_APPROVED_AT,
    notes: 'UNCHANGED — environment shell img2img with marble genesis anchor.',
  },
  {
    routeId: 'nano-banana-pro-founder-full-room',
    assetClass: 'founder-full-room-preview',
    generationMode: 'image-to-image',
    provider: 'fal',
    endpointId: SCENE_STACK_SHELL_FAL_MODEL,
    qualityPreset: 'production',
    targetResolution: '4K',
    referencePolicy: 'brand-material-references-only',
    alphaPolicy: 'none',
    backgroundPolicy: 'full-scene',
    supportsBrandAssetGuidance: true,
    supportsMultipleReferences: true,
    fallbackRouteIds: [],
    enabled: true,
    rolloutState: 'production',
    policyVersion: 'founder-render-routing.v1',
    approvedBy: FOUNDER_APPROVED_BY,
    approvedAt: FOUNDER_APPROVED_AT,
    notes: 'Founder Render™ — photoreal full-room preview for Founder Review approval gate.',
  },
  {
    routeId: 'nano-banana-2-isolated',
    assetClass: 'signature-landmark',
    generationMode: 'text-to-image',
    provider: 'fal',
    endpointId: NANO_BANANA_2_T2I_ENDPOINT,
    qualityPreset: 'production',
    targetResolution: '4K',
    referencePolicy: 'brand-material-references-only',
    alphaPolicy: 'post-cleanup',
    backgroundPolicy: 'studio-seamless',
    supportsBrandAssetGuidance: true,
    supportsMultipleReferences: true,
    fallbackRouteIds: ['nano-banana-2-isolated-edit'],
    enabled: true,
    rolloutState: 'production',
    policyVersion: 'layer-model-routing.v2',
    approvedBy: FOUNDER_APPROVED_BY,
    approvedAt: FOUNDER_APPROVED_AT,
    notes: 'Founder-approved isolated specialist — signature landmarks.',
  },
  {
    routeId: 'nano-banana-2-isolated-edit',
    assetClass: 'signature-landmark',
    generationMode: 'image-to-image',
    provider: 'fal',
    endpointId: NANO_BANANA_2_EDIT_ENDPOINT,
    qualityPreset: 'production',
    targetResolution: '4K',
    referencePolicy: 'brand-material-references-only',
    alphaPolicy: 'post-cleanup',
    backgroundPolicy: 'studio-seamless',
    supportsBrandAssetGuidance: true,
    supportsMultipleReferences: true,
    fallbackRouteIds: [],
    enabled: true,
    rolloutState: 'production',
    policyVersion: 'layer-model-routing.v2',
    approvedBy: FOUNDER_APPROVED_BY,
    approvedAt: FOUNDER_APPROVED_AT,
    notes: 'Brand-material reference mode — material URLs only, zero scene images.',
  },
  {
    routeId: 'nano-banana-2-isolated-group',
    assetClass: 'furniture-objects',
    generationMode: 'text-to-image',
    provider: 'fal',
    endpointId: NANO_BANANA_2_T2I_ENDPOINT,
    qualityPreset: 'production',
    targetResolution: '4K',
    referencePolicy: 'brand-material-references-only',
    alphaPolicy: 'post-cleanup',
    backgroundPolicy: 'studio-seamless',
    supportsBrandAssetGuidance: true,
    supportsMultipleReferences: true,
    fallbackRouteIds: ['nano-banana-2-isolated-edit'],
    enabled: true,
    rolloutState: 'production',
    policyVersion: 'layer-model-routing.v2',
    approvedBy: FOUNDER_APPROVED_BY,
    approvedAt: FOUNDER_APPROVED_AT,
    notes: 'Founder-approved isolated specialist — furniture object groups.',
  },
  {
    routeId: 'nano-banana-2-reception-structure',
    assetClass: 'reception-structure',
    generationMode: 'text-to-image',
    provider: 'fal',
    endpointId: NANO_BANANA_2_T2I_ENDPOINT,
    qualityPreset: 'production',
    targetResolution: '4K',
    referencePolicy: 'brand-material-references-only',
    alphaPolicy: 'post-cleanup',
    backgroundPolicy: 'studio-seamless',
    supportsBrandAssetGuidance: true,
    supportsMultipleReferences: true,
    fallbackRouteIds: ['nano-banana-2-isolated-edit'],
    enabled: true,
    rolloutState: 'production',
    policyVersion: 'layer-model-routing.v2',
    approvedBy: FOUNDER_APPROVED_BY,
    approvedAt: FOUNDER_APPROVED_AT,
    notes: 'Reception structures — brand-grounded isolated generation.',
  },
  {
    routeId: 'nano-banana-2-architectural-prop',
    assetClass: 'architectural-prop',
    generationMode: 'text-to-image',
    provider: 'fal',
    endpointId: NANO_BANANA_2_T2I_ENDPOINT,
    qualityPreset: 'production',
    targetResolution: '4K',
    referencePolicy: 'brand-material-references-only',
    alphaPolicy: 'post-cleanup',
    backgroundPolicy: 'studio-seamless',
    supportsBrandAssetGuidance: true,
    supportsMultipleReferences: true,
    fallbackRouteIds: ['nano-banana-2-isolated-edit'],
    enabled: true,
    rolloutState: 'production',
    policyVersion: 'layer-model-routing.v2',
    approvedBy: FOUNDER_APPROVED_BY,
    approvedAt: FOUNDER_APPROVED_AT,
    notes: 'Architectural props — brand-grounded isolated generation.',
  },
  {
    routeId: 'nano-banana-2-decorative-object',
    assetClass: 'decorative-object',
    generationMode: 'text-to-image',
    provider: 'fal',
    endpointId: NANO_BANANA_2_T2I_ENDPOINT,
    qualityPreset: 'production',
    targetResolution: '4K',
    referencePolicy: 'brand-material-references-only',
    alphaPolicy: 'post-cleanup',
    backgroundPolicy: 'studio-seamless',
    supportsBrandAssetGuidance: true,
    supportsMultipleReferences: true,
    fallbackRouteIds: ['nano-banana-2-isolated-edit'],
    enabled: true,
    rolloutState: 'production',
    policyVersion: 'layer-model-routing.v2',
    approvedBy: FOUNDER_APPROVED_BY,
    approvedAt: FOUNDER_APPROVED_AT,
    notes: 'Decorative objects — brand-grounded isolated generation.',
  },
  {
    routeId: 'birefnet-background-removal',
    assetClass: 'background-removal',
    generationMode: 'background-removal',
    provider: 'fal',
    endpointId: BACKGROUND_REMOVAL_FAL_MODEL,
    qualityPreset: 'production',
    targetResolution: '2K',
    referencePolicy: 'none',
    alphaPolicy: 'requested',
    backgroundPolicy: 'transparent-alpha',
    supportsBrandAssetGuidance: false,
    supportsMultipleReferences: false,
    fallbackRouteIds: [],
    enabled: true,
    rolloutState: 'production',
    policyVersion: 'layer-model-routing.v2',
    approvedBy: 'verified-pipeline',
    approvedAt: FOUNDER_APPROVED_AT,
    notes: 'Dedicated background removal — not NB2.',
  },
  {
    routeId: 'image-upscale-production',
    assetClass: 'image-upscale',
    generationMode: 'upscale',
    provider: 'fal',
    endpointId: 'fal-ai/clarity-upscaler',
    qualityPreset: 'production',
    targetResolution: '4K',
    referencePolicy: 'none',
    alphaPolicy: 'requested',
    backgroundPolicy: 'transparent-alpha',
    supportsBrandAssetGuidance: false,
    supportsMultipleReferences: false,
    fallbackRouteIds: [],
    enabled: true,
    rolloutState: 'production',
    policyVersion: 'layer-model-routing.v2',
    approvedBy: 'resolution-truth-policy',
    approvedAt: FOUNDER_APPROVED_AT,
    notes: 'Post-approval upscale path — labels output post-upscaled-4k.',
  },
];

export function getModelRouteById(routeId: string): ModelRouteDefinition | null {
  return MODEL_REGISTRY_ROUTES.find((r) => r.routeId === routeId && r.enabled) ?? null;
}

export function getPrimaryRouteForAssetClass(assetClass: import('./types.js').ModelAssetClass): ModelRouteDefinition {
  const primary = MODEL_REGISTRY_ROUTES.find(
    (r) => r.assetClass === assetClass && r.enabled && r.rolloutState === 'production'
  );
  if (!primary) {
    throw new Error(`No production route for asset class: ${assetClass}`);
  }
  return primary;
}

/** Isolated asset default — NB2 t2i (Founder decision 2026-07-12). */
export const SCENE_STACK_ISOLATED_OBJECT_FAL_MODEL = NANO_BANANA_2_T2I_ENDPOINT;
