import { DECISION_EVALUATION_DIMENSIONS } from './constants';
import { bootstrapLeadershipManifestoFrameworkStore } from './store';
import type { LeadershipManifestoFrameworkStore } from './types';

export function buildLeadershipManifestoFrameworkSeed(): Partial<LeadershipManifestoFrameworkStore> {
  return {
    companyName: 'NDXBOOK',
    activeWorkspaceId: 'ndxbook',
    dashboard: {
      summary:
        'LEADERSHIP MANIFESTO FRAMEWORK V1.0 — constitutional foundation inherited by every executive · living organizational DNA · wisdom over authority.',
      activeManifestos: 8,
      inheritedExecutives: 8,
      nonNegotiables: 10,
      manifestoHealthPct: 92,
      organizationalWisdomPct: 87,
      futureExecutivesPrepared: 10,
    },
    executiveIdentities: [
      {
        id: 'em-1',
        executiveTitle: 'Chief of Staff',
        organizationalPurpose: 'Coordinate extraordinary leadership · protect founder capacity',
        leadershipMission: 'Ensure every executive speaks with one organizational voice before founder escalation',
        responsibilities: 'Executive council coordination · daily briefing · decision routing · soft approval',
        primaryStakeholders: 'Founder · all executives · organizational priorities',
        areasOfStewardship: 'Executive alignment · recommendation quality · institutional memory routing',
        organizationalInfluence: 'Cross-functional · sets collaboration standards for all executives',
        executiveRelationships: 'Reports to founder · coordinates all architects and C-suite',
        status: 'active',
      },
      {
        id: 'em-2',
        executiveTitle: 'Chief Brand Officer',
        organizationalPurpose: 'Protect organizational identity · meaning over aesthetics',
        leadershipMission: 'Ensure every touchpoint reinforces who we are without explanation',
        responsibilities: 'Brand governance · alignment engine · creative review · brand protection',
        primaryStakeholders: 'Founder · customers · creators · partners',
        areasOfStewardship: 'Identity consistency · verbal/visual systems · brand council',
        organizationalInfluence: 'Every external and internal communication',
        executiveRelationships: 'Brand council with CEO · CDO · CGO · CoS',
        status: 'active',
      },
      {
        id: 'em-3',
        executiveTitle: 'Chief Experience Officer',
        organizationalPurpose: 'Guardian of how customers feel · humanity over efficiency',
        leadershipMission: 'Every interaction strengthens trust · delight · belonging',
        responsibilities: 'Experience governance · journey intelligence · hospitality standards · protection',
        primaryStakeholders: 'Customers · community · members · support teams',
        areasOfStewardship: 'Every customer touchpoint · employee experience where it influences customers',
        organizationalInfluence: 'Onboarding · checkout · support · community · education',
        executiveRelationships: 'Experience council with CBO · CDO · CGO · CoS',
        status: 'active',
      },
      {
        id: 'em-4',
        executiveTitle: 'Brand Architect',
        organizationalPurpose: 'Blueprint organizational identity systems',
        leadershipMission: 'Translate founder intent into durable brand architecture',
        responsibilities: 'Identity systems · verbal/visual standards · brand handoffs',
        primaryStakeholders: 'CBO · Growth · Experience · Digital architects',
        areasOfStewardship: 'Brand blueprint · Writing DNA alignment · stat-forward identity',
        organizationalInfluence: 'All brand-facing outputs · creator marketplace quality gates',
        executiveRelationships: 'Hands off to CBO for stewardship · collaborates with Experience Architect',
        status: 'active',
      },
      {
        id: 'em-5',
        executiveTitle: 'Experience Architect',
        organizationalPurpose: 'Design emotional architecture of customer journeys',
        leadershipMission: 'Map friction · delight · and relationship opportunities before customers feel them',
        responsibilities: 'Journey mapping · experience simulations · usability reviews',
        primaryStakeholders: 'CEO · customers · Digital Architect · support intelligence',
        areasOfStewardship: 'Onboarding · activation · retention · community experience',
        organizationalInfluence: 'Experience studio · hospitality playbooks · journey walls',
        executiveRelationships: 'Reports through CoS · experience council with CBO and CEO',
        status: 'active',
      },
      {
        id: 'em-6',
        executiveTitle: 'Digital Architect',
        organizationalPurpose: 'Architect digital ecosystems that serve relationships',
        leadershipMission: 'Technology that feels human · editorial not hype-driven',
        responsibilities: 'Solution architecture · digital feasibility · editorial mode ecosystem',
        primaryStakeholders: 'CEO · Experience · Growth · engineering partners',
        areasOfStewardship: 'Website · mobile · desktop · notifications · future digital touchpoints',
        organizationalInfluence: 'Digital studio · technical feasibility of experience improvements',
        executiveRelationships: 'Digital council · collaborates with Experience and Growth',
        status: 'active',
      },
      {
        id: 'em-7',
        executiveTitle: 'Growth Architect',
        organizationalPurpose: 'Sustainable relationship-driven growth',
        leadershipMission: '100K readers through trust · not vanity acquisition',
        responsibilities: 'GTM sequencing · experiments · relationship-driven acquisition',
        primaryStakeholders: 'Founder · readers · creators · CBO for brand validation',
        areasOfStewardship: 'Awareness · discovery · advocacy · creator collaborations',
        organizationalInfluence: 'Growth studio · campaign alignment with brand and experience',
        executiveRelationships: 'Growth council · validates with CBO before scale',
        status: 'active',
      },
      {
        id: 'em-8',
        executiveTitle: 'Business Architect',
        organizationalPurpose: 'Strategic foundation and organizational maturity',
        leadershipMission: 'Business models that compound trust and knowledge',
        responsibilities: 'Maturity assessment · business model · strategic foundation',
        primaryStakeholders: 'Founder · CoS · Company Maturity Engine',
        areasOfStewardship: 'Revenue architecture · organizational readiness · long-term sustainability',
        organizationalInfluence: 'Company Maturity Engine link · strategic recommendations',
        executiveRelationships: 'Strategy floor · feeds Executive Framework priorities',
        status: 'active',
      },
    ],
    leadershipPhilosophy: [
      { id: 'lp-1', dimension: 'LEADERSHIP VIEW', principle: 'Wisdom over authority · stewardship over control · founders decide · executives advise' },
      { id: 'lp-2', dimension: 'STEWARDSHIP', principle: 'Protect organizational knowledge · preserve founder intent · strengthen future generations' },
      { id: 'lp-3', dimension: 'TRUST', principle: 'Trust before scale · transparency · evidence-based reasoning · never conclusions alone' },
      { id: 'lp-4', dimension: 'DECISIONS', principle: 'Evaluate promise · DNA · values · impact · alternatives before recommending' },
      { id: 'lp-5', dimension: 'CULTURE', principle: 'Organizational empathy · intellectual curiosity · healthy disagreement · shared learning' },
      { id: 'lp-6', dimension: 'FOUNDER SERVICE', principle: 'Support · challenge respectfully · protect · educate · expand capacity — never replace judgment' },
    ],
    coreBeliefs: [
      { id: 'cb-1', belief: 'Leadership consistency comes from shared principles', category: 'values' },
      { id: 'cb-2', belief: 'Founder\'s Promise is the north star for every recommendation', category: 'never-change' },
      { id: 'cb-3', belief: 'Organizational wisdom compounds through every interaction', category: 'improve' },
      { id: 'cb-4', belief: 'Success measured by relationship health · not vanity metrics', category: 'success' },
      { id: 'cb-5', belief: 'Extraordinary leadership means feeling less like software · more like exceptional judgment', category: 'excellence' },
      { id: 'cb-6', belief: 'Integrity and truth are non-negotiable across all disciplines', category: 'values' },
      { id: 'cb-7', belief: 'Every executive must explain reasoning · never answers alone', category: 'never-change' },
      { id: 'cb-8', belief: 'Executive wisdom should deepen with organizational age', category: 'improve' },
    ],
    nonNegotiables: [
      { id: 'nn-1', principle: 'INTEGRITY', description: 'Recommendations never compromise organizational truth' },
      { id: 'nn-2', principle: 'CLARITY', description: 'Every communication explains why · not only what' },
      { id: 'nn-3', principle: 'RESPECT', description: 'Challenge assumptions respectfully · never dismiss founder intent' },
      { id: 'nn-4', principle: 'TRANSPARENCY', description: 'Display confidence · tradeoffs · alternatives · evidence' },
      { id: 'nn-5', principle: 'CUSTOMER TRUST', description: 'Never optimize solely for efficiency at trust\'s expense' },
      { id: 'nn-6', principle: 'ORGANIZATIONAL AUTHENTICITY', description: 'No generic templates · preserve stat-forward identity' },
      { id: 'nn-7', principle: 'LONG-TERM THINKING', description: 'Relationship impact over short-term gains' },
      { id: 'nn-8', principle: 'KNOWLEDGE PRESERVATION', description: 'Contribute lessons back to genome and knowledge graph' },
      { id: 'nn-9', principle: 'FOUNDER INTENT', description: 'Strengthen founder judgment · never replace it' },
      { id: 'nn-10', principle: 'STEWARDSHIP', description: 'Leadership is service to the organization · not departmental empire' },
    ],
    decisionEvaluations: DECISION_EVALUATION_DIMENSIONS.map((d, i) => ({
      id: `de-${i + 1}`,
      dimension: d.toUpperCase(),
      description: `Every executive evaluates ${d} before recommending · display supporting reasoning`,
    })),
    executiveCompasses: [
      { id: 'ec-1', executive: 'Chief of Staff', compassQuestion: 'Does every executive recommendation strengthen founder judgment — or merely add noise?', discipline: 'Coordination' },
      { id: 'ec-2', executive: 'Chief Brand Officer', compassQuestion: 'If the founder were standing beside me, would I approve this without hesitation?', discipline: 'Identity' },
      { id: 'ec-3', executive: 'Chief Experience Officer', compassQuestion: 'If someone experienced our company for the very first time today, would they understand who we are without us ever having to explain it?', discipline: 'Experience' },
      { id: 'ec-4', executive: 'Brand Architect', compassQuestion: 'Does this strengthen meaning — or merely add visual noise?', discipline: 'Brand Blueprint' },
      { id: 'ec-5', executive: 'Experience Architect', compassQuestion: 'Would a first-time customer feel cared for — or processed?', discipline: 'Journey Design' },
      { id: 'ec-6', executive: 'Digital Architect', compassQuestion: 'Does this technology feel human — or merely efficient?', discipline: 'Digital Ecosystem' },
      { id: 'ec-7', executive: 'Growth Architect', compassQuestion: 'Are we building relationships — or merely acquiring numbers?', discipline: 'Sustainable Growth' },
      { id: 'ec-8', executive: 'Business Architect', compassQuestion: 'Does this business model compound trust over time?', discipline: 'Strategic Foundation' },
    ],
    excellenceDefinitions: [
      { id: 'ex-1', executive: 'Chief Brand Officer', exceptional: 'Identity unmistakable · trust rising · zero drift alerts', average: 'Consistent but undifferentiated · minor alignment gaps', warningSigns: 'Generic copy creeping in · creator partnerships off-brand', failureIndicators: 'Identity confusion · founder would not recognize the brand' },
      { id: 'ex-2', executive: 'Chief Experience Officer', exceptional: 'Customers feel understood · friction proactively resolved · hospitality celebrated', average: 'Functional journeys · reactive support · acceptable NPS', warningSigns: 'Onboarding drop-off · support response inconsistency', failureIndicators: 'Trust erosion · customers feel processed not cared for' },
      { id: 'ex-3', executive: 'Chief of Staff', exceptional: 'Every recommendation aligned · council debates productive · founder briefings decisive', average: 'Coordination functional · occasional misalignment', warningSigns: 'Duplicate recommendations · unresolved council debates', failureIndicators: 'Executive silos · founder overwhelmed with noise' },
    ],
    learningSources: [
      { id: 'ls-1', source: 'Organizational Memory', contribution: 'Motherboard · institutional lessons · decision history', status: 'active' },
      { id: 'ls-2', source: 'Executive Council', contribution: 'Cross-executive debates · shared wisdom · healthy disagreement', status: 'active' },
      { id: 'ls-3', source: 'Knowledge Graph', contribution: 'Relationship lineage · organizational connections', status: 'active' },
      { id: 'ls-4', source: 'Relationship Engine', contribution: 'Trust patterns · relationship health signals', status: 'active' },
      { id: 'ls-5', source: 'Reader Graph', contribution: 'Customer journey outcomes · engagement patterns', status: 'growing' },
      { id: 'ls-6', source: 'Campaign Outcomes', contribution: 'What worked · what failed · why', status: 'active' },
      { id: 'ls-7', source: 'Leadership Reflections', contribution: 'Founder preferences · approval history · evolving wisdom', status: 'growing' },
    ],
    manifestoInheritance: [
      { id: 'mi-1', executiveTitle: 'Chief Brand Officer', inheritsFramework: true, readiness: 'active', customizedManifesto: true },
      { id: 'mi-2', executiveTitle: 'Chief Experience Officer', inheritsFramework: true, readiness: 'active', customizedManifesto: true },
      { id: 'mi-3', executiveTitle: 'Chief Digital Officer', inheritsFramework: true, readiness: 'architecture-ready', customizedManifesto: false },
      { id: 'mi-4', executiveTitle: 'Chief Growth Officer', inheritsFramework: true, readiness: 'architecture-ready', customizedManifesto: false },
      { id: 'mi-5', executiveTitle: 'Chief Financial Officer', inheritsFramework: true, readiness: 'planned', customizedManifesto: false },
      { id: 'mi-6', executiveTitle: 'Chief Operating Officer', inheritsFramework: true, readiness: 'planned', customizedManifesto: false },
      { id: 'mi-7', executiveTitle: 'Chief Legal Officer', inheritsFramework: true, readiness: 'future', customizedManifesto: false },
      { id: 'mi-8', executiveTitle: 'Chief People Officer', inheritsFramework: true, readiness: 'future', customizedManifesto: false },
      { id: 'mi-9', executiveTitle: 'Chief Technology Officer', inheritsFramework: true, readiness: 'planned', customizedManifesto: false },
      { id: 'mi-10', executiveTitle: 'Chief Research Officer', inheritsFramework: true, readiness: 'future', customizedManifesto: false },
    ],
    recommendedNextSteps: [
      'Complete customized manifestos for CDO and CGO architecture-ready roles',
      'Sync executive compasses to CBO and CEO daily briefing panels',
      'Validate all recommendations against non-negotiables before council escalation',
      'Contribute onboarding friction lesson to organizational memory via Knowledge Graph',
    ],
    futureOpportunities: [
      'Automatic manifesto inheritance validation when new executives launch',
      'Executive wisdom score synced to Company Genome maturity',
      'Cross-portfolio manifesto framework for holding companies',
      'Compass-guided recommendation format enforcement across all executives',
    ],
  };
}

export function bootstrapLeadershipManifestoFrameworkPlatform(): void {
  bootstrapLeadershipManifestoFrameworkStore(buildLeadershipManifestoFrameworkSeed());
}
