import { bootstrapOrganizationalDelegationStore } from './store';
import type { OrganizationalDelegationStore } from './types';

export function buildOrganizationalDelegationSeed(): Partial<OrganizationalDelegationStore> {
  return {
    companyName: 'NDXBOOK',
    activeWorkspaceId: 'ndxbook',
    dashboard: {
      summary:
        'ORGANIZATIONAL DELEGATION ENGINE V1.0 — founders delegate outcomes · the organization determines how they are achieved.',
      activeDelegations: 5,
      completedOutcomes: 12,
      pendingFounderDecisions: 2,
      organizationalConfidencePct: 87,
      workflowHealthPct: 90,
      executiveAccountabilityPct: 88,
    },
    delegationTypes: [
      { id: 'dt-1', type: 'Strategic objectives', description: 'Long-term organizational direction aligned with founder promise' },
      { id: 'dt-2', type: 'Growth initiatives', description: 'Relationship-driven acquisition · community · creator ecosystem' },
      { id: 'dt-3', type: 'Customer experiences', description: 'Journey improvements · onboarding · retention · belonging' },
      { id: 'dt-4', type: 'Campaigns', description: 'Editorial distribution · community engagement · brand-aligned GTM' },
      { id: 'dt-5', type: 'Creative work', description: 'Stat-forward identity · Writing DNA quality · brand consistency' },
      { id: 'dt-6', type: 'Operations', description: 'Routine execution · reporting · workflow orchestration' },
      { id: 'dt-7', type: 'Long-term missions', description: 'Multi-quarter outcomes · organizational improvements' },
    ],
    outcomeDelegations: [
      {
        id: 'od-1',
        outcome: 'Reduce customer onboarding friction',
        insteadOf: 'Redesign onboarding screens',
        status: 'in-progress',
        priority: 'high',
        successMetrics: ['Onboarding score > 85', 'Step 3 drop-off reduced 20%', 'Trust-before-scale gate cleared'],
      },
      {
        id: 'od-2',
        outcome: 'Increase community engagement',
        insteadOf: 'Create ten social posts',
        status: 'in-progress',
        priority: 'high',
        successMetrics: ['Reader advocacy pathway +15%', 'Community spotlight participation', 'Organic share rate'],
      },
      {
        id: 'od-3',
        outcome: 'Launch relationship-driven GTM to 100K engaged readers',
        insteadOf: 'Run paid acquisition campaign',
        status: 'planning',
        priority: 'high',
        successMetrics: ['Relationship metrics over vanity', 'Retention stable', 'Brand integrity preserved'],
      },
      {
        id: 'od-4',
        outcome: 'Establish creator marketplace ecosystem',
        insteadOf: 'Onboard 10 creators manually',
        status: 'in-progress',
        priority: 'medium',
        successMetrics: ['10 curated creators live', 'Writing DNA gates enforced', 'Revenue share model validated'],
      },
      {
        id: 'od-5',
        outcome: 'Strengthen editorial identity consistency',
        insteadOf: 'Update brand guidelines document',
        status: 'review',
        priority: 'medium',
        successMetrics: ['Stat-forward consistency score', 'Zero generic template usage', 'CBO approval on all GTM creative'],
      },
    ],
    executiveAssignments: [
      {
        id: 'ea-1',
        delegationId: 'od-1',
        owner: 'Chief Experience Officer',
        supporting: ['Chief Digital Officer', 'Chief Technology Officer'],
        architects: ['Experience Architect', 'Digital Architect'],
        workflows: ['Onboarding simplification', 'Auth refactor', 'Journey intelligence'],
        rationale: 'CEO owns trust-first customer journey · CDO implements · CTO validates engineering scope',
      },
      {
        id: 'ea-2',
        delegationId: 'od-2',
        owner: 'Chief Growth Officer',
        supporting: ['Chief Brand Officer', 'Chief Experience Officer'],
        architects: ['Growth Architect', 'Brand Architect'],
        workflows: ['Community spotlight program', 'Reader advocacy pathway', 'Newsletter engagement'],
        rationale: 'CGO owns sustainable engagement · CBO ensures brand alignment · CEO validates touchpoints',
      },
      {
        id: 'ea-3',
        delegationId: 'od-3',
        owner: 'Chief Growth Officer',
        supporting: ['Chief Brand Officer', 'Chief Experience Officer', 'Chief Digital Officer', 'Chief Technology Officer'],
        architects: ['Growth Architect', 'Brand Architect', 'Experience Architect'],
        workflows: ['Phased GTM pilot', 'Relationship metrics dashboard', 'Council-approved sequencing'],
        rationale: 'CGO leads GTM · full C-suite for trust-before-scale prerequisite · council synthesis applied',
      },
    ],
    delegationPlans: [
      {
        id: 'dp-1',
        delegation: 'Reduce customer onboarding friction',
        executiveStrategy: 'CEO leads journey simplification · CDO implements UX · CTO resolves auth debt · CoS coordinates',
        roadmap: 'Week 1-2: friction audit · Week 3-4: simplification · Week 5: validation · Week 6: GTM gate review',
        dependencies: ['CTO auth refactor', 'CEO journey intelligence', 'OAF Level 3 approval for customer workflows'],
        timeline: '6 weeks · founder review at Week 4',
        risks: ['Scope creep on features', 'Premature GTM pressure'],
        successMetrics: ['Onboarding score > 85', 'Step 3 drop-off -20%', 'Retention stable'],
        confidence: 86,
        alternatives: 'Minimal viable simplification vs full journey redesign',
      },
      {
        id: 'dp-2',
        delegation: 'Increase community engagement',
        executiveStrategy: 'CGO develops engagement strategy · CBO refines messaging · CEO improves touchpoints · CoS coordinates',
        roadmap: 'Week 1: reader spotlight design · Week 2: pilot launch · Week 3-4: measure advocacy pathway',
        dependencies: ['Brand Architect quality gates', 'Reader Graph signals', 'Relationship Engine nurture workflows'],
        timeline: '4 weeks · automatic execution below threshold',
        risks: ['Community fatigue', 'Brand dilution from generic engagement tactics'],
        successMetrics: ['Advocacy +15%', 'Organic share rate up', 'Belonging score stable'],
        confidence: 84,
        alternatives: 'Reader spotlight vs creator co-creation program',
      },
    ],
    collaborativeExecution: [
      { id: 'ce-1', delegation: 'Onboarding friction reduction', executive: 'Chief Experience Officer', contribution: 'Journey audit · friction heat map · simplification proposal', status: 'active' },
      { id: 'ce-2', delegation: 'Onboarding friction reduction', executive: 'Chief Digital Officer', contribution: 'UX implementation plan · editorial mode consistency', status: 'active' },
      { id: 'ce-3', delegation: 'Onboarding friction reduction', executive: 'Chief Technology Officer', contribution: 'Auth refactor scope · deployment validation', status: 'pending' },
      { id: 'ce-4', delegation: 'Community engagement', executive: 'Chief Growth Officer', contribution: 'Engagement strategy · reader spotlight program design', status: 'active' },
      { id: 'ce-5', delegation: 'Community engagement', executive: 'Chief Brand Officer', contribution: 'Stat-forward messaging refinement · creative validation', status: 'active' },
      { id: 'ce-6', delegation: 'Community engagement', executive: 'Chief of Staff', contribution: 'Execution coordination · founder briefing preparation', status: 'active' },
    ],
    delegationGovernance: [
      { id: 'dg-1', domain: 'Automatic execution', rule: 'Inherits OAF Level 3 workflows · customer nurture automatic · GTM requires founder', threshold: 'High-risk delegations always founder review' },
      { id: 'dg-2', domain: 'Approval thresholds', rule: 'CoS soft approval below $500 · founder above · partnerships never automatic', threshold: '$500 operational spend' },
      { id: 'dg-3', domain: 'Risk thresholds', rule: 'Paid acquisition · mission changes · executive appointments · always founder', threshold: 'Strategic risk = founder authority' },
      { id: 'dg-4', domain: 'Publishing authority', rule: 'Routine newsletter automatic · new editorial formats founder review', threshold: 'New format = founder' },
      { id: 'dg-5', domain: 'Customer interaction', rule: 'Relationship nurturing automatic · partnership outreach founder', threshold: 'External partnership = founder' },
    ],
    delegationVisibility: [
      {
        id: 'dv-1',
        delegation: 'Reduce customer onboarding friction',
        owner: 'Chief Experience Officer',
        progressPct: 42,
        dependencies: 'CTO auth refactor · CDO UX implementation',
        pendingApprovals: 1,
        milestones: ['Friction audit complete', 'Simplification design in progress'],
        expectedCompletion: '2026-08-15',
        organizationalImpact: 'Unlocks trust-before-scale GTM · council prerequisite',
      },
      {
        id: 'dv-2',
        delegation: 'Increase community engagement',
        owner: 'Chief Growth Officer',
        progressPct: 58,
        dependencies: 'Reader Graph signals · Brand Architect gates',
        pendingApprovals: 0,
        milestones: ['Reader spotlight designed', 'Pilot launched'],
        expectedCompletion: '2026-07-25',
        organizationalImpact: 'Advocacy pathway · organic compounding · relationship-driven growth',
      },
      {
        id: 'dv-3',
        delegation: '100K relationship-driven GTM',
        owner: 'Chief Growth Officer',
        progressPct: 15,
        dependencies: 'Onboarding score > 85 · council approval · phased pilot plan',
        pendingApprovals: 1,
        milestones: ['Council synthesis complete', 'Awaiting onboarding gate'],
        expectedCompletion: '2026-09-01',
        organizationalImpact: 'Major growth outcome · founder decision pending',
      },
    ],
    delegationLearning: [
      {
        id: 'dl-1',
        delegation: 'Block paid acquisition test',
        results: 'Vanity metrics avoided · brand integrity preserved · council precedent validated',
        lessons: ['Relationship-first GTM outperforms paid hacks', 'Trust engine correctly identified risk'],
        collaboration: 'CGO · CBO · CoS · Executive Council',
        futureRecommendations: 'Encode paid acquisition block in delegation governance defaults',
      },
      {
        id: 'dl-2',
        delegation: 'First 12K organic readers milestone',
        results: 'Relationship-driven acquisition validated · no paid hacks · advocacy emerging',
        lessons: ['Stat-forward hooks consistently outperform generic templates', 'Organic compounding works'],
        collaboration: 'CGO · CBO · CEO · Growth Architect',
        futureRecommendations: 'Apply organic playbook to community engagement delegation',
      },
    ],
    executiveAccountability: [
      { id: 'acc-1', executive: 'Chief Growth Officer', quality: 91, timeliness: 87, collaboration: 92, customerImpact: 89, knowledgeContribution: 88 },
      { id: 'acc-2', executive: 'Chief Experience Officer', quality: 94, timeliness: 85, collaboration: 90, customerImpact: 95, knowledgeContribution: 87 },
      { id: 'acc-3', executive: 'Chief Brand Officer', quality: 93, timeliness: 90, collaboration: 91, customerImpact: 88, knowledgeContribution: 92 },
      { id: 'acc-4', executive: 'Chief of Staff', quality: 90, timeliness: 92, collaboration: 94, customerImpact: 86, knowledgeContribution: 89 },
      { id: 'acc-5', executive: 'Chief Digital Officer', quality: 88, timeliness: 86, collaboration: 87, customerImpact: 84, knowledgeContribution: 85 },
    ],
    recommendedDelegations: [
      { id: 'rd-1', outcome: 'Design membership tier around editorial depth rewards', rationale: 'OI and council identify subscription opportunity · not paywall anxiety', confidence: 82 },
      { id: 'rd-2', outcome: 'International expansion research for English-first editorial markets', rationale: 'Growth evolution recommendation · low-risk research delegation', confidence: 76 },
    ],
    recommendedNextSteps: [
      'Founder review onboarding friction delegation plan at Week 4 checkpoint',
      'Approve community engagement delegation for automatic execution',
      'Feed completed delegation learnings to Organizational Intelligence',
      'Calibrate executive accountability metrics after Q2 outcomes',
    ],
    futureOpportunities: [
      'Natural language outcome delegation from founder intent',
      'Live delegation visibility with executive discussion threads',
      'Automatic executive assignment based on genome and historical accountability',
      'Delegation inheritance packages for organizational succession',
    ],
  };
}

export function bootstrapOrganizationalDelegationPlatform(): void {
  bootstrapOrganizationalDelegationStore(buildOrganizationalDelegationSeed());
}
