import type { ExecutionMode, ImplementationCategory, ImplementationTask } from '../schemas/implementation-task';
import { IMPLEMENTATION_ORCHESTRATOR_VERSION } from '../schemas/implementation-task';

export const CANONICAL_PIPELINE_TASK_IDS = [
  'department-identity-isolation',
  'architectural-dna-registry',
  'studio-world-style-bible',
  'department-bible-registry',
  'studio-world-constitution',
  'golden-prompt-registry',
  'canonical-founder-render',
  'cds-manufacturing',
  'construction-mode-pipeline',
  'studio-world-publishing',
  'implementation-orchestrator',
  'mod-marketplace-runtime',
] as const;

export type CanonicalPipelineTaskId = (typeof CANONICAL_PIPELINE_TASK_IDS)[number];

const DEFAULT_EXECUTION_MODE: Partial<Record<ImplementationCategory, ExecutionMode>> = {
  architecture: 'MANUAL',
  schema: 'MANUAL',
  permissions: 'MANUAL',
  'ai-routing': 'MANUAL',
  documentation: 'AUTONOMOUS',
  tests: 'AUTONOMOUS',
  diagnostics: 'AUTONOMOUS',
  refactor: 'ASSISTED',
  governance: 'MANUAL',
  marketplace: 'MANUAL',
  billing: 'MANUAL',
  licensing: 'MANUAL',
  pipeline: 'ASSISTED',
  infrastructure: 'ASSISTED',
};

const FOUNDER_GATE_CATEGORIES: ImplementationCategory[] = [
  'architecture',
  'schema',
  'permissions',
  'marketplace',
  'billing',
  'licensing',
  'governance',
  'ai-routing',
];

function task(
  partial: Omit<ImplementationTask, 'taskVersion' | 'history' | 'createdDate' | 'updatedDate' | 'founderApprovalRequired'> & {
    status: ImplementationTask['status'];
    currentCommit?: string;
    deployment?: string;
    founderApproved?: boolean;
    founderApprovalRequired?: boolean;
  }
): ImplementationTask {
  const now = '2026-07-13T12:00:00.000Z';
  return {
    taskVersion: IMPLEMENTATION_ORCHESTRATOR_VERSION,
    createdDate: now,
    updatedDate: now,
    history: [{ from: null, to: partial.status, at: now, reason: 'seeded', commitSha: partial.currentCommit, deploymentSha: partial.deployment }],
    founderApprovalRequired: partial.founderApprovalRequired ?? FOUNDER_GATE_CATEGORIES.includes(partial.category),
    ...partial,
    executionMode: partial.executionMode ?? DEFAULT_EXECUTION_MODE[partial.category] ?? 'ASSISTED',
  };
}

/** Canonical Studio World implementation graph — living queue seed. */
export const CANONICAL_IMPLEMENTATION_TASKS: ImplementationTask[] = [
  task({
    taskId: 'department-identity-isolation',
    title: 'Department Identity Isolation',
    description: 'Eliminate cross-department render contamination — each canonical department owns distinct architecture.',
    category: 'architecture',
    priority: 100,
    status: 'DEPLOYED',
    blockedBy: [],
    unlocks: ['architectural-dna-registry'],
    dependencies: [],
    implementationSpec: 'Per-department blueprints, fingerprints, distinctness validator, founder render isolation.',
    acceptanceCriteria: ['Every department renders unique architecture', 'No ReceptionShell contamination'],
    verificationCriteria: ['department-render-isolation tests pass', 'Production build passes'],
    requiredTests: ['department-render-isolation.test.ts'],
    estimatedEffort: 'sprint',
    estimatedCost: 'canonical-infrastructure',
    executionMode: 'MANUAL',
    owner: 'Composer',
    currentCommit: 'def341fa9',
    deployment: 'def341fa9',
    founderApproved: true,
  }),
  task({
    taskId: 'architectural-dna-registry',
    title: 'Architectural DNA Registry',
    description: 'Governed Architectural DNA + Golden Reference Library + Founder Render Prompt Compiler.',
    category: 'architecture',
    priority: 95,
    status: 'DEPLOYED',
    blockedBy: [],
    unlocks: ['golden-prompt-registry', 'studio-world-style-bible'],
    dependencies: ['department-identity-isolation'],
    implementationSpec: 'dna-registry, golden-reference-library, founder-render-prompt-compiler per department.',
    acceptanceCriteria: ['Every department owns DNA profile', 'Prompt compiler replaces handwritten prompts'],
    verificationCriteria: ['architectural-dna.test.ts passes'],
    requiredTests: ['architectural-dna.test.ts'],
    estimatedEffort: 'sprint',
    estimatedCost: 'canonical-infrastructure',
    executionMode: 'MANUAL',
    owner: 'Composer',
    currentCommit: 'e0148f3ec',
    deployment: 'e0148f3ec',
    founderApproved: true,
  }),
  task({
    taskId: 'studio-world-style-bible',
    title: 'Studio World Style Bible',
    description: 'Universal visual language — Command Dock, Workbench, typography placeholders, cohesion validator.',
    category: 'architecture',
    priority: 94,
    status: 'DEPLOYED',
    blockedBy: [],
    unlocks: ['department-bible-registry'],
    dependencies: ['architectural-dna-registry'],
    implementationSpec: 'style-bible registry, design tokens, world cohesion validator, Experience Lab guardian.',
    acceptanceCriteria: ['Style Bible is highest visual authority', 'AI never renders production UI text'],
    verificationCriteria: ['studio-world-style.test.ts passes'],
    requiredTests: ['studio-world-style.test.ts'],
    estimatedEffort: 'sprint',
    estimatedCost: 'canonical-infrastructure',
    executionMode: 'MANUAL',
    owner: 'Composer',
    currentCommit: 'e806fc9d8',
    deployment: 'e806fc9d8',
    founderApproved: true,
  }),
  task({
    taskId: 'department-bible-registry',
    title: 'Department Bible Registry',
    description: 'Operating manual for every canonical department — relationships, permissions, lifecycle, compiler.',
    category: 'governance',
    priority: 93,
    status: 'DEPLOYED',
    blockedBy: [],
    unlocks: ['studio-world-constitution', 'implementation-orchestrator'],
    dependencies: ['studio-world-style-bible'],
    implementationSpec: 'bible-registry, relationship graph, knowledge graph, department compiler, encyclopedia.',
    acceptanceCriteria: ['25/25 departments own one Bible', 'Department Compiler succeeds for all'],
    verificationCriteria: ['department-bible.test.ts passes'],
    requiredTests: ['department-bible.test.ts'],
    estimatedEffort: 'sprint',
    estimatedCost: 'canonical-infrastructure',
    executionMode: 'MANUAL',
    owner: 'Composer',
    currentCommit: 'be4501c4e',
    deployment: 'be4501c4e',
    founderApproved: true,
  }),
  task({
    taskId: 'studio-world-constitution',
    title: 'Studio World Constitution',
    description: 'Supreme governing laws — 8 articles, constitutional gate, immutable audit.',
    category: 'governance',
    priority: 92,
    status: 'DEPLOYED',
    blockedBy: [],
    unlocks: ['implementation-orchestrator'],
    dependencies: ['department-bible-registry'],
    implementationSpec: 'supreme-articles, constitutional-gate, immutable-audit, hierarchy enforcement.',
    acceptanceCriteria: ['Constitution supreme above Style Bible', 'All departments pass constitutional gate'],
    verificationCriteria: ['studio-world-constitution-supreme.test.ts passes'],
    requiredTests: ['studio-world-constitution-supreme.test.ts'],
    estimatedEffort: 'sprint',
    estimatedCost: 'canonical-infrastructure',
    executionMode: 'MANUAL',
    owner: 'Composer',
    currentCommit: '1026b6c35',
    deployment: '1026b6c35',
    founderApproved: true,
  }),
  task({
    taskId: 'golden-prompt-registry',
    title: 'Golden Prompt Registry',
    description: 'Golden Reference Library integration with Prompt Compiler for every department.',
    category: 'pipeline',
    priority: 88,
    status: 'DEPLOYED',
    blockedBy: [],
    unlocks: ['canonical-founder-render'],
    dependencies: ['architectural-dna-registry'],
    implementationSpec: 'golden-reference-library packs wired into founder-render-prompt-compiler.',
    acceptanceCriteria: ['Every department owns golden reference pack'],
    verificationCriteria: ['architectural-dna golden reference tests pass'],
    requiredTests: ['architectural-dna.test.ts'],
    estimatedEffort: 'sprint',
    estimatedCost: 'canonical-infrastructure',
    executionMode: 'ASSISTED',
    owner: 'Composer',
    currentCommit: 'e0148f3ec',
    deployment: 'e0148f3ec',
    founderApproved: true,
  }),
  task({
    taskId: 'canonical-founder-render',
    title: 'Canonical Founder Render',
    description: 'Governed founder render generation via FAL with constitutional + DNA compiled prompts.',
    category: 'pipeline',
    priority: 87,
    status: 'DEPLOYED',
    blockedBy: [],
    unlocks: ['cds-manufacturing'],
    dependencies: ['golden-prompt-registry', 'studio-world-constitution'],
    implementationSpec: 'founderRenderGeneration bundled for Vercel, canonical queue dispatch.',
    acceptanceCriteria: ['Founder Preview compiles without module errors', 'Distinctness validator passes'],
    verificationCriteria: ['Production founder render succeeds on device'],
    requiredTests: ['architectural-dna.test.ts', 'department-bible.test.ts'],
    estimatedEffort: 'sprint',
    estimatedCost: 'fal-generation',
    executionMode: 'MANUAL',
    owner: 'Composer',
    currentCommit: '5b295c772',
    deployment: '5b295c772',
    founderApproved: true,
  }),
  task({
    taskId: 'cds-manufacturing',
    title: 'CD Studio Manufacturing',
    description: 'Creative Director Studio manufactures approved architecture — asset production pipeline.',
    category: 'pipeline',
    priority: 80,
    status: 'READY',
    blockedBy: [],
    unlocks: ['construction-mode-pipeline'],
    dependencies: ['canonical-founder-render'],
    implementationSpec: 'CDS handoff from approved founder render, asset manufacturing graph.',
    acceptanceCriteria: ['CDS receives approved handoff only', 'No canonical architecture invention'],
    verificationCriteria: ['cds-canonical-handoff validates'],
    requiredTests: ['canonical-department-generator.test.ts'],
    estimatedEffort: 'sprint',
    estimatedCost: 'production-pipeline',
    executionMode: 'MANUAL',
    owner: 'Composer',
    founderApprovalRequired: true,
    founderApproved: true,
  }),
  task({
    taskId: 'construction-mode-pipeline',
    title: 'Construction Mode Pipeline',
    description: 'Assembly and manufacturing validation for published departments.',
    category: 'pipeline',
    priority: 75,
    status: 'BLOCKED',
    blockedBy: ['cds-manufacturing'],
    unlocks: ['studio-world-publishing'],
    dependencies: ['cds-manufacturing'],
    implementationSpec: 'construction-mode assembly worker, manufacturing validator, quality guard handoff.',
    acceptanceCriteria: ['Construction plan assembles from approved blueprint'],
    verificationCriteria: ['Construction lifecycle transitions validate'],
    requiredTests: ['canonical-department-generator.test.ts'],
    estimatedEffort: 'sprint',
    estimatedCost: 'production-pipeline',
    executionMode: 'MANUAL',
    owner: 'Composer',
    founderApprovalRequired: true,
  }),
  task({
    taskId: 'studio-world-publishing',
    title: 'Studio World Publishing',
    description: 'Publish canonical departments to Studio World Registry after inspection.',
    category: 'governance',
    priority: 70,
    status: 'BLOCKED',
    blockedBy: ['construction-mode-pipeline'],
    unlocks: [],
    dependencies: ['construction-mode-pipeline'],
    implementationSpec: 'immune-system audit, quality guard, registry publish.',
    acceptanceCriteria: ['Published departments appear in registry', 'Lifecycle reaches PUBLISHED'],
    verificationCriteria: ['Registry lists all published departments'],
    requiredTests: ['canonical-department-generator.test.ts'],
    estimatedEffort: 'sprint',
    estimatedCost: 'canonical-infrastructure',
    executionMode: 'MANUAL',
    owner: 'Composer',
    founderApprovalRequired: true,
  }),
  task({
    taskId: 'implementation-orchestrator',
    title: 'Implementation Orchestrator',
    description: 'Self-managing implementation queue with dependency graph, blocker engine, and autonomous dispatch.',
    category: 'infrastructure',
    priority: 99,
    status: 'DEPLOYED',
    blockedBy: [],
    unlocks: ['mod-marketplace-runtime'],
    dependencies: ['department-bible-registry', 'studio-world-constitution'],
    implementationSpec: 'implementation-orchestrator engine, dependency graph, queue dashboard, Experience Lab panel.',
    acceptanceCriteria: ['Tasks persist and resolve dependencies', 'Blocked tasks auto-unblock', 'Critical path computes'],
    verificationCriteria: ['implementation-orchestrator.test.ts passes', 'Production build passes'],
    requiredTests: ['implementation-orchestrator.test.ts'],
    estimatedEffort: 'sprint',
    estimatedCost: 'canonical-infrastructure',
    executionMode: 'ASSISTED',
    owner: 'Composer',
  }),
  task({
    taskId: 'mod-marketplace-runtime',
    title: 'Mod Marketplace Runtime',
    description: 'Live marketplace mod purchase/install API + Supabase sync for founder mods.',
    category: 'marketplace',
    priority: 60,
    status: 'BLOCKED',
    blockedBy: ['implementation-orchestrator'],
    unlocks: [],
    dependencies: ['implementation-orchestrator', 'studio-world-publishing'],
    implementationSpec: 'B1-ModMarketplace-Runtime — production API wiring, City Council certification gate.',
    acceptanceCriteria: ['Founders can purchase and install mods', 'IP lineage preserved'],
    verificationCriteria: ['Marketplace E2E on production'],
    requiredTests: ['mod-certification tests'],
    estimatedEffort: 'sprint',
    estimatedCost: 'marketplace-ops',
    executionMode: 'MANUAL',
    owner: 'Composer',
    founderApprovalRequired: true,
  }),
];

export function getCanonicalTaskRegistry(): Record<string, ImplementationTask> {
  return Object.fromEntries(CANONICAL_IMPLEMENTATION_TASKS.map((t) => [t.taskId, { ...t }]));
}
