import { aioAppConfig } from '../config/appConfig';

const BASE = aioAppConfig.routes.base;

export const aioPaths = {
  home: BASE,
  portal: `${BASE}/portal`,
  services: `${BASE}/services`,
  permitting: `${BASE}/services/permitting`,
  businessFormation: `${BASE}/services/business-formation`,
  insurance: `${BASE}/services/insurance`,
  dispatching: `${BASE}/services/dispatching`,
  factoring: `${BASE}/services/factoring`,
  brokerage: `${BASE}/services/brokerage`,
  portalFactoring: `${BASE}/portal/factoring`,
  portalFactoringApplication: `${BASE}/portal/factoring/application`,
  portalFactoringReady: `${BASE}/portal/factoring/ready`,
  portalFactoringSubmission: (id: string) => `${BASE}/portal/factoring/submissions/${id}`,
  portalFactoringHistory: `${BASE}/portal/factoring/history`,
  portalFreightInvoice: (id: string) => `${BASE}/portal/factoring/invoices/${id}`,
  officeFactoring: `${BASE}/office/factoring`,
  officeFactoringSubmissions: `${BASE}/office/factoring/submissions`,
  officeFactoringSubmission: (id: string) => `${BASE}/office/factoring/submissions/${id}`,
  officeFactoringClients: `${BASE}/office/factoring/clients`,
  officeFactoringClient: (id: string) => `${BASE}/office/factoring/clients/${id}`,
  officeFactoringProviders: `${BASE}/office/factoring/providers`,
  shipper: `${BASE}/shipper`,
  shipperOnboarding: `${BASE}/shipper/onboarding`,
  shipperShipments: `${BASE}/shipper/shipments`,
  shipperShipmentNew: `${BASE}/shipper/shipments/new`,
  shipperShipment: (id: string) => `${BASE}/shipper/shipments/${id}`,
  shipperQuotes: `${BASE}/shipper/quotes`,
  shipperQuote: (id: string) => `${BASE}/shipper/quotes/${id}`,
  shipperBilling: `${BASE}/shipper/billing`,
  shipperInvoice: (id: string) => `${BASE}/shipper/billing/${id}`,
  portalBrokerage: `${BASE}/portal/brokerage`,
  portalBrokerageOffers: `${BASE}/portal/brokerage/offers`,
  portalBrokerageLoad: (id: string) => `${BASE}/portal/brokerage/loads/${id}`,
  portalBrokeragePayments: `${BASE}/portal/brokerage/payments`,
  officeBrokerageReadiness: `${BASE}/office/brokerage/readiness`,
  officeBrokerageShippers: `${BASE}/office/brokerage/shippers`,
  officeBrokerageShipper: (id: string) => `${BASE}/office/brokerage/shippers/${id}`,
  officeBrokerageLoads: `${BASE}/office/brokerage/loads`,
  officeBrokerageLoad: (id: string) => `${BASE}/office/brokerage/loads/${id}`,
  officeBrokerageCoverage: `${BASE}/office/brokerage/coverage`,
  officeBrokerageCarriers: `${BASE}/office/brokerage/carriers`,
  officeBrokerageCarrier: (id: string) => `${BASE}/office/brokerage/carriers/${id}`,
  officeBrokerageFinance: `${BASE}/office/brokerage/finance`,
  about: `${BASE}/about`,
  contact: `${BASE}/contact`,
  roadmap: `${BASE}/roadmap`,
  getStarted: `${BASE}/get-started`,
  roadmapResults: `${BASE}/roadmap/results`,
  servicePlan: `${BASE}/service-plan`,
  requestSubmit: `${BASE}/request/submit`,
  industries: `${BASE}/about#industries`,
  resources: `${BASE}/about#resources`,
  serviceSlug: (slug: string) => `${BASE}/services/${slug}`,
  portalRequest: (requestId: string) => `${BASE}/portal/requests/${requestId}`,
  requestConfirmation: (requestId: string) => `${BASE}/request/confirmation/${requestId}`,
  portalOnboarding: `${BASE}/portal/onboarding`,
  roadReady: `${BASE}/portal/road-ready`,
  portalFleet: `${BASE}/portal/fleet`,
  portalVehicle: (id: string) => `${BASE}/portal/fleet/vehicles/${id}`,
  portalVault: `${BASE}/portal/vault`,
  portalVaultDocument: (id: string) => `${BASE}/portal/vault/${id}`,
  portalCalendar: `${BASE}/portal/calendar`,
  portalRenewals: `${BASE}/portal/renewals`,
  portalNotifications: `${BASE}/portal/notifications`,
  portalNotificationSettings: `${BASE}/portal/settings/notifications`,
  portalSettings: `${BASE}/portal/settings`,
  portalQuotes: `${BASE}/portal/quotes`,
  portalQuote: (id: string) => `${BASE}/portal/quotes/${id}`,
  portalBilling: `${BASE}/portal/billing`,
  portalInvoice: (id: string) => `${BASE}/portal/billing/invoices/${id}`,
  portalPay: (id: string) => `${BASE}/portal/billing/pay/${id}`,
  portalReceipt: (id: string) => `${BASE}/portal/billing/receipts/${id}`,
  portalDispatch: `${BASE}/portal/dispatch`,
  portalDispatchOnboarding: `${BASE}/portal/dispatch/onboarding`,
  portalDispatchLoads: `${BASE}/portal/dispatch/loads`,
  portalDispatchLoad: (id: string) => `${BASE}/portal/dispatch/loads/${id}`,
  portalDispatchHistory: `${BASE}/portal/dispatch/history`,
  officeDispatch: `${BASE}/office/dispatch`,
  officeDispatchLoads: `${BASE}/office/dispatch/loads`,
  officeDispatchLoadNew: `${BASE}/office/dispatch/loads/new`,
  officeDispatchLoad: (id: string) => `${BASE}/office/dispatch/loads/${id}`,
  /** @deprecated use officeDispatchLoad */
  officeLoad: (id: string) => `${BASE}/office/dispatch/loads/${id}`,
  officeDispatchClients: `${BASE}/office/dispatch/clients`,
  officeDispatchClient: (id: string) => `${BASE}/office/dispatch/clients/${id}`,
  officeDispatchBrokers: `${BASE}/office/dispatch/brokers`,
  officeQuotes: `${BASE}/office/quotes`,
  officeQuote: (id: string) => `${BASE}/office/quotes/${id}`,
  officeBilling: `${BASE}/office/billing`,
  officeInvoice: (id: string) => `${BASE}/office/invoices/${id}`,
  officePricingSettings: `${BASE}/office/settings/pricing`,
  officeRenewals: `${BASE}/office/renewals`,
  office: `${BASE}/office`,
  officeClients: `${BASE}/office/clients`,
  officeClient: (id: string) => `${BASE}/office/clients/${id}`,
  officeRequests: `${BASE}/office/requests`,
  officeRequest: (id: string) => `${BASE}/office/requests/${id}`,
  officeTasks: `${BASE}/office/tasks`,
  officeDeadlines: `${BASE}/office/deadlines`,
  officeDocuments: `${BASE}/office/documents`,
  officeMessages: `${BASE}/office/messages`,
  officePermitting: `${BASE}/office/permitting`,
  officeFormation: `${BASE}/office/business-formation`,
  officeInsurance: `${BASE}/office/insurance`,
  officeBrokerage: `${BASE}/office/brokerage`,
  officeShipment: (id: string) => `${BASE}/office/brokerage/shipments/${id}`,
  officeInvoices: `${BASE}/office/invoices`,
  officePayments: `${BASE}/office/payments`,
  officeTeam: `${BASE}/office/team`,
  officeReports: `${BASE}/office/reports`,
  officeRoadReady: `${BASE}/office/road-ready`,
  officeClientRoadReady: (id: string) => `${BASE}/office/clients/${id}/road-ready`,
  login: `${BASE}/login`,
  signUp: `${BASE}/sign-up`,
  forgotPassword: `${BASE}/forgot-password`,
  resetPassword: `${BASE}/reset-password`,
  verifyEmail: `${BASE}/verify-email`,
  onboarding: `${BASE}/onboarding`,
} as const;

export function aioServicePath(slug: string): string {
  return aioPaths.serviceSlug(slug);
}

export function aioGetStarted(goal?: string): string {
  return goal ? `${BASE}/get-started?goal=${goal}` : `${BASE}/get-started`;
}
