import { aioAppConfig } from '../config/appConfig';

const BASE = aioAppConfig.routes.base;

export const aioPaths = {
  home: BASE,
  portal: `${BASE}/portal`,
  services: `${BASE}/services`,
  permitting: `${BASE}/services/permitting`,
  businessFormation: `${BASE}/services/business-formation`,
  insurance: `${BASE}/services/insurance`,
  dispatching: `${BASE}/services/dispatching`,
  factoring: `${BASE}/services/factoring`,
  brokerage: `${BASE}/services/brokerage`,
  portalFactoring: `${BASE}/portal/factoring`,
  about: `${BASE}/about`,
  contact: `${BASE}/contact`,
  roadmap: `${BASE}/roadmap`,
  getStarted: `${BASE}/get-started`,
  roadmapResults: `${BASE}/roadmap/results`,
  servicePlan: `${BASE}/service-plan`,
  requestSubmit: `${BASE}/request/submit`,
  industries: `${BASE}/about#industries`,
  resources: `${BASE}/about#resources`,
  serviceSlug: (slug: string) => `${BASE}/services/${slug}`,
  portalRequest: (requestId: string) => `${BASE}/portal/requests/${requestId}`,
  requestConfirmation: (requestId: string) => `${BASE}/request/confirmation/${requestId}`,
  portalOnboarding: `${BASE}/portal/onboarding`,
  roadReady: `${BASE}/portal/road-ready`,
  portalFleet: `${BASE}/portal/fleet`,
  portalVehicle: (id: string) => `${BASE}/portal/fleet/vehicles/${id}`,
  portalVault: `${BASE}/portal/vault`,
  portalVaultDocument: (id: string) => `${BASE}/portal/vault/${id}`,
  portalCalendar: `${BASE}/portal/calendar`,
  portalRenewals: `${BASE}/portal/renewals`,
  portalNotifications: `${BASE}/portal/notifications`,
  portalNotificationSettings: `${BASE}/portal/settings/notifications`,
  portalSettings: `${BASE}/portal/settings`,
  officeRenewals: `${BASE}/office/renewals`,
  office: `${BASE}/office`,
  officeClients: `${BASE}/office/clients`,
  officeClient: (id: string) => `${BASE}/office/clients/${id}`,
  officeRequests: `${BASE}/office/requests`,
  officeRequest: (id: string) => `${BASE}/office/requests/${id}`,
  officeTasks: `${BASE}/office/tasks`,
  officeDeadlines: `${BASE}/office/deadlines`,
  officeDocuments: `${BASE}/office/documents`,
  officeMessages: `${BASE}/office/messages`,
  officePermitting: `${BASE}/office/permitting`,
  officeFormation: `${BASE}/office/business-formation`,
  officeInsurance: `${BASE}/office/insurance`,
  officeDispatch: `${BASE}/office/dispatch`,
  officeLoad: (id: string) => `${BASE}/office/dispatch/loads/${id}`,
  officeFactoring: `${BASE}/office/factoring`,
  officeBrokerage: `${BASE}/office/brokerage`,
  officeShipment: (id: string) => `${BASE}/office/brokerage/shipments/${id}`,
  officeInvoices: `${BASE}/office/invoices`,
  officePayments: `${BASE}/office/payments`,
  officeTeam: `${BASE}/office/team`,
  officeReports: `${BASE}/office/reports`,
  officeRoadReady: `${BASE}/office/road-ready`,
  officeClientRoadReady: (id: string) => `${BASE}/office/clients/${id}/road-ready`,
  login: `${BASE}/login`,
  signUp: `${BASE}/sign-up`,
  forgotPassword: `${BASE}/forgot-password`,
  resetPassword: `${BASE}/reset-password`,
  verifyEmail: `${BASE}/verify-email`,
  onboarding: `${BASE}/onboarding`,
} as const;

export function aioServicePath(slug: string): string {
  return aioPaths.serviceSlug(slug);
}

export function aioGetStarted(goal?: string): string {
  return goal ? `${BASE}/get-started?goal=${goal}` : `${BASE}/get-started`;
}
