import {
  adminStudioBusinessDiscoveryBlueprintPath,
  adminStudioDocumentationRegistryPath,
  adminStudioDocumentationGovernancePath,
  adminStudioSystemRegistryPath,
  adminStudioComponentRegistryPath,
  adminStudioDesignTokenEnginePath,
  adminStudioInteractionEnginePath,
  adminStudioEventBusPath,
  adminStudioAutomationRegistryPath,
  adminStudioExecutiveCouncilPath,
  adminStudioExpertMarketplacePath,
  adminStudioKnowledgeCommercePath,
  adminStudioKnowledgeHubPath,
  adminStudioLegacyNetworkPath,
  adminStudioLegacyVaultPath,
  adminStudioMemoryEnginePath,
  adminStudioMissionControlPath,
  adminStudioModelOrchestratorPath,
  adminStudioOrganizationGenomePath,
  adminStudioOrganizationOperatingManualPath,
  adminStudioOrganizationPulsePath,
  adminStudioProfessionBrainPath,
  adminStudioProfessionalTrustFrameworkPath,
  adminStudioStudioFoundationModelsPath,
  adminStudioStudioInstitutePath,
  adminStudioStudioIntelligenceArchitecturePath,
  adminStudioStudioIntelligencePath,
  adminStudioSuccessionModePath,
} from '../../utils/adminStudioRoutes';
import type { DocumentationSystemEntry } from './types';

const BASE = '/admin/studio';

function entry(
  partial: Omit<DocumentationSystemEntry, 'docPath'> & { id: string; label: string; purpose: string; overview: string }
): DocumentationSystemEntry {
  const { id, label, overview } = partial;
  return {
    ...partial,
    docPath: `docs/studio-os/${id}.md`,
    capabilities: partial.capabilities ?? [],
    howItWorks: partial.howItWorks ?? overview,
    whenUsed: partial.whenUsed ?? [],
    relatedSystems: partial.relatedSystems ?? [],
    exampleWorkflows: partial.exampleWorkflows ?? [],
    aliases: partial.aliases ?? [label.replace(/™/g, '').toLowerCase()],
    searchKeywords: partial.searchKeywords ?? [id.replace(/-/g, ' '), label.toLowerCase()],
  };
}

/** Canonical registry — single source of truth for all Studio OS documentation surfaces. */
export const DOCUMENTATION_SYSTEM_REGISTRY: DocumentationSystemEntry[] = [
  entry({
    id: 'business-discovery-blueprint',
    label: 'Business Discovery Blueprint™',
    moduleId: 'business-discovery-blueprint',
    milestone: 'M75',
    route: adminStudioBusinessDiscoveryBlueprintPath(),
    purpose: 'Structured discovery that captures how your organization operates before automation.',
    overview:
      'Guides founders through business identity, customers, operations, and goals — output feeds Profession Brain™ and Organization Genome™.',
    capabilities: ['Discovery chapters', 'Progress tracking', 'Blueprint export', 'Profession Brain seeding'],
    howItWorks: 'Answer discovery questions → Studio OS structures answers into a living Blueprint.',
    whenUsed: ['Day one of Studio OS', 'Before Profession Brain setup', 'When business model shifts'],
    relatedSystems: ['profession-brain', 'organization-genome', 'organization-operating-manual'],
    exampleWorkflows: ['START DISCOVERY → COMPLETE CHAPTERS → ACTIVATE PROFESSION BRAIN'],
    aliases: ['blueprint', 'discovery', 'business blueprint', 'bdb'],
    searchKeywords: ['business discovery', 'discovery blueprint', 'onboarding blueprint'],
  }),
  entry({
    id: 'profession-brain',
    label: 'Profession Brain™',
    moduleId: 'profession-brain',
    milestone: 'M76',
    route: adminStudioProfessionBrainPath(),
    purpose: 'Living professional expertise — how your organization thinks and decides.',
    overview:
      'Captures SOPs, mistakes, best practices, and human knowledge. Feeds Studio Institute™, Knowledge Commerce™, and Studio Models™.',
    capabilities: ['Profession brains', 'Memory graph', 'Human knowledge artifacts', 'Academy bridge'],
    howItWorks: 'Correct and teach Studio OS → Profession Brain learns → expertise compounds.',
    whenUsed: ['Daily operations', 'Training staff', 'Before automations', 'Legacy preservation'],
    relatedSystems: ['studio-institute', 'knowledge-commerce', 'memory-engine', 'studio-foundation-models'],
    exampleWorkflows: ['CAPTURE MISTAKE → ADD BEST PRACTICE → SYNC TO INSTITUTE COURSE'],
    aliases: ['brain', 'professional brain', 'expertise brain'],
    searchKeywords: ['profession brain', 'organizational expertise', 'sop capture'],
  }),
  entry({
    id: 'organization-genome',
    label: 'Organization Genome™',
    moduleId: 'organization-genome',
    milestone: 'M77',
    route: adminStudioOrganizationGenomePath(),
    purpose: 'DNA of the organization — identity, values, voice, and structural patterns.',
    overview: 'Reflects who you are everywhere — departments, content, concierges, and customer experience.',
    capabilities: ['Identity pillars', 'Voice canon', 'Department alignment', 'Genome sync'],
    howItWorks: 'Genome defines patterns → every module inherits organizational identity.',
    whenUsed: ['Brand alignment', 'New department setup', 'Content generation', 'Concierge calibration'],
    relatedSystems: ['business-discovery-blueprint', 'profession-brain', 'organization-operating-manual'],
    exampleWorkflows: ['DEFINE GENOME → REVIEW DEPARTMENT ALIGNMENT → SYNC TO CONTENT'],
    aliases: ['genome', 'org dna', 'organizational identity'],
    searchKeywords: ['organization genome', 'company dna', 'brand voice'],
  }),
  entry({
    id: 'professional-trust-framework',
    label: 'Professional Trust Framework™',
    moduleId: 'professional-trust-framework',
    milestone: 'M78',
    route: adminStudioProfessionalTrustFrameworkPath(),
    purpose: 'Scope validation and professional boundaries for AI-assisted work.',
    overview: 'Gates legal, medical, and regulated workflows — validates before Studio Intelligence executes.',
    capabilities: ['Trust scope', 'Regulated rules', 'Professional boundaries', 'Validation gates'],
    howItWorks: 'Every AI request passes trust validation before execution in regulated contexts.',
    whenUsed: ['Legal intake', 'Medical office workflows', 'Regulated industries', 'Client-facing AI'],
    relatedSystems: ['studio-intelligence-architecture', 'model-orchestrator', 'studio-foundation-models'],
    exampleWorkflows: ['REQUEST LEGAL DRAFT → TRUST SCOPE CHECK → ROUTE TO APPROVED MODEL'],
    aliases: ['trust framework', 'professional trust', 'ptf'],
    searchKeywords: ['trust', 'regulated', 'scope validation', 'professional boundaries'],
  }),
  entry({
    id: 'memory-engine',
    label: 'Memory Engine™',
    moduleId: 'memory-engine',
    milestone: 'M79',
    route: adminStudioMemoryEnginePath(),
    purpose: 'Organizational memory — remember what worked and prove it forever.',
    overview: 'Stores decisions, patterns, and outcomes. Feeds Knowledge Fabric™ and Legacy Vault™.',
    capabilities: ['Memory nodes', 'Decision recall', 'Pattern storage', 'Proof artifacts'],
    howItWorks: 'Capture outcomes → Memory Engine indexes → Context Engine retrieves before AI responses.',
    whenUsed: ['After major decisions', 'Proving what worked', 'Executive briefings', 'Succession planning'],
    relatedSystems: ['legacy-vault', 'studio-intelligence-architecture', 'executive-timeline', 'succession-mode'],
    exampleWorkflows: ['RECORD DECISION → TAG OUTCOME → SURFACE IN EXECUTIVE BRIEFING'],
    aliases: ['memory', 'organizational memory', 'org memory'],
    searchKeywords: ['memory engine', 'remember', 'decision memory', 'what worked'],
  }),
  entry({
    id: 'studio-intelligence-architecture',
    label: 'Knowledge Fabric™ / Studio Intelligence™ Architecture',
    moduleId: 'studio-intelligence-architecture',
    milestone: 'M122',
    route: adminStudioStudioIntelligenceArchitecturePath(),
    purpose: 'Model-agnostic intelligence layer — organization owns knowledge; models reason.',
    overview:
      'Knowledge Fabric™ connects org knowledge. Context Engine assembles trusted context. Intelligence Layer pipeline validates every AI request.',
    capabilities: ['Knowledge Fabric', 'Context Engine', 'Intelligence Layer', 'Model Gateway'],
    howItWorks: 'Org knowledge first → context assembled → model reasons second → validated response.',
    whenUsed: ['Every AI interaction', 'Before trusting model output', 'Knowledge graph exploration'],
    relatedSystems: ['model-orchestrator', 'profession-brain', 'memory-engine', 'legacy-vault'],
    exampleWorkflows: ['QUERY COMMAND DOCK → CONTEXT ENGINE GATHERS → MODEL GATEWAY ROUTES'],
    aliases: ['knowledge fabric', 'intelligence architecture', 'sia', 'context engine'],
    searchKeywords: ['knowledge fabric', 'studio intelligence architecture', 'model agnostic'],
  }),
  entry({
    id: 'knowledge-confidence',
    label: 'Knowledge Confidence™',
    moduleId: 'knowledge-confidence',
    milestone: 'M88',
    route: `${BASE}/knowledge-confidence`,
    purpose: 'Trust through transparency — know what you know, honestly.',
    overview: 'Scores Profession Brain quality and flags gaps before automation or publishing.',
    capabilities: ['Confidence scores', 'Gap detection', 'Quality gates', 'Transparency reports'],
    howItWorks: 'Analyzes Profession Brain completeness → surfaces confidence before high-stakes actions.',
    whenUsed: ['Before automations', 'Before client-facing content', 'Quality reviews'],
    relatedSystems: ['profession-brain', 'professional-trust-framework', 'shadow-mode'],
    exampleWorkflows: ['REVIEW CONFIDENCE SCORE → FILL GAPS → APPROVE AUTOMATION'],
    aliases: ['confidence', 'knowledge quality', 'trust score'],
    searchKeywords: ['knowledge confidence', 'quality score', 'what we know'],
  }),
  entry({
    id: 'executive-council',
    label: 'Executive Council™',
    moduleId: 'executive-council',
    milestone: 'M89',
    route: adminStudioExecutiveCouncilPath(),
    purpose: 'Many minds, one briefing — simulated executive perspectives on decisions.',
    overview: 'Digital executives debate options using org context before founder decides.',
    capabilities: ['Council sessions', 'Multi-perspective analysis', 'Decision briefings', 'Council procedures'],
    howItWorks: 'Present decision → Council members analyze from roles → unified briefing to founder.',
    whenUsed: ['Major decisions', 'Strategy shifts', 'Risk assessment', 'Executive alignment'],
    relatedSystems: ['studio-intelligence', 'command-dock', 'organization-operating-manual'],
    exampleWorkflows: ['SUBMIT DECISION → COUNCIL DEBATE → REVIEW UNIFIED BRIEFING'],
    aliases: ['council', 'executive briefing', 'digital executives'],
    searchKeywords: ['executive council', 'council briefing', 'many minds'],
  }),
  entry({
    id: 'organization-pulse',
    label: 'Organization Pulse™',
    moduleId: 'organization-pulse',
    milestone: 'M90',
    route: adminStudioOrganizationPulsePath(),
    purpose: 'Feel the organization — not just the revenue.',
    overview: 'Holistic health signals beyond financial metrics — morale, load, readiness, drift.',
    capabilities: ['Pulse metrics', 'Health signals', 'Drift detection', 'Executive alerts'],
    howItWorks: 'Aggregates signals from departments → surfaces organizational feeling → alerts founder.',
    whenUsed: ['Weekly health reviews', 'Before expansion', 'Succession readiness checks'],
    relatedSystems: ['company-health-index', 'founder-cognitive-load', 'succession-mode'],
    exampleWorkflows: ['OPEN PULSE → REVIEW SIGNALS → ACT ON DRIFT ALERT'],
    aliases: ['pulse', 'org health feel', 'organizational feel'],
    searchKeywords: ['organization pulse', 'org health', 'morale signals'],
  }),
  entry({
    id: 'succession-mode',
    label: 'Succession Mode™',
    moduleId: 'succession-mode',
    milestone: 'M98',
    route: adminStudioSuccessionModePath(),
    purpose: 'Preserve expertise — survive founder unavailability.',
    overview: 'Knowledge dependency map, succession readiness, and legacy continuity planning.',
    capabilities: ['Dependency map', 'Succession score', 'Continuity recommendations', 'Legacy handoff'],
    howItWorks: 'Maps who knows what → scores survival without founder → recommends continuity actions.',
    whenUsed: ['Succession planning', 'Key person risk', 'Legacy handoff preparation'],
    relatedSystems: ['legacy-vault', 'memory-engine', 'profession-brain', 'organization-operating-manual'],
    exampleWorkflows: ['RUN DEPENDENCY MAP → REVIEW GAPS → ACTIVATE SUCCESSION PLAN'],
    aliases: ['succession', 'continuity', 'founder unavailability'],
    searchKeywords: ['succession mode', 'succession planning', 'knowledge dependency'],
  }),
  entry({
    id: 'legacy-vault',
    label: 'Legacy Vault™',
    moduleId: 'legacy-vault',
    milestone: 'M91',
    route: adminStudioLegacyVaultPath(),
    purpose: 'Preserve the story — build legacy.',
    overview: 'Permanent organizational history — milestones, decisions, and founder narrative.',
    capabilities: ['Vault entries', 'Timeline preservation', 'Legacy narrative', 'Historical recall'],
    howItWorks: 'Significant moments captured → Legacy Vault preserves → feeds Studio Intelligence moat.',
    whenUsed: ['Major milestones', 'Founder reflections', 'Historical reference', 'Legacy planning'],
    relatedSystems: ['executive-timeline', 'memory-engine', 'legacy-network', 'studio-foundation-models'],
    exampleWorkflows: ['CAPTURE MILESTONE → ADD VAULT ENTRY → LINK TO TIMELINE'],
    aliases: ['vault', 'legacy', 'organizational history'],
    searchKeywords: ['legacy vault', 'preserve story', 'organizational history'],
  }),
  entry({
    id: 'studio-institute',
    label: 'Studio Institute™',
    moduleId: 'studio-institute',
    milestone: 'M93',
    route: adminStudioStudioInstitutePath(),
    purpose: 'Learn from expertise — carry the legacy forward.',
    overview: 'Living learning platform generated from Profession Brain™ — courses, paths, certifications.',
    capabilities: ['Course generation', 'Training paths', 'Certifications', 'Academy modules'],
    howItWorks: 'Profession Brain expertise → Institute courses → staff and customers learn org methods.',
    whenUsed: ['Staff onboarding', 'Customer education', 'Expertise monetization prep'],
    relatedSystems: ['profession-brain', 'knowledge-commerce', 'expert-marketplace'],
    exampleWorkflows: ['APPROVE BRAIN MODULE → GENERATE COURSE → PUBLISH TRAINING PATH'],
    aliases: ['institute', 'academy', 'studio academy', 'training'],
    searchKeywords: ['studio institute', 'training', 'courses', 'academy'],
  }),
  entry({
    id: 'expert-marketplace',
    label: 'Expert Marketplace™',
    moduleId: 'expert-marketplace',
    milestone: 'M94',
    route: adminStudioExpertMarketplacePath(),
    purpose: 'Share expertise — expand your legacy.',
    overview: 'Connect organization expertise with external experts — playbooks, certifications, offerings.',
    capabilities: ['Expert listings', 'Playbook exchange', 'Certification paths', 'Institute connection'],
    howItWorks: 'Package expertise → list on marketplace → connect with Institute and Knowledge Commerce.',
    whenUsed: ['Expert partnerships', 'External knowledge import', 'Revenue expansion'],
    relatedSystems: ['studio-institute', 'knowledge-commerce', 'legacy-network'],
    exampleWorkflows: ['PACKAGE PLAYBOOK → LIST ON MARKETPLACE → LINK INSTITUTE COURSE'],
    aliases: ['marketplace', 'experts', 'expert network'],
    searchKeywords: ['expert marketplace', 'share expertise', 'external experts'],
  }),
  entry({
    id: 'knowledge-commerce',
    label: 'Knowledge Commerce™',
    moduleId: 'knowledge-commerce',
    milestone: 'M95',
    route: adminStudioKnowledgeCommercePath(),
    purpose: 'Monetize knowledge — expand your legacy.',
    overview: 'Sell courses, playbooks, and knowledge products derived from Profession Brain™.',
    capabilities: ['Product catalog', 'Pricing', 'Distribution', 'Commerce sync'],
    howItWorks: 'Institute content → Knowledge Commerce products → customers purchase org expertise.',
    whenUsed: ['Revenue from expertise', 'Customer education products', 'Certification sales'],
    relatedSystems: ['studio-institute', 'expert-marketplace', 'profession-brain'],
    exampleWorkflows: ['SELECT COURSE → SET PRICING → PUBLISH KNOWLEDGE PRODUCT'],
    aliases: ['commerce', 'knowledge products', 'sell expertise'],
    searchKeywords: ['knowledge commerce', 'monetize knowledge', 'sell courses'],
  }),
  entry({
    id: 'command-dock',
    label: 'Command Dock™',
    moduleId: 'command-dock',
    milestone: 'M96',
    route: `${BASE}/command-dock`,
    purpose: 'Natural language command center — speak; Studio OS routes intelligently.',
    overview: 'Founder speaks naturally → Dock routes to concierges, modules, and intelligence layers.',
    capabilities: ['Natural language routing', 'Proactive suggestions', 'Context-aware help', 'Concierge orchestration'],
    howItWorks: 'Input command → context resolved → routed to correct module or concierge → response validated.',
    whenUsed: ['Daily executive commands', 'Quick module access', 'Contextual questions', 'Workflow triggers'],
    relatedSystems: ['studio-intelligence-architecture', 'model-orchestrator', 'executive-council'],
    exampleWorkflows: ['SPEAK COMMAND → DOCK ROUTES → REVIEW CONCIERGE RESPONSE'],
    aliases: ['dock', 'command center', 'natural language'],
    searchKeywords: ['command dock', 'speak to studio', 'executive command'],
  }),
  entry({
    id: 'ambient-awareness',
    label: 'Ambient Awareness™',
    moduleId: 'ambient-awareness',
    milestone: 'M100',
    route: `${BASE}/ambient-awareness`,
    purpose: 'Already aware — never asking twice.',
    overview: 'Continuous organizational context without repeated questions — ambient intelligence layer.',
    capabilities: ['Context persistence', 'Ambient briefing', 'Proactive awareness', 'Silent sync'],
    howItWorks: 'Studio OS maintains ambient context → surfaces relevant info without founder re-explaining.',
    whenUsed: ['Daily operations', 'Returning after absence', 'Multi-tasking executives'],
    relatedSystems: ['anticipation-engine', 'presence-engine', 'command-dock'],
    exampleWorkflows: ['OPEN HEADQUARTERS → AMBIENT BRIEFING READY → ACT WITHOUT RE-EXPLAINING'],
    aliases: ['ambient', 'awareness', 'continuous context'],
    searchKeywords: ['ambient awareness', 'already aware', 'context persistence'],
  }),
  entry({
    id: 'anticipation-engine',
    label: 'Anticipation Engine™',
    moduleId: 'anticipation-engine',
    milestone: 'M101',
    route: `${BASE}/anticipation-engine`,
    purpose: 'Prepare tomorrow — before it\'s asked.',
    overview: 'Predicts upcoming needs and prepares drafts, briefings, and actions for founder approval.',
    capabilities: ['Need prediction', 'Draft preparation', 'Approval queue', 'Tomorrow prep'],
    howItWorks: 'Analyzes patterns → anticipates needs → prepares actions → founder approves.',
    whenUsed: ['End of day prep', 'Weekly planning', 'Before known deadlines'],
    relatedSystems: ['autonomous-preparation', 'predictive-organization', 'command-dock'],
    exampleWorkflows: ['REVIEW ANTICIPATED NEEDS → APPROVE PREPARED DRAFTS → EXECUTE TOMORROW'],
    aliases: ['anticipation', 'prepare tomorrow', 'predictive prep'],
    searchKeywords: ['anticipation engine', 'prepare before asked', 'tomorrow prep'],
  }),
  entry({
    id: 'founder-cognitive-load',
    label: 'Founder Cognitive Load™',
    moduleId: 'founder-cognitive-load',
    milestone: 'M102',
    route: `${BASE}/founder-cognitive-load`,
    purpose: 'Protect focus — prioritize what matters.',
    overview: 'Monitors founder attention load and filters noise — protects executive capacity.',
    capabilities: ['Load scoring', 'Priority filtering', 'Noise reduction', 'Focus protection'],
    howItWorks: 'Tracks cognitive load signals → filters low-priority interruptions → surfaces what matters.',
    whenUsed: ['Overwhelming weeks', 'Major launches', 'Recovery periods'],
    relatedSystems: ['organization-pulse', 'command-dock', 'founder-operating-system'],
    exampleWorkflows: ['CHECK LOAD SCORE → DEFER LOW PRIORITY → FOCUS ON TOP THREE'],
    aliases: ['cognitive load', 'founder focus', 'attention protection'],
    searchKeywords: ['cognitive load', 'protect focus', 'founder overwhelm'],
  }),
  entry({
    id: 'presence-engine',
    label: 'Presence Engine™',
    moduleId: 'presence-engine',
    milestone: 'M103',
    route: `${BASE}/presence-engine`,
    purpose: 'Always there — never noisy.',
    overview: 'Calibrated organizational presence — available without interrupting founder flow.',
    capabilities: ['Presence calibration', 'Interrupt filtering', 'Availability signals', 'Quiet assistance'],
    howItWorks: 'Adjusts how Studio OS presents itself based on founder state and context.',
    whenUsed: ['Deep work sessions', 'Client meetings', 'Travel and async periods'],
    relatedSystems: ['ambient-awareness', 'founder-cognitive-load', 'command-dock'],
    exampleWorkflows: ['SET PRESENCE MODE → STUDIO QUIETLY ASSISTS → SURFACE ONLY CRITICAL'],
    aliases: ['presence', 'always there', 'quiet assistance'],
    searchKeywords: ['presence engine', 'never noisy', 'calibrated presence'],
  }),
  entry({
    id: 'relationship-memory',
    label: 'Relationship Memory™',
    moduleId: 'relationship-memory',
    milestone: 'M104',
    route: `${BASE}/relationship-memory`,
    purpose: 'Remember how you work — naturally.',
    overview: 'Remembers people, preferences, and working patterns across the organization.',
    capabilities: ['Relationship profiles', 'Working patterns', 'Preference recall', 'Context continuity'],
    howItWorks: 'Captures relationship context → recalls in future interactions → natural continuity.',
    whenUsed: ['Client relationships', 'Vendor management', 'Team collaboration', 'Repeat interactions'],
    relatedSystems: ['memory-engine', 'studio-intelligence-architecture', 'command-dock'],
    exampleWorkflows: ['INTERACT WITH CLIENT → RELATIONSHIP MEMORY UPDATES → NEXT MEETING PRE-BRIEFED'],
    aliases: ['relationships', 'people memory', 'working patterns'],
    searchKeywords: ['relationship memory', 'remember people', 'client preferences'],
  }),
  entry({
    id: 'predictive-organization',
    label: 'Predictive Organization™',
    moduleId: 'predictive-organization',
    milestone: 'M105',
    route: `${BASE}/predictive-organization`,
    purpose: 'Prepare before tomorrow arrives.',
    overview: 'Organizational-level prediction — trends, risks, and opportunities before they surface.',
    capabilities: ['Trend prediction', 'Risk forecasting', 'Opportunity detection', 'Org-level prep'],
    howItWorks: 'Analyzes org signals → predicts trends → recommends preparation actions.',
    whenUsed: ['Quarterly planning', 'Risk management', 'Growth preparation'],
    relatedSystems: ['anticipation-engine', 'autonomous-preparation', 'organization-pulse'],
    exampleWorkflows: ['REVIEW PREDICTIONS → PREPARE DEPARTMENTS → ACT BEFORE TREND HITS'],
    aliases: ['predictive', 'forecast org', 'prepare ahead'],
    searchKeywords: ['predictive organization', 'org forecast', 'prepare ahead'],
  }),
  entry({
    id: 'autonomous-preparation',
    label: 'Autonomous Preparation™',
    moduleId: 'autonomous-preparation',
    milestone: 'M106',
    route: `${BASE}/autonomous-preparation`,
    purpose: 'One step ahead — always awaiting approval.',
    overview: 'Prepares work autonomously but never executes without founder approval.',
    capabilities: ['Auto-prep drafts', 'Approval gates', 'Pre-work queue', 'Safe autonomy'],
    howItWorks: 'Anticipates task → prepares draft → queues for approval → executes only when approved.',
    whenUsed: ['Recurring workflows', 'Meeting prep', 'Report generation', 'Routine operations'],
    relatedSystems: ['anticipation-engine', 'shadow-mode', 'command-dock'],
    exampleWorkflows: ['PREP QUEUE REVIEW → APPROVE DRAFT → EXECUTE PREPARED WORK'],
    aliases: ['autonomous prep', 'auto prepare', 'approval queue'],
    searchKeywords: ['autonomous preparation', 'prepare automatically', 'awaiting approval'],
  }),
  entry({
    id: 'organizational-consciousness',
    label: 'Organizational Consciousness™',
    moduleId: 'organizational-consciousness',
    milestone: 'M107',
    route: `${BASE}/organizational-consciousness`,
    purpose: 'One intelligence — preserve expertise, build legacy.',
    overview: 'Unified organizational awareness — all systems speak as one coherent intelligence.',
    capabilities: ['Unified awareness', 'Cross-system synthesis', 'Consciousness score', 'Holistic briefing'],
    howItWorks: 'Synthesizes all intelligence layers → presents unified organizational consciousness to founder.',
    whenUsed: ['Strategic reviews', 'Major transitions', 'Holistic health checks'],
    relatedSystems: ['studio-intelligence-architecture', 'organization-pulse', 'executive-council'],
    exampleWorkflows: ['OPEN CONSCIOUSNESS → REVIEW UNIFIED BRIEFING → ACT ON SYNTHESIS'],
    aliases: ['consciousness', 'unified intelligence', 'org consciousness'],
    searchKeywords: ['organizational consciousness', 'one intelligence', 'unified awareness'],
  }),
  entry({
    id: 'executive-timeline',
    label: 'Executive Timeline™',
    moduleId: 'executive-timeline',
    milestone: 'M108',
    route: `${BASE}/executive-timeline`,
    purpose: 'See how you arrived — preserve the journey forever.',
    overview: 'Interactive organizational history — milestones, pivots, and founder journey.',
    capabilities: ['Timeline events', 'Journey replay', 'Milestone markers', 'Historical context'],
    howItWorks: 'Events captured over time → Timeline visualizes journey → feeds Legacy Vault.',
    whenUsed: ['Reflection', 'Board presentations', 'Succession handoff', 'Anniversary reviews'],
    relatedSystems: ['legacy-vault', 'memory-engine', 'succession-mode'],
    exampleWorkflows: ['OPEN TIMELINE → REPLAY MILESTONE → ADD VAULT ENTRY'],
    aliases: ['timeline', 'journey', 'executive history'],
    searchKeywords: ['executive timeline', 'organizational journey', 'how we arrived'],
  }),
  entry({
    id: 'world-knowledge-engine',
    label: 'World Knowledge Engine™',
    moduleId: 'world-knowledge-engine',
    milestone: 'M109',
    route: `${BASE}/world-knowledge-engine`,
    purpose: 'Information finds you — the outside world, filtered.',
    overview: 'Filters external world knowledge through org context — relevant news, trends, regulations.',
    capabilities: ['External filtering', 'Relevance scoring', 'Regulation alerts', 'Trend surfacing'],
    howItWorks: 'Monitors external sources → filters through org lens → surfaces only what matters.',
    whenUsed: ['Industry monitoring', 'Regulatory changes', 'Competitive awareness'],
    relatedSystems: ['studio-intelligence-architecture', 'professional-trust-framework', 'command-dock'],
    exampleWorkflows: ['REVIEW FILTERED FEED → ACT ON REGULATION ALERT → UPDATE OPERATING MANUAL'],
    aliases: ['world knowledge', 'external intelligence', 'outside world'],
    searchKeywords: ['world knowledge engine', 'external news', 'filtered information'],
  }),
  entry({
    id: 'founder-operating-system',
    label: 'Founder Operating System™',
    moduleId: 'founder-operating-system',
    milestone: 'M110',
    route: `${BASE}/founder-operating-system`,
    purpose: 'Founders grow first — organizations follow.',
    overview: 'Personal operating system for founders — habits, growth, and leadership calibration.',
    capabilities: ['Founder habits', 'Growth tracking', 'Leadership calibration', 'Personal OS sync'],
    howItWorks: 'Founder personal OS → calibrates how Studio OS serves the founder → org follows.',
    whenUsed: ['Personal development', 'Leadership growth', 'Founder calibration'],
    relatedSystems: ['founder-cognitive-load', 'executive-council', 'command-dock'],
    exampleWorkflows: ['REVIEW FOUNDER OS → CALIBRATE PRIORITIES → SYNC TO HEADQUARTERS'],
    aliases: ['founder os', 'personal os', 'founder growth'],
    searchKeywords: ['founder operating system', 'founder growth', 'leadership calibration'],
  }),
  entry({
    id: 'studio-intelligence',
    label: 'Studio Intelligence™',
    moduleId: 'studio-intelligence',
    milestone: 'M36',
    route: adminStudioStudioIntelligencePath(),
    purpose: 'Operating intelligence — briefings, opportunities, risks, and proactive recommendations.',
    overview: 'Executive intelligence layer — health, opportunities, risks, and daily briefings.',
    capabilities: ['Executive briefings', 'Opportunity engine', 'Risk engine', 'Health scoring'],
    howItWorks: 'Aggregates org data → generates briefings and recommendations → surfaces proactively.',
    whenUsed: ['Daily executive review', 'Opportunity assessment', 'Risk monitoring'],
    relatedSystems: ['studio-intelligence-architecture', 'executive-council', 'organization-pulse'],
    exampleWorkflows: ['OPEN STUDIO INTELLIGENCE → REVIEW BRIEFING → ACT ON TOP RECOMMENDATION'],
    aliases: ['intelligence', 'executive intelligence', 'operating intelligence'],
    searchKeywords: ['studio intelligence', 'executive briefing', 'business health'],
  }),
  entry({
    id: 'model-orchestrator',
    label: 'Model Orchestrator™ / AI Swap Engine™',
    moduleId: 'model-orchestrator',
    milestone: 'M123',
    route: adminStudioModelOrchestratorPath(),
    purpose: 'AI abstraction — providers interchangeable; Studio Intelligence™ permanent.',
    overview: 'Routes all AI requests. AI Swap Engine switches providers without breaking protected features.',
    capabilities: ['Multi-model routing', 'AI Swap Engine', 'Failover', 'Benchmarking', 'Local/offline'],
    howItWorks: 'All AI flows through orchestrator → best model selected → failover if provider fails.',
    whenUsed: ['Every AI request', 'Provider changes', 'Failover events', 'Cost optimization'],
    relatedSystems: ['studio-intelligence-architecture', 'studio-foundation-models', 'professional-trust-framework'],
    exampleWorkflows: ['SWAP PROVIDER → VERIFY PROTECTED FEATURES → CONTINUE OPERATIONS'],
    aliases: ['orchestrator', 'ai swap', 'model routing', 'swap engine'],
    searchKeywords: ['model orchestrator', 'ai swap engine', 'change ai provider', 'failover'],
  }),
  entry({
    id: 'studio-foundation-models',
    label: 'Studio Foundation Models™ / Profession Models™',
    moduleId: 'studio-foundation-models',
    milestone: 'M124',
    route: adminStudioStudioFoundationModelsPath(),
    purpose: 'Long-term Studio-owned intelligence — general models know the world; Studio Models know organizations.',
    overview: 'Roadmap for Studio-owned models. 13 Profession Models™ for specialized reasoning.',
    capabilities: ['Foundation capabilities', 'Profession Models', 'Hybrid intelligence', 'Training sources', 'Enterprise deployment'],
    howItWorks: 'Hybrid: Studio profession model reasons → external model drafts → Knowledge Fabric contextualizes.',
    whenUsed: ['Long-term AI strategy', 'Regulated workflows', 'Enterprise deployment planning'],
    relatedSystems: ['model-orchestrator', 'profession-brain', 'studio-intelligence-architecture'],
    exampleWorkflows: ['REVIEW ROADMAP PHASE → ACTIVATE PROFESSION MODEL → HYBRID WORKFLOW'],
    aliases: ['foundation models', 'studio models', 'profession models', 'owned intelligence'],
    searchKeywords: ['studio foundation models', 'profession models', 'studio owned ai', 'hybrid intelligence'],
  }),
  entry({
    id: 'organization-operating-manual',
    label: 'Organization Operating Manual™',
    moduleId: 'organization-operating-manual',
    milestone: 'M120',
    route: adminStudioOrganizationOperatingManualPath(),
    purpose: 'One handbook — always current.',
    overview: 'Auto-generated living manual — 21 sections synced from all intelligence systems.',
    capabilities: ['21 auto sections', 'Live sync', 'Searchable Q&A', 'Natural language queries'],
    howItWorks: 'Org changes → manual auto-updates → searchable via natural language.',
    whenUsed: ['Staff reference', 'Policy lookup', 'Onboarding employees', 'Compliance review'],
    relatedSystems: ['profession-brain', 'organization-genome', 'studio-institute', 'legacy-network'],
    exampleWorkflows: ['ASK "HOW DO WE ONBOARD CLIENTS?" → MANUAL ANSWERS FROM LIVE DATA'],
    aliases: ['operating manual', 'handbook', 'org manual', 'sop manual'],
    searchKeywords: ['operating manual', 'employee handbook', 'how do we', 'policy lookup'],
  }),
  entry({
    id: 'legacy-network',
    label: 'Legacy Network™',
    moduleId: 'legacy-network',
    milestone: 'M121',
    route: adminStudioLegacyNetworkPath(),
    purpose: 'Preserve expertise — share legacy. Movement, not marketplace.',
    overview: 'Permission-based global ecosystem for sharing expertise while retaining IP.',
    capabilities: ['Shareable assets', 'Discovery', 'Attribution', 'Community', 'Reputation'],
    howItWorks: 'Voluntarily share approved assets → attributed globally → reputation compounds.',
    whenUsed: ['Sharing frameworks', 'Community contribution', 'Expertise movement'],
    relatedSystems: ['legacy-vault', 'studio-institute', 'knowledge-commerce'],
    exampleWorkflows: ['SELECT ASSET → SET PERMISSIONS → SHARE TO LEGACY NETWORK'],
    aliases: ['legacy network', 'movement', 'share expertise globally'],
    searchKeywords: ['legacy network', 'share expertise', 'global movement'],
  }),
  entry({
    id: 'mission-control',
    label: 'Headquarters / Mission Control',
    moduleId: 'mission-control',
    route: adminStudioMissionControlPath(),
    purpose: 'Executive nerve center — priorities, health, and today\'s best move.',
    overview: 'Start every day here — mission health, intelligence previews, and navigation hub.',
    capabilities: ['Mission health', 'Intelligence previews', 'Legacy wing', 'Navigation hub'],
    howItWorks: 'Aggregates status from all systems → presents executive dashboard → routes to action.',
    whenUsed: ['Start of day', 'Executive review', 'System navigation'],
    relatedSystems: ['command-dock', 'studio-intelligence', 'organization-pulse'],
    exampleWorkflows: ['OPEN MISSION CONTROL → REVIEW HEALTH → NAVIGATE TO PRIORITY MODULE'],
    aliases: ['headquarters', 'hq', 'mission control', 'executive center'],
    searchKeywords: ['mission control', 'headquarters', 'start here', 'executive dashboard'],
  }),
  entry({
    id: 'documentation-sync',
    label: 'Documentation Synchronization™',
    moduleId: 'documentation-sync',
    milestone: 'M125',
    route: adminStudioKnowledgeHubPath(),
    purpose: 'Living documentation system — synchronize all help surfaces with current architecture.',
    overview:
      'Migration and sync pass feeding manual, walkthrough, FAQ, knowledge graph, and semantic search from one canonical system registry.',
    capabilities: ['System registry', 'Semantic search clusters', 'FAQ sync', 'Getting Started progression', 'Contextual help'],
    howItWorks: 'Register system once in registry → sync engine updates all documentation consumers.',
    whenUsed: ['After milestone releases', 'Knowledge Hub search', 'Onboarding help', 'FAQ maintenance'],
    relatedSystems: ['documentation-registry', 'command-dock', 'studio-institute', 'mission-control'],
    exampleWorkflows: ['ADD SYSTEM TO REGISTRY → RUN SYNC → ALL SURFACES UPDATE'],
    aliases: ['documentation sync', 'doc sync', 'living documentation', 'help sync'],
    searchKeywords: ['documentation synchronization', 'help center sync', 'living docs'],
  }),
  entry({
    id: 'documentation-registry',
    label: 'Documentation Registry™',
    moduleId: 'documentation-registry',
    milestone: 'M126',
    route: adminStudioDocumentationRegistryPath(),
    purpose: 'Single source of truth for all Studio OS documentation — register once, sync everywhere.',
    overview:
      'Every feature registers structured metadata once. Manual, walkthrough, Academy, Command Dock, search, tooltips, and health dashboards consume automatically.',
    capabilities: [
      'Feature registry',
      'Smart search',
      'Walkthrough sync',
      'Academy sync',
      'Version history',
      'Documentation health dashboard',
      'Auto-sync surfaces',
    ],
    howItWorks: 'Feature registers metadata → registry fans out to all documentation consumers → no duplicate maintenance.',
    whenUsed: ['Adding milestones', 'Documentation health review', 'Platform Q&A via Command Dock', 'Onboarding updates'],
    relatedSystems: ['documentation-sync', 'command-dock', 'studio-institute', 'organization-inauguration'],
    exampleWorkflows: ['REGISTER FEATURE → AUTO-SYNC SURFACES → QUERY VIA COMMAND DOCK'],
    aliases: ['documentation registry', 'doc registry', 'feature registry', 'dr'],
    searchKeywords: ['documentation registry', 'one source', 'register once', 'documentation health'],
  }),
  entry({
    id: 'documentation-governance',
    label: 'Documentation Governance™',
    moduleId: 'documentation-governance',
    milestone: 'M126.5',
    route: adminStudioDocumentationGovernancePath(),
    purpose: 'Continuously monitor, validate, audit, and improve every piece of documentation.',
    overview:
      'Automated audits, coverage validation, consistency engine, dependency tracking, pre-deployment checks, and self-improvement recommendations.',
    capabilities: [
      'Continuous audits',
      'Coverage validation',
      'Consistency engine',
      'Dependency validation',
      'Health score',
      'Pre-deploy validation',
      'Self-improvement',
    ],
    howItWorks: 'Registry changes → governance audits all surfaces → actionable recommendations → pre-deploy gate.',
    whenUsed: ['Before releases', 'Documentation health review', 'Terminology audits', 'Coverage gaps'],
    relatedSystems: ['documentation-registry', 'documentation-sync', 'command-dock', 'studio-institute'],
    exampleWorkflows: ['RUN AUDITS → FIX GAPS → VALIDATE PRE-DEPLOY → RELEASE'],
    aliases: ['documentation governance', 'doc governance', 'living docs', 'dg'],
    searchKeywords: ['documentation governance', 'audit documentation', 'coverage validation', 'pre-deploy docs'],
  }),
  entry({
    id: 'system-registry',
    label: 'System Registry™',
    moduleId: 'system-registry',
    milestone: 'M127',
    route: adminStudioSystemRegistryPath(),
    purpose: 'Master registry of every object, service, module, feature, and system inside Studio OS.',
    overview:
      'Nothing exists anonymously — organizations, modules, pages, routes, panels, services, APIs, automations, concierges, workflows, and assets all register once.',
    capabilities: [
      'Master directory',
      'System metadata',
      'Dependency graph',
      'System discovery',
      'Registry health',
      'Command Dock integration',
    ],
    howItWorks: 'Everything registers with metadata → master index powers search, docs, architecture, dependencies, Studio Intelligence.',
    whenUsed: ['Architecture review', 'Developer onboarding', 'Dependency analysis', 'Platform discovery'],
    relatedSystems: ['documentation-registry', 'documentation-governance', 'command-dock', 'studio-intelligence'],
    exampleWorkflows: ['REGISTER SYSTEM → DISCOVER VIA SEARCH → TRACE DEPENDENCIES'],
    aliases: ['system registry', 'master directory', 'master index', 'platform registry', 'sr'],
    searchKeywords: ['system registry', 'master directory', 'what exists', 'platform index'],
  }),
  entry({
    id: 'component-registry',
    label: 'Component Registry™',
    moduleId: 'component-registry',
    milestone: 'M128',
    route: adminStudioComponentRegistryPath(),
    purpose: 'Every reusable UI component registered as a managed platform asset.',
    overview:
      'Buttons, cards, panels, charts, navigation, glass, Mission Control widgets, Command Dock — variants, dependencies, usage, design tokens, accessibility.',
    capabilities: ['Component catalog', 'Reuse scores', 'Category index', 'Discovery search', 'Design token binding'],
    howItWorks: 'Register component once → reuse across all Studio OS interfaces → assemble, never recreate.',
    whenUsed: ['Building new modules', 'Design system review', 'Mission Control panels', 'Developer onboarding'],
    relatedSystems: ['system-registry', 'documentation-registry', 'command-dock'],
    exampleWorkflows: ['FIND ExecutiveHeroCard → REUSE IN NEW MODULE → REGISTER VARIANT'],
    aliases: ['component registry', 'ui registry', 'design system', 'cr'],
    searchKeywords: ['component registry', 'reusable ui', 'executive ia', 'design tokens'],
  }),
  entry({
    id: 'design-token-engine',
    label: 'Design Token Engine™',
    moduleId: 'design-token-engine',
    milestone: 'M129',
    route: adminStudioDesignTokenEnginePath(),
    purpose: 'Visual source of truth — spacing, typography, colors, motion, elevation, and themes centralized.',
    overview:
      'Centralizes spacing, typography, border radius, glass, blur, shadows, elevation, animation, opacity, brand/accent colors, gradients, icon sizes, panel heights, margins, padding, breakpoints, and light/dark/future themes.',
    capabilities: ['Token catalog', 'Theme engine', 'Design governance', 'Component inheritance audit', 'Discovery search'],
    howItWorks: 'Seed tokens from Design Bible → components inherit → governance flags overrides → every future screen speaks the same visual language.',
    whenUsed: ['Building new modules', 'Design system review', 'Theme planning', 'Component token binding'],
    relatedSystems: ['component-registry', 'system-registry', 'command-dock'],
    exampleWorkflows: ['FIND spacing token → INHERIT IN COMPONENT → AUDIT GOVERNANCE'],
    aliases: ['design token engine', 'design tokens', 'visual source of truth', 'design bible', 'dte'],
    searchKeywords: ['design tokens', 'spacing', 'typography', 'themes', 'design governance'],
  }),
  entry({
    id: 'interaction-engine',
    label: 'Interaction Engine™',
    moduleId: 'interaction-engine',
    milestone: 'M130',
    route: adminStudioInteractionEnginePath(),
    purpose: 'Behavioral source of truth — standardized hover, focus, click, feedback, navigation, motion, and accessibility.',
    overview:
      'Centralizes interaction patterns (hover, focus, click, drag, expand, approve, modal, drawer), interaction states, motion standards, and accessibility requirements so Studio OS behaves like one cohesive OS.',
    capabilities: ['Pattern catalog', 'State specs', 'Motion standards', 'Accessibility requirements', 'Behavior governance', 'Discovery search'],
    howItWorks: 'Seed patterns from platform behavior → components declare interactionRules → governance flags custom behavior → every click feels intentional.',
    whenUsed: ['Building new modules', 'UX review', 'Accessibility audit', 'Component interaction binding'],
    relatedSystems: ['design-token-engine', 'component-registry', 'command-dock'],
    exampleWorkflows: ['FIND hover pattern → BIND TO COMPONENT → AUDIT GOVERNANCE'],
    aliases: ['interaction engine', 'behavior patterns', 'interaction patterns', 'platform behavior', 'ie'],
    searchKeywords: ['interactions', 'hover', 'focus', 'modal', 'accessibility', 'motion'],
  }),
  entry({
    id: 'event-bus',
    label: 'Event Bus™',
    moduleId: 'event-bus',
    milestone: 'M131',
    route: adminStudioEventBusPath(),
    purpose: 'Communication backbone — publish/subscribe event-driven architecture for loosely coupled systems.',
    overview:
      'Standard event types (created, updated, approved, published, failed, etc.), subscription registry, Event Inspector (monitor, replay, filter, debug), permanent event history, and reaction chains.',
    capabilities: ['Event catalog', 'Publish/subscribe', 'Event Inspector', 'Event history', 'Chain visualization', 'Latency metrics'],
    howItWorks: 'Systems publish events → subscribers react independently → Event Inspector audits delivery → no direct feature coupling.',
    whenUsed: ['Module integration', 'Automation triggers', 'Debugging', 'Compliance auditing', 'Analytics pipelines'],
    relatedSystems: ['interaction-engine', 'system-registry', 'command-dock', 'automation-registry'],
    exampleWorkflows: ['PUBLISH customer.created → CHAIN REACTIONS → INSPECT DELIVERY'],
    aliases: ['event bus', 'publish subscribe', 'event driven', 'nervous system', 'eb'],
    searchKeywords: ['events', 'publish', 'subscribe', 'event inspector', 'event history'],
  }),
  entry({
    id: 'automation-registry',
    label: 'Automation Registry™',
    moduleId: 'automation-registry',
    milestone: 'M132',
    route: adminStudioAutomationRegistryPath(),
    purpose: 'Every automation registered as a visible, searchable, auditable organizational asset.',
    overview:
      'Command Dock, workflows, email, calendar, marketplace, Institute, Knowledge Commerce, Pulse, Council, documentation, scheduling, follow-ups, approvals, notifications, Legacy Vault — full metadata and execution history.',
    capabilities: ['Automation catalog', 'Dashboard visibility', 'Execution history', 'Registration gate', 'Pause/resume', 'Recommendations'],
    howItWorks: 'Register automation → track metadata → monitor dashboard → audit execution history → nothing runs unregistered.',
    whenUsed: ['Automation review', 'Compliance audit', 'Debugging failures', 'Founder transparency', 'Shadow Mode graduation'],
    relatedSystems: ['event-bus', 'shadow-mode', 'command-dock', 'autonomous-preparation'],
    exampleWorkflows: ['REGISTER AUTOMATION → MONITOR DASHBOARD → PAUSE ON FAILURE'],
    aliases: ['automation registry', 'workflow registry', 'automation catalog', 'ar'],
    searchKeywords: ['automations', 'workflows', 'transparent automation', 'execution history'],
  }),
];

export function getDocumentationSystem(id: string): DocumentationSystemEntry | undefined {
  return DOCUMENTATION_SYSTEM_REGISTRY.find((s) => s.id === id || s.moduleId === id);
}

export function getDocumentationSystemsByModuleId(moduleId: string): DocumentationSystemEntry[] {
  return DOCUMENTATION_SYSTEM_REGISTRY.filter((s) => s.moduleId === moduleId);
}

export function getAllDocumentationSystemIds(): string[] {
  return DOCUMENTATION_SYSTEM_REGISTRY.map((s) => s.id);
}
