import { MANSION_TOUR_ID } from '../../constants';
import type { TutorialTourDefinitionV2 } from '../../v2/schema';

/** The Mansion Tour V2 — 18-step ecosystem overview with feature drill-down cards. */
export const MANSION_TOUR_V2_DEF: TutorialTourDefinitionV2 = {
  id: MANSION_TOUR_ID,
  moduleName: 'The Mansion Tour',
  customerName: 'The Mansion Tour',
  productLabel: 'Onboarding Tutorial',
  description:
    'Apple-style onboarding — each page introduces itself, then every important widget can be explored individually.',
  estimatedMinutes: 5,
  status: 'enabled',
  featured: true,
  achievementId: 'explorer-badge',
  nestedTourIds: ['vouchers-walkthrough', 'wishlist-tour', 'checkout-tour'],
  linearNodeIds: [
    'welcome',
    'navigation',
    'shop-page',
    'build-a-wig-page',
    'baw-widgets',
    'signature-collection',
    'hair-analysis',
    'lounge-tv-page',
    'lounge-watch-learn',
    'concierge-page',
    'rewards-page',
    'rewards-points-widget',
    'rewards-tickets-widget',
    'wishlist-page',
    'account-page',
    'account-orders-widget',
    'cart-checkout-page',
    'finish',
  ],
  nodes: [
    {
      id: 'welcome',
      kind: 'page',
      pageId: 'home',
      title: 'WELCOME TO FRONTAL SLAYER',
      body: 'This is your interactive product manual — the Onboarding Tutorial guides you through every important feature in the mansion.',
      benefit: 'Learn by exploring the live site, not watching a video.',
      animationType: 'transition',
      position: 'center',
      spotlight: false,
      completionTrigger: 'manual',
      previewKey: 'welcome',
    },
    {
      id: 'navigation',
      kind: 'page',
      pageId: 'shop',
      title: 'NAVIGATION',
      body: 'Use the menu toggle — Shop, Tools, and Brand. Build-A-Wig, units, booking, and Slay Cam live under Shop.',
      benefit: 'Know where to go before you tap.',
      route: '/home/shop',
      targetSelector: '[data-tutorial-target="nav-menu-toggle"]',
      animationType: 'pulse',
      position: 'bottom',
      spotlight: true,
      completionTrigger: 'view',
      previewKey: 'navigation',
    },
    {
      id: 'shop-page',
      kind: 'page',
      pageId: 'shop',
      title: 'SHOP',
      body: 'Browse units, bundles, HD lace, and digital gift cards. Search from the nav crumb on any storefront page.',
      benefit: 'Find products fast without losing your place.',
      route: '/home/shop',
      animationType: 'glow',
      position: 'bottom',
      spotlight: false,
      completionTrigger: 'view',
      previewKey: 'navigation',
    },
    {
      id: 'build-a-wig-page',
      kind: 'page',
      pageId: 'build-a-wig',
      title: 'BUILD-A-WIG',
      body: 'Customize texture, color, length, density, lace, and add-ons — preview your unit before it lands in your bag.',
      benefit: 'Design your signature look step by step.',
      route: '/build-a-wig/view',
      targetSelector: '[data-attribute="baw-build-area"]',
      animationType: 'glow',
      position: 'bottom',
      spotlight: true,
      actionLabel: 'TRY BUILD-A-WIG',
      actionRoute: '/build-a-wig/view',
      completionTrigger: 'view',
      previewKey: 'build-a-wig',
      relatedTutorialIds: ['build-a-wig-tour'],
    },
    {
      id: 'baw-widgets',
      kind: 'widget',
      pageId: 'build-a-wig',
      widgetId: 'baw-options',
      title: 'CUSTOMIZATION OPTIONS',
      body: 'Each option category opens its own sub-page — length, color, lace, styling, and add-ons stack into your final configuration.',
      benefit: 'See how choices combine into one build.',
      route: '/build-a-wig/view',
      targetSelector: '[data-attribute="baw-build-area"]',
      animationType: 'zoom',
      position: 'bottom',
      spotlight: true,
      completionTrigger: 'view',
      previewKey: 'build-a-wig',
      suggestedNextTutorialId: 'build-a-wig-tour',
    },
    {
      id: 'signature-collection',
      kind: 'page',
      pageId: 'signature-collection',
      title: 'SIGNATURE COLLECTION',
      body: 'Six flagship units: NOIR, BLANCO, SOFT WAVE, BEACH WAVE, SOFT CURL, and OCEAN CURL — each with its own texture story.',
      benefit: 'Match your vibe to the right signature unit.',
      route: '/shop/units',
      targetSelector: '[data-tutorial-target="shop-units-grid"]',
      animationType: 'zoom',
      position: 'bottom',
      spotlight: true,
      actionLabel: 'BROWSE UNITS',
      actionRoute: '/shop/units',
      completionTrigger: 'view',
      previewKey: 'signature-collection',
    },
    {
      id: 'hair-analysis',
      kind: 'page',
      pageId: 'hair-analysis',
      title: 'HAIR ANALYSIS',
      body: 'Upload a selfie or inspo photo for personalized style guidance — ranked looks and unit recommendations.',
      benefit: 'Let AI help you find your best match.',
      route: '/home/tools',
      targetSelector: '[data-attribute="hairstyle-analysis-card"]',
      animationType: 'arrow',
      position: 'bottom',
      spotlight: true,
      actionLabel: 'OPEN TOOLS',
      actionRoute: '/home/tools',
      completionTrigger: 'view',
      previewKey: 'hairstyle-analysis',
      relatedTutorialIds: ['hairstyle-analysis-tour'],
    },
    {
      id: 'lounge-tv-page',
      kind: 'page',
      pageId: 'lounge-tv',
      title: 'LOUNGE TV',
      body: 'Member content in the lobby salon — Featured, Learn, Explore, Live, and Library tabs with tutorials and Slay Tips.',
      benefit: 'Learn install, care, and styling from the lounge.',
      route: '/lobby/lounge',
      animationType: 'spotlight',
      position: 'center',
      spotlight: true,
      completionTrigger: 'view',
      previewKey: 'lounge-tv',
      relatedTutorialIds: ['lounge-tv-tour'],
    },
    {
      id: 'lounge-watch-learn',
      kind: 'widget',
      pageId: 'lounge-tv',
      widgetId: 'watch-learn',
      title: 'WATCH + LEARN',
      body: 'Weekly episodes pair video with articles and checklists — unlock with tickets or membership.',
      benefit: 'Go deeper than a single tutorial clip.',
      route: '/lobby/lounge',
      animationType: 'glow',
      position: 'bottom',
      spotlight: true,
      completionTrigger: 'view',
      previewKey: 'lounge-tv',
    },
    {
      id: 'concierge-page',
      kind: 'page',
      pageId: 'concierge',
      title: 'CONCIERGE',
      body: 'Priority messages, order tracking, Slay Challenge, special offers, and founder support — your white-glove hub.',
      benefit: 'One place for VIP care after you shop.',
      route: '/account/concierge',
      animationType: 'blur',
      position: 'bottom',
      spotlight: true,
      requiresLogin: true,
      completionTrigger: 'view',
      previewKey: 'account',
    },
    {
      id: 'rewards-page',
      kind: 'page',
      pageId: 'rewards',
      title: 'REWARDS',
      body: 'Earn points, tickets, vouchers, collectibles, and tier unlocks. Tap a feature below to drill into that walkthrough.',
      benefit: 'Turn every slay into perks and savings.',
      route: '/account/rewards',
      targetSelector: '[data-tutorial-target="rewards-chart"]',
      animationType: 'glow',
      position: 'bottom',
      spotlight: true,
      requiresLogin: true,
      completionTrigger: 'view',
      previewKey: 'rewards',
      relatedTutorialIds: ['rewards-tour', 'vouchers-walkthrough'],
      featureCards: [
        {
          id: 'points',
          title: 'POINTS',
          description: 'Earn loyalty points from purchases, reviews, and engagement.',
          benefits: ['Track tier progress', 'Unlock redemptions', 'See next reward'],
          showMeRoute: '/account/rewards',
          targetSelector: '[data-tutorial-target="rewards-chart"]',
          nestedTourId: 'rewards-tour',
        },
        {
          id: 'tickets',
          title: 'SLAY TICKETS',
          description: 'Tickets unlock Lounge TV episodes and premium content.',
          benefits: ['Rent or own episodes', 'Bundle packs in Tools', 'Balance on Rewards'],
          showMeRoute: '/account/rewards',
          nestedTourId: 'rewards-tour',
        },
        {
          id: 'vouchers',
          title: 'VOUCHERS',
          description: 'Redeem points for hairline, color, styling, and cap vouchers.',
          benefits: ['Voucher balance', 'History & expiration', 'Checkout redemption'],
          showMeRoute: '/account/rewards',
          nestedTourId: 'vouchers-walkthrough',
        },
        {
          id: 'collectibles',
          title: 'COLLECTIBLES',
          description: 'Badges and unlockables celebrate milestones across the mansion.',
          benefits: ['Completion badges', 'Tier unlocks', 'Explorer rewards'],
          showMeRoute: '/account/rewards',
          nestedTourId: 'rewards-tour',
        },
      ],
    },
    {
      id: 'rewards-points-widget',
      kind: 'widget',
      pageId: 'rewards',
      featureId: 'points',
      widgetId: 'points-chart',
      title: 'LOYALTY POINTS',
      body: 'Your tier chart shows current points, next reward, and premium comparison — progress updates after every eligible order.',
      benefit: 'Always know how close you are to the next perk.',
      route: '/account/rewards',
      targetSelector: '[data-tutorial-target="rewards-chart"]',
      animationType: 'pulse',
      position: 'bottom',
      spotlight: true,
      requiresLogin: true,
      completionTrigger: 'view',
      previewKey: 'rewards',
    },
    {
      id: 'rewards-tickets-widget',
      kind: 'widget',
      pageId: 'rewards',
      featureId: 'tickets',
      widgetId: 'slay-tickets',
      title: 'SLAY TICKETS',
      body: 'Ticket balance unlocks Lounge TV content — buy packs under Tools → Slay Tickets or earn through membership.',
      benefit: 'Pay for premium lessons with tickets instead of cash.',
      route: '/tools/slay-tickets',
      animationType: 'arrow',
      position: 'bottom',
      spotlight: true,
      requiresLogin: true,
      completionTrigger: 'view',
      previewKey: 'rewards',
      searchKeywords: ['slay tickets', 'how do slay tickets work'],
    },
    {
      id: 'wishlist-page',
      kind: 'page',
      pageId: 'wishlist',
      title: 'WISHLIST',
      body: 'Save units and products you are considering — organize lists, compare, and move to bag when ready.',
      benefit: 'Track favorites without committing to cart.',
      route: '/wishlist',
      animationType: 'glow',
      position: 'bottom',
      spotlight: true,
      requiresLogin: true,
      completionTrigger: 'view',
      previewKey: 'navigation',
      relatedTutorialIds: ['wishlist-tour'],
      featureCards: [
        {
          id: 'wishlist-save',
          title: 'WISHLIST',
          description: "Save products you're considering purchasing later.",
          benefits: ['Track favorites', 'Compare products', 'Quick add to cart', 'Restock alerts'],
          showMeRoute: '/wishlist',
          nestedTourId: 'wishlist-tour',
        },
      ],
    },
    {
      id: 'account-page',
      kind: 'page',
      pageId: 'account',
      title: 'ACCOUNT',
      body: 'Dashboard for orders, membership, vouchers, tickets, saved items, messages, and settings.',
      benefit: 'One home for everything you own here.',
      route: '/account',
      animationType: 'blur',
      position: 'bottom',
      spotlight: true,
      requiresLogin: true,
      completionTrigger: 'view',
      previewKey: 'account',
      relatedTutorialIds: ['account-tour'],
    },
    {
      id: 'account-orders-widget',
      kind: 'widget',
      pageId: 'orders',
      widgetId: 'order-history',
      title: 'ORDER HISTORY',
      body: 'Active and past orders with tracking stages, consult offers, and Build-A-Wig configuration snapshots.',
      benefit: 'Revisit every build and shipment in one list.',
      route: '/account/orders',
      animationType: 'pulse',
      position: 'bottom',
      spotlight: true,
      requiresLogin: true,
      completionTrigger: 'view',
      previewKey: 'account',
    },
    {
      id: 'cart-checkout-page',
      kind: 'page',
      pageId: 'checkout',
      title: 'CART & CHECKOUT',
      body: 'Your bag keeps configuration summaries and visual snapshots — checkout confirms every choice before you pay.',
      benefit: 'Review your build before it ships.',
      route: '/bag',
      targetSelector: '[data-tutorial-target="nav-cart"]',
      animationType: 'pulse',
      position: 'bottom',
      spotlight: true,
      actionLabel: 'VIEW BAG',
      actionRoute: '/bag',
      completionTrigger: 'view',
      previewKey: 'cart-checkout',
      relatedTutorialIds: ['checkout-tour'],
    },
    {
      id: 'finish',
      kind: 'page',
      pageId: 'home',
      title: 'TOUR COMPLETE',
      body: 'You have seen the mansion — use ? Learn this page on any screen, or search the Onboarding Tutorial anytime.',
      benefit: 'You are ready to slay with confidence.',
      animationType: 'transition',
      position: 'center',
      spotlight: false,
      completionTrigger: 'manual',
      previewKey: 'finish',
    },
  ],
};
