import type { TutorialTourDefinitionV2 } from '../../v2/schema';

/** Voucher feature drill-down — 6-step nested walkthrough (Rewards → Vouchers). */
export const VOUCHERS_WALKTHROUGH_DEF: TutorialTourDefinitionV2 = {
  id: 'vouchers-walkthrough',
  moduleName: 'Voucher Walkthrough',
  customerName: 'Voucher Walkthrough',
  productLabel: 'Onboarding Tutorial',
  description: 'Learn vouchers — balance, history, redemption, expiration, and where they appear.',
  estimatedMinutes: 2,
  status: 'enabled',
  linearNodeIds: [
    'vouchers-what',
    'vouchers-balance',
    'vouchers-history',
    'vouchers-redeem',
    'vouchers-expiration',
    'vouchers-everywhere',
  ],
  nodes: [
    {
      id: 'vouchers-what',
      kind: 'feature',
      pageId: 'rewards',
      featureId: 'vouchers',
      title: 'WHAT IS A VOUCHER?',
      body: 'Vouchers are premium perks you redeem with loyalty points — hairline, color, styling, and flexible cap credits applied at checkout.',
      benefit: 'Know what you are earning before you redeem.',
      route: '/account/rewards',
      targetSelector: '[data-tutorial-target="rewards-chart"]',
      animationType: 'glow',
      position: 'bottom',
      spotlight: true,
      requiresLogin: true,
      completionTrigger: 'view',
      previewKey: 'rewards',
      searchKeywords: ['voucher', 'what is voucher'],
      suggestedNextTutorialId: 'vouchers-walkthrough',
    },
    {
      id: 'vouchers-balance',
      kind: 'widget',
      pageId: 'rewards',
      featureId: 'vouchers',
      widgetId: 'voucher-balance',
      title: 'VOUCHER BALANCE',
      body: 'Your profile tracks how many vouchers you hold by type. Redeemed vouchers reduce balance; earned vouchers increase it.',
      benefit: 'See what is available before you shop.',
      route: '/account',
      targetSelector: '[data-tutorial-target="voucher-balance"]',
      animationType: 'pulse',
      position: 'bottom',
      spotlight: true,
      requiresLogin: true,
      completionTrigger: 'view',
      previewKey: 'rewards',
    },
    {
      id: 'vouchers-history',
      kind: 'widget',
      pageId: 'account',
      featureId: 'vouchers',
      widgetId: 'voucher-history',
      title: 'VOUCHER HISTORY',
      body: 'Tap your voucher count on Account to open history — every credit and redemption with dates, organized chronologically.',
      benefit: 'Audit how vouchers were earned and spent.',
      route: '/account',
      targetSelector: '[data-tutorial-target="voucher-history-trigger"]',
      animationType: 'arrow',
      position: 'bottom',
      spotlight: true,
      requiresLogin: true,
      completionTrigger: 'view',
      previewKey: 'account',
      searchKeywords: ['voucher history', 'history'],
    },
    {
      id: 'vouchers-redeem',
      kind: 'action',
      pageId: 'rewards',
      featureId: 'vouchers',
      widgetId: 'voucher-redeem',
      title: 'REDEEMING VOUCHERS',
      body: 'Redeem from Rewards when you have enough points. The voucher lands in your balance and applies automatically on eligible checkout lines.',
      benefit: 'Turn points into real savings at checkout.',
      route: '/account/rewards',
      animationType: 'spotlight',
      position: 'bottom',
      spotlight: true,
      requiresLogin: true,
      completionTrigger: 'manual',
      previewKey: 'rewards',
      searchKeywords: ['redeem voucher', 'how do i redeem vouchers'],
    },
    {
      id: 'vouchers-expiration',
      kind: 'widget',
      pageId: 'rewards',
      featureId: 'vouchers',
      widgetId: 'voucher-expiration',
      title: 'VOUCHER EXPIRATION',
      body: 'Redeemed vouchers and reward offers stay valid for 6 months from redemption. Digital cash and gift card balances do not expire.',
      benefit: 'Use perks before they lapse.',
      route: '/account/rewards',
      animationType: 'blur',
      position: 'bottom',
      spotlight: false,
      requiresLogin: true,
      completionTrigger: 'manual',
      previewKey: 'rewards',
      searchKeywords: ['voucher expiration', 'expire'],
    },
    {
      id: 'vouchers-everywhere',
      kind: 'action',
      pageId: 'rewards',
      featureId: 'vouchers',
      title: 'VOUCHERS ACROSS THE SITE',
      body: 'Vouchers surface on Account, Rewards, checkout summaries, and tier benefits — one balance follows you everywhere.',
      benefit: 'Never lose track of perks mid-order.',
      route: '/account/rewards',
      animationType: 'transition',
      position: 'center',
      spotlight: false,
      requiresLogin: true,
      completionTrigger: 'manual',
      previewKey: 'finish',
      relatedTutorialIds: ['checkout-tour'],
    },
  ],
};
