/**
 * Static catalog of every Account → Alerts row variant — for copy review / debug UI.
 * Mirrors getAccountNotifications(), orderAccountAlerts, wishlist/unit stock, order tracking, admin sent.
 */

export type AccountAlertRowVariant = 'standard' | 'consult_offer_ready';

export type AccountAlertCatalogEntry = {
  variantId: string;
  categoryKey: string;
  variantLabel: string;
  /** Typical notification id prefix or pattern. */
  idPattern: string;
  title: string;
  message: string;
  actionText: string;
  actionRoute: string;
  rowVariant: AccountAlertRowVariant;
  source: string;
  notes?: string;
  newAccountOnly?: boolean;
  activityAccountOnly?: boolean;
  adminOnly?: boolean;
};

export type AccountAlertCatalogCategory = {
  categoryKey: string;
  label: string;
  description: string;
  sortOrder: number;
  entries: AccountAlertCatalogEntry[];
};

const SAMPLE = {
  orderNumber: '332',
  orderRef: 'ORDER #332',
  tier: 'RED',
  voucherCount: 3,
  voucherType: 'COLOR',
  balance: '125.00',
  loyaltyPoints: '2,450',
  affiliatePoints: '180',
  referralCode: 'SLAY24',
  activeOrders: 2,
  pastOrders: 5,
  unitName: 'NOIR',
  stageLabel: 'CONSTRUCTING UNIT',
  trackingNote: 'YOUR UNIT IS BEING BUILT.',
  adminHeader: 'MEMBERSHIP · PERK',
  adminBody: 'YOU UNLOCKED EARLY ACCESS TO THE DROP.',
} as const;

/** All account alert copy variants, grouped by category (display order). */
export function getAccountAlertsCatalog(): AccountAlertCatalogCategory[] {
  const catalog: AccountAlertCatalogCategory[] = [
    {
      categoryKey: 'order_received',
      label: 'Order received',
      description: 'Appended when checkout completes — id order_received_{orderId}. Stays in NEW until archived.',
      sortOrder: 1,
      entries: [
        {
          variantId: 'order_received.standard',
          categoryKey: 'order_received',
          variantLabel: 'Order placed / processing',
          idPattern: 'order_received_{orderId}',
          title: "WE'VE RECEIVED YOUR ORDER!",
          message: `ORDER #${SAMPLE.orderNumber} IS BEING PROCESSED.`,
          actionText: 'VIEW DETAILS',
          actionRoute: '/account/orders?orderId=…',
          rowVariant: 'standard',
          source: 'orderAccountAlerts.buildOrderReceivedAccountAlert',
        },
        {
          variantId: 'order_received.concierge',
          categoryKey: 'order_received',
          variantLabel: 'Premium / consult → concierge route',
          idPattern: 'order_received_{orderId}',
          title: "WE'VE RECEIVED YOUR ORDER!",
          message: `ORDER #${SAMPLE.orderNumber} IS BEING PROCESSED.`,
          actionText: 'VIEW DETAILS',
          actionRoute: '/account/concierge?orderId=…',
          rowVariant: 'standard',
          source: 'orderAccountAlerts.alertRouteForOrder (premium/consult)',
          notes: 'Same copy; actionRoute differs for premium or consult booking flow.',
        },
      ],
    },
    {
      categoryKey: 'consult_offer',
      label: 'Consult offer ready',
      description: 'Admin sends consult quote — consult_offer_ready row styling metadata.',
      sortOrder: 2,
      entries: [
        {
          variantId: 'consult_offer.sent_local',
          categoryKey: 'consult_offer',
          variantLabel: 'Consult offer sent (local)',
          idPattern: 'consult_offer_sent_{quoteId}',
          title: 'YOUR ORDER IS READY!',
          message: `ORDER #${SAMPLE.orderNumber} IS COMPLETE.`,
          actionText: 'VIEW OFFER',
          actionRoute: '/account/orders?orderId=…&consultOffer=1',
          rowVariant: 'consult_offer_ready',
          source: 'orderAccountAlerts.appendConsultOfferCompleteAccountAlert',
        },
        {
          variantId: 'consult_offer.admin_migrated',
          categoryKey: 'consult_offer',
          variantLabel: 'Migrated admin / legacy consult row',
          idPattern: 'admin_* or legacy consult title',
          title: 'YOUR ORDER IS READY!',
          message: `ORDER #${SAMPLE.orderNumber} IS COMPLETE.`,
          actionText: 'VIEW OFFER',
          actionRoute: '/account/orders?orderNumber=332&consultOffer=1',
          rowVariant: 'consult_offer_ready',
          source: 'notifications/page.migrateConsultYourOrderReadyNotification',
          notes: 'Legacy titles containing YOUR ORDER IS READY + CONSULT are normalized to this copy.',
        },
      ],
    },
    {
      categoryKey: 'order_tracking',
      label: 'Order tracking update',
      description: 'Pipeline stage notes from admin — id order_track_{orderId}_{timestamp}.',
      sortOrder: 3,
      entries: [
        {
          variantId: 'order_tracking.with_note',
          categoryKey: 'order_tracking',
          variantLabel: 'Stage + note',
          idPattern: 'order_track_{orderId}_{ts}',
          title: 'ORDER TRACKING UPDATE',
          message: `${SAMPLE.stageLabel}: ${SAMPLE.trackingNote}`,
          actionText: 'VIEW TRACKING',
          actionRoute: '/account/concierge?orderId=…',
          rowVariant: 'standard',
          source: 'orderTracking.appendOrderTrackingClientNotification',
        },
        {
          variantId: 'order_tracking.fallback_message',
          categoryKey: 'order_tracking',
          variantLabel: 'Empty note fallback',
          idPattern: 'order_track_{orderId}_{ts}',
          title: 'ORDER TRACKING UPDATE',
          message: 'VIEW YOUR ORDER FOR DETAILS.',
          actionText: 'VIEW TRACKING',
          actionRoute: '/account/concierge?orderId=…',
          rowVariant: 'standard',
          source: 'orderTracking.appendOrderTrackingClientNotification',
        },
      ],
    },
    {
      categoryKey: 'stock_wishlist',
      label: 'Stock — wishlist',
      description: 'Wishlist inventory transitions — id wishlist_{kind}_{trackKey}.',
      sortOrder: 4,
      entries: [
        {
          variantId: 'stock_wishlist.low_stock',
          categoryKey: 'stock_wishlist',
          variantLabel: 'Low stock on wishlist',
          idPattern: 'wishlist_low_stock_{unit}',
          title: 'LOW STOCK: ACT FAST!',
          message: 'YOUR WISHLIST ITEM IS LOW IN STOCK.',
          actionText: 'VIEW PRODUCT',
          actionRoute: '/build-a-wig/noir (product route)',
          rowVariant: 'standard',
          source: 'wishlistStockAlerts.appendWishlistStockAlert',
        },
        {
          variantId: 'stock_wishlist.back_in_stock',
          categoryKey: 'stock_wishlist',
          variantLabel: 'Back in stock on wishlist',
          idPattern: 'wishlist_back_in_stock_{unit}',
          title: 'BACK IN STOCK: SHOP NOW!',
          message: 'YOUR WISHLIST ITEM IS BACK IN STOCK.',
          actionText: 'VIEW PRODUCT',
          actionRoute: '/build-a-wig/noir (product route)',
          rowVariant: 'standard',
          source: 'wishlistStockAlerts.appendWishlistStockAlert',
        },
      ],
    },
    {
      categoryKey: 'stock_unit',
      label: 'Stock — unit notify',
      description: 'Waitlist signup confirmation + back-in-stock product alerts.',
      sortOrder: 5,
      entries: [
        {
          variantId: 'stock_unit.notify_signup',
          categoryKey: 'stock_unit',
          variantLabel: 'Notify-me signup confirmation',
          idPattern: 'stock_notify_signup_{unit}',
          title: `${SAMPLE.unitName} — BACK IN STOCK`,
          message: `WE'LL NOTIFY YOU WHEN ${SAMPLE.unitName} IS AVAILABLE AGAIN.`,
          actionText: 'VIEW SHOP',
          actionRoute: '/home/shop',
          rowVariant: 'standard',
          source: 'unitStockNotify.appendStockNotifySignupAlert',
        },
        {
          variantId: 'stock_unit.back_in_stock',
          categoryKey: 'stock_unit',
          variantLabel: 'Unit back in stock',
          idPattern: 'stock_back_in_stock_{unit}_{ts}',
          title: `${SAMPLE.unitName} IS BACK IN STOCK`,
          message: `${SAMPLE.unitName} IS AVAILABLE NOW — SHOP BEFORE IT SELLS OUT.`,
          actionText: 'SHOP NOW',
          actionRoute: '/home/shop',
          rowVariant: 'standard',
          source: 'unitStockNotify.appendBackInStockAlert',
        },
      ],
    },
    {
      categoryKey: 'onboarding_tier',
      label: 'Onboarding — tier status',
      description: 'acc_tier — shown for all accounts; new accounts stop after core onboarding set.',
      sortOrder: 6,
      entries: [
        {
          variantId: 'onboarding_tier.pending',
          categoryKey: 'onboarding_tier',
          variantLabel: 'No spend tier yet',
          idPattern: 'acc_tier',
          title: 'NO SPEND TIER YET',
          message: 'EARN 1,000 POINTS TO UNLOCK SILVER TIER.',
          actionText: 'VIEW TIER',
          actionRoute: '/account/rewards',
          rowVariant: 'standard',
          source: 'notifications/page.getAccountNotifications',
          newAccountOnly: true,
        },
        {
          variantId: 'onboarding_tier.unlocked',
          categoryKey: 'onboarding_tier',
          variantLabel: 'Tier unlocked',
          idPattern: 'acc_tier',
          title: `YOU'RE NOW ${SAMPLE.tier} TIER STATUS`,
          message: 'VIEW YOUR TIER BENEFITS ON REWARDS PAGE.',
          actionText: 'VIEW TIER',
          actionRoute: '/account/rewards',
          rowVariant: 'standard',
          source: 'notifications/page.getAccountNotifications',
        },
      ],
    },
    {
      categoryKey: 'onboarding_membership',
      label: 'Onboarding — membership',
      description: 'acc_membership — premium vs standard member state.',
      sortOrder: 7,
      entries: [
        {
          variantId: 'onboarding_membership.premium',
          categoryKey: 'onboarding_membership',
          variantLabel: 'Premium active',
          idPattern: 'acc_membership',
          title: 'PREMIUM MEMBERSHIP IS ACTIVE',
          message: 'MANAGE YOUR PREMIUM PERKS ON REWARDS PAGE.',
          actionText: 'VIEW MEMBERSHIP',
          actionRoute: '/account/rewards',
          rowVariant: 'standard',
          source: 'notifications/page.getAccountNotifications',
        },
        {
          variantId: 'onboarding_membership.standard',
          categoryKey: 'onboarding_membership',
          variantLabel: 'Standard member',
          idPattern: 'acc_membership',
          title: "YOU'RE STANDARD MEMBER",
          message: 'UPGRADE TO PREMIUM FOR 2X POINTS + PERKS.',
          actionText: 'VIEW MEMBERSHIP',
          actionRoute: '/account/rewards',
          rowVariant: 'standard',
          source: 'notifications/page.getAccountNotifications',
        },
      ],
    },
    {
      categoryKey: 'onboarding_shipping',
      label: 'Onboarding — shipping + payment',
      description: 'acc_shipping_payment — four address/payment combinations.',
      sortOrder: 8,
      entries: [
        {
          variantId: 'onboarding_shipping.both',
          categoryKey: 'onboarding_shipping',
          variantLabel: 'Address + payment saved',
          idPattern: 'acc_shipping_payment',
          title: 'SHIPPING + PAYMENT SAVED',
          message: 'UPDATE YOUR SAVED ADDRESS + PAYMENT IN SETTINGS.',
          actionText: 'MANAGE',
          actionRoute: '/account/shipping',
          rowVariant: 'standard',
          source: 'notifications/page.getAccountNotifications',
        },
        {
          variantId: 'onboarding_shipping.address_only',
          categoryKey: 'onboarding_shipping',
          variantLabel: 'Address only',
          idPattern: 'acc_shipping_payment',
          title: 'SHIPPING SAVED, ADD PAYMENT',
          message: 'ADD A PAYMENT METHOD IN SETTINGS.',
          actionText: 'MANAGE',
          actionRoute: '/account/shipping',
          rowVariant: 'standard',
          source: 'notifications/page.getAccountNotifications',
        },
        {
          variantId: 'onboarding_shipping.payment_only',
          categoryKey: 'onboarding_shipping',
          variantLabel: 'Payment only',
          idPattern: 'acc_shipping_payment',
          title: 'PAYMENT SAVED, ADD SHIPPING',
          message: 'ADD A SHIPPING ADDRESS IN SETTINGS.',
          actionText: 'MANAGE',
          actionRoute: '/account/shipping',
          rowVariant: 'standard',
          source: 'notifications/page.getAccountNotifications',
        },
        {
          variantId: 'onboarding_shipping.neither',
          categoryKey: 'onboarding_shipping',
          variantLabel: 'Neither saved',
          idPattern: 'acc_shipping_payment',
          title: 'ADD SHIPPING + PAYMENT',
          message: 'ADD SHIPPING + PAYMENT IN SETTINGS.',
          actionText: 'MANAGE',
          actionRoute: '/account/shipping',
          rowVariant: 'standard',
          source: 'notifications/page.getAccountNotifications',
        },
      ],
    },
    {
      categoryKey: 'onboarding_profile',
      label: 'Onboarding — profile',
      description: 'acc_settings — update profile prompt.',
      sortOrder: 9,
      entries: [
        {
          variantId: 'onboarding_profile.settings',
          categoryKey: 'onboarding_profile',
          variantLabel: 'Update profile',
          idPattern: 'acc_settings',
          title: 'UPDATE PROFILE + PREFERENCES',
          message: 'KEEP YOUR PROFILE + PREFERENCES UP TO DATE.',
          actionText: 'OPEN SETTINGS',
          actionRoute: '/account/settings',
          rowVariant: 'standard',
          source: 'notifications/page.getAccountNotifications',
        },
      ],
    },
    {
      categoryKey: 'vouchers',
      label: 'Vouchers',
      description: 'acc_voucher + expiring voucher rows (activity accounts).',
      sortOrder: 10,
      entries: [
        {
          variantId: 'vouchers.none',
          categoryKey: 'vouchers',
          variantLabel: 'No vouchers yet',
          idPattern: 'acc_voucher',
          title: 'NO VOUCHERS AVAILABLE YET',
          message: 'REDEEM POINTS FOR VOUCHERS ON REWARDS PAGE.',
          actionText: 'VIEW VOUCHERS',
          actionRoute: '/account',
          rowVariant: 'standard',
          source: 'notifications/page.getAccountNotifications',
          activityAccountOnly: true,
        },
        {
          variantId: 'vouchers.available',
          categoryKey: 'vouchers',
          variantLabel: 'Vouchers available',
          idPattern: 'acc_voucher',
          title: `${SAMPLE.voucherCount} VOUCHERS AVAILABLE`,
          message: 'YOU HAVE VOUCHERS READY TO APPLY AT CHECKOUT.',
          actionText: 'VIEW VOUCHERS',
          actionRoute: '/account',
          rowVariant: 'standard',
          source: 'notifications/page.getAccountNotifications',
          activityAccountOnly: true,
        },
        {
          variantId: 'vouchers.expiring_24h',
          categoryKey: 'vouchers',
          variantLabel: 'Expiring in 24 hours',
          idPattern: 'acc_voucher_expiring_{type}_{ts}',
          title: 'FREE VOUCHER EXPIRING SOON',
          message: `YOUR ${SAMPLE.voucherType} VOUCHER EXPIRES IN 24 HOURS.`,
          actionText: 'VIEW VOUCHERS',
          actionRoute: '/account',
          rowVariant: 'standard',
          source: 'notifications/page.getAccountNotifications',
          activityAccountOnly: true,
        },
        {
          variantId: 'vouchers.expiring_1w',
          categoryKey: 'vouchers',
          variantLabel: 'Expiring in 1 week',
          idPattern: 'acc_voucher_expiring_{type}_{ts}',
          title: 'FREE VOUCHER EXPIRING SOON',
          message: `YOUR ${SAMPLE.voucherType} VOUCHER EXPIRES IN 1 WEEK.`,
          actionText: 'VIEW VOUCHERS',
          actionRoute: '/account',
          rowVariant: 'standard',
          source: 'notifications/page.getAccountNotifications',
          activityAccountOnly: true,
        },
        {
          variantId: 'vouchers.expiring_1m',
          categoryKey: 'vouchers',
          variantLabel: 'Expiring in 1 month',
          idPattern: 'acc_voucher_expiring_{type}_{ts}',
          title: 'FREE VOUCHER EXPIRING SOON',
          message: `YOUR ${SAMPLE.voucherType} VOUCHER EXPIRES IN 1 MONTH.`,
          actionText: 'VIEW VOUCHERS',
          actionRoute: '/account',
          rowVariant: 'standard',
          source: 'notifications/page.getAccountNotifications',
          activityAccountOnly: true,
        },
      ],
    },
    {
      categoryKey: 'rewards_balance',
      label: 'Digital cash & loyalty',
      description: 'acc_digital_cash and acc_loyalty_points (when points > 0).',
      sortOrder: 11,
      entries: [
        {
          variantId: 'rewards_balance.digital_cash_zero',
          categoryKey: 'rewards_balance',
          variantLabel: 'Digital cash — zero balance',
          idPattern: 'acc_digital_cash',
          title: 'DIGITAL CASH BALANCE',
          message: 'EARN CREDIT VIA TIER DISCOUNTS OR REWARDS.',
          actionText: 'VIEW BALANCE',
          actionRoute: '/account',
          rowVariant: 'standard',
          source: 'notifications/page.getAccountNotifications',
          activityAccountOnly: true,
        },
        {
          variantId: 'rewards_balance.digital_cash_positive',
          categoryKey: 'rewards_balance',
          variantLabel: 'Digital cash — positive balance',
          idPattern: 'acc_digital_cash',
          title: 'DIGITAL CASH BALANCE',
          message: `$${SAMPLE.balance} USD APPLIES AT CHECKOUT + NEVER EXPIRES.`,
          actionText: 'VIEW BALANCE',
          actionRoute: '/account',
          rowVariant: 'standard',
          source: 'notifications/page.getAccountNotifications',
          activityAccountOnly: true,
        },
        {
          variantId: 'rewards_balance.loyalty_points',
          categoryKey: 'rewards_balance',
          variantLabel: 'Loyalty points (when > 0)',
          idPattern: 'acc_loyalty_points',
          title: `YOU HAVE ${SAMPLE.loyaltyPoints} LOYALTY PTS`,
          message: 'EARN + REDEEM POINTS FOR VOUCHERS + CASH.',
          actionText: 'VIEW REWARDS',
          actionRoute: '/account/rewards',
          rowVariant: 'standard',
          source: 'notifications/page.getAccountNotifications',
          activityAccountOnly: true,
        },
      ],
    },
    {
      categoryKey: 'orders_summary',
      label: 'Orders summary',
      description: 'acc_order — synthetic order history summary row.',
      sortOrder: 12,
      entries: [
        {
          variantId: 'orders_summary.none',
          categoryKey: 'orders_summary',
          variantLabel: 'No orders yet',
          idPattern: 'acc_order',
          title: 'NO ORDERS AVAILABLE YET',
          message: 'TRACK + VIEW YOUR ORDERS ON ORDERS PAGE.',
          actionText: 'VIEW ORDERS',
          actionRoute: '/account/orders',
          rowVariant: 'standard',
          source: 'notifications/page.getAccountNotifications',
          activityAccountOnly: true,
        },
        {
          variantId: 'orders_summary.has_orders',
          categoryKey: 'orders_summary',
          variantLabel: 'Active + past orders',
          idPattern: 'acc_order',
          title: `${SAMPLE.activeOrders} ACTIVE, ${SAMPLE.pastOrders} PAST ORDERS`,
          message: 'VIEW ORDER STATUS + TRACK SHIPPING HERE.',
          actionText: 'VIEW ORDERS',
          actionRoute: '/account/orders',
          rowVariant: 'standard',
          source: 'notifications/page.getAccountNotifications',
          activityAccountOnly: true,
        },
        {
          variantId: 'orders_summary.fallback',
          categoryKey: 'orders_summary',
          variantLabel: 'Parse error fallback',
          idPattern: 'acc_order',
          title: 'ORDER HISTORY IS AVAILABLE',
          message: 'TRACK + VIEW YOUR ORDERS ON ORDERS PAGE.',
          actionText: 'VIEW ORDERS',
          actionRoute: '/account/orders',
          rowVariant: 'standard',
          source: 'notifications/page.getAccountNotifications',
          activityAccountOnly: true,
        },
      ],
    },
    {
      categoryKey: 'rewards_program',
      label: 'Rewards & member sales',
      description: 'acc_rewards and acc_sales overview rows.',
      sortOrder: 13,
      entries: [
        {
          variantId: 'rewards_program.overview',
          categoryKey: 'rewards_program',
          variantLabel: 'Rewards program',
          idPattern: 'acc_rewards',
          title: 'REWARDS PROGRAM OVERVIEW PAGE',
          message: 'EARN + REDEEM POINTS ON REWARDS PAGE.',
          actionText: 'VIEW REWARDS',
          actionRoute: '/account/rewards',
          rowVariant: 'standard',
          source: 'notifications/page.getAccountNotifications',
          activityAccountOnly: true,
        },
        {
          variantId: 'rewards_program.sales',
          categoryKey: 'rewards_program',
          variantLabel: 'Member sales',
          idPattern: 'acc_sales',
          title: 'MEMBER SALES + TIER DISCOUNTS',
          message: 'SHOP MEMBER SALES + TIER DISCOUNTS NOW.',
          actionText: 'SHOP',
          actionRoute: '/build-a-wig',
          rowVariant: 'standard',
          source: 'notifications/page.getAccountNotifications',
          activityAccountOnly: true,
        },
      ],
    },
    {
      categoryKey: 'referrals_affiliate',
      label: 'Referrals & affiliate',
      description: 'acc_referrals and acc_affiliate rows.',
      sortOrder: 14,
      entries: [
        {
          variantId: 'referrals.with_code',
          categoryKey: 'referrals_affiliate',
          variantLabel: 'Referral code assigned',
          idPattern: 'acc_referrals',
          title: `YOUR REFERRAL CODE ${SAMPLE.referralCode}`,
          message: 'SHARE YOUR CODE + EARN WHEN FRIENDS JOIN.',
          actionText: 'VIEW REFERRALS',
          actionRoute: '/account/referrals',
          rowVariant: 'standard',
          source: 'notifications/page.getAccountNotifications',
          activityAccountOnly: true,
        },
        {
          variantId: 'referrals.no_code',
          categoryKey: 'referrals_affiliate',
          variantLabel: 'No referral code yet',
          idPattern: 'acc_referrals',
          title: 'GET REFERRAL CODE + EARN',
          message: 'GET YOUR REFERRAL CODE ON REFERRALS PAGE.',
          actionText: 'VIEW REFERRALS',
          actionRoute: '/account/referrals',
          rowVariant: 'standard',
          source: 'notifications/page.getAccountNotifications',
          activityAccountOnly: true,
        },
        {
          variantId: 'affiliate.has_points',
          categoryKey: 'referrals_affiliate',
          variantLabel: 'Affiliate points balance',
          idPattern: 'acc_affiliate',
          title: `YOU HAVE ${SAMPLE.affiliatePoints} AFFILIATE PTS`,
          message: 'REDEEM ON AFFILIATE PAGE.',
          actionText: 'VIEW AFFILIATE',
          actionRoute: '/account/affiliate',
          rowVariant: 'standard',
          source: 'notifications/page.getAccountNotifications',
          activityAccountOnly: true,
        },
        {
          variantId: 'affiliate.no_points',
          categoryKey: 'referrals_affiliate',
          variantLabel: 'No affiliate points yet',
          idPattern: 'acc_affiliate',
          title: 'EARN AFFILIATE POINTS NOW',
          message: 'SUBMIT CONTENT TO EARN AFFILIATE POINTS.',
          actionText: 'VIEW AFFILIATE',
          actionRoute: '/account/affiliate',
          rowVariant: 'standard',
          source: 'notifications/page.getAccountNotifications',
          activityAccountOnly: true,
        },
      ],
    },
    {
      categoryKey: 'admin_sent',
      label: 'Admin-sent messages',
      description: 'Supabase admin notifications — id admin_{id}. Parsed from [HEADER · TOPIC] body format.',
      sortOrder: 15,
      entries: [
        {
          variantId: 'admin_sent.bracket_format',
          categoryKey: 'admin_sent',
          variantLabel: 'Bracket format [HEADER · TOPIC]',
          idPattern: 'admin_{supabaseId}',
          title: SAMPLE.adminHeader,
          message: SAMPLE.adminBody,
          actionText: '(optional from API)',
          actionRoute: '(optional from API)',
          rowVariant: 'standard',
          source: 'notifications/page.parseAdminSentNotificationText',
        },
        {
          variantId: 'admin_sent.plain_fallback',
          categoryKey: 'admin_sent',
          variantLabel: 'Plain text fallback',
          idPattern: 'admin_{supabaseId}',
          title: 'ALERT',
          message: 'YOUR CUSTOM MESSAGE FROM ADMIN APPEARS HERE.',
          actionText: '(optional)',
          actionRoute: '(optional)',
          rowVariant: 'standard',
          source: 'notifications/page.parseAdminSentNotificationText',
          notes: 'When text is not [bracket] format, title becomes ALERT and body is full text uppercased.',
        },
      ],
    },
    {
      categoryKey: 'admin_mock_vouchers',
      label: 'Admin mock voucher expiring (founder only)',
      description: 'Extra expiring voucher rows for isAyoteenzAdminAccount — copy QA only.',
      sortOrder: 16,
      entries: [
        {
          variantId: 'admin_mock_voucher.expiring',
          categoryKey: 'admin_mock_vouchers',
          variantLabel: 'Mock expiring voucher',
          idPattern: 'acc_voucher_expiring_mock_{TYPE}_{24h|1w|1m}',
          title: 'FREE VOUCHER EXPIRING SOON',
          message: `YOUR ${SAMPLE.voucherType} VOUCHER EXPIRES IN 24 HOURS.`,
          actionText: 'VIEW VOUCHERS',
          actionRoute: '/account',
          rowVariant: 'standard',
          source: 'notifications/page.getAccountNotifications',
          adminOnly: true,
          notes: 'Types: COLOR, HAIRLINE, STYLING, FLEXIBLE CAP × 24H / 1W / 1M.',
        },
      ],
    },
  ];

  return catalog.sort((a, b) => a.sortOrder - b.sortOrder);
}

export function formatAccountAlertEntryForCopy(entry: AccountAlertCatalogEntry): string {
  const lines = [
    `VARIANT: ${entry.variantId}`,
    `ID PATTERN: ${entry.idPattern}`,
    `ROW VARIANT: ${entry.rowVariant}`,
    `SOURCE: ${entry.source}`,
    `TITLE: ${entry.title}`,
    `MESSAGE: ${entry.message}`,
    `ACTION: ${entry.actionText}`,
    `ROUTE: ${entry.actionRoute}`,
  ];
  if (entry.newAccountOnly) lines.push('SCOPE: new account (no first purchase)');
  if (entry.activityAccountOnly) lines.push('SCOPE: activity account (hasMadeFirstPurchase)');
  if (entry.adminOnly) lines.push('SCOPE: founder admin account only');
  if (entry.notes) lines.push(`NOTES: ${entry.notes}`);
  return lines.join('\n');
}

export function formatFullAccountAlertsCatalogForCopy(
  categories = getAccountAlertsCatalog()
): string {
  return categories
    .map((cat) => {
      const header = `# ${cat.sortOrder}. ${cat.label.toUpperCase()}\n${cat.description}\n`;
      const blocks = cat.entries.map((e) => formatAccountAlertEntryForCopy(e)).join('\n\n---\n\n');
      return `${header}\n${blocks}`;
    })
    .join('\n\n==========\n\n');
}
