import { STUDIO_OS_OFFICIAL_TAGLINE } from '../studio-os-core/brand-positioning';
import { KNOWLEDGE_COMMERCE_BRAND_PROMISE, KNOWLEDGE_COMMERCE_PHILOSOPHY } from '../studio-os-core/knowledge-commerce/constants';

export const KNOWLEDGE_COMMERCE_PAGE_SUBTITLE = `${STUDIO_OS_OFFICIAL_TAGLINE} · ${KNOWLEDGE_COMMERCE_BRAND_PROMISE}`;

export const KNOWLEDGE_COMMERCE_PAGE_PHILOSOPHY = KNOWLEDGE_COMMERCE_PHILOSOPHY[0];
