/** Prompt Library — editable master prompts (CMS-ready, no AI). */

export type AdminStudioPromptCategoryId =
  | 'slay-report'
  | 'slay-lab'
  | 'campaign'
  | 'build-studio'
  | 'academy'
  | 'journal'
  | 'email'
  | 'pinterest'
  | 'thumbnail';

export type AdminStudioPromptEntry = {
  id: AdminStudioPromptCategoryId;
  title: string;
  category: string;
  description: string;
  body: string;
  tags: string[];
};

export const ADMIN_STUDIO_PROMPT_CATEGORIES: Array<{ id: AdminStudioPromptCategoryId; label: string }> = [
  { id: 'slay-report', label: 'SLAY REPORT' },
  { id: 'slay-lab', label: 'SLAY LAB' },
  { id: 'campaign', label: 'CAMPAIGN' },
  { id: 'build-studio', label: 'BUILD STUDIO' },
  { id: 'academy', label: 'ACADEMY' },
  { id: 'journal', label: 'JOURNAL' },
  { id: 'email', label: 'EMAIL' },
  { id: 'pinterest', label: 'PINTEREST' },
  { id: 'thumbnail', label: 'THUMBNAIL' },
];

export const ADMIN_STUDIO_DEFAULT_PROMPTS: AdminStudioPromptEntry[] = [
  {
    id: 'slay-report',
    title: 'SLAY REPORT — WEEKLY BRIEFING',
    category: 'SLAY REPORT',
    description: 'NEWSROOM OPEN, TREND SEGMENTS, MEMBER WINS, FRIDAY PREMIERE CTA.',
    tags: ['WEEKLY', 'LOUNGE', 'NEWSROOM'],
    body: `ROLE: FRONTAL SLAYER NEWSROOM HOST — CONFIDENT, WARM, NO GATEKEEPING.

STRUCTURE:
1. COLD OPEN — HOOK THE WEEK'S BIGGEST SLAY STORY
2. TREND RADAR — COLOR, TEXTURE, OR TECHNIQUE ON THE RISE
3. MEMBER SPOTLIGHT — ONE WIN FROM THE LOUNGE
4. WHAT TO WATCH — TEASE UPCOMING CONTENT PACK
5. CLOSE — FRIDAY 7PM PREMIERE CTA + SLAY BOARD SAVE

TONE: EDUCATOR + HAIR BESTIE. TRUST OVER SALES.`,
  },
  {
    id: 'slay-lab',
    title: 'SLAY LAB — EXPERIMENT SCRIPT',
    category: 'SLAY LAB',
    description: 'HYPOTHESIS, TOOLS, STEP-BY-STEP TEST, MEASURED RESULT.',
    tags: ['BI-WEEKLY', 'TECHNIQUE', 'MACRO'],
    body: `ROLE: LAB HOST — PRECISE, ENCOURAGING, STEP-BY-STEP.

STRUCTURE:
1. HYPOTHESIS — WHAT ARE WE TESTING TODAY?
2. TOOLS ON DECK — LIST PRODUCTS + WHY
3. PROCEDURE — NUMBERED STEPS WITH MACRO SHOTS
4. RESULT — BEFORE/AFTER WITH HONEST NOTES
5. LAB NOTES CTA — SAVE TO LOUNGE LIBRARY

AVOID HYPE. SHOW THE WORK.`,
  },
  {
    id: 'campaign',
    title: 'CAMPAIGN — BRAND FILM NARRATIVE',
    category: 'CAMPAIGN',
    description: 'SEASONAL STORY ARC, HERO REVEAL, SHOP THE LOOK CLOSE.',
    tags: ['SEASONAL', 'CINEMATIC', 'BRAND'],
    body: `ROLE: BRAND VOICE — ASPIRATIONAL, BOLD, BUILT FOR WOMEN WHO SLAY.

STRUCTURE:
1. OPENING MANIFESTO — 15 SEC BRAND STATEMENT
2. HERO LOOK — ON-LOCATION OR STUDIO CYC
3. PRODUCT MOMENTS — 3 ANGLES, NO HARD SELL
4. COMMUNITY CUT — REAL SLAYERS, REAL TEXTURE
5. END CARD — LOGO LOCKUP + SHOP THE CAMPAIGN

MUSIC: CAMPAIGN SCORE · BRAND ANTHEM BED.`,
  },
  {
    id: 'build-studio',
    title: 'BUILD STUDIO — UNIT WALKTHROUGH',
    category: 'BUILD STUDIO',
    description: 'SWATCH TO SLAY — CUSTOMIZE, PREVIEW, CONFIRM BUILD.',
    tags: ['BUILD-A-WIG', 'PRODUCT', '3-ANGLE'],
    body: `ROLE: PRODUCT EDUCATOR — CLEAR OPTIONS, NO OVERWHELM.

STRUCTURE:
1. UNIT INTRO — NAME, TEXTURE, BEST FOR
2. COLOR + LENGTH OPTIONS — SWATCH MORPH SHOTS
3. LIVE PREVIEW — 3-ANGLE MANNEQUIN HERO
4. ADD-ONS — LACE, DENSITY, STYLING RECS
5. CONFIRM CTA — SAVE BUILD · ADD TO BAG

MAP EVERY OPTION TO REAL CATALOG SKUs.`,
  },
  {
    id: 'academy',
    title: 'ACADEMY — LESSON PACK',
    category: 'ACADEMY',
    description: 'LESSON OBJECTIVE, WATCH EPISODE, READ GUIDE, QUIZ CARD.',
    tags: ['LESSON', 'EDUCATION', 'SLAY CREDIT'],
    body: `ROLE: TEACHER — PATIENT, CLEAR, STRUCTURED.

STRUCTURE:
1. LESSON SLATE — NUMBER + DIFFICULTY BADGE
2. LEARNING OBJECTIVE — ONE SENTENCE OUTCOME
3. WATCH SEGMENT — 8 MIN EPISODE OUTLINE
4. READ GUIDE — 4 MIN JOURNAL TAKEAWAYS
5. COMPLETE LESSON — SLAY CHALLENGE + CREDIT

PAIR VIDEO + ARTICLE FOR BOTH FORMAT BADGE.`,
  },
  {
    id: 'journal',
    title: 'JOURNAL — LONGFORM GUIDE',
    category: 'JOURNAL',
    description: 'HEADLINE, INTRO, STEPS, TAKEAWAYS, SHOP CTA.',
    tags: ['READ', 'SEO', 'GUIDE'],
    body: `ROLE: EDITORIAL WRITER — SCANNABLE, UPPERCASE HEADERS, ACTIONABLE.

STRUCTURE:
1. HEADLINE + READ TIME
2. INTRO — WHY THIS MATTERS NOW
3. STEPS OR SECTIONS — NUMBERED, BOLD SUBHEADS
4. KEY TAKEAWAYS — BULLET BLOCK
5. SHOP THIS LOOK — 1–2 CATALOG UNITS

KEEP PARAGRAPHS SHORT. MOBILE-FIRST READING.`,
  },
  {
    id: 'email',
    title: 'EMAIL — PACK DROP',
    category: 'EMAIL',
    description: 'SUBJECT, PREHEADER, BODY, LOUNGE DEEP LINK.',
    tags: ['EMAIL', 'CRM', 'DROP'],
    body: `ROLE: CRM COPY — WARM, DIRECT, ONE PRIMARY CTA.

FIELDS:
- SUBJECT: YOUR [PACK NAME] IS LIVE
- PREHEADER: WATCH + READ THIS WEEK IN THE LOUNGE
- BODY: HEY SLAYER — 2 SHORT PARAS + BULLET HIGHLIGHTS
- CTA BUTTON: WATCH IN THE LOUNGE
- FOOTER: UNSUBSCRIBE + BRAND SIGNATURE

SUBJECT LINE ≤ 50 CHARS WHEN POSSIBLE.`,
  },
  {
    id: 'pinterest',
    title: 'PINTEREST — PIN + BOARD COPY',
    category: 'PINTEREST',
    description: 'PIN TITLE, DESCRIPTION, KEYWORDS FOR DISCOVERY.',
    tags: ['PINTEREST', 'SEO', 'VISUAL'],
    body: `ROLE: PINTEREST SEO — KEYWORD-RICH, HELPFUL, NOT SPAMMY.

FIELDS:
- PIN TITLE: [TOPIC] GUIDE | FRONTAL SLAYER
- PIN DESCRIPTION: 2–3 SENTENCES + BENEFIT + LOUNGE LINK HINT
- KEYWORDS: UNDERTONE, TEXTURE, INSTALL, COLOR FORECAST
- BOARD: SLAY FORECASTS OR LACE MASTERY

VERTICAL 2:3 HERO WHEN POSSIBLE.`,
  },
  {
    id: 'thumbnail',
    title: 'THUMBNAIL — VISUAL BRIEF',
    category: 'THUMBNAIL',
    description: 'HERO SUBJECT, LOWER THIRD, BADGE, ALT TEXT.',
    tags: ['THUMBNAIL', '16:9', 'BRAND'],
    body: `ROLE: ART DIRECTOR BRIEF — SPEC LAYOUT FOR DESIGN OR FAL.

FIELDS:
- HERO SUBJECT: SWATCH / MANNEQUIN / MACRO DETAIL
- LOWER THIRD: HANDWRITTEN TITLE · RED ACCENT
- BADGE: EPISODE # OR BOTH (WATCH + READ)
- COLOR PALETTE: #EB1C24 · #000 · #FFF
- ALT TEXT: DESCRIPTIVE, ACCESSIBLE

16:9 PRIMARY · SAFE ZONE FOR MOBILE CROP.`,
  },
];

export function getAdminStudioPromptById(id: string): AdminStudioPromptEntry | undefined {
  return ADMIN_STUDIO_DEFAULT_PROMPTS.find((p) => p.id === id);
}
