/**
 * studio os navigation registry — grouped nav, breadcrumbs, and module metadata.
 * UI-only; does not change routes or business logic.
 */

import { ADMIN_STUDIO_BASE_PATH } from './adminStudioRoutes';
import type { StudioOsCoreModuleId } from '../studio-os-core/core/modules';

export type StudioNavGroupId =
  | 'overview'
  | 'create'
  | 'visuals'
  | 'production'
  | 'distribution'
  | 'intelligence'
  | 'legacy'
  | 'settings';

export type StudioModuleStatus = 'live' | 'demo' | 'coming-soon';

export type AdminStudioModule = {
  id: string;
  title: string;
  /** One-sentence plain-English purpose. */
  purpose: string;
  route: string;
  groupId: StudioNavGroupId;
  status: StudioModuleStatus;
  /** Demo metric shown on cards (e.g. last updated count). */
  metric: string;
  ctaLabel: string;
  /** Workspace moduleCopy key when available. */
  moduleKey?: StudioOsCoreModuleId | 'studio-dashboard';
  /** Shown on overview only — omit on dense sub-nav. */
  featuredOnOverview?: boolean;
};

export type StudioNavGroup = {
  id: StudioNavGroupId;
  label: string;
  description: string;
};

export const STUDIO_NAV_GROUPS: readonly StudioNavGroup[] = [
  { id: 'overview', label: 'OVERVIEW', description: 'COMMAND SURFACE · DASHBOARD · DAILY SIGNALS' },
  { id: 'create', label: 'CREATE', description: 'IDEATION · BIBLES · PROMPTS · AI TOOLS' },
  { id: 'visuals', label: 'VISUALS', description: 'SETS · TALENT · ASSETS · CASTING' },
  { id: 'production', label: 'PRODUCTION', description: 'PACKS · PIPELINE · AI EXECUTION' },
  { id: 'distribution', label: 'DISTRIBUTION', description: 'CHANNELS · QUEUE · CALENDAR' },
  { id: 'intelligence', label: 'INTELLIGENCE', description: 'STRATEGY · AUDIENCE · ANALYTICS' },
  { id: 'legacy', label: 'LEGACY', description: 'ARCHIVE · HALL OF FAME · VAULT' },
  { id: 'settings', label: 'SETTINGS', description: 'WORKSPACE · BRAND · PLATFORM' },
] as const;

export const STUDIO_OVERVIEW_PATH = `${ADMIN_STUDIO_BASE_PATH}/overview`;

const p = (segment: string) => `${ADMIN_STUDIO_BASE_PATH}/${segment.replace(/^\//, '')}`;

/** Canonical module directory — every existing Studio route remains reachable. */
export const ADMIN_STUDIO_MODULES: readonly AdminStudioModule[] = [
  // OVERVIEW
  {
    id: 'mission-control',
    title: 'MISSION CONTROL',
    purpose: 'Executive operating room — missions, departments, approvals, and live workspace activity in one view.',
    route: p('mission-control'),
    groupId: 'overview',
    status: 'demo',
    metric: 'HQ',
    ctaLabel: 'ENTER HQ',
    featuredOnOverview: true,
  },
  {
    id: 'chief-of-staff',
    title: 'CHIEF OF STAFF',
    purpose: 'Founder primary executive — soft approvals, unified briefings, and attention protection before escalations.',
    route: p('chief-of-staff'),
    groupId: 'overview',
    status: 'demo',
    metric: '2 REVIEWS',
    ctaLabel: 'OPEN CHIEF OF STAFF',
    featuredOnOverview: true,
  },
  {
    id: 'executive-timeline',
    title: 'EXECUTIVE TIMELINE',
    purpose: 'Permanent visual history — scroll years, filter by department, replay organizational history, intelligent insights. How you arrived here.',
    route: p('executive-timeline'),
    groupId: 'overview',
    status: 'demo',
    metric: 'M116',
    ctaLabel: 'OPEN TIMELINE',
    moduleKey: 'executive-timeline',
    featuredOnOverview: true,
  },
  {
    id: 'executive-organization',
    title: 'EXECUTIVE ORGANIZATION',
    purpose: 'Living leadership team — executive HQ, departments, teams, workers, culture, and organizational memory.',
    route: p('executive-organization'),
    groupId: 'overview',
    status: 'demo',
    metric: 'v1.0',
    ctaLabel: 'OPEN EXEC ORG',
    moduleKey: 'executive-organization',
    featuredOnOverview: true,
  },
  {
    id: 'organizational-inheritance',
    title: 'ORGANIZATIONAL INHERITANCE',
    purpose: 'Inherit proven organizational genetics — DNA, playbooks, executives, and institutional knowledge across companies.',
    route: p('organizational-inheritance'),
    groupId: 'overview',
    status: 'demo',
    metric: 'v1.0',
    ctaLabel: 'OPEN INHERITANCE',
    moduleKey: 'organizational-inheritance',
    featuredOnOverview: true,
  },
  {
    id: 'company-maturity-engine',
    title: 'COMPANY MATURITY ENGINE',
    purpose: 'Universal onboarding — assess maturity, preserve assets, recommend architects and roadmap. Meet founders where they are.',
    route: p('company-maturity-engine'),
    groupId: 'overview',
    status: 'demo',
    metric: 'v1.0',
    ctaLabel: 'OPEN MATURITY',
    moduleKey: 'company-maturity-engine',
    featuredOnOverview: true,
  },
  {
    id: 'brand-architect',
    title: 'BRAND ARCHITECT',
    purpose: 'Transform validated business into complete living brand — blueprint, verbal + visual identity, systems, handoff to Experience Architect.',
    route: p('brand-architect'),
    groupId: 'overview',
    status: 'demo',
    metric: 'v1.0',
    ctaLabel: 'OPEN BRAND',
    moduleKey: 'brand-architect',
    featuredOnOverview: true,
  },
  {
    id: 'experience-architect',
    title: 'EXPERIENCE ARCHITECT',
    purpose: 'Emotional design for every touchpoint — journey maps, emotional architecture, memorability over usability.',
    route: p('experience-architect'),
    groupId: 'overview',
    status: 'demo',
    metric: 'v1.0',
    ctaLabel: 'OPEN EXPERIENCE',
    moduleKey: 'experience-architect',
    featuredOnOverview: true,
  },
  {
    id: 'digital-architect',
    title: 'DIGITAL ARCHITECT',
    purpose: 'Digital solution architect — experience gallery, hybrid modes, ecosystem design, inheritance, launch handoff. V2.0.',
    route: p('digital-architect'),
    groupId: 'overview',
    status: 'demo',
    metric: 'v2.0',
    ctaLabel: 'OPEN DIGITAL',
    moduleKey: 'digital-architect',
    featuredOnOverview: true,
  },
  {
    id: 'growth-architect',
    title: 'GROWTH ARCHITECT',
    purpose: 'Sustainable growth OS — initiatives, GTM, orchestration, compound trust and revenue over decades.',
    route: p('growth-architect'),
    groupId: 'overview',
    status: 'demo',
    metric: 'v1.0',
    ctaLabel: 'OPEN GROWTH',
    moduleKey: 'growth-architect',
    featuredOnOverview: true,
  },
  {
    id: 'company-genome',
    title: 'COMPANY GENOME',
    purpose: 'Living organizational genetics — identity, intelligence, evolution, and the heartbeat of every company.',
    route: p('company-genome'),
    groupId: 'overview',
    status: 'demo',
    metric: 'v1.0',
    ctaLabel: 'OPEN GENOME',
    moduleKey: 'company-genome',
    featuredOnOverview: true,
  },
  {
    id: 'architect-studio',
    title: 'ARCHITECT STUDIO',
    purpose: 'Immersive innovation headquarters — five connected architect studios in one living campus.',
    route: p('architect-studio'),
    groupId: 'overview',
    status: 'demo',
    metric: 'v1.5',
    ctaLabel: 'ENTER STUDIO',
    moduleKey: 'architect-studio',
    featuredOnOverview: true,
  },
  {
    id: 'campus-evolution-engine',
    title: 'CAMPUS EVOLUTION ENGINE',
    purpose: 'Living architectural growth — walk through decades of organizational evolution earned through progress.',
    route: p('campus-evolution-engine'),
    groupId: 'overview',
    status: 'demo',
    metric: 'v1.0',
    ctaLabel: 'WALK CAMPUS',
    moduleKey: 'campus-evolution-engine',
    featuredOnOverview: true,
  },
  {
    id: 'founder-walk',
    title: 'FOUNDER WALK',
    purpose: 'Emotional spine of the campus — preserve the founder journey as a living marble pathway and legacy system.',
    route: p('founder-walk'),
    groupId: 'overview',
    status: 'demo',
    metric: 'v1.0',
    ctaLabel: 'BEGIN WALK',
    moduleKey: 'founder-walk',
    featuredOnOverview: true,
  },
  {
    id: 'remembrance-garden',
    title: 'REMEMBRANCE GARDEN',
    purpose: 'Most personal campus space — honor people, moments, and sacrifices that shaped the organization. Preserve gratitude.',
    route: p('remembrance-garden'),
    groupId: 'overview',
    status: 'demo',
    metric: 'v1.0',
    ctaLabel: 'ENTER GARDEN',
    moduleKey: 'remembrance-garden',
    featuredOnOverview: true,
  },
  {
    id: 'founders-promise',
    title: 'FOUNDER\'S PROMISE',
    purpose: 'Personal north star — deeply personal commitment defining why the company deserves to exist. Not marketing. Truth.',
    route: p('founders-promise'),
    groupId: 'overview',
    status: 'demo',
    metric: 'v1.0',
    ctaLabel: 'READ PROMISE',
    moduleKey: 'founders-promise',
    featuredOnOverview: true,
  },
  {
    id: 'executive-framework',
    title: 'EXECUTIVE FRAMEWORK',
    purpose: 'Constitutional foundation for every AI executive — coordinated leadership organization, not isolated assistants.',
    route: p('executive-framework'),
    groupId: 'overview',
    status: 'demo',
    metric: 'v1.0',
    ctaLabel: 'OPEN FRAMEWORK',
    moduleKey: 'executive-framework',
    featuredOnOverview: true,
  },
  {
    id: 'leadership-manifesto-framework',
    title: 'LEADERSHIP MANIFESTO FRAMEWORK',
    purpose: 'Constitutional foundation inherited by every executive — shared principles, discipline expertise, living organizational DNA.',
    route: p('leadership-manifesto-framework'),
    groupId: 'overview',
    status: 'demo',
    metric: 'v1.0',
    ctaLabel: 'OPEN MANIFESTO',
    moduleKey: 'leadership-manifesto-framework',
    featuredOnOverview: true,
  },
  {
    id: 'chief-brand-officer',
    title: 'CHIEF BRAND OFFICER',
    purpose: 'Lifelong guardian of organizational identity — protect meaning, evolve thoughtfully, strengthen trust. V2.0.',
    route: p('chief-brand-officer'),
    groupId: 'overview',
    status: 'demo',
    metric: 'v2.0',
    ctaLabel: 'OPEN CBO',
    moduleKey: 'chief-brand-officer',
    featuredOnOverview: true,
  },
  {
    id: 'chief-experience-officer',
    title: 'CHIEF EXPERIENCE OFFICER',
    purpose: 'Lifelong guardian of customer experience — trust, delight, belonging across every touchpoint. V2.0.',
    route: p('chief-experience-officer'),
    groupId: 'overview',
    status: 'demo',
    metric: 'v2.0',
    ctaLabel: 'OPEN CEO',
    moduleKey: 'chief-experience-officer',
    featuredOnOverview: true,
  },
  {
    id: 'chief-digital-officer',
    title: 'CHIEF DIGITAL OFFICER',
    purpose: 'Lifelong guardian of the digital ecosystem — technology invisible, experience remembered. V1.0.',
    route: p('chief-digital-officer'),
    groupId: 'overview',
    status: 'demo',
    metric: 'v1.0',
    ctaLabel: 'OPEN CDO',
    moduleKey: 'chief-digital-officer',
    featuredOnOverview: true,
  },
  {
    id: 'chief-technology-officer',
    title: 'CHIEF TECHNOLOGY OFFICER',
    purpose: 'Lifelong guardian of engineering & infrastructure — resilient, secure, built to last. V1.0.',
    route: p('chief-technology-officer'),
    groupId: 'overview',
    status: 'demo',
    metric: 'v1.0',
    ctaLabel: 'OPEN CTO',
    moduleKey: 'chief-technology-officer',
    featuredOnOverview: true,
  },
  {
    id: 'chief-growth-officer',
    title: 'CHIEF GROWTH OFFICER',
    purpose: 'Lifelong guardian of sustainable growth — stronger not simply bigger. V1.0.',
    route: p('chief-growth-officer'),
    groupId: 'overview',
    status: 'demo',
    metric: 'v1.0',
    ctaLabel: 'OPEN CGO',
    moduleKey: 'chief-growth-officer',
    featuredOnOverview: true,
  },
  {
    id: 'executive-council',
    title: 'EXECUTIVE COUNCIL',
    purpose: 'Highest collaborative leadership body — executive debate, synthesis, organizational wisdom. V2.0.',
    route: p('executive-council'),
    groupId: 'overview',
    status: 'demo',
    metric: 'v2.0',
    ctaLabel: 'ENTER COUNCIL',
    moduleKey: 'executive-council',
    featuredOnOverview: true,
  },
  {
    id: 'organizational-intelligence',
    title: 'ORGANIZATIONAL INTELLIGENCE',
    purpose: 'Collective mind of the company — accumulated wisdom that compounds every day. V1.0.',
    route: p('organizational-intelligence'),
    groupId: 'overview',
    status: 'demo',
    metric: 'v1.0',
    ctaLabel: 'OPEN OI',
    moduleKey: 'organizational-intelligence',
    featuredOnOverview: true,
  },
  {
    id: 'organizational-autonomy-framework',
    title: 'ORGANIZATIONAL AUTONOMY FRAMEWORK',
    purpose: 'Constitutional autonomy governance — execute with judgment, transparency, founder alignment. V1.0.',
    route: p('organizational-autonomy-framework'),
    groupId: 'overview',
    status: 'demo',
    metric: 'v1.0',
    ctaLabel: 'OPEN OAF',
    moduleKey: 'organizational-autonomy-framework',
    featuredOnOverview: true,
  },
  {
    id: 'organizational-delegation-engine',
    title: 'ORGANIZATIONAL DELEGATION ENGINE',
    purpose: 'Outcome-based delegation — founders define missions and outcomes, the organization executes. V1.0.',
    route: p('organizational-delegation-engine'),
    groupId: 'overview',
    status: 'demo',
    metric: 'v1.0',
    ctaLabel: 'OPEN ODE',
    moduleKey: 'organizational-delegation-engine',
    featuredOnOverview: true,
  },
  {
    id: 'organizational-workflow-orchestration',
    title: 'ORGANIZATIONAL WORKFLOW ORCHESTRATION',
    purpose: 'Cross-functional workflow choreography — coordinated teams accomplish shared outcomes. V1.0.',
    route: p('organizational-workflow-orchestration'),
    groupId: 'overview',
    status: 'demo',
    metric: 'v1.0',
    ctaLabel: 'OPEN OWF',
    moduleKey: 'organizational-workflow-orchestration',
    featuredOnOverview: true,
  },
  {
    id: 'organizational-self-improvement',
    title: 'ORGANIZATIONAL SELF-IMPROVEMENT',
    purpose: 'Continuous organizational evolution — reflect, learn, and strengthen every day. V1.0.',
    route: p('organizational-self-improvement'),
    groupId: 'overview',
    status: 'demo',
    metric: 'v1.0',
    ctaLabel: 'OPEN OSI',
    moduleKey: 'organizational-self-improvement',
    featuredOnOverview: true,
  },
  {
    id: 'organizational-governance-safeguards',
    title: 'ORGANIZATIONAL GOVERNANCE & SAFEGUARDS',
    purpose: 'Constitutional stewardship — invisible safeguards that preserve trust and enable progress. V1.0.',
    route: p('organizational-governance-safeguards'),
    groupId: 'overview',
    status: 'demo',
    metric: 'v1.0',
    ctaLabel: 'OPEN OGS',
    moduleKey: 'organizational-governance-safeguards',
    featuredOnOverview: true,
  },
  {
    id: 'organizational-maturity-model',
    title: 'ORGANIZATIONAL MATURITY MODEL',
    purpose: 'Master progression system — right systems at the right time. Maturity earned, not unlocked. V1.0.',
    route: p('organizational-maturity-model'),
    groupId: 'overview',
    status: 'demo',
    metric: 'v1.0',
    ctaLabel: 'OPEN OMM',
    moduleKey: 'organizational-maturity-model',
    featuredOnOverview: true,
  },
  {
    id: 'leadership-modes',
    title: 'LEADERSHIP MODES',
    purpose: 'Founder & executive mode — Studio OS adapts to how you want to lead today. V1.0.',
    route: p('leadership-modes'),
    groupId: 'overview',
    status: 'demo',
    metric: 'v1.0',
    ctaLabel: 'OPEN MODES',
    moduleKey: 'leadership-modes',
    featuredOnOverview: true,
  },
  {
    id: 'company-onboarding-intelligence',
    title: 'COMPANY ONBOARDING INTELLIGENCE',
    purpose: 'Intelligent onboarding — discover the story, arrive at headquarters, feel understood. V1.0.',
    route: p('company-onboarding-intelligence'),
    groupId: 'overview',
    status: 'demo',
    metric: 'v1.0',
    ctaLabel: 'OPEN ONBOARDING',
    moduleKey: 'company-onboarding-intelligence',
    featuredOnOverview: true,
  },
  {
    id: 'arrival-experience',
    title: 'ARRIVAL EXPERIENCE',
    purpose: 'Ceremonial headquarters welcome — arrive at your living organization, feel at home. V1.0.',
    route: p('arrival-experience'),
    groupId: 'overview',
    status: 'demo',
    metric: 'v1.0',
    ctaLabel: 'OPEN ARRIVAL',
    moduleKey: 'arrival-experience',
    featuredOnOverview: true,
  },
  {
    id: 'executive-apprenticeship-founder-calibration',
    title: 'EXECUTIVE APPRENTICESHIP & FOUNDER CALIBRATION',
    purpose: 'Executives apprentice under the founder — observe, learn, practice, earn trust through calibration. V1.0.',
    route: p('executive-apprenticeship-founder-calibration'),
    groupId: 'overview',
    status: 'demo',
    metric: 'v1.0',
    ctaLabel: 'OPEN APPRENTICESHIP',
    moduleKey: 'executive-apprenticeship-founder-calibration',
    featuredOnOverview: true,
  },
  {
    id: 'studio-institute',
    title: 'STUDIO INSTITUTE™',
    purpose: 'Educational engine from Profession Brain™ — courses, certifications, scenarios, customer education. M93.',
    route: p('studio-institute'),
    groupId: 'intelligence',
    status: 'demo',
    metric: 'M93',
    ctaLabel: 'OPEN INSTITUTE',
    moduleKey: 'studio-institute',
    featuredOnOverview: true,
  },
  {
    id: 'organizational-apprenticeship',
    title: 'ORGANIZATIONAL APPRENTICESHIP',
    purpose: 'Permanent learning & trust-building — every new intelligence apprentices before earning authority. V1.0.',
    route: p('organizational-apprenticeship'),
    groupId: 'overview',
    status: 'demo',
    metric: 'v1.0',
    ctaLabel: 'OPEN APPRENTICESHIP',
    moduleKey: 'organizational-apprenticeship',
    featuredOnOverview: true,
  },
  {
    id: 'concierge-layer',
    title: 'CONCIERGE LAYER',
    purpose: 'Founder-facing guidance — executives govern · concierges guide · hospitality-driven Studio OS. V1.0.',
    route: p('concierge-layer'),
    groupId: 'overview',
    status: 'demo',
    metric: 'v1.0',
    ctaLabel: 'MEET CONCIERGE TEAM',
    moduleKey: 'concierge-layer',
    featuredOnOverview: true,
  },
  {
    id: 'strategy-engine',
    title: 'STRATEGY ENGINE',
    purpose: 'Defines the game each company is playing — strategy board, initiatives, alignment, and direction before execution.',
    route: p('strategy-engine'),
    groupId: 'intelligence',
    status: 'demo',
    metric: 'v1.0',
    ctaLabel: 'OPEN STRATEGY',
    moduleKey: 'strategy-engine',
    featuredOnOverview: true,
  },
  {
    id: 'reader-graph',
    title: 'READER GRAPH',
    purpose: 'Living relationship map — every person evolves through trust, learning, loyalty, and advocacy over years.',
    route: p('reader-graph'),
    groupId: 'intelligence',
    status: 'demo',
    metric: 'v1.0',
    ctaLabel: 'OPEN READER GRAPH',
    moduleKey: 'reader-graph',
    featuredOnOverview: true,
  },
  {
    id: 'relationship-engine',
    title: 'RELATIONSHIP ENGINE',
    purpose: 'Active relationship OS — nurture trust, next best actions, recognition, and long-term value.',
    route: p('relationship-engine'),
    groupId: 'intelligence',
    status: 'demo',
    metric: 'v1.0',
    ctaLabel: 'OPEN RELATIONSHIPS',
    moduleKey: 'relationship-engine',
    featuredOnOverview: true,
  },
  {
    id: 'creator-marketplace',
    title: 'CREATOR MARKETPLACE',
    purpose: 'Intelligent creator business ecosystem — alignment, career growth, deals, and long-term partnerships.',
    route: p('creator-marketplace'),
    groupId: 'intelligence',
    status: 'demo',
    metric: 'v1.0',
    ctaLabel: 'OPEN MARKETPLACE',
    moduleKey: 'creator-marketplace',
    featuredOnOverview: true,
  },
  {
    id: 'ecosystem-marketplace',
    title: 'ECOSYSTEM MARKETPLACE',
    purpose: 'Organizational intelligence exchange — publish, license, inherit, and compound proven systems.',
    route: p('ecosystem-marketplace'),
    groupId: 'intelligence',
    status: 'demo',
    metric: 'v1.0',
    ctaLabel: 'OPEN ECOSYSTEM',
    moduleKey: 'ecosystem-marketplace',
    featuredOnOverview: true,
  },
  {
    id: 'knowledge-asset-engine',
    title: 'KNOWLEDGE ASSET ENGINE',
    purpose: 'Foundational knowledge model — every content piece is a living asset with lineage, maturity, and SSOT.',
    route: p('knowledge-asset-engine'),
    groupId: 'intelligence',
    status: 'demo',
    metric: 'v1.0',
    ctaLabel: 'OPEN KNOWLEDGE',
    moduleKey: 'knowledge-asset-engine',
    featuredOnOverview: true,
  },
  {
    id: 'campaign-engine',
    title: 'CAMPAIGN ENGINE',
    purpose: 'Transforms strategy into coordinated execution — campaigns bridge initiatives and production.',
    route: p('campaign-engine'),
    groupId: 'production',
    status: 'demo',
    metric: 'v1.0',
    ctaLabel: 'OPEN CAMPAIGNS',
    moduleKey: 'campaign-engine',
    featuredOnOverview: true,
  },
  {
    id: 'work-orchestration',
    title: 'WORK ORCHESTRATION',
    purpose: 'Transforms objectives into coordinated execution — work packages, dependencies, and CoS orchestration.',
    route: p('work-orchestration'),
    groupId: 'production',
    status: 'demo',
    metric: 'v1.0',
    ctaLabel: 'OPEN ORCHESTRATION',
    moduleKey: 'work-orchestration',
    featuredOnOverview: true,
  },
  {
    id: 'executive-command-center',
    title: 'EXECUTIVE COMMAND CENTER',
    purpose: 'See company health, priorities, and decisions in one executive view.',
    route: p('executive-command-center'),
    groupId: 'overview',
    status: 'demo',
    metric: '12 SIGNALS',
    ctaLabel: 'OPEN COMMAND CENTER',
    moduleKey: 'executive-command-center',
    featuredOnOverview: true,
  },
  {
    id: 'studio-overview',
    title: 'STUDIO DASHBOARD',
    purpose: 'Browse every Studio module by department with quick-launch cards.',
    route: STUDIO_OVERVIEW_PATH,
    groupId: 'overview',
    status: 'live',
    metric: '32 MODULES',
    ctaLabel: 'VIEW OVERVIEW',
    moduleKey: 'studio-dashboard',
    featuredOnOverview: true,
  },
  {
    id: 'daily-briefing',
    title: 'DAILY BRIEFING',
    purpose: 'Read today’s creative direction, topics, and production priorities.',
    route: p('creative-director'),
    groupId: 'overview',
    status: 'demo',
    metric: 'TODAY',
    ctaLabel: 'READ BRIEFING',
    moduleKey: 'creative-director',
    featuredOnOverview: true,
  },
  // CREATE
  {
    id: 'content-brain',
    title: 'CONTENT BRAIN',
    purpose: 'Store brand rules, show bibles, and editorial knowledge for every AI tool.',
    route: p('content-brain'),
    groupId: 'create',
    status: 'demo',
    metric: '9 SECTIONS',
    ctaLabel: 'OPEN CONTENT BRAIN',
    moduleKey: 'content-brain',
    featuredOnOverview: true,
  },
  {
    id: 'design-dna-canon',
    title: 'DESIGN DNA & CANON SYSTEM',
    purpose: 'Permanent creative compass — protected canon pages · design relationships · headquarters review before new pages ship.',
    route: p('design-dna-canon'),
    groupId: 'create',
    status: 'demo',
    metric: 'CANON',
    ctaLabel: 'OPEN DESIGN DNA',
    moduleKey: 'design-dna-canon',
    featuredOnOverview: true,
  },
  {
    id: 'creative-director',
    title: 'CREATIVE DIRECTOR',
    purpose: 'Run the creative decision engine before any production or AI run.',
    route: p('creative-director'),
    groupId: 'create',
    status: 'demo',
    metric: '4 WIDGETS',
    ctaLabel: 'OPEN DIRECTOR',
    moduleKey: 'creative-director',
    featuredOnOverview: true,
  },
  {
    id: 'show-bible',
    title: 'SHOW BIBLE',
    purpose: 'Define show DNA, episode structure, and on-air standards.',
    route: p('show-bible'),
    groupId: 'create',
    status: 'demo',
    metric: '8 SHOWS',
    ctaLabel: 'OPEN SHOW BIBLE',
    moduleKey: 'show-bible',
    featuredOnOverview: true,
  },
  {
    id: 'prompt-library',
    title: 'PROMPT LIBRARY',
    purpose: 'Curate approved prompts for PSA, Lounge TV, and marketing.',
    route: p('prompt-library'),
    groupId: 'create',
    status: 'demo',
    metric: '63',
    ctaLabel: 'BROWSE PROMPTS',
    featuredOnOverview: true,
  },
  {
    id: 'ai-studio',
    title: 'AI STUDIO',
    purpose: 'Generate scripts, thumbnails, and campaign assets in one workspace.',
    route: p('ai-studio'),
    groupId: 'create',
    status: 'demo',
    metric: '121',
    ctaLabel: 'OPEN AI STUDIO',
    featuredOnOverview: true,
  },
  {
    id: 'shows',
    title: 'SHOWS',
    purpose: 'Manage series, episodes, and Lounge TV programming.',
    route: p('shows'),
    groupId: 'create',
    status: 'demo',
    metric: '8',
    ctaLabel: 'VIEW SHOWS',
  },
  {
    id: 'ai-orchestrator',
    title: 'AI ORCHESTRATOR',
    purpose: 'Coordinate multi-step AI workflows across Studio modules.',
    route: p('ai-orchestrator'),
    groupId: 'create',
    status: 'demo',
    metric: '6 FLOWS',
    ctaLabel: 'OPEN ORCHESTRATOR',
  },
  {
    id: 'recent-generations',
    title: 'RECENT GENERATIONS',
    purpose: 'Review the latest AI outputs awaiting approval.',
    route: p('recent-generations'),
    groupId: 'create',
    status: 'coming-soon',
    metric: '12',
    ctaLabel: 'VIEW OUTPUTS',
  },
  // VISUALS
  {
    id: 'asset-director',
    title: 'ASSET DIRECTOR',
    purpose: 'Approve studios, talent looks, and visual libraries for every channel.',
    route: p('asset-director'),
    groupId: 'visuals',
    status: 'demo',
    metric: '16 SECTIONS',
    ctaLabel: 'OPEN ASSET DIRECTOR',
    moduleKey: 'asset-director',
    featuredOnOverview: true,
  },
  {
    id: 'blueprint-manager',
    title: 'BLUEPRINT MANAGER',
    purpose: 'Define creative DNA before generation — studios, talent, campaigns, and every asset spec.',
    route: p('blueprint-manager'),
    groupId: 'visuals',
    status: 'demo',
    metric: '16 TYPES',
    ctaLabel: 'OPEN BLUEPRINTS',
    featuredOnOverview: true,
  },
  {
    id: 'asset-factory',
    title: 'ASSET FACTORY',
    purpose: 'Manufacture complete creative systems from approved blueprints — executive, floor, and tour views.',
    route: p('asset-factory'),
    groupId: 'visuals',
    status: 'demo',
    metric: '3 VIEWS',
    ctaLabel: 'ENTER FACTORY',
    featuredOnOverview: true,
  },
  {
    id: 'studio-lot',
    title: 'STUDIO LOT',
    purpose: 'Tour virtual sets and production environments before you shoot.',
    route: p('studio-lot'),
    groupId: 'visuals',
    status: 'demo',
    metric: '5 SETS',
    ctaLabel: 'ENTER LOT',
    moduleKey: 'studio-lot',
    featuredOnOverview: true,
  },
  {
    id: 'talent-agency',
    title: 'TALENT AGENCY',
    purpose: 'Browse on-camera personalities, contracts, and usage rights.',
    route: p('talent-agency'),
    groupId: 'visuals',
    status: 'demo',
    metric: '14 TALENT',
    ctaLabel: 'VIEW ROSTER',
    moduleKey: 'talent-agency',
    featuredOnOverview: true,
  },
  {
    id: 'casting',
    title: 'CASTING',
    purpose: 'Run casting boards and approve talent for each production.',
    route: p('casting'),
    groupId: 'visuals',
    status: 'demo',
    metric: '3 BOARDS',
    ctaLabel: 'OPEN CASTING',
    moduleKey: 'casting',
    featuredOnOverview: true,
  },
  {
    id: 'brand-assets',
    title: 'BRAND ASSETS',
    purpose: 'Official brand visual standards — Photography Bible, media kits, and locked product photography specs.',
    route: p('brand-assets'),
    groupId: 'visuals',
    status: 'demo',
    metric: 'V1.0',
    ctaLabel: 'OPEN BRAND ASSETS',
    featuredOnOverview: true,
  },
  {
    id: 'asset-library',
    title: 'ASSET LIBRARY',
    purpose: 'Browse thumbnails, heroes, B-roll, and brand films.',
    route: p('asset-library'),
    groupId: 'visuals',
    status: 'coming-soon',
    metric: '214',
    ctaLabel: 'BROWSE ASSETS',
  },
  // PRODUCTION
  {
    id: 'director-mode',
    title: 'DIRECTOR MODE',
    purpose: 'Rehearse productions in a cinematic control room before AI generates assets.',
    route: p('director-mode'),
    groupId: 'production',
    status: 'demo',
    metric: 'CINEMA',
    ctaLabel: 'ENTER DIRECTOR MODE',
    featuredOnOverview: true,
  },
  {
    id: 'production-builder',
    title: 'PRODUCTION BUILDER',
    purpose: 'Visually assemble studios, talent, and scenes before AI generates your content pack.',
    route: p('production-builder'),
    groupId: 'production',
    status: 'demo',
    metric: 'VISUAL',
    ctaLabel: 'OPEN BUILDER',
    featuredOnOverview: true,
  },
  {
    id: 'production-studio',
    title: 'PRODUCTION STUDIO',
    purpose: 'Cinematic production headquarters — every approved page becomes production-ready media. AI teams already working.',
    route: p('production-studio'),
    groupId: 'production',
    status: 'demo',
    metric: 'V1.0',
    ctaLabel: 'ENTER STUDIO',
    moduleKey: 'production-studio',
    featuredOnOverview: true,
  },
  {
    id: 'render-queue',
    title: 'RENDER QUEUE',
    purpose: 'Centralized production floor — visible pipeline, live progress, pause/resume/batch. The founder never wonders what AI is doing.',
    route: p('render-queue'),
    groupId: 'production',
    status: 'demo',
    metric: 'LIVE',
    ctaLabel: 'OPEN QUEUE',
    moduleKey: 'render-queue',
    featuredOnOverview: true,
  },
  {
    id: 'screening-room',
    title: 'SCREENING ROOM',
    purpose: 'Luxury private cinema — experience every production before publication. Compare versions · concierge review · approve.',
    route: p('screening-room'),
    groupId: 'production',
    status: 'demo',
    metric: 'CINEMA',
    ctaLabel: 'ENTER THEATER',
    moduleKey: 'screening-room',
    featuredOnOverview: true,
  },
  {
    id: 'concierge-approval-flow',
    title: 'CONCIERGE APPROVAL FLOW',
    purpose: 'Editorial board before founder — six concierges review by discipline · Chief Concierge unified brief · founder decides last.',
    route: p('concierge-approval-flow'),
    groupId: 'production',
    status: 'demo',
    metric: 'BOARD',
    ctaLabel: 'ENTER EDITORIAL BOARD',
    moduleKey: 'concierge-approval-flow',
    featuredOnOverview: true,
  },
  {
    id: 'content-packs',
    title: 'CONTENT PACKS',
    purpose: 'Bundle weekly video, article, and checklist releases.',
    route: p('content-packs'),
    groupId: 'production',
    status: 'demo',
    metric: '42',
    ctaLabel: 'VIEW PACKS',
    featuredOnOverview: true,
  },
  {
    id: 'production',
    title: 'PRODUCTION PIPELINE',
    purpose: 'Track packs from draft through final delivery.',
    route: p('production'),
    groupId: 'production',
    status: 'demo',
    metric: '7 ACTIVE',
    ctaLabel: 'OPEN PIPELINE',
    moduleKey: 'production-pipeline',
    featuredOnOverview: true,
  },
  {
    id: 'ai-production-engine',
    title: 'AI PRODUCTION ENGINE',
    purpose: 'Automate render queues and department handoffs with AI.',
    route: p('ai-production-engine'),
    groupId: 'production',
    status: 'demo',
    metric: '4 RUNS',
    ctaLabel: 'OPEN ENGINE',
    moduleKey: 'ai-production-engine',
    featuredOnOverview: true,
  },
  {
    id: 'drafts',
    title: 'DRAFTS',
    purpose: 'See work-in-progress across every channel.',
    route: p('drafts'),
    groupId: 'production',
    status: 'coming-soon',
    metric: '18',
    ctaLabel: 'VIEW DRAFTS',
  },
  // DISTRIBUTION
  {
    id: 'distribution-engine',
    title: 'DISTRIBUTION ENGINE',
    purpose: 'Global distribution for knowledge assets — channel optimization, evergreen, and institutional learning.',
    route: p('distribution-engine'),
    groupId: 'distribution',
    status: 'demo',
    metric: 'v1.0',
    ctaLabel: 'OPEN DISTRIBUTION',
    moduleKey: 'distribution-engine',
    featuredOnOverview: true,
  },
  {
    id: 'distribution-network',
    title: 'DISTRIBUTION NETWORK',
    purpose: 'Route one story to Lounge, email, social, and partner channels.',
    route: p('distribution-network'),
    groupId: 'distribution',
    status: 'demo',
    metric: '6 CHANNELS',
    ctaLabel: 'OPEN NETWORK',
    moduleKey: 'distribution-network',
    featuredOnOverview: true,
  },
  {
    id: 'campaign-orchestrator',
    title: 'CAMPAIGN ORCHESTRATOR',
    purpose: 'Turn one business objective into a complete launch plan with timeline, tasks, and approvals.',
    route: p('campaign-orchestrator'),
    groupId: 'distribution',
    status: 'demo',
    metric: '16 TYPES',
    ctaLabel: 'OPEN ORCHESTRATOR',
    featuredOnOverview: true,
  },
  {
    id: 'publishing-queue',
    title: 'PUBLISHING QUEUE',
    purpose: 'Ship approved content to Lounge, email, and social.',
    route: p('publishing-queue'),
    groupId: 'distribution',
    status: 'demo',
    metric: '6',
    ctaLabel: 'OPEN QUEUE',
    featuredOnOverview: true,
  },
  {
    id: 'calendar',
    title: 'CALENDAR',
    purpose: 'Plan editorial rhythm and premiere dates.',
    route: p('calendar'),
    groupId: 'distribution',
    status: 'coming-soon',
    metric: '14',
    ctaLabel: 'VIEW CALENDAR',
    featuredOnOverview: true,
  },
  {
    id: 'social-accounts',
    title: 'SOCIAL ACCOUNTS',
    purpose: 'Connect official OAuth accounts for approved publishing.',
    route: p('social-accounts'),
    groupId: 'distribution',
    status: 'demo',
    metric: '4 PLATFORMS',
    ctaLabel: 'MANAGE ACCOUNTS',
  },
  {
    id: 'scheduled',
    title: 'SCHEDULED',
    purpose: 'View locked release dates and premiere slots.',
    route: p('scheduled'),
    groupId: 'distribution',
    status: 'coming-soon',
    metric: '6',
    ctaLabel: 'VIEW SCHEDULE',
  },
  // INTELLIGENCE
  {
    id: 'executive-ai-director',
    title: 'EXECUTIVE AI DIRECTOR',
    purpose: 'Executive advisor that coaches, forecasts, and optimizes from workspace intelligence.',
    route: p('executive-ai-director'),
    groupId: 'intelligence',
    status: 'demo',
    metric: 'ADVISOR',
    ctaLabel: 'OPEN ADVISOR',
    featuredOnOverview: true,
  },
  {
    id: 'knowledge-hub',
    title: 'KNOWLEDGE HUB',
    purpose: 'Living documentation — Documentation Synchronization™ keeps every help surface aligned with current architecture.',
    route: p('knowledge-hub'),
    groupId: 'intelligence',
    status: 'live',
    metric: 'M125',
    ctaLabel: 'OPEN KNOWLEDGE HUB',
    moduleKey: 'knowledge-hub',
    featuredOnOverview: true,
  },
  {
    id: 'memory-bible',
    title: 'MEMORY BIBLE',
    purpose: 'Institutional knowledge — founder context, naming bible, decision log, and AI context builder.',
    route: p('memory-bible'),
    groupId: 'intelligence',
    status: 'live',
    metric: 'v1.0',
    ctaLabel: 'OPEN MEMORY BIBLE',
    moduleKey: 'memory-bible',
    featuredOnOverview: true,
  },
  {
    id: 'leadership-dna',
    title: 'LEADERSHIP DNA',
    purpose: 'Founder operating blueprint — decision framework, approval patterns, and primary Chief of Staff training system.',
    route: p('leadership-dna'),
    groupId: 'intelligence',
    status: 'demo',
    metric: 'v1.0',
    ctaLabel: 'OPEN LEADERSHIP DNA',
    moduleKey: 'leadership-dna',
    featuredOnOverview: true,
  },
  {
    id: 'tutorial-os',
    title: 'TUTORIAL OS',
    purpose: 'Manage onboarding tutorial walkthroughs — The Mansion Tour, hotspots, progress analytics, and preview.',
    route: p('tutorial-os'),
    groupId: 'intelligence',
    status: 'demo',
    metric: 'MANSION',
    ctaLabel: 'OPEN TUTORIAL OS',
    featuredOnOverview: true,
  },
  {
    id: 'intelligence-engine',
    title: 'INTELLIGENCE ENGINE',
    purpose: 'Turn connected data into evidence-based recommendations.',
    route: p('intelligence-engine'),
    groupId: 'intelligence',
    status: 'demo',
    metric: '8 INSIGHTS',
    ctaLabel: 'OPEN ENGINE',
    moduleKey: 'intelligence-engine',
    featuredOnOverview: true,
  },
  {
    id: 'design-genome',
    title: 'DESIGN GENOME',
    purpose: 'Organizational visual memory — promote approved designs · inherit before building · independent genome per organization.',
    route: p('design-genome'),
    groupId: 'intelligence',
    status: 'demo',
    metric: 'GENOME',
    ctaLabel: 'OPEN GENOME',
    moduleKey: 'design-genome',
    featuredOnOverview: true,
  },
  {
    id: 'audience-brain',
    title: 'AUDIENCE BRAIN',
    purpose: 'Learn from every interaction and refine audience journeys.',
    route: p('audience-brain'),
    groupId: 'intelligence',
    status: 'demo',
    metric: '5 SEGMENTS',
    ctaLabel: 'OPEN AUDIENCE',
    moduleKey: 'audience-brain',
    featuredOnOverview: true,
  },
  {
    id: 'growth-network',
    title: 'GROWTH NETWORK',
    purpose: 'Discover opportunities, manage partnerships, and scale revenue intelligently.',
    route: p('growth-network'),
    groupId: 'intelligence',
    status: 'demo',
    metric: '14 TABS',
    ctaLabel: 'OPEN GROWTH',
    moduleKey: 'growth-network',
    featuredOnOverview: true,
  },
  {
    id: 'labs',
    title: 'STUDIO OS LABS',
    purpose: 'Experiment engine & learning system — every publish becomes institutional intelligence.',
    route: p('labs'),
    groupId: 'intelligence',
    status: 'demo',
    metric: '14 TABS',
    ctaLabel: 'OPEN LABS',
    moduleKey: 'labs',
    featuredOnOverview: true,
  },
  {
    id: 'ai-media-network',
    title: 'AI MEDIA NETWORK',
    purpose: 'Digital media network — 5 pillars, 5 shows, programming calendar, monetization, Labs integration.',
    route: p('ai-media-network'),
    groupId: 'intelligence',
    status: 'demo',
    metric: '9 TABS',
    ctaLabel: 'OPEN NETWORK',
    moduleKey: 'ai-media-network',
    featuredOnOverview: true,
  },
  {
    id: 'ndxbook',
    title: 'NDXBOOK',
    purpose: 'Public media brand for AI Media — indexed pages, volumes, chapters, programming, social placeholders, Labs tracking.',
    route: p('ndxbook'),
    groupId: 'intelligence',
    status: 'demo',
    metric: '12 TABS',
    ctaLabel: 'OPEN BRAND',
    moduleKey: 'ndxbook',
    featuredOnOverview: true,
  },
  {
    id: 'talent-network',
    title: 'TALENT NETWORK',
    purpose: 'Unified talent OS — AI + human registry, casting, wardrobe, contracts, performance score, character evolution.',
    route: p('talent-network'),
    groupId: 'intelligence',
    status: 'demo',
    metric: '14 TABS',
    ctaLabel: 'OPEN TALENT NETWORK',
    moduleKey: 'talent-network',
    featuredOnOverview: true,
  },
  {
    id: 'marketplace',
    title: 'MARKETPLACE',
    purpose: 'Professional operating network — intelligent matching, deal center, collaboration hubs, trust, lasting partnerships.',
    route: p('marketplace'),
    groupId: 'intelligence',
    status: 'demo',
    metric: '14 TABS',
    ctaLabel: 'OPEN MARKETPLACE',
    moduleKey: 'marketplace',
    featuredOnOverview: true,
  },
  {
    id: 'business-model-engine',
    title: 'BUSINESS MODEL ENGINE',
    purpose: 'Economic engine — membership, billing, usage, fees, wallets, royalties, asset marketplaces, enterprise, aligned incentives.',
    route: p('business-model-engine'),
    groupId: 'intelligence',
    status: 'demo',
    metric: '14 TABS',
    ctaLabel: 'OPEN BME',
    moduleKey: 'business-model-engine',
    featuredOnOverview: true,
  },
  {
    id: 'ecosystem',
    title: 'STUDIO OS ECOSYSTEM',
    purpose: 'Business operating ecosystem — blueprints, DNA, automations, executives. Install complete operating systems, not plugins.',
    route: p('ecosystem'),
    groupId: 'intelligence',
    status: 'demo',
    metric: '14 TABS',
    ctaLabel: 'OPEN ECOSYSTEM',
    moduleKey: 'ecosystem',
    featuredOnOverview: true,
  },
  {
    id: 'business-discovery-blueprint',
    title: 'BUSINESS DISCOVERY BLUEPRINT™',
    purpose: 'Permanent onboarding architecture — guided chapters, conversational discovery, organizational archaeology. The birth certificate of every organization.',
    route: p('business-discovery-blueprint'),
    groupId: 'settings',
    status: 'demo',
    metric: 'M90',
    ctaLabel: 'BEGIN DISCOVERY',
    moduleKey: 'business-discovery-blueprint',
    featuredOnOverview: true,
  },
  {
    id: 'organization-inauguration',
    title: 'ORGANIZATION INAUGURATION',
    purpose: 'Founder Ceremony after Blueprint completion — Organization Charter, HQ activation, founding timeline, ENTER HEADQUARTERS.',
    route: p('organization-inauguration'),
    groupId: 'settings',
    status: 'demo',
    metric: 'M90.5',
    ctaLabel: 'BEGIN CEREMONY',
    moduleKey: 'organization-inauguration',
    featuredOnOverview: true,
  },
  {
    id: 'profession-brain',
    title: 'PROFESSION BRAIN™',
    purpose: 'Living institutional intelligence — preserves expertise, judgment, and memory. Powers concierges, Academy, and automations.',
    route: p('profession-brain'),
    groupId: 'intelligence',
    status: 'demo',
    metric: 'M91',
    ctaLabel: 'OPEN PROFESSION BRAIN',
    moduleKey: 'profession-brain',
    featuredOnOverview: true,
  },
  {
    id: 'expert-marketplace',
    title: 'EXPERT MARKETPLACE™',
    purpose: 'Publish Profession Brain expertise — trusted experts, not AI bots. Share expertise. Expand your legacy.',
    route: p('expert-marketplace'),
    groupId: 'intelligence',
    status: 'demo',
    metric: 'M92',
    ctaLabel: 'OPEN MARKETPLACE',
    moduleKey: 'expert-marketplace',
    featuredOnOverview: true,
  },
  {
    id: 'knowledge-commerce',
    title: 'KNOWLEDGE COMMERCE™',
    purpose: 'Monetize expertise — product builder, licensing, AI Expert Experiences, revenue intelligence. Not ecommerce — expertise economy.',
    route: p('knowledge-commerce'),
    groupId: 'intelligence',
    status: 'demo',
    metric: 'M92.5',
    ctaLabel: 'MONETIZE KNOWLEDGE',
    moduleKey: 'knowledge-commerce',
    featuredOnOverview: true,
  },
  {
    id: 'professional-trust-framework',
    title: 'PROFESSIONAL TRUST FRAMEWORK™',
    purpose: 'Permanent governance — professional scope, confidence system, natural guidance, regulated industries, escalation. Trust through responsible judgment.',
    route: p('professional-trust-framework'),
    groupId: 'intelligence',
    status: 'demo',
    metric: 'M94',
    ctaLabel: 'OPEN TRUST FRAMEWORK',
    moduleKey: 'professional-trust-framework',
    featuredOnOverview: true,
  },
  {
    id: 'organization-genome',
    title: 'ORGANIZATION GENOME™',
    purpose: 'Permanent identity layer — brand personality, tone, values, decision DNA, customer standards. Every AI interaction consults Genome first.',
    route: p('organization-genome'),
    groupId: 'intelligence',
    status: 'demo',
    metric: 'M95',
    ctaLabel: 'OPEN GENOME',
    moduleKey: 'organization-genome',
    featuredOnOverview: true,
  },
  {
    id: 'memory-engine',
    title: 'MEMORY ENGINE™',
    purpose: 'Organizational memory — projects, campaigns, decisions, lessons. Have we done this before? Remember forever. Compound knowledge.',
    route: p('memory-engine'),
    groupId: 'intelligence',
    status: 'demo',
    metric: 'M96',
    ctaLabel: 'OPEN MEMORY ENGINE',
    moduleKey: 'memory-engine',
    featuredOnOverview: true,
  },
  {
    id: 'company-health-index',
    title: 'COMPANY HEALTH INDEX™',
    purpose: 'Continuous organizational health — 12 categories, Executive Health Score, weak-area alerts. Healthier, not simply larger.',
    route: p('company-health-index'),
    groupId: 'overview',
    status: 'demo',
    metric: 'M97',
    ctaLabel: 'VIEW HEALTH INDEX',
    moduleKey: 'company-health-index',
    featuredOnOverview: true,
  },
  {
    id: 'organization-pulse',
    title: 'ORGANIZATION PULSE™',
    purpose: 'Real-time organizational well-being — 14 pulse indicators, proactive alerts. How is our organization really doing?',
    route: p('organization-pulse'),
    groupId: 'overview',
    status: 'demo',
    metric: 'M100',
    ctaLabel: 'VIEW ORGANIZATION PULSE',
    moduleKey: 'organization-pulse',
    featuredOnOverview: true,
  },
  {
    id: 'wisdom-capture',
    title: 'WISDOM CAPTURE™',
    purpose: 'Preserve small lessons before they fade — wisdom detection, permanent library, organizational learning sync.',
    route: p('wisdom-capture'),
    groupId: 'intelligence',
    status: 'demo',
    metric: 'M101',
    ctaLabel: 'OPEN WISDOM CAPTURE',
    moduleKey: 'wisdom-capture',
    featuredOnOverview: true,
  },
  {
    id: 'shadow-mode',
    title: 'SHADOW MODE™',
    purpose: 'Concierges observe before acting — 4 learning phases, confidence engine, full transparency before automation.',
    route: p('shadow-mode'),
    groupId: 'intelligence',
    status: 'demo',
    metric: 'M102',
    ctaLabel: 'OPEN SHADOW MODE',
    moduleKey: 'shadow-mode',
    featuredOnOverview: true,
  },
  {
    id: 'organization-digital-twin',
    title: 'ORGANIZATION DIGITAL TWIN™',
    purpose: 'Living simulation of the organization — what-if sandbox, executive briefings, no real data changes before acting.',
    route: p('organization-digital-twin'),
    groupId: 'intelligence',
    status: 'demo',
    metric: 'M103',
    ctaLabel: 'OPEN DIGITAL TWIN',
    moduleKey: 'organization-digital-twin',
    featuredOnOverview: true,
  },
  {
    id: 'business-simulation-lab',
    title: 'BUSINESS SIMULATION LAB™',
    purpose: 'Strategic sandbox — test campaigns, pricing, hiring, launches, forecasts. Full reports, Executive Council review, Scenario Library.',
    route: p('business-simulation-lab'),
    groupId: 'intelligence',
    status: 'demo',
    metric: 'M104',
    ctaLabel: 'OPEN SIMULATION LAB',
    moduleKey: 'business-simulation-lab',
    featuredOnOverview: true,
  },
  {
    id: 'knowledge-confidence',
    title: 'KNOWLEDGE CONFIDENCE™',
    purpose: 'Profession Brain quality assurance — 10 confidence dimensions, fuel gauges in Mission Control, learning recommendations when confidence drops.',
    route: p('knowledge-confidence'),
    groupId: 'intelligence',
    status: 'demo',
    metric: 'M105',
    ctaLabel: 'OPEN KNOWLEDGE CONFIDENCE',
    moduleKey: 'knowledge-confidence',
    featuredOnOverview: true,
  },
  {
    id: 'legacy-vault',
    title: 'LEGACY VAULT™',
    purpose: 'Permanent organizational history — archive milestones, version history, founder archive, time capsules, immersive legacy experiences.',
    route: p('legacy-vault'),
    groupId: 'intelligence',
    status: 'demo',
    metric: 'M106',
    ctaLabel: 'OPEN LEGACY VAULT',
    moduleKey: 'legacy-vault',
    featuredOnOverview: true,
  },
  {
    id: 'ambient-awareness',
    title: 'AMBIENT AWARENESS™',
    purpose: 'Continuous organizational context — 10 awareness layers, proactive executive briefings, department awareness. Present, not reactive.',
    route: p('ambient-awareness'),
    groupId: 'intelligence',
    status: 'demo',
    metric: 'M107',
    ctaLabel: 'OPEN AMBIENT AWARENESS',
    moduleKey: 'ambient-awareness',
    featuredOnOverview: true,
  },
  {
    id: 'anticipation-engine',
    title: 'ANTICIPATION ENGINE™',
    purpose: 'Predict organizational needs — proactive preparation, pattern recognition, everything awaits founder approval.',
    route: p('anticipation-engine'),
    groupId: 'intelligence',
    status: 'demo',
    metric: 'M108',
    ctaLabel: 'OPEN ANTICIPATION ENGINE',
    moduleKey: 'anticipation-engine',
    featuredOnOverview: true,
  },
  {
    id: 'founder-cognitive-load',
    title: 'FOUNDER COGNITIVE LOAD™',
    purpose: 'Protect founder attention — cognitive analysis, intelligent filtering, attention modes. Better prioritization, not more information.',
    route: p('founder-cognitive-load'),
    groupId: 'intelligence',
    status: 'demo',
    metric: 'M109',
    ctaLabel: 'OPEN COGNITIVE LOAD',
    moduleKey: 'founder-cognitive-load',
    featuredOnOverview: true,
  },
  {
    id: 'presence-engine',
    title: 'PRESENCE ENGINE™',
    purpose: 'Living executive presence — calm, confident, continuous. Acknowledges milestones, adjusts communication, reflects Headquarters atmosphere.',
    route: p('presence-engine'),
    groupId: 'intelligence',
    status: 'demo',
    metric: 'M110',
    ctaLabel: 'OPEN PRESENCE ENGINE',
    moduleKey: 'presence-engine',
    featuredOnOverview: true,
  },
  {
    id: 'cross-organization-intelligence',
    title: 'CROSS-ORGANIZATION INTELLIGENCE™',
    purpose: 'Trusted cross-org collaboration — intelligent connections, founder network, privacy-first resource sharing. Opportunities, not exposure.',
    route: p('cross-organization-intelligence'),
    groupId: 'intelligence',
    status: 'demo',
    metric: 'M111',
    ctaLabel: 'OPEN CROSS-ORG INTELLIGENCE',
    moduleKey: 'cross-organization-intelligence',
    featuredOnOverview: true,
  },
  {
    id: 'relationship-memory',
    title: 'RELATIONSHIP MEMORY™',
    purpose: 'Professional familiarity — learn how founders, executives, and organizations prefer to work. Familiar, never intrusive.',
    route: p('relationship-memory'),
    groupId: 'intelligence',
    status: 'demo',
    metric: 'M112',
    ctaLabel: 'OPEN RELATIONSHIP MEMORY',
    moduleKey: 'relationship-memory',
    featuredOnOverview: true,
  },
  {
    id: 'predictive-organization',
    title: 'PREDICTIVE ORGANIZATION™',
    purpose: 'Anticipate opportunities, risks, bottlenecks, and trends — prepare for tomorrow before it arrives.',
    route: p('predictive-organization'),
    groupId: 'intelligence',
    status: 'demo',
    metric: 'M113',
    ctaLabel: 'OPEN PREDICTIVE ORGANIZATION',
    moduleKey: 'predictive-organization',
    featuredOnOverview: true,
  },
  {
    id: 'autonomous-preparation',
    title: 'AUTONOMOUS PREPARATION™',
    purpose: 'Quietly prepare work before founders ask — agendas, reports, launch assets. Nothing auto-executes.',
    route: p('autonomous-preparation'),
    groupId: 'intelligence',
    status: 'demo',
    metric: 'M114',
    ctaLabel: 'OPEN AUTONOMOUS PREPARATION',
    moduleKey: 'autonomous-preparation',
    featuredOnOverview: true,
  },
  {
    id: 'organizational-consciousness',
    title: 'ORGANIZATIONAL CONSCIOUSNESS™',
    purpose: 'Master intelligence layer — unifies every system into one continuously learning organizational consciousness.',
    route: p('organizational-consciousness'),
    groupId: 'intelligence',
    status: 'demo',
    metric: 'M115',
    ctaLabel: 'OPEN ORGANIZATIONAL CONSCIOUSNESS',
    moduleKey: 'organizational-consciousness',
    featuredOnOverview: true,
  },
  {
    id: 'world-knowledge-engine',
    title: 'WORLD KNOWLEDGE ENGINE™',
    purpose: 'Monitors the outside world — industry news, regulations, competitors, AI, trends. Filtered intelligence and executive briefings for your organization.',
    route: p('world-knowledge-engine'),
    groupId: 'intelligence',
    status: 'demo',
    metric: 'M117',
    ctaLabel: 'OPEN WORLD KNOWLEDGE ENGINE',
    moduleKey: 'world-knowledge-engine',
    featuredOnOverview: true,
  },
  {
    id: 'founder-operating-system',
    title: 'FOUNDER OPERATING SYSTEM™',
    purpose: 'Operates the founder — focus, coaching, leadership growth, decision load, burnout risk. Complements the Organization Dashboard. Studio OS V1 culmination.',
    route: p('founder-operating-system'),
    groupId: 'intelligence',
    status: 'demo',
    metric: 'M118',
    ctaLabel: 'OPEN FOUNDER OPERATING SYSTEM',
    moduleKey: 'founder-operating-system',
    featuredOnOverview: true,
  },
  {
    id: 'innovation-lab',
    title: 'INNOVATION LAB™',
    purpose: 'Permanent research, invention, and strategic ideation — continuously generate ideas from Profession Brain, Genome, Blueprint, Pulse, World Knowledge, and more.',
    route: p('innovation-lab'),
    groupId: 'intelligence',
    status: 'demo',
    metric: 'M119',
    ctaLabel: 'OPEN INNOVATION LAB',
    moduleKey: 'innovation-lab',
    featuredOnOverview: true,
  },
  {
    id: 'organization-operating-manual',
    title: 'ORGANIZATION OPERATING MANUAL™',
    purpose: 'Living operating manual — auto-generated documentation, searchable Q&A, live sync. One handbook, always current, single source of truth.',
    route: p('organization-operating-manual'),
    groupId: 'intelligence',
    status: 'demo',
    metric: 'M120',
    ctaLabel: 'OPEN OPERATING MANUAL',
    moduleKey: 'organization-operating-manual',
    featuredOnOverview: true,
  },
  {
    id: 'legacy-network',
    title: 'LEGACY NETWORK™',
    purpose: 'Permission-based global ecosystem — voluntarily share expertise, frameworks, and knowledge while retaining IP. Movement not marketplace.',
    route: p('legacy-network'),
    groupId: 'intelligence',
    status: 'demo',
    metric: 'M121',
    ctaLabel: 'OPEN LEGACY NETWORK',
    moduleKey: 'legacy-network',
    featuredOnOverview: true,
  },
  {
    id: 'studio-intelligence-architecture',
    title: 'STUDIO INTELLIGENCE™ ARCHITECTURE',
    purpose: 'Model-agnostic intelligence layer — Knowledge Fabric, Context Engine, durable pipeline. Studio OS owns knowledge; models reason.',
    route: p('studio-intelligence-architecture'),
    groupId: 'intelligence',
    status: 'demo',
    metric: 'M122',
    ctaLabel: 'OPEN INTELLIGENCE ARCHITECTURE',
    moduleKey: 'studio-intelligence-architecture',
    featuredOnOverview: true,
  },
  {
    id: 'model-orchestrator',
    title: 'MODEL ORCHESTRATOR™',
    purpose: 'AI abstraction layer & AI Swap Engine — interchangeable providers, multi-model routing, failover, benchmarking.',
    route: p('model-orchestrator'),
    groupId: 'intelligence',
    status: 'demo',
    metric: 'M123',
    ctaLabel: 'OPEN MODEL ORCHESTRATOR',
    moduleKey: 'model-orchestrator',
    featuredOnOverview: true,
  },
  {
    id: 'studio-foundation-models',
    title: 'STUDIO FOUNDATION MODELS™',
    purpose: 'Long-term Studio-owned intelligence roadmap — Foundation Models, Profession Models, hybrid intelligence, enterprise deployment.',
    route: p('studio-foundation-models'),
    groupId: 'intelligence',
    status: 'demo',
    metric: 'M124',
    ctaLabel: 'OPEN FOUNDATION MODELS',
    moduleKey: 'studio-foundation-models',
    featuredOnOverview: true,
  },
  {
    id: 'documentation-registry',
    title: 'DOCUMENTATION REGISTRY™',
    purpose: 'Single source of truth for all Studio OS documentation — register once, sync everywhere automatically.',
    route: p('documentation-registry'),
    groupId: 'intelligence',
    status: 'live',
    metric: 'M126',
    ctaLabel: 'OPEN DOCUMENTATION REGISTRY',
    moduleKey: 'documentation-registry',
    featuredOnOverview: true,
  },
  {
    id: 'documentation-governance',
    title: 'DOCUMENTATION GOVERNANCE™',
    purpose: 'Continuously monitor, validate, audit, and improve every piece of documentation across Studio OS.',
    route: p('documentation-governance'),
    groupId: 'intelligence',
    status: 'live',
    metric: 'M126.5',
    ctaLabel: 'OPEN DOCUMENTATION GOVERNANCE',
    moduleKey: 'documentation-governance',
    featuredOnOverview: true,
  },
  {
    id: 'system-registry',
    title: 'SYSTEM REGISTRY™',
    purpose: 'Master registry of every object, service, module, feature, and system inside Studio OS — nothing exists anonymously.',
    route: p('system-registry'),
    groupId: 'intelligence',
    status: 'live',
    metric: 'M127',
    ctaLabel: 'OPEN SYSTEM REGISTRY',
    moduleKey: 'system-registry',
    featuredOnOverview: true,
  },
  {
    id: 'component-registry',
    title: 'COMPONENT REGISTRY™',
    purpose: 'Every reusable UI component registered as a managed platform asset — assemble interfaces, never recreate.',
    route: p('component-registry'),
    groupId: 'intelligence',
    status: 'live',
    metric: 'M128',
    ctaLabel: 'OPEN COMPONENT REGISTRY',
    moduleKey: 'component-registry',
    featuredOnOverview: true,
  },
  {
    id: 'design-token-engine',
    title: 'DESIGN TOKEN ENGINE™',
    purpose: 'Visual source of truth — spacing, typography, colors, motion, elevation, and themes centralized for every Studio OS surface.',
    route: p('design-token-engine'),
    groupId: 'intelligence',
    status: 'live',
    metric: 'M129',
    ctaLabel: 'OPEN DESIGN TOKEN ENGINE',
    moduleKey: 'design-token-engine',
    featuredOnOverview: true,
  },
  {
    id: 'interaction-engine',
    title: 'INTERACTION ENGINE™',
    purpose: 'Behavioral source of truth — hover, focus, click, feedback, navigation, motion, and accessibility standardized platform-wide.',
    route: p('interaction-engine'),
    groupId: 'intelligence',
    status: 'live',
    metric: 'M130',
    ctaLabel: 'OPEN INTERACTION ENGINE',
    moduleKey: 'interaction-engine',
    featuredOnOverview: true,
  },
  {
    id: 'event-bus',
    title: 'EVENT BUS™',
    purpose: 'Communication backbone — publish/subscribe event-driven architecture. One event, many intelligent reactions.',
    route: p('event-bus'),
    groupId: 'intelligence',
    status: 'live',
    metric: 'M131',
    ctaLabel: 'OPEN EVENT BUS',
    moduleKey: 'event-bus',
    featuredOnOverview: true,
  },
  {
    id: 'automation-registry',
    title: 'AUTOMATION REGISTRY™',
    purpose: 'Every automation registered as an organizational asset — visible, searchable, auditable, manageable.',
    route: p('automation-registry'),
    groupId: 'intelligence',
    status: 'live',
    metric: 'M132',
    ctaLabel: 'OPEN AUTOMATION REGISTRY',
    moduleKey: 'automation-registry',
    featuredOnOverview: true,
  },
  {
    id: 'prompt-registry',
    title: 'PROMPT REGISTRY™',
    purpose: 'Centralized management for every AI prompt — versioned, searchable, testable, reusable. Prompts are code.',
    route: p('prompt-registry'),
    groupId: 'intelligence',
    status: 'live',
    metric: 'M133',
    ctaLabel: 'OPEN PROMPT REGISTRY',
    moduleKey: 'prompt-registry',
    featuredOnOverview: true,
  },
  {
    id: 'policy-engine',
    title: 'POLICY ENGINE™',
    purpose: 'Centralized rulebook — define policies once; every Concierge, automation, workflow, and department follows automatically.',
    route: p('policy-engine'),
    groupId: 'intelligence',
    status: 'live',
    metric: 'M134',
    ctaLabel: 'OPEN POLICY ENGINE',
    moduleKey: 'policy-engine',
    featuredOnOverview: true,
  },
  {
    id: 'permission-engine',
    title: 'PERMISSION ENGINE™',
    purpose: 'Enterprise authorization — capability-based access, role composition, contextual permissions, approval chains, audit.',
    route: p('permission-engine'),
    groupId: 'intelligence',
    status: 'live',
    metric: 'M135',
    ctaLabel: 'OPEN PERMISSION ENGINE',
    moduleKey: 'permission-engine',
    featuredOnOverview: true,
  },
  {
    id: 'workspace-runtime',
    title: 'WORKSPACE RUNTIME™',
    purpose: 'Isolated execution environment per organization — independent digital headquarters, sandboxes, runtime health.',
    route: p('workspace-runtime'),
    groupId: 'intelligence',
    status: 'live',
    metric: 'M136',
    ctaLabel: 'OPEN WORKSPACE RUNTIME',
    moduleKey: 'workspace-runtime',
    featuredOnOverview: true,
  },
  {
    id: 'plugin-sdk',
    title: 'PLUGIN SDK™',
    purpose: 'Extensible platform — plugin types, SDK registration, sandbox execution, marketplace infrastructure.',
    route: p('plugin-sdk'),
    groupId: 'intelligence',
    status: 'live',
    metric: 'M137',
    ctaLabel: 'OPEN PLUGIN SDK',
    moduleKey: 'plugin-sdk',
    featuredOnOverview: true,
  },
  {
    id: 'workflow-engine',
    title: 'WORKFLOW ENGINE™',
    purpose: 'Visual orchestration — drag-and-drop builder, testing, analytics, living organizational processes.',
    route: p('workflow-engine'),
    groupId: 'intelligence',
    status: 'live',
    metric: 'M138',
    ctaLabel: 'OPEN WORKFLOW ENGINE',
    moduleKey: 'workflow-engine',
    featuredOnOverview: true,
  },
  {
    id: 'state-engine',
    title: 'STATE ENGINE™',
    purpose: 'Centralized lifecycle management — defined states, policy-enforced transitions, complete history.',
    route: p('state-engine'),
    groupId: 'intelligence',
    status: 'live',
    metric: 'M139',
    ctaLabel: 'OPEN STATE ENGINE',
    moduleKey: 'state-engine',
    featuredOnOverview: true,
  },
  {
    id: 'asset-registry',
    title: 'ASSET REGISTRY™',
    purpose: 'Permanent asset home — images, videos, docs, brand kits; metadata, versioning, health monitoring.',
    route: p('asset-registry'),
    groupId: 'intelligence',
    status: 'live',
    metric: 'M140',
    ctaLabel: 'OPEN ASSET REGISTRY',
    moduleKey: 'asset-registry',
    featuredOnOverview: true,
  },
  {
    id: 'experience-engine',
    title: 'EXPERIENCE ENGINE™',
    purpose: 'Emotional and environmental layer — adaptive atmosphere, context-aware modes, subtle transitions.',
    route: p('experience-engine'),
    groupId: 'intelligence',
    status: 'live',
    metric: 'M141',
    ctaLabel: 'OPEN EXPERIENCE ENGINE',
    moduleKey: 'experience-engine',
    featuredOnOverview: true,
  },
  {
    id: 'qa-headquarters',
    title: 'QA HEADQUARTERS™',
    purpose: 'Permanent QA operating layer — Trust Scores™, continuous validation, workflow and AI integrity monitoring.',
    route: p('qa-headquarters'),
    groupId: 'intelligence',
    status: 'live',
    metric: 'M142',
    ctaLabel: 'OPEN QA HEADQUARTERS',
    moduleKey: 'qa-headquarters',
    featuredOnOverview: true,
  },
  {
    id: 'qa-inspector',
    title: 'QA INSPECTOR™',
    purpose: 'Intelligent continuous audit — broken workflows, conflicting automations, permission conflicts. Recommends only.',
    route: p('qa-inspector'),
    groupId: 'intelligence',
    status: 'live',
    metric: 'M143',
    ctaLabel: 'OPEN QA INSPECTOR',
    moduleKey: 'qa-inspector',
    featuredOnOverview: true,
  },
  {
    id: 'qa-simulation-engine',
    title: 'QA SIMULATION ENGINE™',
    purpose: 'Pre-production practice field — simulate customer, employee, founder journeys before production.',
    route: p('qa-simulation-engine'),
    groupId: 'intelligence',
    status: 'live',
    metric: 'M144',
    ctaLabel: 'OPEN QA SIMULATION ENGINE',
    moduleKey: 'qa-simulation-engine',
    featuredOnOverview: true,
  },
  {
    id: 'succession-mode',
    title: 'SUCCESSION MODE™',
    purpose: 'Succession readiness — survive founder unavailability. Knowledge dependency map, recommendations, legacy continuity.',
    route: p('succession-mode'),
    groupId: 'intelligence',
    status: 'demo',
    metric: 'M98',
    ctaLabel: 'OPEN SUCCESSION MODE',
    moduleKey: 'succession-mode',
    featuredOnOverview: true,
  },
  {
    id: 'expansion-center',
    title: 'EXPANSION CENTER',
    purpose: 'Three-layer economy — Headquarters License, permanent Department Packs, Digital Workforce payroll. Grow the organization, never buy software.',
    route: p('expansion-center'),
    groupId: 'settings',
    status: 'demo',
    metric: 'M89',
    ctaLabel: 'EXPAND HQ',
    moduleKey: 'expansion-center',
    featuredOnOverview: true,
  },
  {
    id: 'governance',
    title: 'STUDIO OS GOVERNANCE',
    purpose: 'Trust, quality, compliance, moderation, verification, certification — platform constitution for responsible growth.',
    route: p('governance'),
    groupId: 'intelligence',
    status: 'demo',
    metric: '14 TABS',
    ctaLabel: 'OPEN GOVERNANCE',
    moduleKey: 'governance',
    featuredOnOverview: true,
  },
  {
    id: 'studio-intelligence',
    title: 'STUDIO INTELLIGENCE',
    purpose: 'Operating intelligence — executive briefings, opportunity/risk engines, business health, proactive recommendations.',
    route: p('studio-intelligence'),
    groupId: 'intelligence',
    status: 'demo',
    metric: '14 TABS',
    ctaLabel: 'OPEN INTELLIGENCE',
    moduleKey: 'studio-intelligence',
    featuredOnOverview: true,
  },
  {
    id: 'simulation-engine',
    title: 'SIMULATION ENGINE',
    purpose: 'Model decisions before committing — scenarios, risk, financial/marketing/content sims. Not predictions.',
    route: p('simulation-engine'),
    groupId: 'intelligence',
    status: 'demo',
    metric: '14 TABS',
    ctaLabel: 'OPEN SIMULATION',
    moduleKey: 'simulation-engine',
    featuredOnOverview: true,
  },
  {
    id: 'vision-engine',
    title: 'VISION ENGINE',
    purpose: 'Generate cinematic Vision Modes — Builder, Recorder, Share, Analytics. Internal only.',
    route: p('vision-engine'),
    groupId: 'intelligence',
    status: 'demo',
    metric: '11 MODES',
    ctaLabel: 'OPEN VISION',
    moduleKey: 'vision-engine',
    featuredOnOverview: true,
  },
  {
    id: 'analytics',
    title: 'ANALYTICS',
    purpose: 'Track views, completion, and content performance.',
    route: p('analytics'),
    groupId: 'intelligence',
    status: 'coming-soon',
    metric: '—',
    ctaLabel: 'VIEW ANALYTICS',
    featuredOnOverview: true,
  },
  // LEGACY
  {
    id: 'legacy-system',
    title: 'LEGACY SYSTEM',
    purpose: 'Preserve institutional memory and the living museum of the brand.',
    route: p('legacy-system'),
    groupId: 'legacy',
    status: 'demo',
    metric: 'MUSEUM',
    ctaLabel: 'ENTER LEGACY',
    moduleKey: 'legacy-system',
    featuredOnOverview: true,
  },
  {
    id: 'legacy-archives',
    title: 'ARCHIVES',
    purpose: 'Browse historical records, campaigns, and milestone documents.',
    route: `${p('legacy-system/museum')}?tab=archives`,
    groupId: 'legacy',
    status: 'demo',
    metric: '48 RECORDS',
    ctaLabel: 'OPEN ARCHIVES',
    featuredOnOverview: true,
  },
  {
    id: 'legacy-hall-of-fame',
    title: 'HALL OF FAME',
    purpose: 'Celebrate standout talent, shows, and community moments.',
    route: `${p('legacy-system/museum')}?tab=hall-of-fame`,
    groupId: 'legacy',
    status: 'demo',
    metric: '12 INDUCTEES',
    ctaLabel: 'VIEW HALL',
    featuredOnOverview: true,
  },
  {
    id: 'legacy-vault-of-firsts',
    title: 'VAULT OF FIRSTS',
    purpose: 'Honor first-of-their-kind wins and breakthrough moments (Legacy System museum).',
    route: `${p('legacy-system/museum')}?tab=vault`,
    groupId: 'legacy',
    status: 'demo',
    metric: '9 FIRSTS',
    ctaLabel: 'OPEN VAULT',
    featuredOnOverview: true,
  },
  // SETTINGS
  {
    id: 'workspace-settings',
    title: 'WORKSPACE SETTINGS',
    purpose: 'Switch workspaces and manage brand-scoped Studio access.',
    route: '/admin/studio-os',
    groupId: 'settings',
    status: 'live',
    metric: '4 SPACES',
    ctaLabel: 'OPEN WORKSPACES',
    featuredOnOverview: true,
  },
  {
    id: 'brand-config',
    title: 'BRAND CONFIG',
    purpose: 'Edit brand voice, rules, and visual standards in Content Brain.',
    route: p('content-brain/brand-brain'),
    groupId: 'settings',
    status: 'demo',
    metric: 'BRAND',
    ctaLabel: 'EDIT BRAND',
    featuredOnOverview: true,
  },
  {
    id: 'platform-settings',
    title: 'PLATFORM SETTINGS',
    purpose: 'studio os platform identity and workspace registry (VXD Inc.).',
    route: '/admin/studio-os',
    groupId: 'settings',
    status: 'live',
    metric: 'STUDIO OS',
    ctaLabel: 'PLATFORM',
    featuredOnOverview: true,
  },
] as const;

const MODULES_BY_ROUTE_LENGTH = [...ADMIN_STUDIO_MODULES].sort((a, b) => {
  const aBase = a.route.split('?')[0];
  const bBase = b.route.split('?')[0];
  return bBase.length - aBase.length;
});

export function getStudioNavGroup(id: StudioNavGroupId): StudioNavGroup | undefined {
  return STUDIO_NAV_GROUPS.find((g) => g.id === id);
}

export function getStudioModuleById(id: string): AdminStudioModule | undefined {
  return ADMIN_STUDIO_MODULES.find((m) => m.id === id);
}

export function getModulesForGroup(groupId: StudioNavGroupId, options?: { overviewOnly?: boolean }): AdminStudioModule[] {
  const list = ADMIN_STUDIO_MODULES.filter((m) => m.groupId === groupId);
  if (options?.overviewOnly) {
    const featured = list.filter((m) => m.featuredOnOverview);
    return featured.length > 0 ? featured : list.slice(0, 6);
  }
  return list;
}

/** M83 — module count for department summarization cards. */
export function countModulesForGroup(groupId: StudioNavGroupId): number {
  return ADMIN_STUDIO_MODULES.filter((m) => m.groupId === groupId).length;
}

export function resolveStudioModuleFromPath(pathname: string): AdminStudioModule | undefined {
  const normalized = pathname.replace(/\/$/, '') || '/';

  if (normalized === `${ADMIN_STUDIO_BASE_PATH}/hub`) {
    return getStudioModuleById('studio-overview');
  }

  for (const mod of MODULES_BY_ROUTE_LENGTH) {
    const base = mod.route.split('?')[0];
    if (normalized === base || normalized.startsWith(`${base}/`)) {
      return mod;
    }
  }

  const sectionMatch = normalized.match(new RegExp(`^${ADMIN_STUDIO_BASE_PATH}/([^/]+)`));
  if (sectionMatch) {
    const sectionId = sectionMatch[1];
    return ADMIN_STUDIO_MODULES.find((m) => m.id === sectionId);
  }

  return undefined;
}

export type StudioBreadcrumbSegment = {
  label: string;
  path?: string;
};

export function buildStudioBreadcrumbs(pathname: string, pageTitle?: string): StudioBreadcrumbSegment[] {
  const mod = resolveStudioModuleFromPath(pathname);
  const segments: StudioBreadcrumbSegment[] = [
    { label: 'ADMIN', path: '/admin/dashboard' },
    { label: 'STUDIO OS', path: STUDIO_OVERVIEW_PATH },
  ];

  if (mod) {
    const group = getStudioNavGroup(mod.groupId);
    if (group) {
      segments.push({ label: group.label, path: `${STUDIO_OVERVIEW_PATH}?group=${mod.groupId}` });
    }
    if (mod.id !== 'studio-overview') {
      segments.push({ label: mod.title, path: mod.route.split('?')[0] });
    }
  }

  if (pageTitle && pageTitle !== mod?.title) {
    segments.push({ label: pageTitle });
  }

  return segments;
}

export const STUDIO_STATUS_LABELS: Record<StudioModuleStatus, string> = {
  live: 'LIVE',
  demo: 'DEMO',
  'coming-soon': 'COMING SOON',
};
