/** Auto-generated by scripts/bcf/sync-bcf-video-manifest.mjs — do not edit by hand. */
export const BCF_PDP_HERO_VIDEOS = {
  "bundles-curly-ash": {
    "mp4StoragePath": "BCF/videos/v1/bundles-curly-ash.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-curly-ash",
    "category": "bundles",
    "texture": "curly",
    "colorId": "ASH"
  },
  "bundles-curly-auburn": {
    "mp4StoragePath": "BCF/videos/v1/bundles-curly-auburn.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-curly-auburn",
    "category": "bundles",
    "texture": "curly",
    "colorId": "AUBURN"
  },
  "bundles-curly-cherry": {
    "mp4StoragePath": "BCF/videos/v1/bundles-curly-cherry.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-curly-cherry",
    "category": "bundles",
    "texture": "curly",
    "colorId": "CHERRY"
  },
  "bundles-curly-chestnut": {
    "mp4StoragePath": "BCF/videos/v1/bundles-curly-chestnut.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-curly-chestnut",
    "category": "bundles",
    "texture": "curly",
    "colorId": "CHESTNUT"
  },
  "bundles-curly-citrine": {
    "mp4StoragePath": "BCF/videos/v1/bundles-curly-citrine.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-curly-citrine",
    "category": "bundles",
    "texture": "curly",
    "colorId": "CITRINE"
  },
  "bundles-curly-cobalt": {
    "mp4StoragePath": "BCF/videos/v1/bundles-curly-cobalt.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-curly-cobalt",
    "category": "bundles",
    "texture": "curly",
    "colorId": "COBALT"
  },
  "bundles-curly-copper": {
    "mp4StoragePath": "BCF/videos/v1/bundles-curly-copper.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-curly-copper",
    "category": "bundles",
    "texture": "curly",
    "colorId": "COPPER"
  },
  "bundles-curly-default": {
    "mp4StoragePath": "wig-preview-live/make_this_image_shake_the_hair_Kling_30__24695.mov",
    "webmStoragePath": null,
    "status": "ready_legacy",
    "productKey": "bundles-curly-default",
    "category": "bundles",
    "texture": "curly",
    "colorId": "DEFAULT"
  },
  "bundles-curly-espresso": {
    "mp4StoragePath": "BCF/videos/v1/bundles-curly-espresso.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-curly-espresso",
    "category": "bundles",
    "texture": "curly",
    "colorId": "ESPRESSO"
  },
  "bundles-curly-ginger": {
    "mp4StoragePath": "BCF/videos/v1/bundles-curly-ginger.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-curly-ginger",
    "category": "bundles",
    "texture": "curly",
    "colorId": "GINGER"
  },
  "bundles-curly-golden": {
    "mp4StoragePath": "BCF/videos/v1/bundles-curly-golden.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-curly-golden",
    "category": "bundles",
    "texture": "curly",
    "colorId": "GOLDEN"
  },
  "bundles-curly-honey": {
    "mp4StoragePath": "BCF/videos/v1/bundles-curly-honey.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-curly-honey",
    "category": "bundles",
    "texture": "curly",
    "colorId": "HONEY"
  },
  "bundles-curly-jet-black": {
    "mp4StoragePath": "BCF/videos/v1/bundles-curly-jet-black.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-curly-jet-black",
    "category": "bundles",
    "texture": "curly",
    "colorId": "JET BLACK"
  },
  "bundles-curly-platinum": {
    "mp4StoragePath": "BCF/videos/v1/bundles-curly-platinum.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-curly-platinum",
    "category": "bundles",
    "texture": "curly",
    "colorId": "PLATINUM"
  },
  "bundles-curly-plum": {
    "mp4StoragePath": "BCF/videos/v1/bundles-curly-plum.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-curly-plum",
    "category": "bundles",
    "texture": "curly",
    "colorId": "PLUM"
  },
  "bundles-curly-raspberry": {
    "mp4StoragePath": "BCF/videos/v1/bundles-curly-raspberry.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-curly-raspberry",
    "category": "bundles",
    "texture": "curly",
    "colorId": "RASPBERRY"
  },
  "bundles-curly-sangria": {
    "mp4StoragePath": "BCF/videos/v1/bundles-curly-sangria.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-curly-sangria",
    "category": "bundles",
    "texture": "curly",
    "colorId": "SANGRIA"
  },
  "bundles-curly-slime": {
    "mp4StoragePath": "BCF/videos/v1/bundles-curly-slime.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-curly-slime",
    "category": "bundles",
    "texture": "curly",
    "colorId": "SLIME"
  },
  "bundles-curly-teal": {
    "mp4StoragePath": "BCF/videos/v1/bundles-curly-teal.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-curly-teal",
    "category": "bundles",
    "texture": "curly",
    "colorId": "TEAL"
  },
  "bundles-straight-ash": {
    "mp4StoragePath": "BCF/videos/v1/bundles-straight-ash.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-straight-ash",
    "category": "bundles",
    "texture": "straight",
    "colorId": "ASH"
  },
  "bundles-straight-auburn": {
    "mp4StoragePath": "BCF/videos/v1/bundles-straight-auburn.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-straight-auburn",
    "category": "bundles",
    "texture": "straight",
    "colorId": "AUBURN"
  },
  "bundles-straight-cherry": {
    "mp4StoragePath": "BCF/videos/v1/bundles-straight-cherry.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-straight-cherry",
    "category": "bundles",
    "texture": "straight",
    "colorId": "CHERRY"
  },
  "bundles-straight-chestnut": {
    "mp4StoragePath": "BCF/videos/v1/bundles-straight-chestnut.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-straight-chestnut",
    "category": "bundles",
    "texture": "straight",
    "colorId": "CHESTNUT"
  },
  "bundles-straight-citrine": {
    "mp4StoragePath": "BCF/videos/v1/bundles-straight-citrine.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-straight-citrine",
    "category": "bundles",
    "texture": "straight",
    "colorId": "CITRINE"
  },
  "bundles-straight-cobalt": {
    "mp4StoragePath": "BCF/videos/v1/bundles-straight-cobalt.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-straight-cobalt",
    "category": "bundles",
    "texture": "straight",
    "colorId": "COBALT"
  },
  "bundles-straight-copper": {
    "mp4StoragePath": "BCF/videos/v1/bundles-straight-copper.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-straight-copper",
    "category": "bundles",
    "texture": "straight",
    "colorId": "COPPER"
  },
  "bundles-straight-default": {
    "mp4StoragePath": "wig-preview-live/make_this_image_shake_the_hair_Kling_30__51488.mov",
    "webmStoragePath": null,
    "status": "ready_legacy",
    "productKey": "bundles-straight-default",
    "category": "bundles",
    "texture": "straight",
    "colorId": "DEFAULT"
  },
  "bundles-straight-espresso": {
    "mp4StoragePath": "BCF/videos/v1/bundles-straight-espresso.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-straight-espresso",
    "category": "bundles",
    "texture": "straight",
    "colorId": "ESPRESSO"
  },
  "bundles-straight-ginger": {
    "mp4StoragePath": "BCF/videos/v1/bundles-straight-ginger.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-straight-ginger",
    "category": "bundles",
    "texture": "straight",
    "colorId": "GINGER"
  },
  "bundles-straight-golden": {
    "mp4StoragePath": "BCF/videos/v1/bundles-straight-golden.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-straight-golden",
    "category": "bundles",
    "texture": "straight",
    "colorId": "GOLDEN"
  },
  "bundles-straight-honey": {
    "mp4StoragePath": "BCF/videos/v1/bundles-straight-honey.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-straight-honey",
    "category": "bundles",
    "texture": "straight",
    "colorId": "HONEY"
  },
  "bundles-straight-jet-black": {
    "mp4StoragePath": "BCF/videos/v1/bundles-straight-jet-black.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-straight-jet-black",
    "category": "bundles",
    "texture": "straight",
    "colorId": "JET BLACK"
  },
  "bundles-straight-platinum": {
    "mp4StoragePath": "BCF/videos/v1/bundles-straight-platinum.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-straight-platinum",
    "category": "bundles",
    "texture": "straight",
    "colorId": "PLATINUM"
  },
  "bundles-straight-plum": {
    "mp4StoragePath": "BCF/videos/v1/bundles-straight-plum.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-straight-plum",
    "category": "bundles",
    "texture": "straight",
    "colorId": "PLUM"
  },
  "bundles-straight-raspberry": {
    "mp4StoragePath": "BCF/videos/v1/bundles-straight-raspberry.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-straight-raspberry",
    "category": "bundles",
    "texture": "straight",
    "colorId": "RASPBERRY"
  },
  "bundles-straight-sangria": {
    "mp4StoragePath": "BCF/videos/v1/bundles-straight-sangria.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-straight-sangria",
    "category": "bundles",
    "texture": "straight",
    "colorId": "SANGRIA"
  },
  "bundles-straight-slime": {
    "mp4StoragePath": "BCF/videos/v1/bundles-straight-slime.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-straight-slime",
    "category": "bundles",
    "texture": "straight",
    "colorId": "SLIME"
  },
  "bundles-straight-teal": {
    "mp4StoragePath": "BCF/videos/v1/bundles-straight-teal.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-straight-teal",
    "category": "bundles",
    "texture": "straight",
    "colorId": "TEAL"
  },
  "bundles-wavy-ash": {
    "mp4StoragePath": "BCF/videos/v1/bundles-wavy-ash.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-wavy-ash",
    "category": "bundles",
    "texture": "wavy",
    "colorId": "ASH"
  },
  "bundles-wavy-auburn": {
    "mp4StoragePath": "BCF/videos/v1/bundles-wavy-auburn.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-wavy-auburn",
    "category": "bundles",
    "texture": "wavy",
    "colorId": "AUBURN"
  },
  "bundles-wavy-cherry": {
    "mp4StoragePath": "BCF/videos/v1/bundles-wavy-cherry.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-wavy-cherry",
    "category": "bundles",
    "texture": "wavy",
    "colorId": "CHERRY"
  },
  "bundles-wavy-chestnut": {
    "mp4StoragePath": "BCF/videos/v1/bundles-wavy-chestnut.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-wavy-chestnut",
    "category": "bundles",
    "texture": "wavy",
    "colorId": "CHESTNUT"
  },
  "bundles-wavy-citrine": {
    "mp4StoragePath": "BCF/videos/v1/bundles-wavy-citrine.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-wavy-citrine",
    "category": "bundles",
    "texture": "wavy",
    "colorId": "CITRINE"
  },
  "bundles-wavy-cobalt": {
    "mp4StoragePath": "BCF/videos/v1/bundles-wavy-cobalt.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-wavy-cobalt",
    "category": "bundles",
    "texture": "wavy",
    "colorId": "COBALT"
  },
  "bundles-wavy-copper": {
    "mp4StoragePath": "BCF/videos/v1/bundles-wavy-copper.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-wavy-copper",
    "category": "bundles",
    "texture": "wavy",
    "colorId": "COPPER"
  },
  "bundles-wavy-default": {
    "mp4StoragePath": "wig-preview-live/make_this_image_shake_the_hair_Kling_30__98237.mov",
    "webmStoragePath": null,
    "status": "ready_legacy",
    "productKey": "bundles-wavy-default",
    "category": "bundles",
    "texture": "wavy",
    "colorId": "DEFAULT"
  },
  "bundles-wavy-espresso": {
    "mp4StoragePath": "BCF/videos/v1/bundles-wavy-espresso.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-wavy-espresso",
    "category": "bundles",
    "texture": "wavy",
    "colorId": "ESPRESSO"
  },
  "bundles-wavy-ginger": {
    "mp4StoragePath": "BCF/videos/v1/bundles-wavy-ginger.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-wavy-ginger",
    "category": "bundles",
    "texture": "wavy",
    "colorId": "GINGER"
  },
  "bundles-wavy-golden": {
    "mp4StoragePath": "BCF/videos/v1/bundles-wavy-golden.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-wavy-golden",
    "category": "bundles",
    "texture": "wavy",
    "colorId": "GOLDEN"
  },
  "bundles-wavy-honey": {
    "mp4StoragePath": "BCF/videos/v1/bundles-wavy-honey.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-wavy-honey",
    "category": "bundles",
    "texture": "wavy",
    "colorId": "HONEY"
  },
  "bundles-wavy-jet-black": {
    "mp4StoragePath": "BCF/videos/v1/bundles-wavy-jet-black.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-wavy-jet-black",
    "category": "bundles",
    "texture": "wavy",
    "colorId": "JET BLACK"
  },
  "bundles-wavy-platinum": {
    "mp4StoragePath": "BCF/videos/v1/bundles-wavy-platinum.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-wavy-platinum",
    "category": "bundles",
    "texture": "wavy",
    "colorId": "PLATINUM"
  },
  "bundles-wavy-plum": {
    "mp4StoragePath": "BCF/videos/v1/bundles-wavy-plum.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-wavy-plum",
    "category": "bundles",
    "texture": "wavy",
    "colorId": "PLUM"
  },
  "bundles-wavy-raspberry": {
    "mp4StoragePath": "BCF/videos/v1/bundles-wavy-raspberry.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-wavy-raspberry",
    "category": "bundles",
    "texture": "wavy",
    "colorId": "RASPBERRY"
  },
  "bundles-wavy-sangria": {
    "mp4StoragePath": "BCF/videos/v1/bundles-wavy-sangria.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-wavy-sangria",
    "category": "bundles",
    "texture": "wavy",
    "colorId": "SANGRIA"
  },
  "bundles-wavy-slime": {
    "mp4StoragePath": "BCF/videos/v1/bundles-wavy-slime.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-wavy-slime",
    "category": "bundles",
    "texture": "wavy",
    "colorId": "SLIME"
  },
  "bundles-wavy-teal": {
    "mp4StoragePath": "BCF/videos/v1/bundles-wavy-teal.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-wavy-teal",
    "category": "bundles",
    "texture": "wavy",
    "colorId": "TEAL"
  },
  "closures-curly-default": {
    "mp4StoragePath": "wig-preview-live/make_this_image_shake_the_hair_Kling_30__28643.mov",
    "webmStoragePath": null,
    "status": "ready_legacy",
    "productKey": "closures-curly-default",
    "category": "closures",
    "texture": "curly",
    "colorId": "DEFAULT"
  },
  "closures-straight-ash": {
    "mp4StoragePath": "BCF/videos/v1/closures-straight-ash.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "closures-straight-ash",
    "category": "closures",
    "texture": "straight",
    "colorId": "ASH"
  },
  "closures-straight-default": {
    "mp4StoragePath": "wig-preview-live/make_this_image_shake_the_hair_Kling_30__27854.mov",
    "webmStoragePath": null,
    "status": "ready_legacy",
    "productKey": "closures-straight-default",
    "category": "closures",
    "texture": "straight",
    "colorId": "DEFAULT"
  },
  "closures-straight-golden": {
    "mp4StoragePath": "BCF/videos/v1/closures-straight-golden.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "closures-straight-golden",
    "category": "closures",
    "texture": "straight",
    "colorId": "GOLDEN"
  },
  "closures-straight-platinum": {
    "mp4StoragePath": "BCF/videos/v1/closures-straight-platinum.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "closures-straight-platinum",
    "category": "closures",
    "texture": "straight",
    "colorId": "PLATINUM"
  },
  "closures-wavy-ash": {
    "mp4StoragePath": "BCF/videos/v1/closures-wavy-ash.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "closures-wavy-ash",
    "category": "closures",
    "texture": "wavy",
    "colorId": "ASH"
  },
  "closures-wavy-default": {
    "mp4StoragePath": "wig-preview-live/make_this_image_shake_the_hair_Kling_30__49906.mov",
    "webmStoragePath": null,
    "status": "ready_legacy",
    "productKey": "closures-wavy-default",
    "category": "closures",
    "texture": "wavy",
    "colorId": "DEFAULT"
  },
  "closures-wavy-golden": {
    "mp4StoragePath": "BCF/videos/v1/closures-wavy-golden.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "closures-wavy-golden",
    "category": "closures",
    "texture": "wavy",
    "colorId": "GOLDEN"
  },
  "closures-wavy-platinum": {
    "mp4StoragePath": "BCF/videos/v1/closures-wavy-platinum.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "closures-wavy-platinum",
    "category": "closures",
    "texture": "wavy",
    "colorId": "PLATINUM"
  },
  "frontals-curly-default": {
    "mp4StoragePath": "wig-preview-live/make_this_image_shake_the_hair_Kling_30__79392.mov",
    "webmStoragePath": null,
    "status": "ready_legacy",
    "productKey": "frontals-curly-default",
    "category": "frontals",
    "texture": "curly",
    "colorId": "DEFAULT"
  },
  "frontals-straight-ash": {
    "mp4StoragePath": "BCF/videos/v1/frontals-straight-ash.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "frontals-straight-ash",
    "category": "frontals",
    "texture": "straight",
    "colorId": "ASH"
  },
  "frontals-straight-default": {
    "mp4StoragePath": "wig-preview-live/make_this_image_shake_the_hair_Kling_30__79719.mov",
    "webmStoragePath": null,
    "status": "ready_legacy",
    "productKey": "frontals-straight-default",
    "category": "frontals",
    "texture": "straight",
    "colorId": "DEFAULT"
  },
  "frontals-straight-golden": {
    "mp4StoragePath": "BCF/videos/v1/frontals-straight-golden.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "frontals-straight-golden",
    "category": "frontals",
    "texture": "straight",
    "colorId": "GOLDEN"
  },
  "frontals-straight-platinum": {
    "mp4StoragePath": "BCF/videos/v1/frontals-straight-platinum.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "frontals-straight-platinum",
    "category": "frontals",
    "texture": "straight",
    "colorId": "PLATINUM"
  },
  "frontals-wavy-ash": {
    "mp4StoragePath": "BCF/videos/v1/frontals-wavy-ash.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "frontals-wavy-ash",
    "category": "frontals",
    "texture": "wavy",
    "colorId": "ASH"
  },
  "frontals-wavy-default": {
    "mp4StoragePath": "wig-preview-live/make_this_image_slowly_showcas_Kling_30__78091.mov",
    "webmStoragePath": null,
    "status": "ready_legacy",
    "productKey": "frontals-wavy-default",
    "category": "frontals",
    "texture": "wavy",
    "colorId": "DEFAULT"
  },
  "frontals-wavy-golden": {
    "mp4StoragePath": "BCF/videos/v1/frontals-wavy-golden.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "frontals-wavy-golden",
    "category": "frontals",
    "texture": "wavy",
    "colorId": "GOLDEN"
  },
  "frontals-wavy-platinum": {
    "mp4StoragePath": "BCF/videos/v1/frontals-wavy-platinum.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "frontals-wavy-platinum",
    "category": "frontals",
    "texture": "wavy",
    "colorId": "PLATINUM"
  }
} as const;
export type BcfPdpHeroVideoEntry = (typeof BCF_PDP_HERO_VIDEOS)[keyof typeof BCF_PDP_HERO_VIDEOS];
