/** Auto-generated by scripts/bcf/sync-bcf-video-manifest.mjs — do not edit by hand. */
export const BCF_PDP_HERO_VIDEOS = {
  "bundles-curly-ash": {
    "mp4StoragePath": "BCF/videos/v1/bundles-curly-ash.mp4",
    "webmStoragePath": null,
    "status": "ready_mp4_only",
    "productKey": "bundles-curly-ash",
    "category": "bundles",
    "texture": "curly",
    "colorId": "ASH"
  },
  "bundles-curly-default": {
    "mp4StoragePath": "wig-preview-live/make_this_image_shake_the_hair_Kling_30__24695.mov",
    "webmStoragePath": null,
    "status": "ready_legacy",
    "productKey": "bundles-curly-default",
    "category": "bundles",
    "texture": "curly",
    "colorId": "DEFAULT"
  },
  "bundles-straight-default": {
    "mp4StoragePath": "wig-preview-live/make_this_image_shake_the_hair_Kling_30__51488.mov",
    "webmStoragePath": null,
    "status": "ready_legacy",
    "productKey": "bundles-straight-default",
    "category": "bundles",
    "texture": "straight",
    "colorId": "DEFAULT"
  },
  "bundles-wavy-default": {
    "mp4StoragePath": "wig-preview-live/make_this_image_shake_the_hair_Kling_30__98237.mov",
    "webmStoragePath": null,
    "status": "ready_legacy",
    "productKey": "bundles-wavy-default",
    "category": "bundles",
    "texture": "wavy",
    "colorId": "DEFAULT"
  },
  "closures-curly-default": {
    "mp4StoragePath": "wig-preview-live/make_this_image_shake_the_hair_Kling_30__28643.mov",
    "webmStoragePath": null,
    "status": "ready_legacy",
    "productKey": "closures-curly-default",
    "category": "closures",
    "texture": "curly",
    "colorId": "DEFAULT"
  },
  "closures-straight-default": {
    "mp4StoragePath": "wig-preview-live/make_this_image_shake_the_hair_Kling_30__27854.mov",
    "webmStoragePath": null,
    "status": "ready_legacy",
    "productKey": "closures-straight-default",
    "category": "closures",
    "texture": "straight",
    "colorId": "DEFAULT"
  },
  "closures-wavy-default": {
    "mp4StoragePath": "wig-preview-live/make_this_image_shake_the_hair_Kling_30__49906.mov",
    "webmStoragePath": null,
    "status": "ready_legacy",
    "productKey": "closures-wavy-default",
    "category": "closures",
    "texture": "wavy",
    "colorId": "DEFAULT"
  },
  "frontals-curly-default": {
    "mp4StoragePath": "wig-preview-live/make_this_image_shake_the_hair_Kling_30__79392.mov",
    "webmStoragePath": null,
    "status": "ready_legacy",
    "productKey": "frontals-curly-default",
    "category": "frontals",
    "texture": "curly",
    "colorId": "DEFAULT"
  },
  "frontals-straight-default": {
    "mp4StoragePath": "wig-preview-live/make_this_image_shake_the_hair_Kling_30__79719.mov",
    "webmStoragePath": null,
    "status": "ready_legacy",
    "productKey": "frontals-straight-default",
    "category": "frontals",
    "texture": "straight",
    "colorId": "DEFAULT"
  },
  "frontals-wavy-default": {
    "mp4StoragePath": "wig-preview-live/make_this_image_slowly_showcas_Kling_30__78091.mov",
    "webmStoragePath": null,
    "status": "ready_legacy",
    "productKey": "frontals-wavy-default",
    "category": "frontals",
    "texture": "wavy",
    "colorId": "DEFAULT"
  }
} as const;
export type BcfPdpHeroVideoEntry = (typeof BCF_PDP_HERO_VIDEOS)[keyof typeof BCF_PDP_HERO_VIDEOS];
