/** Member-facing PSA hairstyle analysis delivery window (timeline only in copy). */
export const PSA_HAIR_ANALYSIS_DELIVERY_HOURS = 24;

export const PSA_HAIR_ANALYSIS_SUBMITTED_MESSAGE =
  'YOUR HAIR ANALYSIS IS SUBMITTED. YOUR PERSONALIZED RESULTS WILL BE READY WITHIN 24 HOURS.';

export const PSA_HAIR_ANALYSIS_PANEL_COPY =
  'UPLOAD A SELFIE — YOUR PERSONALIZED HAIR ANALYSIS RETURNS WITHIN 24 HOURS. LIVE TRY-ON IN BUILD-A-WIG STAYS SEPARATE.';
