/** Per-unit DETAILS tab specs for the six wig unit PDPs. */

export type WigUnitKey =
  | 'noir'
  | 'blanco'
  | 'soft-wave'
  | 'beach-wave'
  | 'soft-curl'
  | 'ocean-curl';

type UnitPattern = 'STRAIGHT' | 'WAVY' | 'CURLY';

interface UnitPdpDetailsSpec {
  origin: string;
  pattern: UnitPattern;
  density: string;
  /** Full color phrase used in the length/density bullet. */
  colorPhrase: string;
}

const UNIT_DETAILS_INTRO =
  'WHETHER YOU PREFER A SLEEK EVERYDAY LOOK OR A FULLY CUSTOMIZED TRANSFORMATION, THIS UNIT WAS DESIGNED TO PROVIDE MAXIMUM VERSATILITY, DURABILITY AND LONGEVITY WITH THE MOST NATURAL LOOKING RESULTS. EVERY DETAIL HAS BEEN CAREFULLY SELECTED TO ENSURE A FLAWLESS FINISH THAT LOOKS EXPENSIVE, FEELS COMFORTABLE AND STANDS THE TEST OF TIME.';

const SHARED_DETAILS_BULLETS_TAIL = [
  'CONSTRUCTED ON A STRETCHY, BREATHABLE CAP EQUIPPED WITH REMOVABLE COMBS AND AN ADJUSTABLE ELASTIC BAND FOR A SECURE, COMFORTABLE FIT.',
  'HAIRLINE FEATURES LIGHTLY BLEACHED, SINGLE STRAND KNOTS TO CREATE THE MOST NATURAL LOOKING MELT AND REDUCE THE APPEARANCE OF VISIBLE KNOTTING FOR A READY TO WEAR APPLICATION.',
  'DELIVERED IN ITS NATURAL, UNCUSTOMIZED STATE ALLOWING COMPLETE FREEDOM TO CUT, LAYER, STYLE AND PERSONALIZE THE UNIT TO YOUR DESIRED LOOK.',
  'RAW HAIR CAN BE PROFESSIONALLY LIFTED, COLORED, TONED, DYED AND BLEACHED WHILE MAINTAINING ITS QUALITY WHEN PROPERLY CARED FOR.',
  'MEMBERS GAIN EXCLUSIVE ACCESS TO OUR 3D BUILD-A-WIG GENERATOR ALLOWING YOU TO PREVIEW AND CUSTOMIZE YOUR UNIT WITH COLOR SERVICES, STYLING OPTIONS, LACE CUSTOMIZATION, DENSITY ENHANCEMENTS AND ADDITIONAL UPGRADES BEFORE PURCHASING.',
  'DUE TO THE AUTHENTIC NATURE OF RAW HUMAN HAIR, SLIGHT VARIATIONS IN TEXTURE, COLOR TONE, DENSITY AND PATTERN MAY OCCUR MAKING EACH UNIT UNIQUELY YOURS.',
  'FOR THE PROTECTION OF BOTH OUR CLIENTS AND BRAND, IDENTITY VERIFICATION AND COMPLETION OF THE ORDER AUTHORIZATION FORM ARE REQUIRED BEFORE ALL WIG ORDERS CAN BE PROCESSED, CUSTOMIZED OR SHIPPED.',
] as const;

const SHARED_SIGNATURE_FEATURES_TAIL = [
  'MELTED LACE, NATURAL HAIRLINE',
  'LIGHTLY BLEACHED SINGLE STRAND KNOTS',
  'BEGINNER & STYLIST FRIENDLY',
  'CAN BE COLORED, BLEACHED & CUSTOMIZED',
  'BUILT TO LAST WITH PROPER CARE',
  'COMPATIBLE WITH BUILD-A-WIG CUSTOMIZATION',
] as const;

const UNIT_PDP_DETAILS_SPECS: Record<WigUnitKey, UnitPdpDetailsSpec> = {
  noir: {
    origin: 'CAMBODIAN',
    pattern: 'STRAIGHT',
    density: '250%',
    colorPhrase: 'AN OFF BLACK NATURAL HAIR COLOR',
  },
  blanco: {
    origin: 'RUSSIAN',
    pattern: 'STRAIGHT',
    density: '250%',
    colorPhrase: 'PLATINUM BLONDE HAIR COLOR',
  },
  'soft-wave': {
    origin: 'INDIAN',
    pattern: 'WAVY',
    density: '200%',
    colorPhrase: 'AN OFF BLACK HAIR COLOR',
  },
  'beach-wave': {
    origin: 'INDONESIAN',
    pattern: 'WAVY',
    density: '200%',
    colorPhrase: 'AN OFF BLACK HAIR COLOR',
  },
  'soft-curl': {
    origin: 'FILIPINO',
    pattern: 'CURLY',
    density: '200%',
    colorPhrase: 'AN OFF BLACK HAIR COLOR',
  },
  'ocean-curl': {
    origin: 'VIETNAMESE',
    pattern: 'CURLY',
    density: '200%',
    colorPhrase: 'AN OFF BLACK HAIR COLOR',
  },
};

function buildDetailsBullets(spec: UnitPdpDetailsSpec): readonly string[] {
  return [
    `CRAFTED USING 100% RAW ${spec.origin} ${spec.pattern} HUMAN HAIR SOURCED FROM SINGLE DONOR BUNDLES FOR SUPERIOR LONGEVITY, CONSISTENCY AND VERSATILITY.`,
    'FEATURES A 13X6 ULTRA THIN HD FILM LACE INTENDED TO MELT SEAMLESSLY INTO THE SKIN FOR AN UNDETECTABLE, SCALP LIKE APPEARANCE.',
    `HANDMADE UNIT MEASURING 24 INCHES IN LENGTH WITH ${spec.colorPhrase} AND ${spec.density} DENSITY FOR MAXIMUM FULLNESS, VOLUME AND STYLING FLEXIBILITY.`,
    ...SHARED_DETAILS_BULLETS_TAIL,
  ];
}

function buildSignatureFeatures(spec: UnitPdpDetailsSpec): readonly string[] {
  return [
    'MELTED LACE, NATURAL HAIRLINE',
    `${spec.density} DENSITY FOR FULLNESS AND VOLUME`,
    `SINGLE DONOR RAW ${spec.origin} HUMAN HAIR`,
    ...SHARED_SIGNATURE_FEATURES_TAIL.slice(1),
  ];
}

export function getUnitPdpDetailsConfig(unitKey: WigUnitKey) {
  const spec = UNIT_PDP_DETAILS_SPECS[unitKey];
  return {
    intro: UNIT_DETAILS_INTRO,
    bullets: buildDetailsBullets(spec),
    signatureFeatures: buildSignatureFeatures(spec),
  };
}
