import type { Season1ResidentCanonRecord } from '../types';

export const SW_RESIDENT_001: Season1ResidentCanonRecord = {
  id: 'SW-RESIDENT-001',
  canonicalName: 'Etta Vale',
  aliases: [],
  role: 'Founding Presence / Creative Director / Studio World face / primary creative authority',
  age: 35,
  birthRecord: {
    date: '1991-09-05',
    timeLocal: '11:30 AM',
    place: 'Washington, D.C.',
    authority: 'PROVISIONAL_CANON',
  },
  astrology: {
    sun: 'Virgo',
    moon: 'Leo',
    rising: 'Scorpio',
    authority: 'PROVISIONAL_CANON',
  },
  physicalCanon: {
    height: "5'9\"",
    weightApprox: '~142 lb',
    build: 'long / lean / soft-athletic',
    ethnicityPresentation: 'Black woman',
    authority: 'FOUNDER_APPROVED',
  },
  sexuality: { label: 'Heterosexual', authority: 'FOUNDER_APPROVED', notes: 'Unless later superseded by founder canon.' },
  relationshipStatus: {
    summary: 'Single / highly selective. Private romantic life.',
    authority: 'FOUNDER_APPROVED',
  },
  naturalWardrobeAuthority: 'Sophisticated Fashionista',
  naturalWardrobeNotes: [
    'ivory / cream sculptural tailoring',
    'corseted or sharply feminine structure',
    'wide-leg trouser',
    'long coat',
    'heels',
    'feminine power without corporate blandness',
  ],
  visualEssence: ['poised', 'expensive', 'striking', 'controlled', 'quietly magnetic'],
  personality: [
    'Exacting',
    'poised',
    'emotionally intelligent',
    'quietly funny',
    'discerning',
    'high standards',
    'creative authority',
  ],
  humor: 'Dry, precise, economical',
  icks: [
    'forced innovation',
    '“fix it in post”',
    'bad taste marketed as boldness',
    'unearned confidence',
    'loud weak ideas',
  ],
  contrasts: [
    'restrained exterior / proud creative heart',
    'intimidating presence / emotionally intelligent',
    'exacting / not cruel',
    'highly visual / deeply strategic',
    'polished / capable of very dry humor',
  ],
  cameraBehavior: 'Mostly ignores the camera. When something becomes ridiculous, gives the smallest possible look. Does not overperform.',
  signedPortraitBehavior: 'Elegant restrained signature: “Etta Vale”. Possible dry aside: “Satisfied?”',
  clientValue: 'Creative authority, taste, final visual judgment, direction, quality threshold',
  coreSentence: 'She decides what is good enough to exist.',
  socialLanguage: 'Curated, intentional, minimal, high visual authority, not oversharing',
  protectedOpenFields: ['current partner', 'marriage history', 'full family background'],
  antiFlattening: ['not generic luxury Black woman / CEO stock image'],
  canonVersion: 'season1-v1',
  status: 'FOUNDER_APPROVED',
};
