import type { Season1ResidentCanonRecord } from '../types';

export const SW_RESIDENT_004: Season1ResidentCanonRecord = {
  id: 'SW-RESIDENT-004',
  canonicalName: 'Noa Kline',
  aliases: [],
  role: 'Systems Architect / Studio OS Liaison',
  age: 36,
  birthRecord: {
    date: '1990-01-10',
    timeLocal: '10:00 PM',
    place: 'Honolulu, Hawaii',
    authority: 'PROVISIONAL_CANON',
  },
  astrology: { sun: 'Capricorn', moon: 'Cancer', rising: 'Virgo', authority: 'PROVISIONAL_CANON' },
  physicalCanon: {
    height: "6'0\"",
    weightApprox: '~174 lb',
    build: 'lean, narrow, precise',
    ethnicityPresentation: 'East Asian man',
    authority: 'FOUNDER_APPROVED',
  },
  heritage: 'Japanese with strong Okinawan / Ryukyuan family roots.',
  culturalCanon: [
    'Culture is inheritance — not costume aesthetic',
    'Appears through family, festivals, ceremonies, food, music, language, objects, recipes, community',
    'More animated, nostalgic, opinionated, tactile, openly warm in cultural context',
    'Never exists merely to explain Okinawan culture to the audience',
    'Wants daughters to know where they come from',
  ],
  sexuality: { label: 'Heterosexual', authority: 'FOUNDER_APPROVED' },
  relationshipStatus: {
    summary: 'Married to a woman. Two daughters. Wife identity, names, ages, exact configuration remain OPEN.',
    authority: 'FOUNDER_APPROVED',
  },
  naturalWardrobeAuthority: 'Understated Domestic Systems Dad',
  naturalWardrobeNotes: [
    'muted brown / charcoal jacket',
    'dark knit',
    'pleated gray-brown trousers',
    'simple dark shoes',
    'minimal, refined, repetitive, intentionally “boring”',
  ],
  visualEssence: ['cool', 'minimal', 'cerebral', 'surgical', 'low-drama'],
  personality: ['Cool', 'minimal', 'cerebral', 'surgical', 'low-drama', 'dry', 'loyal'],
  humor: 'Deadpan, literal',
  icks: ['messy logic', 'vague asks', '“make it pop”', 'feature creep'],
  contrasts: [
    'robotic at work / deeply soft at home',
    'emotionally restrained / family-centered',
    'minimalist wardrobe / rich cultural life',
    'boring-looking / extremely intelligent',
    'systems-minded / sentimental around family continuity',
  ],
  cameraBehavior: 'Dislikes it. Endures it.',
  signedPortraitBehavior: 'Plain, clean, minimal: “Noa Kline”. Possible: “Done.” / “Is this necessary?”',
  clientValue: 'Turns vague needs into working logic, systems, structure',
  coreSentence: 'He makes the machinery actually work.',
  protectedOpenFields: [
    'wife name',
    'wife ethnicity/heritage',
    'daughters’ names',
    'daughters’ ages',
    'exact family configuration',
    'specific Okinawan locality/family history',
  ],
  antiFlattening: [
    'not generic East Asian tech guy',
    'not culturally costumed for heritage signaling',
    'not cold robot with no family interior',
  ],
  canonVersion: 'season1-v1',
  status: 'FOUNDER_APPROVED',
};
