import type { Season1ResidentCanonRecord } from '../types';

export const SW_RESIDENT_007: Season1ResidentCanonRecord = {
  id: 'SW-RESIDENT-007',
  canonicalName: 'Marlowe Saint',
  aliases: [],
  role: 'Casting Director / Performance Design / Persona Mapping',
  age: 54,
  birthRecord: {
    date: '1972-08-15',
    timeLocal: '10:30 AM',
    place: 'New Orleans, Louisiana',
    authority: 'PROVISIONAL_CANON',
  },
  astrology: { sun: 'Leo', moon: 'Scorpio', rising: 'Libra', authority: 'PROVISIONAL_CANON' },
  physicalCanon: {
    height: 'Substantial stature',
    weightApprox: 'Larger-bodied — fuller face, broad chest and shoulders',
    build: 'Larger-bodied, older, lived-in, commanding — NOT slender, NOT young, NOT frail',
    ethnicityPresentation: 'Black man (elder queer cultural authority spirit — no real-person likeness)',
    authority: 'FOUNDER_APPROVED',
  },
  sexuality: { label: 'Gay', authority: 'FOUNDER_APPROVED' },
  relationshipStatus: {
    summary: 'Married to husband — long-established, deeply familiar, funny, tender, seasoned. Husband identity/details OPEN.',
    authority: 'FOUNDER_APPROVED',
  },
  naturalWardrobeAuthority: 'Off-Duty Grand Cultural Icon',
  naturalWardrobeNotes: [
    'Direction 04 primary + Direction 03 cultural knowledge + occasional Direction 01 grandeur',
    'burgundy, black, antique gold, richly patterned scarf, tactile fabrics',
    'mature salt-and-pepper curls — comfortable but unmistakably Marlowe',
    'Can wear a T-shirt and still be Marlowe Saint',
  ],
  visualEssence: ['magnetic', 'actorly', 'mercurial', 'grand', 'seasoned'],
  personality: [
    'Magnetic',
    'actorly',
    'mercurial',
    'psychologically sharp',
    'playful',
    'intuitive',
    'mischievous',
    'grand',
    'witty',
    'socially seasoned',
    'culturally encyclopedic',
  ],
  humor: 'Witty, camp-capable, historically literate — not comic relief because of size',
  icks: ['flat personalities', 'inauthenticity', 'confusing charisma with volume'],
  contrasts: [
    'flamboyant / requires solitude',
    'theatrical / emotionally perceptive',
    'indulgent-looking / disciplined',
    'playful / historically knowledgeable',
    'loves attention / does not need validation',
    'older / formidable rather than diminished',
  ],
  quirks: [
    'reading glasses he delays using',
    'annotates books with sharp comments',
    'ancient worn leather folio',
    'claims preferred chair in rooms',
    'particular about lighting on his face',
    'possible recurring phrase: “Darling, context.”',
  ],
  cameraBehavior: 'Always knows exactly where camera is. Performs for it. Can weaponize silence toward it.',
  signedPortraitBehavior: 'Large, dramatic, composition-integrated: “Marlowe Saint”. Possible: “You’re welcome.”',
  clientValue: 'Understands presence, chemistry, casting, persona, performance',
  coreSentence: 'He knows who someone is before they fully know themselves.',
  protectedOpenFields: [
    'husband name',
    'husband profession',
    'exact relationship duration',
    'marriage date',
    'husband appearance',
    'full family history',
  ],
  antiFlattening: [
    'not young or slim',
    'not frail',
    'not comic relief because of size',
    'not “older flamboyant man = robe only”',
  ],
  canonVersion: 'season1-v1',
  status: 'FOUNDER_APPROVED',
};
