import type { Season1ResidentCanonRecord } from '../types';

export const SW_RESIDENT_008: Season1ResidentCanonRecord = {
  id: 'SW-RESIDENT-008',
  canonicalName: 'Elio Vahn',
  aliases: [],
  preferredShortForm: 'EV',
  role: 'Tenancy / Expansion / Business Development',
  age: 43,
  birthRecord: {
    date: '1983-04-28',
    timeLocal: '1:20 AM',
    place: 'Trieste, Italy',
    authority: 'PROVISIONAL_CANON',
  },
  astrology: { sun: 'Taurus', moon: 'Scorpio', rising: 'Capricorn', authority: 'PROVISIONAL_CANON' },
  physicalCanon: {
    height: "6'1\"",
    weightApprox: '~188 lb',
    build: 'mature, tailored, athletic',
    ethnicityPresentation: 'Italian / Mediterranean man',
    authority: 'FOUNDER_APPROVED',
  },
  sexuality: {
    label: 'UNRESOLVED — do not lock',
    authority: 'OPEN',
    notes: 'Mystery intentional. Not a recurring “is he gay?” joke.',
  },
  relationshipStatus: {
    summary: 'Private / unresolved romantic life. Information is leverage.',
    authority: 'OPEN',
  },
  naturalWardrobeAuthority: 'Private Club Strategist',
  naturalWardrobeNotes: [
    'deep burgundy velvet jacket',
    'black silk / dark shirt',
    'black tailored trousers',
    'polished loafers',
    'understated signet / ring',
    'mature Mediterranean grooming — controlled, luxurious, unreadable',
  ],
  visualEssence: ['polished', 'expensive', 'tailored', 'controlled', 'elegant shark'],
  personality: ['Polished', 'expensive', 'tailored', 'strategic', 'ambitious', 'persuasive', 'controlled'],
  humor: 'Smooth, dry, borderline smug',
  icks: ['wasted leverage', 'unserious people', 'unprofitable chaos'],
  contrasts: [
    'socially effortless / prepares obsessively',
    'emotionally detached-looking / remembers everything',
    'luxurious / hates waste',
    'persuasive / rarely raises voice',
    'knows everyone / few people know him',
  ],
  quirks: [
    'rereads messages before sending',
    'almost never uses emojis',
    'always notices exits, watches, shoes, tailoring, luggage',
    'phone face-down during serious conversations',
    'uses silence deliberately',
    'straightens crooked objects while listening',
    'email sign-off canon: “Regards, EV”',
  ],
  cameraBehavior: 'Manages his image around the camera.',
  signedPortraitBehavior: 'ONLY “Regards, EV” with underline beneath EV — do NOT use “Elio Vahn” as portrait signature.',
  clientValue: 'Turns relationships into growth, deals, access, expansion',
  coreSentence: 'He understands leverage, access, and how to make the world bigger.',
  protectedOpenFields: ['sexuality', 'partner', 'marital status', 'private loyalties', 'family relationships'],
  antiFlattening: [
    'not mafia',
    'not billionaire TikTok cliché',
    'not generic Italian businessman',
    'not Caspian-lite',
    'not black-suit stock photo',
  ],
  canonVersion: 'season1-v1',
  status: 'FOUNDER_APPROVED',
};
