import type { Season1ResidentCanonRecord } from '../types';

export const SW_RESIDENT_003: Season1ResidentCanonRecord = {
  id: 'SW-RESIDENT-003',
  canonicalName: 'Jules Mercer',
  aliases: [],
  role: 'Front Office / Concierge / Tenant Relations',
  age: 32,
  birthRecord: {
    date: '1994-09-28',
    timeLocal: '2:50 AM',
    place: 'Memphis, Tennessee',
    authority: 'PROVISIONAL_CANON',
  },
  astrology: { sun: 'Libra', moon: 'Cancer', rising: 'Leo', authority: 'PROVISIONAL_CANON' },
  physicalCanon: {
    height: "5'10\"",
    weightApprox: '~168 lb',
    build: 'lean, naturally athletic',
    ethnicityPresentation: 'Black man',
    signatures: ['extremely long locs — canonical natural-habitat direction'],
    authority: 'FOUNDER_APPROVED',
  },
  sexuality: { label: 'Heterosexual', authority: 'FOUNDER_APPROVED' },
  relationshipStatus: {
    summary: 'Single. Dates. Emotionally available. NOT a player archetype.',
    authority: 'FOUNDER_APPROVED',
  },
  naturalWardrobeAuthority: 'Relaxed Romantic / Earth-Toned Modern Bohemian',
  naturalWardrobeNotes: [
    'loose ivory linen shirt',
    'burgundy / wine relaxed tailored trousers',
    'brown boots',
    'subtle jewelry',
    'tactile, warm, relaxed — handsome without over-styling',
  ],
  visualEssence: ['warm', 'charismatic', 'expressive', 'socially agile'],
  personality: ['Warm', 'charismatic', 'expressive', 'socially agile', 'emotionally perceptive', 'lightly messy', 'witty'],
  humor: 'Witty, warm — not predatory or bragging',
  icks: ['rudeness', 'ignoring the vibe', 'passive aggression', 'poor hosting'],
  contrasts: [
    'naturally flirtatious-looking / often simply being kind',
    'easygoing / emotionally perceptive',
    'attractive / does not build identity around attractiveness',
    'socially expansive / capable of genuine tenderness',
    'seemingly unserious / excellent at reading people',
  ],
  cameraBehavior: 'Plays to camera. Naturally understands when a camera is watching — enjoys it, not sinister.',
  signedPortraitBehavior: 'Loose, warm, casual: “Jules Mercer :)”. Possible: “Call me ♡”, playful fake number 901-555-0142',
  clientValue: 'Makes people feel received, understood, comfortable, connected',
  coreSentence: 'He makes Studio World feel human.',
  protectedOpenFields: ['future serious partner', 'marriage', 'children'],
  antiFlattening: [
    'not predatory or sex-obsessed',
    'not manipulative or misogynistic',
    'not hypersexual influencer gym-bro',
    'not generic attractive Black male model',
  ],
  canonVersion: 'season1-v1',
  status: 'FOUNDER_APPROVED',
};
