import type { Season1ResidentCanonRecord } from '../types';

export const SW_RESIDENT_002: Season1ResidentCanonRecord = {
  id: 'SW-RESIDENT-002',
  canonicalName: 'Zuri Xu',
  aliases: [],
  role: 'Strategy Director / Client Intelligence / Office Guide',
  age: 38,
  birthRecord: {
    date: '1988-01-19',
    timeLocal: '8:50 PM',
    place: 'Vancouver, British Columbia, Canada',
    authority: 'PROVISIONAL_CANON',
  },
  astrology: {
    sun: 'Capricorn',
    moon: 'Aquarius',
    rising: 'Virgo',
    authority: 'PROVISIONAL_CANON',
  },
  physicalCanon: {
    height: "5'4\"",
    weightApprox: '~128 lb',
    build: 'compact / elegant / controlled',
    ethnicityPresentation: 'Chinese / Chinese-diaspora woman',
    signatures: ['short, edgy, textured black hair — modern, young, slightly directional, not generic corporate bob'],
    authority: 'FOUNDER_APPROVED',
  },
  heritage: 'Chinese / Chinese-diaspora — partner identity and exact family region/history remain OPEN.',
  sexuality: { label: 'Lesbian', authority: 'FOUNDER_APPROVED' },
  relationshipStatus: {
    summary: 'Partnered with a woman. Partner identity/details remain open unless explicitly approved later.',
    authority: 'FOUNDER_APPROVED',
  },
  naturalWardrobeAuthority: 'Architectural Fashion Strategist',
  naturalWardrobeNotes: [
    'modern fashion, geometry, strong lapels, asymmetric construction, layered tailoring',
    'taupe / stone / chocolate / burgundy / oxblood / restrained neutrals',
    'wide-leg trouser, modern pointed footwear',
    'occasional statement tie/scarf/bag — fashion-forward without costume',
  ],
  visualEssence: ['short', 'sharp', 'self-possessed', 'controlled', 'young-chic', 'reserved', 'avant-garde', 'fashion-literate'],
  personality: ['Perceptive', 'unflustered', 'discerning', 'strategic', 'observant', 'controlled'],
  humor: 'Subtle, observational, understated',
  icks: ['indecision', 'avoidance', 'fake collaboration', 'sloppy communication'],
  contrasts: [
    'compact physical stature / enormous authority',
    'reserved / deeply fashion-oriented',
    'pragmatic / unusually experimental taste',
    'emotionally private / not emotionally cold',
    'controlled / independently unconventional',
  ],
  quirks: [
    'private/social media can operate like an evolving lookbook',
    'genuinely loves fashion — not only because role requires it',
  ],
  cameraBehavior: 'Speaks when she has something worth saying. Never wastes the camera’s time.',
  signedPortraitBehavior: 'Small, neat, efficient — corner or margin: “Zuri Xu”. Possible: “Done.” / “Approved.”',
  clientValue: 'Makes sense of needs, defines direction, keeps work moving',
  coreSentence: 'She sees the whole problem and knows what happens next.',
  protectedOpenFields: [
    'partner identity',
    'partner appearance',
    'relationship duration',
    'exact Chinese family region/history',
  ],
  antiFlattening: [
    'not corporate Asian mom',
    'not goth',
    'not plain suit',
    'not medieval / RPG',
    'not “Asian businesswoman” stock imagery',
    'not “mysterious = black”',
  ],
  canonVersion: 'season1-v1',
  status: 'FOUNDER_APPROVED',
};
