import type { Season1ResidentCanonRecord } from '../types';

export const SW_RESIDENT_006: Season1ResidentCanonRecord = {
  id: 'SW-RESIDENT-006',
  canonicalName: 'Iona Wells',
  aliases: [],
  role: 'Fabrication Lead / Character Lab / Image Construction',
  age: 30,
  birthRecord: {
    date: '1996-08-27',
    timeLocal: '12:30 AM',
    place: 'Pittsburgh, Pennsylvania',
    authority: 'PROVISIONAL_CANON',
  },
  astrology: { sun: 'Virgo', moon: 'Aquarius', rising: 'Gemini', authority: 'PROVISIONAL_CANON' },
  physicalCanon: {
    height: "5'11\"",
    weightApprox: '~154 lb',
    build: 'tall, lanky, slightly awkward',
    ethnicityPresentation: 'white woman',
    signatures: [
      'heavy freckles',
      'tortoiseshell glasses',
      'reddish-brown hair',
      'well-paid professional grooming — cared-for, intentional, practical',
    ],
    authority: 'FOUNDER_APPROVED',
  },
  sexuality: { label: 'Heterosexual', authority: 'FOUNDER_APPROVED', notes: 'Unless later superseded.' },
  relationshipStatus: { summary: 'Single. Future relationship arc open — do not rush.', authority: 'FOUNDER_APPROVED' },
  naturalWardrobeAuthority: 'Precision Utilitarian',
  naturalWardrobeNotes: [
    'white collared shirt',
    'refined olive / graphite / stone utility jacket',
    'high-waisted technical work trousers',
    'functional pockets, durable luxury materials, refined work boots',
    'hair pinned / clipped / practical — glasses remain important',
  ],
  visualEssence: ['futuristic', 'sculptural', 'technical', 'focused', 'tactile'],
  personality: [
    'Futuristic',
    'sculptural',
    'technical',
    'focused',
    'obsessive',
    'tactile',
    'specific',
    'extremely smart',
    'efficient',
  ],
  humor: 'Nerdy precision — often accidental',
  icks: ['muddy references', 'low-resolution inputs', '“good enough”', 'people touching unfinished work'],
  contrasts: [
    'socially awkward / graceful with tools',
    'practical / exquisite material judgment',
    'quiet / extremely opinionated about fabrication',
    'gangly / precise hands',
    'image-indifferent / excellent at constructing images',
    'underestimated / commanding when something breaks',
  ],
  quirks: [
    'talks to objects while troubleshooting',
    'keeps labeled material scraps',
    'forgets meals while absorbed',
    'pushes glasses up with wrist if hands dirty',
    'measures things unconsciously',
    'apologizes to objects when dropping them',
    'competitive about craftsmanship',
  ],
  glamourArc: {
    principle:
      'Iona was already beautiful. Arc is discovering deliberate control of perception — glamour rare, contextual, surprising, not permanent. NOT makeover-final-state.',
    notMakeoverEndpoint: true,
    contexts: [
      'formal event',
      'date',
      'client presentation',
      'fabrication experiment',
      'social event',
      'Jules dragging her into a photo',
      'wearing something she made',
    ],
    authority: 'FOUNDER_APPROVED',
  },
  cameraBehavior: 'Forgets camera exists. Sometimes says too much.',
  signedPortraitBehavior: 'Careful, modest, small, slightly hesitant — possible correction/arrow/micro-note',
  clientValue: 'Materializes characters, assets, prototypes, physical and visual detail',
  coreSentence: 'She becomes terrifyingly competent once she starts working.',
  protectedOpenFields: ['future partner', 'relationship arc outcome', 'whether glamour becomes more frequent', 'family background'],
  antiFlattening: [
    'not frumpy nerd or ugly duckling',
    'not cottagecore or librarian cosplay',
    'not manic pixie',
    'not glam makeover endpoint',
  ],
  canonVersion: 'season1-v1',
  status: 'FOUNDER_APPROVED',
};
