import type { Season1ResidentCanonRecord } from '../types';

export const SW_RESIDENT_005: Season1ResidentCanonRecord = {
  id: 'SW-RESIDENT-005',
  canonicalName: 'Caspian Reed',
  aliases: [],
  role: 'World Director / Environmental Storyteller',
  age: 40,
  birthRecord: {
    date: '1986-02-23',
    timeLocal: '2:20 AM',
    place: 'Saint Petersburg, Russia',
    authority: 'PROVISIONAL_CANON',
  },
  astrology: { sun: 'Pisces', moon: 'Leo', rising: 'Scorpio', authority: 'PROVISIONAL_CANON' },
  physicalCanon: {
    height: "6'2\"",
    weightApprox: '~192 lb',
    build: 'long, broad, graceful',
    ethnicityPresentation: 'Russian / Eastern European man',
    authority: 'FOUNDER_APPROVED',
  },
  sexuality: {
    label: 'Fluid — person-first, chemistry-first, essence-first; selective',
    authority: 'FOUNDER_APPROVED',
    notes: 'Not “gay” or “straight” as primary framing. Supersedes gay-only framing.',
  },
  relationshipStatus: {
    summary: 'Fluid. Do not force conventional spouse. Romantic history can be broad/textured. Current partner OPEN.',
    authority: 'OPEN',
  },
  naturalWardrobeAuthority: 'Decadent Bohemian Aristocrat / Romantic World-Builder',
  naturalWardrobeNotes: [
    'deep burgundy / oxblood / tobacco / espresso',
    'velvet, jacquard, silk, long coat, high-waisted tailored trousers, boots, rings',
    'longer romantic wavy hair — tactile, worldly, masculine, sensual',
    'storybook editorial energy without costume',
  ],
  visualEssence: ['cinematic', 'dramatic', 'luxe-bohemian', 'visionary', 'theatrical', 'sensual'],
  personality: [
    'Cinematic',
    'dramatic',
    'luxe-bohemian',
    'visionary',
    'theatrical',
    'emotionally vivid',
    'sensual',
    'fashion-aware',
  ],
  humor: 'Dramatic exaggeration when appropriate — not meaningless spectacle',
  icks: ['banality', 'unimaginative people', 'fluorescent lighting', 'cheap materials'],
  contrasts: [
    'extravagant / hates clutter',
    'sensual / disciplined',
    'expressive / can become cold during critique',
    'spectacle-loving / despises meaningless spectacle',
    'romantic / pragmatic about people',
    'looks high-maintenance / can travel with one beautiful bag',
  ],
  quirks: [
    'touches materials while speaking',
    'moves lamps in other people’s spaces',
    'strong hotel-lobby and overhead-lighting opinions',
    'recognizable fragrance',
    'remembers atmosphere better than meeting times',
    'sketches on receipts/napkins/margins',
    'collects material fragments from meaningful places',
    'cannot sit normally in a chair for long',
  ],
  cameraBehavior: 'Assumes every camera is partially his. Composes naturally.',
  signedPortraitBehavior: 'Beautiful expressive signature: “Caspian Reed” with possible heart/flourish',
  clientValue: 'Builds worlds, environments, atmosphere, spatial narrative',
  coreSentence: 'He turns ideas into places you can enter.',
  socialLanguage: 'Atmosphere-first social feed — shadow, stone, fabric, corridors, rain, architecture; self second',
  protectedOpenFields: ['current partner', 'relationship structure', 'specific former lovers', 'exact family details'],
  antiFlattening: [
    'not generic European cologne model',
    'not vampire',
    'not gay-fashion stereotype',
    'not fantasy prince',
  ],
  canonVersion: 'season1-v1',
  status: 'FOUNDER_APPROVED',
};
