/** Genesis Canonical Object Model™ — infrastructure constants */

export const OBJECT_MODEL_SUBSYSTEM_VERSION = '1.0.0';
export const OBJECT_MODEL_SUBSYSTEM_NAME = 'Canonical Object Model™';

/** Core relationship verbs — extensible via string type on edges */
export const CORE_OBJECT_RELATIONSHIP_TYPES = [
  'owns',
  'contains',
  'extends',
  'depends_on',
  'creates',
  'references',
  'teaches',
  'guides',
  'publishes',
  'validates',
  'inherits',
  'belongs_to',
  'operates',
  'compiles_into',
  'implements',
  'requires',
  'triggers',
  'emits',
  'observes',
  'archives',
  'certifies',
  'contradicts',
  'composes',
  'routes_to',
  'governs',
  'supersedes',
  'supports',
  'blocks',
  'renders',
  'published_by',
  'published_as',
  'provided_by',
  'used_by',
  'uses',
  'governed_by',
  'validated_by',
  'owned_by',
  'operated_by',
  'emitted_by',
  'created_by',
  'issued_by',
  'implemented_by',
  'learns_from',
  'approves',
  'hosts',
  'affects',
  'connects',
] as const;

export type CoreObjectRelationshipType = (typeof CORE_OBJECT_RELATIONSHIP_TYPES)[number];

/** 56 canonical object types from Genesis Sprint 3 ontology */
export const CANONICAL_OBJECT_TYPES = [
  'system',
  'institution',
  'collection',
  'book',
  'volume',
  'chapter',
  'article',
  'codex-article',
  'knowledge-artifact',
  'specification',
  'blueprint',
  'research-paper',
  'decision',
  'architecture-decision-record',
  'policy',
  'rule',
  'registry',
  'company',
  'headquarters',
  'department',
  'studio',
  'workspace',
  'room',
  'council',
  'citizen',
  'founder',
  'ai-worker',
  'mentor',
  'profession',
  'profession-brain',
  'mission',
  'workflow',
  'capability',
  'service',
  'journey',
  'relationship-edge',
  'event',
  'notification',
  'briefing',
  'memory',
  'simulation',
  'scenario',
  'state',
  'signal',
  'career-world',
  'marketplace-listing',
  'certification',
  'achievement',
  'asset',
  'hero-object',
  'asset-pack',
  'expansion-pack',
  'contract',
  'identity',
  'interface',
  'implementation',
] as const;

export type CanonicalObjectTypeId = (typeof CANONICAL_OBJECT_TYPES)[number];

export const CANONICAL_OBJECT_FAMILIES = {
  kernel: [
    'collection',
    'book',
    'volume',
    'chapter',
    'article',
    'codex-article',
    'knowledge-artifact',
    'specification',
    'blueprint',
    'research-paper',
    'decision',
    'architecture-decision-record',
    'policy',
    'rule',
    'registry',
  ],
  civilization: [
    'system',
    'institution',
    'company',
    'headquarters',
    'department',
    'studio',
    'workspace',
    'room',
    'council',
  ],
  people: ['citizen', 'founder', 'ai-worker', 'mentor', 'profession', 'profession-brain'],
  work: ['mission', 'workflow', 'capability', 'service', 'journey', 'relationship-edge'],
  experience: [
    'event',
    'notification',
    'briefing',
    'memory',
    'simulation',
    'scenario',
    'state',
    'signal',
  ],
  economy: [
    'career-world',
    'marketplace-listing',
    'certification',
    'achievement',
    'asset',
    'hero-object',
    'asset-pack',
    'expansion-pack',
  ],
  contracts: ['contract', 'identity', 'interface', 'implementation'],
} as const;

/** Approved inheritance families — child types may inherit from parent type */
export const INHERITANCE_FAMILIES: Partial<
  Record<CanonicalObjectTypeId, CanonicalObjectTypeId[]>
> = {
  institution: ['codex-article'],
  company: ['workspace'],
  workspace: ['room'],
  room: ['studio'],
  asset: ['hero-object'],
  article: ['codex-article'],
  decision: ['architecture-decision-record'],
  citizen: ['founder', 'mentor', 'ai-worker'],
  'knowledge-artifact': ['research-paper', 'specification', 'blueprint', 'memory'],
};

/** Structural composition patterns — parent type may contain child types */
export const COMPOSITION_PATTERNS: Partial<
  Record<CanonicalObjectTypeId, CanonicalObjectTypeId[]>
> = {
  headquarters: ['room'],
  department: ['studio', 'capability'],
  'career-world': ['profession', 'simulation', 'certification', 'achievement', 'mission'],
  council: ['citizen', 'ai-worker', 'mentor', 'decision'],
  simulation: ['scenario'],
  workflow: ['capability'],
  'asset-pack': ['asset'],
  collection: ['book'],
  book: ['volume'],
  volume: ['chapter'],
  chapter: ['article'],
};

export const CANONICAL_LIFECYCLE_STATES = [
  'proposed',
  'draft',
  'review',
  'approved',
  'active',
  'canonical',
  'superseded',
  'deprecated',
  'archived',
] as const;

export type CanonicalLifecycleState = (typeof CANONICAL_LIFECYCLE_STATES)[number];
