import type { ProductionCompletionCategory, ProductionQualityGateStage } from './types';

export const PRODUCTION_COMPLETION_VERSION = '1.0.0';

export const PRODUCTION_QUALITY_GATE_STAGES: ProductionQualityGateStage[] = [
  'architecture',
  'implementation',
  'integration',
  'quality-assurance',
  'founder-review',
  'knowledge-update',
  'production-ready',
  'complete',
];

export const PRODUCTION_QUALITY_GATE_LABELS: Record<ProductionQualityGateStage, string> = {
  architecture: 'Architecture',
  implementation: 'Implementation',
  integration: 'Integration',
  'quality-assurance': 'Quality Assurance',
  'founder-review': 'Founder Review',
  'knowledge-update': 'Knowledge Update',
  'production-ready': 'Production Ready',
  complete: 'Complete',
};

export const PRODUCTION_COMPLETION_CATEGORY_LABELS: Record<ProductionCompletionCategory, string> = {
  architecture: 'Architecture',
  engineering: 'Engineering',
  experience: 'Experience',
  'visual-system': 'Visual System',
  performance: 'Performance',
  'world-integration': 'World Integration',
  qa: 'QA',
};

export type ChecklistItemTemplate = {
  id: string;
  category: ProductionCompletionCategory;
  label: string;
  gateStage: ProductionQualityGateStage;
  /** When true, item is required if applicable. */
  required: boolean;
  /** Return false to omit from generated checklist. */
  applies: (scope: import('./types').ProductionFeatureScope) => boolean;
};

export const PRODUCTION_CHECKLIST_TEMPLATES: ChecklistItemTemplate[] = [
  // Architecture
  {
    id: 'constitution-articles',
    category: 'architecture',
    label: 'Constitution Articles updated (if applicable)',
    gateStage: 'architecture',
    required: true,
    applies: (s) => s.requiresConstitutional,
  },
  {
    id: 'adr-generated',
    category: 'architecture',
    label: 'ADR generated or updated',
    gateStage: 'architecture',
    required: true,
    applies: (s) => s.requiresConstitutional || !s.visualOnly,
  },
  {
    id: 'world-bible-updated',
    category: 'architecture',
    label: 'World Bible updated',
    gateStage: 'architecture',
    required: true,
    applies: (s) => !s.routingOnly,
  },
  {
    id: 'knowledge-core-updated',
    category: 'architecture',
    label: 'Knowledge Core updated',
    gateStage: 'knowledge-update',
    required: true,
    applies: () => true,
  },
  {
    id: 'experience-engine-verified',
    category: 'architecture',
    label: 'Experience Engine compatibility verified',
    gateStage: 'integration',
    required: true,
    applies: (s) => !s.routingOnly,
  },
  {
    id: 'world-graph-relationships',
    category: 'architecture',
    label: 'World Graph relationships defined',
    gateStage: 'architecture',
    required: true,
    applies: (s) => s.requiresWorldGraph,
  },
  // Engineering
  {
    id: 'routes-created',
    category: 'engineering',
    label: 'Routes created',
    gateStage: 'implementation',
    required: true,
    applies: (s) => s.requiresRoutes,
  },
  {
    id: 'components-implemented',
    category: 'engineering',
    label: 'Components implemented',
    gateStage: 'implementation',
    required: true,
    applies: (s) => !s.routingOnly,
  },
  {
    id: 'types-updated',
    category: 'engineering',
    label: 'Types updated',
    gateStage: 'implementation',
    required: true,
    applies: (s) => !s.visualOnly,
  },
  {
    id: 'state-management',
    category: 'engineering',
    label: 'State management integrated',
    gateStage: 'implementation',
    required: true,
    applies: (s) => !s.visualOnly && !s.routingOnly,
  },
  {
    id: 'database-changes',
    category: 'engineering',
    label: 'Database changes completed',
    gateStage: 'implementation',
    required: true,
    applies: (s) => s.requiresDatabase,
  },
  {
    id: 'api-connections',
    category: 'engineering',
    label: 'API connections verified',
    gateStage: 'implementation',
    required: true,
    applies: (s) => s.requiresApi,
  },
  {
    id: 'error-handling',
    category: 'engineering',
    label: 'Error handling implemented',
    gateStage: 'implementation',
    required: true,
    applies: (s) => !s.visualOnly,
  },
  {
    id: 'loading-states',
    category: 'engineering',
    label: 'Loading states implemented',
    gateStage: 'implementation',
    required: true,
    applies: (s) => !s.routingOnly,
  },
  {
    id: 'empty-states',
    category: 'engineering',
    label: 'Empty states implemented',
    gateStage: 'implementation',
    required: true,
    applies: (s) => !s.routingOnly && !s.visualOnly,
  },
  // Experience
  {
    id: 'progressive-presence',
    category: 'experience',
    label: 'Progressive Presence™ compliant',
    gateStage: 'integration',
    required: true,
    applies: (s) => !s.routingOnly,
  },
  {
    id: 'orb-compatible',
    category: 'experience',
    label: 'Orb compatible',
    gateStage: 'integration',
    required: true,
    applies: (s) => s.requiresOrb,
  },
  {
    id: 'atlas-compatible',
    category: 'experience',
    label: 'Atlas compatible',
    gateStage: 'integration',
    required: true,
    applies: (s) => s.requiresAtlas,
  },
  {
    id: 'navigation-consistent',
    category: 'experience',
    label: 'Navigation consistent',
    gateStage: 'integration',
    required: true,
    applies: (s) => s.requiresRoutes,
  },
  {
    id: 'motion-language',
    category: 'experience',
    label: 'Motion language consistent',
    gateStage: 'integration',
    required: true,
    applies: (s) => s.requiresMotion,
  },
  {
    id: 'glass-material',
    category: 'experience',
    label: 'Glass material language respected',
    gateStage: 'integration',
    required: true,
    applies: (s) => !s.routingOnly,
  },
  {
    id: 'accessibility',
    category: 'experience',
    label: 'Accessibility reviewed',
    gateStage: 'quality-assurance',
    required: true,
    applies: () => true,
  },
  {
    id: 'mobile-responsive',
    category: 'experience',
    label: 'Mobile responsive',
    gateStage: 'quality-assurance',
    required: true,
    applies: () => true,
  },
  // Visual System
  {
    id: 'industrial-design',
    category: 'visual-system',
    label: 'Industrial design language followed',
    gateStage: 'integration',
    required: true,
    applies: (s) => !s.routingOnly,
  },
  {
    id: 'glassmorphism',
    category: 'visual-system',
    label: 'Glassmorphism standards met',
    gateStage: 'integration',
    required: true,
    applies: (s) => !s.routingOnly,
  },
  {
    id: 'acrylic-materials',
    category: 'visual-system',
    label: 'Acrylic materials correct',
    gateStage: 'integration',
    required: true,
    applies: (s) => s.requiresAssets || !s.routingOnly,
  },
  {
    id: 'lighting-consistent',
    category: 'visual-system',
    label: 'Lighting consistent',
    gateStage: 'integration',
    required: true,
    applies: (s) => s.requiresAssets,
  },
  {
    id: '3d-assets',
    category: 'visual-system',
    label: '3D assets integrated',
    gateStage: 'integration',
    required: true,
    applies: (s) => s.requiresAssets,
  },
  {
    id: 'icon-library',
    category: 'visual-system',
    label: 'Icons follow Studio World asset library',
    gateStage: 'integration',
    required: true,
    applies: (s) => s.requiresAssets || s.visualOnly,
  },
  {
    id: 'no-placeholders',
    category: 'visual-system',
    label: 'No placeholder assets remain',
    gateStage: 'quality-assurance',
    required: true,
    applies: (s) => s.requiresAssets,
  },
  // Performance
  {
    id: 'no-console-errors',
    category: 'performance',
    label: 'No console errors',
    gateStage: 'quality-assurance',
    required: true,
    applies: () => true,
  },
  {
    id: 'no-broken-routes',
    category: 'performance',
    label: 'No broken routes',
    gateStage: 'quality-assurance',
    required: true,
    applies: (s) => s.requiresRoutes,
  },
  {
    id: 'no-duplicate-renders',
    category: 'performance',
    label: 'No duplicate renders',
    gateStage: 'quality-assurance',
    required: true,
    applies: (s) => !s.routingOnly,
  },
  {
    id: 'lazy-loading',
    category: 'performance',
    label: 'Lazy loading implemented where appropriate',
    gateStage: 'implementation',
    required: false,
    applies: (s) => s.requiresRoutes,
  },
  {
    id: 'performance-budget',
    category: 'performance',
    label: 'Performance budget respected',
    gateStage: 'quality-assurance',
    required: true,
    applies: () => true,
  },
  {
    id: 'memory-leaks',
    category: 'performance',
    label: 'Memory leaks checked',
    gateStage: 'quality-assurance',
    required: true,
    applies: (s) => !s.routingOnly,
  },
  // World Integration
  {
    id: 'atlas-node',
    category: 'world-integration',
    label: 'Atlas node created',
    gateStage: 'integration',
    required: true,
    applies: (s) => s.requiresAtlas,
  },
  {
    id: 'company-context',
    category: 'world-integration',
    label: 'Company context integrated',
    gateStage: 'integration',
    required: true,
    applies: (s) => s.requiresRoutes,
  },
  {
    id: 'department-registered',
    category: 'world-integration',
    label: 'Department registered',
    gateStage: 'integration',
    required: false,
    applies: () => false, // enabled via scope override in builder when department mentioned
  },
  {
    id: 'scene-registered',
    category: 'world-integration',
    label: 'Scene registered',
    gateStage: 'integration',
    required: false,
    applies: (s) => !s.routingOnly,
  },
  {
    id: 'knowledge-relationships',
    category: 'world-integration',
    label: 'Knowledge relationships connected',
    gateStage: 'knowledge-update',
    required: true,
    applies: () => true,
  },
  {
    id: 'search-index',
    category: 'world-integration',
    label: 'Search index updated',
    gateStage: 'knowledge-update',
    required: false,
    applies: (s) => !s.visualOnly,
  },
  // QA
  {
    id: 'manual-interaction',
    category: 'qa',
    label: 'Manual interaction review',
    gateStage: 'quality-assurance',
    required: true,
    applies: () => true,
  },
  {
    id: 'visual-regression',
    category: 'qa',
    label: 'Visual regression review',
    gateStage: 'quality-assurance',
    required: true,
    applies: (s) => s.requiresAssets || s.visualOnly || !s.routingOnly,
  },
  {
    id: 'navigation-review',
    category: 'qa',
    label: 'Navigation review',
    gateStage: 'quality-assurance',
    required: true,
    applies: (s) => s.requiresRoutes,
  },
  {
    id: 'animation-review',
    category: 'qa',
    label: 'Animation review',
    gateStage: 'quality-assurance',
    required: true,
    applies: (s) => s.requiresMotion,
  },
  {
    id: 'cross-browser',
    category: 'qa',
    label: 'Cross-browser review',
    gateStage: 'quality-assurance',
    required: false,
    applies: () => true,
  },
  {
    id: 'mobile-review',
    category: 'qa',
    label: 'Mobile review',
    gateStage: 'quality-assurance',
    required: true,
    applies: () => true,
  },
];
