import type { GenerationRecipe, GenerationRecipeId } from './types';

const UNIVERSAL_NEGATIVE =
  'no watermark, no signature, no random text, no broken typography, no low resolution, no muddy lighting, no clutter, no generic stock aesthetic';

export const GENERATION_RECIPES: Record<GenerationRecipeId, GenerationRecipe> = {
  'hero-icon': {
    id: 'hero-icon',
    label: 'Hero Icon™',
    falModel: 'openai/gpt-image-2/edit',
    defaultPromptPrefix:
      'Studio World luxury hero icon, iconic single object silhouette, crystalline glass, polished marble, soft museum spotlight, premium spatial design language.',
    negativePrompt: `${UNIVERSAL_NEGATIVE}, no background, no frame, no UI card, no text label`,
    resolution: '1536x1536',
    aspectRatio: '1:1',
    backgroundBehavior: 'transparent',
    lightingProfile: 'museum-spotlight-soft-rim',
    materialProfile: 'crystal-glass-marble-champagne-metal',
    outputFormat: 'png',
    registryDestination: 'icons',
    versioningStrategy: 'semantic-version',
    upscalingPipeline: 'transparent-png-polish',
    metadata: {
      tags: ['hero-icon', 'transparent', 'studio-world'],
      relatedSystems: ['Orb™', 'Atlas™', 'Mission Control™', 'Asset Registry™'],
      departmentsUsingIt: ['Orb', 'Atlas', 'Mission Control'],
      transparentBackground: true,
      registryLibrary: 'Hero Icon Library™',
    },
  },
  environment: {
    id: 'environment',
    label: 'Environment™',
    falModel: 'fal-ai/nano-banana-pro/edit',
    defaultPromptPrefix:
      'Studio World immersive environment shell, world-first architecture, luxury headquarters atmosphere, modular room background, no dashboard UI.',
    negativePrompt: `${UNIVERSAL_NEGATIVE}, no people, no logos, no brand colors, no interface chrome`,
    resolution: '4K',
    aspectRatio: '16:9',
    backgroundBehavior: 'studio-world-environment',
    lightingProfile: 'ambient-headquarters-depth',
    materialProfile: 'marble-glass-warm-metal-environment',
    outputFormat: 'webp',
    registryDestination: 'images',
    versioningStrategy: 'immutable-generation',
    upscalingPipeline: 'webp-q92-room-polish',
    metadata: {
      tags: ['environment', 'room-shell', 'studio-world'],
      relatedSystems: ['Scene Assembly™', 'Experience Engine™', 'Asset Registry™'],
      departmentsUsingIt: ['Scene Assembly', 'Experience System'],
      transparentBackground: false,
      registryLibrary: 'Environment Library™',
    },
  },
  furniture: {
    id: 'furniture',
    label: 'Furniture™',
    falModel: 'fal-ai/nano-banana-pro/edit',
    defaultPromptPrefix:
      'Single modular luxury furniture asset for Studio World, isolated object, runtime-ready proportions, glass and stone material language.',
    negativePrompt: `${UNIVERSAL_NEGATIVE}, no room background, no people, no text, no logos`,
    resolution: '2K',
    aspectRatio: '1:1',
    backgroundBehavior: 'transparent',
    lightingProfile: 'object-studio-soft-shadow',
    materialProfile: 'glass-marble-brushed-metal',
    outputFormat: 'png',
    registryDestination: '3d-models',
    versioningStrategy: 'surgical-regeneration',
    upscalingPipeline: 'object-cutout-and-lod',
    metadata: {
      tags: ['furniture', 'modular-object', 'scene-assembly'],
      relatedSystems: ['Scene Assembly™', 'Asset Registry™', 'Marketplace™'],
      departmentsUsingIt: ['Scene Assembly', 'Marketplace'],
      transparentBackground: true,
      registryLibrary: 'Furniture Library™',
    },
  },
  orb: {
    id: 'orb',
    label: 'Orb™',
    falModel: 'openai/gpt-image-2/edit',
    defaultPromptPrefix:
      'Studio Orb artifact, luminous intelligent crystal sphere, sacred architectural object, premium glass refraction, calm executive presence.',
    negativePrompt: `${UNIVERSAL_NEGATIVE}, no face, no mascot, no cartoon, no text`,
    resolution: '1536x1536',
    aspectRatio: '1:1',
    backgroundBehavior: 'transparent',
    lightingProfile: 'orb-inner-glow-rim-light',
    materialProfile: 'crystal-energy-glass',
    outputFormat: 'png',
    registryDestination: 'icons',
    versioningStrategy: 'semantic-version',
    upscalingPipeline: 'transparent-png-glow-preservation',
    metadata: {
      tags: ['orb', 'artifact', 'transparent'],
      relatedSystems: ['Orb™', 'Command Dock™', 'Mission Control™'],
      departmentsUsingIt: ['Orb', 'Mission Control'],
      transparentBackground: true,
      registryLibrary: 'Orb Artifact Library™',
    },
  },
  'glass-ui': {
    id: 'glass-ui',
    label: 'Glass UI™',
    falModel: 'fal-ai/nano-banana-pro/edit',
    defaultPromptPrefix:
      'Transparent glass interface material sample for Studio World, acrylic depth, subtle highlights, no readable UI, reusable texture asset.',
    negativePrompt: `${UNIVERSAL_NEGATIVE}, no buttons, no forms, no dashboard, no typography`,
    resolution: '2K',
    aspectRatio: '4:3',
    backgroundBehavior: 'runtime-composited',
    lightingProfile: 'acrylic-edge-highlight',
    materialProfile: 'transparent-acrylic-glass',
    outputFormat: 'webp',
    registryDestination: 'templates',
    versioningStrategy: 'semantic-version',
    upscalingPipeline: 'material-tile-polish',
    metadata: {
      tags: ['glass-ui', 'material', 'interface-language'],
      relatedSystems: ['Experience Engine™', 'Design Language™'],
      departmentsUsingIt: ['Experience System', 'Design Language'],
      transparentBackground: false,
      registryLibrary: 'Glass UI Library™',
    },
  },
  room: {
    id: 'room',
    label: 'Room™',
    falModel: 'fal-ai/nano-banana-pro/edit',
    defaultPromptPrefix:
      'Complete Studio World room concept, physical place not webpage, immersive luxury architecture, spatial storytelling, founder-ready headquarters room.',
    negativePrompt: `${UNIVERSAL_NEGATIVE}, no dashboard, no cards, no app screen, no browser chrome`,
    resolution: '4K',
    aspectRatio: '16:9',
    backgroundBehavior: 'studio-world-environment',
    lightingProfile: 'cinematic-room-depth',
    materialProfile: 'marble-glass-wood-warm-metal',
    outputFormat: 'webp',
    registryDestination: 'images',
    versioningStrategy: 'immutable-generation',
    upscalingPipeline: 'room-preview-polish',
    metadata: {
      tags: ['room', 'architecture', 'studio-world'],
      relatedSystems: ['Atlas™', 'Scene Assembly™', 'Architecture Auditor™'],
      departmentsUsingIt: ['Atlas', 'Scene Assembly'],
      transparentBackground: false,
      registryLibrary: 'Room Concept Library™',
    },
  },
  architecture: {
    id: 'architecture',
    label: 'Architecture™',
    falModel: 'fal-ai/nano-banana-pro/edit',
    defaultPromptPrefix:
      'Studio World architectural landmark, monumental spatial structure, luxury civilization design, museum-grade environmental identity.',
    negativePrompt: `${UNIVERSAL_NEGATIVE}, no signage, no generic office, no webpage metaphors`,
    resolution: '4K',
    aspectRatio: '16:9',
    backgroundBehavior: 'studio-world-environment',
    lightingProfile: 'monumental-architectural-light',
    materialProfile: 'stone-glass-bronze-crystal',
    outputFormat: 'webp',
    registryDestination: 'images',
    versioningStrategy: 'date-stamped-version',
    upscalingPipeline: 'architectural-preview-polish',
    metadata: {
      tags: ['architecture', 'landmark', 'world-first'],
      relatedSystems: ['Atlas™', 'World Graph™', 'Mission Control™'],
      departmentsUsingIt: ['Atlas', 'Mission Control'],
      transparentBackground: false,
      registryLibrary: 'Architecture Library™',
    },
  },
  material: {
    id: 'material',
    label: 'Material™',
    falModel: 'fal-ai/nano-banana-pro/edit',
    defaultPromptPrefix:
      'Studio World seamless material study, premium surface sample, physically plausible texture, runtime material reference.',
    negativePrompt: `${UNIVERSAL_NEGATIVE}, no object, no room, no text, no pattern seams`,
    resolution: '2K',
    aspectRatio: '1:1',
    backgroundBehavior: 'none',
    lightingProfile: 'material-lab-even-light',
    materialProfile: 'surface-study',
    outputFormat: 'webp',
    registryDestination: 'images',
    versioningStrategy: 'semantic-version',
    upscalingPipeline: 'seamless-material-polish',
    metadata: {
      tags: ['material', 'surface', 'design-language'],
      relatedSystems: ['Design Language™', 'Scene Assembly™'],
      departmentsUsingIt: ['Design Language', 'Scene Assembly'],
      transparentBackground: false,
      registryLibrary: 'Material Library™',
    },
  },
  particle: {
    id: 'particle',
    label: 'Particle™',
    falModel: 'deterministic-runtime',
    defaultPromptPrefix:
      'Deterministic Studio World particle system specification, ambient life, subtle luxury motion, performance-safe runtime behavior.',
    negativePrompt: 'not AI-generated; deterministic runtime JSON only',
    resolution: 'runtime',
    aspectRatio: 'runtime',
    backgroundBehavior: 'runtime-composited',
    lightingProfile: 'ambient-reactive',
    materialProfile: 'light-particle',
    outputFormat: 'json',
    registryDestination: 'animations',
    versioningStrategy: 'semantic-version',
    upscalingPipeline: 'not-applicable',
    metadata: {
      tags: ['particle', 'runtime', 'ambient-life'],
      relatedSystems: ['Experience Engine™', 'Scene Assembly™'],
      departmentsUsingIt: ['Experience System', 'Scene Assembly'],
      transparentBackground: true,
      registryLibrary: 'Particle System Library™',
    },
  },
  animation: {
    id: 'animation',
    label: 'Animation™',
    falModel: 'fal-ai/kling-video/v3/pro/image-to-video',
    defaultPromptPrefix:
      'Subtle Studio World cinematic motion, premium slow camera movement, elegant environmental animation, no cuts, no text.',
    negativePrompt: `${UNIVERSAL_NEGATIVE}, no shaky camera, no fast motion, no text overlays`,
    resolution: '1080p',
    aspectRatio: '16:9',
    backgroundBehavior: 'studio-world-environment',
    lightingProfile: 'cinematic-motion-light',
    materialProfile: 'preserve-source-materials',
    outputFormat: 'mp4',
    registryDestination: 'animations',
    versioningStrategy: 'immutable-generation',
    upscalingPipeline: 'motion-qc-and-webm-derivative',
    metadata: {
      tags: ['animation', 'cinematic', 'world-motion'],
      relatedSystems: ['Experience Engine™', 'Mission Control™'],
      departmentsUsingIt: ['Experience System', 'Mission Control'],
      transparentBackground: false,
      registryLibrary: 'Animation Library™',
    },
  },
  portrait: {
    id: 'portrait',
    label: 'Portrait™',
    falModel: 'openai/gpt-image-2/edit',
    defaultPromptPrefix:
      'Premium editorial portrait asset for Studio World, respectful human presentation, luxury lighting, clean isolated composition.',
    negativePrompt: `${UNIVERSAL_NEGATIVE}, no distorted face, no extra limbs, no text, no logo`,
    resolution: '1536x2048',
    aspectRatio: '3:4',
    backgroundBehavior: 'transparent',
    lightingProfile: 'editorial-softbox',
    materialProfile: 'human-editorial',
    outputFormat: 'png',
    registryDestination: 'images',
    versioningStrategy: 'immutable-generation',
    upscalingPipeline: 'portrait-cutout-and-polish',
    metadata: {
      tags: ['portrait', 'editorial', 'transparent'],
      relatedSystems: ['Brand Standards™', 'Experience Engine™'],
      departmentsUsingIt: ['Brand Standards', 'Experience System'],
      transparentBackground: true,
      registryLibrary: 'Portrait Library™',
    },
  },
  'brand-asset': {
    id: 'brand-asset',
    label: 'Brand Asset™',
    falModel: 'openai/gpt-image-2/edit',
    defaultPromptPrefix:
      'Premium brand asset for Studio World, reusable identity object, luxury editorial polish, strong silhouette, system-ready.',
    negativePrompt: `${UNIVERSAL_NEGATIVE}, no random letters, no invented logo text, no low-quality mockup`,
    resolution: '1536x1536',
    aspectRatio: '1:1',
    backgroundBehavior: 'transparent',
    lightingProfile: 'brand-object-spotlight',
    materialProfile: 'brand-material-language',
    outputFormat: 'png',
    registryDestination: 'brand-kits',
    versioningStrategy: 'semantic-version',
    upscalingPipeline: 'brand-asset-polish',
    metadata: {
      tags: ['brand-asset', 'identity', 'transparent'],
      relatedSystems: ['Brand Standards™', 'Asset Registry™', 'Marketplace™'],
      departmentsUsingIt: ['Brand Standards', 'Marketplace'],
      transparentBackground: true,
      registryLibrary: 'Brand Asset Library™',
    },
  },
};

export function getGenerationRecipe(recipeId: GenerationRecipeId): GenerationRecipe {
  return GENERATION_RECIPES[recipeId];
}
