/**
 * Executive Organization V1.0 bootstrap — living org seed (Milestone 41).
 */

import { DNA_ALIGNMENT_LAYERS, EXECUTIVE_ROSTER } from './constants';
import { bootstrapExecutiveOrganizationStore } from './store';
import type { ExecutiveHeadquarters, ExecutiveOrganizationStore } from './types';

function daysFromNow(d: number): string {
  return new Date(Date.now() + d * 86400_000).toISOString();
}

function defaultScorecard(overall: number) {
  const base = overall - 5;
  return {
    quality: base + 3,
    speed: base,
    innovation: base - 2,
    communication: base + 1,
    leadership: base + 2,
    resourceUtilization: base - 1,
    knowledgeContribution: base,
    crossFunctionalCollaboration: base + 1,
    overallPct: overall,
  };
}

function execHQ(
  id: ExecutiveHeadquarters['id'],
  mission: string,
  health: number,
  priorities: string[],
  workload: number,
  initiatives: string[],
  pending: number,
  metrics: { label: string; value: string }[],
  recs: string[],
  decisions: string[],
  knowledge: string[],
  personality: Partial<ExecutiveHeadquarters['personality']>
): ExecutiveHeadquarters {
  const roster = EXECUTIVE_ROSTER.find((r) => r.id === id)!;
  return {
    id,
    title: roster.title,
    department: roster.department,
    mission,
    departmentHealthPct: health,
    currentPriorities: priorities,
    teamWorkloadPct: workload,
    activeInitiatives: initiatives,
    pendingApprovals: pending,
    departmentMetrics: metrics,
    studioIntelligenceRecommendations: recs,
    recentDecisions: decisions,
    knowledgeGrowth: knowledge,
    personality: {
      communicationStyle: personality.communicationStyle ?? ['Direct · evidence-based'],
      leadershipStyle: personality.leadershipStyle ?? ['Coaching over criticism'],
      strengths: personality.strengths ?? ['Department expertise'],
      preferences: personality.preferences ?? ['DNA-aligned decisions'],
      decisionTendencies: personality.decisionTendencies ?? ['Escalate exceptions to CoS'],
      expertise: personality.expertise ?? [roster.department],
      institutionalExperience: personality.institutionalExperience ?? ['Milestone 41 org activation'],
      dnaAlignment: [...DNA_ALIGNMENT_LAYERS],
    },
    scorecard: defaultScorecard(health),
    reportsTo: id === 'chief-of-staff' ? 'founder' : 'chief-of-staff',
  };
}

export function buildExecutiveOrganizationSeed(): Partial<ExecutiveOrganizationStore> {
  const executives: ExecutiveHeadquarters[] = [
    execHQ(
      'chief-of-staff',
      'Coordinate the leadership team · protect founder attention · orchestrate production and approvals',
      86,
      ['Review 2 founder escalations', 'Moderate daily briefing', 'Clear thumbnail bottleneck'],
      72,
      ['Soft approval threshold calibration', 'Newsroom orchestration sync'],
      2,
      [{ label: 'AUTO-APPROVAL RATE', value: '88%' }, { label: 'FOUNDER REVIEW', value: '4 MIN' }],
      ['Delegate 2 additional L2 creative approvals', 'Consolidate duplicate Labs tests'],
      ['Soft-approved page 028 thumbnail', 'Returned page 029 script for hook revision'],
      ['Leadership DNA training active · 47 decision patterns logged'],
      {
        communicationStyle: ['One unified briefing · escalate with confidence + evidence'],
        leadershipStyle: ['Coordinates · never replaces founder judgment'],
        strengths: ['Pattern recognition', 'Cross-department visibility', 'Attention protection'],
        decisionTendencies: ['Soft approve when Leadership DNA aligned · escalate exceptions'],
        expertise: ['Decision routing', 'Executive coaching', 'Portfolio coordination'],
      }
    ),
    execHQ(
      'chief-marketing-officer',
      'Own brand campaigns · cross-channel messaging · growth marketing strategy',
      81,
      ['Money Monday March cycle', 'Instagram carousel test hold until page 028'],
      68,
      ['Q3 campaign calendar', 'Cross-platform push page 028-030'],
      1,
      [{ label: 'CAMPAIGN ROI', value: '3.2x' }, { label: 'REACH WoW', value: '+12%' }],
      ['Hold carousel until page 028 publishes', 'Increase mind volume cadence'],
      ['Soft-approved Money Monday cycle'],
      ['Campaign template v2 archived to org memory'],
      {
        communicationStyle: ['Campaign briefs with clear KPIs'],
        strengths: ['Campaign sequencing', 'Platform packaging'],
        preferences: ['Labs-validated formats before scale'],
      }
    ),
    execHQ(
      'chief-creative-officer',
      'Translate Creative DNA into thumbnails · hooks · visual systems',
      74,
      ['Clear thumbnail queue · page 028-029', 'Implement Labs #38 default template'],
      82,
      ['Stat overlay playbook', 'Thumbnail automation routing'],
      3,
      [{ label: 'QUEUE AGING', value: '3 > 24H' }, { label: 'DNA COMPLIANCE', value: '91%' }],
      ['Default Labs #38 for money/mind volumes', 'Reduce manual review on template matches'],
      ['Approved page 028 stat overlay variant B'],
      ['Creative taste patterns linked to Leadership DNA'],
      {
        communicationStyle: ['Visual references · specific revision notes'],
        leadershipStyle: ['Quality bar never lowered for speed'],
        strengths: ['Visual systems', 'Brand consistency', 'Experiment design'],
        preferences: ['Minimal text thumbnails · stat overlays on money content'],
      }
    ),
    execHQ(
      'chief-operations-officer',
      'Publishing · scheduling · workflow automation · bottleneck resolution',
      86,
      ['Publish page 028 at 2 PM', 'Batch voice renders overnight'],
      55,
      ['Fully-autonomous scheduling', 'Caption A/B routing automation'],
      0,
      [{ label: 'ON-TIME RATE', value: '94%' }, { label: 'AUTOMATIONS', value: '12 LIVE' }],
      ['Increase ops autonomy for schedule adjustments'],
      ['Auto-approved 8 schedule optimizations this week'],
      ['Scheduling delegation pattern → operational DNA'],
      {
        strengths: ['Process optimization', 'Automation design'],
        decisionTendencies: ['Fast approval on reversible scheduling changes'],
      }
    ),
    execHQ(
      'chief-financial-officer',
      'Budget · ROI · vendor · financial approvals',
      79,
      ['Q3 tools renewal $2,400 escalation', 'ROI deck for creator stack'],
      45,
      ['Annual billing preference enforcement', 'Discretionary band tracking'],
      1,
      [{ label: 'REVENUE PACE', value: '$428/DAY' }, { label: 'TOOL ROI', value: '3.2x' }],
      ['Negotiate 15% discount on tool renewal'],
      ['Escalated Q3 tools budget to founder'],
      ['Under-$3K approval pattern logged in Leadership DNA'],
      {
        communicationStyle: ['ROI decks · annual vs monthly comparison'],
        decisionTendencies: ['Founder review above $2K'],
      }
    ),
    execHQ(
      'chief-content-officer',
      'Editorial strategy · content calendar · narrative coherence',
      83,
      ['Page 029 hook revision', 'Mind volume 3 pages/week proposal'],
      78,
      ['Habits chapter expansion', 'Writing Bible compliance gate'],
      2,
      [{ label: 'PAGES/WEEK', value: '14' }, { label: 'WRITING COMPLIANCE', value: '89%' }],
      ['Apply Labs #42 hook template before resubmit'],
      ['Returned page 029 for hook revision'],
      ['Question hook pattern → writing intelligence'],
      {
        strengths: ['Editorial voice', 'Hook patterns', 'Volume strategy'],
        preferences: ['Writing Bible enforcement before submission'],
      }
    ),
    execHQ(
      'chief-growth-officer',
      'Audience segments · retention loops · content experiments',
      77,
      ['Mind volume +18% allocation', 'Automate caption routing to Labs'],
      62,
      ['Retention loop analysis', 'Cadence increase proposal'],
      0,
      [{ label: 'RETENTION WoW', value: '+18%' }, { label: 'NEW READERS', value: '+840/wk' }],
      ['Allocate 2 extra mind volume pages', 'Soft-approve caption automation rule'],
      ['Soft-approved caption A/B routing automation'],
      ['Mind volume outperforming → cross-company insight'],
      {
        strengths: ['Retention analysis', 'Experiment design'],
      }
    ),
    execHQ(
      'chief-legal-officer',
      'Compliance · partnerships · affiliate · policy reviews',
      92,
      ['Affiliate disclosure v2.2 review', 'Consumer volume disclaimer'],
      35,
      ['FTC guidance alignment', 'Partnership template updates'],
      1,
      [{ label: 'POLICY COMPLIANCE', value: '100%' }, { label: 'REVIEWS PENDING', value: '1' }],
      ['Founder acknowledgment on policy updates'],
      ['Escalated affiliate disclosure update'],
      ['Legal conservative pattern → Leadership DNA risk profile'],
      {
        decisionTendencies: ['Always founder-reviewed on policy changes'],
        communicationStyle: ['Diff from approved template · risk summary'],
      }
    ),
    execHQ(
      'chief-brand-officer',
      'Premium positioning · visual genome · editorial standards',
      85,
      ['Page 028 brand voice check', 'ndxbook page badge consistency'],
      58,
      ['Brand voice audit Q3', 'Cross-platform consistency review'],
      0,
      [{ label: 'BRAND CONSISTENCY', value: '94%' }, { label: 'DEVIATIONS', value: '2' }],
      ['Enforce page number badges on all ndxbook pages'],
      ['Auto-approved minor copy edit page 028'],
      ['Brand philosophy captured in company culture layer'],
      {
        strengths: ['Brand guardrails', 'Editorial standards'],
        preferences: ['Template adherence over novelty for core formats'],
      }
    ),
    execHQ(
      'chief-technology-officer',
      'Platform · integrations · OAuth · automation infrastructure',
      80,
      ['Instagram OAuth configuration', 'Social publishing migration'],
      50,
      ['OAuth env checklist', 'API reliability monitoring'],
      0,
      [{ label: 'INTEGRATIONS', value: '4/5 LIVE' }, { label: 'UPTIME', value: '99.2%' }],
      ['Complete Instagram OAuth for ndxbook SOCIALS'],
      ['Social OAuth setup guide deployed'],
      [],
      { expertise: ['OAuth', 'Vercel integrations', 'Supabase migrations'] }
    ),
    execHQ(
      'chief-product-officer',
      'Product roadmap · ndxbook features · reader experience',
      76,
      ['Page workspace UX', 'Reader retention features'],
      48,
      ['Mission Control + Newsroom integration', 'Page atomic unit refinement'],
      0,
      [{ label: 'COMPLETION RATE', value: '72%+' }, { label: 'FEATURE VELOCITY', value: 'M40' }],
      ['Prioritize page workspace as atomic knowledge unit'],
      [],
      [],
      { strengths: ['Product vision', 'Reader experience'] }
    ),
  ];

  const creativeTeams = [
    { id: 'team-art', name: 'ART DIRECTION', leadWorkerId: 'w-art-1', workerIds: ['w-art-1', 'w-art-2'], skills: ['Visual direction', 'Creative DNA'] },
    { id: 'team-graphic', name: 'GRAPHIC DESIGN', leadWorkerId: 'w-gd-1', workerIds: ['w-gd-1', 'w-gd-2'], skills: ['Thumbnails', 'Stat overlays'] },
    { id: 'team-motion', name: 'MOTION DESIGN', leadWorkerId: 'w-motion-1', workerIds: ['w-motion-1'], skills: ['Animation', 'Transitions'] },
    { id: 'team-copy', name: 'COPY SUPPORT', leadWorkerId: 'w-copy-1', workerIds: ['w-copy-1'], skills: ['Captions', 'Writing Bible'] },
  ];

  return {
    dashboard: {
      summary:
        'Living executive organization active · 11 executives · 12 departments · 24 teams · 47 workers · CoS coordinates · Studio Intelligence advises',
      executiveCount: 11,
      departmentCount: 12,
      teamCount: 24,
      workerCount: 47,
      activeCollaborations: 6,
      overallOrgHealthPct: 82,
      cultureMaturityPct: 78,
    },
    executives,
    departments: [
      {
        id: 'dept-creative',
        name: 'CREATIVE',
        executiveId: 'chief-creative-officer',
        objectives: ['Clear thumbnail bottleneck', '91% DNA compliance', 'Labs #38 as default'],
        capacityPct: 68,
        healthPct: 74,
        backlogCount: 5,
        knowledgeItems: ['Stat overlay playbook', 'Minimal text thumbnail standard'],
        activeInitiatives: ['Thumbnail automation', 'Creative taste engine sync'],
        crossFunctionalPartners: ['Marketing', 'Content', 'Brand'],
        teams: creativeTeams,
        quarterlyObjectives: ['Reduce review time 30%', '100% page badge compliance'],
        keyResults: ['Queue < 12h avg', '3 Labs winners rolled out'],
        completedMilestones: ['Labs #38 stat overlay validated'],
        playbookStandards: ['Creative DNA adherence', 'Every thumbnail = experiment opportunity'],
        playbookChecklists: ['DNA check · Labs data · Leadership DNA alignment · CoS threshold'],
      },
      {
        id: 'dept-marketing',
        name: 'MARKETING',
        executiveId: 'chief-marketing-officer',
        objectives: ['Money Monday March cycle', 'Cross-platform page 028 push'],
        capacityPct: 72,
        healthPct: 81,
        backlogCount: 3,
        knowledgeItems: ['Campaign template v2', 'Money Monday playbook'],
        activeInitiatives: ['Q3 campaign calendar'],
        crossFunctionalPartners: ['Creative', 'Growth', 'Operations'],
        teams: [
          { id: 'team-campaigns', name: 'CAMPAIGNS', leadWorkerId: 'w-camp-1', workerIds: ['w-camp-1', 'w-camp-2'], skills: ['Campaign sequencing'] },
          { id: 'team-social', name: 'SOCIAL PACKAGING', leadWorkerId: 'w-social-1', workerIds: ['w-social-1'], skills: ['Platform-specific packaging'] },
        ],
        quarterlyObjectives: ['3 coordinated campaign cycles', '+15% reach WoW'],
        keyResults: ['Campaign ROI > 3x', 'Zero off-brand launches'],
        completedMilestones: ['February Money Monday auto-approved'],
        playbookStandards: ['No launch without Creative DNA sign-off'],
        playbookChecklists: ['Campaign brief · ROI projection · CoS soft approval'],
      },
      {
        id: 'dept-content',
        name: 'CONTENT',
        executiveId: 'chief-content-officer',
        objectives: ['14 pages/week throughput', 'Writing Bible 89% compliance'],
        capacityPct: 78,
        healthPct: 83,
        backlogCount: 4,
        knowledgeItems: ['Hook template B · Question hooks for mind volume'],
        activeInitiatives: ['Habits chapter expansion', '3 pages/week mind cadence'],
        crossFunctionalPartners: ['Creative', 'Research', 'Legal'],
        teams: [
          { id: 'team-editorial', name: 'EDITORIAL', leadWorkerId: 'w-ed-1', workerIds: ['w-ed-1', 'w-ed-2'], skills: ['Scripts', 'Writing DNA'] },
          { id: 'team-research', name: 'RESEARCH', leadWorkerId: 'w-res-1', workerIds: ['w-res-1'], skills: ['Fact verification', 'Sources'] },
        ],
        quarterlyObjectives: ['Mind volume +3 pages/week', '72%+ completion on all pages'],
        keyResults: ['Hook revision rate < 15%', 'Research gate 100%'],
        completedMilestones: ['Page 019 institutional knowledge archived'],
        playbookStandards: ['Writing Bible before script submission'],
        playbookChecklists: ['Research complete · Hook pattern · Tone check · Legal flags'],
      },
      {
        id: 'dept-operations',
        name: 'OPERATIONS',
        executiveId: 'chief-operations-officer',
        objectives: ['94% on-time publish', 'Zero scheduling escalations'],
        capacityPct: 55,
        healthPct: 86,
        backlogCount: 1,
        knowledgeItems: ['Scheduling autonomy pattern', 'Automation rule catalog'],
        activeInitiatives: ['Caption routing automation', 'Overnight voice batch'],
        crossFunctionalPartners: ['Creative', 'Technology', 'Publishing'],
        teams: [
          { id: 'team-scheduling', name: 'SCHEDULING', leadWorkerId: 'w-sched-1', workerIds: ['w-sched-1'], skills: ['Publish optimization'] },
          { id: 'team-automation', name: 'AUTOMATION', leadWorkerId: 'w-auto-1', workerIds: ['w-auto-1', 'w-auto-2'], skills: ['Workflow rules', 'Pipelines'] },
        ],
        quarterlyObjectives: ['Fully autonomous scheduling', '12+ live automations'],
        keyResults: ['0 founder scheduling interrupts', 'Batch voice saves 4h/week'],
        completedMilestones: ['Operations → fully autonomous delegation'],
        playbookStandards: ['Reversible decisions move fast · fallback always exists'],
        playbookChecklists: ['Conflict check · Analytics sign-off · CoS notification'],
      },
      {
        id: 'dept-finance',
        name: 'FINANCE',
        executiveId: 'chief-financial-officer',
        objectives: ['$428/day revenue pace', 'Tool ROI validation'],
        capacityPct: 45,
        healthPct: 79,
        backlogCount: 1,
        knowledgeItems: ['Under-$3K approval pattern', 'Annual billing preference'],
        activeInitiatives: ['Q3 tools renewal'],
        crossFunctionalPartners: ['Legal', 'Operations', 'Growth'],
        teams: [{ id: 'team-budget', name: 'BUDGET & ROI', leadWorkerId: 'w-fin-1', workerIds: ['w-fin-1'], skills: ['ROI modeling', 'Vendor review'] }],
        quarterlyObjectives: ['Revenue pacing target', 'Zero unapproved spend'],
        keyResults: ['ROI deck on all tool renewals'],
        completedMilestones: ['Q2 tool renewal approved with discount'],
        playbookStandards: ['Founder review above $2K'],
        playbookChecklists: ['ROI deck · Annual vs monthly · Discretionary band check'],
      },
      {
        id: 'dept-legal',
        name: 'LEGAL',
        executiveId: 'chief-legal-officer',
        objectives: ['100% policy compliance', 'FTC guidance alignment'],
        capacityPct: 35,
        healthPct: 92,
        backlogCount: 1,
        knowledgeItems: ['Affiliate disclaimer v2.1', 'Consumer volume template'],
        activeInitiatives: ['Disclosure v2.2 update'],
        crossFunctionalPartners: ['Content', 'Brand', 'Finance'],
        teams: [{ id: 'team-compliance', name: 'COMPLIANCE', leadWorkerId: 'w-legal-1', workerIds: ['w-legal-1'], skills: ['FTC', 'Affiliate policy'] }],
        quarterlyObjectives: ['Zero compliance incidents'],
        keyResults: ['All disclaimers current'],
        completedMilestones: ['Consumer disclaimer v2.0 approved May 2026'],
        playbookStandards: ['Policy updates = founder review always'],
        playbookChecklists: ['Template diff · Risk summary · Founder acknowledgment'],
      },
    ],
    workers: [
      { id: 'w-art-1', name: 'Art Direction AI', type: 'ai-specialist', role: 'Art Director', skills: ['Visual systems', 'Creative DNA'], availabilityPct: 85, performancePct: 88, capacityPct: 72, knowledgeAreas: ['Stat overlays', 'Brand hierarchy'], assignedExecutiveId: 'chief-creative-officer', departmentId: 'dept-creative', teamId: 'team-art' },
      { id: 'w-gd-1', name: 'Thumbnail Generator', type: 'automation-agent', role: 'Graphic Designer', skills: ['Thumbnails', 'Labs integration'], availabilityPct: 95, performancePct: 91, capacityPct: 80, knowledgeAreas: ['Labs #38 template'], assignedExecutiveId: 'chief-creative-officer', departmentId: 'dept-creative', teamId: 'team-graphic' },
      { id: 'w-ed-1', name: 'Script Writer AI', type: 'ai-specialist', role: 'Content Writer', skills: ['Writing Bible', 'Hooks'], availabilityPct: 78, performancePct: 84, capacityPct: 75, knowledgeAreas: ['Question hooks', 'Money tone'], assignedExecutiveId: 'chief-content-officer', departmentId: 'dept-content', teamId: 'team-editorial' },
      { id: 'w-auto-1', name: 'Workflow Orchestrator', type: 'automation-agent', role: 'Automation Engineer', skills: ['Pipelines', 'Scheduling'], availabilityPct: 90, performancePct: 93, capacityPct: 60, knowledgeAreas: ['Caption routing', 'Publish optimization'], assignedExecutiveId: 'chief-operations-officer', departmentId: 'dept-operations', teamId: 'team-automation' },
      { id: 'w-res-1', name: 'Research AI', type: 'ai-specialist', role: 'Research Analyst', skills: ['Fact check', 'Source verification'], availabilityPct: 82, performancePct: 87, capacityPct: 65, knowledgeAreas: ['CFPB', 'NIH sleep data'], assignedExecutiveId: 'chief-content-officer', departmentId: 'dept-content', teamId: 'team-research' },
    ],
    collaborations: [
      { id: 'col-1', fromExecutiveId: 'chief-marketing-officer', toExecutiveId: 'chief-creative-officer', request: 'Asset request · page 028 campaign thumbnails', status: 'complete', automated: true },
      { id: 'col-2', fromExecutiveId: 'chief-creative-officer', toExecutiveId: 'chief-content-officer', request: 'Research request · habits chapter visual references', status: 'in-progress', automated: true },
      { id: 'col-3', fromExecutiveId: 'chief-financial-officer', toExecutiveId: 'chief-marketing-officer', request: 'Budget review · Money Monday March cycle', status: 'complete', automated: false },
      { id: 'col-4', fromExecutiveId: 'chief-legal-officer', toExecutiveId: 'chief-brand-officer', request: 'Partnership review · affiliate disclosure alignment', status: 'pending', automated: false },
      { id: 'col-5', fromExecutiveId: 'chief-operations-officer', toExecutiveId: 'chief-creative-officer', request: 'Bottleneck resolution · thumbnail queue > 24h', status: 'in-progress', automated: true },
      { id: 'col-6', fromExecutiveId: 'chief-of-staff', toExecutiveId: 'chief-growth-officer', request: 'Coordinate mind volume cadence increase proposal', status: 'complete', automated: true },
    ],
    organizationalMemory: [
      { id: 'om-1', departmentId: 'dept-creative', type: 'best-practice', title: 'Stat overlay default for money volume', detail: 'Labs #38 winner · +18% CTR · Leadership DNA fast-approval pattern', transferable: true },
      { id: 'om-2', departmentId: 'dept-content', type: 'mistake', title: 'Casual tone in money content rejected', detail: 'Founder rejected 3x · enforce Writing Bible before submission', transferable: true },
      { id: 'om-3', departmentId: 'dept-operations', type: 'workflow', title: 'Fully-autonomous scheduling earned', detail: 'Zero overrides 30 days · delegation pattern logged', transferable: true },
      { id: 'om-4', departmentId: 'dept-marketing', type: 'template', title: 'Money Monday campaign template v2', detail: 'CoS soft-approved · standard sequencing playbook', transferable: true },
      { id: 'om-5', departmentId: 'dept-legal', type: 'case-study', title: 'Consumer disclaimer v2.0 approval', detail: 'Founder reviewed · no compliance issues post-publish', transferable: false },
      { id: 'om-6', departmentId: 'dept-creative', type: 'lesson', title: 'Thumbnail queue aging pattern', detail: 'CCO coached · implement default template routing', transferable: true },
    ],
    meetings: [
      { id: 'mtg-1', type: 'daily-briefing', title: 'DAILY EXECUTIVE BRIEFING', schedule: 'Every day · 8 AM', agenda: ['Overnight production', 'Founder escalations', 'Top 3 priorities per dept', 'Studio Intelligence signals'], moderator: 'chief-of-staff', founderAttendance: 'optional', nextAt: daysFromNow(0) },
      { id: 'mtg-2', type: 'weekly-leadership', title: 'WEEKLY LEADERSHIP MEETING', schedule: 'Mondays · 10 AM', agenda: ['Department health review', 'Cross-functional blockers', 'Campaign alignment', 'CoS delegation updates'], moderator: 'chief-of-staff', founderAttendance: 'optional', nextAt: daysFromNow(1) },
      { id: 'mtg-3', type: 'monthly-review', title: 'MONTHLY BUSINESS REVIEW', schedule: 'First Monday · 2 PM', agenda: ['Revenue pacing', 'Org scorecards', 'Knowledge growth', 'Executive performance'], moderator: 'chief-of-staff', founderAttendance: 'scheduled-only', nextAt: daysFromNow(14) },
      { id: 'mtg-4', type: 'quarterly-strategy', title: 'QUARTERLY STRATEGY REVIEW', schedule: 'Quarter start · full day', agenda: ['OKR review', 'Portfolio strategy', 'New company launches', 'DNA layer updates'], moderator: 'chief-of-staff', founderAttendance: 'always', nextAt: daysFromNow(45) },
      { id: 'mtg-5', type: 'annual-planning', title: 'ANNUAL PLANNING', schedule: 'December · 2 days', agenda: ['Vision alignment', 'Annual OKRs', 'Budget allocation', 'Executive succession prep'], moderator: 'chief-of-staff', founderAttendance: 'always', nextAt: daysFromNow(180) },
    ],
    orgGraph: [
      { id: 'node-founder', label: 'FOUNDER', type: 'founder', connections: ['node-cos'] },
      { id: 'node-cos', label: 'CHIEF OF STAFF', type: 'chief-of-staff', connections: ['node-exec-leadership', 'node-leadership-dna'] },
      { id: 'node-exec-leadership', label: 'EXECUTIVE LEADERSHIP', type: 'executive-leadership', connections: ['dept-creative', 'dept-marketing', 'dept-content', 'dept-operations'] },
      { id: 'dept-creative', label: 'CREATIVE DEPT', type: 'departments', connections: ['team-art', 'team-graphic', 'node-newsroom'] },
      { id: 'team-art', label: 'ART DIRECTION', type: 'teams', connections: ['w-art-1'] },
      { id: 'w-art-1', label: 'ART DIRECTOR AI', type: 'workers', connections: ['proj-page-028'] },
      { id: 'proj-page-028', label: 'PAGE 028 PRODUCTION', type: 'projects', connections: ['task-thumb-review'] },
      { id: 'task-thumb-review', label: 'THUMBNAIL REVIEW', type: 'tasks', connections: ['node-institutional-knowledge'] },
      { id: 'node-institutional-knowledge', label: 'INSTITUTIONAL KNOWLEDGE', type: 'knowledge', connections: [] },
      { id: 'node-leadership-dna', label: 'LEADERSHIP DNA', type: 'knowledge', connections: ['node-cos'] },
      { id: 'node-newsroom', label: 'NEWSROOM', type: 'initiative', connections: ['dept-creative', 'dept-content'] },
    ],
    companyCulture: {
      mission: 'Build media company operating systems that transform ideas into institutional knowledge',
      vision: 'Every organization in Studio OS feels like headquarters of an extraordinary company',
      values: ['Institutional knowledge over tribal knowledge', 'Quality compounds', 'Founder leads · team executes together', 'Clarity over complexity'],
      leadershipPrinciples: ['Build systems before scaling', 'Protect founder attention', 'Automation increases judgment'],
      brandPhilosophy: ['ndxbook = index for everyday knowledge', 'Quality over volume for flagship brands', 'Template adherence for core formats'],
      decisionPhilosophy: ['Evidence-based · DNA-aligned · CoS coordinates · founder on strategy'],
      operatingPrinciples: ['Every page = atomic knowledge unit', 'Newsroom produces · Mission Control summarizes', 'Experiments become reusable knowledge'],
      traditions: ['Money Monday cycles', 'Morning unified briefing', 'Milestone-driven platform evolution'],
    },
    successionPackages: EXECUTIVE_ROSTER.map((r) => ({
      executiveId: r.id,
      inheritsHistory: true,
      inheritsKnowledge: true,
      inheritsStandards: true,
      inheritsPerformance: true,
      inheritsLeadershipPhilosophy: true,
      organizationalContext: ['Department playbooks', 'Organizational memory', 'Scorecard history', 'DNA alignment requirements'],
    })),
    selectedExecutiveId: 'chief-creative-officer',
    selectedDepartmentId: 'dept-creative',
  };
}

export function bootstrapExecutiveOrganizationPlatform(): void {
  bootstrapExecutiveOrganizationStore(buildExecutiveOrganizationSeed());
}
