import type { TutorialTour } from '../types';
import { MANSION_TOUR_ID } from '../constants';

/** The Mansion Tour — flagship onboarding walkthrough (10 steps). */
export const MANSION_TOUR: TutorialTour = {
  id: MANSION_TOUR_ID,
  moduleName: 'The Mansion Tour',
  customerName: 'The Mansion Tour',
  optionalLabel: 'FS Concierge',
  description:
    'A luxury guided walkthrough of Frontal Slayer — learn each feature by exploring the real site with your concierge.',
  estimatedMinutes: 3,
  status: 'enabled',
  featured: true,
  achievementId: 'explorer-badge',
  steps: [
    {
      id: 'welcome',
      tourId: MANSION_TOUR_ID,
      title: 'WELCOME TO FRONTAL SLAYER',
      body: 'Frontal Slayer is a luxury interactive hair shopping experience — customize units, watch member content, earn rewards, and shop with concierge-level guidance.',
      benefit: 'Understand the mansion before you explore on your own.',
      animationType: 'transition',
      position: 'center',
      spotlight: false,
      completionTrigger: 'manual',
      order: 1,
      previewKey: 'welcome',
    },
    {
      id: 'navigation',
      tourId: MANSION_TOUR_ID,
      title: 'NAVIGATION',
      body: 'Use the menu toggle to move between Shop, Tools, and Brand. Units, Build-A-Wig, booking, and Slay Cam live under Shop.',
      benefit: 'Know where to go before you tap.',
      route: '/home/shop',
      targetSelector: '[data-tutorial-target="nav-menu-toggle"]',
      animationType: 'pulse',
      position: 'bottom',
      spotlight: true,
      completionTrigger: 'view',
      order: 2,
      previewKey: 'navigation',
    },
    {
      id: 'build-a-wig',
      tourId: MANSION_TOUR_ID,
      title: 'BUILD-A-WIG',
      body: 'Customize a unit by texture, color, length, density, lace, and add-ons. Preview your look before it lands in your bag.',
      benefit: 'Design your signature unit step by step.',
      route: '/build-a-wig/view',
      targetSelector: '[data-attribute="baw-build-area"]',
      animationType: 'glow',
      position: 'bottom',
      spotlight: true,
      actionLabel: 'TRY BUILD-A-WIG',
      actionRoute: '/build-a-wig/view',
      completionTrigger: 'view',
      order: 3,
      previewKey: 'build-a-wig',
    },
    {
      id: 'signature-collection',
      tourId: MANSION_TOUR_ID,
      title: 'SIGNATURE COLLECTION',
      body: 'Six flagship units anchor the catalog: NOIR, BLANCO, SOFT WAVE, BEACH WAVE, SOFT CURL, and OCEAN CURL — each with its own texture story.',
      benefit: 'Match your vibe to the right signature unit.',
      route: '/shop/units',
      targetSelector: '[data-tutorial-target="shop-units-grid"]',
      animationType: 'zoom',
      position: 'bottom',
      spotlight: true,
      actionLabel: 'BROWSE UNITS',
      actionRoute: '/shop/units',
      completionTrigger: 'view',
      order: 4,
      previewKey: 'signature-collection',
    },
    {
      id: 'hairstyle-analysis',
      tourId: MANSION_TOUR_ID,
      title: 'HAIRSTYLE ANALYSIS',
      body: 'Upload a selfie or inspo photo to receive personalized style guidance — ranked looks and unit recommendations tailored to you.',
      benefit: 'Let AI help you find your best match.',
      route: '/home/tools',
      targetSelector: '[data-attribute="hairstyle-analysis-card"]',
      animationType: 'arrow',
      position: 'bottom',
      spotlight: true,
      actionLabel: 'OPEN TOOLS',
      actionRoute: '/home/tools',
      completionTrigger: 'view',
      order: 5,
      previewKey: 'hairstyle-analysis',
    },
    {
      id: 'lounge-tv',
      tourId: MANSION_TOUR_ID,
      title: 'LOUNGE TV',
      body: 'Member content lives in the lobby salon — tutorials, Slay Tips, Watch + Learn episodes, and premium-gated lessons.',
      benefit: 'Learn install, care, and styling from the lounge.',
      route: '/lobby/lounge',
      animationType: 'spotlight',
      position: 'center',
      spotlight: true,
      completionTrigger: 'view',
      order: 6,
      previewKey: 'lounge-tv',
    },
    {
      id: 'rewards',
      tourId: MANSION_TOUR_ID,
      title: 'REWARDS',
      body: 'Earn loyalty points, Slay Tickets, vouchers, collectibles, and tier unlocks as you shop, review, and engage with the brand.',
      benefit: 'Turn every slay into perks and savings.',
      route: '/account/rewards',
      targetSelector: '[data-tutorial-target="rewards-chart"]',
      animationType: 'glow',
      position: 'bottom',
      spotlight: true,
      requiresLogin: true,
      actionLabel: 'VIEW REWARDS',
      actionRoute: '/account/rewards',
      completionTrigger: 'view',
      order: 7,
      previewKey: 'rewards',
    },
    {
      id: 'account',
      tourId: MANSION_TOUR_ID,
      title: 'ACCOUNT',
      body: 'Your dashboard holds order history, membership status, rewards, tickets, saved items, messages, and concierge support.',
      benefit: 'One home for everything you own here.',
      route: '/account',
      animationType: 'blur',
      position: 'bottom',
      spotlight: true,
      requiresLogin: true,
      actionLabel: 'OPEN ACCOUNT',
      actionRoute: '/account',
      completionTrigger: 'view',
      order: 8,
      previewKey: 'account',
    },
    {
      id: 'cart-checkout',
      tourId: MANSION_TOUR_ID,
      title: 'CART & CHECKOUT',
      body: 'Your bag keeps configuration summaries, Build-A-Wig visual snapshots, and order details — checkout confirms every choice before you pay.',
      benefit: 'Review your build before it ships.',
      route: '/bag',
      targetSelector: '[data-tutorial-target="nav-cart"]',
      animationType: 'pulse',
      position: 'bottom',
      spotlight: true,
      actionLabel: 'VIEW BAG',
      actionRoute: '/bag',
      completionTrigger: 'view',
      order: 9,
      previewKey: 'cart-checkout',
    },
    {
      id: 'finish',
      tourId: MANSION_TOUR_ID,
      title: 'TOUR COMPLETE',
      body: 'You have seen the mansion — explore freely, revisit any feature tour from FS Concierge, and enjoy the Frontal Slayer experience.',
      benefit: 'You are ready to slay with confidence.',
      animationType: 'transition',
      position: 'center',
      spotlight: false,
      completionTrigger: 'manual',
      order: 10,
      previewKey: 'finish',
    },
  ],
};
