import type { TutorialTour } from '../types';

/** Architecture-only tour shells — steps populated in future milestones. */
export const PLACEHOLDER_TOURS: TutorialTour[] = [
  {
    id: 'build-a-wig-tour',
    moduleName: 'Build-A-Wig Tour',
    customerName: 'Build-A-Wig Tour',
    optionalLabel: 'FS Concierge',
    description: 'Deep dive into customization — texture, color, lace, styling, and add-ons.',
    estimatedMinutes: 4,
    status: 'draft',
    achievementId: 'builder-badge',
    steps: [],
  },
  {
    id: 'rewards-tour',
    moduleName: 'Rewards Tour',
    customerName: 'Rewards Tour',
    optionalLabel: 'FS Concierge',
    description: 'Points, tickets, vouchers, collectibles, and tier unlocks explained.',
    estimatedMinutes: 2,
    status: 'draft',
    achievementId: 'collector-badge',
    steps: [],
  },
  {
    id: 'lounge-tv-tour',
    moduleName: 'Lounge TV Tour',
    customerName: 'Lounge TV Tour',
    optionalLabel: 'FS Concierge',
    description: 'Featured, Learn, Explore, Live, and Library — member content navigation.',
    estimatedMinutes: 3,
    status: 'draft',
    steps: [],
  },
  {
    id: 'hairstyle-analysis-tour',
    moduleName: 'Hairstyle Analysis Tour',
    customerName: 'Hairstyle Analysis Tour',
    optionalLabel: 'FS Concierge',
    description: 'Selfie upload, inspo matching, and personalized style guidance.',
    estimatedMinutes: 2,
    status: 'draft',
    steps: [],
  },
  {
    id: 'membership-tour',
    moduleName: 'Membership Tour',
    customerName: 'Membership Tour',
    optionalLabel: 'FS Concierge',
    description: 'Standard vs premium membership benefits and upgrade paths.',
    estimatedMinutes: 2,
    status: 'draft',
    steps: [],
  },
  {
    id: 'account-tour',
    moduleName: 'Account Tour',
    customerName: 'Account Tour',
    optionalLabel: 'FS Concierge',
    description: 'Orders, concierge, alerts, settings, and profile management.',
    estimatedMinutes: 3,
    status: 'draft',
    steps: [],
  },
  {
    id: 'checkout-tour',
    moduleName: 'Checkout Tour',
    customerName: 'Checkout Tour',
    optionalLabel: 'FS Concierge',
    description: 'Bag review, configuration snapshots, and secure checkout flow.',
    estimatedMinutes: 2,
    status: 'draft',
    steps: [],
  },
];
