import { bootstrapReaderGraphStore } from './store';
import type { KnowledgeInterestId, ReaderGraphStore, ReaderProfile } from './types';

function daysFromNow(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString();
}

function daysAgo(days: number): string {
  return daysFromNow(-days);
}

export function buildReaderGraphSeed(): Partial<ReaderGraphStore> {
  const readers: ReaderProfile[] = [
    {
      id: 'reader-maya-k',
      workspaceId: 'ndxbook',
      displayName: 'MAYA K · RETURNING READER',
      relationshipStage: 'return',
      joinedAt: daysAgo(120),
      preferredPlatforms: ['Newsletter', 'Instagram', 'ndxbook'],
      preferredContent: ['Money Monday', 'Truth Tuesday', 'Long-form pages'],
      favoriteVolumes: ['Money Volume', 'Mind Volume'],
      favoriteChapters: ['Chapter 3 · Habits', 'Chapter 7 · Sleep'],
      favoritePages: ['Page 042 · Money habits', 'Page 041 · Sleep debt'],
      favoriteCreators: ['Finance Educator · Tier A'],
      favoriteHosts: ['Money Monday host'],
      favoriteProducts: [],
      favoriteCampaigns: ['MONEY MONDAY · MARCH CYCLE'],
      favoriteBrands: ['ndxbook'],
      readerScore: 78,
      trustScore: 82,
      engagementScore: 74,
      knowledgeScore: 71,
      communityScore: 45,
      advocacyScore: 38,
      lifetimeValue: '$0 · high LTV potential',
      companyIds: ['ndxbook'],
    },
    {
      id: 'reader-jordan-t',
      workspaceId: 'ndxbook',
      displayName: 'JORDAN T · ADVOCATE',
      relationshipStage: 'advocate',
      joinedAt: daysAgo(400),
      preferredPlatforms: ['TikTok', 'YouTube', 'Newsletter'],
      preferredContent: ['Short-form clips', 'Research-gated pages'],
      favoriteVolumes: ['Truth Volume', 'Health Volume'],
      favoriteChapters: ['Chapter 2 · Facts', 'Chapter 5 · Wellness'],
      favoritePages: ['Page 041 · Sleep debt', 'Page 038 · Nutrition myths'],
      favoriteCreators: ['Mind Volume Host'],
      favoriteHosts: ['Truth Tuesday host'],
      favoriteProducts: [],
      favoriteCampaigns: ['TRUTH TUESDAY · FACT-FORWARD'],
      favoriteBrands: ['ndxbook'],
      readerScore: 91,
      trustScore: 94,
      engagementScore: 88,
      knowledgeScore: 86,
      communityScore: 72,
      advocacyScore: 85,
      lifetimeValue: '$240 affiliate · referral value $180',
      companyIds: ['ndxbook'],
    },
    {
      id: 'reader-sam-l',
      workspaceId: 'ndxbook',
      displayName: 'SAM L · MEMBER',
      relationshipStage: 'member',
      joinedAt: daysAgo(60),
      preferredPlatforms: ['ndxbook', 'Email'],
      preferredContent: ['Daily pages', 'Newsletter deep dives'],
      favoriteVolumes: ['Money Volume'],
      favoriteChapters: ['Chapter 1 · Foundations'],
      favoritePages: ['Page 028 · Cross-platform'],
      favoriteCreators: [],
      favoriteHosts: [],
      favoriteProducts: [],
      favoriteCampaigns: ['NEWSLETTER LAUNCH · Q3'],
      favoriteBrands: ['ndxbook'],
      readerScore: 85,
      trustScore: 88,
      engagementScore: 82,
      knowledgeScore: 79,
      communityScore: 68,
      advocacyScore: 55,
      lifetimeValue: '$48 membership · projected $320/yr',
      companyIds: ['ndxbook'],
    },
    {
      id: 'reader-alex-r',
      workspaceId: 'frontal-slayer',
      displayName: 'ALEX R · CUSTOMER',
      relationshipStage: 'customer',
      joinedAt: daysAgo(200),
      preferredPlatforms: ['Site', 'Instagram', 'Concierge'],
      preferredContent: ['BAW live previews', 'Lounge TV', 'Product education'],
      favoriteVolumes: [],
      favoriteChapters: [],
      favoritePages: [],
      favoriteCreators: [],
      favoriteHosts: ['PSA Founder'],
      favoriteProducts: ['NOIR', 'Build-a-Wig'],
      favoriteCampaigns: ['NOIR · LIVE PREVIEW LAUNCH'],
      favoriteBrands: ['Frontal Slayer'],
      readerScore: 88,
      trustScore: 92,
      engagementScore: 76,
      knowledgeScore: 65,
      communityScore: 58,
      advocacyScore: 62,
      lifetimeValue: '$1,840 · premium member · BLACK tier',
      companyIds: ['frontal-slayer', 'ndxbook'],
    },
  ];

  return {
    dashboard: {
      summary:
        'READER GRAPH V1.0 — living relationship map between every company and every person it serves. Not followers · not vanity metrics · trust · learning · loyalty · advocacy over years.',
      totalReaders: 0,
      activeRelationships: 0,
      avgHealthPct: 0,
      topAdvocates: 0,
      emergingCommunities: 0,
      crossCompanyReaders: 0,
      relationshipGrowthPct: 14,
    },
    activeWorkspaceId: 'ndxbook',
    graphZoom: 'company',
    readers,
    relationshipHealth: {
      'reader-maya-k': { readerId: 'reader-maya-k', engagement: 74, trust: 82, consistency: 78, recency: 85, growth: 72, advocacy: 38, knowledgeDepth: 71, brandAffinity: 80, communityInvolvement: 45, overallPct: 76 },
      'reader-jordan-t': { readerId: 'reader-jordan-t', engagement: 88, trust: 94, consistency: 91, recency: 82, growth: 68, advocacy: 85, knowledgeDepth: 86, brandAffinity: 92, communityInvolvement: 72, overallPct: 89 },
      'reader-sam-l': { readerId: 'reader-sam-l', engagement: 82, trust: 88, consistency: 85, recency: 90, growth: 88, advocacy: 55, knowledgeDepth: 79, brandAffinity: 86, communityInvolvement: 68, overallPct: 84 },
      'reader-alex-r': { readerId: 'reader-alex-r', engagement: 76, trust: 92, consistency: 70, recency: 65, growth: 45, advocacy: 62, knowledgeDepth: 65, brandAffinity: 94, communityInvolvement: 58, overallPct: 81 },
    },
    timelines: [
      { id: 'tl-1', readerId: 'reader-maya-k', type: 'first-interaction', label: 'First page read · Money Monday', at: daysAgo(120) },
      { id: 'tl-2', readerId: 'reader-maya-k', type: 'first-bookmark', label: 'Bookmarked Page 042', at: daysAgo(45) },
      { id: 'tl-3', readerId: 'reader-maya-k', type: 'knowledge-growth', label: 'Completed 12 pages · Money + Mind volumes', at: daysAgo(14) },
      { id: 'tl-4', readerId: 'reader-jordan-t', type: 'first-interaction', label: 'Discovered via TikTok · Truth Tuesday', at: daysAgo(400) },
      { id: 'tl-5', readerId: 'reader-jordan-t', type: 'first-share', label: 'Shared Page 041 · sleep debt', at: daysAgo(180) },
      { id: 'tl-6', readerId: 'reader-jordan-t', type: 'subscribe', label: 'Newsletter subscriber', at: daysAgo(150) },
      { id: 'tl-7', readerId: 'reader-jordan-t', type: 'relationship-milestone', label: 'Advocate tier · 5 referrals', at: daysAgo(30) },
      { id: 'tl-8', readerId: 'reader-sam-l', type: 'membership', label: 'ndxbook member · Q1', at: daysAgo(60) },
      { id: 'tl-9', readerId: 'reader-alex-r', type: 'first-purchase', label: 'NOIR unit · Build-a-Wig', at: daysAgo(180) },
      { id: 'tl-10', readerId: 'reader-alex-r', type: 'campaign', label: 'Engaged · Lounge TV · CUTTING YOUR LACE', at: daysAgo(90) },
    ],
    interests: [
      { id: 'int-1', readerId: 'reader-maya-k', interestId: 'finance', label: 'FINANCE', strengthPct: 88, trend: 'rising', firstSeenAt: daysAgo(120), lastSeenAt: daysAgo(2) },
      { id: 'int-2', readerId: 'reader-maya-k', interestId: 'health', label: 'HEALTH', strengthPct: 62, trend: 'stable', firstSeenAt: daysAgo(90), lastSeenAt: daysAgo(14) },
      { id: 'int-3', readerId: 'reader-jordan-t', interestId: 'health', label: 'HEALTH', strengthPct: 92, trend: 'stable', firstSeenAt: daysAgo(400), lastSeenAt: daysAgo(1) },
      { id: 'int-4', readerId: 'reader-jordan-t', interestId: 'psychology', label: 'PSYCHOLOGY', strengthPct: 74, trend: 'rising', firstSeenAt: daysAgo(200), lastSeenAt: daysAgo(3) },
      { id: 'int-5', readerId: 'reader-sam-l', interestId: 'finance', label: 'FINANCE', strengthPct: 78, trend: 'rising', firstSeenAt: daysAgo(60), lastSeenAt: daysAgo(1) },
      { id: 'int-6', readerId: 'reader-alex-r', interestId: 'luxury', label: 'LUXURY', strengthPct: 95, trend: 'stable', firstSeenAt: daysAgo(200), lastSeenAt: daysAgo(7) },
      { id: 'int-7', readerId: 'reader-alex-r', interestId: 'hair', label: 'HAIR', strengthPct: 98, trend: 'stable', firstSeenAt: daysAgo(200), lastSeenAt: daysAgo(7) },
      { id: 'int-8', readerId: 'reader-alex-r', interestId: 'beauty', label: 'BEAUTY', strengthPct: 85, trend: 'stable', firstSeenAt: daysAgo(150), lastSeenAt: daysAgo(14) },
    ],
    behaviorIntel: [
      {
        readerId: 'reader-maya-k',
        readingHabits: 'Tue-Wed evenings · 2-3 pages/session · completes 78%',
        watchHabits: 'Instagram Reels · 42s avg · skips intros',
        purchaseHabits: 'No purchases yet · high intent signals on money content',
        learningPreferences: 'Stat-forward · research citations · short summaries',
        preferredPlatforms: ['Newsletter', 'Instagram', 'ndxbook'],
        preferredPublishingTimes: ['Tue 9am ET', 'Wed 7pm ET'],
        favoriteFormats: ['Long-form page', 'Newsletter', 'Reel'],
        completionBehavior: '78% page completion · bookmarks before finishing',
        bookmarkBehavior: 'Bookmarks 2.3 pages/week · returns within 48h',
        sharingBehavior: 'Rare shares · 1 share/90 days',
        commentBehavior: 'No public comments · email replies occasionally',
        strategyConnection: 'Aligns with MONEY MONDAY · returning reader north star',
      },
      {
        readerId: 'reader-jordan-t',
        readingHabits: 'Daily · Truth Tuesday priority · 95% completion',
        watchHabits: 'TikTok + YouTube Shorts · 51s avg · high retention',
        purchaseHabits: 'Affiliate clicks · $240 attributed · no direct purchase',
        learningPreferences: 'Fact-forward · research-gated · shareable clips',
        preferredPlatforms: ['TikTok', 'YouTube', 'Newsletter'],
        preferredPublishingTimes: ['Tue 9am ET', 'Thu 6pm ET'],
        favoriteFormats: ['Short-form video', 'Research page', 'Newsletter'],
        completionBehavior: '95% completion · reads full citations',
        bookmarkBehavior: 'Bookmarks for reference · 4/month',
        sharingBehavior: 'Active sharer · 2.1 shares/week · advocate signal',
        commentBehavior: 'Engages on TikTok · thoughtful comments',
        strategyConnection: 'Truth Tuesday authority · advocate pipeline · creator candidate',
      },
    ],
    communities: [
      { id: 'comm-1', workspaceId: 'ndxbook', label: 'FINANCE READERS', description: 'Money-curious · returning · stat-forward preference', memberCount: 1240, readerIds: ['reader-maya-k', 'reader-sam-l'], sharedInterests: ['finance', 'entrepreneurship'] as KnowledgeInterestId[], recommendation: 'Invite high-trust finance readers to membership · affiliate pipeline' },
      { id: 'comm-2', workspaceId: 'ndxbook', label: 'HEALTH READERS', description: 'Truth Tuesday loyalists · research-gated content', memberCount: 890, readerIds: ['reader-jordan-t'], sharedInterests: ['health', 'wellness', 'psychology'] as KnowledgeInterestId[], recommendation: 'Bundle wellness learning path · podcast series candidate' },
      { id: 'comm-3', workspaceId: 'ndxbook', label: 'EARLY ADOPTERS', description: 'First 90 days · high engagement · membership candidates', memberCount: 340, readerIds: ['reader-sam-l'], sharedInterests: ['finance', 'technology'] as KnowledgeInterestId[], recommendation: 'Personalized membership invite · community beta' },
      { id: 'comm-4', workspaceId: 'frontal-slayer', label: 'LUXURY BUYERS', description: 'Premium raw hair · BAW completion · concierge engaged', memberCount: 520, readerIds: ['reader-alex-r'], sharedInterests: ['luxury', 'hair', 'beauty'] as KnowledgeInterestId[], recommendation: 'Lounge TV upsell · membership retention focus' },
    ],
    intelligenceSignals: [
      { id: 'sig-1', readerId: 'reader-maya-k', category: 'high-potential', label: 'HIGH POTENTIAL · MEMBERSHIP CANDIDATE', confidencePct: 82, engagementStrategy: 'Invite to membership after Page 042 completion · personalized money volume path' },
      { id: 'sig-2', readerId: 'reader-maya-k', category: 'future-customer', label: 'FUTURE CUSTOMER · AFFILIATE PIPELINE', confidencePct: 68, engagementStrategy: 'Recommend affiliate tools after trust threshold · no hard sell' },
      { id: 'sig-3', readerId: 'reader-jordan-t', category: 'future-advocate', label: 'FUTURE AMBASSADOR · CREATOR PIPELINE', confidencePct: 91, engagementStrategy: 'Creator marketplace outreach · guest collaboration on Truth Tuesday' },
      { id: 'sig-4', readerId: 'reader-jordan-t', category: 'future-creator', label: 'FUTURE CREATOR · UGC OPPORTUNITY', confidencePct: 85, engagementStrategy: 'Affiliate invitation · co-create health clip series' },
      { id: 'sig-5', readerId: 'reader-sam-l', category: 'future-advocate', label: 'EMERGING ADVOCATE · COMMUNITY LEADER', confidencePct: 74, engagementStrategy: 'Recommend community moderator role · event invitation' },
      { id: 'sig-6', readerId: 'reader-alex-r', category: 'future-partner', label: 'CROSS-BRAND · PORTFOLIO READER', confidencePct: 78, engagementStrategy: 'Bridge ndxbook wellness content · FS lounge education crossover' },
    ],
    recommendations: [
      { id: 'rec-1', readerId: 'reader-maya-k', type: 'membership', label: 'INVITE TO MEMBERSHIP', rationale: '82% trust · 78% engagement · money volume completion pattern', longTermValue: 'Projected $320/yr · advocate pipeline in 6 months', confidencePct: 82 },
      { id: 'rec-2', readerId: 'reader-maya-k', type: 'premium-content', label: 'RECOMMEND MONEY VOLUME DEEP DIVE', rationale: 'Finance interest rising · 88% strength · aligns with strategy', longTermValue: 'Knowledge depth → trust → membership conversion', confidencePct: 76 },
      { id: 'rec-3', readerId: 'reader-jordan-t', type: 'creator-collaboration', label: 'CREATOR COLLABORATION · TRUTH TUESDAY', rationale: '91% advocate signal · TikTok performance · brand fit', longTermValue: 'Ambassador tier · UGC pipeline · affiliate revenue', confidencePct: 91 },
      { id: 'rec-4', readerId: 'reader-jordan-t', type: 'affiliate', label: 'AFFILIATE INVITATION', rationale: '$240 attributed · sharing behavior · trust 94%', longTermValue: 'Sustainable referral revenue · community growth', confidencePct: 88 },
      { id: 'rec-5', readerId: 'reader-sam-l', type: 'community', label: 'RECOMMEND FINANCE READERS COMMUNITY', rationale: 'Member · finance interest · early adopter cluster fit', longTermValue: 'Community involvement → advocacy → retention', confidencePct: 74 },
      { id: 'rec-6', readerId: 'reader-alex-r', type: 'partnership', label: 'CROSS-BRAND WELLNESS BRIDGE', rationale: 'Reads ndxbook health · FS customer · portfolio LTV $2K+', longTermValue: 'Portfolio relationship deepening · cross-company value', confidencePct: 78 },
    ],
    crossCompany: [
      {
        id: 'xc-1',
        readerId: 'reader-alex-r',
        displayName: 'ALEX R',
        companies: ['Frontal Slayer', 'NDXBOOK'],
        sharedInterests: ['health', 'wellness', 'luxury', 'hair'] as KnowledgeInterestId[],
        crossBrandBehavior: 'FS customer · ndxbook health reader · Lounge TV engaged',
        opportunities: ['Wellness content bridge', 'Lounge TV × ndxbook crossover', 'Portfolio membership bundle'],
        portfolioLifetimeValue: '$2,080 combined · premium + affiliate potential',
      },
    ],
    creatorOpportunities: [
      { id: 'co-1', readerId: 'reader-jordan-t', type: 'creator', label: 'TRUTH TUESDAY · GUEST HOST', fitScore: 91, rationale: 'Health expertise · TikTok reach · advocate behavior · brand alignment' },
      { id: 'co-2', readerId: 'reader-jordan-t', type: 'ambassador', label: 'NDXBOOK AMBASSADOR PROGRAM', fitScore: 88, rationale: '5 referrals · 94% trust · sharing behavior' },
      { id: 'co-3', readerId: 'reader-jordan-t', type: 'affiliate', label: 'HEALTH AFFILIATE TIER A', fitScore: 85, rationale: '$240 attributed · fact-forward content fit' },
      { id: 'co-4', readerId: 'reader-maya-k', type: 'collaborator', label: 'MONEY MONDAY · COMMUNITY CONTRIBUTOR', fitScore: 72, rationale: 'Finance interest rising · trust building · not yet advocate' },
    ],
    simulations: [
      { id: 'sim-1', campaignId: 'camp-money-monday-mar', campaignLabel: 'MONEY MONDAY · MARCH CYCLE', readerResponse: '+820 new readers · 74% engage rate', communityGrowth: 'Finance Readers +12%', engagement: '+18% CTR on stat overlays', retention: '+12% returning readers', advocacy: '3 new advocate signals', trust: '+4% avg trust score', relationshipImpact: 'Strong · aligns with returning reader strategy', confidencePct: 86 },
      { id: 'sim-2', campaignId: 'camp-newsletter-q3', campaignLabel: 'NEWSLETTER LAUNCH · Q3', readerResponse: '4K signups projected', communityGrowth: 'Early Adopters +28%', engagement: '12% open rate · 4.2 min read', retention: '+15% retention lift', advocacy: 'Membership conversion 8%', trust: 'Owned relationship strengthens trust', relationshipImpact: 'High long-term · reduces platform dependency', confidencePct: 78 },
    ],
    graphNodes: [
      { id: 'gn-reader-maya', type: 'reader', label: 'MAYA K', size: 78, connections: ['gn-int-finance', 'gn-comm-finance', 'gn-camp-mm'] },
      { id: 'gn-reader-jordan', type: 'reader', label: 'JORDAN T', size: 91, connections: ['gn-int-health', 'gn-comm-health', 'gn-creator-1'] },
      { id: 'gn-int-finance', type: 'interest', label: 'FINANCE', size: 88, connections: ['gn-reader-maya', 'gn-reader-sam', 'gn-comm-finance'] },
      { id: 'gn-int-health', type: 'interest', label: 'HEALTH', size: 92, connections: ['gn-reader-jordan', 'gn-comm-health'] },
      { id: 'gn-comm-finance', type: 'community', label: 'FINANCE READERS', size: 1240, connections: ['gn-int-finance', 'gn-reader-maya'] },
      { id: 'gn-comm-health', type: 'community', label: 'HEALTH READERS', size: 890, connections: ['gn-int-health', 'gn-reader-jordan'] },
      { id: 'gn-camp-mm', type: 'campaign', label: 'MONEY MONDAY', size: 84, connections: ['gn-reader-maya'] },
      { id: 'gn-company-ndx', type: 'company', label: 'NDXBOOK', size: 100, connections: ['gn-comm-finance', 'gn-comm-health'] },
    ],
    privacyControls: [
      { id: 'pc-1', label: 'BEHAVIOR TRACKING', description: 'Reading · watch · purchase habits · requires consent', enabled: true, founderControlled: true },
      { id: 'pc-2', label: 'CROSS-COMPANY LINKING', description: 'Portfolio reader profiles across companies · opt-in only', enabled: true, founderControlled: true },
      { id: 'pc-3', label: 'CREATOR MARKETPLACE SHARING', description: 'Share reader fit scores with creator marketplace · anonymized by default', enabled: false, founderControlled: true },
      { id: 'pc-4', label: 'RELATIONSHIP RECOMMENDATIONS', description: 'AI-generated engagement strategies · uses aggregated signals only', enabled: true, founderControlled: true },
      { id: 'pc-5', label: 'THIRD-PARTY CRM SYNC', description: 'Export relationship data to external CRM · founder approval required', enabled: false, founderControlled: true },
    ],
    selectedReaderId: 'reader-maya-k',
  };
}

export function bootstrapReaderGraphPlatform(): void {
  bootstrapReaderGraphStore(buildReaderGraphSeed());
}
