import { aioPaths } from '../utils/paths';
import type { ServiceJourneyDef } from './journeyTypes';

/** Canonical Start Your Business journey — BUILD → ROLL */
export const startBusinessJourneyDef: ServiceJourneyDef = {
  id: 'journey-start-business',
  slug: 'start-your-business',
  name: 'Start Your Business',
  description: 'From formation through your first load — build, authorize, protect, register, activate, and roll.',
  steps: [
    {
      id: 'build',
      order: 1,
      number: '01',
      title: 'BUILD',
      shortTitle: 'Form Your Business',
      description: 'Form your LLC or corporation and establish your business entity.',
      route: `${aioPaths.startYourBusiness}/build`,
      serviceSlug: 'business-formation',
      roadReadyKeys: ['business_formation', 'business_structure', 'ein_status'],
      weight: 1,
    },
    {
      id: 'authorize',
      order: 2,
      number: '02',
      title: 'AUTHORIZE',
      shortTitle: 'Get Your Authority',
      description: 'USDOT, operating authority, and other applicable federal registrations.',
      route: aioPaths.serviceSlug('operating-authority-assistance'),
      serviceSlug: 'operating-authority-assistance',
      roadReadyKeys: ['usdot', 'operating_authority'],
      weight: 1,
    },
    {
      id: 'protect',
      order: 3,
      number: '03',
      title: 'PROTECT',
      shortTitle: 'Insurance Coverage',
      description: 'Commercial trucking insurance intake, quotes, and partner handoff where configured.',
      route: aioPaths.insurance,
      serviceSlug: 'insurance',
      roadReadyKeys: ['commercial_insurance'],
      weight: 1,
    },
    {
      id: 'register',
      order: 4,
      number: '04',
      title: 'REGISTER',
      shortTitle: 'Tags, IFTA, IRP & Permits',
      description: 'Vehicle registration, apportioned plates, fuel tax, and road-operating registrations.',
      route: `${aioPaths.startYourBusiness}/register`,
      roadReadyKeys: ['irp', 'ifta', 'ucr', 'vehicle_registration', 'commercial_tags', 'highway_tax', 'hvut', 'title_tags'],
      weight: 1,
      subSteps: [
        { id: 'irp', label: 'IRP / Apportioned Registration', description: 'Interstate apportioned plates where applicable.', roadReadyKeys: ['irp'], serviceSlug: 'irp-registration', route: aioPaths.serviceSlug('irp-registration') },
        { id: 'ifta', label: 'IFTA / Fuel Tax', description: 'Fuel tax reporting account where applicable.', roadReadyKeys: ['ifta'], serviceSlug: 'ifta-setup', route: aioPaths.serviceSlug('ifta-setup') },
        { id: 'ucr', label: 'UCR', description: 'Unified Carrier Registration where applicable.', roadReadyKeys: ['ucr'], serviceSlug: 'ucr-registration', route: aioPaths.serviceSlug('ucr-registration') },
        { id: 'tags', label: 'Tags / Plates', description: 'Commercial vehicle tags and registration.', roadReadyKeys: ['vehicle_registration', 'commercial_tags'], serviceSlug: 'vehicle-registration', route: aioPaths.serviceSlug('vehicle-registration') },
        { id: 'hvut', label: 'HVUT / Form 2290', description: 'Heavy vehicle use tax where applicable.', roadReadyKeys: ['highway_tax', 'hvut'], serviceSlug: 'hvut-form-2290', route: aioPaths.serviceSlug('hvut-form-2290'), applicability: 'optional' },
        { id: 'title', label: 'Title / Tag Services', description: 'Title and tag assistance.', roadReadyKeys: ['title_tags'], serviceSlug: 'tag-services', route: aioPaths.serviceSlug('tag-services'), applicability: 'optional' },
      ],
    },
    {
      id: 'activate',
      order: 5,
      number: '05',
      title: 'ACTIVATE',
      shortTitle: 'Compliance & Filings',
      description: 'Remaining compliance filings and operational requirements before you roll.',
      route: `${aioPaths.startYourBusiness}/activate`,
      roadReadyKeys: ['boc3', 'mcs150', 'drug_alcohol_consortium', 'clearinghouse', 'dq_files', 'eld', 'new_entrant_audit'],
      weight: 1,
      subSteps: [
        { id: 'boc3', label: 'BOC-3', description: 'Process agent filing.', roadReadyKeys: ['boc3'], serviceSlug: 'boc-3-filing', route: aioPaths.serviceSlug('boc-3-filing') },
        { id: 'mcs150', label: 'MCS-150', description: 'Biennial carrier update.', roadReadyKeys: ['mcs150'], serviceSlug: 'mcs-150-biennial-update', route: aioPaths.serviceSlug('mcs-150-biennial-update') },
        { id: 'drug_alcohol', label: 'Drug & Alcohol Consortium', description: 'Consortium enrollment where applicable.', roadReadyKeys: ['drug_alcohol_consortium'], serviceSlug: 'drug-alcohol-consortium', route: aioPaths.serviceSlug('drug-alcohol-consortium'), applicability: 'optional' },
        { id: 'clearinghouse', label: 'FMCSA Clearinghouse', description: 'Clearinghouse query compliance.', roadReadyKeys: ['clearinghouse'], serviceSlug: 'fmcsa-clearinghouse-assistance', route: aioPaths.serviceSlug('fmcsa-clearinghouse-assistance'), applicability: 'optional' },
        { id: 'dq_files', label: 'DQ Files', description: 'Driver qualification file setup.', roadReadyKeys: ['dq_files'], serviceSlug: 'driver-qualification-files', route: aioPaths.serviceSlug('driver-qualification-files'), applicability: 'optional' },
        { id: 'eld', label: 'ELD', description: 'Electronic logging device services.', roadReadyKeys: ['eld'], serviceSlug: 'eld-services', route: aioPaths.serviceSlug('eld-services'), applicability: 'optional' },
      ],
    },
    {
      id: 'roll',
      order: 6,
      number: '06',
      title: 'ROLL',
      shortTitle: 'Operate & Grow',
      description: 'Transition from startup to operations — dispatch, freight, factoring, and growth services.',
      route: `${aioPaths.startYourBusiness}/roll`,
      roadReadyKeys: [],
      optional: true,
      weight: 0,
    },
  ],
};
