import { bootstrapArrivalExperienceStore } from './store';
import type { ArrivalExperienceStore } from './types';

export function buildArrivalExperienceSeed(): Partial<ArrivalExperienceStore> {
  return {
    companyName: 'NDXBOOK',
    activeWorkspaceId: 'ndxbook',
    arrivalPhase: 'home',
    dashboard: {
      summary:
        'ARRIVAL EXPERIENCE V1.0 — NDXBOOK headquarters live · 6 executives introduced · tour complete · welcome home.',
      sequenceProgressPct: 100,
      executivesIntroduced: 6,
      tourStopsComplete: 8,
      arrivalComplete: true,
      headquartersLive: true,
    },
    arrivalSequence: [
      { id: 'as-1', phase: 'Transition', description: 'Fade away from setup · onboarding dissolves into arrival', atmosphere: 'Calm · anticipatory', order: 1 },
      { id: 'as-2', phase: 'Headquarters reveal', description: 'Campus slowly comes into view · ambient lighting activates', atmosphere: 'Cinematic · premium', order: 2 },
      { id: 'as-3', phase: 'Campus awakening', description: 'Subtle activity throughout the building · executives prepare', atmosphere: 'Hopeful · alive', order: 3 },
      { id: 'as-4', phase: 'Chief of Staff welcome', description: 'Personal greeting · warm · confident · never scripted', atmosphere: 'Personal · welcoming', order: 4 },
      { id: 'as-5', phase: 'Executive introductions', description: 'Meet each executive in their workspace · not profile cards', atmosphere: 'Natural · purposeful', order: 5 },
      { id: 'as-6', phase: 'Headquarters tour', description: 'CoS guides through campus · council · intelligence · genome · KG', atmosphere: 'Exploration · living HQ', order: 6 },
      { id: 'as-7', phase: 'Organizational reveal', description: 'Gradual reveal of genome · maturity · roadmap · strengths', atmosphere: 'Intentional · unhurried', order: 7 },
      { id: 'as-8', phase: 'First executive briefing', description: 'Organization\'s first briefing · where we stand · today\'s focus', atmosphere: 'Clear · grounded', order: 8 },
      { id: 'as-9', phase: 'Arrival memory', description: 'Preserve first day · maturity · team · vision for future generations', atmosphere: 'Institutional · enduring', order: 9 },
      { id: 'as-10', phase: 'Welcome home', description: 'Final message from Chief of Staff · new chapter begun', atmosphere: 'Quiet confidence · wonder', order: 10 },
    ],
    chiefOfStaffWelcome: {
      headline: 'Welcome to your headquarters.',
      message: [
        'We\'ve spent the last few minutes getting to know your organization.',
        'Your executive team has already begun preparing their first observations.',
        'Your headquarters has been prepared specifically for your organization.',
        'Whenever you\'re ready… I\'ll show you around.',
      ],
      tone: 'Warm · confident · personal · never scripted',
      closingNote: 'Not a confirmation screen — you have arrived. The organization is alive. The executive team is waiting.',
    },
    executiveIntroductions: [
      {
        id: 'ei-1',
        executive: 'Chief Brand Officer',
        workspace: 'Brand Studio',
        purpose: 'Protect and evolve stat-forward editorial identity',
        responsibilities: 'Brand governance · Writing DNA alignment · editorial integrity',
        leadershipPhilosophy: 'Trust before scale · identity preserved across every touchpoint',
        executiveCompass: 'Does this strengthen or dilute who we are?',
        founderSupport: 'Guards brand while you focus on vision and creation',
      },
      {
        id: 'ei-2',
        executive: 'Chief Experience Officer',
        workspace: 'Experience Studio',
        purpose: 'Reader journey excellence · belonging over volume',
        responsibilities: 'Onboarding · reader graph · spotlight program · CX governance',
        leadershipPhilosophy: 'Relationships before transactions · every touchpoint earns trust',
        executiveCompass: 'Does this make readers feel understood?',
        founderSupport: 'Leads onboarding simplification sprint · clears trust gates',
      },
      {
        id: 'ei-3',
        executive: 'Chief Digital Officer',
        workspace: 'Digital Studio',
        purpose: 'Digital presence · publishing · distribution architecture',
        responsibilities: 'NDXBOOK · distribution engine · digital campaigns · content systems',
        leadershipPhilosophy: 'Editorial integrity in every digital channel',
        executiveCompass: 'Does this honor our stat-forward promise?',
        founderSupport: 'Orchestrates digital growth within governance boundaries',
      },
      {
        id: 'ei-4',
        executive: 'Chief Technology Officer',
        workspace: 'Technology Operations Center',
        purpose: 'Engineering excellence · infrastructure · auth · live preview pipeline',
        responsibilities: 'Vite/React · Supabase · Vercel · Fal · auth refactor critical path',
        leadershipPhilosophy: 'Build for decades · master craftsman engineering',
        executiveCompass: 'Will this scale with institutional wisdom?',
        founderSupport: 'Owns technical debt resolution · enables enterprise readiness',
      },
      {
        id: 'ei-5',
        executive: 'Chief Growth Officer',
        workspace: 'Growth Laboratory',
        purpose: 'Relationship-driven growth · trust-before-scale GTM',
        responsibilities: 'Reader advocacy · creator marketplace · growth experiments · GTM gates',
        leadershipPhilosophy: 'Sustainable growth through belonging · never vanity metrics',
        executiveCompass: 'Are we ready · or rushing ahead of maturity?',
        founderSupport: 'Enforces trust gates · prevents premature GTM pressure',
      },
      {
        id: 'ei-6',
        executive: 'Chief of Staff',
        workspace: 'Executive Office',
        purpose: 'Founder\'s primary executive · coordinates all departments',
        responsibilities: 'Briefings · routing · council coordination · arrival · founder walk',
        leadershipPhilosophy: 'Invisible stewardship · founder visibility preserved',
        executiveCompass: 'What requires founder judgment · what can be delegated?',
        founderSupport: 'Your constant partner · guides every arrival and every day',
      },
    ],
    headquartersTour: [
      { id: 'ht-1', stop: 'The Campus', introduction: 'Creative headquarters — editorial atelier · newsroom energy · innovation loft. Built for SCALE maturity, evolving toward executive HQ.', order: 1 },
      { id: 'ht-2', stop: 'Architect Studio', introduction: 'Brand · Experience · Digital · Growth architects — your company architecture reflects stat-forward editorial identity.', order: 2 },
      { id: 'ht-3', stop: 'Executive Council Chamber', introduction: 'Full council operational · healthy disagreement · cross-functional synthesis · founder final authority preserved.', order: 3 },
      { id: 'ht-4', stop: 'Organizational Intelligence Center', introduction: 'Continuous evaluation · mode detection · maturity signals · organizational health at a glance.', order: 4 },
      { id: 'ht-5', stop: 'Knowledge Graph', introduction: 'Institutional connections mapped — executives · workflows · governance · maturity · campus · relationships.', order: 5 },
      { id: 'ht-6', stop: 'Company Genome', introduction: 'Stat-forward editorial DNA · Writing DNA · trust-before-scale · relationship-driven growth — your living identity.', order: 6 },
      { id: 'ht-7', stop: 'Future Expansion Areas', introduction: 'Innovation loft · reader relationship center · legacy hall preview — the future you always hoped to build.', order: 7 },
      { id: 'ht-8', stop: 'Recommended Next Milestone', introduction: 'Complete onboarding gate · advance to executive headquarters campus · enterprise readiness when earned.', order: 8 },
    ],
    organizationalReveal: [
      { id: 'or-1', element: 'Company Genome', reveal: 'Stat-forward editorial DNA · trust-before-scale · relationship-driven reader platform', timing: 'early' },
      { id: 'or-2', element: 'Knowledge Graph', reveal: 'Full organizational map — executives · systems · governance · maturity interconnected', timing: 'early' },
      { id: 'or-3', element: 'Organizational Maturity', reveal: 'SCALE stage · 74% maturity · enterprise readiness 68% · earned not unlocked', timing: 'mid' },
      { id: 'or-4', element: 'Executive Recommendations', reveal: 'Full C-suite active · Executive Council · all four architects ready', timing: 'mid' },
      { id: 'or-5', element: 'Growth Roadmap', reveal: 'Enterprise readiness · executive HQ campus · 100K engaged readers · trust gates', timing: 'mid' },
      { id: 'or-6', element: 'Current Strengths', reveal: 'Editorial identity · institutional knowledge · executive systems · governance culture', timing: 'late' },
      { id: 'or-7', element: 'Future Opportunities', reveal: 'Onboarding simplification · auth infrastructure · creator marketplace quality gates', timing: 'late' },
    ],
    environmentalStorytelling: [
      { id: 'es-1', signal: 'Industry', expression: 'Media · publishing · reader platform architecture', atmosphere: 'Editorial atelier · newsroom energy throughout' },
      { id: 'es-2', signal: 'Brand personality', expression: 'Stat-forward aesthetic · trust-first spaces · Writing DNA visible in materials', atmosphere: 'Thoughtful · precise · never generic' },
      { id: 'es-3', signal: 'Organizational maturity', expression: 'Creative HQ progressing to executive headquarters · SCALE stage reflected in space allocation', atmosphere: 'Growing into leadership · earned expansion' },
      { id: 'es-4', signal: 'Future ambition', expression: 'Innovation loft · legacy hall preview · reader relationship center on horizon', atmosphere: 'Hopeful · ambitious · grounded in values' },
      { id: 'es-5', signal: 'Company identity', expression: 'Master craftsman refinement · belonging over volume · institutional wisdom preserved', atmosphere: 'Immediately feels like it belongs to NDXBOOK' },
      { id: 'es-6', signal: 'Ambient activity', expression: 'Subtle movement · executives preparing · campus coming alive · lighting warm', atmosphere: 'Calm · cinematic · premium · alive' },
    ],
    firstExecutiveBriefing: {
      organizationalMaturity: 'SCALE stage · 74% maturity · enterprise readiness 68% · OAF Level 3 trusted execution',
      currentPriorities: [
        'Onboarding simplification sprint · CEO-led · Step 3 friction',
        'Auth refactor · CTO critical path · enterprise readiness blocker',
        'Spotlight program scale · reader advocacy +15% pilot momentum',
        'Trust-before-scale GTM gates · no premature paid acquisition',
      ],
      recommendedExecutives: ['Chief of Staff', 'Chief Brand Officer', 'Chief Experience Officer', 'Chief Digital Officer', 'Chief Technology Officer', 'Chief Growth Officer'],
      recommendedArchitects: ['Brand Architect', 'Experience Architect', 'Digital Architect', 'Growth Architect'],
      immediateOpportunities: [
        'Connect analytics · CRM · email for deeper organizational confidence',
        'Accelerate institutional knowledge capture via OSI',
        'Deepen reader graph · spotlight program expansion',
      ],
      organizationalStrengths: [
        'Stat-forward editorial identity · Writing DNA quality gates',
        'Full executive stack · constitutional governance active',
        'Institutional learning · motherboard · Memory Bible compounding',
        'Relationship-driven reader platform · differentiated positioning',
      ],
      nextMilestone: 'Complete onboarding gate · advance to executive headquarters campus · enterprise readiness when score > 85',
      todaysFocus: 'Take in your headquarters · review first executive observations · begin onboarding simplification sprint when ready',
    },
    arrivalMemory: {
      arrivalDate: '2026-07-05',
      organizationFirstDay: 'NDXBOOK Day One in Studio OS — organizational intelligence born',
      initialMaturity: 'SCALE · 74% · enterprise readiness 68%',
      firstExecutiveTeam: ['Chief of Staff', 'Chief Brand Officer', 'Chief Experience Officer', 'Chief Digital Officer', 'Chief Technology Officer', 'Chief Growth Officer'],
      firstRoadmap: 'Enterprise readiness · executive HQ campus · 100K engaged readers · trust gates cleared',
      foundersFirstVision: 'Build lasting reader relationships through stat-forward editorial — trust before scale · institutional wisdom preserved',
      preservedNote: 'Future generations can revisit this moment — the day NDXBOOK first walked into its headquarters.',
    },
    finalMessage: {
      headline: 'Welcome home.',
      message: 'Whenever you\'re ready… let\'s build something that outlives us.',
    },
    futureOpportunities: [
      'Immersive ambient campus visualization as headquarters evolves',
      'Arrival replay for organizational anniversaries and legacy milestones',
      'Portfolio holding-company arrival ceremonies across multiple headquarters',
    ],
  };
}

export function bootstrapArrivalExperiencePlatform(): void {
  bootstrapArrivalExperienceStore(buildArrivalExperienceSeed());
}
