import { aioAppConfig } from '../config/appConfig';
import { layoutPreviewPaths } from './layoutPreviewPaths';

const BASE = aioAppConfig.routes.base;

export const aioPaths = {
  home: BASE || '/',
  portal: `${BASE}/portal`,
  portalBusiness: `${BASE}/portal/business`,
  portalBusinessSummary: `${BASE}/portal/business/summary`,
  portalOperations: `${BASE}/portal/operations`,
  portalMoney: `${BASE}/portal/money`,
  portalDocuments: `${BASE}/portal/documents`,
  portalCommunication: `${BASE}/portal/communication`,
  portalMessages: `${BASE}/portal/messages`,
  portalMessage: (id: string) => `${BASE}/portal/messages/${id}`,
  portalAppointments: `${BASE}/portal/appointments`,
  portalAppointment: (id: string) => `${BASE}/portal/appointments/${id}`,
  schedule: `${BASE}/schedule`,
  portalRequestsCenter: `${BASE}/portal/requests`,
  portalServicesCenter: `${BASE}/portal/services`,
  portalActivity: `${BASE}/portal/activity`,
  portalTeam: `${BASE}/portal/team`,
  portalSearch: `${BASE}/portal/search`,
  services: `${BASE}/services`,
  servicesFind: `${BASE}/services/find`,
  permitting: `${BASE}/services/permitting`,
  businessFormation: `${BASE}/services/business-formation`,
  insurance: `${BASE}/services/insurance`,
  dispatching: `${BASE}/services/dispatching`,
  factoring: `${BASE}/services/factoring`,
  bookkeeping: `${BASE}/services/bookkeeping`,
  fleetCare: `${BASE}/services/fleetcare`,
  fleetCarePlans: `${BASE}/services/fleetcare/plans`,
  fleetCareProviderJoin: `${BASE}/fleetcare/providers/join`,
  fleetCareProviderApply: `${BASE}/fleetcare/providers/apply`,
  fleetCareProviderPortal: `${BASE}/provider/fleetcare`,
  fleetCareProviderLeads: `${BASE}/provider/fleetcare/leads`,
  fleetCareProviderLead: (ticketId: string) => `${BASE}/provider/fleetcare/leads/${ticketId}`,
  fleetCareProviderJobs: `${BASE}/provider/fleetcare/jobs`,
  fleetCareProviderJob: (ticketId: string) => `${BASE}/provider/fleetcare/jobs/${ticketId}`,
  fleetCareProviderEarnings: `${BASE}/provider/fleetcare/earnings`,
  fleetCareProviderCompliance: `${BASE}/provider/fleetcare/compliance`,
  fleetCareProviderProfile: `${BASE}/provider/fleetcare/profile`,
  portalFleetCare: `${BASE}/portal/fleetcare`,
  portalFleetCareRequest: `${BASE}/portal/fleetcare/request`,
  portalFleetCareTicket: (ticketId: string) => `${BASE}/portal/fleetcare/tickets/${ticketId}`,
  portalFleetCareVehicleHistory: (vehicleId: string) => `${BASE}/portal/fleetcare/vehicles/${vehicleId}/history`,
  driverLink: `${BASE}/services/driverlink`,
  driverLinkSignup: `${BASE}/driverlink/signup`,
  driverLinkDriverPortal: `${BASE}/driver/driverlink`,
  driverLinkDriverProfile: `${BASE}/driver/driverlink/profile`,
  driverLinkDriverCredentials: `${BASE}/driver/driverlink/credentials`,
  driverLinkDriverFindWork: `${BASE}/driver/driverlink/find-work`,
  driverLinkDriverMatches: `${BASE}/driver/driverlink/matches`,
  driverLinkDriverApplications: `${BASE}/driver/driverlink/applications`,
  driverLinkDriverOpportunity: (id: string) => `${BASE}/driver/driverlink/opportunities/${id}`,
  portalDriverLink: `${BASE}/portal/driverlink`,
  portalDriverLinkOpportunities: `${BASE}/portal/driverlink/opportunities`,
  portalDriverLinkOpportunity: (id: string) => `${BASE}/portal/driverlink/opportunities/${id}`,
  portalDriverLinkCreateJob: `${BASE}/portal/driverlink/opportunities/new`,
  portalDriverLinkCandidates: `${BASE}/portal/driverlink/candidates`,
  officeDriverLink: `${BASE}/office/driverlink`,
  officeDriverLinkDrivers: `${BASE}/office/driverlink/drivers`,
  officeDriverLinkJobs: `${BASE}/office/driverlink/jobs`,
  officeDriverLinkApplications: `${BASE}/office/driverlink/applications`,
  officeFleetCare: `${BASE}/office/fleetcare`,
  officeFleetCareTickets: `${BASE}/office/fleetcare/tickets`,
  officeFleetCareProviders: `${BASE}/office/fleetcare/providers`,
  officeFleetCareReferrals: `${BASE}/office/fleetcare/referrals`,
  bookkeepingAssessment: `${BASE}/services/bookkeeping/assessment`,
  bookkeepingRecommendation: `${BASE}/services/bookkeeping/recommendation`,
  brokerage: `${BASE}/services/brokerage`,
  portalFactoring: `${BASE}/portal/factoring`,
  portalFactoringApplication: `${BASE}/portal/factoring/application`,
  portalFactoringReady: `${BASE}/portal/factoring/ready`,
  portalFactoringSubmission: (id: string) => `${BASE}/portal/factoring/submissions/${id}`,
  portalFactoringHistory: `${BASE}/portal/factoring/history`,
  portalFreightInvoice: (id: string) => `${BASE}/portal/factoring/invoices/${id}`,
  portalBookkeeping: `${BASE}/portal/bookkeeping`,
  officeFactoring: `${BASE}/office/factoring`,
  officeFactoringSubmissions: `${BASE}/office/factoring/submissions`,
  officeFactoringSubmission: (id: string) => `${BASE}/office/factoring/submissions/${id}`,
  officeFactoringClients: `${BASE}/office/factoring/clients`,
  officeFactoringClient: (id: string) => `${BASE}/office/factoring/clients/${id}`,
  officeFactoringProviders: `${BASE}/office/factoring/providers`,
  officeBookkeeping: `${BASE}/office/bookkeeping`,
  officeBookkeepingAutopilot: `${BASE}/office/bookkeeping/autopilot`,
  officeBookkeepingSubscriptions: `${BASE}/office/bookkeeping/subscriptions`,
  officeBookkeepingRescue: `${BASE}/office/bookkeeping/books-rescue`,
  officeBookkeepingLeads: `${BASE}/office/bookkeeping/leads`,
  shipper: `${BASE}/shipper`,
  shipperOnboarding: `${BASE}/shipper/onboarding`,
  shipperShipments: `${BASE}/shipper/shipments`,
  shipperShipmentNew: `${BASE}/shipper/shipments/new`,
  shipperShipWithAio: `${BASE}/shipper/ship-with-aio`,
  shipperShipWithAioEdit: (id: string) => `${BASE}/shipper/ship-with-aio/${id}`,
  shipperRequests: `${BASE}/shipper/requests`,
  shipperRequest: (id: string) => `${BASE}/shipper/requests/${id}`,
  shipperShipment: (id: string) => `${BASE}/shipper/shipments/${id}`,
  shipperQuotes: `${BASE}/shipper/quotes`,
  shipperQuote: (id: string) => `${BASE}/shipper/quotes/${id}`,
  shipperBilling: `${BASE}/shipper/billing`,
  shipperInvoice: (id: string) => `${BASE}/shipper/billing/${id}`,
  portalBrokerage: `${BASE}/portal/brokerage`,
  portalBrokerageOffers: `${BASE}/portal/brokerage/offers`,
  portalBrokerageLoad: (id: string) => `${BASE}/portal/brokerage/loads/${id}`,
  portalBrokeragePayments: `${BASE}/portal/brokerage/payments`,
  officeBrokerageReadiness: `${BASE}/office/brokerage/readiness`,
  officeBrokerageShippers: `${BASE}/office/brokerage/shippers`,
  officeBrokerageShipper: (id: string) => `${BASE}/office/brokerage/shippers/${id}`,
  officeBrokerageRequests: `${BASE}/office/brokerage/requests`,
  officeBrokerageRequest: (id: string) => `${BASE}/office/brokerage/requests/${id}`,
  officeBrokerageLoads: `${BASE}/office/brokerage/loads`,
  officeBrokerageLoad: (id: string) => `${BASE}/office/brokerage/loads/${id}`,
  officeBrokerageCoverage: `${BASE}/office/brokerage/coverage`,
  officeBrokerageCarriers: `${BASE}/office/brokerage/carriers`,
  officeBrokerageCarrier: (id: string) => `${BASE}/office/brokerage/carriers/${id}`,
  officeBrokerageFinance: `${BASE}/office/brokerage/finance`,
  about: `${BASE}/about`,
  contact: `${BASE}/contact`,
  requestCallback: `${BASE}/request-callback`,
  publicQuote: (token: string) => `${BASE}/quote/${token}`,
  roadmap: `${BASE}/roadmap`,
  roadReadyPublic: `${BASE}/road-ready`,
  startYourBusiness: `${BASE}/start-your-business`,
  clientPortalInfo: `${BASE}/client-portal`,
  getStarted: `${BASE}/get-started`,
  getStartedDesktop: layoutPreviewPaths.desktopGetStarted,
  getStartedMobile: layoutPreviewPaths.mobileGetStarted,
  desktopRoot: layoutPreviewPaths.desktopRoot,
  mobileRoot: layoutPreviewPaths.mobileRoot,
  getStartedForService: (serviceSlug: string) => `${BASE}/get-started?service=${encodeURIComponent(serviceSlug)}`,
  roadmapResults: `${BASE}/roadmap/results`,
  servicePlan: `${BASE}/service-plan`,
  requestSubmit: `${BASE}/request/submit`,
  industries: `${BASE}/about#industries`,
  resources: `${BASE}/about#resources`,
  serviceSlug: (slug: string) => `${BASE}/services/${slug}`,
  portalRequest: (requestId: string) => `${BASE}/portal/requests/${requestId}`,
  requestConfirmation: (requestId: string) => `${BASE}/request/confirmation/${requestId}`,
  portalOnboarding: `${BASE}/portal/onboarding`,
  roadReady: `${BASE}/portal/road-ready`,
  portalFleet: `${BASE}/portal/fleet`,
  portalVehicle: (id: string) => `${BASE}/portal/fleet/vehicles/${id}`,
  portalVault: `${BASE}/portal/vault`,
  portalVaultDocument: (id: string) => `${BASE}/portal/vault/${id}`,
  portalCalendar: `${BASE}/portal/calendar`,
  portalRenewals: `${BASE}/portal/renewals`,
  portalNotifications: `${BASE}/portal/notifications`,
  portalNotificationSettings: `${BASE}/portal/settings/notifications`,
  portalSettings: `${BASE}/portal/settings`,
  portalQuotes: `${BASE}/portal/quotes`,
  portalQuote: (id: string) => `${BASE}/portal/quotes/${id}`,
  portalBilling: `${BASE}/portal/billing`,
  portalInvoice: (id: string) => `${BASE}/portal/billing/invoices/${id}`,
  portalPay: (id: string) => `${BASE}/portal/billing/pay/${id}`,
  portalReceipt: (id: string) => `${BASE}/portal/billing/receipts/${id}`,
  portalDispatch: `${BASE}/portal/dispatch`,
  portalDispatchOnboarding: `${BASE}/portal/dispatch/onboarding`,
  portalDispatchLoads: `${BASE}/portal/dispatch/loads`,
  portalDispatchLoad: (id: string) => `${BASE}/portal/dispatch/loads/${id}`,
  portalDispatchHistory: `${BASE}/portal/dispatch/history`,
  portalLoadBoard: `${BASE}/portal/load-board`,
  portalLoadBoardResults: `${BASE}/portal/load-board/results`,
  portalLoadBoardLoad: (id: string) => `${BASE}/portal/load-board/loads/${id}`,
  portalLoadBoardMyLoads: `${BASE}/portal/load-board/my-loads`,
  portalLoadBoardFleet: `${BASE}/portal/load-board/fleet`,
  portalLoadBoardMap: `${BASE}/portal/load-board/map`,
  portalLoadBoardSaved: `${BASE}/portal/load-board/saved`,
  portalInsurance: `${BASE}/portal/insurance`,
  portalInsuranceRequest: `${BASE}/portal/insurance/request`,
  portalInsuranceRequestDetail: (id: string) => `${BASE}/portal/insurance/requests/${id}`,
  portalInsurancePolicy: (id: string) => `${BASE}/portal/insurance/policies/${id}`,
  portalInsuranceCertificates: `${BASE}/portal/insurance/certificates`,
  portalInsuranceCertificateNew: `${BASE}/portal/insurance/certificates/new`,
  portalInsuranceRenewals: `${BASE}/portal/insurance/renewals`,
  officeDispatch: `${BASE}/office/dispatch`,
  officeDispatchLoads: `${BASE}/office/dispatch/loads`,
  officeDispatchLoadNew: `${BASE}/office/dispatch/loads/new`,
  officeDispatchLoad: (id: string) => `${BASE}/office/dispatch/loads/${id}`,
  /** @deprecated use officeDispatchLoad */
  officeLoad: (id: string) => `${BASE}/office/dispatch/loads/${id}`,
  officeDispatchClients: `${BASE}/office/dispatch/clients`,
  officeDispatchClient: (id: string) => `${BASE}/office/dispatch/clients/${id}`,
  officeDispatchBrokers: `${BASE}/office/dispatch/brokers`,
  officeQuotes: `${BASE}/office/quotes`,
  officeQuote: (id: string) => `${BASE}/office/quotes/${id}`,
  officeBilling: `${BASE}/office/billing`,
  officeInvoice: (id: string) => `${BASE}/office/invoices/${id}`,
  officePricingSettings: `${BASE}/office/settings/pricing`,
  officeRenewals: `${BASE}/office/renewals`,
  office: `${BASE}/office`,
  officeClients: `${BASE}/office/clients`,
  officeClient: (id: string) => `${BASE}/office/clients/${id}`,
  officeRequests: `${BASE}/office/requests`,
  officeRequest: (id: string) => `${BASE}/office/requests/${id}`,
  officeTasks: `${BASE}/office/tasks`,
  officeDeadlines: `${BASE}/office/deadlines`,
  officeDocuments: `${BASE}/office/documents`,
  officeDocumentVault: `${BASE}/office/documents/vault`,
  officeClientDocuments: (clientId: string) => `${BASE}/office/clients/${clientId}/documents`,
  officeVaultDocument: (documentId: string) => `${BASE}/office/documents/vault/${documentId}`,
  officeArchiveMigration: `${BASE}/office/archive-migration`,
  officeArchiveMigrationDigitize: `${BASE}/office/archive-migration/digitize`,
  officeArchiveMigrationBatch: (batchId: string) => `${BASE}/office/archive-migration/batches/${batchId}`,
  officeMessages: `${BASE}/office/messages`,
  officePermitting: `${BASE}/office/permitting`,
  officeFormation: `${BASE}/office/business-formation`,
  officeInsurance: `${BASE}/office/insurance`,
  officeInsuranceRequests: `${BASE}/office/insurance/requests`,
  officeInsuranceRequest: (id: string) => `${BASE}/office/insurance/requests/${id}`,
  officeInsurancePolicies: `${BASE}/office/insurance/policies`,
  officeInsurancePartners: `${BASE}/office/insurance/partners`,
  officeInsuranceCertificates: `${BASE}/office/insurance/certificates`,
  officeInsuranceRenewals: `${BASE}/office/insurance/renewals`,
  officeInsuranceReadiness: `${BASE}/office/insurance/readiness`,
  officeBrokerage: `${BASE}/office/brokerage`,
  officeShipment: (id: string) => `${BASE}/office/brokerage/shipments/${id}`,
  officeInvoices: `${BASE}/office/invoices`,
  officePayments: `${BASE}/office/payments`,
  officeTeam: `${BASE}/office/team`,
  officeReports: `${BASE}/office/reports`,
  officeManagement: `${BASE}/office/management`,
  officeManagementFinancial: `${BASE}/office/management/financial`,
  officeManagementSales: `${BASE}/office/management/sales`,
  officeManagementServices: `${BASE}/office/management/services`,
  officeManagementCustomers: `${BASE}/office/management/customers`,
  officeManagementDispatch: `${BASE}/office/management/dispatch`,
  officeManagementBrokerage: `${BASE}/office/management/brokerage`,
  officeManagementFactoring: `${BASE}/office/management/factoring`,
  officeManagementInsurance: `${BASE}/office/management/insurance`,
  officeManagementCommunications: `${BASE}/office/management/communications`,
  officeManagementTeam: `${BASE}/office/management/team`,
  officeManagementDeadlines: `${BASE}/office/management/deadlines`,
  officeManagementDataQuality: `${BASE}/office/management/data-quality`,
  officeManagementSettings: `${BASE}/office/settings/management`,
  officeManagementLaunch: `${BASE}/office/management/launch`,
  officeManagementLaunchServices: `${BASE}/office/management/launch/services`,
  officeTraining: `${BASE}/office/training`,
  officeTrainingSops: `${BASE}/office/training/sops`,
  officeIntegrations: `${BASE}/office/integrations`,
  officeIntegrationsReconciliation: `${BASE}/office/integrations/reconciliation`,
  officeIntegrationsSettings: `${BASE}/office/settings/integrations`,
  officeIntegrationsProviders: `${BASE}/office/settings/integrations/providers`,
  officeIntegrationConnection: (id: string) => `${BASE}/office/settings/integrations/${id}`,
  officeIntegrationsLoadBoard: `${BASE}/office/integrations/load-board`,
  portalConnections: `${BASE}/portal/settings/connections`,
  portalSettingsSecurity: `${BASE}/portal/settings/security`,
  portalSettingsPrivacy: `${BASE}/portal/settings/privacy`,
  officeSecurity: `${BASE}/office/security`,
  officeSecurityAudit: `${BASE}/office/security/audit`,
  officeSecurityIncidents: `${BASE}/office/security/incidents`,
  officeSecurityProductionReadiness: `${BASE}/office/security/production-readiness`,
  officeDataHealth: `${BASE}/office/system/data`,
  officeDataMigration: `${BASE}/office/system/data/migration`,
  officeQa: `${BASE}/office/system/qa`,
  officeQaAccessibility: `${BASE}/office/system/qa/accessibility`,
  officeQaPerformance: `${BASE}/office/system/qa/performance`,
  officeQaDevices: `${BASE}/office/system/qa/devices`,
  officeQaBrowsers: `${BASE}/office/system/qa/browsers`,
  officeSystemProduction: `${BASE}/office/system/production`,
  officePrivacy: `${BASE}/office/privacy`,
  officeSettingsSecurity: `${BASE}/office/settings/security`,
  officeWork: `${BASE}/office/work`,
  officeQueues: `${BASE}/office/queues`,
  officeBusinessNameReview: `${BASE}/office/business-name-review`,
  officeApprovals: `${BASE}/office/approvals`,
  officeEscalations: `${BASE}/office/escalations`,
  officeServices: `${BASE}/office/services`,
  officeDocumentsReview: `${BASE}/office/documents/review`,
  officeInbox: `${BASE}/office/inbox`,
  officeCommunications: `${BASE}/office/communications`,
  officeCommunication: (id: string) => `${BASE}/office/communications/${id}`,
  officeCommunicationsOutbox: `${BASE}/office/communications/outbox`,
  officeAppointments: `${BASE}/office/appointments`,
  officeAppointment: (id: string) => `${BASE}/office/appointments/${id}`,
  officeCommunicationsSettings: `${BASE}/office/settings/communications`,
  officeAppointmentsSettings: `${BASE}/office/settings/appointments`,
  officeWorkload: `${BASE}/office/workload`,
  officeActivity: `${BASE}/office/activity`,
  officeAudit: `${BASE}/office/audit`,
  officeCrm: `${BASE}/office/crm`,
  officeCrmLeads: `${BASE}/office/crm/leads`,
  officeCrmLead: (id: string) => `${BASE}/office/crm/leads/${id}`,
  officeCrmPipeline: `${BASE}/office/crm/pipeline`,
  officeCrmOpportunity: (id: string) => `${BASE}/office/crm/opportunities/${id}`,
  officeCrmCalendar: `${BASE}/office/crm/calendar`,
  officeCrmReports: `${BASE}/office/crm/reports`,
  officeCrmSettings: `${BASE}/office/settings/crm`,
  officeWorkflows: `${BASE}/office/workflows`,
  officeWorkflow: (id: string) => `${BASE}/office/workflows/${id}`,
  officeWorkflowSettings: `${BASE}/office/settings/workflows`,
  officeWorkflowTemplate: (id: string) => `${BASE}/office/settings/workflows/${id}`,
  officeAutomationSettings: `${BASE}/office/settings/automations`,
  officeAutomationExceptions: `${BASE}/office/automation-exceptions`,
  officeWorkflowHealth: `${BASE}/office/workflow-health`,
  portalServiceTracker: (requestId: string) => `${BASE}/portal/services/${requestId}`,
  portalJourneyRoadmap: `${BASE}/portal/roadmap`,
  officeSearch: `${BASE}/office/search`,
  officeRoadReady: `${BASE}/office/road-ready`,
  officeClientRoadReady: (id: string) => `${BASE}/office/clients/${id}/road-ready`,
  login: `${BASE}/login`,
  signUp: `${BASE}/signup`,
  signUpLegacy: `${BASE}/sign-up`,
  forgotPassword: `${BASE}/forgot-password`,
  resetPassword: `${BASE}/reset-password`,
  verifyEmail: `${BASE}/verify-email`,
  onboarding: `${BASE}/onboarding`,
} as const;

export function aioServicePath(slug: string): string {
  return aioPaths.serviceSlug(slug);
}

export function aioGetStarted(goal?: string): string {
  return goal ? `${BASE}/get-started?goal=${goal}` : `${BASE}/get-started`;
}
