/** SITE 00 Admin Production OS — route constants (namespace avoids Studio OS /admin/studio/*). */
export const SITE00_ADMIN_ROUTES = {
  root: '/admin/site00',
  dashboard: '/admin/site00',
  studio: '/admin/site00/studio',
  studioQueue: '/admin/site00/studio/queue',
  studioRecipes: '/admin/site00/studio/recipes',
  approvals: '/admin/site00/approvals',
  identities: '/admin/site00/identities',
  bldrIntakes: '/admin/site00/bldr-intakes',
  leads: '/admin/site00/leads',
  discovery: '/admin/site00/discovery',
  projects: '/admin/site00/projects',
  project: (id: string) => `/admin/site00/projects/${id}`,
  projectIntelligence: (id: string) => `/admin/site00/projects/${id}/intelligence`,
  projectStudio: (id: string) => `/admin/site00/projects/${id}/studio`,
  projectApprovals: (id: string) => `/admin/site00/projects/${id}/approvals`,
  projectDeliverables: (id: string) => `/admin/site00/projects/${id}/deliverables`,
  projectAccess: (id: string) => `/admin/site00/projects/${id}/access`,
  projectActivity: (id: string) => `/admin/site00/projects/${id}/activity`,
  sites: '/admin/site00/sites',
  ctrlRoom: '/control/overview',
  finance: '/admin/site00/finance',
  team: '/admin/site00/team',
  reports: '/admin/site00/reports',
  settings: '/admin/site00/settings',
  settingsAutomation: '/admin/site00/settings/studio/automation',
  clientProvisioning: (slug: string) => `/project/${slug}/provisioning`,
} as const;
