import type {
  AiOpportunity,
  AutomationOpportunity,
  BusinessDependency,
  BusinessEvent,
  BusinessFlow,
  BusinessRisk,
  BusinessSystem,
} from '../../business-types';

type SystemSeed = Omit<BusinessSystem, 'dependents'>;

function sys(seed: SystemSeed): BusinessSystem {
  return { ...seed, dependents: [] };
}

export const FRONTAL_SLAYER_BUSINESS_SYSTEMS: BusinessSystem[] = [
  sys({
    systemId: 'brand-genome',
    officialName: 'Brand Genome™',
    purpose: 'Preserve luxury, editorial, trust-centered identity across every touchpoint.',
    owner: 'Founder / Chief Brand Owner',
    dependencies: ['vision-strategy', 'founder-office'],
    ownedData: ['brand principles', 'voice rules', 'visual standards', 'vocabulary'],
    eventsProduced: ['brand_direction_approved', 'brand_rule_changed'],
    eventsConsumed: ['founder_decision_made', 'customer_sentiment_changed'],
    businessRules: ['Trust over sales', 'Real catalog products only', 'Brand coherence over uniformity'],
    operationalStatus: 'active',
    revenueImpact: 'high',
    customerImpact: 'high',
    automationScore: 55,
    aiReadiness: 72,
    expansionReadiness: 68,
    engineClass: 'desire',
    systemClass: 'core',
  }),
  sys({
    systemId: 'vision-strategy',
    officialName: 'Vision & Strategy Genome™',
    purpose: 'Convert founder ambition into priorities, positioning, and operating direction.',
    owner: 'Founder / Executive Council',
    dependencies: ['founder-office', 'analytics'],
    ownedData: ['vision statements', 'strategic pillars', 'roadmap themes'],
    eventsProduced: ['strategic_priority_approved', 'roadmap_updated'],
    eventsConsumed: ['revenue_milestone_reached', 'bottleneck_detected'],
    businessRules: ['Strategy must serve brand promise', 'Strengthen core before adding complexity'],
    operationalStatus: 'active',
    revenueImpact: 'high',
    customerImpact: 'medium',
    automationScore: 48,
    aiReadiness: 70,
    expansionReadiness: 75,
    engineClass: 'desire',
    systemClass: 'knowledge',
  }),
  sys({
    systemId: 'founder-office',
    officialName: 'Founder Office™',
    purpose: 'Central authority for taste, major decisions, approvals, and company memory.',
    owner: 'Founder',
    dependencies: ['studio-os', 'analytics', 'support'],
    ownedData: ['decision log', 'founder preferences', 'approval history'],
    eventsProduced: ['founder_approved', 'founder_rejected', 'founder_override_issued'],
    eventsConsumed: ['critical_support_issue', 'launch_ready', 'revenue_anomaly'],
    businessRules: ['High-impact decisions require founder visibility'],
    operationalStatus: 'active',
    revenueImpact: 'high',
    customerImpact: 'high',
    automationScore: 42,
    aiReadiness: 78,
    expansionReadiness: 60,
    engineClass: 'operating',
    systemClass: 'core',
  }),
  sys({
    systemId: 'product-portfolio',
    officialName: 'Product Portfolio Genome™',
    purpose: 'Own what the company sells, pricing principles, and product lifecycle.',
    owner: 'Founder / Product Lead',
    dependencies: ['brand-genome', 'vision-strategy', 'inventory', 'finance'],
    ownedData: ['product families', 'SKU hierarchy', 'price bands', 'lifecycle status'],
    eventsProduced: ['product_created', 'price_changed', 'product_launched'],
    eventsConsumed: ['inventory_changed', 'customer_demand_spike', 'review_trend'],
    businessRules: ['Catalog must stay understandable', 'Customization cannot destroy margin'],
    operationalStatus: 'active',
    revenueImpact: 'critical',
    customerImpact: 'high',
    automationScore: 68,
    aiReadiness: 65,
    expansionReadiness: 72,
    engineClass: 'product',
    systemClass: 'core',
  }),
  sys({
    systemId: 'unit-catalog',
    officialName: 'Unit Catalog™',
    purpose: 'Own the six primary wig unit identities and their business meaning.',
    owner: 'Product Lead / Founder',
    dependencies: ['product-portfolio', 'inventory', 'photography'],
    ownedData: ['unit names', 'textures', 'base prices', 'availability'],
    eventsProduced: ['unit_available', 'unit_unavailable', 'unit_price_changed'],
    eventsConsumed: ['supplier_stock_changed', 'product_photo_approved'],
    businessRules: ['Unit names are canonical', 'Descriptions must match real catalog'],
    operationalStatus: 'active',
    revenueImpact: 'critical',
    customerImpact: 'critical',
    automationScore: 72,
    aiReadiness: 70,
    expansionReadiness: 65,
    engineClass: 'product',
    systemClass: 'revenue',
  }),
  sys({
    systemId: 'build-a-wig',
    officialName: 'Build-A-Wig™',
    purpose: 'Let customers configure a wig as a luxury guided build.',
    owner: 'Product + Client Experience',
    dependencies: ['unit-catalog', 'product-portfolio', 'inventory', 'photography'],
    ownedData: ['configuration selections', 'option prices', 'draft builds'],
    eventsProduced: ['build_started', 'build_completed', 'build_added_to_cart'],
    eventsConsumed: ['unit_selected', 'membership_status_changed'],
    businessRules: ['Customization must remain fulfillable', 'Options explicit before payment'],
    operationalStatus: 'active',
    revenueImpact: 'critical',
    customerImpact: 'critical',
    automationScore: 75,
    aiReadiness: 82,
    expansionReadiness: 78,
    engineClass: 'product',
    systemClass: 'revenue',
  }),
  sys({
    systemId: 'bcf-catalog',
    officialName: 'Bundles / Closures / Frontals™',
    purpose: 'Sell hair components separately or in bundle deals.',
    owner: 'Product + Inventory',
    dependencies: ['product-portfolio', 'inventory'],
    ownedData: ['bundle SKUs', 'closure SKUs', 'frontal SKUs', 'deal rules'],
    eventsProduced: ['bundle_deal_applied', 'bcf_order_placed'],
    eventsConsumed: ['product_catalog_update', 'supplier_stock_update'],
    businessRules: ['Bundle math must be clear', 'Lace/color treatments must be priced'],
    operationalStatus: 'active',
    revenueImpact: 'high',
    customerImpact: 'high',
    automationScore: 70,
    aiReadiness: 58,
    expansionReadiness: 70,
    engineClass: 'product',
    systemClass: 'revenue',
  }),
  sys({
    systemId: 'website-commerce',
    officialName: 'Website Commerce Channel™',
    purpose: 'Primary digital storefront and conversion surface.',
    owner: 'Digital + Experience Lead',
    dependencies: ['brand-genome', 'product-portfolio', 'creative-assets', 'photography'],
    ownedData: ['page catalog', 'conversion paths', 'merchandising zones'],
    eventsProduced: ['page_viewed', 'product_viewed', 'add_to_cart'],
    eventsConsumed: ['campaign_launched', 'inventory_changed', 'content_published'],
    businessRules: ['Luxury editorial experience', 'Mobile-first commerce'],
    operationalStatus: 'active',
    revenueImpact: 'critical',
    customerImpact: 'critical',
    automationScore: 62,
    aiReadiness: 68,
    expansionReadiness: 70,
    engineClass: 'client',
    systemClass: 'customer',
  }),
  sys({
    systemId: 'customer-accounts',
    officialName: 'Customer Accounts™',
    purpose: 'Authenticate customers and anchor account-level services.',
    owner: 'Client Experience + Technology',
    dependencies: ['policies-legal', 'support'],
    ownedData: ['account ID', 'auth status', 'preferences', 'consent flags'],
    eventsProduced: ['account_created', 'account_signed_in', 'account_deleted'],
    eventsConsumed: ['order_placed', 'membership_purchased', 'support_case_opened'],
    businessRules: ['Account required for personalized services', 'Consent governs messaging'],
    operationalStatus: 'active',
    revenueImpact: 'high',
    customerImpact: 'critical',
    automationScore: 78,
    aiReadiness: 72,
    expansionReadiness: 65,
    engineClass: 'client',
    systemClass: 'customer',
  }),
  sys({
    systemId: 'client-profiles',
    officialName: 'Client Profile Genome™',
    purpose: 'Single relationship truth for each customer across the business.',
    owner: 'Client Experience + Founder CRM',
    dependencies: ['customer-accounts', 'orders', 'memberships', 'rewards'],
    ownedData: ['identity', 'purchase history', 'preferences', 'tier status', 'notes'],
    eventsProduced: ['profile_updated', 'client_segment_changed', 'vip_flagged'],
    eventsConsumed: ['order_placed', 'review_submitted', 'membership_upgraded'],
    businessRules: ['One customer, one relationship record', 'Support and concierge read same profile'],
    operationalStatus: 'active',
    revenueImpact: 'high',
    customerImpact: 'critical',
    automationScore: 70,
    aiReadiness: 80,
    expansionReadiness: 72,
    engineClass: 'client',
    systemClass: 'core',
  }),
  sys({
    systemId: 'checkout',
    officialName: 'Checkout System™',
    purpose: 'Convert purchase intent into a payable, authorized transaction.',
    owner: 'Commerce + Finance',
    dependencies: ['product-portfolio', 'customer-accounts', 'policies-legal', 'inventory'],
    ownedData: ['checkout session', 'quote lines', 'shipping selection', 'promo state'],
    eventsProduced: ['checkout_started', 'checkout_abandoned', 'checkout_completed'],
    eventsConsumed: ['cart_updated', 'inventory_reserved', 'membership_selected'],
    businessRules: ['Customer sees final truth before pay', 'Unavailable items cannot checkout'],
    operationalStatus: 'active',
    revenueImpact: 'critical',
    customerImpact: 'critical',
    automationScore: 80,
    aiReadiness: 65,
    expansionReadiness: 68,
    engineClass: 'revenue',
    systemClass: 'operational',
  }),
  sys({
    systemId: 'payments',
    officialName: 'Payments & Authorization™',
    purpose: 'Authorize and settle money for products, services, memberships, and deposits.',
    owner: 'Finance + Technology',
    dependencies: ['checkout', 'finance', 'policies-legal'],
    ownedData: ['payment intent', 'authorization status', 'refund records', 'membership billing'],
    eventsProduced: ['payment_authorized', 'payment_failed', 'refund_issued'],
    eventsConsumed: ['checkout_completed', 'subscription_renewed', 'support_refund_approved'],
    businessRules: ['No fulfillment before authorization', 'Refunds require policy alignment'],
    operationalStatus: 'active',
    revenueImpact: 'critical',
    customerImpact: 'high',
    automationScore: 85,
    aiReadiness: 60,
    expansionReadiness: 70,
    engineClass: 'revenue',
    systemClass: 'operational',
  }),
  sys({
    systemId: 'orders',
    officialName: 'Order Management™',
    purpose: 'Own the commercial promise after payment authorization.',
    owner: 'Operations + Client Experience',
    dependencies: ['payments', 'checkout', 'client-profiles', 'inventory'],
    ownedData: ['order ID', 'line items', 'build specs', 'status', 'fulfillment notes'],
    eventsProduced: ['order_created', 'order_updated', 'order_cancelled'],
    eventsConsumed: ['payment_authorized', 'inventory_allocated', 'shipping_label_created'],
    businessRules: ['Paid order must match authorized quote', 'Custom builds need explicit spec sheet'],
    operationalStatus: 'active',
    revenueImpact: 'critical',
    customerImpact: 'critical',
    automationScore: 76,
    aiReadiness: 70,
    expansionReadiness: 68,
    engineClass: 'revenue',
    systemClass: 'core',
  }),
  sys({
    systemId: 'processing-fulfillment',
    officialName: 'Processing & Fulfillment™',
    purpose: 'Translate orders into production, packing, and dispatch readiness.',
    owner: 'Operations Lead',
    dependencies: ['orders', 'inventory', 'build-a-wig', 'photography'],
    ownedData: ['fulfillment queue', 'build sheets', 'QC checklist', 'processing status'],
    eventsProduced: ['order_processing_started', 'order_ready_to_ship', 'fulfillment_delayed'],
    eventsConsumed: ['order_created', 'inventory_allocated', 'custom_build_confirmed'],
    businessRules: ['Custom orders require build sheet', 'QC before ship'],
    operationalStatus: 'active',
    revenueImpact: 'critical',
    customerImpact: 'critical',
    automationScore: 72,
    aiReadiness: 68,
    expansionReadiness: 65,
    engineClass: 'operating',
    systemClass: 'operational',
  }),
  sys({
    systemId: 'shipping',
    officialName: 'Shipping & Delivery™',
    purpose: 'Move fulfilled orders to customers with tracking and communication.',
    owner: 'Operations + Client Experience',
    dependencies: ['processing-fulfillment', 'orders', 'client-profiles'],
    ownedData: ['carrier', 'tracking number', 'delivery status', 'delivery exceptions'],
    eventsProduced: ['shipment_created', 'shipment_in_transit', 'order_delivered'],
    eventsConsumed: ['order_ready_to_ship', 'address_validated'],
    businessRules: ['Tracking shared at ship', 'Delivery triggers review invitation'],
    operationalStatus: 'active',
    revenueImpact: 'high',
    customerImpact: 'critical',
    automationScore: 82,
    aiReadiness: 55,
    expansionReadiness: 60,
    engineClass: 'operating',
    systemClass: 'operational',
  }),
  sys({
    systemId: 'inventory',
    officialName: 'Inventory & Availability™',
    purpose: 'Know what can be sold, customized, and fulfilled right now.',
    owner: 'Operations + Product',
    dependencies: ['product-portfolio', 'supplier-relationships'],
    ownedData: ['SKU stock', 'reservations', 'component availability', 'launch readiness'],
    eventsProduced: ['inventory_changed', 'stockout_detected', 'inventory_reserved'],
    eventsConsumed: ['order_created', 'launch_planned', 'supplier_receipt'],
    businessRules: ['Sell only what can be fulfilled', 'Launch requires inventory readiness'],
    operationalStatus: 'active',
    revenueImpact: 'critical',
    customerImpact: 'high',
    automationScore: 78,
    aiReadiness: 62,
    expansionReadiness: 68,
    engineClass: 'operating',
    systemClass: 'supporting',
  }),
  sys({
    systemId: 'memberships',
    officialName: 'Memberships™',
    purpose: 'Sell recurring relationship access and premium benefits.',
    owner: 'Growth + Client Experience',
    dependencies: ['rewards', 'policies-legal', 'payments', 'client-profiles'],
    ownedData: ['tier', 'term', 'renewal status', 'benefit entitlements'],
    eventsProduced: ['membership_purchased', 'membership_renewed', 'membership_cancelled'],
    eventsConsumed: ['payment_authorized', 'tier_benefit_used'],
    businessRules: ['Benefits must match paid tier', 'Renewal terms must be clear'],
    operationalStatus: 'active',
    revenueImpact: 'high',
    customerImpact: 'high',
    automationScore: 80,
    aiReadiness: 70,
    expansionReadiness: 75,
    engineClass: 'revenue',
    systemClass: 'revenue',
  }),
  sys({
    systemId: 'rewards',
    officialName: 'Rewards System™',
    purpose: 'Incentivize repeat behavior through points, tiers, and perks.',
    owner: 'Growth + Finance',
    dependencies: ['orders', 'memberships', 'client-profiles', 'finance'],
    ownedData: ['points balance', 'tier', 'redemption history', 'voucher inventory'],
    eventsProduced: ['points_earned', 'points_redeemed', 'tier_upgraded'],
    eventsConsumed: ['order_delivered', 'review_submitted', 'referral_converted'],
    businessRules: ['Rewards must be fundable', 'Tier rules must be transparent'],
    operationalStatus: 'active',
    revenueImpact: 'high',
    customerImpact: 'high',
    automationScore: 75,
    aiReadiness: 68,
    expansionReadiness: 72,
    engineClass: 'revenue',
    systemClass: 'revenue',
  }),
  sys({
    systemId: 'affiliate-program',
    officialName: 'Affiliate Program™',
    purpose: 'Turn creators and partners into measurable acquisition channels.',
    owner: 'Growth + Finance',
    dependencies: ['rewards', 'client-profiles', 'finance', 'policies-legal'],
    ownedData: ['affiliate ID', 'content submissions', 'conversion attribution', 'payout queue'],
    eventsProduced: ['affiliate_enrolled', 'affiliate_conversion', 'affiliate_paid'],
    eventsConsumed: ['order_placed', 'referral_converted', 'content_approved'],
    businessRules: ['Attribution must be auditable', 'Payout requires approval threshold'],
    operationalStatus: 'active',
    revenueImpact: 'medium',
    customerImpact: 'medium',
    automationScore: 70,
    aiReadiness: 65,
    expansionReadiness: 78,
    engineClass: 'revenue',
    systemClass: 'revenue',
  }),
  sys({
    systemId: 'campaigns-launches',
    officialName: 'Campaign & Launch Genome™',
    purpose: 'Turn strategy into coordinated demand-generation moments.',
    owner: 'Founder / Growth + Brand',
    dependencies: ['vision-strategy', 'brand-genome', 'content', 'inventory'],
    ownedData: ['campaign brief', 'audience', 'offer', 'launch calendar'],
    eventsProduced: ['campaign_planned', 'campaign_launched', 'campaign_completed'],
    eventsConsumed: ['strategic_priority_approved', 'inventory_ready', 'content_ready'],
    businessRules: ['Launch requires readiness across product, inventory, and support'],
    operationalStatus: 'active',
    revenueImpact: 'high',
    customerImpact: 'high',
    automationScore: 58,
    aiReadiness: 75,
    expansionReadiness: 80,
    engineClass: 'desire',
    systemClass: 'creative',
  }),
  sys({
    systemId: 'content',
    officialName: 'Content Genome™',
    purpose: 'Produce reusable stories, education, and proof across channels.',
    owner: 'Brand + Growth',
    dependencies: ['brand-genome', 'photography', 'creative-assets'],
    ownedData: ['content calendar', 'story assets', 'channel adaptations'],
    eventsProduced: ['content_drafted', 'content_published', 'content_retired'],
    eventsConsumed: ['campaign_planned', 'product_launched', 'review_submitted'],
    businessRules: ['Content must match brand voice', 'Product claims must be accurate'],
    operationalStatus: 'active',
    revenueImpact: 'high',
    customerImpact: 'high',
    automationScore: 55,
    aiReadiness: 82,
    expansionReadiness: 75,
    engineClass: 'desire',
    systemClass: 'creative',
  }),
  sys({
    systemId: 'photography',
    officialName: 'Photography & Product Imagery™',
    purpose: 'Create trustworthy visual proof of products and brand world.',
    owner: 'Creative Director + Product',
    dependencies: ['brand-genome', 'product-portfolio', 'creative-assets'],
    ownedData: ['photo sets', 'angles', 'color accuracy refs', 'derivative crops'],
    eventsProduced: ['photo_shoot_completed', 'product_photo_approved', 'asset_derivative_created'],
    eventsConsumed: ['product_created', 'collection_planned', 'launch_planned'],
    businessRules: ['Imagery must match real product', 'Approved assets only in commerce'],
    operationalStatus: 'active',
    revenueImpact: 'high',
    customerImpact: 'critical',
    automationScore: 60,
    aiReadiness: 70,
    expansionReadiness: 68,
    engineClass: 'desire',
    systemClass: 'creative',
  }),
  sys({
    systemId: 'reviews',
    officialName: 'Reviews & Social Proof™',
    purpose: 'Capture customer proof and feed trust across the business.',
    owner: 'Client Experience + Brand',
    dependencies: ['orders', 'shipping', 'client-profiles'],
    ownedData: ['review text', 'rating', 'media', 'moderation status'],
    eventsProduced: ['review_submitted', 'review_published', 'review_flagged'],
    eventsConsumed: ['order_delivered', 'support_case_resolved'],
    businessRules: ['Authentic reviews only', 'Negative reviews route to recovery'],
    operationalStatus: 'active',
    revenueImpact: 'high',
    customerImpact: 'high',
    automationScore: 68,
    aiReadiness: 78,
    expansionReadiness: 70,
    engineClass: 'client',
    systemClass: 'customer',
  }),
  sys({
    systemId: 'ai-concierge',
    officialName: 'AI Concierge / PSA™',
    purpose: 'Provide trusted personalized guidance across shopping and care.',
    owner: 'Founder + Client Experience',
    dependencies: ['client-profiles', 'product-portfolio', 'memberships', 'support'],
    ownedData: ['conversation history', 'recommendations', 'usage limits', 'preference signals'],
    eventsProduced: ['concierge_session_started', 'concierge_recommendation_made'],
    eventsConsumed: ['account_signed_in', 'membership_upgraded', 'product_viewed'],
    businessRules: ['Trust over sales', 'Premium gates must be clear', 'Never invent catalog items'],
    operationalStatus: 'active',
    revenueImpact: 'medium',
    customerImpact: 'critical',
    automationScore: 65,
    aiReadiness: 92,
    expansionReadiness: 85,
    engineClass: 'client',
    systemClass: 'expansion',
  }),
  sys({
    systemId: 'support',
    officialName: 'Support & Service Recovery™',
    purpose: 'Resolve issues and protect trust when operations fail expectations.',
    owner: 'Client Experience Lead',
    dependencies: ['orders', 'policies-legal', 'shipping', 'client-profiles'],
    ownedData: ['case ID', 'issue category', 'resolution', 'SLA status'],
    eventsProduced: ['support_case_opened', 'support_case_resolved', 'support_escalated'],
    eventsConsumed: ['order_delayed', 'payment_failed', 'review_flagged'],
    businessRules: ['Policy-first resolution', 'Escalate trust-threatening issues'],
    operationalStatus: 'active',
    revenueImpact: 'medium',
    customerImpact: 'critical',
    automationScore: 72,
    aiReadiness: 80,
    expansionReadiness: 65,
    engineClass: 'operating',
    systemClass: 'supporting',
  }),
  sys({
    systemId: 'academy',
    officialName: 'Academy™',
    purpose: 'Turn expertise into structured education and certification paths.',
    owner: 'Founder / Education Lead',
    dependencies: ['brand-genome', 'content', 'studio-os'],
    ownedData: ['curriculum', 'student profiles', 'completion records'],
    eventsProduced: ['student_enrolled', 'module_completed', 'certification_issued'],
    eventsConsumed: ['founder_approved', 'community_question_emerged'],
    businessRules: ['Education protects brand standards', 'Teach craft not only products'],
    operationalStatus: 'planned',
    revenueImpact: 'medium',
    customerImpact: 'medium',
    automationScore: 50,
    aiReadiness: 75,
    expansionReadiness: 88,
    engineClass: 'operating',
    systemClass: 'expansion',
  }),
  sys({
    systemId: 'analytics',
    officialName: 'Analytics & Business Intelligence™',
    purpose: 'Turn operating signals into decisions, forecasts, and accountability.',
    owner: 'Founder / Finance + Growth',
    dependencies: ['orders', 'payments', 'campaigns-launches', 'support'],
    ownedData: ['KPIs', 'funnels', 'cohorts', 'anomaly alerts'],
    eventsProduced: ['kpi_updated', 'anomaly_detected', 'report_generated'],
    eventsConsumed: ['order_created', 'campaign_launched', 'support_escalated'],
    businessRules: ['One source of truth per KPI', 'Anomalies escalate to founder when critical'],
    operationalStatus: 'active',
    revenueImpact: 'high',
    customerImpact: 'medium',
    automationScore: 78,
    aiReadiness: 85,
    expansionReadiness: 80,
    engineClass: 'operating',
    systemClass: 'knowledge',
  }),
  sys({
    systemId: 'finance',
    officialName: 'Finance & Reconciliation™',
    purpose: 'Track revenue, liabilities, payouts, and financial truth.',
    owner: 'Founder / Finance',
    dependencies: ['payments', 'orders', 'rewards', 'affiliate-program'],
    ownedData: ['ledger entries', 'revenue by channel', 'liabilities', 'payout queue'],
    eventsProduced: ['revenue_recorded', 'payout_approved', 'financial_anomaly_detected'],
    eventsConsumed: ['payment_authorized', 'refund_issued', 'points_redeemed'],
    businessRules: ['Every dollar traceable', 'Rewards and gift cards are liabilities'],
    operationalStatus: 'active',
    revenueImpact: 'critical',
    customerImpact: 'medium',
    automationScore: 82,
    aiReadiness: 68,
    expansionReadiness: 72,
    engineClass: 'operating',
    systemClass: 'supporting',
  }),
  sys({
    systemId: 'studio-os',
    officialName: 'Studio OS Headquarters™',
    purpose: 'Operating system for founder decisions, memory, campaigns, and company intelligence.',
    owner: 'Founder / Chief of Staff',
    dependencies: ['founder-office', 'analytics'],
    ownedData: ['module registry', 'decision memory', 'company genome', 'briefings'],
    eventsProduced: ['briefing_generated', 'decision_recorded', 'genome_updated'],
    eventsConsumed: ['founder_approved', 'anomaly_detected', 'campaign_planned'],
    businessRules: ['Studio OS serves the business, not the reverse', 'Memory must be governed'],
    operationalStatus: 'active',
    revenueImpact: 'medium',
    customerImpact: 'low',
    automationScore: 70,
    aiReadiness: 90,
    expansionReadiness: 95,
    engineClass: 'operating',
    systemClass: 'knowledge',
  }),
  sys({
    systemId: 'policies-legal',
    officialName: 'Policies & Legal Framework™',
    purpose: 'Define enforceable rules for commerce, privacy, refunds, and programs.',
    owner: 'Founder / Legal Counsel',
    dependencies: ['founder-office'],
    ownedData: ['policy documents', 'terms versions', 'privacy rules', 'program terms'],
    eventsProduced: ['policy_updated', 'policy_exception_granted'],
    eventsConsumed: ['support_escalated', 'new_program_launched'],
    businessRules: ['Policies must be customer-readable', 'Exceptions require documentation'],
    operationalStatus: 'active',
    revenueImpact: 'medium',
    customerImpact: 'high',
    automationScore: 45,
    aiReadiness: 55,
    expansionReadiness: 60,
    engineClass: 'operating',
    systemClass: 'supporting',
  }),
  sys({
    systemId: 'creative-assets',
    officialName: 'Creative Asset Genome™',
    purpose: 'Govern reusable brand and campaign assets across channels.',
    owner: 'Brand + Creative Ops',
    dependencies: ['brand-genome', 'photography'],
    ownedData: ['asset registry', 'approval status', 'usage rights', 'derivatives'],
    eventsProduced: ['asset_approved', 'asset_deprecated', 'asset_requested'],
    eventsConsumed: ['campaign_planned', 'content_drafted'],
    businessRules: ['Approved assets only', 'Track lineage and rights'],
    operationalStatus: 'active',
    revenueImpact: 'medium',
    customerImpact: 'high',
    automationScore: 62,
    aiReadiness: 72,
    expansionReadiness: 70,
    engineClass: 'desire',
    systemClass: 'creative',
  }),
  sys({
    systemId: 'supplier-relationships',
    officialName: 'Supplier Relationships™',
    purpose: 'Manage upstream hair and component supply capability.',
    owner: 'Operations + Product',
    dependencies: ['product-portfolio'],
    ownedData: ['supplier catalog', 'lead times', 'quality standards'],
    eventsProduced: ['supplier_receipt', 'supplier_delay'],
    eventsConsumed: ['inventory_changed', 'product_created'],
    businessRules: ['Quality standards enforced', 'Lead times inform availability'],
    operationalStatus: 'active',
    revenueImpact: 'high',
    customerImpact: 'medium',
    automationScore: 55,
    aiReadiness: 48,
    expansionReadiness: 65,
    engineClass: 'operating',
    systemClass: 'supporting',
  }),
];

export const FRONTAL_SLAYER_BUSINESS_FLOWS: BusinessFlow[] = [
  {
    id: 'flow-visitor-customer',
    name: 'Visitor → Customer',
    flowType: 'customer',
    description: 'Anonymous visitor becomes identified customer through account creation.',
    steps: [
      { systemId: 'website-commerce', label: 'Visitor arrives' },
      { systemId: 'website-commerce', label: 'Browses catalog' },
      { systemId: 'customer-accounts', label: 'Creates account', eventId: 'account_created' },
      { systemId: 'client-profiles', label: 'Profile established' },
    ],
  },
  {
    id: 'flow-lead-purchase',
    name: 'Lead → Purchase',
    flowType: 'revenue',
    description: 'Interest converts to cart and checkout.',
    steps: [
      { systemId: 'campaigns-launches', label: 'Campaign creates demand' },
      { systemId: 'website-commerce', label: 'Product viewed' },
      { systemId: 'build-a-wig', label: 'Configuration completed', eventId: 'build_completed' },
      { systemId: 'checkout', label: 'Checkout started' },
      { systemId: 'payments', label: 'Payment authorized', eventId: 'payment_authorized' },
    ],
  },
  {
    id: 'flow-purchase-fulfillment',
    name: 'Purchase → Fulfillment → Delivery',
    flowType: 'operational',
    description: 'Authorized payment becomes fulfilled and delivered order.',
    steps: [
      { systemId: 'payments', label: 'Payment authorized' },
      { systemId: 'orders', label: 'Order created', eventId: 'order_created' },
      { systemId: 'processing-fulfillment', label: 'Processing started' },
      { systemId: 'shipping', label: 'Shipped', eventId: 'shipment_created' },
      { systemId: 'shipping', label: 'Delivered', eventId: 'order_delivered' },
    ],
  },
  {
    id: 'flow-delivery-loyalty',
    name: 'Delivery → Review → Loyalty → Membership',
    flowType: 'customer',
    description: 'Post-delivery relationship compounding loop.',
    steps: [
      { systemId: 'shipping', label: 'Order delivered' },
      { systemId: 'reviews', label: 'Review submitted', eventId: 'review_submitted' },
      { systemId: 'rewards', label: 'Points earned', eventId: 'points_earned' },
      { systemId: 'memberships', label: 'Membership upgraded', eventId: 'membership_purchased' },
    ],
  },
  {
    id: 'flow-loyalty-repeat',
    name: 'Rewards → Repeat Purchase',
    flowType: 'revenue',
    description: 'Loyalty incentives drive next purchase.',
    steps: [
      { systemId: 'rewards', label: 'Tier upgraded' },
      { systemId: 'client-profiles', label: 'Personalized outreach' },
      { systemId: 'ai-concierge', label: 'Guided recommendation' },
      { systemId: 'checkout', label: 'Repeat checkout' },
      { systemId: 'orders', label: 'Repeat order placed' },
    ],
  },
  {
    id: 'flow-advocacy-referral',
    name: 'Advocacy → Referral → New Customer',
    flowType: 'expansion',
    description: 'Happy customers become acquisition channels.',
    steps: [
      { systemId: 'reviews', label: 'Social proof published' },
      { systemId: 'affiliate-program', label: 'Referral converted', eventId: 'referral_converted' },
      { systemId: 'website-commerce', label: 'New visitor arrives' },
      { systemId: 'customer-accounts', label: 'New account created' },
    ],
  },
  {
    id: 'flow-founder-revenue',
    name: 'Founder Vision → Campaign → Content → Launch → Revenue',
    flowType: 'founder',
    description: 'Founder strategic chain into measurable revenue.',
    steps: [
      { systemId: 'founder-office', label: 'Vision approved' },
      { systemId: 'vision-strategy', label: 'Priority set' },
      { systemId: 'campaigns-launches', label: 'Campaign planned' },
      { systemId: 'content', label: 'Content published' },
      { systemId: 'website-commerce', label: 'Traffic converts' },
      { systemId: 'payments', label: 'Revenue captured' },
      { systemId: 'analytics', label: 'Performance measured' },
    ],
  },
  {
    id: 'flow-academy-community',
    name: 'Academy → Certification → Community',
    flowType: 'expansion',
    description: 'Education path into community authority.',
    steps: [
      { systemId: 'academy', label: 'Student enrolled' },
      { systemId: 'academy', label: 'Module completed' },
      { systemId: 'academy', label: 'Certification issued', eventId: 'certification_issued' },
    ],
  },
];

export const FRONTAL_SLAYER_BUSINESS_EVENTS: BusinessEvent[] = [
  {
    eventId: 'account_created',
    name: 'Account Created',
    producerSystemId: 'customer-accounts',
    consumerSystemIds: ['client-profiles', 'rewards', 'ai-concierge'],
    description: 'New customer account established.',
    category: 'customer',
  },
  {
    eventId: 'payment_authorized',
    name: 'Payment Authorized',
    producerSystemId: 'payments',
    consumerSystemIds: ['orders', 'finance', 'memberships'],
    description: 'Funds authorized for order or subscription.',
    category: 'revenue',
  },
  {
    eventId: 'order_created',
    name: 'Order Created',
    producerSystemId: 'orders',
    consumerSystemIds: ['processing-fulfillment', 'inventory', 'analytics', 'client-profiles'],
    description: 'Commercial promise recorded after payment.',
    category: 'operational',
  },
  {
    eventId: 'order_delivered',
    name: 'Order Delivered',
    producerSystemId: 'shipping',
    consumerSystemIds: ['reviews', 'rewards', 'support', 'client-profiles'],
    description: 'Customer received order; post-purchase loop begins.',
    category: 'customer',
  },
  {
    eventId: 'review_submitted',
    name: 'Review Submitted',
    producerSystemId: 'reviews',
    consumerSystemIds: ['rewards', 'content', 'product-portfolio', 'support'],
    description: 'Customer proof captured.',
    category: 'customer',
  },
  {
    eventId: 'membership_purchased',
    name: 'Membership Purchased',
    producerSystemId: 'memberships',
    consumerSystemIds: ['client-profiles', 'rewards', 'ai-concierge', 'finance'],
    description: 'Customer enters premium relationship tier.',
    category: 'revenue',
  },
  {
    eventId: 'campaign_launched',
    name: 'Campaign Launched',
    producerSystemId: 'campaigns-launches',
    consumerSystemIds: ['website-commerce', 'content', 'analytics', 'inventory'],
    description: 'Demand-generation moment goes live.',
    category: 'creative',
  },
  {
    eventId: 'founder_approved',
    name: 'Founder Approved',
    producerSystemId: 'founder-office',
    consumerSystemIds: ['campaigns-launches', 'product-portfolio', 'studio-os', 'content'],
    description: 'Founder authorizes strategic or creative direction.',
    category: 'founder',
  },
  {
    eventId: 'inventory_changed',
    name: 'Inventory Changed',
    producerSystemId: 'inventory',
    consumerSystemIds: ['product-portfolio', 'website-commerce', 'checkout', 'campaigns-launches'],
    description: 'Availability changed; may affect selling and launches.',
    category: 'operational',
  },
  {
    eventId: 'support_escalated',
    name: 'Support Escalated',
    producerSystemId: 'support',
    consumerSystemIds: ['founder-office', 'policies-legal', 'analytics'],
    description: 'Customer issue requires leadership attention.',
    category: 'operational',
  },
];

export const FRONTAL_SLAYER_BUSINESS_RISKS: BusinessRisk[] = [
  {
    id: 'risk-founder-memory',
    title: 'Founder as undocumented memory',
    category: 'single-point-of-failure',
    affectedSystemIds: ['founder-office', 'brand-genome', 'campaigns-launches'],
    severity: 'critical',
    description: 'Founder taste and decisions can bottleneck or disappear into informal channels.',
    recommendedControl: 'Decision log, founder preference memory, approval packets via Studio OS.',
  },
  {
    id: 'risk-pricing-drift',
    title: 'Pricing and catalog drift',
    category: 'bottleneck',
    affectedSystemIds: ['product-portfolio', 'checkout', 'payments', 'support'],
    severity: 'critical',
    description: 'Product, checkout, marketing, and support may quote different truths.',
    recommendedControl: 'Canonical Product & Pricing Authority with validation events.',
  },
  {
    id: 'risk-custom-order-ambiguity',
    title: 'Custom order ambiguity',
    category: 'bottleneck',
    affectedSystemIds: ['build-a-wig', 'orders', 'processing-fulfillment', 'support'],
    severity: 'high',
    description: 'Build-A-Wig specs can be misunderstood in fulfillment.',
    recommendedControl: 'Structured fulfillment build sheet and pre-ship QA gate.',
  },
  {
    id: 'risk-inventory-launch',
    title: 'Inventory-launch mismatch',
    category: 'bottleneck',
    affectedSystemIds: ['inventory', 'campaigns-launches', 'website-commerce', 'checkout'],
    severity: 'high',
    description: 'Campaigns can sell what operations cannot fulfill.',
    recommendedControl: 'Inventory readiness gate before every launch.',
  },
  {
    id: 'risk-customer-identity-split',
    title: 'Duplicate customer identity responsibilities',
    category: 'duplicate-responsibility',
    affectedSystemIds: ['customer-accounts', 'client-profiles', 'rewards', 'memberships'],
    severity: 'medium',
    description: 'Multiple systems each hold partial customer truth.',
    recommendedControl: 'Client Profile Genome as relationship truth; specialized events elsewhere.',
  },
  {
    id: 'risk-build-sheet-missing',
    title: 'Fulfillment Build Sheet™ missing',
    category: 'missing-system',
    affectedSystemIds: ['build-a-wig', 'orders', 'processing-fulfillment'],
    severity: 'high',
    description: 'No formal bridge from customer configuration to production checklist.',
    recommendedControl: 'Auto-generate build sheet from every paid custom order.',
  },
  {
    id: 'risk-reconciliation-gap',
    title: 'Payment-order reconciliation gap',
    category: 'single-point-of-failure',
    affectedSystemIds: ['payments', 'orders', 'finance', 'memberships'],
    severity: 'high',
    description: 'Fulfillment or membership may not match payment reality.',
    recommendedControl: 'Daily reconciliation ledger and exception alerts.',
  },
];

export const FRONTAL_SLAYER_AUTOMATION_OPPORTUNITIES: AutomationOpportunity[] = [
  {
    id: 'auto-launch-readiness',
    title: 'Launch readiness scoring',
    systemIds: ['campaigns-launches', 'inventory', 'website-commerce', 'checkout', 'support'],
    automationShape: 'Checklist + risk score + go/no-go brief',
    priority: 95,
    estimatedImpact: 'Prevents stockout launches and support overload',
  },
  {
    id: 'auto-build-sheet',
    title: 'Custom order build sheet generation',
    systemIds: ['build-a-wig', 'orders', 'processing-fulfillment'],
    automationShape: 'Auto-generate production spec from final selections',
    priority: 92,
    estimatedImpact: 'Reduces fulfillment errors and support escalations',
  },
  {
    id: 'auto-reconciliation',
    title: 'Payment/order reconciliation',
    systemIds: ['payments', 'orders', 'finance', 'memberships'],
    automationShape: 'Daily mismatch detection and alerting',
    priority: 90,
    estimatedImpact: 'Protects revenue truth and membership entitlements',
  },
  {
    id: 'auto-review-routing',
    title: 'Review sentiment routing',
    systemIds: ['reviews', 'support', 'content', 'product-portfolio'],
    automationShape: 'Positive proof to marketing; negative to recovery',
    priority: 82,
    estimatedImpact: 'Compounds social proof while protecting trust',
  },
  {
    id: 'auto-founder-briefing',
    title: 'Founder daily business brief',
    systemIds: ['studio-os', 'analytics', 'founder-office'],
    automationShape: 'Priorities, risks, approvals, revenue signals',
    priority: 88,
    estimatedImpact: 'Reduces founder context reconstruction load',
  },
  {
    id: 'auto-loyalty-triggers',
    title: 'Loyalty lifecycle triggers',
    systemIds: ['orders', 'rewards', 'memberships', 'client-profiles'],
    automationShape: 'Stage-based retention journeys',
    priority: 80,
    estimatedImpact: 'Increases repeat purchase and membership conversion',
  },
];

export const FRONTAL_SLAYER_AI_OPPORTUNITIES: AiOpportunity[] = [
  {
    id: 'ai-concierge-guided',
    title: 'AI Concierge guided shopping',
    horizon: 'near-term',
    systemIds: ['ai-concierge', 'build-a-wig', 'unit-catalog', 'client-profiles'],
    description: 'Trusted product education and build assistance for premium members.',
    readinessScore: 92,
  },
  {
    id: 'ai-founder-brief',
    title: 'Founder daily business brief',
    horizon: 'near-term',
    systemIds: ['studio-os', 'analytics', 'founder-office'],
    description: 'Synthesize KPIs, risks, and approval queue into one morning packet.',
    readinessScore: 88,
  },
  {
    id: 'ai-build-sheet',
    title: 'Custom order build sheet generation',
    horizon: 'near-term',
    systemIds: ['build-a-wig', 'orders', 'processing-fulfillment'],
    description: 'Translate configuration into production-ready fulfillment instructions.',
    readinessScore: 85,
  },
  {
    id: 'ai-review-clustering',
    title: 'Review sentiment and product insight clustering',
    horizon: 'near-term',
    systemIds: ['reviews', 'product-portfolio', 'content'],
    description: 'Cluster proof and issues by unit, customization, and service moment.',
    readinessScore: 82,
  },
  {
    id: 'ai-churn-model',
    title: 'Predictive churn and next-best-offer',
    horizon: 'mid-term',
    systemIds: ['client-profiles', 'rewards', 'memberships', 'analytics'],
    description: 'Model retention risk and recommend timely offers.',
    readinessScore: 72,
  },
  {
    id: 'ai-genome-generator',
    title: 'Universal Company Genome generator',
    horizon: 'long-term',
    systemIds: ['studio-os', 'analytics', 'product-portfolio'],
    description: 'Generate business genomes for any company regardless of industry.',
    readinessScore: 78,
  },
];

export function buildFrontalSlayerBusinessDependencies(systems: BusinessSystem[]): BusinessDependency[] {
  const edges: BusinessDependency[] = [];
  for (const system of systems) {
    for (const depId of system.dependencies) {
      edges.push({
        id: `dep-${depId}-${system.systemId}`,
        fromSystemId: depId,
        toSystemId: system.systemId,
        relationshipType: 'upstream',
        strength: 80,
        description: `${system.officialName} depends on ${depId}`,
      });
    }
  }
  return edges;
}
