import type { KnowledgeIndustryUpdate, KnowledgeRetentionProfile } from '../types';
import { normalizeRetentionProfile } from './schemas';

const learned = '2026-01-01T09:00:00.000Z';

export const LAUNCH_RETENTION_PROFILES: KnowledgeRetentionProfile[] = [
  {
    id: 'memory-hair-bleaching-chemistry',
    brainId: 'hair-color',
    conceptTitle: 'Hair bleaching chemistry',
    profession: 'licensed-colorist',
    domain: 'chemistry',
    learnedAt: learned,
    lastPracticed: '2026-06-18T14:00:00.000Z',
    lastRealUsageAt: '2026-06-18T14:00:00.000Z',
    confidenceScore: 84,
    recallScore: 79,
    applicationsCompleted: 18,
    mistakesMade: 2,
    industryVersion: '2026.2',
    industryUpdateCount: 1,
    certificationStatus: 'renewal-due',
    certificationRelevance: 92,
    careerRelevance: 88,
    difficulty: 'advanced',
    careerGoalIds: ['licensed-colorist', 'corrective-color-specialist'],
    upcomingSimulationIds: ['sim-corrective-color-consult'],
    upcomingProjectIds: ['client-color-correction-week'],
  },
  {
    id: 'memory-color-theory',
    brainId: 'hair-color',
    conceptTitle: 'Color theory',
    profession: 'licensed-colorist',
    domain: 'color-theory',
    learnedAt: learned,
    lastPracticed: '2026-07-01T11:30:00.000Z',
    lastRealUsageAt: '2026-07-01T11:30:00.000Z',
    confidenceScore: 91,
    recallScore: 88,
    applicationsCompleted: 42,
    mistakesMade: 1,
    industryVersion: '2026.1',
    industryUpdateCount: 0,
    certificationStatus: 'current',
    certificationRelevance: 77,
    careerRelevance: 82,
    difficulty: 'intermediate',
    careerGoalIds: ['licensed-colorist'],
    upcomingSimulationIds: [],
    upcomingProjectIds: ['summer-shade-consultations'],
  },
  {
    id: 'memory-lace-installation',
    brainId: 'hair-analysis',
    conceptTitle: 'Lace installation',
    profession: 'luxury-install-specialist',
    domain: 'installation',
    learnedAt: learned,
    lastPracticed: '2026-05-20T16:45:00.000Z',
    lastRealUsageAt: '2026-05-20T16:45:00.000Z',
    confidenceScore: 76,
    recallScore: 68,
    applicationsCompleted: 25,
    mistakesMade: 4,
    industryVersion: '2026.1',
    industryUpdateCount: 0,
    certificationStatus: 'current',
    certificationRelevance: 61,
    careerRelevance: 74,
    difficulty: 'intermediate',
    careerGoalIds: ['luxury-install-specialist'],
    upcomingSimulationIds: ['sim-lace-customization-client'],
    upcomingProjectIds: ['bridal-install-series'],
  },
  {
    id: 'memory-client-consultations',
    brainId: 'customer-experience',
    conceptTitle: 'Client consultations',
    profession: 'beauty-professional',
    domain: 'consultation',
    learnedAt: learned,
    lastPracticed: '2026-07-07T10:15:00.000Z',
    lastRealUsageAt: '2026-07-07T10:15:00.000Z',
    confidenceScore: 93,
    recallScore: 90,
    applicationsCompleted: 64,
    mistakesMade: 0,
    industryVersion: '2026.1',
    industryUpdateCount: 0,
    certificationStatus: 'not-applicable',
    certificationRelevance: 52,
    careerRelevance: 95,
    difficulty: 'foundational',
    careerGoalIds: ['premium-client-experience'],
    upcomingSimulationIds: ['sim-sensitive-client-consult'],
    upcomingProjectIds: ['vip-consult-block'],
  },
  {
    id: 'memory-corrective-color',
    brainId: 'hair-color',
    conceptTitle: 'Corrective color',
    profession: 'corrective-color-specialist',
    domain: 'technical-skill',
    learnedAt: learned,
    lastPracticed: '2025-12-06T13:20:00.000Z',
    lastRealUsageAt: '2025-12-06T13:20:00.000Z',
    confidenceScore: 67,
    recallScore: 54,
    applicationsCompleted: 9,
    mistakesMade: 6,
    industryVersion: '2025.4',
    industryUpdateCount: 1,
    certificationStatus: 'expiring-soon',
    certificationRelevance: 88,
    careerRelevance: 91,
    difficulty: 'expert',
    careerGoalIds: ['corrective-color-specialist'],
    upcomingSimulationIds: ['sim-corrective-color-consult'],
    upcomingProjectIds: ['high-risk-color-calendar'],
  },
  {
    id: 'memory-salon-management',
    brainId: 'customer-experience',
    conceptTitle: 'Salon management',
    profession: 'studio-owner',
    domain: 'operations',
    learnedAt: learned,
    lastPracticed: '2026-04-12T09:00:00.000Z',
    lastRealUsageAt: '2026-04-12T09:00:00.000Z',
    confidenceScore: 72,
    recallScore: 65,
    applicationsCompleted: 13,
    mistakesMade: 3,
    industryVersion: '2026.1',
    industryUpdateCount: 0,
    certificationStatus: 'not-applicable',
    certificationRelevance: 45,
    careerRelevance: 78,
    difficulty: 'advanced',
    careerGoalIds: ['studio-owner'],
    upcomingSimulationIds: ['sim-staffing-salon-day'],
    upcomingProjectIds: ['operations-playbook'],
  },
  {
    id: 'memory-marketing-strategy',
    brainId: 'marketing',
    conceptTitle: 'Marketing strategy',
    profession: 'beauty-brand-builder',
    domain: 'marketing',
    learnedAt: learned,
    lastPracticed: '2026-06-09T12:00:00.000Z',
    lastRealUsageAt: '2026-06-09T12:00:00.000Z',
    confidenceScore: 81,
    recallScore: 74,
    applicationsCompleted: 21,
    mistakesMade: 2,
    industryVersion: '2026.2',
    industryUpdateCount: 2,
    certificationStatus: 'not-applicable',
    certificationRelevance: 36,
    careerRelevance: 70,
    difficulty: 'intermediate',
    careerGoalIds: ['beauty-brand-builder'],
    upcomingSimulationIds: ['sim-launch-campaign'],
    upcomingProjectIds: ['fall-campaign'],
  },
  {
    id: 'memory-accounting',
    brainId: 'bookkeeping',
    conceptTitle: 'Accounting',
    profession: 'profitable-studio-owner',
    domain: 'finance',
    learnedAt: learned,
    lastPracticed: '2026-03-02T15:00:00.000Z',
    lastRealUsageAt: '2026-03-02T15:00:00.000Z',
    confidenceScore: 62,
    recallScore: 57,
    applicationsCompleted: 7,
    mistakesMade: 5,
    industryVersion: '2026.1',
    industryUpdateCount: 1,
    certificationStatus: 'expiring-soon',
    certificationRelevance: 70,
    careerRelevance: 76,
    difficulty: 'advanced',
    careerGoalIds: ['profitable-studio-owner'],
    upcomingSimulationIds: ['sim-month-end-close'],
    upcomingProjectIds: ['quarterly-finance-review'],
  },
  {
    id: 'memory-leadership',
    brainId: 'customer-experience',
    conceptTitle: 'Leadership',
    profession: 'team-lead',
    domain: 'leadership',
    learnedAt: learned,
    lastPracticed: '2026-06-25T08:30:00.000Z',
    lastRealUsageAt: '2026-06-25T08:30:00.000Z',
    confidenceScore: 78,
    recallScore: 72,
    applicationsCompleted: 16,
    mistakesMade: 1,
    industryVersion: '2026.1',
    industryUpdateCount: 0,
    certificationStatus: 'not-applicable',
    certificationRelevance: 40,
    careerRelevance: 84,
    difficulty: 'advanced',
    careerGoalIds: ['team-lead'],
    upcomingSimulationIds: ['sim-team-conflict'],
    upcomingProjectIds: ['assistant-stylist-training'],
  },
].map((profile) => normalizeRetentionProfile(profile as KnowledgeRetentionProfile));

export const LAUNCH_INDUSTRY_UPDATES: KnowledgeIndustryUpdate[] = [
  {
    id: 'update-bleaching-bond-integrity-standard',
    conceptId: 'memory-hair-bleaching-chemistry',
    brainId: 'hair-color',
    title: 'Bleaching standard now emphasizes bond integrity documentation',
    changedAt: '2026-07-08T09:00:00.000Z',
    industryVersion: '2026.3',
    summary: 'Record hair history, strand-test outcome, and bond-support plan before high-lift services.',
    whyItChanged: 'New professional guidance prioritizes damage prevention and informed consent.',
    workImpact: 'Consultations should include a clearer risk explanation before bleach processing.',
    severity: 'certification',
  },
  {
    id: 'update-short-form-local-campaign-shift',
    conceptId: 'memory-marketing-strategy',
    brainId: 'marketing',
    title: 'Local beauty marketing shifted toward short-form proof content',
    changedAt: '2026-07-06T09:00:00.000Z',
    industryVersion: '2026.2',
    summary: 'Campaigns perform better when they show transformation evidence quickly.',
    whyItChanged: 'Audience trust is moving toward proof, behind-the-scenes process, and visible expertise.',
    workImpact: 'Marketing refreshers should connect offer strategy to before/after client narratives.',
    severity: 'moderate',
  },
];

export function listRetentionProfiles(): KnowledgeRetentionProfile[] {
  return LAUNCH_RETENTION_PROFILES;
}

export function listIndustryUpdates(): KnowledgeIndustryUpdate[] {
  return LAUNCH_INDUSTRY_UPDATES;
}

export function getRetentionProfile(profileId: string): KnowledgeRetentionProfile | undefined {
  return LAUNCH_RETENTION_PROFILES.find((profile) => profile.id === profileId);
}

export function listProfilesForBrain(brainId: string): KnowledgeRetentionProfile[] {
  return LAUNCH_RETENTION_PROFILES.filter((profile) => profile.brainId === brainId);
}

export function listProfilesForProfession(profession: string): KnowledgeRetentionProfile[] {
  return LAUNCH_RETENTION_PROFILES.filter((profile) => profile.profession === profession);
}
