/**
 * Studio OS Ecosystem — AI Media workspace demo seeds & bootstrap.
 */

import { AI_MEDIA_WORKSPACE_ID } from '../../../studio-os-core/ai-media-network/constants';
import {
  bootstrapEcosystemStore,
  mergeEcosystemPatch,
  readEcosystemStore,
  refreshEcosystemRecommendations,
} from '../../../studio-os-core/ecosystem/store';
import type { EcosystemStore } from '../../../studio-os-core/ecosystem/types';

const WS = AI_MEDIA_WORKSPACE_ID;
const now = '2026-07-04T16:00:00.000Z';

export function buildEcosystemStorePatch(): Partial<EcosystemStore> {
  return {
    assets: [
      {
        id: 'eco-asset-media-bp',
        workspaceId: WS,
        title: 'Digital Media Network Company Blueprint',
        category: 'company-blueprint',
        creatorId: 'creator-studio-os',
        creatorName: 'Studio OS Labs',
        stage: 'published',
        description: 'Complete operating system for a digital media company — 5 pillars, 5 shows, network calendar, monetization, Labs integration.',
        version: '2.1.0',
        downloads: 1842,
        rating: 4.9,
        reviewCount: 124,
        favorites: 890,
        pricing: '$499 launch · 12% royalty',
        licenseModel: 'royalty',
        knowledgeGraphNodeId: 'node-eco-media-blueprint',
        featured: true,
        trending: true,
        createdAt: '2026-03-01T00:00:00.000Z',
        updatedAt: now,
      },
      {
        id: 'eco-asset-writing',
        workspaceId: WS,
        title: 'Finance Myth-Busting Writing Bible',
        category: 'writing-bible',
        creatorId: 'creator-maya',
        creatorName: 'Maya Chen',
        stage: 'published',
        description: 'Editorial standards, hook library, script frameworks for finance education content.',
        version: '2.0.1',
        downloads: 967,
        rating: 4.9,
        reviewCount: 88,
        favorites: 420,
        pricing: '$99 license',
        licenseModel: 'paid',
        knowledgeGraphNodeId: 'node-eco-writing-bible',
        featured: true,
        trending: false,
        createdAt: '2026-04-01T00:00:00.000Z',
        updatedAt: now,
      },
      {
        id: 'eco-asset-exec-cmo',
        workspaceId: WS,
        title: 'CMO · Growth Strategist Executive AI Team',
        category: 'executive-ai-team',
        creatorId: 'creator-studio-os',
        creatorName: 'Studio OS',
        stage: 'published',
        description: 'Specialized AI executives — Chief Marketing Officer, Growth Strategist, Partnership Director.',
        version: '1.3.0',
        downloads: 524,
        rating: 4.6,
        reviewCount: 42,
        favorites: 210,
        pricing: '$49/mo subscribe',
        licenseModel: 'subscription',
        knowledgeGraphNodeId: 'node-eco-exec-cmo',
        featured: true,
        trending: true,
        createdAt: '2026-05-01T00:00:00.000Z',
        updatedAt: now,
      },
      {
        id: 'eco-asset-auto-labs',
        workspaceId: WS,
        title: 'Publish → Labs Experiment Pipeline',
        category: 'automation-pack',
        creatorId: 'creator-studio-os',
        creatorName: 'Studio OS Labs',
        stage: 'published',
        description: 'Workflow automation — every publish creates experiment, feeds learning engine.',
        version: '1.0.2',
        downloads: 412,
        rating: 4.8,
        reviewCount: 36,
        favorites: 180,
        pricing: '$199',
        licenseModel: 'paid',
        knowledgeGraphNodeId: 'node-eco-auto-labs',
        featured: false,
        trending: true,
        createdAt: '2026-05-15T00:00:00.000Z',
        updatedAt: now,
      },
      {
        id: 'eco-asset-cdna',
        workspaceId: WS,
        title: 'Short-Form Thumbnail Creative DNA System',
        category: 'creative-dna',
        creatorId: 'creator-sam',
        creatorName: 'Sam Ortiz',
        stage: 'published',
        description: 'Photography + visual framework for short-form thumbnail systems.',
        version: '1.2.0',
        downloads: 678,
        rating: 4.8,
        reviewCount: 52,
        favorites: 340,
        pricing: '$149 license',
        licenseModel: 'paid',
        knowledgeGraphNodeId: 'node-eco-cdna-thumb',
        featured: true,
        trending: false,
        createdAt: '2026-04-20T00:00:00.000Z',
        updatedAt: now,
      },
      {
        id: 'eco-asset-newsletter-bp',
        workspaceId: WS,
        title: 'Newsletter Company Blueprint',
        category: 'company-blueprint',
        creatorId: 'creator-studio-os',
        creatorName: 'Studio OS',
        stage: 'review',
        description: 'Complete operating system for newsletter-first creator business.',
        version: '1.4.0',
        downloads: 0,
        rating: 0,
        reviewCount: 0,
        favorites: 12,
        pricing: '$299',
        licenseModel: 'paid',
        knowledgeGraphNodeId: 'node-eco-newsletter-bp',
        featured: false,
        trending: false,
        createdAt: '2026-06-28T00:00:00.000Z',
        updatedAt: now,
      },
      {
        id: 'eco-asset-podcast-bp',
        workspaceId: WS,
        title: 'Podcast Company Operating System',
        category: 'company-blueprint',
        creatorId: 'creator-pulse',
        creatorName: 'Pulse Creator Agency',
        stage: 'pilot',
        description: 'Launch a podcast company — shows, guests, monetization, distribution.',
        version: '0.9.0',
        downloads: 0,
        rating: 0,
        reviewCount: 0,
        favorites: 28,
        pricing: 'TBD',
        licenseModel: 'custom',
        knowledgeGraphNodeId: 'node-eco-podcast-bp',
        featured: false,
        trending: false,
        createdAt: '2026-07-01T00:00:00.000Z',
        updatedAt: now,
      },
    ],
    dependencies: [
      { id: 'dep-1', assetId: 'eco-asset-media-bp', requiresModule: 'memory-bible', label: 'Memory Bible', required: true },
      { id: 'dep-2', assetId: 'eco-asset-media-bp', requiresModule: 'labs', label: 'Studio OS Labs', required: true },
      { id: 'dep-3', assetId: 'eco-asset-media-bp', requiresModule: 'growth-network', label: 'Growth Network', required: false },
      { id: 'dep-4', assetId: 'eco-asset-auto-labs', requiresModule: 'labs', label: 'Studio OS Labs', required: true },
      { id: 'dep-5', assetId: 'eco-asset-auto-labs', requiresModule: 'distribution-network', label: 'Distribution Network', required: true },
      { id: 'dep-6', assetId: 'eco-asset-exec-cmo', requiresModule: 'executive-command-center', label: 'Executive Command Center', required: true },
      { id: 'dep-7', assetId: 'eco-asset-writing', requiresModule: 'content-brain', label: 'Content Brain', required: true },
      { id: 'dep-8', assetId: 'eco-asset-cdna', requiresModule: 'asset-factory', label: 'Asset Factory', required: false },
    ],
    reviews: [
      {
        id: 'rev-media-bp',
        assetId: 'eco-asset-media-bp',
        quality: 'pass',
        documentation: 'pass',
        compatibility: 'pass',
        dependencies: 'pass',
        security: 'pass',
        licensing: 'pass',
        versioning: 'pass',
        studioOsCompatibility: 'Milestone 29+ · AI Media Network required',
      },
      {
        id: 'rev-newsletter',
        assetId: 'eco-asset-newsletter-bp',
        quality: 'pass',
        documentation: 'pending',
        compatibility: 'pass',
        dependencies: 'pass',
        security: 'pass',
        licensing: 'pass',
        versioning: 'pending',
        studioOsCompatibility: 'Milestone 32+ · Business Model Engine recommended',
      },
    ],
    installs: [
      {
        id: 'inst-media-bp',
        workspaceId: WS,
        assetId: 'eco-asset-media-bp',
        assetTitle: 'Digital Media Network Company Blueprint',
        version: '2.1.0',
        installedAt: '2026-04-01T00:00:00.000Z',
        status: 'active',
        backupCreated: true,
        dependenciesInstalled: ['memory-bible', 'labs', 'growth-network'],
        kgUpdated: true,
        memoryBibleUpdated: true,
      },
      {
        id: 'inst-auto-labs',
        workspaceId: WS,
        assetId: 'eco-asset-auto-labs',
        assetTitle: 'Publish → Labs Experiment Pipeline',
        version: '1.0.2',
        installedAt: '2026-05-20T00:00:00.000Z',
        status: 'active',
        backupCreated: true,
        dependenciesInstalled: ['labs', 'distribution-network'],
        kgUpdated: true,
        memoryBibleUpdated: false,
      },
    ],
    versions: [
      { id: 'ver-media-21', assetId: 'eco-asset-media-bp', version: '2.1.0', type: 'minor', releaseNotes: 'Labs bridge + monetization center integration', compatibilityMatrix: 'Studio OS 29+', publishedAt: '2026-06-01' },
      { id: 'ver-media-20', assetId: 'eco-asset-media-bp', version: '2.0.0', type: 'major', releaseNotes: 'AI Media Network v1 launch alignment', compatibilityMatrix: 'Studio OS 29+', publishedAt: '2026-04-01' },
      { id: 'ver-auto-102', assetId: 'eco-asset-auto-labs', version: '1.0.2', type: 'patch', releaseNotes: 'Fixed experiment ID collision on rapid publish', compatibilityMatrix: 'Labs 1.0+', publishedAt: '2026-06-15' },
    ],
    creators: [
      { id: 'creator-studio-os', displayName: 'Studio OS Labs', verified: true, followers: 4200, assetsPublished: 12, totalDownloads: 8420, reputation: 96, badges: ['VERIFIED CREATOR', 'FEATURED', 'BLUEPRINT ARCHITECT'], featured: true },
      { id: 'creator-maya', displayName: 'Maya Chen', verified: true, followers: 890, assetsPublished: 3, totalDownloads: 1240, reputation: 91, badges: ['VERIFIED CREATOR', 'WRITING BIBLE AUTHOR'], featured: true },
      { id: 'creator-sam', displayName: 'Sam Ortiz', verified: true, followers: 420, assetsPublished: 2, totalDownloads: 890, reputation: 88, badges: ['CREATIVE DNA DESIGNER'], featured: false },
      { id: 'creator-pulse', displayName: 'Pulse Creator Agency', verified: false, followers: 210, assetsPublished: 1, totalDownloads: 0, reputation: 72, badges: ['PILOT CREATOR'], featured: false },
    ],
    analytics: {
      totalDownloads: 4423,
      activeInstalls: 892,
      retentionPct: 87,
      avgRating: 4.8,
      totalRevenue: 28400,
      subscriptionRevenue: 6200,
      renewalPct: 78,
      updateAdoptionPct: 64,
      supportRequests: 24,
      satisfactionScore: 92,
    },
    enterpriseLibraries: [
      {
        id: 'ent-lib-fs',
        organizationName: 'Frontal Slayer Holdings (private ecosystem)',
        privateBlueprints: 4,
        privateExecutives: 6,
        privateAutomations: 12,
        privateMarketplace: true,
      },
    ],
    hubCards: [
      { id: 'hub-1', type: 'blueprint', title: 'Digital Media Network Blueprint', subtitle: 'TOP DOWNLOAD · 1,842 installs', assetId: 'eco-asset-media-bp' },
      { id: 'hub-2', type: 'executive', title: 'CMO · Growth Strategist Team', subtitle: 'TRENDING · 524 downloads', assetId: 'eco-asset-exec-cmo' },
      { id: 'hub-3', type: 'creative-dna', title: 'Thumbnail Creative DNA', subtitle: 'FEATURED · Sam Ortiz', assetId: 'eco-asset-cdna' },
      { id: 'hub-4', type: 'writing-bible', title: 'Finance Myth-Busting Bible', subtitle: '★ 4.9 · Maya Chen', assetId: 'eco-asset-writing' },
      { id: 'hub-5', type: 'automation', title: 'Publish → Labs Pipeline', subtitle: 'NEW RELEASE · v1.0.2', assetId: 'eco-asset-auto-labs' },
      { id: 'hub-6', type: 'creator', title: 'Studio OS Labs', subtitle: 'VERIFIED · 12 assets', assetId: undefined },
      { id: 'hub-7', type: 'workspace', title: 'AI Media Network', subtitle: 'FEATURED WORKSPACE · PILOT', assetId: undefined },
      { id: 'hub-8', type: 'enterprise', title: 'Frontal Slayer Private Library', subtitle: 'ENTERPRISE ECOSYSTEM', assetId: undefined },
    ],
  };
}

export function bootstrapAiMediaEcosystem(): void {
  bootstrapEcosystemStore();
  const store = readEcosystemStore();
  if (store.assets.length > 0) return;
  mergeEcosystemPatch(buildEcosystemStorePatch());
  refreshEcosystemRecommendations(WS);
}
