import { bootstrapKnowledgeAssetEngineStore } from './store';
import type { KnowledgeAssetEngineStore, KnowledgeAssetProfile } from './types';

export function buildKnowledgeAssetEngineSeed(): Partial<KnowledgeAssetEngineStore> {
  const assets: KnowledgeAssetProfile[] = [
    {
      id: 'kae-page-042',
      knowledgeAssetId: 'KA-042-MONEY-HABITS',
      workspaceId: 'ndxbook',
      title: 'PAGE 042 · MONEY HABITS CHAPTER',
      description: 'Research-gated money habits · stat-forward · Money Monday anchor content · Labs-validated patterns',
      assetType: 'page',
      owner: 'NDXBOOK Editorial',
      organization: 'NDXBOOK',
      origin: 'Newsroom · Page strategy',
      version: '3.2.0',
      status: 'approved',
      maturityStage: 'institutional',
      knowledgeMaturityPct: 88,
      confidencePct: 92,
      qualityScore: 91,
      knowledgeScore: 92,
      usageCount: 847,
      contributors: ['Editorial', 'Labs', 'Distribution Engine'],
      lastUpdated: '2026-06-20',
      futurePotential: 'Course module · ebook chapter · executive finance briefing',
      distributionEngineId: 'ka-page-042',
      campaignId: 'camp-money-monday-mar',
    },
    {
      id: 'kae-truth-sleep',
      knowledgeAssetId: 'KA-041-SLEEP-DEBT',
      workspaceId: 'ndxbook',
      title: 'TRUTH TUESDAY · SLEEP DEBT',
      description: 'Evergreen health fact · research-gated · Truth Tuesday cadence · advocate pipeline driver',
      assetType: 'page',
      owner: 'NDXBOOK Health Desk',
      organization: 'NDXBOOK',
      origin: 'Newsroom · Truth Tuesday',
      version: '2.1.0',
      status: 'evergreen',
      maturityStage: 'timeless',
      knowledgeMaturityPct: 95,
      confidencePct: 94,
      qualityScore: 93,
      knowledgeScore: 95,
      usageCount: 1240,
      contributors: ['Health Desk', 'Reader Graph', 'Relationship Engine'],
      lastUpdated: '2026-05-10',
      futurePotential: 'Wellness course · creator collab · podcast series anchor',
      distributionEngineId: 'ka-truth-sleep',
      campaignId: 'camp-truth-tuesday',
    },
    {
      id: 'kae-page-028',
      knowledgeAssetId: 'KA-028-CROSS-PLATFORM',
      workspaceId: 'ndxbook',
      title: 'PAGE 028 · CROSS-PLATFORM CORE',
      description: 'Cross-platform distribution anchor · mind volume crossover · multi-channel adaptation source',
      assetType: 'page',
      owner: 'NDXBOOK Editorial',
      organization: 'NDXBOOK',
      origin: 'Newsroom · Page 028',
      version: '1.4.0',
      status: 'published',
      maturityStage: 'validated',
      knowledgeMaturityPct: 72,
      confidencePct: 78,
      qualityScore: 80,
      knowledgeScore: 85,
      usageCount: 412,
      contributors: ['Editorial', 'Distribution Engine'],
      lastUpdated: '2026-06-28',
      futurePotential: 'Podcast outline · course lesson · internal training',
      distributionEngineId: 'ka-page-028',
      campaignId: 'camp-page-028',
    },
    {
      id: 'kae-leadership-dna',
      knowledgeAssetId: 'KA-LDNA-V1',
      workspaceId: 'studio-os',
      title: 'LEADERSHIP DNA · FOUNDER OPERATING BLUEPRINT',
      description: 'Delegation modes · soft approval · escalation routing · CoS evaluation framework',
      assetType: 'company-dna',
      owner: 'VXD · Studio OS',
      organization: 'STUDIO OS',
      origin: 'Leadership DNA module',
      version: '1.8.0',
      status: 'approved',
      maturityStage: 'foundational',
      knowledgeMaturityPct: 89,
      confidencePct: 91,
      qualityScore: 94,
      knowledgeScore: 96,
      usageCount: 623,
      contributors: ['VXD', 'Chief of Staff', 'Executive Organization'],
      lastUpdated: '2026-05-22',
      futurePotential: 'Executive education · inheritance package · marketplace asset',
    },
    {
      id: 'kae-newsroom-playbook',
      knowledgeAssetId: 'KA-NEWSROOM-PB',
      workspaceId: 'ndxbook',
      title: 'NEWSROOM OPERATING PLAYBOOK',
      description: 'Editorial cadence · page strategy · QA gates · CoS approval · Labs integration',
      assetType: 'playbook',
      owner: 'NDXBOOK Editorial',
      organization: 'NDXBOOK',
      origin: 'Ecosystem Marketplace · Organizational asset',
      version: '2.4.1',
      status: 'approved',
      maturityStage: 'institutional',
      knowledgeMaturityPct: 92,
      confidencePct: 93,
      qualityScore: 90,
      knowledgeScore: 91,
      usageCount: 534,
      contributors: ['Editorial', 'Strategy Engine', 'Campaign Engine'],
      lastUpdated: '2026-06-15',
      futurePotential: 'Media company inheritance · academy course · certification path',
    },
  ];

  return {
    dashboard: {
      summary:
        'KNOWLEDGE ASSET ENGINE V1.0 — foundational object model for Studio OS. Everything is a knowledge asset · living organizational intelligence · single source of truth · knowledge compounds forever.',
      totalAssets: 0,
      canonicalSources: 0,
      avgMaturityPct: 0,
      derivedFormats: 0,
      academyPaths: 0,
      knowledgeHealthPct: 87,
    },
    activeWorkspaceId: 'ndxbook',
    assets,
    singleSourceOfTruth: [
      {
        canonicalAssetId: 'kae-page-042',
        canonicalTitle: 'PAGE 042 · MONEY HABITS CHAPTER',
        derivedAssets: [
          { id: 'der-1', parentAssetId: 'kae-page-042', format: 'Instagram Reel', title: 'MONEY HABITS · REEL', status: 'published', lastSynced: '2026-06-18' },
          { id: 'der-2', parentAssetId: 'kae-page-042', format: 'YouTube Short', title: 'MONEY HABITS · SHORT', status: 'published', lastSynced: '2026-06-18' },
          { id: 'der-3', parentAssetId: 'kae-page-042', format: 'Newsletter', title: 'MONEY MONDAY · NL FEATURE', status: 'published', lastSynced: '2026-06-19' },
          { id: 'der-4', parentAssetId: 'kae-page-042', format: 'Podcast Outline', title: 'MONEY HABITS · PODCAST', status: 'approved', lastSynced: '2026-06-15' },
          { id: 'der-5', parentAssetId: 'kae-page-042', format: 'Course Lesson', title: 'FINANCE 101 · LESSON 3', status: 'draft', lastSynced: '2026-06-10' },
        ],
        syncRecommendation: 'Update v3.2 stat overlay → recommend refresh on Reel + Short + Newsletter derived assets',
      },
      {
        canonicalAssetId: 'kae-truth-sleep',
        canonicalTitle: 'TRUTH TUESDAY · SLEEP DEBT',
        derivedAssets: [
          { id: 'der-6', parentAssetId: 'kae-truth-sleep', format: 'Instagram Reel', title: 'SLEEP DEBT · REEL', status: 'evergreen', lastSynced: '2026-05-08' },
          { id: 'der-7', parentAssetId: 'kae-truth-sleep', format: 'Newsletter', title: 'TRUTH TUESDAY · NL', status: 'evergreen', lastSynced: '2026-05-08' },
          { id: 'der-8', parentAssetId: 'kae-truth-sleep', format: 'YouTube Short', title: 'SLEEP DEBT · SHORT', status: 'published', lastSynced: '2026-05-01' },
        ],
        syncRecommendation: 'Timeless asset · no refresh needed · monitor advocate pipeline linkage',
      },
    ],
    evolutions: [
      {
        assetId: 'kae-page-042',
        versions: [
          { version: '3.2.0', date: '2026-06-20', summary: 'Labs #38 stat overlay validated · +18% CTR', contributor: 'Labs' },
          { version: '3.1.0', date: '2026-05-01', summary: 'Money Monday cadence alignment', contributor: 'Editorial' },
          { version: '3.0.0', date: '2026-03-15', summary: 'Research-gated rewrite · fact-forward tone', contributor: 'Health Desk' },
        ],
        feedback: ['Strong completion rate', 'Affiliate link performance above avg', 'Reader requests deeper dive'],
        readerInsights: ['95% completion on TikTok · 51s avg watch', 'Returning reader cluster +12%'],
        performanceTrend: '+18% CTR · +28% reach vs v3.1',
        institutionalLearning: ['Stat overlay pattern → Labs playbook', 'Money Monday timing → Campaign Engine'],
        accuracyImprovementPct: 8,
      },
      {
        assetId: 'kae-truth-sleep',
        versions: [
          { version: '2.1.0', date: '2026-05-10', summary: 'Evergreen status · advocate pipeline integration', contributor: 'Relationship Engine' },
          { version: '2.0.0', date: '2025-12-01', summary: 'Research update · sleep debt stat refresh', contributor: 'Health Desk' },
        ],
        feedback: ['Highest share rate in health category', '5 advocate referrals traced'],
        readerInsights: ['Advocate behavior cluster · Jordan T pipeline'],
        performanceTrend: 'Stable evergreen · 91% retention',
        institutionalLearning: ['Truth Tuesday → Creator Marketplace collab template'],
        accuracyImprovementPct: 12,
      },
    ],
    lineage: [
      { id: 'lin-1', assetId: 'kae-page-042', label: 'ORIGIN', relation: 'origin', targetLabel: 'Newsroom · pg-042' },
      { id: 'lin-2', assetId: 'kae-page-042', label: 'CAMPAIGN', relation: 'campaign', targetLabel: 'MONEY MONDAY · MARCH CYCLE' },
      { id: 'lin-3', assetId: 'kae-page-042', label: 'STRATEGY', relation: 'strategy', targetLabel: '100K READERS · AUTHORITY GOAL' },
      { id: 'lin-4', assetId: 'kae-page-042', label: 'DERIVED', relation: 'derived', targetLabel: '5 format adaptations' },
      { id: 'lin-5', assetId: 'kae-truth-sleep', label: 'READER', relation: 'community', targetLabel: 'Jordan T · advocate pipeline' },
      { id: 'lin-6', assetId: 'kae-truth-sleep', label: 'MARKETPLACE', relation: 'marketplace', targetLabel: 'Creator collab template' },
      { id: 'lin-7', assetId: 'kae-leadership-dna', label: 'EXECUTIVE', relation: 'executive', targetLabel: 'Chief of Staff · evaluation source' },
      { id: 'lin-8', assetId: 'kae-leadership-dna', label: 'INHERITANCE', relation: 'cross-company', targetLabel: 'Organizational Inheritance · all new companies' },
    ],
    maturityMetrics: [
      { assetId: 'kae-page-042', accuracyPct: 91, adoptionPct: 88, reusePct: 76, longevityPct: 82, readerValuePct: 89, communityImpactPct: 72, organizationalImportancePct: 90, learningContributionPct: 85, stage: 'institutional' },
      { assetId: 'kae-truth-sleep', accuracyPct: 94, adoptionPct: 92, reusePct: 88, longevityPct: 96, readerValuePct: 93, communityImpactPct: 91, organizationalImportancePct: 88, learningContributionPct: 90, stage: 'timeless' },
      { assetId: 'kae-page-028', accuracyPct: 78, adoptionPct: 65, reusePct: 58, longevityPct: 70, readerValuePct: 72, communityImpactPct: 55, organizationalImportancePct: 68, learningContributionPct: 60, stage: 'validated' },
    ],
    relationships: [
      { id: 'rel-1', assetId: 'kae-page-042', type: 'campaign', targetId: 'camp-money-monday-mar', targetLabel: 'MONEY MONDAY · MARCH' },
      { id: 'rel-2', assetId: 'kae-page-042', type: 'strategy', targetId: 'strat-100k-readers', targetLabel: '100K READERS INITIATIVE' },
      { id: 'rel-3', assetId: 'kae-page-042', type: 'department', targetId: 'dept-editorial', targetLabel: 'EDITORIAL · NEWSROOM' },
      { id: 'rel-4', assetId: 'kae-truth-sleep', type: 'reader', targetId: 'reader-jordan-t', targetLabel: 'JORDAN T · ADVOCATE' },
      { id: 'rel-5', assetId: 'kae-truth-sleep', type: 'community', targetId: 'comm-health-curious', targetLabel: 'HEALTH-CURIOUS CLUSTER' },
      { id: 'rel-6', assetId: 'kae-leadership-dna', type: 'executive', targetId: 'exec-cos', targetLabel: 'CHIEF OF STAFF' },
    ],
    transformations: [
      { id: 'tx-1', sourceAssetId: 'kae-page-042', targetFormat: 'video', label: 'INSTAGRAM REEL · STAT OVERLAY', preservesSourceOfTruth: true, status: 'complete' },
      { id: 'tx-2', sourceAssetId: 'kae-page-042', targetFormat: 'newsletter', label: 'MONEY MONDAY FEATURE', preservesSourceOfTruth: true, status: 'complete' },
      { id: 'tx-3', sourceAssetId: 'kae-page-042', targetFormat: 'course', label: 'FINANCE 101 · LESSON 3', preservesSourceOfTruth: true, status: 'in-progress' },
      { id: 'tx-4', sourceAssetId: 'kae-page-042', targetFormat: 'ebook', label: 'MONEY HABITS · CHAPTER', preservesSourceOfTruth: true, status: 'recommended' },
      { id: 'tx-5', sourceAssetId: 'kae-truth-sleep', targetFormat: 'podcast', label: 'WELLNESS PODCAST · EPISODE', preservesSourceOfTruth: true, status: 'recommended' },
      { id: 'tx-6', sourceAssetId: 'kae-truth-sleep', targetFormat: 'presentation', label: 'CONFERENCE · HEALTH TALK', preservesSourceOfTruth: true, status: 'available' },
    ],
    intelligenceRecs: [
      { id: 'intel-1', assetId: 'kae-page-042', action: 'refresh', label: 'REFRESH DERIVED REEL + SHORT', confidencePct: 91, rationale: 'v3.2 stat overlay validated · derived assets on v3.1', expectedImpact: '+12% CTR on derived formats' },
      { id: 'intel-2', assetId: 'kae-page-042', action: 'teach', label: 'ADD TO FINANCE ACADEMY PATH', confidencePct: 88, rationale: 'Reader requests deeper dive · course lesson in draft', expectedImpact: 'Passive revenue · reader retention +15%' },
      { id: 'intel-3', assetId: 'kae-page-042', action: 'monetize', label: 'LICENSE TO ECOSYSTEM MARKETPLACE', confidencePct: 82, rationale: 'Institutional maturity · 12 company adoptions potential', expectedImpact: '$2K/quarter licensing' },
      { id: 'intel-4', assetId: 'kae-truth-sleep', action: 'combine', label: 'BUNDLE WITH CREATOR COLLAB', confidencePct: 85, rationale: 'Jordan T advocate pipeline · 94% alignment', expectedImpact: 'Ambassador content · 3 new advocates' },
      { id: 'intel-5', assetId: 'kae-truth-sleep', action: 'deepen', label: 'WELLNESS COURSE MODULE', confidencePct: 79, rationale: 'Timeless asset · highest share rate · course demand signal', expectedImpact: '$8K/quarter passive revenue' },
      { id: 'intel-6', assetId: 'kae-page-028', action: 'expand', label: 'PODCAST + COURSE TRANSFORMS', confidencePct: 76, rationale: 'Cross-platform underperforming vs Page 042 · untapped formats', expectedImpact: '2x reach on mind content' },
    ],
    revenue: {
      'kae-page-042': {
        assetId: 'kae-page-042',
        totalRevenue: '$1,240/mo',
        channels: [
          { channel: 'Affiliate', amount: '$840' },
          { channel: 'Newsletter sponsor', amount: '$400' },
        ],
        forecast: '+22% with course module launch',
        monetizationPotential: 'Course · ebook · marketplace license · consulting',
      },
      'kae-truth-sleep': {
        assetId: 'kae-truth-sleep',
        totalRevenue: '$600/mo affiliate',
        channels: [{ channel: 'Affiliate', amount: '$600' }],
        forecast: 'Stable evergreen · course unlocks +$8K/quarter',
        monetizationPotential: 'Wellness course · creator collab · certification',
      },
    },
    academyPaths: [
      { id: 'acad-1', title: 'FINANCE 101 · MONEY MONDAY PATH', type: 'learning-path', assetIds: ['kae-page-042'], description: 'Stat-forward finance education · Money Monday cadence · reader to member', progressPct: 45 },
      { id: 'acad-2', title: 'WELLNESS · TRUTH TUESDAY CERT', type: 'certification', assetIds: ['kae-truth-sleep'], description: 'Research-gated health facts · advocate pipeline · community education', progressPct: 20 },
      { id: 'acad-3', title: 'EXECUTIVE LEADERSHIP · CoS TRAINING', type: 'executive-ed', assetIds: ['kae-leadership-dna'], description: 'Leadership DNA · delegation · soft approval · escalation', progressPct: 78 },
      { id: 'acad-4', title: 'NEWSROOM ONBOARDING', type: 'onboarding', assetIds: ['kae-newsroom-playbook'], description: 'New editorial team · page strategy · QA gates · cadence', progressPct: 60 },
    ],
    executiveLinks: [
      { id: 'exec-1', executiveRole: 'CHIEF MARKETING OFFICER', assetIds: ['kae-page-042', 'kae-newsroom-playbook'], trainingFocus: 'Marketing playbooks · campaign frameworks · stat-forward content' },
      { id: 'exec-2', executiveRole: 'CHIEF CREATIVE OFFICER', assetIds: ['kae-page-028'], trainingFocus: 'Creative systems · cross-platform adaptation · visual standards' },
      { id: 'exec-3', executiveRole: 'CHIEF OF STAFF', assetIds: ['kae-leadership-dna'], trainingFocus: 'Leadership decisions · soft approval · delegation · escalation routing' },
    ],
    inheritancePackages: [
      { id: 'inh-1', industry: 'Media · Digital publishing', assetIds: ['kae-newsroom-playbook', 'kae-page-042'], description: 'Newsroom + editorial knowledge for media companies', preservesEvolution: true },
      { id: 'inh-2', industry: 'Cross-industry · Leadership', assetIds: ['kae-leadership-dna'], description: 'Leadership DNA for any new Studio OS company', preservesEvolution: true },
      { id: 'inh-3', industry: 'Education · Wellness', assetIds: ['kae-truth-sleep'], description: 'Evergreen health knowledge · course-ready · community education', preservesEvolution: true },
    ],
    health: {
      overallPct: 87,
      connectedAssetsPct: 94,
      orphanedAssets: 0,
      staleAssets: 1,
      avgMaturityPct: 85,
      revenueGenerating: 2,
    },
    selectedAssetId: 'kae-page-042',
  };
}

export function bootstrapKnowledgeAssetEnginePlatform(): void {
  bootstrapKnowledgeAssetEngineStore(buildKnowledgeAssetEngineSeed());
}
