import { bootstrapOrganizationalIntelligenceStore } from './store';
import type { OrganizationalIntelligenceStore } from './types';

export function buildOrganizationalIntelligenceSeed(): Partial<OrganizationalIntelligenceStore> {
  return {
    companyName: 'NDXBOOK',
    activeWorkspaceId: 'ndxbook',
    dashboard: {
      summary:
        'ORGANIZATIONAL INTELLIGENCE V1.0 — collective mind of the company · accumulated wisdom that compounds every day.',
      wisdomPct: 84,
      learningVelocityPct: 79,
      knowledgeMaturityPct: 81,
      eventsObserved: 1247,
      activeQuestions: 8,
      forecastsActive: 6,
      memoryEntries: 342,
    },
    continuousLearning: [
      { id: 'cl-1', source: 'Executive Council', event: '100K GTM council session · healthy disagreement on scale timing', category: 'Executive debates', capturedAt: '2026-07-05' },
      { id: 'cl-2', source: 'Campaign Engine', event: 'Newsletter distribution expansion outperforming social hooks', category: 'Campaigns', capturedAt: '2026-07-04' },
      { id: 'cl-3', source: 'Reader Graph', event: 'Engagement spike on stat-forward editorial hooks · retention stable', category: 'Reader behavior', capturedAt: '2026-07-04' },
      { id: 'cl-4', source: 'Relationship Engine', event: '12K engaged readers · advocacy pathway emerging', category: 'Relationships', capturedAt: '2026-07-03' },
      { id: 'cl-5', source: 'Chief Experience Officer', event: 'Onboarding friction identified as scale gate · score 72', category: 'Customer interactions', capturedAt: '2026-07-03' },
      { id: 'cl-6', source: 'Creator Marketplace', event: 'Pilot approved · 10 curated creators · quality gates active', category: 'Creator ecosystem', capturedAt: '2026-07-02' },
      { id: 'cl-7', source: 'Chief Growth Officer', event: 'Paid acquisition blocked · vanity metrics precedent preserved', category: 'Financial decisions', capturedAt: '2026-06-28' },
      { id: 'cl-8', source: 'Knowledge Asset Engine', event: 'Writing DNA quality gates encoded in creator onboarding', category: 'Knowledge assets', capturedAt: '2026-07-01' },
    ],
    organizationalReasoning: [
      { id: 'or-1', question: 'What happened?', answer: 'Council deferred 100K GTM until onboarding score exceeds 85 · phased 5K pilot recommended', confidence: 91 },
      { id: 'or-2', question: 'Why did it happen?', answer: 'Trust-before-scale pattern · onboarding friction · executive consensus on relationship metrics over vanity', confidence: 89 },
      { id: 'or-3', question: 'What patterns are emerging?', answer: 'Stat-forward editorial hooks consistently outperform generic templates · organic relationship growth compounds', confidence: 87 },
      { id: 'or-4', question: 'What should we preserve?', answer: 'Brand voice rejection of generic media · paid acquisition block precedent · council healthy disagreement model', confidence: 92 },
      { id: 'or-5', question: 'What should never happen again?', answer: 'Vanity metric acquisition · hype-driven creative · scale before trust foundation', confidence: 94 },
      { id: 'or-6', question: 'What opportunities are appearing?', answer: 'Creator marketplace · reader spotlight community · membership tier editorial depth rewards', confidence: 86 },
      { id: 'or-7', question: 'What is likely to happen next?', answer: 'Onboarding fix unlocks phased GTM · creator pilot generates ecosystem learning · retention compounding', confidence: 82 },
    ],
    crossSystemIntelligence: [
      { id: 'csi-1', fromSystem: 'Reader Graph', toSystem: 'Campaign Engine', insight: 'Stat-forward hook engagement signals → campaign creative optimization' },
      { id: 'csi-2', fromSystem: 'Campaign Engine', toSystem: 'Experience Architect', insight: 'Newsletter distribution success → onboarding touchpoint alignment' },
      { id: 'csi-3', fromSystem: 'Relationship Engine', toSystem: 'Growth Architect', insight: 'Retention health 89% → sustainable GTM validation over vanity acquisition' },
      { id: 'csi-4', fromSystem: 'Executive Council', toSystem: 'Company Genome', insight: 'Trust-before-scale decision encoded in organizational DNA' },
      { id: 'csi-5', fromSystem: 'Knowledge Graph', toSystem: 'Chief Brand Officer', insight: 'Creative review precedents → brand governance intelligence for every executive' },
      { id: 'csi-6', fromSystem: 'Company Genome', toSystem: 'Brand Architect', insight: 'Organizational DNA strengthens stat-forward brand identity consistency' },
    ],
    organizationalCuriosity: [
      { id: 'oc-1', question: 'Why has engagement changed on long-form editorial vs stat-forward hooks?', category: 'Reader behavior', priority: 'high' },
      { id: 'oc-2', question: 'What caused newsletter distribution to outperform social channel tests?', category: 'Campaign performance', priority: 'medium' },
      { id: 'oc-3', question: 'Which decisions consistently produce exceptional outcomes?', category: 'Decision patterns', priority: 'high' },
      { id: 'oc-4', question: 'What organizational habit is quietly creating onboarding friction risk?', category: 'Operational risk', priority: 'high' },
      { id: 'oc-5', question: 'What relationship deserves more investment — creators or reader advocates?', category: 'Relationship investment', priority: 'medium' },
      { id: 'oc-6', question: 'Where is knowledge no longer flowing between executives and architects?', category: 'Knowledge flow', priority: 'low' },
      { id: 'oc-7', question: 'What assumptions about paid acquisition have we stopped questioning?', category: 'Strategic assumptions', priority: 'medium' },
    ],
    decisionIntelligence: [
      {
        id: 'di-1',
        decision: '100K readers GTM sequencing',
        historicalContext: 'First 12K organic succeeded · paid test blocked June 2026 · generic template rejected Dec 2025',
        evidence: 'Council synthesis 89% confidence · onboarding score 72 · relationship health 89%',
        alternatives: 'Full launch now · 5K pilot · defer to Q4',
        tradeoffs: '4-6 week delay preserves trust · smaller cohort · higher LTV',
        confidence: 89,
        longTermImpact: 'Trust-before-scale becomes institutional precedent · future generations inherit pattern',
      },
      {
        id: 'di-2',
        decision: 'Creator marketplace pilot expansion',
        historicalContext: 'Writing DNA gates established · 10 creator pilot approved with CBO validation',
        evidence: 'Brand alignment 91% · ecosystem expansion opportunity · low brand risk',
        alternatives: 'Expand to 25 creators · maintain 10 · defer expansion',
        tradeoffs: 'Quality vs speed · curation overhead vs ecosystem depth',
        confidence: 88,
        longTermImpact: 'Creator economy becomes compounding knowledge and revenue stream',
      },
    ],
    organizationalReflection: [
      {
        id: 'ref-w1',
        period: 'weekly',
        title: 'Week of July 1 · Trust before scale',
        lessons: ['Council healthy disagreement improved GTM criteria', 'Onboarding friction is organizational scale gate'],
        breakthroughs: ['Executive council decision synthesis model validated'],
        mistakes: [],
        priorities: ['Resolve onboarding · phased GTM pilot · creator marketplace kickoff'],
      },
      {
        id: 'ref-m1',
        period: 'monthly',
        title: 'June 2026 · Relationship-driven growth',
        lessons: ['Paid acquisition blocked preserves brand integrity', 'Organic 12K engaged readers validates relationship-first GTM'],
        breakthroughs: ['Creator marketplace pilot approved · council oath applied to debate'],
        mistakes: ['Near-miss on paid social test — caught by CGO and council'],
        priorities: ['100K GTM council decision · membership tier design · community spotlight'],
      },
      {
        id: 'ref-q1',
        period: 'quarterly',
        title: 'Q2 2026 · Executive maturity',
        lessons: ['C-suite pipeline complete through CGO · council V2.0 operational'],
        breakthroughs: ['Full executive chain connected to genome and KG'],
        mistakes: [],
        priorities: ['Organizational intelligence center · cross-system learning velocity'],
      },
    ],
    organizationalWisdom: [
      { id: 'ow-1', level: 'information', example: 'Customer churn increased on onboarding step 3', context: 'Raw metric from Reader Graph' },
      { id: 'ow-2', level: 'knowledge', example: 'Customers left after onboarding became more complex', context: 'Pattern across 3 cohorts' },
      { id: 'ow-3', level: 'understanding', example: 'Feature additions increased cognitive load without value alignment', context: 'CEO journey analysis + council debate' },
      { id: 'ow-4', level: 'wisdom', example: 'Organizations grow when onboarding becomes simpler — not when it impresses', context: 'Encoded in genome · council precedent · future generation inheritance' },
    ],
    institutionalMemory: [
      { id: 'im-1', category: 'DECISION', memory: 'Paid acquisition blocked · vanity metrics · council unanimous on relationship-first path', preservedAt: '2026-06-28' },
      { id: 'im-2', category: 'EXECUTIVE DEBATE', memory: '100K GTM council session · 5 perspectives · phased pilot synthesis', preservedAt: '2026-07-05' },
      { id: 'im-3', category: 'CREATIVE BREAKTHROUGH', memory: 'Stat-forward editorial hooks outperform generic templates consistently', preservedAt: '2026-06-15' },
      { id: 'im-4', category: 'FOUNDER PHILOSOPHY', memory: 'Trust before scale · relationship metrics over vanity numbers', preservedAt: '2026-07-05' },
      { id: 'im-5', category: 'CUSTOMER STORY', memory: 'First 12K organic readers · no paid hacks · advocacy emerging', preservedAt: '2026-06-01' },
      { id: 'im-6', category: 'LEADERSHIP LESSON', memory: 'Generic media template rejected · brand voice preserved · December 2025', preservedAt: '2025-12-10' },
    ],
    organizationalForecasting: [
      { id: 'of-1', dimension: 'Customer behavior', prediction: 'Retention improves 8-12% after onboarding simplification', confidence: 78, uncertainty: 'Depends on auth refactor timeline · CEO initiative scope' },
      { id: 'of-2', dimension: 'Organizational growth', prediction: 'Phased 5K GTM achieves higher LTV than full 100K premature launch', confidence: 85, uncertainty: 'Market timing · competitive movement' },
      { id: 'of-3', dimension: 'Knowledge maturity', prediction: 'Cross-system intelligence velocity increases 15% with OI center operational', confidence: 72, uncertainty: 'Executive adoption · automation depth' },
      { id: 'of-4', dimension: 'Relationship evolution', prediction: 'Creator marketplace generates 3x advocacy pathway vs paid acquisition', confidence: 81, uncertainty: 'Creator quality gate enforcement · pilot size' },
      { id: 'of-5', dimension: 'Future risks', prediction: 'Onboarding debt becomes crisis if GTM pressure overrides council decision', confidence: 88, uncertainty: 'Founder judgment · stakeholder pressure' },
      { id: 'of-6', dimension: 'Executive workload', prediction: 'Council simulation demand increases with organizational maturity', confidence: 76, uncertainty: 'Meeting mode adoption rate' },
    ],
    intelligenceCenter: [
      { id: 'ic-1', element: 'Knowledge connections', description: 'Living graph of cross-system insights · no system operates independently', location: 'Organizational Intelligence Center · Architect Studio · central hall' },
      { id: 'ic-2', element: 'Organizational reasoning', description: 'Transparent what/why/pattern/opportunity/next reasoning display', location: 'Reasoning wall' },
      { id: 'ic-3', element: 'Learning velocity', description: 'Events observed · wisdom elevation rate · knowledge maturity trajectory', location: 'Velocity dashboard' },
      { id: 'ic-4', element: 'Executive intelligence', description: 'Historical context and lessons available to every C-suite executive', location: 'Executive support hub' },
      { id: 'ic-5', element: 'Relationship networks', description: 'Reader · creator · partner relationship intelligence overlay', location: 'Network visualization' },
      { id: 'ic-6', element: 'Future predictions', description: 'Forecasts with honest confidence and uncertainty · not overwhelming analytics', location: 'Forecast chamber' },
      { id: 'ic-7', element: 'Institutional memory', description: 'Decisions · debates · breakthroughs · traditions preserved for generations', location: 'Memory archive' },
      { id: 'ic-8', element: 'Wisdom evolution', description: 'Information → knowledge → understanding → wisdom elevation tracker', location: 'Wisdom spiral' },
    ],
    executiveIntegration: [
      { id: 'ei-1', executive: 'Chief Brand Officer', support: 'Creative review precedents · brand memory · generic template rejection history', insight: 'Every campaign inherits brand governance intelligence' },
      { id: 'ei-2', executive: 'Chief Experience Officer', support: 'Onboarding friction patterns · journey intelligence · trust-before-scale lessons', insight: 'Customer experience decisions grounded in accumulated wisdom' },
      { id: 'ei-3', executive: 'Chief Growth Officer', support: 'Paid acquisition block precedent · organic compounding data · relationship metrics history', insight: 'Growth decisions validated against institutional memory' },
      { id: 'ei-4', executive: 'Chief of Staff', support: 'Council decision history · escalation patterns · founder decision learning', insight: 'Facilitation informed by organizational reasoning archive' },
      { id: 'ei-5', executive: 'Chief Technology Officer', support: 'Auth debt lessons · scale gate patterns · observability initiative context', insight: 'Engineering decisions connected to organizational growth history' },
    ],
    founderIntelligence: [
      { id: 'fi-1', question: 'What have we learned?', insight: 'Trust before scale · stat-forward identity · relationship metrics over vanity · council healthy disagreement works' },
      { id: 'fi-2', question: 'What are we missing?', insight: 'Predictive maturity modeling early stage · cross-system automation gaps · international expansion journey validation' },
      { id: 'fi-3', question: 'What should we revisit?', insight: 'Membership tier pricing · onboarding simplification scope · creator marketplace expansion timing' },
      { id: 'fi-4', question: 'Where are we strongest?', insight: 'Brand integrity · organic relationship growth · executive council maturity · editorial identity' },
      { id: 'fi-5', question: 'Where are we vulnerable?', insight: 'Onboarding friction · scale pressure vs council decisions · knowledge flow between silos' },
      { id: 'fi-6', question: 'What deserves our attention next?', insight: 'Onboarding fix · phased GTM pilot · OI center operational · creator marketplace kickoff' },
    ],
    recommendedNextSteps: [
      'Connect executive council decisions to institutional memory automatically',
      'Elevate onboarding friction from information to wisdom in Company Genome',
      'Weekly reflection cadence for cross-system learning summary',
      'Founder intelligence briefing from accumulated organizational wisdom',
    ],
    futureOpportunities: [
      'Live organizational intelligence center in Architect Studio',
      'Automatic wisdom elevation on every organizational event',
      'Predictive cross-system intelligence with honest uncertainty display',
      'Future generation inheritance packages from institutional memory',
    ],
  };
}

export function bootstrapOrganizationalIntelligencePlatform(): void {
  bootstrapOrganizationalIntelligenceStore(buildOrganizationalIntelligenceSeed());
}
