import {
  EXECUTIVE_HEADQUARTERS_BASE_PATH,
  HQ_DEFAULT_ROOM_ID,
  type HqRoomId,
} from '../constants';
import type { HeadquartersRoomRecord } from '../types';

function roomPath(slug: HqRoomId): string {
  return slug === HQ_DEFAULT_ROOM_ID
    ? EXECUTIVE_HEADQUARTERS_BASE_PATH
    : `${EXECUTIVE_HEADQUARTERS_BASE_PATH}/${slug}`;
}

/** Platform room registry — generic, expandable per company without redesign */
export const HEADQUARTERS_ROOM_REGISTRY: HeadquartersRoomRecord[] = [
  {
    roomId: 'executive-atrium',
    title: 'Executive Atrium',
    officialName: 'Executive Atrium™',
    purpose: 'Headquarters arrival, orientation, and company presence.',
    roomClass: 'core-executive',
    maturityLevel: 'operational',
    launchStackV1: true,
    locked: false,
    routePath: roomPath('executive-atrium'),
    relatedSystems: ['Identity Engine™', 'Workspace Framework™', 'Orb™'],
    sortOrder: 0,
  },
  {
    roomId: 'founder-office',
    title: 'Founder Office',
    officialName: 'Founder Office™',
    purpose: 'Strategic deep work, decisions, reflection, and priorities.',
    roomClass: 'core-executive',
    maturityLevel: 'operational',
    launchStackV1: true,
    locked: false,
    routePath: roomPath('founder-office'),
    relatedSystems: ['Decision Engine™', 'Identity Engine™', 'Company Genome™'],
    sortOrder: 1,
  },
  {
    roomId: 'mission-control',
    title: 'Mission Control',
    officialName: 'Mission Control™',
    purpose: 'Operational runway — missions, blockers, approvals, outcomes.',
    roomClass: 'core-executive',
    maturityLevel: 'projection',
    launchStackV1: true,
    locked: false,
    routePath: roomPath('mission-control'),
    relatedSystems: ['Mission Engine™', 'Workflow Engine™'],
    sortOrder: 2,
  },
  {
    roomId: 'daily-briefing',
    title: 'Daily Briefing',
    officialName: 'Daily Briefing™',
    purpose: 'Executive clarity at the start of every session.',
    roomClass: 'core-executive',
    maturityLevel: 'operational',
    launchStackV1: true,
    locked: false,
    routePath: roomPath('daily-briefing'),
    relatedSystems: ['Ambient Awareness™', 'Company Health Index™'],
    sortOrder: 3,
  },
  {
    roomId: 'command-center',
    title: 'Command Center',
    officialName: 'Command Center™',
    purpose: 'Guarded command intake, approval, routing, and monitoring.',
    roomClass: 'core-executive',
    maturityLevel: 'projection',
    launchStackV1: true,
    locked: false,
    routePath: roomPath('command-center'),
    relatedSystems: ['Command Center™', 'Permissions Engine™'],
    sortOrder: 4,
  },
  {
    roomId: 'department-directory',
    title: 'Department Directory',
    officialName: 'Department Directory™',
    purpose: 'Company structure as navigable wings and rooms.',
    roomClass: 'department',
    maturityLevel: 'operational',
    launchStackV1: true,
    locked: false,
    routePath: roomPath('department-directory'),
    relatedSystems: ['Department Framework™', 'Atlas™'],
    sortOrder: 5,
  },
  {
    roomId: 'knowledge-wing',
    title: 'Knowledge Wing',
    officialName: 'Knowledge Wing™',
    purpose: 'Source-backed operating knowledge and manuals.',
    roomClass: 'knowledge',
    maturityLevel: 'projection',
    launchStackV1: true,
    locked: false,
    routePath: roomPath('knowledge-wing'),
    relatedSystems: ['Knowledge Core™'],
    sortOrder: 6,
  },
  {
    roomId: 'content-studio',
    title: 'Content Studio',
    officialName: 'Content Studio™',
    purpose: 'Founder-level content planning and launch preparation.',
    roomClass: 'creation',
    maturityLevel: 'projection',
    launchStackV1: true,
    locked: false,
    routePath: roomPath('content-studio'),
    relatedSystems: ['Asset Registry™', 'Mission Engine™'],
    sortOrder: 7,
  },
  {
    roomId: 'creative-direction-studio',
    title: 'Creative Direction Studio',
    officialName: 'Creative Direction Studio™',
    purpose: 'Founder-level creative command and direction.',
    roomClass: 'creation',
    maturityLevel: 'projection',
    launchStackV1: true,
    locked: false,
    routePath: roomPath('creative-direction-studio'),
    relatedSystems: ['Creative Direction™', 'Asset Registry™'],
    sortOrder: 8,
  },
  {
    roomId: 'marketing-headquarters',
    title: 'Marketing Headquarters',
    officialName: 'Marketing Headquarters™',
    purpose: 'Launch and revenue planning visibility.',
    roomClass: 'department',
    maturityLevel: 'projection',
    launchStackV1: true,
    locked: false,
    departmentId: 'marketing',
    routePath: roomPath('marketing-headquarters'),
    relatedSystems: ['Marketing Systems™', 'Analytics™'],
    sortOrder: 9,
  },
  {
    roomId: 'operations-wing',
    title: 'Operations Wing',
    officialName: 'Operations Wing™',
    purpose: 'Core business execution and delivery view.',
    roomClass: 'department',
    maturityLevel: 'projection',
    launchStackV1: true,
    locked: false,
    departmentId: 'operations',
    routePath: roomPath('operations-wing'),
    relatedSystems: ['Workflow Engine™', 'Mission Engine™'],
    sortOrder: 10,
  },
  {
    roomId: 'customer-experience-headquarters',
    title: 'Customer Experience HQ',
    officialName: 'Customer Experience Headquarters™',
    purpose: 'Client and customer state for founder decisions.',
    roomClass: 'department',
    maturityLevel: 'projection',
    launchStackV1: true,
    locked: false,
    departmentId: 'customer-experience',
    routePath: roomPath('customer-experience-headquarters'),
    relatedSystems: ['Customer Experience™', 'Analytics™'],
    sortOrder: 11,
  },
  {
    roomId: 'finance-headquarters',
    title: 'Finance Headquarters',
    officialName: 'Finance Headquarters™',
    purpose: 'Financial metrics and accounting depth.',
    roomClass: 'department',
    maturityLevel: 'preview',
    launchStackV1: false,
    locked: true,
    lockReason: 'Requires finance connectors and Analytics™ maturity.',
    unlockDependency: 'Finance/accounting connectors + Analytics™',
    routePath: roomPath('finance-headquarters'),
    relatedSystems: ['Analytics™', 'Finance Connectors'],
    sortOrder: 12,
  },
  {
    roomId: 'research-wing',
    title: 'Research Wing',
    officialName: 'Research Wing™',
    purpose: 'Research, learning, and profession intelligence.',
    roomClass: 'knowledge',
    maturityLevel: 'preview',
    launchStackV1: false,
    locked: true,
    lockReason: 'Requires Knowledge Core™ and Research Engine™.',
    unlockDependency: 'Knowledge Core™ + Research Engine™',
    routePath: roomPath('research-wing'),
    relatedSystems: ['Knowledge Core™', 'Research Engine™'],
    sortOrder: 13,
  },
  {
    roomId: 'automation-lab',
    title: 'Automation Lab',
    officialName: 'Automation Lab™',
    purpose: 'Automation design and execution preparation.',
    roomClass: 'expansion',
    maturityLevel: 'preview',
    launchStackV1: false,
    locked: true,
    lockReason: 'Unsafe before Command, Workflow, and Permissions maturity.',
    unlockDependency: 'Workflow + Command + Permissions + Automation Engine™',
    routePath: roomPath('automation-lab'),
    relatedSystems: ['Automation Engine™', 'Command Center™'],
    sortOrder: 14,
  },
  {
    roomId: 'meeting-rooms',
    title: 'Meeting Rooms',
    officialName: 'Meeting Rooms™',
    purpose: 'Calendar-integrated meeting and council spaces.',
    roomClass: 'expansion',
    maturityLevel: 'preview',
    launchStackV1: false,
    locked: true,
    lockReason: 'Full meeting OS ships in a future Launch Stack sprint.',
    unlockDependency: 'Calendar + identity + mission integration',
    routePath: roomPath('meeting-rooms'),
    relatedSystems: ['Meeting OS™', 'Calendar'],
    sortOrder: 15,
  },
  {
    roomId: 'expansion-wings',
    title: 'Expansion Wings',
    officialName: 'Expansion Wings™',
    purpose: 'Department Packs and marketplace expansion preview.',
    roomClass: 'expansion',
    maturityLevel: 'preview',
    launchStackV1: false,
    locked: true,
    lockReason: 'Unlocks through Department Packs and platform maturity.',
    unlockDependency: 'Department Packs + Monetization Architecture',
    routePath: roomPath('expansion-wings'),
    relatedSystems: ['Studio Exchange™', 'Department Packs'],
    sortOrder: 16,
  },
];

export function listHeadquartersRooms(): HeadquartersRoomRecord[] {
  return [...HEADQUARTERS_ROOM_REGISTRY].sort((a, b) => a.sortOrder - b.sortOrder);
}

export function getHeadquartersRoom(roomId: HqRoomId): HeadquartersRoomRecord | undefined {
  return HEADQUARTERS_ROOM_REGISTRY.find((r) => r.roomId === roomId);
}

export function listLaunchStackRooms(): HeadquartersRoomRecord[] {
  return listHeadquartersRooms().filter((r) => r.launchStackV1);
}

export function listLockedHeadquartersRooms(): HeadquartersRoomRecord[] {
  return listHeadquartersRooms().filter((r) => r.locked);
}

export function resolveHeadquartersRoomFromSlug(slug: string | undefined): HqRoomId {
  if (!slug) return HQ_DEFAULT_ROOM_ID;
  const match = HEADQUARTERS_ROOM_REGISTRY.find((r) => r.roomId === slug);
  return match && !match.locked ? match.roomId : HQ_DEFAULT_ROOM_ID;
}
