import { bootstrapOrganizationalSelfImprovementStore } from './store';
import type { OrganizationalSelfImprovementStore } from './types';

export function buildOrganizationalSelfImprovementSeed(): Partial<OrganizationalSelfImprovementStore> {
  return {
    companyName: 'NDXBOOK',
    activeWorkspaceId: 'ndxbook',
    dashboard: {
      summary:
        'ORGANIZATIONAL SELF-IMPROVEMENT V1.0 — the organization becomes better every day · learning compounds · continuous refinement.',
      organizationalHealthPct: 86,
      recommendedImprovements: 8,
      activeInitiatives: 4,
      learningVelocityPct: 78,
      completedImprovements: 14,
      maturityScorePct: 72,
    },
    reflectionDomains: [
      { id: 'rd-1', domain: 'Leadership', status: 'strong', insight: 'Executive council synthesis effective · cross-functional recommendations increasing' },
      { id: 'rd-2', domain: 'Customer experience', status: 'developing', insight: 'Onboarding friction improving · Step 3 still needs attention' },
      { id: 'rd-3', domain: 'Brand health', status: 'strong', insight: 'Stat-forward consistency rising · zero generic template usage this quarter' },
      { id: 'rd-4', domain: 'Digital ecosystem', status: 'developing', insight: 'Auth refactor in progress · platform readiness for GTM improving' },
      { id: 'rd-5', domain: 'Technology', status: 'attention', insight: 'Auth debt blocking onboarding simplification · CTO prioritizing' },
      { id: 'rd-6', domain: 'Growth', status: 'developing', insight: 'Relationship-driven GTM planned · vanity metrics successfully blocked' },
      { id: 'rd-7', domain: 'Relationships', status: 'strong', insight: 'Advocacy pathway activation +12% · nurture sequences effective' },
      { id: 'rd-8', domain: 'Knowledge', status: 'strong', insight: 'OI wisdom elevation at 84% · institutional memory compounding' },
      { id: 'rd-9', domain: 'Community', status: 'developing', insight: 'Spotlight program replacing volume tactics · belonging stable' },
      { id: 'rd-10', domain: 'Creator ecosystem', status: 'developing', insight: 'Marketplace pilot progressing · Writing DNA gates enforced' },
      { id: 'rd-11', domain: 'Organizational maturity', status: 'developing', insight: 'OAF Level 3 · trust score 86% · autonomy earned not assumed' },
    ],
    continuousReflection: [
      {
        id: 'cr-1',
        evaluation: 'Q2 organizational performance · trust-before-scale discipline holding',
        strengths: ['Executive collaboration', 'Brand consistency', 'Relationship nurture', 'Knowledge preservation'],
        weaknesses: ['Onboarding Step 3 friction', 'Auth technical debt', 'GTM readiness timing'],
        opportunities: ['Reader spotlight program scale', 'Creator marketplace expansion', 'Workflow memory templates'],
        risks: ['Premature GTM pressure', 'Community fatigue from volume tactics', 'Scope creep on onboarding'],
        blindSpots: ['Paid acquisition temptation when growth targets tighten', 'Over-automation before trust earned'],
        recommendation: 'Complete onboarding simplification before Phase 1 GTM · capture workflow memory from newsletter launch',
      },
    ],
    crossFunctionalImprovements: [
      {
        id: 'cfi-1',
        executive: 'Chief Growth Officer',
        outsideDiscipline: 'Customer experience',
        recommendation: 'Simplify onboarding Step 3 before scaling community engagement',
        rationale: 'CGO observed advocacy drop-off correlates with Step 3 confusion · not a growth tactic issue',
      },
      {
        id: 'cfi-2',
        executive: 'Chief Experience Officer',
        outsideDiscipline: 'Marketing',
        recommendation: 'Replace volume social tactics with reader spotlight program',
        rationale: 'CEO identified engagement quality over content volume · CBO messaging alignment needed',
      },
      {
        id: 'cfi-3',
        executive: 'Chief Technology Officer',
        outsideDiscipline: 'Operations',
        recommendation: 'Automate weekly executive briefing compilation from OI signals',
        rationale: 'CTO identified manual reporting bottleneck · CoS coordination time recoverable',
      },
      {
        id: 'cfi-4',
        executive: 'Chief Brand Officer',
        outsideDiscipline: 'Relationships',
        recommendation: 'Creator messaging should emphasize long-term partnership over transaction',
        rationale: 'CBO identified relationship opportunity in creator pipeline · aligns with founder promise',
      },
    ],
    improvementOpportunities: [
      {
        id: 'io-1',
        category: 'Workflow optimization',
        recommendation: 'Integrate Reader Graph signals into weekly CoS improvement standup',
        whyNow: 'Advocacy data available but not in improvement rhythm',
        whyItMatters: 'Cross-functional improvements require shared intelligence',
        expectedImpact: 'Faster identification of customer experience gaps',
        confidence: 91,
        status: 'recommended',
      },
      {
        id: 'io-2',
        category: 'Customer experience improvements',
        recommendation: 'Step 3 onboarding simplification sprint',
        whyNow: 'Friction audit complete · auth refactor parallel path available',
        whyItMatters: 'GTM gate requires onboarding score > 85',
        expectedImpact: 'Drop-off -20% · GTM readiness unlocked',
        confidence: 87,
        status: 'active',
      },
      {
        id: 'io-3',
        category: 'Knowledge preservation',
        recommendation: 'Template successful newsletter launch workflow in OWF memory',
        whyNow: 'Newsletter Q1 success captured in OWF memory · not yet templated',
        whyItMatters: 'Future campaigns inherit proven orchestration',
        expectedImpact: 'Reduced campaign setup time · higher consistency',
        confidence: 89,
        status: 'recommended',
      },
      {
        id: 'io-4',
        category: 'Community initiatives',
        recommendation: 'Scale reader spotlight from pilot to monthly program',
        whyNow: 'Pilot showing +15% advocacy · community fatigue risk from old tactics eliminated',
        whyItMatters: 'Engagement outcome delegated · spotlight is proven path',
        expectedImpact: 'Sustainable community growth · brand integrity preserved',
        confidence: 84,
        status: 'active',
      },
      {
        id: 'io-5',
        category: 'Innovation initiatives',
        recommendation: 'Creator marketplace Writing DNA gate automation',
        whyNow: 'Manual review bottleneck as creator pipeline grows',
        whyItMatters: 'Scale without quality dilution',
        expectedImpact: '10 creators live with maintained editorial standards',
        confidence: 82,
        status: 'recommended',
      },
    ],
    organizationalExperiments: [
      {
        id: 'oe-1',
        name: 'Reader spotlight pilot',
        type: 'Pilot program',
        executive: 'Chief Growth Officer',
        status: 'running',
        hypothesis: 'Quality spotlight features drive advocacy better than volume social posts',
        lessons: ['Early signal: advocacy +15%', 'Brand alignment critical'],
        futureRecommendations: 'Scale to monthly program if Week 4 metrics hold',
      },
      {
        id: 'oe-2',
        name: 'Onboarding Step 3 minimal variant',
        type: 'A/B testing',
        executive: 'Chief Experience Officer',
        status: 'running',
        hypothesis: 'Reduced Step 3 fields improve completion without trust gate bypass',
        lessons: [],
        futureRecommendations: 'Pending Week 2 results',
      },
      {
        id: 'oe-3',
        name: 'Newsletter nurture sequence timing',
        type: 'Small experiment',
        executive: 'Chief Growth Officer',
        status: 'complete',
        hypothesis: 'Relationship nurture outperforms broadcast timing',
        results: 'Open rate +22% · advocacy pathway +12%',
        lessons: ['Nurture timing matters more than frequency', 'Writing DNA gates prevented generic templates'],
        futureRecommendations: 'Become standard for all newsletter workflows',
      },
    ],
    improvementGovernance: [
      { id: 'ig-1', domain: 'Automatic improvements', rule: 'Workflow optimizations below OAF threshold execute automatically', threshold: 'Trust Level 3+ · impact < $5K' },
      { id: 'ig-2', domain: 'Approval thresholds', rule: 'Customer-facing changes require CoS review · founder review above risk score 7', threshold: 'Risk 1-10 scale' },
      { id: 'ig-3', domain: 'Experimentation permissions', rule: 'Executives may propose pilots · CoS prioritizes · OAF governs autonomy', threshold: 'Max 3 concurrent experiments per department' },
      { id: 'ig-4', domain: 'Structural improvements', rule: 'Major structural changes always require founder approval', threshold: 'Org identity · mission · executive appointments' },
      { id: 'ig-5', domain: 'Risk tolerance', rule: 'Never compromise trust-before-scale for improvement velocity', threshold: 'Founder promise alignment mandatory' },
    ],
    continuousLearning: [
      {
        id: 'cl-1',
        initiative: 'Newsletter launch Q1',
        succeeded: ['Relationship nurture timing', 'Writing DNA quality gates', 'CGO-CBO-CoS collaboration triangle'],
        failed: ['Initial distribution sequencing bottleneck'],
        surprised: ['Advocacy activation higher than open rate improvement'],
        becomeStandard: ['Nurture-over-broadcast timing', 'OI learning capture after every campaign'],
        neverRepeat: ['Broadcast-only sends without nurture sequence'],
        collaborationNotes: 'CGO-CBO-CoS triangle effective · add CTO earlier for tech-dependent campaigns',
        relationshipEvolution: 'Advocacy pathway +12% · belonging score stable',
        knowledgeExpansion: 'Workflow memory template created · feeds OI wisdom elevation',
      },
      {
        id: 'cl-2',
        initiative: 'Community engagement adaptation',
        succeeded: ['Pivot from volume to spotlight', 'Cross-functional executive recommendations'],
        failed: ['Initial volume tactic fatigue signal missed for 2 weeks'],
        surprised: ['CGO onboarding recommendation from growth data'],
        becomeStandard: ['Cross-functional improvement reviews in weekly CoS standup'],
        neverRepeat: ['Volume engagement tactics without relationship intelligence'],
        collaborationNotes: 'CGO identified CEO domain issue · model for cross-functional improvement',
        relationshipEvolution: 'Reader spotlight participants showing higher loyalty scores',
        knowledgeExpansion: 'Blind spot documented: paid acquisition temptation under growth pressure',
      },
    ],
    maturityDimensions: [
      { id: 'md-1', dimension: 'Leadership maturity', currentLevel: 3, trend: 'rising', yearsTrajectory: 'Year 1: framework · Year 2: council · Year 3: cross-functional improvement culture' },
      { id: 'md-2', dimension: 'Knowledge maturity', currentLevel: 4, trend: 'rising', yearsTrajectory: 'OI at 84% wisdom · institutional memory compounding quarterly' },
      { id: 'md-3', dimension: 'Operational maturity', currentLevel: 3, trend: 'rising', yearsTrajectory: 'OWF orchestration · workflow memory templates emerging' },
      { id: 'md-4', dimension: 'Relationship maturity', currentLevel: 3, trend: 'rising', yearsTrajectory: 'Advocacy pathways · nurture sequences · creator pipeline' },
      { id: 'md-5', dimension: 'Innovation maturity', currentLevel: 2, trend: 'rising', yearsTrajectory: 'Experiment culture forming · 3 successful pilots this quarter' },
      { id: 'md-6', dimension: 'Organizational resilience', currentLevel: 3, trend: 'stable', yearsTrajectory: 'Trust-before-scale discipline · OAF Level 3 governance' },
      { id: 'md-7', dimension: 'Customer maturity', currentLevel: 3, trend: 'rising', yearsTrajectory: 'Onboarding improving · belonging stable · journey intelligence growing' },
      { id: 'md-8', dimension: 'Community maturity', currentLevel: 2, trend: 'rising', yearsTrajectory: 'Spotlight program · moving from volume to belonging' },
    ],
    chiefOfStaffCoordination: [
      {
        id: 'cos-1',
        responsibility: 'Prioritize high-impact improvements',
        priority: 'Onboarding Step 3 simplification',
        status: 'active',
        detail: 'Blocks GTM gate · CEO-CDO-CTO coordination · founder review Week 4',
      },
      {
        id: 'cos-2',
        responsibility: 'Organizational dependencies',
        priority: 'Auth refactor before GTM Phase 1',
        status: 'active',
        detail: 'CTO critical path · CoS monitoring · no GTM until onboarding > 85',
      },
      {
        id: 'cos-3',
        responsibility: 'Executive participation',
        priority: 'Cross-functional improvement standup',
        status: 'active',
        detail: 'Weekly · all executives may recommend outside discipline · OI signals shared',
      },
      {
        id: 'cos-4',
        responsibility: 'Founder visibility',
        priority: 'Improvement dashboard briefing',
        status: 'monitoring',
        detail: 'Monthly maturity trajectory · active experiments · never overwhelm with change volume',
      },
    ],
    recommendedNextSteps: [
      'Complete Step 3 onboarding experiment · capture learning in OI',
      'Template newsletter launch workflow from OWF memory',
      'Scale reader spotlight if Week 4 metrics hold',
      'Document cross-functional improvement as standard CoS practice',
    ],
    futureOpportunities: [
      'Autonomous improvement proposals when OAF trust exceeds Level 4',
      'Multi-year maturity visualization across portfolio companies',
      'Experiment-to-standard pipeline automated through OI learning loop',
    ],
  };
}

export function bootstrapOrganizationalSelfImprovementPlatform(): void {
  bootstrapOrganizationalSelfImprovementStore(buildOrganizationalSelfImprovementSeed());
}
