import { bootstrapCompanyMaturityEngineStore } from './store';
import type { CompanyMaturityEngineStore, DomainMaturityScore } from './types';

export function buildCompanyMaturityEngineSeed(): Partial<CompanyMaturityEngineStore> {
  const domainScores: DomainMaturityScore[] = [
    { domain: 'business', label: 'BUSINESS', scorePct: 82, confidencePct: 88, strength: 'Clear mission · registered entity · revenue model', weakness: 'Concentration risk · single-brand dependency', recommendation: 'Diversify revenue streams · document business model', growthOpportunity: 'Business Model Engine activation' },
    { domain: 'leadership', label: 'LEADERSHIP', scorePct: 78, confidencePct: 85, strength: 'Leadership DNA seeded · CoS active · delegation modes', weakness: 'Founder bottleneck on approvals above threshold', recommendation: 'Expand soft approval band · executive org maturation', growthOpportunity: 'Executive Organization · CoS monitoring' },
    { domain: 'strategy', label: 'STRATEGY', scorePct: 85, confidencePct: 90, strength: 'Strategy Engine active · 100K readers initiative · alignment checks', weakness: 'Cross-company strategy coordination', recommendation: 'Portfolio strategy view · Frontal Slayer alignment doc', growthOpportunity: 'Strategic bet expansion' },
    { domain: 'branding', label: 'BRANDING', scorePct: 88, confidencePct: 92, strength: 'Creative DNA · Writing Bible · brand assets · photography bible', weakness: 'Cross-brand consistency automation', recommendation: 'Skip Brand Architect · optimize existing systems', growthOpportunity: 'Brand asset inheritance packages' },
    { domain: 'customer-experience', label: 'CUSTOMER EXPERIENCE', scorePct: 72, confidencePct: 80, strength: 'Reader graph · relationship engine · returning reader focus', weakness: 'Commerce CX separate from media CX', recommendation: 'Experience Architect · unified journey map', growthOpportunity: 'Cross-company portfolio relationships' },
    { domain: 'digital-experience', label: 'DIGITAL EXPERIENCE', scorePct: 80, confidencePct: 86, strength: 'ndxbook platform · mobile-first · newsroom · Build-a-Wig commerce', weakness: 'Studio OS workspace maturity varies by brand', recommendation: 'Digital optimization · not rebuild', growthOpportunity: 'Unified Studio OS dashboard' },
    { domain: 'marketing', label: 'MARKETING', scorePct: 86, confidencePct: 89, strength: 'Campaign engine · distribution engine · Money Monday · Truth Tuesday', weakness: 'Attribution across channels incomplete', recommendation: 'Labs experiment cadence · analytics maturity', growthOpportunity: 'Growth Network integration' },
    { domain: 'sales', label: 'SALES', scorePct: 68, confidencePct: 75, strength: 'Commerce · memberships · affiliate pipeline', weakness: 'B2B sales motion undefined · enterprise path', recommendation: 'Sales systems architect when B2B emerges', growthOpportunity: 'Creator marketplace B2B deals' },
    { domain: 'operations', label: 'OPERATIONS', scorePct: 74, confidencePct: 82, strength: 'Work orchestration · newsroom cadence · editorial QA', weakness: 'Cross-brand ops duplication', recommendation: 'Operational DNA inheritance · SOP library', growthOpportunity: 'Automation systems from ecosystem marketplace' },
    { domain: 'finance', label: 'FINANCE', scorePct: 65, confidencePct: 70, strength: 'Stripe integration · membership billing · revenue tracking', weakness: 'Forecasting · tax automation · multi-entity accounting', recommendation: 'Finance architect · forecasting module', growthOpportunity: 'Business Model Engine financial layer' },
    { domain: 'legal', label: 'LEGAL', scorePct: 58, confidencePct: 65, strength: 'Basic terms · FTC creator compliance awareness', weakness: 'Contract templates · IP registry · entity structure docs', recommendation: 'Legal systems architect · contract library', growthOpportunity: 'Creator marketplace deal templates' },
    { domain: 'human-resources', label: 'HUMAN RESOURCES', scorePct: 55, confidencePct: 62, strength: 'Executive org defined · talent network · contractor model', weakness: 'Formal HR policies · onboarding SOPs · performance systems', recommendation: 'HR architect when team scales past 10', growthOpportunity: 'Agency mode creator teams' },
    { domain: 'technology', label: 'TECHNOLOGY', scorePct: 83, confidencePct: 88, strength: 'Vercel · Supabase · React · Studio OS platform stack', weakness: 'Integration center not fully connected', recommendation: 'Integration center activation · GitHub/Vercel sync', growthOpportunity: 'Architecture-ready import paths' },
    { domain: 'knowledge', label: 'KNOWLEDGE', scorePct: 91, confidencePct: 93, strength: 'Knowledge Asset Engine · newsroom · memory bible · KG', weakness: 'Frontal Slayer knowledge partially siloed', recommendation: 'Cross-company knowledge graph linking', growthOpportunity: 'Ecosystem marketplace knowledge assets' },
    { domain: 'automation', label: 'AUTOMATION', scorePct: 70, confidencePct: 78, strength: 'CoS soft approval · distribution calendar · campaign automation', weakness: 'Manual editorial handoffs · approval bottlenecks', recommendation: 'Work orchestration expansion · automation architect', growthOpportunity: 'Relationship engine next-best-action automation' },
    { domain: 'analytics', label: 'ANALYTICS', scorePct: 76, confidencePct: 81, strength: 'Labs · reader graph signals · campaign analytics', weakness: 'Unified executive dashboard · cross-brand rollup', recommendation: 'Analytics maturity · Studio Intelligence feeds', growthOpportunity: 'Executive Command Center integration' },
    { domain: 'community', label: 'COMMUNITY', scorePct: 79, confidencePct: 84, strength: 'Reader communities · advocate pipeline · Lounge TV', weakness: 'Community monetization paths', recommendation: 'Community architect · membership tiers', growthOpportunity: 'Creator ecosystem community programs' },
    { domain: 'relationships', label: 'RELATIONSHIPS', scorePct: 84, confidencePct: 87, strength: 'Reader graph · relationship engine · long-term nurturing', weakness: 'B2B relationship tracking', recommendation: 'Continue relationship engine · skip rebuild', growthOpportunity: 'Creator marketplace relationship layer' },
    { domain: 'commerce', label: 'COMMERCE', scorePct: 77, confidencePct: 83, strength: 'Build-a-Wig · memberships · Stripe · cart/wishlist', weakness: 'Multi-brand commerce unification', recommendation: 'Commerce architect for FS+ndxbook rollup', growthOpportunity: 'Ecosystem marketplace commerce templates' },
    { domain: 'creator-ecosystem', label: 'CREATOR ECOSYSTEM', scorePct: 73, confidencePct: 80, strength: 'Creator marketplace · ambassador pipeline · Jordan T', weakness: 'Creator program formalization · agency mode', recommendation: 'Creator marketplace expansion · academy paths', growthOpportunity: 'Creator OS dashboard rollout' },
    { domain: 'organizational-intelligence', label: 'ORG INTELLIGENCE', scorePct: 81, confidencePct: 86, strength: 'Studio Intelligence · simulation engine · maturity assessment', weakness: 'Predictive maturity modeling early stage', recommendation: 'Connect all assessments to KG · compound accuracy', growthOpportunity: 'Cross-company organizational learning' },
  ];

  return {
    dashboard: {
      summary:
        'COMPANY MATURITY ENGINE V1.0 — universal onboarding · organizational understanding before improvement · meet founders where they are · build new or import existing · same blueprint.',
      overallMaturityPct: 0,
      assessmentConfidencePct: 0,
      domainsAssessed: 0,
      roadmapItems: 0,
      organizationalHealthPct: 79,
    },
    activeWorkspaceId: 'ndxbook',
    onboardingPath: 'import-existing',
    companyStage: 'operating',
    companyName: 'NDXBOOK',
    domainScores,
    existingAssets: [
      { id: 'ea-1', category: 'Identity', label: 'Company name · mission · vision', status: 'present', notes: 'ndxbook · authority through consistency · 100K readers' },
      { id: 'ea-2', category: 'Branding', label: 'Logo · brand assets · creative DNA', status: 'present', notes: 'Writing Bible · stat-forward · Labs-validated templates' },
      { id: 'ea-3', category: 'Digital', label: 'Website · mobile app · newsroom', status: 'present', notes: 'ndxbook platform · mobile-first · page strategy' },
      { id: 'ea-4', category: 'Content', label: 'Content library · knowledge base', status: 'present', notes: 'Knowledge Asset Engine · 847+ assets · newsroom pages' },
      { id: 'ea-5', category: 'Marketing', label: 'Email · social · analytics', status: 'partial', notes: 'Newsletter · distribution engine · attribution gaps' },
      { id: 'ea-6', category: 'Commerce', label: 'Products · memberships · CRM', status: 'partial', notes: 'Membership tiers · reader graph · no formal CRM' },
      { id: 'ea-7', category: 'Operations', label: 'SOPs · automation · employees', status: 'partial', notes: 'Newsroom playbook · editorial QA · small team + contractors' },
      { id: 'ea-8', category: 'Community', label: 'Community · creator partnerships', status: 'present', notes: 'Reader graph · creator marketplace pipeline · Jordan T' },
      { id: 'ea-9', category: 'Financial', label: 'Financial systems · legal', status: 'partial', notes: 'Stripe · basic terms · forecasting gaps' },
    ],
    integrations: [
      { id: 'int-1', platform: 'Supabase', category: 'Database · Auth', status: 'architecture-ready', purpose: 'Profiles · orders · app_config · analytics events' },
      { id: 'int-2', platform: 'Stripe', category: 'Payments', status: 'architecture-ready', purpose: 'Membership billing · checkout · webhooks' },
      { id: 'int-3', platform: 'Vercel', category: 'Hosting · Deploy', status: 'architecture-ready', purpose: 'Production deploy · serverless API · preview' },
      { id: 'int-4', platform: 'GitHub', category: 'Code · CI', status: 'architecture-ready', purpose: 'Source control · agent commits · deploy triggers' },
      { id: 'int-5', platform: 'Shopify', category: 'Commerce', status: 'planned', purpose: 'Future multi-channel commerce import' },
      { id: 'int-6', platform: 'HubSpot', category: 'CRM · Marketing', status: 'planned', purpose: 'CRM · email · pipeline import path' },
      { id: 'int-7', platform: 'Notion', category: 'Knowledge', status: 'planned', purpose: 'Documentation · SOP import' },
      { id: 'int-8', platform: 'Instagram', category: 'Social', status: 'planned', purpose: 'Social publishing · engagement signals' },
    ],
    diagnostic: {
      strengths: ['Knowledge maturity 91% · institutional memory strong', 'Strategy + marketing alignment · campaign engine active', 'Relationship engine · reader graph · advocate pipeline', 'Creative DNA + branding systems mature · skip rebuild'],
      risks: ['Founder approval bottleneck · leadership plateau risk', 'Finance/legal/HR maturity below 65% · scaling constraints', 'Cross-brand knowledge silos · FS partially disconnected', 'Attribution gaps · analytics not unified executive view'],
      knowledgeGaps: ['Formal contract library · IP registry', 'Cross-company SOP documentation', 'B2B sales playbook · enterprise motion'],
      missingSystems: ['Unified CRM · formal HR policies', 'Multi-entity accounting · tax automation', 'Legal contract templates · compliance registry'],
      duplicateSystems: ['Editorial queue dual ownership · marketing/content overlap', 'Separate commerce CX vs media CX workflows'],
      bottlenecks: ['Founder review above $2K threshold', 'Manual editorial handoffs · approval latency', 'Cross-brand ops coordination'],
      growthConstraints: ['Finance forecasting immaturity', 'Legal/HR not scaled for team growth', 'Integration center not fully activated'],
      automationOpportunities: ['CoS soft approval expansion · work orchestration', 'Distribution calendar automation · campaign handoffs', 'Relationship engine next-best-action pipeline'],
      leadershipOpportunities: ['Delegation mode expansion · executive org maturation', 'CoS proactive maturity monitoring', 'Leadership DNA conflict arbiter for multi-brand'],
      futureRecommendations: ['Activate Integration Center · Supabase/Stripe/Vercel first', 'Experience Architect for unified CX journey', 'Finance + Legal architects before scale', 'Skip Brand Architect · optimize existing · inherit to new companies'],
    },
    architectRecs: [
      { id: 'arch-1', architect: 'BRAND ARCHITECT', action: 'skip', rationale: 'Branding maturity 88% · Creative DNA mature · Writing Bible active', maturityTrigger: 'branding ≥ 85%', confidencePct: 92 },
      { id: 'arch-2', architect: 'EXPERIENCE ARCHITECT', action: 'recommended', rationale: 'Customer experience 72% · commerce/media CX split', maturityTrigger: 'customer-experience < 75%', confidencePct: 86 },
      { id: 'arch-3', architect: 'DIGITAL ARCHITECT', action: 'optimize', rationale: 'Digital 80% · existing platform strong · optimize not rebuild', maturityTrigger: 'digital-experience ≥ 75%', confidencePct: 88 },
      { id: 'arch-4', architect: 'FINANCE ARCHITECT', action: 'recommended', rationale: 'Finance 65% · forecasting · tax · multi-entity gaps', maturityTrigger: 'finance < 70%', confidencePct: 82 },
      { id: 'arch-5', architect: 'LEGAL ARCHITECT', action: 'recommended', rationale: 'Legal 58% · contract templates · IP registry missing', maturityTrigger: 'legal < 65%', confidencePct: 78 },
      { id: 'arch-6', architect: 'AUTOMATION ARCHITECT', action: 'recommended', rationale: 'Automation 70% · approval bottlenecks · handoff latency', maturityTrigger: 'automation < 75%', confidencePct: 84 },
    ],
    roadmap: [
      { id: 'rm-1', title: 'INTEGRATION CENTER · SUPABASE + STRIPE + VERCEL', sequence: 1, effort: 'medium', impact: 'Organizational continuity · data import foundation', dependencies: [], priority: 'critical', confidencePct: 91 },
      { id: 'rm-2', title: 'EXPERIENCE ARCHITECT · UNIFIED CX JOURNEY', sequence: 2, effort: 'high', impact: '+12% customer experience maturity', dependencies: ['rm-1'], priority: 'high', confidencePct: 86 },
      { id: 'rm-3', title: 'LEADERSHIP DNA · APPROVAL BAND EXPANSION', sequence: 3, effort: 'low', impact: '+8% leadership maturity · reduce founder bottleneck', dependencies: [], priority: 'high', confidencePct: 89 },
      { id: 'rm-4', title: 'KNOWLEDGE ASSET ENGINE · CROSS-BRAND LINKING', sequence: 4, effort: 'medium', impact: '+6% knowledge maturity · FS integration', dependencies: ['rm-1'], priority: 'medium', confidencePct: 84 },
      { id: 'rm-5', title: 'FINANCE ARCHITECT · FORECASTING LAYER', sequence: 5, effort: 'medium', impact: '+15% finance maturity', dependencies: ['rm-1'], priority: 'medium', confidencePct: 80 },
      { id: 'rm-6', title: 'CREATOR MARKETPLACE · PROGRAM FORMALIZATION', sequence: 6, effort: 'medium', impact: '+10% creator ecosystem maturity', dependencies: ['rm-2'], priority: 'medium', confidencePct: 82 },
    ],
    timeline: [
      { id: 'tl-1', date: '2024-01', label: 'NDXBOOK FOUNDED · AUTHORITY MEDIA VISION', type: 'founding' },
      { id: 'tl-2', date: '2024-06', label: 'NEWSROOM LAUNCH · PAGE STRATEGY', type: 'launch' },
      { id: 'tl-3', date: '2025-03', label: 'STUDIO OS PLATFORM · MILESTONE ARCHITECTURE', type: 'milestone' },
      { id: 'tl-4', date: '2025-09', label: 'READER GRAPH · RELATIONSHIP ENGINE', type: 'milestone' },
      { id: 'tl-5', date: '2026-01', label: 'KNOWLEDGE ASSET ENGINE · INSTITUTIONAL MEMORY', type: 'milestone' },
      { id: 'tl-6', date: '2026-07', label: 'COMPANY MATURITY ENGINE · UNIVERSAL ONBOARDING', type: 'milestone' },
      { id: 'tl-7', date: '2026-Q4', label: '100K READERS · AUTHORITY GOAL', type: 'future' },
      { id: 'tl-8', date: '2027', label: 'CROSS-BRAND PORTFOLIO · FS INTEGRATION', type: 'future' },
    ],
    simulations: [
      {
        id: 'sim-1',
        label: 'PATH A · INTEGRATION FIRST',
        path: 'Integration Center → Experience Architect → Finance',
        maturityImprovementPct: 18,
        organizationalImpact: 'Data continuity · reduced manual import · faster architect activation',
        effort: 'Medium · 6-8 weeks',
        resources: '1 founder review · CoS orchestration · technical integration',
        risks: ['Integration complexity · data mapping errors'],
        confidencePct: 88,
      },
      {
        id: 'sim-2',
        label: 'PATH B · LEADERSHIP FIRST',
        path: 'Leadership DNA expansion → Automation → Experience',
        maturityImprovementPct: 14,
        organizationalImpact: 'Founder bottleneck reduced · approval velocity +40%',
        effort: 'Low · 2-3 weeks',
        resources: 'Leadership DNA config · CoS delegation modes',
        risks: ['Over-delegation without guardrails'],
        confidencePct: 85,
      },
      {
        id: 'sim-3',
        label: 'PATH C · KNOWLEDGE FIRST',
        path: 'Cross-brand KG linking → Ecosystem Marketplace → Creator formalization',
        maturityImprovementPct: 12,
        organizationalImpact: 'Knowledge compounds · creator pipeline accelerates',
        effort: 'Medium · 4-6 weeks',
        resources: 'Knowledge Asset Engine · Creator Marketplace activation',
        risks: ['FS knowledge silo persistence if incomplete'],
        confidencePct: 82,
      },
    ],
    cosAlerts: [
      { id: 'cos-1', domain: 'MARKETING', trend: 'increasing', message: 'Marketing maturity +6% since campaign engine activation', recommendation: 'Continue Labs cadence · expand attribution' },
      { id: 'cos-2', domain: 'KNOWLEDGE', trend: 'improving', message: 'Knowledge maturity 91% · institutional leader', recommendation: 'Cross-brand linking · ecosystem marketplace assets' },
      { id: 'cos-3', domain: 'LEADERSHIP', trend: 'plateauing', message: 'Leadership maturity plateau at 78% · founder bottleneck', recommendation: 'Expand soft approval band · delegation mode review' },
      { id: 'cos-4', domain: 'FINANCE', trend: 'declining', message: 'Finance maturity risk · forecasting gaps widening', recommendation: 'Prioritize Finance Architect · Business Model Engine layer' },
    ],
    historicalProgress: [
      { date: '2025-06', overallPct: 62 },
      { date: '2025-12', overallPct: 71 },
      { date: '2026-03', overallPct: 76 },
      { date: '2026-07', overallPct: 78 },
    ],
    futureProjections: [
      'Path A (Integration First): 96% maturity potential by Q4 2026',
      'Leadership expansion alone: +8% overall · bottleneck relief in 3 weeks',
      'Skip Brand Architect saves 4-6 weeks · reinvest in Experience + Finance',
    ],
  };
}

export function bootstrapCompanyMaturityEnginePlatform(): void {
  bootstrapCompanyMaturityEngineStore(buildCompanyMaturityEngineSeed());
}
