import type { CareLesson } from '../../types';

const PLACEHOLDER_POSTER = '/assets/NOIR/blanco-thumb.png';

/** Structural curriculum slots — NOT final scripts or media. */
export const CARE_LESSON_SLOTS: CareLesson[] = [
  {
    id: 'care-universal-store-unit',
    slug: 'store-your-unit',
    title: 'HOW TO STORE YOUR UNIT',
    subtitle: 'CARE · UNIVERSAL',
    shortDescription: 'STRUCTURAL PLACEHOLDER — STORAGE PRINCIPLES FOR UNITS AND LACE PIECES.',
    pillar: 'care',
    category: 'storage',
    accessType: 'qualifying-product',
    contentType: 'care-guide',
    format: 'mixed' as const,
    published: true,
    comingSoon: true,
    thumbnailUrl: PLACEHOLDER_POSTER,
    posterUrl: PLACEHOLDER_POSTER,
    tags: ['storage', 'universal'],
    careApplicability: { universal: true },
    educationOwnership: {
      ownsConcepts: ['unit storage between wears'],
      excludesConcepts: ['advanced customization', 'plucking technique'],
    },
  },
  {
    id: 'care-universal-brush-detangle',
    slug: 'brush-and-detangle',
    title: 'HOW TO BRUSH & DETANGLE',
    subtitle: 'CARE · UNIVERSAL',
    shortDescription: 'STRUCTURAL PLACEHOLDER — SAFE DETANGLING FUNDAMENTALS.',
    pillar: 'care',
    category: 'detangling',
    accessType: 'qualifying-product',
    contentType: 'care-guide',
    format: 'mixed' as const,
    published: true,
    comingSoon: true,
    thumbnailUrl: PLACEHOLDER_POSTER,
    posterUrl: PLACEHOLDER_POSTER,
    tags: ['detangling', 'universal'],
  },
  {
    id: 'care-unit-wash',
    slug: 'wash-your-unit',
    title: 'HOW TO WASH YOUR UNIT',
    subtitle: 'CARE · UNIT',
    shortDescription: 'STRUCTURAL PLACEHOLDER — ROUTINE WASHING FOR WIG / UNIT OWNERS.',
    pillar: 'care',
    category: 'washing',
    applicableProductTypes: ['unit'],
    accessType: 'qualifying-product',
    contentType: 'care-guide',
    format: 'mixed' as const,
    published: true,
    comingSoon: true,
    thumbnailUrl: PLACEHOLDER_POSTER,
    posterUrl: PLACEHOLDER_POSTER,
    tags: ['washing', 'unit'],
    educationOwnership: {
      ownsConcepts: ['routine unit washing'],
      excludesConcepts: ['advanced color processing'],
    },
  },
  {
    id: 'care-unit-dry',
    slug: 'dry-your-unit',
    title: 'HOW TO DRY YOUR UNIT',
    subtitle: 'CARE · UNIT',
    shortDescription: 'STRUCTURAL PLACEHOLDER — DRYING WITHOUT DAMAGE.',
    pillar: 'care',
    category: 'drying',
    applicableProductTypes: ['unit'],
    accessType: 'qualifying-product',
    contentType: 'care-guide',
    format: 'mixed' as const,
    published: true,
    comingSoon: true,
    thumbnailUrl: PLACEHOLDER_POSTER,
    posterUrl: PLACEHOLDER_POSTER,
    tags: ['drying', 'unit'],
  },
  {
    id: 'care-texture-straight-maintain',
    slug: 'maintain-straight-hair',
    title: 'HOW TO MAINTAIN STRAIGHT HAIR',
    subtitle: 'CARE · STRAIGHT',
    shortDescription: 'STRUCTURAL PLACEHOLDER — STRAIGHT TEXTURE MAINTENANCE.',
    pillar: 'care',
    category: 'maintenance',
    applicableTextures: ['straight'],
    accessType: 'qualifying-product',
    contentType: 'care-guide',
    format: 'mixed' as const,
    published: true,
    comingSoon: true,
    thumbnailUrl: PLACEHOLDER_POSTER,
    posterUrl: PLACEHOLDER_POSTER,
    tags: ['straight', 'maintenance'],
  },
  {
    id: 'care-texture-wavy-refresh',
    slug: 'refresh-wavy-hair',
    title: 'HOW TO REFRESH WAVY HAIR',
    subtitle: 'CARE · WAVY',
    shortDescription: 'STRUCTURAL PLACEHOLDER — WAVY TEXTURE REFRESH.',
    pillar: 'care',
    category: 'refresh',
    applicableTextures: ['wavy'],
    accessType: 'qualifying-product',
    contentType: 'care-guide',
    format: 'mixed' as const,
    published: true,
    comingSoon: true,
    thumbnailUrl: PLACEHOLDER_POSTER,
    posterUrl: PLACEHOLDER_POSTER,
    tags: ['wavy', 'refresh'],
  },
  {
    id: 'care-texture-curly-refresh',
    slug: 'refresh-curly-hair',
    title: 'HOW TO REFRESH CURLY HAIR',
    subtitle: 'CARE · CURLY',
    shortDescription: 'STRUCTURAL PLACEHOLDER — CURL PATTERN REFRESH.',
    pillar: 'care',
    category: 'refresh',
    applicableTextures: ['curly'],
    accessType: 'qualifying-product',
    contentType: 'care-guide',
    format: 'mixed' as const,
    published: true,
    comingSoon: true,
    thumbnailUrl: PLACEHOLDER_POSTER,
    posterUrl: PLACEHOLDER_POSTER,
    tags: ['curly', 'refresh'],
  },
  {
    id: 'care-bundles-care',
    slug: 'care-for-bundles',
    title: 'CARING FOR BUNDLES',
    subtitle: 'CARE · EXTENSIONS',
    shortDescription: 'STRUCTURAL PLACEHOLDER — BUNDLE / EXTENSION CARE.',
    pillar: 'care',
    category: 'maintenance',
    applicableProductTypes: ['bundles'],
    accessType: 'qualifying-product',
    contentType: 'care-guide',
    format: 'mixed' as const,
    published: true,
    comingSoon: true,
    thumbnailUrl: PLACEHOLDER_POSTER,
    posterUrl: PLACEHOLDER_POSTER,
    tags: ['bundles'],
  },
  {
    id: 'care-closures-care',
    slug: 'care-for-closures',
    title: 'CARING FOR CLOSURES',
    subtitle: 'CARE · LACE',
    shortDescription: 'STRUCTURAL PLACEHOLDER — CLOSURE CARE.',
    pillar: 'care',
    category: 'protection',
    applicableProductTypes: ['closures'],
    accessType: 'qualifying-product',
    contentType: 'care-guide',
    format: 'mixed' as const,
    published: true,
    comingSoon: true,
    thumbnailUrl: PLACEHOLDER_POSTER,
    posterUrl: PLACEHOLDER_POSTER,
    tags: ['closures', 'lace'],
  },
  {
    id: 'care-lace-between-wears',
    slug: 'lace-care-between-wears',
    title: 'LACE CARE BETWEEN WEARS',
    subtitle: 'CARE · LACE PRESERVATION',
    shortDescription:
      'STRUCTURAL PLACEHOLDER — ROUTINE LACE PRESERVATION BETWEEN WEARS (OWNERSHIP EDUCATION).',
    pillar: 'care',
    category: 'protection',
    applicableProductTypes: ['unit', 'frontals', 'closures'],
    accessType: 'qualifying-product',
    contentType: 'care-guide',
    format: 'mixed' as const,
    published: true,
    comingSoon: true,
    thumbnailUrl: PLACEHOLDER_POSTER,
    posterUrl: PLACEHOLDER_POSTER,
    tags: ['lace', 'preservation', 'between-wears'],
    educationOwnership: {
      ownsConcepts: ['lace preservation between wears', 'routine lace protection'],
      excludesConcepts: [
        'advanced customization',
        'plucking technique',
        'adhesive installation',
        'paid PSA Today preservation lesson',
      ],
    },
  },
  {
    id: 'care-frontals-care',
    slug: 'care-for-frontals',
    title: 'CARING FOR FRONTALS',
    subtitle: 'CARE · LACE',
    shortDescription: 'STRUCTURAL PLACEHOLDER — FRONTAL / LACE PIECE CARE.',
    pillar: 'care',
    category: 'protection',
    applicableProductTypes: ['frontals'],
    accessType: 'qualifying-product',
    contentType: 'care-guide',
    format: 'mixed' as const,
    published: true,
    comingSoon: true,
    thumbnailUrl: PLACEHOLDER_POSTER,
    posterUrl: PLACEHOLDER_POSTER,
    tags: ['frontals', 'lace'],
  },
];
