/**
 * Talent Network — AI Media workspace demo seeds & bootstrap.
 */

import { AI_MEDIA_WORKSPACE_ID } from '../../../studio-os-core/ai-media-network/constants';
import { calculateTalentScore } from '../../../studio-os-core/talent-network/talentScore';
import {
  bootstrapTalentNetworkStore,
  mergeTalentNetworkPatch,
  readTalentNetworkStore,
  refreshTalentScores,
} from '../../../studio-os-core/talent-network/store';
import type {
  AudienceIntelRecord,
  CastingAssignment,
  CharacterVersion,
  HumanOnboardingDraft,
  SeriesAssignment,
  TalentContract,
  TalentNetworkStore,
  TalentProfile,
  WardrobeLook,
} from '../../../studio-os-core/talent-network/types';

const WS = AI_MEDIA_WORKSPACE_ID;
const now = '2026-07-04T12:00:00.000Z';

export const DEMO_WARDROBES: WardrobeLook[] = [
  {
    id: 'ward-business-maya',
    workspaceId: WS,
    name: 'Maya · Business Anchor',
    category: 'business',
    description: 'Navy blazer, white blouse, minimal jewelry — Money Monday default.',
    colors: ['#1e3a5f', '#ffffff', '#c9a962'],
    reusable: true,
    assignedTalentIds: ['talent-maya-chen'],
  },
  {
    id: 'ward-tech-alex',
    workspaceId: WS,
    name: 'Alex · Tech Studio',
    category: 'technology',
    description: 'Dark crew neck, subtle LED accent — Future Friday AI stack episodes.',
    colors: ['#0f172a', '#6366f1', '#22d3ee'],
    reusable: true,
    assignedTalentIds: ['talent-alex-rivera'],
  },
  {
    id: 'ward-casual-jordan',
    workspaceId: WS,
    name: 'Jordan · Casual Expert',
    category: 'casual',
    description: 'Soft knit, approachable health & wellness look — Truth Tuesday.',
    colors: ['#f5f0eb', '#6b7280', '#10b981'],
    reusable: true,
    assignedTalentIds: ['talent-jordan-kim'],
  },
  {
    id: 'ward-formal-network',
    workspaceId: WS,
    name: 'Network · Formal Special',
    category: 'formal',
    description: 'Campaign launch & sponsor integration wardrobe — reusable across shows.',
    colors: ['#111827', '#ffffff', '#dc2626'],
    reusable: true,
    assignedTalentIds: ['talent-maya-chen', 'talent-alex-rivera'],
  },
  {
    id: 'ward-fitness-guest',
    workspaceId: WS,
    name: 'Fitness Guest Kit',
    category: 'fitness',
    description: 'Athleisure set for wellness collabs and background talent.',
    colors: ['#374151', '#f97316', '#ffffff'],
    reusable: true,
    assignedTalentIds: [],
  },
];

function basePerformance(overrides: Partial<TalentProfile['performance']>): TalentProfile['performance'] {
  return {
    views: 42000,
    watchTimeSec: 1260000,
    retention: 0.68,
    engagement: 0.72,
    shares: 890,
    comments: 1240,
    followers: 18500,
    revenue: 2400,
    affiliateRevenue: 890,
    sponsorshipRevenue: 1200,
    conversion: 0.034,
    brandSafety: 0.94,
    sentiment: 0.88,
    ...overrides,
  };
}

export const DEMO_TALENTS: TalentProfile[] = [
  {
    id: 'talent-maya-chen',
    workspaceId: WS,
    displayName: 'Maya Chen',
    legalName: 'Maya Chen (AI)',
    talentType: 'ai-presenter',
    status: 'active',
    biography: 'Primary Money Monday host — finance credibility, warm authority, myth-busting energy.',
    profileImage: '/assets/ai-media/talent/maya-chen.jpg',
    portfolio: ['Money Monday S2', 'Q3 Finance Campaign', 'Credit Myths Debunked'],
    contactEmail: 'maya@ai-media.studio',
    representation: 'AI Media Network · In-house',
    availability: 'Mon–Wed · Network calendar priority',
    verified: true,
    onboardingStatus: 'complete',
    knowledgeGraphNodeId: 'node-talent-maya-chen',
    aiProfile: {
      appearance: 'East Asian, mid-30s, professional anchor aesthetic',
      ageRange: '32–38',
      voice: 'Voice A · Warm Authority',
      accent: 'General American',
      speakingSpeed: 'Moderate · 145 wpm',
      tone: 'Confident, approachable, educational',
      personality: 'Calm expert who simplifies complex finance topics',
      facialExpressions: ['knowing smile', 'concerned eyebrow', 'celebratory nod'],
      emotionPresets: ['authoritative', 'empathetic', 'surprised'],
      bodyLanguage: 'Open posture, subtle hand gestures on key points',
      cameraConfidence: 92,
      defaultWardrobeId: 'ward-business-maya',
      alternateWardrobeIds: ['ward-formal-network'],
      signatureColors: ['#1e3a5f', '#c9a962'],
      brandRestrictions: ['No crypto pump schemes', 'No predatory lending promos'],
      catchphrases: ["Let's break this myth.", 'Your money deserves clarity.'],
      knowledgeDomains: ['personal finance', 'credit', 'debt management', 'investing basics'],
      approvedTopics: ['credit scores', 'budgeting', 'debt payoff', 'savings'],
      restrictedTopics: ['medical advice', 'legal advice', 'political endorsements'],
      creativeDnaVersion: 'creative-dna-v2.4',
      voiceModel: 'eleven-v3-maya',
      imageModel: 'flux-pro-presenter',
      animationModel: 'runway-presenter-v2',
    },
    performance: basePerformance({ views: 84200, retention: 0.74, revenue: 4120, followers: 28400 }),
    talentScore: calculateTalentScore(basePerformance({ views: 84200, retention: 0.74, revenue: 4120, followers: 28400 })),
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'talent-alex-rivera',
    workspaceId: WS,
    displayName: 'Alex Rivera',
    talentType: 'ai-presenter',
    status: 'active',
    biography: 'Future Friday host — AI tools, automation stacks, creator tech with high-energy delivery.',
    profileImage: '/assets/ai-media/talent/alex-rivera.jpg',
    portfolio: ['Future Friday S2', 'AI Tool Reviews', 'Automation Stack 2026'],
    representation: 'AI Media Network · In-house',
    availability: 'Thu–Fri · Tech pillar priority',
    verified: true,
    onboardingStatus: 'complete',
    knowledgeGraphNodeId: 'node-talent-alex-rivera',
    aiProfile: {
      appearance: 'Latino, late-20s, tech-creator aesthetic with subtle futurism',
      ageRange: '26–32',
      voice: 'Voice B · High Energy Tech',
      accent: 'General American · slight West Coast',
      speakingSpeed: 'Fast · 165 wpm',
      tone: 'Enthusiastic, curious, demo-forward',
      personality: 'Early adopter who tests tools so viewers do not have to',
      facialExpressions: ['excited lean-in', 'skeptical squint', 'mind-blown'],
      emotionPresets: ['hyped', 'analytical', 'impressed'],
      bodyLanguage: 'Dynamic, screen-share friendly, points at overlays',
      cameraConfidence: 88,
      defaultWardrobeId: 'ward-tech-alex',
      alternateWardrobeIds: ['ward-formal-network'],
      signatureColors: ['#6366f1', '#22d3ee'],
      brandRestrictions: ['No unverified AI scams', 'Disclose affiliate when applicable'],
      catchphrases: ['This replaced my entire workflow.', 'Sixty seconds. Watch this.'],
      knowledgeDomains: ['ai tools', 'automation', 'creator workflows', 'productivity'],
      approvedTopics: ['AI editors', 'automation', 'SaaS stacks', 'no-code'],
      restrictedTopics: ['Finance advice', 'Health claims'],
      creativeDnaVersion: 'creative-dna-v2.4',
      voiceModel: 'eleven-v3-alex',
      imageModel: 'flux-pro-presenter',
      animationModel: 'runway-presenter-v2',
    },
    performance: basePerformance({ views: 32000, retention: 0.62, revenue: 1890, followers: 12200 }),
    talentScore: calculateTalentScore(basePerformance({ views: 32000, retention: 0.62, revenue: 1890, followers: 12200 })),
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'talent-jordan-kim',
    workspaceId: WS,
    displayName: 'Jordan Kim',
    talentType: 'ai-presenter',
    status: 'active',
    biography: 'Truth Tuesday wellness host — evidence-based health myth busting with empathetic delivery.',
    profileImage: '/assets/ai-media/talent/jordan-kim.jpg',
    portfolio: ['Truth Tuesday S2', 'Sleep Supplement Truth', 'Nutrition Myths'],
    availability: 'Tue · Health pillar',
    verified: true,
    onboardingStatus: 'complete',
    knowledgeGraphNodeId: 'node-talent-jordan-kim',
    aiProfile: {
      appearance: 'Korean-American, early-30s, clean wellness aesthetic',
      ageRange: '28–34',
      voice: 'Voice C · Empathetic Educator',
      accent: 'General American',
      speakingSpeed: 'Moderate · 140 wpm',
      tone: 'Warm, evidence-first, non-judgmental',
      personality: 'Trusted friend who cites sources before opinions',
      facialExpressions: ['gentle concern', 'relieved smile', 'thoughtful pause'],
      emotionPresets: ['supportive', 'curious', 'cautionary'],
      bodyLanguage: 'Seated calm, minimal movement, eye-contact focused',
      cameraConfidence: 90,
      defaultWardrobeId: 'ward-casual-jordan',
      alternateWardrobeIds: [],
      signatureColors: ['#10b981', '#f5f0eb'],
      brandRestrictions: ['No miracle cure claims', 'No unverified supplements'],
      catchphrases: ['What does the evidence actually say?', 'Your body is not broken.'],
      knowledgeDomains: ['sleep', 'nutrition', 'wellness myths', 'habits'],
      approvedTopics: ['sleep hygiene', 'supplements', 'nutrition basics'],
      restrictedTopics: ['Medical diagnosis', 'Prescription advice'],
      creativeDnaVersion: 'creative-dna-v2.3',
      voiceModel: 'eleven-v3-jordan',
      imageModel: 'flux-pro-presenter',
      animationModel: 'runway-presenter-v2',
    },
    performance: basePerformance({ views: 52100, retention: 0.71, revenue: 2180, followers: 19800 }),
    talentScore: calculateTalentScore(basePerformance({ views: 52100, retention: 0.71, revenue: 2180, followers: 19800 })),
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'talent-sam-ortiz',
    workspaceId: WS,
    displayName: 'Sam Ortiz',
    talentType: 'photographer',
    status: 'active',
    biography: 'Human photographer — thumbnail, B-roll, and set photography for AI Media productions.',
    profileImage: '/assets/ai-media/talent/sam-ortiz.jpg',
    portfolio: ['Money Monday thumbnails', 'Network B-roll package', 'Campaign stills'],
    contactEmail: 'sam@creators.example',
    representation: 'Freelance · AI Media preferred vendor',
    availability: 'Mon–Fri · 20 hrs/week',
    verified: true,
    onboardingStatus: 'complete',
    knowledgeGraphNodeId: 'node-talent-sam-ortiz',
    performance: basePerformance({ views: 0, retention: 0, engagement: 0, revenue: 4800, followers: 3200 }),
    talentScore: calculateTalentScore(basePerformance({ views: 0, retention: 0, engagement: 0, revenue: 4800, followers: 3200 }), 95),
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'talent-riley-park',
    workspaceId: WS,
    displayName: 'Riley Park',
    talentType: 'human-creator',
    status: 'onboarding',
    biography: 'Incoming human creator — personal finance TikTok · 120K followers · niche overlap with Money Monday.',
    profileImage: '/assets/ai-media/talent/riley-park.jpg',
    portfolio: ['TikTok @rileybudgets', 'Newsletter · 8K subs'],
    contactEmail: 'riley@example.com',
    availability: 'Pending contract · Q3 start',
    verified: false,
    onboardingStatus: 'in-progress',
    knowledgeGraphNodeId: 'node-talent-riley-park',
    performance: basePerformance({ views: 890000, retention: 0.58, engagement: 0.81, followers: 120000, revenue: 0 }),
    talentScore: calculateTalentScore(basePerformance({ views: 890000, retention: 0.58, engagement: 0.81, followers: 120000, revenue: 0 }), 60),
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'talent-casey-lee',
    workspaceId: WS,
    displayName: 'Casey Lee',
    talentType: 'editor',
    status: 'active',
    biography: 'Human video editor — short-form pacing, caption timing, and multi-platform exports.',
    profileImage: '/assets/ai-media/talent/casey-lee.jpg',
    portfolio: ['Cross-platform exports', 'Caption timing QA', 'Workflow Wednesday cuts'],
    contactEmail: 'casey@editors.example',
    availability: 'Flexible · 30 hrs/week',
    verified: true,
    onboardingStatus: 'complete',
    knowledgeGraphNodeId: 'node-talent-casey-lee',
    performance: basePerformance({ views: 0, revenue: 6200, followers: 890 }),
    talentScore: calculateTalentScore(basePerformance({ views: 0, revenue: 6200, followers: 890 }), 90),
    createdAt: now,
    updatedAt: now,
  },
];

export const DEMO_CASTINGS: CastingAssignment[] = [
  {
    id: 'cast-mm-host',
    workspaceId: WS,
    productionId: 'ep-mm-s2e12',
    productionTitle: 'Credit Score Myths Debunked',
    talentId: 'talent-maya-chen',
    role: 'host',
    status: 'confirmed',
  },
  {
    id: 'cast-tt-host',
    workspaceId: WS,
    productionId: 'ep-tt-s2e10',
    productionTitle: 'Sleep Supplement Truth',
    talentId: 'talent-jordan-kim',
    role: 'host',
    status: 'confirmed',
  },
  {
    id: 'cast-ff-host',
    workspaceId: WS,
    productionId: 'ep-ff-s2e9',
    productionTitle: 'AI Tool That Edits Videos in 60 Seconds',
    talentId: 'talent-alex-rivera',
    role: 'host',
    status: 'confirmed',
  },
  {
    id: 'cast-mm-vo',
    workspaceId: WS,
    productionId: 'ep-mm-s2e13',
    productionTitle: 'Debt Avalanche vs Snowball',
    talentId: 'talent-maya-chen',
    role: 'narrator',
    status: 'cast',
  },
  {
    id: 'cast-campaign-expert',
    workspaceId: WS,
    productionId: 'campaign-q3-finance',
    productionTitle: 'Q3 Finance Campaign Launch',
    talentId: 'talent-maya-chen',
    role: 'expert',
    status: 'audition',
  },
  {
    id: 'cast-riley-guest',
    workspaceId: WS,
    productionId: 'ep-mm-collab-01',
    productionTitle: 'Creator Collab · Budget Hacks',
    talentId: 'talent-riley-park',
    role: 'guest',
    status: 'audition',
  },
];

export const DEMO_SERIES_ASSIGNMENTS: SeriesAssignment[] = [
  {
    id: 'series-mm-maya',
    workspaceId: WS,
    talentId: 'talent-maya-chen',
    showId: 'money-monday',
    showName: 'Money Monday',
    seriesName: 'Season 2',
    campaign: 'Q3 Finance Push',
    episodeIds: ['ep-mm-s2e12', 'ep-mm-s2e13'],
    recurring: true,
  },
  {
    id: 'series-tt-jordan',
    workspaceId: WS,
    talentId: 'talent-jordan-kim',
    showId: 'truth-tuesday',
    showName: 'Truth Tuesday',
    seriesName: 'Season 2',
    episodeIds: ['ep-tt-s2e10'],
    recurring: true,
  },
  {
    id: 'series-ff-alex',
    workspaceId: WS,
    talentId: 'talent-alex-rivera',
    showId: 'future-friday',
    showName: 'Future Friday',
    seriesName: 'Season 2',
    episodeIds: ['ep-ff-s2e9'],
    recurring: true,
  },
  {
    id: 'series-sam-thumbnails',
    workspaceId: WS,
    talentId: 'talent-sam-ortiz',
    showId: 'money-monday',
    showName: 'Money Monday',
    campaign: 'Thumbnail & B-roll retainer',
    episodeIds: ['ep-mm-s2e12', 'ep-mm-s2e13'],
    recurring: true,
  },
];

export const DEMO_AUDIENCE_INTEL: AudienceIntelRecord[] = [
  {
    id: 'intel-maya',
    talentId: 'talent-maya-chen',
    bestDemographics: '25–44 · US · finance-curious · mobile-first',
    bestPlatforms: ['tiktok', 'youtube-shorts', 'instagram'],
    bestPillars: ['money', 'consumer-intelligence'],
    bestPublishingTimes: ['Mon 6:00 PM ET', 'Mon 6:30 PM ET'],
    bestVoice: 'Voice A · Warm Authority',
    bestWardrobeId: 'ward-business-maya',
    bestHooks: ['Did you know this credit myth…', 'Stop doing this with your money'],
    bestCollaborations: ['FinTech sponsors', 'Human finance creators 50K–200K'],
  },
  {
    id: 'intel-alex',
    talentId: 'talent-alex-rivera',
    bestDemographics: '18–34 · creators · tech early adopters',
    bestPlatforms: ['tiktok', 'youtube-shorts', 'x'],
    bestPillars: ['ai-technology'],
    bestPublishingTimes: ['Fri 12:00 PM ET'],
    bestVoice: 'Voice B · High Energy Tech',
    bestWardrobeId: 'ward-tech-alex',
    bestHooks: ['This AI tool replaced…', '60-second workflow demo'],
    bestCollaborations: ['SaaS affiliates', 'Tool founders'],
  },
];

export const DEMO_CHARACTER_VERSIONS: CharacterVersion[] = [
  {
    id: 'ver-maya-v1',
    talentId: 'talent-maya-chen',
    version: 1,
    label: 'Launch · Money Monday S1',
    appearanceSnapshot: 'East Asian, early-30s, lighter makeup, red accent blazer',
    voiceSnapshot: 'Voice A · v1 · slightly faster pace',
    wardrobeSnapshot: 'Red blazer business set',
    personalitySnapshot: 'More energetic, less myth-bust framing',
    creativeDnaVersion: 'creative-dna-v2.1',
    createdAt: '2026-03-01T00:00:00.000Z',
  },
  {
    id: 'ver-maya-v2',
    talentId: 'talent-maya-chen',
    version: 2,
    label: 'Current · S2 Authority Refresh',
    appearanceSnapshot: 'East Asian, mid-30s, navy anchor aesthetic',
    voiceSnapshot: 'Voice A · v2 · warm authority 145 wpm',
    wardrobeSnapshot: 'Navy business anchor (ward-business-maya)',
    personalitySnapshot: 'Calm expert, myth-busting energy',
    creativeDnaVersion: 'creative-dna-v2.4',
    createdAt: now,
  },
  {
    id: 'ver-alex-v1',
    talentId: 'talent-alex-rivera',
    version: 1,
    label: 'Future Friday launch',
    appearanceSnapshot: 'Hoodie + cap creator look',
    voiceSnapshot: 'Voice B · v1',
    wardrobeSnapshot: 'Casual creator hoodie',
    personalitySnapshot: 'Raw early-adopter energy',
    creativeDnaVersion: 'creative-dna-v2.2',
    createdAt: '2026-04-15T00:00:00.000Z',
  },
];

export const DEMO_CONTRACTS: TalentContract[] = [
  {
    id: 'contract-maya-host',
    talentId: 'talent-maya-chen',
    workspaceId: WS,
    title: 'Money Monday · Primary Host Retainer',
    rate: '$2,400/ep · 12 eps/season',
    deliverables: ['Host on-camera', 'Voice-over pickups', 'Campaign integrations'],
    exclusivity: 'Finance vertical · non-compete 90 days',
    usageRights: 'Perpetual · all platforms · AI likeness included',
    renewalDate: '2026-12-31',
    representation: 'AI Media Network · In-house',
    notes: 'Auto-renew unless 60-day notice.',
    paymentHistory: [
      { date: '2026-06-01', amount: 2400, label: 'S2E12 · Credit Myths' },
      { date: '2026-05-01', amount: 2400, label: 'S2E11 · Emergency Fund' },
    ],
  },
  {
    id: 'contract-sam-photo',
    talentId: 'talent-sam-ortiz',
    workspaceId: WS,
    title: 'Thumbnail & B-roll · Freelance',
    rate: '$800/week · 20 hrs',
    deliverables: ['Thumbnail stills', 'B-roll package', 'Set photography'],
    exclusivity: 'None',
    usageRights: 'Network productions only · 24-month license',
    renewalDate: '2026-09-30',
    notes: 'Human talent · same registry architecture as AI presenters.',
    paymentHistory: [{ date: '2026-06-28', amount: 800, label: 'Week 26 retainer' }],
  },
  {
    id: 'contract-riley-pending',
    talentId: 'talent-riley-park',
    workspaceId: WS,
    title: 'Guest Creator · Collab Pilot (draft)',
    rate: 'TBD · revenue share proposed',
    deliverables: ['1 co-hosted episode', 'Cross-promo package'],
    exclusivity: 'Finance niche · 30 days',
    usageRights: 'Draft — legal review pending',
    notes: 'Onboarding in progress — human creator workflow.',
    paymentHistory: [],
  },
];

export const DEMO_ONBOARDING: HumanOnboardingDraft[] = [
  {
    id: 'onboard-riley',
    workspaceId: WS,
    displayName: 'Riley Park',
    bio: 'Personal finance TikTok creator · myth-busting · 120K followers',
    platforms: ['tiktok', 'instagram', 'newsletter'],
    portfolio: ['@rileybudgets', 'Budget Myths series'],
    rates: '$3,500/collab · open to rev share',
    audience: '18–32 · US · first-time earners',
    niche: 'Personal finance · budgeting',
    goals: ['Co-host Money Monday special', 'Newsletter cross-promo'],
    availability: 'Q3 2026 · 2 episodes/month max',
    verificationStatus: 'pending',
  },
  {
    id: 'onboard-marcus',
    workspaceId: WS,
    displayName: 'Marcus Webb',
    bio: 'Voice actor · commercial + narration · home studio',
    platforms: ['voices.com', 'linkedin'],
    portfolio: ['FinTech narrations', 'Podcast intros'],
    rates: '$450/session',
    audience: 'B2B · podcast listeners',
    niche: 'Finance narration · authoritative male voice',
    goals: ['Voiceover for campaign spots', 'Alternate narrator for Maya'],
    availability: 'Immediate · 10 hrs/week',
    verificationStatus: 'pending',
  },
];

export function buildTalentNetworkStorePatch(): Partial<TalentNetworkStore> {
  return {
    talents: DEMO_TALENTS,
    wardrobes: DEMO_WARDROBES,
    castings: DEMO_CASTINGS,
    seriesAssignments: DEMO_SERIES_ASSIGNMENTS,
    audienceIntel: DEMO_AUDIENCE_INTEL,
    characterVersions: DEMO_CHARACTER_VERSIONS,
    contracts: DEMO_CONTRACTS,
    onboardingDrafts: DEMO_ONBOARDING,
  };
}

export function bootstrapAiMediaTalentNetwork(): void {
  bootstrapTalentNetworkStore();
  const store = readTalentNetworkStore();
  if (store.talents.length > 0) return;
  mergeTalentNetworkPatch(buildTalentNetworkStorePatch());
  refreshTalentScores(WS);
}
