import { SCREENING_ROOM_PHILOSOPHY } from './constants';
import { bootstrapScreeningRoomStore } from './store';
import type { ScreeningRoomStore } from './types';

export function buildScreeningRoomSeed(): Partial<ScreeningRoomStore> {
  return {
    companyName: 'NDXBOOK',
    selectedProductionId: 'sr-lace-mastery',
    currentVersionId: 'sr-lace-v2',
    compareMode: false,
    compareVersionIds: ['sr-lace-v2'],
    compareField: 'hook',
    playerPlaying: false,
    dashboard: {
      summary:
        'SCREENING ROOM V1.0 · NDXBOOK · private cinema · experience every production before publication.',
      awaitingReview: 3,
      approvedToday: 2,
      experimentsQueued: 1,
      avgConfidencePct: 89,
    },
    philosophy: [...SCREENING_ROOM_PHILOSOPHY],
    productions: [
      {
        id: 'sr-lace-mastery',
        title: 'CUTTING YOUR LACE · LACE MASTERY',
        pageRoute: '/ndxbook/lace-mastery/cutting-your-lace',
        readyAt: '2026-07-05T14:00:00.000Z',
        versions: [
          {
            id: 'sr-lace-v1',
            label: 'VERSION A · ORIGINAL CUT',
            isCurrent: false,
            runtimeSec: 248,
            thumbnailNote: 'LACE EDGE CLOSE-UP · HIGH CONTRAST · RED THREAD',
            voiceNote: 'WARM EDUCATOR · STANDARD CADENCE',
            hook: 'Most lace fails in the first 30 seconds — here is why.',
            caption: '4 steps no one shows you · trust-first pacing',
            title: 'CUT YOUR LACE LIKE A PRO',
            description: 'Educational evergreen · beginner-friendly · NDXBOOK Lace Mastery series.',
            performancePrediction: 'STRONG · EDUCATIONAL EVERGREEN',
            confidencePct: 86,
            renderQualityPct: 94,
          },
          {
            id: 'sr-lace-v2',
            label: 'VERSION B · CURRENT · BRAND CONCIERGE REFINED',
            isCurrent: true,
            runtimeSec: 242,
            thumbnailNote: 'SOFT MARBLE · LACE MACRO · CHAMPAGNE ACCENT',
            voiceNote: 'WARM EDUCATOR · SLOWER STEP 2 · TRUST-FIRST',
            hook: 'Before you cut lace — watch this 30-second mistake.',
            caption: 'The 4-step method our community trusts · lace mastery',
            title: 'CUT YOUR LACE LIKE A PRO — 4 STEPS',
            description: 'Refined hook · Brand Concierge aligned · Experience Concierge trust pacing.',
            performancePrediction: 'STRONG · +14% RETENTION VS VERSION A',
            confidencePct: 91,
            renderQualityPct: 96,
          },
          {
            id: 'sr-lace-v3',
            label: 'VERSION C · HOOK EXPERIMENT',
            isCurrent: false,
            runtimeSec: 238,
            thumbnailNote: 'SPLIT SCREEN BEFORE/AFTER · BOLD TYPE',
            voiceNote: 'ENERGETIC OPEN · CALM DEMONSTRATION',
            hook: 'Stop destroying your lace — do this instead.',
            caption: 'Bold hook test · same 4-step core',
            title: 'STOP RUINING YOUR LACE (DO THIS)',
            description: 'Growth Concierge experiment · higher curiosity · monitor brand tone.',
            performancePrediction: 'MODERATE · HIGHER CLICK · WATCH BRAND TONE',
            confidencePct: 78,
            renderQualityPct: 93,
          },
        ],
      },
      {
        id: 'sr-slay-report',
        title: 'SLAY REPORT · WEEK 12',
        pageRoute: '/ndxbook/slay-report/week-12',
        readyAt: '2026-07-05T12:30:00.000Z',
        versions: [
          {
            id: 'sr-sr-v1',
            label: 'VERSION A · BROADCAST CUT',
            isCurrent: true,
            runtimeSec: 312,
            thumbnailNote: 'WEEK 12 · MARBLE DESK · GOLD TYPE',
            voiceNote: 'EDITORIAL · LUXURY BROADCAST',
            hook: 'Week 12 — what the community accomplished together.',
            caption: 'Weekly ritual · reader spotlight · what is next',
            title: 'SLAY REPORT · WEEK 12',
            description: 'Weekly editorial · community proof first · Growth Concierge approved.',
            performancePrediction: 'SOLID · WEEKLY RITUAL',
            confidencePct: 88,
            renderQualityPct: 95,
          },
          {
            id: 'sr-sr-v2',
            label: 'VERSION B · SHORT FORM',
            isCurrent: false,
            runtimeSec: 90,
            thumbnailNote: 'VERTICAL PREVIEW · REELS CUT',
            voiceNote: 'CONDENSED · SAME ENERGY',
            hook: 'This week in 90 seconds.',
            caption: 'Short form experiment · Reels + TikTok',
            title: 'SLAY REPORT · 90 SEC',
            description: 'Platform adaptation · Technology Concierge codec optimized.',
            performancePrediction: 'STRONG · SOCIAL SHORTS',
            confidencePct: 85,
            renderQualityPct: 97,
          },
        ],
      },
      {
        id: 'sr-membership-guide',
        title: 'MEMBERSHIP VALUE GUIDE · PREMIUM PATH',
        pageRoute: '/ndxbook/membership/value-guide',
        readyAt: '2026-07-05T10:00:00.000Z',
        versions: [
          {
            id: 'sr-mg-v1',
            label: 'VERSION A · HOSPITALITY CUT',
            isCurrent: true,
            runtimeSec: 142,
            thumbnailNote: 'PREMIUM CARD · CHAMPAGNE · SOFT LIGHT',
            voiceNote: 'CHIEF CONCIERGE · HOSPITALITY OVER SALES',
            hook: 'What premium actually feels like — not a feature list.',
            caption: 'Trust-building · calm CTA · membership invitation',
            title: 'THE PREMIUM PATH · MEMBERSHIP VALUE',
            description: 'Experience Concierge softer pacing · Chief Concierge voice.',
            performancePrediction: 'MODERATE · CONVERSION SUPPORT',
            confidencePct: 84,
            renderQualityPct: 92,
          },
        ],
      },
    ],
    conciergeReviews: [
      {
        id: 'brand-concierge',
        title: 'BRAND CONCIERGE',
        accent: '#7C3AED',
        notes: 'Version B preserves Writing DNA · hook refined without losing trust. Version C risks tone — monitor if selected.',
        analysis: 'Brand alignment: 94% · Thumbnail B strongest for long-term brand memory.',
      },
      {
        id: 'experience-concierge',
        title: 'EXPERIENCE CONCIERGE',
        accent: '#0891B2',
        notes: 'Trust-first pacing on Version B · step 2 slower cadence approved for beginners.',
        analysis: 'Viewer experience: calm · confident · never rushed · hospitality over urgency.',
      },
      {
        id: 'growth-concierge',
        title: 'GROWTH CONCIERGE',
        accent: '#059669',
        notes: 'Version B predicted +14% retention · Version C higher curiosity but watch unsubscribe on bold hook.',
        analysis: 'Expected performance: B for evergreen · C for experiment only · A as baseline.',
      },
      {
        id: 'technology-concierge',
        title: 'TECHNOLOGY CONCIERGE',
        accent: '#2563EB',
        notes: 'Render quality 96% on Version B · codec clean · captions synced · no frame drops.',
        analysis: 'Technical readiness: approved for all platforms · Short form cut ready for Reels.',
      },
      {
        id: 'chief-concierge',
        title: 'CHIEF CONCIERGE',
        accent: '#92704A',
        notes: 'Final summary: Version B is the recommended publication cut. Compare A vs B before approving.',
        analysis: 'This is the emotional moment before content enters the world — take your time. Your judgment final.',
      },
    ],
  };
}

export function bootstrapScreeningRoomPlatform(): void {
  bootstrapScreeningRoomStore(buildScreeningRoomSeed());
}
