/** Generated by scripts/generate-studio-world-icons-from-crops.mjs — deterministic v3 crops only. */
import type { ExperienceLabIconName } from './experience-lab-icon-registry';



export type ExperienceLabIconAssetEntry = {
  src: string;
  sourceLabel: string;
  category: string;
  confidence: number;
  auditStatus: 'PASS' | 'WARN' | 'FAIL' | 'PENDING';
  contentSha256: string;
  approved: boolean;
  cropManifestVersion: string;
};

export const EXPERIENCE_LAB_ICON_ASSETS: Partial<Record<ExperienceLabIconName, ExperienceLabIconAssetEntry>> = {

} as Partial<Record<ExperienceLabIconName, ExperienceLabIconAssetEntry>>;

export const EXPERIENCE_LAB_ICON_EXTRACTION_SOURCE_SHA256 = 'd7476775716d3f2dc9b2416198c81bbd19d8e1a7f5730c5ff3c79fe6cda1f51d';
export const EXPERIENCE_LAB_ICON_EXTRACTION_VERSION = 'studio-world-icons-v3';
export const EXPERIENCE_LAB_ICON_OPTICAL_LOCK_VERSION = 'studio-world-icons-v3-pending-approval';
export const EXPERIENCE_LAB_ICON_BUNDLE_SHA256 = 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855';
export const EXPERIENCE_LAB_ICON_LOCKDOWN_CERTIFIED = false;
export const EXPERIENCE_LAB_ICON_V2_PIPELINE_FROZEN = true;
export const EXPERIENCE_LAB_ICON_OUTPUT_CANVAS = 512;
export const EXPERIENCE_LAB_ICON_ASSET_DIR = 'generated-v3';
