/** Generated by scripts/extract-experience-lab-icons.mjs — do not edit manually. */
import type { ExperienceLabIconName } from './experience-lab-icon-registry';

import experienceLabAsset from '../../../assets/studio-world/experience-lab/icons/generated/experience-lab.png';
import blueprintAsset from '../../../assets/studio-world/experience-lab/icons/generated/blueprint.png';
import constructionAsset from '../../../assets/studio-world/experience-lab/icons/generated/construction.png';
import materialsAsset from '../../../assets/studio-world/experience-lab/icons/generated/materials.png';
import lightingAsset from '../../../assets/studio-world/experience-lab/icons/generated/lighting.png';
import cameraAsset from '../../../assets/studio-world/experience-lab/icons/generated/camera.png';
import splitViewAsset from '../../../assets/studio-world/experience-lab/icons/generated/split-view.png';
import founderRenderAsset from '../../../assets/studio-world/experience-lab/icons/generated/founder-render.png';
import projectsAsset from '../../../assets/studio-world/experience-lab/icons/generated/projects.png';
import historyAsset from '../../../assets/studio-world/experience-lab/icons/generated/history.png';
import revisionsAsset from '../../../assets/studio-world/experience-lab/icons/generated/revisions.png';
import milestonesAsset from '../../../assets/studio-world/experience-lab/icons/generated/milestones.png';
import analyticsAsset from '../../../assets/studio-world/experience-lab/icons/generated/analytics.png';
import performanceAsset from '../../../assets/studio-world/experience-lab/icons/generated/performance.png';
import issuesAsset from '../../../assets/studio-world/experience-lab/icons/generated/issues.png';
import approvedAsset from '../../../assets/studio-world/experience-lab/icons/generated/approved.png';
import playbackAsset from '../../../assets/studio-world/experience-lab/icons/generated/playback.png';
import pauseAsset from '../../../assets/studio-world/experience-lab/icons/generated/pause.png';
import stopAsset from '../../../assets/studio-world/experience-lab/icons/generated/stop.png';
import nextAsset from '../../../assets/studio-world/experience-lab/icons/generated/next.png';
import previousAsset from '../../../assets/studio-world/experience-lab/icons/generated/previous.png';
import loopAsset from '../../../assets/studio-world/experience-lab/icons/generated/loop.png';
import captureAsset from '../../../assets/studio-world/experience-lab/icons/generated/capture.png';
import fullscreenAsset from '../../../assets/studio-world/experience-lab/icons/generated/fullscreen.png';
import zoomInAsset from '../../../assets/studio-world/experience-lab/icons/generated/zoom-in.png';
import zoomOutAsset from '../../../assets/studio-world/experience-lab/icons/generated/zoom-out.png';
import panAsset from '../../../assets/studio-world/experience-lab/icons/generated/pan.png';
import fitViewAsset from '../../../assets/studio-world/experience-lab/icons/generated/fit-view.png';
import orbitAsset from '../../../assets/studio-world/experience-lab/icons/generated/orbit.png';
import perspectiveAsset from '../../../assets/studio-world/experience-lab/icons/generated/perspective.png';
import toggleUiAsset from '../../../assets/studio-world/experience-lab/icons/generated/toggle-ui.png';
import gridAsset from '../../../assets/studio-world/experience-lab/icons/generated/grid.png';
import hideAsset from '../../../assets/studio-world/experience-lab/icons/generated/hide.png';
import lockAsset from '../../../assets/studio-world/experience-lab/icons/generated/lock.png';
import unlockAsset from '../../../assets/studio-world/experience-lab/icons/generated/unlock.png';
import duplicateAsset from '../../../assets/studio-world/experience-lab/icons/generated/duplicate.png';
import deleteAsset from '../../../assets/studio-world/experience-lab/icons/generated/delete.png';
import editAsset from '../../../assets/studio-world/experience-lab/icons/generated/edit.png';
import settingsAsset from '../../../assets/studio-world/experience-lab/icons/generated/settings.png';
import filterAsset from '../../../assets/studio-world/experience-lab/icons/generated/filter.png';
import exportAsset from '../../../assets/studio-world/experience-lab/icons/generated/export.png';
import importAsset from '../../../assets/studio-world/experience-lab/icons/generated/import.png';
import cloudSyncAsset from '../../../assets/studio-world/experience-lab/icons/generated/cloud-sync.png';
import databaseAsset from '../../../assets/studio-world/experience-lab/icons/generated/database.png';
import linkAsset from '../../../assets/studio-world/experience-lab/icons/generated/link.png';
import shareAsset from '../../../assets/studio-world/experience-lab/icons/generated/share.png';
import usersAsset from '../../../assets/studio-world/experience-lab/icons/generated/users.png';
import teamAsset from '../../../assets/studio-world/experience-lab/icons/generated/team.png';
import notificationsAsset from '../../../assets/studio-world/experience-lab/icons/generated/notifications.png';
import commentsAsset from '../../../assets/studio-world/experience-lab/icons/generated/comments.png';
import notesAsset from '../../../assets/studio-world/experience-lab/icons/generated/notes.png';
import attachmentsAsset from '../../../assets/studio-world/experience-lab/icons/generated/attachments.png';
import scheduleAsset from '../../../assets/studio-world/experience-lab/icons/generated/schedule.png';
import timeTrackingAsset from '../../../assets/studio-world/experience-lab/icons/generated/time-tracking.png';
import flagAsset from '../../../assets/studio-world/experience-lab/icons/generated/flag.png';
import favoriteAsset from '../../../assets/studio-world/experience-lab/icons/generated/favorite.png';
import dashboardAsset from '../../../assets/studio-world/experience-lab/icons/generated/dashboard.png';
import focusModeAsset from '../../../assets/studio-world/experience-lab/icons/generated/focus-mode.png';
import terminalAsset from '../../../assets/studio-world/experience-lab/icons/generated/terminal.png';
import diagnosticsAsset from '../../../assets/studio-world/experience-lab/icons/generated/diagnostics.png';
import securityAsset from '../../../assets/studio-world/experience-lab/icons/generated/security.png';
import permissionsAsset from '../../../assets/studio-world/experience-lab/icons/generated/permissions.png';
import helpAsset from '../../../assets/studio-world/experience-lab/icons/generated/help.png';
import aboutAsset from '../../../assets/studio-world/experience-lab/icons/generated/about.png';

export type ExperienceLabIconAssetEntry = {
  src: string;
  sourceLabel: string;
  category: string;
  confidence: number;
};

export const EXPERIENCE_LAB_ICON_ASSETS: Record<ExperienceLabIconName, ExperienceLabIconAssetEntry> = {
  experienceLab: {
    src: experienceLabAsset,
    sourceLabel: 'EXPERIENCE LAB',
    category: 'viewport',
    confidence: 1.000,
  },
  blueprint: {
    src: blueprintAsset,
    sourceLabel: 'BLUEPRINT',
    category: 'viewport',
    confidence: 1.000,
  },
  construction: {
    src: constructionAsset,
    sourceLabel: 'CONSTRUCTION',
    category: 'viewport',
    confidence: 1.000,
  },
  materials: {
    src: materialsAsset,
    sourceLabel: 'MATERIALS',
    category: 'viewport',
    confidence: 1.000,
  },
  lighting: {
    src: lightingAsset,
    sourceLabel: 'LIGHTING',
    category: 'viewport',
    confidence: 1.000,
  },
  camera: {
    src: cameraAsset,
    sourceLabel: 'CAMERA',
    category: 'viewport',
    confidence: 1.000,
  },
  splitView: {
    src: splitViewAsset,
    sourceLabel: 'SPLIT VIEW',
    category: 'viewport',
    confidence: 1.000,
  },
  founderRender: {
    src: founderRenderAsset,
    sourceLabel: 'FOUNDER RENDER',
    category: 'viewport',
    confidence: 1.000,
  },
  projects: {
    src: projectsAsset,
    sourceLabel: 'PROJECTS',
    category: 'project',
    confidence: 1.000,
  },
  history: {
    src: historyAsset,
    sourceLabel: 'HISTORY',
    category: 'project',
    confidence: 1.000,
  },
  revisions: {
    src: revisionsAsset,
    sourceLabel: 'REVISIONS',
    category: 'project',
    confidence: 1.000,
  },
  milestones: {
    src: milestonesAsset,
    sourceLabel: 'MILESTONES',
    category: 'project',
    confidence: 1.000,
  },
  analytics: {
    src: analyticsAsset,
    sourceLabel: 'ANALYTICS',
    category: 'project',
    confidence: 1.000,
  },
  performance: {
    src: performanceAsset,
    sourceLabel: 'PERFORMANCE',
    category: 'project',
    confidence: 1.000,
  },
  issues: {
    src: issuesAsset,
    sourceLabel: 'ISSUES',
    category: 'project',
    confidence: 1.000,
  },
  approved: {
    src: approvedAsset,
    sourceLabel: 'APPROVED',
    category: 'project',
    confidence: 1.000,
  },
  playback: {
    src: playbackAsset,
    sourceLabel: 'PLAYBACK',
    category: 'playback',
    confidence: 1.000,
  },
  pause: {
    src: pauseAsset,
    sourceLabel: 'PAUSE',
    category: 'playback',
    confidence: 1.000,
  },
  stop: {
    src: stopAsset,
    sourceLabel: 'STOP',
    category: 'playback',
    confidence: 1.000,
  },
  next: {
    src: nextAsset,
    sourceLabel: 'NEXT',
    category: 'playback',
    confidence: 1.000,
  },
  previous: {
    src: previousAsset,
    sourceLabel: 'PREVIOUS',
    category: 'playback',
    confidence: 1.000,
  },
  loop: {
    src: loopAsset,
    sourceLabel: 'LOOP',
    category: 'playback',
    confidence: 1.000,
  },
  capture: {
    src: captureAsset,
    sourceLabel: 'CAPTURE',
    category: 'playback',
    confidence: 1.000,
  },
  fullscreen: {
    src: fullscreenAsset,
    sourceLabel: 'FULLSCREEN',
    category: 'playback',
    confidence: 1.000,
  },
  zoomIn: {
    src: zoomInAsset,
    sourceLabel: 'ZOOM IN',
    category: 'viewport-tools',
    confidence: 1.000,
  },
  zoomOut: {
    src: zoomOutAsset,
    sourceLabel: 'ZOOM OUT',
    category: 'viewport-tools',
    confidence: 1.000,
  },
  pan: {
    src: panAsset,
    sourceLabel: 'PAN',
    category: 'viewport-tools',
    confidence: 1.000,
  },
  fitView: {
    src: fitViewAsset,
    sourceLabel: 'FIT VIEW',
    category: 'viewport-tools',
    confidence: 1.000,
  },
  orbit: {
    src: orbitAsset,
    sourceLabel: 'ORBIT',
    category: 'viewport-tools',
    confidence: 1.000,
  },
  perspective: {
    src: perspectiveAsset,
    sourceLabel: 'PERSPECTIVE',
    category: 'viewport-tools',
    confidence: 1.000,
  },
  toggleUi: {
    src: toggleUiAsset,
    sourceLabel: 'TOGGLE UI',
    category: 'viewport-tools',
    confidence: 1.000,
  },
  grid: {
    src: gridAsset,
    sourceLabel: 'GRID',
    category: 'viewport-tools',
    confidence: 1.000,
  },
  hide: {
    src: hideAsset,
    sourceLabel: 'HIDE',
    category: 'inspector',
    confidence: 1.000,
  },
  lock: {
    src: lockAsset,
    sourceLabel: 'LOCK',
    category: 'inspector',
    confidence: 1.000,
  },
  unlock: {
    src: unlockAsset,
    sourceLabel: 'UNLOCK',
    category: 'inspector',
    confidence: 1.000,
  },
  duplicate: {
    src: duplicateAsset,
    sourceLabel: 'DUPLICATE',
    category: 'inspector',
    confidence: 1.000,
  },
  delete: {
    src: deleteAsset,
    sourceLabel: 'DELETE',
    category: 'inspector',
    confidence: 1.000,
  },
  edit: {
    src: editAsset,
    sourceLabel: 'EDIT',
    category: 'inspector',
    confidence: 1.000,
  },
  settings: {
    src: settingsAsset,
    sourceLabel: 'SETTINGS',
    category: 'inspector',
    confidence: 1.000,
  },
  filter: {
    src: filterAsset,
    sourceLabel: 'FILTER',
    category: 'inspector',
    confidence: 1.000,
  },
  export: {
    src: exportAsset,
    sourceLabel: 'EXPORT',
    category: 'data',
    confidence: 1.000,
  },
  import: {
    src: importAsset,
    sourceLabel: 'IMPORT',
    category: 'data',
    confidence: 1.000,
  },
  cloudSync: {
    src: cloudSyncAsset,
    sourceLabel: 'CLOUD SYNC',
    category: 'data',
    confidence: 1.000,
  },
  database: {
    src: databaseAsset,
    sourceLabel: 'DATABASE',
    category: 'data',
    confidence: 1.000,
  },
  link: {
    src: linkAsset,
    sourceLabel: 'LINK',
    category: 'data',
    confidence: 1.000,
  },
  share: {
    src: shareAsset,
    sourceLabel: 'SHARE',
    category: 'data',
    confidence: 1.000,
  },
  users: {
    src: usersAsset,
    sourceLabel: 'USERS',
    category: 'data',
    confidence: 1.000,
  },
  team: {
    src: teamAsset,
    sourceLabel: 'TEAM',
    category: 'data',
    confidence: 1.000,
  },
  notifications: {
    src: notificationsAsset,
    sourceLabel: 'NOTIFICATIONS',
    category: 'collaboration',
    confidence: 1.000,
  },
  comments: {
    src: commentsAsset,
    sourceLabel: 'COMMENTS',
    category: 'collaboration',
    confidence: 1.000,
  },
  notes: {
    src: notesAsset,
    sourceLabel: 'NOTES',
    category: 'collaboration',
    confidence: 1.000,
  },
  attachments: {
    src: attachmentsAsset,
    sourceLabel: 'ATTACHMENTS',
    category: 'collaboration',
    confidence: 1.000,
  },
  schedule: {
    src: scheduleAsset,
    sourceLabel: 'SCHEDULE',
    category: 'collaboration',
    confidence: 1.000,
  },
  timeTracking: {
    src: timeTrackingAsset,
    sourceLabel: 'TIME TRACKING',
    category: 'collaboration',
    confidence: 1.000,
  },
  flag: {
    src: flagAsset,
    sourceLabel: 'FLAG',
    category: 'collaboration',
    confidence: 1.000,
  },
  favorite: {
    src: favoriteAsset,
    sourceLabel: 'FAVORITE',
    category: 'collaboration',
    confidence: 1.000,
  },
  dashboard: {
    src: dashboardAsset,
    sourceLabel: 'DASHBOARD',
    category: 'navigation',
    confidence: 1.000,
  },
  focusMode: {
    src: focusModeAsset,
    sourceLabel: 'FOCUS MODE',
    category: 'navigation',
    confidence: 1.000,
  },
  terminal: {
    src: terminalAsset,
    sourceLabel: 'TERMINAL',
    category: 'navigation',
    confidence: 1.000,
  },
  diagnostics: {
    src: diagnosticsAsset,
    sourceLabel: 'DIAGNOSTICS',
    category: 'navigation',
    confidence: 1.000,
  },
  security: {
    src: securityAsset,
    sourceLabel: 'SECURITY',
    category: 'navigation',
    confidence: 1.000,
  },
  permissions: {
    src: permissionsAsset,
    sourceLabel: 'PERMISSIONS',
    category: 'navigation',
    confidence: 1.000,
  },
  help: {
    src: helpAsset,
    sourceLabel: 'HELP',
    category: 'navigation',
    confidence: 1.000,
  },
  about: {
    src: aboutAsset,
    sourceLabel: 'ABOUT',
    category: 'navigation',
    confidence: 1.000,
  }
} as Record<ExperienceLabIconName, ExperienceLabIconAssetEntry>;

export const EXPERIENCE_LAB_ICON_EXTRACTION_SOURCE_SHA256 = 'd7476775716d3f2dc9b2416198c81bbd19d8e1a7f5730c5ff3c79fe6cda1f51d';
export const EXPERIENCE_LAB_ICON_OUTPUT_CANVAS = 256;
