import type { ExperienceLabIconName } from './experience-lab-icon-registry';

/** Canonical Studio World icon presentation — runtime display only (PNG assets frozen). */
export type IconPresentationScores = {
  presentation: number;
  centering: number;
  scale: number;
  padding: number;
  visualWeight: number;
  consistency: number;
  overall: number;
};

export type IconPresentationProfile = {
  scale: number;
  offsetX: number;
  offsetY: number;
  strokeWeight: number;
  opticalWeight: number;
  padding: number;
  minimumSize: number;
  maximumSize: number;
  baselineAdjust: number;
  scores: IconPresentationScores;
};

export const STUDIO_WORLD_ICON_PRESENTATION_VERSION = 'studio-world-icon-presentation-v1';

/** Single source of truth for all Studio World departments and Industry Packs. */
export const StudioWorldIconPresentationRegistry: Record<
  ExperienceLabIconName,
  IconPresentationProfile
> = {
  experienceLab: {
    scale: 0.99,
    offsetX: 0,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 0.97,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 94,
      centering: 82,
      scale: 100,
      padding: 100,
      visualWeight: 91,
      consistency: 98,
      overall: 93,
    },
  },
  blueprint: {
    scale: 1.1,
    offsetX: 0,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 1.08,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 99,
      centering: 95,
      scale: 100,
      padding: 100,
      visualWeight: 102,
      consistency: 98,
      overall: 99,
    },
  },
  construction: {
    scale: 1.18,
    offsetX: 0,
    offsetY: -1,
    strokeWeight: 1,
    opticalWeight: 1.05,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 97,
      centering: 88,
      scale: 100,
      padding: 100,
      visualWeight: 99,
      consistency: 98,
      overall: 97,
    },
  },
  materials: {
    scale: 1.26,
    offsetX: 0,
    offsetY: -2,
    strokeWeight: 1,
    opticalWeight: 1.08,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 96,
      centering: 81,
      scale: 100,
      padding: 100,
      visualWeight: 102,
      consistency: 98,
      overall: 95,
    },
  },
  lighting: {
    scale: 1.1,
    offsetX: 1,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 1.08,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 94,
      centering: 69,
      scale: 100,
      padding: 100,
      visualWeight: 102,
      consistency: 98,
      overall: 92,
    },
  },
  camera: {
    scale: 1.16,
    offsetX: 1,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 1.06,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 94,
      centering: 72,
      scale: 100,
      padding: 100,
      visualWeight: 100,
      consistency: 98,
      overall: 93,
    },
  },
  splitView: {
    scale: 1.1,
    offsetX: 1,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 1.08,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 92,
      centering: 61,
      scale: 100,
      padding: 100,
      visualWeight: 102,
      consistency: 98,
      overall: 90,
    },
  },
  founderRender: {
    scale: 1.1,
    offsetX: 1,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 1.08,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 92,
      centering: 61,
      scale: 100,
      padding: 100,
      visualWeight: 102,
      consistency: 98,
      overall: 90,
    },
  },
  projects: {
    scale: 1.1,
    offsetX: 0,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 1.08,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 95,
      centering: 97,
      scale: 100,
      padding: 79,
      visualWeight: 102,
      consistency: 98,
      overall: 95,
    },
  },
  history: {
    scale: 1.1,
    offsetX: 0,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 1.08,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 99,
      centering: 96,
      scale: 100,
      padding: 100,
      visualWeight: 102,
      consistency: 98,
      overall: 99,
    },
  },
  revisions: {
    scale: 1.1,
    offsetX: 0,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 1.08,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 99,
      centering: 99,
      scale: 100,
      padding: 96,
      visualWeight: 102,
      consistency: 98,
      overall: 99,
    },
  },
  milestones: {
    scale: 1.1,
    offsetX: 0,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 1.08,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 100,
      centering: 98,
      scale: 100,
      padding: 100,
      visualWeight: 102,
      consistency: 98,
      overall: 100,
    },
  },
  analytics: {
    scale: 1.14,
    offsetX: 1,
    offsetY: -1,
    strokeWeight: 1,
    opticalWeight: 1.05,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 91,
      centering: 56,
      scale: 100,
      padding: 100,
      visualWeight: 99,
      consistency: 98,
      overall: 89,
    },
  },
  performance: {
    scale: 1.1,
    offsetX: 1,
    offsetY: 1,
    strokeWeight: 1,
    opticalWeight: 1.08,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 91,
      centering: 56,
      scale: 100,
      padding: 100,
      visualWeight: 102,
      consistency: 98,
      overall: 89,
    },
  },
  issues: {
    scale: 1.1,
    offsetX: 0,
    offsetY: 1,
    strokeWeight: 1,
    opticalWeight: 1.08,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 89,
      centering: 64,
      scale: 100,
      padding: 79,
      visualWeight: 102,
      consistency: 98,
      overall: 87,
    },
  },
  approved: {
    scale: 1.1,
    offsetX: 0,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 1.08,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 96,
      centering: 99,
      scale: 100,
      padding: 79,
      visualWeight: 102,
      consistency: 98,
      overall: 96,
    },
  },
  playback: {
    scale: 1.18,
    offsetX: 0,
    offsetY: -1,
    strokeWeight: 1,
    opticalWeight: 1.05,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 92,
      centering: 65,
      scale: 100,
      padding: 100,
      visualWeight: 99,
      consistency: 98,
      overall: 91,
    },
  },
  pause: {
    scale: 1.07,
    offsetX: 0,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 1.05,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 99,
      centering: 96,
      scale: 100,
      padding: 100,
      visualWeight: 99,
      consistency: 98,
      overall: 99,
    },
  },
  stop: {
    scale: 1.1,
    offsetX: 0,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 1.08,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 100,
      centering: 99,
      scale: 100,
      padding: 100,
      visualWeight: 102,
      consistency: 98,
      overall: 100,
    },
  },
  next: {
    scale: 1.1,
    offsetX: 0,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 1.08,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 100,
      centering: 99,
      scale: 100,
      padding: 100,
      visualWeight: 102,
      consistency: 98,
      overall: 100,
    },
  },
  previous: {
    scale: 1.1,
    offsetX: 0,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 1.08,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 100,
      centering: 99,
      scale: 100,
      padding: 100,
      visualWeight: 102,
      consistency: 98,
      overall: 100,
    },
  },
  loop: {
    scale: 1.1,
    offsetX: 0,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 1.08,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 95,
      centering: 97,
      scale: 100,
      padding: 79,
      visualWeight: 102,
      consistency: 98,
      overall: 95,
    },
  },
  capture: {
    scale: 1.03,
    offsetX: 0,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 1.01,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 98,
      centering: 99,
      scale: 100,
      padding: 100,
      visualWeight: 95,
      consistency: 98,
      overall: 98,
    },
  },
  fullscreen: {
    scale: 1.1,
    offsetX: 0,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 1.08,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 100,
      centering: 98,
      scale: 100,
      padding: 100,
      visualWeight: 102,
      consistency: 98,
      overall: 100,
    },
  },
  zoomIn: {
    scale: 1.12,
    offsetX: 0,
    offsetY: -1,
    strokeWeight: 1,
    opticalWeight: 1.04,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 94,
      centering: 75,
      scale: 100,
      padding: 100,
      visualWeight: 98,
      consistency: 98,
      overall: 93,
    },
  },
  zoomOut: {
    scale: 1.03,
    offsetX: 0,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 1.01,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 99,
      centering: 100,
      scale: 100,
      padding: 100,
      visualWeight: 95,
      consistency: 98,
      overall: 99,
    },
  },
  pan: {
    scale: 1.12,
    offsetX: 0,
    offsetY: 1,
    strokeWeight: 1,
    opticalWeight: 1.1,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 90,
      centering: 71,
      scale: 100,
      padding: 79,
      visualWeight: 103,
      consistency: 98,
      overall: 89,
    },
  },
  fitView: {
    scale: 1.03,
    offsetX: 0,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 1.01,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 97,
      centering: 94,
      scale: 100,
      padding: 100,
      visualWeight: 95,
      consistency: 98,
      overall: 97,
    },
  },
  orbit: {
    scale: 1.1,
    offsetX: 1,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 1.08,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 91,
      centering: 56,
      scale: 100,
      padding: 100,
      visualWeight: 102,
      consistency: 98,
      overall: 89,
    },
  },
  perspective: {
    scale: 1.2,
    offsetX: 1,
    offsetY: -1,
    strokeWeight: 1,
    opticalWeight: 1.06,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 91,
      centering: 56,
      scale: 100,
      padding: 100,
      visualWeight: 100,
      consistency: 98,
      overall: 89,
    },
  },
  toggleUi: {
    scale: 1.1,
    offsetX: 0,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 1.08,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 99,
      centering: 97,
      scale: 100,
      padding: 100,
      visualWeight: 102,
      consistency: 98,
      overall: 99,
    },
  },
  grid: {
    scale: 1.1,
    offsetX: 0,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 1.08,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 95,
      centering: 98,
      scale: 100,
      padding: 79,
      visualWeight: 102,
      consistency: 98,
      overall: 95,
    },
  },
  hide: {
    scale: 1.07,
    offsetX: 0,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 1.05,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 99,
      centering: 97,
      scale: 100,
      padding: 100,
      visualWeight: 99,
      consistency: 98,
      overall: 99,
    },
  },
  lock: {
    scale: 1.12,
    offsetX: 0,
    offsetY: 1,
    strokeWeight: 1,
    opticalWeight: 1.1,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 95,
      centering: 74,
      scale: 100,
      padding: 100,
      visualWeight: 103,
      consistency: 98,
      overall: 94,
    },
  },
  unlock: {
    scale: 1.1,
    offsetX: 0,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 1.08,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 95,
      centering: 95,
      scale: 100,
      padding: 79,
      visualWeight: 102,
      consistency: 98,
      overall: 95,
    },
  },
  duplicate: {
    scale: 1.1,
    offsetX: 0,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 1.08,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 99,
      centering: 95,
      scale: 100,
      padding: 100,
      visualWeight: 102,
      consistency: 98,
      overall: 99,
    },
  },
  delete: {
    scale: 1.08,
    offsetX: 0,
    offsetY: 1,
    strokeWeight: 1,
    opticalWeight: 1.06,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 89,
      centering: 70,
      scale: 100,
      padding: 79,
      visualWeight: 100,
      consistency: 98,
      overall: 88,
    },
  },
  edit: {
    scale: 1.08,
    offsetX: 0,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 1.06,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 96,
      centering: 82,
      scale: 100,
      padding: 100,
      visualWeight: 100,
      consistency: 98,
      overall: 95,
    },
  },
  settings: {
    scale: 1.1,
    offsetX: 0,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 1.08,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 100,
      centering: 100,
      scale: 100,
      padding: 100,
      visualWeight: 102,
      consistency: 98,
      overall: 100,
    },
  },
  filter: {
    scale: 1.1,
    offsetX: 0,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 1.08,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 99,
      centering: 99,
      scale: 100,
      padding: 96,
      visualWeight: 102,
      consistency: 98,
      overall: 99,
    },
  },
  export: {
    scale: 1,
    offsetX: 0,
    offsetY: -1,
    strokeWeight: 1,
    opticalWeight: 0.98,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 93,
      centering: 74,
      scale: 100,
      padding: 100,
      visualWeight: 92,
      consistency: 98,
      overall: 92,
    },
  },
  import: {
    scale: 1,
    offsetX: 0,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 0.98,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 96,
      centering: 88,
      scale: 100,
      padding: 100,
      visualWeight: 92,
      consistency: 98,
      overall: 95,
    },
  },
  cloudSync: {
    scale: 1.1,
    offsetX: 0,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 1.08,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 99,
      centering: 96,
      scale: 100,
      padding: 100,
      visualWeight: 102,
      consistency: 98,
      overall: 99,
    },
  },
  database: {
    scale: 0.95,
    offsetX: 0,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 0.93,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 96,
      centering: 95,
      scale: 100,
      padding: 100,
      visualWeight: 87,
      consistency: 98,
      overall: 96,
    },
  },
  link: {
    scale: 1,
    offsetX: 0,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 0.98,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 98,
      centering: 100,
      scale: 100,
      padding: 100,
      visualWeight: 92,
      consistency: 98,
      overall: 98,
    },
  },
  share: {
    scale: 1.16,
    offsetX: 1,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 1.14,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 94,
      centering: 63,
      scale: 100,
      padding: 100,
      visualWeight: 107,
      consistency: 98,
      overall: 92,
    },
  },
  users: {
    scale: 0.96,
    offsetX: 0,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 0.94,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 97,
      centering: 100,
      scale: 100,
      padding: 100,
      visualWeight: 88,
      consistency: 98,
      overall: 97,
    },
  },
  team: {
    scale: 1.16,
    offsetX: 1,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 1.14,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 92,
      centering: 53,
      scale: 100,
      padding: 100,
      visualWeight: 107,
      consistency: 98,
      overall: 89,
    },
  },
  notifications: {
    scale: 1,
    offsetX: 0,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 0.98,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 97,
      centering: 94,
      scale: 100,
      padding: 100,
      visualWeight: 92,
      consistency: 98,
      overall: 97,
    },
  },
  comments: {
    scale: 0.96,
    offsetX: 0,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 0.94,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 95,
      centering: 90,
      scale: 100,
      padding: 100,
      visualWeight: 88,
      consistency: 98,
      overall: 95,
    },
  },
  notes: {
    scale: 0.96,
    offsetX: 0,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 0.94,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 96,
      centering: 96,
      scale: 100,
      padding: 100,
      visualWeight: 88,
      consistency: 98,
      overall: 96,
    },
  },
  attachments: {
    scale: 1.1,
    offsetX: 0,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 1.08,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 95,
      centering: 74,
      scale: 100,
      padding: 100,
      visualWeight: 102,
      consistency: 98,
      overall: 94,
    },
  },
  schedule: {
    scale: 0.96,
    offsetX: 0,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 0.94,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 96,
      centering: 94,
      scale: 100,
      padding: 100,
      visualWeight: 88,
      consistency: 98,
      overall: 96,
    },
  },
  timeTracking: {
    scale: 0.96,
    offsetX: 0,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 0.94,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 97,
      centering: 97,
      scale: 100,
      padding: 100,
      visualWeight: 88,
      consistency: 98,
      overall: 97,
    },
  },
  flag: {
    scale: 0.96,
    offsetX: 0,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 0.94,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 94,
      centering: 82,
      scale: 100,
      padding: 100,
      visualWeight: 88,
      consistency: 98,
      overall: 93,
    },
  },
  favorite: {
    scale: 1,
    offsetX: 0,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 0.98,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 96,
      centering: 92,
      scale: 100,
      padding: 100,
      visualWeight: 92,
      consistency: 98,
      overall: 96,
    },
  },
  dashboard: {
    scale: 1.34,
    offsetX: 0,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 1.1,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 96,
      centering: 80,
      scale: 100,
      padding: 100,
      visualWeight: 103,
      consistency: 98,
      overall: 95,
    },
  },
  focusMode: {
    scale: 1.04,
    offsetX: 0,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 1.02,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 98,
      centering: 95,
      scale: 100,
      padding: 100,
      visualWeight: 96,
      consistency: 98,
      overall: 98,
    },
  },
  terminal: {
    scale: 1.22,
    offsetX: 0,
    offsetY: -1,
    strokeWeight: 1,
    opticalWeight: 1.07,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 97,
      centering: 86,
      scale: 100,
      padding: 100,
      visualWeight: 101,
      consistency: 98,
      overall: 96,
    },
  },
  diagnostics: {
    scale: 1.16,
    offsetX: 0,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 1.14,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 96,
      centering: 76,
      scale: 100,
      padding: 100,
      visualWeight: 107,
      consistency: 98,
      overall: 95,
    },
  },
  security: {
    scale: 1,
    offsetX: 0,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 0.98,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 94,
      centering: 88,
      scale: 100,
      padding: 93,
      visualWeight: 92,
      consistency: 98,
      overall: 94,
    },
  },
  permissions: {
    scale: 1.2,
    offsetX: 1,
    offsetY: -1,
    strokeWeight: 1,
    opticalWeight: 1.06,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 92,
      centering: 63,
      scale: 100,
      padding: 100,
      visualWeight: 100,
      consistency: 98,
      overall: 90,
    },
  },
  help: {
    scale: 0.96,
    offsetX: 0,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 0.94,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 96,
      centering: 93,
      scale: 100,
      padding: 100,
      visualWeight: 88,
      consistency: 98,
      overall: 96,
    },
  },
  about: {
    scale: 1,
    offsetX: 0,
    offsetY: 0,
    strokeWeight: 1,
    opticalWeight: 0.98,
    padding: 0,
    minimumSize: 10,
    maximumSize: 36,
    baselineAdjust: 0,
    scores: {
      presentation: 97,
      centering: 97,
      scale: 100,
      padding: 100,
      visualWeight: 92,
      consistency: 98,
      overall: 97,
    },
  }
} as Record<ExperienceLabIconName, IconPresentationProfile>;

export const ExperienceLabIconPresentationSystem = {
  version: STUDIO_WORLD_ICON_PRESENTATION_VERSION,
  registry: StudioWorldIconPresentationRegistry,
} as const;

export function resolveStudioWorldIconPresentation(
  name: ExperienceLabIconName,
): IconPresentationProfile {
  return StudioWorldIconPresentationRegistry[name];
}
