/** Generated by scripts/extract-experience-lab-icons.mjs — do not edit manually. */
import type { ExperienceLabIconName } from './experience-lab-icon-registry';

import experienceLabAsset from '../../../assets/studio-world/experience-lab/icons/generated/experience-lab.png';
import blueprintAsset from '../../../assets/studio-world/experience-lab/icons/generated/blueprint.png';
import constructionAsset from '../../../assets/studio-world/experience-lab/icons/generated/construction.png';
import materialsAsset from '../../../assets/studio-world/experience-lab/icons/generated/materials.png';
import lightingAsset from '../../../assets/studio-world/experience-lab/icons/generated/lighting.png';
import cameraAsset from '../../../assets/studio-world/experience-lab/icons/generated/camera.png';
import splitViewAsset from '../../../assets/studio-world/experience-lab/icons/generated/split-view.png';
import founderRenderAsset from '../../../assets/studio-world/experience-lab/icons/generated/founder-render.png';
import projectsAsset from '../../../assets/studio-world/experience-lab/icons/generated/projects.png';
import historyAsset from '../../../assets/studio-world/experience-lab/icons/generated/history.png';
import revisionsAsset from '../../../assets/studio-world/experience-lab/icons/generated/revisions.png';
import milestonesAsset from '../../../assets/studio-world/experience-lab/icons/generated/milestones.png';
import analyticsAsset from '../../../assets/studio-world/experience-lab/icons/generated/analytics.png';
import performanceAsset from '../../../assets/studio-world/experience-lab/icons/generated/performance.png';
import issuesAsset from '../../../assets/studio-world/experience-lab/icons/generated/issues.png';
import approvedAsset from '../../../assets/studio-world/experience-lab/icons/generated/approved.png';
import playbackAsset from '../../../assets/studio-world/experience-lab/icons/generated/playback.png';
import pauseAsset from '../../../assets/studio-world/experience-lab/icons/generated/pause.png';
import stopAsset from '../../../assets/studio-world/experience-lab/icons/generated/stop.png';
import nextAsset from '../../../assets/studio-world/experience-lab/icons/generated/next.png';
import previousAsset from '../../../assets/studio-world/experience-lab/icons/generated/previous.png';
import loopAsset from '../../../assets/studio-world/experience-lab/icons/generated/loop.png';
import captureAsset from '../../../assets/studio-world/experience-lab/icons/generated/capture.png';
import fullscreenAsset from '../../../assets/studio-world/experience-lab/icons/generated/fullscreen.png';
import zoomInAsset from '../../../assets/studio-world/experience-lab/icons/generated/zoom-in.png';
import zoomOutAsset from '../../../assets/studio-world/experience-lab/icons/generated/zoom-out.png';
import panAsset from '../../../assets/studio-world/experience-lab/icons/generated/pan.png';
import fitViewAsset from '../../../assets/studio-world/experience-lab/icons/generated/fit-view.png';
import orbitAsset from '../../../assets/studio-world/experience-lab/icons/generated/orbit.png';
import perspectiveAsset from '../../../assets/studio-world/experience-lab/icons/generated/perspective.png';
import toggleUiAsset from '../../../assets/studio-world/experience-lab/icons/generated/toggle-ui.png';
import gridAsset from '../../../assets/studio-world/experience-lab/icons/generated/grid.png';
import hideAsset from '../../../assets/studio-world/experience-lab/icons/generated/hide.png';
import lockAsset from '../../../assets/studio-world/experience-lab/icons/generated/lock.png';
import unlockAsset from '../../../assets/studio-world/experience-lab/icons/generated/unlock.png';
import duplicateAsset from '../../../assets/studio-world/experience-lab/icons/generated/duplicate.png';
import deleteAsset from '../../../assets/studio-world/experience-lab/icons/generated/delete.png';
import editAsset from '../../../assets/studio-world/experience-lab/icons/generated/edit.png';
import settingsAsset from '../../../assets/studio-world/experience-lab/icons/generated/settings.png';
import filterAsset from '../../../assets/studio-world/experience-lab/icons/generated/filter.png';
import exportAsset from '../../../assets/studio-world/experience-lab/icons/generated/export.png';
import importAsset from '../../../assets/studio-world/experience-lab/icons/generated/import.png';
import cloudSyncAsset from '../../../assets/studio-world/experience-lab/icons/generated/cloud-sync.png';
import databaseAsset from '../../../assets/studio-world/experience-lab/icons/generated/database.png';
import linkAsset from '../../../assets/studio-world/experience-lab/icons/generated/link.png';
import shareAsset from '../../../assets/studio-world/experience-lab/icons/generated/share.png';
import usersAsset from '../../../assets/studio-world/experience-lab/icons/generated/users.png';
import teamAsset from '../../../assets/studio-world/experience-lab/icons/generated/team.png';
import notificationsAsset from '../../../assets/studio-world/experience-lab/icons/generated/notifications.png';
import commentsAsset from '../../../assets/studio-world/experience-lab/icons/generated/comments.png';
import notesAsset from '../../../assets/studio-world/experience-lab/icons/generated/notes.png';
import attachmentsAsset from '../../../assets/studio-world/experience-lab/icons/generated/attachments.png';
import scheduleAsset from '../../../assets/studio-world/experience-lab/icons/generated/schedule.png';
import timeTrackingAsset from '../../../assets/studio-world/experience-lab/icons/generated/time-tracking.png';
import flagAsset from '../../../assets/studio-world/experience-lab/icons/generated/flag.png';
import favoriteAsset from '../../../assets/studio-world/experience-lab/icons/generated/favorite.png';
import dashboardAsset from '../../../assets/studio-world/experience-lab/icons/generated/dashboard.png';
import focusModeAsset from '../../../assets/studio-world/experience-lab/icons/generated/focus-mode.png';
import terminalAsset from '../../../assets/studio-world/experience-lab/icons/generated/terminal.png';
import diagnosticsAsset from '../../../assets/studio-world/experience-lab/icons/generated/diagnostics.png';
import securityAsset from '../../../assets/studio-world/experience-lab/icons/generated/security.png';
import permissionsAsset from '../../../assets/studio-world/experience-lab/icons/generated/permissions.png';
import helpAsset from '../../../assets/studio-world/experience-lab/icons/generated/help.png';
import aboutAsset from '../../../assets/studio-world/experience-lab/icons/generated/about.png';

export type ExperienceLabIconAssetEntry = {
  src: string;
  sourceLabel: string;
  category: string;
  confidence: number;
  auditStatus: 'PASS' | 'WARN' | 'FAIL';
  contentSha256: string;
};

export const EXPERIENCE_LAB_ICON_ASSETS: Record<ExperienceLabIconName, ExperienceLabIconAssetEntry> = {
  experienceLab: {
    src: experienceLabAsset,
    sourceLabel: 'EXPERIENCE LAB',
    category: 'viewport',
    confidence: 0.920,
    auditStatus: 'PASS',
    contentSha256: 'f97b64c77da837b6119445f2f2dd92ce0131c9c97d216dad8f9f96976875421f',
  },
  blueprint: {
    src: blueprintAsset,
    sourceLabel: 'BLUEPRINT',
    category: 'viewport',
    confidence: 1.000,
    auditStatus: 'PASS',
    contentSha256: 'd9e55658b30dea80edeae0f46257c7996f4358842a829843f1f84a6ed2266f96',
  },
  construction: {
    src: constructionAsset,
    sourceLabel: 'CONSTRUCTION',
    category: 'viewport',
    confidence: 1.000,
    auditStatus: 'PASS',
    contentSha256: '230d8ab1dbffb74d353c982eeaf210335a9dd5c4d2875a5c4f369516825adad0',
  },
  materials: {
    src: materialsAsset,
    sourceLabel: 'MATERIALS',
    category: 'viewport',
    confidence: 0.720,
    auditStatus: 'PASS',
    contentSha256: '7c9077c95bae3d05c48ddcb42a0e1ac70e19c08a666dbbc8ba41802326da8cad',
  },
  lighting: {
    src: lightingAsset,
    sourceLabel: 'LIGHTING',
    category: 'viewport',
    confidence: 0.720,
    auditStatus: 'PASS',
    contentSha256: '1864bf420e90d0c40d01fa730b093b757b204d841724fbfcf010f5be40095db4',
  },
  camera: {
    src: cameraAsset,
    sourceLabel: 'CAMERA',
    category: 'viewport',
    confidence: 0.720,
    auditStatus: 'PASS',
    contentSha256: '0478401a26f6183632d9312f8cdb0676c237a51c0dc655d69dab8a45bb5bcff0',
  },
  splitView: {
    src: splitViewAsset,
    sourceLabel: 'SPLIT VIEW',
    category: 'viewport',
    confidence: 1.000,
    auditStatus: 'PASS',
    contentSha256: 'd00187cebcc33e6c5d8f241807198d340175901452a84d014ef278f743497dac',
  },
  founderRender: {
    src: founderRenderAsset,
    sourceLabel: 'FOUNDER RENDER',
    category: 'viewport',
    confidence: 1.000,
    auditStatus: 'PASS',
    contentSha256: '950041f3773434cbe92d199dae4285b22ea08b21dd221b181d15b870c2ab350a',
  },
  projects: {
    src: projectsAsset,
    sourceLabel: 'PROJECTS',
    category: 'project',
    confidence: 1.000,
    auditStatus: 'PASS',
    contentSha256: 'bdb7b556d210069cdb21fa0b543996d65d23079cebee81c965edd1a6fa275943',
  },
  history: {
    src: historyAsset,
    sourceLabel: 'HISTORY',
    category: 'project',
    confidence: 1.000,
    auditStatus: 'PASS',
    contentSha256: '85cacd7a8d5de92668cc9ed75978fbc62f8864cb617d541cd1c5615cab8eb4ce',
  },
  revisions: {
    src: revisionsAsset,
    sourceLabel: 'REVISIONS',
    category: 'project',
    confidence: 1.000,
    auditStatus: 'PASS',
    contentSha256: 'b26427d97c5a8d0242da870d880679abfecaef3dddb8d9da79083dc78a68e2c3',
  },
  milestones: {
    src: milestonesAsset,
    sourceLabel: 'MILESTONES',
    category: 'project',
    confidence: 0.920,
    auditStatus: 'PASS',
    contentSha256: '408da27d9e0893e941b17665e414060ec138c0aacf22e51995aa9d0e5a12389b',
  },
  analytics: {
    src: analyticsAsset,
    sourceLabel: 'ANALYTICS',
    category: 'project',
    confidence: 1.000,
    auditStatus: 'PASS',
    contentSha256: 'c194c97be8e2f1ec1e4496708daef5275566655b01baca7abc85dda6e201ed9a',
  },
  performance: {
    src: performanceAsset,
    sourceLabel: 'PERFORMANCE',
    category: 'project',
    confidence: 1.000,
    auditStatus: 'PASS',
    contentSha256: '50f47a990faabc619f8c7746abec6abdb1a7e08d455d80fcb0a26b9d972be088',
  },
  issues: {
    src: issuesAsset,
    sourceLabel: 'ISSUES',
    category: 'project',
    confidence: 1.000,
    auditStatus: 'PASS',
    contentSha256: 'e6157df2919686ac495bb07945c613247de6755e0fa75b27556ab711b12c7dd7',
  },
  approved: {
    src: approvedAsset,
    sourceLabel: 'APPROVED',
    category: 'project',
    confidence: 1.000,
    auditStatus: 'PASS',
    contentSha256: '49c55b2c05abef62b086c9584ab98c21818cea55c622d08a28d66afe4d8a21ff',
  },
  playback: {
    src: playbackAsset,
    sourceLabel: 'PLAYBACK',
    category: 'playback',
    confidence: 1.000,
    auditStatus: 'PASS',
    contentSha256: '3081594bb5a31f20c7f06116e1ca19257adf8492be247668470374c7d387e269',
  },
  pause: {
    src: pauseAsset,
    sourceLabel: 'PAUSE',
    category: 'playback',
    confidence: 1.000,
    auditStatus: 'PASS',
    contentSha256: 'd78e0cd46d217e22df8155ab93761a010baaa1cfe84e0431c21a349d1a4b13cd',
  },
  stop: {
    src: stopAsset,
    sourceLabel: 'STOP',
    category: 'playback',
    confidence: 1.000,
    auditStatus: 'PASS',
    contentSha256: 'db1fbd84d1148fcd9d49a3e5177dbf3d5319576a837dc7ca0f2023cc8661aa19',
  },
  next: {
    src: nextAsset,
    sourceLabel: 'NEXT',
    category: 'playback',
    confidence: 1.000,
    auditStatus: 'PASS',
    contentSha256: '982017e499f93fba021e238089e1aafcc58f31debb5e923c26e4c3f71924f5bb',
  },
  previous: {
    src: previousAsset,
    sourceLabel: 'PREVIOUS',
    category: 'playback',
    confidence: 1.000,
    auditStatus: 'PASS',
    contentSha256: 'aef7fa5b8e4499add5585fb074ce4ae72f9b3a5fd21d7bc1d038f614f67ba9ab',
  },
  loop: {
    src: loopAsset,
    sourceLabel: 'LOOP',
    category: 'playback',
    confidence: 1.000,
    auditStatus: 'PASS',
    contentSha256: 'c58ac9e71aedfcf2071144d750c0438ff46a04e1c8ce0fecc7d17ba7dd104e0d',
  },
  capture: {
    src: captureAsset,
    sourceLabel: 'CAPTURE',
    category: 'playback',
    confidence: 1.000,
    auditStatus: 'PASS',
    contentSha256: 'c965f247238aa523f7185db1058afbb08ad483b3aea597639627e441c43d1d7d',
  },
  fullscreen: {
    src: fullscreenAsset,
    sourceLabel: 'FULLSCREEN',
    category: 'playback',
    confidence: 1.000,
    auditStatus: 'PASS',
    contentSha256: '1e3600ffba6a11aec48c6f0ef31f609b05ce78dbe318d4789281a376a1d15dcf',
  },
  zoomIn: {
    src: zoomInAsset,
    sourceLabel: 'ZOOM IN',
    category: 'viewport-tools',
    confidence: 1.000,
    auditStatus: 'PASS',
    contentSha256: '0360e8ef31109f2a62f957d90d01c1c24c310588054827c542d7d2236c9839c7',
  },
  zoomOut: {
    src: zoomOutAsset,
    sourceLabel: 'ZOOM OUT',
    category: 'viewport-tools',
    confidence: 1.000,
    auditStatus: 'PASS',
    contentSha256: '863a36c63dddf93bbdda6cac635283bb8015c4a2cfc071e6fb97d4c870de07e6',
  },
  pan: {
    src: panAsset,
    sourceLabel: 'PAN',
    category: 'viewport-tools',
    confidence: 1.000,
    auditStatus: 'PASS',
    contentSha256: '2fec8cbfe8309ef3866f5a22e9a402200b5bf766be2a502f67d8a3c71d858224',
  },
  fitView: {
    src: fitViewAsset,
    sourceLabel: 'FIT VIEW',
    category: 'viewport-tools',
    confidence: 0.920,
    auditStatus: 'PASS',
    contentSha256: '8d943decd7d54e59e266f502d8ab46a66582fbbbc2df29d59842a0e594a62c3c',
  },
  orbit: {
    src: orbitAsset,
    sourceLabel: 'ORBIT',
    category: 'viewport-tools',
    confidence: 1.000,
    auditStatus: 'PASS',
    contentSha256: '9070ee2b8ebcd3cb3a0cb61bc6cb9e9990f86689398518e530277bf1d6776196',
  },
  perspective: {
    src: perspectiveAsset,
    sourceLabel: 'PERSPECTIVE',
    category: 'viewport-tools',
    confidence: 0.720,
    auditStatus: 'PASS',
    contentSha256: '3569931b6abb711aef30d9fff5faf8ca0a5d3c08a4f58c7abf880051c2463a3d',
  },
  toggleUi: {
    src: toggleUiAsset,
    sourceLabel: 'TOGGLE UI',
    category: 'viewport-tools',
    confidence: 1.000,
    auditStatus: 'PASS',
    contentSha256: '0c4a108f5f60a66fa7f81969920b8d738ff29c5970f8f5030a07056dce6ab827',
  },
  grid: {
    src: gridAsset,
    sourceLabel: 'GRID',
    category: 'viewport-tools',
    confidence: 1.000,
    auditStatus: 'PASS',
    contentSha256: '6765bf24b0e2fc0826a94374bcc58c3577077d220e313fb969fdeec9dd9ff50e',
  },
  hide: {
    src: hideAsset,
    sourceLabel: 'HIDE',
    category: 'inspector',
    confidence: 0.920,
    auditStatus: 'PASS',
    contentSha256: 'ba28f4228599b69c139ea5f86639ea58b56dda15648ebc420e10b7fa0bb13224',
  },
  lock: {
    src: lockAsset,
    sourceLabel: 'LOCK',
    category: 'inspector',
    confidence: 1.000,
    auditStatus: 'PASS',
    contentSha256: '43d9257e406374b9812c352a5a48b962ef71970deb7a1a44d5c8de3e8472cd97',
  },
  unlock: {
    src: unlockAsset,
    sourceLabel: 'UNLOCK',
    category: 'inspector',
    confidence: 1.000,
    auditStatus: 'PASS',
    contentSha256: '29d41372a222d9ad66ebab022137d01351b9fefea124c850444929801952ed37',
  },
  duplicate: {
    src: duplicateAsset,
    sourceLabel: 'DUPLICATE',
    category: 'inspector',
    confidence: 0.920,
    auditStatus: 'PASS',
    contentSha256: '4ad2b408bb3b94669937e741f775d097386d84070d4bdb4e5f79710090f3360f',
  },
  delete: {
    src: deleteAsset,
    sourceLabel: 'DELETE',
    category: 'inspector',
    confidence: 0.920,
    auditStatus: 'PASS',
    contentSha256: '37e35c212e1f4c76a4c3f48efb25c029f868155ae21137d81db540a26a6f546d',
  },
  edit: {
    src: editAsset,
    sourceLabel: 'EDIT',
    category: 'inspector',
    confidence: 1.000,
    auditStatus: 'PASS',
    contentSha256: 'd5c3b79d6ffa72d1580e6df9244108d77ed4447c5cad2d606eb66fad9b29ec71',
  },
  settings: {
    src: settingsAsset,
    sourceLabel: 'SETTINGS',
    category: 'inspector',
    confidence: 0.920,
    auditStatus: 'PASS',
    contentSha256: 'ce220b549773154a5fb90fc46b415c6075b16a1a848cb4fbfa78509baffd9c76',
  },
  filter: {
    src: filterAsset,
    sourceLabel: 'FILTER',
    category: 'inspector',
    confidence: 1.000,
    auditStatus: 'PASS',
    contentSha256: '618156b248666adf3d76857cc6c9f52a4b1b1124cce2e49f5ce2913b7284fcda',
  },
  export: {
    src: exportAsset,
    sourceLabel: 'EXPORT',
    category: 'data',
    confidence: 0.920,
    auditStatus: 'PASS',
    contentSha256: '7b52b6747c01d6a67e7f9324c669115bbba3e9a50a4bcefed8c2796b889de1b8',
  },
  import: {
    src: importAsset,
    sourceLabel: 'IMPORT',
    category: 'data',
    confidence: 1.000,
    auditStatus: 'PASS',
    contentSha256: '2d590d53c06256f2d1e5d30412cff380d15a9f437cd1411a46b130996e0c0505',
  },
  cloudSync: {
    src: cloudSyncAsset,
    sourceLabel: 'CLOUD SYNC',
    category: 'data',
    confidence: 0.920,
    auditStatus: 'PASS',
    contentSha256: 'b4c6a2ba755ef0df7843f5c31dc868d61f228c97cbaa36c8cb3d8076ffa309ba',
  },
  database: {
    src: databaseAsset,
    sourceLabel: 'DATABASE',
    category: 'data',
    confidence: 0.920,
    auditStatus: 'PASS',
    contentSha256: '3504769164fedb3de935a5ababd20f3f1adc08b84aaa5863198f8f22d7d87789',
  },
  link: {
    src: linkAsset,
    sourceLabel: 'LINK',
    category: 'data',
    confidence: 1.000,
    auditStatus: 'PASS',
    contentSha256: '392a50d30a2d0b8edbe5ca4a2a09a8cb46f740642677a9522ee3b3049387b1b8',
  },
  share: {
    src: shareAsset,
    sourceLabel: 'SHARE',
    category: 'data',
    confidence: 1.000,
    auditStatus: 'PASS',
    contentSha256: 'b35200097757f4ed8195205f1b141def184cdc1b6df10683cdc60ba3576dad18',
  },
  users: {
    src: usersAsset,
    sourceLabel: 'USERS',
    category: 'data',
    confidence: 0.920,
    auditStatus: 'PASS',
    contentSha256: 'f777a10f8a29617c454f94ed67a2373a1ade6cacafb7f9e361a73f31b64aaf5c',
  },
  team: {
    src: teamAsset,
    sourceLabel: 'TEAM',
    category: 'data',
    confidence: 1.000,
    auditStatus: 'PASS',
    contentSha256: '9fa2a3d2b62a8af4d2c7fb9ec10295b44f69fa5709684bde8866725335a3cfb4',
  },
  notifications: {
    src: notificationsAsset,
    sourceLabel: 'NOTIFICATIONS',
    category: 'collaboration',
    confidence: 1.000,
    auditStatus: 'PASS',
    contentSha256: 'f86c9807f4d751755592f3bdee11c11326cdb67efb46b4e132641634a6d9c660',
  },
  comments: {
    src: commentsAsset,
    sourceLabel: 'COMMENTS',
    category: 'collaboration',
    confidence: 1.000,
    auditStatus: 'PASS',
    contentSha256: '877e04286f436ee3ccb33c439cff921e89ca1fd8853f3b7bf5788c637db62b9f',
  },
  notes: {
    src: notesAsset,
    sourceLabel: 'NOTES',
    category: 'collaboration',
    confidence: 0.920,
    auditStatus: 'PASS',
    contentSha256: '4fd49b74ae55e25a3a0da53444c2fa6553fed73538e00cf86a4cc9387c6483ab',
  },
  attachments: {
    src: attachmentsAsset,
    sourceLabel: 'ATTACHMENTS',
    category: 'collaboration',
    confidence: 1.000,
    auditStatus: 'PASS',
    contentSha256: '284257694c522efc360396f7ec7a3c10fa7facc7cc48eb883607b4c7e38d086a',
  },
  schedule: {
    src: scheduleAsset,
    sourceLabel: 'SCHEDULE',
    category: 'collaboration',
    confidence: 0.920,
    auditStatus: 'PASS',
    contentSha256: 'ab448b97f074863e3d27d9aaf52da9d62f6d959988959911e259334ac8f6924d',
  },
  timeTracking: {
    src: timeTrackingAsset,
    sourceLabel: 'TIME TRACKING',
    category: 'collaboration',
    confidence: 1.000,
    auditStatus: 'PASS',
    contentSha256: '745a9efd58649e0192aaa8da00bb3c976569ccecf8cf89ec7b1ef16892d76d77',
  },
  flag: {
    src: flagAsset,
    sourceLabel: 'FLAG',
    category: 'collaboration',
    confidence: 1.000,
    auditStatus: 'PASS',
    contentSha256: '4c4de9913153078522ae8fe4088e3efe40af4b41bf129abacd0f5b107bc0facb',
  },
  favorite: {
    src: favoriteAsset,
    sourceLabel: 'FAVORITE',
    category: 'collaboration',
    confidence: 1.000,
    auditStatus: 'PASS',
    contentSha256: 'd273b66c70607b3b39d79de7ae419992cf1328fc8c1f8b2aed30b9e4765610df',
  },
  dashboard: {
    src: dashboardAsset,
    sourceLabel: 'DASHBOARD',
    category: 'navigation',
    confidence: 1.000,
    auditStatus: 'PASS',
    contentSha256: '804bd4a64657cf3a66c3be2db38b4b85c07e8ff1175c9ec2ed88e760fc110e23',
  },
  focusMode: {
    src: focusModeAsset,
    sourceLabel: 'FOCUS MODE',
    category: 'navigation',
    confidence: 1.000,
    auditStatus: 'PASS',
    contentSha256: '3aa7953de7357f1f1014919abb061665641e41dc4b641a1f357421785f39edd6',
  },
  terminal: {
    src: terminalAsset,
    sourceLabel: 'TERMINAL',
    category: 'navigation',
    confidence: 0.720,
    auditStatus: 'PASS',
    contentSha256: 'cea2f45c0f64bc15c73b5211e8f8ce4dd571165cee534729191080b3b199217e',
  },
  diagnostics: {
    src: diagnosticsAsset,
    sourceLabel: 'DIAGNOSTICS',
    category: 'navigation',
    confidence: 1.000,
    auditStatus: 'PASS',
    contentSha256: '29b1e87b3dab305b410296872e84b018a567c6e04684a1944a76c86ee8ed13bf',
  },
  security: {
    src: securityAsset,
    sourceLabel: 'SECURITY',
    category: 'navigation',
    confidence: 1.000,
    auditStatus: 'PASS',
    contentSha256: '3e63bcd7138b272346ae198e771cf2d382dc89edf9a6db329cd15a4242a42cd9',
  },
  permissions: {
    src: permissionsAsset,
    sourceLabel: 'PERMISSIONS',
    category: 'navigation',
    confidence: 1.000,
    auditStatus: 'PASS',
    contentSha256: 'f8916808151cdd63d9cfc2a7384c12f7d61da0570dcfd9ad81847334a7be7960',
  },
  help: {
    src: helpAsset,
    sourceLabel: 'HELP',
    category: 'navigation',
    confidence: 1.000,
    auditStatus: 'PASS',
    contentSha256: '7d2ad6d34e567915949da86fde503b547acc34ced114c8e5fe2c791aad42e728',
  },
  about: {
    src: aboutAsset,
    sourceLabel: 'ABOUT',
    category: 'navigation',
    confidence: 1.000,
    auditStatus: 'PASS',
    contentSha256: '984d3945e6629e83c25f6d0a33060dd21b70d00f54d0e87e7659d731ab2bf4e2',
  }
} as Record<ExperienceLabIconName, ExperienceLabIconAssetEntry>;

export const EXPERIENCE_LAB_ICON_EXTRACTION_SOURCE_SHA256 = 'd7476775716d3f2dc9b2416198c81bbd19d8e1a7f5730c5ff3c79fe6cda1f51d';
export const EXPERIENCE_LAB_ICON_EXTRACTION_VERSION = 'experience-lab-icons-v2';
export const EXPERIENCE_LAB_ICON_OPTICAL_LOCK_VERSION = 'experience-lab-icons-v2-locked';
export const EXPERIENCE_LAB_ICON_BUNDLE_SHA256 = 'b7fd4d0a61e282461894bdd8605ddc2e91e4c44ca371f27fbe8e7c163c2daecd';
export const EXPERIENCE_LAB_ICON_LOCKDOWN_CERTIFIED = true;
export const EXPERIENCE_LAB_ICON_OUTPUT_CANVAS = 256;
