/** Generated by scripts/build-experience-lab-icon-atlas.mjs — do not edit manually. */
import type { ExperienceLabIconName } from './experience-lab-icon-registry';

export type ExperienceLabIconRuntimeCoord = {
  x: number;
  y: number;
  w: number;
  h: number;
  sourceLabel: string;
  labelStartInCell: number;
};

export const EXPERIENCE_LAB_ICON_RUNTIME_MAP: Record<ExperienceLabIconName, ExperienceLabIconRuntimeCoord> = {
  "experienceLab": {
    "x": 0,
    "y": 0,
    "w": 96,
    "h": 96,
    "sourceLabel": "EXPERIENCE LAB",
    "labelStartInCell": 117
  },
  "blueprint": {
    "x": 96,
    "y": 0,
    "w": 96,
    "h": 96,
    "sourceLabel": "BLUEPRINT",
    "labelStartInCell": 117
  },
  "construction": {
    "x": 192,
    "y": 0,
    "w": 96,
    "h": 96,
    "sourceLabel": "CONSTRUCTION",
    "labelStartInCell": 117
  },
  "materials": {
    "x": 288,
    "y": 0,
    "w": 96,
    "h": 96,
    "sourceLabel": "MATERIALS",
    "labelStartInCell": 117
  },
  "lighting": {
    "x": 384,
    "y": 0,
    "w": 96,
    "h": 96,
    "sourceLabel": "LIGHTING",
    "labelStartInCell": 117
  },
  "camera": {
    "x": 480,
    "y": 0,
    "w": 96,
    "h": 96,
    "sourceLabel": "CAMERA",
    "labelStartInCell": 117
  },
  "splitView": {
    "x": 576,
    "y": 0,
    "w": 96,
    "h": 96,
    "sourceLabel": "SPLIT VIEW",
    "labelStartInCell": 117
  },
  "founderRender": {
    "x": 672,
    "y": 0,
    "w": 96,
    "h": 96,
    "sourceLabel": "FOUNDER RENDER",
    "labelStartInCell": 117
  },
  "projects": {
    "x": 0,
    "y": 96,
    "w": 96,
    "h": 96,
    "sourceLabel": "PROJECTS",
    "labelStartInCell": 116
  },
  "history": {
    "x": 96,
    "y": 96,
    "w": 96,
    "h": 96,
    "sourceLabel": "HISTORY",
    "labelStartInCell": 116
  },
  "revisions": {
    "x": 192,
    "y": 96,
    "w": 96,
    "h": 96,
    "sourceLabel": "REVISIONS",
    "labelStartInCell": 116
  },
  "milestones": {
    "x": 288,
    "y": 96,
    "w": 96,
    "h": 96,
    "sourceLabel": "MILESTONES",
    "labelStartInCell": 116
  },
  "analytics": {
    "x": 384,
    "y": 96,
    "w": 96,
    "h": 96,
    "sourceLabel": "ANALYTICS",
    "labelStartInCell": 116
  },
  "performance": {
    "x": 480,
    "y": 96,
    "w": 96,
    "h": 96,
    "sourceLabel": "PERFORMANCE",
    "labelStartInCell": 116
  },
  "issues": {
    "x": 576,
    "y": 96,
    "w": 96,
    "h": 96,
    "sourceLabel": "ISSUES",
    "labelStartInCell": 116
  },
  "approved": {
    "x": 672,
    "y": 96,
    "w": 96,
    "h": 96,
    "sourceLabel": "APPROVED",
    "labelStartInCell": 116
  },
  "playback": {
    "x": 0,
    "y": 192,
    "w": 96,
    "h": 96,
    "sourceLabel": "PLAYBACK",
    "labelStartInCell": 115
  },
  "pause": {
    "x": 96,
    "y": 192,
    "w": 96,
    "h": 96,
    "sourceLabel": "PAUSE",
    "labelStartInCell": 115
  },
  "stop": {
    "x": 192,
    "y": 192,
    "w": 96,
    "h": 96,
    "sourceLabel": "STOP",
    "labelStartInCell": 115
  },
  "next": {
    "x": 288,
    "y": 192,
    "w": 96,
    "h": 96,
    "sourceLabel": "NEXT",
    "labelStartInCell": 115
  },
  "previous": {
    "x": 384,
    "y": 192,
    "w": 96,
    "h": 96,
    "sourceLabel": "PREVIOUS",
    "labelStartInCell": 115
  },
  "loop": {
    "x": 480,
    "y": 192,
    "w": 96,
    "h": 96,
    "sourceLabel": "LOOP",
    "labelStartInCell": 115
  },
  "capture": {
    "x": 576,
    "y": 192,
    "w": 96,
    "h": 96,
    "sourceLabel": "CAPTURE",
    "labelStartInCell": 115
  },
  "fullscreen": {
    "x": 672,
    "y": 192,
    "w": 96,
    "h": 96,
    "sourceLabel": "FULLSCREEN",
    "labelStartInCell": 115
  },
  "zoomIn": {
    "x": 0,
    "y": 288,
    "w": 96,
    "h": 96,
    "sourceLabel": "ZOOM IN",
    "labelStartInCell": 116
  },
  "zoomOut": {
    "x": 96,
    "y": 288,
    "w": 96,
    "h": 96,
    "sourceLabel": "ZOOM OUT",
    "labelStartInCell": 116
  },
  "pan": {
    "x": 192,
    "y": 288,
    "w": 96,
    "h": 96,
    "sourceLabel": "PAN",
    "labelStartInCell": 116
  },
  "fitView": {
    "x": 288,
    "y": 288,
    "w": 96,
    "h": 96,
    "sourceLabel": "FIT VIEW",
    "labelStartInCell": 116
  },
  "orbit": {
    "x": 384,
    "y": 288,
    "w": 96,
    "h": 96,
    "sourceLabel": "ORBIT",
    "labelStartInCell": 116
  },
  "perspective": {
    "x": 480,
    "y": 288,
    "w": 96,
    "h": 96,
    "sourceLabel": "PERSPECTIVE",
    "labelStartInCell": 116
  },
  "toggleUi": {
    "x": 576,
    "y": 288,
    "w": 96,
    "h": 96,
    "sourceLabel": "TOGGLE UI",
    "labelStartInCell": 116
  },
  "grid": {
    "x": 672,
    "y": 288,
    "w": 96,
    "h": 96,
    "sourceLabel": "GRID",
    "labelStartInCell": 116
  },
  "hide": {
    "x": 0,
    "y": 384,
    "w": 96,
    "h": 96,
    "sourceLabel": "HIDE",
    "labelStartInCell": 114
  },
  "lock": {
    "x": 96,
    "y": 384,
    "w": 96,
    "h": 96,
    "sourceLabel": "LOCK",
    "labelStartInCell": 122
  },
  "unlock": {
    "x": 192,
    "y": 384,
    "w": 96,
    "h": 96,
    "sourceLabel": "UNLOCK",
    "labelStartInCell": 114
  },
  "duplicate": {
    "x": 288,
    "y": 384,
    "w": 96,
    "h": 96,
    "sourceLabel": "DUPLICATE",
    "labelStartInCell": 114
  },
  "delete": {
    "x": 384,
    "y": 384,
    "w": 96,
    "h": 96,
    "sourceLabel": "DELETE",
    "labelStartInCell": 114
  },
  "edit": {
    "x": 480,
    "y": 384,
    "w": 96,
    "h": 96,
    "sourceLabel": "EDIT",
    "labelStartInCell": 114
  },
  "settings": {
    "x": 576,
    "y": 384,
    "w": 96,
    "h": 96,
    "sourceLabel": "SETTINGS",
    "labelStartInCell": 114
  },
  "filter": {
    "x": 672,
    "y": 384,
    "w": 96,
    "h": 96,
    "sourceLabel": "FILTER",
    "labelStartInCell": 114
  },
  "export": {
    "x": 0,
    "y": 480,
    "w": 96,
    "h": 96,
    "sourceLabel": "EXPORT",
    "labelStartInCell": 110
  },
  "import": {
    "x": 96,
    "y": 480,
    "w": 96,
    "h": 96,
    "sourceLabel": "IMPORT",
    "labelStartInCell": 110
  },
  "cloudSync": {
    "x": 192,
    "y": 480,
    "w": 96,
    "h": 96,
    "sourceLabel": "CLOUD SYNC",
    "labelStartInCell": 110
  },
  "database": {
    "x": 288,
    "y": 480,
    "w": 96,
    "h": 96,
    "sourceLabel": "DATABASE",
    "labelStartInCell": 110
  },
  "link": {
    "x": 384,
    "y": 480,
    "w": 96,
    "h": 96,
    "sourceLabel": "LINK",
    "labelStartInCell": 112
  },
  "share": {
    "x": 480,
    "y": 480,
    "w": 96,
    "h": 96,
    "sourceLabel": "SHARE",
    "labelStartInCell": 110
  },
  "users": {
    "x": 576,
    "y": 480,
    "w": 96,
    "h": 96,
    "sourceLabel": "USERS",
    "labelStartInCell": 110
  },
  "team": {
    "x": 672,
    "y": 480,
    "w": 96,
    "h": 96,
    "sourceLabel": "TEAM",
    "labelStartInCell": 110
  },
  "notifications": {
    "x": 0,
    "y": 576,
    "w": 96,
    "h": 96,
    "sourceLabel": "NOTIFICATIONS",
    "labelStartInCell": 105
  },
  "comments": {
    "x": 96,
    "y": 576,
    "w": 96,
    "h": 96,
    "sourceLabel": "COMMENTS",
    "labelStartInCell": 105
  },
  "notes": {
    "x": 192,
    "y": 576,
    "w": 96,
    "h": 96,
    "sourceLabel": "NOTES",
    "labelStartInCell": 105
  },
  "attachments": {
    "x": 288,
    "y": 576,
    "w": 96,
    "h": 96,
    "sourceLabel": "ATTACHMENTS",
    "labelStartInCell": 105
  },
  "schedule": {
    "x": 384,
    "y": 576,
    "w": 96,
    "h": 96,
    "sourceLabel": "SCHEDULE",
    "labelStartInCell": 106
  },
  "timeTracking": {
    "x": 480,
    "y": 576,
    "w": 96,
    "h": 96,
    "sourceLabel": "TIME TRACKING",
    "labelStartInCell": 105
  },
  "flag": {
    "x": 576,
    "y": 576,
    "w": 96,
    "h": 96,
    "sourceLabel": "FLAG",
    "labelStartInCell": 106
  },
  "favorite": {
    "x": 672,
    "y": 576,
    "w": 96,
    "h": 96,
    "sourceLabel": "FAVORITE",
    "labelStartInCell": 105
  },
  "dashboard": {
    "x": 0,
    "y": 672,
    "w": 96,
    "h": 96,
    "sourceLabel": "DASHBOARD",
    "labelStartInCell": 93
  },
  "focusMode": {
    "x": 96,
    "y": 672,
    "w": 96,
    "h": 96,
    "sourceLabel": "FOCUS MODE",
    "labelStartInCell": 92
  },
  "terminal": {
    "x": 192,
    "y": 672,
    "w": 96,
    "h": 96,
    "sourceLabel": "TERMINAL",
    "labelStartInCell": 93
  },
  "diagnostics": {
    "x": 288,
    "y": 672,
    "w": 96,
    "h": 96,
    "sourceLabel": "DIAGNOSTICS",
    "labelStartInCell": 92
  },
  "security": {
    "x": 384,
    "y": 672,
    "w": 96,
    "h": 96,
    "sourceLabel": "SECURITY",
    "labelStartInCell": 93
  },
  "permissions": {
    "x": 480,
    "y": 672,
    "w": 96,
    "h": 96,
    "sourceLabel": "PERMISSIONS",
    "labelStartInCell": 93
  },
  "help": {
    "x": 576,
    "y": 672,
    "w": 96,
    "h": 96,
    "sourceLabel": "HELP",
    "labelStartInCell": 93
  },
  "about": {
    "x": 672,
    "y": 672,
    "w": 96,
    "h": 96,
    "sourceLabel": "ABOUT",
    "labelStartInCell": 93
  }
} as Record<ExperienceLabIconName, ExperienceLabIconRuntimeCoord>;

export const EXPERIENCE_LAB_ICON_ATLAS_IMPORT = new URL(
  '../../../assets/studio-world/experience-lab/experience-lab-icon-runtime-atlas.png',
  import.meta.url,
).href;
