import type { ExperienceLabIconName } from './experience-lab-icon-registry';

/** Deterministic crop manifest — canonical authority for Studio World icon extraction v3. */
export const STUDIO_WORLD_ICON_CROP_MANIFEST_VERSION = 'studio-world-icon-crops-v3' as const;

export const STUDIO_WORLD_ICON_SOURCE = {
  path: 'src/assets/studio-world/experience-lab/experience-lab-icon-source-labeled.png',
  width: 1402,
  height: 1122,
  rows: 8,
  columns: 8,
  sha256: 'd7476775716d3f2dc9b2416198c81bbd19d8e1a7f5730c5ff3c79fe6cda1f51d',
} as const;

export type StudioWorldIconCropEntry = {
  semanticKey: ExperienceLabIconName;
  sourceLabel: string;
  row: number;
  column: number;
  cropX: number;
  cropY: number;
  cropWidth: number;
  cropHeight: number;
  glyphPadding: number;
  outputSize: number;
  opticalScale: number;
  translateX: number;
  translateY: number;
  approved: boolean;
  notes: string;
};

export const StudioWorldIconCropManifest: Record<ExperienceLabIconName, StudioWorldIconCropEntry> = {
  experienceLab: {
    semanticKey: 'experienceLab',
    sourceLabel: 'EXPERIENCE LAB',
    row: 0,
    column: 0,
    cropX: 83,
    cropY: 36,
    cropWidth: 47,
    cropHeight: 43,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  blueprint: {
    semanticKey: 'blueprint',
    sourceLabel: 'BLUEPRINT',
    row: 0,
    column: 1,
    cropX: 183,
    cropY: 8,
    cropWidth: 160,
    cropHeight: 100,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  construction: {
    semanticKey: 'construction',
    sourceLabel: 'CONSTRUCTION',
    row: 0,
    column: 2,
    cropX: 359,
    cropY: 8,
    cropWidth: 159,
    cropHeight: 100,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  materials: {
    semanticKey: 'materials',
    sourceLabel: 'MATERIALS',
    row: 0,
    column: 3,
    cropX: 567,
    cropY: 42,
    cropWidth: 52,
    cropHeight: 41,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  lighting: {
    semanticKey: 'lighting',
    sourceLabel: 'LIGHTING',
    row: 0,
    column: 4,
    cropX: 714,
    cropY: 42,
    cropWidth: 90,
    cropHeight: 48,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  camera: {
    semanticKey: 'camera',
    sourceLabel: 'CAMERA',
    row: 0,
    column: 5,
    cropX: 903,
    cropY: 49,
    cropWidth: 65,
    cropHeight: 41,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  splitView: {
    semanticKey: 'splitView',
    sourceLabel: 'SPLIT VIEW',
    row: 0,
    column: 6,
    cropX: 1060,
    cropY: 8,
    cropWidth: 159,
    cropHeight: 100,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  founderRender: {
    semanticKey: 'founderRender',
    sourceLabel: 'FOUNDER RENDER',
    row: 0,
    column: 7,
    cropX: 1235,
    cropY: 8,
    cropWidth: 159,
    cropHeight: 100,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  projects: {
    semanticKey: 'projects',
    sourceLabel: 'PROJECTS',
    row: 1,
    column: 0,
    cropX: 32,
    cropY: 140,
    cropWidth: 143,
    cropHeight: 109,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  history: {
    semanticKey: 'history',
    sourceLabel: 'HISTORY',
    row: 1,
    column: 1,
    cropX: 175,
    cropY: 140,
    cropWidth: 175,
    cropHeight: 102,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  revisions: {
    semanticKey: 'revisions',
    sourceLabel: 'REVISIONS',
    row: 1,
    column: 2,
    cropX: 351,
    cropY: 140,
    cropWidth: 157,
    cropHeight: 48,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  milestones: {
    semanticKey: 'milestones',
    sourceLabel: 'MILESTONES',
    row: 1,
    column: 3,
    cropX: 534,
    cropY: 140,
    cropWidth: 120,
    cropHeight: 47,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  analytics: {
    semanticKey: 'analytics',
    sourceLabel: 'ANALYTICS',
    row: 1,
    column: 4,
    cropX: 706,
    cropY: 140,
    cropWidth: 107,
    cropHeight: 107,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  performance: {
    semanticKey: 'performance',
    sourceLabel: 'PERFORMANCE',
    row: 1,
    column: 5,
    cropX: 886,
    cropY: 140,
    cropWidth: 99,
    cropHeight: 48,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  issues: {
    semanticKey: 'issues',
    sourceLabel: 'ISSUES',
    row: 1,
    column: 6,
    cropX: 1052,
    cropY: 140,
    cropWidth: 175,
    cropHeight: 118,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  approved: {
    semanticKey: 'approved',
    sourceLabel: 'APPROVED',
    row: 1,
    column: 7,
    cropX: 1227,
    cropY: 140,
    cropWidth: 153,
    cropHeight: 47,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  playback: {
    semanticKey: 'playback',
    sourceLabel: 'PLAYBACK',
    row: 2,
    column: 0,
    cropX: 50,
    cropY: 281,
    cropWidth: 114,
    cropHeight: 98,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  pause: {
    semanticKey: 'pause',
    sourceLabel: 'PAUSE',
    row: 2,
    column: 1,
    cropX: 221,
    cropY: 281,
    cropWidth: 101,
    cropHeight: 47,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  stop: {
    semanticKey: 'stop',
    sourceLabel: 'STOP',
    row: 2,
    column: 2,
    cropX: 372,
    cropY: 281,
    cropWidth: 116,
    cropHeight: 98,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  next: {
    semanticKey: 'next',
    sourceLabel: 'NEXT',
    row: 2,
    column: 3,
    cropX: 528,
    cropY: 281,
    cropWidth: 132,
    cropHeight: 47,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  previous: {
    semanticKey: 'previous',
    sourceLabel: 'PREVIOUS',
    row: 2,
    column: 4,
    cropX: 701,
    cropY: 281,
    cropWidth: 121,
    cropHeight: 47,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  loop: {
    semanticKey: 'loop',
    sourceLabel: 'LOOP',
    row: 2,
    column: 5,
    cropX: 876,
    cropY: 281,
    cropWidth: 149,
    cropHeight: 100,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  capture: {
    semanticKey: 'capture',
    sourceLabel: 'CAPTURE',
    row: 2,
    column: 6,
    cropX: 1059,
    cropY: 281,
    cropWidth: 89,
    cropHeight: 47,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  fullscreen: {
    semanticKey: 'fullscreen',
    sourceLabel: 'FULLSCREEN',
    row: 2,
    column: 7,
    cropX: 1227,
    cropY: 281,
    cropWidth: 117,
    cropHeight: 47,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  zoomIn: {
    semanticKey: 'zoomIn',
    sourceLabel: 'ZOOM IN',
    row: 3,
    column: 0,
    cropX: 50,
    cropY: 421,
    cropWidth: 115,
    cropHeight: 100,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  zoomOut: {
    semanticKey: 'zoomOut',
    sourceLabel: 'ZOOM OUT',
    row: 3,
    column: 1,
    cropX: 227,
    cropY: 421,
    cropWidth: 87,
    cropHeight: 108,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  pan: {
    semanticKey: 'pan',
    sourceLabel: 'PAN',
    row: 3,
    column: 2,
    cropX: 392,
    cropY: 421,
    cropWidth: 75,
    cropHeight: 94,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  fitView: {
    semanticKey: 'fitView',
    sourceLabel: 'FIT VIEW',
    row: 3,
    column: 3,
    cropX: 555,
    cropY: 421,
    cropWidth: 76,
    cropHeight: 47,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  orbit: {
    semanticKey: 'orbit',
    sourceLabel: 'ORBIT',
    row: 3,
    column: 4,
    cropX: 703,
    cropY: 421,
    cropWidth: 111,
    cropHeight: 91,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  perspective: {
    semanticKey: 'perspective',
    sourceLabel: 'PERSPECTIVE',
    row: 3,
    column: 5,
    cropX: 894,
    cropY: 421,
    cropWidth: 76,
    cropHeight: 93,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  toggleUi: {
    semanticKey: 'toggleUi',
    sourceLabel: 'TOGGLE UI',
    row: 3,
    column: 6,
    cropX: 1052,
    cropY: 421,
    cropWidth: 106,
    cropHeight: 98,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  grid: {
    semanticKey: 'grid',
    sourceLabel: 'GRID',
    row: 3,
    column: 7,
    cropX: 1227,
    cropY: 421,
    cropWidth: 133,
    cropHeight: 47,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  hide: {
    semanticKey: 'hide',
    sourceLabel: 'HIDE',
    row: 4,
    column: 0,
    cropX: 56,
    cropY: 561,
    cropWidth: 101,
    cropHeight: 93,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  lock: {
    semanticKey: 'lock',
    sourceLabel: 'LOCK',
    row: 4,
    column: 1,
    cropX: 212,
    cropY: 561,
    cropWidth: 119,
    cropHeight: 105,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  unlock: {
    semanticKey: 'unlock',
    sourceLabel: 'UNLOCK',
    row: 4,
    column: 2,
    cropX: 397,
    cropY: 561,
    cropWidth: 76,
    cropHeight: 106,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  duplicate: {
    semanticKey: 'duplicate',
    sourceLabel: 'DUPLICATE',
    row: 4,
    column: 3,
    cropX: 542,
    cropY: 561,
    cropWidth: 102,
    cropHeight: 48,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  delete: {
    semanticKey: 'delete',
    sourceLabel: 'DELETE',
    row: 4,
    column: 4,
    cropX: 718,
    cropY: 561,
    cropWidth: 81,
    cropHeight: 94,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  edit: {
    semanticKey: 'edit',
    sourceLabel: 'EDIT',
    row: 4,
    column: 5,
    cropX: 876,
    cropY: 561,
    cropWidth: 138,
    cropHeight: 139,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  settings: {
    semanticKey: 'settings',
    sourceLabel: 'SETTINGS',
    row: 4,
    column: 6,
    cropX: 1052,
    cropY: 561,
    cropWidth: 118,
    cropHeight: 93,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  filter: {
    semanticKey: 'filter',
    sourceLabel: 'FILTER',
    row: 4,
    column: 7,
    cropX: 1240,
    cropY: 561,
    cropWidth: 71,
    cropHeight: 48,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  export: {
    semanticKey: 'export',
    sourceLabel: 'EXPORT',
    row: 5,
    column: 0,
    cropX: 75,
    cropY: 701,
    cropWidth: 65,
    cropHeight: 103,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  import: {
    semanticKey: 'import',
    sourceLabel: 'IMPORT',
    row: 5,
    column: 1,
    cropX: 228,
    cropY: 724,
    cropWidth: 84,
    cropHeight: 74,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  cloudSync: {
    semanticKey: 'cloudSync',
    sourceLabel: 'CLOUD SYNC',
    row: 5,
    column: 2,
    cropX: 393,
    cropY: 726,
    cropWidth: 70,
    cropHeight: 48,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  database: {
    semanticKey: 'database',
    sourceLabel: 'DATABASE',
    row: 5,
    column: 3,
    cropX: 553,
    cropY: 723,
    cropWidth: 79,
    cropHeight: 51,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  link: {
    semanticKey: 'link',
    sourceLabel: 'LINK',
    row: 5,
    column: 4,
    cropX: 718,
    cropY: 724,
    cropWidth: 81,
    cropHeight: 82,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  share: {
    semanticKey: 'share',
    sourceLabel: 'SHARE',
    row: 5,
    column: 5,
    cropX: 893,
    cropY: 724,
    cropWidth: 77,
    cropHeight: 62,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  users: {
    semanticKey: 'users',
    sourceLabel: 'USERS',
    row: 5,
    column: 6,
    cropX: 1073,
    cropY: 724,
    cropWidth: 60,
    cropHeight: 60,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  team: {
    semanticKey: 'team',
    sourceLabel: 'TEAM',
    row: 5,
    column: 7,
    cropX: 1232,
    cropY: 726,
    cropWidth: 85,
    cropHeight: 48,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  notifications: {
    semanticKey: 'notifications',
    sourceLabel: 'NOTIFICATIONS',
    row: 6,
    column: 0,
    cropX: 67,
    cropY: 842,
    cropWidth: 79,
    cropHeight: 87,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  comments: {
    semanticKey: 'comments',
    sourceLabel: 'COMMENTS',
    row: 6,
    column: 1,
    cropX: 226,
    cropY: 842,
    cropWidth: 87,
    cropHeight: 83,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  notes: {
    semanticKey: 'notes',
    sourceLabel: 'NOTES',
    row: 6,
    column: 2,
    cropX: 389,
    cropY: 842,
    cropWidth: 80,
    cropHeight: 77,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  attachments: {
    semanticKey: 'attachments',
    sourceLabel: 'ATTACHMENTS',
    row: 6,
    column: 3,
    cropX: 555,
    cropY: 842,
    cropWidth: 78,
    cropHeight: 83,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  schedule: {
    semanticKey: 'schedule',
    sourceLabel: 'SCHEDULE',
    row: 6,
    column: 4,
    cropX: 717,
    cropY: 842,
    cropWidth: 84,
    cropHeight: 77,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  timeTracking: {
    semanticKey: 'timeTracking',
    sourceLabel: 'TIME TRACKING',
    row: 6,
    column: 5,
    cropX: 888,
    cropY: 842,
    cropWidth: 87,
    cropHeight: 75,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  flag: {
    semanticKey: 'flag',
    sourceLabel: 'FLAG',
    row: 6,
    column: 6,
    cropX: 1062,
    cropY: 842,
    cropWidth: 81,
    cropHeight: 86,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  favorite: {
    semanticKey: 'favorite',
    sourceLabel: 'FAVORITE',
    row: 6,
    column: 7,
    cropX: 1231,
    cropY: 842,
    cropWidth: 87,
    cropHeight: 75,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  dashboard: {
    semanticKey: 'dashboard',
    sourceLabel: 'DASHBOARD',
    row: 7,
    column: 0,
    cropX: 63,
    cropY: 982,
    cropWidth: 85,
    cropHeight: 86,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  focusMode: {
    semanticKey: 'focusMode',
    sourceLabel: 'FOCUS MODE',
    row: 7,
    column: 1,
    cropX: 225,
    cropY: 982,
    cropWidth: 92,
    cropHeight: 88,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  terminal: {
    semanticKey: 'terminal',
    sourceLabel: 'TERMINAL',
    row: 7,
    column: 2,
    cropX: 393,
    cropY: 982,
    cropWidth: 81,
    cropHeight: 71,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  diagnostics: {
    semanticKey: 'diagnostics',
    sourceLabel: 'DIAGNOSTICS',
    row: 7,
    column: 3,
    cropX: 551,
    cropY: 982,
    cropWidth: 92,
    cropHeight: 83,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  security: {
    semanticKey: 'security',
    sourceLabel: 'SECURITY',
    row: 7,
    column: 4,
    cropX: 717,
    cropY: 982,
    cropWidth: 84,
    cropHeight: 87,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  permissions: {
    semanticKey: 'permissions',
    sourceLabel: 'PERMISSIONS',
    row: 7,
    column: 5,
    cropX: 888,
    cropY: 982,
    cropWidth: 88,
    cropHeight: 86,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  help: {
    semanticKey: 'help',
    sourceLabel: 'HELP',
    row: 7,
    column: 6,
    cropX: 1058,
    cropY: 982,
    cropWidth: 90,
    cropHeight: 88,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
  about: {
    semanticKey: 'about',
    sourceLabel: 'ABOUT',
    row: 7,
    column: 7,
    cropX: 1229,
    cropY: 982,
    cropWidth: 90,
    cropHeight: 88,
    glyphPadding: 18,
    outputSize: 512,
    opticalScale: 1,
    translateX: 0,
    translateY: 0,
    approved: false,
    notes: 'Deterministic glyph crop; excludes printed label band.',
  },
} as const;

export const STUDIO_WORLD_ICON_CROP_KEYS = Object.keys(StudioWorldIconCropManifest) as ExperienceLabIconName[];

export function resolveStudioWorldIconCrop(key: ExperienceLabIconName): StudioWorldIconCropEntry {
  return StudioWorldIconCropManifest[key];
}

export function resolveStudioWorldIconCellBounds(entry: StudioWorldIconCropEntry): {
  left: number;
  top: number;
  width: number;
  height: number;
} {
  const { width: sw, height: sh, rows, columns } = STUDIO_WORLD_ICON_SOURCE;
  const left = Math.round((entry.column * sw) / columns);
  const top = Math.round((entry.row * sh) / rows);
  const right = Math.round(((entry.column + 1) * sw) / columns);
  const bottom = Math.round(((entry.row + 1) * sh) / rows);
  return { left, top, width: Math.max(1, right - left), height: Math.max(1, bottom - top) };
}

export function isCropInsideCell(entry: StudioWorldIconCropEntry): boolean {
  const cell = resolveStudioWorldIconCellBounds(entry);
  return (
    entry.cropX >= cell.left &&
    entry.cropY >= cell.top &&
    entry.cropX + entry.cropWidth <= cell.left + cell.width &&
    entry.cropY + entry.cropHeight <= cell.top + cell.height
  );
}

export const STUDIO_WORLD_ICON_V3_OUTPUT_DIR =
  'src/assets/studio-world/experience-lab/icons/generated-v3' as const;

/** v2 automated extraction is frozen — do not certify until v3 crops are founder-approved. */
export const EXPERIENCE_LAB_ICON_V2_PIPELINE_FROZEN = true as const;
export const EXPERIENCE_LAB_ICON_LOCKDOWN_CERTIFIED = false as const;
