/** Per-cell label masks — generated by scripts/create-studio-world-unlabeled-source-twin.mjs */
export const STUDIO_WORLD_ICON_LABEL_MASK_VERSION = 'studio-world-icons-v5-source-twin' as const;

export type StudioWorldIconLabelMask = {
  key: string;
  sourceLabel: string;
  iconSafeTop: number;
  iconSafeBottom: number;
  labelMaskTop: number;
  labelMaskBottom: number;
  left: number;
  right: number;
};

export const STUDIO_WORLD_ICON_LABEL_MASKS: Record<string, StudioWorldIconLabelMask> = {
  "experienceLab": {
    "key": "experienceLab",
    "sourceLabel": "EXPERIENCE LAB",
    "iconSafeTop": 0,
    "iconSafeBottom": 71,
    "labelMaskTop": 72,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 174
  },
  "blueprint": {
    "key": "blueprint",
    "sourceLabel": "BLUEPRINT",
    "iconSafeTop": 0,
    "iconSafeBottom": 71,
    "labelMaskTop": 72,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 175
  },
  "construction": {
    "key": "construction",
    "sourceLabel": "CONSTRUCTION",
    "iconSafeTop": 0,
    "iconSafeBottom": 71,
    "labelMaskTop": 72,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 174
  },
  "materials": {
    "key": "materials",
    "sourceLabel": "MATERIALS",
    "iconSafeTop": 0,
    "iconSafeBottom": 71,
    "labelMaskTop": 72,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 174
  },
  "lighting": {
    "key": "lighting",
    "sourceLabel": "LIGHTING",
    "iconSafeTop": 0,
    "iconSafeBottom": 71,
    "labelMaskTop": 72,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 174
  },
  "camera": {
    "key": "camera",
    "sourceLabel": "CAMERA",
    "iconSafeTop": 0,
    "iconSafeBottom": 71,
    "labelMaskTop": 72,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 175
  },
  "splitView": {
    "key": "splitView",
    "sourceLabel": "SPLIT VIEW",
    "iconSafeTop": 0,
    "iconSafeBottom": 71,
    "labelMaskTop": 72,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 174
  },
  "founderRender": {
    "key": "founderRender",
    "sourceLabel": "FOUNDER RENDER",
    "iconSafeTop": 0,
    "iconSafeBottom": 71,
    "labelMaskTop": 72,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 174
  },
  "projects": {
    "key": "projects",
    "sourceLabel": "PROJECTS",
    "iconSafeTop": 0,
    "iconSafeBottom": 83,
    "labelMaskTop": 84,
    "labelMaskBottom": 140,
    "left": 0,
    "right": 174
  },
  "history": {
    "key": "history",
    "sourceLabel": "HISTORY",
    "iconSafeTop": 0,
    "iconSafeBottom": 81,
    "labelMaskTop": 82,
    "labelMaskBottom": 140,
    "left": 0,
    "right": 175
  },
  "revisions": {
    "key": "revisions",
    "sourceLabel": "REVISIONS",
    "iconSafeTop": 0,
    "iconSafeBottom": 79,
    "labelMaskTop": 80,
    "labelMaskBottom": 140,
    "left": 0,
    "right": 174
  },
  "milestones": {
    "key": "milestones",
    "sourceLabel": "MILESTONES",
    "iconSafeTop": 0,
    "iconSafeBottom": 77,
    "labelMaskTop": 78,
    "labelMaskBottom": 140,
    "left": 0,
    "right": 174
  },
  "analytics": {
    "key": "analytics",
    "sourceLabel": "ANALYTICS",
    "iconSafeTop": 0,
    "iconSafeBottom": 88,
    "labelMaskTop": 89,
    "labelMaskBottom": 140,
    "left": 0,
    "right": 174
  },
  "performance": {
    "key": "performance",
    "sourceLabel": "PERFORMANCE",
    "iconSafeTop": 0,
    "iconSafeBottom": 80,
    "labelMaskTop": 81,
    "labelMaskBottom": 140,
    "left": 0,
    "right": 175
  },
  "issues": {
    "key": "issues",
    "sourceLabel": "ISSUES",
    "iconSafeTop": 0,
    "iconSafeBottom": 87,
    "labelMaskTop": 88,
    "labelMaskBottom": 140,
    "left": 0,
    "right": 174
  },
  "approved": {
    "key": "approved",
    "sourceLabel": "APPROVED",
    "iconSafeTop": 0,
    "iconSafeBottom": 78,
    "labelMaskTop": 79,
    "labelMaskBottom": 140,
    "left": 0,
    "right": 174
  },
  "playback": {
    "key": "playback",
    "sourceLabel": "PLAYBACK",
    "iconSafeTop": 0,
    "iconSafeBottom": 79,
    "labelMaskTop": 80,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 174
  },
  "pause": {
    "key": "pause",
    "sourceLabel": "PAUSE",
    "iconSafeTop": 0,
    "iconSafeBottom": 79,
    "labelMaskTop": 80,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 175
  },
  "stop": {
    "key": "stop",
    "sourceLabel": "STOP",
    "iconSafeTop": 0,
    "iconSafeBottom": 79,
    "labelMaskTop": 80,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 174
  },
  "next": {
    "key": "next",
    "sourceLabel": "NEXT",
    "iconSafeTop": 0,
    "iconSafeBottom": 79,
    "labelMaskTop": 80,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 174
  },
  "previous": {
    "key": "previous",
    "sourceLabel": "PREVIOUS",
    "iconSafeTop": 0,
    "iconSafeBottom": 79,
    "labelMaskTop": 80,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 174
  },
  "loop": {
    "key": "loop",
    "sourceLabel": "LOOP",
    "iconSafeTop": 0,
    "iconSafeBottom": 83,
    "labelMaskTop": 84,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 175
  },
  "capture": {
    "key": "capture",
    "sourceLabel": "CAPTURE",
    "iconSafeTop": 0,
    "iconSafeBottom": 78,
    "labelMaskTop": 79,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 174
  },
  "fullscreen": {
    "key": "fullscreen",
    "sourceLabel": "FULLSCREEN",
    "iconSafeTop": 0,
    "iconSafeBottom": 80,
    "labelMaskTop": 81,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 174
  },
  "zoomIn": {
    "key": "zoomIn",
    "sourceLabel": "ZOOM IN",
    "iconSafeTop": 0,
    "iconSafeBottom": 73,
    "labelMaskTop": 74,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 174
  },
  "zoomOut": {
    "key": "zoomOut",
    "sourceLabel": "ZOOM OUT",
    "iconSafeTop": 0,
    "iconSafeBottom": 73,
    "labelMaskTop": 74,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 175
  },
  "pan": {
    "key": "pan",
    "sourceLabel": "PAN",
    "iconSafeTop": 0,
    "iconSafeBottom": 72,
    "labelMaskTop": 73,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 174
  },
  "fitView": {
    "key": "fitView",
    "sourceLabel": "FIT VIEW",
    "iconSafeTop": 0,
    "iconSafeBottom": 71,
    "labelMaskTop": 72,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 174
  },
  "orbit": {
    "key": "orbit",
    "sourceLabel": "ORBIT",
    "iconSafeTop": 0,
    "iconSafeBottom": 71,
    "labelMaskTop": 72,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 174
  },
  "perspective": {
    "key": "perspective",
    "sourceLabel": "PERSPECTIVE",
    "iconSafeTop": 0,
    "iconSafeBottom": 73,
    "labelMaskTop": 74,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 175
  },
  "toggleUi": {
    "key": "toggleUi",
    "sourceLabel": "TOGGLE UI",
    "iconSafeTop": 0,
    "iconSafeBottom": 78,
    "labelMaskTop": 79,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 174
  },
  "grid": {
    "key": "grid",
    "sourceLabel": "GRID",
    "iconSafeTop": 0,
    "iconSafeBottom": 73,
    "labelMaskTop": 74,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 174
  },
  "hide": {
    "key": "hide",
    "sourceLabel": "HIDE",
    "iconSafeTop": 0,
    "iconSafeBottom": 71,
    "labelMaskTop": 72,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 174
  },
  "lock": {
    "key": "lock",
    "sourceLabel": "LOCK",
    "iconSafeTop": 0,
    "iconSafeBottom": 71,
    "labelMaskTop": 72,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 175
  },
  "unlock": {
    "key": "unlock",
    "sourceLabel": "UNLOCK",
    "iconSafeTop": 0,
    "iconSafeBottom": 71,
    "labelMaskTop": 72,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 174
  },
  "duplicate": {
    "key": "duplicate",
    "sourceLabel": "DUPLICATE",
    "iconSafeTop": 0,
    "iconSafeBottom": 72,
    "labelMaskTop": 73,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 174
  },
  "delete": {
    "key": "delete",
    "sourceLabel": "DELETE",
    "iconSafeTop": 0,
    "iconSafeBottom": 71,
    "labelMaskTop": 72,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 174
  },
  "edit": {
    "key": "edit",
    "sourceLabel": "EDIT",
    "iconSafeTop": 0,
    "iconSafeBottom": 71,
    "labelMaskTop": 72,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 175
  },
  "settings": {
    "key": "settings",
    "sourceLabel": "SETTINGS",
    "iconSafeTop": 0,
    "iconSafeBottom": 79,
    "labelMaskTop": 80,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 174
  },
  "filter": {
    "key": "filter",
    "sourceLabel": "FILTER",
    "iconSafeTop": 0,
    "iconSafeBottom": 71,
    "labelMaskTop": 72,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 174
  },
  "export": {
    "key": "export",
    "sourceLabel": "EXPORT",
    "iconSafeTop": 0,
    "iconSafeBottom": 72,
    "labelMaskTop": 73,
    "labelMaskBottom": 140,
    "left": 0,
    "right": 174
  },
  "import": {
    "key": "import",
    "sourceLabel": "IMPORT",
    "iconSafeTop": 0,
    "iconSafeBottom": 72,
    "labelMaskTop": 73,
    "labelMaskBottom": 140,
    "left": 0,
    "right": 175
  },
  "cloudSync": {
    "key": "cloudSync",
    "sourceLabel": "CLOUD SYNC",
    "iconSafeTop": 0,
    "iconSafeBottom": 72,
    "labelMaskTop": 73,
    "labelMaskBottom": 140,
    "left": 0,
    "right": 174
  },
  "database": {
    "key": "database",
    "sourceLabel": "DATABASE",
    "iconSafeTop": 0,
    "iconSafeBottom": 72,
    "labelMaskTop": 73,
    "labelMaskBottom": 140,
    "left": 0,
    "right": 174
  },
  "link": {
    "key": "link",
    "sourceLabel": "LINK",
    "iconSafeTop": 0,
    "iconSafeBottom": 74,
    "labelMaskTop": 75,
    "labelMaskBottom": 140,
    "left": 0,
    "right": 174
  },
  "share": {
    "key": "share",
    "sourceLabel": "SHARE",
    "iconSafeTop": 0,
    "iconSafeBottom": 105,
    "labelMaskTop": 106,
    "labelMaskBottom": 140,
    "left": 0,
    "right": 175
  },
  "users": {
    "key": "users",
    "sourceLabel": "USERS",
    "iconSafeTop": 0,
    "iconSafeBottom": 72,
    "labelMaskTop": 73,
    "labelMaskBottom": 140,
    "left": 0,
    "right": 174
  },
  "team": {
    "key": "team",
    "sourceLabel": "TEAM",
    "iconSafeTop": 0,
    "iconSafeBottom": 72,
    "labelMaskTop": 73,
    "labelMaskBottom": 140,
    "left": 0,
    "right": 174
  },
  "notifications": {
    "key": "notifications",
    "sourceLabel": "NOTIFICATIONS",
    "iconSafeTop": 0,
    "iconSafeBottom": 83,
    "labelMaskTop": 84,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 174
  },
  "comments": {
    "key": "comments",
    "sourceLabel": "COMMENTS",
    "iconSafeTop": 0,
    "iconSafeBottom": 83,
    "labelMaskTop": 84,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 175
  },
  "notes": {
    "key": "notes",
    "sourceLabel": "NOTES",
    "iconSafeTop": 0,
    "iconSafeBottom": 83,
    "labelMaskTop": 84,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 174
  },
  "attachments": {
    "key": "attachments",
    "sourceLabel": "ATTACHMENTS",
    "iconSafeTop": 0,
    "iconSafeBottom": 83,
    "labelMaskTop": 84,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 174
  },
  "schedule": {
    "key": "schedule",
    "sourceLabel": "SCHEDULE",
    "iconSafeTop": 0,
    "iconSafeBottom": 83,
    "labelMaskTop": 84,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 174
  },
  "timeTracking": {
    "key": "timeTracking",
    "sourceLabel": "TIME TRACKING",
    "iconSafeTop": 0,
    "iconSafeBottom": 83,
    "labelMaskTop": 84,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 175
  },
  "flag": {
    "key": "flag",
    "sourceLabel": "FLAG",
    "iconSafeTop": 0,
    "iconSafeBottom": 83,
    "labelMaskTop": 84,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 174
  },
  "favorite": {
    "key": "favorite",
    "sourceLabel": "FAVORITE",
    "iconSafeTop": 0,
    "iconSafeBottom": 83,
    "labelMaskTop": 84,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 174
  },
  "dashboard": {
    "key": "dashboard",
    "sourceLabel": "DASHBOARD",
    "iconSafeTop": 0,
    "iconSafeBottom": 72,
    "labelMaskTop": 73,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 174
  },
  "focusMode": {
    "key": "focusMode",
    "sourceLabel": "FOCUS MODE",
    "iconSafeTop": 0,
    "iconSafeBottom": 72,
    "labelMaskTop": 73,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 175
  },
  "terminal": {
    "key": "terminal",
    "sourceLabel": "TERMINAL",
    "iconSafeTop": 0,
    "iconSafeBottom": 72,
    "labelMaskTop": 73,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 174
  },
  "diagnostics": {
    "key": "diagnostics",
    "sourceLabel": "DIAGNOSTICS",
    "iconSafeTop": 0,
    "iconSafeBottom": 72,
    "labelMaskTop": 73,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 174
  },
  "security": {
    "key": "security",
    "sourceLabel": "SECURITY",
    "iconSafeTop": 0,
    "iconSafeBottom": 72,
    "labelMaskTop": 73,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 174
  },
  "permissions": {
    "key": "permissions",
    "sourceLabel": "PERMISSIONS",
    "iconSafeTop": 0,
    "iconSafeBottom": 72,
    "labelMaskTop": 73,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 175
  },
  "help": {
    "key": "help",
    "sourceLabel": "HELP",
    "iconSafeTop": 0,
    "iconSafeBottom": 72,
    "labelMaskTop": 73,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 174
  },
  "about": {
    "key": "about",
    "sourceLabel": "ABOUT",
    "iconSafeTop": 0,
    "iconSafeBottom": 72,
    "labelMaskTop": 73,
    "labelMaskBottom": 139,
    "left": 0,
    "right": 174
  }
} as Record<string, StudioWorldIconLabelMask>;
