import { bootstrapDistributionEngineStore } from './store';
import type { DistributionEngineStore, DistributionFormatId, KnowledgeAsset } from './types';

function daysFromNow(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString();
}

function daysAgo(days: number): string {
  return daysFromNow(-days);
}

export function buildDistributionEngineSeed(): Partial<DistributionEngineStore> {
  const knowledgeAssets: KnowledgeAsset[] = [
    {
      id: 'ka-page-042',
      workspaceId: 'ndxbook' as const,
      title: 'PAGE 042 · MONEY HABITS CHAPTER',
      sourceType: 'page' as const,
      sourceId: 'pg-042',
      campaignId: 'camp-money-monday-mar',
      campaignLabel: 'MONEY MONDAY · MARCH CYCLE',
      status: 'approved' as const,
      knowledgeValueScore: 92,
      maturityPct: 88,
      potentialFormats: ['instagram-reel', 'tiktok', 'youtube-shorts', 'linkedin-carousel', 'newsletter', 'blog-article', 'podcast-outline'] as DistributionFormatId[],
      approvedFormats: ['instagram-reel', 'tiktok', 'youtube-shorts', 'newsletter'] as DistributionFormatId[],
      unifiedSourceOfTruth: 'pg-042 · ndxbook newsroom page',
      createdAt: daysAgo(14),
    },
    {
      id: 'ka-page-028',
      workspaceId: 'ndxbook' as const,
      title: 'PAGE 028 · CROSS-PLATFORM CORE',
      sourceType: 'page' as const,
      sourceId: 'pg-028',
      campaignId: 'camp-page-028',
      campaignLabel: 'PAGE 028 · CROSS-PLATFORM PUSH',
      status: 'distributing' as const,
      knowledgeValueScore: 85,
      maturityPct: 72,
      potentialFormats: ['instagram-reel', 'tiktok', 'pinterest-pin', 'x-thread', 'threads'] as DistributionFormatId[],
      approvedFormats: ['instagram-reel', 'tiktok'] as DistributionFormatId[],
      unifiedSourceOfTruth: 'pg-028 · ndxbook newsroom page',
      createdAt: daysAgo(7),
    },
    {
      id: 'ka-truth-sleep',
      workspaceId: 'ndxbook' as const,
      title: 'TRUTH TUESDAY · SLEEP DEBT',
      sourceType: 'page' as const,
      sourceId: 'pg-041',
      campaignId: 'camp-truth-tuesday',
      campaignLabel: 'TRUTH TUESDAY · FACT-FORWARD',
      status: 'evergreen' as const,
      knowledgeValueScore: 88,
      maturityPct: 95,
      potentialFormats: ['instagram-reel', 'youtube-shorts', 'linkedin-post', 'newsletter', 'podcast-episode'] as DistributionFormatId[],
      approvedFormats: ['instagram-reel', 'youtube-shorts', 'newsletter'] as DistributionFormatId[],
      unifiedSourceOfTruth: 'pg-041 · research-gated page',
      createdAt: daysAgo(90),
    },
  ];

  return {
    dashboard: {
      summary:
        'DISTRIBUTION ENGINE V1.0 — global nervous system for knowledge assets. One approved asset becomes dozens of platform-specific experiences while maintaining a unified source of truth. Founders approve strategy · Studio OS executes.',
      knowledgeAssets: 0,
      formatsGenerated: 0,
      scheduledThisWeek: 0,
      evergreenActive: 0,
      avgHealthPct: 0,
      knowledgeReach: '128K',
    },
    activeWorkspaceId: 'ndxbook',
    knowledgeAssets,
    strategies: [
      {
        id: 'ds-1',
        assetId: 'ka-page-042',
        campaignId: 'camp-money-monday-mar',
        label: 'MONEY MONDAY · MULTI-PLATFORM LAUNCH',
        objective: 'Maximize reader growth via stat-forward short-form + newsletter depth',
        founderApproved: true,
        status: 'active',
        targetAudiences: ['New readers', 'Returning readers', 'Money-curious professionals'],
        primaryChannels: ['instagram', 'tiktok', 'youtube', 'newsletter'],
        confidencePct: 89,
        rationale: 'Historical money content +18% CTR on stat overlays · Labs #38 validated',
      },
      {
        id: 'ds-2',
        assetId: 'ka-page-028',
        campaignId: 'camp-page-028',
        label: 'DISCOVERY-FIRST · TIKTOK + INSTAGRAM',
        objective: '2x reach vs organic baseline · platform-native hooks',
        founderApproved: true,
        status: 'active',
        targetAudiences: ['New readers', 'Students'],
        primaryChannels: ['tiktok', 'instagram'],
        confidencePct: 74,
        rationale: 'Cross-platform initiative · OAuth pending · defer LinkedIn until page matures',
      },
    ],
    adaptations: [
      {
        id: 'pa-1',
        assetId: 'ka-page-042',
        formatId: 'instagram-reel',
        channelId: 'instagram',
        status: 'ready',
        hook: '3 money habits keeping you broke (backed by Federal Reserve data)',
        caption: 'Research-gated · ndxbook Money Monday · link in bio',
        hashtags: ['#MoneyMonday', '#PersonalFinance', '#ndxbook'],
        thumbnail: 'Stat overlay · Labs #38 template',
        timing: '0:00 hook · 0:03 stat · 0:12 CTA',
        preservesKnowledge: true,
      },
      {
        id: 'pa-2',
        assetId: 'ka-page-042',
        formatId: 'tiktok',
        channelId: 'tiktok',
        status: 'ready',
        hook: 'POV: you finally read the fine print on your savings account',
        caption: 'Money habits chapter · full page on ndxbook',
        timing: 'Fast pace · 28s · sound: trending finance',
        preservesKnowledge: true,
      },
      {
        id: 'pa-3',
        assetId: 'ka-page-042',
        formatId: 'newsletter',
        channelId: 'newsletter',
        status: 'generating',
        title: 'Money Monday · The 3 habits chapter',
        cta: 'Read full chapter · share with a friend',
        tone: 'Long-form narrative · authority through consistency',
        preservesKnowledge: true,
      },
      {
        id: 'pa-4',
        assetId: 'ka-truth-sleep',
        formatId: 'youtube-shorts',
        channelId: 'youtube',
        status: 'published',
        title: 'Sleep debt is real · what research says',
        description: 'Truth Tuesday · research-gated · ndxbook',
        seo: 'sleep debt, research, health facts',
        preservesKnowledge: true,
      },
    ],
    intelligenceRecs: [
      {
        id: 'ir-1',
        assetId: 'ka-page-042',
        where: 'TikTok + Instagram Reels first · Newsletter 48h later',
        when: 'Tuesday 9am ET · Money Monday cadence',
        how: 'Stat overlay hook · question CTA · Labs #38 thumbnail',
        why: 'Money content peaks Tue-Wed · stat overlays +18% CTR historically',
        confidencePct: 89,
        factors: {
          platformFit: 92,
          audienceFit: 88,
          historicalPerformance: 91,
          campaignObjective: 90,
          trends: 78,
          seasonality: 85,
          competition: 72,
          timing: 88,
          contentMaturity: 86,
          knowledgeValue: 92,
        },
      },
      {
        id: 'ir-2',
        assetId: 'ka-truth-sleep',
        where: 'Republish YouTube Shorts · refresh LinkedIn carousel',
        when: 'Q2 evergreen window · low competition week',
        how: 'Update stat citation · new thumbnail A/B via Labs',
        why: 'Evergreen health content · 91% completion on prior publish',
        confidencePct: 84,
        factors: {
          platformFit: 86,
          audienceFit: 90,
          historicalPerformance: 88,
          campaignObjective: 82,
          trends: 70,
          seasonality: 92,
          competition: 75,
          timing: 80,
          contentMaturity: 95,
          knowledgeValue: 88,
        },
      },
    ],
    calendar: [
      { id: 'cal-1', assetId: 'ka-page-042', formatId: 'instagram-reel', channelId: 'instagram', label: 'Money habits · Reel', scheduledAt: daysFromNow(2), status: 'scheduled', timezone: 'America/New_York', campaignId: 'camp-money-monday-mar' },
      { id: 'cal-2', assetId: 'ka-page-042', formatId: 'tiktok', channelId: 'tiktok', label: 'Money habits · TikTok', scheduledAt: daysFromNow(2), status: 'scheduled', timezone: 'America/New_York', campaignId: 'camp-money-monday-mar' },
      { id: 'cal-3', assetId: 'ka-page-042', formatId: 'newsletter', channelId: 'newsletter', label: 'Money Monday · Newsletter', scheduledAt: daysFromNow(4), status: 'processing', timezone: 'America/New_York', campaignId: 'camp-money-monday-mar' },
      { id: 'cal-4', assetId: 'ka-truth-sleep', formatId: 'youtube-shorts', channelId: 'youtube', label: 'Sleep debt · Republish', scheduledAt: daysFromNow(14), status: 'evergreen', timezone: 'America/New_York' },
      { id: 'cal-5', assetId: 'ka-page-028', formatId: 'tiktok', channelId: 'tiktok', label: 'Page 028 · Launch', scheduledAt: daysFromNow(10), status: 'scheduled', timezone: 'America/New_York', campaignId: 'camp-page-028' },
    ],
    evergreen: [
      { id: 'ev-1', assetId: 'ka-truth-sleep', title: 'Sleep debt · Truth Tuesday', action: 'republish', reason: '91% completion · evergreen health topic · Q2 refresh window', confidencePct: 84, lastPublishedAt: daysAgo(60), projectedLift: '+12% reach vs baseline' },
      { id: 'ev-2', assetId: 'ka-truth-sleep', title: 'Sleep debt · Bundle opportunity', action: 'bundle', reason: '3 Truth Tuesday health pages → learning path', confidencePct: 78, lastPublishedAt: daysAgo(60), projectedLift: 'Course lesson candidate' },
    ],
    collections: [
      { id: 'col-1', workspaceId: 'ndxbook', type: 'series', title: 'MONEY MONDAY · MARCH VOLUME', assetIds: ['ka-page-042'], assetCount: 4, bundlingOpportunity: '4 pages → ebook chapter + course module', status: 'active' },
      { id: 'col-2', workspaceId: 'ndxbook', type: 'learning-path', title: 'TRUTH TUESDAY · HEALTH ESSENTIALS', assetIds: ['ka-truth-sleep'], assetCount: 6, bundlingOpportunity: '6 pages → wellness learning path · podcast series', status: 'proposed' },
    ],
    audienceSegments: [
      { id: 'aud-1', label: 'New readers', description: 'Discovery-first · short-form hooks · platform-native', distributionStrategy: 'TikTok + Reels · question hooks · low-friction CTA', personalizationLevel: 'tailored' },
      { id: 'aud-2', label: 'Returning readers', description: 'Depth-first · newsletter · long-form', distributionStrategy: 'Newsletter primary · blog secondary · member CTAs', personalizationLevel: 'custom' },
      { id: 'aud-3', label: 'Professionals', description: 'LinkedIn · authority tone · carousel format', distributionStrategy: 'LinkedIn carousel · stat-forward · professional CTA', personalizationLevel: 'tailored' },
    ],
    creatorRecs: [
      { id: 'cc-1', assetId: 'ka-page-042', type: 'partnership', creatorName: 'Finance Educator · Tier A', fitScore: 92, reachEstimate: '48K · money-curious 25-45', rationale: 'Historical +34% reach on finance clips · brand fit aligned' },
      { id: 'cc-2', assetId: 'ka-page-042', type: 'affiliate', creatorName: 'Money Monday affiliate network', fitScore: 85, reachEstimate: '12K qualified clicks', rationale: 'Campaign objective includes affiliate revenue · FTC template ready' },
    ],
    simulations: [
      { id: 'sim-1', assetId: 'ka-page-042', strategyLabel: 'TikTok-first · 3 platforms', reach: '62K', engagement: '7.2%', watchTime: '38s avg', clickThrough: '3.8%', conversion: '2.4%', readerGrowth: '+820', revenue: '$840 affiliate', resourceUtilization: 'Moderate · 3 formats', platformSaturation: 'Low · money niche', confidencePct: 86 },
      { id: 'sim-2', assetId: 'ka-page-042', strategyLabel: 'Newsletter-first · owned audience', reach: '18K', engagement: '12.1%', watchTime: '4:20 read', clickThrough: '8.2%', conversion: '4.1%', readerGrowth: '+340', revenue: 'Retention lift', resourceUtilization: 'Low · 1 format', platformSaturation: 'N/A', confidencePct: 78 },
      { id: 'sim-3', assetId: 'ka-page-028', strategyLabel: 'Instagram-first vs TikTok-first', reach: '44K vs 58K', engagement: '5.8% vs 7.4%', watchTime: '32s vs 41s', clickThrough: '2.9% vs 3.6%', conversion: '1.8% vs 2.2%', readerGrowth: '+520 vs +680', revenue: '—', resourceUtilization: 'Same · 2 formats', platformSaturation: 'Medium', confidencePct: 72 },
    ],
    performance: {
      'ka-truth-sleep': {
        assetId: 'ka-truth-sleep',
        reach: '34.2K',
        views: '28.8K',
        watchTime: '48s avg',
        retention: '91%',
        completion: '87%',
        shares: '1,240',
        bookmarks: '890',
        comments: '342',
        clicks: '2,180',
        conversions: '—',
        revenue: '—',
        readerGrowth: '+420',
        brandGrowth: 'Trust signal up',
        knowledgeContribution: 'Research gate pattern archived · evergreen template',
        topPatterns: ['Question hook · Tue publish · YouTube Shorts first'],
      },
      'ka-page-042': {
        assetId: 'ka-page-042',
        reach: 'Pre-launch',
        views: '—',
        watchTime: '—',
        retention: '—',
        completion: '—',
        shares: '—',
        bookmarks: '—',
        comments: '—',
        clicks: '—',
        conversions: '—',
        revenue: '—',
        readerGrowth: 'Projected +820',
        brandGrowth: 'Authority signal building',
        knowledgeContribution: 'Stat overlay pattern · Labs #38',
        topPatterns: ['Stat overlay thumbnails · Money Monday cadence'],
      },
    },
    feedback: [
      {
        id: 'fb-1',
        assetId: 'ka-truth-sleep',
        worked: ['Question hook outperformed statement', 'Tuesday 9am ET optimal', 'YouTube Shorts 91% retention'],
        failed: ['LinkedIn carousel underperformed · too casual tone'],
        unexpected: ['Pinterest pin drove unexpected bookmark saves'],
        platformDifferences: ['TikTok favors faster pace · YouTube favors stat citations'],
        audienceBehavior: ['Returning readers clicked through to full page 3x more'],
        improvements: ['Add LinkedIn professional tone variant', 'Schedule republish Q2'],
        updatesFutureRecs: true,
      },
    ],
    lineage: [
      { id: 'ln-1', assetId: 'ka-page-042', type: 'source', label: 'PAGE 042 · Newsroom source', at: daysAgo(14) },
      { id: 'ln-2', assetId: 'ka-page-042', type: 'derived', label: 'Instagram Reel adaptation', formatId: 'instagram-reel', channelId: 'instagram', at: daysAgo(3) },
      { id: 'ln-3', assetId: 'ka-page-042', type: 'derived', label: 'TikTok adaptation', formatId: 'tiktok', channelId: 'tiktok', at: daysAgo(3) },
      { id: 'ln-4', assetId: 'ka-truth-sleep', type: 'source', label: 'PAGE 041 · Research-gated source', at: daysAgo(90) },
      { id: 'ln-5', assetId: 'ka-truth-sleep', type: 'published', label: 'YouTube Shorts · first publish', formatId: 'youtube-shorts', channelId: 'youtube', at: daysAgo(60), performanceNote: '91% retention · 34K reach' },
      { id: 'ln-6', assetId: 'ka-truth-sleep', type: 'evergreen-update', label: 'Stat citation refresh · Q2', at: daysFromNow(14) },
    ],
    crossCompany: [
      { id: 'xc-1', assetId: 'ka-truth-sleep', topic: 'Research-gated health content pattern', sourceCompany: 'NDXBOOK', targetCompanies: ['Studio OS Labs', 'AI Media pilot'], safe: true, identityProtection: 'Strip ndxbook branding · preserve methodology', recommendation: 'Share research gate workflow · not page content' },
      { id: 'xc-2', assetId: 'ka-page-042', topic: 'Money education · entrepreneurship', sourceCompany: 'NDXBOOK', targetCompanies: ['Frontal Slayer lounge content'], safe: false, identityProtection: 'Different audience · different tone · do not cross-publish', recommendation: 'Extract leadership principles only · not money page copy' },
    ],
    health: {
      executionVelocity: 82,
      channelEfficiency: 78,
      formatCoverage: 74,
      evergreenUtilization: 68,
      knowledgeLongevity: 86,
      overallPct: 79,
      bottlenecks: ['OAuth pending for Page 028 social publish', 'Newsletter sequence not yet wired'],
      recommendations: ['Prioritize TikTok + Reels for Money Monday launch', 'Queue evergreen republish for Truth Tuesday sleep content', 'Bundle 4 Money Monday pages into ebook chapter'],
    },
    selectedAssetId: 'ka-page-042',
  };
}

export function bootstrapDistributionEnginePlatform(): void {
  bootstrapDistributionEngineStore(buildDistributionEngineSeed());
}
