import type { MemoryEventRegistration, ProfessionalMemoryClass, ProfessionalMemoryRecord } from '../types';
import { normalizeProfessionalMemory } from './schemas';

export const PROFESSIONAL_MEMORY_CLASSES: Array<{
  id: ProfessionalMemoryClass;
  label: string;
  description: string;
}> = [
  {
    id: 'career-memory',
    label: 'Career Memories™',
    description: 'Promotions, firsts, credentials, transitions, and identity-defining milestones.',
  },
  {
    id: 'client-memory',
    label: 'Client Memories™',
    description: 'Meaningful service moments, trust earned, corrections, reviews, and outcomes.',
  },
  {
    id: 'simulation-memory',
    label: 'Simulation Memories™',
    description: 'Practice outcomes that changed judgment before real-world consequences arrived.',
  },
  {
    id: 'teaching-memory',
    label: 'Teaching Memories™',
    description: 'Mentorship, apprentices, feedback given, and mastery passed forward.',
  },
  {
    id: 'innovation-memory',
    label: 'Innovation Memories™',
    description: 'New methods, systems, formulas, tools, or workflows created by the professional.',
  },
  {
    id: 'business-memory',
    label: 'Business Memories™',
    description: 'Businesses opened, teams hired, offers launched, risks taken, and growth moments.',
  },
  {
    id: 'leadership-memory',
    label: 'Leadership Memories™',
    description: 'Decisions under pressure, team trust, conflict resolution, and responsibility.',
  },
  {
    id: 'community-memory',
    label: 'Community Memories™',
    description: 'Contributions to peers, clients, local community, and professional culture.',
  },
  {
    id: 'historical-memory',
    label: 'Historical Memories™',
    description: 'Industry events, awards, competitions, and moments that place a career in history.',
  },
];

/** Profession-agnostic launch seeds — one example per supported world family. */
export const LAUNCH_PROFESSIONAL_MEMORIES: ProfessionalMemoryRecord[] = [
  {
    id: 'wisdom-beauty-first-client-win',
    learnerId: 'studio-local-learner',
    worldId: 'hair-world',
    profession: 'beauty-professional',
    category: 'client-memory',
    title: 'First successful client outcome',
    occurredAt: '2023-07-08T10:00:00.000Z',
    sceneId: 'client-consult-room',
    simulationId: 'sim-client-consult',
    careerLevel: 'apprentice',
    importance: 82,
    participants: ['client-a', 'mentor-lead'],
    relatedSkillIds: ['client-consultation', 'service-delivery'],
    relatedBrainConceptIds: ['memory-client-consultations'],
    relatedCertificationIds: [],
    reflectionSummary: 'Client confidence rises when technical precision and calm communication happen together.',
    signals: ['achievement', 'career-milestone'],
    summary: 'Completed the first client service that earned trust and proved technique under pressure.',
    wisdomExtracted: 'Client confidence rises when technical precision and calm communication happen together.',
    emotionalTone: 'proud',
    relatedCareerGoalIds: ['premium-client-experience'],
    relatedBusinessIds: [],
    relatedMentorshipIds: [],
    impactScore: 82,
    masteryDelta: 14,
    visibleToOrb: true,
  },
  {
    id: 'wisdom-architecture-first-blueprint',
    learnerId: 'studio-local-learner',
    worldId: 'architecture-world',
    profession: 'licensed-architect',
    category: 'career-memory',
    title: 'First blueprint approved',
    occurredAt: '2024-03-14T09:00:00.000Z',
    sceneId: 'plan-review-board',
    careerLevel: 'associate',
    importance: 88,
    participants: ['review-board', 'project-lead'],
    relatedSkillIds: ['code-compliance', 'technical-drawing'],
    relatedBrainConceptIds: ['building-code-review'],
    relatedCertificationIds: ['architect-license-prep'],
    reflectionSummary: 'Approval comes from evidence, not confidence — document assumptions before presenting.',
    signals: ['achievement', 'certification'],
    summary: 'First project blueprint passed municipal review without major revision.',
    wisdomExtracted: 'Approval comes from evidence, not confidence — document assumptions before presenting.',
    emotionalTone: 'recognized',
    relatedCareerGoalIds: ['licensed-architect'],
    relatedBusinessIds: [],
    relatedMentorshipIds: [],
    impactScore: 88,
    masteryDelta: 16,
    visibleToOrb: true,
  },
  {
    id: 'wisdom-finance-first-close',
    learnerId: 'studio-local-learner',
    worldId: 'finance-world',
    profession: 'financial-analyst',
    category: 'business-memory',
    title: 'First quarterly close completed',
    occurredAt: '2024-06-30T17:00:00.000Z',
    sceneId: 'month-end-close',
    simulationId: 'sim-month-end-close',
    careerLevel: 'analyst',
    importance: 79,
    participants: ['controller', 'bookkeeping-team'],
    relatedSkillIds: ['reconciliation', 'reporting'],
    relatedBrainConceptIds: ['memory-accounting'],
    relatedCertificationIds: ['cpa-track'],
    reflectionSummary: 'Close quality depends on daily discipline, not heroic end-of-quarter effort.',
    signals: ['achievement', 'business'],
    summary: 'Led first quarterly close with reconciled books and on-time reporting.',
    wisdomExtracted: 'Close quality depends on daily discipline, not heroic end-of-quarter effort.',
    emotionalTone: 'responsible',
    relatedCareerGoalIds: ['profitable-studio-owner'],
    relatedBusinessIds: ['regional-advisory-firm'],
    relatedMentorshipIds: [],
    impactScore: 79,
    masteryDelta: 12,
    visibleToOrb: true,
  },
  {
    id: 'wisdom-healthcare-first-consult',
    learnerId: 'studio-local-learner',
    worldId: 'healthcare-world',
    profession: 'clinical-professional',
    category: 'client-memory',
    title: 'First patient consult completed independently',
    occurredAt: '2024-09-12T11:00:00.000Z',
    sceneId: 'patient-consult-suite',
    simulationId: 'sim-sensitive-patient-consult',
    careerLevel: 'resident',
    importance: 90,
    participants: ['patient', 'attending-physician'],
    relatedSkillIds: ['patient-consultation', 'informed-consent'],
    relatedBrainConceptIds: ['clinical-judgment'],
    relatedCertificationIds: ['board-eligibility-track'],
    reflectionSummary: 'Trust is built when the professional explains options before recommending action.',
    signals: ['achievement', 'career-milestone'],
    summary: 'Completed first independent consult with documented consent and follow-up plan.',
    wisdomExtracted: 'Trust is built when the professional explains options before recommending action.',
    emotionalTone: 'trusted',
    relatedCareerGoalIds: ['patient-advocacy'],
    relatedBusinessIds: [],
    relatedMentorshipIds: ['attending-mentorship'],
    impactScore: 90,
    masteryDelta: 18,
    visibleToOrb: true,
  },
  {
    id: 'wisdom-construction-safety-audit',
    learnerId: 'studio-local-learner',
    worldId: 'construction-world',
    profession: 'site-supervisor',
    category: 'leadership-memory',
    title: 'First site safety audit passed',
    occurredAt: '2025-01-20T08:00:00.000Z',
    sceneId: 'active-job-site',
    simulationId: 'sim-site-safety-audit',
    careerLevel: 'foreman',
    importance: 93,
    participants: ['safety-inspector', 'crew-leads'],
    relatedSkillIds: ['safety-compliance', 'crew-coordination'],
    relatedBrainConceptIds: ['permit-compliance'],
    relatedCertificationIds: ['osha-supervisor'],
    reflectionSummary: 'Safety culture is visible behavior, not paperwork — crews mirror what leaders tolerate.',
    signals: ['achievement', 'certification'],
    summary: 'Passed first formal safety audit with zero critical findings.',
    wisdomExtracted: 'Safety culture is visible behavior, not paperwork — crews mirror what leaders tolerate.',
    emotionalTone: 'responsible',
    relatedCareerGoalIds: ['general-contractor'],
    relatedBusinessIds: [],
    relatedMentorshipIds: [],
    impactScore: 93,
    masteryDelta: 20,
    visibleToOrb: true,
  },
  {
    id: 'wisdom-marketing-campaign-launch',
    learnerId: 'studio-local-learner',
    worldId: 'marketing-world',
    profession: 'brand-strategist',
    category: 'innovation-memory',
    title: 'First campaign launch with measurable proof',
    occurredAt: '2025-05-18T14:00:00.000Z',
    sceneId: 'campaign-war-room',
    simulationId: 'sim-launch-campaign',
    careerLevel: 'strategist',
    importance: 85,
    participants: ['creative-team', 'client-stakeholder'],
    relatedSkillIds: ['campaign-strategy', 'proof-content'],
    relatedBrainConceptIds: ['memory-marketing-strategy'],
    relatedCertificationIds: [],
    reflectionSummary: 'Proof beats promise — campaigns perform when transformation evidence appears quickly.',
    signals: ['achievement', 'project'],
    summary: 'Launched first campaign using short-form proof content with strong early conversion.',
    wisdomExtracted: 'Proof beats promise — campaigns perform when transformation evidence appears quickly.',
    emotionalTone: 'curious',
    relatedCareerGoalIds: ['beauty-brand-builder'],
    relatedBusinessIds: ['agency-client-alpha'],
    relatedMentorshipIds: [],
    impactScore: 85,
    masteryDelta: 15,
    visibleToOrb: true,
  },
  {
    id: 'wisdom-mentorship-apprentice-promotion',
    learnerId: 'studio-local-learner',
    worldId: 'hair-world',
    profession: 'team-lead',
    category: 'teaching-memory',
    title: 'Apprentice earned master-level promotion',
    occurredAt: '2026-06-12T12:00:00.000Z',
    sceneId: 'certification-ceremony',
    careerLevel: 'master-mentor',
    importance: 96,
    participants: ['apprentice', 'studio-owner'],
    relatedSkillIds: ['mentorship', 'leadership'],
    relatedBrainConceptIds: ['memory-leadership'],
    relatedCertificationIds: ['master-stylist'],
    reflectionSummary: 'Mentorship becomes legacy when the apprentice can decide confidently without imitation.',
    signals: ['mentorship', 'promotion', 'certification'],
    summary: 'An apprentice trained under the learner advanced into master-level status.',
    wisdomExtracted: 'Mentorship becomes legacy when the apprentice can decide confidently without imitation.',
    emotionalTone: 'legacy-building',
    relatedCareerGoalIds: ['team-lead'],
    relatedBusinessIds: ['studio-training-program'],
    relatedMentorshipIds: ['mentor-apprentice-master'],
    impactScore: 96,
    masteryDelta: 22,
    visibleToOrb: true,
  },
].map((memory) => normalizeProfessionalMemory(memory as ProfessionalMemoryRecord));

/** Career Worlds register event types here — no world-specific logic in the engine. */
export const MEMORY_EVENT_REGISTRY: MemoryEventRegistration[] = [
  {
    worldId: '*',
    profession: '*',
    eventType: 'client-outcome',
    description: 'Meaningful client service result — success, correction, or trust milestone.',
  },
  {
    worldId: '*',
    profession: '*',
    eventType: 'simulation-complete',
    description: 'Simulation debrief insight worth preserving as professional memory.',
  },
  {
    worldId: '*',
    profession: '*',
    eventType: 'promotion-earned',
    description: 'Career level advancement inside a Career World.',
  },
  {
    worldId: '*',
    profession: '*',
    eventType: 'business-opened',
    description: 'New business, studio, firm, or practice launched.',
  },
  {
    worldId: '*',
    profession: '*',
    eventType: 'certification-earned',
    description: 'Credential or certification ceremony completed.',
  },
  {
    worldId: '*',
    profession: '*',
    eventType: 'mentorship-milestone',
    description: 'Apprentice progress, teaching moment, or mentorship legacy event.',
  },
  {
    worldId: '*',
    profession: '*',
    eventType: 'award-received',
    description: 'Competition, industry award, or community recognition.',
  },
  {
    worldId: '*',
    profession: '*',
    eventType: 'industry-contribution',
    description: 'Contribution that changed peers, clients, community, or craft.',
  },
];

export function listProfessionalMemoryClasses() {
  return PROFESSIONAL_MEMORY_CLASSES;
}

export function listLaunchProfessionalMemories(): ProfessionalMemoryRecord[] {
  return LAUNCH_PROFESSIONAL_MEMORIES;
}

export function listMemoryEventRegistrations(): MemoryEventRegistration[] {
  return MEMORY_EVENT_REGISTRY;
}

export function findMemoryEventRegistration(eventType: string): MemoryEventRegistration | undefined {
  return MEMORY_EVENT_REGISTRY.find((entry) => entry.eventType === eventType);
}
