/** Business Model Engine v1.0 — constants. */

import type { MembershipTier } from './types';

export const BME_STORAGE_KEY = 'studioOsBusinessModelEngine_v1';
export const BME_VERSION = '1.0.0';

export const MEMBERSHIP_TIERS: MembershipTier[] = [
  'free',
  'creator',
  'professional',
  'business',
  'agency',
  'enterprise',
  'enterprise-plus',
];

export const MEMBERSHIP_TIER_LABELS: Record<MembershipTier, string> = {
  free: 'FREE',
  creator: 'CREATOR',
  professional: 'PROFESSIONAL',
  business: 'BUSINESS',
  agency: 'AGENCY',
  enterprise: 'ENTERPRISE',
  'enterprise-plus': 'ENTERPRISE PLUS',
};

export const TIER_CAPABILITIES: Record<MembershipTier, import('./types').MembershipCapabilities> = {
  free: {
    workspaceLimit: 1,
    aiGenerationsPerMonth: 50,
    automationLimit: 5,
    storageGb: 1,
    marketplaceParticipation: false,
    analyticsDepth: 'basic',
    executiveAiTeamSize: 0,
    approvalWorkflows: false,
    teamSeats: 1,
    apiAccess: false,
    customBranding: false,
    prioritySupport: false,
    enterprisePermissions: false,
  },
  creator: {
    workspaceLimit: 2,
    aiGenerationsPerMonth: 500,
    automationLimit: 25,
    storageGb: 10,
    marketplaceParticipation: true,
    analyticsDepth: 'standard',
    executiveAiTeamSize: 1,
    approvalWorkflows: false,
    teamSeats: 2,
    apiAccess: false,
    customBranding: false,
    prioritySupport: false,
    enterprisePermissions: false,
  },
  professional: {
    workspaceLimit: 5,
    aiGenerationsPerMonth: 2000,
    automationLimit: 100,
    storageGb: 50,
    marketplaceParticipation: true,
    analyticsDepth: 'advanced',
    executiveAiTeamSize: 3,
    approvalWorkflows: true,
    teamSeats: 5,
    apiAccess: true,
    customBranding: false,
    prioritySupport: true,
    enterprisePermissions: false,
  },
  business: {
    workspaceLimit: 10,
    aiGenerationsPerMonth: 5000,
    automationLimit: 250,
    storageGb: 200,
    marketplaceParticipation: true,
    analyticsDepth: 'advanced',
    executiveAiTeamSize: 5,
    approvalWorkflows: true,
    teamSeats: 15,
    apiAccess: true,
    customBranding: true,
    prioritySupport: true,
    enterprisePermissions: false,
  },
  agency: {
    workspaceLimit: 25,
    aiGenerationsPerMonth: 15000,
    automationLimit: 500,
    storageGb: 500,
    marketplaceParticipation: true,
    analyticsDepth: 'enterprise',
    executiveAiTeamSize: 10,
    approvalWorkflows: true,
    teamSeats: 50,
    apiAccess: true,
    customBranding: true,
    prioritySupport: true,
    enterprisePermissions: false,
  },
  enterprise: {
    workspaceLimit: 100,
    aiGenerationsPerMonth: 50000,
    automationLimit: 2000,
    storageGb: 2000,
    marketplaceParticipation: true,
    analyticsDepth: 'enterprise',
    executiveAiTeamSize: 25,
    approvalWorkflows: true,
    teamSeats: 200,
    apiAccess: true,
    customBranding: true,
    prioritySupport: true,
    enterprisePermissions: true,
  },
  'enterprise-plus': {
    workspaceLimit: 999,
    aiGenerationsPerMonth: 999999,
    automationLimit: 9999,
    storageGb: 10000,
    marketplaceParticipation: true,
    analyticsDepth: 'enterprise',
    executiveAiTeamSize: 99,
    approvalWorkflows: true,
    teamSeats: 999,
    apiAccess: true,
    customBranding: true,
    prioritySupport: true,
    enterprisePermissions: true,
  },
};
